### ISSUE TITLE
documentation "senderId" correction

### ISSUE THREAD

**Issue by carefreews** [phonegap/phonegap-plugin-push#10]
Hi,
currently, there is an error in the documentation:

var push = PushNotification.init({ "android": {"senderId": "12345679"},
	    	 "ios": {}, "wp": {"channelName": "12345679"} } );

which cause "No value for senderID" error.

Correction: senderId => senderID

**Comment by macdonst** [comment]
@carefreews Thanks for the heads up. I've made the necessary change.
