### ISSUE TITLE
Allowing app user to select his/her own notification sound

### ISSUE THREAD

**Issue by skyprimer** [phonegap/phonegap-plugin-push#1000]
**Platform:** Phonegap Build - IOS & Android

I've been working over 2 months for my app with phonegap. I've managed to play custom beep sound on both foreground / background.

But my question is if it is possible to offer user 5 sound notifications and let the user chose one of them for background sound?

I know that the beep.wav goes to www folder (which is not writable) with phonegap build so downloading new beep.wav over old one with user's choice is not possible..

I want to know if it is **possible** to change background notificaton sound from app by user choice? Please point me to the right direction...

**Comment by macdonst** [comment]
@skyprimer yes, it is possible but you need to have the user select what sound they want and send that choice to your server. You'll need to be able to identify your user uniquely and store their sound preference. Then when you send a push to them you will specify which of your 5 sounds to play.

**Comment by skyprimer** [comment]
Ohh so sorry macdonst i've forgot to tell i am talking about "topic users".

**Comment by macdonst** [comment]
@skyprimer ah, then the answer is nope. It is actually the OS that plays the sound when a push notification arrives by reading what is in the push payload or playing the default system sound. So, if you are sending to topic users they are all going to get the same sound.
