### ISSUE TITLE
Integrate to existing PhoneGap Application

### ISSUE THREAD

**Issue by lddd** [phonegap/phonegap-plugin-push#1001]
Hello there,

i am new to PhoneGap at all. I do have the Application Template of "Ionic Material Design" and would like to add Push Notification to it for WordPress using the Plugin of delitestudio.com (WordPress Push Notifications Plugin (lite).

Now i added the Plugin like described in the docs.

Now i stuck after
**cordova plugin add phonegap-plugin-push --variable SENDER_ID="XXXXXXX"**

Could anyone explain the next steps to me? thanks in advance.

**Comment by macdonst** [comment]
@lddd try following my workshop to get an idea of how it all works:

http://macdonst.github.io/push-workshop/

**Comment by lddd** [comment]
thanks, helped a lot.
