### ISSUE TITLE
Enhancement: Add preference to copy notification icon to /res folders like splashscreen plugin does

### ISSUE THREAD

**Issue by pke** [phonegap/phonegap-plugin-push#1003]
The Splashscreen plugin uses the following entries in `config.xml`

```
<splash density="land-ldpi" src="res/screens/android/screen-ldpi-landscape.png" />
<splash density="land-mdpi" src="res/screens/android/screen-mdpi-landscape.png" />
<splash density="land-hdpi" src="res/screens/android/screen-hdpi-landscape.png" />
<splash density="land-xhdpi" src="res/screens/android/screen-xhdpi-landscape.png" />
<splash density="port-ldpi" src="res/screens/android/screen-ldpi-portrait.png" />
<splash density="port-hdpi" src="res/screens/android/screen-hdpi-portrait.png" />
<splash density="port-mdpi" src="res/screens/android/screen-mdpi-portrait.png" />
<splash density="port-xhdpi" src="res/screens/android/screen-xhdpi-portrait.png" />
```

It would be nice to have something similar for the notification icon:

```
<notification-icon density="ldpi" src="res/icons/android/notification-icon-36-ldpi.png" />
<notification-icon density="mdpi" src="res/icons/android/notification-icon-48-mdpi.png" />
<notification-icon density="hdpi" src="res/icons/android/notification-icon-72-hdpi.png" />
<notification-icon density="xhdpi" src="res/icons/android/notification-icon-96-xhdpi.png" />
<notification-icon density="xxhdpi" src="res/icons/android/notification-icon-144-xxhdpi.png" />
<notification-icon density="xxxhdpi" src="res/icons/android/notification-icon-192-xxxhdpi.png" />
```

And it would end up as `ic_notification` in the respective `platform/android` folder

**Comment by macdonst** [comment]
@pke I don't think the appetite is there to add more tags to `configs.xml`. However, I'd like for you to go vote up: 

https://github.com/cordova/cordova-discuss/issues/6

It would allow for generic resources to be specified in `config.xml` whether they be icons for push or translated strings for instance.

**Comment by pke** [comment]
you are right. I voted over there. But the cordova folks do not seem to understand why one would need that. All they can think of is the `www` folder :)

**Comment by macdonst** [comment]
@pke actually the Cordova folks, of whom which I am one, do understand why we would need it but we are very busy. We welcome PR's from others.

**Comment by pke** [comment]
I'll see what I can do.
