### ISSUE TITLE
[Enhancement] Add preference for icon name and color

### ISSUE THREAD

**Issue by pke** [phonegap/phonegap-plugin-push#1004]
Instead of having to specify the icon name and colour in the `init` call it would be nice to be able to specify it in the `config.xml` preferences.

**Comment by grandhisubrahmanyam35** [comment]
@pke Is it possible to add icon color as preference in config.xml. if yes can you refer any documentation or else any other resource.

**Comment by pke** [comment]
I haven't found a way yet. I guess this could be solved with a PR but I haven't had the time to work on such. I am not actively using Cordova at the moment.
