### ISSUE TITLE
Problems with integrating it to existing app

### ISSUE THREAD

**Issue by lddd** [phonegap/phonegap-plugin-push#1005]
Hi there,

i am currently trying to integrate this plugin to my existing app but hitting the following problems. When i demo run my app (ionic serve -l)

```
ReferenceError: Can't find variable: cordova
global code — push.js:8

ReferenceError: Can't find variable: Ionic
initialPushNotifications — app.js:47
(anonyme Funktion) — app.js:253
(anonyme Funktion) — ionic.bundle.js:44991
onPlatformReady — ionic.bundle.js:2447
onWindowLoad — ionic.bundle.js:2428
replace
url — ionic.bundle.js:13880
setBrowserUrlWithFallback — ionic.bundle.js:20140
(anonyme Funktion) — ionic.bundle.js:20262
$eval — ionic.bundle.js:23228
$digest — ionic.bundle.js:23044
$apply — ionic.bundle.js:23333
bootstrapApply — ionic.bundle.js:10275
invoke — ionic.bundle.js:13012
doBootstrap — ionic.bundle.js:10273
bootstrap — ionic.bundle.js:10293
angularInit — ionic.bundle.js:10187
(anonyme Funktion) — ionic.bundle.js:34952
trigger — ionic.bundle.js:11571
eventHandler — ionic.bundle.js:11841
```

-----

**My steps so far:**
1) Installed the plugin
2) copied push.js to /www/js from the plugin root 
3) linked push.js inside my index.html (  <script src="js/push.js"></script> )

**Added to App.js**

angular.module('starter', ['ionic','ngIOS9UIWebViewPatch', 'starter.controllers', 'starter.services', 'ngMaterial', 'ngMessages', 'ngCordova'])
    .run(function ($ionicPlatform, $cordovaSQLite, $rootScope, $ionicHistory, $state, $mdDialog, $mdBottomSheet) {
		
		// Push Notifications
		function initialPushNotifications() {
		
		var push = new Ionic.Push({
		      "debug": true
		    });
 
		    push.register(function(token) {
		      console.log("My Device token:",token.token);
		      push.saveToken(token);  // persist the token in the Ionic Platform
		    });
			
			};

$ionicPlatform.ready(function () {
            ionic.Platform.isFullScreen = true;
            if (window.cordova && window.cordova.plugins.Keyboard) {
                cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
                cordova.plugins.Keyboard.disableScroll(true);
            }
            if (window.StatusBar) {
                StatusBar.styleDefault();
            }
	    initialPushNotifications();
            initialSQLite();
            initialRootScope();
```

**Comment by macdonst** [comment]
@lddd are you trying to run your demo in web browser?

**Comment by lddd** [comment]
Over ionic serve -l, yes.

**Comment by macdonst** [comment]
@lddd yeah, I can't see you manually needing to copy push.js into your www folder in order for this to work. So, something is wacky with your setup. I'm sorry but I'm going to push you off to Ionic support for this one as running `ionic serve` and push in debug mode doesn't really touch this plugin so I wouldn't know where to start. cc: @ericb

**Comment by lddd** [comment]
I am going to test it on a real device hold on.

**Comment by jcesarmobile** [comment]
But if you are going to test on a real device, remove the manual steps you did (copying & linking js files) and install the plugin as explained on the install instructions

**Comment by lddd** [comment]
@jcesarmobile Yes i did so already

**Comment by lddd** [comment]
I get something like

2016-06-20 15:12:59.020 App Demo[303:140628] createNotificationChecker
2016-06-20 15:12:59.020 App Demo[303:140628] not coldstart
2016-06-20 15:12:59.022 App Demo[303:140628] active
2016-06-20 15:12:59.024 App Demo[303:140628] PushPlugin skip clear badge
2016-06-20 15:13:01.361 App Demo[303:140628] Resetting plugins 
2016-06-20 15:13:03.926 App Demo[303:140628] Finished load of: 

to my Xcode console after run but there is no popup dialog on the device asking me to allow Push...

**Comment by lddd** [comment]
I am now trying to rebuild it based on your iOS example. Some stupid question maybe but regarding GCM Sender ID for iOS. Do i need this? How to use it with my own server having a Plugin for WordPress handling the Server side part?

**Comment by lddd** [comment]
```
2016-06-20 18:18:46.933 Dead Stock[363:260565] GCM Sender ID (null)
2016-06-20 18:18:46.933 Dead Stock[363:260565] Using APNS Notification
2016-06-20 18:18:48.412 Dead Stock[363:260369] Push Plugin register success: <0bad3d9b beeebd26 6d207450 3e1714fc bbb71d11 71294562 36adc080 68808358>
2016-06-20 18:21:38.092 Dead Stock[363:260369] active
2016-06-20 18:21:38.093 Dead Stock[363:260369] PushPlugin skip clear badge
```

Hooray. Now can anyone explain the "PushPlugin skip clear badge" to me? Why its doing that?

When i send a Push to my device token i get (app is in background mode)

```
016-06-20 18:24:05.597 Dead Stock[363:260369] Notification received
2016-06-20 18:24:05.598 Dead Stock[363:260369] Push Plugin key: alert
2016-06-20 18:24:05.598 Dead Stock[363:260369] Push Plugin key: badge
2016-06-20 18:24:05.598 Dead Stock[363:260369] Push Plugin key: sound
2016-06-20 18:25:08.396 Dead Stock[363:260369] active
2016-06-20 18:25:08.397 Dead Stock[363:260369] PushPlugin skip clear badge
```
I see the notification but the badge won´t clear after opening the app and closing it again.

**Comment by jcesarmobile** [comment]
That is a console message telling you that it's skipping the clear the badge (because you didn't configure it to clear the badge)

**Comment by lddd** [comment]
Thanks. Appreciate all your kind help so far.
