### ISSUE TITLE
iOS GCM file size

### ISSUE THREAD

**Issue by Manduro** [phonegap/phonegap-plugin-push#1009]
The plugin for iOS has a huge 25MB GCM folder. This means that this plugin adds 25 megs to my iOS app, even when I'm not using GCM on iOS.

Is there any way to make the GCM installation optional for iOS? Maybe by adding an optional `--variable IOS_GCM=false`, or some other better way.

Right now I have manually removed all of these files and references to them.

**Comment by ihuseynoff** [comment]
@Manduro could you please share how you remove gcm stuffs?

**Comment by Manduro** [comment]
@ihuseynoff I just removed the GCM folder in the iOS plugin folder and removed all references to it in the code until Xcode stopped throwing build errors ;).

**Comment by macdonst** [comment]
@Manduro Yeah, it is unfortunate. Recently a commit landed into Apache Cordova to support CocoaPod dependencies. Once that makes it into a Cordova CLI release I'll be able to move the GCM files out of the repo. Still will need to figure out a way not to download them if not required.

**Comment by macdonst** [comment]
GCM libs removed from plugin.
