### ISSUE TITLE
Calling init always creates a new registrationId?

### ISSUE THREAD

**Issue by pke** [phonegap/phonegap-plugin-push#1010]
### Expected Behaviour

calling `init` to return the same `registrationId` for the same app on the same device.

### Actual Behaviour

The `registrationId` is always different on Android 5.1. It then needs to be re-synced with the back-end server.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 5.1

#### Plugin version

   phonegap-plugin-push 1.6.0 "PushPlugin"

**Comment by macdonst** [comment]
@pke it usually doesn't do that, in fact it is not doing that on my phones right now. Are you uninstalling the application each time?

Regardless, you really should check for a change in the registration ID each time you start your app and sync back to the server if it changes. So, things appear to be working as expected.

**Comment by pke** [comment]
Shouldn't it be the same even across re-installs?
