### ISSUE TITLE
"Can't find variable: Module"

### ISSUE THREAD

**Issue by filipeprado1** [phonegap/phonegap-plugin-push#1013]
### Actual Behaviour

I implemented Push Plugin in Android and it is working well.
But now I'm trying to implement the plugin in iOS and when I execute my app occours the folow error:

_ReferenceError: Can't find variable: Module - push.js:246_

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 9.3.2

#### Cordova CLI version and cordova platform version
    cordova --version                                    # 6.2.0
    cordova platform version ios                     # 3.9.1

#### Plugin version
    cordova plugin version # 1.7.1

**Comment by macdonst** [comment]
@filipeprado1 version 1.7.1 of the plugin requires cordova-ios 4.1.x or better. It shouldn't even install with an earlier version of cordova ios. Please upgrade to the latest cordova-ios package.

**Comment by filipeprado1** [comment]
@macdonst now I updated my cordova ios to 4.1.1 but the problem is still occurring.

```
$ sudo cordova platform version ios
Installed platforms:
  ios 4.1.1
```

did I forget something else?

**Comment by macdonst** [comment]
@filipeprado1 I'm not sure. How did you add the plugin to the app? You should never get an error from that line of push.js as it is using standard cordova API's. Did you by chance copy push.js into the app manually?

**Comment by filipeprado1** [comment]
@macdonst I have added the plugin using `cordova plugin add` command. After I copied de push.js file to my www/js folder.

**Comment by filipeprado1** [comment]
@macdonst  have another way to implement that code without use de module.exports??

**Comment by macdonst** [comment]
@filipeprado1 you should never need to copy push.js to your www/js folder. The `cordova plugin add ` command should put the JS in the correct folder for you and add it to cordova_plugins.js which will load it at runtime. 

Remove that push.js from www/js and any reference to it. Then rm/add the plugin again.

**Comment by filipeprado1** [comment]
@macdonst u are totally right. The error doesnt occours more. 
Sorry to take your time.
