### ISSUE TITLE
Not getting device.uuid or device.platform after upgrading cordova platform update ios@4.1.0

### ISSUE THREAD

**Issue by ajaysaini95700** [phonegap/phonegap-plugin-push#1014]
i upgrated cordova platform update ios@4.1.0 for installing phonegap-plugin-push plugin but after installing i am not getting device UUid and device Platform from device.uuid and device.platform for ios but i got these value for android platform and i have already installed cordova plugin add cordova-plugin-device. 
$ionicPlatform.ready(function() {
         console.log('deviceready');
  });
$ionicPlatform.ready fired only for android. not for ios

**Comment by macdonst** [comment]
@ajaysaini95700 this has nothing to do with this plugin. Please open an issue on the device plugin or with ionic or on the PhoneGap forums.
