### ISSUE TITLE
Tapping on one notification clears all others on Android

### ISSUE THREAD

**Issue by lakshaydulani** [phonegap/phonegap-plugin-push#1015]
### Expected Behaviour
When you multiple notifications from the app, tapping on one should open the app and remove that particular notification from the notification tray

### Actual Behaviour
Tapping on one notification opens the app and calls the event handler, but clears all the other notifications and doesnt call their handlers.

#### Steps to Reproduce 
Get multiple notifications with different notId
Tap on any one notification.
App will open up and other notifications will be cleared.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android L & M

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung, OnePlus One

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@lakshaydulani right because you probably did not set the `clearNotifications` property to `false`, the default is `true`. Look at the [init](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushnotificationinitoptions) docs.

**Comment by lakshaydulani** [comment]
@macdonst thanks a lot i will check it

**Comment by lakshaydulani** [comment]
yes @macdonst it worked..thanks a ton..was stupid for not reading the docs properly :(
