### ISSUE TITLE
Show notification in the notifiaction bar when app is foreground in iOS

### ISSUE THREAD

**Issue by malwatte** [phonegap/phonegap-plugin-push#1016]
Is there any way we can show the notification on the notification bar even if the app is running on foreground?
(Something similar to android forceShow)

**Comment by macdonst** [comment]
@malwatte no, it is not possible. Even if you use the local notification plugin it won't show in the notification shade when the app is in the foreground.

**Comment by malwatte** [comment]
Thank you for your quick response
