### ISSUE TITLE
The data.launchArgs for Windows notification is always undefined

### ISSUE THREAD

**Issue by JD76** [phonegap/phonegap-plugin-push#1018]
### Expected Behaviour
Find the data I passed through launch parameters in the xml

### Actual Behaviour
launchArgs is always undefined

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Windows 10.0.10586.107

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Nokia Lumia 930

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.2.0
    cordova platform version android            4.3.2

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push  1.6.0

#### Sample Push Data Payload
```
<toast launch="{&quot;myContext&quot;:&quot;12345&quot;}">
    <visual>
        <binding template="ToastImageAndText01">
            <image id="1" src="ms-appx:///images/redWide.png" alt="red graphic"/>
            <text id="1">Hello World!</text>
        </binding>
    </visual>
</toast>

```

#### Sample Code that illustrates the problem
`
push.on('notification', function (dati) {
     console.log(dati.launchArgs);   // alway undefined
});
`

**Comment by rakatyal** [comment]
Is this happening when the application is launched through the push notification when the app is in background? For normal scenarios(when the app is in foreground or not launched), this is expected.

**Comment by JD76** [comment]
Hi, this happens when the application is in background. I can see in the debug of Visual Studio that the push.on("notification") event is fired up, but launcArgs is undefined.Thanks 

    Il Giovedì 23 Giugno 2016 19:58, Raghav Katyal <notifications@github.com> ha scritto:
 

 Is this happening when the application is launched through the push notification when the app is in background? For normal scenarios(when the app is in foreground or not launched), this is expected.—

**Comment by rakatyal** [comment]
Ahh I see what's going on. You are using an older version of the plugin where this wasn't implemented. Please update to the latest one.

**Comment by JD76** [comment]
Thanks for finding the first problem! I was sure I had the last version... But now the application in Visual Studio throws an error in the plugin (where it evaluates the activactionContext ...). After the sentence:var context = cordova.require('cordova/platform').activationContext;
context is undefined.. I checked my cordova version, and I'm sure it's the last version.Thanks again


    Il Lunedì 27 Giugno 2016 19:41, Raghav Katyal <notifications@github.com> ha scritto:
 

 Ahh I see what's going on. You are using an older version of the plugin where this wasn't implemented. Please update to the latest one.—

**Comment by mdbw3** [comment]
I got the same issue. Dirty solution that's working for me:

launchArgs = data.additionalData.pushNotificationReceivedEventArgs.toastNotification.content.getElementsByTagName('toast')[0].getAttribute('launch');

**Comment by rakatyal** [comment]
I am unable to reproduce this issue. Did you try to run the app on VS emulator?

**Comment by mdbw3** [comment]
I got this issue also when running it on a lumia 640.

**Comment by JD76** [comment]
I just updated to version 1.7.4 and now it works.

**Comment by andreszs** [comment]
On latest version (1.8.1) I also don't have any data.launchArgs content.

XML toast contains this:

```
<?xml version="1.0" encoding="utf-8"?>
<toast launch="{&quot;myContext&quot;:&quot;12345&quot;}"><visual>
<binding template="ToastText02">
    <text id="1">Title</text>
    <text id="2">Message</text>
</binding>
</visual></toast>
```

data.additionalData contains only this:

```
coldstart: false
pushNotificationReceivedEventArgs: [object Windows.Networking.PushNotifications.PushNotificationReceivedEventArgs]
```

while **data.launchArgs remains undefined**. This happens regardless of the app being in background or foreground. Any ideas why?

Also, is it true that I won't be able to get my custom arguments with the app in the foreground? I could get them from the old WP8 platform, I don't get why new plugin+platform versions are more crippled than the older ones.
