### ISSUE TITLE
iOS and Android configuration

### ISSUE THREAD

**Issue by purinagripal** [phonegap/phonegap-plugin-push#1019]
Can the plugin detect if the device is Android or iOS by itself???
I mean...Is it enought to write the function init like this??

```

var push = PushNotification.init({
    android: {
        senderID: "12345679"
    },
    ios: {
        alert: "true",
        badge: true,
        sound: 'false'
    },
    windows: {}
});
```

**Comment by macdonst** [comment]
@purinagripal yes, the plugin is smart enough to know if it is running on Android, iOS or Windows. I purposely made it so that you could put all the necessary init options for all platforms into the call so the developer didn't need to have different JS files for Android, iOS and Windows.
