### ISSUE TITLE
Example Template not building

### ISSUE THREAD

**Issue by edubaka** [phonegap/phonegap-plugin-push#1022]
### Expected Behaviour

After setting up the sender_id on Config.xml it should work on build.phonegap.com and build a example ok app.

### Actual Behaviour

After setup the sender_id and send to build it returns the error "Error - One of your plugins requires a parameter: SENDER_ID" version on the template plugin 1.6.2
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android , Windows and IOS

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
All
#### Cordova CLI version and cordova platform version
Cordova CLI 
    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version
Phonegap-plugin-push 1.62 ( come with the template example)
    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@edubaka what does your config.xml look like? Also, what template are you using? URL please or reproduction scenario.

**Comment by macdonst** [comment]
Closing, inactivity
