### ISSUE TITLE
Windows Phone 10 Problem with push plugin 

### ISSUE THREAD

**Issue by jcus0006** [phonegap/phonegap-plugin-push#1023]
### Expected Behaviour

Should register with Azure and unauthenticated WNS and receive notifications, 
### Actual Behaviour

It is not getting past the init function. 
### Reproduce Scenario (including but not limited to)

Recently I continued working on Windows Phone. When trying to deploy I started getting asked for a Pin number. It seemed that this problem was solved when installing the latest Windows SDK (Version 10.0.10586.212) For some reason, however, code that used to work before with previous versions of Cordova and Push Plugin ceased to work. I am not getting any simple errors that specify what the problem is but I can provide some screenshots that explain what's happening (see below). Reverting to previous versions is not an option because of other features of the app that do not work properly with earlier versions.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Windows Phone 10
#### (Windows) What device vendor (e.g. Samsung, HTC, Sony...)

Nokia Lumia 930 
#### Cordova CLI version and cordova platform version

 Cordova CLI 6.2.0
#### Plugin version

```
Push Plugin 1.6.4
```
#### Sample Code that illustrates the problem

The exception seems to be fired from this line, which is found in 'eval code dynamic':

var o = {};o["Promise handler"] = function () { o["WinRT Promise.done()"();};
 o["WinRT Promise object for      Windows.Foundation.IAsyncOperation`1<Windows.Networking.PushNotifications.PushNotificationChannel>"] = function (){
 o["Promise handler"](); };
 o["WinRT Promise.done()"] = function () { rethrowPromiseError(); };
 o["WinRT Promise object for Windows.Foundation.IAsyncOperation`1<Windows.Networking.PushNotifications.PushNotificationChannel>"]

The whole problem seems to originate from the init code of the push plugin:

pushNotification = PushNotification.init({
        "android": { "senderID": GCM_SENDER_ID, "icon": "logo", "iconColor": "#dc6900" },
        "ios": { "alert": "true", "badge": "false", "sound": "false", "icon": "logo.png"}, "windows": {}
    });
#### Logs taken while reproducing problem

Exception, Output and CallStack:

http://imgur.com/a/R1QuT

**Comment by ajeckmans** [comment]
I'd like to add that I also have this with _Windows10 Mobile_
Windows SDK 10.0.10586.212. Microsoft Lumia 950XL 10.0.14383.0 (this is an insider build). Cordova 6.2.0

**Comment by daserge** [comment]
@jcus0006, could you test if it works with the dev version of cordova-windows?
`cordova platform add https://github.com/apache/cordova-windows`

**Comment by slorber** [comment]
Also got this error on init(cfg) on Windows 10 emulator.
This error makes the emulator app stop.

Surprisingly, in the beginning it seemed to work fine and the error happened a bit later. Maybe it's related tocalling init() at the very startup of my app? (on my app, init() is called depending on weither the user is logged in or not on app startup)

Also, I'm pretty sure to have seen in my app logs a deviceId at some point, which looked like an URI. Actually I think I was able to get the URI, and then the app crashed.



@daserge I'll try to bring more infos and try the latest windows platform soon.

**Comment by Avijeetmishra** [comment]
I am also getting the same error with a different cordova plugin for bluetooth: https://github.com/don/BluetoothSerial#isconnected . 
After I try to disconnect the device, everything works great and suddenly I receive exception in eval code 

(function() { return function(err) { var o = {};o["Promise handler"] = function () { o["WinRT Promise.done()"](); };o["WinRT Promise object for Windows.Storage.Streams.DataReaderLoadOperation"] = function () { o["Promise handler"](); };o["WinRT Promise.done()"] = function () { throw err; };return o["WinRT Promise object for Windows.Storage.Streams.DataReaderLoadOperation"]}})()

and error is thrown 

Unhandled exception at line 6, column 279 in eval code
0x80000013 - JavaScript runtime error: The object has been closed.

The object has been closed.
WinRT information: The object has been closed.

I don't understand that from where this code is popping up and disrupting the normal functionality as this exception forces app to crash in simulator.

I am using latest cordova-version 7.0.1
