### ISSUE TITLE
Any way to know when device notification ids are no longer valid?

### ISSUE THREAD

**Issue by richmartin** [phonegap/phonegap-plugin-push#1026]
As per the docs,

```
Note: you will want to call PushNotification.init() each time your app starts. The remote push service can periodically reset your registration ID so this ensures you have the correct value.
```

But this means that on our servers we have an ever-growing list of device notification ids for each user. We see this particularly on test accounts where the app has been through a lot of de-/re-install cycles, but over time it is going to be true for normal users as well. 

Is there any way to avoid this? For example, when a new id is returned in the init() callback, is there any way to know that this _replaces_ an existing value instead of being an additional value that should be tracked? Or, alternatively, when sending a GCM message to a destination, is there any way to tell if we are sending to a stale id?

**Comment by macdonst** [comment]
@richmartin well when you call init and the registration event returns you a new registration ID then you know the old one is invalid. At that point in time you should tell your server what the new registration ID is and also to delete the old one, that you've saved in localStorage or some other persistent storage.

Regardless, the functionality that you are requesting is better implemented on the server side. Both GCM and APNS give you ways if telling if the registration ID is invalid when you try to send a push. If you read up on [Interpreting Downstream Messages](https://developers.google.com/cloud-messaging/http-server-ref#interpret-downstream) for GCM or implementing a connection to the [APNS Feedback Service](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Appendixes/BinaryProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH106-SW4).
