### ISSUE TITLE
update badge number even if the app is totally closed

### ISSUE THREAD

**Issue by alaa-alshamy** [phonegap/phonegap-plugin-push#1027]
On ios this is so simple we can just calc the badge number on the server and add badge payload to the notification we send

but is there any thing like "badge" payload in android to update badge number from os?  because i need to update it even if the app is totally closed

any help please

**Comment by macdonst** [comment]
@alaa-alshamy if you send `msgcnt`, `badge` or `count` in the `data` object of your payload it should work in the background as long as your device is supported by shortcutbadger. Give it a try and let me know and I will officially document it.

**Comment by alaa-alshamy** [comment]
thanks man, it's work like a charm.

go ahead and document it :+1:

**Comment by ravisuryawanshi** [comment]
![android-badgecount on notifications](https://cloud.githubusercontent.com/assets/12716503/22742637/7058e4ac-ee3d-11e6-84a2-c77e91b16b3a.JPG)
Hi,

I am getting badge count on the notification bar. I am not sure why it is coming. Can anyone help me?

Thanks
 Ravi

**Comment by alaa-alshamy** [comment]
@ravisuryawanshi  i asked same question before in another issue, check it out 

https://github.com/phonegap/phonegap-plugin-push/issues/1096
