### ISSUE TITLE
confused about GCM in ios

### ISSUE THREAD

**Issue by gbaumgart** [phonegap/phonegap-plugin-push#1031]
Hi,
last time i used this plugin (1-2 years ago), there were not GCM code/files. Instead, I had only PushPlugin.h / PushPlugin.m. We have build a special push server in C++ for both: ios (APNS) & google (GCM). We basically tell our server to push messages for our apps with JSON-RPC.

However, I am very confused what to do now, does that mean our push server is obsolete? I also can't find any docs how to use this new version in regard with certificates.

Sorry, really don't know what to do now. I see now also "Firebase" on the horizon.

well, thanks in advance. I'd be delighted to know what to do. I guess the save path is to downgrade to the older Push plugin, right?

**Comment by gbaumgart** [comment]
apparently you're sending ios push messages over GCM, very confusing.

**Comment by Greenestgreen** [comment]
you can send notifications through APNS and GCM to iOS devices.

To use GCM
- Xcode needed
- You need to use register an App on Google Console Developer.
- Then upload the APNS certificates [Here](https://developers.google.com/mobile/add?platform=ios&cntapi=gcm&cnturl=https:%2F%2Fdevelopers.google.com%2Fcloud-messaging%2Fios%2Fclient&cntlbl=Continue%20Adding%20GCM%20Support&%3Fconfigured%3Dtrue) (The iOS bundle id you enter on that form must be the same on which the certificates are created )
-A payload well formatted.

**Comment by gbaumgart** [comment]
ok, thanks. so i can kill our homebrew APNs server feature and just send all over GCM. ok to me too.

**Comment by Greenestgreen** [comment]
yup, but is very frustrating, if you need help AMA, i've recently made it work

**Comment by gbaumgart** [comment]
ok, thank you,  

to me this makes all sense now: i do now APNS over GCM over GOOGLE, then wait for Firebase and the update again.
