### ISSUE TITLE
 MismatchSenderId error when trying to send notifications to IOS device

### ISSUE THREAD

**Issue by dtmdata** [phonegap/phonegap-plugin-push#1032]
### Expected Behavior

Send Notifications to IOS DEVICE is not working for me. I have created the APNS in development mode and using the P12 fill-in the GCM console.

I got the GoogleService-Info.plist  file and I added it to my XCODE project. It has the correct ID of my project created on the GCM.

### Actual Behavior

```
Violetas-MacBook-Pro:node viotorres$ node notifications.js
{ multicast_id: 8194407334300346000,
  success: 0,
  failure: 2,
  canonical_ids: 0,
  results: [ { error: 'MismatchSenderId' }, { error: 'MismatchSenderId' } ] }
```

### Reproduce Scenario (including but not limited to)

I am able to get the registration id:
```
2016-06-30 01:43:03.571 PulseBox[2060:1038087] GCM Sender ID 619792080xxx
2016-06-30 01:43:03.571 PulseBox[2060:1038087] Using GCM Notification
2016-06-30 01:43:03.571 PulseBox[2060:1038087] Using GCM Sandbox
2016-06-30 01:43:04.240 PulseBox[2060:1037964] Push Plugin register success: <9fb6ef0f 557831ad 5ebb4461 314da3c7 933f2df0 5df731dc 1210288a xxxxxxxx>
2016-06-30 01:43:04.620: GGLInstanceID | Invalid last checkin timestamp in future.
2016-06-30 01:43:04.655: GGLInstanceID | Unable to find token in cache Error Domain=com.google.iid Code=-25300 "(null)"
2016-06-30 01:43:06.119 PulseBox[2060:1037964] GCM Registration Token: k1uFXUttY_o:APA91bGfV_0JbflKHjB4wedHAv5uSWZdv5bkTS2-NH1yGTL6cgkYP1SVV8ngIrF0lXS18Iw858dvW2tmlSC_ZC60-M_VPOhytWORr-1_WYD_O-af89FCmLk5BQ1trofTWu4R_9Xzajxx
2016-06-30 01:43:07.777 PulseBox[2060:1037964] active
```

#### Steps to Reproduce 
run my app in development mode using XCODE (Apache Cordova)

I send this from my APP

```
var push = PushNotification.init({
            "android": {  },
            "ios": { "senderID": "619792080xxx","gcmSandbox": "true","alert": "true", "badge": "true", "sound": "true" },
            "windows": {}
        });
```

I get the correct registration ID

then I use my app server to send the notification (NODE JS)

```
Violetas-MacBook-Pro:node viotorres$ more notifications.js
"use stric";
var gcm = require('node-gcm');

// Set up the sender with you API key, prepare your recipients' registration tokens. 
var sender = new gcm.Sender('XXXXXXXX');

function sendPushToId(profile_id,type,message,payload,callback){
var genMessage = new gcm.Message();
genMessage.addNotification({
data: {category:type, user_id: profile_id, servicecall_id: payload["servicecall_id"]}
});

genMessage.addData({
message: message,
title: 'PulseBox'
});

var tokens=[];

tokens.push("APA91bGfV_0JbflKHjB4wedHAv5uSWZdv5bkTS2-NH1yGTL6cgkYP1SVV8ngIrF0lXS18Iw858dvW2tmlSC_ZC60-M_VPOhytWORr-1_WYD_O-af89FCmLk5BQ1trofTWu4R_9XzajXX");

sender.sendNoRetry(genMessage, tokens, function(err,result){
//console.log(response);
if(err) {
      console.error(err);
    } else {
      console.log(result);
    }
});

callback(null, null);


}

sendPushToId(1336,"ACCEPTED ","DD MESSAGE", {servicecall_id:12},function(e,c){});
```

ALL time I received:

```
{ error: 'MismatchSenderId' } 
```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Ios 9.3

#### Cordova CLI version and cordova platform version

Violetas-MacBook-Pro:node viotorres$ cordova --version
6.2.0

#### Plugin version

   phonegap-plugin-push 1.6.2 "PushPlugin"

#### Logs taken while reproducing problem

**Comment by macdonst** [comment]
@dtmdata I can see in your logs that you get the registration ID:

```
2016-06-30 01:43:06.119 PulseBox[2060:1037964] GCM Registration Token: k1uFXUttY_o:APA91bGfV_0JbflKHjB4wedHAv5uSWZdv5bkTS2-NH1yGTL6cgkYP1SVV8ngIrF0lXS18Iw858dvW2tmlSC_ZC60-M_VPOhytWORr-1_WYD_O-af89FCmLk5BQ1trofTWu4R_9Xzajxx
```

but when you go to send the push you use:

```
tokens.push("APA91bGfV_0JbflKHjB4wedHAv5uSWZdv5bkTS2-NH1yGTL6cgkYP1SVV8ngIrF0lXS18Iw858dvW2tmlSC_ZC60-M_VPOhytWORr-1_WYD_O-af89FCmLk5BQ1trofTWu4R_9XzajXX");
```

So you are missing the `k1uFXUttY_o:` prefix so the line should be:

```
tokens.push("k1uFXUttY_o:APA91bGfV_0JbflKHjB4wedHAv5uSWZdv5bkTS2-NH1yGTL6cgkYP1SVV8ngIrF0lXS18Iw858dvW2tmlSC_ZC60-M_VPOhytWORr-1_WYD_O-af89FCmLk5BQ1trofTWu4R_9XzajXX");
```

**Comment by dtmdata** [comment]
Simon
thank you so much for your reply.  I removed this part intentionally because If I add it then I get that the id is invalid.

k1uFXUttY_o:


For Android it allows me to send the prefix. Actually I receive the message for Android if I pass the id with or without the prefix, but IOS when the id belongs to an IOS device it does not like it.


I was going to ask if there is somethign else I need to do in XCODE.

Do I have to install CocoaPods in my ios project (xcode) to make it work?

I really appreciate all your help
Alex


On Jun 30, 2016, at 09:11 AM, Simon MacDonald <notifications@github.com> wrote:

@dtmdata I can see in your logs that you get the registration ID:
2016-06-30 01:43:06.119 PulseBox[2060:1037964] GCM Registration Token: k1uFXUttY_o:APA91bGfV_0JbflKHjB4wedHAv5uSWZdv5bkTS2-NH1yGTL6cgkYP1SVV8ngIrF0lXS18Iw858dvW2tmlSC_ZC60-M_VPOhytWORr-1_WYD_O-af89FCmLk5BQ1trofTWu4R_9Xzajxx
but when you go to send the push you use:
tokens.push("APA91bGfV_0JbflKHjB4wedHAv5uSWZdv5bkTS2-NH1yGTL6cgkYP1SVV8ngIrF0lXS18Iw858dvW2tmlSC_ZC60-M_VPOhytWORr-1_WYD_O-af89FCmLk5BQ1trofTWu4R_9XzajXX");
So you are missing the k1uFXUttY_o: prefix so the line should be:
tokens.push("k1uFXUttY_o:APA91bGfV_0JbflKHjB4wedHAv5uSWZdv5bkTS2-NH1yGTL6cgkYP1SVV8ngIrF0lXS18Iw858dvW2tmlSC_ZC60-M_VPOhytWORr-1_WYD_O-af89FCmLk5BQ1trofTWu4R_9XzajXX");

**Comment by macdonst** [comment]
@dtmdata No, you don't need to install CocoaPods, the GCM libs are included in the project.

Generally that error is caused by sending a push to the wrong project. So make sure that the senderId you use in iOS, 619792080xxx, matches the one you use for Android. Then you have to make sure that API key you are using in your node-gcm code matches up with the project that is using your sender ID.

Barring that check to see if your device is being signed with a production key instead of development key.

**Comment by dtmdata** [comment]
Simon

Thanks a lot for the TIP.
In GCM I created a different Project for the IOS aPP. SO, I got a different project_id and different API key than the one I use for Android.

I was using the Develpment SSL APNS from IOS. I will update to use the production APNs SSL and I will upload that key in the GCM for the same Android project.

I will try these changes today.

Thanks a lot for your help. I will let you know if that worked.

Alex



On Jun 30, 2016, at 02:00 PM, Simon MacDonald <notifications@github.com> wrote:

@dtmdata No, you don't need to install CocoaPods, the GCM libs are included in the project.
Generally that error is caused by sending a push to the wrong project. So make sure that the senderId you use in iOS, 619792080xxx, matches the one you use for Android. Then you have to make sure that API key you are using in your node-gcm code matches up with the project that is using your sender ID.
Barring that check to see if your device is being signed with a production key instead of development key.

**Comment by macdonst** [comment]
@dtmdata yeah, if you are using two different project's from Google that could be causing the problem. Just use the same sender ID as your Android project and generate a new pList file and upload to Google. 

Keep testing with the development cert until it works. You don't need to switch from production at this point. I only mentioned it as many people upload the wrong certs.

**Comment by dtmdata** [comment]
Hi, How are you?
Sorry for the delay answering.

I have made the following and I am still getting this error:
C:\Users\aleja\Documents\node>node testnotif.js
{ multicast_id: 5299152479703730000,
success: 0,
failure: 1,
canonical_ids: 0,
results: [ { error: 'MismatchSenderId' } ] }
C:\Users\aleja\Documents\node>



1) I cleaned up all my certificates from apple.
2) I created a new certificate. (Production Certificate)
3)I  enabled the Push notifications for my ios app. I used the same production key as the above. After that I create my production profile that I use to deploy my ios app.
4) I export my Push Notification certificate to create my p12 file. It contains the production certificate
5) I Updated the my file in the google page to add the new p12 file. I selected the same project I am using for Android app.



6) I got a new google-service file that I used in my IOS app. thise service file shows the correct APP name, APP_ID, dender_id.

7) I linked this file to my ios app (PulseBox).

8) I compiled and uploaded to production.
9) My app was released and when I installed it ask me if I want tio enable push notifications. I get the GCM registration_id but when I try to send it I get the mistmatchSenderId error. For my android version I get everything and I am able to send the notification and see it in my device.

kuss8HpygFo:APA91bGfc9yt1_ygnwL8WeF2kLb9aQNZ8jLvzzgAnc8-GNbpxywkAhpybwBbo3ypugLQEGZo7sOQ-1VjEZtc5170Zs3BlRTSdqVU_k9tUtiia5cWdpEd5BARcn9vK0xtJ00aUe_eUWSs



Any other advice you think can be useful?
I tried to do the same for the development profile but it is the same. I get the GCM registration id, but then when sending the notification I get the same error as production.

I have been working with this over 2 weeks now and not able to send notifications to ios device using this app.

thanks a lot for your advice and feedback
Alex



On Jun 30, 2016, at 04:50 PM, Simon MacDonald <notifications@github.com> wrote:

@dtmdata yeah, if you are using two different project's from Google that could be causing the problem. Just use the same sender ID as your Android project and generate a new pList file and upload to Google.
Keep testing with the development cert until it works. You don't need to switch from production at this point. I only mentioned it as many people upload the wrong certs.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
C:\Users\aleja\Documents\node>node testnotif.js
{ multicast_id: 5299152479703730000,
success: 0,
failure: 1,
canonical_ids: 0,
results: [ { error: 'MismatchSenderId' } ] }

C:\Users\aleja\Documents\node>

**Comment by macdonst** [comment]
@dtmdata what does your `PushNotification.init` look like?

**Comment by dtmdata** [comment]
this is my function

I am using gcmSandbox=false because I used the production profile.

In my test device I have used gsmSandbox=true

thanks
alex


        var push = PushNotification.init({
            "android": { "senderID": "706330172009"},
            "ios": {"senderID": "706330172009","gcmSandbox": "false","alert": "true", "badge": "true", "sound": "true" },
            "windows": {}
        });

        var registrationID = null;
        


        push.on('registration', function (data) {
            console.log(data.registrationId);
            registrationID = data.registrationId;
            $("#gcm_id").html(data.registrationId);

            if (registrationID === ' ' || registrationID === undefined || registrationID == null || registrationID.length <= 0) {
                console.log("Not able to register");
            }

On Jul 05, 2016, at 05:57 AM, Simon MacDonald <notifications@github.com> wrote:

@dtmdata what does your PushNotification.init look like?

**Comment by dtmdata** [comment]
Simon
how are you?

this is my function

I am using gcmSandbox=false because I used the production profile.

In my test device I have used gsmSandbox=true

thanks a lot for your help
Alex




        var push = PushNotification.init({
            "android": { "senderID": "706330172009"},
            "ios": {"senderID": "706330172009","gcmSandbox": "false","alert": "true", "badge": "true", "sound": "true" },
            "windows": {}
        });

        var registrationID = null;
        


        push.on('registration', function (data) {
            console.log(data.registrationId);
            registrationID = data.registrationId;
            $("#gcm_id").html(data.registrationId);

            if (registrationID === ' ' || registrationID === undefined || registrationID == null || registrationID.length <= 0) {
                console.log("Not able to register");
            }



On Jul 05, 2016, at 05:57 AM, Simon MacDonald <notifications@github.com> wrote:

@dtmdata what does your PushNotification.init look like?

**Comment by macdonst** [comment]
@dtmdata um, if you are using the sandbox in one place and production in another then that is what could give you the mismatch error.

**Comment by macdonst** [comment]
Closing, inactivity
