### ISSUE TITLE
How to show badge with notifications count on iOS

### ISSUE THREAD

**Issue by starostin** [phonegap/phonegap-plugin-push#1034]
Hi, first thanks a lot for your plugin. It is a great job. I have some problems with displaying badge with notification count on iOS.

So, I register plugin

```
 window.PushNotification.init({
      android: {
        senderID: settings.senderId,
        clearBadge: true
      },
      ios: {
        alert: true,
        badge: true,
        sound: true,
        clearBadge: true
      },
      windows: {}
    });
```
And on Android I see badge. But I don't see it on iOS. I don't send any specific data in payload (seems data.count should be send automatically). But I dont see this data.count in the message. Could you please help me, what I am doing wrong?

**Comment by macdonst** [comment]
@starostin when you send your push payload to APNS you have to set the `badge` property. For instance:

```
{ 
  aps: {
    alert: "my alert",
    badge: 7
  }
}
```

It is up to you to send the correct badge number from your server.

See https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH107-SW1 for more docs from Apple.

**Comment by starostin** [comment]
Thanks a lot, I thought about it. But now our server side should make some calculation on his side). Thanks again
