### ISSUE TITLE
Can't find variable: cordova when I receive a notification on iOS

### ISSUE THREAD

**Issue by Greenestgreen** [phonegap/phonegap-plugin-push#1035]
When I receive a notification  on iOS push.on("notification) is not triggered and the console shows me  Can't find variable: cordova.
I have included :
- cordova.js
- index.js

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Greenestgreen** [comment]
Expected Behaviour

trigger on('notification') when i receive a notification

Actual Behaviour

When i send a notification to the device  gives me an error instead of firing on(‘notification’).
The error: Can't find variable: cordova

Reproduce Scenario (including but not limited to)

Steps to reproduce.

Open the app, send a push notification  , expect to on(‘notification’) to be fired

Platform and Version

iPad 2 iOS 9.1

Cordova CLI version and cordova platform version

cordova --version  6.2.8
cordova platform version ios 4.1.1

Plugin version

phonegap-plugin-push 1.7.1

**Comment by macdonst** [comment]
@Greenestgreen seems odd. Are you including other plugins in your project? Can you call those Cordova API's? How are you adding cordova.js to your app (you shouldn't need to do it manually)?

Can you do a Safari remote inspect so I can see the Console logs?

**Comment by Greenestgreen** [comment]
The others plugins are phone gap plugins.
The cordova.js i didn't add it manually, was through the building for iOS in phone gap.

The only log that Safari Show me are. 
[Error] ReferenceError: Can't find variable: cordova
	global code (movil.reporte_reconocimientos.php:1)
[Log] exeption nativeEvalAndFetch : ReferenceError: Can't find variable: cordova (movil.reporte_reconocimientos.php, line 1)
[Log] exeption nativeEvalAndFetch : ReferenceError: Can't find variable: cordova (movil.reporte_reconocimientos.php, line 1)

**Comment by macdonst** [comment]
@Greenestgreen wait why do I see PHP? Are you bundling PHP files in your app? Or are you loading that site remotely?

**Comment by Greenestgreen** [comment]
Loading them remotely

**Comment by macdonst** [comment]
@Greenestgreen Ah, I see. I'd be willing to bet your remote PHP file has not loaded cordova.js.

**Comment by Greenestgreen** [comment]
But why the remote PHP file should load cordova.js? I have this same App for Android and is working right ...

**Comment by macdonst** [comment]
@Greenestgreen well, it's very hard for me to answer since I don't really know how your app is structured but here is the best explanation I can give you.

- you app starts up and it loads index.html.
- index.html includes a reference to cordova.js so the `cordova` object is loaded into memory.
- you navigate from the local index.html to movil.reporte_reconocimientos.php, at this point all of the JS that was loaded by index.html is unloaded from memory.

Make sense?

As for why it would be working in Android, well it shouldn't if both are written the same way but without seeing exactly what you are trying to do I can't really give you a better answer than the above.
