### ISSUE TITLE
[iOS] unregister for a topic: parameter is not consistent between ios/android

### ISSUE THREAD

**Issue by hungdoan2** [phonegap/phonegap-plugin-push#1039]
### Expected Behaviour
Run this Code 
````
push.unregister(function(){}, function(){}, [ios_abcdef123456])
````
and get  message
```
Successfully unsubscribe from topic ios_abcdef123456
```

### Actual Behaviour
Get message
```
Failed to unsubscribe from topic ios_abcdef123456

invalid gcm pubsub topic
```

### Reproduce Scenario (including but not limited to)
N/A

#### Steps to Reproduce 
1. Login
2. Subscribe for topic `ios_abcdef123456`
3. Logout
4. unsubscribe for topic `ios_abcdef123456`
5. unsubscribe fail
6. End

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 9.3

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPhone 5

#### Cordova CLI version and cordova platform version
Cordova 6.2.0

#### Plugin version
v1.7.2

#### Sample Push Data Payload
N/A

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
N/A

I looked at the source code. I seem in iOS It doesn't add '/topics/' to the input (which It did in Android)

**Comment by macdonst** [comment]
@hungdoan2 why don't you send a pull request from your branch and I can merge in the fix.
