### ISSUE TITLE
NotRegistered repsonse from GCM server

### ISSUE THREAD

**Issue by alexislg2** [phonegap/phonegap-plugin-push#104]
Hey all,
I use your plugin with the node-gcm plugin for sending notifications from a Node.js server. It works fine, I can send notifications to devices and they receive it instantly. But after few days, I receive notRegistered answer from GCM. I looked at the GCM documentation and NotRegistered mean that either the device unregistered or that the app is no longer installed on the device

But I never unregistered neither uninstalled the app. If I launch the app again, then the app registers again and then I can receive notifications again but during the time between the first notRegistered response appears and the time I lauch the app, device does not receive any notification and server always get the NotRegistered response.

Anyone else experienced this?

**Comment by alexislg2** [comment]
I think it is because the app always registers at startup even if the app is already registered. This cause GCM to generate a new regId. But if the app has no time to transmit this new regId to the server, then the server has an old regId in its DB.

i think the app should first check that the app is not already registered and that there is internet access.

**Comment by fredgalvao** [comment]
AFAIK multiple and consecutive calls to the register service on GCM do not generate new regIds, and this has been the case since always the apps I have that use pushNotification plugins (be it PushPlugin or phonegap-plugin-push), so that might not be the root of this issue.

**Comment by alexislg2** [comment]
Could this be related?
https://github.com/phonegap-build/PushPlugin/pull/497

**Comment by macdonst** [comment]
@alexislg2 good hint, I will look into it.

**Comment by alexislg2** [comment]
Other hypothesis: Does regId is modified when the user updates the app through the Google Play Store?

If so then any notification sent between the app auto update moment and the first launch would throw a notRegistered error. I will try to investigate this

**Comment by fredgalvao** [comment]
@alexislg2 , that's not the case. RegistrationIDs do not change inbetween different app versions.

**Comment by alexislg2** [comment]
Hey. I still have this annoying issue.

I foud something that might be linked http://stackoverflow.com/questions/17893117/gcm-registration-id-changed

_So, for handling that you should have a Broadcast Listener which could handle com.google.android.c2dm.intent.REGISTRATION intent, which Google send to the app when it has to refresh the registration ID. The broadcast receiver will have the onReceive method with an Intent. From the intent you can get the Bundle using which you can extract the new registration ID from Google. You can save that and send it to the 3rd part server to replace your previous registered ID for that user._

Is this possibel to implement this with your plugin?

**Comment by macdonst** [comment]
@alexislg2 that's out of date now as the plugin uses Google's new Instance ID API for registration ID's. It has a service `com.adobe.phonegap.push.PushInstanceIDListenerService` that will listen for any changes on the registration ID and throw a new registration event.

**Comment by alexislg2** [comment]
I'm not sure I get this. You mean that Google might decide to unregister some regId for whatever reason and that your app will automatically re-register to GCM?
What about when the app is not running? The app cannot send its new regId to the server.

**Comment by fredgalvao** [comment]
@alexislg2 please read up on my comment [here](https://github.com/phonegap/phonegap-plugin-push/issues/296#issuecomment-153836811) for the part where I talk about android.

Regarding your last question, if for some reason Google decides to refresh your instance-id (or invalidate it) while your app is in background or completely shut down, as soon as it's up again the plugin code will check for the current values and trigger the `'registration'` event if it's different than what it has saved previously, so you'll always be guaranteed to be notified about any changes in the instance-id **as soon as possible**.

**Comment by alexislg2** [comment]
OK thanks!

So it means that if Google refreshs the instance-id, my backend won't be able to send notifications to the device as long as the user does not start its app. This is very annoying. I send ~300 notifications a day to 40 differents users and I got 1-2 notRegistered errors per day.

On my mobile phone I have some app like Pushbullet, Pushover or News app that I never open and they keep sending me notifications. I wounder how they do that. Or maybe this is because they are not based on Cordova so they can send their new regId without starting the app.

**Comment by fredgalvao** [comment]
This has close to nothing to do with cordova itself: remember, any native code is agnostic to cordova and it's shells or bridges by default (plugins only make that code *aware* of the shells and bridges).

Being literal, the only way to guarantee a valid token "forever" is to use the old `registrationId` instead of the new `instance-id`, as the former didn't have documented events on which it could change by itself, although I know for a fact that software updates (e.g. android 4.4 -> 5.0) **do** change the device `UUID` and sometimes the `registrationId`.

However, I'd take a long shot and guess that Google isn't naïve and somehow handles these *dead intervals*. They wouldn't upgrade the management of tokens to something less efficient. Something like:

## This is pure speculation and guessing

* Google creates token "123abc_1"
* Application receives and stores "123abc_1"
* Google **for some reason** invalidates "123abc_1" and creates "123abc_2"
* Google still accepts push events sent for "123abc_1" until `com.adobe.phonegap.push.PushInstanceIDListenerService` receives a new event with the new `instance-id`
* Application receives and updates "123abc_2"
* Google frees the previous token permanently

**Comment by alexislg2** [comment]
OK, that would make totally sense.

I updated the plugin so that now my users have instance-id instead of register-id. I don't have any `notRegistered` anymore (let's wait a couple of weeks to be 100% sure).

But I noticed someting weird: With some users after some time, GCM returns me canonical_id for some users. So I update the instance-id in my database and replace with that canonical_id. I can send notifications successfully with this canonical_id. But then when the user starts the app again, the app sends the "old" instance-id (the one that is working but that tiggers canonical_ids from GCM).

Is that normal?

**Comment by fredgalvao** [comment]
I don't get what you mean by the difference between `canonical_id` and  `old instance-id`.

**Comment by alexislg2** [comment]
registration callback gives me an id R1. My app sends R1 to my backend. My
backend saves it and send a message to R1. Then GCM answers gives me a
canonical_id R2. As recommanded by GCM docs, I save that R2 in my database,
overwriting R1.

But then app starts again and registration callback still returns R1. So R1
is sent to my backend. then new notification, GCM re-returns me R2 and so
on....

All the notiifcations are received but this is weird. Is that the right way
to handle instance ids and canonical ids?

**Comment by fredgalvao** [comment]
OH I see... well that's strange. Theoretically we should always follow what the response from GCM tells us to do (update some, delete invalid ones, etc).

Can you please post at least the initial characters of both of these `registrationId`s? I suspect we're dealing with the same content on different formats.

**Comment by alexislg2** [comment]
Example of R1 :

APA91bFTqR54EBjglHCpYLGuES5wDt23UH5ClYBBWQDiHUAYstrqBpebRiVNAyyMMJaJktroOxc22V36HLiWMsa3wOIRmvNAlE0oAO74hszFERtuHfd-l2Sy3_bc9OnjeUgSN1......

Example of R2 (canonical id replied by GCM after we sent notification to
R1) :

ctq9HEOZ7XU:APA91bEmy6Ibjm0RUIogtRCjD5cHNbASC0-oyd6WqivXJy8S-OizU7ds70efBj0a7aBKAu17QydY_d3JHIQFcASa1A_l5gdQD_JZoA_b7o_EhvvUtwPLjUXhH6-pJ0gYgyXwj8......
Both are working

**Comment by fredgalvao** [comment]
Well, R1 is the format/pattern I'm used to seeing on my end too, and there doesn't seem to be anything similar to these two. Maybe @macdonst  has some clue, because I'm kinda lost now.

**Comment by alexislg2** [comment]
BTW on your server you never receives any canonical_ids ? If do, do you update the regId saved in your database?

**Comment by fredgalvao** [comment]
I do have code to update my pair on the server when `canonical_ids` is not null, but I don't log that nor do I have data on how often that's called.

**Comment by alexislg2** [comment]
Well after a few days without any NotRegistered errors, I now have almost as many as before when I send to the canonical_ids. I just don't understand why I'm the only one to have this issue.

**Comment by alexislg2** [comment]
After APK update some of my users' phone send a wrong regId (it gives me a NotRegistered error as soon as I use it to send notification).

Before (when your plugin used registration ids instead of instance id) I had NotRegistered errors but when the user starter its app again a new regId was generated and then I could send notifications.

Now some of my users app directly send invalid id to my server. The only thing I can do is to ask them to uninstall my app and install it again. Then a new id is generated. What am I doing wrong? (I have the last version of your plugin)
