### ISSUE TITLE
Application has stopped

### ISSUE THREAD

**Issue by ignaciochiazzo** [phonegap/phonegap-plugin-push#1043]
### Expected Behaviour
Lunch the application without problems.

### Actual Behaviour
When I run the application, after code of the .run procedure is excecuted, the application stopped and show me the message "Unfortunately, the application has stopped".

### Reproduce Scenario (including but not limited to)
If I delete the code of the pushNotification the application works fine, but if I use the code the app crashed as I have described.

#### Steps to Reproduce 
Open the app in android, and it crahsed

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.2.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
I tried in sony D5106 and in Lg-D724 both of them are using Android 4.4.2

#### Cordova CLI version and cordova platform version
Cordova version : 5.3.3
Installed platforms: android 5.1.1, browser 4.1.0, ios 4.1.0

#### Plugin version
phonegap-plugin-push 1.7.2 "PushPlugin"

#### Sample Code that illustrates the problem
I tried with many code, for example with the Quick example, is happening the same : 

```
 $ionicPlatform.ready(function()  {
   var push = PushNotification.init({
      android: {
        senderID: "892618222375"
      },
      ios: {
          alert: "true",
          badge: "true",
          sound: "false",
          clearBadge: "true"
      }
    });

    push.on('registration', function(data) {
        // data.registrationId
    });

    push.on('notification', function(data) {
        // data.message,
        // data.title,
        // data.count,
        // data.sound,
        // data.image,
        // data.additionalData
    });

    push.on('error', function(e) {
        // e.message
    });
})
```
This code into the .runu

#### Logs taken while reproducing problem

There are no errors the uniques logs that the console throw me are the following:
Resource interpreted as Script but transferred with MIME type text/plain: "file:///android_asset/www/...".
But it always happened.

**Comment by macdonst** [comment]
See issue #909 and all the related issues. You'll need to update Google Play Services on your device and build environment.
