### ISSUE TITLE
Error installing in IOS, version requirement: >=4.1.0

### ISSUE THREAD

**Issue by ignaciochiazzo** [phonegap/phonegap-plugin-push#1047]
Installing the ios  plugin I get the following error : 

```
> Installing "phonegap-plugin-push" for ios
> Plugin doesn't support this project's cordova-ios version. cordova-ios: 3.9.2, failed version requirement: >=4.1.0
> Skipping 'phonegap-plugin-push' for ios
> 
```

Is that ok?  Is 4.1.0 requiered? I ask because the readme says that you could have installed 4.0.0 or less.

**Comment by macdonst** [comment]
@ignaciochiazzo yeah, I'm now requiring people to use cordova-ios 4.1 or better due to a bug in cordova-ios 4.0 that can cause your app to hang. Where did you see it in the docs so I can make the necessary update?

**Comment by mlabarca** [comment]
@macdonst I added a PR with the changes. If I recall correctly, the update to cordova ios 4 was because builds were failing when using armv7s as arquitechtures, right? and then to 4.1 because of an error in cordova ios 4? Is there any other issues that are fixed by using cordova ios 4? Asking since I forked this and removed the version requirement since I don't build for armv7s.

**Comment by macdonst** [comment]
@ignaciochiazzo let me know if PR #1049 fixes the confusion.

@mlabarca thanks for the PR, already merged. Nope, your recollection seems to be complete as to why we did version changes.

**Comment by ignaciochiazzo** [comment]
@macdonst  Thanks for the update, I am having a lot of conflicts using cordova-ios 4.1.0. I will try to fix it.

**Comment by mlabarca** [comment]
@macdonst just as a sidenote, watch out for the minimum deployment target when you use cordova ios 4 - it doesn't support ios ver. < 8.

**Comment by macdonst** [comment]
@mlabarca Yeah, I believe I dropped support for iOS 7 or earlier about a year ago. Most iOS devices are running iOS 8 or 9. The last device that is stuck on iOS 7 is an iPhone 4 which was released in 2010 so I'm okay with the iOS 8 or higher requirement.
