### ISSUE TITLE
PushNotificaton init on iOS does only returns invalid token - not gcm format

### ISSUE THREAD

**Issue by felixsteghofer** [phonegap/phonegap-plugin-push#1048]
### Expected Behaviour
```PushNotification.init()``` should deliver the GCM token with the ```on.register()``` method.

### Actual Behaviour
```push.on``` passes unknown token (APNS?)
example: e42c18e50e3bac33950fb65710db0696482b409a4dac08ff108e273c6828a7c2

### Reproduce Scenario (including but not limited to)
GCM project with Apple push certificate for development and production has been created.
PushPlugin version 1.6.4 (with senderId set on install)
Cordova version 6.0.0

#### Steps to Reproduce 

- Start application
- look into return values of on.registration

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

- iOS 9.3.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

- Apple iPad 2

#### Cordova CLI version and cordova platform version

    cordova --version                    
    6.0.0
    cordova platform version ios
Installed platforms: ios 4.0.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   
phonegap-plugin-push 1.6.4 "PushPlugin"

#### Sample Push Data Payload

not necessary

#### Sample Code that illustrates the problem

```
PushNotification.init({
          android: {
            senderID: "#senderId",
            icon: "icon",
            forceShow: true
          },
          ios: {
            senderId: "#senderId",
            gcmSandbox: true, 
            alert: "true",
            badge: "true",
            sound: "true"
          },
          windows: {}
        });
```

#### Logs taken while reproducing problem

```{registrationId: "e85f54f498baca96943a4e5dcecebe35aed8ba7f2292230ae49881d11b51d853"}```

**Comment by cmgchris** [comment]
The GCM token and APNS token look quiet different. What you are seeing there (since you said you are on iOS) is the APNS token. It looks like it is working as intended.

What problem are you having exactly?

**Comment by felixsteghofer** [comment]
I was able to fix it now, at some time the device.ready() was removed so the registration happend to early. Stragely this was not an issue on android but only on iOS. (I want to send iOS push notifications using GCM so i needed the GCM token instead of the APNS)
Thx anyway!
