### ISSUE TITLE
Enhancement - Led, Vibration Pattern, Priority on Android

### ISSUE THREAD

**Issue by alexislg2** [phonegap/phonegap-plugin-push#105]
Hey,
I could write a PR for supporting following:
- send a Led Color
- send a vibration pattern
- send priority (from 0 to 2)

For Android only of course. Interested?

**Comment by macdonst** [comment]
@alexislg2 Yes, please do.

**Comment by macdonst** [comment]
I'm reopening until I get a chance to merge your PR.

**Comment by macdonst** [comment]
@alexislg2 re-test with the upcoming 1.3.0 release and re-open if it doesn't fix your issue.

**Comment by ezequielrozen** [comment]
Hi, I'm making a push notification with node-gcm, and I don't know how to turn on the led in the phone. I tried as you showed in the example but it didn't work. Please can you tell me the way?

Thanks!

**Comment by fredgalvao** [comment]
What device are you testing on?

Direct quote from android docs on [notificationBuilder.setLights](http://developer.android.com/reference/android/app/Notification.Builder.html#setLights(int, int, int)):
> Not all devices will honor all (or even any) of these values.

**Comment by ezequielrozen** [comment]
@fredgalvao I just saw that there is a new release with the fix, but now I'm having this problem: https://github.com/phonegap/phonegap-plugin-push/issues/159
