### ISSUE TITLE
Failed to load resource: the server responded with a status of 404

### ISSUE THREAD

**Issue by iangithub** [phonegap/phonegap-plugin-push#1053]
I'm creating a cordova project and use azure mobile app + notification hub service. In the cordova project, I add "cordova-plugin-ms-azure-mobile-apps" and "phonegap-plugin-push" plugins, but when run project I get an 404 error

> Failed to load resource: the server responded with a status of 404 - Cannot GET /push/installations/xxxxx(it's a guid string)

### Expected Behaviour
pushChannel registration success
### Actual Behaviour
get 404 error in push.register function
#### Steps to Reproduce 
1.use visual studio 2015  create cordova 6.1.1 project 
2.add phonegap-plugin-push : version="1.7.2"
3.add cordova-plugin-ms-azure-mobile-apps : version="2.0.0-beta5"

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4.2
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
physical devices (Samsung tab 4)

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.1.1
    cordova platform version android                     # e.g. 6.1.1

#### Plugin version

   phonegap-plugin-push : version="1.7.2"
   cordova-plugin-ms-azure-mobile-apps : version="2.0.0-beta5"

**Comment by macdonst** [comment]
@iangithub can you share the code in your `push.register` function? I have a feeling this is not related to the push plugin but would like to confirm.

**Comment by iangithub** [comment]
```
var azureClient = new WindowsAzure.MobileServiceClient('http://ianmobileapp2.azurewebsites.net');
              
        //PushNotification.
        var push = PushNotification.init({
            android: {
                senderID: "1028958039327"
            },
            ios: {
                alert: "true",
                badge: "true",
                sound: "true",
            },
            windows: {}
        });
        
        push.on('registration', function (data) {
            azureClient.push.register('gcm', data.registrationId);
        });
        
        push.on('notification', function (data, d2) {
            alert('Push Received: ' + data.message);
        });
```

WindowsAzure.MobileServiceClient  is a cordova-plugin-ms-azure-mobile-apps plugin that connect azure mobile apps and "azureClient.push.register" function will call executeRequest function in MobileServices.Cordova.js ( cordova-plugin-ms-azure-mobile-apps plugin )

```
function executeRequest(client, method, pushChannel, content, installationId, callback) {
    Validate.isString(pushChannel, 'pushChannel');
    Validate.notNullOrEmpty(pushChannel, 'pushChannel');

    var headers = { 'If-Modified-Since': 'Mon, 27 Mar 1972 00:00:00 GMT' };
    headers[constants.apiVersionHeaderName] = constants.apiVersion;

    client._request(
        method,
        'push/installations/' + encodeURIComponent(installationId),
        content,
        null,
        headers,
        callback
    );
}
```

**Comment by macdonst** [comment]
@iangithub the issue really appears to be in the cordova-plugin-ms-azure-mobile-apps plugin so why don't you open an issue in that repo?

**Comment by iangithub** [comment]
@macdonst  , thank you , I will open an issue in cordova-plugin-ms-azure-mobile-apps plugin git repo .

**Comment by macdonst** [comment]
@iangithub closing this for now. Let me know if you run into other problems with the plugin.
