### ISSUE TITLE
App close when use the plugin

### ISSUE THREAD

**Issue by pilladooo** [phonegap/phonegap-plugin-push#1054]
A few days ago, when I use the plugin "phonegap-plugin-push" my app is closed. Before, it worked well. So I can't register to GCM or APNS.

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2

Android Lollipop 5.1.1

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by pilladooo** [comment]
* Model: Android - Nexus 4 - Lollipop 5.1.1
* Cordova version: 6.2.0
* Cordova platform version: 5.1.1
* Plugin version: 1.7.2

* Sample Code that illustrates the problem:

```
        $ionicPlatform.ready(function() {

            var options = {
                android: {
                    senderID: SOCIAL.SENDER_ID_GCM,
                    //Nombre icono en platform/android/rest
                    icon: "ic_stat_image_edit",
                    iconColor: 'aqua',
                    clearNotifications: 'false',
                    sound: "true",
                    vibrate: "true",
                    forceShow: 'true'
                },
                ios: {
                    alert: "true",
                    badge: "true",
                    sound: "true",
                    clearBadge: "true"
                }
            };

            // initialize
            $cordovaPushV5.initialize(options).then(function() {
                alert(JSON.stringify(options));

                $cordovaPushV5.register().then(function(data) {
                    alert(JSON.stringify(data.registrationId));
                }) 
            });

        })
```

* Logs taken while reproducing problem:
When execute the code abode, I get the message "The application has stopped" and I can't obtain any log...

Thanks!
