### ISSUE TITLE
How to open a specific page on notification clicked in android 

### ISSUE THREAD

**Issue by ajaysaini95700** [phonegap/phonegap-plugin-push#1057]

**Comment by macdonst** [comment]
@ajaysaini95700 for examples: 

http://macdonst.github.io/push-workshop/module7.html
http://macdonst.github.io/push-workshop-eu/module7.html

**Comment by ajaysaini95700** [comment]
When app is in foreground then push.on('notification', function(data)  is fired but when app is in background or closed then push.on('notification', function(data) is not fired

**Comment by macdonst** [comment]
@ajaysaini95700 show me your payload.

**Comment by ajaysaini95700** [comment]
I have fixed it
