### ISSUE TITLE
Registered only for badges

### ISSUE THREAD

**Issue by tgale96** [phonegap/phonegap-plugin-push#106]
Hello,

I essentially copied the exact example code to set up PN in my app, but when I go into settings I see that it is only registered to receive badges. Is there something else I have to pass into the iOS options in the PushNotification instance to register for banners and sound as well?

Thanks,
Trevor

**Comment by macdonst** [comment]
@tgale96 I keep forgetting to update the docs but for the options you pass into the init function for iOS you can use:

```
var push = PushNotification.init({ "android": {"senderID": "12345679"},
         "ios": { "badge": "true", "sound": "true", "alert": "true"}, "windows": {} } );
```

**Comment by macdonst** [comment]
@tgale96 please re-open if you still have the problem on 1.4.0 and can provide a reproduction scenario.
