### ISSUE TITLE
There is a way to ask for permission on demand?

### ISSUE THREAD

**Issue by raphagodoi** [phonegap/phonegap-plugin-push#1061]
all aps are doing this to explain to users why they need the notifications, and this improve the chances to users allow the notifications.

what I want is: open the app, explain the user why i need the notifications and after that ask for permission.

**Comment by macdonst** [comment]
@raphagodoi right so you start the app, explain why you need notifications then call `PushPlugin.init()`. The dialog to ask for push permission on iOS won't be shown until after you call init.

**Comment by raphagodoi** [comment]
@macdonst I think there was a mistake, sorry if I did not explain myself right. Take a look at this site

https://techcrunch.com/2014/04/04/the-right-way-to-ask-users-for-ios-permissions/

he explains a better way to approach the user to request permission.

by the way I just did a test and found that even without putting any code, the plugin asks the user's permission.

**Comment by macdonst** [comment]
@raphagodoi nope, I understood exactly what you meant. I've actually read and referred to that article before. As I said you'd need to provide your own UI before you call `PushPlugin.init()`. If you are seeing the system dialog before calling `init` that is odd. It reminds me of #201 which I could never reproduce.
