### ISSUE TITLE
Android push.on('notification') event handlers not being called when using FCM

### ISSUE THREAD

**Issue by lukebpowell** [phonegap/phonegap-plugin-push#1062]
### Expected Behaviour
Android only:
1.1  Push message arrives with app in background (payload does not contain `content-available: 1`)
1.2  User clicks on notification in notification center
1.3  The app resumes and the plugin calls all of the `notification` event handlers

2.1  Push message arrives with app closed (payload does not contain `content-available: 1`)
2.2  User clicks on notification in notification center
2.3  The app starts and the plugin calls all of the `notification` event handlers

### Actual Behaviour
Android only. This applies to both the app being in the background and the app being closed.
1. Push message arrives
2. User clicks on notification in notification center
3. The app starts but does NOT call the `notification` event handlers

Behavior that is working correctly:

- (Android) Push message arrives while app is in foreground.  `notification` event handlers are called.

- (iOS) Push message arrives while app is in background or closed.  User clicks on notification in notification center.  The app starts and `notification` event handlers are called.

- (iOS) Push message arrives while app is in foreground.  `notification` event handers are called.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android: 5.1
iOS: 9.3.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Motorola: Moto E (2nd Generation)

#### Cordova CLI version and cordova platform version

    cordova 6.2.0
    cordova android 4.1.1
    cordova ios 4.1.0

#### Plugin version

    phonegap-plugin-push 2.0.0 "PushPlugin"
    Using the most recent commit of the 'FCM' branch
    07fa81b7a3a62400915ac70b9a24a802465a6f95

#### Sample Push Data Payload

I am using FCM for push notifications, not GCM.  

```
{
  to: '/topics/news',
  data: {
    message: 'this is a custom param',
    signal_id: 'this is a custom param'
  },
  notification: {
    title: 'Test title',
    body: 'Test body',
    sound: 'default',
    badge: '1',
    icon: 'ic_launcher'
  },
  priority: 'high'
};
```
#### Sample Code that illustrates the problem
This is the initialization code:
```
let config = {
  android: {
    senderID: '85XXXXXXXXX',
    icon: 'icon',
    sound: true,
    vibrate: true,
    clearNotifications: true,
    topics: ['news']
  },
  ios: {
    senderID: '85XXXXXXXXX',
    gcmSandbox: true,
    alert: true,
    badge: true,
    sound: true,
    clearBadge: true,
    topics: ['news']
  }
};
this.push = PushNotification.init(config);

this.push.on('registration', (data) => {
  console.log('registration complete');
  console.log(data.registrationId);
});

this.push.on('notification', (data) => {
  console.log('notification event handler invoked');
});
```
#### Logs taken while reproducing problem
There were no errors.

**Comment by macdonst** [comment]
@lukebpowell the plugin does not currently support FCM. It is being worked on in the `v2.0.x` branch of this plugin. When issue #929 is finished then support will be official at this time we're not opening bugs on unreleased code.

**Comment by lukebpowell** [comment]
@macdonst alright, thanks for the reply.

**Comment by macdonst** [comment]
@lukebpowell np, feel free to comment on #929 with your findings. I'm on vacation this week but I'll be getting to FCM with Julio and hopefully another committer soon.
