### ISSUE TITLE
Cordova 6.1.1 + crosswalk 1.3.8 app crash in some devices

### ISSUE THREAD

**Issue by mvnerisantos** [phonegap/phonegap-plugin-push#1063]
### Expected Behaviour
Load app

### Actual Behaviour
App crash when call PushNotification.init after install crosswalk 1.3.8

### Reproduce Scenario (including but not limited to)
Test in Asus Zenfone 5

#### Steps to Reproduce 
Just run the app

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
 android 4.4.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Asus Zenfone 5

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.1.1
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.6.3

**Comment by macdonst** [comment]
@mvnerisantos please give me the stack trace from the app when it crashes. Run `adb logcat` while reproducing the error.

**Comment by mvnerisantos** [comment]
Hello @macdonst log attached.

Thanks

[log.txt](https://github.com/phonegap/phonegap-plugin-push/files/355505/log.txt)

**Comment by macdonst** [comment]
@mvnerisantos please see issue #909 as to why this happens. I released version 1.7.3 of this plugin that will force you to compile with a version of the library that has the fix from Google.
