### ISSUE TITLE
Plugin causes build to fail in PhoneGap Buil

### ISSUE THREAD

**Issue by andrewbriggs** [phonegap/phonegap-plugin-push#1064]
Our PhoneGap build is failing even though the Build Status page says it is up and running. I know that it is this plugin because when I remove these lines from the config.xml the build will work:

```
<preference` name="android-build-tool" value="gradle" />
<plugin name="phonegap-plugin-push" source="npm">
<param name="SENDER_ID" value="XXXXXXXXXXX" />
</plugin>
```

We are getting this error: Oh geez. Your build failed. Sorry, but a problem occurred on the build server

This is the error log:

Build Date: 2016-07-07 01:38:33 +0000

FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring root project 'project'.
  
  > Could not resolve all dependencies for configuration ':_debugCompile'.
  > Could not find any version that matches com.google.android.gms:play-services-gcm:9.0.2+.
  > Searched in the following locations:
  > https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
  > https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/
  > file:/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/ma ven-metadata.xml
  > file:/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/
  > file:/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-gcm/mav en-metadata.xml
  > Required by:
  > :project:unspecified
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.369 secs
undefined

**Comment by macdonst** [comment]
@andrewbriggs that means the build service doesn't have version 9.0.2 of Google Play Services on it. I will talk to the build team. In the mean time pin your version to 1.7.2.

**Comment by gustavocampos** [comment]
I only got a successful build with version 1.6.4 due to the same problem

**Comment by cmalard** [comment]
@gustavocampos : By the way... with PGB you should only be able to use <=1.7.0 or the app will crash (see https://github.com/phonegap/phonegap-plugin-push/issues/1020), whatever device or Android version :-/

**Comment by gustavocampos** [comment]
@cmalard oh thanks for letting me know

**Comment by andrewbriggs** [comment]
@cmalard I am using 1.7.2 and the app is not crashing.

**Comment by AnSharipov** [comment]
In my config.xml:
```
  <preference` name="android-build-tool" value="gradle" />
  <plugin name="phonegap-plugin-push" source="npm" spec="1.6.4">
    <param name="SENDER_ID" value="653658856830"/>
  </plugin>
  <platform name="android">
```

But I still get an error:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-gcm:9.0.2+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/
```

What do I do incorrect?

**Comment by macdonst** [comment]
All, I sent another message to the PGB team to update.

**Comment by oleksiy-nesterov** [comment]
same issue for me ((

**Comment by AnSharipov** [comment]
Hello, guys! I need to show today an app. But I cant compile it for reasone - play-services-gcm:9.0.2+. 
How can I fix it?

**Comment by SanjayYadav90** [comment]
hi all,
I have same issue, and trying to fix from last evening.
I need to implement Push Notification in my existing application, and i follow
https://www.youtube.com/watch?v=LV1CjQ1UsYA
when I try to build apk-
`$ cordova build android --release`
It gives following error as-

FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred evaluating root project 'android'.
> Failed to apply plugin [id 'android']
   > Plugin with id 'android' not found.

=>Wanted to know what is the issue behind?
=> and how to get it fixed?

**Comment by SanjayYadav90** [comment]
HI ALL,
I have same issue, and trying to fix from last evening.
I need to implement Push Notification in my existing application, and i follow
https://www.youtube.com/watch?v=LV1CjQ1UsYA
when I try to build apk-
`$ cordova build android --release`
It gives following error as-

FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred evaluating root project 'android'.
> Failed to apply plugin [id 'android']
   > Plugin with id 'android' not found.

=>Wanted to know what is the issue behind?
=> and how to get it fixed?

**Comment by fentas** [comment]
In my case, this message was because of missing packages in the Android SDK, so it was required to install some packages via the Android SDK Manager.
```sh
android # To open the SDK manager
```
Look for:
```
Extras -> Google play services
Extras -> Google repository
```
And install them.

> Source: http://stackoverflow.com/questions/33475178/cordova-fails-to-build-on-android-gcm-dependency

**Comment by thatsmekaustubh** [comment]
build fails with same issue even after setting version to 1.7.2

  <plugin name="phonegap-plugin-push" source="npm" spec="~1.7.2">
        <param name="SENDER_ID" value="xxxxxx56830"/>
  </plugin>

**Comment by AnSharipov** [comment]
I updated Google Play Service in Android SDK Manager and it worked

**Comment by thatsmekaustubh** [comment]
@AnSharipov  my playservices are level 31 no more updates available still issue persists

**Comment by romuloinnocencio** [comment]
It's my first contact with this kind of stuff....

**Here goes my erros**
http://prntscr.com/bv8044

**SDK's: **
http://prntscr.com/bv80uj

**Comment by productank** [comment]
solution for this?

**Comment by ezequielnaftali** [comment]
Hi, have you resolve this? 
I have updated to the latest SDK for all the dependencies and still the same.
Thanks!

**Comment by cmalard** [comment]
@ezequielnaftali : nothing to resolve here. We're waiting PGB update.
What you can do now : https://github.com/phonegap/phonegap-plugin-push/issues/1064#issuecomment-231481150

**Comment by cmalard** [comment]
They made an update ! https://twitter.com/phonegapbuild/status/758412620038713345

**Comment by tetecriizz** [comment]
I've getting error:

`* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-gcm:9.0.2+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/`

And then I've updated as fentas said:

`Extras -> Google play services
Extras -> Google repository`

Regards

**Comment by gitekiras** [comment]
Hi, is there any fixes or work arounds, i am also stuck with the same thing

Could not find any version that matches com.google.android.gms:play-services-gcm:9.0.2+

**Comment by tetecriizz** [comment]
Open your SDK Manager and then search Google Play Services (Extras folder, below of all) check on Google Play Services and Install Packages.

You tried it?

**Comment by j-ramirez-bi4group** [comment]
Updating the Google Play Services worked for me. Thanks

**Comment by thatsmekaustubh** [comment]
Updating play services isn't helping ... Currently get build from build.phonegap.com
But there are plugins which require install time parameters which are thus stuck

Please do help

**Comment by barkatdhillon** [comment]
I installed Extras -> Google Play Services and Extras -> Google Repository, and my build worked successfully.
<plugin name="phonegap-plugin-push" spec="~1.8.1">
        <variable name="SENDER_ID" value="XXXXXXXXX" />
</plugin>

**Comment by wwwguy** [comment]
Still getting the same error. Have updated Google Play Services and Google Repository.

**Comment by wwwguy** [comment]
Figured it out. If you are running via CLI and update Android SDK directly it may not work. You need to also update from within Android Studio. That did it for me!

**Comment by ppiatek** [comment]
`Could not find any version that matches com.google.android.gms:play-services-gcm:9.0.2+.`
Solution in my case: 
I modified file `/platforms/android/project.properties`:
- `cordova.system.library.2=com.google.android.gms:play-services-gcm:9.0.2+`
- `cordova.system.library.2=com.google.android.gms:play-services-gcm:8.4.0`

**Comment by PterPmnta** [comment]
@ppiatek how you do it?, i find this [other solution](http://stackoverflow.com/questions/37311794/upgrade-to-google-play-services9-0-0-error-failed-to-resolve-com-google-androi)

**Comment by sklaujb** [comment]
Has this problem been solved? I tired all suggestion and still fail with the same error

**Comment by ppiatek** [comment]
I had below error message the suggestion of which versions of play-services-gcm I have installed in my OS, so I chose 8.4.0 and then it started working. I tried to install version 9.0.2 but without results but changing to this version in this file (/platforms/android/project.properties) helped me.

**Comment by sklaujb** [comment]
@ppiatek how do I check which version of play-services-gcm I have on my OS? Obviously I don't have the 8.4.0 because I got the same error

**Comment by souly1** [comment]
For me it was the exact opposite from @wwwguy , update from Android Studio didn't work, but update from Android SDK manager directly (writing `android` in console like @fentas mentioned) solved it for me

**Comment by droolingOnU88** [comment]
@ppiatek worked for me too!

**Comment by haxpor** [comment]
@fentas solution works for me (updating packages via `android` manager).

**Comment by ppiatek** [comment]
@sklaujb sorry that I didn't answer when you asked. Maybe you solved that but I would try to use some of version available and check is it work. I had few days ago tha same problem after updating some packages. 

Logs in console began with this:

`Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-gcm:9.8+.
     Versions that do not match:
         9.6.1
         9.6.0
         9.4.0
         9.2.1
         9.2.0
         + 7 more
`

so I took the tried with first version "9.6.1" and the application has compiled. 
Now I changed this line:

`cordova.system.library.3=com.google.android.gms:play-services-gcm:9.8+`

to this:

`cordova.system.library.3=com.google.android.gms:play-services-gcm:9.6.1`

**Comment by luiswill** [comment]
Thanks @ppiatek ! I solved this thanks to you

**Comment by macdonst** [comment]
the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.

**Comment by fcampinho** [comment]
Android > SDK Manager.
Update the Android Studio SDK Manager: click SDK Tools, expand Support Repository, select Google Repository, and then click OK.
