### ISSUE TITLE
Question - Does the id in the cordova config.xml have to match the application/package id for iOS and Android?

### ISSUE THREAD

**Issue by vsecades** [phonegap/phonegap-plugin-push#1065]
Does the id in the cordova config.xml have to match the application/package id for iOS and Android?

I noticed that if we kept the id attribute in the widget tag of the config.xml different than the one in the package identifier for Android, we had problems getting notifications.  

Is this behavior also consistent in iOS?

**Comment by macdonst** [comment]
@vsecades on Android it should not matter. Android uses the `senderID` to identify which Google Project it should register with. As long as you sender ID matches the API key you use to send the push then you will be okay.

On iOS the id in the config.xml will be used as your "Bundle Identifier" in Xcode. This is the ID that iOS uses to look up the cert/provisioning files. So if you create an app with an ID of `com.abc.push` in config.xml but your certificate is using `com.def.push` you will never receive pushes.

**Comment by vsecades** [comment]
@macdonst we ran across a problem with HTC 4.4.x phones, and basically setting the id to equal the identifier of the package cleared that up.

Thanks for the tip on iOS, we'll take a look at that immediately.
