### ISSUE TITLE
include the 'notId' parameter in the readme

### ISSUE THREAD

**Issue by letscodehu** [phonegap/phonegap-plugin-push#1067]
### Expected Behaviour

Ability to separate messages with the unique ID stated in GCM documentation. 

OR

the documentation should contain the unique identifier (payload.data.notId) which used to separate the notifications received.

### Actual Behaviour

Only the last message appear.

#### Steps to Reproduce 

Send messages without a unique 'notId' field inside the 'data' field of the payload and only the last one appears.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung

#### Cordova CLI version and cordova platform version
Cordova 6.2.0
Android 5.1.1

#### Plugin version
1.7.2

#### Sample Push Data Payload

Only the last ones appear:

 {
    ["title"]=>
    string(9) "EDES ELET"
    ["message"]=>
    string(30) "New series on air AMR: 143 868"
  }
 {
    ["title"]=>
    string(16) "A TORVENY EMBERE"
    ["message"]=>
    string(30) "New series on air AMR: 131 455"
  }

If the notId field is fileld then separate notification for each one
{
   ["notId"]=> (int) 1
    ["title"]=>
    string(16) "A TORVENY EMBERE"
    ["message"]=>
    string(30) "New series on air AMR: 131 455"
  }

#### Sample Code that illustrates the problem

public static final String NOT_ID = "notId";
int notId = parseInt(NOT_ID, extras);
mNotificationManager.notify(appName, notId, mBuilder.build());

**Comment by macdonst** [comment]
@letscodehu is the section on Stacking not descriptive enough or hard to find? 

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#stacking

**Comment by letscodehu** [comment]
Totally my faullt, I missed that payload section.
