### ISSUE TITLE
error 65

### ISSUE THREAD

**Issue by benag** [phonegap/phonegap-plugin-push#1068]
### Expected Behaviour

Build on ios

### Actual Behaviour

Error on build

### Reproduce Scenario (including but not limited to)

cordova plugin add phonegap-plugin-push --variable SENDER_ID="XXXXXXX"

ionic platform add ios

ionic run ios

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
OSx capitan

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iphone 4

#### Cordova CLI version and cordova platform version

   ionic 1.7.16
   cordova 6.2.0
   node 4.4.7

#### Plugin version

    phonegap-plugin-push 1.7.3 "PushPlugin"

#### Logs taken while reproducing problem

CompileC build/client.build/Debug-
iphonesimulator/client.build/Objects-normal/i386/PushPlugin.o client/Plugins/phonegap-plugin-push/PushPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/bengoldenberg/Projects/autonomo/client/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/vl/39tdd3g11k73p1_pl9stj0dw0000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/bengoldenberg/Projects/autonomo/client/platforms/ios/build/client.build/Debug-iphonesimulator/client.build/client-generated-files.hmap -I/Users/bengoldenberg/Projects/autonomo/client/platforms/ios/build/client.build/Debug-iphonesimulator/client.build/client-own-target-headers.hmap -I/Users/bengoldenberg/Projects/autonomo/client/platforms/ios/build/client.build/Debug-iphonesimulator/client.build/client-all-target-headers.hmap -iquote /Users/bengoldenberg/Projects/autonomo/client/platforms/ios/build/client.build/Debug-iphonesimulator/client.build/client-project-headers.hmap -I/Users/bengoldenberg/Projects/autonomo/client/platforms/ios/build/emulator/include -I/Users/bengoldenberg/Projects/autonomo/client/platforms/ios/build/emulator/usr/local/lib/include -I/Users/bengoldenberg/Projects/autonomo/client/platforms/ios/build/UninstalledProducts/include -I/Users/bengoldenberg/Projects/autonomo/client/platforms/ios/build/UninstalledProducts/iphonesimulator/include -I/Users/bengoldenberg/Projects/autonomo/client/platforms/ios/build/emulator -I/Users/bengoldenberg/Projects/autonomo/client/platforms/ios/build/client.build/Debug-iphonesimulator/client.build/DerivedSources/i386 -I/Users/bengoldenberg/Projects/autonomo/client/platforms/ios/build/client.build/Debug-iphonesimulator/client.build/DerivedSources -F/Users/bengoldenberg/Projects/autonomo/client/platforms/ios/build/emulator -include /Users/bengoldenberg/Projects/autonomo/client/platforms/ios/build/sharedpch/client-Prefix-fpbmvzxakzwgzdabhsswndwpwqqo/client-Prefix.pch -MMD -MT dependencies -MF /Users/bengoldenberg/Projects/autonomo/client/platforms/ios/build/client.build/Debug-iphonesimulator/client.build/Objects-normal/i386/PushPlugin.d --serialize-diagnostics /Users/bengoldenberg/Projects/autonomo/client/platforms/ios/build/client.build/Debug-iphonesimulator/client.build/Objects-normal/i386/PushPlugin.dia -c /Users/bengoldenberg/Projects/autonomo/client/platforms/ios/client/Plugins/phonegap-plugin-push/PushPlugin.m -o /Users/bengoldenberg/Projects/autonomo/client/platforms/ios/build/client.build/Debug-iphonesimulator/client.build/Objects-normal/i386/PushPlugin.o
clang: error: no such file or directory: '/Users/bengoldenberg/Projects/autonomo/client/platforms/ios/client/Plugins/phonegap-plugin-push/PushPlugin.m'
clang: error: no input files

** BUILD FAILED **

The following build commands failed:
        CompileC build/client.build/Debug-iphonesimulator/client.build/Objects-normal/i386/AppDelegate+notification.o client/Plugins/phonegap-plugin-push/AppDelegate+notification.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
        CompileC build/client.build/Debug-iphonesimulator/client.build/Objects-normal/i386/PushPlugin.o client/Plugins/phonegap-plugin-push/PushPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/bengoldenberg/Projects/autonomo/client/platforms/ios/cordova/build-debug.xcconfig,-project,client.xcodeproj,ARCHS=i386,-target,client,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/bengoldenberg/Projects/autonomo/client/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/bengoldenberg/Projects/autonomo/client/platforms/ios/build/sharedpch

**Comment by macdonst** [comment]
@benag what version of cordova-ios are you using?

**Comment by benag** [comment]
sorry i dont remember installing one

**Comment by benag** [comment]
I believe that after running "cordova platform update ios" this error disappear and the error 65 seems to be related to certificate. Thank you for your help

**Comment by JoseOcasio** [comment]
I am having the exact same issue. I have tried the following and no luck

cordova platform update ios
sudo ionic platform remove/add ios
