### ISSUE TITLE
Unable to Build for Android ionic project

### ISSUE THREAD

**Issue by arunap** [phonegap/phonegap-plugin-push#1069]
I'm getting following error during the Android deployment. This is working for ios 

Note: I'm using visual studio as the IDE

``1>
1>MSBUILD : cordova-build error : FAILURE: Build failed with an exception.
1>  FAILURE: Build failed with an exception.
1>
1>MSBUILD : cordova-build error : * What went wrong:
1>  * What went wrong:
1>MSBUILD : cordova-build error : Execution failed for task ':mergeDebugResources'.
1>  Execution failed for task ':mergeDebugResources'.
1>MSBUILD : cordova-build error : > C:\Users\aruna\Documents\Visual Studio 2015\Projects\Ionic Tabs Template4\Ionic Tabs Template4\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.0.2\res\drawable-tvdpi-v4\common_plus_signin_btn_icon_dark_pressed.9.png: Error: File path too long on Windows, keep below 240 characters : C:\Users\aruna\Documents\Visual Studio 2015\Projects\Ionic Tabs Template4\Ionic Tabs Template4\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.0.2\res\drawable-tvdpi-v4\common_plus_signin_btn_icon_dark_pressed.9.png
1>  > C:\Users\aruna\Documents\Visual Studio 2015\Projects\Ionic Tabs Template4\Ionic Tabs Template4\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.0.2\res\drawable-tvdpi-v4\common_plus_signin_btn_icon_dark_pressed.9.png: Error File path too long on Windows, keep below 240 characters : C:\Users\aruna\Documents\Visual Studio 2015\Projects\Ionic Tabs Template4\Ionic Tabs Template4\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.0.2\res\drawable-tvdpi-v4\common_plus_signin_btn_icon_dark_pressed.9.png
1>
1>MSBUILD : cordova-build error : * Try:
1>  * Try:
1>MSBUILD : cordova-build error : Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
1>  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
1>  :mergeDebugResources FAILED
1>
1>  BUILD FAILED

**Comment by macdonst** [comment]
@arunap It's no a problem with the plugin it is a problem with the Windows operating system. The error indicates:

```
Error: File path too long on Windows, keep below 240 characters
```

So you will need to patch the version of Windows you are using. See: https://support.microsoft.com/en-ca/kb/2891362
