### ISSUE TITLE
Elaborate on token/registration_id change handling

### ISSUE THREAD

**Issue by iDobbler** [phonegap/phonegap-plugin-push#1072]
I'm having difficulty understanding the way a token refresh is handled. I have searched around a lot and have trouble finding an answer. To explain my situation; I'm working on an application that notifies the user of any unusual events happening in his/her area. So sometimes the app will be running in the background for maybe 6 months. According to GCM docs the registration token can cease to be valid and this change event needs to be handled.

So i have the following questions; How does this plugin handle a token change after it has been initialized?; And how is a token change handled when the app is running in the background? If this is not handled, do you have a suggestion as to how i can handle this event myself?

I'm using plugin version 1.6.4 and GCM for both iOS and Android.

**Comment by macdonst** [comment]
@iDobbler the plugin registers a listener for registration ID changes with GCM. When it detects a registration ID change it fires the `registration` event for your app to handle. If you app is running in the background it should be able to handle it. If the app has been killed then it will fetch the new registration ID on app startup.

**Comment by iDobbler** [comment]
@macdonst That's all i needed to know. Thanks a lot for the quick response. :)
