### ISSUE TITLE
plugin not working for ios

### ISSUE THREAD

**Issue by praveens96** [phonegap/phonegap-plugin-push#1074]
### Expected Behaviour

after installing the plugin and trying to registerForPushNotifications() by doing a push.init(). But request for push notifications is not displaying. i have followed the steps given in the help page as is. upgraded to ios4.1. created new app a couple of times but still the alert/request for push notification is not showing.

### Actual Behaviour

PushNotification object in window.cordova.plugins is coming as Null. i am trying on actual device.

#### Steps to Reproduce 
1. Just create a new app
2. add push plugin
3. in app.js, under ionic.ready call method registerForPush() where i will do an init. registerPush itself is not getting called.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS9.2 and 9.3

#### Cordova CLI version and cordova platform version
latest
    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

latest
    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@praveens96 sorry, are you testing this in the iOS simulator?

**Comment by praveens96** [comment]
i have tried in simulator and device.
also, on android device when trying the below received Service_Not_Available error message:
var push = PushNotification.init({
    android: {
        senderID: "927016678125"
    },
    ios: {
        alert: "true",
        badge: true,
        sound: 'false'
    },
    windows: {}
	});
	push.on('registration', function(data) {
		console.log(data.registrationId);
		alert("registered");
	});
	push.on('error', function(e) {
		console.log(e.message);
		alert("push errr"+e.message);
	});

do you have idea on this?

**Comment by macdonst** [comment]
@praveens96 On iOS did you setup your certs with the push capability?

On Android if you see `Service_Not_Available` it's exactly that. Your device cannot connect to the GCM servers. Do you have internet connection?

**Comment by praveens96** [comment]
Thanks Simon. i have got it in android. in iOS i am planning to use azure. there in the notification HUB i have placed my certificates. i guess prior to that it should ask for permission to send push notifications. correct? i am not getting that even. Azure push notification uses this plugin so, i am not sure how to proceed for iOS. 
ref: https://azure.microsoft.com/en-in/documentation/articles/app-service-mobile-cordova-get-started-push/

**Comment by praveens96** [comment]
i remove ios.json in plugins folder and then removed platform ios from terminal. then added platform then built ios. it worked then but didnt got the registration id from apns i.e. push.on('registration') or push.on('error') callbacks are not getting called. any idea how to solve this?

**Comment by mail2lulu** [comment]
You may check this: works for iOS and Android
https://github.com/mail2lulu/cordova-plugin-fcm.git

**Comment by macdonst** [comment]
@mail2lulu hey, it would be great if you could contribute some of that FCM code into the v2.0.x branch of this plugin as we want to support FCM in an upcoming release.

**Comment by macdonst** [comment]
@praveens96 it sounds like you don't have the certs on your build machine to give the app push privs. Can you run in Xcode to see what the logs are?

**Comment by praveens96** [comment]
@macdonst it was an issue with provisioning profile. i havent gave my apple account and trying to do push register because of which it is not getting registered. issue is resolved now.
