### ISSUE TITLE
Fails after running cordova build android command

### ISSUE THREAD

**Issue by donny08** [phonegap/phonegap-plugin-push#1075]
cordova version 6.1.1
I'm using  Apache Cordova  for developing hybrid app on a Ubuntu machine and installed phonegap-plugin-push plugin using cmd: cordova plugin add phonegap-plugin-push --variable SENDER_ID="XXXXXXX" and after installation I run cordova build android cmd got below error:

FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-gcm:9.0.2+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/
         file:/home/devuser/Android/Sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
         file:/home/devuser/Android/Sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/
         file:/home/devuser/Android/Sdk/extras/google/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.13 secs
Error: Error code 1 for command: /home/devuser/projects/exampleProjects/mixpanel/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/devuser/projects/exampleProjects/mixpanel/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true

**Comment by macdonst** [comment]
@donny08 run android from the command line and update Android Support Library, Local Maven repository for Support Libraries (formerly Android Support Repository), Google Play Services and Google Repository to get the latest library you need.

**Comment by miparnisari** [comment]
@macdonst I did that and I'm still getting the same error. Cordova 5.1.1 here.

**Comment by macdonst** [comment]
@miparnisari I saw you commented on another issue. Did you get it resolved?

**Comment by miparnisari** [comment]
No :(

-- Maria Ines

On Jul 24, 2016 12:01 PM, "Simon MacDonald" <notifications@github.com>
wrote:
>
> @miparnisari I saw you commented on another issue. Did you get it
resolved?

**Comment by macdonst** [comment]
@miparnisari you need to make sure you have all the latest Android SDK's. If you are updating from Android Studio please note that you may also need to run `android` from the command line to update the SDK's as well. Sometimes Android Studio and the CLI store the SDK's in different locations.

**Comment by miparnisari** [comment]
Ok I got it fixed! All packages appeared as updated in the SDK manager, but when I opened Androd Studio it recognized many new updates, so I updated those.
