### ISSUE TITLE
question about init

### ISSUE THREAD

**Issue by clembou590** [phonegap/phonegap-plugin-push#1076]
if I do call the init function like this.
_var push = PushNotification.init({
    android: {
        senderID: "12345679"
    },
    ios: {
        alert: "true",
        badge: "true",
        sound: "true"
    },
    windows: {}
});

push.on('registration', function(data) {
    // data.registrationId
});

push.on('error', function(e) {
    // e.message
});

does the "on registration" is called or the "on error is called"?

(my question is: if I call init does one of these two methods gets called? ie is there any condition when none of these two methods get called?)

**Comment by macdonst** [comment]
@clembou590 the only time I've seen one of the two events not get fired is when you are trying to run the code on the iOS simulator.
