### ISSUE TITLE
Question about topics subscribe

### ISSUE THREAD

**Issue by kivson** [phonegap/phonegap-plugin-push#1078]
Hi,

I have a doubt about registration for topics. In my scenario the user will choose which topics subscribe during the use of the application, so the ideal would be to have something like 'push.registerToTopic (' topic ')'.

There is something like this (I did not find in the documentation)?

I can call the function 'init' several times during the execution of the app to register on other topics? Any other idea?

**Comment by macdonst** [comment]
@kivson currently there is no methods like that but I talked to @hungdoan2  about adding them. Check out the discussion in #1040.
