### ISSUE TITLE
[Android] icon picture not showing on background

### ISSUE THREAD

**Issue by franciscofsales** [phonegap/phonegap-plugin-push#1079]
#### Expected Behaviour

    The notification on the status bar having the defined icon.

#### Actual Behaviour
    White empty icon

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
    Android 6
    Android 5.1 

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

    ZenFone 2 

#### Cordova CLI version and cordova platform version
    cordova 6.2.0
    cordova android 5.1.1

#### Plugin version

    phonegap-plugin-push 1.7.4

#### Sample Push Data Payload
     { 
        "data":{
           "title": "MyApp",
           "message": "test",
           "priority": "high",
        },
        "to" : "eLX70s..."
    }

If I push the following:

     { 
        "data": {
           "title": "MyApp",
           "message": "test",
           "priority": "high",
           "image": "icon"
        },
        "to" : "eLX70s..."
    }

I get the image that I would like to use as the icon (this validates that the image is on the app's drawables, right?)

#### Sample Code that illustrates the problem

    var pushNotif = PushNotification.init({
          "android": {
            "senderID": "41...",
            "icon": "icon",
            "iconColor": "red"
          },
          "ios": {},
          "windows": {}
     });

As per the documentation, I have a before_build hook that copies:
```
     { 
        "source": "resources/android/icon/icon.png",
        "dest": "platforms/android/drawable/icon.png"
     }
```

and also for the different sizes: drawable-hdpi, drawable-ldpi, drawable-mdpi, etc..

**Any idea of what I am doing wrong?
 Thanks**

**Comment by macdonst** [comment]
@franciscofsales does your icon have transparent pixels in it? Actually can you just post your icon in this thread?

**Comment by franciscofsales** [comment]
@macdonst no, it doesn't

![icon](https://cloud.githubusercontent.com/assets/7977645/16806403/4a215192-490c-11e6-8e54-cb602736416f.png)

**Comment by macdonst** [comment]
@franciscofsales please read the Android image guidelines on images
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images

If there are no transparent pixels then the whole image will show up white.

**Comment by franciscofsales** [comment]
@macdonst thank you, closing it
