### ISSUE TITLE
New push notification overrides older ones in Android.

### ISSUE THREAD

**Issue by GauravButola** [phonegap/phonegap-plugin-push#1082]
### Expected Behaviour
When sending multiple push notifications, all the previous ones should also be preserved in the notification tray.

### Actual Behaviour
Only the last notification shows up in the notification tray.

#### Steps to Reproduce 
Send multiple notifications on android and I only see the last one.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Motorola Moto G2

#### Cordova CLI version and cordova platform version

    cordova --version                                   - 6.2.0
    cordova platform version android          - android 5.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   - 1.7.4

**Comment by macdonst** [comment]
@GauravButola did you read this part of the docs? https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#stacking

**Comment by GauravButola** [comment]
Thanks a lot for the reply @macdonst. That's exactly what I needed, but somehow none of my searches could land me on that doc page or any similar issues. Sorry about that.

I've followed your other answers as well and they've been very helpful. Thanks for all the help :)
