### ISSUE TITLE
Push Woosh compatibility

### ISSUE THREAD

**Issue by dagmawim** [phonegap/phonegap-plugin-push#1083]
Is it possible to use this plugin with other 3rd party plugins, SAFELY? I used this plugin with Push Woosh's sdk and it had some very weird effects like the GCM (on Android) was only sending the notification to be handled by the Phonegap-push-plugin. I want to know if there was an easy way to access this plugin's API methods( like hasPermissions ) safely while using a 3rd party plugin?

**Comment by macdonst** [comment]
@dagmawim if I were integrating with a PushWoosh backend I'd use their plugin:

https://github.com/Pushwoosh/pushwoosh-phonegap-plugin

Having two separate pieces of code listening for incoming push messages seems like a bad idea.

**Comment by dagmawim** [comment]
@macdonst I saw some pretty weird effects when I tried using these two plugins together. Is there anyway to use this plugin without having it listen for notifications( I only want to use the method 'hasPermission' ). If this is not possible, is there another way to check whether notifications are disabled on the user's device? Any advice is welcome!

**Comment by macdonst** [comment]
@dagmawim yeah, don't use both at the same time. If you only want to use `hasPermission` you might want to extract the code for yourself in a plugin as there is no way to only pull in one method of a plugin.
