### ISSUE TITLE
How to receive notification when app is open

### ISSUE THREAD

**Issue by beckmx** [phonegap/phonegap-plugin-push#1084]
### Expected Behaviour
Display notifiction when the app is opened

### Actual Behaviour
No notification is displayed
### Reproduce Scenario (including but not limited to)
Keep an app opened
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10
#### Cordova CLI version and cordova platform version

    cordova --version                                     6.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.7.4

#### Sample Push Data Payload
{"message"=>"msg","title"=>"coin","sound"=> "default","ios"=>{"sound"=> "default"}}

**Comment by macdonst** [comment]
@beckmx this has been discussed before in #1046 #1045 and documented over here https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#push-message-arrives-with-app-in-foreground
