### ISSUE TITLE
undefined is not an object (evaluating 'n.plugins.pushNotification.register')

### ISSUE THREAD

**Issue by ventr1x** [phonegap/phonegap-plugin-push#1085]
My xcode log shows above message when trying to init/register on startup.

I'm using ionic with Angular (+ngCordova $cordovaPushV5).
I'm currently using build.phonegap and did not try a manual build.
Yes, I am listening to device ready.

Version used:
 
PhoneGap (iOS / Android / Windows)
cli-6.1.0 (4.1.0 / 5.1.1 / 4.3.1)

phonegap-plugin-push 1.7.4

Build settings from command line:
    ARCHS = armv7 arm64
    ENABLE_BITCODE = false
    ONLY_ACTIVE_ARCH = NO

The build.phonegap log shows a high amount of "not found" warnings for the push plugin.
For example:

object file (/tmp/gimlet/*/project/*/Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(PBWireFormat.o)) was built for newer iOS version (8.3) than being linked (8.0)

while processing /tmp/gimlet/*/project/*/Plugins/phonegap-plugin-push/GCM/Libraries/libGcmLib.a(GCMAuthKeychain.o):
/var/folders/f4/lg23spf10fv19twg_lmrp8zm0045gx/C/org.llvm.clang.136701/ModuleCache/1JNUDWCYE5LC7/Darwin-MI6WZSG1PNOM.pcm: No such file or directory

/var/folders/f4/lg23spf10fv19twg_lmrp8zm0045gx/C/org.llvm.clang.136701/ModuleCache/IH0T3JNLJER8/Foundation-A3SOD99KJ0S9.pcm: No such file or directory

Is it a build.phonegap issue? 
Anyone has/had the same issue or a hint to resolve this?

**Comment by macdonst** [comment]
@ventr1x why are you looking for `n.plugins.pushNotification.register`? That's not a place where the Push Plugin is installed unless that is an Ionic thing.

**Comment by macdonst** [comment]
Closed, inactivity

**Comment by gdiodati** [comment]
I do get this error :(

**Comment by fredgalvao** [comment]
@gdiodati Would you please create a new issue with full details?

**Comment by ishan123456789** [comment]
Someone found the solution ?
