### ISSUE TITLE
how to use this plugin with phonegap build, i stuck on this from 2 days. & i am lacking the deadline of project completion. Please help

### ISSUE THREAD

**Issue by saksham09** [phonegap/phonegap-plugin-push#1088]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by jcesarmobile** [comment]
You say that you want to use it on phonegap build, but on the issue you add cordova details
What have you tried? what isn't working?

This is the doc about how to use it on phonegap build
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md

**Comment by saksham09** [comment]
i tried this also also using cordova its giving gradle error on cordova & server build error on phonegap build. Will you please elaborate how to pass those errors

**Comment by saksham09** [comment]
Oh geez. Your build failed. Sorry, but a problem occurred on the build server

Logs: FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> Error: more than one library with package name 'com.google.android.gms'
  You can temporarily disable this error with android.enforceUniquePackageName=false
  However, this is temporary and will be enforced in 1.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.505 secs

/project/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /project/gradlew with args: cdvBuildRelease,-b,/project/build.gradle,-Dorg.gradle.daemon=true,-PcdvBuildMultipleApks=false

**Comment by jcesarmobile** [comment]
cordova CLI version? cordova-android version?
plugin version?
what did you put in your config.xml to install the plugin in phonegap build?

**Comment by macdonst** [comment]
@saksham09 you have conflicting packages that use `'com.google.android.gms`. Can't really tell you more than that with the info you've provided.

**Comment by saksham09** [comment]
Push plugin is conflicting with admob plugin. How to solve? Same issue
com.google.android.gms.
How to solve?

**Comment by macdonst** [comment]
Resolution found in issue #283
