### ISSUE TITLE
XDK not including plugin in iOS build

### ISSUE THREAD

**Issue by ppetree** [phonegap/phonegap-plugin-push#1089]
### Expected Behaviour
Plugin to be included in build or build error

### Actual Behaviour
Plugin skipped - plugin shows it supports cordova versions > 3.6.3 but actually requires 4.1.0 and is built with cordova-ios 4.0.1

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
XDK v. 3400

#### Cordova CLI version and cordova platform version
5.4.1
cordova-ios 4.0.1

#### Plugin version
1.7.2

#### Logs taken while reproducing problem
Installing "phonegap-plugin-push" for ios
Running command: .../builds/build.2016-07-16.14-05-53.Z3mnpE.tmp/cordova_project/platforms/ios/cordova/version 
Command finished with error code 0: .../builds/build.2016-07-16.14-05-53.Z3mnpE.tmp/cordova_project/platforms/ios/cordova/version 
Plugin doesn't support this project's cordova-ios version. cordova-ios: 4.0.1, failed version requirement: >=4.1.0 Skipping 'phonegap-plugin-push' for ios

I documented the problem in the XDK forums as well (including screenshots):
[XDK forum post](https://software.intel.com/en-us/forums/intel-xdk/topic/669982#comment-1878349)

**Comment by macdonst** [comment]
@ppetree version 1.7.x of the plugin requires cordova-ios 4.1.x or better for your safety. There is a bug in cordova-ios 4.0.x that causes the app to freeze. The requirement for cordova-ios 4.1.0 is documented here: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PLATFORM_SUPPORT.md#supported-platforms
