### ISSUE TITLE
how to install Push Plugin in IOS

### ISSUE THREAD

**Issue by Neotrixsx** [phonegap/phonegap-plugin-push#1090]
I am new in IOS I try to install Push Plugin for my IOS app but it send error "required sender id". I am little bit confuse that in sender ID what i put.

Platform: IOS
Cordova CLI version: 5.1.1
 cordova plugin version | grep phonegap-plugin-push   :1.7.4

**Comment by macdonst** [comment]
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md
