### ISSUE TITLE
No documentation to Handle notification on click

### ISSUE THREAD

**Issue by genezablan** [phonegap/phonegap-plugin-push#1095]
Im using node-gcm to send the push notification with payload
   var message = new gcm.Message({
        contentAvailable: true,
        data : {
          articleTitle: title,
          articleId: articleId,
          icon: "ic_launcher",
          articleBody: title
        }
        ,
        notification: {
          title: title,
          articleId: articleId,
          icon: "ic_launcher",
          body: title
        }
    });

how can i handle notification on specially when the app is closed

**Comment by LightZam** [comment]
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/EXAMPLES.md

    push.on('notification', function(data) {
      // data.message,
      // data.title,
      // data.count,
      // data.sound,
      // data.image,
      // data.additionalData
    });


this event do the trick

**Comment by morris014** [comment]
cause i want to create a handler when the user click the notif i will
redirect it to a certain page im using ionic 1

**Comment by morris014** [comment]
var push = new Ionic.Push({
  "debug": true,
  "onNotification": function(notification) {
    var payload = notification.payload;
    console.log(notification, payload);
  },
  "onRegister": function(data) {
    console.log(data.token);
  }
});

**Comment by morris014** [comment]
the problem is that onNotification was not called when the notification is
received when the app is closed

**Comment by macdonst** [comment]
@morris014 first off when you are sending the push via node-gcm use the following format where everything is in the `data` object. If you put items in `notification` the Android OS takes over and the plugin code never gets fired. 

Also, how to get the notification event fired when the app is in the background is described here: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications

so your script should be:

```
var message = new gcm.Message({
data : {
  articleTitle: title,
  articleId: articleId,
  icon: "ic_launcher",
  articleBody: title
  title: title,
  body: title,
  content-available: "1"
}
});
```
