### ISSUE TITLE
IOS Push /!\

### ISSUE THREAD

**Issue by jedofus** [phonegap/phonegap-plugin-push#1098]
Hello , i have a problem with plugin , 
I can not get my token device while this plugin is implemented in my application since 1 month.
It work fine last last week.
someone has the same problem as me?

**Comment by yihyang** [comment]
Hi there @jedofus, I am currently developing using this plugin and is currently facing the same issue as you.

I am testing on my iOS app and from the logs that I retrieved I got message as follows:

```
Jul 19 20:57:21 Device[1054] <Warning>: Ionic Core: plugins are ready
Jul 19 20:57:22 Device[1054] <Warning>: Push Plugin register called
Jul 19 20:57:22 Device[1054] <Warning>: PushPlugin.register: setting badge to false
Jul 19 20:57:22 Device[1054] <Warning>: PushPlugin.register: clear badge is set to 0
Jul 19 20:57:22 Device[1054] <Warning>: PushPlugin.register: better button setup
Jul 19 20:57:22 Device[1054] <Warning>: GCM Sender ID (null)
Jul 19 20:57:22 Device [1054] <Warning>: Using APNS Notification
```

I have placed alert inside and outside *$cordovaPushV5.initialize* and it works fine, however when I placed an alert inside *$cordovaPushV5.register()* to retrieve the registrationId nothing as replied.

Are you facing the same issue?

**Comment by schankam** [comment]
I've got exactly the same issue. On iOS, the registration callback is never called.

```
      push.on('registration', (data) => {
        console.log(data.registrationId);
      });
```

The really weird thing here is that it was working for me so far, looks like I didn't change anything in my code and it suddenly stopped working... The callback was called yesterday, and today is not anymore. I tried to uninstall the plugin and install it again, does not change anything.

My bundle ID is correct, same for certificates..

Xcode output:

```
2016-07-19 21:10:40.640 App[10894:5885195] DEVICE READY FIRED AFTER 1784 ms
2016-07-19 21:10:40.656 App[10894:5885226] Push Plugin register called
2016-07-19 21:10:40.656 App[10894:5885226] PushPlugin.register: setting badge to false
2016-07-19 21:10:40.656 App[10894:5885226] PushPlugin.register: clear badge is set to 0
2016-07-19 21:10:40.656 App[10894:5885226] PushPlugin.register: better button setup
2016-07-19 21:10:40.657 App[10894:5885226] GCM Sender ID (null)
2016-07-19 21:10:40.657 App[10894:5885226] Using APNS Notification
```

I tried a lot of different things but I am out of ideas right now... Any help would be really appreciated.

I am using Ionic2, using this plugin imported via ionic-native.

I repeat, it was working yesterday and I didn't change anything (Actually, I generate new app icons...), just rebuilt my app and it stopped.

**Comment by Thomasvdam** [comment]
We're having the same issue. Yesterday it suddenly stopped working on iOS 9.3.2. However, I was able to get it to work on 8.4 on an iPhone 4s.

**Comment by yihyang** [comment]
@schankam I am having the same issues with u, managed to get it work last night 12am (GMT+8) (18/7)
But when I try to test it today I doesn't work anymore...

**Comment by gpini** [comment]
Same for me. Nothing has changed but the app does not fire the registration event.

**Comment by macdonst** [comment]
Not sure what to tell you all as there aren't many details. If your app has stopped getting a registration ID then check to see if APSN is up https://developer.apple.com/system-status/

**Comment by Thomasvdam** [comment]
When we deployed a prod version and were able to register for a device token, so my guess is that it is related to the sandbox environment.

**Comment by panaggio** [comment]
Same issue here. Yesterday the apps that use this plugin were able to register for tokens and receive push notifications, but today none happen anymore in development environment. I'm investigating the issue and will show up with more details as soon as I have them.

**Comment by hungdoan2** [comment]
Getting this issue as well, It work perfectly since this morning (over 12 hours ago UTC+7) in production environment
It working on Android but iOS. I think this issue is related to GCM sanbox.

**Comment by panaggio** [comment]
I don't use GCM and have the same issue. So if it's related to some sandbox, it should be related to APN's.

**Comment by ebarault** [comment]
i had the exact same issue all day, when suddenly it worked again. Are you guys experiencing the same thing?

for what it's worth I was using phonegap-push-plugin v1.6.4, tried with v1.7.4 (latest), then it worked, but reverted to 1.6.4 to test again, and it worked also...

2 possible explanations : 
- either something was broken in my build and removing/adding again the plugin fixed it
- or APNS sandbox was down, but it was not advertised on apple's site

if it does not work for you, try updating the plugin and retry.

@macdonst : isn't the on('error') callback supposed to fire at some point if the call to Apple's apns server times out?

**Comment by mbuschgens** [comment]
In Testflight and production this is working.

**Comment by macdonst** [comment]
Folks, I know this annoying but I don't think it has anything to do with the plugin. I believe it to be a problem with Apple's servers.

**Comment by panaggio** [comment]
> or APNS sandbox was down, but it was not advertised on apple's site

This ^

> @macdonst : isn't the on('error') callback supposed to fire at some point if the call to Apple's apns server times out?

Let's suppose this happens again, specially in production. This is a good question.

Maybe a timeout for register could help?

**Comment by usatox** [comment]
I had encountered same issue yesterday, but it works for me now with the same code.
In my case, this problem was happened in GCM Notification and iOS.

**Comment by schankam** [comment]
I am not using GCM for iOS, I am using APN. Still not working yet for me this morning.

**Comment by jedofus** [comment]
@macdonst is right, the cause was from the apple server. But the problem was apparently solved.
[https://forums.developer.apple.com/thread/52224](url)

**Comment by hungdoan2** [comment]
It's working right now, I think we can close this topic :smiley:

**Comment by panaggio** [comment]
> > or APNS sandbox was down, but it was not advertised on apple's site
> 
> This ^
> 
> > @macdonst : isn't the on('error') callback supposed to fire at some point if the call to Apple's apns server times out?
> 
> Let's suppose this happens again, specially in production. This is a good question.

I really think this issue is worth something.

> Maybe a timeout for register could help?

@macdonst if you agree, I can work on some code so that the plugin do that.

**Comment by macdonst** [comment]
@panaggio yeah, if you want to send a PR that fires an error event when registration takes too long that'd be great.
