### ISSUE TITLE
change default notification sound

### ISSUE THREAD

**Issue by wilberparedes** [phonegap/phonegap-plugin-push#1099]
#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.4.3

#### one of the solutions I found was this!
    'sound'=> 'sonido'  //it does not work at all

They say put the audio in the res / raw folder, stick it there and not work.

#### and when I send you to set the default sound, it does not work
example: 
    'sound'=> 'default' 

one of the solutions I have thought is, if there is any function that executes when the notification reaches the device

**Comment by wendellpalazzo** [comment]
@wilberparedes i have this problem too.... but i using android 4.4.4 on cyanogenmod 13.... 
i've tested in android 5.0 on moto g2 and sound works... 

Now, i dont know if is problem in android 4.4.4 or cyanogenmod.

I expect the solution too 🚨

**Comment by macdonst** [comment]
@wilberparedes did you follow the instructions on sound? https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#sound

Seems like your payload is using `sound` when I specify `soundname` but you haven't given me an example payload.

**Comment by wendellpalazzo** [comment]
@macdonst i did the instructed ... i've tested in one xaomiMI device with 4.4.4 and works ...

i suspect if exists any bug or modification on android for cyanogenmod13 to Galaxy S3 ...
only my device not works.

You can test in Galaxy S3 without cyanogenmod and using android 4.4.4?

**Comment by macdonst** [comment]
@wendellpalazzo I don't have access to a S3 running Cyanogenmod13. This code has been tested on a wide variety of Android devices and OS versions but I don't have unlimited access. Sorry if it doesn't work on that model/Cyanogen version. Perhaps if you collected some logs while reproducing the problem I might be able to help.

**Comment by wendellpalazzo** [comment]
@macdonst great! i understood

I'll look over the log ... I used the logcat to see probable errors but really the question was not playing any sound.

sending soundname:" default" or " ringtone" .. or a custom audio with name "beep" added in res / raw directory (beep.mp3).

Also added to the plugin a log to show the "sound URI " and was on the right place ..

Soon send you a log to evaluate.

Thank you for your help.....

**Comment by macdonst** [comment]
Closing inactivity
