### ISSUE TITLE
PGB (build.phonegap.com) problem

### ISSUE THREAD

**Issue by bau720123** [phonegap/phonegap-plugin-push#11]
hi @macdonst 
I am using PGB 3.7.1 (build.phonegap.com)
I know your plugin have no wp8 version for now
but it will Indirectly cause wp8 platform build fail
see my screenshot
![wp8](https://cloud.githubusercontent.com/assets/5110085/8022531/3b5b4d5a-0d0a-11e5-90e4-bea28681f231.gif)

**Comment by macdonst** [comment]
@bau720123 my apologies. I've removed the Windows configuration from the plugin.xml until it is officially supported. Please let me know if you are still encountering problems on build.

**Comment by bau720123** [comment]
hi @macdonst 
thanks your reply
but the npm page
https://www.npmjs.com/package/phonegap-plugin-push
still 1.0.0 version
I guess that you just update the git but not already update to npm
right ?

**Comment by macdonst** [comment]
@bau720123 Yeah, sorry. NPM to be updated this week.

**Comment by bau720123** [comment]
got it
thanks @macdonst
