### ISSUE TITLE
read  all notifications 

### ISSUE THREAD

**Issue by shibins** [phonegap/phonegap-plugin-push#1100]
I am sending remote  push notifications to my application and store these notification in locally in the application. Everything works fine when application is  running. But when the application is  not running and the application starts up later , is possible to read all notifications which was received when the app was not up or at least read notifications when application starts up  

Cordova CLI version and cordova platform version

 android 5.1.1
  ios 4.1.1

  phonegap-plugin-push 1.7.2 "PushPlugin"

**Comment by macdonst** [comment]
@shibins no, that's not possible. The only way to get the information into the app when it is not running is for the user to click on the notification. The only other thing you can do is use background notifications but if the user kills your app you are kinda out of luck.

**Comment by shibins** [comment]
Thanks . So  only  notification  that is clicked is read rite , not all  others in notification area

**Comment by macdonst** [comment]
Correct
