### ISSUE TITLE
Plugin ignored on installing plugins

### ISSUE THREAD

**Issue by Wouter0100** [phonegap/phonegap-plugin-push#1101]
### Expected Behaviour
Plugin is download and installed to the platform.

### Actual Behaviour
Plugin isn't downloaded nor install to the platform.

### Reproduce Scenario (including but not limited to)
* Create a new project (`phonegap create test`)
* Manually add the plugin to the `config.xml`:
```
<plugin name="phonegap-plugin-push" source="npm">
    <param name="SENDER_ID" value="<Sender ID>" />
</plugin>
```
* Add a new platform, for example android (`phonegap create android`). 

The plugin is fetched, but not added to the platform. It's also not added to the `plugins` folder nor added to the `fetch.json` in the plugins folder. Try over by removing `platforms` and `plugins` directories to ensure it isn't working.

It isn't ignored by the Phonegap Build service and works flawless there. Just for local testing it isn't working.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Cordova CLI

#### Cordova CLI version and cordova platform version
Cordova version 6.0.0

#### Plugin version
Not installed

#### Logs taken while reproducing problem
```
Discovered plugin "phonegap-plugin-push" in config.xml. Installing to the project
```
Which should look like:
```
Discovered plugin "cordova-plugin-whitelist" in config.xml. Installing to the project

Fetching plugin "cordova-plugin-whitelist@~1.2.1" via npm

Installing "cordova-plugin-whitelist" for windows
```

**Comment by Wouter0100** [comment]
Tried different types of defining in `config.xml`, resorting, GIT, and so on. None seems to work.

**Comment by Wouter0100** [comment]
Fixed by using:
```
  <plugin name="phonegap-plugin-push" spec="1.7.4">
    <variable name="SENDER_ID" value="139449204899" />
  </plugin>
```

Not sure why this works and the other's dont..

**Comment by mica16** [comment]
Same issue, the plugin installation doesn't update ios.json, I have to manually add the relevant section in "installed_plugins" to make it work. 
Besides, your solution does not fix the issue.

**Comment by macdonst** [comment]
@mica16 make sure you are using cordova-ios 4.1 or later if you are using the latest version of this plugin.

**Comment by jcesarmobile** [comment]
In fact, I think that was a cordova-ios plugin that was fixed on cordova-ios 4.2.0

**Comment by mica16** [comment]
Exact! I was using cordova-ios 4.0.1.
Upgraded to 4.2.0 and it works automatically, thanks a lot @jcesarmobile ;)

**Comment by RezaRahmati** [comment]
I had same problem, updating to ios 4.2.0 solved my issue.
`cordova platform update ios@4.2.0`
