### ISSUE TITLE
Set custom icon and custom sound to push notification

### ISSUE THREAD

**Issue by tomilenko** [phonegap/phonegap-plugin-push#1107]
Hello,

I have a problem in Ionic framework.

I can't set the notification sound and icon. I put the icon for notification to the platforms/android/res/drawable/notification_icon.png
and sound for notification to the platforms/android/res/raw/chirp1.mp3.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung, LG, Lenovo

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.2.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

#### Sample Push Data Payload
```
"notification": {
    "title": "My App",
    "message": "My message",
    "sound": "chirp1.mp3"
    "android": {
       "icon": "notification_icon.png",
  }
```

or 
```
"notification": {
    "title": "My App",
    "message": "My message",
    "sound": "chirp1.mp3"
    "android": {
         "icon": "notification_icon.png",
    }

```

#### Init code in app.js file in Ionic:
        var push = new Ionic.Push({
            "debug": false
        });

        push.register(function(token) {
            console.log("Device token:", token.token);
            LocalStorage.set('device.token', token.token)
        });

#### What I wrong do? What do I need to do for set custom sound and custom icon?

**Comment by macdonst** [comment]
@tomilenko I'm not sure about the correct payload for Ionic but if you use node-gcm scripts I provide examples:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#sound

One thing that you may want to try is to remove the .mp3/.jpg from your properties. When Android looks in it's res folders it only wants the file name, not file name plus extension.

**Comment by pritish5** [comment]
@tomilenko custom sound will play for enterprise IOS app?

```
**IOS**
"aps": {
		"alert": "Test sound",
		"sound": "sub.caf"
	}
```

**Comment by mulikiran** [comment]
very useful link for custom sounds 
https://documentation.onesignal.com/docs/customize-notification-sounds
