### ISSUE TITLE
Installation.MD has a mistake

### ISSUE THREAD

**Issue by veer0318** [phonegap/phonegap-plugin-push#1109]
So there's a small mistake in the Installation.MD file regarding the installation of the plugin, which bugged me for quite some time. In the file there's this line:

`<plugin name="phonegap-plugin-push" spec="1.6.0">
    <variable name="SENDER_ID" value="XXXXXXX" />
</plugin>`

which should be

`<plugin name="phonegap-plugin-push" spec="1.6.0">
    <param name="SENDER_ID" value="XXXXXXX" />
</plugin>`

Then it magically works again.

**Comment by macdonst** [comment]
@veer0318 wow, thought I fixed that ages ago. I just updated the docs. THanks for the heads up.
