### ISSUE TITLE
No notification in notification center when app is closed (Android)

### ISSUE THREAD

**Issue by denisjacquemin** [phonegap/phonegap-plugin-push#1111]
Hi

### Expected Behaviour
A notification sent when app is closed should be displayed in notification center

### Actual Behaviour
Nothing is displayed in notification center
Works fine when app is in foreground or background

#### Steps to Reproduce 

1. close the app
2. send a notification

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android Vesrion 5.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Asus Zenfone 2

#### Cordova CLI version and cordova platform version

    cordova --version  6.2.0                             
    cordova platform version android     android 5.1.1 

#### Plugin version

    phonegap-plugin-push 1.7.4 "PushPlugin"

#### Sample Push Data Payload

```
{
   "registration_ids":[
      "my id"
   ],
   "delay_while_idle":true,
   "data":{
      "message_id":50,
      "notId":50,
      "priority":2,
      "title":"Journée pédagogique",
      "message":"",
      "content-available":"1",
      "visibility":1
   },
   "time_to_live":86400
}
```

#### Logs taken while reproducing problem

`adb logcat | grep PushPlugin` doesn't show anything when app is closed

just fyi `adb logcat | grep PushPlugin` when app is in background

V/PushPlugin( 8807): execute: action=hasPermission
V/PushPlugin( 8807): execute: action=init
V/PushPlugin( 8807): execute: data=[{"android":{"senderID":"..."},"ios":{"alert":"true","badge":"true","sound":"true"},"windows":{}}]
V/PushPlugin( 8807): execute: jo={"senderID":"..."}
V/PushPlugin( 8807): execute: senderID=...
V/PushPlugin( 8807): onRegistered: {"registrationId":"..."}
D/PushPlugin( 8807): no icon option
D/PushPlugin( 8807): no iconColor option
D/PushPlugin_GCMIntentService( 8807): onMessage - from: ...
D/PushPlugin_GCMIntentService( 8807): normalize extras
D/PushPlugin_GCMIntentService( 8807): key = content-available
D/PushPlugin_GCMIntentService( 8807): replace key content-available with content-available
D/PushPlugin_GCMIntentService( 8807): key = message_id
D/PushPlugin_GCMIntentService( 8807): replace key message_id with message_id
D/PushPlugin_GCMIntentService( 8807): key = priority
D/PushPlugin_GCMIntentService( 8807): replace key priority with priority
D/PushPlugin_GCMIntentService( 8807): key = notId
D/PushPlugin_GCMIntentService( 8807): replace key notId with notId
D/PushPlugin_GCMIntentService( 8807): key = title
D/PushPlugin_GCMIntentService( 8807): replace key title with title
D/PushPlugin_GCMIntentService( 8807): key = message
D/PushPlugin_GCMIntentService( 8807): replace key message with message
D/PushPlugin_GCMIntentService( 8807): key = collapse_key
D/PushPlugin_GCMIntentService( 8807): replace key collapse_key with collapse_key
D/PushPlugin_GCMIntentService( 8807): key = visibility
D/PushPlugin_GCMIntentService( 8807): replace key visibility with visibility
D/PushPlugin_GCMIntentService( 8807): background
D/PushPlugin_GCMIntentService( 8807): message =[]
D/PushPlugin_GCMIntentService( 8807): title =[Journée pédagogique]
D/PushPlugin_GCMIntentService( 8807): contentAvailable =[1]
D/PushPlugin_GCMIntentService( 8807): create notification
D/PushPlugin_GCMIntentService( 8807): stored icon=null
D/PushPlugin_GCMIntentService( 8807): stored iconColor=null
D/PushPlugin_GCMIntentService( 8807): stored sound=true
D/PushPlugin_GCMIntentService( 8807): stored vibrate=true
D/PushPlugin_GCMIntentService( 8807): no icon resource found - using application icon
D/PushPlugin_GCMIntentService( 8807): create actions
D/PushPlugin_GCMIntentService( 8807): send notification event
D/PushPlugin( 8807): convert extras to json
D/PushPlugin( 8807): key = content-available
D/PushPlugin( 8807): key = message_id
D/PushPlugin( 8807): key = priority
D/PushPlugin( 8807): key = notId
D/PushPlugin( 8807): key = title
D/PushPlugin( 8807): key = message
D/PushPlugin( 8807): key = collapse_key
D/PushPlugin( 8807): key = visibility
D/PushPlugin( 8807): key = foreground
V/PushPlugin( 8807): extrasToJSON: {"title":"Journée pédagogique","message":"","additionalData":{"content-available":"1","message_id":"50","priority":"2","notId":"50","collapse_key":"do_not_collapse","visibility":"1","foreground":false}}

**Comment by handhead-dev** [comment]
i have the same issue here.

**Comment by macdonst** [comment]
@denisjacquemin can you send a push with the message property omitted? Like this:

```
{
   "registration_ids":[
      "my id"
   ],
   "delay_while_idle":true,
   "data":{
      "message_id":50,
      "notId":50,
      "priority":2,
      "title":"Journée pédagogique",
      "content-available":"1",
      "visibility":1
   },
   "time_to_live":86400
}
```

and then send one with the message property populated:

```
{
   "registration_ids":[
      "my id"
   ],
   "delay_while_idle":true,
   "data":{
      "message_id":50,
      "notId":50,
      "priority":2,
      "title":"Journée pédagogique",
      "message":"test message",
      "content-available":"1",
      "visibility":1
   },
   "time_to_live":86400
}
```

I want to narrow down the root cause/reproduction scenario.

**Comment by denisjacquemin** [comment]
first test with the following payload

- works fine with app in background or foreground
- doesn't works with app closed

```
{
   "registration_ids":[
      "..."
   ],
   "delay_while_idle":true,
   "data":{
      "message_id":50,
      "notId":50,
      "priority":2,
      "title":"Journée pédagogique",
      "content-available":"1",
      "visibility":1
   },
   "time_to_live":86400
} 
```

second test with the following payload

- works fine with app in background or foreground
- doesn't works with app closed
```
{
   "registration_ids":[
      "..."
   ],
   "delay_while_idle":true,
   "data":{
      "message_id":50,
      "notId":50,
      "priority":2,
      "title":"Journée pédagogique",
      "message":"test message",
      "content-available":"1",
      "visibility":1
   },
   "time_to_live":86400
}
```
same behaviour

**Comment by denisjacquemin** [comment]
same behaviour with the following payload

- works fine with app in background or foreground
- doesn't works with app closed

```
{
   "registration_ids":[
      "..."
   ],
   "data":{
      "title":"Only title and message",
      "message":"test message"
   }
}
```

the response

```
{
    "multicast_id": 5045685496317449000,
    "success": 1,
    "failure": 0,
    "canonical_ids": 0,
    "results": [
        {
            "message_id": "0:1469461647410824%42d621a3f9fd7ecd"
        }
    ]
}
```

**Comment by denisjacquemin** [comment]
Hi,

I created a new cordova from scratch with latest versions, and it works fine now, even when app is closed. Don't know what was the problem.

thank @macdonst for your support

**Comment by denisjacquemin** [comment]
ok, it didn't work for long

now I manage to get an error from logcat

with `adb logcat | grep intent`, only when app is closed, I get

`W/GCM-DMM ( 2424): broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=io.cordova.hellocordova (has extras) }`

the app used for testing could be found here https://github.com/denisjacquemin/sample_app_phonegap-plugin-push

I use Postman for testing, here is the payload 

```
{
   "registration_ids":[
      "..."
   ],
   "delay_while_idle":true,
   "data":{
      "message_id":50,
      "notId":50,
      "title":"test message",
      "message":"test message",
      "content-available":"1",
      "visibility":1
   },
   "time_to_live":86400
}
```

and the response

```
{
    "multicast_id": 4885439607009137000,
    "success": 1,
    "failure": 0,
    "canonical_ids": 0,
    "results": [
        {
            "message_id": "0:1469776244314931%39597f64f9fd7ecd"
        }
    ]
}
```

Do you have any insights on how I can troubleshoot deeper this issue?

**Comment by denisjacquemin** [comment]
ok, my problem is solved
The app needs to be marked as "allowed" to start in the Autostart Manager of my Asus Zenfone 2
