### ISSUE TITLE
In iOS, notification appears, but notification event is not triggered on click of notification.

### ISSUE THREAD

**Issue by NishatJahan** [phonegap/phonegap-plugin-push#1112]
Hi,
I am using APN to send push notifications to iOS.
### Expected Behaviour

On notification clicked, App should open and notifcation event handler should be triggered
### Actual Behaviour

App opens but notification event is not fired.
#### Cordova CLI version and cordova platform version

```
cordova --version                                    #  6.0.0
cordova platform version iOS                  # 4.0.1
```
#### Plugin version

```
cordova plugin version | grep phonegap-plugin-push   # 1.5.3
```
#### Sample Push Data Payload

$body['aps'] = array(
  'alert' => "test message",
  'sound' => 'default',
  'link_url' => $url,
  );
#### Sample Code that illustrates the problem

I am trying to check if notification event is triggered

push.on('notification', function(data) {
            // data.message,
            // data.title,
        document.getElementById("event"). value = "notification recieved";
            // data.count,
            // data.sound,
            // data.image,
            // data.additionalData
            alert("here");
});

**Comment by macdonst** [comment]
@NishatJahan can you give me more details on how you setup the push code?

**Comment by jcesarmobile** [comment]
you are not using latest version of the plugin, can you update and try again?

**Comment by NishatJahan** [comment]
@jcesarmobile: Sorry, my plugin version is 1.7.4. I think its the latest one

**Comment by NishatJahan** [comment]
@macdonst :  I have tried both approaches, using GCM fro iOS push notification and using APN itself.

**USING GCM:**
I have create genetared .p12 certifiacte file and uploaded it  in google developers console.
and my server code is,
<?php


// API access key from Google API's Console
define( 'API_ACCESS_KEY', 'my_api_access_key' );

$registrationIds = array("njmZeS0cZgE:APA91bHiwhJBEeKm5C_q4MsVWt_7rDkdLDPhqRVahGQiQAvTPueysRQmpXkvwPaYZZdhZpH9ITae1bSu_xp3i7QysWtFd9eBgLEWXYl2VXuv--NWiUYgr-9HRVZSd-yVkVcQmvVV21GE");
$msg = array
(
    'message'       => 'here is a message. message',
    'title'         => 'This is a title. title',
    'subtitle'      => 'This is a subtitle. subtitle',
    'tickerText'    => 'Ticker text here...Ticker text here...Ticker text here',
    'vibrate'   => 1,
    'sound'     => 1
);

$fields = array
(
    'registration_ids'  => $registrationIds,
    'notification'              => $msg
);

$headers = array
(
    'Authorization: key=' . API_ACCESS_KEY,
    'Content-Type: application/json'
);

$ch = curl_init();
curl_setopt( $ch,CURLOPT_URL, 'https://android.googleapis.com/gcm/send' );
curl_setopt( $ch,CURLOPT_POST, true );
curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fields ) );
$result = curl_exec($ch );
curl_close( $ch );

echo $result;
?>

Here the output is,
{"multicast_id":5623416507480230413,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1469511283640485%394e7de1394e7de1"}]}

But notification doesn't show up in iPhone.

**Using APN**
I have created pem file and placed in server and i have added provisioning profile in xCode. Server side code is,

<?php

// Put your device token here (without spaces):
$deviceToken = '81d3c34e9f6b9f46a160c31839b3e693239457a3e6ed54ed17aaed568f64ff74';

// Put your private key's passphrase here:
$passphrase = '';

$message = $argv[1];
$url = $argv[2];

if (!$message || !$url)
    exit('Example Usage: $php newspush.php \'Breaking News!\' \'https://raywenderlich.com\'' . "\n");

////////////////////////////////////////////////////////////////////////////////

$ctx = stream_context_create();
stream_context_set_option($ctx, 'ssl', 'local_cert', 'ck.pem');
stream_context_set_option($ctx, 'ssl', 'passphrase', $passphrase);

// Open a connection to the APNS server
$fp = stream_socket_client(
  'ssl://gateway.sandbox.push.apple.com:2195', $err,
  $errstr, 60, STREAM_CLIENT_CONNECT|STREAM_CLIENT_PERSISTENT, $ctx);

if (!$fp)
  exit("Failed to connect: $err $errstr" . PHP_EOL);

echo 'Connected to APNS' . PHP_EOL;

// Create the payload body
$body['aps'] = array(
  'alert' => $message,
  'sound' => 'default',
  'link_url' => $url,
  );

// Encode the payload as JSON
$payload = json_encode($body);

// Build the binary notification
$msg = chr(0) . pack('n', 32) . pack('H*', $deviceToken) . pack('n', strlen($payload)) . $payload;

// Send it to the server
$result = fwrite($fp, $msg, strlen($msg));

if (!$result)
  echo 'Message not delivered' . PHP_EOL;
else
  echo 'Message successfully delivered' . PHP_EOL;

// Close the connection to the server
fclose($fp);


here notification arrives, but on click of notification notification event is not triggered. it just opens up the app.

Please tell me which is the preferred method and where the problem is.

**Comment by NishatJahan** [comment]
@macdonst 

this is the plugin code in my app,

var push = PushNotification.init({ "android": {"senderID": "1022715757975", icon: "notification", "iconColor": "#43B426"},
        "ios": {"senderID": "1022715757975","alert": "true", "badge": "true", "sound": "true", "gcmSandbox": "true"}, "windows": {} } );

	
push.on('registration', function(data) {
        alert(data.registrationId);		
});  
	
push.on('notification', function(data) {
	        // data.message,
	        // data.title,
		
	        // data.count,
	        // data.sound,
	        // data.image,
	        // data.additionalData
		alert(JSON.stringify(data));
 });

push.on('error', function(e) {
	        // e.message
});

**Comment by NoNameProvided** [comment]
@NishatJahan Do you have iOS10 on your device? 

I can confirm this issue on iOS 10. With iOS9 everything was fine. On iOS10 when the app is open I get the notifications, but when the app is closed and a notification has been received, clicking on the notification will open the app, but it won't trigger the handler function.

**Comment by NoNameProvided** [comment]
I just tested on an older device, it works well there, so iOS 10 is the source of the problem.

**Comment by NoNameProvided** [comment]
I have opened a new ticket for my problem: #1228

**Comment by macdonst** [comment]
@NishatJahan can you retest with 1.8.2?

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
