### ISSUE TITLE
iOS Build Failed - library not found for -lGGLCloudMessaging

### ISSUE THREAD

**Issue by NigroDev** [phonegap/phonegap-plugin-push#1113]
### Expected Behaviour
iOS Build Successful
### Actual Behaviour
Error: 
ld: library not found for -lGGLCloudMessaging
clang: error: linker command failed with exit code 1 (use -v to see invocation)
#### Versions
X-Code: Version 7.3.1
Cordova version: 6.3.0
iOS platform version: 4.1.1

#### Plugin version
1.7.4

**Comment by NigroDev** [comment]
Is anybody here who knows why this library is missing ? No one had similar issue..?

**Comment by macdonst** [comment]
@NigroDev nope, but you can try removing and adding your ios platform and then rebuilding.

```
cordova platform rm ios
cordova platform add ios
cordova build ios
```

**Comment by NigroDev** [comment]
@macdonst 
I found missing library in files. Manual linking in X-Code (build config) helped me. :)
App is building successful, im able to get a token but device is not receiving any notification ( tested on iPad and iPhone [newest softs]) - android devices with same plugin and app's configuration work properly.

**Comment by macdonst** [comment]
@NigroDev that is usually a problem where the device is registered with the sandbox and the server is registered with production or vice versa. Can you make sure everything is matching.

**Comment by macdonst** [comment]
Closing, inactivity

**Comment by gautamc1106** [comment]
Hi guys,
I made an ionic app that uses firebase for push notifications. I installed all the required plugins for android and ios. While Android works perfectly fine, i get this error each time i build on ios

Showing Recent Issues
ld: library not found for -lGoogleToolboxForMac
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tiagocedrim** [comment]
@gautamc1106 Same problem here, Any solution?

**Comment by jcesarmobile** [comment]
You have to install CocoaPods in your machine, it should install those things.
In case it still doesn't work you can run this
```cd platforms/ios
pod install```
