### ISSUE TITLE
error in build application

### ISSUE THREAD

**Issue by cordova-android** [phonegap/phonegap-plugin-push#1114]
### Expected Behaviour
build success
### Actual Behaviour
build faild
### Reproduce Scenario (including but not limited to)
after adding command 
cordova plugin add phonegap-plugin-push --variable SENDER_ID="#####"
cordova build
error appear
"
BUILD FAILED

Total time: 4.441 secs
ERROR running one or more of the platforms: Error code 1 for command: cmd with a
rgs: /s,/c,"C:\MyAndroid\Payment_New\platforms\android\gradlew cdvBuildDebug -b
C:\MyAndroid\Payment_New\platforms\android\build.gradle -PcdvBuildArch=arm -Dorg
.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"
You may not have the required environment or OS to run this project

"
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1.1

#### Cordova CLI version and cordova platform version
cordova 6.0.0

#### Plugin version

phonegap-plugin-push   1.6.0

**Comment by jcesarmobile** [comment]
You are not using latest version of the plugin, update it and try again

**Comment by cordova-android** [comment]
what is the last version of phonegap-plugin-push

**Comment by jcesarmobile** [comment]
latest is 1.8.0 released yesterday

https://www.npmjs.com/package/phonegap-plugin-push

**Comment by cordova-android** [comment]
after install last version
Cordova plugin add phonegap-plugin-push@~1.8.0

 i get same error in build

BUILD FAILED

Total time: 3.916 secs
ERROR building one of the platforms: Error code 1 for command: cmd with args: /s
,/c,"C:\MyAndroid\Payment_New\platforms\android\gradlew cdvBuildDebug -b C:\MyAn
droid\Payment_New\platforms\android\build.gradle -Dorg.gradle.daemon=true -Pandr
oid.useDeprecatedNdk=true"
You may not have the required environment or OS to build this project

**Comment by macdonst** [comment]
@cordova-android can you build any cordova projects without the plugin?

**Comment by cordova-android** [comment]
yes

**Comment by shawnlehner** [comment]
I am getting this same error when building with this plugin. If I remove it from the config.xml them PhoneGap Build works fine and I can create the APK. As soon as I add this plugin back into the mix I get the following errors:

```
:compileDebugJava/project/src/com/adobe/phonegap/push/GCMIntentService.java:390: error: cannot find symbol
                        Log.d(LOG_TAG, "Version: " + android.os.Build.VERSION.SDK_INT + " = " + android.os.Build.VERSION_CODES.M);
                                                                                                                              
  symbol:   variable M
  location: class VERSION_CODES
/project/src/com/adobe/phonegap/push/GCMIntentService.java:391: error: cannot find symbol
                        if (android.os.Build.VERSION.SDK_INT <= android.os.Build.VERSION_CODES.M) {
                                                                                              
  symbol:   variable M
  location: class VERSION_CODES
/project/src/com/adobe/phonegap/push/GCMIntentService.java:401: error: cannot find symbol
                        if (android.os.Build.VERSION.SDK_INT <= android.os.Build.VERSION_CODES.M) {
```

**Comment by macdonst** [comment]
@shawnlehner please open a ticket with PGB to add Android N libraries to the build service or you can pin you plugin to 1.7.4. I started introducing Android N support in 1.8.0

**Comment by shawnlehner** [comment]
@macdonst Thanks for the follow-up. We are currently using version 1.7.4 as the spec version to get around this error so we will continue to do that. I just thought you might like to know that PGB users are seeing this issue and it might be something good to add as a note to the GitHub docs for this plugin.

Thanks!

**Comment by roysG** [comment]
any new fix for the version 1.8.0?

**Comment by ElliotNB** [comment]
I am experiencing this same issue with plugin version 1.8.1 as well. My build errors are the exact same as those posted by @shawnlehner.

@macdonst Do you think this will be addressed with the next release?

**Comment by mlabarca** [comment]
Issue still persisting on version >= 1.8.0

**Comment by djidel** [comment]
I had this issue using Cordova for Android@4.1.1
This workaround fixed the issue for me:

- Editing: app/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java
- commenting the lines: 451, 452, 455 to 458, 462, 465 to 468

This executes the code for my android version without checking and comparing the version.

**Comment by zivkaziv** [comment]
Hi Guys,
I'm facing the same issue here with version 1.8.4
Any advice how to solve it?
