### ISSUE TITLE
Notification doesn't show the app icon

### ISSUE THREAD

**Issue by ashishsajwan** [phonegap/phonegap-plugin-push#112]
```
var push = PushNotification.init({ 
        "android": { 
            "senderID": "123456789", "icon": "icon", "iconColor": "blue"}, 
       "ios": {}, "windows": {} 
    });
```

setting "icon" : "icon" because i have icon.png inside drawable folder ...

but on receiving notification , instead of icon, it shows white square inside a grey circle ...

@macdonst @bobeast @EddyVerbruggen

**Comment by ashishsajwan** [comment]
Here are the screen shots. .. on lock screen it shows app icon with colored background .. although i was expecting app icon to fill up all the space ..


![screenshot_2015-09-07-16-44-12](https://cloud.githubusercontent.com/assets/3591492/9715777/5e096d18-5581-11e5-958c-a2227adc2f52.png)

but once you unlock this is how it looks

![screenshot_2015-09-07-16-45-06](https://cloud.githubusercontent.com/assets/3591492/9715778/5e1340ae-5581-11e5-8516-108659219cfe.png)

**Comment by macdonst** [comment]
@ashishsajwan what you show here is proper behaviour. As of Android 5+ there are new guidelines to follow for icons. Check out: http://developer.android.com/design/patterns/notifications.html under "Use distinct icons". 

The small icon is only supposed to be white with transparency. That is why I added in the icon property for Android so you could specify the properly formatted icon.

**Comment by ashishsajwan** [comment]
but how to show colored notification icon on kitkat & user this new icon only on lolipop ??

@macdonst

**Comment by usman8806** [comment]
@macdonst, like @ashishsajwan asked, how can we show the new icon for Android 5+ but also be backwards compatible for Android versions below 5 (mainly Android versions Jelly Bean and KitKat, they still have pretty significant install numbers [Google Dashboard](https://developer.android.com/about/dashboards/index.html)).
