### ISSUE TITLE
What is server address to send notofcation for ios using apn

### ISSUE THREAD

**Issue by RezaRahmati** [phonegap/phonegap-plugin-push#1120]
Hi guys

For sending notification for android I user https://android.googleapis.com/gcm/send but I couldn't find what is the address for sending notification data for apn

**Comment by jcesarmobile** [comment]
It depends, apple allow you to use a socket or HTTP/2 and each service has a different address, read the apple docs:

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html

This is the section about HTTP/2
https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH101-SW1
