### ISSUE TITLE
LG-H815 Android show White Icons in notification bar

### ISSUE THREAD

**Issue by ramaguduri** [phonegap/phonegap-plugin-push#1122]
### Expected Behaviour
Notification should be displayed with the Image provided during the Init with Config.

{"senderID": "*****", "icon" : "push_icon", "iconColor" : "#3DC996"}

### Actual Behaviour
Notification shows up correctly in Samsung Note 4 OS 6.0.1 and Genymotion emulator with Samsung Galaxy 6 OS 5.0. But it fails to show the Icon image on LG H815 OS 6.0, instead it shows White square Icon.

Below is the screenshot of the Genymotion Emulator (Tick is the app Icon)
![image](https://cloud.githubusercontent.com/assets/5284005/17177471/324e2312-53d7-11e6-91a2-ff2883643d86.png)

### Reproduce Scenario (including but not limited to)
1] Create Cordova application with 5.4.1
2] Add android platform with 5.1.1
3] Add Push plugin and do the Init with above config.
4] Send notification from GCM.
5] This issue is happening only on LG-H815.

push_icon asset it available in 
drawable-ldpi, drawable-mdpi, drawable-hdpi, drawable-xhdpi, drawable-xxhdpi

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
LG H815 Android 6.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
LG H815

#### Cordova CLI version and cordova platform version
Cordova - 5.4.1
Android - 5.1.1

#### Plugin version
Plugin version - 1.7.0

#### Sample Push Data Payload
{"data":{"title" : "test", "info":"empty","content-available":"1","xdata":{"requestId": 11}},"time_to_live":30,"priority": "high","contentAvailable": true,"delayWhileIdle": false,"registration_ids":["****"]}

#### Sample Code that illustrates the problem
.init({"android" : {"senderID": "*****", "icon" : "push_icon", "iconColor" : "#3DC996"}})

**Comment by macdonst** [comment]
@ramaguduri what you are describing is by Android OS design. Please read over my docs on images. https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images

**Comment by ramaguduri** [comment]
@macdonst The sample screenshot with Genymotion it working as per the design. There is no issue with that.
I should have added the screenshot from LG device. I am adding them below.

![image](https://cloud.githubusercontent.com/assets/5284005/17221699/7a4b3dba-54ba-11e6-8268-27d18006d58b.png)

![image](https://cloud.githubusercontent.com/assets/5284005/17221728/969545a6-54ba-11e6-847c-ee936cde16df.png)

As I mentioned this issue is happening only on LG-H815. It works fine on Samsung Note, Samsung nexus and Genymotion emulator.

**Comment by macdonst** [comment]
@ramaguduri please read the docs I referenced. It is a change Google introduced along with Material Design. The solution is documented and many issues have been opened (and closed) with the same question.
