### ISSUE TITLE
When app is in background notification is sent to notification area

### ISSUE THREAD

**Issue by Natanael1234** [phonegap/phonegap-plugin-push#1123]
In Android, with background mode plugin, when a notification is received and the app is in background the notification is sent to system's notifications area, not to the app as when the app is open. If I don't tap the notification there or slides it to the side the notification is not sent to the app.

It the a way to send the notification directly to the app?

**Comment by fredgalvao** [comment]
Please read the docs on the notification paylod options: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md. You'll find your answer there, at the `Background Events` section.

**Comment by Natanael1234** [comment]
It says that if the app is running on background and the notification has no title, no message and content-available=1 the notification will not be shown in notification area, but instead sent directly to the app, if the app.

But it's not happening. At least in the emulator. I still receive the notification with the app in foreground, but not in background.

My notification code:
```
{
   "delay_while_idle": true,
   "priority": "high",
   "sound": "default",
   "color": "FFFF00",
   //payload   
   "data": {
       "content-available": "1",
       "somda_var": "some_value",
       "type": "msg",       
   }
}
```

**Comment by Natanael1234** [comment]
Thanks for reply, It says that if the app is running on background and the notification has no title, no message and content-available=1 the notification will not be shown in notification area, but instead sent directly to the app, if the app.

In fact, it works now. But the on notification event is called only after the app is open manually. Even if background mode is enabled. If I send a message with the app in background, the app will be notified when I open it.

My notification code:
```
{
   "delay_while_idle": true,
   "priority": "high",
   "data": {
       "content-available": "1",
       "some_var": "some_value",
       "other_var": "other_value",       
   }
}
```

**Comment by Natanael1234** [comment]
Backgroundmode plugin is a possible cause for this. It seem not to be working after I press back button or close the app via side menu.
