### ISSUE TITLE
Cordova push notification - PushNotification is not defined whenever i run the example

### ISSUE THREAD

**Issue by Mahesh3911** [phonegap/phonegap-plugin-push#1125]
I am getting Uncaught ReferenceError: PushNotification is not defined whenever i run the example..
I have installed this plugin - cordova plugin add phonegap-plugin-push
and android libraries from SDK manager  
   - Android Support Library version(obsolete) 23.2.1
   - Android Support Repository version 35
   - Google Play Services version 31
   - Google Repository version 31 

This is the line i am getting error

var push = PushNotification.init({

using Nexus HTC device
cordova --version is 6.3.0
cordova platform android version is 5.2.1

Plugin version
phonegap-plugin-push tried both 1.3.0 and 1.6.0 as well

What is the problem and how can i fix this ?

**Comment by Mahesh3911** [comment]
Issue resolved - received registration id as well.

**Comment by mattcollins171** [comment]
How did you fix it?

**Comment by Mahesh3911** [comment]
I have Re-install Android Support Library and on device ready I have called 
push method  - PushNotification.init({

For now I got registration id and working on to get notification on mobile device.
