### ISSUE TITLE
PushNotification.init is not a function for Android

### ISSUE THREAD

**Issue by phoxoey** [phonegap/phonegap-plugin-push#1126]
Works for iOS. Android, all I get is PushNotification.init is not a function. I'm calling after the device is ready. I have tried everything I can find on the subject and nothing will get it to work on Android. Not sure where to go from here.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
