### ISSUE TITLE
Installation guide states Android Support Library required although now obsolete

### ISSUE THREAD

**Issue by ltfschoen** [phonegap/phonegap-plugin-push#1128]
### Expected Behaviour
The first dot point in [Compilation section of the INSTALLATION.md](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#compilation) states that "Android Support Library version 23 or greater" should be installed via Android SDK Manager, however this library is now "Obsolete"

### Actual Behaviour
In the "Extras" folder of Android SDK Manager it is now necessary to click the "Obsolete" checkbox in order for it to display "Android Support Library (Obsolete)" Rev. 23.2.1. 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android SDK Manager v25.1.7

#### Cordova CLI version and cordova platform version
cordova 6.2.0
android 5.1.1
ios 4.1.1

#### Plugin version
phonegap-plugin-push 1.8.0 "PushPlugin"

**Comment by fredgalvao** [comment]
@ltfschoen  I've manually updated my android sdk more than once in the last  few days, and I still see the maven repositories visible as normal packages, in the `Extras` sections, without me having to check for `Obsolete` packages. Could you provide an screenshot of your sdk where it shows as an Obsolete package?

**Comment by ltfschoen** [comment]
Obsolete checkbox selected: ![screen shot 2016-08-02 at 10 03 54 am](https://cloud.githubusercontent.com/assets/6226175/17312775/9b244ea0-5898-11e6-8737-d5f418855594.png)

Obsolete checkbox unselected: 
![screen shot 2016-08-02 at 10 04 12 am](https://cloud.githubusercontent.com/assets/6226175/17312791/b991cbec-5898-11e6-82e6-98ee7385bc60.png)

**Comment by macdonst** [comment]
@ltfschoen weird, I don't have the same behaviour and I'm also running Android SDK Manager v25.1.7.

**Comment by jcesarmobile** [comment]
I'm seeing that behaviour, but I don't know which SDK Manager do I have

**Comment by fredgalvao** [comment]
Can you post the versions at the `About` section in the `Tools` menu, please?

Mine are like this:
![obs3](https://cloud.githubusercontent.com/assets/616464/17340991/f80cd274-58c8-11e6-8f0f-a16a0fff8a86.png)

Without obsolete checked:
![obs1](https://cloud.githubusercontent.com/assets/616464/17341005/06a578c2-58c9-11e6-8044-d05173d5b754.png)

With obsolete checked:
![obs2](https://cloud.githubusercontent.com/assets/616464/17341016/0f1f6ecc-58c9-11e6-8263-910134d7ddbd.png)

**Comment by jcesarmobile** [comment]
In another computer it appears as your screenshot, might be related that I had them installed from long ago?

**Comment by ltfschoen** [comment]
@fredgalvao Mine appears the same as yours ![screen shot 2016-08-03 at 10 11 07 am](https://cloud.githubusercontent.com/assets/6226175/17349601/af8a9aa0-5962-11e6-90a3-52eb2794c108.png)

**Comment by fredgalvao** [comment]
Cool, (as in not cool). I'll just update the docs saying it **can** be obsolete.

**Comment by fredgalvao** [comment]
Actually, now that I've re-read it all, I might've understood it.
@ltfschoen, could you uninstall that osbolete package and try building any application that requires any form of `com.android.support:support-vX:Y` with gradle?
If it does build successfully, it means that the `Android Support Repository` is enough to resolve all dependencies on this scope (support modules).

**Comment by macdonst** [comment]
Closing, inactivity.
