### ISSUE TITLE
PG Build - no notification after reboot

### ISSUE THREAD

**Issue by Marix1** [phonegap/phonegap-plugin-push#1130]
Hello,

i use PG Build and Firebase Notifications

In my config.xml:
  <plugin name="phonegap-plugin-push" source="npm"
     <param name="SENDER_ID" value="701132123" /
  </plugin

So, once i started the app, notification are working even the app is closed.

But after reboot notifications aren't working.

Any solution?

**Comment by macdonst** [comment]
@Marix1 yes, you have to put the sender ID in both places in order for the plugin to work. In the 2.0.0 release you won't need to pass it to init. 

The plugin currently does not support Firebase Notifications. If you provide some logs I may be able to help but you may need to wait for the 2.0.0 release for official FCM support.

**Comment by Marix1** [comment]
Ok, without init in index.html  notification only working if app running. 
If app is closed there a no notification anymore.

But the problem is after reboot

**Comment by macdonst** [comment]
@Marix1 I'm sorry, I don't understand what the actual problem is. Please provide more details as per the issue guideline.

**Comment by Marix1** [comment]
Ok,  
if i started the app once:
app is on - notifications working
app is killed - notifications working

then if i reboot or hotboot notifications are not working.

So - the user have to start the app every time he startet the phone.

My question is how can i fix this?

I can add autostart plugin - but then the app is in foreground every time.

**Comment by Marix1** [comment]
now tested on nexus 6p and marshmallow and its working after reboot - with lollipop 1/2 sometimes won't work
