### ISSUE TITLE
GCM for android, correct payload for setting priority to high

### ISSUE THREAD

**Issue by checo06** [phonegap/phonegap-plugin-push#1133]
### Expected Behaviour
All the time i send my pushnotifications they arrive at the moment they were send. I want to set priority high attribute.

### Actual Behaviour
My pushnotifications work good. Only sometimes in "Samsung Galaxy A3 2016"(newer device) pushnotifications arrive with a delay (maybe 5 minutes later). In other hand, Ive been testing . with "Samsung S3 Mini"(older device) and havent seen any delay (just have one of 1 minute) between sending and receving.
I dont know if the delay is due to priority settings in payload.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Samsung Galaxy A3 2016:  Android OS, v5.1.1 (Lollipop)
Samsung S3 mini : Android OS, v4.1 (Jelly Bean)

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy A3 2016
Samsung S3 Mini

#### Cordova CLI version and cordova platform version

cordova --version: 6.2.0
cordova platform version android: android 5.1.1

#### Plugin version

1.7.4

#### Sample Push Data Payload

Here is the core of my question. I dont know where to put the priority attribute, as per phonegap-plugin-push documentation is one way and in gcm is another way

phonegap-plugin-push:
{
    "registration_ids": ["my device id"],
    "data": {
        "title": "This is a maximum priority Notification",
        "message": "This notification should appear in front of all others",
        "content-available" : "1",
        **"priority": 2**
    }
}

gcm:
{
    "registration_ids": ["my device id"],
    **"priority" : "high",**
    "data": {
        "title": "This is a maximum priority Notification",
        "message": "This notification should appear in front of all others",
        "content-available" : "1"
    }
}

**Comment by macdonst** [comment]
@checo06 What I've documented in the [priority](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#priority-in-notifications) section is how the notification is handled once it reaches the phone. It places the notification higher or lower in the notification shade and determines whether or not it should be shown on the lock screen as per the [Android docs](https://developer.android.com/reference/android/app/Notification.html#priority).

The delay in the notification arriving on the device has nothing to do with that setting from the docs. Delays in GCM are outside the scope of the plugin.
