### ISSUE TITLE
URL re-direction if location in app is dynamic

### ISSUE THREAD

**Issue by ef33zy** [phonegap/phonegap-plugin-push#1134]
I have followed the guidelines for URL re-redirection detailed here.. [http://macdonst.github.io/push-workshop-eu/module7.html](url)
### Expected Behaviour
When a user receives a notification, on click of the notification, it should re-direct to page/location and display information relating to received notification. 
For example, the page displays YouTube videos, the first notification shows the YouTube video sent in the notification, the second notification shows the second video e.t.c.
### Actual Behaviour
Page displays the same information from the first notification. On click of every notification (after the first) it shows the YouTube video from the first notification.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1
iOS 9.3.3
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung
#### Cordova CLI version and cordova platform version
Using PhoneGap Build

#### Plugin version
phonegap-plugin-push  1.8.0

#### Sample Push Data Payload
Using PHP:
```
...
$msg = array(
	'title' => $title,
	'message' => $message_recommendation,
	'vibrate' => 1,
	'sound' => 1,
	'style' => 'inbox',
	'summaryText' => 'You have %n% notifications',
	'url' => 'videospage.html'
 );
//For Android
	$fields = array(
		'registration_ids' => $registrationIds,
		'data' => $msg,
)
//For iOS
	$fields = array(
		'registration_ids' => $registrationIds,
		'notification' => $msg,
		'priority' => 'high',
)....
```

Your help is greatly appreciated.

**Comment by macdonst** [comment]
@ef33zy how are you passing the dynamic location to the app? I see you have the `url` set to `videeopage.html` but no indication how you are sending the dynamic info nor do I see how you are handling the incoming notification. Without more info I can't give you a better answer.

**Comment by ef33zy** [comment]
@macdonst, without a programming background, this is how I've done it.
In redirecting from one page with the list of videos, I have a bridge file (`bridge.php`) in the server that acts as a 'carrier', it carries the unique id of the video from the db and 'transfers' that id to the `videospage.html` which displays that video...

Below is my on(notification):
```
    push.on('notification', function (data) {
        console.log(data.message);
        if (!data.additionalData.foreground) {
            if (devicePlatform == "ios") {
                push.getApplicationIconBadgeNumber(function (n) {
                        var number = n + 1;
                        push.setApplicationIconBadgeNumber(function () {
                            console.log('success..badge count set');
                            console.log(data.count);
                        }, function () {
                            console.log('error');
                        }, number);
                    },
                    function () {}
                );
            } else {
                cordova.plugins.notification.badge.increase();
                console.log('app not in foreground, badge increased');
            }
        } else {
            // On clicking the notification, re-direct to the page specified in the URL.
            var video = data.additionalData.url;

            function onConfirm(buttonIndex) {
                if (buttonIndex === 1) {
                    document.location.href = video;
                }
            }

            if (video) {
                console.log("URL: " + video);
                navigator.notification.confirm(
                    data.message + 'Would you like to?', // message
                    onConfirm, // callback to invoke with index of button pressed
                    'New Video', // title
            ['Sure', 'Nah, not now'] // buttonLabels
                );
            } else {
                console.log('No video link in notification');
            }
        }

        // Call finish to let the OS know we are done
        push.finish(function () {
            console.log("processing of push data is finished");
        }, function () {
            console.log('error');
        });
```

**Comment by fredgalvao** [comment]
If you're always sending `{url: "videospage.html"}`, how is that page (or the associated `bridge.php` file, if I got it right from what you said) able to differ from one video to another?

In my opinion, you should send the id with the `url` field, like this:
```js
{url: "videospage.html?v=dQw4w9WgXcQ"}
```

**Comment by ef33zy** [comment]
@fredgalvao Thanks for your suggestion. I've implemented a solution using your suggestion but slightly differently using `localStorage`.
