### ISSUE TITLE
PhoneGap Build error

### ISSUE THREAD

**Issue by circleride** [phonegap/phonegap-plugin-push#1138]
PhoneGap Build error 

> Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: GCMIntentService.java

Plugins in config.xml:

Plugin	Source	Version	Installed	Latest	Platforms
cordova-plugin-battery-status   	npm	*	1.1.2	n/a	android,ios,winphone
cordova-plugin-camera   	npm	*	2.2.0	n/a	android,ios,winphone
cordova-plugin-console   	npm	*	1.0.3	n/a	android,ios,winphone
cordova-plugin-contacts   	npm	*	2.1.0	n/a	android,ios,winphone
cordova-plugin-customurlscheme   	npm	*	4.2.0	n/a	android,ios,winphone
cordova-plugin-device   	npm	*	n/a	n/a	android,ios,winphone
cordova-plugin-device-motion   	npm	*	1.2.1	n/a	android,ios,winphone
cordova-plugin-device-orientation   	npm	*	1.0.3	n/a	android,ios,winphone
cordova-plugin-dialogs   	npm	*	1.2.1	n/a	android,ios,winphone
cordova-plugin-file   	npm	*	n/a	n/a	android,ios,winphone
cordova-plugin-file-transfer   	npm	*	1.5.1	n/a	android,ios,winphone
cordova-plugin-flashlight   	npm	*	3.0.0	n/a	android,ios,winphone
cordova-plugin-geolocation   	npm	*	2.2.0	n/a	android,ios,winphone
cordova-plugin-globalization   	npm	*	1.0.3	n/a	android,ios,winphone
cordova-plugin-googlemaps   	npm	*	1.3.9	n/a	android,ios,winphone
cordova-plugin-inappbrowser   	npm	*	1.4.0	n/a	android,ios,winphone
cordova-plugin-media   	npm	*	2.3.0	n/a	android,ios,winphone
cordova-plugin-media-capture   	npm	*	1.3.0	n/a	android,ios,winphone
cordova-plugin-network-information   	npm	*	1.2.1	n/a	android,ios,winphone
cordova-plugin-statusbar   	npm	*	2.1.3	n/a	android,ios,winphone
cordova-plugin-vibration   	npm	*	2.1.1	n/a	android,ios,winphone
cordova-plugin-whitelist   	npm	*	1.2.2	n/a	android,ios,winphone
cordova-plugin-x-socialsharing   	npm	*	5.1.1	n/a	android,ios,winphone
de.appplant.cordova.plugin.background-mode   	pgb	0.6.4	0.6.4	0.6.4	android,ios,winphone
hazems-cordova-plugin-sms   	npm	*	0.0.2	n/a	android,ios,winphone
phonegap-plugin-barcodescanner   	npm	*	6.0.1	n/a	android,ios,winphone
phonegap-plugin-push   	npm	*	1.8.0	n/a	android,ios,winphone

Can you help me?

(sorry, bad english :( )

**Comment by macdonst** [comment]
@circleride the build team has asked me to re-direct people to https://forums.adobe.com/community/phonegap/build in order to get their questions answered.
