### ISSUE TITLE
Sending custom pictures on iOS.

### ISSUE THREAD

**Issue by lavarith** [phonegap/phonegap-plugin-push#1139]
I'm using the latest version of phonegap and phonegap-plugin-push. Are sending custom pictures (like you can in Android) supported on iOS? If so, how?

According to:
https://developer.apple.com/ios/human-interface-guidelines/features/notifications/
some sort of detail view should be possible?

Thanks!

**Comment by macdonst** [comment]
@lavarith not currently possible as I would need to build detailed views for each type of notification. More than happy to receive pull requests on this functionality though.

**Comment by lavarith** [comment]
Any suggestions on understanding the ins and outs of phonegap plugins? I'd happily add a detail view that mirrors the Android functionality, at the very least.

**Comment by lavarith** [comment]
May be bitting off a bit more than I can chew here. Programming in C is a bit outside my wheelhouse. I'll probably come back to this a bit later.

**Comment by macdonst** [comment]
No problem, thanks for looking at it.

**Comment by lavarith** [comment]
Worth noting:
[](http://stackoverflow.com/questions/37839171/how-to-display-image-in-ios-push-notification)

**Comment by macdonst** [comment]
I did some work over on #1347 so I'm going to close this as a duplicate.
