### ISSUE TITLE
Issue Related to Badge and notification bar - Notification title and text

### ISSUE THREAD

**Issue by bhuvneshg21** [phonegap/phonegap-plugin-push#1143]
Expected Behaviour

Push notification without sound on foreground and in notification bar if app is not running with message and application name with sound. Like -
**App  Name
you have push Notification**

Badge should get clear when app will open.

Actual Behavior

Foreground - Push notification is appearing as expected without sound

**Background - I'm getting two types of notification - Either with application name or with the text which I'm pushing from server.(Please see the image) 
When Notification is coming with app name at that time sound is also coming.But when it is coming with message , Phone is only vibrating sound is not coming some times it is not vibrating also. 
When it is coming with application name it is appending in notification bar (as In Image) but when it is coming with message it is overwriting the previous one.** 

**Badge - It is appearing properly on application Icon as per my requirement but it is not getting clear same as -> Badge is shown on iOS even though it was not configured #1141**

Reproduce Scenario (including but not limited to)

I have followed the following tutorial and used the same coding as in this tutorial.
http://phonegappro.com/tutorials/apache-cordova-phonegap-push-notification-tutorial-part-2/

Steps to Reproduce

```
cordova create test com.test.testapp testapp
cordova plugin add phonegap-plugin-push --variable SENDER_ID="721393051486(I used my Sender Id)"
cordova platform add android.
```

Import project in android studio, and added required coding.
the following code I have added at a particular user action (eq: - After successful login) -

```
document.addEventListener("deviceready",onDeviceReady,false);
function onDeviceReady(){
console.log("Device Ready")
var push = PushNotification.init({ "android": {"senderID": "721393051486"},
"ios": {}, "windows": {} } );

push.on('registration', function(data) {
console.log(data.registrationId);
});

push.on('notification', function(data) {
alert(data.title+" Message: " +data.message);
});

push.on('error', function(e) {
console.log(e.message);
});
}
```

Platform and Version (Android 4.2 )

(Android) What device vendor (e.g. Samsung, HTC, Sony...)

Samsung Tab

Cordova CLI version and cordova platform version

cordova --version - 6.3.0
cordova platform version android # e.g. 5.2.1

Plugin version

cordova plugin version | grep phonegap-plugin-push   - . 1.8.0
Sample Push Data Payload

I'm sending push notification from POSTMAN  using SAP HCPms Connection URL and Connection ID.

**Header in Postman  (POST CALL)-**
authorization: Basic YXNsdfsdasdfsaTAdfajc2dfa==
X-SMP-GCM-DATA: TEST NOTIFICATOIN

**Body -** 
```
{
 "alert": "test push notification Pending approval",
  "badge": 5,
 "data": "testData",
 "sound": "soundval"
}
```

**Response-**
Stautus - 201 - Created.
(And some other information)

Sample Code that illustrates the problem

Logs taken while reproducing problem
![screenshot_2016-08-03-15-03-45 1](https://cloud.githubusercontent.com/assets/20182616/17391184/3cab0b8c-5a25-11e6-9ebe-8cf035a1c95a.png)

**Comment by macdonst** [comment]
@bhuvneshg21 wow, you have a conflagration of issues here which I will attempt to address. First, I believe most of the problems you are running into are because the push data you are sending is not in the correct format for Android. I extensively document all of the [various payload options](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md). You should read that over and you'll see the basic Android push payload should look like:

```
{
    "data": {
        "title": "Large Icon",
        "message": "Loaded from drawables folder"
    }
}
``` 

That is how you will get a title and body in your notification shade.

If you don't want the last push to be replaced you need to provide a [notification ID](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#stacking).

Your badge isn't being cleared as that option is [default by false](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#android). 

So, please read over the docs I've linked to and let me know if it resolves your issues.

**Comment by bhuvneshg21** [comment]
@macdonst Thanks a lot for your immediate response.
I have gone through with all the links provided in your reply. It was realy helpful.
I want to make few points here.
As per my Understanding of the following documnet provided by SAP. We have very only one option for payload. 
https://help.hana.ondemand.com/hana_cloud_platform_mobile_services/frameset.htm?aaec2dbe78ec4fc08ef0a605a899e3dd.html
To resolve the Issue, I have done nothing I just changed the header and body(Payload) in POSTMAN.
Now I'm sending -
 **-  HEADER -
content-type :application/json,
cache-control: no-cache,
authorization :Basic YXNoa2FyY
 -  BODY -
{
 "alert": "You have a pending Approval1",
 "data": "Data",
 "sound": "default",
 "badge": "1"
}**

The Issue still  I'm facing is,  the very first notification is coming with application name (means with no message). Afterwards it is coming fine(With Title,message,sound).
Could you please put some light, What may be the issue.

**Comment by macdonst** [comment]
@bhuvneshg21 well you are sending the push through SAP so I'm not too sure what they could be doing to the payload and I don't have time to test something like that. Seems like something SAP support could help with. 

That being said try the following two thing, 1) use one of the node-gcm scripts I have provided in the PAYLOAD.md section to test the behaviour and 2) run `adb logcat | grep PushPlugin` to gather some logs while testing via SAP and let me see what actually shows up on the device.

**Comment by bhuvneshg21** [comment]
Dear @macdonst , I got stuck with a high priority issue, that's why not getting time to test or capturing logs. But definitely I'll do . After that I'll open this issue again.
Thanks for your valuable help.
