### ISSUE TITLE
Error 401 HTTPS Google when trying to register iOS device

### ISSUE THREAD

**Issue by MateusTeles** [phonegap/phonegap-plugin-push#1144]
## Expected Behaviour

My code works normally when sending a message by Firebase, and the api of the same on any device that I have registered with Android, I can receive messages without problems.
But when I try to register an iOS device on the same happens this error, I configured the IOS Push certificates and etc.

### Actual Behaviour

Cant register ios device using Firebase.

#### Cordova CLI version and cordova platform version

    cordova --version 6.0.0
    cordova platform version ios  4.1.0

#### Plugin version

    cordova plugin version   # e.g. 1.8.0

#### Sample Push Data Payload

When i try to register a IOS device, i just got this error on my alert:

The operation couldnt be completed.( com.google.HTTPStatus.error.401.)

#### Sample Code that illustrates the problem

My cod works fine, because on android i can send a message using Firebase 

```
  function ativaPush(){
    var push = PushNotification.init({
        android: {
            senderID: "google_project_id",
            alert: "true",
            badge: 'true',
            sound: 'true',
            clearNotifications: 'true',
            vibrate: 'true',
            topics: ['topic']
        },
        browser: {
            pushServiceURL: 'http://push.api.phonegap.com/v1/push'
        },
        ios: {
            alert: "true",
            badge: true,
            sound: 'true',
            vibrate: 'true',
            senderID: "google_project_id",
            gcmSandbox: true
        },
        windows: {}
    });
```

One thing, I realized that this is due to some setting in XCode or perhaps in code, what would be the correct way to perform this configuration in relation to Push certificates in Xcode / iOS?

And there is a change in relation to how to set up the project using Firebase?

**Comment by macdonst** [comment]
@MateusTeles we don't officially support FCM at this point. Please track #929.

**Comment by MateusTeles** [comment]
Is there any deadline when it will support FCM? Or a way that i can use FCM with the plugin?

**Comment by macdonst** [comment]
@MateusTeles no deadline set, it is a volunteer effort and one of my top contributors just got married so he's off for a couple of weeks.
