### ISSUE TITLE
IOS Dont show any notification

### ISSUE THREAD

**Issue by MateusTeles** [phonegap/phonegap-plugin-push#1145]
### Expected Behaviour

IOS receive push message as Android

### Actual Behaviour

IOS did not get any message, but the cell is recorded normally and the message is sent.

### Reproduce Scenario (including but not limited to)

I sent several messages for both IOS devices, the android, and the return I have is that all messages have been sent, but in the case of IOS no notification is displayed.

I have performed all of the project configuration in the GMC sending all certificates and etc, what could this be?

#### Cordova CLI version and cordova platform version

cordova --version 6.0.0
cordova platform version ios  4.1.0

#### Plugin version

cordova plugin version   # e.g. 1.8.0

#### Sample Push Data Payload

Android show push as expected, but on ios its doents show nothing.

#### Sample Code that illustrates the problem

    var push = PushNotification.init({
        android: {
            senderID: "gcm_id",
            alert: "true",
            badge: 'true',
            sound: 'true',
            clearNotifications: 'true',
            vibrate: 'true',
            topics: ['topic']
        },
        browser: {
            pushServiceURL: 'http://push.api.phonegap.com/v1/push'
        },
        ios: {
            alert: "true",
            badge: true,
            sound: 'true',
            vibrate: 'true',
            senderID: "gcm_id",
            gcmSandbox: false
        },
        windows: {}
    });

Is there any configuration that im forgetting on ios or gcm?

**Comment by fredgalvao** [comment]
You didn't include the part where you show us how you sent the payload to iOS/Android. That's a very important information for us to be able to investigate/reproduce/help.

**Comment by MateusTeles** [comment]
Ok, this is the part where i construct my message:

**//generic php function to send GCM push notification**

function sendPushNotificationToGCM($registatoin_ids, $message, $title, $image, $id, $style, 
$summaryText, $ledcolor,$vibrationPattern) {

**//Google cloud messaging GCM-API url**

$url = 'https://android.googleapis.com/gcm/send';

$fields = array(
           'registration_ids' => $registatoin_ids,
           "data" => array(
	  "title" => $title,
	  "message" => $message,
	  'msgcnt' => count($message),
         "image" => $image,
         "notId" => $id,
         "style" => $style,
         "summaryText" => $summaryText,
         "ledColor" => $ledcolor,
         "actions" => $actions,
         "vibrationPattern" => $vibrationPattern,
         "content-available" => "1",  
	 'timestamp' => date('Y-m-d h:i:s')
	  )
);

I got the registration ids from a txt, where i got a ios id and a android id.

And here is the part where i set my server for send:

// Google Cloud Messaging GCM API Key

define("GOOGLE_API_KEY", "Google Server Key");

The problem is that, when i try to send a message i got the return of sucess on it, and i receive it on android, but on ios, i get a valida hash to my device, but the device just dont receive nothing. But on android, i receive the messages normally.

Is there anything that i need to change on my api, or in my project on the ios related to the provisioning files or to the sandbox?

And there is the part related to the ios on my app:

ios: {
         alert: "true",
         badge: 'true',
         sound: 'true',
         vibrate: 'true',
         senderID: "google project id",
         gcmSandbox: true,
         topics: ['testeTopico']
},

I have set both production, and development Provisioning files for the project.

**Comment by MateusTeles** [comment]
My real problem is how to configure my server to send messages to the ios, since in the case of android I send the url: **https://android.googleapis.com/gcm/send** in the case of ios would be necessary to change something about it? Since I can register both devices normally, and send the message to both, but to receive messages only android gets them.

What would be the correct way to set this up in relation to the ios? The device I'm testing an Iphone 4s in the latest version of ios.

**Comment by MateusTeles** [comment]
I realized these changes, and managed to send this way, though I still do not get the messages on the Iphone 4S, which would be the correct way to use the GCM Sandbox, considering that I upei both production and development certificates?

PS: here is my ios config on my app:

```
        ios: {
            alert: "true",
            badge: 'true',
            sound: 'true',
            vibrate: 'true',
            senderID: "google-project-id",
            gcmSandbox: 'true'
        }
```

**Comment by MateusTeles** [comment]
I managed to receive notifications on iOS, with my open application on the page that has the **`push.on ('notification', function (data) {}),`** but still can not create a push notification with a closed application, which will be my problem?

**Comment by MateusTeles** [comment]
I found the problem I was having, and in the end lacked declare a priority for notification, but one problem I found was the lack of documentation on specific platforms.

Here's my code for sending messages, and functional on iOS / Android:

```
`        $fields = array(
            'registration_ids' => $registatoin_ids,
            "priority" => "high",
            "notification" => array( // see here, I changed from data to notification, this will make it work on ios
              "title" => $title,
              "body" => $body,
              "click-action" => $clickaction
              // "content-available" > 1
              )
        );`
```

And i set GCMSandox as true, and uploaded both certs. ;)

**Comment by fredgalvao** [comment]
@macdonst I remember seeing quite a few issues mentioning the need to specify this `priority` field on the payload recently. Is it reasonable to add it to the docs too? Is the problem somewhere else? This might be worth investigating, to barrier us from a few of those "I can't get notifications on iOS" issues.

**Comment by macdonst** [comment]
@fredgalvao yeah, go ahead and add it. The whole GCM on iOS has been a problem since day one. I hope things are much cleaner in FCM which I hope to get on next week. Been on vacation!
