### ISSUE TITLE
PG Build - no notification aon iOS 

### ISSUE THREAD

**Issue by Marix1** [phonegap/phonegap-plugin-push#1146]
I build with PG Build.

App on Android is working.  Now im testing for ios.
My ios app shows the gcm id - but no notifications are working.
After installation ios ask on permission for notification that i granted.

And i build the app with "iOS Development" certificate.

Have i build with "APNs Development iOS" certificate??

**Comment by macdonst** [comment]
@Marix1 the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
