### ISSUE TITLE
Android and icons during push notification in Marshmallow

### ISSUE THREAD

**Issue by pliablepixels** [phonegap/phonegap-plugin-push#1148]
### Expected Behavior
Should show my custom notification icon

### Actual Behavior
I am running Android 5.0 - works well for me. Several users who are on marshmallow are reporting icons are not being shown during push

### Reproduce Scenario (including but not limited to)

A push notification is received, a beep is heard, but no icon on sys tray for some users (works for me)
(one sample user report is [here](https://github.com/pliablepixels/zmNinja/issues/279))

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

I have Android 5.0, on a Moto E - works well. Other folks on 6.0 are saying there is no sys tray icon.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

One of the devices is a nexus 5

#### Cordova CLI version and cordova platform version

cordova version 6.1.1
platform version 5.1.1

I think I've followed the [guidelines](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images).

My init code is as follows:
```
push = PushNotification.init(

                        {
                            "android": {
                                "senderID": zm.gcmSenderId,
                                "icon": "ic_stat_notification",
                                "sound":"true"
             
                            }
                        }

                    );
```

The icons are generated using https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_stat_example 

The generated icons are as follows (they are white with  transparencies)
https://drive.google.com/file/d/0B3iQz0D8vxltRG5jYldwczNURU0/view?usp=sharing

Am I missing something? Has something changed?

Thank you.

**Comment by macdonst** [comment]
@pliablepixels I have two Android M phones and I've never seen this before. If you can get some logs that would be great.

**Comment by pliablepixels** [comment]
@macdonst thanks - I'll update this thread as soon as a I get something

**Comment by pliablepixels** [comment]
@macdonst - I tried pushplugin on a 6.0 emulator (with google APIs) and it seems to be working for me. 
https://github.com/pliablepixels/zmNinja/issues/279#issuecomment-238118411

Can you take a look at the PushPlugin logs in that comment and let me know if you see anything abnormal that might be causing issues on other devices?

**Comment by pliablepixels** [comment]
I am closing this - the folks reporting this issue haven't gotten back, so no point in keeping this open. I'll re-open if I get any tangible data from them. Thanks!
