### ISSUE TITLE
open app from app icon 

### ISSUE THREAD

**Issue by jedofus** [phonegap/phonegap-plugin-push#1149]
Hello , i have a problem , maybe i use your older plugin .
When i received push notification and i click on notification bar , i can get my notification and get my additionnal data .
But when i received push notification and i click on logo of my app , the plugin is init and i can't get my additionnal data.
How can i resolved it ?

**Comment by macdonst** [comment]
@jedofus what you are describing is the expected behaviour. The notification event does not get called unless the user interacts with the notification. Alternatively, you can use background notifications which are documented.
