### ISSUE TITLE
On Android, unable to get background notification and notification title to work at the same time.

### ISSUE THREAD

**Issue by striche2** [phonegap/phonegap-plugin-push#1151]
### Expected Behaviour
Sending the following json payload, while the app is in the background or closed entirely, I would expect to see a notification appear in the notification tray displaying both a title and a message. When I click the notification I would expect the app to open, and execute the on('notification') event.

```
{
     "registration_ids": ["some id", "some other id"],
     "data": 
     {
          "title": "My Title",
          "message": "My test message.",
          "content-available": "1"
      }
}
```

### Actual Behaviour
The notification in the notification tray displays the message, but not the title. The on('notification') DOES fire as expected.

If I try to send either of the following alternate payloads, the notification appears in the notification tray with both title and message, but when the notification is clicked and the app opens, the on('notification') event does NOT fire.

Example 1:
```
{
	"registration_ids":["some id", "some other id"],
	"notification":{
		"title":"My Title",
		"body":"My message.",
		"content-available":"1"
	}
}
```

Example 2:
```
{
	"registration_ids":["some id", "some other id"],
	"notification":{
		"title":"My Title",
		"body":"My message."
	},
	"data":{
		"title":"My Title",
		"message":"My message.",
		"content-available":"1"
	}
}
```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
ASUS Nexus 7

#### Cordova CLI version and cordova platform version

    cordova --version                          6.3.0
    cordova platform version android           5.2.1

#### Plugin version
Tried with both 1.5.3 and 1.8.1

**Comment by macdonst** [comment]
@striche2 the first way:

```
{
     "registration_ids": ["some id", "some other id"],
     "data": 
     {
          "title": "My Title",
          "message": "My test message.",
          "content-available": "1"
      }
}
```

is the correct way to send the data.

Can you run `adb logcat | grep PushPlugin` while reproducing the problem so I can see the logs?

**Comment by striche2** [comment]
It looks like we've never actually been sending a title. I believe in the two "alternate" examples, it was just using the app's name and not a title we'd actually been sending.
