### ISSUE TITLE
[doc] Explain usage of the top level `priority` in GCM notifications

### ISSUE THREAD

**Issue by fredgalvao** [phonegap/phonegap-plugin-push#1155]
As partially discussed in #1145 and in some other issues, it seems like background notifications need to have the top-level `priority` field maxed out (`{"priority": "high"}`) in the payload for GCM to be able to consistently wake the service up and trigger the necessary code. This affects iOS more than Android, according to the number of issues created relating that field with iOS malfunctioning.

Documentation on that field is located subjectively [here](https://developers.google.com/cloud-messaging/concept-options#setting-the-priority-of-a-message) and objectively [here](https://developers.google.com/cloud-messaging/http-server-ref#priority).

A new section named **GCM priority on background notifications** is to be created as child of both sections related to this on the docs ([android](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications) and [ios](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications-1)).

### However,

there is already mention of a use case of the inner `priority` field [in the docs](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#priority-in-notifications), but with a different sintax and possible values \[-2,-1,0,1,2\] vs \["normal","high"\] (and most probably different behaviour). So, should we remove the current one and document only the GCM version? Should we keep both, and if yes, how do we differ from one another in behaviour?

**Comment by macdonst** [comment]
@fredgalvao there are two different priorities. One to tell GCM how quickly it should attempt to deliver the message, that one is described here: https://developers.google.com/cloud-messaging/http-server-ref#downstream-http-messages-json

The second priority is to tell Android where to put the notification in the notification shade which is described here: https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html#setPriority(int)

So both are needed but it is confusing.
