### ISSUE TITLE
iOS 7.1.2 fails :(

### ISSUE THREAD

**Issue by circleride** [phonegap/phonegap-plugin-push#1156]
After the August 3rd update when the Build Service updated to cli 6.3.0 my apps haven't been working for iOS, I have an iPhone 4 running iOS 7.1.2 and an iPad running iOS 9.3.3. After the build service update, no matter if I specify a lower cli version, on the iPhone it asks for a newer software when I try to install from iTunes, but both the iPhone and iTunes are running on the latest version. On the iPad it does install, but the app's icon doesn't appear on the iPad so I can't access to the application.

**Comment by macdonst** [comment]
@circleride sorry, this plugin does not support iOS 7.

**Comment by circleride** [comment]
What version number supports iOS 7?
