### ISSUE TITLE
Picture size rule ?

### ISSUE THREAD

**Issue by fluidz91** [phonegap/phonegap-plugin-push#116]
Hi,

Is there a size rule (Width x Height) using parameter 'Picture' to display a large picture in notification ?
I have tried it on a Nexus 5 and Galaxy Tab 10.1 and the cat picture given in the example is truncated.
I managed to find something acceptable in Nexus 5 (512x285), but still not displaying correctly in the Samsung tablet.
Thanks for any clue.

**Comment by macdonst** [comment]
@fluidz91 The image is 256dp high and it is center cropped.
