### ISSUE TITLE
Problem to build iOS on phonegap build missing SENDER_ID

### ISSUE THREAD

**Issue by zubus** [phonegap/phonegap-plugin-push#1164]
Hello, I can't build my iOS project on phonegap build, this is the log of error:

> Fetching plugin "cordova-plugin-statusbar@~2.1.3" via npm
Installing "cordova-plugin-statusbar" at "2.1.3" for ios
"plugman install --platform ios --project /project --plugin phonegap-plugin-push@~1.8.0": Fetching plugin "phonegap-plugin-push@~1.8.0" via npm
Installing "phonegap-plugin-push" at "1.8.1" for ios
Failed to install 'phonegap-plugin-push':Error: Variable(s) missing: SENDER_ID
    at /usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:362:23
    at _fulfilled (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
Variable(s) missing: SENDER_ID

**Comment by macdonst** [comment]
@zubus did you follow the instructions to include the plugin in PGB?

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md#including-the-plugin

**Comment by zubus** [comment]
@macdonst I have this on confix.xml:

`<plugin name="phonegap-plugin-push" source="npm">
        <variable name="SENDER_ID" value="123456789" />
    </plugin>`

My project is only iOS, using as a base the push template (it work fine with de phonegap APP) and delete all Android parts.

*Excuse my English

**Comment by ef33zy** [comment]
@zubus Try using `param` instead of `variable` as described in the link @macdonst sent above

```
<plugin name="phonegap-plugin-push" source="npm"> 
        <param name="SENDER_ID" value="123456789" /> 
</plugin>
```

**Comment by wildabeast** [comment]
FYI `variable` should be working on PhoneGap Build again now, interchangeable with `param`.
