### ISSUE TITLE
android ionic push ----TIMEOUT  

### ISSUE THREAD

**Issue by yywai** [phonegap/phonegap-plugin-push#1165]
I build a new project(android) accorrding to http://docs.ionic.io/docs/push-full-setup.

but when i run android,an error occured:

```
**Ionic Push: (debug) unexpected error occured.
Ionic Push: TIMEOUT**
```

the detail in the console 

```
**Ionic Push: Error: TIMEOUT
at fail (file:///android_asset/www/plugins/phonegap-plugin-push/www/push.js:57:49)
at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:295:52)
at processMessage (file:///android_asset/www/cordova.js:1081:17)
at processMessages (file:///android_asset/www/cordova.js:1104:9)
at pollOnce (file:///android_asset/www/cordova.js:973:9)
at pollOnceFromOnlineEvent (file:///android_asset/www/cordova.js:960:5)
i.value @ ionic.io.bundle.min.js:2
e @ ionic.io.bundle.min.js:3
PushNotification.emit @ push.js:217
fail @ push.js:58
cordova.callbackFromNative @ cordova.js:295
processMessage @ cordova.js:1081
processMessages @ cordova.js:1104
pollOnce @ cordova.js:973
pollOnceFromOnlineEvent @ cordova.js:960**
```

```
**nativeapiprovider.js**-------------the deepest place i can find.yeah,"TIMEOUT" error born in the call of get:function() in another place.
```

```
var nativeApi = this._cordovaNative || require('cordova/android/promptbasednativeapi');
var currentApi = nativeApi;

module.exports = {
    get: function() { return currentApi; },
    setPreferPrompt: function(value) {
        currentApi = value ? require('cordova/android/promptbasednativeapi') : nativeApi;
    },
    // Used only by tests.
    set: function(value) {
        currentApi = value;
    }
};
```

i suspect that it is caused by network
thanks in advance.

(this is my first time to use this github,so sorry that i can make my text nice-looking.... and my english is not
"nice-looking" too :P)

**Comment by macdonst** [comment]
@yywai what version of Android are you testing this on?

**Comment by yywai** [comment]
@macdonst the targetSdkVersion="23" , 
 in PROJECT_PATH\platforms\platform.json   ,it has "android": "5.2.1"
thanks for your help :D

**Comment by macdonst** [comment]
@yywai what version of Android is the device that are you testing this on?

**Comment by yywai** [comment]
@macdonst API 19,  android 4.4 . should i use the device with android 6.0+?

**Comment by yywai** [comment]
> Got JSON Exception TIMEOUT
> 
> If you run this plugin on older versions of Android and you get an error:
> 
> E/PushPlugin(20077): execute: Got JSON Exception TIMEOUT
> It means you are running an older version of Google Play Services. You will need to open the Google Play Store app and update your version of Google Play Services.


OMG,i saw  this in the documention...how careless i am!!!!!!!!!
anyway,thank you !

**Comment by macdonst** [comment]
@yywai did it get resolved for you?
