### ISSUE TITLE
Push not working on android 6.0.1 

### ISSUE THREAD

**Issue by aniljailta** [phonegap/phonegap-plugin-push#1167]
### Expected Behaviour

Notification  should have worked as it is working in other android versions 

### Actual Behaviour

Looks like notification are not coming on 6.0.1 android version . 
push.on('notification') never get called , though it works for android 5.x and then 4.x version .
though token is getting saved . so push.on('registration') works fine 

#### Steps to Reproduce 

Install 1.7.2 or latest version and check build on android 6.0.1

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android version 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Samsung note 5 (upgraded to 6.0.1) and MOTO G4.

#### Cordova CLI version and cordova platform version

    cordova --version   : "6.3.1"                                 # e.g. 6.0.0
    cordova platform version android     : "5.2.1"                # e.g. 4.1.1

#### Plugin version

    1.7.2 , also tried with latest one too .

#### Sample Push Data Payload

//using some plugin , included half of it 
                    $message = array(
					'badge' => 1,
					'title' => 'New Request',
					"priority"=> 2,
					"notId" =>str_random(3),
					"content-available"=>"1", 
					);

//update : push payload that i receive in other versions

{"message":" Test message","count":"1","additionalData":{"collapse_key":"do_not_collapse","foreground":true,"google.message_id":"0:1471556738743869%fcbbe173f9fd7ecd","coldstart":false,"custom":{"notId":"0oW","state":"app.requestedvalet","priority":2}},"title":"Vehicle retrieval request"}

#### Sample Code that illustrates the problem
            document.addEventListener("deviceready", function() {

                var push = PushNotification.init({
                    android: {
                        senderID: GCM_SENDER_ID,
                        icon: "icon",
                        badge: 'true',
                        sound: 'true',
                        alert: 'true',
                    }
                });

                push.on('registration', function(data) {

                    console.log(data);

                    NodePushServer.storeDeviceToken("android", data.registrationId);
                    // data.registrationId
                });

                push.on('notification', function(data) {
                       console.log(data);
                });

                push.on('error', function(e) {
                    console.log(e);
                    // e.message
                });
            }, false);

**Comment by macdonst** [comment]
@aniljailta well I have multiple phones running Android 6 so I don't think that is the problem. The payload you sent seems weird. Can you give me more details surrounding how you send that payload? Does `$message` show up in the `data` or `notification` part of the push to GCM?

Also, running `adb logcat | grep PushPlugin` really helps debug things.

**Comment by aniljailta** [comment]
@macdonst Oops , my bad , i am using laravel for this , have used some plugin , included half of it . 

{"message":" Test message","count":"1","additionalData":{"collapse_key":"do_not_collapse","foreground":true,"google.message_id":"0:1471556738743869%fcbbe173f9fd7ecd","coldstart":false,"custom":{"notId":"0oW","state":"app.requestedvalet","priority":2}},"title":"Vehicle retrieval request"}

check above push payload   i receive on data as notification part in GCM  .

**Comment by macdonst** [comment]
@aniljailta okay, that's cool. I see that it is coming in correctly when it works but can you get me logs from the device where it is not working?

Running `adb logcat | grep PushPlugin` really helps debug things.

**Comment by aniljailta** [comment]
[log.txt](https://github.com/phonegap/phonegap-plugin-push/files/428483/log.txt)
@macdonst 
Ok i have attached a log file that i have got from one of my customer . because at my end things are looking fine.app id is  com.ritzcarlton.valetone.

**Comment by macdonst** [comment]
@aniljailta so when I look at the log I see 4 variants of the following:

```
08-20 15:28:23.448: V/PushPlugin(14830): execute: action=init
08-20 15:28:23.449: V/PushPlugin(14830): execute: data=[{"android":{"senderID":"168415887446","icon":"icon","badge":"true","sound":"true","alert":"true"},"ios":{"alert":"true","badge":"true","sound":"true"},"windows":{}}]
08-20 15:28:23.450: V/PushPlugin(14830): execute: jo={"senderID":"168415887446","icon":"icon","badge":"true","sound":"true","alert":"true"}
08-20 15:28:23.450: V/PushPlugin(14830): execute: senderID=168415887446
08-20 15:28:23.454: V/PushPlugin(14830): onRegistered: {"registrationId":"f_Fp7hjjY1Q:APA91bHk5d9IjMqtJSDWJzuk10MLVSqe_KqzXXr9Qz-lq41JYTx1z3bYqMWzUjEmR9h36E9px_srYbWgFAdlIx15Ga_csMl74wNwJvfTU1K9o_v9Myfdkh0yIVMkOr4EpdLahFRT95HC"}
08-20 15:28:23.454: D/PushPlugin(14830): no iconColor option
```

This is the code that would get executed when the Push Plugins init method is called. I never see an instance of a message arriving on the device from GCM. 

However, looking into the logs a bit more I see:

```
08-20 15:27:09.959: D/GCM(5013): GcmService start Intent { act=com.google.android.gms.gcm.PACKAGE_FULLY_REMOVED cmp=com.google.android.gms/.gcm.GcmService (has extras) } com.google.android.gms.gcm.PACKAGE_FULLY_REMOVED
```

Which leads me to believe that the GCM sub-system isn't even installed on this device. That is beyond strange but I put nothing past Samsung.

**Comment by aniljailta** [comment]
@macdonst well yes , those logs are from moto G4. i tested in Samsung , it all looks fine over there .I have attached more [logs](https://www.dropbox.com/s/fdzud2wgylrn215/logs.txt) that customer has sent . this is bit strange . 
Registration works fine but they are not able to receive notifications

what should be my approach to fix this ?

**Comment by aniljailta** [comment]
@macdonst well yes , those logs are from moto G4. i tested in Samsung , it all looks fine over there .I have attached more [logs](https://www.dropbox.com/s/fdzud2wgylrn215/logs.txt) that customer has sent . this is bit strange . 
Registration works fine but they are not able to receive notifications

what should be my approach to fix this ?

**Comment by yonigo** [comment]
+1 

No push only on Note 5 with 6.0.1

I'm using SNS & Node.js on server side and I Noticed I get "disabled Endpoint" error when I try sending a push notification.

**Comment by macdonst** [comment]
@aniljailta the updated log you sent doesn't ever show a push notification arriving on the device.

@yonigo that is a Amazon SNS error, not a push plugin error. If you look at the Amazon SNS console you'll see that the end point you are trying to send to has been disabled by SNS.

**Comment by compitDanielos** [comment]
Same here.
No push on Nexus 6P 6.0.1
Other Nexus 6P but with 6.0.0 works fine.

**Comment by Creawebs** [comment]
Same here on xperia z5c on android 6.0.1, push is firing registered event successfully like shown in the logs by doing grep on PushPlugin. It worked fine on 6.0.0.
The Google push API is sending me:
{"error":"NotRegistered"}

**Comment by Creawebs** [comment]
Update:
Calling push unregister refreshed my ID and fixed the problem.
https://github.com/phonegap/phonegap-plugin-push/issues/927#issuecomment-235618880

**Comment by aniljailta** [comment]
Awesome , that works , Just need to call unregister and init again to get new token to fix this problem .
