### ISSUE TITLE
iOS notification from cold boot

### ISSUE THREAD

**Issue by Deathspike** [phonegap/phonegap-plugin-push#117]
When the application has been killed completely, and a notification is tapped in the action center, the application launches but does not process the notification correctly. This is the flow of actions that occurred during my investigation:

1. `didReceiveRemoteNotification` is fired; stores the notification as `launchNotification`.
2. `applicationDidBecomeActive` is fired; uses `launchNotification` to invoke `notificationReceived`.
3. `notificationReceived` is fired; processes and fires it into JavaScript world.
4. Cordova becomes ready, `init` is fired, and JavaScript event handlers are attached.

At (4), the notification from (3) is lost. Some observations to handle the situation gracefully:

1. `notificationReceived` does not check if the `callbackId` is registered yet (L244).
2. `init` recognizes a pending `notificationMessage` and invokes `notificationReceived` (L111).

So, `notificationReceived` merely needs to check if `callbackId` is available. Replace:

    if (notificationMessage)

On https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/PushPlugin.m#L244 with:

    if (notificationMessage && self.callbackId != nil)

A pull request seemed like overkill for a one-line change. I'd appreciate it if this was merged :+1:

**Comment by macdonst** [comment]
@Deathspike Line 244 is:

`[self.commandDelegate sendPluginResult:pluginResult callbackId:self.callbackId];` 

so maybe a pull request or point me at exact line.

**Comment by Deathspike** [comment]
Change:

    if (notificationMessage)

On https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/PushPlugin.m#L186 with:

    if (notificationMessage && self.callbackId != nil)

Not sure how it ended up with L244 earlier.

**Comment by macdonst** [comment]
@Deathspike merged and thanks
