### ISSUE TITLE
Android Samsung badge permissions?

### ISSUE THREAD

**Issue by SvenTobback** [phonegap/phonegap-plugin-push#1171]
Hello, 

I recently added the phonegap-push-plugin in a Cordova Android 5.2.1 app (works great btw) but noticed something strange on the Samsung devices.

 It requires the additional permissions **com.sec.android.provider.badge.permission.READ** and **com.sec.android.provider.badge.permission.WRITE**. 

After some googling it turns out this permissions is for a notification badge that can be set on Samsung devices. 

Does the plugin specifically set this? I can't find any reference to this in the source? Would I be able to safely remove it (as I’m not planning on using the feature)?

![image](https://cloud.githubusercontent.com/assets/12933037/17857423/fb47692c-6881-11e6-8e71-b0e9dc5ab525.png)

Device: Samsung Galaxy S6 Edge (Android 5.0)

Kind Regards,
Sven T

**Comment by macdonst** [comment]
@SvenTobback it is the ShortcutBadger component this plugin uses to set the badges on Android devices that includes this permission. I have a feeling if you remove it you should be okay but I've not tested that configuration.

**Comment by SvenTobback** [comment]
@macdonst Thanks for the clarification and the quick reply! 

I'll post the results of removing the permissions here for other people who stumble over this.

**Comment by macdonst** [comment]
@SvenTobback that would be great. I'm going to re-open this issue, post your results back here and I'll put them into the plugins docs.

**Comment by SvenTobback** [comment]
Hi,

I've managed to delete all the permissions used by ShortcutBadger and everything seems to keep working! :)

For those interested (because it was quite the challenge), I used the plugin cordova-custom-config and the code below in the config.xml: 



        <preference name="android-manifest/@xmlns:tools" value="http://schemas.android.com/tools" />
        <config-file target="AndroidManifest.xml" parent="/*">
            
            <uses-permission android:name="com.sec.android.provider.badge.permission.READ" tools:node="remove"/>
            <uses-permission android:name="com.sec.android.provider.badge.permission.WRITE" tools:node="remove"/>
            <uses-permission android:name="com.htc.launcher.permission.READ_SETTINGS" tools:node="remove"/>
            <uses-permission android:name="com.htc.launcher.permission.UPDATE_SHORTCUT" tools:node="remove"/>
            <uses-permission android:name="com.sonyericsson.home.permission.BROADCAST_BADGE" tools:node="remove"/>
            <uses-permission android:name="com.sonymobile.home.permission.PROVIDER_INSERT_BADGE" tools:node="remove"/>
            <uses-permission android:name="com.anddoes.launcher.permission.UPDATE_COUNT" tools:node="remove"/>
            <uses-permission android:name="com.majeur.launcher.permission.UPDATE_BADGE" tools:node="remove"/>
            <uses-permission android:name="com.huawei.android.launcher.permission.CHANGE_BADGE" tools:node="remove"/>
            <uses-permission android:name="com.huawei.android.launcher.permission.READ_SETTINGS" tools:node="remove"/>
            <uses-permission android:name="com.huawei.android.launcher.permission.WRITE_SETTINGS" tools:node="remove"/>
        </config-file>


Kind Regards,
Sven

**Comment by sparkshanto** [comment]
Hi my app ask for run time permission for badge and crash the app, how to add run time permission for badge?
        
Caused by: java.lang.SecurityException: Permission Denial: writing com.sec.android.provider.badge.BadgeProvider uri content://com.sec.badge/apps from pid=5325, uid=10242 requires com.sec.android.provider.badge.permission.WRITE, or grantUriPermission()
