### ISSUE TITLE
How to catch "activated" event triggered by Toast notification for Windows

### ISSUE THREAD

**Issue by tarsusi** [phonegap/phonegap-plugin-push#1172]
Hi,
I am currently trying to get toast notifications for my windows app. I can successfully receive any toast notification sent by my Azure Notification Hub when application is working at foreground or background.  However, while my push-app is closed, when i receive toast notification, how i can decide that my application has been started by tapping notification?

According to [this document](https://msdn.microsoft.com/en-us/library/windows/apps/hh761468.aspx):
It says "The activated event fires, The app's activated event handler reads the launch string"

Is there any way to listen this "**activated**" event in my cordova application?

**Comment by daserge** [comment]
@tarsusi see if this helps:
https://github.com/phonegap/phonegap-plugin-push/issues/1033#issuecomment-238237978
