### ISSUE TITLE
iOS need help about GCM

### ISSUE THREAD

**Issue by Hurinj** [phonegap/phonegap-plugin-push#1173]
Hello all,

I started to use this plugin for my Cordova app on iOS.
First, I succeed having the message asking me if I want to allow notifications on my app.
I also created a APNS on Apple and on Google I followed this link https://developers.google.com/cloud-messaging/ios/client
So I connected cloud messaging to my apple app and I put the configuration file GoogleService-Info in my xcode app folder.

ON xcode i got this message which tell me GCM is not connected : 

```
HelloCordova[1640:453970] Push Plugin register called
2016-08-24 11:02:49.300 HelloCordova[1640:453970] PushPlugin.register: setting badge to true
2016-08-24 11:02:49.300 HelloCordova[1640:453970] PushPlugin.register: clear badge is set to 1
2016-08-24 11:02:49.300 HelloCordova[1640:453970] PushPlugin.register: better button setup
2016-08-24 11:02:49.302 HelloCordova[1640:453970] GCM Sender ID 1630XXXXXXX
2016-08-24 11:02:49.303 HelloCordova[1640:453970] Using GCM Notification
2016-08-24 11:02:49.331 HelloCordova[1640:453903] Push Plugin register success: <defef2b5 2b4c6eb1 0da78031 a475a0d6 15c008ae 6d649605 5c7877c1 b4c5tg6>
2016-08-24 11:02:50.099: GGLInstanceID | Unable to find token in cache Error Domain=com.google.iid Code=-25300 "(null)"
2016-08-24 11:02:52.204 HelloCordova[1640:453903] Registration to GCM failed with error: The operation couldn’t be completed. (com.google.HTTPStatus error 401.)
```

It is weird because I put it in my js code, have a look : 

```
var push = PushNotification.init({
                "ios": {
                    "senderID": "1630XXXXXX",
                    "sound": "true",
                    "alert": "true",
                    "badge": "true",
                    "clearBadge": "true"
                }
            });
```

Do you know what to do ?

**Comment by xavianaxw** [comment]
Shouldn't it be

``` js
var push = PushNotification.init({
        "android": {
          "senderID": "123456"
        },
        "ios": {
          "alert": "true",
          "badge": "true",
          "sound": "true"
        }
      });
```

instead?

**Comment by Hurinj** [comment]
Well I created again a certificate development for push notification on Apple.
I have the token now but there is still one error about GGLInstanceID. What is it ?

2016-08-24 11:29:36.204: GGLInstanceID | Unable to find token in cache Error Domain=com.google.iid Code=-25300 "(null)"
2016-08-24 11:29:37.614 HelloCordova[1679:461813] GCM Registration Token: m8IQiGkOn-Q:APA91bEABqeG9q3s1QQRRCGh0um4zEUpHz4r1XYsChdB16MV7Rez3OCz5EB46983_z_ssiuIsqBh5P_MVefxOdnZ62UvzM1CRtoYLl4aKJfTil9JYLhIYG0pLBaTXQx23ZRaPg1qz6mv

**Comment by xavianaxw** [comment]
Oh you are trying to hook up APNS and GCM. I haven't tried it before so I can't really advise you.

Try checking out some of this stackoverflow threads
[#1](http://stackoverflow.com/questions/33361326/gcm-in-swift-bundle-id-error)
[#2](http://stackoverflow.com/questions/35713906/ionic-ios-push-unable-to-find-token-in-cache-error-domain-com-google-iid-code)

Sorry can't be much of a help

**Comment by santhoshscs** [comment]
> GCM Registration Token: m8IQiGkOn-Q:APA91bEABqeG9q3s1QQRRCGh0um4zEUpHz4r1XYsChdB16MV7Rez3OCz5EB46983_z_ssiuIsqBh5P_MVefxOdnZ62UvzM1CRtoYLl4aKJfTil9JYLhIYG0pLBaTXQx23ZRaPg1qz6mv

indicates that GCM registration Id is successfully created for your device  see the **m8IQiGkOn-Q:APA...** format
Are you trying development/Production App ? If it is development(sandbox) then you need to put
 "gcmSandbox":true in your ios  option 

`
var push = PushNotification.init({
                "ios": {
                    "senderID": "1630XXXXXX",
                    "gcmSandbox":"true" ,
                    "sound": "true",
                    "alert": "true",
                    "badge": "true",
                    "clearBadge": "true"
                }
            });
`

**Comment by Hurinj** [comment]
Ok thank you. 
What is difference between development/production ? and what is the sandbox ?

Moreover, now i collect the registrationId thank to the plugin and store them in my database.
What is the next step ?

push.on('registration', function(data) {
// send data.registrationId to my database
			});

**Comment by santhoshscs** [comment]
> What is difference between development/production ? and what is the sandbox ?

development/sandbox = DEV environment - for testing purpose 
prroduction = LIVE enviroment when deployed to appstore

Apple push notification needs different types of certificates for Production and DEV environments

The next step for you is to 

1.  accept notification in your client code with 
    `app.push.on('notification', function (data) {`
2. run on ios and test with POST Request  to  GCM send notification and verify you can recieve messages

**Comment by Hurinj** [comment]
OK :)

Well I already accept notification when my app is launched for the first time.
Moreover, each time we reload it I update the registrationId given in push.on ...

I can post directly to GCM with in the javascript or I have to use my server ?
Also where can I find how and what to send it to GCM with a java server..

Thank you again.

**Comment by santhoshscs** [comment]
> I can post directly to GCM with in the javascript or I have to use my server ?
Also where can I find how and what to send it to GCM with a java server..

You need  to use a backend server for sending notifications for several reasons
[https://developers.google.com/cloud-messaging/](url) gives you good enough doc to do it

**Comment by Hurinj** [comment]
Well i don't understand all because it is in native ^^ but thank you ;)

**Comment by santhoshscs** [comment]
just focus on the server side POSt request like 

```
https://gcm-http.googleapis.com/gcm/send
Content-Type:application/json
Authorization:key=AIzaSyZ-1u...0GBYzPu7Udno5aA

{ "data": {
    "score": "5x1",
    "time": "15:10"
  },
  "to" : "bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1..."
}
```
this POST can be tested with some tools like PostMan Chrome Plugin or CURL requests
or even some GCM online testers like
[http://apns-gcm.bryantan.info/]

the client side will be already handled in the  `app.push.on('notification'.. ` cordova code

**Comment by Hurinj** [comment]
Ok, i test your website in the link for GCM.
In Device token i put the token beginning with " llS5KB-Xxog:APA91bFpi6oRopko ... " ?

**Comment by santhoshscs** [comment]
whatever device registration id's u recieved in the 'registration' event
