### ISSUE TITLE
Background push for iOS

### ISSUE THREAD

**Issue by Hurinj** [phonegap/phonegap-plugin-push#1178]
Hello I tried to send push notification to my Iphone with Postman.
It is ok but when I have my app in background, the notification doesn't come even if I followed the documentation about it - ie - I put "content-available": 1 in my json

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md

**Comment by jcesarmobile** [comment]
If you use content-available = 1 it will call on('notification'), but it won't be displayed

**Comment by Hurinj** [comment]
Yes but how can I have the native notification like if I received a message in facebook or something when I am not on the app ?
As I said in this link https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md 
Section iOS and Action Buttons
we can see the wanted behavior (pop up on top of HelloCordova)

**Comment by jcesarmobile** [comment]
removing the content-available from the payload, that is used for silent background notifications, and silent means they are not shown by the system.

it was working fine on the screenshoot you sent me, right?

**Comment by Hurinj** [comment]
The screenshoot I sent was for showing you what I'd like to have ^^
I tried with this in my payload but the notification only comes when I launch/open the app.
I'd like to have the message like if it was a sms (like in the screenshoot).

```
{
    "to" : "dpi1_JX5yb4:APA91bHN-iQ4b2mQsUXIU2vQV6S4J9fPvY5hprsNrQzDGqrz3JhN9CuicijrKU_DtW4BKN8AdxNZlaVals1k4AA0_9yp1VfYoYXosOqoBAaRGSOvdsp86nKuDTbq4o5lvdmpEvXbQsLv",
    "notification" : {
      "body" : "Nouvelle invitation par",
      "title" : "MonoNoAware"
    },
    "aps": {
        "alert": "This is a notification that will be displayed ASAP.",
        "category": "invite"
    }
  }
```

**Comment by macdonst** [comment]
@Hurinj we don't currently support FCM. We are working on it though.

**Comment by Hurinj** [comment]
But it works when I am on my app ^^
So how can I remove FCM of my project and go back in GCM ?

**Comment by Hurinj** [comment]
Add "priority":"high" and it works

**Comment by Hurinj** [comment]
Add "priority":"high" and it works
