### ISSUE TITLE
ionic build/emulate ios fails with this plugin

### ISSUE THREAD

**Issue by shack2012** [phonegap/phonegap-plugin-push#1189]
My ionic app works perfectly, but after phonegap-plugin-push install fails.
I have already tried to uninstall and re-install iOS platform and the plugin, but i've the same error.

UPDATE: it seems a conflict with googleplus plugin. Solutions? Thanks

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v4.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014 
#### Plugin version

phonegap-plugin-push  1.8.1
#### Logs taken while reproducing problem

….
GTM_iPhone.a(GTMUILocalizer.o)
duplicate symbol _OBJC_CLASS_$_GSDK_GTMUILocalizer in:
    italianfoodxp/Plugins/cordova-plugin-googleplus/GoogleSignIn.framework/GoogleSignIn(GTMUILocalizer.o)
    /Users/simplicio/ionic/italianfoodxp/platforms/ios/italianfoodxp/Plugins/phonegap-plugin-push/GCM/Libraries/libGTM_iPhone.a(GTMUILocalizer.o)
duplicate symbol _OBJC_METACLASS_$_GSDK_GTMUILocalizer in:
    italianfoodxp/Plugins/cordova-plugin-googleplus/GoogleSignIn.framework/GoogleSignIn(GTMUILocalizer.o)
    /Users/simplicio/ionic/italianfoodxp/platforms/ios/italianfoodxp/Plugins/phonegap-plugin-push/GCM/Libraries/libGTM_iPhone.a(GTMUILocalizer.o)
ld: 276 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

*\* BUILD FAILED **

The following build commands failed:
    Ld build/emulator/italianfoodxp.app/italianfoodxp normal i386
(1 failure)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/simplicio/ionic/italianfoodxp/platforms/ios/cordova/build-debug.xcconfig,-project,italianfoodxp.xcodeproj,-target,italianfoodxp,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,build,CONFIGURATION_BUILD_DIR=/Users/simplicio/ionic/italianfoodxp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/simplicio/ionic/italianfoodxp/platforms/ios/build/sharedpch

thanks

**Comment by avizcaino** [comment]
Same problem here... Any clue?

**Comment by macdonst** [comment]
@shack2012 @avizcaino Yeah, both plugins include some Google libraries directly and they conflict at build time. Right now @shazron is working on CocoaPod support for this plugin (https://github.com/phonegap/phonegap-plugin-push/pull/1183) and Cordova in general which should resolve this issue.

**Comment by shack2012** [comment]
**@macdonst** ok thanks :)

**Comment by avizcaino** [comment]
@macdonst thanks!

**Comment by macdonst** [comment]
Should be fixed in 1.9.0
