### ISSUE TITLE
Ios receives notifications in json

### ISSUE THREAD

**Issue by Dmatafonov** [phonegap/phonegap-plugin-push#1190]
### Expected Behaviour

Supposed to be just text
### Actual Behaviour

Get json.
![image](https://cloud.githubusercontent.com/assets/8863854/18210053/6149aae4-713f-11e6-8012-dac96e2c609f.png)

Is it a bug? Was working perfectly, we changed nothing. Started 1 of september.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
