### ISSUE TITLE
Push phugin lot of error 

### ISSUE THREAD

**Issue by vikash28** [phonegap/phonegap-plugin-push#1191]
1.When we tap on notification  the event push.on('notification' ) not trigger .This problem have not solve yet.As lot of have this issue.

The app in background.

the  notification is working on foregroung

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
