### ISSUE TITLE
Localization title and other constants on Android?

### ISSUE THREAD

**Issue by polyn0m** [phonegap/phonegap-plugin-push#1194]
My application uses 2 languages.

Is it possible to use the constants from strings.xml for notify title or summaryText? 

It is very expensive detect current language of user device on the server side.

**Comment by macdonst** [comment]
@polyn0m currently this behaviour is not supported. It would be an interesting enhancement though.

Right now you best bet is to send the local of the user back to your server when you send it the registration ID. Then you can send separate push notifications out to your 2 languages.

**Comment by polyn0m** [comment]
@macdonst tanks for quick reply.

Send locale to app server may cause errors, when user change language but not start app. It's rare case but possible. In my opinion store part of application on app server it is wrong.

I have start worked for this enhancement https://github.com/polyn0m/phonegap-plugin-push/commit/68c866363e8e0307e9334b43423c1644f380ba84 when finish it (hope 1-2 days), I'll make a pr.
