### ISSUE TITLE
"PushNotification not defined" for Cordova Windows Apps

### ISSUE THREAD

**Issue by AparnaChinya** [phonegap/phonegap-plugin-push#1197]
### Expected Behaviour
Push notification should work without issue

### Actual Behaviour
"PushNotification not defined" error

### Reproduce Scenario (including but not limited to)
Quick Start App from Azure mobile apps then add the push notification code JUST For WINDOWS APPS
Ref link: https://azure.microsoft.com/en-in/documentation/articles/app-service-mobile-cordova-get-started-push/
Try to add an Item to the To-DoList App - errors out.

#### Platform and Version 
Windows x64,Windowsx86,Windows Phone (Universal)

#### Cordova CLI version and cordova platform version
6.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   

#### Sample Code that illustrates the problem
https://1drv.ms/u/s!AipTsyc27A7EkJw36LRgxl2R9wSULA

#### What I found out -
I see that when SENDER_ID is null - we get this error. SO, I added a random value in place of SENDER_ID and the push notification started working for Windows UWP as well.

**Comment by macdonst** [comment]
@AparnaChinya Yup, the SENDER_ID is required. Even a fake one.

**Comment by AparnaChinya** [comment]
Thank you for the confirmation!
