### ISSUE TITLE
Question with forceShow on Android

### ISSUE THREAD

**Issue by mindr242** [phonegap/phonegap-plugin-push#1198]
Hi,

For some pushes I want the notification to be shown on the shader even if the app is in **foreground**, so I set forceShow = true for Android.

However, I have some other pushes that I don't need to be shown if the app is in **foreground**, instead I only want them to be shown in the shader if the app is in **background**.

How can I achieve this? In other words control forceShow option for specific pushes under the same app?

**Comment by macdonst** [comment]
@mindr242 the plugin does not support that type of behaviour. You either always get the notification in the shader or only when the app is in the background. If you want the type of behaviour you describe set `forceShow: false` and use the local notification plugin to selectively show a notification while in the foreground.
