### ISSUE TITLE
Handling multiple notifications on Android devices 

### ISSUE THREAD

**Issue by carefreews** [phonegap/phonegap-plugin-push#12]
Currently, notifications won't stacked in the notification panel, so old notifications replaced by new one. I think "notId" option worth mentioning in the documentation. However, in my point of view stacking notifications is a better approach.

**Comment by macdonst** [comment]
@carefreews Say I send 3 pushes to my app, do you expect there to be 3 entries in the shader or a multi-line notification like Gmail for instance? The first is trivial to do.
