### ISSUE TITLE
Only specifying SENDER_ID in config.xml fails init call

### ISSUE THREAD

**Issue by pke** [phonegap/phonegap-plugin-push#1201]
### Expected Behaviour

init call to succeed without providing a `senderId`.

### Actual Behaviour

init call fails with "No value for senderId"

### Reproduce Scenario (including but not limited to)

Specify the SENDER_ID `param` in config.xml as described by the doc.
Call `init` without specifying a `senderId` key.

#### Plugin version

   1.8.0

**Comment by macdonst** [comment]
@pke you need to do both for now.

**Comment by pke** [comment]
Oh why oh why is that? That's horrible API.
You require a VARIABLE to be specified at install time. Require a PARAM to be specified if the plugin is to be restored.
But all that does not work on its own confusing way but we are required to provide the id in yet another way, namely programmatically.
Please consider harmonising the API surface.

**Comment by macdonst** [comment]
@pke why do you keep asking this question? You opened #1175 which I answered and referred you to #679.

**Comment by pke** [comment]
Because its confusing as hell. It's not about getting people to get used to it, if the sender if from the config is not even used by the plugin. The docs also just add to the confusion by not clearly saying that the sender ID in the config is not used anywhere.

**Comment by macdonst** [comment]
@pke Can you send a pull request to clarify the docs?
