### ISSUE TITLE
iOS unregisters after first notification is sent

### ISSUE THREAD

**Issue by avizcaino** [phonegap/phonegap-plugin-push#1202]
### Expected Behavior
Receive push notifications in foreground and background in iOS devices

### Actual Behavior
The device registers successfully to GCM providing a registration token. When sending the **first notification**, the message is sent successfully although I do not receive any notification. The subsequent notifications are not sent with a message result of 'Not registered'.

**This only happens in iOS devices.**

### Reproduce Scenario (including but not limited to)
This is my configuration:
```
PushNotification.init({
          android: {
            senderID: "XXXXX",
            vibrate: "true",
            sound: "true",
            badge: "true"
          },
          ios: {
            senderID: "XXXXX",
            vibrate: "true",
            sound: "true",
            badge: "true",
            gcmSandbox: "true"
          }
```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 9.3

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPad / iPhone

#### Cordova CLI version and cordova platform version
cordova 6.3.1
cordova platform iOS 4.1.1

#### Plugin version
phonegap-plugin-push 1.8.1

#### Sample Push Data Payload
```
to: "xxxxxxxx",
{
  notification: {
    title: "Hello, World",
    body: "This is a notification that will be displayed ASAP."
  }
}
```

#### Sample Code that illustrates the problem
```
{ message_id: 6584932061909982000 }
{ multicast_id: 8903643569140261000,
  success: 0,
  failure: 1,
  canonical_ids: 0,
  results: [ { error: 'NotRegistered' } ] }
```

**Comment by macdonst** [comment]
@avizcaino by chance do you call the `unregister` method anywhere in your code? Also, are you sure you are registering and pushing to the same APNS server? Sometimes people with register with dev and push to production or vice versa.

**Comment by avizcaino** [comment]
@macdonst I do not unregister anywhere... About the registering and pushing to the same APNS server, I generated the GoogleService-Info.plist only with my development certificate to avoid this confusion and in the iOS push client configuration I'm specifying gcmSandbox, so I don't know why I'm having this behavior :(

**Comment by macdonst** [comment]
@avizcaino right, but how are you sending the push payload to APNS?

**Comment by avizcaino** [comment]
@macdonst sorry... but I don't understand what you mean... :(

My payload is:

```
to: "xxxxxxxx",
{
  notification: {
    title: "Hello, World",
    body: "This is a notification that will be displayed ASAP."
  }
}
```

And I'm sending it through [node-gcm](https://www.npmjs.com/package/node-gcm):

```
var message = new gcm.Message({
  notification: {
    title: "Hello, World",
    body: "This is a notification that will be displayed ASAP."
  }
});

var regTokens = [TOKEN];
var sender = new gcm.Sender(API_KEY);

sender.send(message, {registrationTokens: regTokens}, function (err, response) {
  if (err) console.error(err);
  else console.log(response);
});

sender.sendNoRetry(message, {topic: '/topics/global'}, function (err, response) {
  if (err) console.error(err);
  else console.log(response);
});

```

Don't know if that is what you mean...

**Comment by malwatte** [comment]
@avizcaino ,
Certificate issue? Something similar happened to me when I had not installed certificates correctly (APNS certificates and updated provisioning profile)

**Comment by avizcaino** [comment]
@malwatte Checked twice, all about certificates is properly done...

**Comment by avizcaino** [comment]
Well, it seems it works now... I had to re-do everything (app, certificates, appids, etc) and now it works. Really weird everything, really...

Thanks anyway!

**Comment by software-services** [comment]
Hi @avizcaino, what exactly did you have to do to fix this? I have exactly the same issue. Worked fine in io9/xcode7, issue now appeared with ios10/xcode 8. Thanks

**Comment by avizcaino** [comment]
I'm still working with iOS9 so I'm not sure if the procedure will work also for iOS10.

Create project in Google Developers Console: [here](https://console.developers.google.com/apis/)
Add Google Services GCM to your App: [here](https://developers.google.com/mobile/add?platform=ios&cntapi=analytics&cnturl=https:%2F%2Fdevelopers.google.com%2Fanalytics%2Fdevguides%2Fcollection%2Fios%2Fv3%2Fapp%3Fconfigured%3Dtrue%23add%2Dconfig&cntlbl=Continue%20Adding%20Analytics)

> You have to chose the previous project created in the first Developers Console, upload the proper certificate (still development in my case) and this will provide you with your API_KEY, SenderId and GoogleServices-Info.plist

Configuration for GCM registry:
```
this._pn = window.PushNotification.init(<any>{
          android: {
            senderID: "XXXXXXXXX",
            vibrate: "true",
            //forceShow: "true",
            sound: "true",
            badge: "true"
          },
          ios: {
            senderID: "XXXXXXXXX",
            gcmSandbox: "true", //if you are working with development certificates
            alert: "true",
            sound: "true",
            badge: "true"
          }
        });
```

Activate Push for the App in Xcode:
![captura de pantalla 2016-10-04 a les 12 41 40](https://cloud.githubusercontent.com/assets/12660226/19071880/956a6b90-8a32-11e6-8f7f-f9096cfb9f16.png)

Add GoogleServices-Info.plist to Resources folder in Xcode:
![captura de pantalla 2016-10-04 a les 12 41 47](https://cloud.githubusercontent.com/assets/12660226/19071875/908c9bde-8a32-11e6-908c-211abf8689da.png)

Hope this works for you!

> PS: I'm working on an extended documentation I can share shortly.

**Comment by jb-72** [comment]
Found it...
While developing
iOS9/xCode7 worked with gcmSandbox: false
iOS10/xCode8 only works with gcmSandbox: true

**Comment by avizcaino** [comment]
@jb-72 Will this work with Production environment? Isn't gcmSandbox just for development certificates? I need to upgrade to iOS10 next week and I may face the same problem...

**Comment by jb-72** [comment]
@avizcaino I haven't checked yet but I'm assuming that gcmSandbox will need to be false when uploading to itunes.
