### ISSUE TITLE
I need to remove "gcmSandbox": "true" on production app??

### ISSUE THREAD

**Issue by J261** [phonegap/phonegap-plugin-push#1203]
hello, what is the function of gcmSandbox:true. I need this for FCM? o i can remove it for production app?

**Comment by macdonst** [comment]
@J261 if you are using GCM/FCM in development set gcmSandbox:true. When you are building a production app set gcmSandbox:false. If you are not using GCM to send message to Apple devices then you can ignore sender_id and gcmSandbox.
