### ISSUE TITLE
push.on('notification') Event not fire in android when app is closed

### ISSUE THREAD

**Issue by ominfowave** [phonegap/phonegap-plugin-push#1204]
### Reproduce Scenario (including but not limited to)
Platform and Version (eg. Android 4.2.2)(lenovo s650)

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.3.1
  

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
