### ISSUE TITLE
phonegap-plugin-push doesnt add android permission

### ISSUE THREAD

**Issue by ledil** [phonegap/phonegap-plugin-push#1205]
### Expected Behaviour

phonegap-plugin-push should add android permission (for notification)
The app will be compiled under phonegap-build. I dont have "feature" value in config.xml and Im using phonegap cli 6.3.0
### Actual Behaviour

when I install my application it doesnt ask for push notification permission on android
#### Steps to Reproduce

ive created a new example for phonegap build.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 5.0.
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Samsung Galaxy S5
#### Cordova CLI version and cordova platform version

```
cordova --version                                    # e.g. 6.0.0
```

6.3.0
    cordova platform version android                     # e.g. 4.1.1
5.2.1
#### Plugin version

```
cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3
```

1.8.1

**Comment by macdonst** [comment]
What do you mean? Android doesn't have a dialog to request permission to
receive pushes.

**Comment by ledil** [comment]
the problem is that pushnotification is undefined. Im using it after deviceready event.

**Comment by macdonst** [comment]
@ledil oh, that's not the same thing at all. You need to give me more details in order for me to be able to help though.

**Comment by ledil** [comment]
@macdonst , you are right the title is misleading ... this is actually my code:

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" id="metaViewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
  <link media="all" rel="stylesheet" href="css/main.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
  <link rel="stylesheet" media="all" href="css/animate.min.css">
    <link rel="stylesheet" href="css/scooch.min.css">
    <link rel="stylesheet" href="css/scooch-style.min.css">
    <link rel="stylesheet" href="css/csshake.min.css">
    <script type="text/javascript" src="cordova.js"></script>
</head>
<body>
<body class="login-pg animated fadeIn">
    <script>
        document.addEventListener("deviceready", onDeviceReady, false);
        function onDeviceReady() {
            alert(typeof(PushNotification));
        }
    </script>
</body>
</html>

<plugin name="phonegap-plugin-push" source="npm" version="1.8.1">
     <param name="SENDER_ID" value="295501643961" />
</plugin>

the alert shows "PushNotification" is undefined. Im using phonegap build with cli 6.3.0 ... above you can see the content of the index.html after unzipping the apk.

**Comment by macdonst** [comment]
@ledil I'm willing to bet something went wrong with the build of your app and Push was not included. Do you have the build log from PGB?

**Comment by ledil** [comment]
@macdonst yes here it is http://pastebin.com/X0650UZ3

**Comment by macdonst** [comment]
@ledil okay, cool. I can see the support lib and GCM libs were added for Android. Can you rename you .apk to a .zip, unzip that file and check the `assets/www/plugins/phonegap-plugin-push/www` folder to see if you can find `push.js` in there? Also, check `assets/www/cordova_plugins.js` to make sure `push.js` is being loaded.

**Comment by ledil** [comment]
@macdonst both files are there ... and push.js will be loaded in cordova_plugins.js

**Comment by macdonst** [comment]
@ledil that doesn't make any sense. I think the best thing to do is to open a ticket with the PGB team as they can look at your build in more detail.

https://forums.adobe.com/community/phonegap/build

**Comment by numerized** [comment]
Hello guys, 

I'm using the latest Ionic2, although on IOS it worked very well, on Android it's not. I've check this too and everything looks ok.

```
Can you rename you .apk to a .zip, unzip that file and check the assets/www/plugins/phonegap-plugin-push/www folder to see if you can find push.js in there? Also, check assets/www/cordova_plugins.js to make sure push.js is being loaded.
```

I've tried from scratch a second time and still not working.
The calls to the plugin fail silently, I tried to put some console.log and any callback is fired.

I'm on Android 5.01 on archos 80c and a friend tried on Android6 Sony Xperia.
Any help to find the reason of the problem is welcome.

```
 this.platform.ready().then( () => {
      if(this.platform.is('mobile')){
        console.log('push1');
            this.push.register()
                .then( (token) => {
                this.push.saveToken(token).then( (token) => {
                    // I do stuff here
                });
            }, (error) => { console.error('[PushService] Cannot register push token.'); });

            console.log('push2');
            this.push.rx.notification()
                .subscribe((msg) => {
                alert(msg.title + ': ' + msg.text);
            });
            console.log('push3');
        }
    })
```
