### ISSUE TITLE
Question: Are you planning to migrate from GCM to Firebase Cloud Messaging for Android?

### ISSUE THREAD

**Issue by emc2spider** [phonegap/phonegap-plugin-push#1206]
Hi, I've been using the plugin for some time and works great guys. Thank you so much!

I recently came across the following https://developers.google.com/cloud-messaging/android/android-migrate-fcm

So I was wondering if this is something that will be affecting the plugin implementation any time soon?

**Comment by macdonst** [comment]
@emc2spider yes, we already have a `FCM` branch.
