### ISSUE TITLE
Tapping on notification go to specific state/url (Android)

### ISSUE THREAD

**Issue by s4dman** [phonegap/phonegap-plugin-push#1207]
### Expected Behaviour
I want to redirect my app to a specific state or url when I tap on the notification in notification drawer of Android device

### Actual Behaviour
Nothing happens. The app starts from my default state and remains there.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.0 > 

#### Cordova CLI version and cordova platform version

    cordova 6.3.1
    cordova platform version android 5.2.2

#### Plugin version

    cordova plugin version 1.8.0

#### Sample Code
```
 push.on('notification', function(data) {
                    console.log(data.message);
                    console.log(data.title);
                    console.log(data.count);
                    console.log(data.sound);
                    console.log(data.image);
                    console.log(data.additionalData);
                    console.log("Here");
                    console.log("On notification: " + JSON.stringify(data));
                    $state.go('on-request');
                });
```

**Comment by s4dman** [comment]
I have solved the issue by installing **Cordova Inappbrowser** inside my project & calling my service inside **device ready events**

_Inside app.js :_
```
 $ionicPlatform.ready(function(PushService) {

// Calling registerPush method from PushService. registerPush() holds all notification codes
   
 PushService.registerPush();
 });

$ionicPlatform.on('resume', function() {
      PushService.registerPush();
});

$ionicPlatform.on('resume', function() {
      PushService.registerPush();
});
```
_Inside service.js :_
```
starter.factory('PushService', ['$http', '$state', function($http, $state) {
    return {
          registerPush: function() {

// .init()
// .isEnabled()
//...... other necessary codes
 
                push.on('notification', function(data) {
                    console.log(data.message);
                    console.log(data.title);
                    console.log(data.count);
                    console.log(data.sound);
                    console.log(data.image);
                    console.log(data.additionalData);
                    console.log("Here");
                    console.log("On notification: " + JSON.stringify(data));
                    $state.go('on-request');
                });
            }
        }
    }
}]);
```

**Comment by sadiq-mc** [comment]
@s4dman Same issue here... Is it necessary to install inappbrowser.? 
Below is my code snippet from app.js
```


app.run(function($ionicPlatform, $rootScope, $location, $localStorage,
    appConstants, logService, $cordovaPushV5) {
	
	var pushOptions = {
		android: {
			forceShow: false,
			clearNotifications: false,
			iconColor: '#EB0000',
			sound: true
		},
		ios: {
			alert: true,
			badge: false,
			sound: true
		}
	};


	$ionicPlatform.ready(function() {
		$cordovaPushV5.initialize(pushOptions).then(function() {
			// start listening for new notifications
			$cordovaPushV5.onNotification();
			// start listening for errors
			$cordovaPushV5.onError();

			// register to get registrationId
			$cordovaPushV5.register().then(function(registrationId) {
				// save `registrationId`
				logService.log("Reg Id: " + registrationId);
				$localStorage.deviceToken = registrationId;
			});
		});
	});
	
	$ionicPlatform.on("resume", function() {
        //code for action on resume
        logService.log("onresume event");
        logService.log($localStorage.notificationData);
    });
	
	// triggered every time notification received
    $rootScope.$on('$cordovaPushV5:notificationReceived', function(event, data) {
        logService.log(data);
        $localStorage.notificationData = JSON.stringify(data);       
    });

});
```

Can you please help me to solve the same issue. I need to open a specific page on tapping the notification.

**Comment by s4dman** [comment]
@sadiq-mc First of all, Are you sure you're using the correct version? Seems like there's no v2.0.0 released yet for this plugin. Please use the released and stable versions.

Use `$state.go("desired_view");` inside your notification received event to redirect to a specific view.

**Comment by sadiq-mc** [comment]
@s4dman v2.0.0 is not yet released, but I need to integrate FCM in my app as the Google API console doesn't provide GCM integration anymore.

**Comment by sadiq-mc** [comment]
I can get the notification using this plugin, but i need to navigate to a view if user taps the notification. But there is a condition for me, if the user is not logged in, he should be redirected to login page and then from there after successful login, redirect to the specific view.

**Comment by sadiq-mc** [comment]
@s4dman I added a 'pause' event and its getting fired while, but the 'resume' event is not getting fired as expected. 'resume' events gets fired only when I switch to a different app and then return back to my app. But when I close the app and launch it again, the 'resume' event is not fired. Also the same gets fired after some seconds which am not able to understand.

**Comment by s4dman** [comment]
@sadiq-mc The answer lives inside your question. You should check for the condition inside your notification trigger event if the user is logged-in. 
```
if( logged_in == true ){
    $state.go("desired_view");
}else{
   $state.go("login_view");
}
```
Use `$state.go()` if you are using **Ionic** or **AngularJs** for your app. 

When you close an app using the back button or remove it from recent activities it gets killed. If you then open the the `OnCreate() / On() event` will fire. But if you switch between apps or leave the app using menu button, then next time you open the app `resume() event` will fire.

For a quick review on android activity lifecycle you can go through the following link : 
https://cordova.apache.org/docs/en/latest/guide/platforms/android/#cordova-and-android

**Comment by sadiq-mc** [comment]
I was about to update it here, but went through some other stuff by that time. I did the one you said and I noticed the same with ```resume()``` event. It was fired only when I switch the apps and not when launching the app after exiting. 
As you mentioned, I checked whether user is logged in the ```notificationRecieved()``` event and proceeded to the required view.

Thanks for the support.. 👍

**Comment by s4dman** [comment]
@sadiq-mc Glad to know that you're issue is solved !

_Happy Coding_ :)
