### ISSUE TITLE
Andriod :More than 2 notifications in status bar it is not works.

### ISSUE THREAD

**Issue by ramakrishna-nyros** [phonegap/phonegap-plugin-push#121]
Hi, I am using phonegap build to my app,I used this plugin successfully to send push notification . When I send more than 2 notifications with different notId ,I get the notifications in phone status bar,when click on first notification  it opens app and show in a page . But  when click on 2nd notification  it opens app & show in a page and close all the notification in status bar.

How to solve this issue ? 

Thanks in advance

**Comment by macdonst** [comment]
@ramakrishna-nyros set `options.android.clearNotifications` to false on init.

**Comment by ramakrishna-nyros** [comment]
@macdonst Thanks for the reply, As you specified I used init function like below:

onDeviceReady: function() {
        var push = PushNotification.init({
            "android": {
                "senderID": "88812375449",
                'options.android.clearNotifications' : false
            },
            "ios": {}, 
            "windows": {} 
        });
But no change , Same issue.The above code is correct ?

**Comment by macdonst** [comment]
@ramakrishna-nyros No, it is not correct.

```
onDeviceReady: function() {
var push = PushNotification.init({
"android": {
"senderID": "88812375449",
"clearNotifications" : "false"
},
"ios": {}, 
"windows": {} 
});
```

**Comment by ramakrishna-nyros** [comment]
Thanks **Macdonst** , It's working now.
