### ISSUE TITLE
Ask for a FCM token instead of GCM

### ISSUE THREAD

**Issue by Hurinj** [phonegap/phonegap-plugin-push#1211]
Hello,

I had to rebuild my app with cordova and reinstall this plugin. I am on iOS.
Before that I had a FCM token when I connect with my app. Now I have a GCM token in the console of Xcode.

Is there a way to precise I'd like to have the FCM token like I used to have.
Change something in the plugin ?

**Comment by Hurinj** [comment]
I just downloaded the branch fcm, changed the file of the plugin.
Don't forget to add the generated file GoogleService-Info.plist in root and platforms/ios.
Cordova prepare
Cordova build ios
The first token is null, just wait.

**Comment by Hurinj** [comment]
Well It goes back using GCM token. One idea ?

**Comment by Hurinj** [comment]
Well It goes back using GCM token. One idea ?

**Comment by macdonst** [comment]
@Hurinj please add any comments on FCM in #929
