### ISSUE TITLE
Make "if" in push.on(notification)

### ISSUE THREAD

**Issue by Hurinj** [phonegap/phonegap-plugin-push#1212]
Hello,
I'd like to make a if according to the type of notification I am sending.
Each time I send a notification, I call this : 

```
                push.on('notification', function (data) {

                    console.log(data.additionalData.notif);

                    if (data.additionalData.notif == 1 || data.additionalData.notif == 2){

                    console.log("if");

                    } else {
                    	console.log("else");
                    }
```

Each time, the function only calls `console.log("else") `.
The fact is `console.log(data.additionalData.notif)` is 1.
So it must go in the "if" and show "if' in the console.log...

Is there a special way to see if the additionalData is equal to something ?
Thank you !

**Comment by fredgalvao** [comment]
Don't you mean [`notId`](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#stacking)?

**Comment by Hurinj** [comment]
What ?
In additional data I put a data named notif with value 0 1 or 2

**Comment by ef33zy** [comment]
@Hurinj is this or iOS or Android?

**Comment by Hurinj** [comment]
well the both ^^

**Comment by fredgalvao** [comment]
Can you share what's the payload you sent and also how you sent it? It's pretty much impossible for us to help you without more info.
Also, no, there's nothing special to the additionalData object. It's a plain simple javascript object.

**Comment by macdonst** [comment]
@Hurinj are you using the FCM branch?

**Comment by ShamimIslam** [comment]
No idea why you do a console("if") but not a console(JSON.stringify(data))

You are trying to debug blind.

**Comment by Hurinj** [comment]
@macdonst yes I am using the fcm branch !

**Comment by ShamimIslam** [comment]
I think you should add console(JSON.stringify(data)) in place of your console(data.additionalData.notif)

That way you will know for sure if the notif is a number or a string

console('1') and console(1) return the same visual display while console(JSON.stringify('1')) returns "1" and console(JSON.stringify(1)) returns 1

Note the quotes.

**Comment by Hurinj** [comment]
@ShamimIslam 

It shows 

`{"additionalData":{"coldstart":false,"foreground":true,"notif":"1","x":"1.56","y":"43","gcm.message_id":"0:1473......"},"message":"Nouvelle invitation","sound":"default"}`

**Comment by ShamimIslam** [comment]
And there is your error.

Your line should read

=='1' || =='2'

You are failing because 1!='1' and 2!='2'

In reality, NONE of your numbers are numbers in your datastructure. They
are all text.

The computer can't figure out what you mean. It can only do as you say.

**Comment by fredgalvao** [comment]
@ShamimIslam You're partially wrong. In pure old javascript, double equal (`==`) does type coercion, so `1=='1'` actually outputs `true`. Type coercion works on every raw type except arrays and objects to some extent. [detailed explanation](https://developer.mozilla.org/en/docs/Web/JavaScript/Equality_comparisons_and_sameness).

**Comment by Hurinj** [comment]
Thank, it is working !

**Comment by ShamimIslam** [comment]
@fredgalvao Please note Hurinj stated very clearly: "if" is never executing. Only "else" is executing. 

Given his data structure, and code, I can only see one explanation for why it is failing and type coercion does not cover it.

Please suggest the alternative reason it may be failing if the data structure has "1" and the comparison to ==1 is failing.

**Comment by ShamimIslam** [comment]
@fredgalvao I reviewed your link. It should follow A is a string and B is a number which translates to ToNumber(A) === B. But this is not occurring. Can you tell me why?

I only see the failure, but not the rationale for the failure.

**Comment by fredgalvao** [comment]
@ShamimIslam I don't know what's making his `1=='1'` to evaluate to false, AFAIK not even `"use strict";` makes type coercion stop working like that. But I tend to believe more in [the specs of the compiler/runtime](http://ecma-international.org/ecma-262/5.1/#sec-11.9.3) than in a partial solution to a single problem.
If changing to `=='1' || =='2'` made it work, then we're settled and the issue is gone, but that's not how javascript works.

At least it's fixed, I guess.

**Comment by ShamimIslam** [comment]
As you say - I was going on the basis of his error and not the ECMA 262.
