### ISSUE TITLE
Messages sometimes not getting overridden correctly

### ISSUE THREAD

**Issue by MBuchalik** [phonegap/phonegap-plugin-push#1214]
I am sending two messages using GCM to my Android phone.

### Expected Behaviour
The second notification overrides the first one.

### Actual Behaviour
This seems to happen only after restarting the device: Sometimes, the second message is shown. Sometimes, the first one is shown. And sometimes, the "wrong" badge number is shown (so if message 1 is shown, it still shows the badge number of the second notification and vice versa).

#### Steps to Reproduce 
Restart the device. While it is loading, send yourself two messages. I have created a small php script that allows me to test it easier - you can find it below.

It is a bit unfortunate: I cannot find out when this happens. As stated above - this seems to happen "randomly". But I have only managed to reproduce this after the device was restarted. It seems like most of the times the message gets overridden correctly - but in approximately 1 out of 3 messages, the wrong one is shown.
What I do all the time: airplane mode is turned on and wifi is turned off. Then I restart the device, turn off airplane mode to enter my PIN, turn it back on and then I turn on wifi.

The last time I managed to get this behavior, I did the following:
Send myself a test message, click on it so that the app opens. Then, close the app and turn off wifi. Restart the device and call the php script below two times with a delay of maybe 4 seconds - one time with the count set to 1 and the other time with the count set to 2. When the device is turned back on, turn off airplane mode, enter PIN code, turn it back on, turn on wifi and wait. I can see that the two messages arrive: There is a short animation in the status bar showing me the title of the two messages. At first, the message "This is message 2" appears and is replaced by "This is message 1". The badge, however, is 2. So, in the end, I see "This is message 1" and the badge "2" on my application's icon.

Have you experienced something similar? I am not a developer for native Android code but this looks a bit like a race condition to me. Is there anything I can to to prevent it (or to assist you with finding the reason for this behavior)?

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung (Galaxy Alpha)

#### Cordova CLI version and cordova platform version

PGB with cli-6.3.0

#### Plugin version

1.8.1 (from NPM)

#### Sample Push Data Payload
See below

#### Sample Code that illustrates the problem
The script I used to test it:
``` php
define( 'API_ACCESS_KEY', 'My gcm access key' );


$registrationIds = array("my registration ID" );

$count = 0;
if(isset($_REQUEST['badge']))
	$count = $_REQUEST['badge'];
$msg = array
(
    'message'       => $count .' unread messages',
    'badge' => $count,
    'title'         => 'This is message ' . $count,
    'vibrate'   => 1,
    'sound'     => 1,
    'ledColor' => array(0, 255, 255, 255)
);

$fields = array
(
    'dry_run' => false,
    'registration_ids'  => $registrationIds,
    'data'              => $msg
);

$headers = array
(
    'Authorization: key=' . API_ACCESS_KEY,
    'Content-Type: application/json'
);

$ch = curl_init();
curl_setopt( $ch,CURLOPT_URL, 'https://android.googleapis.com/gcm/send' );
curl_setopt( $ch,CURLOPT_POST, true );
curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fields ) );
$result = curl_exec($ch);
curl_close($ch);
print_r($result);
```
The response from GCM shows no errors. But this can't be the problem anyways since both messages arrive on the device for sure - the badge number wouldn't be 2 and the message "This is message 1" if one of the messages didn't arrive on the device.

**Comment by macdonst** [comment]
@MBuchalik just to make sure I completely understand what is being asked here, you take your device off the network then send two messages to the device. Sometimes you only see the second message replaces the first but other times the first message replaces the second?

**Comment by MBuchalik** [comment]
@macdonst Correct. Additinally: Sometimes, a mix of both messages can be seen. Let me explain it using an example.

Let's say I send the following messages:
**message 1**
title: "This is message 1"
badge: 1

** message 2 **
title: "This is message 2"
badge: 2

What I sometimes see on my device:
title: "This is message 1"
badge (on the application's icon): 2

I hope this made it a bit clearer - if not, I can try to clarify it :smiley:


It only happens after turning the device off and on again. So: I turn my device off. Then, I send myself these messages. Then, I turn my device on again and see this "random" behavior when the messages arrive. Is there anything I can to to prevent this from happening?

**Comment by macdonst** [comment]
@MBuchalik yeah, it makes sense to me now. Thanks for the clarification. What you actually need to do is use [`collapse_key`](https://developers.google.com/cloud-messaging/http-server-ref#downstream-http-messages-json). 

> If the device is connected but idle, the message will still be delivered right away unless the delay_while_idle flag is set to true. Otherwise, it will be stored in the GCM servers until the device is awake. And that's where the collapse_key flag plays a role: if there is already a message with the same collapse key (and registration ID) stored and waiting for delivery, the old message will be discarded and the new message will take its place (that is, the old message will be collapsed by the new one). However, if the collapse key is not set, both the new and old messages are stored for future delivery.

So in your PHP code you would need to add `collapse_key`:

```
$fields = array
(
    'dry_run' => false,
    'collapse_key' => $key,
    'registration_ids'  => $registrationIds,
    'data'              => $msg
);
```

That should take care of this from the server side.

**Comment by MBuchalik** [comment]
@macdonst Thank you! I think that did the trick :+1: 
I have tried it a couple of times now and the correct message seems to be shown every time :smiley:
