### ISSUE TITLE
[iOS] Notifications not showing when the app is force closed

### ISSUE THREAD

**Issue by jdhinten** [phonegap/phonegap-plugin-push#1217]
So basically I figured out how to implement the push notification system on both iOS and Android. 
The only problem I have is that on iOS the notification is not being received when the app is force closed and isnt running. Is there any simple way to fix this? I have some basic skills with javascript and everything but zero with the programming for iOS in Xcode. Hopefully someone has a solution to this problem. 

Thanks in advance.

**Comment by ricardokdz** [comment]
Me too.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

Also, this issue sounds a lot like what is described in #158 

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by chamerling** [comment]
Hi,

It looks like this is an autostart issue: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#huawei-and-xiaomi-phones

Worked for me on Xiaomi.
