### ISSUE TITLE
Notification icon on iOS shows phonegap default icon instead of the app icon

### ISSUE THREAD

**Issue by yoav-zibin** [phonegap/phonegap-plugin-push#1218]
### Expected Behaviour

Show the app icon when a push notification arrives.

### Actual Behaviour
Phonegap icon is displayed (no idea where it even came from), see printscreen: 
![5a1479a2-3cd4-43d1-bfd6-6041b37c8f3b](https://cloud.githubusercontent.com/assets/1890589/18491321/cfed64da-79d3-11e6-88cc-5745babd1569.PNG)

### Reproduce Scenario (including but not limited to)

I use phonegap build with this repo:
https://github.com/yoav-zibin/friendlygo-phonegap/tree/master/www
Note that my icon have .pgbomit to save space. 

Maybe that's causing the issue?

Will passing icon in the payload (as described for android) work on iOS?

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10 :)

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Works fine on Android.

#### Cordova CLI version and cordova platform version
cli-6.3.0

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version
1.8.1
gap:plugin name="phonegap-plugin-push" source="npm" spec="1.8.1"

#### Sample Push Data Payload
{"message":"Your turn\nGuest-872 just played","count":3,"additionalData":{"matchId":"3297837026043734190","updatedTimestampMillis":"1473799221807","foreground":true,"coldstart":false,"notId":"2029297307","matchInfoJson":"..."}}

**Comment by yoav-zibin** [comment]
BTW, you can reproduce the issue with the live app here:
https://itunes.apple.com/us/app/ycheckers/id1105953393?mt=8

I really have no clue where it took the default phonegap icon from :)

**Comment by macdonst** [comment]
the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.

**Comment by fredgalvao** [comment]
By looking at your [config.xml](https://github.com/yoav-zibin/friendlygo-phonegap/blob/master/www/config.xml), which by the way is placed in the wrong spot (it should be in the project root, instead of inside the `www` folder), I see you're pointing [here](https://friendlygo.com/?phonegapPlugins=v102) for your content. Digging deeper, on [this js file](https://friendlygo.com/js/everything.min.js), I can see that this is your registration code (unminified and beautified):
```js
var a = p.PushNotification.init({
    android: {
        senderID: "24803504516",
        clearNotifications: !1
    },
    ios: {
        alert: !0,
        badge: !0,
        sound: !0,
        clearBadge: !0
    },
    windows: {}
});
```

And the lack of `android.icon` there says that "I don't want to specify any icon for my notifications", according to the usage described [here in the docs](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#android).

### Conclusion

You should try actually specifying the icon property and see if it obeys you as one would expect.

What should be the behaviour if you don't specify it? Should it be blank? No icon at all? Search for a default one (it's probably doing this option right now, it seems)? I honestly don't know.

**Comment by yoav-zibin** [comment]
I really appreciate the quick replies :)

It's actually working fine on android (even without android.icon).
The problem is on ios :)
I unzipped the IPA and I think I figured out the issue and it's indeed a phonegap build issue: I didn't specify a "3x" icon so they used the default icon for AppIcon29x29@3x.png .

BTW, last question: 
will passing "image" on the payload work on ios?
For example, the docs say this works on android, but they don't mention ios:
         "title": "Large Icon",
        "message": "Loaded from URL",
        "image": "https://dl.dropboxusercontent.com/u/887989/antshot.png"

It would be awesome if it worked for ios too :D



See working example on android:
![screenshot_20160913-175832](https://cloud.githubusercontent.com/assets/1890589/18492913/d92684f2-79db-11e6-875b-65cca424261d.png)

**Comment by macdonst** [comment]
@yoav-zibin no, it won't work on iOS as that OS doesn't allow you to change the push notification icon. It only uses your app icon.

**Comment by stileinverso** [comment]
Same problem here!
**In iOS** the push notification icon is the PGB default icon, not the app icon (in Android I can see the app icon instead).
How can I fix it in iOS?
Is there a link to show me how I can use the app icon with push notification?
![img_0003](https://cloud.githubusercontent.com/assets/6285444/19240560/3a6e58c2-8f0b-11e6-918a-572a4938014b.PNG)

**Comment by tejit2004** [comment]
Same issue here, any solution?

**Comment by lpender** [comment]
PhoneGap may need to add support for notification icon sizes:

https://developer.apple.com/ios/human-interface-guidelines/graphics/app-icon/

![image](https://user-images.githubusercontent.com/1406554/29226107-c928c614-7e9e-11e7-9383-f9ee8eb4cffa.png)

I'm passing the icon sizes but seeing this:

![image](https://user-images.githubusercontent.com/1406554/29226116-d2185820-7e9e-11e7-86f5-a34663ed4ca5.png)

**Comment by lucasalima** [comment]
Anyone found a solution for this issue? I'm facing the same situation of you guys. PLEASE HELP!
