### ISSUE TITLE
FCM branch how to use the google-services.json

### ISSUE THREAD

**Issue by slimsami** [phonegap/phonegap-plugin-push#1219]
### Expected Behaviour

Uploading stats to Firebase console
### Actual Behaviour

Not working
### Reproduce Scenario (including but not limited to)

google-services.json put on the project folder
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 
#### Plugin version

 2.0.0 (compiled with custom code added)
#### The Question

How can we add the google-services.json to the plugin to get the stats on the console.
If the plugin is compiled and then added to the project, do we have to add the json at the end before the cordova build or on the plugin directory?

**Comment by jcesarmobile** [comment]
Right now the google-services.json is not used, we should create a hook that copies it to the Android project

**Comment by Eccenux** [comment]
In case some is looking for the Sender ID to configure the plugin then it is in the `google-services.json`:
```json
{
  "project_info": {
    "project_number": "[SENDER ID]"
...
```

**Comment by macdonst** [comment]
Now explained at: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements
