### ISSUE TITLE
Android: possibility to send a notification with a title and without message

### ISSUE THREAD

**Issue by slorber** [phonegap/phonegap-plugin-push#122]
If the notification only has a title and message == "", it is not displayed in the status bar when the app is in background.

I'm not sure but I think it may make sens to display notifications in the status bar with only a title no?

**Comment by macdonst** [comment]
@slorber re-test with the upcoming 1.3.0 release and re-open if it doesn't fix your issue.

**Comment by slorber** [comment]
ok thanks, just ping me when it's released :)
