### ISSUE TITLE
iOS 10 Background Issue

### ISSUE THREAD

**Issue by embarbosa** [phonegap/phonegap-plugin-push#1222]
Hi there

The Plugin stopped to call the callback function when an user clicks on App Notification (when the iPhone is locked).
Does it happen just in my app or it is a problem for anyone in iOS 10?

Thanks!

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
