### ISSUE TITLE
All pending notifications Clear when the app is opened - or brought to foreground from background

### ISSUE THREAD

**Issue by martyzz1** [phonegap/phonegap-plugin-push#1223]
### Expected Behaviour

I'd like notifications to remain in the shade on ios and android until a user clears them or I choose to do so programattically

### Actual Behaviour

All pending notifications clear when app opens

Is this normal behaviour?

**Comment by fredgalvao** [comment]
According to [the docs](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md), you can change that **on android** by setting `android.clearNotifications` to `false` in your init options.

**Comment by martyzz1** [comment]
yeah, it wasn't working, but I think it was a weird caching issue... having cleared cache and data and then uninstalled the app before reinstalling it now works...
