### ISSUE TITLE
Can i turn off push notfications for a specific type/module based upon the payload data?

### ISSUE THREAD

**Issue by chaitanyagupta76** [phonegap/phonegap-plugin-push#1229]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by fredgalvao** [comment]
What exactly do you mean by `type/module`?

**Comment by chaitanyagupta76** [comment]
Hi,
Thanks for your response. My application is having different modules. Is
there any way I can mute push notification. not even showing on
notification drawer. Like the way WhatsApp does for particular chat/group.

**Comment by chaitanyagupta76** [comment]
I want to mute notifications for specific modules based on the user choice.

**Comment by macdonst** [comment]
@chaitanyagupta76 that's not done on the device side that is done on the server side. When your user makes a choice not to receive a particular type of notification then you send that info up to your app server. Then when you go to send that type of notification you omit that device.
