### ISSUE TITLE
INVALID_REGISTRATION when http post request with to IOS

### ISSUE THREAD

**Issue by serohh** [phonegap/phonegap-plugin-push#123]
Returns ;
register success: <1234 sdsdsd asasasa 343dwd sdsd33 sdsd3d3d d4139f26 e02c10f4>

But gives INVALID_REGISTRATION error when i try to make a post request with this token without spaces(1234sdsdsdasasasa343dwdsdsd33sdsd3d3dd4139f26e02c10f4) 

Any ideas?

**Comment by bluejamesbond** [comment]
Same. How did you solve it?
