### ISSUE TITLE
[iOS] Notifications not showing when the app is force closed

### ISSUE THREAD

**Issue by jdhinten** [phonegap/phonegap-plugin-push#1231]
The expected and desired behaviour is when the push notification is send the notification is shown on the devices whether the application is running in the background or not.

The actual behaviour is that on iOS the notification is only shown if the app is running in the background. if it is force closed or not running at all the notification isnt shown/not arriving. It works perfect on android.

the platform on which this is tested is iOS 9.3.5 using phonegap version 6.2.9 and the plugin version is 1.7.4

The way I implemented the plugin is too use javascript to register the device and send the token to a database using php. this is the code that I use:

```
document.addEventListener("deviceready",onDeviceReady,false);
function onDeviceReady(){
  alert("Device Ready")
  var push = PushNotification.init({
    android: {
      senderID: "XXXXXXXXXXX"
    },
    ios: {
                                   
      alert: "true",
      badge: "true",
      sound: "true",
      senderID: "XXXXXXXXX",
     gcmSandbox: "true"
    },
    windows: {}
  });
  push.on('registration', function(data) {
   alert(data.registrationId);
   $("#regid").val(data.registrationId);
 });
  push.on('notification', function(data) {
  });
  push.on('error', function(e) {
  });
}
$(document).ready(function() {
  $("#submit").click(function() {
    var regid = $("#regid").val();
    var name = $("#name").val();
    var email = $("#email").val();
    alert(regid);
    alert(name);
    alert(email);
    $.ajax({
      url: "url to php file",
      type: "POST",
      dataType:'text',
      data: {regid: regid,name: name,email:email},
      success: function(data){
        alert(data);
      }
    });
  });
});
```

and then using php again to send the info to google cloud messaging, for which i use this code:

```
<?php

$servername = "server";
$username = "username";
$password = "password";
$dbname = "name of database";

$conn = mysqli_connect($servername, $username, $password,$dbname);

$registrationIds = array();
$result = mysqli_query($conn, "SELECT * FROM gcm");
if (mysqli_num_rows($result) > 0) {

while ($row = mysqli_fetch_assoc($result)) {
    
    $registrationIds[] = $row["regid"];
}
} else {
echo "0 results";
}

mysqli_close($conn);

define( 'API_ACCESS_KEY', 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' );

$msg = array(
        'body'  => "message text",
        'title'     => "message title",
        'vibrate'   => 1,
        'sound'     => 1,
		"priority" => "high",
		"content_available" => true,
		"badge" => 1,
    );
$fields = array(
            'registration_ids'  => $registrationIds,
            'notification'      => $msg
        );

$headers = array(
            'Authorization: key=' . API_ACCESS_KEY,
            'Content-Type: application/json'
        );
$ch = curl_init();

curl_setopt( $ch,CURLOPT_URL, 'https://android.googleapis.com/gcm/send' );

curl_setopt( $ch,CURLOPT_POST, true );
curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fields ) );

$result = curl_exec($ch );


curl_close( $ch );
echo $result;
?>
```

I have no clue what to do next and this is the only problem that needs to be solved before the app is finished. any suggestions are welcome. 

thanks in advance.

**Comment by macdonst** [comment]
@jdhinten just to clarify, what you are saying, when the app has been killed and you send a message via GCM on iOS the message never arrives in the notification shade?

**Comment by jdhinten** [comment]
Indeed thats the problem i am facing. On the android phones i tested it on it worked perfect

**Comment by macdonst** [comment]
@jdhinten yeah, I'm not sure what to tell you at this point. I'm not a huge fan of GCM on iOS. When you can try is setting priority to high in the right spot of your payload.

```
$msg = array(
        'body'  => "message text",
        'title'     => "message title",
        'vibrate'   => 1,
        'sound'     => 1,
        "content_available" => true,
        "badge" => 1,
    );
$fields = array(
            'registration_ids'  => $registrationIds,
            'notification'      => $msg,
           "priority" => "high",
        );
```

There is and issue over on the GCM repo: https://github.com/google/gcm/issues/103

**Comment by redbird19** [comment]
I'm experiencing the same thing, the notification is never received/shown when the app is closed.  If the app is open, it does work though.  

I'm using an older version of the plugin though, and just started looking into things after some of my users reported not reveiving their notifications.  It seems like nearly every time there's an iOS version update, it breaks the push functionality of my app, very frustrating...

Another piece of information that might be helpful, while I never receive the notification when the app is closed, the badge number on the app icon does get updated correctly.  So it's like it's partially working, any ideas?  I'm gonna try to jump to the latest version of the plugin and see if that works.

**Comment by abdohossam5** [comment]
same issue with ios 10 using the latest plugin version. for me the badge doesn't even get updated.

**Comment by ivanpetrov16130** [comment]
Same problem (iOS 8, 9, 10). 
"Foreground" & "background" modes work as expected, but OS doesn't even show notifications for "killed"(Home+Swipe Up) app. Another strange behaviour: if you send notifications while app is killed and then run it, sent notifications are delivered sometimes(very rarely, 1/80 chance). 
Tried both own server and Firebase console. 
Setting "priority" property to "high"  resolves the problem, but it's unwelcome solution.

**Comment by abdohossam5** [comment]
fixed my issue by setting apns priority to 10

**Comment by jdhinten** [comment]
yeah setting the priority to high in the correct part of the payload worked perfect thanks alot for the help.
