### ISSUE TITLE
App design issue

### ISSUE THREAD

**Issue by mbachaalani** [phonegap/phonegap-plugin-push#1234]
Hello,

I had a version of cordova 4.0.2 and when I wanted to publish to the play store I could not because this version has security vulnerabilities. So I updated to version 5.2.2 but when I did that the app font and components zoomed in and the view was larger on each page (this happened for new devices like note5, htc, samsung S7, LG G2 but for older devices samsung S3 there is no problem). When I upgraded to 5.2.2, I was forced to update to the new push plugin. However when I found out it was causing the design issues I've removed it and the design was fixed on the devices. 
What is the source of the problem with the new push plugin with the rendering of new android devices?

btw: I am using media queries to render elements specifically for each group of devices.
Please I need help with this issue.
Thank you.

**Comment by macdonst** [comment]
@micholine how did it create design issues? I can't imagine that being possible as the push plugin doesn't include any CSS or HTML to mess with your design.

**Comment by andreszs** [comment]
If I were in your situation, I would try this:

1. Install at least cordova 6.1.1.
2. Create a new blank project.
3. Add all your relevant files to the project, but keep the headers and CSS created by cordova 6 or your IDE.
4. Test the app without the push plugin.
5. If everything looks good, proceed to install the push plugin.

I know this process is very tedious and time-consuming, but for me this is the only solution when migrating from major cordova versions and everything else fails.
