### ISSUE TITLE
Additional image on iOS 10 push notifications

### ISSUE THREAD

**Issue by skyprimer** [phonegap/phonegap-plugin-push#1237]
Today i've received a notification with an image..

Is this possible with our plugin?

(iphone SE with iOS 10)

![push-image](https://cloud.githubusercontent.com/assets/6178973/18750254/0b974940-80e3-11e6-8bb3-33c0bdfe6a97.jpg)

**Comment by skyprimer** [comment]
https://www.leanplum.com/blog/push-notification-updates-ios-10/

**Comment by macdonst** [comment]
Go click the 👍 button on #1221
