### ISSUE TITLE
RegistratioId return "MESSENGER"

### ISSUE THREAD

**Issue by AndreVicenteW** [phonegap/phonegap-plugin-push#1238]
When I use the plugin in android I recive "MESSENGER" in registrationId.
It's happens all plugin versions.
I'm using android 4.4.2

            `var push = null;
                push = PushNotification.init({
                    android: {
                        senderID: "56XXXXX", 
                        vibrate: true
                    },
                    ios: {
                        alert: "true",
                        badge: "true",
                        sound: "true",
                        vibration: "true",
                        senderID: "56XXXXX",
                        gcmSandbox: "true"
                    },
                    windows: {}
                });

                push.on('registration', function (data) {
                    console.log('registation');
                    console.log(data.registrationId);
                });`

**Comment by macdonst** [comment]
@AndreVicenteW that's weird. Are you talking to a GCM endpoint or FCM endpoint?

**Comment by AndreVicenteW** [comment]
I verified my senderId in firebase console and google console, it's right.
In August I was using this plugin normally, now I get "MESSENGER" everytime. 
I changed the plugin version to test and always get "MESSENGER"

**Comment by macdonst** [comment]
@AndreVicenteW yeah, we currently do not support FCM. There is a `FCM` branch you can try in the meantime. If you have problems with that branch let us know in issue #929

**Comment by AndreVicenteW** [comment]
I tested to follow https://developers.google.com/cloud-messaging/android/android-migrate-fcm but same error.
So I just created a new project and now the registrationId is comming right. Without or importing to FCM the projects now is working
