### ISSUE TITLE
Unregister not working. Returns success but still receive notification

### ISSUE THREAD

**Issue by rmabunga** [phonegap/phonegap-plugin-push#1239]
### Expected Behaviour

Not receive a push notification after calling the unregister.
### Actual Behaviour

Still receives push notification
#### Steps to Reproduce

Use the unregister api.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 9
#### Cordova CLI version and cordova platform version

```
cordova --version                                    # e.g. 6.0.0
cordova platform version android                     # e.g. 4.1.1
```
#### Plugin version

```
cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3
```

push = PushNotification.init({
        "android": {"senderID": ###########},
        "ios": {
          "senderID": ###########,
          "alert": true,
          "badge":true,
          "sound": true,
          "gcmSandbox": true
        },
        "windows": {}
      });
#### Sample Code that illustrates the problem

pushNotificationInstance.unregister(function() {
        console.log('success unregister');
      }, function() {
        console.log('error unregister');
      });

Its printing success, but Im still receiving notifications.
#### Logs taken while reproducing problem

Here at unregister
success unregister
Push Plugin register called
PushPlugin.register: setting badge to false
PushPlugin.register: clear badge is set to 0
PushPlugin.register: better button setup
GCM Sender ID ###########
Using GCM Notification
Using GCM Sandbox
Push Plugin register success: <###### ###### ###### ###### ###### ###### ###### ######>

**Comment by malwatte** [comment]
GCM unregister is not recommended. I saw this in GCM docs and could not find the exact place. You need to have a service to unregister from your services and remove token from your database, not GCM unregister.

**Comment by macdonst** [comment]
@rmabunga it may take a bit before GCM invalidates that token. The success method just tells you that GCM has received your wish to remove the token from it's DB. As @malwatte said you should remove the token from you app server on the success method of unregister.
