### ISSUE TITLE
How do I determine if app was launched from the notification bar?

### ISSUE THREAD

**Issue by andreszs** [phonegap/phonegap-plugin-push#1243]
Hi can I find out if the app was opened by clicking the **app's icon** or the **received notification** from the notifications bar? The parameters `.coldstart` and` .foreground `are not really useful, we need to know the who triggered the app's initialization. Thanks.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by jourdan-jobox** [comment]
@andreszs Did you figure this out?
