### ISSUE TITLE
[Question] How to set dynamic large icon?

### ISSUE THREAD

**Issue by jhlee8804** [phonegap/phonegap-plugin-push#1246]
Thanks to useful plugin!

I wanto set user thumbnail image to large icon, but how can i do?

I know set image key to gcm data payload([link](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images)), but my mobile server needs to authentication(JWT).

How can i do?

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
