### ISSUE TITLE
undefined message on Android

### ISSUE THREAD

**Issue by rooz121359** [phonegap/phonegap-plugin-push#1247]
I'm using this plugin for ios and android. it works fine on ios.

However, on android I get an undefined for message.

The message comes through properly and I can see it when the app is closed and I see the notification at the top of my android device.

but the undefined message happens only when the app is open and the `alert(data.message);` comes through!

this is my entire code:

```
document.addEventListener("deviceready",onDeviceReady,false);
function onDeviceReady(){
console.log("Device Ready")
var push = PushNotification.init({ "android": {"senderID": "32732xxxxxxx"},
"ios": {"alert": "true", "badge": "true", "sound": "true"}, "windows": {} } );

push.on('registration', function(data) {
console.log(data.registrationId);
$("#gcm_id").html(data.registrationId);

});

push.on('notification', function(data) {
console.log(data.message);

alert(data.message);

//alert(data.title+" Message: " +data.message);
// data.title,
// data.count,
// data.sound,
// data.image,
// data.additionalData
});

push.on('error', function(e) {
console.log(e.message);
});
}
```

**Comment by jhlee8804** [comment]
How to send your gcm message via server?

**Comment by rooz121359** [comment]
I'm using PHP to send the message to server.

**Comment by macdonst** [comment]
@rooz121359 we really need to see the payload you send to the device and also if you could get some logs following the instructions in the issue template that would be great.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
