### ISSUE TITLE
LogCat "Error Uncaught ReferenceError: module is not defined in push.js" (Android < 5)

### ISSUE THREAD

**Issue by Gionni** [phonegap/phonegap-plugin-push#1250]
Hi,

after one year with an old cordova and the deprecated plugin in production, I just migrated to newest versions.

    cordova --version                               6.3.1
    cordova platform version android      5.2.2
    cordova plugin version | grep phonegap-plugin-push   1.8.2

Unfortunately, while a LG Android 5.0 device is 100% successful, the old usual Android 4.2.2 chinese device does not let my app start and reports "module is not defined at file push.js".

Is there any reason? I can't believe there is no retro compatibility.

Thanks for any hint, Gionni

**Comment by macdonst** [comment]
@Gionni it should work just fine on 4.2.2. The oldest device I have to test on is running 4.4 right now. It is possible that your Chinese device does not include Google Play Services, can you check that? Although, the error that you describe seems to indicate there is not push.js on the 4.2.2 device. Are you building both from the same project?

**Comment by Gionni** [comment]
Obviously, same project (unique source). Otherwise, I should not ask.

The problem is "module.exports = { ..." in push.js, Android 4.2.2 sees only typeof module as 'undefined'...

**Comment by Gionni** [comment]
In order to be chirurgical accurate, I'm now on all newest things as for Android SDK except extras-google-play-services still ver. 28 (5 Nov 2015).

**Comment by Gionni** [comment]
That's really weird but, after 2 days of doing nothing, today 4.2.2 reports still error at that line of push.js but anyhow goes on and handles notifications perfectly, just like 5.0

Weird. I'll close issue very soon.
