### ISSUE TITLE
[Android] deviceId persists between uninstalls, but is invalid after an uninstall.

### ISSUE THREAD

**Issue by spencerwi** [phonegap/phonegap-plugin-push#1251]
### Expected Behaviour
1. Application registers with GCM, gets a deviceId, which can be used to push notifications.
2. User uninstalls Application at some point, and GCM invalidates the deviceId, and the deviceId is discarded from the device's storage, since it's no longer valid (see https://developers.google.com/cloud-messaging/registration )
3. User reinstalls Application, which registers anew with GCM, and gets a new deviceId, which can be used to push notifications.
### Actual Behaviour
1. Application registers with GCM, gets a deviceId, which can be used to push notifications.
2. deviceId is stored in Shared Preferences, which persist between uninstalls.
3. User uninstalls Application at some point, and GCM invalidates the deviceId, but Shared Preferences (along with the now-invalid deviceId) persist.
4. User reinstalls Application, the Phonegap Push Plugin sees the old invalid deviceId, so it does not re-register with GCM. Device is unable to receive notifications.
### Reproduce Scenario (including but not limited to)
- An Android user has installed the app at one point, uninstalled it, and after some time re-installs the app.
#### Steps to Reproduce
1. Install an application which registers with Google Cloud Messaging onto an Android device.
2. Uninstall the application after it registers with GCM.
3. Allow some time for the deviceId to be invalidated (Google notes that it's not an immediate step; however, this time period is certainly long enough for a user who uninstalled the app to later decide to re-install).
4. Re-install the application, and see that the old, invalid deviceId is returned and a new GCM registration is not requested.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android, all (to my knowledge -- observed on 7.0 and 6.x)
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

All; observed on Nexus 6P and Nexus 6.
#### Cordova CLI version and cordova platform version

```
cordova@6.2.0
cordova-android@5.0.0
```
#### Plugin version

```
phonegap-plugin-push 1.8.2 "PushPlugin"
```

**Comment by macdonst** [comment]
@spencerwi thanks for the excellent bug report.

**Comment by spencerwi** [comment]
No problem! Just running into this issue in my employer's app, and hoping to minimize/correct its impact on users.

**Comment by malwatte** [comment]
I think Shared Preferences is not persistent between uninstalls.
Please correct me if I am wrong.

**Comment by allanpoppe** [comment]
Any news in this issue? I can't send push notifications to users that have reinstalled the app.

**Comment by spencerwi** [comment]
@malwatte Ah, okay. So the backups are what's causing the cache to persist across uninstalls? I can't seem to figure out why, but somehow the same deviceId is being shortcut-fetched from cache (no web request, same deviceId returned) even after I uninstall and reinstall.

**Comment by malwatte** [comment]
@spencerwi I had faced similar issue relevant to Shared Preferences. And it was not about this plugin. I assumed cause for this issue is the same.
I am using this plugin as well and I have not tested uninstall and installed in a Android M device. Please let me know if setting android:allowBackup="false" worked for you.
Thanks.

**Comment by spencerwi** [comment]
@malwatte Thanks! I'll give that a shot to see if that helps.

**Comment by malwatte** [comment]
@spencerwi 
Tested in a Galaxy S5 (Android 6.0.1).  App gets new deviceId after uninstall and install. No issue. Did not even set android:allowBackup="false".
Hmmm. Weird.

Steps I followed
1. Installed the app and got the deviceId
2. Sent a push. Push received
3. Uninstalled the app.
3. Sent a push. Got "NotRegistered" error from GCM
4. Installed the app again. A new deviceId received
5. Sent a push. Push received

**Comment by spencerwi** [comment]
Maybe it's a device/version-specific thing; I tested on a Nexus 6p running Android 7.0.

**Comment by allanpoppe** [comment]
I tested App reinstall on 3 devices:

- Motorola Moto X 2014 with Android 6.0: Push stop working
- Samsung Galaxy S6 Edge with Android 6.0.1: Push stop working
- Samsung Galaxy S5 Neo with Android 6.0.1: Push **has not** stop working

I made a hook to add the android:allowBackup="false" in the AndroidManifest application tag and will test on production this week.

**Comment by malwatte** [comment]
Any updates?

**Comment by allanpoppe** [comment]
I can confirm that after adding android:allowBackup="false" as explained above, the two devices that had problems receiving notifications after a reinstall are now receiving them again.

**Comment by malwatte** [comment]
@allanpoppe ,
Good to hear that it fixed. Appreciate if you can share the hook.
Thanks

**Comment by macdonst** [comment]
@spencerwi @malwatte okay, as part of 1.8.4 I removed the code that persists the registration ID to shared preferences. It will request a token from GCM each time the init method is called now instead of checking for a cached version.

You won't need to turn off backup in your app with that version of the plugin.
