### ISSUE TITLE
Enahancement : Add custom permission for PushHandlerActivity 

### ISSUE THREAD

**Issue by Vabs28** [phonegap/phonegap-plugin-push#1252]
Hi

I work on a Banking App. And before every release we send our App for Pen testing. 
One of the finding from pen testing is Push Handler Activity being exported. 
I understand it is the requirement of Push Plugin. 

To fix this issue we create custom permission to access Push Handler Activity and add signature level protection. This blocks access to Push Handler Activity from external Apps and still continues to work. 

Can we do same changes in plugin as well ?

**Comment by macdonst** [comment]
@Vabs28 this seems like a really good candidate for a PR.

**Comment by Vabs28** [comment]
@macdonst Thanks. I will do it

**Comment by Vabs28** [comment]
@macdonst I have raised a PR and tested it on different devices. Please approve #1362

**Comment by macdonst** [comment]
Merged, closing
