### ISSUE TITLE
[Question] Is it possible to get more than 3 action buttons on Android notifications?

### ISSUE THREAD

**Issue by mikepsinn** [phonegap/phonegap-plugin-push#1254]
Android seems to ignore any additional ones that I try to add. 

Does anyone know if that's a hard limit of the platform?   I'm wondering if I should try to modify the plugin to support this or if all such efforts would be futile?

**Comment by macdonst** [comment]
@mikepsinn Android maxes out at 3 buttons. You can see that in the Android API docs: https://developer.android.com/reference/android/app/Notification.Builder.html#addAction(int, java.lang.CharSequence, android.app.PendingIntent) but I'll add it to the plugin docs as well.

**Comment by mikepsinn** [comment]
Thanks for the info! :D
