### ISSUE TITLE
[Question] Is it possible to show a notification for each push message on Android?

### ISSUE THREAD

**Issue by NickAdriaenssens** [phonegap/phonegap-plugin-push#1255]
On iOS a notification is shown for each push message, this is not the case for Android. Is it possible to have the same behaviour on Android or is this an Android convention?

**Comment by ef33zy** [comment]
Hi @NickAdriaenssens read through [this section](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#stacking), I think the regular stacking should do it. Not the inbox style.
