### ISSUE TITLE
Make permission request optional

### ISSUE THREAD

**Issue by russx2** [phonegap/phonegap-plugin-push#1257]
Beginning with iOS 8 (according to this post, and confirmed by my own experimentation of declining the permission and still receiving silent pushes, http://blog.parse.com/learn/ready-for-ios-8-so-is-parse-push/) push notification permissions are not required for silent pushes.

I have an app that only needs silent pushes and so I'd rather not run the "ask for permission" routine when it's not required. However, the register method doesn't seem to have any option for this so it'll always prompt for a permission I don't need.

**Comment by macdonst** [comment]
@russx2 I don't think that is correct. By default you'll get silent pushes even if you say no to the dialog. Try this code:

```
var push = PushNotification.init({
    ios: {
        alert: "false",
        badge: false,
        sound: 'false'
    }
});
```

as it will skip all the UI bits but still allow silent pushes.

**Comment by russx2** [comment]
Thanks for your reply. The thing is, even if I pass those exact parameters, I still get the permission dialog ("X Would Like to Send You Notifications"). I only need to send silent notifications and so I therefore I don't want the user to see receive this permission request.

Can you clarify that what I'd like is in fact the expected behaviour? In which case I'm either doing something wrong or this is a bug, correct?

**Comment by macdonst** [comment]
@russx2 yeah, I don't think you can ever avoid the permission dialog on iOS. I've never seen a way to do it even if you only want silent notifications. I think what the article you linked to is trying to say is that you will still get silent notifications even if your user selects `No` to the push permission dialog.

**Comment by russx2** [comment]
Oh right. Thanks for your input. So just to confirm finally this isn't a plugin issue - it's that, if you request a push token using iOS's APIs, it'll always throw a permission prompt? 

So no app can ever send silent notifications without first asking for notifications in general... which doesn't actually apply to the silent notifications. Weird behaviour!

**Comment by macdonst** [comment]
@russx2 to the best of my knowledge that is the case. If you find evidence to the contrary please let me know and we can make some code changes.
