### ISSUE TITLE
$cordovaPushV5:notificationReceived not fired when Android in background

### ISSUE THREAD

**Issue by DimDrop** [phonegap/phonegap-plugin-push#1258]
### Expected Behaviour
When app is not in foreground and a push notification is received, the cordovaPushV5:notificationReceived event should fire.

### Actual Behaviour
The cordovaPushV5:notificationReceived does not fire when app is in background.  Works when app is in foreground.

### Reproduce Scenario (including but not limited to)
Works on iOS. Push notifications are being received by the device and display in the notifications shade but the app is not receiving notice that they ever arrived.

#### Steps to Reproduce 
Send a push message to the device when the app is in background. 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
* Android 6.0
* Android 4.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
* BLU 6.0
* LG Tribute 4.1

#### Cordova CLI version and cordova platform version

    cordova --version = 6.2
    cordova platform version android  = android 5.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push = 1.8.2

#### Sample Push Data Payload
```
{
"title":"Notification",
"message":"hello",
"additionalData":{
  "subject":"Notification Test",
  "notification_type":"message",
  "icon":"myicon",
  "google.message_id":"0:####",
  "custom_app_id":"public",
  "coldstart":false,
  "collapse_key":"com.####",
  "foreground":true
  }
}
```

#### Sample Code that illustrates the problem
```javascript
$cordovaPushV5.initialize( 
            {
                android: {
                    senderID: GCM_SENDER_ID
                },
                ios: {
                    alert: 'true',
                    badge: true,
                    sound: 'true',
                    clearBadge: true
                },
                windows: {}
            }
        ).then(function (result) {
            $cordovaPushV5.onNotification();
            $cordovaPushV5.onError();
            $log.debug("About to register");
            $cordovaPushV5.register().then(function (device_token) {
                $log.debug("Register success with device_token " + device_token);
                registerDevice();
            }, function (err) {
                // handle error
                $log.debug("Error registering device");
            });
        });

        $rootScope.$on('$cordovaPushV5:notificationReceived', function(event, notification) {
            //Never reaches here for Android in background, but works fine for iOS when in background
            //Reaches here for Android when in foreground
            
           $log.debug('Received some notification: ', JSON.stringify([notification]));
            if (ionic.Platform.isAndroid())
            {
                handleAndroid(notification);
            }
            else if (ionic.Platform.isIOS)
            {
                handleIOS(notification);
            }

            $cordovaPushV5.finish().then(function (result) {
                $log.debug('finished notificationReceived RESULT: ' + result);
            }, function (err) {
                // handle error
                $log.debug('finished notificationReceived ERROR: ' + err);

            });
        });

        $rootScope.$on('$cordovaPushV5:errorOccurred', function(event, error) {
            // handle error
            $log.debug('cordovaPushV5:errorOccurred ERROR: ' + error);
        });
```
#### Logs taken while reproducing problem
#App put into background
log >> 78    659833   debug    paused app!
#No output
#Open app back up
log >> 79    676663   debug    Resuming with state: app.list
#No output

**Comment by macdonst** [comment]
@DimDrop yup, that is the correct behaviour. If you want the event to be fired when the app is in the background you need to set the proper value in the payload which is documented here: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications
