### ISSUE TITLE
API Changes for FCM

### ISSUE THREAD

**Issue by edtiley** [phonegap/phonegap-plugin-push#1259]
#### Plugin version
2.0

I'd like to find an XDK compatible plugin for Firebase Notifications that I can use to begin creating a productioni app for Android and IOS.

Is this version of the plugin stable enough for a relatively low volume app?

Are there any changes to syntax for this version of the plugin, and is it necessary to provide IOS provisioning to Firebase?

Thanks,

Ed

**Comment by macdonst** [comment]
@edtiley move you comments on FCM support over to #929.
