### ISSUE TITLE
 It is using in gcm data.additionalData ?	

### ISSUE THREAD

**Issue by eros2187** [phonegap/phonegap-plugin-push#126]
plus data.image , etc. there is a possibility of sending tightens customized using data.additionadata but how? you can see an example of java code must send via gcm thanks

**Comment by macdonst** [comment]
@eros2187 I'm not sure I understand the question. Any key that doesn't match the basic types: message, title, count, sound, image it will end up in additionalData.

**Comment by eros2187** [comment]
have sent a strringa of this type to gcm
 $ response = $ gcpm- > send ( $ message , array ( ' title ' = > $ _POST [ "title " ] , $ additionalData = > additionalData ) ) ; // Push Título do ... //
echo $ response ;
$ additionalData = array ( ' url ' = > ' www.google.com ' , ' image ' = > ' http://exsample/foto/55ee9dac2470d.jpg ' ) ;

Once I receive these data hang them using jquery in html

$ ( " #myid " ) .Append ( " < P > ' + ' < img class = " photo " src = ' + data.additional.url + ' > < / p > ' ) ;

data.additional.url from value indefinited not pass me the value ?
if you use those works data.title works!!

What's wrong ? You can help me
I can have Besides these data.image, , etc. Caunt you can send a customized string ? Example data.url ? can you explain one thing I do not understand what is additionalData  or additionalData.
thanks for your help I await your response joseph greetings and thanks

**Comment by macdonst** [comment]
@eros2187 So for this code to work:

`$ ( " #myid " ) .Append ( " < P > ' + ' < img class = " photo " src = ' + data.additional.url + ' > < / p > ' ) ;`

you would need to use the following code to send to GCM:

```
$ response = $ gcpm- > send ( $ message , array ( ' title ' = > $ _POST [ "title " ] ,
  ' image ' = > ' http://exsample/foto/55ee9dac2470d.jpg ',  
  ' url ' = > ' www.google.com '  ) ) ; 
```

the plugin will recognize the `title` and `image` properties and call the notification event with those items as `data.title` and `data.image`. Since `url` is not recognized property on all platforms it gets put in as `data.additionalData.url`.

When you get a chance to test this and it works please comment and close the issue.

**Comment by eros2187** [comment]
ssa a italiano

I already tried to pass these values ​​and work wanted to know if it was possible to pass other values ​​given . as well as those who are there .. In addition to those available .. You must do using AdditionalData ? If you like ? Or is there another way to pass other values ​​in addition to the date listed in the documentation .. Thanks for your support sincerely Joseph

**Comment by eros2187** [comment]
ssa a italiano

I already tried to pass these values ​​and work wanted to know if it was possible to pass other values ​​given . as well as those who are there .. In addition to those available .. You must do using AdditionalData ? If you like ? Or is there another way to pass other values ​​in addition to the date listed in the documentation .. Thanks for your support sincerely Joseph

**Comment by macdonst** [comment]
You would send:

```
$ response = $ gcpm- > send ( $ message , array ( ' title ' = > $ _POST [ "title " ] ,
  ' image ' = > ' http://exsample/foto/55ee9dac2470d.jpg ',  
  ' url ' = > ' www.google.com ',
  'allegato' => 'some value'  ) ) ; 
```

and it would be available at `data.additionalData.allegato`

**Comment by eros2187** [comment]
Thanks I tried but it does not work there will be a problem with a data.additionalData this point ?

the value of attachment
annexed ' = > ' some value '

some value means that you have any feedback ? thanks regards joseph

**Comment by macdonst** [comment]
@eros2187 I think I know what is going on. Fix to be pushed soon.

**Comment by macdonst** [comment]
@eros2187 re-test with the upcoming 1.3.0 release and re-open if it doesn't fix your issue.

**Comment by eros2187** [comment]
https://github.com/phonegap/phonegap-plugin-push/issues/130
