### ISSUE TITLE
iOS 10 no sound

### ISSUE THREAD

**Issue by atgillette** [phonegap/phonegap-plugin-push#1262]
### Expected Behaviour

Sound when getting notification
### Actual Behaviour

No sound when getting notification
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 10.2
#### Cordova CLI version and cordova platform version

```
cordova --version                                    # 6.3.1
cordova platform version iOS                     # 4.2.1
```
#### Plugin version

```
cordova plugin version | grep phonegap-plugin-push   # 1.8.2
```
#### Sample Push Data Payload

gcmNotification.sound = 'default'

I get sound notification for earlier versions of iOS

**Comment by jcesarmobile** [comment]
Can this be related? 
https://github.com/phonegap/phonegap-plugin-push/issues/1260

Is the sound turned on on the device?

**Comment by atgillette** [comment]
Hi @jcesarmobile,

Sound is turned on the device and I've verified that sound notification is working at least with iMessenger.  The other thing that I just noticed is that if the screen is off and a notification is sent for my app, the screen does not turn on.  But if I press the home button and turn on the screen, I see the notification for my app.  This is only happening on iOS 10.  All other versions are working as expected.

**Comment by jcesarmobile** [comment]
Can you share the code you used to init the plugin?

**Comment by atgillette** [comment]
```
push = PushNotification.init({
      android: {
        senderID    : 'xxxxxxxxxxxx'
      },
      ios: {
        senderID    : 'xxxxxxxxxxxx',
        gcmSandbox  : config.pushNotification[config.selectedEnv],
        alert       : true,
        badge       : true,
        sound       : true
      }
    });
```

**Comment by macdonst** [comment]
@atgillette can you share the full payload of the push you are sending to the device?

**Comment by atgillette** [comment]
@macdonst,
I'm using node-gcm.

```
var gcmNotification = {
                    title     : 'My app',
                    body      : writerName + ' wrote on "' + discussion.topic + '"'
                    sound    : 'default
                  };

                  var message = new gcm.Message({
                    priority    : 'high',
                    notification: gcmNotification
                  });

                  var sender = new gcm.Sender('xxxxxxxxxxxxxx');

                  // Send the message
                  // ... trying only once
                  sender.sendNoRetry(message, { registrationTokens: [pushId]}, function(err, response) {
                    if (err) {
                      console.error('gcm error', err);
                    }
                    else {
                      console.log(response);
                    }
                  });
```

**Comment by atgillette** [comment]
Hi everyone,

Who has successes with notifications on iOS 10?  I'm seeing that for that version, the screen does not activate for notifications that are pushed for my app.  It's only when I wake up my phone, do I see there's a notification.
