### ISSUE TITLE
Phonegap: Building the app via phonegap 6.3.0 for Windows fails

### ISSUE THREAD

**Issue by ThorStan** [phonegap/phonegap-plugin-push#1263]
Hi,

iam getting following issue when trying to build the app via phonegap cli 6.3.0 for Windows (windows: 4.4.1) and plugin spec 1.8.2. with no signing key selected over https://build.phonegap.com.

`Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "phonegap-plugin-push@1.8.2" via npm Installing "phonegap-plugin-push" at "1.8.2" for windows Updating appxmanifests with ToastCapable=true... Failed to install 'phonegap-plugin-push':Error: Cannot find module 'C:\cygwin\tmp\gimlet\<ID>\project\platforms\windows\cordova\lib\AppxManifest' at Function.Module._resolveFilename (module.js:337:15) at Function.Module._load (module.js:287:25) at Module.require (module.js:366:17) at require (module.js:385:17) at module.exports (C:\cygwin\tmp\gimlet\<ID>\project\cordova\plugins\phonegap-plugin-push\hooks\windows\setToastCapable.js:5:24) at runScriptViaModuleLoader (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pgb-plugman\node_modules\pgb-cordova-lib\src\hooks\HooksRunner.js:187:18) at runScript (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pgb-plugman\node_modules\pgb-cordova-lib\src\hooks\HooksRunner.js:165:16) at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pgb-plugman\node_modules\pgb-cordova-lib\src\hooks\HooksRunner.js:133:20 at _fulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pgb-plugman\node_modules\q\q.js:787:54) at self.promiseDispatch.done (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pgb-plugman\node_modules\q\q.js:816:30) Cannot find module 'C:\cygwin\tmp\gimlet\<ID>\project\platforms\windows\cordova\lib\AppxManifest' - You can fix this here`

Any hints how to solve this are welcome.

Thanks,
ThorStan

**Comment by macdonst** [comment]
@ThorStan the PGB team has asked for issues to be raised on the forums instead. 

https://forums.adobe.com/community/phonegap/build
