### ISSUE TITLE
iOS notifications are not received when app is closed (previously registered)

### ISSUE THREAD

**Issue by avizcaino** [phonegap/phonegap-plugin-push#1264]
### Expected Behaviour

Receive notification even with closed application.
### Actual Behaviour

If the app is closed, the notifications are not received.
#### Steps to Reproduce

Send a notification with the app closed (previously registered to GCM service).
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 9
#### Cordova CLI version and cordova platform version

```
cordova --version                            6.3.1
cordova platform version ios           4.1.1
```
#### Plugin version

```
cordova plugin version | grep phonegap-plugin-push  1.8.1
```
#### Sample Push Data Payload

```
{
  contentAvailable: true,
  priority: 2,
  style: 'inbox',
  ledColor: [0, 0, 102, 158],
  notId: '1',
  notification: {
    title: 'Test Push',
    body: 'Push body',
    badge: 0
  }
}
```

**Comment by thsantac** [comment]
Hi,

With iOS 10.0.1 and plugin 1.8.2, this issue is resolved. But there is now another one, which used to work before iOS 10: when app is in background, notifications are received but the onNotification event is more fired...

This issue has been declared one week ago and still not have any answer from the developer...

**Comment by avizcaino** [comment]
@thsantac so I will have to check 1.8.2 with iOS9 to see if my issue is resolved...

Hopefully someone can answer about the other issue you name!

**Comment by macdonst** [comment]
@avizcaino yes, definitely upgrade to 1.8.2 as it fixes an issue in iOS 10. I believe the solution to the problem you describe is documented here:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#gcm-messages-not-arriving

**Comment by avizcaino** [comment]
Well, I've tried with iOS9 and 1.8.2 and is still not working... I'll try later with iOS10, but our requirements specify that we have to make it work with iOS9... Anyone is facing the same problems?

**Comment by macdonst** [comment]
@avizcaino sorry are you using GCM on iOS? If so please updated your payload to set the [priority to high](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#gcm-messages-not-arriving). I believe something has changed in GCM.

**Comment by maa105** [comment]
hello this is happening to me too on IOS, if i send notifications when the app is killed not just background but killed. I get the notification but when i enter the app the notifications does not get processed. I need to click on the notifications to receive them. this is in contrast to Android where if u send a notification while app is killed upon opening the app (not clicking the notification) all the notifications are received. please help.
