### ISSUE TITLE
[Question] How to process silent notification in closed app

### ISSUE THREAD

**Issue by jonatarussi** [phonegap/phonegap-plugin-push#1269]
Hi, there's a way to process a silent notification even if the app is totally closed?

Thanks

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
