### ISSUE TITLE
How to use GCM 3.0 with this plugin?

### ISSUE THREAD

**Issue by bhaveshgohel** [phonegap/phonegap-plugin-push#127]

**Comment by macdonst** [comment]
@bhaveshgohel what is your questions exactly as it is not clear? Are you asking how to send a message from GCM to an app using this plugin or something different?

**Comment by bhaveshgohel** [comment]
@macdonst : In Google IO 2015, they launched [GCM 3.0](https://youtu.be/gJatfdattno).
The API suggest to Register your app and get Instance ID and a token from GCM Server and when you want to send push notification you can simply pass the token and a message payload to GCM Server and it taken care of sending message.

The App working fine with the current method of getting Registration-id and and Getting Push Messages via server. But i'm confuse with the new method in GCM 3.0, what the difference between Instance-id vs Registration-id? and does current version of PushPlugin supporting the new changes in GCM 3.0?

Some Quick Links:
https://developers.google.com/cloud-messaging/registration
https://developers.google.com/instance-id/

Thanks.

**Comment by macdonst** [comment]
@bhaveshgohel Instance ID is analogous to Registration ID. This plugin should work fine with GCM 3.0 for receiving messages but I have not updated the internals to use the new API.

**Comment by bhaveshgohel** [comment]
@macdonst :Thank you... :)
