### ISSUE TITLE
FCM `click_action` support or any other way to send data to closed app

### ISSUE THREAD

**Issue by Eccenux** [phonegap/phonegap-plugin-push#1274]
### Expected Behaviour
Open application and receive data sent with the notification with `push.on('notification'...)`.

See also: https://firebase.google.com/docs/notifications/android/console-device#receive_and_handle_messages

### Actual Behaviour

Without `click_action` in the message, the application is opened, but function registered with `push.on('notification', function(data) {...})` is not called.

With `"click_action":"FCM_PLUGIN_ACTIVITY"` the application is not opened.

#### Steps to Reproduce 

1. Send notification like below (with required `Authorization` and `Content-Type` headers).
2. Click on notification.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Sony Xperia Z5 Compact

#### Cordova CLI version and cordova platform version

PGB: `<preference name="phonegap-version" value="cli-6.0.0" />`

#### Plugin version
```xml
	<preference name="android-build-tool" value="gradle" />
	<plugin name="phonegap-plugin-push" source="git"
		spec="https://github.com/phonegap/phonegap-plugin-push#07fa81b7a3a62400915ac70b9a24a802465a6f95">
		<param name="SENDER_ID" value="..." />
	</plugin>
```

#### Sample Push Data Payload
```
{
	"notification":{
		"title":"Notification title",
		"body":"Notification body",
		"click_action":"FCM_PLUGIN_ACTIVITY",
	},
	"data":{
		"param1":"value1",
		"param2":"value2"
	},
	"priority":"high",
}
```

#### Sample Code that illustrates the problem

Code used in application (I run this from [Chrome's remote console](https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging) when the app is loaded): [push.zip](https://github.com/phonegap/phonegap-plugin-push/files/519883/push.zip)

Micro-server implementation in Node.js: [fcm-server.zip](https://github.com/phonegap/phonegap-plugin-push/files/519881/fcm-server.zip)

**Comment by macdonst** [comment]
@Eccenux what you describe makes sense as expected behaviour. If you specify ` "click_action":"FCM_PLUGIN_ACTIVITY"` then the OS will try to start the activity `FCM_PLUGIN_ACTIVITY` which probably doesn't exist in this case.  

Instead try sending this payload:

```
{
    "data":{
        "title":"Notification title",
        "body":"Notification body",
        "param1":"value1",
        "param2":"value2"
    },
    "priority":"high",
}
```

and let me know if that fixes the issue.

**Comment by Eccenux** [comment]
Strange. When anything is set in `notification` it doesn't work in background, but when I remove all information then notification data is received in background.

i.e. this doesn't work:
```js
{
	"notification":{
		"sound":"default"
	},
	"data":{
		"title":"Notification title",
		"body":"Notification body",
		"param1":"value1",
		"param2":"value2"
	},
	"priority":"high",
	"content_available": true
}
```

This works:
```js
{
	"notification":{
	},
	"data":{
		"title":"Notification title",
		"body":"Notification body",
		"param1":"value1",
		"param2":"value2"
	},
	"priority":"high",
	"content_available": true
}
```
So seems like every notification should be sent twice currently... Not that good.

`click_action` description for Android in [FCM docs](https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support):

> Indicates the action associated with a user click on the notification. When this is set, an activity with a matching intent filter is launched when user clicks the notification.

**Comment by macdonst** [comment]
@Eccenux why do you think the notification needs to be sent twice? But yes, when sending to an Android device your payload must be in `data` that is well discussed elsewhere in this repo.

**Comment by Eccenux** [comment]
I have to use `notification` to supply additional options (sound, icon...), so I need to send two notifications -- one with options for foreground apps and one for background apps. Or can those be defined differently?

**Comment by fredgalvao** [comment]
Where exactly do the **data-only** notification payload fail for you? It is(or maybe was) known to us up until this point that the **data-only** variant is what works for everything as much as possible. If it's failing in some case, we should fix that case then.

**Comment by Eccenux** [comment]
From the [FCM docs](https://firebase.google.com/docs/cloud-messaging/concept-options#notifications) I though I was supposed to use `notification` for icons and such... I see examples for this plugin differ... So I guess I need to do more testing.

**Comment by romanarrieta** [comment]
I need a notification with click_action, but in cordova, where is name of activity?


I want to do the following:

......
notification":{
        "title":"Notification title",
        "body":"Notification body",
        "click_action":"hello.html",

    },
....

Is it possible??
Thank you

**Comment by AdrienV** [comment]
@Eccenux Yeah !!! Thanks. Since few days I am looking for what my notifications doesn't work good, in my case :  
- White icon
- No redirection when tapped

Your message was very helpful, I just deleted the content in notification, and put everything in "data", now it works, and I don't need to specify any logo. Thanks a lot :)

Like that : 
`{
    "to":"ID-TO-PUSH",
    "notification":{
    },
    "data":{
        "title":"Notification title",
        "body":"Notification body",
        "click_action":"FCM_PLUGIN_ACTIVITY"
    },
    "priority":"high",
    "content_available": true
}`

**Comment by fredgalvao** [comment]
@AdrienV Can you tell us how the documentation at https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads wasn't enough for you? If you had to find an old issue and use it as a solution, it's an indication that the docs are not as clear as it should.
