### ISSUE TITLE
iOS problem with push notification (default PhoneGap icon and no sound)

### ISSUE THREAD

**Issue by stileinverso** [phonegap/phonegap-plugin-push#1275]
### Expected Behaviour
App icon in push notification on iOS device

### Actual Behaviour
PhoneGap icon instead of app icon and no sound on iOS device (in Android all work well, see below)

### Reproduce Scenario (including but not limited to)
I send push notification both for Android and iOS device via PHP code.
The push notification arrives in this way...

**on Android device:**

- [x] App icon
- [x] Title & message
- [x] Big image
- [x] Sound

**on iOS device**

- [ ] **_PhoneGap icon_** (problem)
- [x] Title & body (the only things that work)
- [ ] **_No image_** (problem)
- [ ] **_No sound_** (problem)

#### Platform and Version (iOS v7)
I use PhoneGap Build to compile both Android and iOS apps

#### Plugin version

phonegap-plugin-push (npm)

#### Sample Push Data Payload

    var push = PushNotification.init({    
      android: {
        senderID: "**************",
        sound: "true"  
      },
      ios: {
        senderID: "**************",
        gcmSandbox: false,
        alert: "true",
        badge: "true",
        sound: "true"
      },
      windows: {}
    });

#### Screenshot iOS

Here you can see the default PhoneGap icon instead the app icon

![img_0003](https://cloud.githubusercontent.com/assets/6285444/19240560/3a6e58c2-8f0b-11e6-918a-572a4938014b.PNG)

**Comment by stileinverso** [comment]
For app icon I solved creating all this icons listed here (see solution also):
https://forums.adobe.com/thread/2200494
but **I can't receive sound and image**

**Comment by macdonst** [comment]
@stileinverso impossible for me to debug without the push payload.

**Comment by stileinverso** [comment]
It was only a PHP code error during sending. Sorry for the inconvenience
