### ISSUE TITLE
$cordovaPushV5.register() event not called on IOS.

### ISSUE THREAD

**Issue by amadercode** [phonegap/phonegap-plugin-push#1278]
Push notification features for ionic hybrid framework phonegap-plugin-push with version 1.8.2.

Plugins xml engine info 
<engines>
    <engine name="cordova" version=">=3.6.3"/>
    <engine name="cordova-android" version=">=4.0.0"/>
    <engine name="cordova-ios" version=">=4.1.0"/>
  </engines>
  
 Plugin using sample  Link: 
 https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/EXAMPLES.md
 
During my app start $cordovaPushV5.register() to be called on IOS and Android so I can capture the
registrationId and send it to my backend server. 

Only one month ago (early month of september 2016) it was working fine for both of Android and Ios
but Now it is not working for IOS though working fine for android still now.

Actual Behaviour

On IOS don't see $cordovaPushV5.register() being called, but I do on Android.

Reproduce Scenario

Install push plugin and sample code on Cordova app and run on IOS device, startup app and look at
logs to confirm, do same on Android device and $cordovaPushV5.register() isn't called on IOS,
but works fine on Android.

Ionic info :
 Locally installed version: 1.7.16
 Xcode version is : 7.2.1
 
 My Code gist link: https://gist.github.com/amadercode/c12fc43aeced05451bd086169e3abaae

Even i don't get error message from 

$rootScope.$on('$cordovaPushV5:errorOcurred', function(event, e){
			 alert('ERROR'+e.message);
			// e.message
		  });

Thank you

**Comment by macdonst** [comment]
@amadercode some logs from Xcode when starting the app would really help.

**Comment by chansaikit** [comment]
the 
push.on('registration', function(data) 
is not working on iOS devices but Android is working fine.

this is the Xcode logs

2016-10-11 21:21:41.756146  [253:8938] Push Plugin register called
2016-10-11 21:21:41.756270  [253:8938] PushPlugin.register: setting badge to false
2016-10-11 21:21:41.756322  [253:8938] PushPlugin.register: clear badge is set to 0
2016-10-11 21:21:41.756362  [253:8938] PushPlugin.register: better button setup
2016-10-11 21:21:41.764408  [253:8938] GCM Sender ID (null)
2016-10-11 21:21:41.764496  [253:8938] Using APNS Notification
2016-10-11 21:21:41.779209  [253:8762] Push Plugin register failed
2016-10-11 21:21:42.770830  [253:8762] active
2016-10-11 21:21:42.771073  [253:8762] PushPlugin skip clear badge

**Comment by macdonst** [comment]
@chansaikit well there you go:

```
2016-10-11 21:21:41.779209 [253:8762] Push Plugin register failed
```

The logs say the registration failed which is why you are not get the registration event handler called. Usual cause of something like this is your iOS certificates are expired or invalid.

**Comment by chansaikit** [comment]
Thanks for helping on this.
I found the issue is because the notification didn't set to "ON" on capability tab in Xcode after upgraded to latest version.

**Comment by macdonst** [comment]
@chansaikit yeah, I'm tracking that annoyance in #1154
