### ISSUE TITLE
On notification event not fired on iOS 10 ever. Could you help me guys to solve this please?

### ISSUE THREAD

**Issue by cretupaul** [phonegap/phonegap-plugin-push#1281]
![capture](https://cloud.githubusercontent.com/assets/22791079/19307702/8ef13e08-9084-11e6-92c9-bff3f496eb8d.PNG)
#### Cordova CLI version and cordova platform version

```
cordova --version                                    # e.g. 6.0.0
cordova platform version android                     # e.g. 4.1.1
```
#### Plugin version

```
cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3
```
#### Sample Push Data Payload

```
PushNotification.init({
                "android": {
                    // "senderID": "271545434788" PAUL
                    // "senderID": "721893874385" OLD
                    "senderID": "762104952670",
                    "ecb": "onNotificationGCM",
                    "badge": true,
                    "sound": false
                },
                ios: {
                    alert: "true",
                    badge: true,
                    sound: 'false'
                }                //"windows": {} 
            });


            if (message.type == MessageTypes.ChatMsg ||
                message.type == MessageTypes.Action) {
                pnMessage.gcm = _getNotificationData(message);
                pnMessage.aps = {
                    alert: 'The room temperature is set too high'
                };
                pnMessage.apns = {
                    alert: 'The room temperature is set too high'
                };
                alert(JSON.stringify(pnMessage));
            }

            /*pnMessage.gcm = {
                    title: 'PubNub Push Demo',
                    message: 'The room temperature is set too high'
            };*/

            pnMessage.publish();
```

**Comment by macdonst** [comment]
@cretupaul This isn't enough information for me to be able to debug the problem. It seems like you are moving over from the old Push Plugin and if you are expecting to set `"ecb": "onNotificationGCM"` and have that event fired then you haven't read the updated API docs.

Please give me more information on what the problem is for instance, the actual push payload you send and if you ever see the notification in the shade, what are the situations you've tested?

**Comment by cretupaul** [comment]
No no, i understand, but the "ecb": "onNotificationGCM" it is not used anymore. On android everything works , but on iOS the on notification is not triggered. The payload for ios is :  pnMessage.apns = {
                        "alert": {
                                    "title" : "Swifting.io Notifications",
                                    "subtitle" : "Swifting.io presents",
                                    "body" : "Rich notifications" 
                                 },
                        "content-available": 1
                }; and i have tried also with 
  pnMessage.apns = {
                        "alert": "ALERT!!",
                        "content-available": 1
                };

**Comment by cretupaul** [comment]
The registration works , but the on notification is not triggered. From ios to android is working also.

**Comment by macdonst** [comment]
@cretupaul okay, it really seems like your push payload is in a non-standard format. How do you send the pushes? Can you try using one of the node scripts I link to in the docs?

**Comment by cretupaul** [comment]
I have tried in this way also:  var pnMessage = PUBNUB.PNmessage();
            pnMessage.pubnub = _pubnub;
            pnMessage.channel = message.target
 pnMessage.gcm = _getNotificationData(message);
                pnMessage.apns = {
                        "alert":"Testing....",
                        "badge":3,
                        "sound":"default"
                };

**Comment by cretupaul** [comment]
Another way that i tried is this one.
var message =  PUBNUB.PNmessage();
                    message.pubnub = gridClient.getPubnub();;
                    message.callback = function(msg){ alert("callback"); };
                    message.error = function (msg){ alert("error");};
                    message.channel = 399;
                    message.apns = {
                        alert: 'The room temperature is set too high'
                    };
                    message.gcm={
                         'title': "ss",
                        'message': "notification_text",
                        'style': "inbox",
                        'soundname': "default",
                        'content-available':'1'
                        };
On Android works perfectly, on ios not.

**Comment by macdonst** [comment]
@cretupaul I don't know anything about PubNub. Can you try to send via the node-apns scripts I refer to in the docs and/or grab some logs in xcode to see what the app receives.

**Comment by cretupaul** [comment]
This is what app receives (the hole Json):
{

    "pn_apns":{
        "aps":{
            "alert":"Testing....",
            "badge":3
        },
        "sound":"default"
    },
    "pn_gcm":{
        "data":{
            "title":"Paul Cretu: ppp",
            "message":"Paul Cretu: ppp",
            "style":"inbox",
            "summaryText":"There are %n% notifications",
            "ledColor":[
                0,
                0,
                255,
                0
            ],
            "groupid":"399",
            "soundname":"default",
            "content-available":"1"
        }
    },
    "type":"chatMsg",
    "creationTimestamp":1476345588655,
    "sender":"972111111111",
    "contextGroup":"399",
    "target":"399",
    "data":{
        "text":"ppp",
        "session":4,
        "isNewSession":true,
        "important":false,
        "delayed":false
    }

}

**Comment by macdonst** [comment]
@cretupaul the problem is the way PubNub delivers the data. The `aps` property should be in the root of the JSON object, without that iOS does not interpret it correctly.

**Comment by cretupaul** [comment]
Ok, i have made it in the right way and is still not working. I will write also the registration, maybe in here is the problem. This is the registration  var gwType=(device.platform=="Android") ? "gcm" : "apns";
        var channels = app.data.groupNames;
        var pubnub = gridClient.getPubnub();
        for (var i = 0; i < channels.length; i++) {
            pubnub.mobile_gw_provision({
                device_id: regid, // Reg ID you got on your device
                channel: channels[i],
                op: 'add',
                gw_type: gwType,
                error: function (msg) { console.log(msg); },
                callback: function () {;}
            });
        }

And the following one is the string i receive right now:
{
    "pn_gcm":{
        "data":{
            "title":"Ovidiu Movila: Ok",
            "message":"Ovidiu Movila: Ok",
            "style":"inbox",
            "summaryText":"There are %n% notifications",
            "ledColor":[
                0,
                0,
                255,
                0
            ],
            "groupid":"70",
            "soundname":"default",
            "content-available":"1"
        }
    },
    "type":"chatMsg",
    "creationTimestamp":1476438660397,
    "sender":"9721111111111",
    "contextGroup":"70",
    "target":"70",
    "data":{
        "text":"Ok",
        "session":2,
        "isNewSession":true,
        "important":false,
        "delayed":false
    },
    "aps":{
        "alert":"Testing...."
    }
}

**Comment by macdonst** [comment]
@cretupaul I can't reproduce this problem. Can you please use the node-apns script from https://github.com/node-apn/node-apn/blob/master/examples/sending-to-multiple-devices.js in order to test?

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
