### ISSUE TITLE
App name is not shown in Android notification panel if title is empty

### ISSUE THREAD

**Issue by malwatte** [phonegap/phonegap-plugin-push#1282]
Hi,
In iOS if we did not send anything for title OS shows the app name for title by default.
```
{ "data": {
      .....
        },
     "notification" : {
          "body" : "Body"
        },
.....
    }
```

This is the default behaviour in Android as well.

But in Android when we send body and title in data payload, plugin handles the incoming push. But the problem is if title is empty it does not show app name by default.
Can we show app name if title is empty by default?
Thank you.

**Comment by bau720123** [comment]
+1

**Comment by macdonst** [comment]
@bau720123 use the "Add your reaction" feature instead of adding `+1` as a comment. It makes the issue cleaner while still counting your vote.

**Comment by bau720123** [comment]
hi @macdonst 
got it，sorry for bother

**Comment by macdonst** [comment]
@bau720123 no problem, just letting you know for the future. It's hard to keep up with all the new features of all the tools we use. I'm going to delete our comments on this issue in a few minutes once you get a chance to read and vote.
