### ISSUE TITLE
Registration event not working on ios 9.3.5 and ios 10.

### ISSUE THREAD

**Issue by VishalKryptos** [phonegap/phonegap-plugin-push#1284]
Everything was working fine for android and ios. But after updating the device to ios9.3.5 the registration event is not giving registration ID. When i open the app, it fires init event, which gives a permission pop up in ios "Allow app to send notification", after pressing "Ok" button registration event is called but no registration ID is generated. I tried adding error event to see if any errror is getting generated but seems like error event is not getting called. I cross checked the certificate and provisioning profile and it is fine. Not sure what is the issue here, as it was working fine before. Can you try the plugin in iOS 9.3.5. Please help.

**Comment by macdonst** [comment]
@VishalKryptos run the app in Xcode to see what the logs tell you. Also, check out issue #1154 if you have upgraded to Xcode 8.

**Comment by VishalKryptos** [comment]
I did more testing and tried the app in other ios device and i was able to get the registration ID. But in one of the device running on ios 9.3.5 the issue is still coming. Not sure what is causing the issue. I am using phonegap build to generate the build, cant use xcode and see logs. Will do more testing and try to get more info about the issue.

Closing the issue as of now. Thanks for the help.

**Comment by VishalKryptos** [comment]
I have an ipad which has iOS 10.1 running and the plugin is not able to generate registrationID. I checked issue #1154 as suggested but i cant use it as i am using phonegap build to generate iOS builds. Is there any way we can add push entitlement for phonegap build.

**Comment by VishalKryptos** [comment]
Oct 27 23:47:34 iPod-touch [534] <Warning>: Push Plugin register called
Oct 27 23:47:34 iPod-touch [534] <Warning>: PushPlugin.register: setting badge to false
Oct 27 23:47:34 iPod-touch [534] <Warning>: PushPlugin.register: clear badge is set to 0
Oct 27 23:47:34 iPod-touch [534] <Warning>: PushPlugin.register: better button setup
Oct 27 23:47:34 iPod-touch [534] <Warning>: GCM Sender ID (null)
Oct 27 23:47:34 iPod-touch [534] <Warning>: Using APNS Notification

Nothing comes up after these logs. The app just hungs up.
