### ISSUE TITLE
hasPermission() on iOS doesn't work

### ISSUE THREAD

**Issue by JqckB** [phonegap/phonegap-plugin-push#1288]
### Expected Behaviour

hasPermission() on iOS should pass when the certificate is well-configured with data.isEnabled.

### Actual Behaviour

hasPermission() doesn't work even when the certificate is well configured. On my example, data.isEnabled is false, when I removed it, it's working.

#### Platform and Version 
iOS 10.0.2

#### Cordova CLI version and cordova platform version

    cordova --version
      6.3.1
    cordova platform version | grep ios
      ios 4.2.1

#### Plugin version

    ionic plugin | grep phonegap-plugin-push
    phonegap-plugin-push 1.8.3 "PushPlugin"

#### Sample Code that illustrates the problem

    PushNotification.hasPermission(function (data) {
         if (data.isEnabled) {
           push = PushNotification.init({
             android: {
               senderID: AppSettings.gcmSenderID
             },
             ios: {
               senderID: AppSettings.gcmSenderID,
               gcmSandbox: AppSettings.gcmSandbox
             }
           });
           listen(push);
         }
    });

**Comment by jcesarmobile** [comment]
hasPermission means that the user accepted the permission, not that you configured the certificates properly, the permission won't be asked until you init the plugin, so in your case data.isEnabled is false because you check it before calling init
