### ISSUE TITLE
Since 1.8.3 IOS build fails

### ISSUE THREAD

**Issue by kaynz** [phonegap/phonegap-plugin-push#1289]
Hi,

just switched from 1.8.2 to 1.8.3, where the iOS build fails:

`cordova build ios --release --device`

result: https://paste.xinu.at/WTvPJ/

**Comment by kaynz** [comment]
Looks like the build is failing only on El Capitan.

Fails with XCode 7.3.1
Works with XCode 8.0

**Comment by macdonst** [comment]
@kaynz weird, because there was only one change in the iOS code from 1.8.2 to 1.8.3 and that was the removal of an unused line of code. Pretty sure this is just Apple messing with us. I should update the docs to tell everyone to use XCode 8 regardless.

**Comment by kaynz** [comment]
Okay. So, how can I solve this? I can't update to Xcode 8 because of #1154.

**Comment by kaynz** [comment]
It looks like it is unrelated to this plugin, thanks.
