### ISSUE TITLE
Push notification support for Blackberry10 OS.

### ISSUE THREAD

**Issue by chetanporiya** [phonegap/phonegap-plugin-push#129]
Hi there,
As i have already used PushPlugin for android, ios and blackberry10 which is deprecated,
Now, i would like to switch to the new plugin but i found that there is no support provided for blackberry 10 in the new plugin (i had checked plugin.xml and documentation).

What about providing support for BlackBerry10 OS ?

**Comment by macdonst** [comment]
@chetanporiya sadly I don't have the hardware necessary to do the testing for BB10. The old code from the previous plugin is in a blackberry branch. At this point I need someone with BB knowledge to contribute a PR.

**Comment by macdonst** [comment]
Closing as BB is 0.2% of monthly mobile phone sales and we've only got 1 request for this in 2 years.
