### ISSUE TITLE
android build fails

### ISSUE THREAD

**Issue by GHR-Arash** [phonegap/phonegap-plugin-push#1293]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not download artifact 'ShortcutBadger.aar (me.leolin:ShortcutBadger:1.1.4)'
   > Could not GET 'https://repo1.maven.org/maven2/me/leolin/ShortcutBadger/1.1.4/ShortcutBadger-1.1.4.aar'.
      > Connection to http://127.0.0.1:6571 refused

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 17.238 secs
Error: Error code 1 for command: cmd with args: /s,/c,"C:\Users\Admin\Desktop\Projects\push\MobileApp\platforms\android\gradlew cdvBuildDebug -b C:\Users\Admin\Desktop\Projects\push\MobileApp\platforms\android\build.gradle -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"

**Comment by macdonst** [comment]
@GHR-Arash that looks like a maven issue. Are you behind a proxy or firewall that could be preventing the download?

**Comment by GHR-Arash** [comment]
you are right , it suddenly solved . how can i clear maven or gradle proxy ?
