### ISSUE TITLE
[QUESTION ]what is push.finish(function() { id process

### ISSUE THREAD

**Issue by J261** [phonegap/phonegap-plugin-push#1295]
In push.finish(function() { what is the id

"id	String		Tells the OS which background process is complete."

but where i get this id or what is?

**Comment by macdonst** [comment]
@J261 from the docs on iOS [Action Buttons](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons-1):

> You may notice that the finish method now takes success, failure and id parameters. The id parameter let's the operating system know which background process to stop. You'll set it in the next step.
> 
> Then you will need to set the category value in your aps payload to match one of the objects in the categories object. As well you should set a notId property in the root of payload object. This is the parameter you pass to the finish method in order to tell the operating system that the processing of the push event is done.
