### ISSUE TITLE
Getting iOS device ID

### ISSUE THREAD

**Issue by MarcoDias7** [phonegap/phonegap-plugin-push#1296]
Hi,

I'm using Ionic. I have trouble understanding how this works with GCM/Firebase and iOS.

This is my code : 

```
var push = PushNotification.init({
            "android": {
                "senderID": "xxxxxx",
                "alert": "true",
                "badge": "true",
                "sound": "true"
            },
            "ios": {
                "senderID": "xxxxxx",
                "alert": "true",
                "badge": "true",
                "sound": "true"
            },
            "windows": {}
        });
        push.on('registration', function(data) {
            localStorage.registration_id = data.registrationId;
        });
        push.on('notification', function(data) {
            localStorage.title = data.title;
            localStorage.message = data.message;
            localStorage.uid = data.additionalData.uid;
            $state.go('alert');
            // data.title,
            // data.count,
            // data.sound,
            // data.image,
            // data.additionalData
        });
        push.on('error', function(e) {});
```

At the moment in my app, this works on Android, I'm able to receive notifications (sent from a web server PHP), to open them and go to an other page. But when I install this app on iOS, on registration I don't get the registrationId. Is it different to get it from iOS ?
I have an error in the logs :

> 2016-10-18 12:02:55.574 HelproIonicV2[2110:1419499] GCM Sender ID 605538484827
2016-10-18 12:02:55.574 HelproIonicV2[2110:1419499] Using GCM Notification
2016-10-18 12:02:55.594 HelproIonicV2[2110:1419115] Push Plugin register success: <2fea80ff d733f51e 8040a7b5 a2a09bab 4c8ab564 fdfbad52 5ec1e8ba e62917c7>
2016-10-18 12:02:55.678: GGLInstanceID | Unable to find token in cache Error Domain=com.google.iid Code=-25300 "(null)"
2016-10-18 12:02:56.137 HelproIonicV2[2110:1419115] Registration to GCM failed with error: The operation couldn’t be completed. (com.google.HTTPStatus error 401.)

Other small issue, is that I don't have sound when receiving a notification on Android. This is my payload even if in my payload I have vibrate and sound on 1.

Thanks for the plugin by the way

**Comment by jcesarmobile** [comment]
On iOS you have to create an App ID for you app's bundle id, enable push notifications for that App ID, generate a provisioning profile for that App ID and then use that provisioning profile when running the app.
All those things can be done on https://developer.apple.com/account/ios/certificate/

**Comment by MarcoDias7** [comment]
Thanks I did that now, but it's still not working. I imported my Provisioning file into xcode, but when I run the app, I still have 

> 2016-10-18 12:02:55.574 HelproIonicV2[2110:1419499] GCM Sender ID 605538484827
2016-10-18 12:02:55.574 HelproIonicV2[2110:1419499] Using GCM Notification
2016-10-18 12:02:55.594 HelproIonicV2[2110:1419115] Push Plugin register success: <2fea80ff d733f51e 8040a7b5 a2a09bab 4c8ab564 fdfbad52 5ec1e8ba e62917c7>
2016-10-18 12:02:55.678: GGLInstanceID | Unable to find token in cache Error Domain=com.google.iid Code=-25300 "(null)"
2016-10-18 12:02:56.137 HelproIonicV2[2110:1419115] Registration to GCM failed with error: The operation couldn’t be completed. (com.google.HTTPStatus error 401.)

**Comment by jcesarmobile** [comment]
You have to generate a development push certificate on the same site for your App ID, download it to your map and open it so it's imported into your keychain, then export it as .p12 selecting the private key too and upload it to google console

**Comment by MarcoDias7** [comment]
Oh god, didn't know all of that. I had almost nothing to do to make it works on Android, but for iOS, there was all this thing I didn't know. The configuration was a mess.
I can now get my registrationId, however, when I send a Push Notification, I don't receive it on my iPad. Is it because I created a Development certificate and I need a Production ? Same for the provisioning profile ? Is my payload wrong ?

**Comment by jcesarmobile** [comment]
No, while you are testing the push certificate has to be a development one as your app will be in development mode too.
You have not posted your payload, so I can't tell you if it's wrong. 
Did you test with the app open or with it in background?

**Comment by MarcoDias7** [comment]
`{"registration_ids":["mCSJzjBmn6I:APA91bESx4xgryrqx43QiGa37lddofey22KUOhijsHlY5LyHjjFark9eJO5F60fV3QlaFbwtLN0otD9rEYCs3gd48ehP5P2Trfn44FyG7zyGHWlYgPsxKieBPex62VJ8P_cp794FRNIU"],"data":{"message":"Nouvelle intervention \u00e0 r\u00e9aliser","title":"Helpro Alerte","uid":"58062f69b0ced","vibrate":1,"sound":1}}`

**Comment by macdonst** [comment]
@MarcoDias7 you didn't set gcmSandbox to true to tell the app you are in development mode.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#ios-gcm-support

**Comment by MarcoDias7** [comment]
Sorry I couldn't answer.

So, I still have this problem. I put gcmSandbox to true in my PushNotification.init like this : 
`var push = PushNotification.init({
            "android": {
                "senderID": "xxxxxx",
                "alert": "true",
                "badge": "true",
                "sound": "true"
            },
            "ios": {
                "senderID": "xxxxxx",
                "alert": "true",
                "badge": "true",
                "sound": "true"
            },
            "windows": {}
        });`

And as I understand, the payload is a bit different on iOS. This is mine currently :
`{"registration_ids":["n_crmfl5QVo:APA91bEsexRdIgzoFDwN5Y7jX6LCG5r8kbsnPV7cION0MTxFrG4oKc9RvS0hetUtUMqq7GKiskz98DZQ8kooidknK90tx1U64VEWPUS0HcYMJ5IGbeC3Iz1LHtNEtXVF7qk12vkvrJdN"],"data":{"message":"Test","title":"Message","uid":"58105ee7747f8","quittance":0,"vibrate":1}}`
Is the payload ok ? Is there an example of a payload for my case (using GCM for iOS)

I don't even receive the notification. 
On Firebase I created a project, and imported my .p12 certificate, and when creating the app, they gave me a GoogeService-info.plist, is it necessary to make it work ?

**Comment by fredgalvao** [comment]
@MarcoDias7 I still don't see mention of `gcmSandbox` in your initialization code. Are you sure you're passing it as true?

**Comment by MarcoDias7** [comment]
I don't know why, but I changed this file in XCode, but it only changed the app.js file in the Ionic root, and not in the iOS folder. So I changed it not in XCode, Anyway, sometimes I get a 
`{"multicast_id":6534908412421686944,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1477485933250204%fc39444cfc39444c"}]}`

But no notification on the iPad. It doesn't work 100%, sometimes I still get the InternatServerError sometimes. I tried to put priority high on the payload, still no notification on the iPad.

**Comment by MarcoDias7** [comment]
It's working now, I receive notifications, and I can add additional data in the payload and retrieve it in my app like I did on android, just had to use data and notifications.

Thanks !

**Comment by Assylkhan** [comment]
Hi MarcoDias7. I am having the same issue (push error =  - The operation couldn’t be completed. (com.google.HTTPStatus error 401.)). Could you show your config.xml and index.js files, and tell what did you do else for getting it work. It would be great. Thank you.
