### ISSUE TITLE
handeling push.on('notification') when app is in background in android

### ISSUE THREAD

**Issue by GHR-Arash** [phonegap/phonegap-plugin-push#1297]
push.on('notification', function(data) {
    // data.message,
    // data.title,
    // data.count,
    // data.sound,
    // data.image,
    // data.additionalData
});
 works when app is running 
i receive notification and it works 

but when i close app i receive notification but cant handle it . it just open the app when i click it . 

how can i handle notification when app in in background in andorid ?

**Comment by macdonst** [comment]
@GHR-Arash please read the docs:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#push-message-arrives-with-app-in-background

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications

**Comment by GHR-Arash** [comment]
below is json i am sending to fcm using postman , i recive push notification both in foreground and background mode ,  but can handle it only app is foreground
 ```
     { 
"notification": {
    "title": "Welcome To Push Notification App",
    "body": "This is body of push Notification Message",

    "sound":"default"
  },
  "sound":"default",
  "data": {
  	"content-available":"1",
    "score": "5x1",
    "time": "15:10",
    "sound":"default",
    "IsRecivedFromManager":"true"
  },
  "content-available":"1",
  "to" : "fCtqyTsgXaM:APA91bFyx5yLRPDzjkpKHk85V-8HQ28C6_RTHdv3RSyqxQ0p9bA02mc_GphoB2SZ8v5cW_PMzEyNzw1_ulL0YrxN74LwpHQD2xXxiyKW6xHjVr6RMIZuVigMjV9qiwHLd3DfFV0v6q5F",
   "priority":"high"
}  
```

my js file 

```
$ionicPlatform.ready(function () {


        // initialize
        $cordovaPushV5.initialize(options).then(function () {
            // start listening for new notifications
            $cordovaPushV5.onNotification();
            // start listening for errors
            $cordovaPushV5.onError();

            // register to get registrationId
            $cordovaPushV5.register().then(function (registrationId) {
                // save `registrationId` somewhere;
                window.localStorage.setItem("appToken", registrationId)
            })
        });

        // triggered every time notification received
        $rootScope.$on('$cordovaPushV5:notificationReceived', function (event, data) {

           console.log(data)

        });

        // triggered every time error occurs
        $rootScope.$on('$cordovaPushV5:errorOcurred', function (event, e) {
            // e.message
        });

```

**Comment by macdonst** [comment]
@GHR-Arash so the plugin does not yet support FCM. Also, when you send the payload it should all be in `data`.

```
{ 
  "data": {
    "title": "Welcome To Push Notification App",
    "body": "This is body of push Notification Message",
    "sound":"default",
    "content-available":"1",
    "score": "5x1",
    "time": "15:10",
    "sound":"default",
    "IsRecivedFromManager":"true"
  },
  "to" : "fCtqyTsgXaM:APA91bFyx5yLRPDzjkpKHk85V-8HQ28C6_RTHdv3RSyqxQ0p9bA02mc_GphoB2SZ8v5cW_PMzEyNzw1_ulL0YrxN74LwpHQD2xXxiyKW6xHjVr6RMIZuVigMjV9qiwHLd3DfFV0v6q5F",
   "priority":"high"
}  
```

**Comment by GHR-Arash** [comment]
thanks , now it is working . but how about when i close app ? i can handle push when in background , but when i close app i Receive  push notification but cant handle it . is there any solution for this ?

thank you .

**Comment by macdonst** [comment]
@GHR-Arash please read the documentation, you are asking questions that have already been answered, repeatedly.
