### ISSUE TITLE
Error in notifications expand in words with accent mark

### ISSUE THREAD

**Issue by cholomanLP** [phonegap/phonegap-plugin-push#1298]
In the image attach showed the error, for example: llev&oacute; this notification should show "llevó", the codification called for push notification is "utf-8".  (This error is visible only when were expand, but it is not expand it didn't show the error, I showed the example in the attach picture 2).

I need to find a solution for that error.
I hope could you help me.

![14725152_1397703193590461_1606233286_o](https://cloud.githubusercontent.com/assets/4528337/19482991/63261f08-9518-11e6-84f8-90f0c613dfc3.jpeg)
![14787527_1397703213590459_1345142474_o](https://cloud.githubusercontent.com/assets/4528337/19482994/66dcc00c-9518-11e6-848f-eba5b29ea87a.png)
![14803132_1397703190257128_360544864_o](https://cloud.githubusercontent.com/assets/4528337/19482999/6912e0fe-9518-11e6-88f9-70e750f00ee2.png)

**Comment by fredgalvao** [comment]
That's probably related to the new html support.

**Comment by cholomanLP** [comment]
What support??
What is the possible solution?

**Comment by fredgalvao** [comment]
[This PR](https://github.com/phonegap/phonegap-plugin-push/pull/892) was added kinda recently, and I'd bet it's the one responsible for the loss of fidelity on those strings. I may be wrong though, and we might just need to specify an encoding on the android API.

**Comment by cholomanLP** [comment]
I found the solution.

The problem was in my code php:
The content of variable $sumarioFinal is get it from my database so it has html tags.

$sumarioFinal = strip_tags($sumarioFinal);
**$sumarioFinal = html_entity_decode($sumarioFinal, ENT_QUOTES, "UTF-8");** /*this is my solution*/

Thank for all.

**Comment by fredgalvao** [comment]
Thanks for sharing that and clearing it out.
