### ISSUE TITLE
Know if the app received the notification from server side

### ISSUE THREAD

**Issue by smileapplications** [phonegap/phonegap-plugin-push#1299]
I'm building a newspaper-like app and I would like to know **how many people received the article's push notification** vs **how many actually read it**. 

I was thinking to implement a way in which when the notification is received the app wakes up and send a request to the server saying "**Hi I'm _____, I've received the notification of the article  ____**" and store it in the database. Then afterwards if the user click on the notification and goes to read the article I send another request saying "**Hi I'm ____ and I've read the article _____**" and I also store it on the database. Afterwards with some queries I'm able to understand the percentage read/received.

From the documentation I don't understand:

- if this plugin is able to **wake up the app** even if it was not opened by the user in a while and **send a request to the server** (for background is meant that the application is not launched or that is in the cache ?).
- if this approach works for **both Android and iOS**  

Thank you for your patience and this plugin.

**Comment by smileapplications** [comment]
I would like to achieve what they did with Whatsapp:

- I receive a new message on Whatsapp
- I don't open the app
- I go to WhatsApp Web
- I open the conversation on WhatsApp Web
- The badge and the notification on the phone goes away because I read it somewhere else

I think that that feature is achieved with silent push notifications that just update the app badge and clear the read notification.

**Comment by macdonst** [comment]
@smileapplications when the your `on('notification')` event is fired that is where you communicate back to your app server to let them know it was read. The functionality you want is better done on the app server side as both GCM and APNS will tell you how many push messages got delivered.

**Comment by fredgalvao** [comment]
Neither GCM nor APNS can tell you at the time you send the request to them, how many users/devices received the message. That process in async and could take hours/days to completely render finished.

The `read` event is mapped to the already existing `on('notification')` event with the plugin's API, as stated by @macdonst, so you can already implement that with the highest accuracy possible right now.

There are different points on which you could implement the `receive` event though, each with different levels of accuracy/efficiency/cost of implementation:
- Modify the GCMIntentService class [at this line](https://github.com/phonegap/phonegap-plugin-push/blob/3d7a3a39fb931aafa86be6b1568a682133c36de7/src/android/com/adobe/phonegap/push/GCMIntentService.java#L63) to make an HTTP request (for example) to your server notifying that the device *DEFINITELY* received the push, and that the user is about to be notified of it. This is the earliest you can get in the flowchart after the message is delivered from GCM to the device, but requires you to modify the plugin's source code right now.
- Send a silent notification and hope that the plugin is able to notify your app's code of it's receipt right away (there needs to be a webview for that to happen currently, but there's a PR that will fix that for android soon). This is later down the pipe compared to the solution above, and it can fail (if the webview isn't available and the plugin is unable to start it up), but the good side is that it can be done in application's code side only, no need to modify the plugin in any way, and *can be used for iOS too, just as in android*.

If you use option 1, I can't help you with iOS.

**Comment by smileapplications** [comment]
@fregalvao but it's tecnically possible in iOS or not ?

**Comment by fredgalvao** [comment]
I'm pretty sure you could implement it yourself on the Objective-C side of things to make an HTTP request just like I did on android through the GCMIntentService class. However, I don't know how to guide you there.

If you find how to do it, I'd be highly interested in reusing that if I may, so please share 😉

**Comment by smileapplications** [comment]
I really need this feature so I've opened a reward on StackOverflow [here](http://stackoverflow.com/questions/40119069/know-if-the-app-received-the-notification-from-server-side)

The thin that I don't understand of iOS is that everywhere I go they say that if the app is killed by the user than no callback will be called when the notification arrives.

Here an example:
![schermata 2016-10-21 alle 06 08 27](https://cloud.githubusercontent.com/assets/2022691/19586420/042e5d28-9755-11e6-948e-d1119334fe0d.png)

**Comment by smileapplications** [comment]
And this is from Apple
![schermata 2016-10-21 alle 06 21 02](https://cloud.githubusercontent.com/assets/2022691/19586587/bd98324c-9756-11e6-9326-2eec32b4211d.png)

**Comment by uruparel** [comment]
Hello, did you find any solution for this? Like whats app showing delivered status even if user just received push notification but app is killed.
