### ISSUE TITLE
Support Win8.1 + Phone 8.1 Universal Apps (WNS), drop support for WP8.0 (MPNS)

### ISSUE THREAD

**Issue by T18970237136** [phonegap/phonegap-plugin-push#13]
Hi,

I found this plugin when searching for a successor of the PushPlugin (https://github.com/phonegap-build/PushPlugin) which seems not to be developed further.

The current readme says that support for "WP8" is under development. However it does not say about the Win 8.1/WP 8.1 (Universal Apps) platform.

As this seems to be a new plugin, what about dropping support for WP 8.0 and instead only supporting Win 8/8.1/WP 8.1 "Universal Apps"? Note that these platforms will use WNS (Windows Notification Service) instead of MPNS (Microsoft Push Notification Service) that was used in WP 8.0 (Note that the Cordova Device Plugin reports an Universal App on WP 8.1 as "windows".

Note that the old PushPlugin (https://github.com/phonegap-build/PushPlugin) does not work on Win 8.1/WP 8.1 in the current Cordova version shipped with VS 2015 RC as it specifies a wrong include file, but I found a fork that fixes this issue: https://github.com/kenwu27/PushPlugin (it worked for me on a Windows Phone 8.1 emulator included in Visual Studio 2015 RC, using a Cordova App).

So you could implement support for Push Notifications on Win 8/8.1/WP 8.1 using WNS based on that implementation.

Thanks!

**Comment by macdonst** [comment]
@T18970237136 thanks for the detailed issue. I'll let @rakatyal comment on Win 8.1 support.

**Comment by solhuebner** [comment]
:+1: for the new approach

**Comment by rakatyal** [comment]
@T18970237136 : Thanks for the issue. That is exactly what I am working on. I am adding the support for Win 8/8.1/WP 8.1 using WNS. The first version is ready and should be merged soon.

**Comment by T18970237136** [comment]
Cool, Thanks!

**Comment by rakatyal** [comment]
@T18970237136: This has been merged now.
