### ISSUE TITLE
when build using build.phonegap.com cli-6.3.0

### ISSUE THREAD

**Issue by MahmoudFawzy** [phonegap/phonegap-plugin-push#1300]
## PLUGIN OUTPUT

Installing "org.apache.cordova.statusbar" at "0.1.4" for android
Fetching plugin "cordova-plugin-device" via npm
Installing "cordova-plugin-device" at "1.1.3" for android
Fetching plugin "cordova-plugin-network-information" via npm
Installing "cordova-plugin-network-information" at "1.3.0" for android
Fetching plugin "cordova-plugin-splashscreen" via npm
Installing "cordova-plugin-splashscreen" at "4.0.0" for android
Fetching plugin "cordova-plugin-inappbrowser" via npm
Installing "cordova-plugin-inappbrowser" at "1.5.0" for android
Fetching plugin "cordova-plugin-geolocation" via npm
Installing "cordova-plugin-geolocation" at "2.4.0" for android
Fetching plugin "cordova-plugin-compat" via npm
Installing "cordova-plugin-compat" at "1.0.0" for android
Fetching plugin "cordova-plugin-vibration" via npm
Installing "cordova-plugin-vibration" at "2.1.2" for android
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" at "1.3.0" for android

```
           This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
```

Fetching plugin "uk.co.workingedge.phonegap.plugin.launchnavigator" via npm
Installing "uk.co.workingedge.phonegap.plugin.launchnavigator" at "3.2.1" for android
Fetching plugin "cordova-plugin-actionsheet" via npm
Installing "cordova-plugin-actionsheet" at "2.3.1" for android
Fetching plugin "https://github.com/fastrde/phonegap-checkGPS.git" via git clone
Using shallow clone
Repository "https://github.com/fastrde/phonegap-checkGPS.git" checked out to git ref "master" at "3725722".
Installing "cordova-plugin-fastrde-checkgps" at "0.9.9" for android
Dependent plugin "cordova-plugin-geolocation" already installed on android.
"plugman install --platform android --project /project --plugin https://github.com/phonegap/phonegap-plugin-push.git": Fetching plugin "https://github.com/phonegap/phonegap-plugin-push.git" via git clone
Using shallow clone
Repository "https://github.com/phonegap/phonegap-plugin-push.git" checked out to git ref "master" at "d0547ba".
Installing "phonegap-plugin-push" at "1.8.3" for android
Failed to install 'phonegap-plugin-push':Error: Variable(s) missing: SENDER_ID
    at /.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:362:23
    at _fulfilled (/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:749:13)
    at /.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:557:44
    at flush (/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Variable(s) missing: SENDER_ID

**Comment by macdonst** [comment]
@MahmoudFawzy did you include the SENDER_ID in your config.xml?

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md#including-the-plugin

**Comment by Heshyo** [comment]
I confirm that things work well for me on PGB with cli 6.3.0. I guess @MahmoudFawzy forgot to add the SENDER_ID parameter.

**Comment by MahmoudFawzy** [comment]
I did that and not build when I build using git link worked.
