### ISSUE TITLE
subscribe/unsubscribe don't seem to be functioning

### ISSUE THREAD

**Issue by mbaggott** [phonegap/phonegap-plugin-push#1308]
### Expected Behaviour
subscribe/unsuscribe from topic

### Actual Behaviour
push.subscribe or push.unsubscribe don't execute at all

### Reproduce Scenario (including but not limited to)
Attempt to call either function in app.js, when platform is ready

#### Steps to Reproduce 
Call function as follows:
push.subscribe('scheduleAndroid', function() {
        console.log('success');
}, function(e) {
    console.log('error:');
    console.log(e);
 });

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4.4

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
LeapDroid emulator

#### Cordova CLI version and cordova platform version

    cordova --version                                    Cordova CLI: 6.3.1
    cordova platform version android                    android 5.2.2

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.8.3

#### Sample Push Data Payload
Note: payload works, and sends to all topics. I am trying to unsubscribe from 'all' and subscribe to an Android only topic, so i can send different payloads to iOS and Android.
{
        "to": "/topics/scheduleAndroid", //Topic or single device
        "data":{
          "content-available": "1",
          "title": "Notification title",  //Any value 
          "body": "Notification body"  //Any value 
         }
}
#### Sample Code that illustrates the problem
See steps to reproduce

#### Logs taken while reproducing problem
No logs, as using Ionic and cloud9 for development. Observed behaviour is that either function breaks the app.js flow, which will then work if i comment out the push.subscribe or push.unsubscribe functions.
This may have been functioning a week ago, but i removed the plugin and re-added the latest version yesterday.

**Comment by Eccenux** [comment]
Seems like subscriptions was added after 1.8.3. And only added to master (not to v2.0).

**Comment by macdonst** [comment]
@mbaggott subscribe/unsubscribe is not in 1.8.3. I'll see if I can get a 1.8.4 out today. In the meantime you can just install directly from github.

**Comment by mbaggott** [comment]
@macdonst Thank you :) Love the plugin, is working really well for me
