### ISSUE TITLE
Push Notification not received Android

### ISSUE THREAD

**Issue by amitdangwal** [phonegap/phonegap-plugin-push#1309]
Issue##1304 was marked as closed but issue exist and hence opening a new ticket.

 I have tried GCM and it is not working. In my previous response I have sent the GCM command along with attempt of sending notification through FCM UI. I understand FCM not supported but it is not responding to GCM. Before trying this push notification plugin I was using an outdated plugin from PGB build for sending notifications to ios and android using GCM, APNS and it is working till CLI 5.2. I am moving toward new CLI 6.3 as from November old plugin support will end.

I may be missing something about this plugin. App is taken as it is from the template phonegap-template-push. I have tried winere, gapdebug, phonegap developer to listen for event "Notification"( push.on('notification', function(data) ) but it is not hitting it and no notifications are appearing. Screenshot attached(debugger added in push.on('notification', but never hit)

Point 1) Will it show the Push Notification prompt in Android ? It does shows that in iOS
As per documentation it will show but it is not showing. So is this a bug?
http://docs.phonegap.com/develop/push-notifications/

Point 2) Here is GCM attempts and still no message received.

phonegap push --deviceID fNs4ddtdAm8:APA91bFY-EojwPaDgVBATDX8snrnf1Mx2mi-Iutgpg0up-5kAa8falfwEcFeCCBsp8a8aw7Vfm5KTVh9f2o0EVyQwILtMTCkIfUNZSSlVbg11YIDXgQyQ3hme354OQUkc2v3W7HdqBqW --service **gcm** --payload '{ "data": { "title": "Hello", "message": "World"} }'

body: OK

The only scenario notification message are received when I run the app through phonegap develop app and send the phonegap push. If I build the android app using adobe Phonegap cli 6.3 then it is not receiving message.

I am suspecting some issue with registration id as it seem to getting changed as the below command tells that the registration id is invalid. I am using correct sender ID. Please guide me. Do I need to try any specific version of plugin? I have not given any version in config and let it pick the latest. I understand people are using it and it might be working for them but where it is getting stuck for me is not clear and I need your assistance.

$ curl --header "Authorization: key=MYKEY" --header "Content-Type: application/json" https://android.googleapis.com/**gcm**/send -d "{\"registration_ids\":[\"fNs4ddtdAm8:APA91bFY-EojwPaDgVBATDX8snrnf1Mx2mi-Iutgpg0up-5kAa8falfwEcFeCCBsp8a8aw7Vfm5KTVh9f2o0EVyQwILtMTCkIfUNZSSlVbg11YIDXgQyQ3hme354OQUkc2v3W7HdqBqW \"],
\"data\": {
\"message\": \"This is a GCM Topic Message!\",
}}"

{"multicast_id":7236890165229808725,"success":0,"failure":1,"canonical_ids":0,"results":**[{"error":"InvalidRegistration"}]}**

<img width="1279" alt="screen shot 2016-10-21 at 2 12 46 pm" src="https://cloud.githubusercontent.com/assets/2646843/19617550/0c31de26-9851-11e6-9fd6-9d9ff8afa96e.png">
<img width="1280" alt="screen shot 2016-10-21 at 2 11 51 pm" src="https://cloud.githubusercontent.com/assets/2646843/19617551/0c34a6b0-9851-11e6-9031-c546d5c51faf.png">

**Comment by amitdangwal** [comment]
GCM notifications started working. Not sure what has gone wrong before but now it is working. Base template app is working with GCM and now I hopefully I will be able to integrate it with sencha touch. I will close this ticket

**Comment by q00d0** [comment]
Hello, I have the same problem as you. How did you fixed it?
