### ISSUE TITLE
ios 10 + iphone 5s receives push but without sound

### ISSUE THREAD

**Issue by ledil** [phonegap/phonegap-plugin-push#1310]
### Expected Behaviour

my app should receive a push with sound. My init has:

..
sound: true,
alert: true
..

everytime my server sends a push my app should receive the push with sound (no custom sound, just normal sound). In the ios notification settings everything is fine.

### Actual Behaviour

my app receives a push but everytime without sound. Im using the apple developer push certificate, could this be the root of the problem ?

**Comment by mbaggott** [comment]
I am having the same problem. Infact, when i set sound to true it breaks my iOS notifications altogether

**Comment by mbaggott** [comment]
This is fixed for me now, when i posted my last comment i was being hasty, the notifiaction just took a minute to come through. For me when i set the following init:

var push = PushNotification.init({
      android: {
          senderID: "1062032799809",
          topics: ["scheduleAndroid"]
      },
      ios: {
          senderID: "1062032799809",
          gcmSandbox: true,
          alert: "true",
          badge: "true",
          sound: "true",
          clearBadge: "true",
          topics: ["scheduleIOS"]
      },
      windows: {}
    });

And the following payload for FCM:
{
    "to": "/topics/scheduleIOS", //Topic or single device
        "priority": "high", //If not set, notification won't be delivered on completely closed iOS app 
        "notification":{
          "title": "Notification title",  //Any value 
          "body": "Notification body",  //Any value
          "content_available": true,
          "sound": "default",
          "badge": "1"
}

I get the result of the app having the "badges, banners and sounds" title in the notification center, and when the app is in the background, the notification sound does indeed work

**Comment by amitdangwal** [comment]
@mbaggott  Is FCM working for you with this plugin ? I have been told FCM is not supported

**Comment by mbaggott** [comment]
@amitdangwal  yes it is working fine for me with the posted init and payload. Try it out. If you need any more details just let me know

**Comment by ledil** [comment]
its working now, the problem was missing "sound":"default" when sending the payload ...
