### ISSUE TITLE
On register event not fired

### ISSUE THREAD

**Issue by Tommy10802** [phonegap/phonegap-plugin-push#1311]
```
var push = PushNotification.init({
    android: {
        senderID: "12345679"
    },
    browser: {
        pushServiceURL: 'http://push.api.phonegap.com/v1/push'
    },
    ios: {
        alert: "true",
        badge: "true",
        sound: "true"
    },
    windows: {}
});

push.on('registration', function(data) {
    // data.registrationId
});

push.on('notification', function(data) {
    // data.message,
    // data.title,
    // data.count,
    // data.sound,
    // data.image,
    // data.additionalData
});

push.on('error', function(e) {
    // e.message
});
```

Hello everyone, i need little help with this plugin i tried sample code above and on registration event wont be fired up. Is there something miss or forgot. Thanks very much for advices.

**Comment by amitdangwal** [comment]
hmm. Not sure what exactly you have in confix.xml or in app. Also not sure what code you have put in 'registration' as shown by you in issue description. How are checking the registration event is not fired ?

I have tried this plugin in last 3 days and I was getting some issue with Notifications(which I hope they have fixed behind the scene). So the app is working for me on iOS, android(GCM) and on sencha touch. All event are getting fired.

Simply install node.js, install phonegap on your system after it using node.js. then  create a new sample application using template given by this plugin(command given) and build it and run it. It should work. Try this and I hope it should work or in not working case atleast you can share the details from the example template code.

phonegap create my-app --template phonegap-template-push

Read the document:
http://docs.phonegap.com/develop/push-notifications/
http://docs.phonegap.com/references/phonegap-cli/install/

**Comment by macdonst** [comment]
@Tommy10802 Yeah, how do you know the registration event is not fired if you don't log anything in the registration event handler. Also, you haven't mentioned what platform you are trying this on.

**Comment by Tommy10802** [comment]
sorry guys, i wrote that post from mobile, so i just copied example from readme. But in my code i have alert() and console.log in function which is called on registration event. But nothing happend. Because of that i know that registration method not fired up

**Comment by amitdangwal** [comment]
I recommend trying the code through template as that is the best to start with. compare your code with the example template. If you can share the code as zip then it will be good to check. I am sure you are using correct sender id but still check it once more. Registration event should be fired after device ready. Also from where are you checking this ? from mobile (ios,android app) or through a web browser ? If through webbrowser then it will not call registration event probably. Is that the case ? sorry I am just sharing thoughts in wild directions as nothing concrete shared to review.

**Comment by macdonst** [comment]
@Tommy10802 still don't see any code or a mention of what platform you are on.

**Comment by Tommy10802** [comment]
Sorry guys i appologize.
So i am working on app in visual studio, using cordova ionic plugin for visual studio.
I used old PhonegapPushPlugin for notification. This plugin works fine for android, but with realesed of ios10 and xcode6 it stop work for IOS. So i decided to use this new one plugin. So i uninstall old one, install this new one plugin and just replace code in app.js 

I am trying it for IOS and when i build app through remote build and start app in my phone nothing happend.

Here is a code.

       var push = PushNotification.init({
            android: {
                senderID: "7777777"
            },
            browser: {
                pushServiceURL: 'http://push.api.phonegap.com/v1/push'
            },
            ios: {
                alert: "true",
                badge: "true",
                sound: "true"
            },
            windows: {}
        });

        push.on('registration', function (data) {
            alert("notifikacie" + data)
            // data.registrationId
        });

        push.on('notification', function (data) {
            // data.message,
            // data.title,
            // data.count,
            // data.sound,
            // data.image,
            // data.additionalData
        });

        push.on('error', function (e) {
            alert("notifikacie error" + e)
        });

whole code is called in $ionicPlatform.ready(function () {})

**Comment by oceanpad** [comment]
@Tommy10802 maybe you are using IOS10, It seems register event is not fired, this issue is not solved by now.
see [https://github.com/phonegap/phonegap-plugin-push/issues/1284](https://github.com/phonegap/phonegap-plugin-push/issues/1284)

**Comment by sambegin** [comment]
It may be the same issue as #1326.

We used phonegap plugin push for about 4 months now and we discovered that some iOS 10 devices did not received the registration token anymore while iOS 9.3.5 devices does. 

Everything works fine on android devices. 

We could get those logs from xcode... Look at the difference between OS versions. It seems that nothing is going any further on iOS 10 devices after "version ready" 

iPad on ios 10.0.2

2016-10-28 11:02:59.039918 ...[474:127578] Push Plugin register called
2016-10-28 11:02:59.040022 ... [474:127578] PushPlugin.register: setting badge to true
2016-10-28 11:02:59.040127 ... [474:127578] PushPlugin.register: clear badge is set to 1
2016-10-28 11:02:59.040152 ... [474:127578] PushPlugin.register: better button setup
2016-10-28 11:02:59.040358 ... [474:127578] GCM Sender ID (null)
2016-10-28 11:02:59.040387 ... [474:127578] Using APNS Notification
2016-10-28 11:02:59.060666 ... [474:127007] version ready

On iPhone 5 iOS 9.3.5 , I get the registration token :

2016-10-28 11:07:53.891 ... [2326:1644698] Push Plugin register called
2016-10-28 11:07:53.891 ... [2326:1644698] PushPlugin.register: setting badge to true
2016-10-28 11:07:53.891 ... [2326:1644698] PushPlugin.register: clear badge is set to 1
2016-10-28 11:07:53.891 ... [2326:1644698] PushPlugin.register: better button setup
2016-10-28 11:07:53.891 ... [2326:1644698] GCM Sender ID (null)
2016-10-28 11:07:53.892 ... [2326:1644698] Using APNS Notification
2016-10-28 11:07:53.907 ... [2326:1644495] Push Plugin register success: <... ... ... f35c7ca1 d4aa6c4c c2ec67d4 71378868 421f5851>
2016-10-28 11:07:53.941 ... [2326:1644495] {"registrationId":" .... .. .. ....b25e6de5f4fa88c1954df35c7ca1d4aa6c4cc2ec67d471378868421f5851"}

Note that everything was working on every device about two weak ago...

**Comment by macdonst** [comment]
@Tommy10802 yes, logs from Xcode would be very useful in this case.

**Comment by tmwebs** [comment]
Hi @Tommy10802, you've got to fix, works for me perfectly locally, but when I build the apk with phonegap build stops working and not know why.

**Comment by timeseriesBH** [comment]
Same problem here, permission is asked, but after that no onRegister event....

**Comment by Tommy10802** [comment]
Ok guys i allready had registration id. But it was necessery copy project from visual studio windows directly to mac and build then deploy it at phone from console bash on MAC book.

**Comment by paweldziura** [comment]
On my side, everything works fine on iOS 10.0.1 but on another phone with iOS 10.1.1 it has stopped to work.

In XCode I'm getting:

> 2016-11-08 14:09:25.046773 NotifyMe[1111:439051] Push Plugin register called
> 2016-11-08 14:09:25.046896 NotifyMe[1111:439051] PushPlugin.register: setting badge to false
> 2016-11-08 14:09:25.046978 NotifyMe[1111:439051] PushPlugin.register: clear badge is set to 0
> 2016-11-08 14:09:25.047036 NotifyMe[1111:439051] PushPlugin.register: better button setup
> 2016-11-08 14:09:27.719768 NotifyMe[1111:439051] GCM Sender ID (null)
> 2016-11-08 14:09:27.719914 NotifyMe[1111:439051] Using APNS Notification

Confirmation alert is being displayed but after clicking "OK" nothing happens. DeviceID is not received.

**Comment by macdonst** [comment]
Closing as original poster solved issue.
