### ISSUE TITLE
iOS: InvalidRegistration & Android: MismatchSenderId

### ISSUE THREAD

**Issue by loredanAdrian** [phonegap/phonegap-plugin-push#1315]
### Expected Behaviour
Receive push notifications on iOS and Android

### Actual Behaviour
Tested with PostMan:
POST: 
https://fcm.googleapis.com/fcm/send

HEADERS:
Authorization: key= **Firebase Cloud Messaging app key**
Content-Type: application/json

BODY:
`{ 
	"notification": {
   		"title": "Title",
   		"text": "Message"
 	},
 	"to" : "registration id from iOS device or Android"
}`

RESPONSE:
`{
  "multicast_id": 8731872394382480183,
  "success": 0,
  "failure": 1,
  "canonical_ids": 0,
  "results": [
    {
      "error": "InvalidRegistration on iOS, MismatchSenderId on Android"
    }
  ]
}`

### Reproduce Scenario (including but not limited to)
1. Create a new app in Firebase Cloud and add an Android & iOS app
2. Create a phoneGap app (`phonegap create app`)
2. Add last `v2.0.x` commit (`cordova plugin add https://github.com/phonegap/phonegap-plugin-push#3691c41bc135c5cc284314b9851c055f4cf505df --variable SENDER_ID="sender_id"`) _sender_id_ is Firebase Cloud Messaging Sender Id
3. Copy _google-services.json_ & _GoogleService-Info.plist_ in folder root path
4. Edit index.js:
`
receivedEvent: function(id) {

        console.log("Received Event: " + id);

        console.log("calling push init");
        var push = PushNotification.init({
            "android": {
                "senderID": "sender_id"
            },
            "browser": {},
            "ios": {
                "sound": true,
                "vibration": true,
                "badge": true
            },
            "windows": {}
        });
        console.log("after init");

        push.on("registration", function(data) {
            console.log("registration event: " + data.registrationId);

            var oldRegId = localStorage.getItem("registrationId");
            if (oldRegId !== data.registrationId) {
                // Save new registration ID
                localStorage.setItem("registrationId", data.registrationId);
                // Post registrationId to your app server as the value has changed
            }
        });

        push.on("error", function(e) {
            console.log("push error = " + e.message);
        });

        push.on("notification", function(data) {
            console.log("notification event");
            navigator.notification.alert(
                data.message,         // message
                null,                 // callback
                data.title,           // title
                "Ok"                  // buttonName
            );
        });
    }
`

**Comment by macdonst** [comment]
@loredanAdrian well, we are working on FCM support. Please refer to issue #929

**Comment by tranhai** [comment]
Hi, 
I have the same problem Console Fire Base alway invalid token
![image](https://cloud.githubusercontent.com/assets/5829613/19655155/33148764-9a45-11e6-87f8-6bceab6c30ba.png)

Here is my token : b0ae50721b53e6b8f66f82cf9598548205abff3c3f27242d6e43c7b5869b636a

Can you help me. Thanks

**Comment by Eccenux** [comment]
@macdonst I think this was broken between `phonegap-plugin-push#07fa81b7a3a62400915ac70b9a24a802465a6f95` and `phonegap-plugin-push#3691c41bc135c5cc284314b9851c055f4cf505df`. I get a weird, short token on iOS as tranhai mentions while in previous version of the plugin I got 3 times as long token and it was valid.

@loredanAdrian You must send all your information in `data` not in `notification` part. That way you can get it working in Android. Also remeber to set your sender ID in JS too:
```js
var push = PushNotification.init({
    "android": {
        "senderID": "sender_id" // <- MUST change this
//...
```

**Comment by tranhai** [comment]
Hi, 
Please help me how i can get the right token? As google i saw some idea the token i got was APNs and i also upload my certificate as enclosed.  The registration token still invalid
![certificate](https://cloud.githubusercontent.com/assets/5829613/19674487/b87a34e0-9ab2-11e6-86c9-f7f25b9c3002.PNG)

Thanks for your help.

**Comment by loredanAdrian** [comment]
In local it doesn´t work, I build Android app and tested it in one Android device and it works. I can´t test it on Apple device because I´m working on a Windows machine. Am I wrong?
