### ISSUE TITLE
Plugin not working on Android 6.0

### ISSUE THREAD

**Issue by davidgamarra** [phonegap/phonegap-plugin-push#1316]
### Expected Behaviour
Receive push notifications on Android 6.0
### Actual Behaviour
I want to implement push notification to my cordova app and I add this plugin to do it. I implemented the methods like in the tutorial and I sent a test notification from Firebase Console. On a Android 4.4 device I get the notification correctly, but on Android 6.0 it seems like not work. I check the console log from my app and I see an error. Also 'registration' not fired correctly on this device because I dont get the registrationId.
This is the error message:

    SERVICE_NOT_AVAILABLE

And this is the full error:

    Error: SERVICE_NOT_AVAILABLE
        at fail (file:///android_asset/www/plugins/phonegap-plugin-push/www/push.js:57:45)
        at Object.callbackFromNative (file:///android_asset/www/cordova.js:295:52)
        at processMessage (file:///android_asset/www/cordova.js:1081:17)
        at processMessages (file:///android_asset/www/cordova.js:1104:9)
        at pollOnce (file:///android_asset/www/cordova.js:973:9)
        at pollOnceFromOnlineEvent (file:///android_asset/www/cordova.js:960:5)

### Reproduce Scenario (including but not limited to)

This is the code that I have in my app:

    document.addEventListener("deviceready", function() {
        var push = PushNotification.init({
            android: {
                senderID: "xxx"
            },
            browser: {},
            ios: {
                alert: "true",
                badge: true,
                sound: 'true'
            },
            windows: {}
        });

        PushNotification.hasPermission(function(data) {
            if (data.isEnabled) {
                console.log('isEnabled');
            }
        });

        push.on('registration', function(data) {
            console.log(data);
            console.log(data.registrationId);
        });

        push.on('notification', function(data) {
            console.log(data.message);
            console.log(data.title);
            console.log(data.count);
            console.log(data.sound);
            console.log(data.image);
            console.log(data.additionalData);
        });

        push.on('error', function(e) {
            console.log(e.message);
            console.log(e);
        });
    }, false);

**Comment by macdonst** [comment]
@davidgamarra well, we are working on FCM support. Please refer to issue #929
