### ISSUE TITLE
Dynamic data.count 

### ISSUE THREAD

**Issue by trazek** [phonegap/phonegap-plugin-push#1317]
### Expected Behaviour

Using a place holder like `%n%` which `data.summaryText` accepts: `summaryText": "There are %n% notifications`, the count of notifications in the Android shade increments automatically.
### Actual Behaviour

When using `data.count: %n%`, nothing is displayed. Only when the count is hardcoded in, will it display
### Reproduce Scenario (including but not limited to)

Send push notification with `"data": {
        "message": "An employee request PTO",
        "title": "PTO Request",
        "style": "inbox",
        "count": "%s%",
        "summaryText": "There are %n% notifications"
      }` as the payload
#### Steps to Reproduce

Send push notification with `"data": {
        "message": "An employee request PTO",
        "title": "PTO Request",
        "style": "inbox",
        "count": "%s%",
        "summaryText": "There are %n% notifications"
      }` as the payload
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 6
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Droid Turbo 2
#### Cordova CLI version and cordova platform version

6.3.1
    cordova --version                                    # e.g. 6.0.0

```
cordova platform version android                     # e.g. 4.1.1
```

Installed platforms:
  android 5.2.2
  browser 4.1.0
  ios 4.2.0
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  firefoxos ~3.6.3
  osx ~4.0.1
  webos ~3.7.0
#### Plugin version

phonegap-plugin-push 1.8.3 "PushPlugin"
    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3
#### Sample Push Data Payload

`"data": {
        "message": "An employee request PTO",
        "title": "PTO Request",
        "style": "inbox",
        "count": "%s%",
        "summaryText": "There are %n% notifications"
      }` as the payload

**Comment by macdonst** [comment]
@trazek out of curiosity, why did you close this?

**Comment by trazek** [comment]
Hello. While trying to figure things out, I thought maybe the `data.count` field is not meant to show the number of messages unread/sent. The `data.summaryText` seems to support the `%n%` placeholder but `data.count` does not.  If the `data.count` field is meant to denote how many messages are being pushed to the user at once, then I need to look elsewhere for my solution and not try to use the `data.count`. What I am looking for is a dynamic/running count of messages sent to the user, similar to how multiple messages from other apps are handled.

**Comment by macdonst** [comment]
@trazek yeah, the data.count field is supposed to be sent from the server. It is up to the server, not the client, to keep track of the badge number.

**Comment by trazek** [comment]
Hmm. The summary text accepts a dynamic place holder. So the server should
keep track of how many notifications sent to a particular user and I guess
have client respond by saying a notification was read(tapped)?

**Comment by macdonst** [comment]
@trazek yes, the summary text can accept a dynamic place holder because you need to specify a notification ID and the device knows how many pushes are in the inbox view.

For the count, you'd need to update the server when the user reads/taps on the notification.

**Comment by trazek** [comment]
Ok understood. Thanks for clarifying.

**Comment by trazek** [comment]
It's worth mentioning for the to get the inbox styling, I sent this data packet:

`"data": {
        "message": "An employee request PTO",
        "title": "PTO Request",
        "style": "inbox",
        "summaryText": "There are %n% messages"
      }`

And the placeholder `%n%` incremented on it's own. I did not give a notification id in this case.

Thanks again for clarifying

**Comment by macdonst** [comment]
@trazek not specifying the notId in this case makes the plugin assume it is 0.
