### ISSUE TITLE
notId: String or Integer?

### ISSUE THREAD

**Issue by dannywillems** [phonegap/phonegap-plugin-push#1318]
(Guidelines are not useful because it's a question).

In payload examples, `notId` is sent as a string (`"2"`, action buttons) and sometimes as an Integer (`1`, stacking). In the source code for Android, `notId` is cast to an Integer and it's always used as an Integer.
But, `notId` is used by the `messageMap` which is of type `HashMap<Integer, ArrayList<String>` and I think the Integer properties are never used because it's only to have a key. So, `notId`can be a string.

I think it would be very useful to get a string instead of an Integer because it gives more flexibility. This change won't affect current users which use Integer because casts are OK in Java and JavaScript.

**I didn't analyze the iOS case.**

**Comment by fredgalvao** [comment]
The thing is, although on everything plugin-side and application-side it could be handled with a `string notId`, it doesn't map to the actual parameter that the android API expects. Check the [docs here](https://developer.android.com/reference/android/app/NotificationManager.html), it's spec'd as `int id` there.

**Comment by dannywillems** [comment]
@fredgalvao Thanks. I didn't see it. For the project I work on, we implemented a hash map from string to ID between the client and the server. I suppose we are not the first one to do it so I think it could be a good feature to implement it. What do you think?
Maybe not with `notId` payload but something else like `notification_key`.

**Comment by dannywillems** [comment]
https://developer.android.com/reference/android/app/NotificationManager.html#notify(java.lang.String,%20int,%20android.app.Notification).
can be interesting.

**Comment by macdonst** [comment]
@dannywillems I need to stick with an int in order to be able to cancel notifications, replace one notification with an updated one, etc. The Android API requires and int so we're kinda stuck with that.

**Comment by dannywillems** [comment]
@macdonst You can have a map `HashMap<String, Int>` with string keys to notification id. We'll implement it very soon because we need to manage lots of notifications on the same time. If you are interested in, I can contribute to this repo for Android.

**Comment by macdonst** [comment]
Yes, please send a PR.
