### ISSUE TITLE
Differing behaviour with push.on on iOS/Android, when app is in background

### ISSUE THREAD

**Issue by mbaggott** [phonegap/phonegap-plugin-push#1320]
Not sure if this is intended behaviour or a bug. iOS is working great with the below payload. Am able to send multiple notifications to the phone, and they each get processed with push.on if the app is in the background, when the app is opened. This is the expected behaviour.

Android this does not happen, with below payload. Using the differing notId's registers different alerts in the shade. But when i open the app (without tapping notification), only the most recently sent notify is processed by push.on

Is this intended behaviour, an error with my configuration, or a bug?

INIT
```
var push = PushNotification.init({
      android: {
          senderID: "1062032799809",
          topics: ["scheduleAndroid"],
          clearNotifications: "false"
      },
      ios: {
          senderID: "1062032799809",
          gcmSandbox: true,
          alert: "true",
          badge: "true",
          sound: "true",
          clearBadge: "true",
          topics: ["scheduleIOS"]
      },
      windows: {}
    });
```
iOS PAYLOAD
```
{
        "to": "/topics/scheduleIOS", //Topic or single device
        "priority": "high", //If not set, notification won't be delivered on completely closed iOS app 
        "notification":{
          "title": "Notification title",  //Any value 
          "body": "Notification body",  //Any value
          "content_available": true,
          "sound": "default",
          "badge": "1"
        }
}
```
ANDROID PAYLOAD (Have tried sending POST with differing notId. Get multiple notifications ok, but only one notification is processed with push.on when app is brought to foreground
```
{
        "to": "/topics/scheduleAndroid",
        "data":{
          "title": "test",
          "body": "Notification body",
          "notId": 2,
          "content-available": "1"
        }
}
```

**Comment by macdonst** [comment]
@mbaggott can you try installing the latest code directly from Github? This bug may now be fixed.

**Comment by mbaggott** [comment]
@macdosnt will do, i'll report back in a few hours. Thank you

**Comment by mbaggott** [comment]
@macdonst this is indeed fixed on the github repo. Thanks so much again for your time.
