### ISSUE TITLE
Background push on Android doesn't work?

### ISSUE THREAD

**Issue by HectorFGarcia** [phonegap/phonegap-plugin-push#1322]
### Expected Behaviour

From docs:

> On Android if you want your on('notification') event handler to be called when your app is in the background it is relatively simple.
> 
> First the JSON you send from GCM will need to include "content-available": "1". This will tell the push plugin to call your on('notification') event handler no matter what other data is in the push notification.

### Actual Behaviour

Nothing happens when the app is in background.

### Reproduce Scenario (including but not limited to)

I'm sending this from Node using fcm-node.

```
{"to":"LonGkEy",
"notification":
{
"title":"Nuevo mensaje",
"body":"Bla bla bla bla"
},
"data":
{
"id_solicitud":2,
"id_company":7,
"texto":"ola k ase",
"content-aviable":1
}}
```
Response from FCM API is ok and if the app is active, works fine, but when it's in background, nothing happens. I recive the notification and that's all.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Ionic2 running on Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Nexus 5 (2013)

#### Cordova CLI version and cordova platform version

    cordova --version: 6.3.1
    cordova platform version android: 5.2.2

#### Plugin version

    cordova plugin version: 1.8.3

**Comment by fredgalvao** [comment]
Switch from

```json
{  
   "to":"LonGkEy",
   "notification":{  
      "title":"Nuevo mensaje",
      "body":"Bla bla bla bla"
   },
   "data":{  
      "id_solicitud":2,
      "id_company":7,
      "texto":"ola k ase",
      "content-aviable":1
   }
}
```

to

```json
{  
   "to":"LonGkEy",
   "data":{  
      "id_solicitud":2,
      "id_company":7,
      "title":"Nuevo mensaje",
      "body":"Bla bla bla bla",
      "texto":"ola k ase",
      "content-aviable":1
   }
}
```

and see if it works.

**Comment by HectorFGarcia** [comment]
Yes, that worked!

Is documented that you can't use notification, data and content-aviable at the same time?

**Comment by fredgalvao** [comment]
The thing is that, as of right now, you need to use the `data` namespace/object to send the payload to android and get all features/scenarios working. I don't think it has anything to do with `content-available`.
By the way, if you want to send notifications to iOS using GCM too, you'll need to send 2 separate payloads: 1 with `notification` for iOS and 1 with `data` for android.

I'm closing this as resolved, but feel free to reopen if you have any further issues regarding this topic.
