### ISSUE TITLE
Uncaught ReferenceError: PushNotification is not defined(…)

### ISSUE THREAD

**Issue by stoconnor** [phonegap/phonegap-plugin-push#1324]
At my wits end with $cordovaPushV5! Keep getting the following error:

ng-cordova.js:6378 Uncaught ReferenceError: PushNotification is not defined(…)

Problem points to the following line in ng-cordova.js:6378
        `push = PushNotification.init(options);`

Your system information:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.2.0-nightly-1823
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
ios-deploy version: Not installed
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v4.1.1
Xcode version: Xcode 7.0.1 Build version 7A1001 

Using the latest Cordova CLI (6.4.0), ng-cordova. This through testing on the device and below is my code for initializing:

```
$ionicPlatform.ready(function() {
localStorage.myPush = ; // I use a localStorage variable to persist the token

        $cordovaPushV5.initialize(  // important to initialize with the multidevice structure !!
            {
                android: {
                    senderID: "XXXX"
                },
                ios: {
                    alert: 'true',
                    badge: true,
                    sound: 'true',
                    clearBadge: true
                },
                windows: {}
            }
        ).then(function (result) {
            $cordovaPushV5.onNotification();
            $cordovaPushV5.onError();
            $cordovaPushV5.register().then(function (resultreg) {
                localStorage.myPush = resultreg;
                console.log(resultreg)
                var confirmPopup = $ionicPopup.alert({
          title: 'Popup',
          template: resultreg
          });
                // SEND THE TOKEN TO THE SERVER, best associated with your device id and user
            }, function (err) {
                // handle error
            });
        });
```

Been at this for hours at this stage, my package.json file:

```
"dependencies": {
    "gulp": "^3.5.6",
    "gulp-sass": "^2.0.4",
    "gulp-concat": "^2.2.0",
    "gulp-minify-css": "^0.3.0",
    "gulp-rename": "^1.2.0"
  },
  "devDependencies": {
    "bower": "^1.3.3",
    "gulp-util": "^2.2.14",
    "shelljs": "^0.3.0"
  },
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard",
    "cordova-plugin-inappbrowser",
    "cordova-plugin-contacts",
    "cordova-plugin-geolocation",
    "phonegap-plugin-push"
  ],
  "cordovaPlatforms": [
    "ios",
    "android"
  ]
}

```

Have the following in my config.xml also:

```
    <plugin name="phonegap-plugin-push" spec="~1.8.3">
        <variable name="SENDER_ID" value="XXXX" />
    </plugin>
```

I've even tried building a release version apk and installing it on the device to be 100% but to no avail. Is this an issue with ngCordova as the error suggests? Or is it a problem with the plugin?

**Comment by macdonst** [comment]
@stoconnor it's probably an issue with the version of cordova-android that ionic is including is too old for the push plugin. Can you do `cordova platforms` in your project directory to see what is included?

**Comment by mmmarc** [comment]
@stoconnor I think the cordova-android version is too old for that pluging. 
You can try making
`rm -rf plugins/`
`rm -rf platforms/`
`cordova prepare`
And then look after any warning

**Comment by akume** [comment]
+1.  getting the same error using ionic.  when i run 
`ionic serve --lab`
PushNotification is not defined

**Comment by akume** [comment]
```
cordova platforms:

Installed platforms:
  ios 4.3.0
Available platforms: 
  amazon-fireos ~3.6.3 (deprecated)
  android ~6.0.0
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  osx ~4.0.1
  webos ~3.7.0
```

**Comment by jcesarmobile** [comment]
Not familiar with ionic, but serve is used to preview the app, right? 
You have to actually run the app to make push work, you can't use the plugin in preview

**Comment by akume** [comment]
gotcha, but doesn't it have a browser push as well?

**Comment by jcesarmobile** [comment]
Yes, but for that you have to add browser platform

**Comment by tgensol** [comment]
I got the same issue, with the new plugin 1.9.0, on ios and android devices

**Comment by crewbeacon** [comment]
I am having the same issue

**Comment by macdonst** [comment]
Closing this issue as original poster never came back.

@tgensol @crewbeacon check to make sure your projects have the minimum cordova and platform versions for the plugin version you are using.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements

**Comment by gotoAndBliss** [comment]
Can confirm that everything is up to date. But this only appears in my chrome console debugger. I think it still works in the Platforms. Is that normal?
