### ISSUE TITLE
Android > stacking notifications

### ISSUE THREAD

**Issue by appzer** [phonegap/phonegap-plugin-push#1327]
Hello,

i want to stack my notification among each other.
In the documentation stand, i have to provide a  notification ID.

Where and how i define the  notification ID  in the payload.

kevin

**Comment by ef33zy** [comment]
@appzer it is defined here: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#stacking

**Comment by appzer** [comment]
`notId`
if found it. I have to read it two times.

Thanks

**Comment by appzer** [comment]
it works
