### ISSUE TITLE
Android Version 6 Not Receiving Notifications (After users migration OS to Android 6.0)

### ISSUE THREAD

**Issue by joaolori** [phonegap/phonegap-plugin-push#1328]
### Expected Behaviour

Receive Notification; This is happen in Production App, all notifcations are working, but some user who has migration android version to 6.0 are not receiving notifications.
### Actual Behaviour

Not Receiving
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 6.0
#### Cordova CLI version and cordova platform version

```
cordova --version                                    # e.g. 6.0.0
cordova platform version android                     # e.g. 4.1.1
```
#### Plugin version

```
cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3
```

**Comment by macdonst** [comment]
@joaolori you are not giving me much to go on here. Do you have any logs from the affected devices? Are you really using push plugin 1.5.3?

**Comment by fredgalvao** [comment]
I think that's data from the issue template. No real information on that, I believe.

**Comment by emc2spider** [comment]
I've had the same issue reported on my apps, currently researching what might be going on!

**Comment by macdonst** [comment]
Closing until someone provides me some details. One thing people should try is updating to 1.8.4 or higher where we no longer cache the GCM registration ID on Android. See issue #1251
