### ISSUE TITLE
XCODE 8.1 cannot find protocol definition GGLInstanceIDDelegate & GCMReceiverDelegate

### ISSUE THREAD

**Issue by envisiondata** [phonegap/phonegap-plugin-push#1329]
### Expected Behaviour

  Before I updated to xcode 8.1 everything worked fine. I even updated the plugin.
### Actual Behaviour

  Push Plugin register failed
  cannot find protocol definition GGLInstanceIDDelegate
  cannot find protocol definition GCMReceiverDelegate
#### Steps to Reproduce

  simply compile
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

  iOS 10.1
#### Cordova CLI version and cordova platform version

```
cordova --version                                    # e.g. 6.0.0
cordova platform version android                     # e.g. 4.1.1
```
#### Plugin version

   version 1.8.3

**Comment by hackfanatic** [comment]
Clean install of safari, can confirm I'm facing the same issue outlined above

Cordova version - 6.4.0

**Comment by macdonst** [comment]
@envisiondata can you make sure you have [CocoaPods installed](https://guides.cocoapods.org/using/getting-started.html) then try the latest code from master to see if your bug is resolved.

**Comment by envisiondata** [comment]
Simon,

I had to downgrade Xcode to get this live. Once I go back to Xcode 8 I will try again. 

James

**Comment by macdonst** [comment]
@envisiondata okay, cool. I have upgraded to Xcode 8.1 today and am not running into any problems.

**Comment by hackfanatic** [comment]
I am using xcode-select to switch between xcode 8 and 8.1, installed the cocoapods gem and package.json points to the repo.

xcode 8 currently throws

```
In file included from /Users/esh/work/twisted/mobile-demo/platforms/ios/BlueprintApp/Plugins/phonegap-plugin-push/AppDelegate+notification.m:10:
/Users/esh/work/twisted/mobile-demo/platforms/ios/BlueprintApp/Plugins/phonegap-plugin-push/PushPlugin.h:31:35: warning: cannot find protocol definition for 'GGLInstanceIDDelegate'
@interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate>
                                  ^
/Users/esh/work/twisted/mobile-demo/platforms/ios/BlueprintApp/Plugins/phonegap-plugin-push/PushPlugin.h:30:11: note: protocol 'GGLInstanceIDDelegate' has no definition
@protocol GGLInstanceIDDelegate;
```

and 8.1 konks out a bit, with a couple of deprecation warnings.

```
In file included from /Users/esh/work/twisted/mobile-demo/platforms/ios/BlueprintApp/Plugins/phonegap-plugin-push/PushPlugin.m:29:
/Users/esh/work/twisted/mobile-demo/platforms/ios/BlueprintApp/Plugins/phonegap-plugin-push/PushPlugin.h:31:35: warning: cannot find protocol definition for 'GGLInstanceIDDelegate'
@interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate>
                                  ^
/Users/esh/work/twisted/mobile-demo/platforms/ios/BlueprintApp/Plugins/phonegap-plugin-push/PushPlugin.h:30:11: note: protocol 'GGLInstanceIDDelegate' has no definition
@protocol GGLInstanceIDDelegate;
          ^
/Users/esh/work/twisted/mobile-demo/platforms/ios/BlueprintApp/Plugins/phonegap-plugin-push/PushPlugin.m:100:9: warning: 'UIRemoteNotificationType' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]
        UIRemoteNotificationType notificationTypes = UIRemoteNotificationTypeNone;
        ^
...
```

**Comment by hackfanatic** [comment]
Actually spoke too soon, i hadn't setup cocoa pods, and it failed with an error saying i needed to `pod setup`. Though after this I run into 
`ld: library not found for -lPods-BlueprintApp beta` tested on xcode 8.1
