### ISSUE TITLE
iOS compilation error 'FirebaseAnalytics.h' not found

### ISSUE THREAD

**Issue by akz92** [phonegap/phonegap-plugin-push#1331]
### Expected Behaviour

Compile and run the app on iOS simulator

### Actual Behaviour

Compilation error

```
** BUILD FAILED **


The following build commands failed:
	CompileC build/*******.build/Debug-iphonesimulator/*******.build/Objects-normal/i386/PushPlugin.o *******/Plugins/phonegap-plugin-push/PushPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler

(1 failure)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/***/dev/******/platforms/ios/cordova/build-debug.xcconfig,-project,*******.xcodeproj,ARCHS=i386,-target,*******,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/***/dev/******/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/***/dev/*******/platforms/ios/build/sharedpch
```

For more details please check the log

#### Platform and Version

iOS 8.0 or greater

#### Cordova CLI version and cordova platform version

    cordova --version                                    # 6.3.1
    cordova platform version ios                         # 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # 1.8.4

#### Logs taken while reproducing problem

https://gist.github.com/akz92/4a7ab4f5e507ab5ae98b4e9af9bc4d9a

**Comment by macdonst** [comment]
@akz92 I'm not taking bugs on the FCM branch right now as it is a development branch. Also, it won't work in the simulator so don't even try it.
