### ISSUE TITLE
Missing Files on Phonegap build compilation for Android

### ISSUE THREAD

**Issue by Sylvian** [phonegap/phonegap-plugin-push#1332]
Here is the compilation error log for Android:
(It's working fine for iOS)

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-gcm:9.8+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/
         file:/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
         file:/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/
         file:/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
     Required by:
         :project:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED`

It seems these two files aren't available on the specified server... Error is occuring since a few hours.

> https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
> https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/

Thanks for your help, this plugin is working awesome for me on Android and iOS.

**Comment by manuelfc1** [comment]
same error happens to me

**Comment by manuelfc1** [comment]
solved by removing the android project and reinstalling it. 
cordova platform rm android
cordova platform add android

**Comment by macdonst** [comment]
@Sylvian the PGB team has asked for questions regarding that service to be opened at:

https://forums.adobe.com/community/phonegap/build
