### ISSUE TITLE
Version 1.8.4 not compatible with PhoneGap Build on Android

### ISSUE THREAD

**Issue by aplimovil** [phonegap/phonegap-plugin-push#1333]
### Expected Behaviour
The Android app should compile in PhoneGap Build normally.

### Actual Behaviour
The app doesn't compile due to a "Could not find any version that matches com.google.android.gms:play-services-gcm:9.8+" error.

Note that using version 1.8.3 works just fine, but the new 1.8.4 release causes this problem.

### Reproduce Scenario (including but not limited to)
Just create an app in PGB using version 1.8.4 of this plugin and the CLI/platform versions below.

#### Steps to Reproduce 
See above.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
N/A

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
N/A

#### Cordova CLI version and cordova platform version
CLI: 6.3.0
Platform (Android): 5.2.1

#### Plugin version
1.8.4

#### Sample Push Data Payload
N/A

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
Build Date: 2016-11-02 03:22:51 +0000
Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-gcm:9.8+.
     Versions that do not match:
         9.4.0
         9.2.1
         9.2.0
         9.0.2
         9.0.1
         + 5 more
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/
         https://jcenter.bintray.com/com/google/android/gms/play-services-gcm/maven-metadata.xml
         https://jcenter.bintray.com/com/google/android/gms/play-services-gcm/
         file:/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
         file:/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/
         file:/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
     Required by:
         :project:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.007 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-gcm:9.8+.
     Versions that do not match:
         9.4.0
         9.2.1
         9.2.0
         9.0.2
         9.0.1
         + 5 more
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/
         https://jcenter.bintray.com/com/google/android/gms/play-services-gcm/maven-metadata.xml
         https://jcenter.bintray.com/com/google/android/gms/play-services-gcm/
         file:/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
         file:/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/
         file:/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
     Required by:
         :project:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by macdonst** [comment]
@aplimovil the PGB team has asked for questions regarding that service to be opened at:

https://forums.adobe.com/community/phonegap/build
