### ISSUE TITLE
ios build field

### ISSUE THREAD

**Issue by arv10singh** [phonegap/phonegap-plugin-push#1335]
cordova --version    6.3.1

cordova plugin version | grep phonegap-plugin-push    1.8.4

xcode-> Version 6.1 (6A1052d)

iOS Simulator (Version 8.1 (550.3)) set device -> iphone-> 6

ios build failed (Android is working fine)

--------------------------------------
In file included from /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/AppDelegate+notification.m:10:
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.h:32:35: warning: cannot find protocol definition for 'GGLInstanceIDDelegate'
@interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate, GCMReceiverDelegate>
                                  ^
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.h:32:58: warning: cannot find protocol definition for 'GCMReceiverDelegate'
@interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate, GCMReceiverDelegate>
                                                         ^
2 warnings generated.

CompileC build/cargoBookingApp.build/Debug-iphonesimulator/cargoBookingApp.build/Objects-normal/i386/PushPlugin.o cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/bitlasoft/.rvm/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk -fexceptions -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -mios-simulator-version-min=8.0 -iquote /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/cargoBookingApp.build/Debug-iphonesimulator/cargoBookingApp.build/cargoBookingApp-generated-files.hmap -I/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/cargoBookingApp.build/Debug-iphonesimulator/cargoBookingApp.build/cargoBookingApp-own-target-headers.hmap -I/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/cargoBookingApp.build/Debug-iphonesimulator/cargoBookingApp.build/cargoBookingApp-all-target-headers.hmap -iquote /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/cargoBookingApp.build/Debug-iphonesimulator/cargoBookingApp.build/cargoBookingApp-project-headers.hmap -I/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/emulator/include -I/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/emulator/usr/local/lib/include -I/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/UninstalledProducts/include -I/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/UninstalledProducts/iphonesimulator/include -I/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/emulator -I/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/cargoBookingApp.build/Debug-iphonesimulator/cargoBookingApp.build/DerivedSources/i386 -I/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/cargoBookingApp.build/Debug-iphonesimulator/cargoBookingApp.build/DerivedSources -F/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/emulator -include /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/sharedpch/cargoBookingApp-Prefix-eefvrtdbrdidrygxmqxzvjbheofr/cargoBookingApp-Prefix.pch -MMD -MT dependencies -MF /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/cargoBookingApp.build/Debug-iphonesimulator/cargoBookingApp.build/Objects-normal/i386/PushPlugin.d --serialize-diagnostics /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/cargoBookingApp.build/Debug-iphonesimulator/cargoBookingApp.build/Objects-normal/i386/PushPlugin.dia -c /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m -o /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/cargoBookingApp.build/Debug-iphonesimulator/cargoBookingApp.build/Objects-normal/i386/PushPlugin.o

In file included from /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:29:
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.h:32:35: warning: cannot find protocol definition for 'GGLInstanceIDDelegate'
@interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate, GCMReceiverDelegate>
                                  ^
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.h:32:58: warning: cannot find protocol definition for 'GCMReceiverDelegate'
@interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate, GCMReceiverDelegate>
                                                         ^
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:86:39: warning: capturing 'self' strongly in this block is likely to lead to a retain cycle [-Warc-retain-cycles]
            [weakSelf failWithMessage:self.callbackId withMsg:@"" withError:error];
                                      ^~~~
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:55:5: note: block will be retained by an object strongly retained by the captured object
    gcmRegistrationHandler = ^(NSString *registrationToken, NSError *error){
    ^~~~~~~~~~~~~~~~~~~~~~
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:223:54: warning: 'UIRemoteNotificationTypeNone' is deprecated: first deprecated in iOS 8.0 - Use UIUserNotificationType for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]
        UIRemoteNotificationType notificationTypes = UIRemoteNotificationTypeNone;
                                                     ^
In module 'UIKit' imported from /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/emulator/include/Cordova/CDVAvailabilityDeprecated.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:62:5: note: 'UIRemoteNotificationTypeNone' has been explicitly marked deprecated here
    UIRemoteNotificationTypeNone    = 0,
    ^
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:232:34: warning: 'UIRemoteNotificationTypeBadge' is deprecated: first deprecated in iOS 8.0 - Use UIUserNotificationType for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]
            notificationTypes |= UIRemoteNotificationTypeBadge;
                                 ^
In module 'UIKit' imported from /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/emulator/include/Cordova/CDVAvailabilityDeprecated.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:63:5: note: 'UIRemoteNotificationTypeBadge' has been explicitly marked deprecated here
    UIRemoteNotificationTypeBadge   = 1 << 0,
    ^
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:240:34: warning: 'UIRemoteNotificationTypeSound' is deprecated: first deprecated in iOS 8.0 - Use UIUserNotificationType for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]
            notificationTypes |= UIRemoteNotificationTypeSound;
                                 ^
In module 'UIKit' imported from /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/emulator/include/Cordova/CDVAvailabilityDeprecated.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:64:5: note: 'UIRemoteNotificationTypeSound' has been explicitly marked deprecated here
    UIRemoteNotificationTypeSound   = 1 << 1,
    ^
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:248:34: warning: 'UIRemoteNotificationTypeAlert' is deprecated: first deprecated in iOS 8.0 - Use UIUserNotificationType for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]
            notificationTypes |= UIRemoteNotificationTypeAlert;
                                 ^
In module 'UIKit' imported from /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/emulator/include/Cordova/CDVAvailabilityDeprecated.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:65:5: note: 'UIRemoteNotificationTypeAlert' has been explicitly marked deprecated here
    UIRemoteNotificationTypeAlert   = 1 << 2,
    ^
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:254:30: warning: 'UIRemoteNotificationTypeNewsstandContentAvailability' is deprecated: first deprecated in iOS 8.0 - Use UIUserNotificationType for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]
        notificationTypes |= UIRemoteNotificationTypeNewsstandContentAvailability;
                             ^
In module 'UIKit' imported from /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/emulator/include/Cordova/CDVAvailabilityDeprecated.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:66:5: note: 'UIRemoteNotificationTypeNewsstandContentAvailability' has been explicitly marked deprecated here
    UIRemoteNotificationTypeNewsstandContentAvailability = 1 << 3,
    ^
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:269:34: warning: 'UIRemoteNotificationTypeNone' is deprecated: first deprecated in iOS 8.0 - Use UIUserNotificationType for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]
        if (notificationTypes == UIRemoteNotificationTypeNone)
                                 ^
In module 'UIKit' imported from /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/emulator/include/Cordova/CDVAvailabilityDeprecated.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:62:5: note: 'UIRemoteNotificationTypeNone' has been explicitly marked deprecated here
    UIRemoteNotificationTypeNone    = 0,
    ^
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:343:15: warning: 'UIRemoteNotificationTypeBadge' is deprecated: first deprecated in iOS 8.0 - Use UIUserNotificationType for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]
             (UIRemoteNotificationTypeBadge | UIRemoteNotificationTypeSound | UIRemoteNotificationTypeAlert)];
              ^
In module 'UIKit' imported from /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/emulator/include/Cordova/CDVAvailabilityDeprecated.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:63:5: note: 'UIRemoteNotificationTypeBadge' has been explicitly marked deprecated here
    UIRemoteNotificationTypeBadge   = 1 << 0,
    ^
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:3
43:47: warning: 'UIRemoteNotificationTypeSound' is deprecated: first deprecated in iOS 8.0 - Use UIUserNotificationType for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]
             (UIRemoteNotificationTypeBadge | UIRemoteNotificationTypeSound | UIRemoteNotificationTypeAlert)];
                                              ^
In module 'UIKit' imported from /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/emulator/include/Cordova/CDVAvailabilityDeprecated.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:64:5: note: 'UIRemoteNotificationTypeSound' has been explicitly marked deprecated here
    UIRemoteNotificationTypeSound   = 1 << 1,
    ^
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:343:79: warning: 'UIRemoteNotificationTypeAlert' is deprecated: first deprecated in iOS 8.0 - Use UIUserNotificationType for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]
             (UIRemoteNotificationTypeBadge | UIRemoteNotificationTypeSound | UIRemoteNotificationTypeAlert)];
                                                                              ^
In module 'UIKit' imported from /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/emulator/include/Cordova/CDVAvailabilityDeprecated.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:65:5: note: 'UIRemoteNotificationTypeAlert' has been explicitly marked deprecated here
    UIRemoteNotificationTypeAlert   = 1 << 2,
    ^
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:342:48: warning: 'registerForRemoteNotificationTypes:' is deprecated: first deprecated in iOS 8.0 - Please use registerForRemoteNotifications and registerUserNotificationSettings: instead [-Wdeprecated-declarations]
            [[UIApplication sharedApplication] registerForRemoteNotificationTypes:
                                               ^
In module 'UIKit' imported from /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/emulator/include/Cordova/CDVAvailabilityDeprecated.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:310:1: note: 'registerForRemoteNotificationTypes:' has been explicitly marked deprecated here
- (void)registerForRemoteNotificationTypes:(UIRemoteNotificationType)types NS_DEPRECATED_IOS(3_0, 8_0, "Please use registerForRemoteNotifications and registerUserNotificationSettings: instead");
^
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:602:42: warning: undeclared selector 'userHasRemoteNotificationsEnabled' [-Wundeclared-selector]
    if ([appDelegate respondsToSelector:@selector(userHasRemoteNotificationsEnabled)]) {
                                         ^
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:603:49: warning: undeclared selector 'userHasRemoteNotificationsEnabled' [-Wundeclared-selector]
        enabled = [appDelegate performSelector:@selector(userHasRemoteNotificationsEnabled)];
                                                ^
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:603:17: warning: incompatible pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from 'id' [-Wint-conversion]
        enabled = [appDelegate performSelector:@selector(userHasRemoteNotificationsEnabled)];
                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:614:9: warning: local declaration of 'callbackId' hides instance variable [-Wshadow-ivar]
    if (callbackId != nil)
        ^
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:617:73: warning: local declaration of 'callbackId' hides instance variable [-Wshadow-ivar]
        [self.commandDelegate sendPluginResult:commandResult callbackId:callbackId];
                                                                        ^
/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/PushPlugin.m:636:69: warning: local declaration of 'callbackId' hides instance variable [-Wshadow-ivar]
    [self.commandDelegate sendPluginResult:commandResult callbackId:callbackId];
                                                                    ^
19 warnings generated.

Ld build/emulator/cargoBookingApp.app/cargoBookingApp normal i386
    cd /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/bitlasoft/.rvm/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk -L/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/emulator -L/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/cargoBookingApp/Plugins/phonegap-plugin-push/GCM/Libraries -F/Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/emulator -filelist /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/cargoBookingApp.build/Debug-iphonesimulator/cargoBookingApp.build/Objects-normal/i386/cargoBookingApp.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -objc_abi_version -Xlinker 2 -ObjC -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=8.0 /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/emulator/libCordova.a -lGGLCloudMessaging -lGGLCore -lGGLInstanceIDLib -lGIP_Reachability -lGSDK_Overload -lGTMSessionFetcher_core -lGTMSessionFetcher_full -lGTMStackTrace -lGTM_AddressBook -lGTM_DebugUtils -lGTM_GTMURLBuilder -lGTM_KVO -lGTM_NSData+zlib -lGTM_NSDictionary+URLArguments -lGTM_NSScannerJSON -lGTM_NSStringHTML -lGTM_NSStringXML -lGTM_Regex -lGTM_RoundedRectPath -lGTM_StringEncoding -lGTM_SystemVersion -lGTM_UIFont+LineHeight -lGTM_core -lGTM_iPhone -lGcmLib -lProtocolBuffers -framework AddressBook -Xlinker -dependency_info -Xlinker /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/cargoBookingApp.build/Debug-iphonesimulator/cargoBookingApp.build/Objects-normal/i386/cargoBookingApp_dependency_info.dat -o /Users/bitlasoft/arvind/cargoBookingApp/platforms/ios/build/emulator/cargoBookingApp.app/cargoBookingApp

Undefined symbols for architecture i386:
  "_deflate", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByCompressingBytes:length:compressionLevel:mode:] in libGTM_NSData+zlib.a(GTMNSData+zlib.o)
  "_deflateEnd", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByCompressingBytes:length:compressionLevel:mode:] in libGTM_NSData+zlib.a(GTMNSData+zlib.o)
  "_deflateInit2_", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByCompressingBytes:length:compressionLevel:mode:] in libGTM_NSData+zlib.a(GTMNSData+zlib.o)
  "_inflate", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByInflatingBytes:length:isRawData:] in libGTM_NSData+zlib.a(GTMNSData+zlib.o)
  "_inflateEnd", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByInflatingBytes:length:isRawData:] in libGTM_NSData+zlib.a(GTMNSData+zlib.o)
  "_inflateInit2_", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByInflatingBytes:length:isRawData:] in libGTM_NSData+zlib.a(GTMNSData+zlib.o)
  "_sqlite3_bind_blob", referenced from:
      ___59-[GMRSqliteStore upsertStatementForRecord:inTableWithName:]_block_invoke350 in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore saveMessageWithRmqId:tag:data:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_bind_double", referenced from:
      ___59-[GMRSqliteStore upsertStatementForRecord:inTableWithName:]_block_invoke350 in libGGLCore.a(GMRSqliteStore.o)
  "_sqlite3_bind_int", referenced from:
      -[GCMRmq2PersistentStore saveMessageWithRmqId:tag:data:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore updateLastOutgoingRmqId:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore saveSyncMessageWithRmqID:expirationTime:apnsReceived:mcsReceived:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_bind_int64", referenced from:
      ___59-[GMRSqliteStore upsertStatementForRecord:inTableWithName:]_block_invoke350 in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore saveMessageWithRmqId:tag:data:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore deleteMessagesFromTable:withRmqIds:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore updateLastOutgoingRmqId:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore saveSyncMessageWithRmqID:expirationTime:apnsReceived:mcsReceived:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_bind_null", referenced from:
      ___59-[GMRSqliteStore upsertStatementForRecord:inTableWithName:]_block_invoke350 in libGGLCore.a(GMRSqliteStore.o)
  "_sqlite3_bind_text", referenced from:
      -[GMRSqliteStore bindToStatement:text:atIndex:] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore saveUnackedS2dMessageWithRmqId:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore deleteMessagesFromTable:withRmqIds:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore saveSyncMessageWithRmqID:expirationTime:apnsReceived:mcsReceived:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore updateSyncMessageWithRmqID:column:value:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_changes", referenced from:
      -[GCMRmq2PersistentStore deleteMessagesFromTable:withRmqIds:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore deleteExpiredOrFinishedSyncMessages:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_clear_bindings", referenced from:
      -[GMRSqliteStore tableExists:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore rowCountForTableWithName:columnName:columnValue:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore recordsForQuery:] in libGGLCore.a(GMRSqliteStore.o)
  "_sqlite3_close", referenced from:
      -[GMRSqliteStore closeDatabase] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore dealloc] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_column_blob", referenced from:
      -[GMRSqliteStore valueAtColumn:forStatement:] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore scanOutgoingRmqMessagesWithHandler:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_column_bytes", referenced from:
      -[GMRSqliteStore valueAtColumn:forStatement:] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore scanOutgoingRmqMessagesWithHandler:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_column_count", referenced from:
      -[GMRSqliteStore recordsForQuery:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore validateDatabase] in libGGLCore.a(GMRSqliteStore.o)
  "_sqlite3_column_double", referenced from:
      -[GMRSqliteStore valueAtColumn:forStatement:] in libGGLCore.a(GMRSqliteStore.o)
  "_sqlite3_column_int", referenced from:
      -[GMRSqliteStore rowCountForTableWithName:columnName:columnValue:] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore scanOutgoingRmqMessagesWithHandler:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore querySyncMessageWithRmqID:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_column_int64", referenced from:
      -[GMRSqliteStore valueAtColumn:forStatement:] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore queryHighestRmqId] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore queryLastRmqId] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore scanOutgoingRmqMessagesWithHandler:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore querySyncMessageWithRmqID:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_column_name", referenced from:
      -[GMRSqliteStore recordsForQuery:] in libGGLCore.a(GMRSqliteStore.o)
  "_sqlite3_column_text", referenced from:
      -[GMRSqliteStore columnsForTableWithName:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore validateDatabase] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore valueAtColumn:forStatement:] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore unackedS2dRmqIds] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore querySyncMessageWithRmqID:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_column_type", referenced from:
      -[GMRSqliteStore valueAtColumn:forStatement:] in libGGLCore.a(GMRSqliteStore.o)
  "_sqlite3_errcode", referenced from:
      -[GCMRmq2PersistentStore saveMessageWithRmqId:tag:data:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore deleteExpiredOrFinishedSyncMessages:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore saveSyncMessageWithRmqID:expirationTime:apnsReceived:mcsReceived:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore updateSyncMessageWithRmqID:column:value:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore lastErrorCode] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_errmsg", referenced from:
      -[GMRSqliteStore lastErrorMessage] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore saveMessageWithRmqId:tag:data:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore lastErrorMessage] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_exec", referenced from:
      -[GMRSqliteStore beginTransaction] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore endTransaction] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore rollbackTransaction] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore createTableWithName:command:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore dropTableWithName:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_finalize", referenced from:
      -[GMRSqliteStore columnsForTableWithName:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore deleteRecordFromTableWithName:columnName:columnValue:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore deleteRecordsFromTableWithName:condition:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore recordsForQuery:] in libGGLCore.a(GMRS

**Comment by macdonst** [comment]
@arv10singh nope, not even going to try to support XCode 6 problems. Please upgrade to [minimum version](https://github.com/phonegap/phonegap-plugin-push/blob/ca18653d6ff332db41f48824a2d65bd2699ed8bc/docs/INSTALLATION.md#xcode) and better yet go to XCode 8.
