### ISSUE TITLE
Registration id saving to database

### ISSUE THREAD

**Issue by mbachaalani** [phonegap/phonegap-plugin-push#1336]
Hello,

I have an app where the user have to login to access it. Once he logs in I send the registration id to be saved to the database (a new row is created in the table).
Now I am sending a new update of the app where a new api server key is created with a new sender id. The users already having the app and logged in should have when upgrading the app a new registration id to be updated in the database. I am wondering if there is a way to update the registration id even if the user is logged in since I am doing this update only on log in.
I was thinking to do an update of the registration id on each page visit but is there a better way to do that because I do not want to call a service on each page navigation.
As well when keeping the old api key and sender id I got an authentication failed erro from the server, so I was forced to change them which means the previous reg Ids for already signed in users became invalid and this leads to making them logout then log in again. Is there a solution to this issue. How is it usually handled in that case?

Thank you.

**Comment by macdonst** [comment]
@mbachaalani if you listen for the registration event you will be notified when the registration ID changes and you can update your server.

**Comment by fredgalvao** [comment]
The correct time for you to listen to the `registration` event is whenever the app starts. So I suggest moving your code to the start of the cicle, which is immediately after you receive the `deviceready` event from cordova/phonegap. That way, regardless of whether you have a new registrationId, you'll always receive the most up-to-date value everytime the application starts, and you can then notify or not your server
