### ISSUE TITLE
Build error after adding the plugin

### ISSUE THREAD

**Issue by D4rthR4tz3** [phonegap/phonegap-plugin-push#1338]
After installing the plugin I get the following message while trying to compile the app:

> Error:Error converting bytecode to dex:
> Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;
> 
> Error:Execution failed for task ':transformClassesWithDexForArmv7Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

Device: Samsung Galaxy Tab S2 (Android 6.0.1) - but that's not important

Cordova version: 6.4.0
Cordova platform version Android: 6.0.0

Plugin version: 1.9.0

Android Support Library version: 23.2.1
Google Play Services version: 37
Android Support Repository version: 39.0.0
Google Repository version: 38

Android Studio version: 2.2.2

This is my [build.gradle.txt](https://github.com/phonegap/phonegap-plugin-push/files/571069/build.gradle.txt)

And a list of plugins I'm currently using:

> com.dvdbrink.cordova.indexeddb 0.1.0 "Cordova-indexedDB"
> cordova-media-with-compression 2.0.22 "Media With Compression: Alpha Software Edition"
> cordova-plugin-android-permissions 0.10.0 "Permissions"
> cordova-plugin-camera 2.3.0 "Camera"
> cordova-plugin-compat 1.0.0 "Compat"
> cordova-plugin-crosswalk-webview 2.1.0 "Crosswalk WebView Engine"
> cordova-plugin-device 1.1.3 "Device"
> cordova-plugin-email-composer 0.8.3 "EmailComposer"
> cordova-plugin-file 3.0.0 "File"
> cordova-plugin-file-opener2 2.0.2 "File Opener2"
> cordova-plugin-file-transfer 1.6.0 "File Transfer"
> cordova-plugin-google-analytics 1.6.0 "Google Universal Analytics Plugin"
> cordova-plugin-googleplayservices 19.0.3 "Google Play Services for Android"
> cordova-plugin-image-picker 1.1.1 "ImagePicker"
> cordova-plugin-inappbrowser 1.5.0 "InAppBrowser"
> cordova-plugin-network-information 1.3.0 "Network Information"
> cordova-plugin-splashscreen 4.0.0 "Splashscreen"
> cordova-plugin-statusbar 2.2.0 "StatusBar"
> cordova-plugin-whitelist 1.3.0 "Whitelist"
> phonegap-plugin-barcodescanner 6.0.2 "BarcodeScanner"
> phonegap-plugin-push 1.9.0 "PushPlugin"

**Comment by macdonst** [comment]
@D4rthR4tz3 I'd be willing to bet that:

```
cordova-plugin-googleplayservices 19.0.3 "Google Play Services for Android"
```

is the problem. You shouldn't need to add Google Play Services in as a jar. Let gradle do the downloading for you.

**Comment by D4rthR4tz3** [comment]
That's it! Thanks for your help :)
