### ISSUE TITLE
Apn tag pass on server for redirection in app on client side

### ISSUE THREAD

**Issue by mbachaalani** [phonegap/phonegap-plugin-push#1339]
Hello,

I am using the latest version of pushsharp the payload looks like that Payload = JObject.Parse("{"aps":{ "alert" : "Hello!" ,\"url\":\"/pathtopage.html\"}} }") but I also want to add a tag to be redirected to a specific page once the notification tile is clicked. In the old push I used
pushBroker.QueueNotification(new AppleNotification()
.ForDeviceToken(deviceToken)
.WithAlert(message)
.WithCustomItem("tag", tag));
where a custom item was added for the tag. 
I have added on the client side data.tag to redirect to specific page but when the notification arrives and I click on it no redirection i done (app is loaded in foreground but I it seems data.tag is not executed because I've put it in an alert). Is there something in the way I set it on the server side or should I do something on the client side to force the app to reload on notification tile click?

Thank you.

**Comment by macdonst** [comment]
@mbachaalani looks like you should use:

```
Payload = JObject.Parse("{"aps":{ "alert" : "Hello!" ,"url":"/pathtopage.html", "tag": "my tag"}} }") 
```

**Comment by mbachaalani** [comment]
Thank you. Either the tag or url can be used but the thing is to use on notification event data.url if url set in payload or data.tag if tag used in payload so the idea is that on the server we set a custom name.

**Comment by macdonst** [comment]
@mbachaalani when the notification event is fired the the object will look like this:

```
{
  "message": "Hello!",
  "additionalData": {
    "url": "/pathtopage.html", 
    "tag": "my tag"
  }
}
```

Then you can write a notification event handler like:

```
push.on('notification', function(data) {
    if (data.additionalData.url) {
      document.location.href = data.additionalData.url;
    } else if (data.additionalData.tag) {
      // something with tag
    }
});
```

**Comment by macdonst** [comment]
Assumed answered, re-open if still an issue.
