### ISSUE TITLE
Drop support for iOS 8

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-plugin-push#1340]
As of the 2.0.0 branch I'll be dropping support for iOS 8. That means I'll no longer actively be checking to see if the plugin still works on iOS 8 and possibly removing spaghetti code to support this old version if that makes the plugin cleaner.

Current, as of this writing, [statistics](https://developer.apple.com/support/app-store/) show iOS 9 & 10 adoption at 92% of the market.

The plugin may still work with iOS 8 but it will not actively be supported.

Discuss...

**Comment by jcesarmobile** [comment]
If we remove the spaghetti code to support iOS 8 it then it will not work on iOS 8 (I'm saying this because you say it may work)

But I'm +1 with it, so I can update my iPad

**Comment by macdonst** [comment]
@jcesarmobile for sure, I'm dropping support for iOS8. Possibly remove the iOS 8 specific code if there is no strong objection.

**Comment by Gerjo** [comment]
Bear in mind, losing 8% of 10 users isn't as bad as 8% of a million. Of course, one could always pin the version to an older build.

**Comment by jcesarmobile** [comment]
The thing is, the v.2.0.x branch will be the one with FCM support, so older versions won't get FCM

**Comment by macdonst** [comment]
Currently only 6% of devices are on iOS 8 or earlier as per [Apple](https://developer.apple.com/support/app-store/) and iOS 8 is no longer being supported in cordova-ios 4.4.0 (#1498) which has some bug fixes we really need. With respect to those two data points I'm going ahead with removing all the ifdef spaghetti code that allows the plugin to work on iOS 8 or earlier.
