### ISSUE TITLE
Fail to add 1.9.0 to ios platform

### ISSUE THREAD

**Issue by uamstar** [phonegap/phonegap-plugin-push#1342]
### Expected Behaviour
succeed to install 1.9.0 to ios platform
### Actual Behaviour
$ cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable SENDER_ID="xxxxxxx" <- (real ID removed)
Fetching plugin "https://github.com/phonegap/phonegap-plugin-push" via git clone
Repository "https://github.com/phonegap/phonegap-plugin-push" checked out to git ref "master".
Installing "phonegap-plugin-push" for android
ANDROID_HOME=/Users/laihioh/android-sdk-macosx
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home
Subproject Path: CordovaLib
Incremental java compilation is an incubating feature.
:clean
:CordovaLib:clean

BUILD SUCCESSFUL

Total time: 2.63 secs
Subproject Path: CordovaLib
Installing "phonegap-plugin-push" for ios
Failed to install 'phonegap-plugin-push':Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/laihioh/Documents/Development/ionic/S168App/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: pod: Command failed with exit code 1

### Reproduce Scenario (including but not limited to)
A ionic project "S168App" exists and used 1.8.1 phonegap-plugin-push,
#### Steps to Reproduce 
1. remove platform io
$ cordova platform rm ios
2. remove 1.8.1
$ cordova plugin rm phonegap-plugin-push
3. install current version from git
cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable SENDER_ID="xxxxxxx" <- (real ID removed)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
$ cordova -v
6.4.0
$ cordova platform version ios
Installed platforms:
  android 6.0.0
  ios 4.3.0
Available platforms: 
  amazon-fireos ~3.6.3 (deprecated)
......
$ gem which cocoapods
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods.rb

xcode: 8.1
ios: 10.1 SDK

#### Cordova CLI version and cordova platform version
$ cordova -v
6.4.0
$ cordova platform version ios
Installed platforms:
  android 6.0.0
  ios 4.3.0
Available platforms: 
  amazon-fireos ~3.6.3 (deprecated)
......

#### Plugin version
1.9.0

**Comment by M-H-M-A** [comment]
I am facing same issue  when i run "sudo cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable SENDER_ID="XXXXXXXXXXX"
i got error : 
Failed to install 'phonegap-plugin-push':undefined
Error: /Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)

Usage:

    $ pod COMMAND

      CocoaPods, the Cocoa library package manager.

Commands:

    + cache      Manipulate the CocoaPods cache
    + env        Display pod environment
    + init       Generate a Podfile for the current directory
    + install    Install project dependencies according to versions from a
                 Podfile.lock
    + ipc        Inter-process communication
    + lib        Develop pods
    + list       List pods
    + outdated   Show outdated project dependencies
    + repo       Manage spec-repositories
    + setup      Setup the CocoaPods environment
    + spec       Manage pod specs
    + update     Update outdated project dependencies and create new Podfile.lock

Options:

    --silent     Show nothing
    --version    Show the version of the tool
    --verbose    Show more debugging information
    --no-ansi    Show output without ANSI codes
    --help       Show help banner of specified command
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:47:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'

**Comment by podliy16** [comment]
same here

**Comment by uamstar** [comment]
@M-H-M-A , as the error said, don't run with root or sudo, "chown" to files for the login name instead, if you have permission issues of some files.

**Comment by macdonst** [comment]
@uamstar do you have CocoaPods installed?

@M-H-M-A you can run CocoaPods as root. Don't do `sudo cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable SENDER_ID="XXXXXXXXXXX` just do `cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable SENDER_ID="XXXXXXXXXXX`

**Comment by skyprimer** [comment]
I'm using Phonegap Build (6.3.0 with IOS). It installs the plugin without any error but does not registering to topics...

I don't know what the hack cocoapads is :) We phonegap build users need that?

This is the code that gets user registered at the start of my app. But the loading gif keeps turning which means no registeration ID

`var push = PushNotification.init({
            "android": {
                "senderID": "926282828595",
				 "topics":["android"]
            },
            "ios": {
                    "gcmSandbox": "true",
					"senderID": "926282828595",
                    "sound": "true",
                    "alert": "true",
                    "badge": "true",
                    "clearBadge": "true",
                    "vibration":"true",
                    "content-available": 1,
                    "delayWhileIdle" : "false",
                    //"timeToLive": "true",
                    "priority" : "true",
					"topics":["ios"]
            }
        });
		
	
push.on('registration', function(data) {
          //  console.log("registration event");
      //document.getElementById("regId").value = data.registrationId;	
	  localStorage.setItem('regId', data.registrationId);	
        //    console.log(JSON.stringify(data));			
        });
		
		push.on('error', function(e) {
           
            });
		 push.finish(function () {
                console.log('finish successfully called');
            });	`

**Comment by jcesarmobile** [comment]
@skyprimer it's probably not being installed as 1.9.0 requires CLI 6.4.0 and Phonegap build doesn't have it yet.
Your issue has nothing to do with this one.

**Comment by fechidal89** [comment]
I have the same problem with v2.0.x

I try:  `cordova plugin add https://github.com/phonegap/phonegap-plugin-push#v2.0.x --variable SENDER_ID="xyz"`

And result is:

```
support for subdirectories is deprecated and will be removed in Cordova@7
Fetching plugin "https://github.com/phonegap/phonegap-plugin-push" via git clone
Repository "https://github.com/phonegap/phonegap-plugin-push" checked out to git ref "v2.0.x".
Installing "phonegap-plugin-push" for android
ANDROID_HOME=/.../Android/sdk
JAVA_HOME=/Library...
Subproject Path: CordovaLib
Incremental java compilation is an incubating feature.
:clean
:CordovaLib:clean

BUILD SUCCESSFUL

Total time: 1.519 secs
Subproject Path: CordovaLib
**Installing "phonegap-plugin-push" for ios**
**Failed to install 'phonegap-plugin-push':Error: pod: Command failed with exit code 1**
    at ChildProcess.whenDone (/...../platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:469:12)
**Error: pod: Command failed with exit code 1**
```

In android run perfect, but ios I can't install the plugin.

#$ cordova -v
6.4.0

#$cordova platform version ios
Installed platforms:
  android 6.0.0
  ios 4.3.0
Available platforms: 
...

#$gem which cocoapods
/..../Ruby/gems/cocoapods-1.1.1/lib/cocoapods.rb

**Comment by jcesarmobile** [comment]
@fechidal89 did you create your project with sudo?

just as a test, from your terminal go to your project platforms/ios/ and run `pod install` there to see if it's throwing any error

**Comment by fechidal89** [comment]
@jcesarmobile No, I didn't create my project with sudo. I'm going to run the command `pod install` to test.

thanks

**Comment by spaceagestereo** [comment]
I'm having a similar build issue:
1>  No scripts found for hook "before_plugin_install".
1>  Install start for "phonegap-plugin-push" on ios.
1>  Beginning processing of action stack for ios project...
1>  Action stack processing complete.
1>  Failed to install 'phonegap-plugin-push':TypeError colors[style] is not a function
1>      at /Users/iOSDeveloper/.taco_home/node_modules/taco-remote-lib/2.2.1/node_modules/taco-remote-lib/node_modules/taco-utils/logFormatHelper.js:142:44
1>      at Array.forEach (native)
1>      at Function.LogFormatHelper.colorize (/Users/iOSDeveloper/.taco_home/node_modules/taco-remote-lib/2.2.1/node_modules/taco-remote-lib/node_modules/taco-utils/logFormatHelper.js:140:24)
1>      at Function.LogFormatHelper.toFormattedString (/Users/iOSDeveloper/.taco_home/node_modules/taco-remote-lib/2.2.1/node_modules/taco-remote-lib/node_modules/taco-utils/logFormatHelper.js:69:57)
1>      at EventEmitter.Logger.log (/Users/iOSDeveloper/.taco_home/node_modules/taco-remote-lib/2.2.1/node_modules/taco-remote-lib/node_modules/taco-utils/logger.js:22:47)
1>      at emitOne (events.js:77:13)
1>      at EventEmitter.emit (events.js:169:7)
1>      at EventEmitter.module.exports.emit (/Users/iOSDeveloper/.taco_home/node_modules/cordova/6.4.0/node_modules/cordova/node_modules/cordova-common/src/events.js:71:17)
1>      at EventEmitter.module.exports.emit (/Users/iOSDeveloper/.taco_home/remote-builds/taco-remote/builds/14044/cordovaApp/platforms/ios/cordova/node_modules/cordova-common/src/events.js:68:30)
1>      at /Users/iOSDeveloper/.taco_home/remote-builds/taco-remote/builds/14044/cordovaApp/platforms/ios/cordova/Api.js:255:20
1>  Failed to build app for buildNumber 14044: colors[style] is not a function
1>MSBUILD : cordova-build error : Error: Remote build error from the build server Build failed with error colors[style] is not a function - 1
1>  Error Remote build error from the build server Build failed with error colors[style] is not a function - {1}

**Comment by macdonst** [comment]
Anyone getting the error:

```
Installing "phonegap-plugin-push" for ios
Failed to install 'phonegap-plugin-push':Error: pod: Command failed with exit code 1
```

should go to the command line and run `pod repo update` then try to re-install the plugin.

**Comment by SergTomcat** [comment]
Version 1.9.2, same error as @macdonst has

_Failed to install 'phonegap-plugin-push':TypeError colors[style] is not a function_

`
 Failed to install 'phonegap-plugin-push':TypeError colors[style] is not a function
1>             at /Users/WebsoftMac/.taco_home/node_modules/taco-remote-lib/2.3.0/node_modules/taco-remote-lib/node_modules/taco-utils/logFormatHelper.js:142:44
1>             at Array.forEach (native)
1>             at Function.LogFormatHelper.colorize (/Users/WebsoftMac/.taco_home/node_modules/taco-remote-lib/2.3.0/node_modules/taco-remote-lib/node_modules/taco-utils/logFormatHelper.js:140:24)
1>             at Function.LogFormatHelper.toFormattedString (/Users/WebsoftMac/.taco_home/node_modules/taco-remote-lib/2.3.0/node_modules/taco-remote-lib/node_modules/taco-utils/logFormatHelper.js:69:57)
1>             at EventEmitter.Logger.log (/Users/WebsoftMac/.taco_home/node_modules/taco-remote-lib/2.3.0/node_modules/taco-remote-lib/node_modules/taco-utils/logger.js:22:47)
1>             at emitOne (events.js:90:13)
1>             at EventEmitter.emit (events.js:182:7)
1>             at EventEmitter.module.exports.emit (/Users/WebsoftMac/.taco_home/node_modules/cordova/6.4.0/node_modules/cordova-common/src/events.js:71:17)
1>             at EventEmitter.module.exports.emit (/Users/WebsoftMac/.taco_home/remote-builds/taco-remote/builds/1006/cordovaApp/platforms/ios/cordova/node_modules/cordova-common/src/events.js:68:30)
1>             at /Users/WebsoftMac/.taco_home/remote-builds/taco-remote/builds/1006/cordovaApp/platforms/ios/cordova/Api.js:255:20
1>         Не удалось создать приложение для номера сборки 1006: colors[style] is not a function
`

Any solutions yet?

**Comment by jeroennoten** [comment]
Same problem here... When running these commands:

```
cordova create test-cordova test.cordova Test
cd test-cordova
cordova platform add ios
cordova plugin add phonegap-plugin-push
```

The last command gives this output:

```
Fetching plugin "phonegap-plugin-push@1.9.2" via npm
Installing "phonegap-plugin-push" for ios
Failed to install 'phonegap-plugin-push':Error: pod: Command failed with exit code null
    at ChildProcess.whenDone (/Users/jeroennoten/Projects/test-cordova/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: pod: Command failed with exit code null
```

`pod repo update` did not work for me.

**Comment by davidmarquis** [comment]
This was happening to me so I went into `platforms/ios/` and ran `pod install`. This led me to an error that read

    ...
    Generating Pods project
    Abort trap: 6

A quick Google search led me on [StackOverflow](http://stackoverflow.com/questions/39980096/xcode8-cocoapods-abort-trap6), where I found out that installing Cocoapods from Homebrew was the culprit. 

I uninstalled the Homebrew package and the installed directly with `gem`:

    $ brew uninstall cocoapods
    $ sudo gem install cocoapods

This fixed the installation issue and the `phonegap-plugin-push` was properly setup in my project without an error.

**Comment by gnhub** [comment]
I thing it should permission issues, I have tried,


```
sudo chown -R <username> /Users/<username>/yourworkingurl
cordova platform add ios --save
cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable SENDER_ID="xxxxxxx"
```

(without sudo - no root permission)

Working for me. Hope can find some guide.
Thanks.
