### ISSUE TITLE
Failed to get plugin in 1.9.0

### ISSUE THREAD

**Issue by debugerr** [phonegap/phonegap-plugin-push#1343]
### Expected Behaviour
I can access window["PushNotification"] after device ready fired.

### Actual Behaviour
window["PushNotification"] is always undefined

#### Steps to Reproduce 
Install 1.9.0 as a plugin (I use PhoneGap build for that)
Install the app on the device
check the window["PushNotification"] after deviceready fired

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.1.1

#### Cordova CLI version and cordova platform version
cordova platform version ios 	4.2.0
phonegap: cli-6.3.0

#### Plugin version
1.9.0

**Comment by jcesarmobile** [comment]
1.9.0 requires CLI 6.4.0, so you'll have to use a previous version until they update the CLI.
