### ISSUE TITLE
phonegap-plugin-push 1.9.0 not working with cordova-plugin-crosswalk-webview

### ISSUE THREAD

**Issue by pedrogarciyalopez** [phonegap/phonegap-plugin-push#1344]
### Expected Behaviour
Get registration id.

### Actual Behaviour
push.on('registration') not firing.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Asus Zenfone

#### Cordova CLI version and cordova platform version
cordova --version                               6.4.0
cordova platform version android      6.0.0

#### Plugin version
cordova-plugin-crosswalk-webview 2.1.0 "Crosswalk WebView Engine"
cordova-plugin-whitelist 1.3.0 "Whitelist"
phonegap-plugin-push 1.9.0 "PushPlugin"

#### Sample Code that illustrates the problem
`document.addEventListener('deviceready', () => {

    var push = PushNotification.init({
        android: {
            senderID: "1234567890"
        }
    });

    push.on('registration', function(data) {
        alert(data.registrationId)
    });

})`

#### Logs taken while reproducing problem
adb logcat | grep PushPlugin  returns absolutely empty result.

However this works fine without cordova-plugin-crosswalk-webview. Or when i downgrade android platform to 5.2.2 and phonegap-plugin-push to 1.8.3.

**Comment by jcesarmobile** [comment]
The problem is crosswalk plugin, not the push plugin, 2.1.0 is not compatible with cordova-android 6.0.0.
It has been fixed, but not released yet, you can install the crosswalk plugin from github 
´cordova plugin add https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview,
