### ISSUE TITLE
Working with ionic 1 push notification step by step explained on ionic.io. I have installed the prerequisites like ionic core service, ionic push service, ionic loud and also have injected them in my main module. The register method is not working. Also I have set dev_push = true. The register function returns nothing while there is no error on console 

### ISSUE THREAD

**Issue by Attaullah7396** [phonegap/phonegap-plugin-push#1345]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@Attaullah7396 this really seems like a question for the Ionic forums.
