### ISSUE TITLE
"GoogleCloudMessaging.h" file not found ios

### ISSUE THREAD

**Issue by atulkrajput** [phonegap/phonegap-plugin-push#1352]
File Name: PushPlugin.m
#import "GoogleCloudMessaging.h" <'GoogleCloudMessaging.h' file not found>

Installed platforms:
  android 6.0.0
  ios 4.3.0

#### Plugin version
   phonegap-plugin-push 1.9.0 "PushPlugin"

**Comment by reyazucar** [comment]
i have updated to 1.9.0 and now i have the same error

**Comment by D4rthR4tz3** [comment]
You have to install cocoapod and then initialize your project with that configuration in your project root. Further details here: https://cocoapods.org/pods/Firebase (I just had to solve excactly that problem after configuring my iOS project)

**Comment by macdonst** [comment]
@atulkrajput @reyazucar do you have CocoaPods installed?

@D4rthR4tz3 you shouldn't need Firebase. The project will automatically grab the GCM pod when using 1.9.0. 2.0.0 will move to FCM.

**Comment by atulkrajput** [comment]
Thanks @macdonst for reply, Yes I have already installed cocoaPods, still getting following error.

> /Volumes/OTHER/cordova/cmd/platforms/ios/CheckMyDeals/Plugins/phonegap-plugin-push/PushPlugin.h:32:35: warning: 
>       cannot find protocol definition for 'GGLInstanceIDDelegate'
> @interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate, GCMReceiverDelegate>
>                                   ^
> /Volumes/OTHER/cordova/cmd/platforms/ios/CheckMyDeals/Plugins/phonegap-plugin-push/PushPlugin.h:30:11: note: 
>       protocol 'GGLInstanceIDDelegate' has no definition
> @protocol GGLInstanceIDDelegate;
>           ^
> /Volumes/OTHER/cordova/cmd/platforms/ios/CheckMyDeals/Plugins/phonegap-plugin-push/PushPlugin.h:32:58: warning: 
>       cannot find protocol definition for 'GCMReceiverDelegate'
> @interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate, GCMReceiverDelegate>
>                                                          ^
> /Volumes/OTHER/cordova/cmd/platforms/ios/CheckMyDeals/Plugins/phonegap-plugin-push/PushPlugin.h:31:11: note: 
>       protocol 'GCMReceiverDelegate' has no definition
> @protocol GCMReceiverDelegate;
>           ^
> /Volumes/OTHER/cordova/cmd/platforms/ios/CheckMyDeals/Plugins/phonegap-plugin-push/PushPlugin.m:30:9: fatal error: 
>       **'GoogleCloudMessaging.h' file not found**
> #import "GoogleCloudMessaging.h"
>         ^
> 2 warnings and 1 error generated.
> 
> ** BUILD FAILED **

**Comment by macdonst** [comment]
@atulkrajput what version of Xcode are you running?

**Comment by atulkrajput** [comment]
@macdonst  my MAC Xcode version 8.0 updating to 8.1.

**Comment by atulkrajput** [comment]
I found the solution file named "GoogleService-Info.plist", wasn't correct, I created a new file with all the details like app ID, team ID and replaced it with the old file. Now the error is gone.
 
Thanks @macdonst  for your support.

**Comment by atulkrajput** [comment]
Now it's building success but after removing PushPlugin.m from target, By adding back issue still persist.

**Comment by macdonst** [comment]
@atulkrajput my suggestion is to completely remove the platforms/ios directory and then add everything back in.

**Comment by tore90turris** [comment]
Hi, i am ionic development and unfortunately, i have the same problem.

I have installed **CocoaPods** _(1.1.1)_ from terminal on my mac _(Sierra OS)_
Prepare solution iOS with **VS2015** and build app in **XCode** _(8.0)_..
In XCode, i have this error:  [_"GoogleCloudMessaging.h" file not found_]

I forced rebuild solution in **VS2015**, removed and added iOS platform.. but.. the problem has remained..
Do you have any idea to help me?
Thx

**Comment by ILABUTK** [comment]
I had the same problem. After many hours of googling & trying, I find out that the sequence how you created the project may matter. You need to "add platform" before "add plugin".

This is my sample sequence:

>cordova create demo com.xyz.demo Demo
>cd Demo
>cordova platform add ios --save
>cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable SENDER_ID="123456789"

Then, open the Demo.xcworkspace file in xcode.
 The error is gone! 

Also, I did have to do a "pod setup" for cocoapod.

**Comment by tore90turris** [comment]
I resolved removed this files generated from **VS2015**:
File: Podfile.lock, MyApp.xcworkspace
Folder: Pods

and then in terminal run: **pod install**

Now the solution MyApp.xcworkspace build correctly, but not publish on device when i press Run button. 

I am very sad in this moment :(

**Comment by ILABUTK** [comment]
You have to post some codes such that we can help. There could be many reasons ...

**Comment by tore90turris** [comment]
Yes, i'm sorry @ILABUTK  :) 
This is my **Podfile**
![image](https://cloud.githubusercontent.com/assets/23500694/20423250/953fee3c-ad6f-11e6-8bdf-2c97b1f5b305.png)

And there are my **plugins and Build phases..** 
![image](https://cloud.githubusercontent.com/assets/23500694/20423416/6100f6d8-ad70-11e6-8a9d-d58607db013e.png)

Now, Reading the **PushPlugin** i noticed that there is a **WARNING**
`Cannot find the protocol: **GGLInstanceIDDelegate, GCMReceiverDelegate**`
![image](https://cloud.githubusercontent.com/assets/23500694/20423568/5e73d1c8-ad71-11e6-8022-ab6e7006e018.png)


This could be the problem?

Thx @ILABUTK and others members :)

**Comment by figdev1** [comment]
Update Podfile to...
target '[ProjectName]' do
pod 'GoogleCloudMessaging', '~> 1.2'
pod 'GGLInstanceID', '~> 1.2.1'
end

Then..
run command:
pod install
pod update

Then..
Encounter error GoogleCloudMessaging.h not found.

Then... 
Open project in XCode and add a custom search variable to instruct XCode to search the Root of Pod directory for the GoogleCloudMessaging.h found in the cocoapod.

Find the variable by Searching for it:
"User Header Search Path" by typing in the search box top right of Build Settings tab in XCode
Double click and a popup will display
Click the "+" bottom left
Enter:
"${PODS_ROOT}/" and choose "Recursive" 

Builds but i get a new error:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GCMPubSub", referenced from:
      objc-class-ref in PushPlugin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by cagb80** [comment]
Hi everyone... After 3 days searching a solution I found one :)
Follow the instructions:

1. uninstall all beta version of cocoa pods
2. install cocoa pods 1.1.1
3. install the plugin phonegap-plugin-push even with the error
4. install iOS platform
5. cd platforms/ios
6. try pod install
6.1 f you get an error about Nanaimo, uninstall Nanaimo with: sudo gem uninstall nanaimo
6.2 reinstall Nanaimo: sudo gem install nanaimo -v 0.1.2
7. Cordova build ios

All this steps save my project :)

**Comment by akz92** [comment]
Thanks @cagb80, your comment helped me find my solution. The only thing I did different was that I installed the latest version of the Nanaimo gem, and it worked after that.

**Comment by cagb80** [comment]
Good For you.. :) Don't install the last version of Cordova...!!!! Don't DO IT!!! I commend you!

**Comment by fredgalvao** [comment]
@cagb80 can you share the reason for that comment against upgrading cordova?

**Comment by cagb80** [comment]
Hi @fredgalvao The same problem happen again. I reinstalled Cordova and all the pods to get work. Is so tired. But if you have a better solution, lets me know :)

**Comment by cinder92** [comment]
same error here! +1

**Comment by prosenjit-itobuz** [comment]
I follow this steps

- uninstall all beta version of cocoa pods
- install cocoa pods 1.1.1
- install the plugin phonegap-plugin-push even with the error
- install iOS platform
- cd platforms/ios
- pod install

I am getting this error 

[!] Unable to find a specification for `GoogleCloudMessaging (~> 1.2.0)`

I update the cocoapods repo located at ~/.cocoapods/repos/master


Still unable to find how to solve. :(

**Comment by ElizandroSchramm** [comment]
same error here! +1

**Comment by prosenjit-itobuz** [comment]
My problem was fixed. Cocapod was not properly installed. Uninstall cocapods. Remove ~/.cocapods then reinstall. Try pod list. If packages available then go to ios dir and run pod install.

**Comment by chiragpurohit71085** [comment]
Hi 

I think this is similar to following...

https://github.com/phonegap/phonegap-plugin-push/issues/1573

For me following worked..

platform :ios, '8.0'
use_frameworks!
target 'Specialguest' do
    pod 'GoogleCloudMessaging'
    pod 'GGLInstanceID'
end

**Comment by macdonst** [comment]
Closing as most cocoapod issues have been fixed with 4.4.0

**Comment by AgNm** [comment]
@ILABUTK best solution... thanks a lot :)

**Comment by Ziv-Barber** [comment]
If anyone still have a problem then you need to do the following IN THIS ORDER:

sudo gem install cocoapods
pod setup
install the ios platform
install the push plugin

else it'll not work for you.
