### ISSUE TITLE
Manytimes push.on('error') is called on iPad running on iOS 10 but some times push.on('registration') is called successfully

### ISSUE THREAD

**Issue by rohitbhoite** [phonegap/phonegap-plugin-push#1353]
### Expected Behaviour
push.on('registration') should be called successfully
### Actual Behaviour
push.on('error') is called many times giving "**com.google.iid error 5**"error 
#### Steps to Reproduce 
1. Call PushNotification.init() method inside $ionicPlatform.ready() function
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Sample Code that illustrates the problem

    $ionicPlatform.ready(function() {

    var push = PushNotification.init({ "android": {"senderID": "SENDERID"},
    "ios": {senderID: "SENDERID",gcmSandbox: true,alert: "true",badge: "true",sound: "true"}, "windows": {} } );

    push.on('registration', function(data) {
      
    });
      
    push.on('notification', function(data) {
        
    });

    push.on('error', function(e) {
        alert(e.message)
    });
     }

As I mentioned,sometimes I am getting device token successfully but many times I am getting above error.

**Comment by macdonst** [comment]
@rohitbhoite based on the Google docs error 5 is `Operation In Progress Another similar operation is in progress. This one was canceled.` which leads me to ask are you calling `init` more than once?

**Comment by rohitbhoite** [comment]
No I am calling it only once inside run section of ionic app

**Comment by rohitbhoite** [comment]
2016-11-11 00:28:11.150: GGLInstanceID | Invalid last checkin timestamp in future.
     2016-11-11 00:28:11.183: GGLInstanceID | Unable to find token in cache Error            Domain=com.google.iid Code=-25300 "(null)"

I am also getting above logs in the Xcode console

**Comment by macdonst** [comment]
@rohitbhoite is your phone's date/time set into the future?

**Comment by rohitbhoite** [comment]
No it is set to current time.11th Nov.Time is also equal to local time.
