### ISSUE TITLE
PushNotification is not defined for Android

### ISSUE THREAD

**Issue by clarklight** [phonegap/phonegap-plugin-push#1355]
For the life of me, i can't figure out why the PushNotification is not defined isn't a function error getting called.

I just expect it to run and register the GCM. Basically that error is called, then the whole app is stopped.

```
Uncaught ReferenceError: PushNotification is not defined
    at Channel.<anonymous> (file:///android_asset/www/index.html:1321:15)
    at Channel.fire (file:///android_asset/www/cordova.js:822:23)
    at file:///android_asset/www/cordova.js:231:49
```

 ```
document.addEventListener("deviceready", function(){
console.log("test device ready");
   var push = PushNotification.init({
    android: {
        senderID: "12345"
    },
      browser: {},
    ios: {
        alert: "true",
        badge: "true",
        sound: "true"
    },
    windows: {}
});

push.on('registration', function(data) {
    // data.registrationId
    console.log("New push registration process="+data.registrationId);
});

push.on('notification', function(data) {
    // data.message,
    // data.title,
    // data.count,
    // data.sound,
    // data.image,
    // data.additionalData
});

push.on('error', function(e) {
    // e.message
});
```
Running on Android 5.0 Phonegap CLI 6.3.0

Included this in the config

```
  <plugin name="phonegap-plugin-push" source="npm">
        <param name="SENDER_ID" value="12345" />
    </plugin>

```

**Comment by jcesarmobile** [comment]
Can you try specifying the 1.8.4 version of the plugin? Might be trying to get latest (1.9.0) that isn't compatible with CLI 6.3.0, and skipping it.

**Comment by clarklight** [comment]
When i specify it to 1.8.4 the phone gap build won't build, giving me this `Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: BadgeImpl.java - You can fix this here`

So i pretty much have to use 1.9.0, and when i use the 1.9.0 version it gives me the  PushNotification is not defined(…)   so i am pretty stuck.

**Comment by jcesarmobile** [comment]
How did you specify it?
You can't use 1.9.0 because it requires CLI 6.4.0

**Comment by clarklight** [comment]
in the config.xml i did   ```
 <plugin name="phonegap-plugin-push" version="1.9.0" source="npm">
        <param name="SENDER_ID" value="12345" />
    </plugin>
```

Also did it without the version so it should pull whatever is latest  ```
  <plugin name="phonegap-plugin-push"  source="npm">
        <param name="SENDER_ID" value="758464369243" />
    </plugin>
```

**Comment by jcesarmobile** [comment]
I just added the 1.8.4 version of the plugin to a sample app and build correctly
https://github.com/jcesarmobile/phonegap-template-hello-world

**Comment by clarklight** [comment]
Assuming you are not using Phonegap build? I built it with Phonegap build with the config.xml defining
 ```
<plugin name="phonegap-plugin-push" version="1.8.4" source="npm">
        <param name="SENDER_ID" value="12345" />
    </plugin>
```

But the build failed `"Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: BadgeImpl.java - You can fix this here"`

Would there be any way that i can help debug it?

**Comment by clarklight** [comment]
Ahhhhh..... i dug deeper, there is another plugin that caused a conflict with the badgeImpl.java. i removed that plugin and now the 1.8.4 is working. I will try to figure out more about that conflict and come back to you. Thanks!!
