### ISSUE TITLE
Plugin doesn't support this project's cordova version. cordova: 6.3.2, failed version requirement: >=6.4.0

### ISSUE THREAD

**Issue by SiddiquiImran** [phonegap/phonegap-plugin-push#1356]
### Expected Behaviour
Plugin should be installed using Phonegap build
<plugin name="phonegap-plugin-push"  source="npm" >
        <param name="SENDER_ID" value="xxxxxxx" />
    </plugin>

and work properly in installed app

### Actual Behaviour
**Giving this error:**
Plugin doesn't support this project's cordova version. cordova: 6.3.2, failed version requirement: >=6.4.0

**Working with** 
<plugin name="phonegap-plugin-push" spec="1.8.4"  source="npm" >
        <param name="SENDER_ID" value="xxxxxxx" />
    </plugin>

### Reproduce Scenario (including but not limited to)

use latest version of phonegap-plugin-push in phonegap build without spec

#### Steps to Reproduce 

use latest version of phonegap-plugin-push in phonegap build without spec

#### Cordova CLI version and cordova platform version

  Cordova CLI version:  cli-6.3.0                                # e.g. 6.0.0
    cordova android platform version: 5.2.1                 # e.g. 4.1.1

#### Logs taken while reproducing problem
Build Date: 2016-11-10 12:34:39 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-device" via npm
Installing "cordova-plugin-device" at "1.1.3" for android
Fetching plugin "cordova-plugin-camera" via npm
Installing "cordova-plugin-camera" at "2.3.0" for android
Fetching plugin "cordova-plugin-compat" via npm
Installing "cordova-plugin-compat" at "1.1.0" for android
Fetching plugin "cordova-plugin-geolocation" via npm
Installing "cordova-plugin-geolocation" at "2.4.0" for android
Dependent plugin "cordova-plugin-compat" already installed on android.
Fetching plugin "cordova-plugin-inappbrowser" via npm
Installing "cordova-plugin-inappbrowser" at "1.5.0" for android
Fetching plugin "cordova-plugin-globalization" via npm
Installing "cordova-plugin-globalization" at "1.0.4" for android
Fetching plugin "cordova-plugin-network-information" via npm
Installing "cordova-plugin-network-information" at "1.3.0" for android
Fetching plugin "cordova-plugin-splashscreen" via npm
Installing "cordova-plugin-splashscreen" at "4.0.0" for android
Fetching plugin "cordova-plugin-media" via npm
Installing "cordova-plugin-media" at "2.4.0" for android
Fetching plugin "cordova-plugin-file" via npm
Installing "cordova-plugin-file" at "4.3.0" for android
Dependent plugin "cordova-plugin-compat" already installed on android.

The Android Persistent storage location now defaults to "Internal". Please check this plugins README to see if you application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />"

to config.xml in order for the application to find previously stored files.

    
Dependent plugin "cordova-plugin-compat" already installed on android.
Fetching plugin "cordova-plugin-dialogs" via npm
Installing "cordova-plugin-dialogs" at "1.3.0" for android
Fetching plugin "phonegap-plugin-push" via npm
Installing "phonegap-plugin-push" at "1.9.0" for android
Plugin doesn't support this project's cordova version. cordova: 6.3.2, failed version requirement: >=6.4.0
Skipping 'phonegap-plugin-push' for android
Fetching plugin "cordova-plugin-screen-orientation" via npm
Installing "cordova-plugin-screen-orientation" at "1.4.2" for android
Fetching plugin "phonegap-plugin-barcodescanner" via npm
Installing "phonegap-plugin-barcodescanner" at "6.0.3" for android
Dependent plugin "cordova-plugin-compat" already installed on android.
Fetching plugin "cordova-sqlite-evcore-extbuild-free" via npm
Installing "cordova-sqlite-evcore-extbuild-free" at "0.8.2" for android
Fetching plugin "cordova-plugin-x-toast" via npm
Installing "cordova-plugin-x-toast" at "2.5.2" for android
Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist" at "1.3.0" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:compileDebugAidl
:CordovaLib:generateDebugBuildConfig
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:compileReleaseAidl
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareBarcodescannerLibrary
:prepareComAndroidSupportSupportCompat2500Library
:prepareComAndroidSupportSupportCoreUi2500Library
:prepareComAndroidSupportSupportCoreUtils2500Library
:prepareComAndroidSupportSupportFragment2500Library
:prepareComAndroidSupportSupportMediaCompat2500Library
:prepareComAndroidSupportSupportV42500Library
:prepareProjectCordovaLibUnspecifiedDebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:mergeDebugShaders
:compileDebugShaders
:generateDebugAssets
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:incrementalDebugJavaCompilationSafeguard
:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /project/src/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:compileDebugNdk UP-TO-DATE
:compileDebugSources
:prePackageMarkerForDebug
:transformClassesWithDexForDebug
Merged dex #1 (86 defs/108.5KiB)
Merged dex #2 (437 defs/468.4KiB)
Merged dex #3 (130 defs/243.6KiB)
Merged dex #4 (53 defs/76.5KiB)
Merged dex #5 (56 defs/147.3KiB)
Merged dex #6 (141 defs/172.2KiB)
Merged dex #7 (1 defs/0.7KiB)
Merged dex #8 (164 defs/223.0KiB)
Merged dex #9 (368 defs/644.0KiB)
Merged dex #10 (73 defs/58.2KiB)
Merged dex #11 (8 defs/8.3KiB)
Merged dex #12 (17 defs/28.5KiB)
Merged dex #13 (250 defs/187.2KiB)
Merged dex #14 (10 defs/15.2KiB)
Merged dex #15 (47 defs/8.6KiB)
Result is 1841 defs/2892.1KiB. Took 0.1s
:mergeDebugJniLibFolders
:transformNative_libsWithMergeJniLibsForDebug
:processDebugJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForDebug
:validateDebugSigning
:packageDebug
:zipalignDebug
:assembleDebug
:cdvBuildDebug

BUILD SUCCESSFUL

Total time: 8.068 secs
Built the following apk(s): 
	/project/build/outputs/apk/project-debug.apk

**Comment by jcesarmobile** [comment]
You need the 6.4.0 CLI to use the latest version, it's a requisite. And also cordova-ios 4.3.0 or greater and cordova-android 6.0.0 or greater (I recommend using 6.1.0)

**Comment by macdonst** [comment]
@SiddiquiImran you are not specifying a version in your plugin tag so it is using 1.9.0 which requires cordova-cli 6.4.0 as @jcesarmobile mentioned. PGB does not currently have 6.4.0 so you should change your plugin tag to:

```
<plugin name="phonegap-plugin-push" source="npm" spec="~1.8.4">
    <param name="SENDER_ID" value="<Your Sender ID>" />
</plugin>
```

**Comment by SiddiquiImran** [comment]
@jcesarmobile , @macdonst 
Thanks for the information i will change the configuration accordingly.
