### ISSUE TITLE
Use push notifications for data and not for notification

### ISSUE THREAD

**Issue by yosiat** [phonegap/phonegap-plugin-push#1357]
Hi,

I want to use push notifications, and on some notifications I want to display notification and other I don't want to display notification (and add the data to list in the ui, update some cache, etc).

Is it possible/supported?

Thanks!

**Comment by macdonst** [comment]
@yosiat yes, yes it is. Please read the section on background notifications https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications

**Comment by yosiat** [comment]
@macdonst Just to make sure - all I need to do is to set "content-available" to 1?
and then if my app is on the background/foreground, there will be no ui notification, but I will get the data?

and If I want to selectively on my ui code to show notifications/not? I will need to send all message with "content-available" of 1 and using some phonegap/ionic plugin to show notification?

**Comment by yosiat** [comment]
Trying to install 1.9.0, so if fixes the problem - #1367 

I found that the phone vibrates but the 'notification' event isn't dispatched.

**Comment by macdonst** [comment]
@yosiat you are not giving me enough info. Please follow the issue template guidelines.

**Comment by yosiat** [comment]
@macdonst I don't have my computer next to me, but the problem is:
I am sending message with content-available set to "1".

**android:**

- forgeround: the "notification" handler is called
- background: the "notification" handler is called

**ios:**

- forgeround: the "notification" handler is called
- background: the "notification" handler is **not** called and the phone vibrates

The problem is in ios - background, notification handler is **not**, there is no notification disappearing ( which is ok), but the phone vibrates (like it get a notification).

I will give more information if there is need to - just request it!

Thanks!

**Comment by macdonst** [comment]
@yosiat Again, you are not giving me enough info. What you have posted above is incomplete. Please follow the issue template guidelines and probably create a new issue at this point.
