### ISSUE TITLE
on('registration') not fired on android 

### ISSUE THREAD

**Issue by ntkzwane** [phonegap/phonegap-plugin-push#1359]
The on('registration') event is not firing on for android (working fine on iOS 4.3.0) while testing on a Sony (running android@6.0.1) and a Samsung (running android@5.0.1). This seems to be similar to #800, however I haven't been able to resolve it from following that thread.

I am using `cordova@6.4.0` and building for `android@6.0.0`
I've installed `phonegap-plugin-push@1.9.0` alongside the `cordova-plugin-google-analytics`.
I've also removed the `cordova-google-play-services` plugin since it constantly gave me the error around multiple declarations of the `com.google.android.gms` package.

I've installed the required items through the Android SDK (see screenshot below):
![selection_270](https://cloud.githubusercontent.com/assets/9074285/20171036/9ae4492a-a737-11e6-8899-4d1dd93a21ff.png)

and I'm using my `config.xml` file to install the plugin, and specified the SENDER_ID as part of that like so:
```
<plugin name="phonegap-plugin-push" spec="1.9.0">
    <param name="SENDER_ID" value="XXXXXXX" />
</plugin>
```

Steps to reproduce (starting from a clean project with no platform added):
1. `add the plugins to `config.xml`
2. `cordova platform add android`
2. `cordova run android`

This is what the code looks like where I make use of the plugin:
```
push = PushNotification.init({
        "android": { "senderID": "XXXXXXXXX", "icon": "notification_icon", "iconColor": "#0197e2" },
                "ios": { "alert": "true", "badge": "true", "sound": "true" }, "windows": {}
});

push.on('registration', function (data) {
        console.log(data.registrationId);
});

push.on('notification', function (message) {
        console.log(message);
});

push.on('error', function (e) {
        console.log(e);
});
```

For reference, this is the complete list of plugins I am using:
```
cordova-plugin-camera 2.3.0 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-crosswalk-webview 2.1.0 "Crosswalk WebView Engine"
cordova-plugin-file 4.3.0 "File"
cordova-plugin-file-transfer 1.6.0 "File Transfer"
cordova-plugin-google-analytics 1.6.0 "Google Universal Analytics Plugin"
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-whitelist 1.3.0 "Whitelist"
cordova-plugin-x-toast 2.5.2 "Toast"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.9.0 "PushPlugin"
```

Note: I've tried all sorts of different permutations of the three plugins (`phonegap-plugin-push`, `cordova-plugin-google-analytics` and `cordova-google-play-services`) and concluded that `cordova-google-play-services` was a common denominator for me with either the **MultiDex** or **More than one library with name** issue, thus resulted in removing it completely.

**Comment by macdonst** [comment]
@ntkzwane can you run `adb logcat | grep PushPlugin` and then start up the app? That should help debug. Also, do you see anything in the Chrome developer console?

**Comment by ntkzwane** [comment]
@macdonst nothing comes up in the `adb logcat` logs when filtering for `PushPlugin` related logging.
I've verified that the `PushNotification` object is not undefined when the `PushNotification.init({})` function is called.
There is nothing unusual being logged in the JS console either.

**Comment by macdonst** [comment]
@ntkzwane the `init` method outputs some info to logs so if you are seeing nothing it makes me think `init` on the Java side is never being called. Try opening the project in Android Studio and setting a breakpoint.

**Comment by ntkzwane** [comment]
@macdonst so I've debugged the code and it looks you are spot on, the `init` method for the plugin is not being called on the Java side. Do you have ideas as to what could be causing this? Is there possibly a step I am missing in my cordova config?

**Comment by fredgalvao** [comment]
Native `init` not being called could be caused by, amongs some other ghost stuff, the following:

- You simply didn't call `PushNotification.init({...})` on your app's code.
- You called `init` from js, but you somehow don't have the native code available. This can be caused by:
  - Bad compilation
  - Bad plugin installation
  - Cordova bug
- You called `init` and the native code exists, but there's a bug with it.

I'm willing to bet it's a bad installation.

**Comment by ntkzwane** [comment]
Do you perhaps have pointers on how to diagnose a bad installation @fredgalvao? As mentioned in my opening issue, I'm using `cordova build android` ensuring that the build is not using previously installed plugins i.e removing added platforms and clearing out the `plugins/` directory.

**Comment by macdonst** [comment]
@ntkzwane at this point I'd probably do:

```
cordova plugin rm cordova-plugin-google-analytics
cordova plugin rm cordova-google-play-services
cordova platform rm android
cordova platform add android
cordova clean android
cordova build android
```

Then check the `platforms/android/src/com/adobe/phonegap/push` directory to make sure that all of the source files were correctly delivered. Then test without the analytics plugin.

**Comment by ntkzwane** [comment]
@macdonst I have verified that the issue is the `cordova-plugin-crosswalk-webview` plugin, and looking at this thread #1344 confirms this. I have tested this with the repository version of the crosswalk plugin and it all works fine. Thanks a ton for the help :+1:
