### ISSUE TITLE
Meizu does not receive push notifications

### ISSUE THREAD

**Issue by Dmatafonov** [phonegap/phonegap-plugin-push#1360]
### Expected Behaviour
Should receive push notifications. Token is set, google responces without errors, application is on the background. All other users receive push.

### Actual Behaviour
No push notifications.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
5.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Meizu m3

#### Cordova CLI version and cordova platform version

Not sure, compiled at build.phonegap.com

#### Plugin version

Not sure, compiled at build.phonegap.com

Everyone receive notifications, but just one particular phone doesnt.
Everything is checked twice - token is valid and fresh, google respones with message_id and no errors,
application is on the background. But still no push received.

**What should I try next? Where to dig? Pls advise**

**Comment by macdonst** [comment]
@Dmatafonov some phones by Chinese manufacturers are very aggressive at closing apps when not in use which can cause some problems. Read:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#huawei-and-xiaomi-phones

If that doesn't help then get some logs `adb logcat | grep PushPlugin`

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
