### ISSUE TITLE
No instance of push gets created

### ISSUE THREAD

**Issue by bmwertman** [phonegap/phonegap-plugin-push#1363]
### Expected Behaviour
To have an instance of `Push` set on `$rootScope` that would be available in my `pushSubscribe` factory with access to the `Push.subscribe` and `Push.unsubscribe` methods

### Actual Behaviour
No `Push` instance gets set on `$rootScope` after the app loads from `ionic run Android` or from building the app in Xcode after `ionic build ios`.

None of the `console.log()`s in `$ionicPlatform.ready(function(){}` print anything to console.

Not getting any errors in console

#### Steps to Reproduce 

1) Add `debugger` in `pushSubscribe` factory 
2) Add new chat room which triggers `$$added` on user's chat rooms `$firebaseArray`
```
   Pta.factory('pushSubscribe', [
      '$firebaseArray',
      '$rootScope',
      function ($firebaseArray, $rootScope) {
          return $firebaseArray.$extend({
          $$added: function(room){
          // Room topic is the $id of the chat room
          debugger;
          $rootScope.Push.subscribe(room.key);
      },
          $$removed: function(room){
          $rootScope.Push.unsubscribe(room.key);
       }
     });
   }]);
```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

    Android: 6.1.0 also tried with 6.0.0
    ios: 4.3.0

#### Cordova CLI version and cordova platform version

    cordova --version: 6.4.0
    cordova platform version: 6.4.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push: 1.9.0 Also tried with installing from git url

#### Sample Push Data Payload
```
$scope.sendMessage = function() {
        // Get the users auth jwt to verify them on the node server
        firebase.auth().currentUser.getToken(true)
        .then(function(userToken){
            $http({
                method: 'POST',
                url:'MY_HEROKU_HOSTED_NODE_SERVER_URL',// using node-apn and node-gcm
                data:{
                    reg_id: $scope.pushRegId,
                    token: userToken,
                    message: $scope.IM.textMessage,
                    sender_name: $scope.user.name,
                    topic: '/topics/' + $state.params.roomId,
                    state: 'app.room',
                    roomId: $state.params.roomId,
                    sender_imgURL: $scope.user.pic,
                    chatters: chatters,
                    platform:  $scope.platform
                }
            })
            .then(function(res){
                Chats.send($scope.user, $scope.IM.textMessage);
                $scope.IM.textMessage = "";
            })
            .catch(function(err){
                debugger;
            });
        });
    };
```

#### Sample Code that illustrates the problem
```
$ionicPlatform.ready(function(){
    $rootScope.Push = PushNotification.init({
            android: {
                senderID: "MY_SENDER_ID"
            },
            ios: {
                alert: "true",
                badge: "true",
                sound: "true"
            }
        });

        $rootScope.Push.on('registration', function(data) {
            console.log("registration event: " + registrationId);
            var oldRegId = localStorage.get('registrationId');
            if (oldRegId !== registrationId) {
              // Save new registration ID
              $localstorage.set('registrationId', registrationId);
              // Post registrationId to your app server as the value has changed
            }
        });

        $rootScope.Push.on('notification', function(data){
              // Make sure the user isn't getting notified about their own message
              if(!data.wasTapped && data.sender_imgUrl !== userService.getUser().pic){
                   //Notification was received in foreground. Check if the user is already in the room
                  if(!$state.is(data.state, { roomId: data.roomId })){
                     var queue = document.getElementById('queue');
                     if(!queue){ // This is the first queued chatter
                        //My code for displaying queued chatters in foreground 
                     }
                     if($rootScope.queuedChatters.length > 0){
                        for (var i = $rootScope.queuedChatters.length - 1; i >= 0; i--) {
                            value = $rootScope.queuedChatters[i];
                            // If it isn't the same person in the same room sending another message, add them
                            if(value.roomId !== data.roomId && value.sender_imgUrl !== data.sender_imgUrl && i === 0){
                            $rootScope.queuedChatters.push(data);
                        }
                     }
                   } else {
                      $rootScope.queuedChatters.push(data);
                   }
                  $rootScope.$apply();
                } 
             } else {
                 //Notification was received on device tray and tapped by the user.
                $localstorage.setObject('pushNotification', data);
             }
         });

        $rootScope.Push.on('error', function(e) {
           console.log("Push error event: ", e);
        });
   });
```

**Comment by fredgalvao** [comment]
Personal advice: don't polute the $rootScope with things like that. The Push class/object has close to nothing to do with view state management, and thus it shouldn't end up in any scope per se. That's usually the role of  a singleton service on angular.

Could you switch

```js
$ionicPlatform.ready(function(){
```

with

```js
$ionicPlatform.ready(function(){
    console.log("I'm a device and I'm ready!", PushNotification, $rootScope);
```

and see what prints?

**Comment by bmwertman** [comment]
That prints and `$rootScope` and `pushNotification` contain the same as when I check them in my `pushSubscribe` factory. But I still don't understand how I can access the topic `subscribe` and `unsubscribe` methods.

![screen shot 2016-11-11 at 1 12 13 pm](https://cloud.githubusercontent.com/assets/2573903/20225286/8bc12682-a810-11e6-8812-61e67a4e1d6d.png)

**Comment by fredgalvao** [comment]
And I'm expecting `$rootScope.Push  && $rootScope.Push instanceof PushNotification` to be `true` and the end of the deviceReady event. Can you confirm that?

If the answer to the above is true, then the issue is with angular or with where you put that factory code of yours. Moving all push related code to a service as I suggested would probably solve it if that's indeed the case.

**Comment by bmwertman** [comment]
I put `console.log('$rootScope.Push: ', $rootScope.Push);` 
and `console.log('PushNotification: ', PushNotification);` at the end of my `$ionicPlatform.ready` closure but nothing gets printed.

**Comment by fredgalvao** [comment]
Nothing as in `""` or as in `"$rootScope.Push: "\n"PushNotification: "`?

**Comment by bmwertman** [comment]
Well it was nothing as in "". But I moved the registration to the top of `$ionicPlatform.ready(function() {` and It seems something in my code was failing silently and preventing the registration from happening. Now the registration goes through and I have;
![screen shot 2016-11-11 at 4 23 18 pm](https://cloud.githubusercontent.com/assets/2573903/20230701/3c42e2ba-a82b-11e6-9b4c-c11de4caa66d.png)
 But it seems still no `subscribe` or `unsubscribe` methods

**Comment by bmwertman** [comment]
Thanks for the help @fredgalvao. I'm going to close this as it seems even though the `success` method doesn't show on the object returned from my `$rootScope.Push` it is in fact there. As long as I pass a success and error callback after my topic string everything works.
