### ISSUE TITLE
Notification bar has no title

### ISSUE THREAD

**Issue by NateShoy** [phonegap/phonegap-plugin-push#1365]
When the notification is received, the notification bar shows app's icon but *no title*, when I slide down, then the app icon & title & message show. Tested other phones having earlier Android versions with the same app setup using the same notification process and the title shows.

phonegap-plugin-push 1.8.0
android-minSdkVersion 14
PhoneGap Cloud Build (iOS / Android / Windows) cli-6.3.0 (4.2.0 / 5.2.1 / 4.4.1)
Windows PhoneGap Desktop (PhoneGap.exe) 0.1.9
Android PhoneGap Developer 1.7.6
Android 6.0.1 – Marshmallow
Phone Motorola DROID MAXX 2

![no title in notify](https://cloud.githubusercontent.com/assets/23431877/20244992/a42a571c-a963-11e6-8f78-94cc58b4efd5.png)

**Comment by macdonst** [comment]
@NateShoy I confess that I don't actually understand what the problem is. Can you take a screen shot of what you expect to see from another phone and then compare it to the one that has a problem?

**Comment by NateShoy** [comment]
Sure, here are both images: working and not working. TY

![title in notify](https://cloud.githubusercontent.com/assets/23431877/20251907/6b7cd8e4-a9eb-11e6-8e25-6137aefedc88.png)

![no title in notify](https://cloud.githubusercontent.com/assets/23431877/20251908/71e727b6-a9eb-11e6-8748-2590e1956330.png)

**Comment by macdonst** [comment]
@NateShoy okay, I see what you are talking about now. As of Android L the title text is no longer shown. See https://developer.android.com/reference/android/app/Notification.html#tickerText
