### ISSUE TITLE
Storing data.message in the localStorage when the app is in the background?

### ISSUE THREAD

**Issue by rooz121359** [phonegap/phonegap-plugin-push#1366]
Hi,

I'm trying to store the message that's received in the push notification in the localstorage when the app is in the background but I can't seem to figure out how...

I get the massages coming through nicely when the app is in the background but the localstorage is always null.

I'm actually tying to set the local storage in the `push.on('notification')` function like this:

```
push.on('notification', function(data) {


console.log(data.message);

window.localStorage.setItem('test', data.message);

});
```
Is this even possible?

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by rooz121359** [comment]
Thanks for the reply. I just feel like it doesn't matter even if I re-open it, there is no way to do what I'm trying to do otherwise the answer would've been given in this question.

**Comment by macdonst** [comment]
@rooz121359 well, I'm not sure what you are trying to do as you haven't given me enough information. I don't know what platform you are on, what version of the OS you have, what version of the plugin, what your payload looks like, etc. etc. This is why there is an issue guidelines.
