### ISSUE TITLE
Open alert message in android when the push notification is clicked in Android?

### ISSUE THREAD

**Issue by rooz121359** [phonegap/phonegap-plugin-push#1368]
### Expected Behaviour

To explain this, you can look at this plugin's behaviour on iOS. When a message's received  while the app is in the background and when you click on the message, it will open your app and then the same message will show up in the alert(); 

This is the exact thing I need for Android too.

### Actual Behaviour

But on Android, this is not the case. the only time that the alert(); will show up is when you already have the app open.

### Reproduce Scenario (including but not limited to)

run the app in the background on your android and then send a push notification... then click on the received message and this should open your app... but you will never get an alert(); as it will in iOS.

#### Steps to Reproduce 

Send a push notification while your app is on the background (NOT OPEN) and then send a push notification to your app/device... This will produce a push notification in your device's tray (at the top) and then press/click on that message and this should open your app.... 

on iOS, when the app is opened, the alert(data.message); will show the same message again in teh alert once the app is opened.

But on Android this wont happen which is needed in my case.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 4.2.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

EASTCOM

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.3.0
    cordova platform version android                    4.2.2

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.4.2

#### Sample Push Data Payload
```

<?php
$ch = curl_init("https://fcm.googleapis.com/fcm/send");
$header=array('Content-Type: application/json',
"Authorization: key=AIzaSyAHJKHJKH");
curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );

curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{ \"notification\": {\"title\": \"Some Tile\", \"sound\": \"default\",   \"text\": \"MESSAGE GOES HERE\"  },    \"to\" : \"eiF7ZveFBo4:APA91bGu_m_8DEtpgzFKSfKpy_PP2CXIDNIXFKqDJvJuAV_KXObLvLlklgOT9mocVKH4vTOVGg\"}");

curl_exec($ch);
curl_close($ch);
?>
```

### Sample Code that illustrates the problem

```

document.addEventListener("deviceready",onDeviceReady,false);


function onDeviceReady(){
console.log("Device Ready"

var push = PushNotification.init({
    android: {
        senderID: "327546456456",
        sound: true,
        vibrate: true,
	alert: true
    },
    browser: {
        pushServiceURL: 'http://push.api.phonegap.com/v1/push'
    },
    ios: {
        alert: true,
        badge: true,
        sound: true
    },
    windows: {}
});

push.on('registration', function(data) {
console.log(data.registrationId);

$("#gcm_id").html(data.registrationId);


var user = data.registrationId;


});

push.on('notification', function(data) {

console.log(data.message);


///////This is where we alert/show the message received once the app is opened//////////
alert(data.message);

//alert(data.title+" Message: " +data.message);
// data.title,
// data.count,
// data.sound,
// data.image,
// data.additionalData
});

push.on('error', function(e) {
console.log(e.message);
});
}
```

#### Logs taken while reproducing problem
N/A

**Comment by macdonst** [comment]
@rooz121359 I can't reproduce your issue. I can go back as far as an Android 4.4 device and when I click on the notification it opens the app and executes the notification handler.

**Comment by rooz121359** [comment]
So you actually click on the notification and then it opens the app and then it will show the notofication message in the alert(); as well?!

**Comment by rooz121359** [comment]
You also said, you went back as far as 4.4.. I'm not using 4.4.. I'm using 4.2.2.

**Comment by macdonst** [comment]
@rooz121359 that is correct. I click on the notification, it opens the app and then it will show the notification message in the alert();.

I only went as far back as Android 4.4 as I don't have a device that runs 4.2.2.

**Comment by mokingguy** [comment]
@rooz121359 Could you solve it, I have the same problem in android. 6.0.1 to be exact.

@macdonst Do you have to send something with the notification to make it work?, i send a simple json with a string and an number to identify the type of notification im receiving

**Comment by macdonst** [comment]
@mokingguy @rooz121359 don't put the push info in `notification` put it in `data`.

So this:

{ \"data\": {\"title\": \"Some Tile\", \"sound\": \"default\",   \"text\": \"MESSAGE GOES HERE\"  },    \"to\" : \"eiF7ZveFBo4:APA91bGu_m_8DEtpgzFKSfKpy_PP2CXIDNIXFKqDJvJuAV_KXObLvLlklgOT9mocVKH4vTOVGg\"}

not this:

{ \"notification\": {\"title\": \"Some Tile\", \"sound\": \"default\",   \"text\": \"MESSAGE GOES HERE\"  },    \"to\" : \"eiF7ZveFBo4:APA91bGu_m_8DEtpgzFKSfKpy_PP2CXIDNIXFKqDJvJuAV_KXObLvLlklgOT9mocVKH4vTOVGg\"}");

**Comment by rooz121359** [comment]
@mokingguy no, i couldn't solve this at all on android.

@macdonst i haven't tested the solution that you've provided but I wonder why you didn't give me that solution when it was needed and when i posted this question!

**Comment by rooz121359** [comment]
I can confirm that I now have tested the solution that @macdonst posted and it worked like a charm on my Android 4.2.2

such a simple solution but affective. :)


Thanks

I just wish Push notifications were a bit more reliable in terms of delivery.

**Comment by ef33zy** [comment]
@rooz121359 I think you're using FCM, but the logic is exactly the same as described for GCM in [the docs here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#gcm-and-additional-data). 
Where it explicitly shows that for Android you put the info in `data` and for iOS you use `notification`.

**Comment by macdonst** [comment]
@rooz121359 You said `@macdonst i haven't tested the solution that you've provided but I wonder why you didn't give me that solution when it was needed and when i posted this question!`

Maybe because I'm an over worked open source software maintainer and while I'm happy that I was able to resolve your problem I (and other OSS maintainers) don't appreciate those types of comments. Just giving you a heads up for the future.

**Comment by mokingguy** [comment]
@macdonst Hey, I appreciate that you took the time to respond and while I used another solution, Thank you so much for going out of you way to respond and find a solution.

You're doing god's work, Hope you have a nice day :)
