### ISSUE TITLE
Android: Got JSON Exception No value for android

### ISSUE THREAD

**Issue by mohanchalla** [phonegap/phonegap-plugin-push#1371]
#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.8.4

#### Sample Code that illustrates the problem
app.run(['$ionicPlatform',function($ionicPlatform) {
    document.addEventListener("deviceready", function(){
            $cordovaPushV5.initialize(config).then(function() {
				$cordovaPushV5.register().then(function(registrationId) {
                                    console.log("got the registrationId", registrationId);
                                  });
             });
    });
});

#### Logs taken while reproducing problem
adb logcat | grep PushPlugin
V PushPlugin: execute: action=init
V PushPlugin: execute: data=[{"senderID":"XXXXXXX"}]
E PushPlugin: execute: Got JSON Exception No value for android

**Comment by macdonst** [comment]
@mohanchalla well, you haven't shown me what your config is but I believe it is:

```
{"senderID":"XXXXXXX"}
```

which is incorrect, it should be:

```
{"android": {
    "senderID":"XXXXXXX"
  }
}
```

**Comment by mohanchalla** [comment]
The following is the config part Please look at it
var androidConfig = {
	"senderID": "XXXXXX"
};

var iosConfig = {
	"badge": true,
	"sound": true,
	"alert": true
};

var config = ionic.Platform.isIOS() ? iosConfig : androidConfig;

**Comment by fredgalvao** [comment]
Change your code to:

```js
var androidConfig = {
    "senderID": "XXXXXX"
};

var iosConfig = {
    "badge": true,
    "sound": true,
    "alert": true
};

var config = {android: androidConfig, ios: iosConfig};
```

And see if it works.

**Comment by mohanchalla** [comment]
Thank you @macdonst and @fredgalvo
