### ISSUE TITLE
Call on('notification') immediately in background (Android)?

### ISSUE THREAD

**Issue by ryanagler** [phonegap/phonegap-plugin-push#1372]
How can this plugin be configured so that on('notification') gets called immediately while it is in the background? 

Essentially we need to make it so that the user receives a normal push notification (for example, a messaging app of someone saying "hi"), but the message will already have been handled and visible in the app whether the user taps the notification or the app icon itself.  Right now, if the user taps the app icon, it brings the app to the foreground but they will not see that the sender said "hi".

**Comment by fredgalvao** [comment]
Please read: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#push-message-arrives-with-app-in-background

**Comment by ryanagler** [comment]
Perfect, I can't believe I overlooked that, I was trying to find an flag for it in the option parameters -- including content-available in the payload does exactly the trick.  Thanks!
