### ISSUE TITLE
setApplicationIconBadgeNumber doesn't set the badge [android]

### ISSUE THREAD

**Issue by jperruchas** [phonegap/phonegap-plugin-push#1374]
### Expected Behaviour
'1' should be set on the app icon

### Actual Behaviour
no number on the app icon

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Sony Z2 device

#### Cordova CLI version and cordova platform version
    cordova --version                                    # e.g. 6.0.0

#### Plugin version
    cordova plugin version | grep phonegap-plugin-push   # e.g. phonegap-plugin-push 1.8.3 "PushPlugin"

#### Sample Code that illustrates the problem
        push.on('notification', function(data) {
            push.setApplicationIconBadgeNumber(function() {
                console.log('icon success');
            }, function() {
                console.log('icon error');
            }, data.count);
            
            push.finish(function() {
                console.log("processing of push data is finished");
            });
        });

#### Logs taken while reproducing problem
    11-15 12:08:25.701 25974 27409 V PushPlugin: extrasToJSON: {"count":"1","title":"New QuickPoll!","message":"QuickPoll ","additionalData":{"content-available":"1","icon":"ic_notification","lestate":"quickpolls","google.message_id":"0:1479208106762415%ca3b1c94f9fd7ecd","coldstart":false,"collapse_key":"do_not_collapse","foreground":true}}
    11-15 12:08:25.706 25974 26813 V PushPlugin: execute: action=setApplicationIconBadgeNumber
    11-15 12:08:25.709 25974 26813 V PushPlugin: execute: action=finish
    11-15 12:08:25.711 25974 25974 I chromium: [INFO:CONSOLE(143)] "processing of push data is finished", source: file:///android_asset/www/js/controllers.js (143)
    11-15 12:08:25.711 25974 27410 V PushPlugin: setApplicationIconBadgeNumber: data=[{"badge":"1"}]
    11-15 12:08:25.716 25974 25974 I chromium: [INFO:CONSOLE(135)] "icon success", source: file:///android_asset/www/js/controllers.js (135)

I can see the notification on the device, but no badge on the app icon.
Although, as you can see above in the logcat, there is the success message (icon success)

To test if my device is compatible, I installed the application ShortcutBadger and I can set a badge on the icon, then I suppose my device is compatible.

Thank you for your help

**Comment by macdonst** [comment]
@jperruchas hey, I'm afraid I can't help. I have 6 phones but none of them are supported by ShortcutBadger. So when you tested with ShortcutBadger what version did you use? The plugin uses 1.1.4 and maybe it needs to get upgraded so if you could test and send a PR that would be awesome.

**Comment by jperruchas** [comment]
Thank you @macdonst I checked the ShortcutBadger app that I use is the 1.1.11
The latest on the play store : https://play.google.com/store/apps/details?id=me.leolin.isbadgeworking

**Comment by macdonst** [comment]
@jperruchas okay, I'll update ShortcutBadger but I'll need you to test okay?

**Comment by jperruchas** [comment]
@macdonst sure !

**Comment by macdonst** [comment]
@jperruchas okay, I just pushed the change to master. Do the following to test:

```
cordova plugin rm phonegap-plugin-push
cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable SENDER_ID=XXXXXXXX
```

Build, run, test and let me know.

**Comment by macdonst** [comment]
See #1248 for original request to update ShortcutBadger

**Comment by jperruchas** [comment]
@macdonst I juste tested with the latest version, but unfortunally, I can't see any badge on the app icon...
See logcat :
    11-16 17:41:42.659 24162 24312 V PushPlugin: extrasToJSON: {"count":"1","title":"New QuickPoll!","message":"new quickpoll","additionalData":{"content-available":"1","icon":"ic_notification","lestate":"quickpolls","google.message_id":"0:1479314481229592%ca3b1c94f9fd7ecd","coldstart":true,"collapse_key":"do_not_collapse","foreground":false}}
    11-16 17:41:42.684 24162 24311 V PushPlugin: execute: action=setApplicationIconBadgeNumber
    11-16 17:41:42.684 24162 24312 V PushPlugin: setApplicationIconBadgeNumber: data=[{"badge":"1"}]
    11-16 17:41:42.689 24162 24311 V PushPlugin: execute: action=finish
    11-16 17:41:42.691 24162 24162 D SystemWebChromeClient: file:///android_asset/www/js/controllers.js: Line 143 : processing of push data is finished
    11-16 17:41:42.691 24162 24162 I chromium: [INFO:CONSOLE(143)] "processing of push data is finished", source: file:///android_asset/www/js/controllers.js (143)
    11-16 17:41:42.692 24162 24311 V PushPlugin: execute: action=setApplicationIconBadgeNumber
    11-16 17:41:42.692 24162 24312 V PushPlugin: setApplicationIconBadgeNumber: data=[{"badge":"1"}]
    11-16 17:41:42.695 24162 24311 V PushPlugin: execute: action=finish
    11-16 17:41:42.701 24162 24162 D SystemWebChromeClient: file:///android_asset/www/js/controllers.js: Line 143 : processing of push data is finished
    11-16 17:41:42.701 24162 24162 I chromium: [INFO:CONSOLE(143)] "processing of push data is finished", source: file:///android_asset/www/js/controllers.js (143)
    11-16 17:41:42.724 24162 24162 D SystemWebChromeClient: file:///android_asset/www/js/controllers.js: Line 135 : icon success
    11-16 17:41:42.724 24162 24162 I chromium: [INFO:CONSOLE(135)] "icon success", source: file:///android_asset/www/js/controllers.js (135)
    11-16 17:41:42.724 24162 24162 D SystemWebChromeClient: file:///android_asset/www/js/controllers.js: Line 135 : icon success
    11-16 17:41:42.724 24162 24162 I chromium: [INFO:CONSOLE(135)] "icon success", source: file:///android_asset/www/js/controllers.js (135)
Sorry...

**Comment by macdonst** [comment]
@jperruchas what is your testing procedure? Do you have `clearBadge` set to true?

**Comment by jperruchas** [comment]
@macdonst yes I set clearbadge to true.
I will explain what I did, maybe I'm wrong...
Each time I launch the app, I register (to be sure to have the latest register ID)
This code is the starter code of the app:

        var push = PushNotification.init({
            android: {
                "senderID": "XXX",
                "icon": "ic_notification",
                "iconColor": "blue",
                "alert": "true",
                "badge": "true",
                "sound": "true",
                "clearBadge": "true"
            },
            ios: {
                "alert": "true",
                "badge": "true",
                "sound": "true",
                "clearBadge": "true"
            },
            windows: {}
        });

        push.on('registration', function(data) {
            console.log("id "+data.registrationId);
            if (ionic.Platform.isAndroid()) {
                manageDeviceToken('register', 'android', data.registrationId);
            } else if (ionic.Platform.isIOS()) {
                manageDeviceToken('register', 'ios', data.registrationId);
            }
        });

        push.on('notification', function(data) {
            console.log(data.additionalData.lestate);
            push.setApplicationIconBadgeNumber(function() {
                console.log('icon success');
            }, function() {
                console.log('icon error');
            }, data.count);
            
            push.finish(function() {
                console.log("processing of push data is finished");
            });
        });

This is now all event store via the logcat

    ====== 1st app launch
    11-17 10:46:32.699 19576 19576 I CordovaLog: Changing log level to DEBUG(3)
    11-17 10:46:32.699 19576 19576 I CordovaActivity: Apache Cordova native platform version 6.0.0 is starting
    11-17 10:46:32.699 19576 19576 D CordovaActivity: CordovaActivity.onCreate()
    11-17 10:46:33.041 19576 19576 D PluginManager: init()
    11-17 10:46:33.186 19576 19576 D CordovaActivity: Started the activity.
    11-17 10:46:33.186 19576 19576 D CordovaActivity: Resumed the activity.
    11-17 10:46:36.323 19576 19576 W cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 19576
    11-17 10:46:36.326 19576 19650 V PushPlugin: execute: action=init
    11-17 10:46:36.326 19576 19651 V PushPlugin: execute: data=[{"android":{"senderID":"XXXX","icon":"ic_notification","iconColor":"blue","alert":"true","badge":"true","sound":"true","clearBadge":"true"},"ios":{"alert":"true","badge":"true","sound":"true","clearBadge":"true"},"windows":{}}]
    11-17 10:46:36.327 19576 19651 V PushPlugin: execute: jo={"senderID":"XXXX","icon":"ic_notification","iconColor":"blue","alert":"true","badge":"true","sound":"true","clearBadge":"true"}
    11-17 10:46:36.327 19576 19651 V PushPlugin: execute: senderID=XXXX
    11-17 10:46:36.343 19576 19651 V PushPlugin: onRegistered: {"registrationId":"___id___"}
    11-17 10:46:36.363 19576 19576 I chromium: [INFO:CONSOLE(123)] "id ___id___", source: file:///android_asset/www/js/controllers.js (123)
    11-17 10:46:36.758 19576 19576 I chromium: [INFO:CONSOLE(170)] "Token register", source: file:///android_asset/www/js/controllers.js (170)
    
    ====== close the app
    11-17 10:46:51.128 19576 19576 D CordovaActivity: Paused the activity.
    11-17 10:46:51.146 19576 19576 D CordovaActivity: Stopped the activity.
    11-17 10:46:51.953   976  3326 I ActivityManager: Killing 19576:com.domain.app/u0a390 (adj 9): remove task
    
    ====== receive notification
    11-17 10:47:27.825   976  1044 I ActivityManager: Start proc 19910:com.domain.app/u0a390 for broadcast com.domain.app/com.google.android.gms.gcm.GcmReceiver
    11-17 10:47:27.886 19910 19910 W System  : ClassLoader referenced unknown path: /data/app/com.domain.app-1/lib/arm
    11-17 10:47:27.910 19910 19924 D PushPlugin_GCMIntentService: onMessage - from: XXXX
    11-17 10:47:27.914 19910 19924 D PushPlugin_GCMIntentService: normalize extras
    11-17 10:47:27.914 19910 19924 D PushPlugin_GCMIntentService: key = content-available
    11-17 10:47:27.915 19910 19924 D PushPlugin_GCMIntentService: replace key content-available with content-available
    11-17 10:47:27.915 19910 19924 D PushPlugin_GCMIntentService: key = google.sent_time
    11-17 10:47:27.915 19910 19924 D PushPlugin_GCMIntentService: replace key google.sent_time with google.sent_time
    11-17 10:47:27.915 19910 19924 D PushPlugin_GCMIntentService: key = icon
    11-17 10:47:27.915 19910 19924 D PushPlugin_GCMIntentService: replace key icon with icon
    11-17 10:47:27.915 19910 19924 D PushPlugin_GCMIntentService: key = lestate
    11-17 10:47:27.915 19910 19924 D PushPlugin_GCMIntentService: replace key lestate with lestate
    11-17 10:47:27.915 19910 19924 D PushPlugin_GCMIntentService: key = badge
    11-17 10:47:27.915 19910 19924 D PushPlugin_GCMIntentService: replace key badge with count
    11-17 10:47:27.915 19910 19924 D PushPlugin_GCMIntentService: key = count
    11-17 10:47:27.915 19910 19924 D PushPlugin_GCMIntentService: replace key count with count
    11-17 10:47:27.915 19910 19924 D PushPlugin_GCMIntentService: key = title
    11-17 10:47:27.915 19910 19924 D PushPlugin_GCMIntentService: replace key title with title
    11-17 10:47:27.916 19910 19924 D PushPlugin_GCMIntentService: no locale found for key = title, error Value New of type java.lang.String cannot be converted to JSONObject
    11-17 10:47:27.916 19910 19924 D PushPlugin_GCMIntentService: key = google.message_id
    11-17 10:47:27.916 19910 19924 D PushPlugin_GCMIntentService: replace key google.message_id with google.message_id
    11-17 10:47:27.916 19910 19924 D PushPlugin_GCMIntentService: key = message
    11-17 10:47:27.916 19910 19924 D PushPlugin_GCMIntentService: replace key message with message
    11-17 10:47:27.916 19910 19924 D PushPlugin_GCMIntentService: no locale found for key = message, error Value QuickPoll of type java.lang.String cannot be converted to JSONObject
    11-17 10:47:27.916 19910 19924 D PushPlugin_GCMIntentService: key = collapse_key
    11-17 10:47:27.917 19910 19924 D PushPlugin_GCMIntentService: replace key collapse_key with collapse_key
    11-17 10:47:27.926 19910 19924 D PushPlugin_GCMIntentService: background
    11-17 10:47:27.926 19910 19924 D PushPlugin_GCMIntentService: count =[1]
    11-17 10:47:27.927 19910 19924 D PushPlugin_GCMIntentService: message =[new quickpoll]
    11-17 10:47:27.928 19910 19924 D PushPlugin_GCMIntentService: title =[New QuickPoll!]
    11-17 10:47:27.928 19910 19924 D PushPlugin_GCMIntentService: contentAvailable =[1]
    11-17 10:47:27.928 19910 19924 D PushPlugin_GCMIntentService: forceStart =[null]
    11-17 10:47:27.928 19910 19924 D PushPlugin_GCMIntentService: create notification
    11-17 10:47:27.928 19910 19924 E PushPlugin_GCMIntentService: Number format exception - Error parsing notId: Invalid int: "null"
    11-17 10:47:27.933 19910 19924 D PushPlugin_GCMIntentService: stored icon=ic_notification
    11-17 10:47:27.933 19910 19924 D PushPlugin_GCMIntentService: stored iconColor=blue
    11-17 10:47:27.933 19910 19924 D PushPlugin_GCMIntentService: stored sound=true
    11-17 10:47:27.934 19910 19924 D PushPlugin_GCMIntentService: stored vibrate=true
    11-17 10:47:27.934 19910 19924 D PushPlugin_GCMIntentService: using icon from plugin options
    11-17 10:47:27.935 19910 19924 D PushPlugin_GCMIntentService: count =[1]
    11-17 10:47:27.936 19910 19924 D PushPlugin_GCMIntentService: create actions: with in-line
    11-17 10:47:27.953 19910 19924 D PushPlugin_GCMIntentService: app is not running and content available true
    11-17 10:47:27.953 19910 19924 D PushPlugin_GCMIntentService: send notification event
    11-17 10:47:27.953 19910 19924 V PushPlugin: sendExtras: caching extras to send at a later time.
    
    ====== tap on the notifcation => start the app
    11-17 10:47:46.475 19910 19910 D PushPlugin_PushHandlerActivity: not id = 0
    11-17 10:47:46.475 19910 19910 V PushPlugin_PushHandlerActivity: onCreate
    11-17 10:47:46.475 19910 19910 D PushPlugin_PushHandlerActivity: callback = null
    11-17 10:47:46.476 19910 19910 D PushPlugin_PushHandlerActivity: bringToForeground = true
    11-17 10:47:46.478 19910 19910 V PushPlugin: sendExtras: caching extras to send at a later time.
    11-17 10:47:46.790 19910 19910 D PushPlugin_PushHandlerActivity: isPushPluginActive = false
    11-17 10:47:46.790 19910 19910 D PushPlugin_PushHandlerActivity: forceMainActivityReload
    11-17 10:47:46.793 19910 19910 I Timeline: Timeline: Activity_launch_request id:com.domain.app time:74821424
    11-17 10:47:46.864 19910 19910 I CordovaLog: Changing log level to DEBUG(3)
    11-17 10:47:46.864 19910 19910 I CordovaActivity: Apache Cordova native platform version 6.0.0 is starting
    11-17 10:47:46.864 19910 19910 D CordovaActivity: CordovaActivity.onCreate()
    11-17 10:47:47.212 19910 19910 D PluginManager: init()
    11-17 10:47:47.297 19910 19910 D CordovaActivity: Started the activity.
    11-17 10:47:47.297 19910 19910 D CordovaActivity: Resumed the activity.
    11-17 10:47:50.424 19910 19910 I chromium: [INFO:CONSOLE(102)] "register + clear", source: file:///android_asset/www/js/controllers.js (102)
    11-17 10:47:50.543 19910 20132 V PushPlugin: execute: action=init
    11-17 10:47:50.544 19910 20133 V PushPlugin: execute: data=[{"android":{"senderID":"XXXX","icon":"ic_notification","iconColor":"blue","alert":"true","badge":"true","sound":"true","clearBadge":"true"},"ios":{"alert":"true","badge":"true","sound":"true","clearBadge":"true"},"windows":{}}]
    11-17 10:47:50.544 19910 20133 V PushPlugin: execute: jo={"senderID":"XXXX","icon":"ic_notification","iconColor":"blue","alert":"true","badge":"true","sound":"true","clearBadge":"true"}
    11-17 10:47:50.544 19910 20133 V PushPlugin: execute: senderID=XXXX
    11-17 10:47:50.560 19910 20133 V PushPlugin: onRegistered: {"registrationId":"___id___"}
    11-17 10:47:50.565 19910 20133 V PushPlugin: sending cached extras
    11-17 10:47:50.565 19910 20133 D PushPlugin: convert extras to json
    11-17 10:47:50.565 19910 20133 D PushPlugin: key = content-available
    11-17 10:47:50.565 19910 20133 D PushPlugin: key = google.sent_time
    11-17 10:47:50.566 19910 20133 D PushPlugin: key = icon
    11-17 10:47:50.566 19910 20133 D PushPlugin: key = lestate
    11-17 10:47:50.566 19910 20133 D PushPlugin: key = count
    11-17 10:47:50.566 19910 20133 D PushPlugin: key = title
    11-17 10:47:50.566 19910 20133 D PushPlugin: key = google.message_id
    11-17 10:47:50.566 19910 20133 D PushPlugin: key = message
    11-17 10:47:50.566 19910 20133 D PushPlugin: key = coldstart
    11-17 10:47:50.566 19910 20133 D PushPlugin: key = collapse_key
    11-17 10:47:50.566 19910 20133 D PushPlugin: key = foreground
    11-17 10:47:50.566 19910 20133 V PushPlugin: extrasToJSON: {"count":"1","title":"New QuickPoll!","message":"new quickpoll","additionalData":{"content-available":"1","icon":"ic_notification","lestate":"quickpolls","google.message_id":"0:1479376047714303%ca3b1c94f9fd7ecd","coldstart":false,"collapse_key":"do_not_collapse","foreground":false}}
    11-17 10:47:50.566 19910 20133 D PushPlugin: convert extras to json
    11-17 10:47:50.566 19910 20133 D PushPlugin: key = content-available
    11-17 10:47:50.566 19910 20133 D PushPlugin: key = google.sent_time
    11-17 10:47:50.566 19910 20133 D PushPlugin: key = actionCallback
    11-17 10:47:50.566 19910 20133 D PushPlugin: key = icon
    11-17 10:47:50.566 19910 20133 D PushPlugin: key = lestate
    11-17 10:47:50.566 19910 20133 D PushPlugin: key = count
    11-17 10:47:50.567 19910 20133 D PushPlugin: key = title
    11-17 10:47:50.567 19910 20133 D PushPlugin: key = google.message_id
    11-17 10:47:50.567 19910 20133 D PushPlugin: key = message
    11-17 10:47:50.567 19910 20133 D PushPlugin: key = coldstart
    11-17 10:47:50.567 19910 20133 D PushPlugin: key = collapse_key
    11-17 10:47:50.568 19910 20133 D PushPlugin: key = foreground
    11-17 10:47:50.569 19910 20133 V PushPlugin: extrasToJSON: {"count":"1","title":"New QuickPoll!","message":"new quickpoll","additionalData":{"content-available":"1","icon":"ic_notification","lestate":"quickpolls","google.message_id":"0:1479376047714303%ca3b1c94f9fd7ecd","coldstart":true,"collapse_key":"do_not_collapse","foreground":false}}
    11-17 10:47:50.599 19910 19910 I chromium: [INFO:CONSOLE(123)] "id ___id___", source: file:///android_asset/www/js/controllers.js (123)
    11-17 10:47:50.608 19910 19910 I chromium: [INFO:CONSOLE(133)] "quickpolls", source: file:///android_asset/www/js/controllers.js (133)
    11-17 10:47:50.609 19910 20132 V PushPlugin: execute: action=setApplicationIconBadgeNumber
    11-17 10:47:50.610 19910 20133 V PushPlugin: setApplicationIconBadgeNumber: data=[{"badge":"1"}]
    11-17 10:47:50.615 19910 20132 V PushPlugin: execute: action=finish
    11-17 10:47:50.619 19910 20132 V PushPlugin: execute: action=setApplicationIconBadgeNumber
    11-17 10:47:50.620 19910 20133 V PushPlugin: setApplicationIconBadgeNumber: data=[{"badge":"1"}]
    11-17 10:47:50.621 19910 19910 I chromium: [INFO:CONSOLE(143)] "processing of push data is finished", source: file:///android_asset/www/js/controllers.js (143)
    11-17 10:47:50.621 19910 19910 I chromium: [INFO:CONSOLE(133)] "quickpolls", source: file:///android_asset/www/js/controllers.js (133)
    11-17 10:47:50.627 19910 20132 V PushPlugin: execute: action=finish
    11-17 10:47:50.629 19910 19910 I chromium: [INFO:CONSOLE(143)] "processing of push data is finished", source: file:///android_asset/www/js/controllers.js (143)
    11-17 10:47:50.646 19910 19910 I chromium: [INFO:CONSOLE(135)] "icon success", source: file:///android_asset/www/js/controllers.js (135)
    11-17 10:47:50.653 19910 19910 I chromium: [INFO:CONSOLE(135)] "icon success", source: file:///android_asset/www/js/controllers.js (135)
    11-17 10:47:51.108 19910 19910 I chromium: [INFO:CONSOLE(170)] "Token register", source: file:///android_asset/www/js/controllers.js (170)
    11-17 10:47:57.135 19910 19910 D CordovaActivity: Paused the activity.
    11-17 10:47:57.323 19910 19910 D CordovaActivity: Stopped the activity.

**Comment by bromeostasis** [comment]
@macdonst @jperruchas do you think it would be worth mentioning the device support somewhere in the documentation? I just spent a few hours trying to upgrade versions because badges were working on some devices and not others. 

I thought I had this exact issue as well, but after searching for a while, I finally found discussions that told me badges just weren't possible on certain Android devices. I recently switched phones from an LG to a Moto.

I know it would've helped me to read about the device support before beginning to implement badges, and it certainly would've helped me diagnose this issue faster.

It could be mentioned in [Android details](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#android-details) or with [the actual method](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushsetapplicationiconbadgenumbersuccesshandler-errorhandler-count---ios--android-only). 

Let me know what you think!

**Comment by fredgalvao** [comment]
@bromeostasis We kinda already do document this peculiarity [here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#badges):

> On Android not all launchers support badges. In order for us to set badges we use ShortcutBadger in order to set the badge. Check out their website to see which launchers are supported.

I would agree that we can have a more detailed and clear instruction there or somewhere else. Would you be willing to create a PR for that?

**Comment by bromeostasis** [comment]
@fredgalvao ah I see, that's what I would've been looking for 😄 . Yeah I can make a PR! I'll probably just add a few links to that page, just to let others like me know it exists.

**Comment by bromeostasis** [comment]
@fredgalvao submitted https://github.com/phonegap/phonegap-plugin-push/pull/1398 . First time contributing here, so feel free to provide any feedback!
