### ISSUE TITLE
Notification's sound and vibration does not play when being inside a phone call

### ISSUE THREAD

**Issue by HamzaLJ** [phonegap/phonegap-plugin-push#1375]
### Expected Behavior

Play sound even if the phone call is running...
Vibrate

### Actual Behavior

When having a phone call, the notification does not play any sound.
It's does not vibrate at all

### Reproduce Scenario (including but not limited to)

Using a smartphone start a phone call and push the notification, you'll see that you'll not hear the notification voice nor feel the vibration. 

**_P.S. The vibration never trigger in all the cases._**

#### Steps to Reproduce 

        1.  Start a phone call
        2. Push the notification, using the sample code that can be found below.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

# Android  6.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Samsung Note 5

#### Cordova CLI version and cordova platform version

    cordova --version              
     6.3.0
    cordova platform version android   
    android 5.2.2

#### Plugin version

   phonegap-plugin-push 1.8.0 "PushPlugin"

#### Sample Push Data Payload

N/A

#### Sample Code that illustrates the problem

                 data: {
                       sound: "default",
                       title: "New",
                       alert: "This is a new notification !",
                       soundname:"ringtone",
                       vibrate:true,
                       vibrationPattern: [2000, 1000, 500, 500],
                       priority: 2,
                       visibility: 1
                   }

#### Logs taken while reproducing problem

N/A

**Comment by macdonst** [comment]
@HamzaLJ I'm pretty sure this is a setting in the Phone app of your device. IIRC there is a setting in the app to determine whether or not notification sounds are played during a phone call.

**Comment by HamzaLJ** [comment]
@macdonst you maybe right, but the thing is that it does not even Vibrate, nor trigger the vibration pattern.

**Comment by macdonst** [comment]
@HamzaLJ yeah, that is a setting on your phone. It would be really annoying if the phone started vibrating in your hand while you had it plastered to your ear. Did you check the Phone app's settings?

**Comment by HamzaLJ** [comment]
@macdonst I've already tried all the settings, none works.
A good example of what I want to reach is "Facebook Messenger" when someone calls you on it, the phone rings and vibrate with pattern, you can try it out.
So, far I was not able similar result, and I am still stuck.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
