### ISSUE TITLE
Xcode 8 shows a lot of Deprecated Warnings

### ISSUE THREAD

**Issue by abhijeet-gupta** [phonegap/phonegap-plugin-push#1376]
I used this plugin **(Version 1.8.4)** for my PhoneGap project. But with the Xcode 8, **PushPlugin.m** file shows a lot of deprecated warnings.
- **Plugins/phonegap-plugin-push/PushPlugin.m:223:9: 'UIRemoteNotificationType' is deprecated:** first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
- **Plugins/phonegap-plugin-push/PushPlugin.m:223:54: 'UIRemoteNotificationTypeNone' is deprecated:** first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
- **Plugins/phonegap-plugin-push/PushPlugin.m:232:34: 'UIRemoteNotificationTypeBadge' is deprecated:** first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
- **Plugins/phonegap-plugin-push/PushPlugin.m:240:34: 'UIRemoteNotificationTypeSound' is deprecated:** first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
- **Plugins/phonegap-plugin-push/PushPlugin.m:248:34: 'UIRemoteNotificationTypeAlert' is deprecated:** first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
- **Plugins/phonegap-plugin-push/PushPlugin.m:254:30: 'UIRemoteNotificationTypeNewsstandContentAvailability' is deprecated:** first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
- **Plugins/phonegap-plugin-push/PushPlugin.m:269:34: 'UIRemoteNotificationTypeNone' is deprecated:** first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
- **Plugins/phonegap-plugin-push/PushPlugin.m:343:15: 'UIRemoteNotificationTypeBadge' is deprecated:** first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
- **Plugins/phonegap-plugin-push/PushPlugin.m:343:47: 'UIRemoteNotificationTypeSound' is deprecated:** first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
- **Plugins/phonegap-plugin-push/PushPlugin.m:343:79: 'UIRemoteNotificationTypeAlert' is deprecated:** first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
- **Plugins/phonegap-plugin-push/PushPlugin.m:342:48: 'registerForRemoteNotificationTypes:' is deprecated:** first deprecated in iOS 8.0 - Use -[UIApplication registerForRemoteNotifications] and UserNotifications Framework's -[UNUserNotificationCenter requestAuthorizationWithOptions:completionHandler:]
- **Plugins/phonegap-plugin-push/PushPlugin.m:430:54: 'enabledRemoteNotificationTypes' is deprecated:** first deprecated in iOS 8.0 - Use -[UIApplication isRegisteredForRemoteNotifications] and UserNotifications Framework's -[UNUserNotificationCenter getNotificationSettingsWithCompletionHandler:] to retrieve user-enabled remote notification and user notification settings
- **Plugins/phonegap-plugin-push/PushPlugin.m:442:18: 'UIRemoteNotificationTypeBadge' is deprecated:** first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
- **Plugins/phonegap-plugin-push/PushPlugin.m:445:18: 'UIRemoteNotificationTypeAlert' is deprecated**: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
- **Plugins/phonegap-plugin-push/PushPlugin.m:448:18: 'UIRemoteNotificationTypeSound' is deprecated:** first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.

**Please remove these deprecated methods from the Plugin and release a new update.**

**Comment by macdonst** [comment]
@abhijeet-gupta @Hamzal_J I can't remove these deprecation notices without stopping support for earlier iOS versions. Please add your thumbs up to #1340
