### ISSUE TITLE
Help needed to implement dynamic firebase push notification or stack of push notifications using cordova plugin

### ISSUE THREAD

**Issue by anoj-kumar** [phonegap/phonegap-plugin-push#1377]
Hi All,

I have developed mobile app using cordova plugins where i used "https://www.npmjs.com/package/cordova-plugin-fcm" plugin to implement push notification feature in my app. Now i want to enhance this firebase push notification feature by customizing notification content like below:
1. Group of notifications in stack manner(i.e. latest notification on top and oldest unread notification at bottom) with only one app title. It means grouping of more than one unread notifications under one notification title. 
Ex: MY TITLE
       message 1
       message 2
       message 3(Please refer attached "stack notification.png" sample image
![stacked notifications](https://cloud.githubusercontent.com/assets/13646751/20344129/7d1a7c4a-ac17-11e6-97e1-8dd998232d76.png)
)
2. Custom notification with big customized image and buttons, where image will be my app brand image and buttons like:SUBMIT/OPEN/GO will be placed over image to provide click action.

I researched a lot but couldn't get any article where FCM is used to send multiple notifications & to customized the notification. I found this plugin i.e."phonegap-plugin-push" but it is not helpful in my case because Google Cloud Messaging is implemented here to explain sample codes.

Kindly guide me to implement above listed features or else provide and any article or cordova plugin details so that i will implement.

Thanks a lot in advance!

**Comment by macdonst** [comment]
@anoj-kumar we are planning FCM support for 2.0.0 of this plugin.
