### ISSUE TITLE
Is it possible to enable only vibration on IOS ?

### ISSUE THREAD

**Issue by ledil** [phonegap/phonegap-plugin-push#1379]
Actually I can see only the option disable/enable push and sound, what about to say ... enable push but only vibration, is this possible ?

**Comment by macdonst** [comment]
@ledil I'm assuming this is on iOS. "If the sound file doesn’t exist or default is specified as the value, the default alert sound is played.". What they don't say is that if you don't provide a sound key at all, no sound will be played. If no sound is played, the phone should not vibrate as well.
