### ISSUE TITLE
Question concerning frequency of communication with APNs

### ISSUE THREAD

**Issue by dtc7240** [phonegap/phonegap-plugin-push#138]
I apologize that I'm not familiar enough with Objective-C to determine the answer to this question myself, and therefore am very grateful in advance to anyone who can answer it for me.

In short, the question is:  Does this plugin 'register' with APNs every time `var push = PushNotification.init{...}` is called?  

My hope is that the native code in the plugin only communicates with APNs once upon cold start no matter how many times `PushNotification.init{...}` is called.

Because I'm in a somewhat unique environment in which I reload the client side Javascript often, I will have to re-initialize each time in order to maintain the `push.on('notification', ...)` listener.  With this plugin's predecessor, one of the iOS options was 'ecb' ... the name of the javascript function to call when a notification was received.  Therefore, I had no problem only registering with APNs once every cold start, as I did not have to re-establish a listener each time the client side Javascript was reloaded.

I would much prefer to use this newer version of the plugin for several reasons (and kudos to all who have participated in its development):
* Uniform javascript front-end for all platforms
* A Boolean showing whether the app was open in the foreground when a notification was received
* The ability to pass the extra data as a JSON object (the predecessor plugin would only pass flat data)

Many thanks for a speedy answer so that I know which way I must go...
Scott

**Comment by dtc7240** [comment]
@macdonst, I'm hoping you can give me a quick answer to the question above Simon....?

Many thanks,
Scott

**Comment by macdonst** [comment]
@dtc7240 I'm pretty sure that if the app is already registered it won't talk to APNS again and it will just give you back the registration ID. However, I'm speaking at a conference today and haven't had the time to sniff the phone to see what is going across the network to give you a definitive answer.

**Comment by dtc7240** [comment]
@macdonst Thank you so much for taking a moment to answer even while you're tied up in a conference Simon!  I truly appreciate it.  I think I will proceed with the new plugin based upon your gut feel, and will look for a confirmation later when you (or someone else) has time to look a little more thoroughly.  

Either way, given your answer, it sounds like it can and perhaps would benefit from working that way even if it doesn't currently.

Thanks again,
Scott Seitz

**Comment by fredgalvao** [comment]
Once a device is registered, it doesn't need to be registered again unless that regId is undone at some point and needs to be restored, so I don't think it **should** actually try to register again.

If you happen to lose regIds along the way even though you didn't uninstall your app from such devices, it's probably something related to the certificate (I've had that issue with expired certificates).

**Comment by dtc7240** [comment]
Thanks for your feedback on this, gentlemen.

@fredgalvao, I'm not actually worried about losing regIDs along the way.  My concern is centered around not "bugging" APNs with frequent unnecessary registrations (due to my particular environment in which I will have to call `PushNotification.init{...}` often).  I want to say I recall reading somewhere along the way that Apple might treat that unfavorably ... of course, I may just be recalling their instructions to leave a socket connection open for sending push notifications over rather than constantly tearing down the connection after every send.

At any rate, I'd REALLY appreciate it if someone smarter than me can confirm that the code on the native side does NOT attempt to register with APNs again if it already has a regID.  My hope is that it only attempts to register with APNs upon cold start.

Many thanks in advance to anyone who might have a moment to confirm this...

Scott

**Comment by fredgalvao** [comment]
Do you mean **cold start** or do you actually mean **first run after install**?

**Comment by dtc7240** [comment]
I meant **cold start**, but now that you mention it, the token (regID) would never change unless the app had been removed from the device (along with any other apps from the same author) and reinstalled, so **first run after install** might be just as viable an answer.  

In the second scenario, I'm unfamiliar what criteria Apple uses to drop tokens from APNs (discovered via their feedback mechanism).  If they only drop a token because it is no longer valid, then this works well.  If they drop a token because they haven't heard from it in a particular amount of time, then not so well.

Knowing how deliberate Apple typically is, it would be my guess that **first run after install** is what I really meant. :smile:

**Comment by fredgalvao** [comment]
Ok at least the questioning makes sense to me now. **Cold start** wasn't really an option, as it would imply that the native code would keep calling APNS in a loop/interval even if the `.init()` has finished.

Although I'd highly doubt it to be an issue in Apple's eyes, it's worth a shot to ask @macdonst if this plugin
* **saves the received regId somewhere native-side so that future calls to `.init()` only re-registers callbacks** or if it
* **tries again at APNS to see if maybe anything changed, or maybe just to ping APNS server to keep that regId alive** (I, as you, don't know what circumstances Apple use to decide on the life of a regId).

If anyone have details on the inner mechanics Apple use to kill a regId, I'm also interested.

**Comment by macdonst** [comment]
From the iOS docs:

```
The device token is your key to sending push notifications to your app on a specific device. Device tokens can change, so your app needs to reregister every time it is launched and pass the received token back to your server. If you fail to update the device token, remote notifications might not make their way to the user’s device. Device tokens always change when the user restores backup data to a new device or computer or reinstalls the operating system. When migrating data to a new device or computer, the user must launch your app once before remote notifications can be delivered to that device.
```

So yes, the app should and does communicate with APNS every time it is started.

Reference: https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/IPhoneOSClientImp.html
