### ISSUE TITLE
[v2.0.x][Android] Multiple build errors

### ISSUE THREAD

**Issue by JaimeFerBec** [phonegap/phonegap-plugin-push#1381]
## First build error
> FAILURE: Build failed with an exception.
>
> What went wrong:
> Execution failed for task ':transformClassesWithDexForArmv7Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

I looked this error up on the web, and found out it had something to do with Android Support Libraries v4. I looked for v4 Android Support Libraries in my project plugin's directory, finding references in several of the plugins I'm using, one of the references being the `push.gradle` file in this plugin. This led me to issue #909.
The timeline goes like this:

1. `push.gradle` gets updated on master branch to compensate for new Google Play Services' incompatibility with older Android Support Libraries (v4 being on of them).
2. The v2.0.x branch is created.
3. `push.gradle` changes are reverted since Google fixes its incompatibility issues. The changes are only reverted in the master branch, not in the v2.0.x branch.

### Solution
I reverted the changes to `push.gradle` locally, which basically means deleting the following lines from the end of the file:
```
configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-v4:23.4.0'
    }
}
```
This solves the first build error.

## Second build error
After solving the first error I tried `cordova build android` again, and encountered the following error:
> FAILURE: Build failed with an exception.
>
> What went wrong:
> Execution failed for task ':transformClassesWithDexForArmv7Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/FirebaseException;

Which led me to a couple of comments on issue #929. The first one is exactly the same build error I got. The second one led me to the solution:

> @pierreNeck: You probably have a mismatch with the google play services version and the firebase version. If you have google play services v31 you need firebase 9.2.0.
>
>Google play services you can find in your sdk manager. Firebase version you find in your app in build.gradle.
>
>It will probably say something like compile "com.google.firebase:firebase-core:9.2.0"

### Solution
I changed the following line in `plugin.xml`:
```
<framework src="com.google.firebase:firebase-messaging:9.0.0" />
```
As it turns out version 9.0.0 of Firebase messaging did not match the more recent Google Play Services I had installed (rev 37). Since 9.0.0 was the version originally specified for this plugin, I decided the best solution would be to allow versions greater than 9.0.0 for Firebase messaging, so I changed the previous line in `plugin.xml` by this one:
```
<framework src="com.google.firebase:firebase-messaging:9+" />
```

## Aggregated solution
Delete following lines at the end of the `push.gradle` file located in the root folder of this plugin:
```
configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-v4:23.4.0'
    }
}
```

In file `plugin.xml` (also located in the root folder of this project) change this line:
```
<framework src="com.google.firebase:firebase-messaging:9.0.0" />
```
by this one:
```
<framework src="com.google.firebase:firebase-messaging:9+" />
```

## Request
I would like for these couple of changes to be made to the v2.0.x branch of this great project, thus solving the build errors I described.

**Comment by macdonst** [comment]
@JaimeFerBec then send a PR for it, what you say makes sense and it would help us out.

**Comment by JaimeFerBec** [comment]
@macdonst I just did. Sorry for not knowing exactly how to proceed, I am kind of new to github.
