### ISSUE TITLE
App notification not showing in status bar when app is opened

### ISSUE THREAD

**Issue by mbachaalani** [phonegap/phonegap-plugin-push#1382]
Hello,

When I send a notification and the app is opened the notification is not showing in the status bar. Is it a normal behavior? As well no redirection to the notification related is done.

Thank you

**Comment by jcesarmobile** [comment]
Yes, it's the normal behaviour, when the app it's open it won't show anything, but on notification will be called with all the notification payload

**Comment by mbachaalani** [comment]
Can we override this behavior? and in the payload there is the url to the redirection page. Meaning I do not want the user be redirected automatically to the page on notification if the app is opened.

Thank you

**Comment by macdonst** [comment]
@mbachaalani please read the docs. There is a [force show](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#android) attribute you can set on Android but not on iOS. iOS just won't allow it.

For re-directing based on url you can read up on it in my workshops:

http://macdonst.github.io/push-workshop-eu/module7.html

**Comment by mbachaalani** [comment]
Ok thank you for the information it is helpful

**Comment by fgagneten** [comment]
@macdonst  When are you gonna solve the problem of notification on iPhone? Thanks

**Comment by macdonst** [comment]
@fgagneten well it is only possible on iOS 10 so I will get to it at some point in the future but PR's are always welcome. Honestly, I need to get the FCM release out first and drop support for iOS 8 before I tackle this issue.

**Comment by packruler** [comment]
Is there any update on this?
