### ISSUE TITLE
push notif not working in iOS, do we need to buy $99 first ?

### ISSUE THREAD

**Issue by hendranata** [phonegap/phonegap-plugin-push#1387]
### Expected Behaviour
push notification should be working in iOS device

### Actual Behaviour
push notification does not working in iOS device

#### Steps to Reproduce 
do we need to actually purchase $99 apple developer account to activated push notification in iOS?

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iphone 6s

#### Cordova CLI version and cordova platform version

    cordova --version                                     6.4.0
    cordova platform version ios                      3.6

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.9.0

**Comment by jcesarmobile** [comment]
Yes, for making push work you need a developer license, so you can create the push certificates
