### ISSUE TITLE
On register event not fired using ios 10.1.1

### ISSUE THREAD

**Issue by js12690** [phonegap/phonegap-plugin-push#1388]
I am using latest plugin version of push notification (1.9.0) and create build using phonegap build with cli 6.4.0. Build created successfully and work fine on IOS 9.3.0 but when  test application on IOS 10.1.1 register event not fire.

I am using following code. Please help me as soon as possible

var push = PushNotification.init({
    android: {
        senderID: "12345679"
    },
    browser: {
        pushServiceURL: 'http://push.api.phonegap.com/v1/push'
    },
    ios: {
        alert: "true",
        badge: "true",
        sound: "true"
    },
    windows: {}
});

push.on('registration', function(data) {
     alert(data.registrationId);
});

push.on('notification', function(data) {
    // data.message,
    // data.title,
    // data.count,
    // data.sound,
    // data.image,
    // data.additionalData
});

push.on('error', function(e) {
    // e.message
});

**Comment by nnzfly** [comment]
same issue, I test different ios version, all version more than ios 10.0.0 have this issue.

**Comment by macdonst** [comment]
@js12690 @nnzfly what version of cordova-ios are you using?

**Comment by nnzfly** [comment]
@macdonst <preference name="cordova " value="5.4.0"/>, I use phonegap online build.
 <plugin name="phonegap-plugin-push" spec="~1.8.4"  source="npm">
        <param name="SENDER_ID" value="84080317431" />
    </plugin>

**Comment by nnzfly** [comment]
@macdonst `<preference name="cordova " value="5.4.0"/>`
` <plugin name="phonegap-plugin-push" spec="~1.8.4"  source="npm">
        <param name="SENDER_ID" value="84080317431" />
    </plugin>`

**Comment by js12690** [comment]
@macdonst I am using 4.3.0 version of cordova-ios and cli-6.4.0 for phonegap build

Please help me as soon as possible

**Comment by omhybrid** [comment]
i have same issue

error :  no valid aps environment entitlement string found for application

**Comment by ef33zy** [comment]
@nnzfly can you click on the **Log** next to iOS on your apps build page to see if there are any errors from the plugin?
![image](https://cloud.githubusercontent.com/assets/15075449/20498515/5fe5b6fa-b025-11e6-9d2b-4fa960ba3851.png)

**Comment by nnzfly** [comment]
@ef33zy `CompileC build/BAScheduling.build/Release-iphoneos/BAScheduling.build/Objects-normal/armv7/AppDelegate+notification.o BAScheduling/Plugins/phonegap-plugin-push/AppDelegate+notification.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/fp/3wvbbc4n2xxf1dt9bfpqtdd00000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=7.0 -g -fvisibility=hidden -Wno-sign-conversion -iquote /project/build/BAScheduling.build/Release-iphoneos/BAScheduling.build/BAScheduling-generated-files.hmap -I/project/build/BAScheduling.build/Release-iphoneos/BAScheduling.build/BAScheduling-own-target-headers.hmap -I/project/build/BAScheduling.build/Release-iphoneos/BAScheduling.build/BAScheduling-all-target-headers.hmap -iquote /project/build/BAScheduling.build/Release-iphoneos/BAScheduling.build/BAScheduling-project-headers.hmap -I/project/build/include -I/project/build/usr/local/lib/include -I/project/build/UninstalledProducts/include -I/project/build/UninstalledProducts/iphoneos/include -I/project/build -I/project/build/BAScheduling.build/Release-iphoneos/BAScheduling.build/DerivedSources/armv7 -I/project/build/BAScheduling.build/Release-iphoneos/BAScheduling.build/DerivedSources -F/project/build -include /var/folders/fp/3wvbbc4n2xxf1dt9bfpqtdd00000gn/C/com.apple.DeveloperTools/7.1-7B91b/Xcode/SharedPrecompiledHeaders/BAScheduling-Prefix-cdhkzdftnoaeoxbfpjbdetapqgmy/BAScheduling-Prefix.pch -MMD -MT dependencies -MF /project/build/BAScheduling.build/Release-iphoneos/BAScheduling.build/Objects-normal/armv7/AppDelegate+notification.d --serialize-diagnostics /project/build/BAScheduling.build/Release-iphoneos/BAScheduling.build/Objects-normal/armv7/AppDelegate+notification.dia -c /project/BAScheduling/Plugins/phonegap-plugin-push/AppDelegate+notification.m -o /project/build/BAScheduling.build/Release-iphoneos/BAScheduling.build/Objects-normal/armv7/AppDelegate+notification.o
In file included from /project/BAScheduling/Plugins/phonegap-plugin-push/AppDelegate+notification.m:10:
/project/BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.h:32:35: warning: cannot find protocol definition for 'GGLInstanceIDDelegate'
@interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate, GCMReceiverDelegate>
                                  ^
/project/BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.h:30:11: note: protocol 'GGLInstanceIDDelegate' has no definition
@protocol GGLInstanceIDDelegate;
          ^
/project/BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.h:32:58: warning: cannot find protocol definition for 'GCMReceiverDelegate'
@interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate, GCMReceiverDelegate>
                                                         ^
/project/BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.h:31:11: note: protocol 'GCMReceiverDelegate' has no definition
@protocol GCMReceiverDelegate;
          ^
2 warnings generated.

CompileC build/BAScheduling.build/Release-iphoneos/BAScheduling.build/Objects-normal/armv7/PushPlugin.o BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/fp/3wvbbc4n2xxf1dt9bfpqtdd00000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=7.0 -g -fvisibility=hidden -Wno-sign-conversion -iquote /project/build/BAScheduling.build/Release-iphoneos/BAScheduling.build/BAScheduling-generated-files.hmap -I/project/build/BAScheduling.build/Release-iphoneos/BAScheduling.build/BAScheduling-own-target-headers.hmap -I/project/build/BAScheduling.build/Release-iphoneos/BAScheduling.build/BAScheduling-all-target-headers.hmap -iquote /project/build/BAScheduling.build/Release-iphoneos/BAScheduling.build/BAScheduling-project-headers.hmap -I/project/build/include -I/project/build/usr/local/lib/include -I/project/build/UninstalledProducts/include -I/project/build/UninstalledProducts/iphoneos/include -I/project/build -I/project/build/BAScheduling.build/Release-iphoneos/BAScheduling.build/DerivedSources/armv7 -I/project/build/BAScheduling.build/Release-iphoneos/BAScheduling.build/DerivedSources -F/project/build -include /var/folders/fp/3wvbbc4n2xxf1dt9bfpqtdd00000gn/C/com.apple.DeveloperTools/7.1-7B91b/Xcode/SharedPrecompiledHeaders/BAScheduling-Prefix-cdhkzdftnoaeoxbfpjbdetapqgmy/BAScheduling-Prefix.pch -MMD -MT dependencies -MF /project/build/BAScheduling.build/Release-iphoneos/BAScheduling.build/Objects-normal/armv7/PushPlugin.d --serialize-diagnostics /project/build/BAScheduling.build/Release-iphoneos/BAScheduling.build/Objects-normal/armv7/PushPlugin.dia -c /project/BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.m -o /project/build/BAScheduling.build/Release-iphoneos/BAScheduling.build/Objects-normal/armv7/PushPlugin.o
In file included from /project/BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.m:29:
/project/BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.h:32:35: warning: cannot find protocol definition for 'GGLInstanceIDDelegate'
@interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate, GCMReceiverDelegate>
                                  ^
/project/BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.h:30:11: note: protocol 'GGLInstanceIDDelegate' has no definition
@protocol GGLInstanceIDDelegate;
          ^
/project/BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.h:32:58: warning: cannot find protocol definition for 'GCMReceiverDelegate'
@interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate, GCMReceiverDelegate>
                                                         ^
/project/BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.h:31:11: note: protocol 'GCMReceiverDelegate' has no definition
@protocol GCMReceiverDelegate;
          ^
/project/BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.m:86:39: warning: capturing 'self' strongly in this block is likely to lead to a retain cycle [-Warc-retain-cycles]
            [weakSelf failWithMessage:self.callbackId withMsg:@"" withError:error];
                                      ^~~~
/project/BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.m:55:5: note: block will be retained by an object strongly retained by the captured object
    gcmRegistrationHandler = ^(NSString *registrationToken, NSError *error){
    ^~~~~~~~~~~~~~~~~~~~~~
/project/BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.m:602:42: warning: undeclared selector 'userHasRemoteNotificationsEnabled' [-Wundeclared-selector]
    if ([appDelegate respondsToSelector:@selector(userHasRemoteNotificationsEnabled)]) {
                                         ^
/project/BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.m:603:49: warning: undeclared selector 'userHasRemoteNotificationsEnabled' [-Wundeclared-selector]
        enabled = [appDelegate performSelector:@selector(userHasRemoteNotificationsEnabled)];
                                                ^
/project/BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.m:603:17: warning: incompatible pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from 'id' [-Wint-conversion]
        enabled = [appDelegate performSelector:@selector(userHasRemoteNotificationsEnabled)];
                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/project/BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.m:614:9: warning: local declaration of 'callbackId' hides instance variable [-Wshadow-ivar]
    if (callbackId != nil)
        ^
/project/BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.m:617:73: warning: local declaration of 'callbackId' hides instance variable [-Wshadow-ivar]
        [self.commandDelegate sendPluginResult:commandResult callbackId:callbackId];
                                                                        ^
/project/BAScheduling/Plugins/phonegap-plugin-push/PushPlugin.m:636:69: warning: local declaration of 'callbackId' hides instance variable [-Wshadow-ivar]
    [self.commandDelegate sendPluginResult:commandResult callbackId:callbackId];
                                                                    ^
9 warnings generated.`

**Comment by gpiroux** [comment]
I have the same issue with cordova-ios@4.3.1 on iOS 10.1.1 and phonegap-plugin-push@1.8.4
What can I do to help solving this issue ?

**Comment by manuelfc1** [comment]
The same issue is happening to me. on register is not firing at all

**Comment by KnoxArg** [comment]
Same issue. 

I'm using phonegap build

**Comment by Jorij** [comment]
Same problem here.
I'm using PGB which doesn't support 1.9.x, so i cannot upgrade to that.
Is there any solution to get it work with PGB before it starts to supports 1.9.x?

We should be updating some minor issues to our application, but this is preventing us to do it.

**Comment by federicoitollo** [comment]
Did you solve this? It seems I have the same problem. Old plugin is still working fine, new one seems just not firing register event.

**Comment by jdnichollsc** [comment]
@federicoitollo what version of the plugin works? I'm having the same issue with the version *1.8.2*

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
