### ISSUE TITLE
How to configure content-available server side for background notifications on iOS and Android

### ISSUE THREAD

**Issue by bmwertman** [phonegap/phonegap-plugin-push#1389]
### Expected Behaviour
`push.on('notification')` callback gets ran in background for both iOS and Android

### Actual Behaviour
`push.on('notification')` callback only gets ran when initiating a push notification from iOS that is received on Android but not when the push is initiated on Android and received on iOS.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Actual iOS 10.1.1
Build target 8

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iphone 5
Oneplus One
Nexus 5

#### Cordova CLI version and cordova platform version

    cordova --version                          6.4
    cordova platform version android           6.1
    cordova platform version ios           4.3

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.9.0

#### Sample Code that illustrates the problem
node server
```
router.post('/', jsonParser, function(req, res){
  var payload;
  if(req.body.platform === "Android"){
    payload = {
      priority: "high",
      data: {
              title: req.body.sender_name,
              body: req.body.message,
              state: req.body.state,
              roomId: req.body.roomId,
              sender_imgUrl: req.body.sender_imgURL,
              "content-available": "1"
            }
    }
  } else {
    payload = {
      aps: {
        "content-available": 1
      },
      priority: 10, 
      notification: {
        title: req.body.sender_name,
        body: req.body.message
      },
      data: {
        state: req.body.state,
        roomId: req.body.roomId,
        sender_imgUrl: req.body.sender_imgURL
      }
    }
  }
  var message = new gcm.Message(payload);
  sender.send(message, { topic: req.body.topic }, function(err, response){
    if(err){
      res.status(500).json({ error: err });
    } else {
      res.status(200).json({ response: 'Push notification sent' });
    }
  });
});
```

**Comment by macdonst** [comment]
@bmwertman please try this for the payload when you send to iOS:

```
payload = {
      "content_available": true,
      priority: 10, 
      notification: {
        title: req.body.sender_name,
        body: req.body.message
      },
      data: {
        state: req.body.state,
        roomId: req.body.roomId,
        sender_imgUrl: req.body.sender_imgURL
      }
    }
```

the GCM code from Google requires the key in a different location, name and format as what I require in the plugin.

**Comment by bmwertman** [comment]
@macdonst that did not work. The closest thing I've gotten to desired behavior is this;

```
 if(req.body.platform === "Android"){
    payload = {
      priority: "high",
      data: {
              title: req.body.sender_name,
              body: req.body.message,
              state: req.body.state,
              roomId: req.body.roomId,
              sender_imgUrl: req.body.sender_imgURL,
              contentAvailable: "1"
            }
    }
  } else {
    payload = {
      content_available: true, 
      priority: 10,
      notification: {
        title: req.body.sender_name,
        body: req.body.message
      },
      data: {
        state: req.body.state,
        roomId: req.body.roomId,
        sender_imgUrl: req.body.sender_imgURL
      }
    }
  }
```
Which I grabbed from @bardu on the issue posted [here](https://github.com/phonegap/phonegap-plugin-push/issues/1266).
With this payload I have to press the send button several times on the iOS app or it sends nothing. Then I receive two to three push notifications on the Android app for the same message. But when the notification is selected the app opens from the background and runs my `on('notification'` callback that opens the correct chat room.

When sending from Android to iOS one click of the send suffices but no push notification is received on the iOS device. But when I click the iOS app's launch icon it opens the app then transitions to the correct chat room like the `on('notification'` callback got ran.

**Comment by macdonst** [comment]
@bmwertman are you able to run the app from Xcode to see what logs are captured when the push arrives?

**Comment by bmwertman** [comment]
I don't know how much this helps. But here is a screenshot of the Xcode log. 

I had tried to send a bunch of push notifications to the iOS device from my Android and the notification wasn't showing. And when I would open the app from the launch icon it wasn't transitioning to the chat room from the landing view like it was when I opened this issue. 

But I came back several hours later and the logs below show `didReceiveNotification with fetchCompletionHandler` and `Notification received` in several places. 9:30 would have been around the time I was sending them. But None of the notifications were in the tray.

![screen shot 2016-11-22 at 1 00 16 pm](https://cloud.githubusercontent.com/assets/2573903/20535834/86444ec6-b0b4-11e6-8fc7-0daf24d295bf.png)

**Comment by bmwertman** [comment]
I'm closing this. I found that the issue was related to a conditional I had set on my Node server.

I was checking whether the notification was sent **FROM** an Android or iOS device and formatting the JSON object being sent to GCM accordingly. 

When what I needed to do was to send formatted JSON for both Android and iOS because I had no way of knowing which device type I was sending a notification to.

**Comment by ef33zy** [comment]
Hi @bmwertman,

You can use the [cordova device plugin](https://github.com/apache/cordova-plugin-device#deviceplatform) to determine the device platform. I currently use this to detect the device so I can send the notification in the right format.

**Comment by bmwertman** [comment]
Hi @ef33zy,

The JSON format matters for the device that is receiving the notification. If I am on an iOS device and I send a chat message to someone I don't know what type of device they have. Are you doing some type of check for each message at the server redirecting to GCM?

Unless I'm missing something I don't see any drawback to sending both JSON formats out with each chat message initiated. then topic registrations can sort out what type of device the recipient has, right?

It seems to be working this way.
