### ISSUE TITLE
Failed to install 'phonegap-plugin-push':undefined

### ISSUE THREAD

**Issue by sinedied** [phonegap/phonegap-plugin-push#1391]
### Expected Behaviour

Plugin v1.0.9 install correctly.

### Actual Behaviour

An error `Failed to install 'phonegap-plugin-push':undefined` is generated when trying to add or restore platform. The complete related error log:
```
Failed to install 'phonegap-plugin-push':undefined
Error: The CocoaPods repo has not been synced yet, this will take a long time (approximately 500MB as of Sept 2016). Please run `pod setup` first to sync the repo.
```

### Reproduce Scenario (including but not limited to)

`cordova prepare` (when trying to restore from config.xml)
or simply `cordova platform add ios`

The same project install works as expected on another machine with the same env, but with OSX El Capitan instead of Sierra.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Cordova Android: 6.0.0
Cordova iOS: 4.3.0

#### Cordova CLI version and cordova platform version

Cordova CLI: 6.4.0
CocoaPods: 1.1.1
OS: Sierra 10.12.1
Node: 6.9.1
NPM: 3.10.9

#### Plugin version

1.9.0

#### Logs with `--verbose`

```sh
Installing "phonegap-plugin-push" for ios
Running command: /Users/facilitylogbook/build-agent/_work/5/s/platforms/ios/cordova/version 
Command finished with error code 0: /Users/facilitylogbook/build-agent/_work/5/s/platforms/ios/cordova/version 
Finding scripts for "before_plugin_install" hook from plugin phonegap-plugin-push on ios platform only.
No scripts found for hook "before_plugin_install".
Install start for "phonegap-plugin-push" on ios.
Beginning processing of action stack for ios project...
Action stack processing complete.
Adding pods since the plugin contained <framework>(s) with type="podspec"
pods.json: The file at /Users/facilitylogbook/build-agent/_work/5/s/platforms/ios/pods.json does not exist.
Creating new pods.json in platforms/ios
Wrote to pods.json.
Podfile: The file at /Users/facilitylogbook/build-agent/_work/5/s/platforms/ios/Podfile does not exist.
Creating new Podfile in platforms/ios
Wrote to Podfile.
Set pods.json for `GoogleCloudMessaging`
Added pod line for `GoogleCloudMessaging`
Set pods.json for `GGLInstanceID`
Added pod line for `GGLInstanceID`
Wrote to pods.json.
Wrote to Podfile.
Running `pod install` (to install plugins)
Failed to install 'phonegap-plugin-push':undefined
Error: The CocoaPods repo has not been synced yet, this will take a long time (approximately 500MB as of Sept 2016). Please run `pod setup` first to sync the repo.
```

**Comment by jcesarmobile** [comment]
Do you have CocoaPods installed?
If you have it, do you have at least 1.0.0 version?
can you type on your terminal, `pod repo update`?

**Comment by sinedied** [comment]
Yes it is installed.

I solved the issue, I had to run `pod setup` (which took quite a long time) before trying to add platform. Maybe this should be noted in the preqequisites, as installing cocoapods does not necessary trigger the `pod setup` command beforehand.

**Comment by pallaviMN** [comment]
@sinedied  @jcesarmobile , can you please tell the solution to this. I am working on ionic project. 

1)How to install cocoapods & is there anything we need to create podfile in project?
2)How much time it takes for pod setup?

Regards
Pallavi M N

**Comment by jcesarmobile** [comment]
To install CocoaPods read
https://guides.cocoapods.org/using/getting-started.html

You don't have to create a Podfile, cordova will do it and will add the Pods the plugin want to use.

About the time, I don't know exactly
