### ISSUE TITLE
push.on('registration', callback) not firing iOS 

### ISSUE THREAD

**Issue by omhybrid** [phonegap/phonegap-plugin-push#1392]
use ionic package service for ios build 

push.on('registration', callback) not firing iOS 

 push.on('error', function(data) {   }); ==> error responce " no valid aps environment entitlement string found for application"

var pushNot = PushNotification.init( {android: {senderID: "462756420685",sound:true},ios: {
									alert: true,
									badge: true,
									sound: true
							}});
			
			pushNot.on('registration', function(data) {
			
		                    alert(data.registrationId):
			
			});
			
			 pushNot.on('error', function(data) {
                   alert('ERROR ' + data);
               });
		
			pushNot.on('notification', function(data) {
			
			});

 cordova CLI: 6.4.0
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.1

**Comment by macdonst** [comment]
@omhybrid this doesn't help me at all. Have you tried asking at the Ionic forums?

**Comment by codeHatcher** [comment]
did you add the push notification entitlement to your app in xcode? I had a similar problem (not with ionic) and that's what solved it for me

**Comment by ericb** [comment]
@omhybrid as @codeHatcher suggested, make sure you've enabled the [Push Notifications](http://docs.ionic.io/services/profiles/#enabling-push) ability in Xcode for your provision profile.
