### ISSUE TITLE
Picture Message :

### ISSUE THREAD

**Issue by natanraj** [phonegap/phonegap-plugin-push#1393]
### Expected Behaviour
Trying to follow example for Picture message. Below is my server code.

```
data: {
        my_key:'mykey'
    },
    notification: {
        title: 'Hey Friend',
        body: 'my Dude',
        sound: "default",
        style: "picture",
        picture: 'https://dl.dropboxusercontent.com/u/887989/antshot.png',
        summaryText:'Hi me..'
    }
```

### Actual Behaviour
Notification is received at device, but the picture never comes. May I know what is missing
### Reproduce Scenario (including but not limited to)
i am using fcm-push in node.js.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Xiomi
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.8.2

#### Sample Push Data Payload

```
data: {
        my_key:'mykey'
    },
    notification: {
        title: 'Hey Friend',
        body: 'my Dude',
        sound: "default",
        style: "picture",
        picture: 'https://dl.dropboxusercontent.com/u/887989/antshot.png',
        summaryText:'Hi me..'
    }
```

**Comment by macdonst** [comment]
@natanraj you are sending the payload wrong. It should all be in `data` as documented here: 
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#picture-messages

For instance:

```
data: {
        my_key:'mykey'
        title: 'Hey Friend',
        body: 'my Dude',
        sound: "default",
        style: "picture",
        picture: 'https://dl.dropboxusercontent.com/u/887989/antshot.png',
        summaryText:'Hi me..'
    }
```

**Comment by natanraj** [comment]
@macdonst : i tried that as well.

collapse_key: '1', 
    data: {
        title:'mykey',
        "force-start": 1,
        style: "picture",
        picture: 'https://dl.dropboxusercontent.com/u/887989/antshot.png',
        summaryText:'Hi me..',
        body: 'my Dude'
    }
Am i overcomplicating here ?

**Comment by macdonst** [comment]
@natanraj did you pull down on the notification to reveal the picture?

**Comment by natanraj** [comment]
I couldn't pull down the notification on this. Is it something to do with Xiomi ? I could only click.
would i have to do something on the init() method ?

**Comment by macdonst** [comment]
@natanraj can you run `adb logcat | grep PushPlugin` and send your message to the device so I can see the logs?

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
