### ISSUE TITLE
Plugin always undefined with Sencha Touch 2.4.2

### ISSUE THREAD

**Issue by AntoniosFesenmeier** [phonegap/phonegap-plugin-push#1395]
### Expected Behaviour
on('notification') should be called if app got closed and the plugin get initialized after/while the onDeviceReady-Event

### Actual Behaviour
Actually i can receive push messages itselfs all the time but the events didn't get fired after i closed the app because the plugin can't be initialized in my launch method of sencha touch's app.js (TypeReference Error undefined). If i initialize the plugin at another screen/workflow the plugin can be initialized.

### Reproduce Scenario (including but not limited to)
Just create a new Sencha Touch 2.4.2 Application and try to initialize the plugin in launch method of app.js.  onDeviceReady-Handler already got fired (https://www.sencha.com/forum/showthread.php?302354-Handling-deviceready-in-controller)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4+ and iOS 9+

#### Cordova CLI version and cordova platform version

    cordova --version                                              #6.2.0
    cordova platform version android                     #4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # 1.8.4

#### Some things i've tried so far

- phonegap plugin add phonegap-plugin-push --variable SENDER_ID="XXXXXXX"
- load push.js directly over index.html
- double checked cordova.js and cordova_plugins.js
- create new empty project and try to initialize the plugin
- initialize plugin while onDeviceReady handler in sencha index.js	
- window.plugins.PushNotification || window.plugins.pushNotification 
- update all android libraries

Would be nice if anyone could give an adivce how to solve this problem ;)

**Comment by macdonst** [comment]
@AntoniosFesenmeier without seeing any of your code it really sounds like you are not waiting for `deviceready` to call `init` of the push plugin.

**Comment by AntoniosFesenmeier** [comment]
@macdonst sencha say's that they capture the onDeviceReady-event and that the launch-method of the app.js only gets fired after onDeviceReady. So my approach was to init the plugin there: 
```
 launch : function() {
        var push = PushNotification.init({
                "android": {
                    "senderID": "XXXXXXX384",
                    "forceShow": "true"
                },
                "browser": {}
          });

        this.setAppTheme();           
        var loadingCtrl = BSA.app.getController("LoadingCtrl");
        loadingCtrl.askGatewayIfCompatible();
    },
```
Result of this solution is an undefined plugin... then i tried to capture the onDeviceReady-event directly in the index.html of my application

```
<!DOCTYPE HTML>
<html manifest="" lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' 'unsafe-eval'; img-src * data: 'unsafe-inline' 'unsafe-eval'; font-src * data: 'unsafe-inline' 'unsafe-eval'" >
    <title>BSA</title>    
    <style type="text/css">    
        html, body {
            height: 100%;    
            background-color: /*#1985D0*/ #222;
        }

    </style>
    <script id="microloader" type="text/javascript" src="touch/microloader/development.js"></script>
    <script id="base64" type="text/javascript" src="base64.js"></script>
     
    <script type="text/javascript">
		document.addEventListener("deviceready", function(){
                    alert('onDeviceReady! try initialize plugin');
                    var push = PushNotification.init({
                         "android": {
                             "senderID": "XXXXXXX384",
                             "forceShow": "true"
                          },
                          "browser": {}
                    });
		});
    </script>
    <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=true"></script>
</head>
<body>
    <div id="appLoadingIndicator">
        <div></div>
        <div></div>
        <div></div>
    </div>
</body>
</html>
```
```
 launch : function() {
        document.addEventListener('deviceReady', this.deviceReady, false);
        this.setAppTheme();           
        var loadingCtrl = BSA.app.getController("LoadingCtrl");
        loadingCtrl.askGatewayIfCompatible();
    },

 deviceReady: function () {
     var push = PushNotification.init({
                "android": {
                    "senderID": "XXXXXXX384",
                    "forceShow": "true"
                },
                "browser": {}
          });
 }, 
```
With the second and third approach the deviceReady-event never gets catpured... 

Now i've got it running, but dont understand why ;-) the trick was just to change the order of the function declarations of deviceReady and the launch.
