### ISSUE TITLE
Branch cleanup

### ISSUE THREAD

**Issue by fredgalvao** [phonegap/phonegap-plugin-push#1397]
### Expected Behaviour

Clean and consise branch timeline/tree.

### Actual Behaviour

We have a ton of branches that outlived their yet-to-be-seen importance.

#### Steps to Reproduce 

Click [here](https://github.com/phonegap/phonegap-plugin-push/branches/all)

Shall we do a cleanup on those branches?, that:

#### have already been merged

- [x] [raghav/toast_Capable](https://github.com/phonegap/phonegap-plugin-push/tree/raghav/toast_Capable)
- [x] [raghav/background_notifications](https://github.com/phonegap/phonegap-plugin-push/tree/raghav/background_notifications)
  - This has been merged but there is one leftover commit: https://github.com/phonegap/phonegap-plugin-push/commit/d620969dcf1a534378a246c3eef61a292c390f69
- [x] [raghav/doclaunch](https://github.com/phonegap/phonegap-plugin-push/tree/raghav/doclaunch)

#### have no diff `from` _master_ (most of them have diff `to` _master_, as they're outdated)

- [ ] [blackberry](https://github.com/phonegap/phonegap-plugin-push/tree/blackberry)
- [x] [icons](https://github.com/phonegap/phonegap-plugin-push/tree/icons)
- [x] [issue230](https://github.com/phonegap/phonegap-plugin-push/tree/issue230) #230
- [x] [issue299](https://github.com/phonegap/phonegap-plugin-push/tree/issue299) #299
- [x] [issue79](https://github.com/phonegap/phonegap-plugin-push/tree/issue79) #79
- [x] [v1.7.x](https://github.com/phonegap/phonegap-plugin-push/tree/v1.7.x)
- [x] [issue683](https://github.com/phonegap/phonegap-plugin-push/tree/issue683) #683
- [ ] [v1.9.x](https://github.com/phonegap/phonegap-plugin-push/tree/v1.9.x)

#### have a diff `from` _master_ but that diff has already been cherry-picked to _master_

- [x] [issue144](https://github.com/phonegap/phonegap-plugin-push/tree/issue144) #144

#### who knows

- [ ] [cocoapod_support](https://github.com/phonegap/phonegap-plugin-push/tree/cocoapod_support)
- [x] [v1.5.x-pod](https://github.com/phonegap/phonegap-plugin-push/tree/v1.5.x-pod)
  - This superseeds/contains the `cocoapod_support` branch.
- [x] [v1.6.x](https://github.com/phonegap/phonegap-plugin-push/tree/v1.6.x) https://github.com/phonegap/phonegap-plugin-push/pull/671
  - This seems to be someone trying to merge a branch into master that had already been merged (the PR was closed, but the commits are unlinked)
- [ ] [amazon](https://github.com/phonegap/phonegap-plugin-push/tree/amazon)
  - This branch has some nice ideas of separating concepts and abstracting our code that would allow people (like myself) to adapt the plugin easily to work with third-party providers, like `Pushy.me` or Amazon. IMO this should be considered and not deleted right away. https://github.com/phonegap/phonegap-plugin-push/pull/822
- [x] [background](https://github.com/phonegap/phonegap-plugin-push/tree/raghav/background)
  - I didn't dig deep, but this seems like something that has been superseeded by a more recent version.
- [ ] [es6](https://github.com/phonegap/phonegap-plugin-push/tree/es6)
  - I want this to be true (I'd prefer Typescript, but hey, ES6 is cool too).
- [x] [browser](https://github.com/phonegap/phonegap-plugin-push/tree/browser)
  - Hasn't this been done on master too?
- [ ] [v2.0.x](https://github.com/phonegap/phonegap-plugin-push/tree/v2.0.x)
  - Is superseeded by the new `v2.0.x-rebase`
- [x] [windows](https://github.com/phonegap/phonegap-plugin-push/tree/windows) https://github.com/phonegap/phonegap-plugin-push/pull/1087
  - Code is superseeded by what's already on `master`

**Comment by macdonst** [comment]
@fredgalvao all of the branches I've put checkmarks beside can be cleaned up. I want to leave the following around:

* `v1.9.x` - may end up becoming a legacy support branch for folks not moving to FCM.
* `cocoapod_support` - Holly was looking at turning this plugin into a CocoaPod so this will be a reminder of where she left off.
* `amazon` - legacy but still interesting
* `es6` - yup, plan on doing this once `v2.0.x` is out.
* `v2.0.x` - once @jcesarmobile and I straighten out the rebase I'm going to push `v2.0.x-rebase` to `v2.0.x` and delete `v2.0.x-rebase`.

Feel free to start cleaning and thanks for supporting this project!

**Comment by fredgalvao** [comment]
Should I leave `v1.5.x-prod` alive and delete `cocoapod-support` instead? The former works on top of the later, so if we want to preserve all work done on the topic, `v1.5.x-prod` is the one to preserve imo.

**Comment by macdonst** [comment]
@fredgalvao nah, I think the work will need to be restarted so just having Holly's commit in `cocoapod-support` will be enough of a hint to get her going.

**Comment by fredgalvao** [comment]
I forgot the [windows](https://github.com/phonegap/phonegap-plugin-push/tree/windows) (https://github.com/phonegap/phonegap-plugin-push/pull/1087) on the way. Seems outdated to me. Removable?

**Comment by fredgalvao** [comment]
Yep, just verified and the code on that `windows` branch is already on master. I'm adding it to the OP for reference and deleting it.

**Comment by fredgalvao** [comment]
Seems good enough for now! (now to create a few new branches/issues for crazy ideas I have for the api...)

**Comment by macdonst** [comment]
@fredgalvao at some point the two of us and @jcesarmobile should get together for a roadmap planning session. Rough schedule is:

* FCM support
* ES2015 API changes
* W3C Push API implementation (tricky without service worker support).

**Comment by fredgalvao** [comment]
@macdonst  I'd love to have a chance at sharing my opinion on some of those topics.
