### ISSUE TITLE
How i can set icons for push notifications in status bar and push view in android

### ISSUE THREAD

**Issue by MikeBazhenov** [phonegap/phonegap-plugin-push#14]
Hi!

How?:)

**Comment by macdonst** [comment]
@MikeBazhenov currently the push plugin on Android just uses the application icon.

**Comment by MikeBazhenov** [comment]
@macdonst why don`t add simple resource for status bar icon and push message?

**Comment by macdonst** [comment]
@MikeBazhenov fixed as part of Issue #20, check out the new information in the README.

**Comment by ruben82** [comment]
Hi there.
I've the same problem. I put a icon to res/drawable called spiaggia.png. In my Android object I put
 `android: {
        senderID: '',
        icon: 'spiaggia',
        iconColor: 'red',
      },`

But App icon is showed, so I see icon notification bar all blank. Can someone help me pls?

**Comment by matzhang2019** [comment]
I think you are very strong about head
