### ISSUE TITLE
Version 1.9.0 on PGB not working

### ISSUE THREAD

**Issue by MBuchalik** [phonegap/phonegap-plugin-push#1400]
### Expected Behaviour
When updating from 1.8.4 to 1.9.0, PushNotification should still be available. Furthermore, the permissions needed for the push plugin should stay the same.
### Actual Behaviour
When building with PGB (cli-6.4.0), version 1.9.0 doesn't add the necessary permissions. The variable PushNotification is undefined after deviceready.
### Reproduce Scenario (including but not limited to)
I have created a small test application to use on PGB.
The config.xml: http://pastebin.com/qPXvJCSM
The index.html: http://pastebin.com/CZv8tusx

I have created almost the same application again, but this time with spec="1.8.4".

When installing the 1.8.4 version, it tells me that it needs a few permissions (full network access, receive data from internet, view network connections, control vibration, prevent phone from sleeping, com.sec.android.provider.badge.permission.READ, com.sec.android.provider.badge.permission.WRITE).
The 1.9.0 version on the other hand only needs "full network access" and "view network connections".

When starting the application, the 1.8.4 alerts "onregistration". The 1.9.0 version alerts "ReferenceError: PushNotification is not defined".

Is version 1.9.0 not compatible with PGB?

#### Steps to Reproduce 
Create one PGB appliaction with the code I provided and one with plugin-push version 1.8.4. When launching the 1.9.0 one, you will get the alert saying "ReferenceError".
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0.2
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung
#### Cordova CLI version and cordova platform version

    PGB with cli-6.4.0

#### Plugin version

    1.9.0

#### Sample Code that illustrates the problem
(see above)
#### Logs taken while reproducing problem
N/A

**Comment by JohnMcAvinue** [comment]
Yes I am experiencing this as well. I'm pretty sure it did work last week but now even though PGB builds correctly and the plugin is listed in the plugins list, there's no push plugin in the plugins folder when I go to debug on the device.

**Comment by ef33zy** [comment]
I had the same issue, [this post in Adobe PGB forum](https://forums.adobe.com/thread/2231446) was also raised on the same issue.

1.9.0 requires cordova 6.4.0, but for now unfortunately PGB doesn't have 6.4.0.

As @macdonst mentioned [in this post](https://github.com/phonegap/phonegap-plugin-push/issues/1356#issuecomment-259698247), using the 1.8.4 is the way out for now, that's what I have done and it works.

**Comment by macdonst** [comment]
Yeah, we'll need to wait until PGB updates their servers. Added a note in docs for now.

**Comment by MBuchalik** [comment]
Ok, so we will just have to wait for it. Thanks for your reply.
It's still pretty interesting that PGB supports a version called "cli-6.4.0" but that's different from cordova 6.4.0...
