### ISSUE TITLE
Automatic xcode configuration throught plugin.xml(config.xml) Add pushNotification capability

### ISSUE THREAD

**Issue by Lestt** [phonegap/phonegap-plugin-push#1401]
Hi all,

Is there a way to set all the plugin configuration (not talking about SENDER_ID or GOOGLE_APP_ID) through the config.xml.
I'am using ionicV1, and plugins like phonegap-plugin-push are described in config.xml. I wanted to build my app for iOs, but i don't have a mac. So ionic provide a command with their client, **ionic package build ios** (wich use **cordova prepare** command before building), where you pass your developer account and they build the app for you.
Unfortunately, i have no interaction with xcode, so i can't set on the **Push Notification** capability for the build. Is there a way to do it, without xcode (maybe in a plist file ?).
Moreover, i try to use push notification to iOs with GCM, and i got this error (this way it was with a correct iOs build, error was find in xcode console):

According to this [post](https://github.com/phonegap/phonegap-plugin-push/issues/440), the .plist information has been added to the project , but the app still doesn't ask the right to receive notification.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
