### ISSUE TITLE
force-start:1 brings a killed application to foreground, not background.

### ISSUE THREAD

**Issue by TrevorPage** [phonegap/phonegap-plugin-push#1402]
### Expected Behaviour
According to the documentation: 
> If you add `force-start:1` to the data payload the application will be restarted in background even if it was force closed.

### Actual Behaviour
Initial condition is that the application has been killed so is not running. A notification is received with `force-start:1`. My application is started and the `.on('notification'...` handler is called (good) and the application comes into the foreground (very undesired). 

#### Steps to Reproduce 
Kill application.
Send push notification without a title or content, and with `force-start:1`

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
HTC 10

#### Cordova CLI version and cordova platform version
cordova 6.4.0
cordova-android 6.0.0

#### Plugin version
1.9.0

#### Sample Push Data Payload

```
{
    "registration_ids": [ ...  ],
    "data":
    {
        "content-available":1,
        "force-start":1,
        ...
    }
}
```

**Comment by macdonst** [comment]
@TrevorPage I don't have a HTC 10 so it's hard for me to debug without logs. Can you run `adb logcat | grep PushPlugin` to capture them for me?

**Comment by fredgalvao** [comment]
Also, can you share what's inside your main activity java class?

**Comment by TrevorPage** [comment]
Thanks ever so for responding so quickly! Apologies for lack of log. Here it is. I will also post the contents of the Activity shortly. 

This log is from the application being newly started, with one notification then being received. (The XXX's are mine in place of potentially sensitive bits.) I do notice straight away that "foreground" appears in a few places.

`11-23 20:22:40.762 28444 28499 V PushPlugin: execute: action=init
11-23 20:22:40.764 28444 28503 V PushPlugin: execute: data=[{"android":{"senderID":"XXXXXXXX"},"ios":{"badge":true,"sound":true,"alert":true}}]
11-23 20:22:40.764 28444 28503 V PushPlugin: execute: jo={"senderID":"XXXXXXXX"}
11-23 20:22:40.764 28444 28503 V PushPlugin: execute: senderID=XXXXXXXX
11-23 20:22:40.769 28444 28503 V PushPlugin: onRegistered: {"registrationId":"XXXXXXXX"}
11-23 20:22:40.769 28444 28503 D PushPlugin: no icon option
11-23 20:22:40.769 28444 28503 D PushPlugin: no iconColor option
11-23 20:22:50.919 28444 28748 D PushPlugin_GCMIntentService: onMessage - from: XXXXXXXX
11-23 20:22:50.919 28444 28748 D PushPlugin_GCMIntentService: normalize extras
11-23 20:22:50.919 28444 28748 D PushPlugin_GCMIntentService: key = content-available
11-23 20:22:50.919 28444 28748 D PushPlugin_GCMIntentService: replace key content-available with content-available
11-23 20:22:50.919 28444 28748 D PushPlugin_GCMIntentService: key = google.sent_time
11-23 20:22:50.920 28444 28748 D PushPlugin_GCMIntentService: replace key google.sent_time with google.sent_time
11-23 20:22:50.920 28444 28748 D PushPlugin_GCMIntentService: key = system-name
11-23 20:22:50.920 28444 28748 D PushPlugin_GCMIntentService: replace key system-name with system-name
11-23 20:22:50.920 28444 28748 D PushPlugin_GCMIntentService: key = force-start
11-23 20:22:50.920 28444 28748 D PushPlugin_GCMIntentService: replace key force-start with force-start
11-23 20:22:50.920 28444 28748 D PushPlugin_GCMIntentService: key = mac
11-23 20:22:50.920 28444 28748 D PushPlugin_GCMIntentService: replace key mac with mac
11-23 20:22:50.920 28444 28748 D PushPlugin_GCMIntentService: key = event
11-23 20:22:50.920 28444 28748 D PushPlugin_GCMIntentService: replace key event with event
11-23 20:22:50.920 28444 28748 D PushPlugin_GCMIntentService: key = google.message_id
11-23 20:22:50.920 28444 28748 D PushPlugin_GCMIntentService: replace key google.message_id with google.message_id
11-23 20:22:50.920 28444 28748 D PushPlugin_GCMIntentService: key = collapse_key
11-23 20:22:50.920 28444 28748 D PushPlugin_GCMIntentService: replace key collapse_key with collapse_key
11-23 20:22:50.920 28444 28748 D PushPlugin_GCMIntentService: key = affects-XXXXXXXX
11-23 20:22:50.920 28444 28748 D PushPlugin_GCMIntentService: replace key affects-XXXXXXXX with affects-XXXXXXXX
11-23 20:22:50.920 28444 28748 D PushPlugin_GCMIntentService: foreground
11-23 20:22:50.920 28444 28748 D PushPlugin: convert extras to json
11-23 20:22:50.920 28444 28748 D PushPlugin: key = content-available
11-23 20:22:50.920 28444 28748 D PushPlugin: key = google.sent_time
11-23 20:22:50.920 28444 28748 D PushPlugin: key = system-name
11-23 20:22:50.920 28444 28748 D PushPlugin: key = force-start
11-23 20:22:50.920 28444 28748 D PushPlugin: key = mac
11-23 20:22:50.920 28444 28748 D PushPlugin: key = event
11-23 20:22:50.920 28444 28748 D PushPlugin: key = google.message_id
11-23 20:22:50.920 28444 28748 D PushPlugin: key = coldstart
11-23 20:22:50.920 28444 28748 D PushPlugin: key = collapse_key
11-23 20:22:50.920 28444 28748 D PushPlugin: key = foreground
11-23 20:22:50.920 28444 28748 D PushPlugin: key = affects-XXXXXXXX
11-23 20:22:50.920 28444 28748 V PushPlugin: extrasToJSON: {"additionalData":{"content-available":"1","system-name":"XXXXXXXX","force-start":"1","mac":"XXXXXXXX","event":"XXXXXXXX","google.message_id":"XXXXXXXX","coldstart":false,"collapse_key":"do_not_collapse","foreground":true,"affects-XXXXXXXX":"0"}}`

**Comment by TrevorPage** [comment]
Regarding the main Activity class (within our app's package folder), all it does is:

`public class MainActivity extends CordovaActivity
{
    @Override
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        // Set by <content src="index.html" /> in config.xml
        loadUrl(launchUrl);
    }
}`

I develop natively on Android, so if there's any further poking about I can do to help, please let me know.

**Comment by macdonst** [comment]
@TrevorPage well that's why it doesn't work. The main activity class in cordova-android 6 and higher adds some new stuff to make force-start work.

```
public class MainActivity extends CordovaActivity
{
    @Override
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);

        // enable Cordova apps to be started in the background
        Bundle extras = getIntent().getExtras();
        if (extras != null && extras.getBoolean("cdvStartInBackground", false)) {
            moveTaskToBack(true);
        }

        // Set by <content src="index.html" /> in config.xml
        loadUrl(launchUrl);
    }
}
```

**Comment by TrevorPage** [comment]
I have noticed that the `PushHandlerActivity` places `START_IN_BACKGROUND` flag into the Intent to start the main `Activity`. Is the default `Activity` somehow supposed to be overridden to handle it?

**Comment by TrevorPage** [comment]
Ah, so I was on the right track! OK. Fantastic. Well, I wonder if this is because I upgraded cordova-android but didn't completely rebuild the platform? I'll delete the platform now and see what happens.

**Comment by macdonst** [comment]
kk, let me know so I can properly upgrade the docs.

**Comment by TrevorPage** [comment]
Deleted the Android platform and did `ionic run android -c`, allowing it to rebuild the platform again. The `MainActivity` is still as before. I have double checked the following:

cordova --version   6.4.0
cordova platform version android   6.0.0

I've good experience with native Android development but Cordova/Ionic is relatively new to me. I need to try to understand now why my platform is apparently using old Java source despite having cordova-android 6.

**Comment by TrevorPage** [comment]
For further info: The platforms.json contains `{ "android":"6.0.0"}`, even after I delete the platform. So, as far as I can see, I really should have the later version of `Activity`. When the platform is reinstalled for me, I admit I don't know where the templates actually come from to create the main `Activity`. I can see that its template is at https://github.com/apache/cordova-android/blob/master/bin/templates/project/Activity.java but I don't know if this is sat on my machine somewhere and copied over or pulled off the network. Perhaps now is time to raise an issue with cordova-android.

**Comment by fredgalvao** [comment]
@TrevorPage Can you create a simple cordova app and check if that receives the updated version?
```
cordova create please please please
cd please
cordova platform add android
cordova prepare
```

**Comment by TrevorPage** [comment]
@fredgalvao OK. I have done that procedure, and confirm that the new simple app *does* receive the updated Activity version.

**Comment by TrevorPage** [comment]
Wait! Sorry - I have checked again in my main project, and actually the `MainActivity` **does** reflect the new version now. So, it seems that completely rebuilding the platform has resolved this. I've no idea why on earth I thought it was the older version when I first looked.

**Comment by TrevorPage** [comment]
So, just to recap:

I believe that at one stage I had the older Activity version despite platforms.json stating 6.0.0. This might have been caused by me upgrading cordova-android (which I did a few days ago) but without deleting and rebuilding the Android platform afterwards.

Deleting and re-installing the platform has given me the new Activity version. (Me stating otherwise an hour ago must have been just down to very tired eyes.)

Furthermore, I have now sent a push notification to the application running on my HTC 10 and it appears that the application is now starting and going to background successfully.

Thanks ever so for the brilliant help. Is it feasible that I've highlighted an upgrade mechanism issue?

**Comment by fredgalvao** [comment]
If you're refering to the `cordova platform update android` mechanism, it has always been ineficient and buggy imo, I don't trust it anymore. Everytime I need to update stuff, I do `remove`/`add` and reverify all changes in the platforms/plugins folders (I keep them under version control).

**Comment by TrevorPage** [comment]
Yep, I was referring to that. I'll close this issue now. Thanks ever so much for your fantastic help!

**Comment by macdonst** [comment]
@TrevorPage I'm re-opening this issue as a reminder to add some lines to the docs. Thanks for having the patience to go through this with us.

**Comment by macdonst** [comment]
@TrevorPage check out this commit and let me know if that makes sense: https://github.com/phonegap/phonegap-plugin-push/commit/256f28fa08da4aab9691d628a3150022b67da02d

**Comment by TrevorPage** [comment]
That makes total sense. To really get the message across you might want to say: "If you find that force-close:1 causes your application to start and immediately come to foreground, then you do NOT have the correct MainActivity.java from cordova-android 6.0.0."

**Comment by VinceOPS** [comment]
Hi guys,

Sorry to revive this thread but I guess something is still going wrong with `force-start`: it keeps running the app in foreground when it has been killed.

It was working perfectly fine with version 1.9.0 but not anymore with version 1.9.2 (Android 5.1 and Android 6.0.1, cordova-android 6.1.0, cordova-cli 6.4.0).

I wonder if it could be related to https://github.com/phonegap/phonegap-plugin-push/commit/dd61ec34c0ca5c3fadf6797a8e192b9343324f68#diff-99eebd9d4588c3386ebd8d4a17fcc617R46. I assume `inline` may be true when it shouldn't. Sorry, I can't do deeper debugging at the present time.
