### ISSUE TITLE
How to stop push notification in the notification drawer when app is opened

### ISSUE THREAD

**Issue by sourav86** [phonegap/phonegap-plugin-push#1404]
I need to stop notification to arrive in notification drawer when app is opened. currently it display notification even app is opened.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
