### ISSUE TITLE
How to stop notification to show in notification drawer when app is opened

### ISSUE THREAD

**Issue by sourav86** [phonegap/phonegap-plugin-push#1405]
**Expected Behaviour**

Notification will only arrive in notification drawer when app will be in background.

**Actual Behaviour**

Notification arrives when app is opened in .on('notification')... handler,

**Platform and Version (eg. Android 5.0 or iOS 9.2.1)**
Android 5.1

**(Android) What device vendor (e.g. Samsung, HTC, Sony...)**

Moto G

**Cordova CLI version and cordova platform version**
cordova 6.3.0

**Plugin version**
1.8.2

**Sample Push Data Payload**

let push = Push.init({
android: {
senderID: "XXXXXXXXX",
"icon": "icon",
"iconColor": "Gray"
},
ios: {
alert: "true",
badge: false,
sound: "true"
},
windows: {}
});

**Comment by macdonst** [comment]
@sourav86 I've never seen this behaviour before. When the app is in the foreground the `on('notificaiton')` event handler should be called but nothing should shop up in the notification shade.

**Comment by sourav86** [comment]
this issue is solved not. I use data.additionalData.foreground == false && data.additionalData.coldstart == true in push.on('notification', (data)...  Now it is working file
