### ISSUE TITLE
Unable to install the plugin

### ISSUE THREAD

**Issue by pallaviMN** [phonegap/phonegap-plugin-push#1409]
Expected - Need to install the plugin

Actual - Unable to install

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.4.0
    cordova platform version iOS          4.3.0

#### Plugin version

    cordova plugin version   # e.g. 1.9.0

I have installed cocoa pods. but still pod file is not created in the xcode project, asking me to do pod set up. Its taking lot of time. Can i install old version of plugin?

**Comment by jcesarmobile** [comment]
You have to wait until pod setup finish.

You can use an old version if you wish
`cordova plugin add phonegap-plugin-push@1.8.4`
