### ISSUE TITLE
Custom icon are not working

### ISSUE THREAD

**Issue by rodriguesgm** [phonegap/phonegap-plugin-push#1411]
I'm using phonegap-plugin-push with Ionic2 and my custom icon for notifications are not working anymore, they are not showing on android bar. It was working some months ago, but when I updated the Ionic2 to RCx, it stop working. This is a related issue with the problem driftyco/ionic#9270.

Does anyone have some clue to help me?

**Comment by macdonst** [comment]
@rodriguesgm you didn't fill in the issue template and this really seems like an Ionic issue, not this plugin.
