### ISSUE TITLE
push.subscribe "not a function" error

### ISSUE THREAD

**Issue by hguldal** [phonegap/phonegap-plugin-push#1412]
when i call the

```
push.subscribe('my-sstopic', function() {
    console.log('ok');
}, function(e) {
    console.log('error:');
    console.log(e);
});
```

on error occured, "push.subscribe not a function"
### Expected Behaviour
       receive spesific topic notifications
### Actual Behaviour
      return error push.subscribe not a function
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
         Browser

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
         Desktop

#### Cordova CLI version and cordova platform version
         cordova version 6.4.0
#### Plugin version
           1.8.4

#### Sample Code that illustrates the problem

 pushNotificationSetup:function () {
            var push = PushNotification.init({
                android: {
                    senderID: "XXXXXXXX"
                },
                browser: {},
                ios: {
                    alert: "true",
                    badge: "true",
                    sound: "true"
                },
                windows: {}
            });

            push.on('registration', function(data) {
                //console.log(data.registrationId);
            });

            push.on('notification', function(data) {
                // data.message,
                // data.title,
                // data.count,
                // data.sound,
                // data.image,
                // data.additionalData
            });

            push.on('error', function(e) {
            });
         
           push.subscribe('foo-bar', function() {
                console.log('Success');
            }, function(e) {
                               console.log('error');
                            console.log(e);
            });

}

**Comment by fredgalvao** [comment]
Please, don't ignore all of those sections on the issue template. They are there to remind you to provide important information, such as versions and logs.

**Comment by macdonst** [comment]
@hguldal I see what is going on. The browser implementation did not add the subscribe/unsubscribe methods.

**Comment by hguldal** [comment]
i think, this state must describe in documentation

**Comment by macdonst** [comment]
@hguldal no, it's a bug I need to fix 😄

**Comment by macdonst** [comment]
@hguldal Okay, I pushed a fix for this. Now subscribe/unsubscribe will always call the success callback provided in the browser platform.
