### ISSUE TITLE
How to set large icon in Android notification tray?

### ISSUE THREAD

**Issue by malwatte** [phonegap/phonegap-plugin-push#1413]
Notification icon in Android notification tray is small. How to make it large?

Plugin version: 1.8.3
Device: Android S5 6.0.1

My init config
```
android: {
                        senderID: senderId,
                        clearNotifications: false,
                        sound: true,
                        vibrate: true
                    }
```

And payload is

```
{ "data": {
        "ticketId": "123",
        "notId": 12,
  		"body": "My test push notification"
        },
     "priority":"high",
      "registration_ids" :["tokens"]
    }
```

Please have a look at below screenshots. Notice that the app icon in notification tray is small.
I want to cover the whole area with the icon.

![screen shot 2016-11-25 at 2 35 01 pm](https://cloud.githubusercontent.com/assets/2534778/20620333/36605c8e-b31f-11e6-9430-993e5948a598.png)
![screen shot 2016-11-25 at 2 35 12 pm](https://cloud.githubusercontent.com/assets/2534778/20620334/3660d754-b31f-11e6-84a2-747c2f092063.png)
![screen shot 2016-11-25 at 2 35 27 pm](https://cloud.githubusercontent.com/assets/2534778/20620335/3664f21c-b31f-11e6-9a19-15925ad7c07c.png)

Thank you

**Comment by macdonst** [comment]
@malwatte well that's not really the way that Android works. When the notification code is using the apps icon it just centers the icon in that lovely grey circle. There is all sorts of info on how to work with icons in your push notification here:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images
