### ISSUE TITLE
from ver 1.9.0 to this one no notifications are recived on phonegap desktop 

### ISSUE THREAD

**Issue by brunoalex** [phonegap/phonegap-plugin-push#1414]
### Expected Behaviour
firebase sends push and android recives even if  app is on bg and on click open app and display full push notification

1.9.0  and this ver dont work

### Actual Behaviour
firebase sends push and android dont recive nothing...in 1.8.0 it works but on click in notification open the app but no alert ...

debug shows Uncaught ReferenceError: PushNotification is not defined(…)

### Reproduce Scenario (including but not limited to)

`<plugin spec="https://github.com/phonegap/phonegap-plugin-push.git#v2.0.x" source="git" />`

firebase and android s6

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung 6.0

#### Cordova CLI version and cordova platform version

phonegap Desktop 

#### Plugin version

  <plugin spec="https://github.com/phonegap/phonegap-plugin-push.git#v2.0.x" source="git" />

**Comment by macdonst** [comment]
@brunoalex what does the payload you send to the app look like?

**Comment by brunoalex** [comment]
Im using firebase console but my app.dont.register i get Uncaught ReferenceError ... it can only register on older versions like 1.8.4 ...i would.use.that but my notifications dont open on app on tap

**Comment by macdonst** [comment]
@brunoalex whelp, the log of the ReferenceError would sure be helpful as well as filling out the rest of the required info.

**Comment by brunoalex** [comment]
hi mac... well theres only that... 

Received Device Ready Event
not.js:37 calling setup push
not.js:41 calling push init
not.js:42 Uncaught ReferenceError: PushNotification is not defined(…)

**Comment by macdonst** [comment]
@brunoalex okay and what version of cordova-android are you using?

**Comment by brunoalex** [comment]
i tried using 1.9.0 and #v2.0.x of the plugin with cli-6.4.0 (4.3.0 / android 6.1.0 / 4.4.3)

**Comment by macdonst** [comment]
@brunoalex and are you building from the command line? Because it seems like there is a failure to add the plugin to the project.

**Comment by brunoalex** [comment]
Other thing i can see is that the plugin isent getting into build ... when i check the Sources on the debug theres no push plugin folder... but if i build with 1.8.4 there is..

**Comment by brunoalex** [comment]
no...ill give the CMd line a try and let u know if it works

**Comment by brunoalex** [comment]
i cant use the cmg line ..some how i get [warning] The command `phonegap local <command>` has been DEPRECATED.
 [warning] The command has been delegated to `phonegap <command>`.
 [warning] The command `phonegap local <command>` will soon be removed.
[phonegap] executing 'cordova plugin add https://github.com/phonegap-build/PushPlugin.git ' ...
Fetching plugin "https://github.com/phonegap-build/PushPlugin.git" via git clone


Error: Failed to fetch plugin https://github.com/phonegap-build/PushPlugin.git via git.
Either there is a connection problems, or plugin spec is incorrect:
	Error: git: Command failed with exit code 1 Error output:
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by macdonst** [comment]
@brunoalex first, ignore the `local` part of the command line. Second, this plugin is not `https://github.com/phonegap-build/PushPlugin.git`. Use this command:

`phonegap plugin add phonegap-plugin-push --variable SENDER_ID=XXXXXXX`

where you replace `XXXXXXXX` with your sender ID.

**Comment by brunoalex** [comment]
ok that worked but... same bug... when geting the notification if i tap on it the app is fired but not the alert ... do u know how can i try to use 2.0.x brunch?  i had tried to phonegap plugin add phonegap-plugin-push#2.0.x --variable SENDER_ID=655844105827 but didnt install

**Comment by macdonst** [comment]
@brunoalex well the v2.0.x branch is under development right now so YMMV on quality until I merge it into master. You won't need SENDER_ID in the v2.0.x branch.

However, I believe I know what your problem is. If you are sending a message via FCM you need to put all of the properties in the `data` part of the payload not the `notification` part. If you put it in the `notification` part the OS will take over and the push plugin will not be able to fire the `on('notification')` event.

**Comment by brunoalex** [comment]
i can set Custom data key and value on FCM but dont know what changes i need to get into my app code... right now i have  ```
push.on('notification', function(data) {
            console.log('notification event');
            navigator.notification.alert(
                data.message,         // message
                null,                 // callback
                data.title,           // title
                'Ok'                  // buttonName
            );
``` and the regular 

```
var push = PushNotification.init({
            "android": {
                "senderID": "xxxxxx"
            },
            "browser": {},
            "ios": {
                "sound": true,
                "vibration": true,
                "badge": true
            },
            "windows": {}
        });
```

**Comment by brunoalex** [comment]
@macdonst  i tried like this but still the same result ...do i need to update any code on my app ?
![screen shot 2016-11-28 at 3 03 46 pm](https://cloud.githubusercontent.com/assets/15779919/20673147/e78afbe6-b57b-11e6-876d-0fb32ad40720.png)

**Comment by brunoalex** [comment]
@macdonst it worked with a php script just sending data
