### ISSUE TITLE
Unable to receive notifications in the latest version 1.9.0

### ISSUE THREAD

**Issue by pallaviMN** [phonegap/phonegap-plugin-push#1417]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.4.0
    cordova platform version android                     # e.g. 4.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.9.0

I have made, push plugin enable even in the "Capablilites" section in xcode, plugin was working fine till last month but after installing cocoapods & update of plugin from 1.8.4 to 1.9.0, i am unable to get notification but where as registration is working fine. Please let me know, if any addtional changes need to be done.

**Comment by fredgalvao** [comment]
Yes, one change that could be done to help is provide the information mentioned in the issue template, like
- logs taken during the tests
- steps to reproduce
- the code on app that initializes the plugin
- the code on your server that sends the notifications
- the actual versions of cordova and its platforms

**Comment by pallaviMN** [comment]
Is there any change i can install old version of plugin with cordova version 6.4.0 & ios version 4.3.0? Or will it take 1.9.0 version by default?

**Comment by pallaviMN** [comment]
*is there any chance - mistyped

**Comment by rajeshvishnani** [comment]
http://stackoverflow.com/questions/41738903/phonegap-push-plugin-ios-doesnt-send-notification-succesfull-device-registrati

I have this issue

**Comment by macdonst** [comment]
Closing as @pallaviMN never responded.

@rajeshvishnani the behaviour you describe is usually, well always, a mis-match between the development and production certificates.
