### ISSUE TITLE
PushNotification is not defined

### ISSUE THREAD

**Issue by Neocortexxx** [phonegap/phonegap-plugin-push#1418]
Hi, 

### Actual Behaviour
I am working on my cordova application with Visual Studio and have some issues with the new push-plugin. The application worked perfect with the old (deprecated) plugin, but nowI want to test on iOS. The compiling for iOS requires the new push-plugin, so I deleted the old one and added the this one. Now I want to check, if the plugin is still working and changed the code to initialize the pushNotifications. My first test on Android wasnt successful, because on application start I got following error:

> "Error: Uncaught ReferenceError: PushNotification is not defined in file:///android_asset/www/js/Plugins/PushMobi.js

In PushMobi.js I use this example-code insinde my device-ready-methode, but it stops on the error I showed above.

`    var push = PushNotification.init({
        "android": { "senderID": "963798XXXXXX" },
         "ios": {"alert": "true", "badge": "true", "sound": "true"}, "windows": {} } );
`

I am using Visual Studio and added the plugin over the config.xml design view for custom plugins via git-url.

#### Platform and Version 
My device is a Huawai Honor 7 (PLK-L01) and runs on Android 6.0. 

#### Cordova CLI version and cordova platform version

    Cordova version: 6.1.1
    Cordova version Android: 5.1.1

#### Plugin version

    Cordova push-plugin version 1.9.0

I read about requiered google-play-services and support-library and installed them over android SDK manager but still no fix of my error.

**Comment by jcesarmobile** [comment]
Version 1.9.0 of the plugin requires Cordova CLI 6.4.0 or greater, so the plugin is not being installed and that's why you get that error.

You have to update the CLI to 6.4.0 and the platform to cordova-android 6.0.0 or greater, or use an older version of the plugin (1.8.4 should work)
