### ISSUE TITLE
Receive notification in Javascript but not in the device

### ISSUE THREAD

**Issue by adantart** [phonegap/phonegap-plugin-push#142]
Hi:

I've installed everything alright. I've got the registrationId, and form a server I send a message ... and the function:
```
notification.push.on('notification', function(data) {            
           // here the data
});
```
is triggered correctly when it's received.

But I don't see the Android notification itself, in the notification bar.

Any idea ?
thank you !

**Comment by macdonst** [comment]
@adantart you should only see the notification in the shade when the app is in the background and it has a message and/or title.
