### ISSUE TITLE
Notification delay caused by icon bitmap timeout

### ISSUE THREAD

**Issue by laagland** [phonegap/phonegap-plugin-push#1421]
Spend some time trying to solve a problem where we had a significant delay in the popup showing up on Android devices, even though the GCMIntentService had incoming data immediately. Eventually found out that the notification icon we were trying to load gave a timeout error, but only after 2/3 minutes. The popup was waiting for the timeout before showing up!

It might be a good idea to put a (configurable?) setConnectTimeout on the HttpURLConnection when retrieving assets for the popup.

What do you think?

**Comment by macdonst** [comment]
@laagland I think that is a great idea.

**Comment by laagland** [comment]
Do you want me to create a pull request for this?

**Comment by macdonst** [comment]
I always welcome PR's
