### ISSUE TITLE
Phonegap plugin push for phonegap build app

### ISSUE THREAD

**Issue by MooUser** [phonegap/phonegap-plugin-push#1422]
Hello, i'm trying to integrate Push Notification functionality to my app build with phonegap build. 
I've added the plugin 

```
<preference name="android-build-tool" value="gradle"/>
<plugin name="phonegap-plugin-push" source="npm"  spec="1.7" >
     <param name="SENDER_ID" value="XXXXXXX" />
</plugin>
```
 in my _config.xml_

And the code: 

> var push; 
> 	try {  
> 	push = PushNotification.init({ "android": {"senderID": "XXXXXX"}});
> 	}	
> 	catch (error) {
> 	alert(error.message)
> 	}
in the "ondeviceready" event of my _index.js_

When i generate the apk on PhoneGap Build, everything is fine, but when i install it on my device, the catch section of my code give me an alert with "PushNotification is not defined".

I've tried everything, but with no success. 

Can u please help me? 

Thank you very much.

**Comment by fredgalvao** [comment]
Why `1.7` exactly?

**Comment by macdonst** [comment]
@MooUser yeah, that spec looks invalid. PGB probably can't find a version `1.7` and thereby does not include it in your app. Use a valid semver in your spec like `1.7.0` for instance.

**Comment by MooUser** [comment]
Version 1.7 was just a try... before that i put also version 1.8.4 which was the suggested value to use.

**Comment by MooUser** [comment]
Hi everybody: after multple attempts, finally i had my registrationID. Thanks to @macdonst  and the first section of his workshop available at http://macdonst.github.io/push-workshop/ 
Maybe this page will help some people having the same trouble.
I think i will close this question and maybe i will open another one about sending custom notification, instead of using the FCM Notification panel. 
Thank you so much for your interesting.
