### ISSUE TITLE
What should be correct behaviour if app is killed?

### ISSUE THREAD

**Issue by yiwong2001** [phonegap/phonegap-plugin-push#1423]
### Expected Behaviour

Receive google notification all the case.

### Actual Behaviour
No notification is shown when app is killed manually OR by OS.

#### Steps to Reproduce 

It happen on my Huawei mate7. App is easily be killed if I switch off screen/lock phone for a while.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Huawei mate7

#### Cordova CLI version and cordova platform version
cordova 6.4.0

#### Plugin version
1.8.2

#### Sample Code that illustrates the problem

Manifest file:

<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="10000" android:versionName="1.0.0" package="io.pubble.mod" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <application android:hardwareAccelerated="true" android:icon="@drawable/icon" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:exported="true" android:name="com.adobe.phonegap.push.PushHandlerActivity" />
        <receiver android:name="com.adobe.phonegap.push.BackgroundActionButtonHandler" />
        <receiver android:exported="true" android:name="com.google.android.gms.gcm.GcmReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="io.pubble.mod" />
            </intent-filter>
        </receiver>
        <service android:exported="false" android:name="com.adobe.phonegap.push.GCMIntentService">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>
        <service android:exported="false" android:name="com.adobe.phonegap.push.PushInstanceIDListenerService">
            <intent-filter>
                <action android:name="com.google.android.gms.iid.InstanceID" />
            </intent-filter>
        </service>
        <service android:exported="false" android:name="com.adobe.phonegap.push.RegistrationIntentService" />
    </application>
    <uses-sdk android:minSdkVersion="15" android:targetSdkVersion="24" />

    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.VIBRATE" />

    <uses-permission android:name="io.pubble.mod.permission.C2D_MESSAGE" />
    <permission android:name="io.pubble.mod.permission.C2D_MESSAGE" android:protectionLevel="signature" />
</manifest>

#### Logs taken while reproducing problem

11-30 23:49:17.935 31625-21581/? I/GCM: GCM message io.pubble.mod 0:1480520957115653%508bcc1a00000031
11-30 23:49:17.951 31625-31625/? W/GCM-DMM: broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000000 pkg=io.pubble.mod (has extras) }

Hi guys,

It seems my mate7 always kill my app if I lock phone/screen for a while. 

I want know what is correct behaviour when app is not running. such as app is killed, Or after I reboot mobile.  Currently I got no notification but noticed following in log:  

     broadcast intent callback: result=CANCELLED forIntent in log

A side question, I have been reading issues here. When someone mention close app, does it mean to kill app? Or just shift to home and get app to work in background?

Thanks!

**Comment by macdonst** [comment]
@yiwong2001 you are running into an oddity of Huawei phones. See the docs:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#huawei-and-xiaomi-phones

**Comment by yiwong2001** [comment]
Hi Macdonst, 

I read that post too. I have applied solution there but still face issue.

But I want to know what would be correct behaviour for GCM/this plugin if not run on a huawei mate7 mobile.

I want know what is correct behaviour when app is not running. such as app is killed, Or after I reboot mobile. Will it always get gcm?

I got it when app is not running, is that normal?

 broadcast intent callback: result=CANCELLED forIntent in log

A side question, I have been reading issues here. When someone mention close app, does it mean to kill app? Or just shift to home and get app to work in background?

thanks.

**Comment by macdonst** [comment]
@yiwong2001 if you are not on a Huawei device and you have killed the app then the notification will be correctly received and clicking on the notification will open the app.

killed -> app not running
closed -> app running in background

**Comment by yiwong2001** [comment]
thanks, @macdonst

I will try my app on other devices to see how it work.

**Comment by fredgalvao** [comment]
> killed -> app not running
> closed -> app running in background

I don't think everyone abides to that convention, @macdonst. Some people might mean:

- `killed`||`closed` -> app not running (force-killed, closed on the "alt-tab", not initially running, etc)
- `on background` -> app running in background (alt-tabbed, home button pressed, backbutton pressed and not handled, etc)

**Comment by christianraj** [comment]
i googled but could not find solutions to cordova app i need the app to receive notification when app is killed , i could receive notification when app is in foreground and when in background .
am using cordova-firebase-plugin 
getting push message from firebase google cloud
