### ISSUE TITLE
How can i make a button on my notification ? 

### ISSUE THREAD

**Issue by brunoalex** [phonegap/phonegap-plugin-push#1424]
### Expected Behaviour
Use buttons on Notifications 
### Actual Behaviour
i cant use them 
### Reproduce Scenario (including but not limited to)
my js

```
 push.on('notification', function(data) {
            console.log('notification event');
            navigator.notification.alert(
                data.message,         // message
                null,                 // callback
                data.title,           // title
                'Ok'                  // buttonName
            );

```

and my fields that send firabase push over php

```
$fields = array
(
 'to' =>   $row1['fcm_registered_id'] ,
 'priority' => "high",
 'data' => array("title" =>$titlepost, "body"=> $msg),
);

```

#### Steps to Reproduce 
phonegap + firebase
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.1
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
Please read the docs before opening issues:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons

**Comment by brunoalex** [comment]
i did but my problem is the APP js .. can send tha data like this

$fields = array
(
 'to' =>   $row1['fcm_registered_id'] ,
 'priority' => "high",
 'data' => array("title" =>$titlepost, "body"=> $msg, "actions"=>  array('title' => 'EMAIL GUESTS','callback' => 'callbackName','foreground' => true ) ),
);

but in my app js i cant make it work ...
```

     push.on('notification', function(data) {
            console.log(data);
            console.log(data.additionalData);
            navigator.notification.alert(
                data.message,         // message
                null,                 // callback
                data.title,           // title
                'Ok'                  // buttonName
            );

window.callbackName = function (data) { 
    alert("additionalData");
};
```
