### ISSUE TITLE
Clicking on the same notification on multiple devices at the same time

### ISSUE THREAD

**Issue by mbachaalani** [phonegap/phonegap-plugin-push#1425]
Hello,

When logged in into different users or same users in my app, I send the same notification. I am testing when I click on the notification tile at the same time on the different devices the data related to the notification is not showed on all the devices. What I implemented previously is insertion into a table when new data is avaible to send as notification but the insert was done max recID +1 now I changed the table structure to have the recId as identity to lock the table on each insert if occurring at the same time but still I am facing the same problem. Any tips on that?

Thank you.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
