### ISSUE TITLE
CocoaPods was not found

### ISSUE THREAD

**Issue by bau720123** [phonegap/phonegap-plugin-push#1426]
[my environment]
cordova 6.4.0
cordova-android 6.2.0 dev
cordova-ios 4.3.0
cocoapods 1.1.1
macOS sierra 10.12

hi @macdonst 
I use the latest phonegap-plugin-push plugin verison 1.9.1 from npm，but in iOS occur some trouble (Android seem no problem)

first，I use "cordova platform add ios@4.3.0"，but it will appear a "CocoaPods was not found" error message，so I try to use the command and install it (https://cocoapods.org/)
![01](https://cloud.githubusercontent.com/assets/5110085/20793240/08d4a5f4-b801-11e6-93fa-e8cf684e1dc6.png)

second，after first step，I use "cordova platform add ios@4.3.0" again，but this time it appear another wrong message
![02](https://cloud.githubusercontent.com/assets/5110085/20793313/64c4051c-b801-11e6-915e-6dac7b7cf4b2.png)

I am unfamiliar with CocoaPods，so...don't know what is the next step
use the "pod repo update" command ?
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#cocoapods
or...
use the "pod setep" ?
any idea or suggestion ?

**Comment by macdonst** [comment]
@bau720123 do `pod setup` first then if your app is not building then do `pod repo update`.

**Comment by bau720123** [comment]
hi @macdonst 
thanks your reply，but after I use `pod setup` and waiting for a long time
![03](https://cloud.githubusercontent.com/assets/5110085/20795909/962f2a98-b80e-11e6-84cb-c4898701343a.png)
should I use `pod setup` once again (I am sure my network is no problem)

**Comment by laagland** [comment]
You're getting a CocoaPods error, quick search from their issue list revealed this:
[https://github.com/CocoaPods/CocoaPods/issues/5744](https://github.com/CocoaPods/CocoaPods/issues/5744)

**Comment by bau720123** [comment]
hi @laagland 
so you mean is use `pod init` to solve it ?
or
`git clone https://github.com/CocoaPods/Specs.git master`

**Comment by laagland** [comment]
I would try both, starting with: 
Go to ~/.cocoapods/repos and run git clone https://github.com/CocoaPods/Specs.git master

If that's not working, search their issue list for other solutions or report an issue there.

Good luck.

**Comment by bau720123** [comment]
ok @laagland 
I will try those，it seem like a network isuue ?!
but my network really work well

**Comment by bau720123** [comment]
hi all
I try many method but no luck
after change the network (phone network)
work perfect...what the...@_@||
