### ISSUE TITLE
Why does this plugin require Android >= 6.0.0

### ISSUE THREAD

**Issue by pke** [phonegap/phonegap-plugin-push#1427]
My app does not start up with Android 6.1.0 (6.0.0 is broken for copying icon resources).
That's why I wonder why from 1.9.x onwards this plugin requires Android 6.0.0 for which functionality exactly?

**Comment by macdonst** [comment]
@pke in order for you to use `force-start` on Android you'll need to use cordova-android 6.0.0 or greater. 

http://phonegap.com/blog/2016/11/03/phonegap-plugin-push-1.9.0/

**Comment by pke** [comment]
Understood. Would be nice if the blog entry would be referenced somewhere. I didn't find that blog entry myself.

Still Cordova Android 6.0.0 makes my app to not fire the ready event anymore. Going back to 5.1.1 and all works.

**Comment by macdonst** [comment]
@pke yeah, I'm trying to get better at docs. I just fixed 3 doc issues. WIth regards to your cordova-android 6 issue, hit me up on cordova slack.

**Comment by fredgalvao** [comment]
Maybe add blog post link to the changelog IF EXISTS?

**Comment by fattanasio** [comment]
Hi, I have same problem. Did you resolve the bug?
Thank you!
