### ISSUE TITLE
Question: OnNotification trigger when app is lauch again

### ISSUE THREAD

**Issue by embarbosa** [phonegap/phonegap-plugin-push#1428]
Is there any way to trigger OnNotification method when the app received an push, but user opened the App without clicking on the push notification?

Thanks

**Comment by macdonst** [comment]
@embarbosa 

![ex1wekt](https://cloud.githubusercontent.com/assets/353180/20806688/ecc9f21a-b7c9-11e6-9f58-e94e693c6b60.png)

I believe the answer you are looking for is documented for [Android](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications) and [iOS](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications-1).

Was there a problem with the docs as written? Was it difficult to find the answer? Or did you not look? I ask these questions as I want to see if I need to make the docs better.

**Comment by embarbosa** [comment]
Thank you
