### ISSUE TITLE
An issue I can attach reaction gifs to

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-plugin-push#1429]
Not a real issue.

**Comment by macdonst** [comment]
![ex1wekt](https://cloud.githubusercontent.com/assets/353180/20806688/ecc9f21a-b7c9-11e6-9f58-e94e693c6b60.png)

**Comment by fredgalvao** [comment]
Please make that a saved reply.

**Comment by macdonst** [comment]
@fredgalvao are saved replies shared between users?

**Comment by jcesarmobile** [comment]
What about this one?
![RTFM](https://media.giphy.com/media/l2Jht0Jt5UjkUEipG/giphy.gif)

**Comment by macdonst** [comment]
Yup, we can cycle between them.

**Comment by fredgalvao** [comment]
They are not shared, but I'll save those two. Forever in my heart they will be.

**Comment by shazron** [comment]
When someone sends a Pull Request with more than 5 commits in it, with 50 changed files and 1000 lines changed:
![michael-scott-no](https://cloud.githubusercontent.com/assets/36107/20810157/688a6d6a-b7bd-11e6-814f-b1535f7cbe84.gif)
