### ISSUE TITLE
How to implement push notification for ios with this plug-in?

### ISSUE THREAD

**Issue by ramakrishna-nyros** [phonegap/phonegap-plugin-push#143]
Hi ,

By using this push plugin and **phonegap build** , I implemented push notification for **andriod** with GCM successfully.

How to implement push notifications for **ios,windows** by using this push plugin and **phonegap build** , what I need to required to get device id for ios like GCM senderid ?

I googled it, most of the articles shows about phonegap but not about **phonegap build**

Anyone help me

Thanks in advance.

**Comment by macdonst** [comment]
Please take a look at issue #124 for a link on how to setup APNS
