### ISSUE TITLE
Question: How to listen to a push notification click?

### ISSUE THREAD

**Issue by jourdan-jobox** [phonegap/phonegap-plugin-push#1430]
Hi everybody,

I'm building a chat application where a user should be directed to the correct conversation page when clicking on a push notification that they receive via a message sent by someone else.

My question is, how do I listen to a push notification click? Is there some data in `.on('notification')` that gets passed in when a user clicks on a notification? Is there some `.on('notificationClick')` listener?

Thanks in advance!

**Comment by macdonst** [comment]
@jourdan-jobox tell you what, run through this tutorial.

http://macdonst.github.io/push-workshop-eu/

If it doesn't answer your question, specifically, step 7 then re-open this issue.

**Comment by jourdan-jobox** [comment]
@macdonst Thanks for the swift response, will let you know!

**Comment by jourdan-jobox** [comment]
@macdonst I went through your tutorial and it makes sense, but I don't know if it helps me with this issue

What I'm trying to do is navigate to a push ONLY when a user presses on the push notification while the app is in the background. However, with this `foreground` check, it will still navigate the app to the push notification's page even if a user didn't click on the notification.

Is there anything similar to `data.additionalData.coldstart` except when the app is already launched?

**Comment by fredgalvao** [comment]
That's not a `workaround` per se, for that's the one way to do it currently. You're doing it right if you're doing it that way.

I have some suggestions laying around on semi-old issues to add a new event to the api to separate the notification `arrival` from `interaction`. Until then, we'll keep doing it the way you described.
