### ISSUE TITLE
unable to user action buttons (dont know how)

### ISSUE THREAD

**Issue by brunoalex** [phonegap/phonegap-plugin-push#1432]
### Expected Behaviour

use buttons on notifications 

### Actual Behaviour
i can pass the data but dont know how to implement in app js

#### Cordova CLI version and cordova platform version

phonegap cli-6.4.0

#### Plugin version

    <plugin name="phonegap-plugin-push" source="npm" spec="~1.8.4">

#### Sample Push Data Payload
using FCM
```
$fields = array
(
 'to' =>   $row1['fcm_registered_id'] ,
 'priority' => "high",
 'data' => array("title" =>$titlepost, "body"=> $msg, "actions"=>  array('title' => 'EMAIL GUESTS','callback' => 'callbackName','foreground' => true ) ),
);
```
#### Sample Code that illustrates the problem

```
        push.on('notification', function(data) {
            console.log(data);
            console.log(data.additionalData);
            navigator.notification.alert(
                data.message,         // message
                null,                 // callback
                data.title,           // title
                'Ok'                  // buttonName
            );

window.callbackName = function (data) { 
    alert("additionalData");
};

```

#### Logs taken while reproducing problem

```
Object {title: "dwq", message: "dwq", additionalData: Object}
additionalData: Objectmessage: "dwq"title: "dwq"__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()
not.js:91 Object actions: Object callback: "callbackName" foreground: true title: "EMAIL GUESTS"__proto__: Object coldstart: false collapse_key: "do_not_collapse"foreground: truegoogle.message_id: "0:1480692890563641%e72e3b9df9fd7ecd"__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()arguments: nullcaller: nulllength: 0name: "valueOf"__proto__: ()[[FunctionLocation]]: <unknown>get __proto__: __proto__()set __proto__: __proto__()
callbackName()
```

**Comment by macdonst** [comment]
@brunoalex I'm getting a little frustrated because you aren't giving me enough information. You didn't give me a reproduction scenario for this issue and the logs are a mess. You need to tell me what you've tried and `adb logcat | grep PushPlugin` when you are reproducing the problem is always useful.

Did you read over my tutorial which includes setting up action buttons? http://macdonst.github.io/push-workshop/module6.html

My best guess with the limited information is `callbackName` is not a function available to be called by the plugin's JS code.

**Comment by brunoalex** [comment]
im on android ... and using a php script to send the push 
```
$fields = array
(
 'to' =>   $row1['fcm_registered_id'] ,
 'priority' => "high",
 'data' => array("title" =>$titlepost, "body"=> $msg, "actions"=>  array('title' => 'EMAIL GUESTS','callback' => 'callbackName','foreground' => true ) ),
);
```

if i inspect my app i can see the push  with message ,  title  and additionalData
but my alert only as one button "ok" i need other "EMAIL GUESTS" that callbacks callbackName function but can for the dsake of me make it work ...

my js code.
  

>  push.on('notification', function(data) {
>             console.log(data);
>             console.log(data.additionalData);
>             navigator.notification.alert(
>                 data.message,         // message
>                 null,                 // callback
>                 data.title,           // title
>                 'Ok' , 'Estou Disponível e quero cadidatar-me!'                 // buttonName
>             );
> 
> window.callbackName = function (data) { 
>     alert("additionalData");
> };
> 
> 
>

**Comment by fredgalvao** [comment]
@brunoalex 
If I know PHP enough (I highly doubt it), the sintax of `array` gives you an array of whatever you pass him, be it properties or other complex objects.
Assuming from
```php
'data' => array("title" =>$titlepost, "body"=> $msg, ...)
```
which is expected to give me:
```json
{
  "data": {
    "title": "valueOfTitlePost",
    "body": "valueOfMsg",
    ...
  }
}
```

then
```php
"actions"=>  array('title' => 'EMAIL GUESTS','callback' => 'callbackName','foreground' => true )
```
will give you:
```json
{
  "actions": {
    "title": "EMAIL GUESTS",
    "callback": "callbackName",
    "foreground": true
  }
}
```

Which is not how the documentation specifies it to be. `actions` is expected to be an actual ARRAY OF OBJECTS, instead of AN OBJECT. If that's the case, I cannot help you any further, that's PHP knowledge and has nothing to do with the plugin.

Other than that, if you keep ignoring the information we request to help you, then it's **really hard** to help. You completely ignored the versions, you didn't say which service you're using (FCM/GCM), etc.

<pt_BR>`Me ajude a te ajudar, cara. Preenche o template da issue direitinho.`</pt_BR>

**Comment by brunoalex** [comment]
Sorry! i updated the info above... im getting this output is it correct ?

Fields:`{"to":"this is my device id n:xxx","priority":"high","data":{"title":"TEXTO","body":"TEXTO","actions":{"icon":"","title":"EMAIL GUESTS","callback":"app.callbackName","foreground":true}}}`

**Comment by brunoalex** [comment]
my console.log(data.additionalData);
> Object {actions: Object, google.message_id: "0:1480703195582104%e72e3b9df9fd7ecd", coldstart: false, collapse_key: "do_not_collapse", foreground: true}

**Comment by brunoalex** [comment]
ARRAY OF OBJECTS, instead of AN OBJECT ... u lost me there (noob here)

**Comment by brunoalex** [comment]
i also tried  this but buttons dont show```
$fields = array
(
 'to' =>   $row1['fcm_registered_id'] ,
 'priority' => "high",
 'data' => array("title" =>$titlepost, "body"=> $msg),
 "actions" => array('icon' => 'icon.png', 'title' => 'EMAIL GUESTS','callback' => 'app.callbackName','foreground' => true )
);
```

**Comment by fredgalvao** [comment]
Você precisa garantir que o atributo `actions` do payload enviado pelo PHP seja um array de objetos, ao invés de ser um objeto em si. Reveja essa construção do payload aí, eu tenho quase certeza que o problema está aí. Outra coisa, você está usando FCM ou GCM pra mandar essas notificações?

**Comment by brunoalex** [comment]
Estou a utilizar o FCM

**Comment by brunoalex** [comment]
tenho isto no output:
{"to":"this is my device id n:xxx","priority":"high","data":{"title":"TEXTO","body":"TEXTO","actions":{"icon":"","title":"EMAIL GUESTS","callback":"app.callbackName","foreground":true}}}

**Comment by fredgalvao** [comment]
Exatamente, o seu `actions` é um objeto, ele precisa ser uma lista de objetos. O problema está no PHP. Vou fechar a issue, se você resolver a questão do PHP e o problema ainda existir, você pode reabrir a issue.

Outra coisa, esse plugin ainda não dá suporte oficial ao FCM. Se você está utilizando-o, precisa instalar o plugin no branch v2.0.x. Mais detalhes você encontrará aqui: https://github.com/phonegap/phonegap-plugin-push/issues/929
