### ISSUE TITLE
Cordova Push V5 register () crashes App when initialized with topicList 

### ISSUE THREAD

**Issue by haresh333** [phonegap/phonegap-plugin-push#1433]
### Expected Behaviour
I am implementing PUSH in ionic Project.

### Actual Behaviour
1. when I run app on device, when I call $cordovaPushV5.register() it just **exits** App without any error message in logs (I had inspect on in browser while device connected to my laptop).
Look at the code below. it reaches console.log('PUSH: 2....');. 
But it does not reach console.log('PUSH: 3....');

2. **However** if I remove the topicList from the initialization process the registration is successful. 

#### Steps to Reproduce 
Look at below code.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Lenovo, HTC

#### Cordova CLI version and cordova platform version
cordova 6.4
cordova-android android 5.1.1

#### Plugin version
phonegap-plugin-push 1.8.4 "PushPlugin"

#### Sample Push Data Payload
not captured

#### Sample Code that illustrates the problem
```js
$cordovaPushV5.initialize({
  android: {
    senderID: config.GCM_SENDER_ID,
    forceShow: true,
    topics: topicList,
  }
}).then(function() {
  console.log('PUSH: 1....');
  $cordovaPushV5.onNotification(); // start listening for new notifications
  $cordovaPushV5.onError(); // start listening for errors
  console.log('PUSH: 2....');
  $cordovaPushV5.register().then(function(registrationId) {   // register to get registrationId
    console.log('PUSH: 3....');
    $rootScope.device_id = registrationId;
  });
});
```

#### Logs taken while reproducing problem
not captured

**Comment by macdonst** [comment]
@haresh333 run `adb logcat` to gather the logs of the crash.

**Comment by haresh333** [comment]
Hi
As you suggested I ran adb logcat. And I found the issue. Also attached is the adb log
1. When creating topic list I was prepending **/topic/** to each topic (as per documentation of Google GCM.
2. it appears Cordova plugin is also prepending **/topic/**
3. So I removed my /topic/ and after this no exception. Registration is succcessful
4. I am yet to test of the PUSH is sent successfully by the GCM and if I will receive those. Will test it in few days
**Now few questions**
5. Is this prepending of /topic/ by cordova to the list provided to the initialize API is by design?
6. if yes, it seems its not documented anywhere ? May be I missed if it is
7. if the topic name is invalid because /topic/  was prepended twice - why the app crashes, why does cordova  not gracefully handle java.lang.IllegalArgumentException  
8. Please advice if I should know more about PUSH handling and if there is any extra documentation?

Thanks and regards
Haresh


I/chromium(30221): [INFO:CONSOLE(55)] "!!!!PUSH: registerWithGCM 6....", source: file:///android_asset/www/services/gcmPushNotification.js (55)
V/PushPlugin(30221): execute: action=init
V/PushPlugin(30221): execute: data=[{"android":{"senderID":"mybabybox-1080","forceShow":true,"icon":"aamhi_numaviya_icon","topics":["\/topics\/NMV","\/topics\/NMV-1985","\/topics\/NMV-1985-A","\/topics\/NMV-ALL-Admin","\/topics\/NMV-AppAdmin"]},"ios":{"senderID":"mybabybox-1080","alert":"true","badge":"true","sound":"true"}}]
V/PushPlugin(30221): execute: jo={"senderID":"mybabybox-1080","forceShow":true,"icon":"aamhi_numaviya_icon","topics":["\/topics\/NMV","\/topics\/NMV-1985","\/topics\/NMV-1985-A","\/topics\/NMV-ALL-Admin","\/topics\/NMV-AppAdmin"]}
V/PushPlugin(30221): execute: senderID=mybabybox-1080

V/PushPlugin(30221): onRegistered: {"registrationId":"flsW6UKWRKA:APA91bGX7_D0KxUX4RV4SHLuqdw8Zmk3gwV2F07GRpcVOUGkO607hb8-MySuj2U4r2M6TRgzng3dz7JmqEAJ2aT1CLO40tipiNEr0W63YCQYMKDGf1ISLaXmbDkCf55WU6A9ZBlHYSuu"}

D/PushPlugin(30221): Subscribing to topic: /topics/NMV

E/AndroidRuntime(30221): FATAL EXCEPTION: pool-1-thread-1

E/AndroidRuntime(30221): Process: com.ionicframework.alumni673906, PID: 30221

E/AndroidRuntime(30221): java.lang.IllegalArgumentException: Invalid topic name: **/topics/**/topics/NMV

E/AndroidRuntime(30221): 	at com.google.android.gms.gcm.GcmPubSub.subscribe(Unknown Source)

E/AndroidRuntime(30221): 	at com.adobe.phonegap.push.PushPlugin.subscribeToTopic(PushPlugin.java:349)

E/AndroidRuntime(30221): 	at com.adobe.phonegap.push.PushPlugin.subscribeToTopics(PushPlugin.java:339)

E/AndroidRuntime(30221): 	at com.adobe.phonegap.push.PushPlugin.access$300(PushPlugin.java:30)

E/AndroidRuntime(30221): 	at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:82)

E/AndroidRuntime(30221): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

E/AndroidRuntime(30221): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

E/AndroidRuntime(30221): 	at java.lang.Thread.run(Thread.java:818)

V/SettingsProvider(32248): call(global:dropbox:data_app_crash) for 0


[android-app_1.txt](https://github.com/phonegap/phonegap-plugin-push/files/628791/android-app_1.txt)

**Comment by macdonst** [comment]
@haresh333 you are right, the code should guard against the IllegalArgumentException and the docs should be better. I've switched this to a bug and docs issue.
