### ISSUE TITLE
App crashes when in foreground received a push

### ISSUE THREAD

**Issue by ai2010** [phonegap/phonegap-plugin-push#1436]
### Expected Behaviour
Receive the push 

### Actual Behaviour
When the app is in foreground and it receives a push it crashes
#### Steps to Reproduce 
1) open the app in foreground
2) send a push
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Motorola
#### Cordova CLI version and cordova platform version
cordova 6.3.1
cordova platform version android 5.2.2

#### Plugin version
1.8.4
### Log:
0java.lang.RuntimeException: Unable to start receiver co.realtime.plugins.android.cordovapush.GcmReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(java.lang.String)' on a null object reference
1	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2750)
2	at android.app.ActivityThread.-wrap14(ActivityThread.java)
3	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1431)
4	at android.os.Handler.dispatchMessage(Handler.java:102)
5	at android.os.Looper.loop(Looper.java:148)
6	at android.app.ActivityThread.main(ActivityThread.java:5443)
7	at java.lang.reflect.Method.invoke(Native Method)
8	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
9	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
10	Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(java.lang.String)' on a null object reference
11	at co.realtime.plugins.android.cordovapush.OrtcPushPlugin.convertBundleToJson(OrtcPushPlugin.java:365)
12	at co.realtime.plugins.android.cordovapush.OrtcPushPlugin.sendExtras(OrtcPushPlugin.java:345)
13	at co.realtime.plugins.android.cordovapush.GcmReceiver.onReceive(GcmReceiver.java:36)
14	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2743)
15	... 8 more
16	java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(java.lang.String)' on a null object reference
17	at co.realtime.plugins.android.cordovapush.OrtcPushPlugin.convertBundleToJson(OrtcPushPlugin.java:365)
18	at co.realtime.plugins.android.cordovapush.OrtcPushPlugin.sendExtras(OrtcPushPlugin.java:345)
19	at co.realtime.plugins.android.cordovapush.GcmReceiver.onReceive(GcmReceiver.java:36)
20	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2743)
21	at android.app.ActivityThread.-wrap14(ActivityThread.java)
22	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1431)
23	at android.os.Handler.dispatchMessage(Handler.java:102)
24	at android.os.Looper.loop(Looper.java:148)
25	at android.app.ActivityThread.main(ActivityThread.java:5443)
26	at java.lang.reflect.Method.invoke(Native Method)
27	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
28	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618).

**Comment by macdonst** [comment]
@ai2010 can you do a `adb logcat | grep PushPlugin` while reproducing the bug?

**Comment by ai2010** [comment]
@macdonst 
E AndroidRuntime: 	at co.realtime.plugins.android.cordovapush.OrtcPushPlugin.convertBundleToJson(OrtcPushPlugin.java:365)
12-06 15:02:53.391 25099 25099 E AndroidRuntime: 	at co.realtime.plugins.android.cordovapush.OrtcPushPlugin.sendExtras(OrtcPushPlugin.java:345)

**Comment by macdonst** [comment]
@ai2010 thanks for the info but `co.realtime.plugins.android.cordovapush.OrtcPushPlugin` is not a class in this plug in so your issue is in code we don't own. Please open this issue in the correct repo.

**Comment by ai2010** [comment]
Ok I have seen the file: something is wrong with the line:
String newMsg = message.substring(message.indexOf("_", message.indexOf("_") + 1)+1);
Do you know what it is?
