### ISSUE TITLE
Error: Class not found

### ISSUE THREAD

**Issue by rkaartikeyan** [phonegap/phonegap-plugin-push#1437]
My code is like Bellow

```
var push = PushNotification.init({
	"android": {
		"senderID": "1234567"
	}
});

push.on('registration', function(data) {
	console.log("registration event");
	console.log(JSON.stringify(data));
});

push.on('notification', function(data) {
	console.log("notification event");
	console.log(JSON.stringify(data));
	
	var card = '<div class="row">' +
		  '<div class="col s12 m6">' +
		  '  <div class="card darken-1">' +
		  '    <div class="card-content black-text">' +
		  '      <span class="card-title black-text">' + data.title + '</span>' +
		  '      <p>' + data.message + '</p>' +
		  '    </div>' +
		  '  </div>' +
		  ' </div>' +
		  '</div>';
	console.log(card);
	
	push.finish(function () {
		console.log('finish successfully called');
	});
});

push.on('error', function(e) {
	console.log(e);
});
```
in my console i got this `Error: Class not found` Please Help me to resolve this issue.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by rkaartikeyan** [comment]
I have used 1.4.2 and its working.
