### ISSUE TITLE
'notification received' event fired twice on launching app by tapping notification

### ISSUE THREAD

**Issue by sadiq-mc** [phonegap/phonegap-plugin-push#1439]
### Expected Behaviour
Notification event should be fired only once on tapping notification.
And notification event should not be fired on launching app by tapping app icon.

### Actual Behaviour
Notification event fired twice with the same notification data on taping notification.
And notification event fired one's on launching app by tapping app icon when the notification is available in device's notification area.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy A7

#### Cordova CLI version and cordova platform version

    cordova --version                               6.4.0
    cordova platform version android                6.0.0
    ionic --version                                2.1.8

#### Plugin version
2.0.0

#### Sample Push Data Payload
```
{"to":"DEVICE_TOKEN","priority":"high","data":{"notId":"1","title":"My title","body":"my msg body","state":"tips","content-available":"1"}}
```

#### Sample Code that illustrates the problem
```
$rootScope.$on('$cordovaPushV5:notificationReceived', function(event, data) {
            console.log('$cordovaPushV5:notificationReceived');  // fired twice on launching app by tapping notification and fired one's on launching app by tapping app icon. (Notificaion is available in the device notification area)
            logService.log(data);
        });
```

Am using the push plugin v2.0.0 from v2.0.x branch as I need to integrate FCM for android push notification.

**Comment by sadiq-mc** [comment]
Got it resolved... 
I removed the ```"content-available":"1"``` from payload and now it works as expected...

**Comment by gerhardcit** [comment]
@sadiq-mc , that's not really solving it?
if you don't have `content-available":"1"` the cordovaPushV5:notificationReceived are not fired whe nthe app is in the background and that way you cannot handle a badge count?

**Comment by sadiq-mc** [comment]
@gerhardcit Well I am not updating badge in my application.
