### ISSUE TITLE
How to integrate plugin in a project that already handles push

### ISSUE THREAD

**Issue by jccazeaux** [phonegap/phonegap-plugin-push#1441]
### Expected Behaviour
My project alreay has a push notification service that handles notifications to be sent to a widget. So it's purely native code. The Phonegap plugin push includes a `FCMService` that needs to be declared in `AndroidManifest.xml` but it's not possible to declare two services on the same intent `com.google.firebase.MESSAGING_EVENT`
How would you do it? Should I modify the plugin's FCMService?

How would you do this?

#### Cordova CLI version and cordova platform version

    cordova 6.3.1
    android 23

#### Plugin version

    2.0.x

**Comment by macdonst** [comment]
@jccazeaux yeah, you are going to have to fork and modify the `FCMService` class.
