### ISSUE TITLE
CocoaPods support vs requirement

### ISSUE THREAD

**Issue by TommyO** [phonegap/phonegap-plugin-push#1442]
### Expected Behaviour
If CocoaPods isn't installed, throw a warning about _Google Cloud Messaging_ support but continue.

### Actual Behaviour
Build fails for ios.

#### Cordova CLI version and cordova platform version

`$ cordova --version`
`6.4.0`

`$ cordova platform version`
`ios 4.3.1`

#### Plugin version

`$ cordova plugin version | grep phonegap-plugin-push`
`phonegap-plugin-push 1.9.1 "PushPlugin"`

**Comment by macdonst** [comment]
@TommyO the build should fail. Without cocoapods the plugin won't build correctly as it will be missing header files and frameworks.

**Comment by VinceOPS** [comment]
I don't get what's the point of using CocoaPods, which requires 1GB+ of download as December 2016 to get the full repo (running `pod setup`) only to be able to get the few files required by this plugin?

Is there any way to achieve the install manually, without using CocoaPods?

**Comment by macdonst** [comment]
@VinceOPS not currently but you are not the only one with the question http://stackoverflow.com/questions/38757167/pod-setup-consuming-a-significant-amount-of-disk-space

**Comment by VinceOPS** [comment]
@macdonst I actually find a way to get CocoaPods ready quickly.
I cloned the repo manually, using only the very last version with `--depth=1`

`git clone --verbose --depth=1 https://github.com/CocoaPods/Specs.git ~/.cocoapods/repos/master`

Then, running `pod setup --verbose` is barely instant, as the repo is already here.
