### ISSUE TITLE
Push Notification not Working while download app from play store,but working fine when installed unsigned apk

### ISSUE THREAD

**Issue by sourav86** [phonegap/phonegap-plugin-push#1443]
Expected Behaviour

Push Notification Should work in both debug and release mode

Actual Behaviour

Only working in debug mode

Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1

(Android) What device vendor (e.g. Samsung, HTC, Sony...)

Moto G

Cordova CLI version and cordova platform version
cordova 6.3.0

Plugin version
1.8.2

Sample Push Data Payload

let push = Push.init({
android: {
senderID: "XXXXXXXXX",
"icon": "icon",
"iconColor": "Gray"
},
ios: {
alert: "true",
badge: false,
sound: "true"
},
windows: {}
});

push.on('registration', (data) => {
            alert(data.registrationId.toString());
 });

**Comment by codeHatcher** [comment]
I know you are on android but I can tell you with iOS you have to keep track of whether you are using the Sandbox (development) environment or the production distribution env, not sure if that's something to keep track of with Android also

**Comment by macdonst** [comment]
@sourav86 I've never seen this before. Do you have any logs from the device having the issue?

**Comment by sourav86** [comment]
Actually push.on('registration', (data) ... function not called in signed apk, but it is working for unsigned apk.

**Comment by macdonst** [comment]
@sourav86 okay, that is weird. Can you get any logs from the signed APK?

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.

**Comment by sdsanders** [comment]
@sourav86 did you ever resolve this issue?
