### ISSUE TITLE
my app crash when i use this plugin with  cordova-plugin-googlemaps

### ISSUE THREAD

**Issue by dsemerida** [phonegap/phonegap-plugin-push#1444]
hello, im my first issue, my issue are when i try install the cordova -plugin -googlemaps my app crased before finish load, i dont know what is the bug

https://github.com/mapsplugin/cordova-plugin-googlemaps

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
