### ISSUE TITLE
Randomly error on registration iOS

### ISSUE THREAD

**Issue by entiendoNull** [phonegap/phonegap-plugin-push#1445]
### Expected Behaviour
Get a push token, deliver it to my external server to store the token in a database.

### Actual Behaviour
In fact, a token is received and I can store it at most times. But randomly it seem to fail and below seems to be the issue.
It can work well on one device. And next time I try it, it will fail. Even if nothing has changed within the app.

If I use the sender_id paramater in the payload in order to use FCM for iOS as well the issue seems to occure more often. Although, as it does occure randomly it's hard to confirm if that is the case.

In either way, this error message is returned to me upon failure.

`{\"line\":57,\"column\":54,\"sourceURL\":\"file:///var/containers/Bundle/Application/88FF1B19-C9B2-49B3-905E-4AAE3D65D79D/myappname.app/www/plugins/phonegap-plugin-push/www/push.js\"}`

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS v 10.1
iOS v. 10.1.1

#### Cordova CLI version and cordova platform version
I've tried this
cli-6.3.0,	iOS: 5.2.1, Android: 4.2.0, Windows: 4.4.1
and this
cli-6.4.0,	iOS: 6.1.0, Android: 4.3.0, Windows: 4.4.3

I use Phonegap cloud service to compile the app.
The plugin is included to my build by adding this to my config.xml
```
<plugin name="phonegap-plugin-push" source="npm" spec="1.9.1">
      <variable name="SENDER_ID" value="xxxxxxx" />
</plugin>
```

#### Plugin version
I've tried:
1.8.4
and 
1.9.1

When using 1.9.1 the dialog that asks me whether I want push messages or not is not triggered on iOS v.10.1. I receive no error.

#### Sample Code that illustrates the problem

```
function initPush(){
    push = PushNotification.init({
        'android': {
            'senderID': ""
        },
        'ios': {
            //'senderID': "xxxxxxx",
            'alert': 'true', 
            'badge': 'true', 
            'sound': 'true'
        }, 
        'windows': {}
    });

    push.on('registration', function(data) {
        if(data.registrationId != settings.push_token){

            db.transaction(function(tx){
                tx.executeSql('UPDATE settings SET push_messages = ?, push_token = ?', [1,data.registrationId], function(){
                    app.getSettings();
                }, app.onSQLError);
            });

            $.ajax({
                type: 'POST',
                data: {task: 'push',uuid : device.uuid,token : data.registrationId, os : (device.platform == 'iOS' ? 1 : 0), username : settings.user_name},
                crossDomain: true,
                contentType: 'application/x-www-form-urlencoded',
                url: 'my-url',
                success: function(response){
                    // console.log('Device has been registered');
                },
                 error: function (request, status, error) {
                    app.actionError('Push Registration',status +' '+ request.responseText +' '+ error,'',false);
                }
            });
        }
    });

    push.on('notification', function(data){
        pushDestination  = data.additionalData.sitemapid;
        pushMessage = data.message;
        app.openNewsPage(pushMessage,pushDestination);
    });

    push.on('error', function(e) {
        app.actionError('Push Error','Something wen't wrong...',JSON.stringify(e),true);
    });
```

**Comment by tigergroup** [comment]
Is there a fix for this.  I'm getting the same error too.

**Comment by macdonst** [comment]
@entiendoNull @tigergroup I'm not looking at this for 1.9.x as it does not support FCM. The 2.0.0 branch does support FCM and I'm about to do a release candidate.

**Comment by turshija** [comment]
Sorry for re-opening closed issue.

This is first result when you Google this problem, so I feel like others should know its fairly easy fix !

I was receiving same error in push.js line 57, and found a solution that you need to enable Push Notifications in XCode here and error is magically gone: http://www.pics.rs/i/sbDjr
