### ISSUE TITLE
Notification action button icons not being shown

### ISSUE THREAD

**Issue by bmwertman** [phonegap/phonegap-plugin-push#1447]
### Expected Behavior
Icons displayed next to action button in the push notification
 
### Actual Behaviour
No icons displayed
![actualnotification](https://cloud.githubusercontent.com/assets/2573903/21022192/b6891548-bd49-11e6-87b9-a3a5ae8b6971.png)

Also possibly related `REPLY` action button launches the application instead of displaying the inline reply field see #1446 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
     Android 5.0.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
    Oneplus One

#### Cordova CLI version and cordova platform version
    cordova --version                          6.4
    cordova platform version android           6.1
    cordova platform version ios           4.3

#### Plugin version
    cordova plugin version | grep phonegap-plugin-push   1.9.1

#### Sample Push Data Payload
```
{
    priority: "high",
    data: {
            "content-available": "1",
            title: req.body.sender_name,
            body: req.body.message,
            state: req.body.state,
            roomId: req.body.roomId,
            ledColor: [17, 2, 255, 1],
            soundname: "default",
            image: req.body.sender_imgURL,
            sender_imgUrl: req.body.sender_imgURL,
            actions: [
              {
                "icon": "chat",
                "title": "Chat",
                "foreground": true,
                "callback":"showChatter"
              },
              {
                "icon": "reply",
                "title": "Reply",
                "inline": true,
                "foreground": false,
                "callback": "inlineReply"
              }
            ]
          }
  }
```

#### Sample Code that illustrates the problem
Hook for transferring icons in `hooks/after_prepare` with chmod permission granted and no errors in build.
```
#!/usr/bin/env node
var filestocopy = [
    {"resources/android/reply/drawable-hdpi/reply.png":"platforms/android/res/drawable/drawable-hdpi/reply.png"},
    {"resources/android/reply/drawable-mdpi/reply.png":"platforms/android/res/drawable/drawable-mdpi/reply.png"},
    {"resources/android/reply/drawable-xhdpi/reply.png":"platforms/android/res/drawable/drawable-xhdpi/reply.png"},
    {"resources/android/reply/drawable-xxhdpi/reply.png":"platforms/android/res/drawable/drawable-xxhdpi/reply.png"},
    {"resources/android/reply/drawable-xxxhdpi/reply.png":"platforms/android/res/drawable/drawable-xxxhdpi/reply.png"},
    {"resources/android/chat/drawable-hdpi/chat.png":"platforms/android/res/drawable/drawable-hdpi/chat.png"},
    {"resources/android/chat/drawable-mdpi/chat.png":"platforms/android/res/drawable/drawable-mdpi/chat.png"},
    {"resources/android/chat/drawable-xhdpi/chat.png":"platforms/android/res/drawable/drawable-xhdpi/chat.png"},
    {"resources/android/chat/drawable-xxhdpi/chat.png":"platforms/android/res/drawable/drawable-xxhdpi/chat.png"},
    {"resources/android/chat/drawable-xxxhdpi/chat.png":"platforms/android/res/drawable/drawable-xxxhdpi/chat.png"}
];
var fs = require('fs');
var path = require('path');
// no need to configure below
var rootdir = process.argv[2];
 
filestocopy.forEach(function(obj) {
    Object.keys(obj).forEach(function(key) {
        var val = obj[key];
        var srcfile = path.join(rootdir, key);
        var destfile = path.join(rootdir, val);
        //console.log("copying "+srcfile+" to "+destfile);
        var destdir = path.dirname(destfile);
        if (fs.existsSync(srcfile) && fs.existsSync(destdir)) {
            fs.createReadStream(srcfile).pipe(
               fs.createWriteStream(destfile));
        }
    });
});
```

**Comment by bmwertman** [comment]
I was able to get the action button icons to show with the following update of the directory passed to my copy hook.

```
#!/usr/bin/env node
var filestocopy = [
    {"resources/android/reply/drawable-mdpi/reply.png":"platforms/android/res/drawable/reply.png"},
    {"resources/android/chat/drawable-mdpi/chat.png":"platforms/android/res/drawable/chat.png"}
];
var fs = require('fs');
var path = require('path');
// no need to configure below
var rootdir = process.argv[2];
 
filestocopy.forEach(function(obj) {
    Object.keys(obj).forEach(function(key) {
        var val = obj[key];
        var srcfile = path.join(rootdir, key);
        var destfile = path.join(rootdir, val);
        //console.log("copying "+srcfile+" to "+destfile);
        var destdir = path.dirname(destfile);
        if (fs.existsSync(srcfile) && fs.existsSync(destdir)) {
            fs.createReadStream(srcfile).pipe(
               fs.createWriteStream(destfile));
        }
    });
});
```
I'll go ahead and close this. But I'm still curious how to structure multiple image resolution/sizes within the res/drawable directory to support various Android device screen resolutions if someone  cares to share.

**Comment by fredgalvao** [comment]
You can define those image mappings on config.xml itself, so that cordova will do the work of copying
/moving them around to wherever you specify.

**Comment by bmwertman** [comment]
@fredgalvao so in my config.xml I have `<icon>` and `<splash>` tags in various resolutions which map to the launch icon and splash screen images in their `src` attribute. Is there an `<action>` tag?  how would I differentiate between different action buttons in my notification when I have multiple?

**Comment by fredgalvao** [comment]
I haven't tested this, and I was kinda refering to something else when I thougth made that comment: I was thinking about the `resource-file` that is available to the `plugin.xml` sintax. However, over further investigation, that same tag is not available to users through `config.xml` yet. Sorry on that part.

Nevertheless, I'd say it might be possible to trick cordova into copying an image thinking it's supposed to be used as an icon, but actually not. That would have you declaring your extra images as icons for whatever pixel density you want (or none/all) so that it'd copy the image. I don't know what it'll do about duplicate tags for the same (platform, density), but worth a try imo.

PS: Please create an issue on cordova so that they might add this tag to `config.xml`. I'm sure a hundred developers would +1 it in a blink of an eye.: http://cordova.apache.org/contribute/issues.html

**Comment by bmwertman** [comment]
Yeah I'm not sure what would keep Cordova from confusing the other images for the launch icon image if using the `<icon>` tag to copy them in. But I'll be sure to add an issue/feature request for some type of `<action>` tag. No doubt it would be appreciated by many.
