### ISSUE TITLE
Question about receiving Notification in WINDOWS Desktop / Phone

### ISSUE THREAD

**Issue by appzer** [phonegap/phonegap-plugin-push#1448]
Hello,

which script / function in this Plugin is called when a notification arrives, whether the app is open or closed.

I want to insert the message in a tile update!

This is working fine when i insert my code in the push.on('notification') handler.
But not when the app is closed.

It can also be a native function that is called.
Can someone help me.

Thanks Kevin

**Comment by fredgalvao** [comment]
For the `notification` event to be triggered and handled by your application's code regardless of whether the app was open or on background when it arrived, you need to send it as a background notification. You can check the docs on how to do this for `windows` [here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications-2). Overall details on what happens during background are described [here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#push-message-arrives-with-app-in-background).

**Comment by appzer** [comment]
thanks for the info.
But now i send the tile and toast notification directly over the WINDOWS WNS service.

Kevin
