### ISSUE TITLE
Missing Push Notification Entitlement: Phonegap build error

### ISSUE THREAD

**Issue by w3irdo** [phonegap/phonegap-plugin-push#1449]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by w3irdo** [comment]
hi, looks like phonegap build has changed or updated something. Forum feedback tat since 2 days ago, Push on ios stopped working due to Missing Push Notification Entitlement error during submission to itune. 

Seems likely this plugin needs to be updated too

**Comment by macdonst** [comment]
@w3irdo please, please, please fill out the issue template. Don't just leave the default info. 

Also, read this: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md#phonegap-build-support

**Comment by mobileias** [comment]
we have also same issue.

Since last 8th Dec 2016 till now.

As previous just one day we have already created new build and it working fine.
Just after one day we rebuild with same type code and app give above type error.
Any one have solution please ?

**Comment by w3irdo** [comment]
this is closed. pls refer here https://github.com/phonegap/phonegap-plugin-push/issues/1452
