### ISSUE TITLE
iOS Compilation error using 1.9.1 version

### ISSUE THREAD

**Issue by diegocst90** [phonegap/phonegap-plugin-push#1450]
Hello,

Recently our push notifications stop working on iOS 10 so we decided to upgrade our version from 1.8.4 to 1.9.1.

After a hard time trying to install CocoaPods, we were able to install the plugin nevertheless, when we compile our iOS app and try to run it using Xcode v. 8.1, on a device or emulator, it throws an error (explained lines below)

### Expected Behaviour

App should compile and run on a device or emulator

### Actual Behaviour

"Apple Mach-O Linker(id) Error"

`Ld /Users/diegocastillorios/Library/Developer/Xcode/DerivedData/Wishfinity-gnwzyutynojxfybuofvonuduyylq/Build/Products/Debug-iphoneos/Wishfinity.app/Wishfinity normal arm64
    cd /Applications/MAMP/htdocs/mobile-apps/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk -L/Users/diegocastillorios/Library/Developer/Xcode/DerivedData/Wishfinity-gnwzyutynojxfybuofvonuduyylq/Build/Products/Debug-iphoneos -L/Applications/MAMP/htdocs/mobile-apps/platforms/ios/Pods/GGLInstanceID/Libraries -L/Applications/MAMP/htdocs/mobile-apps/platforms/ios/Pods/GoogleCloudMessaging/Libraries -L/Applications/MAMP/htdocs/mobile-apps/platforms/ios/Wishfinity/Plugins/cordova-plugin-google-analytics -F/Users/diegocastillorios/Library/Developer/Xcode/DerivedData/Wishfinity-gnwzyutynojxfybuofvonuduyylq/Build/Products/Debug-iphoneos -F/Applications/MAMP/htdocs/mobile-apps/platforms/ios/Pods/GoogleIPhoneUtilities/Frameworks -F/Applications/MAMP/htdocs/mobile-apps/platforms/ios/Pods/GoogleInterchangeUtilities/Frameworks/frameworks -F/Applications/MAMP/htdocs/mobile-apps/platforms/ios/Pods/GoogleSymbolUtilities/Frameworks/frameworks -F/Applications/MAMP/htdocs/mobile-apps/platforms/ios/Pods/GoogleUtilities/Frameworks/frameworks -FWishfinity/Plugins/cordova-fabric-plugin -filelist /Users/diegocastillorios/Library/Developer/Xcode/DerivedData/Wishfinity-gnwzyutynojxfybuofvonuduyylq/Build/Intermediates/Wishfinity.build/Debug-iphoneos/Wishfinity.build/Objects-normal/arm64/Wishfinity.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/diegocastillorios/Library/Developer/Xcode/DerivedData/Wishfinity-gnwzyutynojxfybuofvonuduyylq/Build/Intermediates/Wishfinity.build/Debug-iphoneos/Wishfinity.build/Objects-normal/arm64/Wishfinity_lto.o -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -ObjC -ObjC -lGGLInstanceIDLib -lGcmLib -lsqlite3 -lz -framework AddressBook -framework CoreGraphics -framework GoogleIPhoneUtilities -framework GoogleInterchangeUtilities -framework GoogleSymbolUtilities -framework GoogleUtilities -framework SystemConfiguration /Users/diegocastillorios/Library/Developer/Xcode/DerivedData/Wishfinity-gnwzyutynojxfybuofvonuduyylq/Build/Products/Debug-iphoneos/libCordova.a -weak_framework MessageUI -lz -lc++ -framework SystemConfiguration -weak_framework Security -framework Fabric -framework Crashlytics -weak_framework ImageIO -framework CoreLocation -framework AVFoundation -lGoogleAnalyticsServices -framework CoreData -lsqlite3 -weak_framework Social -framework AddressBook -lsqlite3 -lz -lPods-Wishfinity -Xlinker -dependency_info -Xlinker /Users/diegocastillorios/Library/Developer/Xcode/DerivedData/Wishfinity-gnwzyutynojxfybuofvonuduyylq/Build/Intermediates/Wishfinity.build/Debug-iphoneos/Wishfinity.build/Objects-normal/arm64/Wishfinity_dependency_info.dat -o /Users/diegocastillorios/Library/Developer/Xcode/DerivedData/Wishfinity-gnwzyutynojxfybuofvonuduyylq/Build/Products/Debug-iphoneos/Wishfinity.app/Wishfinity`

ERROR:
`ld: library not found for -lPods-Wishfinity
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

<img width="902" alt="screen shot 2016-12-10 at 6 10 29 pm" src="https://cloud.githubusercontent.com/assets/1117719/21076831/07364e46-bf04-11e6-8769-2b90dc8cfb89.png">

#### Steps to Reproduce 

Run:
`$ cordova build ios`
`Open Xcode and run it on a connected device`

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

phonegap-plugin-push 1.9.1 "PushPlugin"
ios: 4.3.0
cordova: 6.4.0

**Comment by macdonst** [comment]
@diegocst90 did you open the project or the workspace? You need to open the workspace in order for XCode to find the cocoapods file.

**Comment by samukt** [comment]
Got the same error here.

Opened the **.xcworkspace** and it worked perfectly.

**Comment by jcesarmobile** [comment]
When using CocoaPods you have to close the .xcodeproj and open the .xcworkspace
