### ISSUE TITLE
Push being replaced by previous in the Android Notification Area

### ISSUE THREAD

**Issue by jasonatt** [phonegap/phonegap-plugin-push#1451]
### Expected Behaviour
New Push should show with previous Push

### Actual Behaviour
New Push is being replaced with previous Push

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android: 4.4.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung

#### Cordova CLI version and cordova platform version

    cordova --version: Latest
    cordova platform version android: Latest

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   #1.8.3

**Comment by macdonst** [comment]
![ex1wekt](https://cloud.githubusercontent.com/assets/353180/20806688/ecc9f21a-b7c9-11e6-9f58-e94e693c6b60.png)

@jasonatt sorry (not sorry) to be a dick but the reason why is right here in the docs:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#stacking

**Comment by jasonatt** [comment]
@macdonst sorry did not know the term was called stacking but been over the docs and must have skipped that part. Thanks
