### ISSUE TITLE
IOS: Missing Push Notification Entitlement: Phonegap build error

### ISSUE THREAD

**Issue by w3irdo** [phonegap/phonegap-plugin-push#1452]
#### Error Message
Missing Push Notification Entitlement - Your app includes an API for Apple's Push Notification service, but the aps-environment entitlement is missing from the app's signature. To resolve this, make sure your App ID is enabled for push notification in the Provisioning Portal. Then, sign your app with a distribution provisioning profile that includes the aps-environment entitlement. This will create the correct signature, and you can resubmit your app. See "Provisioning and Development" in the Local and Push Notification Programming Guide for more information. If your app does not use the Apple Push Notification service, no action is required. You may remove the API from future submissions to stop this warning. If you use a third-party framework, you may need to contact the developer for information on removing the API.

#### Suggestion

hi, looks like phonegap build has changed or updated something. Forum(https://forums.adobe.com/thread/2248424) feedback tat since 9Dec, Push on ios stopped working due to Missing Push Notification Entitlement error during submission to itune. Push on android is working fine.

Seems likely this plugin needs to be updated too on Entitlements.plist

**Comment by jcesarmobile** [comment]
This is fixed in 1.9.x version of the plugin, you'll have to wait until phonegap build can use it

**Comment by w3irdo** [comment]
Hi, PGB might not update this year. Any solution for Push Plugin version 1.8.4 users? Used to be fine just 3 days ago

**Comment by mvestuto** [comment]
Suffering the same problem. Seconding the request for some sort of fix..anything..please.

**Comment by Jorij** [comment]
Same problem here, last week it worked, but not anymore with same config.
Is there any solution to get it work with PGB before it starts to supports 1.9.x?

We should be updating some minor issues to our application, but this is preventing us to do it.

**Comment by mlabarca** [comment]
There's a workaround in the adobe forum posted above: https://forums.adobe.com/thread/2248424 Basically you export the entitlements.plist file from the failed .app and then re-sign it using it the 'iresign app'. This means you need a mac with the installed certificate and the mobile provision file. If you do have a mac or use a service like macincloud.com  you can also look up how to locally build and sign, it'll probably take less time than waiting for phonegap build. I managed to send this for review this once using the iresign workaround but I'm thinking of switching to local builds for next release to avoid these issues. 🙃

**Comment by noveweb** [comment]
Hi!
Any solution without workaround?

**Comment by mvestuto** [comment]
I've haven't had any issues with the latest version of PGB and the latest version of the plugin. Everything seems fine lately. Are you still having problems?

**Comment by noveweb** [comment]
@mvestuto I don't know what I'm doing wrong, but the error Missing Push Notification Entitlement persists. Look: https://forums.adobe.com/message/9718749#9718749

For Android works fine, but IOS not.

Can you help me?

**Comment by mvestuto** [comment]
If you are confident that you're building it with the right certs, push certs and provision profile then the issue may be with phonegap. I noticed sometimes that apps dont build right for a few days and entitlements dont get included. If I wait a few days or a week, the build is fine. Please check your certs and provision profile again though.

**Comment by noveweb** [comment]
All my certificates still ok. Im using Phonegap latest cli-6.5.0 + push plugin spec 1.9.4 and you?

**Comment by mvestuto** [comment]
Here are the juicy parts from my web config.
![image](https://user-images.githubusercontent.com/22959489/28533439-b9b98398-7062-11e7-9784-3661587cc30b.png)

![image](https://user-images.githubusercontent.com/22959489/28533392-8fe6c08a-7062-11e7-86b6-09e3652a8e6c.png)

This is a screenshot of the module.exports metadata in the cordova_plugins file in the payload. This is the version of the plugin that's actually rolled in:
![image](https://user-images.githubusercontent.com/22959489/28533529-0ce6be1e-7063-11e7-932c-68bcb990343a.png)
