### ISSUE TITLE
ionic cordova (android) app closing without any message or exception 

### ISSUE THREAD

**Issue by haresh333** [phonegap/phonegap-plugin-push#1453]
### Expected Behaviour
1. I have cordova/ionic app running on android.
2. When I call '$cordovaCamera.getPicture' to select picture from gallery of phone, the app closes/crashes without any message or exception in logs.
3 This behaviour I have NEVER seen on MOST devices. 
4. BUT its there ALMOST ALWAYS reproducable on Sony Experia

### Actual Behaviour
App Crash without any msg or exception

### Reproduce Scenario (including but not limited to)
NA
#### Steps to Reproduce 
Call API to select Image - as shown in code snippet

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Sony Experia

#### Cordova CLI version and cordova platform version

cordova 6.4
cordova-android android 5.1.1

#### Plugin version
cordova-plugin-camera 2.2.0 "Camera"

#### Sample Push Data Payload
NA

#### Sample Code that illustrates the problem
    $scope.upload = function() {
      var options = {
        quality: 50,
        destinationType: Camera.DestinationType.FILE_URI,
        sourceType: Camera.PictureSourceType.PHOTOLIBRARY,
        allowEdit: false,
        encodingType: Camera.EncodingType.JPEG,
        mediaType : Camera.MediaType.PICTURE,
        saveToPhotoAlbum: false,
        correctOrientation: true,
        //targetWidth: 500, 
        //targetWidth: 500,
      };

      try {
        $cordovaCamera.getPicture(options)
          .then(function (imageURI) {
            $scope.profilePic.src = imageURI;
          }, function (err) {
            console.log(err);
          });
      }
      catch (exception)
      {
        commonServices.alert("An error occurred while selecting message: " + exception);
      }
    }

#### Logs taken while reproducing problem
Attached is Logcat logs;
It shows 2 exceptions which may be of importance
1. SQLLite exception - I am not sure if it is related. But it comes every time
2. NullPointerExceotion - I am not sure again if this is related? I have seen this in logcat once when I took log.
[logcat.txt](https://github.com/phonegap/phonegap-plugin-push/files/645751/logcat.txt)
[logcat1.txt](https://github.com/phonegap/phonegap-plugin-push/files/645752/logcat1.txt)

**Comment by macdonst** [comment]
@haresh333 this is the push plugin, not the camera plugin. You should raise an issue on JIRA. 

https://issues.apache.org/jira/browse/CB/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel
