### ISSUE TITLE
Notification icon not set on Android 6 devices

### ISSUE THREAD

**Issue by markeh** [phonegap/phonegap-plugin-push#1454]
### Expected Behaviour
App icon should show in the notification

### Actual Behaviour
White box icon appears, icon cannot be set via android options or the fcm post data

### Reproduce Scenario (including but not limited to)
create ionic project
run - ionic plugin add phonegap-plugin-push@1.9.1
add icon.png to resources folder
run - ionic resources

#### Steps to Reproduce 
run app on device and subscribe to topic
send fcm json and observe notification on app

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6 & 6.0.1 

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Ulefone Power / OnePlusOne

#### Cordova CLI version and cordova platform version
cordova --version 6.4.0
cordova platform version android 6.0.0

#### Plugin version
cordova plugin version | grep phonegap-plugin-push - tried both 1.8.4 / 1.9.1

#### Sample Push Data Payload
{  
   "data":{  
      "title":"Title",
      "body":"body"
   },
   "notification":{  
      "title":"Title",
      "body":"body",
      "content_available": true
   },
   "to":"/topics/group"
}

#### Sample Code that illustrates the problem
         var options = {
            android: {
              senderID: "10000000000",
              "icon": "icon", //tried with and without, no effect
              "iconColor": "blue" //tried with and without, no effect
            },

**Comment by macdonst** [comment]
@markeh what does you icon look like cause if it doesn't have transparent pixels then the behaviour you mention sounds correct.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images

**Comment by fredgalvao** [comment]
Also, `phonegap-plugin-push@1.9.1` does not support FCM yet. The incoming 2.0 version of the plugin will fix that part (although I'm not sure if the image issue you're seeing has anything to do with this).

**Comment by markeh** [comment]
apologies @macdonst you're right, I had tried with a transparent icon but the original non-transparent had been cached and resources was using that. Works correctly now, thankyou

**Comment by markeh** [comment]
thanks for the info @fredgalvao
