### ISSUE TITLE
IOS build faild with error ld: library not found for -lPods-

### ISSUE THREAD

**Issue by kingkarki** [phonegap/phonegap-plugin-push#1455]
### Expected Behaviour
run on iOS device and get device token for push notificaiton
### Actual Behaviour
**ld: library not found for -lPods-Winglists
clang: error: linker command failed with exit code 1 (use -v to see invocation)**
```
Ld /Users/krishnak/Library/Developer/Xcode/DerivedData/Winglists-bwpajgezaxilqldfzumxfqqqibmc/Build/Products/Debug-iphoneos/Winglists.app/Winglists normal armv7
    cd /Applications/apps/winglists/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk -L/Users/krishnak/Library/Developer/Xcode/DerivedData/Winglists-bwpajgezaxilqldfzumxfqqqibmc/Build/Products/Debug-iphoneos -L/Applications/apps/winglists/platforms/ios/Pods/GGLInstanceID/Libraries -L/Applications/apps/winglists/platforms/ios/Pods/GoogleCloudMessaging/Libraries -F/Users/krishnak/Library/Developer/Xcode/DerivedData/Winglists-bwpajgezaxilqldfzumxfqqqibmc/Build/Products/Debug-iphoneos -F/Applications/apps/winglists/platforms/ios/Pods/GoogleIPhoneUtilities/Frameworks -F/Applications/apps/winglists/platforms/ios/Pods/GoogleInterchangeUtilities/Frameworks/frameworks -F/Applications/apps/winglists/platforms/ios/Pods/GoogleSymbolUtilities/Frameworks/frameworks -F/Applications/apps/winglists/platforms/ios/Pods/GoogleUtilities/Frameworks/frameworks -FWinglists/Plugins/cordova-plugin-facebook4 -filelist /Users/krishnak/Library/Developer/Xcode/DerivedData/Winglists-bwpajgezaxilqldfzumxfqqqibmc/Build/Intermediates/Winglists.build/Debug-iphoneos/Winglists.build/Objects-normal/armv7/Winglists.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/krishnak/Library/Developer/Xcode/DerivedData/Winglists-bwpajgezaxilqldfzumxfqqqibmc/Build/Intermediates/Winglists.build/Debug-iphoneos/Winglists.build/Objects-normal/armv7/Winglists_lto.o -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -ObjC -ObjC -lGGLInstanceIDLib -lGcmLib -lsqlite3 -lz -framework AddressBook -framework CoreGraphics -framework GoogleIPhoneUtilities -framework GoogleInterchangeUtilities -framework GoogleSymbolUtilities -framework GoogleUtilities -framework SystemConfiguration /Users/krishnak/Library/Developer/Xcode/DerivedData/Winglists-bwpajgezaxilqldfzumxfqqqibmc/Build/Products/Debug-iphoneos/libCordova.a -framework Bolts -framework FBSDKCoreKit -framework FBSDKLoginKit -framework FBSDKShareKit -weak_framework SystemConfiguration -framework CoreTelephony -weak_framework Social -weak_framework MessageUI -framework AddressBook -lsqlite3 -lz -lPods-Winglists -Xlinker -dependency_info -Xlinker /Users/krishnak/Library/Developer/Xcode/DerivedData/Winglists-bwpajgezaxilqldfzumxfqqqibmc/Build/Intermediates/Winglists.build/Debug-iphoneos/Winglists.build/Objects-normal/armv7/Winglists_dependency_info.dat -o /Users/krishnak/Library/Developer/Xcode/DerivedData/Winglists-bwpajgezaxilqldfzumxfqqqibmc/Build/Products/Debug-iphoneos/Winglists.app/Winglists

ld: library not found for -lPods-Winglists
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

#### Steps to Reproduce 
cordova platform add ios 
cordova plugin add phonegap-plugin-push --variable SENDER_ID="xxx"
cordova build ios
and run app on ios device or simulator from xcode

#### Cordova CLI version and cordova platform version

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 1.1.0
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.9.0 
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v4.0.0
Xcode version: Xcode 8.1 Build version 8B62 

#### Plugin version
phonegap-plugin-push 1.9.1 "PushPlugin"

#### other plugins used 
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-x-socialsharing 5.0.12 "SocialSharing"
cordova-sqlite-storage 1.4.1 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.0 "Keyboard"
phonegap-plugin-push 1.9.1 "PushPlugin"

I also tried with plugin version 1.8.0 in same environment but app doesn't return device token with 1.8.0. 

Please suggest me how to fix this issue.

**Comment by distante** [comment]
PushPlugin uses [Cocoa Pods](https://cocoapods.org/
) now, once it is installed you can not run your regular `yourProjectName.xcodeproj` file you must open a new file that was creating after you installed PushPlugin called `yourProjectName.l.xcworkspace`.

**Comment by kingkarki** [comment]
**OMG** Thank you so much @distante you saved my day. Now what happens to  my regular  yourProjectName.xcodeproj? which project i should submit to appstore .xcodeproj or .xcworkspace? Also now it shows 2 projects on xcode when i open .xcworkspace. 1 with project name 2 with name Pods. Can you provide me few more information please. Thanks

**Comment by distante** [comment]
@kingkarki The one with your project name. Just to everything like you did before, you just have to open the workspace, build your project/archive it and upload it.

**Comment by kingkarki** [comment]
ok Thank you very much  @distante

**Comment by kirillgroshkov** [comment]
saved me!
