### ISSUE TITLE
Notifications get deleted after leave the app [Android]

### ISSUE THREAD

**Issue by distante** [phonegap/phonegap-plugin-push#1456]
### Expected Behaviour
- The devices receives 3 notifications.
- The user clicks on one of those.
- App loads and shows content.
- User go to the devices home screen.
- 2 Notifications are still on the notifications drawer.

### Actual Behaviour
- The devices receives 3 notifications.
- The user clicks on one of those.
- App loads and shows content.
- User go to the devices home screen.
- All notifications from the app disappears.

#### Steps to Reproduce 
- Send more than 1 push notification
- Open one of those
- Exit app

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Tested on Android 5.1.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
OnePlus One
#### Cordova CLI version and cordova platform version

    cordova --version              6.4.0
    cordova platform version android     6.0.0

#### Plugin version

    cordova plugin version 1.9.1

**Comment by fredgalvao** [comment]
Chek [this section of the docs](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#android), more specifically the `android.clearNotifications` attribute. Try calling `init()` passing it as `false`, and see if that's what you wanted.

**Comment by macdonst** [comment]
I'm going to assume this is closed with @fredgalvao answer.
