### ISSUE TITLE
How can i take windows front end build from a cordova application with wns details included?

### ISSUE THREAD

**Issue by suja-balan** [phonegap/phonegap-plugin-push#1457]
I am developing a cross platform mobile application using angular js. In windows 10 we were taking build from visual studio after creating a cordova application.

Currently we need to implement push notification in all platforms.We are using pushsharp dll in middleware for push notifications.In IOS and android it was working successfully.

But in windows 10 i dont know how to take build for windows with those client SID,Secret key etc(for push notification) . While searching links it was given that change in appmanifest file.But here i couldnot see any file like that.

How can i take the build with the push notification details included ? Can anyone help me to solve this?

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
