### ISSUE TITLE
push.on('notification') not called from cold start on windows phone universal

### ISSUE THREAD

**Issue by nates-dennis** [phonegap/phonegap-plugin-push#1458]
### Expected Behaviour
on('notification') to be called after init with launchArgs when launching app from notification
### Actual Behaviour
init called but not on('notification')
### Reproduce Scenario (including but not limited to)
App is in cold start (removed from app tray) a notification comes in the user will tap on the notification which will launch the app and be directed to a specific screen 
#### Steps to Reproduce 
launch the app 
login to the app
put the app into cold start
receive a push notification 
tap on the notification 
app launches to the home screen
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
windows phone 10 (works on windows phone 8.1)
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Microsoft Lumia 650
#### Cordova CLI version and cordova platform version
    cordova --version     6.1.1
    cordova platform version Windows 4.3.2
#### Plugin version
    cordova plugin version | grep phonegap-plugin-push  1.8.2
#### Sample Push Data Payload
toast launch="xyz"
	visual
		binding template="ToastText02"
			text id="1">New Message text
			text id="2">UPDATED: Text text
		binding
	visual
toast
#### Sample Code that illustrates the problem
default handling of push notification as stated in the documentation 
#### Logs taken while reproducing problem
n/a

**Comment by nates-dennis** [comment]
updating the version fixed the issue which i found here 
http://stackoverflow.com/questions/41124990/push-onnotification-not-called-from-cold-start-on-windows-phone-universal-on

**Comment by fredgalvao** [comment]
> You need to use cordova-windows@4.4+ as it has CB-11658 activated event is not fired issue fixed.
> For coldstart you should use toast' launch attribute and subscribe to activated cordova event.

@macdonst  Should we bump [platform support](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PLATFORM_SUPPORT.md) because of that?
