### ISSUE TITLE
iconColor does not set icon background on Android

### ISSUE THREAD

**Issue by kwebble** [phonegap/phonegap-plugin-push#146]
To set the background color for the notification icon on Android I have set iconColor like this:

    var push = PushNotification.init(
                   { android: { senderID: api.gcmSenderId
                              , iconColor: 'red'
                              }
                   , ios:     {}
                   , windows: {}
                   })

I have tried color values like 'red', 'blue'  and #RRGGBB values, but in a notification the result is always the default gray color. 

Is there something else required to set the background color of the icon?

I'm using version 1.2.3 of PushPlugin with Cordova 5.1.1.

**Comment by kwebble** [comment]
Perhaps, I'm not 100% sure, this only sets the color once, when registering. 

I changed the software that creates the notifications to include a color property with each notification.

**Comment by fredgalvao** [comment]
FYI, the iconColor [only applies to android Lollipop (5.0, sdk=21)](http://developer.android.com/reference/android/app/Notification.Builder.html#setColor(int)) and newer. Older versions will use their default theme for notifications unless you create it yourself.

**Comment by macdonst** [comment]
@kwebble Yeah, this will only set the background color on Android 5.0 and greater. I'll update the README to make it more explicit.
