### ISSUE TITLE
App crashes when initialising with topics (v2.0.0-rc1)

### ISSUE THREAD

**Issue by CookieCookson** [phonegap/phonegap-plugin-push#1461]
### Expected Behaviour
App should initialise push notifications with the FCM server.

### Actual Behaviour
App crashes out to home screen.

### Reproduce Scenario (including but not limited to)
?

#### Steps to Reproduce
1. Perform `window.PushNotification.init()` and pass through `topics` as an array of strings e.g.
```
window.PushNotification.init({
    ...
    topics: ['test']
...
});
```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.2 (Beta 8)

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Apple

#### Cordova CLI version and cordova platform version

cordova 6.4.0
cordova-ios 4.3.0

#### Plugin version

2.0.0-rc1

#### Sample Push Data Payload
N/A

#### Sample Code that illustrates the problem
```
window.PushNotification.init({
    ...
    topics: ['test']
...
});
```

#### Logs taken while reproducing problem
[19f1db496c063f52367708acab000543.log.txt](https://github.com/phonegap/phonegap-plugin-push/files/652180/19f1db496c063f52367708acab000543.log.txt)

**Comment by macdonst** [comment]
@CookieCookson it's fixed in the 2.0.x branch now. I believe I screwed up a merge. Thanks for raising the bug.
