### ISSUE TITLE
Create round bitmap icon for large icon image passed in from local resource or url

### ISSUE THREAD

**Issue by bmwertman** [phonegap/phonegap-plugin-push#1464]
I wanted the large icon in the push notification on Android to match the default Android style of being round instead of square.

I plugged the `getCircleBitmap` method shown in [this blog](http://curious-blog.blogspot.de/2014/05/create-circle-bitmap-in-android.html) into the GCMIntentService.java file. I've tested it on my Android L device and it converts the square icon to round with no issues.

I would like to create a pull request for this but because it is really a feature the PR prompts suggested creating an issue first.

**Comment by fredgalvao** [comment]
I think that's great, and maybe it can live behind a setting specific for android, passed on `init`. Also, it's important to double check if that compiles with lower android target SDKs.

**Comment by bmwertman** [comment]
I searched around to see when the large icon for push notifications became a standard feature on Android but as far as I could tell it has always been that way, at least back to Android 4. @fredgalvao  what is the best way to be certain that this will compile down to lower target SDK's?

As you will see in my commits to the PR I also initially thought that it should be a configurable setting. Although I tried to set it up as a property passed on `data` in the payload instead of on `init`. Something like `roundIcon: true`. 

I was having trouble getting a conditional setup properly to create the desired effect though. And the more I thought about it I couldn't think of a case where you wouldn't want the icon to match the others in the notification tray. So I'm a little more for just making it the default style.

Should I go ahead and make the PR for this and link back to this issue?

**Comment by fredgalvao** [comment]
Well, if it has been the standard since `sdk=14`, then I'm all for making it the default behaviour. I still am not sure if we should make it the **only** option.

As for the **compile** thing, it's just a good habit to try and compile it with a lower target sdk (like 14, if we want to make the previous point literal). I have seen situations where a new API was used on a project/plugin, but it wouldn't compile on lower versions, and the developer forgot to use the compat library for that, thus breaking the project. Basically, that means assuring that all classes/objects used on that new code of yours are present and available uniformly throughout all supported versions of the android sdk.

Considering both points above, I think we're/we'll be ready for the PR.

I'm now kinda surprised me never seeing my app icon as round as strange...

**Comment by bmwertman** [comment]
Sounds reasonable. For reference here is the method added in `GCMIntentService.java`. It only uses a few additional Classes from `android.graphics`. The [developer reference](https://developer.android.com/reference/android/graphics/package-summary.html) says they were  introduced in the level 1 API. Here is the method for reference;

```
private Bitmap getCircleBitmap(Bitmap bitmap) {
        final Bitmap output = Bitmap.createBitmap(bitmap.getWidth(), bitmap.getHeight(), Bitmap.Config.ARGB_8888);
        final Canvas canvas = new Canvas(output);
        final int color = Color.RED;
        final Paint paint = new Paint();
        final Rect rect = new Rect(0, 0, bitmap.getWidth(), bitmap.getHeight());
        final RectF rectF = new RectF(rect);

        paint.setAntiAlias(true);
        canvas.drawARGB(0, 0, 0, 0);
        paint.setColor(color);
        canvas.drawOval(rectF, paint);

        paint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.SRC_IN));
        canvas.drawBitmap(bitmap, rect, rect, paint);

        bitmap.recycle();

        return output;
    }
```

I'll go ahead and submit the PR now and if there are any concerns we can continue the discussion there.

**Comment by macdonst** [comment]
@bmwertman I'll comment in the PR but what I would like to see is when a push includes a large image there should be a boolean options to convert the image into a circular one.

**Comment by macdonst** [comment]
![screenshot_20170308-214947](https://cloud.githubusercontent.com/assets/353180/23733917/902a4650-0449-11e7-924e-d45a38030c74.png)

**Comment by macdonst** [comment]
Will be in 1.10.0
