### ISSUE TITLE
Duplicate notification from different SENDER_ID

### ISSUE THREAD

**Issue by TVolly** [phonegap/phonegap-plugin-push#1466]
My app has a plugin with the PushNotification service (for example Tapjoy). It receives pushes only from its own SENDER_ID.
Your plugin catches and displays all the pushes including other undesirable SENDER_IDs.
Thus, when those plugins (Tapjoy and others) send a push, it is being caught by two push services, and as a result I get 2 identical pushes .

Question: Is it possible to set a limit list of SENDER_ID so that your plugin could ignore it?
For example: add filter by "from" here:
https://github.com/phonegap/phonegap-plugin-push/blob/master/src/android/com/adobe/phonegap/push/GCMIntentService.java#L64

**Comment by macdonst** [comment]
@TVolly yeah, it's possible but why do you have two services to receive push messages?

**Comment by TVolly** [comment]
These plugins with different functionals. 
Push notification of that plugin is a bonus to its other features.
When a push sending from their service, it will be better if that notification would be catching by their plugin.
When a push sending from the server, that notification would be catching by your plugin

**Comment by macdonst** [comment]
@TVolly uh sure. It's possible but it's not a high priority for me right now but pull requests are always welcome.

**Comment by TVolly** [comment]
@macdonst I've sent a pull request with solution of this issue. We’re using your wonderful plugin as a dependency in our apps, so this issue is critical for us. Could you please review it? If there is something wrong we will fix it asap.

**Comment by macdonst** [comment]
It will be part of 1.10.0.
