### ISSUE TITLE
Cannot install phonegap-plugin-push on master

### ISSUE THREAD

**Issue by CookieCookson** [phonegap/phonegap-plugin-push#1470]
### Expected Behaviour
Plugin to be installed successfully

### Actual Behaviour
Cordova CLI throws an undefined error

### Reproduce Scenario (including but not limited to)
N/A

#### Steps to Reproduce 
`cordova plugin add https://github.com/phonegap/phonegap-plugin-push#1b17756ea5e7f3e33de7f1852737e66e909dc9c0`

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
All

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
N/A

#### Cordova CLI version and cordova platform version

cordova 6.4.0
cordova-android 6.1.0

#### Plugin version

From master
(https://github.com/phonegap/phonegap-plugin-push/commit/1b17756ea5e7f3e33de7f1852737e66e909dc9c0)

#### Sample Push Data Payload
N/A

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem

![screen shot 2016-12-16 at 09 56 20](https://cloud.githubusercontent.com/assets/3473396/21258862/dcf1f532-c376-11e6-998d-3aa8c808f2c8.png)

**Comment by jcesarmobile** [comment]
do you have the google-services.json in www folder?

**Comment by CookieCookson** [comment]
I do, and it's exported from the Firebase dashboard.

**Comment by jcesarmobile** [comment]
I think the error message is wrong and you should put it in the root of the project, not in www (looking into the hook code)

**Comment by jcesarmobile** [comment]
No, I think it was just a mistake, and hooks doesn't work on PGB
