### ISSUE TITLE
InvalidRegistration problem when sending a msg to GCM

### ISSUE THREAD

**Issue by stefantry** [phonegap/phonegap-plugin-push#1472]
Hey guys,
I'm trying to add phonegap-plugin-push to my app, however I'm running into a problem when trying to send a push notifications to GCM.

I'm sending this message to: https://fcm.googleapis.com/fcm/send
`{"to":"egvwoOGQPXQ:APA91bHZyTsph3y6pwCxirG9mWZgVLJ_VEzISVa953BvnvNI6WQJCVsqgEnUYt8IOuWuTnvWqeAxoJ2exY5j6ImOcYgYw3qGx82rBKDScUhLgv6fwwMlqEXCR7XUJWV35p8ESEM9H0y","data":{"message":"Push Notification Message","title":"Push Notification Title","vibrate":1,"sound":1}}`
With a correct server key and content type header.

Where the "to" is the GCM code I obtained using your plugin. I also tried using registration_ids with an array only containg this ID.

Then in the end I get the message:
`{"multicast_id":5382822473434480707,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"InvalidRegistration"}]}`

So I verified all these steps:
- Changing my sender_id to make sure my gcm project ID is correct (I only get result with a correct ID)
- Changing the Autorization key in the push request. This checked out.
- Changing the GCM code. I removed a letter. Then I got a msg the code wasn't correct.

So I figured all steps are good and I have no clue what is going wrong. Perhaps a sandbox mode I'm not aware of?

Testing on android. I got the GCM code printed in the register method in my app.

Versions:
phonegap-plugin-push 1.9.2
phonegap --v: 6.4.2
Got all android SDK's installed available. Just in case.

Thanks guys!

**Comment by macdonst** [comment]
@stefantry it's definitely a mis-match between the sender ID you are registering with and the API key. When Google reports that error the two are from different projects. 

How do you add the push plugin to the project?

**Comment by stefantry** [comment]
I figured it out. It indeed had something to do with the api key. I used this link to help me further. Thanks!
https://support.pushcrew.com/support/solutions/articles/9000064351-setting-up-your-fcm-keys-previously-called-gcm-
