### ISSUE TITLE
Version 1.9.2 not on npm registry (still 1.8.4)

### ISSUE THREAD

**Issue by sebrojas14** [phonegap/phonegap-plugin-push#1473]

**Comment by fredgalvao** [comment]
`npm info phonegap-plugin-push` shows me this:
```js
{ name: 'phonegap-plugin-push',
  description: 'Register and receive push notifications.',
  'dist-tags': { latest: '1.9.2' },
...
```
https://www.npmjs.com/package/phonegap-plugin-push shows me:
`1.9.2 is the latest of 36 releases`


Where exactly did you see **1.8.4** as the frontline version?

**Comment by sebrojas14** [comment]
I can't install the 1.9.2 version, if I left without version, cordova installas 1.8.4, if I specify la version #1.9.2, I get Error: Registry returned 404..

**Comment by sebrojas14** [comment]
It was because of the cordova android version
