### ISSUE TITLE
Android: force-start starts the app in Foreground instead of Background

### ISSUE THREAD

**Issue by VinceOPS** [phonegap/phonegap-plugin-push#1474]
Hi guys, I discovered what looks like a bug on Android, as I gave more details here https://github.com/phonegap/phonegap-plugin-push/issues/1402#issuecomment-267629692.

### Expected Behaviour
When the app has been killed (force-closed), and a notification with `force-start` is sent, the device should starts the app again in the **background**.

### Actual Behaviour
The device starts the app again in the **foreground**.

### Reproduce Scenario (including but not limited to)
Using plugin version 1.9.2 (1.9.0 was working well), receiving any force-start notification.

#### Steps to Reproduce
Use version 1.9.2 (1.9.0 is not suffering from this bug).
Kill your app.
Send yourself a push notification using `force-start`.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5+ and 6+ (not tested on 4+).

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung (Galaxy A5 2016, Galaxy S7) and LG (Nexus 5)

#### Cordova CLI version and cordova platform version

    cordova --version
**6.4.0**

    cordova platform version android
**6.1.0**

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push
**1.9.2**

If I can be of any help, please let me know :-).

Thanks.

**Comment by macdonst** [comment]
@VinceOPS can you grab some logs while reproducing the problem?

`adb logcat | grep PushPlugin`

**Comment by macdonst** [comment]
@VinceOPS I believe I've fixed the issue. Can you install the latest from master and just give it another try for me?

**Comment by VinceOPS** [comment]
Hi @macdonst. Sorry for the late answer. Xmas holidays :-).

Your commit does fix the behavior I described, when app is force-closed. 
**But** if the app is just sent in the background,  and I receive a new notification, then the app is set in the foreground automatically. 
**Plus**, if the app is in the foreground, a notification is still created, instead of simply "silently" calling my event handler.

Let me know if I can be of any help. Thanks!

**Comment by macdonst** [comment]
@VinceOPS okay cool, thanks for looking at it. I wanted to try and get you something before Xmas as I'd be taking some time off as well. I'll look at the remaining issue soonish and get a 1.9.x release out. 

What would really help me is if you post an example of your push payload just so I'm comparing 🍎 's to 🍎 's.

**Comment by VinceOPS** [comment]
Here are more details:

From `cordova plugin add https://github.com/phonegap/phonegap-plugin-push` (to use `master`).

# App in the background, receiving a notification
The app is automatically set in foreground (shouldn't), a notification is created (shouldn't), but the JS event handler is not triggered (should?).

Logs:

> D/PushPlugin_GCMIntentService(13443): onMessage - from: [removed]
> D/PushPlugin_GCMIntentService(13443): normalize extras
> D/PushPlugin_GCMIntentService(13443): key = google.sent_time
> D/PushPlugin_GCMIntentService(13443): replace key google.sent_time with google.sent_time
> D/PushPlugin_GCMIntentService(13443): key = force-start
> D/PushPlugin_GCMIntentService(13443): replace key force-start with force-start
> D/PushPlugin_GCMIntentService(13443): key = priority
> D/PushPlugin_GCMIntentService(13443): replace key priority with priority
> D/PushPlugin_GCMIntentService(13443): key = payload
> D/PushPlugin_GCMIntentService(13443): replace key payload with payload
> D/PushPlugin_GCMIntentService(13443): key = title
> D/PushPlugin_GCMIntentService(13443): replace key title with title
> D/PushPlugin_GCMIntentService(13443): **no locale found for key = title, error Value NEW of type java.lang.String cannot be converted to JSONObject**
> D/PushPlugin_GCMIntentService(13443): key = google.message_id
> D/PushPlugin_GCMIntentService(13443): replace key google.message_id with google.message_id
> D/PushPlugin_GCMIntentService(13443): key = message
> D/PushPlugin_GCMIntentService(13443): replace key message with message
> D/PushPlugin_GCMIntentService(13443): **no locale found for key = message, error Value HELLO of type java.lang.String cannot be converted to JSONObject**
> D/PushPlugin_GCMIntentService(13443): key = ledColor
> D/PushPlugin_GCMIntentService(13443): replace key ledColor with ledColor
> D/PushPlugin_GCMIntentService(13443): key = collapse_key
> D/PushPlugin_GCMIntentService(13443): replace key collapse_key with collapse_key
> D/PushPlugin_GCMIntentService(13443): background
> D/PushPlugin_GCMIntentService(13443): message =[HELLO]
> D/PushPlugin_GCMIntentService(13443): title =[NEW MESSAGE from VinceOPS]
> D/PushPlugin_GCMIntentService(13443): contentAvailable =[null]
> D/PushPlugin_GCMIntentService(13443): **forceStart** =[1]
> D/PushPlugin_GCMIntentService(13443): create notification
> E/PushPlugin_GCMIntentService(13443): Number format exception - Error parsing notId: Invalid int: "null"
> D/PushPlugin_GCMIntentService(13443): stored icon=null
> D/PushPlugin_GCMIntentService(13443): stored iconColor=#343434
> D/PushPlugin_GCMIntentService(13443): stored sound=true
> D/PushPlugin_GCMIntentService(13443): stored vibrate=true
> D/PushPlugin_GCMIntentService(13443): no icon resource found - using application icon
> D/PushPlugin_GCMIntentService(13443): create actions: with in-line
> D/PushPlugin_GCMIntentService(13443): **app is not running but we should start it and put in background**
> D/PushPlugin_PushHandlerActivity(13443): not id = 0
> V/PushPlugin_PushHandlerActivity(13443): onCreate
> D/PushPlugin_PushHandlerActivity(13443): callback = null
> V/PushPlugin(13443): sendExtras: caching extras to send at a later time.
> D/PushPlugin_PushHandlerActivity(13443): bringToForeground = false
> D/PushPlugin_PushHandlerActivity(13443): isPushPluginActive = false
> D/PushPlugin_PushHandlerActivity(13443): startOnBackgroundTrue


### When clicking on the notification (in the notification center) with app in the FOREGROUND:

> D/PushPlugin_PushHandlerActivity(13443): not id = 0
> V/PushPlugin_PushHandlerActivity(13443): onCreate
> D/PushPlugin_PushHandlerActivity(13443): callback = null
> V/PushPlugin(13443): sendExtras: caching extras to send at a later time.
> D/PushPlugin_PushHandlerActivity(13443): bringToForeground = true
> D/PushPlugin_PushHandlerActivity(13443): isPushPluginActive = false
> D/PushPlugin_PushHandlerActivity(13443): forceMainActivityReload

JS Handler **still** not triggered :(

# App killed, receiving a notification

App is started in background (good), notification is created (good).

LOGS

> D/PushPlugin_GCMIntentService(13939): onMessage - from: [removed]
> D/PushPlugin_GCMIntentService(13939): normalize extras
> D/PushPlugin_GCMIntentService(13939): key = google.sent_time
> D/PushPlugin_GCMIntentService(13939): replace key google.sent_time with google.sent_time
> D/PushPlugin_GCMIntentService(13939): key = force-start
> D/PushPlugin_GCMIntentService(13939): replace key force-start with force-start
> D/PushPlugin_GCMIntentService(13939): key = priority
> D/PushPlugin_GCMIntentService(13939): replace key priority with priority
> D/PushPlugin_GCMIntentService(13939): key = payload
> D/PushPlugin_GCMIntentService(13939): replace key payload with payload
> D/PushPlugin_GCMIntentService(13939): key = title
> D/PushPlugin_GCMIntentService(13939): replace key title with title
> D/PushPlugin_GCMIntentService(13939): no locale found for key = title, error Value NEW of type java.lang.String cannot be converted to JSONObject
> D/PushPlugin_GCMIntentService(13939): key = google.message_id
> D/PushPlugin_GCMIntentService(13939): replace key google.message_id with google.message_id
> D/PushPlugin_GCMIntentService(13939): key = message
> D/PushPlugin_GCMIntentService(13939): replace key message with message
> D/PushPlugin_GCMIntentService(13939): no locale found for key = message, error Value hmmmm of type java.lang.String cannot be converted to JSONObject
> D/PushPlugin_GCMIntentService(13939): key = ledColor
> D/PushPlugin_GCMIntentService(13939): replace key ledColor with ledColor
> D/PushPlugin_GCMIntentService(13939): key = collapse_key
> D/PushPlugin_GCMIntentService(13939): replace key collapse_key with collapse_key
> D/PushPlugin_GCMIntentService(13939): background
> D/PushPlugin_GCMIntentService(13939): message =[hmmmm]
> D/PushPlugin_GCMIntentService(13939): title =[NEW MESSAGE from VinceOPS]
> D/PushPlugin_GCMIntentService(13939): contentAvailable =[null]
> D/PushPlugin_GCMIntentService(13939): forceStart =[1]
> D/PushPlugin_GCMIntentService(13939): create notification
> E/PushPlugin_GCMIntentService(13939): Number format exception - Error parsing notId: Invalid int: "null"
> D/PushPlugin_GCMIntentService(13939): stored icon=null
> D/PushPlugin_GCMIntentService(13939): stored iconColor=#343434
> D/PushPlugin_GCMIntentService(13939): stored sound=true
> D/PushPlugin_GCMIntentService(13939): stored vibrate=true
> D/PushPlugin_GCMIntentService(13939): no icon resource found - using application icon
> D/PushPlugin_GCMIntentService(13939): create actions: with in-line
> D/PushPlugin_GCMIntentService(13939): app is not running but we should start it and put in background
> D/PushPlugin_PushHandlerActivity(13939): not id = 0
> V/PushPlugin_PushHandlerActivity(13939): onCreate
> D/PushPlugin_PushHandlerActivity(13939): callback = null
> V/PushPlugin(13939): sendExtras: caching extras to send at a later time.
> D/PushPlugin_PushHandlerActivity(13939): bringToForeground = false
> D/PushPlugin_PushHandlerActivity(13939): isPushPluginActive = false
> D/PushPlugin_PushHandlerActivity(13939): startOnBackgroundTrue  
  

### App in the background, clicking on the notification (in the notification center)

LOGS

> D/PushPlugin_PushHandlerActivity(13939): not id = 0
> V/PushPlugin_PushHandlerActivity(13939): onCreate
> D/PushPlugin_PushHandlerActivity(13939): callback = null
> V/PushPlugin(13939): sendExtras: caching extras to send at a later time.
> D/PushPlugin_PushHandlerActivity(13939): bringToForeground = true
> D/PushPlugin_PushHandlerActivity(13939): isPushPluginActive = false
> D/PushPlugin_PushHandlerActivity(13939): forceMainActivityReload

# App in the foreground, receiving a notification

A notification is created (shouldn't), JS event handler isn't triggered (should).

LOGS:

> D/PushPlugin_GCMIntentService(13939): onMessage - from: [removed]
> D/PushPlugin_GCMIntentService(13939): normalize extras
> D/PushPlugin_GCMIntentService(13939): key = google.sent_time
> D/PushPlugin_GCMIntentService(13939): replace key google.sent_time with google.sent_time
> D/PushPlugin_GCMIntentService(13939): key = force-start
> D/PushPlugin_GCMIntentService(13939): replace key force-start with force-start
> D/PushPlugin_GCMIntentService(13939): key = priority
> D/PushPlugin_GCMIntentService(13939): replace key priority with priority
> D/PushPlugin_GCMIntentService(13939): key = payload
> D/PushPlugin_GCMIntentService(13939): replace key payload with payload
> D/PushPlugin_GCMIntentService(13939): key = title
> D/PushPlugin_GCMIntentService(13939): replace key title with title
> D/PushPlugin_GCMIntentService(13939): no locale found for key = title, error Value NEW of type java.lang.String cannot be converted to JSONObject
> D/PushPlugin_GCMIntentService(13939): key = google.message_id
> D/PushPlugin_GCMIntentService(13939): replace key google.message_id with google.message_id
> D/PushPlugin_GCMIntentService(13939): key = message
> D/PushPlugin_GCMIntentService(13939): replace key message with message
> D/PushPlugin_GCMIntentService(13939): no locale found for key = message, error Value Me of type java.lang.String cannot be converted to JSONObject
> D/PushPlugin_GCMIntentService(13939): key = ledColor
> D/PushPlugin_GCMIntentService(13939): replace key ledColor with ledColor
> D/PushPlugin_GCMIntentService(13939): key = collapse_key
> D/PushPlugin_GCMIntentService(13939): replace key collapse_key with collapse_key
> D/PushPlugin_GCMIntentService(13939): background
> D/PushPlugin_GCMIntentService(13939): message =[Me again]
> D/PushPlugin_GCMIntentService(13939): title =[NEW MESSAGE from VinceOPS]
> D/PushPlugin_GCMIntentService(13939): contentAvailable =[null]
> D/PushPlugin_GCMIntentService(13939): forceStart =[1]
> D/PushPlugin_GCMIntentService(13939): create notification
> E/PushPlugin_GCMIntentService(13939): Number format exception - Error parsing notId: Invalid int: "null"
> D/PushPlugin_GCMIntentService(13939): stored icon=null
> D/PushPlugin_GCMIntentService(13939): stored iconColor=#343434
> D/PushPlugin_GCMIntentService(13939): stored sound=true
> D/PushPlugin_GCMIntentService(13939): stored vibrate=true
> D/PushPlugin_GCMIntentService(13939): no icon resource found - using application icon
> D/PushPlugin_GCMIntentService(13939): create actions: with in-line
> D/PushPlugin_GCMIntentService(13939): app is not running but we should start it and put in background
> D/PushPlugin_PushHandlerActivity(13939): not id = 0
> V/PushPlugin_PushHandlerActivity(13939): onCreate
> D/PushPlugin_PushHandlerActivity(13939): callback = null
> V/PushPlugin(13939): sendExtras: caching extras to send at a later time.
> D/PushPlugin_PushHandlerActivity(13939): bringToForeground = false
> D/PushPlugin_PushHandlerActivity(13939): isPushPluginActive = false
> D/PushPlugin_PushHandlerActivity(13939): startOnBackgroundTrue


### Clicking the notification from the notification center (app in the foreground)

JS event handler not triggered :(

LOGS

> D/PushPlugin_PushHandlerActivity(13939): not id = 0
> V/PushPlugin_PushHandlerActivity(13939): onCreate
> D/PushPlugin_PushHandlerActivity(13939): callback = null
> V/PushPlugin(13939): sendExtras: caching extras to send at a later time.
> D/PushPlugin_PushHandlerActivity(13939): bringToForeground = true
> D/PushPlugin_PushHandlerActivity(13939): isPushPluginActive = false
> D/PushPlugin_PushHandlerActivity(13939): forceMainActivityReload


# Payload

Regarding the server-side, I'm using ionic.io "Push" service, in order to keep my API code as clean as possible (I'd rather communicate with only one service, instead of two, even if it comes with new security/availability risks, etc).

My payload looks like (ES6/ES7):

```
{
        title: title || 'My App',
        message,
        payload,
        ios: {
            badge: 1,
            priority: 5
        },
        android: {
            data: {
                // here goes custom data: summaryText, style, etc
                ledColor: [0, 38, 184, 201],
                priority: 1,
                'force-start': 1
          }
      }
}
```

I didn't change it since my initial tests with 1.9.0 (where everything seemed to work well), but Ionic may have changed their inner API code...

Hope it will help.

Thanks

**Comment by VinceOPS** [comment]
@macdonst Forget about my last comment from yesterday, I wasn't initializing the plugin anymore, thus, the behavior I described wasn't accurate.

Regarding the server-side, I'm using ionic.io "Push" service, in order to keep my API code as clean as possible (I'd rather communicate with only one service, instead of two, even if it comes with new security/availability risks, etc).

My payload looks like (ES6/ES7):

```
{
        title: title || 'My App',
        message,
        payload,
        ios: {
            badge: 1,
            priority: 5
        },
        android: {
            data: {
                // here goes custom data: summaryText, style, etc
                ledColor: [0, 38, 184, 201],
                priority: 1,
                'force-start': 1
          }
      }
}
```

I didn't change it since my initial tests with 1.9.0 (where everything seemed to work well), but Ionic may have changed their inner API code...

Hope it will help.

Thanks

**Comment by VinceOPS** [comment]
After many _proper_ tests, I can confirm that the issue is solved by this commit, and that it doesn't seem to add any new issue :-). Thanks!
