### ISSUE TITLE
on Android 6, Push notifications doesn't work when I stopped App

### ISSUE THREAD

**Issue by fattanasio** [phonegap/phonegap-plugin-push#1477]
Cordova CLI version and cordova platform version

Plugin version
1.9.2
Sample Push Data Payload
Sample Code that illustrates the problem
Logs taken while reproducing problem
nothing

Thank you

### Expected Behaviour
When I stopped the App (kill from memory or restart smartphone) I would like to receive notification
### Actual Behaviour
When the app is opened i receive push notifications but when I stopped the App (kill from memory or restart smartphone) doesn't receive push notifications
#### Steps to Reproduce 
On Android 6 kill app and try to receive push notifications. It doesn't work. It works on Android 5
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0, Tested on Asus Zen Fone Max and on Huawey P8
#### Cordova CLI version and cordova platform version
Cordova 6.4
#### Plugin version
1.9.2

#### Logs taken while reproducing problem
nothing

Thank you!

**Comment by fattanasio** [comment]
Hello guys, no one has experienced this problem?

**Comment by macdonst** [comment]
@fattanasio sorry, I can't reproduce this problem. If you send me your sample push payload I may be able to figure out what is going on. However, I do notice you are using a Huawei phone and that may mean you are running into this:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#huawei-and-xiaomi-phones

**Comment by fattanasio** [comment]
Hi Simon,
thank you for your answer. I remove app from protected apps of huawei and it works. 
Also Asus Zen Fone Max with Autostart Manager has this behavior.
I was wondering if there is a way to set automatically these settings like Whatsapp o Facebook ? (Manifest or other ways)
Thank you !

**Comment by macdonst** [comment]
@fattanasio YMMV but this is one way it is handled from a SO answer:

http://stackoverflow.com/a/35220476/41679
