### ISSUE TITLE
Unable to generate Push Token in Production mode

### ISSUE THREAD

**Issue by saurabhPV** [phonegap/phonegap-plugin-push#1479]
### Expected Behaviour
Should get device token in  push.on('registration', function(data) 
### Actual Behaviour
Didn't get  device token in  push.on('registration', function(data)  when deployed  using Adhoc mode.
#### Steps to Reproduce 
I have just installed the plugin and can receive notification if app is run in sandbox mode
It used to work with 1.8.4 but now even if I rollback to it, it does not work.
#### Platform and Version 
iOS 9.3 and 10.1.1

#### Cordova CLI version and cordova platform version

    cordova --version                                    #  6.4.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   #  1.9.2 

#### Logs taken while reproducing problem

Control reaches here
[[UIApplication sharedApplication] registerForRemoteNotifications];
but 
neither 
- (void)didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken 
or
- (void)didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
is called

However it works perfectly fine when I run it on device using Xcode

**Comment by fredgalvao** [comment]
When you say
> However it works perfectly fine when I run it on device using Xcode

you imply that it is **not working perfectly fine on some other situation different than on a device**. What situation is that, exactly? iOS simulator?

**Comment by saurabhPV** [comment]
I meant if I run it on an iPhone from Xcode I get notification but when I create an ipa using Adhoc profile and then install it on same iPhone it does not generate device token

**Comment by fredgalvao** [comment]
Are you changing `sandbox` from true to false when you run adhoc? Other than that, I can tell you that 95% of the time something doesn't work on iOS it means the certificate/provision profiles are incorrect.

**Comment by saurabhPV** [comment]
Are you changing sandbox from true to false when you run adhoc?
How do I do this ? 
you meant it on server ?

**Comment by saurabhPV** [comment]
If certificate/provision profile are incorrect  I would not get notification but I should still get token right?  
I get that notification permission popup in Adhoc mode but not the token

**Comment by fredgalvao** [comment]
Nevermind about the `sandbox` thing, that's exclusive to GCM usage, which isn't your case it seems. My mistake.

To answer your last question, if your certificate is wrong, you won't receive the `registrationId`/`token`, and by consequence you won't be able to receive notifications.

**Comment by saurabhPV** [comment]
which certificate you are referring ? Push certificate or Distribution certificate.  I am certain about distribution certificate is being used while creating ipa.

**Comment by pointiitm** [comment]
Hi @fredgalvao I am facing the same issue. And my certificate is correct. Even sandbox certificate is correct.

**Comment by saurabhPV** [comment]
@pointiitm Please test it with another device. It didn't work for me on my testing device but works on my client's iPhone . I have also created a tiny native app but even it fails on that testing device. 
I was able to retreive token once after I changed the date to next date and restrted it

**Comment by pointiitm** [comment]
@saurabhPV Thanks man. That didn't work though. But same package is working on another iphone. Weird!
