### ISSUE TITLE
No notification with Priority "normal" on iOS 10.2 when app is closed

### ISSUE THREAD

**Issue by skyprimer** [phonegap/phonegap-plugin-push#1481]
### Expected Behaviour
Notification with priority "normal" payload should arrive to the app which is not opened.

### Actual Behaviour
If the app is on foreground or background no problem. But if the app is not opened at all no notification arrives.

### Reproduce Scenario
Close the app and send a notification with priority "normal" payload option

#### Platform and Version
IOS 10.2 (No problem with 10.1.1) i've tested with 2 different devices 5SE and 6

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
No Problem on Android

#### Cordova CLI version and cordova platform version
Phonegap Build 6.3.0 -  Cordova 6.4.0

#### Plugin version
1.8.4 to 1.9.2

#### Sample Push Data Payload
'to' => '/topics/topicid',
			"content_available" => true,
			'priority' => 'normal',
			'notification' => array (
                'body' => $mesaj,
     )

**Comment by macdonst** [comment]
@skyprimer yup, documented that here:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#gcm-messages-not-arriving

I believe it to be a problem with the GCM library from google.
