### ISSUE TITLE
Receive non notifications pushes when apps open

### ISSUE THREAD

**Issue by theinvensi** [phonegap/phonegap-plugin-push#1482]
Hello for all...

I already know, when I receive and push with "message" and "title" on payload, even the app is closed, a notifications are displayed on my Android.

But if my push don't have this keys on payload, and only "additional_data". Have some way to receive this push without notification, when the app are opened...?

**Comment by macdonst** [comment]
@theinvensi what you do is use a silent background notification as documented here: 

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications-1

This way you app can react to background pushes without having to be opened.
