### ISSUE TITLE
iOS10 push notification not received

### ISSUE THREAD

**Issue by peterpeterparker** [phonegap/phonegap-plugin-push#1486]
### Expected Behaviour
On Android and iOS I should be able to push and get notifications.

### Actual Behaviour
On Android and iOS <= 9 I'm able to push and get notifications.
On iOS >= 10 I'm unable to push and get notifications aka it doesn't work.

### Reproduce Scenario (including but not limited to)
Push a notification to an iOS 10 terminal.

I use Amazon SNS but I could reproduce the problem with tools like "Easy APNs Provider" or "NWPusher" (see screenshot)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.48
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.0 Build version 8A218a

Installed platforms:
  android 6.1.0
  ios 4.3.1

phonegap-plugin-push 1.9.2 "PushPlugin"

cocoapods 1.1.1

#### Sample Push Data Payload

    {
      "aps" : {
        "content-available" : 1,
        "alert" : {
          "title" : "My title",
          "body" : "Your message Here"
        },
        "badge" : 0,
        "sound" : "default"
      }
    }

P.S.: But same results with a simpler payload too

My service code:

    init(user: UserAccess, iOSPlatform: boolean, androidPlatform: boolean):Promise<{}> {
        return new Promise((resolve) => {
            this.push = Push.init({
                android: {
                    senderID: Resources.Constants.GOOGLE.PROJECT.NUMBER,
                    icon: 'icon_notification_fluster',
                    iconColor: '#ff65a9',
                    sound: true
                },
                ios: {
                    alert: 'true',
                    badge: true,
                    sound: 'true'
                },
                windows: {}
            });

            if (this.isPushValid()) {
                this.push.on('registration', (data: RegistrationEventResponse) => {

                    if (!Comparator.isEmpty(data)) {
                        // Update device token in my backend
                        this.updateDevice(user, data.registrationId, iOSPlatform, androidPlatform).then((result:Communication.PushUpdate) => {
                            // Do nothing
                        }, (errorResponse:Response) => {
                            // Do nothing
                        });
                    }

                });

                this.clearTheBadge().then(() => {
                    // Do nothing
                }, () => {
                    // Do nothing
                });
            }

            resolve();
        });
    }

  
    private isPushValid(): boolean {
        // In the browser, push gonna contains a .error object
        return !Comparator.isEmpty(this.push) && Comparator.isStringEmpty((<any> this.push).error);
    }

P.S.: Note that in my code I don't subscribe to the "on notification event" because I do not need to proceed it. For internal conversation I use socket.io, therefore I don't need to catch the push when the app is running. But let me knows if that is wrong...

I already spent hours mostly trying to do the same tests without any success. I would really appreciate any help or ideas and let me know if you need more informations or if I should perform other tests.

Best regards

<img width="482" alt="capture d ecran 2016-12-27 a 17 54 36" src="https://cloud.githubusercontent.com/assets/16886711/21504370/a583ddfe-cc5e-11e6-8780-70c7e59e4afb.png">

**Comment by macdonst** [comment]
@peterpeterparker in Xcode go to the Capabilities control panel and see if push notifications is off like the image below:

![screenshot 2017-01-03 09 10 55](https://cloud.githubusercontent.com/assets/353180/21610164/8f82541e-d194-11e6-85d0-e562400ce016.png)

If it is turn it on and re-test. This issue popped up for iOS 10 devices.

**Comment by peterpeterparker** [comment]
thx for the idea @macdonst unfortunately that settings is already on (see screenshot).

<img width="699" alt="capture d ecran 2017-01-03 a 19 27 12" src="https://cloud.githubusercontent.com/assets/16886711/21618934/abef60e8-d1ed-11e6-9a6f-f3fc8332eff1.png">

**Comment by macdonst** [comment]
Just making sure. Can you get the logs from xcode?

**Comment by peterpeterparker** [comment]
@macdonst sure, I'm open to any suggestion or help, thx a lot! 

I'll only have access to what I need to provide these logs tomorrow night (European time), please excuse me in advance for the delay

**Comment by peterpeterparker** [comment]
@macdonst seems that the problem is solved, at least on my new test phone.

I was using Xcode 8.0. 
Updating Xcode to version 8.2.1 and building a new app seems to have solve the issue.

Therefor I close this task and thx you for the support!

:)
