### ISSUE TITLE
Notifiactions are not getting in MI, Oneplus, Lenovo Mobiles

### ISSUE THREAD

**Issue by mohanchalla** [phonegap/phonegap-plugin-push#1487]
_I am developing an android app, In that I have incorporated Push Notifications When some action performed in the web app I send a notification to the registered user(Push is incorporated using Amazon AWS). To configure these push notifications I have used cordova PushPlugin. If the application is in background, then I am getting the notifications. But If I close the app from recent apps try then Notifications are not firing. I want to how Facebook and Whatsapp apps are sending notifications if the app is terminated. I am using cordova and ionic framework to develop the hybrid mobile app. Anyone help is appreciated!_

**Comment by fredgalvao** [comment]
Are you using **PushPlugin** or **phonegap-plugin-push**? Those are two very different plugins.

**Comment by mohanchalla** [comment]
I am using phonegap-plugin-push

**Comment by macdonst** [comment]
@mohanchalla you might be running into this:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#huawei-and-xiaomi-phones

**Comment by mohanchalla** [comment]
@macdonst If I use force-start: 1 then I am getting the notifications in MI mobile but app is loading in the background I don't want to do that. Even I have to tell all the users to enable autostart to my app. Which is some what risky process I have to call each and every one tell. Is there any workaround instead of this?

**Comment by macdonst** [comment]
@mohanchalla nope, sorry. That's the way a lot of Chinese manufacturers of Android phones have decided to setup the Android OS. When you kill the app they also kill the services responsible for receiving push. You could put a first time warning in your app to direct people where to turn on auto-start.

**Comment by mohanchalla** [comment]
But If I put the force-start option it is effecting even Non-China manufacturers also. Because I will have to keep this option to work on all kinds of mobiles. If I receive a notification Motorola mobiles with force-start option it is staring the app in the background.
