### ISSUE TITLE
How can I open project with xcode? There are no files with extension .xcodeproj or .xcworkspace

### ISSUE THREAD

**Issue by Assylkhan** [phonegap/phonegap-plugin-push#1488]

**Comment by macdonst** [comment]
@Assylkhan Yes, they are in `platforms/ios`

**Comment by Assylkhan** [comment]
No, they don't exist in the example project, which I cloned by this command: *phonegap create my-app --template phonegap-template-push*. No such files, I searched in all project. Here is my project: https://github.com/Assylkhan/phoneGapPushTest/tree/master/platforms/browser.

**Comment by macdonst** [comment]
@Assylkhan did you add the ios platform to your project did you build?

```
phonegap platform add ios
phonegap build ios
```

Then stuff should be there.

**Comment by Assylkhan** [comment]
No, didn't know about it, thank you. Now they have appeared.
