### ISSUE TITLE
Registration failing in Production mode 

### ISSUE THREAD

**Issue by pointiitm** [phonegap/phonegap-plugin-push#1489]
# Expected Behaviour
Should get device token in push.on('registration', function(data)

### Actual Behaviour
Didn't get device token in push.on('registration', function(data) when deployed using Adhoc mode (installing ipa) on certain iPhones

### Reproduce Scenario (including but not limited to)
Issue (on certain phones - iPhone 5) when installing the app directly through ipa. There is no problem when installing directly on device by XCode (Product-> Run). Registration works fine along with notifications. Issue comes only when the app is installed from ipa. Also the same package worked well with iPhone 6S

#### Steps to Reproduce 

1. ionic build ios / ionic build --release ios
2. open xcode to create Adhoc build package - ipa
3. install

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.2

#### Cordova CLI version and cordova platform version

    cordova --version                                   # 6.4.0
    cordova platform version ios                        # ios 4.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.8.2

#### Sample Code that illustrates the problem
```
this.push.on('registration', (data) => {
  let notification_id: string = data.registrationId;
  console.log('device token ->', notification_id);
  if (notification_id) {
    this.databaseService.getValueFromKey(DatabaseConstants.NOTIFICATION_ID)
      .then(notification_id_local => {
        // Doing something
      })
      .catch(error => {
        // Doing something
      });
  }
  else {
    console.error('FCM registration failed');
  }
});
```

#### Logs taken while reproducing problem
No logs as the problem is only with archived package

**Comment by wiewioraseb** [comment]
@pointiitm Have you found a solution to this? Maybe some work around?

**Comment by pointiitm** [comment]
@wiewioraseb No success. Out of three testing phones that I have it's only working on iphone 6. Effectively I am still stuck

**Comment by macdonst** [comment]
@pointiitm did this get resolved for you?

**Comment by pointiitm** [comment]
@macdonst Couldn't wait for the issue to get solved so just went native. Now my both android and iOS apps are native.
