### ISSUE TITLE
Push not received when the app is in foreground after 10min from the last installation

### ISSUE THREAD

**Issue by ai2010** [phonegap/phonegap-plugin-push#1490]
### Expected Behaviour
The app receives the push both in background and foreground even after 10min or so from installation.
### Actual Behaviour
The app receives the the push always in background not in foreground after 10min or so from installation
#### Steps to Reproduce 
1.install the app with the push activated
2.wait 10 min or so
3.send push when the app is in foreground
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
android 6.0 
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Motorola moto g3
#### Cordova CLI version and cordova platform version
cordova 6.3.1
cordova android 3.7.0
#### Plugin version
1.8.4
#### Sample Push Data Payload
{"payload": {"type": "notification", "pushid": "11", "foreground": true}, "message": "Hello World oh man!"}
#### Sample Code that illustrates the problem
.run(function($ionicPlatform,$ionicPush,$cordovaPushV5,$localStorage,$rootScope,$ionicPopup,$cordovaPushV5,$cordovaNetwork,$ionicLoading,$cordovaStatusbar,$cordovaGoogleAnalytics,Messages,EventServices) {  

$ionicPlatform.ready(function() {
$rootScope.push = PushNotification.init({
			    android: {
			        senderID: "XXX",
				    //"forceShow": "true",
	                "icon": "icon",//"ic_icon_google",
	                //"iconColor": "blue"
			    },
			    ios: {
			        alert: "true",
			        badge: "true",
			        sound: "true"
			    }
			});
        
			$rootScope.push.on('registration', function(data) {
			    // data.registrationId
				console.log('REG TOKEN'+JSON.stringify(data))
				alert('dev token'+data.registrationId+'--'+$localStorage.device_token_new)
				if(data.registrationId!=$localStorage.device_token_new){
					$localStorage.device_token_new = data.registrationId
				}
			});
})
$rootScope.push.on('notification', function(data) {	
alert('push:'+JSON.stringify(data))
})
})

**Comment by macdonst** [comment]
@ai2010 can you clarify what you mean by "Push not received when the app is in foreground"? Do you mean you don't see the push in the notification shade or does your on push event handler not get called?

**Comment by ai2010** [comment]
@macdonst I mean '$rootScope.push.on('notification', function(data) {' is not triggered

**Comment by macdonst** [comment]
@ai2010 okay, I got you now but I can't reproduce it. I don't use Ionic very often. Do you know if the `$rootScope` clears down the `push` variable?

**Comment by ai2010** [comment]
no the rootScope is not really the problem. As an hack what I'm doing now is a period function that every minute or so initialize the push plugin:
`$rootScope.push = PushNotification.init({
android: {
senderID: "XXX",
//"forceShow": "true",
"icon": "icon",//"ic_icon_google",
//"iconColor": "blue"
},
ios: {
alert: "true",
badge: "true",
sound: "true"
}
});`

**Comment by macdonst** [comment]
@ai2010 that's redundant, I wouldn't do that. Can you check to see if the `on('notification')` handler gets cleared periodically? Without seeing your code I'm guessing that is the issue.

Also, if you reproduce the problem while running `adb logcat | grep PushPlugin` it'll help pin down the issue.

**Comment by fredgalvao** [comment]
`$rootScope` functions more like a namespace than like a scoped object, @macdonst . I see no way it'd be getting cleared in the sense that would break the plugin or event propagation/lifecycle. That said, I still can't see what's going on without logs either.

**Comment by ericb** [comment]
@ai2010 You might be running into issues with livereload or deploy wherein you are not calling [`register()`](http://docs.ionic.io/api/client/push/#register) every time the page is loaded. This is necessary for the notification handler to work properly.
