### ISSUE TITLE
App crashes after refreshing when using FCM (v2)

### ISSUE THREAD

**Issue by AndreasGassmann** [phonegap/phonegap-plugin-push#1497]
I have an Ionic2 app and I'm using the v2 branch of this plugin to use FCM push notifications. I noticed that the app crashes when refreshing it using safari. My initial thought was to only call the .init() method after the first launch, but according to the docs the registrationId might change and it should be called on every app launch.

After reading a bit on stackoverflow, it might be related to this issue: http://stackoverflow.com/questions/37910766/app-crashing-when-using-firebase-auth-reason-default-app-has-already-been-con

Maybe it could be fixed with the following snippet:

```
    // Configure Firebase
    // ------------------
    if FIRApp.defaultApp() == nil {
        FIRApp.configure()            
    }
```

### Expected Behaviour

When refreshing the app, I expect the app to work normally and the push registration to succeed (or be skipped)

### Actual Behaviour

The app crashes after refreshing

#### Steps to Reproduce 

Build and run app using FCM and v2 from XCode
Wait for the registration to go through (without any errors)
Open Safari Dev Tools
Refresh the Page
App will load but crash once it tries to register again

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 10.1

#### Cordova CLI version and cordova platform version

    cordova --version: 6.4.0
    cordova platform version ios: 4.3.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push: 2.0.0-rc1 "PushPlugin"

#### Logs taken while reproducing problem

```2017-01-04 00:06:36.083081 App[xxx] Push Plugin register called
2017-01-04 00:06:36.083123 App[xxx] PushPlugin.register: setting badge to false
2017-01-04 00:06:36.083136 App[xxx] PushPlugin.register: clear badge is set to 0
2017-01-04 00:06:36.083146 App[xxx] PushPlugin.register: better button setup
2017-01-04 00:06:36.090700 App[xxx] FCM Sender ID xxx
2017-01-04 00:06:36.090921 App[xxx] Using FCM Notification
2017-01-04 00:06:36.103581 App[xxx] *** Terminating app due to uncaught exception 'com.firebase.core', reason: 'Default app has already been configured.'
*** First throw call stack:
(0x1842221c0 0x182c5c55c 0x184222108 0x10027e430 0x10027e1f8 0x100215118 0x100ec525c 0x100ec521c 0x100eca284 0x1841cff2c 0x1841cdb18 0x1840fc048 0x185b82198 0x18a0e72fc 0x18a0e2034 0x1000e90e4 0x1830e05b8)
libc++abi.dylib: terminating with uncaught exception of type NSException```

The error happens at [FIRApp configure]; on line 333 in the following file: https://github.com/phonegap/phonegap-plugin-push/blob/v2.0.x/src/ios/PushPlugin.m

**Comment by jcesarmobile** [comment]
Looks like we missed this PR after the rebase
https://github.com/phonegap/phonegap-plugin-push/pull/1396

**Comment by macdonst** [comment]
@AndreasGassmann yeah, that is my screw up on a rebase. I will fix today and maybe get RC2 out.

**Comment by AndreasGassmann** [comment]
Ok, thanks!

**Comment by macdonst** [comment]
@AndreasGassmann I just pushed the fix to the `v2.0.x` branch. Give it a try and let me know if it resolves the issue for you, it should and I'll start looking at that RC2 candidate push to NPM.

**Comment by AndreasGassmann** [comment]
Works like a charm. Thanks!

**Comment by macdonst** [comment]
@AndreasGassmann releasing a 2.0.0-rc2 now.
