### ISSUE TITLE
Linker errors with phonegap-plugin-push and also bunch of compile warnings

### ISSUE THREAD

**Issue by stib** [phonegap/phonegap-plugin-push#1499]
Hi,

I am using ionic (1.3.1) and for this push-plugin I have installed cocoapods (1.1.1) and done pod install

My ionic info gives the following - 
> Cordova CLI: 6.4.0 
> Ionic CLI Version: 2.1.8
> Ionic App Lib Version: 2.1.4
> ios-deploy version: 1.9.0 
> ios-sim version: 5.0.11 
> OS: OS X El Capitan
> Node Version: v6.9.1
> Xcode version: Xcode 8.0 Build version 8A218a

I have the latest version of phonegap-plugin-push (1.9.2)

I started with getting the GoogleCloudMessaging.h not found error. To resolve that, after digging around a lot I added PODS_ROOT to point to ${SRCROOT}/Pods in User-Defined section in Build Settings. 

Now I am getting linker errors as below. Detailed compile and link log is [here](https://gist.github.com/stib/f6374612c73d32961b76491d2d27a6a9)

> Undefined symbols for architecture arm64:
>   "_OBJC_CLASS_$_GCMService", referenced from:
>       objc-class-ref in PushPlugin.o
>   "_OBJC_CLASS_$_GCMConfig", referenced from:
>       objc-class-ref in PushPlugin.o
>   "_OBJC_CLASS_$_GGLInstanceIDConfig", referenced from:
>       objc-class-ref in PushPlugin.o
>   "_OBJC_CLASS_$_GCMPubSub", referenced from:
>       objc-class-ref in PushPlugin.o
>   "_OBJC_CLASS_$_GGLInstanceID", referenced from:
>       objc-class-ref in PushPlugin.o
>   "_kGGLInstanceIDAPNSServerTypeSandboxOption", referenced from:
>       -[PushPlugin didRegisterForRemoteNotificationsWithDeviceToken:] in PushPlugin.o
>   "_kGGLInstanceIDRegisterAPNSOption", referenced from:
>       -[PushPlugin didRegisterForRemoteNotificationsWithDeviceToken:] in PushPlugin.o
>   "_kGGLInstanceIDScopeGCM", referenced from:
>       -[PushPlugin onTokenRefresh] in PushPlugin.o
>       -[PushPlugin didRegisterForRemoteNotificationsWithDeviceToken:] in PushPlugin.o
> ld: symbol(s) not found for architecture arm64

I tried removing arm64 from the architecture variable in Build Settings just to see what it does and I started getting a bunch of other linker errors. I have read through many posts and spent a lot of time but don't know what to do here. 

As suggested in a post I have tried adding $(inherited) to the Other Linker Flags - that didn't help. Though that converts to -ObjC which was already there - don't quite understand that.

I am not a Xcode power user and my knowledge of Xcode is limited.

Thanks for any help and pointers to help resolve.

Sanjay.

**Comment by macdonst** [comment]
@stib try doing:

```
cordova platform rm ios
cordova platform add ios
cordova build ios
```

that should get you the latest version of cordova-ios and everything should build for you. Ionic may be pinning an earlier version of cordova-ios that does not work correctly with this plugin.

**Comment by stib** [comment]
@macdonst thank you for the suggestion. That removed my linker errors.
`cordova platform version` shows that my ios remains unchanged at 4.3.1 - not sure what changed but glad that it fixed the problem.

However I am now getting the error as below after successful Push Plugin register

> 2017-01-04 19:56:01.031: GCM | GCM library version 1.1.4
> 2017-01-04 19:56:01.112: GCM | Invalid key in checkin plist: GMSInstanceIDDeviceDataVersion

If I can't resolve I will open another ticket so as to not mix different issues.
