### ISSUE TITLE
Registration is not working in IOS9

### ISSUE THREAD

**Issue by oscarabilleira** [phonegap/phonegap-plugin-push#150]
After update to ios9 registration is not working. Anyone with this same problem??

**Comment by Mojo90** [comment]
I tested with iOS 9 and does work for me. But only on GM hope that nothing changed since GM :O

**Comment by oscarabilleira** [comment]
I apreciate if you test ir ok final version

**Comment by Mojo90** [comment]
When I am able to download iOS 9 final :-D
But I do think GM is always the same as final and would be very bad if it is not working cause my Update is already in Review.

**Comment by oscarabilleira** [comment]
Finally sudenly atart la to work... Everything ok now,  thanks
