### ISSUE TITLE
Push notification works in native iOS app, but in phonegap does not work.

### ISSUE THREAD

**Issue by Assylkhan** [phonegap/phonegap-plugin-push#1500]
<b>Expected Behaviour</b>
for iOS device should work push notification within web server. Within web server i.e. by starting web server, not Xcode project separately.
<b>Actual Behaviour</b>
When I run separately xcodeproject in my iPhone, I receive push notifications from firebase. But when I run all phonegap project(android, iOS, web), I don't receive push notifications in my iPhone. 
I tried running phonegap project in remote server(build.phonegap.com and locally by command "phonegap serve") but push notification does not work.
<b>Reproduce Scenario (including but not limited to)</b>

<b>Steps to Reproduce</b>
download example project, created cert, upload p12 to firebase, downloaded .plist and provisioning profile, enabled in capabilities push notification mode, i.e. all neccessary things for push notification.
<b>Platform and Version (eg. Android 5.0 or iOS 9.2.1)</b>
iOS 10.1.1
<b>Cordova CLI version and cordova platform version</b>
cordova --version: 6.4.0
cordova platform version ios: 4.3.1

<b>Plugin version</b>
cordova plugin version | grep phonegap-plugin-push: e.g. 1.5.3

<b>Sample Push Data Payload</b>
I use firebase console for sending push notification. Credentials of test firebase account: email: justForTestingEduMark@gmail.com; password: qazwsxedc12345. Settings I use: delivery date: send now, target: user segment, priority: high, expiration: 1 min, badge count: 1

<b>Sample Code that illustrates the problem</b>
Here is my project: https://github.com/Assylkhan/phoneGapPushTest.

<b>Logs taken while reproducing problem</b>
nothing happens. I don't receive push notification.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Assylkhan** [comment]
Reopen please

**Comment by macdonst** [comment]
@Assylkhan What do you mean by `by starting web server`? I'm confused as to how you are testing.

**Comment by Assylkhan** [comment]
By starting web server I mean: <b>phonegap serve</b> locally or uploading my project to build.phonegap.com. But in both case didn't work for me.

**Comment by macdonst** [comment]
@Assylkhan if you are running this using `phonegap serve` are you then loading the app in the broswer or the PhoneGap Developer app?

**Comment by Assylkhan** [comment]
I am loading in phonegap developer app.

**Comment by Assylkhan** [comment]
You can close. I understood not right, it works.
