### ISSUE TITLE
Badge Count Not Working

### ISSUE THREAD

**Issue by siddharthnaik7** [phonegap/phonegap-plugin-push#1501]
### Expected Behaviour
Using "push.setApplicationIconBadgeNumber(function successCallback(){ console.log('success');}, function errorCallback(){ console.log('error');}, 50);" the badge count should work.

### Actual Behaviour
Using  "push.setApplicationIconBadgeNumber(function successCallback(){ console.log('success');}, function errorCallback(){ console.log('error');}, 50);" Badge count works on few Samsung based Android devices viz.: Samsung Note 3 Neo (Android- 5.1.1), etc

### Reproduce Scenario (including but not limited to)
After registering the device for push notification, on the event of notification received, I have added:
 "push.setApplicationIconBadgeNumber(function successCallback(){ console.log('success');}, function errorCallback(){ console.log('error');}, 50);", to set the Badge count.

#### Steps to Reproduce 
push.on('registration', (data) => {
		//push.setApplicationIconBadgeNumber(function successCallback(){ console.log('success');}, function errorCallback(){ console.log('error');}, 50);
        console.log("device token ->", data.registrationId);
        //TODO - send device token to server
      });
      push.on('notification', (data) => {
		push.setApplicationIconBadgeNumber(function successCallback(){ console.log('success');}, function errorCallback(){ console.log('error');}, 50);
        console.log('message', data.message);
        let self = this;
        //if user using app and push notification comes
        if (data.additionalData.foreground) {
          // if application open, show popup
          let confirmAlert = this.alertCtrl.create({
            title: 'New Notification',
            message: data.message,
            buttons: [{
              text: 'Ignore',
              role: 'cancel'
            }, {
              text: 'View',
              handler: () => {
                //TODO: Your logic here
                self.nav.push(DetailsPage, {message: data.message});
              }
            }]
          });
          confirmAlert.present();
        } else {
          //if user NOT using app and push notification comes
          //TODO: Your logic on click of push notification directly
          self.nav.push(DetailsPage, {message: data.message});
          console.log("Push notification clicked");
        }
      });

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android-5.0.2, 5.1.1, 7.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Lenovo(A6000), Samsung(Note 3 Neo), Moto(G 4)

#### Cordova CLI version and cordova platform version
Cordova CLI - 6.4.0

Cordova Platform Version Android -
Installed platforms:
  android 6.0.0
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  webos ~3.7.0
  windows ~4.4.0
  wp8 ~3.8.2 (deprecated)

#### Plugin version
Cordova plugin version | grep phonegap-plugin-push -
phonegap-plugin-push 1.8.2 "PushPlugin"

#### Sample Code that illustrates the problem
push.on('registration', (data) => {
		//push.setApplicationIconBadgeNumber(function successCallback(){ console.log('success');}, function errorCallback(){ console.log('error');}, 50);
        console.log("device token ->", data.registrationId);
        //TODO - send device token to server
      });
      push.on('notification', (data) => {
		push.setApplicationIconBadgeNumber(function successCallback(){ console.log('success');}, function errorCallback(){ console.log('error');}, 50);
        console.log('message', data.message);
        let self = this;
        //if user using app and push notification comes
        if (data.additionalData.foreground) {
          // if application open, show popup
          let confirmAlert = this.alertCtrl.create({
            title: 'New Notification',
            message: data.message,
            buttons: [{
              text: 'Ignore',
              role: 'cancel'
            }, {
              text: 'View',
              handler: () => {
                //TODO: Your logic here
                self.nav.push(DetailsPage, {message: data.message});
              }
            }]
          });
          confirmAlert.present();
        } else {
          //if user NOT using app and push notification comes
          //TODO: Your logic on click of push notification directly
          self.nav.push(DetailsPage, {message: data.message});
          console.log("Push notification clicked");
        }
      });

**Comment by macdonst** [comment]
@siddharthnaik7 not all Android phones have the ability to set the badge number. We use [ShortcutBadger](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#badges) to provide this functionality. If it doesn't work for your phone you should check out https://github.com/leolin310148/ShortcutBadger to see if your phone is supported.

**Comment by siddharthnaik7** [comment]
@macdonst , Yes I have checked https://github.com/leolin310148/ShortcutBadger . Over there (For an instance) Xiomi devices are supported, but for me using phonegap-plugin-push, I am not getting the badge count on Mi4i of Xiomi. Is there any workaround?

**Comment by siddharthnaik7** [comment]
@macdonst , Yes I did download and checked, but it didn't worked.

**Comment by macdonst** [comment]
@siddharthnaik7 okay if the ShortcutBadger app didn't work then the bug is with ShortcutBadger/Mi4i. You should raise an issue on the ShortcutBadger repo as I can't help.

**Comment by siddharthnaik7** [comment]
@macdonst okay sure. Thanks
