### ISSUE TITLE
Fail to add 1.9.2 to ios platform (using Visual Studio / taco)

### ISSUE THREAD

**Issue by thegruffalo** [phonegap/phonegap-plugin-push#1502]
This seems to have been mentioned before and not resolved. I've created a new issue as the previous mentions of this specific issue piggybacked on existing issue #1342 

Other users who could perhaps add additional information @spaceagestereo, @SergTomcat, 

### Expected Behaviour

Should be able to install 1.9.2 to ios platform in a windows machine using taco

### Actual Behaviour

Plugin fails to install

C:\Temp\pushtest\test2>taco plugin add phonegap-plugin-push
Fetching plugin "phonegap-plugin-push@1.9.2" via npm
Installing "phonegap-plugin-push" for ios
Failed to install 'phonegap-plugin-push':undefined
CocoaPods was not found. Please install version 1.0.1 or greater from https://cocoapods.org/

### Reproduce Scenario (including but not limited to)

Create a new cordova project, add the ios platform and then attempt to add the plugin

#### Steps to Reproduce 

in a command prompt on windows machine

taco create test2 com.foo.bar test --cordova 6.4.0
cd test2
taco platforms add ios
taco plugin add phonegap-plugin-push

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
n/a

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

n/a

#### Cordova CLI version and cordova platform version

    cordova --version
6.4.0
    cordova platform version ios
4.3.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

phonegap-plugin-push 1.9.2 "PushPlugin"

#### Sample Push Data Payload
n/a

#### Sample Code that illustrates the problem

n/a

#### Logs taken while reproducing problem

**When adding on windows machine**
Fetching plugin "phonegap-plugin-push@1.9.2" via npm
Installing "phonegap-plugin-push" for ios
Failed to install 'phonegap-plugin-push':undefined
CocoaPods was not found. Please install version 1.0.1 or greater from https://cocoapods.org/

**When compiling on MacOS**
Installing plugin "phonegap-plugin-push" following successful platform add of ios
1>  Found variables for "phonegap-plugin-push". Processing as cli_variables.
1>  Installing "phonegap-plugin-push" for ios
1>  Running command: /Users/sammediabuild/.taco_home/remote-builds/taco-remote/builds/697/cordovaApp/platforms/ios/cordova/version
1>  Command finished with error code 0: /Users/sammediabuild/.taco_home/remote-builds/taco-remote/builds/697/cordovaApp/platforms/ios/cordova/version
1>  Finding scripts for "before_plugin_install" hook from plugin phonegap-plugin-push on ios platform only.
1>  No scripts found for hook "before_plugin_install".
1>  Install start for "phonegap-plugin-push" on ios.
1>  Beginning processing of action stack for ios project...
1>  Action stack processing complete.
1>  Failed to install 'phonegap-plugin-push':TypeError colors[style] is not a function
1>      at /Users/sammediabuild/.taco_home/node_modules/taco-remote-lib/2.2.1/node_modules/taco-utils/logFormatHelper.js:142:44
1>      at Array.forEach (native)
1>      at Function.LogFormatHelper.colorize (/Users/sammediabuild/.taco_home/node_modules/taco-remote-lib/2.2.1/node_modules/taco-utils/logFormatHelper.js:140:24)
1>      at Function.LogFormatHelper.toFormattedString (/Users/sammediabuild/.taco_home/node_modules/taco-remote-lib/2.2.1/node_modules/taco-utils/logFormatHelper.js:69:57)
1>      at EventEmitter.Logger.log (/Users/sammediabuild/.taco_home/node_modules/taco-remote-lib/2.2.1/node_modules/taco-utils/logger.js:22:47)
1>      at emitOne (events.js:90:13)
1>      at EventEmitter.emit (events.js:182:7)
1>      at EventEmitter.module.exports.emit (/Users/sammediabuild/.taco_home/node_modules/cordova/6.4.0/node_modules/cordova-common/src/events.js:71:17)
1>      at EventEmitter.module.exports.emit (/Users/sammediabuild/.taco_home/remote-builds/taco-remote/builds/697/cordovaApp/platforms/ios/cordova/node_modules/cordova-common/src/events.js:68:30)
1>      at /Users/sammediabuild/.taco_home/remote-builds/taco-remote/builds/697/cordovaApp/platforms/ios/cordova/Api.js:255:20
1>  Failed to build app for buildNumber 697: colors[style] is not a function
1>MSBUILD : cordova-build error : Error: Remote build error from the build server Build failed with error colors[style] is not a function - 1
1>  Error Remote build error from the build server Build failed with error colors[style] is not a function - {1}

**Comment by macdonst** [comment]
@thegruffalo sorry man but I don't have the time nor the inclination to research, reproduce and fix bugs with the `taco` CLI. You are better off raising an issue with Microsoft. It appears they don't have cocoapods installed on their build service. Without cocoapods you'll need to use the 1.8.x version of this plugin.
