### ISSUE TITLE
.on('notification') Handler For Silent Notifications Called Less Times Than Expected (Ionic + Fabric/Crashlytics)

### ISSUE THREAD

**Issue by jourdan-jobox** [phonegap/phonegap-plugin-push#1504]
### Expected Behaviour
It seems that only on a Fabric/Crashlytics build (and potentially TestFlight? I'm not sure yet), the `.on` notification handler frequently stops executing after the 3rd silent notification is processed. I noticed that this does not seem to happen on a local Xcode build. The expected behavior is, for example, if I send myself 5 silent notifications, that the `.on('notification')` handler is called 5 times.

### Actual Behaviour
Usually, `.on('notification')` is called no more than 3 times.

#### Steps to Reproduce 
- Inside `.on('notification')` handler, display a toast message
- Submit an iOS build via Fabric/Crashlytics
- Open your app, put your app in the background
- Send yourself about 5+ silent notifications
- Open your app again, and you'll usually see less than 5 toast messages

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.2

#### Cordova CLI version and cordova platform version
`cordova --version`: 6.4.0

#### Plugin version
`cordova plugin version | grep phonegap-plugin-push`: phonegap-plugin-push 1.9.2 "PushPlugin"

#### Sample Push Data Payload
In Ruby:
```ruby
{
  aps: {
    'content-available': 1
  }
  notId: SecureRandom.uuid
}
```

#### Sample Code that illustrates the problem
```js
this.push.on('notification', (notification: any) => {
   this.showToasts('notification handler called');
   this.push.finish(() => {}, () => {}, notification.additionalData.notId);
});
```

#### Logs taken while reproducing problem
N/A because I don't know how to see console logs generated from Crashlytics builds

#### Personal Notes
If it's working as expected in a regular Xcode build, it could be that perhaps my Build Settings aren't configured properly, meaning somehow a Fabric/Crashlytics build has something different compared to my Xcode build. If anyone has any pointers regarding this or can point me in the right direction, please feel free to share.

**Comment by macdonst** [comment]
@jourdan-jobox woof, that is pretty specific issue but I don't have a setup like yours to reproduce. If other folks can help I'd really appreciate it.
