### ISSUE TITLE
Push notifications not working on iOS production (v1.9.2 and v.2.0.x tested)

### ISSUE THREAD

**Issue by wiewioraseb** [phonegap/phonegap-plugin-push#1505]
### Expected Behaviour
Receive push notification for iOS on production after sending them from Firebase Notification console. Plugin version - 1.9.2 and 2.0.x tested. Not working.

### Actual Behaviour
I get the notification for Android dev/prod but for iOS I got only for development. All sent from Firebase.

For iOS on production I can see logs saying that I received FCM registration token and also this log: 

`default 12:55:41.361990 +0100 MyApplication2017 [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.`

while I can see this snipped of code in my AppDelegate.m :
`[FIRApp configure];`
so I'm not sure if this is related. 

#### Steps to Reproduce 

Create production application for iOS (TestFlight) with plugin version 1.9.2 or 2.0.x.
Send push notification from Firebase console.

#### Platform and Version
target iOS 8.0

#### Cordova CLI version and cordova platform version

    phonegap --version   6.4.2
    phonegap platform version ios   4.3.1

#### Plugin version

    version phonegap-plugin-push  v1.9.2 and v2.0.x 

#### Sample Push Data Payload
Just a standard new message to all from Firebase console. 
  
.  
I will be grateful for any tips.

**Comment by macdonst** [comment]
@wiewioraseb yes, it does work but you should not be calling `FIRApp configure` in your AppDelegate.m as it is called in PushPlugin.m. You could potentially cause your app to crash if you call it twice.

**Comment by wiewioraseb** [comment]
@macdonst but this snipped of code was not added by me. It was already there, created by cordova.

**Comment by macdonst** [comment]
@wiewioraseb nope, cordova-ios does not put that line in AppDelegate.m and neither does this plugin. Do you have another plugin in your project that is mucking with things?

**Comment by wiewioraseb** [comment]
This is the list of my plugins:

```
call-number 0.0.2 "Cordova Call Number Plugin"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-vibration 2.1.3 "Vibration"
cordova-plugin-whitelist 1.2.2 "Whitelist"
phonegap-plugin-push 2.0.0-rc2 "PushPlugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.2.1 "Launch Navigator"

```

**Comment by wiewioraseb** [comment]
@macdonst Ups. I have gcmSandbox: false

```
  var push = PushNotification.init({
    android: {
      senderID: "882945405543"
    },
    ios: {
      senderID: "882945405543",
      gcmSandbox: false,
      alert: "true",
      badge: "false",
      sound: "true"
    }
  });

```

**Comment by wiewioraseb** [comment]
@macdonst Still no luck. 
I got rid of this `FIRApp configure` in AppDelegate.m.
Changed gcmSandbox to fcmSanbox. 
Obviously I build as production.
Removed platforms, removed plugin directory, created again.
Still no notifications on iOS.

Could anyone confirm that it's possible to send push notifications from Firebase console to production iOS?
Thanks in advance.

**Comment by wiewioraseb** [comment]
I rolled back to version 1.9.2 with config:
```
  var push = PushNotification.init({
    android: {
      senderID: "XYZXYZXYZXYZ"
    },
    ios: {
      alert: "true",
      badge: "false",
      sound: "true"
    }
  });
```
I used APNS online tester form for iOS APNS (pushtry.com) to send notifications on ios production and development. Development work good, but still no notification for production.

In this case the blame should be on certificates, but on production i receive registration token, and also I created everything for certificate 3 times already from the beginning. So this should not be the reason.

**Comment by macdonst** [comment]
@wiewioraseb yeah, this really sounds like a certification problem. It seems like the app is registering with one server and the pushes are being sent with a different one. Can you run it in Xcode to see if there are any better logs or sniff the network traffic to see if the device is registering with the sandbox or production APNS?

**Comment by wiewioraseb** [comment]
Thank you for your response. I did go thought logs in console for app in production, but I haven't found anything that could give me a clue to solve the issue.

I'm not sure if there are any logs with information about sandbox or production APNS. Is 'apns' process itself responsible for logging this?

Browsing the logs, this one got me thinking:
```
Setting topics for environment production:
enabled: (
)
ignored: (
)
opportunistic:(
    "com.apple.TestFlight",
    "com.apple.mobilenotes",
    "com.apple.icloud-container.com.apple.mobilenotes",
    "com.mycompany.mycustomapp",
    "com.adobe.phonegap.app"
)
```
Maybe `"com.mycompany.mycustomapp"` should be somehow placed in enabled section?

**Comment by Jntz** [comment]
I have same problem. Every app build working well except Testflight build. Have @wiewioraseb any progress?

**Comment by wiewioraseb** [comment]
@Jntz I remember I tried hard to solve this, but failed. I had to forfeit after working on this for 3 nights.

**Comment by Jntz** [comment]
Ok. Yup I used 2 weeks that I got that plugin work with iOS so it's not surprise that I need to spend same time to fix that problem then..

**Comment by ef33zy** [comment]
What 'type' of certificate are you uploading to Firebase/GCM?
It should be the 'Apple Push Services' certificate used to generate the .P12

![image](https://cloud.githubusercontent.com/assets/15075449/24966168/21549c92-1f9e-11e7-8bdd-cf29282fd0b8.png)

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.

**Comment by vijayb** [comment]
I'm having this issue as well. I can built a production release of my Ionic/Cordova app and deploy manually to my phone. I can get push notifications to show up on the phone when I use the Pusher tool on Mac. However, when I try to use the Firebase console to send message nothing shows up. Would really appreciate some advice/steps on how I might get that to work. I have an iOS app setup in my Firebase account with the details that come from Apple developer account. I don't see anywhere to put in my p12 certificate, however

**Comment by windhandel** [comment]
Where in the plugin installation steps does it mention ever needing a firebase account?  Call me crazy, but shouldn't the plugin actually mention that it's entirely predicated on firebase and what to do to set it up?
