### ISSUE TITLE
Question: How to enable the push notification capability (not on XCode)?

### ISSUE THREAD

**Issue by kukikiloke** [phonegap/phonegap-plugin-push#1507]
1. When I build the app through cordova CLI, the push notification does not work properly.
2. I open the project on XCode, enable the Push Notifications under capabilities, rebuild the project through XCode and push notification works properly.
3. Is there some config that I can set like in config.xml or Info.plist to enable the capability so that I don't have to enable it with XCode, anyone? If this is not the expected behaviour, can someone point me some steps which I might have missed?

**Comment by kukikiloke** [comment]
Will this issue be fixed by [this PR](https://github.com/phonegap/phonegap-plugin-push/pull/1469/files) ?

**Comment by macdonst** [comment]
@kukikiloke will be fixed by cordova-ios change, see #1498

**Comment by liujiekm** [comment]
any solution?

**Comment by amodolo** [comment]
i'm in the same situation. Anyone have found some workaround?

**Comment by jcesarmobile** [comment]
It's not implemented in cordova-ios yet

But anyway, push notifications are enabled and work fine, just because it doesn't appear as enabled on Xcode doesn't mean they aren't enabled.

**Comment by lfxsantos** [comment]
@jcesarmobile for me push notifications aren't enabled. How did you enabled?

**Comment by jcesarmobile** [comment]
You don't have to enable them, Cordova enables them, but it's not visible on Xcode

**Comment by lfxsantos** [comment]
@jcesarmobile tks. For me, after add this plugin in my project my process to generate the archive failed. I have to open the xcode every build and enable manually.
