### ISSUE TITLE
iOS initialization gives "Invalid key in checkin plist" error

### ISSUE THREAD

**Issue by stib** [phonegap/phonegap-plugin-push#1508]
### Expected Behaviour
The iOS message should show up on device and the code for notification event should hit the breakpoint. Works for Android.

### Actual Behaviour
The message doesn't show up and the breakpoint is not hit on iOS. Works for Android.
Get this error in Xcode with physical device connected

> 2017-01-05 14:44:53.011113 GroupTrac[19362:13586632] GCM Sender ID XXXXXX
> 2017-01-05 14:44:53.011185 GroupTrac[19362:13586632] Using GCM Notification
> 2017-01-05 14:44:53.067104 GroupTrac[19362:13586451] Push Plugin register success: <xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx  xxxxxxxx xxxxxxxx>
> 2017-01-05 14:44:53.163: GCM | GCM library version 1.1.4
> 2017-01-05 14:44:53.174: GCM | Invalid key in checkin plist: GMSInstanceIDDeviceDataVersion

Tried sending the message through FB console to the device directly and also through the Topic that the device is registered to. The status there says "Completed" but the message doesn't arrive on iPhone. Android device also subscribed to the same Topic receives the message through FB console, and also a direct message to the Android device (to the registration id) works fine.

I have looked at the development and production certificates and redone the installation couple times to be sure.

### Reproduce Scenario (including but not limited to)
Standard setup with this iOS configuration

`"ios": {
		       "senderID": senderID,
		       "gcmSandbox": true,
			   "sound": true,
			   "vibration": true,
			   "badge": true
		   },`

I saw in some other posts that having quotes around the boolean value of gcmSandbox may have some effect tried both with and without quotes and tried both true and false.

#### Steps to Reproduce 
using phonegap-plugin-push version 1.9.2
Start the app with the above configuration and see the error when PushNotification initializes

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 8.0

output of `ionic info` is below

> Cordova CLI: 6.4.0 
> Ionic CLI Version: 2.1.8
> Ionic App Lib Version: 2.1.4
> ios-deploy version: 1.9.0 
> ios-sim version: 5.0.11 
> OS: OS X El Capitan
> Node Version: v6.9.1
> Xcode version: Xcode 8.0 Build version 8A218a

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
N/A  - The one I have working is an old Nexus phone - receives notifications

#### Cordova CLI version and cordova platform version
    cordova --version            6.4.0                        
    cordova platform version android      4.1.1      

#### Plugin version
    cordova plugin version | grep phonegap-plugin-push   1.9.2

#### Sample Push Data Payload
```
message.addData('title', 'Direct test message');
message.addData('body', 'Body of test message');
```
#### Sample Code that illustrates the problem
<Not sure what code I can provide here>

#### Logs taken while reproducing problem
> 2017-01-05 14:44:53.011113 GroupTrac[19362:13586632] GCM Sender ID XXXXXX
> 2017-01-05 14:44:53.011185 GroupTrac[19362:13586632] Using GCM Notification
> 2017-01-05 14:44:53.067104 GroupTrac[19362:13586451] Push Plugin register success: <xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx  xxxxxxxx xxxxxxxx>
> 2017-01-05 14:44:53.163: GCM | GCM library version 1.1.4
> 2017-01-05 14:44:53.174: GCM | Invalid key in checkin plist: GMSInstanceIDDeviceDataVersion

Other tickets I have seen on this seem to indicate certificate being a potential problem but I have checked that. I have turned on Push Notification in Xcode capabilities.

Being new to Xcode I am not sure where is the environment variable is set for the code to pick development or production - I have tried gcmSandbox both true and false with and without quotes.

I have also recently removed and added ios platform to the project so that shouldn't be an issue either.

Not quite sure how to debug this failure. Appreciate any pointers.

Thanks,
Sanjay.

**Comment by stib** [comment]
iOS version of the iPhone I am running the App on is 10.0.2

**Comment by macdonst** [comment]
@stib Did you check if the bundle id that you've got in the gcm configuration plist corresponds to the bundle id in the APN certificate and the bundle id of your xcode project?

**Comment by stib** [comment]
Thanks @macdonst I double checked and confirmed that the bundle id matches across. To be sure,  I have a different bundle id for the Android side but I understand the system allows for that so we should be fine there.

I tried to look through the other fields in the gcm configuration list to be sure and found that the API_KEY in the plist file is similar to the Web API key on Firebase but doesn't match. Aren't they supposed to match?

**Comment by stib** [comment]
Update: I noticed that the API KEY for Android, iOS and Web are similar but different - sounds like they are meant to be different for different platforms.

Look forward to any pointers on what else I can do to debug and resolve this issue. Thanks.

**Comment by stib** [comment]
Hi @macdonst - I have been trying to figure out why I am getting the "Invalid key in checkin plist: GMSInstanceIDDeviceDataVersion" error I am getting and can't send out message to iOS device. I have tried the following with partial success.

I have been trying to send message using your sample code as below 

```
var gcm = require('node-gcm');

// Replace these with your own values.
var apiKey = <SERVER Key>; 
var deviceID = <DEVICE REG ID>;

var service = new gcm.Sender(apiKey);
var message = new gcm.Message();
message.addData('title', 'Direct test message');
message.addData('body', 'Body of test message');

service.send(message, { registrationTokens: [ deviceID ] }, function (err, response) {  
	if(err) console.error(err);
	else 	console.log(response);
});
```

and the system tells me it is delivered successfully (as below) but I don't get that message on iPhone.

> { multicast_id: 7551079996355907000,
>   success: 1,
>   failure: 0,
>   canonical_ids: 0,
>   results: [ { message_id: '0:1483860185792872%d8f24420f9fd7ecd' } ] }

Since sending message through Firebase console was also saying "Completed" but not delivering the message I contacted Firebase support and they asked me to run the code below

```
server_key=<Project server key>
curl --header "Authorization: key=$server_key" \
--header Content-Type:"application/json" \
https://fcm.googleapis.com/fcm/send \
-d '{"to":"<Registration token of FCM>","priority":"high","notification":{"body":"testing","title":"testing"}}'
```

Running this code gave an InternalServerError as below

> {"multicast_id":5734231541072545433,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"InternalServerError"}]}

Firebase support said that could be caused by any number of issues and were asking for more information. Before doing that, I decided to clean up the whole thing and redo the certificates one more time.

Now when I run the Firebase code above with curl command and also through the Firebase console using the same registration id the message gets delivered to my iPhone. But using the node-gcm code (above from your example) I get the same success result but the message still doesn't get delivered. One thing I can deduce from this is that it is not a certificate issue anymore.

And all along I still see the error "Invalid key in checkin plist: GMSInstanceIDDeviceDataVersion" when I try to run the code from Xcode on my device while the push plugin is registered successfully.

Not quite sure what to try next, I decided to remove the GoogleServices-Info.plist file from my project and to my surprise the error didn't change - I was expecting it to complain about the file missing but don't see any such error. But without the Info.plist file the code is still able to register the Push Plugin successfully. To be sure, I had the GoogleServices-Info.plist file in platforms/ios directory - at the same level as the .xcworkspace file - before removing it.

I noticed that the plugin's config.xml is looking for *-Info.plist files and searched for that in platforms/ios. I noticed that under platforms/ios/<AppName> we have a file <AppName>-Info.plist file which has info similar to that in GoogleService-Info.plist which is perhaps being used. Not quite clear how the GoogleServices-Info.plist file gets used here.

While I am still thinking of what to do/try next I am wondering if you can help guide in some way to get to the bottom of this. Especially if you can help clarify how the GoogleServices-Info.plist file gets used. I am thinking of digging into the plugin code but that will take me some time as I am less familiar with operation of Cordova Plugins and am hoping I can avoid that.

Thanks for your help.

Sanjay.

**Comment by AbuHani** [comment]
Hello Guys,

I have the same issue, any updates ?

**Comment by monsif** [comment]
Hi, 
same issue here after updating to cordova-ios@4.4.0
