### ISSUE TITLE
Know which version is used in build service

### ISSUE THREAD

**Issue by oscarabilleira** [phonegap/phonegap-plugin-push#151]
With build service is there any way to Know which version of this plugin is used in build service at any time?

**Comment by macdonst** [comment]
@oscarabilleira Do you mean on PhoneGap Build? All you need to do is setup the correct tag in config.xml:

`<gap:plugin name="phonegap-plugin-push" source="npm" version="1.2.3" />`

You use the version attribute to specify what version you want.

**Comment by oscarabilleira** [comment]
Thanks, I knew that, I asked if I use without version, is supposed to use the last version avaliable .

<gap:plugin name="phonegap-plugin-push" source="npm" " />

**Comment by macdonst** [comment]
@oscarabilleira yes, it will use the latest.
