### ISSUE TITLE
Getting 'malformed config.xml' error in Phonegap Build

### ISSUE THREAD

**Issue by jamminjames** [phonegap/phonegap-plugin-push#1511]
I'm getting a  'malformed config.xml' error in Phonegap Build when I include the plugin like so:
`<plugin name="phonegap-plugin-push" spec="~1.8.4" source="npm">
	<param name="SENDER_ID" value="<MySenderID>" />
</plugin>`

When I take that out, it passes, so the problem is in this block. It seems fine to me, can someone tell me what's wrong with it? (Of course, I have my actual sender ID in there for the value.)

Most plugin names for Phonegap start with "cordova", that's not it, is it?

**Comment by jamminjames** [comment]
Okay, took the brackets out for the version number, just using the number itself between the quotes, and it passed. The example in the instructions seemed to indicate you need the brackets.

**Comment by macdonst** [comment]
@jamminjames what example instructions?

**Comment by jamminjames** [comment]
At https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md

**Comment by macdonst** [comment]
@jamminjames oh, I see. No, don't include the `<` or `>`. Everything inside those brackets should be replaced including the brackets.

**Comment by fredgalvao** [comment]
Reopening for doc improvement.

**Comment by fredgalvao** [comment]
Fixed on abdb656315bd4457c7ae43aaa52e2357df85d139, @jamminjames please let me know if that makes it clear. Also, thanks for spotting hard spots on the docs!

**Comment by jamminjames** [comment]
Yes, thanks, and you're quite welcome!
