### ISSUE TITLE
Unable to get device token value in iOS 10.0 with ionic?

### ISSUE THREAD

**Issue by manojrejinthala** [phonegap/phonegap-plugin-push#1512]
I successfully received push notifications in Android and iPad but I am not able to get push notifications because I am not able get the device token from the iPhone of version 10.0 - it gives me undefined value.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by manojrejinthala** [comment]
Please check now i updated the info
