### ISSUE TITLE
Unable to get device token value in iOS 10.0 with ionic? 

### ISSUE THREAD

**Issue by manojrejinthala** [phonegap/phonegap-plugin-push#1514]
Expected Behaviour
unable to get the device token form the device ios of os version 10.0
Actual Behaviour
I successfully received push notifications in Android and iPad but I am not able to get push notifications because I am not able get the device token from the iPhone of version 10.0 - it gives me undefined value.

Steps to Reproduce
download example project, created cert, upload p12 to firebase, downloaded .plist and provisioning profile, enabled in capabilities push notification mode, i.e. all neccessary things for push notification.
Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.1.1
Cordova CLI version and cordova platform version
cordova --version: 6.4.0
cordova platform version ios: 4.3.1

Plugin version
cordova plugin version | grep phonegap-plugin-push: e.g. 1.8.4

Sample Code that illustrates the problem
var push = PushNotification.init({
"android": {
"senderID": "61426985247"
},
"ios": {"alert": "true", "badge": "true", "sound": "true"},
"windows": {}
});

push.on('registration', function(data) {
    console.log("registration event");
    //here is your registration id
	$rootScope.deviceToken1=data;
    alert(JSON.stringify($rootScope.deviceToken1));
});

Logs taken while reproducing problem

**Comment by hazeem1991** [comment]
if you are using fcm you should set the sender id in ios to like this 
 var push=Push.init({
        android: {
          senderID: "615407541952",
          icon: "ic_stat_iconn",
          iconColor: "#991B55"
        },
        ios: {
          senderID: "615407541952",
          alert: "true",
          badge: true,
          sound: 'true'
        },
        windows: {}
      });

**Comment by macdonst** [comment]
@manojrejinthala  in Xcode 8 there is a problem where the Push Notification toggle needs to get set to ON in this screen.

![xcode](https://cloud.githubusercontent.com/assets/12952835/18989625/430a9686-870d-11e6-9b17-8da03f860e7c.png)

I'm not sure what version of cordova-ios you are using but there was an attempt at a fix in cordova-ios 4.3.x and a true fix should be in cordova-ios 4.4.0. You should try using version 1.9.0 where we have the partial fix.
