### ISSUE TITLE
How play sound and vibrate when app is in foreground?

### ISSUE THREAD

**Issue by malwatte** [phonegap/phonegap-plugin-push#1515]
Hi,
I need to play sound and vibrate when a push receives even if the app is in foreground. Currently sound/vibration works only when app is background. I am not sure how can I achieve this. Any suggestion is greatly appreciated.
Thank you.

**Comment by fredgalvao** [comment]
Have you tried changing the value of `android.forceShow` during `init`? Check the description on the docs and see if that solves it for you: [here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#android).

**Comment by malwatte** [comment]
Yes. I checked forceShow. But if the app is foreground, I do not want to show a push notification in OS notification bar. I want to handle in the app itself. Additionally I need to play notification sound.
Looks like I have to use another plugin to play a sound.
What do you think?

**Comment by macdonst** [comment]
@malwatte yes, that is exactly what you need to do. You will be able to do something like this:

```
push.on('notification', function(data) {
  if (data.sound) {
    var mySound = new Media(data.sound);
    mySound.play();
    navigator.vibrate(1000);
  }
});
```

If you include cordova-plugin-media and cordova-plugin-vibration.
