### ISSUE TITLE
Push notification not received in production ios using xcode8

### ISSUE THREAD

**Issue by ai2010** [phonegap/phonegap-plugin-push#1516]
### Expected Behaviour
Push notification received  both in development and production mode in ios
### Actual Behaviour
Push notification not received when the production certificate is used
### Reproduce Scenario (including but not limited to)
Using a service like http://pushtry.com/, send a push to a device with the token id, if the 'production' field is checked the push is not received
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ios 9.3
#### Cordova CLI version and cordova platform version
Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 8.2.1 Build version 8C1002                

#### Plugin version
phonegap-plugin-push 1.9.0 "PushPlugin"

**Comment by ai2010** [comment]
I did ionic build ios --release and the app is then build in release (Product->Scheme->Edit Scheme->Run-> Build Configuration).
The push notifications are on. I didn't have this problem on xcode 7: even in debug mode the push were received.
Is there something else I should do?

**Comment by macdonst** [comment]
@ai2010 in Xcode 8 there is a problem where the Push Notification toggle needs to get set to ON in this screen.

![xcode](https://cloud.githubusercontent.com/assets/12952835/18989625/430a9686-870d-11e6-9b17-8da03f860e7c.png)

I'm not sure what version of cordova-ios you are using but there was an attempt at a fix in cordova-ios 4.3.x and a true fix should be in cordova-ios 4.4.0.

**Comment by ai2010** [comment]
@macdonst PushNotificatins toggle is definitely on. Do you mean In-app Purchase toggle on?

**Comment by macdonst** [comment]
@ai2010 No, I mean the push notification one. I was just using the above image as an example. 

If the app is signed with the production cert and is getting a registration ID then the only thing it can be is that your push service is sending the push to the development APNS server. I'd look at pushtry.com and see what info they get back. They must have a way to check the APNS response code.

**Comment by ai2010** [comment]
Ok thanks

**Comment by ai2010** [comment]
Yes I confirm the problem: using the production certificate in pushtry.com it will send only if I uncheck production (so I guess in development mode)

**Comment by ai2010** [comment]
Furthermore: In my ionic settings ('Security Profiles & Credentials') I put the production certificates in the development settings and I can receive the push.

**Comment by macdonst** [comment]
@ai2010 so I don't think this is an issue with the plugin. Can we close the issue?

**Comment by ai2010** [comment]
Well fi you can be kind to let it open so maybe someone else can provide a solution... I don't really know what to do.

**Comment by macdonst** [comment]
@ai2010 it's a certification problem for sure. You have a mis-match between the client and server. You are either trying to send via production but your app is built for development or you are trying to send to development when your app is built for production. Not sure what else to tell you.

**Comment by ai2010** [comment]
Is there any way to check if the app installed is in release or debug mode?

**Comment by jcesarmobile** [comment]
If you try to debug it with safari remote web inspector, you won't be able to do it if the app is in release mode.

Also, is good to send the push notifications from your Mac with Pusher (https://github.com/noodlewerk/NWPusher) just to check the certificates are good

**Comment by ai2010** [comment]
Ok just used it. When in production the error is 'Notification error: APN invalid token'

**Comment by ai2010** [comment]
Ok for some reasons Specialguest.entitlements has 'APS Environment' set to development. If I change it manually to production I got the problem in Capabilities:
<img width="678" alt="capture d ecran 2017-01-12 a 19 37 23" src="https://cloud.githubusercontent.com/assets/8618000/21905227/9a4d4cf2-d8fe-11e6-9921-e67e15055a49.png">
If I press 'fixx issue' it will sent 'APS Environment' to development. For the record in my ionic folder the Specialguest.entitlements file is:
`<plist version="1.0">
<dict>
	<key>aps-environment</key>
	<string>production</string>
</dict>
</plist>`

**Comment by macdonst** [comment]
@ai2010 are you sure you are building for release? If you are pressing "Fix issue" and it sets it to "development" then Xcode must think you are doing a development build.

**Comment by jcesarmobile** [comment]
That is a bug in Xcode (or a feature), if you change the value to production, then the issue appears in capabilities.
According to people, you don't have to change it to production, when you archive and sign it will use the right value http://stackoverflow.com/questions/39266891/xcode-8-push-notification-capabilities-and-entitlements-file-setting

**Comment by vijayb** [comment]
I had this same issue. I could get push notifications to work locally using Pusher, but it wouldn't work with pushtry.com. Turned out that the certificate I was using I thought was a production certificate, but it wasn't, so I had to uncheck the production flag in the pushtry interface
