### ISSUE TITLE
Apple Match-O Linker Error

### ISSUE THREAD

**Issue by akz92** [phonegap/phonegap-plugin-push#1518]
### Expected Behaviour

Run app on iOS simulator

### Actual Behaviour

Xcode compilation error

#### Steps to Reproduce 

Add the plugin to the project and try to run on a simulator from Xcode

#### Platform and Version
    iOS 10.2

#### Cordova CLI version and cordova platform version

    cordova version: 6.4.0
    cordova ios version: 4.3.1

#### Plugin version

    phonegap-plugin-push version: 1.9.2

#### Logs taken while reproducing problem

    ld: library not found for -lPods-*ProjectName*
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by macdonst** [comment]
@akz92 push notifications are not supported on the simulator so I'm not going to spend any time on this.

**Comment by akz92** [comment]
@macdonst I'm sorry, I didn't provide all the details. This error also happens when compiling for a device or to archive.

**Comment by macdonst** [comment]
@akz92 well that's totally different then. Make sure you have [cocoapods](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#cocoapods) 1.1.1 installed and do `pod setup`. Also, if you are upgrading from an earlier version of cordova-ios you may want to do:

```
cordova platform rm ios
cordova platform add ios
```

**Comment by Jarvey** [comment]
@akz92 I have the exact same issue. I have cocoapods-1.1.1 installed and removed my iOS platform en added it again. issue is still there.

**Comment by tiff** [comment]
Same problem here. cocoa-pods 1.1.1 and re-adding ios platform didn't help

**Comment by akz92** [comment]
@macdonst I did what you suggested but nothing changed =/

**Comment by svewag** [comment]
Same problem here

**Comment by tiff** [comment]
Workaround: Open project in XCode -> Go to "Build Phases" -> "Link Binary with Libraries" -> Remove the Pods entry

**Comment by VinceRafale** [comment]
try to open the .xcworkspace instead of the .xcodeproj file with xcode

**Comment by akz92** [comment]
Opening the `.xcworkspace` solved the issue for me

**Comment by macdonst** [comment]
Yeah, you should be opening the `.xcworkspace`. Now that cordova-ios has cocoapod support there are 2 projects that are now contained in the work space.

**Comment by Gopimaruvada** [comment]
Hii all how to add a  .m file in xcode

**Comment by jeffreyrajanofficial** [comment]
Updating the pod helped me to fix this issue. 
`pop update`
Use this code in your iOS directory
