### ISSUE TITLE
Image on push notification iOS

### ISSUE THREAD

**Issue by lionalex** [phonegap/phonegap-plugin-push#1519]
In Android when I set the "image" value in the fields sended to FMC, I see this image in notification alert.
Io iOS I don't see this image. Why? Is possible to attach a custom image in the iOS notification?

In Android I use this structure to show the image:
```
$fields = array(
'data' => array (
					"title"			=> "Title notification",
					"message" 		=> "message text",
					"priority" 		=> 2,
					"sound" 		=> "default",
					"image"			=> "http://www.url.com/images.png"
)
);
```

**Comment by macdonst** [comment]
@lionalex nope, not currently possible.

**Comment by tgensol** [comment]
Do you think it will be possible "soon" ? Thanks ! :)

**Comment by macdonst** [comment]
@tgensol I've actually got it implemented now in the `rich` branch but I'm waiting for some changes to cordova-ios. Without them it is a very manual process.

**Comment by lluisnieto** [comment]
Any updates on this. I'm also waiting for this as a kid in christmas.

**Comment by macdonst** [comment]
@lluisnieto I need a fix in cordova-ios to support multiple targets. Shazon hopes to that in the 4.5.0 release but no date so far.

**Comment by ruhan974** [comment]
@macdonst is it possible to implement this function manually with cordova? 
I created the files indicated in this link but I can not send images on ios:
https://github.com/phonegap/phonegap-plugin-push/commit/154f2cb68433e48dd0d195e4104051f8eb625a4b
Thank you in advance for your help

**Comment by Jeremlicious** [comment]
Hi, any update on implementing push with images on iOS ?

**Comment by erictonussi** [comment]
@macdonst , any news on this? Looks like cordova-ios reached 4.5.0 6 months ago

**Comment by d3vtoolsmith** [comment]
cordova-ios is now on v4.5.4, does it yet include the needed fix for iOS support of 'image'? 
just wanted to see if it's in the plans at all. 
thank you
