### ISSUE TITLE
Not Foreground true when notification screen open

### ISSUE THREAD

**Issue by carlos-beny** [phonegap/phonegap-plugin-push#152]
If you open the app and open the notification screen, if in this momento you received a notification, it not load in notification screen and when close the notification screen you have aditionalData.foreground = false, but it should be true or you should have a notification in the notification screen.

And nothig of that is happened, in this case you lost the notification.

Thank you

**Comment by macdonst** [comment]
@carlos-beny what platform? iOS, Android or both?

**Comment by carlos-beny** [comment]
@macdonst, sorry. I ony tried un iOs

**Comment by macdonst** [comment]
@carlos-beny No problem, just like to know where to focus my testing on.

Simon Mac Donald
http://hi.im/simonmacdonald

**Comment by carlos-beny** [comment]
More data, I tried the same on Nexus 4, Android 5.1.1 and everything work.

I detected this error on Iphone 5s, with iOs 7

**Comment by macdonst** [comment]
@carlos-beny I see what you mean as I have been able to reproduce this but I'm not sure if there is anything I can do about it. For instance if you try the same scenario with the Gmail app on iOS you will see the same issue. So unless something changes, like someone comes up with something that I'm unaware of I'm going to close this issue.
