### ISSUE TITLE
windows phone push notification while app is running

### ISSUE THREAD

**Issue by mkurzweil** [phonegap/phonegap-plugin-push#1520]
### Expected Behaviour
Get only push notification, if the app runs in the background.

### Actual Behaviour
It works perfectly on iOS and android, but on windows phone I get also a push notification while the app is running in front.

#### Steps to Reproduce 
1.) Open App and let it successful register
2.) Send a event for a push notification
3.) Push notification will be shown while app is running

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
windows phone 8.1 and also 10

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Microsoft Lumia 550

#### Cordova CLI version and cordova platform version

    cordova --version  --> 6.4.0
    cordova platform version android -->4.4.2

#### Plugin version

    phonegap-plugin-push 1.9.0 "PushPlugin"

#### Sample Code that illustrates the problem
    var push = PushNotification.init({
             "android": {
                 "senderID": "XXXXXXX"
              },
             "ios": {
                senderID: "XXXXXXXX",
                 alert: "true",
                 badge: "true",
                 sound: "true",
                 gcmSandbox: "false"
             },
                  "windows": {}
        });

**Comment by mkurzweil** [comment]
No one?

**Comment by nates-dennis** [comment]
firstly what type of push notification are you sending eg. toast/raw

**Comment by mkurzweil** [comment]
@nates-dennis toast/raw

**Comment by nates-dennis** [comment]
if it is a toast notification you need to implment the onActivated event and use launchArgs this should help
#1033 (comment)

**Comment by samimaliks** [comment]
I am facing same issue, when app is in foreground in IOS, event handler automatically calls.,

**Comment by iometrine** [comment]
I have the same problem, on windows phone I get also a push notification while the app is running in front.

I saw here something interessting :
https://docs.microsoft.com/fr-fr/windows/uwp/controls-and-patterns/tiles-and-notifications-adaptive-interactive-toasts#a-namehandling-activation-foreground-and-backgroundagestion-de-lactivation-au-premier-plan-et-en-arrière-plan

Here a piece of code 
```
<toast launch? duration? activationType? scenario? >
  <visual lang? baseUri? addImageQuery? >
    <binding template? lang? baseUri? addImageQuery? >
      <text lang? hint-maxLines? >content</text>
      <image src placement? alt? addImageQuery? hint-crop? />
      <group>
        <subgroup hint-weight? hint-textStacking? >
          <text />
          <image />
        </subgroup>
      </group>
    </binding>
  </visual>
  <audio src? loop? silent? />
</toast>
```

There is a field 'ActivationType' who take this values 
activationType? = "foreground | background | protocol | system"

So I tried to put  backgroung but it doesn't work. I think this functionality is not implemented yet to this plugin.

If someone has other idea, it would be great.

**Comment by iometrine** [comment]
Yes, i did many test.

But if i understand well the doc , the parameter launch let to launch the notification in background, but my problem is different, i have the toast in backgroung I just doesn't  want to get  the toast in foreground.

**Comment by nates-dennis** [comment]
i understand what you mean now. i could not find a way of controlling that either so when the app is in the foreground unlike Android and IOS it seems the toast will always come i have not seen anything that says that can be changed.

**Comment by michaelulm** [comment]
Any solution for this problem available?
