### ISSUE TITLE
Override Silent Mode / Device Volume Settings

### ISSUE THREAD

**Issue by ggiordan** [phonegap/phonegap-plugin-push#1521]
I have some iOS users asking for the ability to override silent settings.  I have mixed feelings about this, but who am I to say they're wrong.

Is there a way, to override a silenced device (if the user so asks for this, my thinking would be to have a switch for them).  With android, you pretty much have this ability using priority alerts.

I did find this, so it seems that it would be possible.  My other thought would be to have some code when the push is received and play the sound in the callback.  The trick here would be to figure out that the device is silenced and we're not in the foreground and the user wants a silence override, then play the sound problematically.

I did find this too, so I guess it's possible:
http://stackoverflow.com/questions/3740528/play-sound-on-iphone-even-in-silent-mode

**Comment by macdonst** [comment]
@ggiordan Notifications cannot override the ring/silent switch or the device’s Do Not Disturb setting. At best you can have the notification vibrate the phone which is referenced in #1509. The SO question you referenced would not work in this case as the OS does the audio playing when the push is received.

**Comment by ggiordan** [comment]
@macdonst, I get overriding the switch, what about when the device is DND? I may have been a bit unclear.  The SO article I reference seems to imply that it's possible.  Or are am I mixing apples and  oranges?

**Comment by macdonst** [comment]
@ggiordan the SO article talks about when your app is in the foreground. If the app is in the background the OS is in charge of displaying the notification and playing the sounds so there is no way around AFAIK.

If you do figure out how it's done then send me a PR.

**Comment by ggiordan** [comment]
ok, sure thing, I'll play with it some.  My thinking is that if I can make use the content-available: 1 stuff (https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications-1) then we've got 30 seconds to do something.  the key here i think is to know if the phone is DND, if that can be detected, then you know that you should play the sound (if the service has been requested).  Thoughts?
