### ISSUE TITLE
Notification does not use the icon passed in `init`

### ISSUE THREAD

**Issue by firoze** [phonegap/phonegap-plugin-push#1522]
### Expected Behaviour
Notification should use icon whose name was passed in `PushNotification.init`

### Actual Behaviour
Notification icon falls back to app icon, and since app icon does not have transparency, icon is a white square in notification

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Tested on Android 5.0 through 7.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
OnePlus One, Galaxy S7, Asus Zenfone 2

#### Cordova CLI version and cordova platform version
Cordova 6.4.0
Cordova Android 6.1.1

#### Plugin version
PushPlugin 1.9.2

#### Sample Push Data Payload
Unfortunately, I don't have access to this, as I don't have access to the server environment at this time. But text appears as expected so this might not be related.

#### Sample Code that illustrates the problem
```
                    const push = PushNotification.init({
                        android: {
                            senderID: CONFIG.GCM_SENDER_ID,
                            icon: 'ic_stat_droid_notification',
                            iconColor: '#1A66A7',
                            forceShow: true
                        },
                        ios: {
                            alert: true
                        },
                    });
```

#### Additional Information

The `ic_stat_droid_notification` file exists in the folder structure, in several drawable folders, separated by `drawable-*dpi`, it was created using [Roman Nurik's Icon Generator](https://romannurik.github.io/AndroidAssetStudio/icons-notification.html)
Any help would be appreciated. I'm not sure what I'm doing wrong. For now, I've avoided the white square by setting minSdkVersion to 20 so it at least shows the app icon properly, but ideally, I want to use the asset that was intended for notifications in the first place. Thanks!

**Comment by macdonst** [comment]
@firoze please get the logs from `adb logcat | grep PushPlugin` that capture when you call the `init` method.

**Comment by firoze** [comment]
@macdonst ah missed that bit earlier. here it is:

```
01-11 22:27:46.608 21504 21543 V PushPlugin: execute: action=init
01-11 22:27:46.609 21504 21554 V PushPlugin: execute: data=[{"android":{"senderID":"707025891003","icon":"ic_stat_droid_notification","iconColor":"#1A66A7","forceShow":true},"ios":{"alert":true}}]
01-11 22:27:46.612 21504 21554 V PushPlugin: execute: jo={"senderID":"707025891003","icon":"ic_stat_droid_notification","iconColor":"#1A66A7","forceShow":true}
01-11 22:27:46.613 21504 21554 V PushPlugin: execute: senderID=707025891003
01-11 22:27:47.390 21504 21554 V PushPlugin: onRegistered: {"registrationId":"dNgAq4GhYH0:APA91bEoQlnJKoX98z_Qht6PeZjlqKC1HkO3kIBDuiok3ndNXIfojl0J5muSMuNLC8WPGoehExgZIweQCHnW4MEI_3RLe_VCn4Fh_cI91NZztXq9I2kSS995C0so8e0RNFaeiSEawCv4"}
```

nothing else is logged when the actual notification comes in. the actual notification is pushed from SNS like so:

```
    self.publishPushNotification = (TopicArn, description, title) => {
        let message = {
            "default" : `${title}! \'${description}\'`,
            "GCM": `{
                        \"notification\": {
                            \"text\": \"${title}! \'${description}\'\",
                            \"title\": \"Title\",
                            \"force-start\": 1
                        },
                        \"time_to_live\": 3600
                    }`,
        };

        return SNS.publish({
            Message: JSON.stringify(message),
            Subject: 'Title',
            MessageStructure: 'json',
            TopicArn,
        }).promise();
    };
```

I reverted the plugin version to `v1.8.3` because we were having some issues with notifications on iOS on 1.9.2

Please let me know if there is any other information that I can provide.

**Comment by macdonst** [comment]
@firoze Ah, I see what your problem is. In order for this plugin to be called when a push notification is received you need to use the `data` portion, not `notification`.

Send your pushes like:

```
    self.publishPushNotification = (TopicArn, description, title) => {
        let message = {
            "default" : `${title}! \'${description}\'`,
            "GCM": `{
                        \"data\": {
                            \"body\": \"${title}! \'${description}\'\",
                            \"title\": \"Title\",
                            \"force-start\": 1
                        },
                        \"time_to_live\": 3600
                    }`,
        };

        return SNS.publish({
            Message: JSON.stringify(message),
            Subject: 'Title',
            MessageStructure: 'json',
            TopicArn,
        }).promise();
    };
```

try that and let me know if it fixes the problem.

**Comment by firoze** [comment]
@macdonst cool, thanks for the update! 👍 the reason we switched to `notification` was because when using `data`, notifications wouldn't show up on the device at all. We assumed that to be an incompatibility between GCM (or FCM?) and SNS. I'll close this issue for now. Thanks for helping me with this!

**Comment by macdonst** [comment]
@firoze yeah, the problem is that `notification` only pushes are completely handled by the OS. Putting everything in `data` makes it work in all situations.
