### ISSUE TITLE
Registration function error

### ISSUE THREAD

**Issue by LukasBlu1** [phonegap/phonegap-plugin-push#1525]
The registration function doesnt fire in IOS and Android with the phonegap build compiled app. In the phonegap test app all is working fine. What can I do to fix this?

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
