### ISSUE TITLE
(Android)PushNotification.init is not work

### ISSUE THREAD

**Issue by erica07312002** [phonegap/phonegap-plugin-push#1526]
# Expected Behaviour
I want to receive Microsoft Azure push notifications in Android, but "PushNotification.init is not work

# Actual Behaviour
Modify the program is not used "notification", only "registration" and "error" , but the implementation of the "PushNotification.init is not work
I've installed the required items through the Android SDK (see screenshot below):
![image](https://cloud.githubusercontent.com/assets/25074622/21968782/74e522be-dbd3-11e6-98c7-ce0b0ab1fcee.png)
and in config.xml install the plugin:
```
<plugin name="phonegap-plugin-push" version="1.9.2" src="https://github.com/phonegap/phonegap-plugin-push">
    <variable name="SENDER_ID" value="783223414517" />
  </plugin>
```

# Steps to Reproduce 
Follow the example:
https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-cordova-get-started-push

# Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0.2

# (Android) What device vendor (e.g. Samsung, HTC, Sony...)
HTC One Me dual sim

# Cordova CLI version and cordova platform version
Visual Studio 2015 Cordova
Cordova CLI 6.1.1

# Plugin version
cordova-plugin-inappbrowser # e.g. 1.5.0
cordova-plugin-ms-azure-mobile-apps # e.g. 2.0.0
cordova-plugin-whitelist # e.g. 1.3.1
cordova-sqlite-storage # e.g. 1.4.8
phonegap-plugin-push   # e.g. 1.9.2

# Sample Code that illustrates the problem
Different from the example index.js:

```
function onDeviceReady() {
        // Create a connection reference to our Azure Mobile Apps backend 
        client = new WindowsAzure.MobileServiceClient('https://ericaapptest.azurewebsites.net');

        if (useOfflineSync) {
            initializeStore().then(setup);
        } else {
            setup();
        }
        // Create a table reference
        todoItemTable = client.getTable('todoitem');

        // Refresh the todoItems
        refreshDisplay();

        // Wire up the UI Event Handler for the Add Item
        $('#add-item').submit(addItemHandler);
        $('#refresh').on('click', refreshDisplay);
        alert("TESTA");

        var pushRegistration = null;
        alert("TESTB");
        pushRegistration = PushNotification.init({
            android: { senderID: '783223414517' },
            ios: { alert: 'true', badge: 'true', sound: 'true' },
            wns: {}
        });

        alert("TESTC");

        pushRegistration.on('registration', function (data) {
            alert("TESTD");
        });

        push.on('error', function (e) {
            alert("Error:" + e.message);
        });

    }
```

# Logs taken while reproducing problem
alert show:
  TESTA
  TESTB
There are no other error messages
I missed something?

**Comment by fredgalvao** [comment]
How exactly did you install the plugin?

**Comment by erica07312002** [comment]
![image](https://cloud.githubusercontent.com/assets/25074622/21971665/cb232576-dbed-11e6-8d4f-b2c57cad17fb.png)

Follow the example:
https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-cordova-get-started-push

**Comment by fredgalvao** [comment]
Yes, I saw the example, just wanted to know which path you took (as it explains both CLI and VS ways). 

I didn't follow the example, as I don't have the needed environment set up for it, but I can only say that 95% chance is that the plugin wasn't correctly/successfully installed.

Could you try creating a new empty application following a raw cordova tutorial (like the ones we have on the repo docs) and see if you can at least find the `PushNotification` objetct on `window`?

**Comment by macdonst** [comment]
@erica07312002 run `adb logcat | grep PushPlugin` when starting the app so we can see what's going on.

**Comment by erica07312002** [comment]
@fredgalvao
Thank you for your response.
The path is https://github.com/phonegap/phonegap-plugin-push
I try creating a new empty application,there is no warning message before installing the PushNotification objetct,the phone performs the same result.
You are right,plugin is not work successfully installed,but I do not know other methods install plugin in Visual Studio.

**Comment by erica07312002** [comment]
@macdonst 
Sorry,I do not know where to run adb logcat | grep PushPlugin
I can not find how the work in Visual Studio

**Comment by erica07312002** [comment]
Now PushNotification.init working properly!!
Execution order:
1.Creating a new empty 
2.Install the plugin (https://github.com/phonegap/phonegap-plugin-push)
3.Cordova CLI set up 6.4.0

P.S The same application Cordova CLI set up 6.1.1 is not work
