### ISSUE TITLE
Installation is not working

### ISSUE THREAD

**Issue by akvaliya** [phonegap/phonegap-plugin-push#1527]
![push_plugin_issue](https://cloud.githubusercontent.com/assets/25152577/21984976/a45056cc-dc1e-11e6-9f3c-093621d4fe68.png)

can anyone help me with this issue??

**Comment by macdonst** [comment]
@akvaliya the version of Ionic you are using is pinned to cordova 4.1.1 and you need 6.4.0 or greater so you need to upgrade Ionic.

**Comment by akvaliya** [comment]
@macdonst I want to use this plugin with android 4.4.1
Is there anyway to do that??

**Comment by macdonst** [comment]
@akvaliya do not confuse the version of Cordova wth the version of Android. Corodva is the base and cli then cordova-android has android support and even if you had cordova-android 6.0.0 you would still be able to use this on Android 4.4.1 as the version of cordova-android is the version that we released. We are currently supporting API level 16 and up which is Android 4.1 and greater.
