### ISSUE TITLE
Push notification not received on Android when app is 'force closed' by user

### ISSUE THREAD

**Issue by TheBurgerShot** [phonegap/phonegap-plugin-push#1528]
Hi all,

I am trying to send a push notification to an Android device that is force closed by the user. I've seen several posts about this topic, but even after trying different suggested possible solutions I am not experiencing any success. The push notifications do pop up on IOS when it is force closed by the user, but for Android this does not seem to work. However, the push notifications are received when the app is in background, and after opening the app and checking the data that was sent with the push notification I can see that the data ('force-start', 'priority') is sent with the push notification. Anyone else experiencing similar problems. Solutions are more than welcome :)

### Expected Behaviour
Push notification received on Android

### Actual Behaviour
Nothing happens

### Reproduce Scenario (including but not limited to)
Sending a push notification from server with the following JSON data:

{
  'registration_ids' => ['bla-bla-bla']
  'data': {
    'badge': 1,
    'message': 'New questions available',
    'force-start': 1,
    'priority': 1,
    'title': 'My App Name',
    'notId': 1,
  },
  'time_to_live': 600,
}

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Huawei P5 Lite

#### Cordova CLI version and cordova platform version
Cordova 6.4.0
Cordova platform version 6.0.0

#### Plugin version
1.9.2

#### Sample Push Data Payload
{
  'registration_ids' => ['bla-bla-bla']
  'data': {
    'badge': 1,
    'message': 'New questions available',
    'force-start': 1,
    'priority': 1,
    'title': 'My App Name',
    'notId': 1,
  },
  'time_to_live': 600,
}

**Comment by macdonst** [comment]
@TheBurgerShot I'm pretty sure you are running into this:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#huawei-and-xiaomi-phones

Try what is documented there and let me know.

**Comment by TheBurgerShot** [comment]
@macdonst Fortunately there are always others with a sharp mind. Thanks a lot!
