### ISSUE TITLE
Badge increment on push notification not working 

### ISSUE THREAD

**Issue by amolc** [phonegap/phonegap-plugin-push#1529]
### Expected Behaviour
Badge count should be incremented
### Actual Behaviour
Badge count shows always one

#### Cordova CLI version and cordova platform version

    cordova --version      6.1.1                            
 

#### Plugin version
    cordova plugin version | grep phonegap-plugin-push   1.8.4

#### Sample Push Data Payload
     {
          "alert": "true",
          "badge": "true",
          "sound": "true"
        }

#### Sample Code that illustrates the problem

      push.on('notification', function(data) {
          push.getApplicationIconBadgeNumber(function(n) {
                push.setApplicationIconBadgeNumber(function() {
                  //  console.log('in setApplicationIconBadgeNumber success');
                    }, function() {
                    }, parseInt( n ) + 1);
            }, function() {
                //console.log('in getApplicationIconBadgeNumber error');
            });
    
        push.finish(function() {
          console.log('finish successfully called');
        });
        
        
      });

**Comment by macdonst** [comment]
@amolc that's not how you set a badge. You push payload to needs to include the badge number to be set. The way you have things setup `n` will always be `0` and therefore the badge will get set to `1`.

For example iOS:

```
{
  alert: { 
    title: "My Title",
    body: "My Body"
  },
  badge: 7
}
```

On Android:

```
{
    "data": {
        "title": "Badge Test",
        "message": "Badges, we don't need no stinking badges",
        "badge": 7
    }
}
```

**Comment by madara134** [comment]
@macdonst @amolc  How to do with android Badge increment ?

**Comment by falinsin** [comment]
Please, We need increment badget not set a value. How could We do it?

And how could We decrement Badget form my App. For example,, when users go into the content of a notification We could decrement badge number. Like e-mails Apps.

Sorry my english, thanks in advance.

**Comment by brandecho** [comment]
Hello @macdonst Not sure why this issue was closed when similar question by @falinsin was not answered. I believe the question is relevant and yet to be answered. Can you please provide insight on what the payload for "badge" should be to in order to automatically increase the badge number on IOS and Android.  

{
   "data": {
          "title": "Badge Test",
          "message": "Badges, we don't need no stinking badges",
          **"badge": 7**
     }
} 

Or would you suggest using the plugin?  [cordova-plugin-badge](https://github.com/katzer/cordova-plugin-badge) ?

**Comment by macdonst** [comment]
@brandecho on iOS you should a payload like:

```
{
  alert: { 
    title: "My Title",
    body: "My Body"
  },
  badge: 7
}
```

on [Android](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#badges) you should use: 

```
{
    "registration_ids": ["my device id"],
    "data": {
    	"title": "Badge Test",
    	"message": "Badges, we don't need no stinking badges",
    	"badge": 7
    }
}
```

Please note the badge number is not incremented, it is set to whatever is in the payload. It is up to your app server to maintain the correct badge number.
