### ISSUE TITLE
Question: What logic should i use to make users scheduled notifications?

### ISSUE THREAD

**Issue by leonardopaiva** [phonegap/phonegap-plugin-push#153]
Hello, i`m making a hello world app with push notification, just a simple todo list, where the user can put a reminder on tasks that he create. 

What logic should i use to make this notification? i need to register when the user create the reminder, sending an ajax to my server, then make my server watch 30 by 30 seconds if have a notification to send? if so, send it? I dont want to overload my server doing 30 by 30 seconds requests.

**Comment by fredgalvao** [comment]
For locally created notifications and scheduling, you should try [this plugin instead](https://github.com/katzer/cordova-plugin-local-notifications), otherwise you'd be coding a lot of redundant logic yourself, such as that serve roundtrip you just mentioned :smile:

**Comment by leonardopaiva** [comment]
@fredgalvao this plugin that you mentioned works when the app is closed?

**Comment by fredgalvao** [comment]
As long as you schedule it when the app is open, it should notify the user regardless of the current app status, but that's a guess as I haven't used that plugin that deeply.

**Comment by macdonst** [comment]
@leonardopaiva this seems to be more of a server side question, not client side to do with the plugin. 

However, what I would do would be to send an AJAX request to my server when the task is created with the time. Then I would be using a scheduler on my server, not polling, to wake up and send the push. A couple of things though, if this is time sensitive then push is not guaranteed to be delivered by Apple/Google. I'd lean more toward using the local notification plugin that @fredgalvao mentioned as it saves you working on the logic on the server side.

**Comment by leonardopaiva** [comment]
ok, but this push notification plugin suports scheduled push notification? or will suport one day?

**Comment by fredgalvao** [comment]
`phonegap-plugin-push` doesn't support notification scheduling as of now, that's for sure.

Now, whether it will someday is up to @macdonst. 
```html
<dream> I would personaly love to see this plugin merge in features with
https://github.com/katzer/cordova-plugin-local-notifications.
One push notification plugin to rule them all! </dream>
```

**Comment by leonardopaiva** [comment]
yeah, that would be great @fredgalvao ...

thanks for help @fredgalvao and @macdonst
