### ISSUE TITLE
Unable to receive notification on my android device

### ISSUE THREAD

**Issue by capaccio** [phonegap/phonegap-plugin-push#1531]
I'm using PhoneGap Build (cli 6.4) + phonegap-plugin-push 1.9.2.
 
My app compile and install correctly on my device
it registers to Firebase and get a RegisterID correctly
From Firebase console I can send a notification message to my device using my RegisterID
From Firebase console "message sent correctly"
...but... on my device I don't get any notification in foreground and background mode
 
What can I do?
 
PS. this is my notification javascript:
 
push.on('notification', function(data) {  
     localStorage.setItem('msg', data.message); 
     navigator.notification.alert(
            data.message,         // message
            null,                 // callback
            data.title,           // title
            'Ok'                  // buttonName
        );

**Comment by fredgalvao** [comment]
If you're using FCM, you should use branch `v2.0.x` of this plugin. Support for FCM/Firebase is in a release candidate version as of right now.

**Comment by capaccio** [comment]
Thanks Fred for your quick feedback, googoling I read something about it but I'm not able to install "phonegap-plugin-push 2.x" from Phonegap Build, maybe is not still available yet.

What can I do in the while using PGB?

**Comment by macdonst** [comment]
@capaccio when you send a test push from the Firebase console it puts everything in the `notification` object when we need stuff in `data`. Read about why here:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads
