### ISSUE TITLE
Windows Raw notification when app is closed/background

### ISSUE THREAD

**Issue by bolivir** [phonegap/phonegap-plugin-push#1532]
### Expected Behaviour
When the app is in the background or closed, receive the push notification

### Actual Behaviour
Currently i can receive the push notifications as long as the app is in the foreground. The push will be send as raw and the app will handle it.
Its all working fine until i set the app into the background or close the app, then i am not receiving any push message. The strange behavior is that when i run the app trough visual studio and then close the app, its working fine (Could be because the debugger still stays attached?)

Can someone tell me what i need to do to make the Raw push notification work when the app is closed or in the background. I saw under the Declarations that there is an option for a background task - Push notication but then i need to add app settings (executable, entry point, start page or resource group)

Hope that someone can help me with this problem.

### Reproduce Scenario (including but not limited to)
Send a push notification (Raw)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Windows 10

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Windows Lumnia 650

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
   6.4.0
    cordova platform version android                     # e.g. 4.1.1
   Windows 4.4.3

#### Plugin version
   1.9.0

**Comment by kamilo81** [comment]
Same issue here. Any idea?

**Comment by daserge** [comment]
See if this snippet helps @kamilo81 
https://github.com/phonegap/phonegap-plugin-push/issues/1033#issuecomment-238237978
