### ISSUE TITLE
(Windows) How to receive raw notification in background or when app is closed

### ISSUE THREAD

**Issue by bolivir** [phonegap/phonegap-plugin-push#1533]
Hi, 

Currently i can receive the push notifications as long as the app is in the foreground. The push will be send as raw and the app will handle it.
Its all working fine until i set the app into the background or close the app, then i am not receiving any push message. The strange behavior is that when i run the app trough visual studio and  then close the app, its working fine (Could be because the debugger still stays attached?)

Can someone tell me what i need to do to make the Raw push notification work when the app is closed or in the background. I saw under the Declarations that there is an option for a background task - Push notication but then i need to add app settings (executable, entry point, start page or resource group)

Hope that someone can help me with this problem.

Thanks in advance!

**Comment by macdonst** [comment]
Dup of #1532
