### ISSUE TITLE
Icon and iconColor are not being displayed on Android6.0

### ISSUE THREAD

**Issue by Matias-Carazzo** [phonegap/phonegap-plugin-push#1535]
### Expected Behaviour
Display correct icon and iconcolor

### Actual Behaviour
I see a white circle on Android 6.0. even the color is not being displayed

### Reproduce Scenario (including but not limited to)
This is my initialize json
  $cordovaPushV5.initialize({
                        "android": {
                            senderID: "xxxxxxxx",
                            iconColor: "#FF0000",
                            icon: "ic_notification"
                        }
                });
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Motorola

#### Cordova CLI version and cordova platform version

    cordova --version                6.40
    cordova platform version android        6.0.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.9.2

#### Logs taken while reproducing problem
$ adb logcat | grep PushPlugin
01-19 02:10:17.304  6383  6547 V PushPlugin: execute: action=init
01-19 02:10:17.309  6383  6548 V PushPlugin: execute: data=[{"android":{"senderI                                                                                                                                                 D":"xxxxxx","iconColor":"#FF0000","icon":"ic_notification"}}]
01-19 02:10:17.314  6383  6548 V PushPlugin: execute: jo={"senderID":"xxxxxx","iconColor":"#FF0000","icon":"ic_notification"}
01-19 02:10:17.314  6383  6548 V PushPlugin: execute: senderID=xxxxxxx
01-19 02:10:17.337  6383  6548 V PushPlugin: onRegistered: {"registrationId":"fq                                                                                                                                                 hP..........:............................9C_"}

**Comment by samkelleher** [comment]
@Matias-Carazzo Are you seeing this in the notification tray or the status bar, or both?

**Comment by Matias-Carazzo** [comment]
Hi,
I see that white circle in both places.
Regards.

**Comment by macdonst** [comment]
@Matias-Carazzo I need to see your push payload Also, you are using Ionic and I'm not sure if they pass on the icon and icon color attributes as part of initialize.

**Comment by Matias-Carazzo** [comment]
Thanks. I didnt realize that should be manage from push payload
