### ISSUE TITLE
Opening a specific Page inside app on Push notification Click

### ISSUE THREAD

**Issue by GaneshSawant** [phonegap/phonegap-plugin-push#1539]
Hello Team, 

Sorry its not really an issue but a question on how to achieve the above functionality.
I saw various post around this but all those implementations are for Native approach.

We are building hybrid remote android app(Cordova/Forcedroid) for our salesforce community.
Currently stuck on the issue where we need to open specific app page on Push notification click.
By default it opens the app and takes you to the app's Landing Page.

Is there any specific documentation available for hybrid remote approach ?

I tried to utilize the action button feature within the Push Notification Payload but was not sure as to where exactly add the Callback javascript related to specific button.

Really appreciate any help on this.

Thank you,
Ganesh

**Comment by intellectlogic** [comment]
Hi you can do it by sending specific message title in payload and check in the app for that title if it matches then open specific page in app, if app is in background it will take you to that page upon opening message and it app is not running at all then it will first load initial loading screen and there after take you to the specified file.

This should work 

 push.on('notification', function(data) {
           if(data.additionalData.coldstart){
                  if(data.title=="News!"){
                   window.location.replace("#newspage"); }
       					 }

         });

**Comment by GaneshSawant** [comment]
Hello @intellectlogic ,

Thank you so much for your kind response.
I am bit new bee to the Mobile development and it sound silly if I may ask as where exactly this code should go ?

Should it be in the com.salesforce.util.push.js or on my Server landing page inside onResume method ?

**Comment by macdonst** [comment]
@GaneshSawant I have a tutorial you can read here:

http://macdonst.github.io/push-workshop/module7.html

**Comment by GaneshSawant** [comment]
Hello @macdonst , 

Thanks for the tutorial, as per tutorial the changes will be made in the index.js file but as we are using hybrid remote approach, I am still not sure as where to add the changes. 

Can you please point to the right direction if I am missing something here.

Thanks again.

**Comment by macdonst** [comment]
@GaneshSawant I don't know the structure of your code so I have no idea where you should put the changes. Wherever you setup your push event listener for `notification` you need to add logic like what I or @intellectlogic suggested.

**Comment by GaneshSawant** [comment]
Sorry @macdonst  for asking specific details.
Actually We are using hybrid Remote approach and I cant find Push event Listener inside any code.
We are not having index.js page which is used in your documentation. 

In would be really helpful if you have any specific documents related to hybrid Remote approach.

Also I tried to add the Action buttons to Push message but again where will the callback methods will reside ? as we are not having any index page. its a Server based approach 

Waiting to hear from you :)

**Comment by macdonst** [comment]
@GaneshSawant Dude, I'm sorry but I can't help you as you are asking me to guess to the structure of your code. Somewhere in your code base you must call `PushNotification.init()` and it is around there is where you need to do the other setup.

**Comment by GaneshSawant** [comment]
@macdonst  @intellectlogic thank you so much for All your guidance, 
I was able to fix this issue finally :) as I was using the code that @intellectlogic  sent previously but was missing out PushNotification.init() method.
After adding that, It actually worked for me.

Thank again.

**Comment by manojrejinthala** [comment]
Can you please share your code here @GaneshSawant  i am also same problem with navigation if you provide your code spinet it will help me to achieve my goal.

**Comment by GaneshSawant** [comment]
@manojrejinthala ,

I followed the steps described above, 
So basically we are building hybrid remote app for Salesforce Community so your code will go onto the Landing page of your App(Index file if its a Native or hybrid local).

Used the OnDeviceListener Method to achieved this.

//Use this on Page Load JS
document.addEventListener("deviceready", myDeviceReadyListener, false); 

and Push registration code will go into "myDeviceReadyListener" event, 

                    function myDeviceReadyListener() {
                          var push = PushNotification.init({
                            "android": {
                                "senderID": "<<<<Your GCM Project Id(Same as added in BootConfig)>>>>>>"
                            },
                            "ios": {"alert": "true", "badge": "true", "sound": "true"}, 
                            "windows": {} 
                          });
                          push.on('notification', function(data) {
                            if(data.additionalData.foreground)
                            	window.alert(data.title+'\n'+data.message); //This is optional as I am trying to show 
//Push message as an Alert when the app is in Foreground
                            //window.alert('insidePushDeviceReady');
                                   if(data.additionalData.coldstart){
                                          //redirecturl will be additional key in your payload to hold the relative url for redirection
                            window.open(data.additionalData.redirecturl); 
                                     
                                                 }                         
                          });                 
                    }

----------------------------------------
Hope this Helps :)

Thanks

**Comment by manojrejinthala** [comment]
@GaneshSawant  i used the same code as you mentioned above but still push.on("notification") not triggered.

here is my payload from server.

{
      to: token, // required
      //collapse_key: 'your_collapse_key',
      data: {
          'content-available': '1',
          your_custom_data_key: 'your_custom_data_value'
      },
      notification: {
          title: 'Eventely notifications',
          body: msg
      }
  };

**Comment by AndreGoto** [comment]
Any solution for this?

I'm also trying to open my app through a notification but the push.on notification is not triggering.
