### ISSUE TITLE
Registration Callback not Firing on iOS

### ISSUE THREAD

**Issue by 19113** [phonegap/phonegap-plugin-push#154]
I am attempting to initialize push notifications on iOS, but push.on("registration, function() {... is not firing. I know that the push plugin is installed because when I run it on the simulator, I am logging the error "remote notifications are not supported". When run on device push.on('error', ... is not firing. What steps can I take to help diagnose/debug this issue?

**Comment by 19113** [comment]
I think this was an issue with badging and permissions, is there any way to automatically check for the correct permissions for the app?

**Comment by nofxx** [comment]
The plugin is working just fine. 
Recheck your member cetner Identifiers!

**Comment by leonardopaiva** [comment]
@19113  maybe this help you: 
https://github.com/phonegap/phonegap-plugin-push/issues/124

**Comment by macdonst** [comment]
@19113 I can't reproduce this. Please re-open with more details if this is still a problem.
