### ISSUE TITLE
Unable get message on IOS from firebase console

### ISSUE THREAD

**Issue by intellectlogic** [phonegap/phonegap-plugin-push#1540]
Expected Behaviour - Should send push notification if triggered from firebase console

Actual Behaviour - Not sending message even after successfully getting token from firebase

Platform and Version - Current stable phonegap and plugin version

i have successfully implemented Firebase cloud messaging in my phonegap app on IOS, i am receiving token from Firebase on register event, i print it in alert message and it shows me token. Below is my code

function onDeviceReady(){
           var push = PushNotification.init({
            "android": {
                  "senderID": "xxxxxxxxxxx",
				  sound: true,
				  vibrate: true
				       },
            "ios": {"senderID": "xxxxxxxxxxx","alert": "true", "badge": "true", "sound": "true"},
            "windows": {}
        });

        push.on('registration', function(data)
                {
                globalpushtoken1 = data.registrationId;
                alert("Token IS HERE..  "+globalpushtoken1);
                   
                     checktoken(data.registrationId);

                });

        push.on('notification', function(data) {
            if(data.additionalData.coldstart){
                  if(data.title=="New Offer !"){
                   window.location.replace("#offerspage"); }
       					 }

         });

        push.on('error', function(e) {
          alert("Push Error");
            console.log("push error");
        });

Now the problem is when i try to send some test message from firebase console and select User segment and select my app and send message it shows message status as completed however i dont get any notification on real device, and if i send the message to specific device using token of that device then it shows status as FAILED Unregistered registration token " I am new to firebase and phonegap, please help me resolve this. 

![image](https://cloud.githubusercontent.com/assets/25280347/22182667/0e34b842-e0d1-11e6-82e9-fff5ff64d817.png)

**Comment by jcesarmobile** [comment]
The latest stable version of the plugin doesn't support FCM, you have to use v2.0.x branch.
https://github.com/phonegap/phonegap-plugin-push/tree/v2.0.x

You also have to put the google-services.plist file on the root of the project

And it doesn't work with Phonegap Build, just with Phonegap CLI (or Cordova CLI)

**Comment by intellectlogic** [comment]
I have installed version 2.0.0 manually from this branch and have also placed GoogleService-Info.plist in root of my project (NOT IN WWW) code is same havnt changed it from previous code, i still get my token from FCM on app load as i have put it in alter message, but from firebase console it fails to send message to my device, please help me out have tried all possible solutions.

**Comment by jcesarmobile** [comment]
Did you upload your push certificate to firebase console?

**Comment by intellectlogic** [comment]
ya i did upload and no error there, as I mentioned i am getting token from FCM if my certificate or registration had problem it wouldnt have returned me with token i believe you can correct me if its incorrect

**Comment by jcesarmobile** [comment]
The certificate is used to send the push message from FCM to APNs, you can get a token even with no certificate uploaded

**Comment by intellectlogic** [comment]
ya i have created APNs certificates (.p12 files) for development and distribution i have checked it many times but same issue, can you give me any link related to this issue. 
Your help is appreciated big time

thanks

**Comment by intellectlogic** [comment]
Or if you can give steps to perform this ?

**Comment by jcesarmobile** [comment]
Try using [Pusher](https://github.com/noodlewerk/NWPusher) to send the push from your computer to make sure the certificate is ok.
You have to send it to the APNs token, not to the FCM one

**Comment by intellectlogic** [comment]
Tried it but will need to write native code for IOS

**Comment by jcesarmobile** [comment]
what? it's an app, you download it and use it, no coding required

**Comment by intellectlogic** [comment]
ya downloaded that app but after going through its documentation i saw it needs some native code to be placed in an app.. sorry to bother you but can you help me sort this out

**Comment by intellectlogic** [comment]
I tried with the software, it says Notification Error: APN invalid token size

**Comment by jcesarmobile** [comment]
You have to download the binary https://github.com/noodlewerk/NWPusher/releases/latest

You have to use the APNs token, not the FCM token, the APNs token is shorter, it should be displayed on the logs

**Comment by intellectlogic** [comment]
ok you mean to say in XCODE LOGs i can get to see my APNs token on app start is it?

**Comment by jcesarmobile** [comment]
yes, it should be "Push Plugin register success: <your-token-here>", I think Pusher will remove the < - and > chars from the token when you paste it on the app, if not, you have to do it.

**Comment by intellectlogic** [comment]
Wow amazing that worked ! i got test message from Pusher with Push Plugin register success token., i used development sandbox.. it means my certificates are correctly prepared ...now where is the problem

**Comment by jcesarmobile** [comment]
does your bundle identifier match with the one you used on firebase console?

**Comment by intellectlogic** [comment]
yes it does match its exactly same

**Comment by intellectlogic** [comment]
Now i am trying to update my googleserviceinfo.plist file will check and let you know if it works

**Comment by intellectlogic** [comment]
no success still same issue from FCM

**Comment by intellectlogic** [comment]
What do you think could be the issue, i have almost gave up now cant think of any solution

**Comment by intellectlogic** [comment]
can you help ???

**Comment by Avishaidev** [comment]
Same error here.
Change to fcm plugin but want to work with phonegap-push-plugin.
Any solution?

**Comment by SudoPlz** [comment]
Same!

**Comment by jcesarmobile** [comment]
Can you try with latest master branch? 
You need latest Cordova CLI and latest cordova-ios to use the new resource-file element in the config.xml to copy the GoogleService-Info.plist

**Comment by Alijaaan** [comment]
Same error here .
Is there any solution?!

**Comment by Alijaaan** [comment]
Successfully Recieved in iOS:
I've sent my messages by node instead of firebase.
Use this [item](https://github.com/node-apn/node-apn)
hope it would be helpfull.

But unfortunately I didn't find any luck with firebase for iOS yet.
