### ISSUE TITLE
Ability to cancel notifications?

### ISSUE THREAD

**Issue by gjongenelen** [phonegap/phonegap-plugin-push#1541]
Is it possible to cancel a specific notification? 

I know this is possible on android by using **NotificationManager nMgr.cancel(0);**.

**Comment by macdonst** [comment]
@gjongenelen you can use https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushclearallnotificationssuccesshandler-errorhandler---ios--android-only but I don't have a way to clear a single notification on iOS so I haven't add this functionality to the plugin.
