### ISSUE TITLE
PushNotification is not defined.

### ISSUE THREAD

**Issue by jreijt** [phonegap/phonegap-plugin-push#1544]
Hello, 

I've installed the plugin to my app and built it on an Android device in debug mode. 
Although I've called it after _onDeviceReady_ the console shows an error when calling the init function:

> Uncaught ReferenceError: PushNotification is not defined 

When I try running in browser (using run not serve) I don't get the error and the init function actually returns a registrationId. Is there something on Android I might be setting wrong?

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
