### ISSUE TITLE
This code is not working for bar code scanning any  ideas .How will we do this.

### ISSUE THREAD

**Issue by Teenashrivastava** [phonegap/phonegap-plugin-push#1546]
/**
 * Created by TShrivastava on 1/22/2017.
 */
Ext.define('BarcodeExampel.view.main.Scanner', {
    extend: 'Ext.Container',
    xtype:'Scanner',

    /*
    Uncomment to give this component an xtype
    xtype: 'scanner',
    */

    requires: [
        'Ext.Button',
        'Ext.Img',
        'Ext.layout.VBox'
    ],
    config: {
        layout: {
            type:"vbox",
            pack:"center",
            align:"center"
        },
        items: [
            {
                xtype: "image",
                src: "http://placehold.it/200x200",
                width: 200,
                height: 200
            },
            {
                xtype: "button",
                text: "Photo",
                handler: function() {
                    cordova.plugins.barcodeScanner.scan(
                        function (result) {
                            alert("We got a barcode\n" +
                                "Result: " + result.text + "\n" +
                                "Format: " + result.format + "\n" +
                                "Cancelled: " + result.cancelled);
                        },
                        function (error) {
                            alert("Scanning failed: " + error);
                        },
                        {
                            preferFrontCamera : true, // iOS and Android
                            showFlipCameraButton : true, // iOS and Android
                            showTorchButton : true, // iOS and Android
                            torchOn: true, // Android, launch with the torch switched on (if available)
                            prompt : "Place a barcode inside the scan area", // Android
                            resultDisplayDuration: 500, // Android, display scanned text for X ms. 0 suppresses it entirely, default 1500
                            formats : "QR_CODE,PDF_417", // default: all but PDF_417 and RSS_EXPANDED
                            orientation : "landscape", // Android only (portrait|landscape), default unset so it rotates with the device
                            disableAnimations : true // iOS
                        }
                    );

                }
            }
        ]
    }
});

**Comment by Teenashrivastava** [comment]
I got the error on localhost,When we tap the button and scan the product .
Uncaught ReferenceError: cordova is not defined
    at constructor.handler [as _handler] (Scanner.js?_dc=1485243742253:37)
    at Object.callback (ext-modern-all-debug.js?_dc=1485243742253:5676)
    at constructor.doTap (ext-modern-all-debug.js?_dc=1485243742253:82881)
    at ext-modern-all-debug.js?_dc=1485243742253:13127
    at constructor.fire (ext-modern-all-debug.js?_dc=1485243742253:12957)
    at constructor.doFireEvent (ext-modern-all-debug.js?_dc=1485243742253:13640)
    at constructor.doFireEvent (ext-modern-all-debug.js?_dc=1485243742253:28158)
    at constructor.prototype.doFireEvent (ext-modern-all-debug.js?_dc=1485243742253:34461)
    at constructor.fireEventArgs (ext-modern-all-debug.js?_dc=1485243742253:13546)
    at constructor.fireEventArgs (ext-modern-all-debug.js?_dc=1485243742253:4728)

**Comment by jcesarmobile** [comment]
I think you are talking about this other plugin https://github.com/phonegap/phonegap-plugin-barcodescanner

**Comment by Teenashrivastava** [comment]
Yes ,I am talking about that but not working this plugin in android device.

**Comment by jcesarmobile** [comment]
So, create the issue there, it's a different plugin

**Comment by Teenashrivastava** [comment]
Plz check this i have created: https://gist.github.com/Teenashrivastava/d5cfb636b501e6e8619e650258b568a7
