### ISSUE TITLE
Unable to open a specific page when click on push notification in ionic?

### ISSUE THREAD

**Issue by manojrejinthala** [phonegap/phonegap-plugin-push#1548]
Expected Behaviour
click on push notification need to open corresponding page based on notification information
Actual Behaviour
by default my app open with dashboard page but when user click on notification need to write a code snippet to navigate to the user profile page.

Steps to Reproduce
download example project, created cert, upload p12 to firebase, downloaded .plist and provisioning profile, enabled in capabilities push notification mode, i.e. all neccessary things for push notification.
Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.1.1
Cordova CLI version and cordova platform version
cordova --version: 6.4.0
cordova platform version ios: 4.3.1

Plugin version
cordova plugin version | grep phonegap-plugin-push: e.g. 1.8.4

Sample Code that illustrates the problem
$cordovaPushV5.initialize(options).then(function() {
    // start listening for new notifications
    $cordovaPushV5.onNotification();
    // start listening for errors
    $cordovaPushV5.onError();
    
    // register to get registrationId
    $cordovaPushV5.register().then(function(registrationId) {
		$rootScope.deviceToken=registrationId;
      alert(registrationId);
    })
  });
  
  // triggered every time notification received
  $rootScope.$on('$cordovaPushV5:notificationReceived', function(event, data){
	  alert("data");
	  alert(JSON.stringify(data));
    // data.message,
    // data.title,
    // data.count,
    // data.sound,
    // data.image,
    // data.additionalData
  });

  // triggered every time error occurs
  $rootScope.$on('$cordovaPushV5:errorOcurred', function(event, e){
	  alert("error");
    alert(e.message);// e.message
  });

**Comment by macdonst** [comment]
@manojrejinthala read the tutorial:

http://macdonst.github.io/push-workshop/module7.html

**Comment by manojrejinthala** [comment]
hi @macdonst  i am using ionic  in that i added following code below

	var push = PushNotification.init({
    android: {
        senderID: "61426985247"
    },
    browser: {
        pushServiceURL: 'http://push.api.phonegap.com/v1/push'
    },
    ios: {
        alert: "true",
        badge: true,
        sound: 'false'
    },
    windows: {}
});

PushNotification.hasPermission(function(data) {
	
});

push.on('registration', function(data) {
  
   $rootScope.deviceToken=data.registrationId;
});
push.on('notification', function(data) {
	$state.go("tabs.createevent",{"eventId":"createNewEvent"});
    alert(JSON.stringify(data));
});
push.on('error', function(e) {
    alert(e.message);
});

in device ready event it gives the device token value but when i receive push notifications click on that push notification not navigate to the specified page in above code
