### ISSUE TITLE
actions  buttons on push notification not fire android

### ISSUE THREAD

**Issue by dsemerida** [phonegap/phonegap-plugin-push#1549]
Im trying to set this payload json to send push `{ "icon": "emailGuests", "title": "Aceptar", "callback": "window.actions_left", "foreground": false}`

but i dont know where i cant setting the window.actions_left on my javascript context

my app setting is `   var push = PushNotification.init({ "android": {
                 "senderID": "xxx",
                  "icon": "phonegap",
                  "iconColor": "blue"
               },
                  "ios": { "alert": "true", "badge": "true", "sound": "true" }, "windows": {}
              });''

              push.on('registration', function (data) {
                alert(data.registrationId);
              });

              push.on('notification', function (data) {
                  
                  // data.title,
                  // data.count,
                  // data.sound,
                  // data.image,
                  // data.additionalData
              });

              push.on('error', function (e) {
                  console.log(e.message);
              });`

**Comment by dsemerida** [comment]
I HAVE BEEN RESOLVED sorry!

**Comment by marianoarga** [comment]
@dsemerida how do you fixed this?
