### ISSUE TITLE
Message and summaryText are truncated

### ISSUE THREAD

**Issue by Remskei** [phonegap/phonegap-plugin-push#1550]
### Expected Behaviour

When I use "style" : "picture" in notification and I expand it, the picture is revealed and the entire text too.

### Actual Behaviour

When I use "style" : "picture" in notification and I expand it, the picture is revealed but not the entire text.
But when I use default style without picture, I can expand too see all the text.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Oneplus

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.4.0
    cordova platform version android           6.0.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.9.2

#### Sample Push Data Payload

`$data = array(
                                               'ledColor' => [0, 255, 0, 0],
						'message' => $message,
						'title' => $title,
						'icon' => 'icon',
						'style' => 'picture',
						'picture' => $photo,
	        			        'summaryText' => $message
);`

**Comment by Remskei** [comment]
![screenshot_20170125-125421](https://cloud.githubusercontent.com/assets/15141534/22376776/a31fc410-e4af-11e6-9c63-bc987b33b396.png)

**Comment by Remskei** [comment]
@macdonst 
I still have the problem. Is it just only me?

**Comment by danielfnz** [comment]
Mee too have this problem.

**Comment by macdonst** [comment]
@Remskei sorry, you'd have to create a custom view to have multi-line summary text in a big picture message and that is out of scope for this plugin.
