### ISSUE TITLE
Data messages not delivered

### ISSUE THREAD

**Issue by rbrondi** [phonegap/phonegap-plugin-push#1551]
Hello everyone. First of all thanks for your great job.

### Expected Behaviour
I'm developing a Ionic application using your plugin to get notification through FCM. I've tried to send both notification messages and data messages. The first works fine. The application is notified when the user tap on the notification and if I put a payload in the data field of the message I receive everything.
I would expect the same happening with a data message

### Actual Behaviour
Data messages are not received by the application. Firebase assert that the message has been correctly sent and if I check on the play store developer console I can see that the messages reached the device (acknowledged state).

It is important to have this working for us since data messages can have up to 4KB of payload while notification messages can have no more than 2KB

#### Steps to Reproduce 
Send a data message to a client
```
    {       
        "to":"<device id>",
        "priority": "high",
        "content-available": "true",
        "data":{
            "test": "Hello World"
        }
    }
```
The [notification callback](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushonnotification-callback) is never called.

#### Platform and Version
I've tested the application on a Nexus 5x device running Android 7.1.1

#### Cordova CLI version and cordova platform version
cordova --version **6.4.0**
cordova platform version android **6.0.0**

#### Plugin version
Plugin version **2.0.0-rc2**

**Comment by macdonst** [comment]
@rbrondi your payload doesn't look right for this plugin. See my docs on the subject and let me know if that fixes it:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#use-of-content-available-true

**Comment by rbrondi** [comment]
Thanks for your reply. I didn't see that section.
