### ISSUE TITLE
library not found for -lPods-Appname

### ISSUE THREAD

**Issue by markeh** [phonegap/phonegap-plugin-push#1552]
I'm getting this error when trying to build the project in xcode, it appears that i library is missing but I dont know how to  fix this issue - screenshot 
http://i.imgur.com/ohz1cmb.png

### Expected Behaviour
    Project builds successfully

### Actual Behaviour
    Project fails to build

### Reproduce Scenario (including but not limited to) 
    cordova plugin add phonegap-plugin-push
    ionic build ios
    open in xcode

#### Steps to Reproduce 
    Osx Xcode 8.1 build

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.5.0
    cordova platform version android                     4.3.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.9.2

#### Logs taken while reproducing problem
ld: library not found for -lPods-Appname
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by macdonst** [comment]
@markeh did you open the project or the workspace? You should open the workspace which includes the project for your app and the cocoapods project.

**Comment by markeh** [comment]
@macdonst exactly what the problem was, sorry for the hassle. thanks

**Comment by macdonst** [comment]
@markeh no problem, happy it's sorted.

**Comment by shi11** [comment]
fwiw, this just happened to me aswell. I feel like it should be in the installation doc, no? Chances are most cordova devs are newbies with cocoapods.

**Comment by surindersammy** [comment]
I am getting same issue. i tried with workspace trick but didn't work for me.
Phonegap version  6.5.0
phonegap platform version ios 4.3.1
