### ISSUE TITLE
$cordovaPushV5:notificationReceived event is not being fired when app is in background

### ISSUE THREAD

**Issue by Matias-Carazzo** [phonegap/phonegap-plugin-push#1553]
### Expected Behaviour
Im sending different push notifications to my ionic mobile app using FCM apis from my custom backend.
I expect that notificationReceived event is being fired in all the cases.

### Actual Behaviour
Push notifications are received fine.
App is started fine. But the notification event is not being triggered if the app is not running.
If user is using the app when the notification is received the event is fired.

This part of the code is just executed if the app is running and is being used when the notification arrives
$rootScope.$on('$cordovaPushV5:notificationReceived', function(event, data){
        console.log(event);
        console.log(data);
});

i could not find a way to know when the app is started from a notification in order to redirect to a specific page.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0 and Android 6.0 tested in both

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung and Motorola

#### Cordova CLI version and cordova platform version
cordova --version                6.40
cordova platform version android        6.0.0

#### Plugin version

cordova plugin version | grep phonegap-plugin-push   1.9.2

#### Sample Push Data Payload
{
  "to":"da0TfVkzrV8:........................UT1",
  "notification": {
    "title": "",
    "body": "This is my body",
    "color": "black",
    "icon": "ic_notification",
    "content-available": 1
  },
  "data": {
    "Pagina": "TargetPage",
    "PaginaParams": { "PageParameter": 1 }
  }
}
#### Logs taken while reproducing problem
No logs are registered when event is not triggered.

Logs when event is triggered:
$ adb logcat | grep PushPlugin
V/PushPlugin( 4929): execute: action=init
V/PushPlugin( 4929): execute: data=[{"android":{"senderID":"........","icon":"ic_notification","topics":["Novedades"]},"ios":{"sound":true,"alert":true,"badge":true},"windows":{}}]
V/PushPlugin( 4929): execute: jo={"senderID":".........","icon":"ic_notification","topics":["Novedades"]}
V/PushPlugin( 4929): execute: senderID=705639757688
V/PushPlugin( 4929): onRegistered: {"registrationId":"da0TfVkzrV8:APA91bFg-n_oZlgzl6SSH......................1"}
D/PushPlugin( 4929): Subscribing to topic: Novedades
D/PushPlugin( 4929): no iconColor option
D/PushPlugin_GCMIntentService( 4929): onMessage - from: 705639757688
D/PushPlugin_GCMIntentService( 4929): normalize extras
D/PushPlugin_GCMIntentService( 4929): key = Pagina
D/PushPlugin_GCMIntentService( 4929): replace key Pagina with Pagina
D/PushPlugin_GCMIntentService( 4929): key = google.sent_time
D/PushPlugin_GCMIntentService( 4929): replace key google.sent_time with google.sent_time
D/PushPlugin_GCMIntentService( 4929): key = google.message_id
D/PushPlugin_GCMIntentService( 4929): replace key google.message_id with google.message_id
D/PushPlugin_GCMIntentService( 4929): key = notification
D/PushPlugin_GCMIntentService( 4929): notifkey = content-available
D/PushPlugin_GCMIntentService( 4929): replace key content-available with content-available
D/PushPlugin_GCMIntentService( 4929): notifkey = body
D/PushPlugin_GCMIntentService( 4929): replace key body with message
D/PushPlugin_GCMIntentService( 4929): no locale found for key = message, error Value Un of type java.lang.String cannot be converted to JSONObject
D/PushPlugin_GCMIntentService( 4929): notifkey = icon
D/PushPlugin_GCMIntentService( 4929): replace key icon with icon
D/PushPlugin_GCMIntentService( 4929): notifkey = color
D/PushPlugin_GCMIntentService( 4929): replace key color with color
D/PushPlugin_GCMIntentService( 4929): notifkey = title
D/PushPlugin_GCMIntentService( 4929): replace key title with title
D/PushPlugin_GCMIntentService( 4929): no locale found for key = title, error End of input at character 0 of
D/PushPlugin_GCMIntentService( 4929): key = PaginaParams
D/PushPlugin_GCMIntentService( 4929): replace key PaginaParams with PaginaParams
D/PushPlugin_GCMIntentService( 4929): key = collapse_key
D/PushPlugin_GCMIntentService( 4929): replace key collapse_key with collapse_key
D/PushPlugin_GCMIntentService( 4929): foreground
D/PushPlugin( 4929): convert extras to json
D/PushPlugin( 4929): key = Pagina
D/PushPlugin( 4929): key = content-available
D/PushPlugin( 4929): key = google.sent_time
D/PushPlugin( 4929): key = icon
D/PushPlugin( 4929): key = color
D/PushPlugin( 4929): key = title
D/PushPlugin( 4929): key = google.message_id
D/PushPlugin( 4929): key = PaginaParams
D/PushPlugin( 4929): key = message
D/PushPlugin( 4929): key = coldstart
D/PushPlugin( 4929): key = collapse_key
D/PushPlugin( 4929): key = foreground
V/PushPlugin( 4929): extrasToJSON: {"message":"This is my body","additionalData":{"icon":"ic_notification","collapse_key":"xxxxxxx","color":"black","content-available":"1","coldstart":false,"PaginaParams":{"PageParam":1},"foreground":true,"google.message_id":"0:14853576...........a1442","TargetPage":"tab.xxxxx"},"title":""}
V/PushPlugin( 4929): execute: action=finish

**Comment by Matias-Carazzo** [comment]
Should I use version 2.0 of the plugin?
How I can install it?

Thanks

**Comment by macdonst** [comment]
@Matias-Carazzo try with this payload and let me know:

```
{
"to":"da0TfVkzrV8:........................UT1",
"data": {
"title": "",
"body": "This is my body",
"color": "black",
"icon": "ic_notification",
"content-available": 1,
"Pagina": "TargetPage",
"PaginaParams": { "PageParameter": 1 }
}
}
```

**Comment by Matias-Carazzo** [comment]
It worked perfectly.
Thanks
