### ISSUE TITLE
push.on('notification') not triggered - Ionic

### ISSUE THREAD

**Issue by manojrejinthala** [phonegap/phonegap-plugin-push#1557]
I'm using Android only.

Expected Behavior

When I received new notification, then click on push notification  push.on('notification') should be fired.

Actual Behavior

When I received new notification, then click on notification it just opens the home page of the app.

Reproduce Scenario (including but not limited to)

Once the app open, I called this code first:

 var push = PushNotification.init({
       "android": {
           "senderID": "XXXXXXXXXXX",
           "sound": "true",
           "vibrate": "true"
       },
       "ios": {
           "alert": "true",
           "badge": "true",
           "sound": "true"
        },
        "windows": {}
})

push.on('notification', function (data) {
     alert('You Got New Notification');
 })
It should alert 'You Got New Notification' but it didn't. I tried to push notification again while the app is already launch/open/run, then magically the app able to alert 'You Got New Notification'.

Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android Version and device model:

Android 5.0.2 (Xiomi Redmi Note 3)
Android 4.4.2 (Lenovo K910L)
Android 4.1.2 (Samsung GT-I9070)

**Comment by jmacboy** [comment]
Same issue here, only using cordova, not ionic, but it works exactly as shown above

**Comment by macdonst** [comment]
@manojrejinthala @jmacboy I need to see the push payload you send to the device.

**Comment by jmacboy** [comment]
These are the fields I send
` $fields = array
                (
                'registration_ids' => $registrationIds, //this is a comma separated array of keys
                'notification' => array(
                    "title" => 'the title',
                    "body" => "Test alert summary",
                    "content-available" => "1", //tried with this, but it didn't changed anything
                    "force-start" => "1"  //same here
                ),
                'data' => array(
                    "contenido" => $mensaje,
                    "content-available" => "1", //and here
                    "force-start" => "1" //and here
                )
            );

            $headers = array
                (
                'Content-Type:application/json',
                'Authorization:key=' . API_ACCESS_KEY
            );`
And I use this to make a CURL request

**Comment by macdonst** [comment]
@jmacboy right, try this and I bet it works and please let me know:

```
$fields = array
                (
                "registration_ids" => $registrationIds, //this is a comma separated array of keys
                "data" => array(
                    "title" => 'the title',
                    "body" => "Test alert summary",
                    "contenido" => $mensaje,  //this is a custom variable where I store some html content
                    // "content-available" => "1", // won't need this
                    // "force-start" => "1"  // won't need this
                )
            );

            $headers = array
                (
                "Content-Type:application/json",
                "Authorization:key=" . API_ACCESS_KEY
            );
```

**Comment by jmacboy** [comment]
It worked flawlessly!, thank you so much @macdonst!

**Comment by macdonst** [comment]
@jmacboy okay great. I've talked about this requirement many times before but I think I need to make it more obvious in the docs.

**Comment by macdonst** [comment]
@jmacboy please read this over and let me know if it makes sense:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

**Comment by manojrejinthala** [comment]
this is my payload

**Comment by macdonst** [comment]
@manojrejinthala read https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

**Comment by andymurakami** [comment]
@macdonst on the payload, if I use "data" and "notification" does not work. But if use only data, this work !
How I know whats token is IOS or Android ? What the difference ?

**Comment by jayeshanandani** [comment]
@andymurakami : you can know what device it is via platform api. Why do you need to know ios/android based on token?

**Comment by andymurakami** [comment]
@jayeshanandani I´m using php, on my databank is no one field to specify the platform. But is not the bigger problem, when I sendo to IOS, the IOS App 'on notification" trigger not fired.. why ? Do you have any idea ?

**Comment by Bowtch** [comment]
Just to be clear, i read notification vs payload for android behaviour (https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads) but if you don't send a notification object for iOS devices you don't receive any notifications. 
So you have to format the object you send to FCM differently for Android and iOS devices without a notification object for Android and with one for Android ?

**Comment by andymurakami** [comment]
Yes, I already do different for IOS and Android, the message arrives and showed on the IOS device, but the 'on notification' trigger is not fired. I want to use the 'on notification' trigger to read the parameters sent in the notification (client_id, offer_id, etc)

**Comment by macdonst** [comment]
@andymurakami you can use the cordova-plugin-device plugin's `device.platform` to determine if you are running on Android or iOS.

**Comment by andymurakami** [comment]
@macdonst thank you. But how the cordova-plugin-device works ? Remember, my problem is on receive on IOS, the 'on notification' event is not called.  I´m use the IOS payload to send notification. The mesasge arrive on IOS, I can read but, the event 'on notification' is not fired.
