### ISSUE TITLE
Getting error : attempted to initialize an object with an unknown UUID.

### ISSUE THREAD

**Issue by tushar-velingkar** [phonegap/phonegap-plugin-push#1558]
### Expected Behaviour
Plugin should install properly

### Actual Behaviour
Installing "phonegap-plugin-push" for ios

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `7EC8547169A74BD5A8A5460B` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `A681F5B62F934658A6DEC23E` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `E23C540A0DA14793BE17F093` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `1AC97AB1822E4E15997E168E` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `AE2A50F808434C37B9584D53` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `EB49FF87CB794718B96280A7` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `998B570BB91F4A0FB8D4B663` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `8562C2D8B88748C69F022169` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Installed platforms:
  android 6.0.0
  ios 4.3.1

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.5.0
    cordova platform version android                     6.0.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.9.2

#### Logs taken while reproducing problem
Fetching plugin "https://github.com/phonegap/phonegap-plugin-push" via git clone

Repository "https://github.com/phonegap/phonegap-plugin-push" checked out to git ref "master".

Installing "phonegap-plugin-push" for android

ANDROID_HOME=/Users/tusharvelingkar/Library/Android/sdk

JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home

Subproject Path: CordovaLib

Incremental java compilation is an incubating feature.

:clean

:CordovaLib:clean

BUILD SUCCESSFUL

Total time: 1.605 secs

Subproject Path: CordovaLib

Installing "phonegap-plugin-push" for ios

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `7EC8547169A74BD5A8A5460B` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `A681F5B62F934658A6DEC23E` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `E23C540A0DA14793BE17F093` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `1AC97AB1822E4E15997E168E` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `AE2A50F808434C37B9584D53` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `EB49FF87CB794718B96280A7` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `998B570BB91F4A0FB8D4B663` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `8562C2D8B88748C69F022169` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `F07DC83F4D744CFB8600CBAF` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `4C4252986B454BB2AEA5BEAA` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `D544E47F51E34013A8BEBA26` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `6656642C828846CFB54B5435` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `04BA6D2DC48E4F5FAA2DED24` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `10D1F6C3D92944F8A234B8E0` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `C45D56F95DA240C8860DB1BE` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `DA4F045443BB4C2295CE5FB2` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `C398E45C799B4779BDC63608` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `FAF195B091384AC58493678C` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

**Comment by macdonst** [comment]
@tushar-velingkar that's more of an issue with CocoaPods than the plugin. See these issues:

https://github.com/CocoaPods/Xcodeproj/issues/42
https://github.com/CocoaPods/CocoaPods/issues/1822

**Comment by tushar-velingkar** [comment]
I have reinstalled the cocoapods and tried but getting same error.

Here in this link
http://stackoverflow.com/questions/21366549/errorthe-sandbox-is-not-in-sync-with-the-podfile-lock-after-installing-res/22878202#22878202

Theres one step : Remove all libPods*.a in Build Phases > Link Binary With Libraries

Where to find these files in phonegap-plugin-push project?

**Comment by macdonst** [comment]
@tushar-velingkar you'd have to open the Xcode workspace in platforms/ios

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
