### ISSUE TITLE
Screen flickers black when push notification received/force-start=1

### ISSUE THREAD

**Issue by clarklight** [phonegap/phonegap-plugin-push#1559]
### Expected Behaviour
App to start in the background without disturbing the user. 

### Actual Behaviour
If the phone's screen is on, without anything opened and push notification received(force-start set to 1), then the screen goes black for half a second when the app is booting up, then the screen goes back to normal. The same behavior occurs even if other apps are opened, i have tried Chrome app, youtube....and if i receive a push notification with the app in the background, the Chrome app/youtube etc will go blank with black screen, then goes back to normal. 

### Reproduce Scenario (including but not limited to)
Set Version to 1.9x and up and have youtube app opened, then phonegap/cordova app closed and send a notification to device, then should see the screen goes all black for half a second.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1/Android 6.0 

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
LG/Samsung

#### Cordova CLI version and cordova platform version
CLI 6.4.0 

#### Plugin version
Plugin version 1.9.0,Plugin version 1.9.2

**Comment by macdonst** [comment]
@clarklight yup, and there is absolutely nothing I can do about it. What is happening is if your app is not running the incoming push notification starts up the app and immediately sends it to the background. Depending on the speed of the phone, amount of resources available, etc. you may see a quick flicker of the app being opened/closed in short order.

I can't make any improvements on this behaviour until Android gives us some API to start the app without it being brought to the foreground.
