### ISSUE TITLE
Plugin with id 'com.google.gms.google-services' not found.

### ISSUE THREAD

**Issue by elemenofi** [phonegap/phonegap-plugin-push#1561]
### Expected Behaviour

ionic run android to complete

### Actual Behaviour

get error when building

### Reproduce Scenario (including but not limited to)

`cordova platform add android
`
Add google-services.json to platforms/android
`cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable SENDER_ID="XX"
`

#### Cordova CLI version and cordova platform version

    cordova --version  6.5.0
    cordova platform version android 6.1.2

#### Plugin version

    cordova plugin version 2.0.0-rc

#### Logs taken while reproducing problem
```
Error: /platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script platforms/android/phonegap-plugin-push/cordova-push.gradle' line: 12

* What went wrong:
A problem occurred evaluating root project 'android'.
> Plugin with id 'com.google.gms.google-services' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```

**Comment by elemenofi** [comment]
I fixed this by adding the following thing in project level gradles

`dependencies {
        ...
        classpath 'com.google.gms:google-services:3.0.0'
    }`

**Comment by harishmahajan** [comment]
@elemenofi where could i found project level gradles?
