### ISSUE TITLE
Send badge_count via GCM?

### ISSUE THREAD

**Issue by gjongenelen** [phonegap/phonegap-plugin-push#1562]
Is it possible to include a badge_count value in the notification-payload?

Because I'm currently using background-refresh to fetch the number of badge_count. But when the app is killed this is not working and can lead to very confusing situations.

**Comment by macdonst** [comment]
@gjongenelen on Android or iOS?

**Comment by gjongenelen** [comment]
In this case, iOS.

But I would love to see the same feature in Android too.

**Comment by macdonst** [comment]
@gjongenelen if you are using APNS then you just need to include the `badge` in the `aps` of your payload.

```
{ 
  "aps": {
    "badge": 7
  }
}
```

If you are using GCM on iOS then you need to include the `badge` in the `notification` part of your payload.

```
{ 
  "notification": {
    "badge": 7
  }
}
```

If you are using GCM on Android then you need to include the `badge` in the `data` part of your payload.


```
{ 
  "data": {
    "badge": 7
  }
}
```

However on Android it depends on if your phone is supported by ShortcutBadger which is what I used to set badges.
