### ISSUE TITLE
Clicking on Notification doesn't fire actions in iOS 10

### ISSUE THREAD

**Issue by joaodmsoares** [phonegap/phonegap-plugin-push#1564]
### Expected Behaviour
When the user receives a notification and click on it and the application is closed or in background the app should open a page with the information refered to the notification.
If the app is running it should create an alert message and then the user can choose if he wants to see or ignore the notification details

### Actual Behaviour
After installing the app and allowing notifications, when the app is open or in backgroung, it works like the expected behaviour, but after closing the application I still received the notifications but when I click on it, it only opens the app, it doesn't execute any of the actions I create. Even with the app opened or in background the expected behavior stop working.

### Reproduce Scenario (including but not limited to)
Just need to install the app and then close it. The expected behavior stop working after that.

#### Steps to Reproduce 
Just need to install the app and then close it. The expected behavior stop working after that.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.2 and iOS 10.2.1

#### Cordova CLI version and cordova platform version

6.4.0

#### Plugin version

1.9.2

**Comment by fredgalvao** [comment]
Please provide the following information (which is asked for on the issue template):

```
Sample Push Data Payload

Sample Code that illustrates the problem

Logs taken while reproducing problem
```

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by joaodmsoares** [comment]
issue submited with more information
