### ISSUE TITLE
GCM registration failed in iOS but received token.

### ISSUE THREAD

**Issue by dpaksoni** [phonegap/phonegap-plugin-push#1566]
### Expected Behaviour
If the registration has been failed, I should not have received the token

### Actual Behaviour
It shows gcm registration failed but received the token as well.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.2.1
#### Cordova CLI version and cordova platform version
 Cordova version 5.4.1
Cordova platform version ios = 3.9.2
    cordova --version                                   # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version
1.5.3
    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@dpaksoni Yeah, I'd need to see some logs. I have a feeling you are getting the APNS registration ID which is then used to get the GCM registration ID.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
