### ISSUE TITLE
How to import typescript definitions?

### ISSUE THREAD

**Issue by davidanaya** [phonegap/phonegap-plugin-push#1567]
Hi,

I'm sorry but I'm trying to use the type definitions for typescript and I can´t figure out how to do it.

### Expected Behaviour
I installed the typings with npm and the I tried to import it in my ts file using
```import { PushNotification } from 'phonegap-plugin-push';```
and I expected to have type information when using PushNotification methods.

### Actual Behaviour
I get a `[ts] File 'my_src_path/node_modules/@types/phonegap-plugin-push/index.d.ts' is not a module` error

#### Steps to Reproduce 
I installed it with `$npm install --save-dev @types/phonegap-plugin-push`

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Ionic Framework: 2.0.0
Ionic Native: 2.4.0
Ionic App Scripts: 1.0.0
Angular Core: 2.4.5
Angular Compiler CLI: 2.4.5
Node: 6.9.4
OS Platform: macOS Sierra

**Comment by fredgalvao** [comment]
There has been a refactoring recently on a dance of branches on DefinitelyTyped for Typescript 2.0, and I would have to guess that that refactoring didn't aim the exporting schema used on the type definition for phonegap-plugin-push, and thus you're not able to use `import` clauses on it. Would you mind creating that issue on DefinitelyTyped instead? There will at least be more people capable of helping on the topic there than here.
