### ISSUE TITLE
[Question] Could someone explain to me how to implement the action button on Android?

### ISSUE THREAD

**Issue by yesroh** [phonegap/phonegap-plugin-push#1569]
### Expected Behaviour
When click on action button should console.log(data)

### Actual Behaviour
The console.log(data) is fired when the notification comes in background with the value of null

#### Sample Push Data Payload

   ```
 "devices" : ids,
    "title" :   message.sender_name,
    "message" : message.text,
    "style" :   "inbox",
    "summaryText": "%n% novas mensagens",
    "sound" :   true,
    "color" :   '#00A8E8',
    "content-available": "1",
    "force-start": 1,
    "badge" :   10,
    "notId": message.conversation,
    "payload" : {
      "conversationId": message._id,
      "type": "notification"
    },
    "actions": [
         {"title": "Abrir Conversa", "callback": "openConversation", "foreground": true}
     ]
  };
```

#### Sample Code that illustrates the problem
```
 $rootScope.$on('$cordovaPushV5:notificationReceived', (event, data) => {
      console.log(data);
      console.log($window.openConversation);
 });
```
when event is fired the second log is undefined, when I open the click button this message is loged: 
`Error in Success callbackId: PushNotification1421737314 : TypeError: Cannot read property 'apply' of undefined`

on doc says: if there isn't an event will be emitted with the callback name, so I tried:

   ```
 $rootScope.$on('openConversation', (event, data) => {
      console.log(data);
      console.log('oi, agora estou aqui!');
    });
```
but the same problem is logged: `Error in Success callbackId: PushNotification1601750510 : TypeError: Cannot read property 'apply' of undefined`

my question is: How can I access the function? Is she in the right place? I'm using angularjs 1.5

#### My data structure
<img src="https://cldup.com/UQXLLnpDvh.png"/>

since now, thank you for the question!

**Comment by macdonst** [comment]
@yesroh This is more of a question for the Ionic team. I'm not sure if their push service puts the `actions` array in the correct part of the payload.

**Comment by fredgalvao** [comment]
Also, if you said `console.log($window.openConversation);` prints `undefined` when the event is triggered for the notification arrival, that is a sign that the `openConversation` function/object is not available on window at all, which would explain the plugin not finding the action to take, and thus the error. How are you setting up that function exactly?

**Comment by yesroh** [comment]
Setei `$window.openConversation ` no controller da minha diretiva. Mas o que mais intriga é que no meu push-server eu setei o action dessa forma: 

```
message.addData('actions', [
        { "icon": "emailGuests", "title": "EMAIL GUESTS", "callback": "app.emailGuests", "foreground": true}
 ]);

```

e no controller da minha diretiva tenho isso:

```
    $rootScope.$on('emailGuests', (event, data) => {
      console.log('Event button recived');
    });
```

e tenho esse erro: 
`Error in Success callbackId: PushNotification1695385513 : TypeError: Cannot read property 'emailGuests' of undefined`

e na documentação diz que se o push não encontrar nenhuma função com o nome da action ele dispara um evento, mas isso não está acontecendo.

**Comment by fredgalvao** [comment]
Você tem acesso ao stacktrace desse erro? Estou com a impressão de que ele não está acontecendo no código do plugin do push, mas sim no Ionic de alguma forma.

Tem como você testar usando o código do plugin direto? Digo, tente remover o código do angular que escuta por esse evento, pois se você mandou o payload com `"callback": "emailGuests"`, então a function window.emailGuests deveria realmente ser chamada (se ela existir).

De qualquer forma, se tiver a stackstrace do erro vai ajudar bastante.

**Comment by yesroh** [comment]
Por código do angular você quis dizer remover o ngCordova?

**Comment by fredgalvao** [comment]
Não, remover o listener do $rootScope. Basicamente remover essas linhas de código:
```ts
    $rootScope.$on('emailGuests', (event, data) => {
      console.log('Event button recived');
    });
```

**Comment by yesroh** [comment]
Usei o monitor e tive essa mensagem: 

`02-13 10:57:10.806: D/SystemWebChromeClient(21192): file:///android_asset/www/cordova.js: Line 312 : Error in Success callbackId: PushNotification1912986140 : TypeError: Cannot read property 'apply' of undefined`

quando eu envio a mensagem tenho essa resposta:

```
{ multicast_id: 5531345678615276000,
  success: 1,
  failure: 8,
  canonical_ids: 0,
  results: 
   [ { error: 'NotRegistered' },
     { error: 'NotRegistered' },
     { error: 'NotRegistered' },
     { error: 'NotRegistered' },
     { error: 'NotRegistered' },
     { error: 'NotRegistered' },
     { error: 'NotRegistered' },
     { error: 'NotRegistered' },
     { message_id: '0:1486992290072755%7901853a7901853a' } ] }

```
essa é a minha função para enviar os push para o gcm:

```
  function GCM(body, tokens) {

    return new Promise((resolve, reject) => {
      let message = new gcm.Message({
        data: {
          sound: body.sound,
          tag:   body.tag,
          color: body.color,
          title: body.title,
          body:  body.message,
        }
      });

      message.addNotification({
        style: body.style,
        image: body.image,
        summaryText: "%n% novas mensagens"
      });

      message.addData('force-start', 1);
      message.addData('content-available', '1');
      message.addData('actions', [
        { "icon": "emailGuests", "title": "EMAIL GUESTS", "callback": "emailGuests", "foreground": true}
      ]);

      let sender = new gcm.Sender(process.env.SENDER_KEY);
      let regTokens = tokens;

      sender.send(message, { registrationTokens: regTokens }, function (err, response) {
          if(err) {
            reject(err);
            console.log(err);
          }
          resolve(response)
      });
    })

  };
```

mesmo retirando a escuta do evento ele manda esse evento

**Comment by fredgalvao** [comment]
E onde está definida a function `emailGuests` no seu código?

**Comment by yesroh** [comment]
em lugar nenhum, eu defini `$window.emailGuests` no meu controller e ele veio undefined. Daí o comportamento esperado segundo a documentação:

"However if they click on either of the action buttons the app will open (or start) and the specified JavaScript callback will be executed if there is a function defined, `and if there isn't an event will be emitted with the callback name.`"

**Comment by fredgalvao** [comment]
Consultando o código fonte do `push.js` da última versão estável lançada (1.9.2), [disponível aqui](https://github.com/phonegap/phonegap-plugin-push/blob/v1.9.2/www/push.js), dá pra ver que não existe mais a função `executeFunctionByName`, pois ela foi substituida pela função `executeFuctionOrEmitEventByName`, que faz exatamente o que a documentação está dizendo:
**executa a função ou dispara o evento**.

Isso significa que você está numa versão anterior a essa, e por isso essa funcionalidade não está disponível pra você, como era de se esperar.

Logo, pra que você use os eventos das notificações com `action`, vai ter que atualizar seu projeto pra usar a versão mais recente do plugin.

Vou fechar a issue, mas se depois de atualizar o plugin você ainda não conseguir usar essa funcionalidade, fique à vontade pra reabrir a issue ou criar uma nova com mais detalhes.

**Comment by fredgalvao** [comment]
@macdonst Let me know if you want anything from this translated, but I'd say you'll be able to sightsee it through code mentions.
