### ISSUE TITLE
1.3.0 version from npm will cause PGB(build.phonegap.com)'s Android build fail

### ISSUE THREAD

**Issue by bau720123** [phonegap/phonegap-plugin-push#157]
hi @macdonst 
I am using PGB 5.2.0
when I use 1.2.3 version from npm，build all success
but if I upgrade to 1.3.0，it will cause only Android build fail (ios is fine)

the error message is
Error: Project contains at least one plugin that requires a system library. This is not supported with ANT. Please build using gradle. (1.3.0 will show this warning message，1.2.3 won't)

**Comment by macdonst** [comment]
@bau720123 Yes, this is known. If you look at the README - https://github.com/phonegap/phonegap-plugin-push#phonegap-build-support or my blog post (http://simonmacdonald.blogspot.ca/2015/09/phonegap-plugin-push-version-130-has.html) it will explain why. You will need to keep using 1.2.3 until PGB supports Gradle. They are working on it.

**Comment by bau720123** [comment]
thanks @macdonst reply
