### ISSUE TITLE
Is @1.8.4 the latest non-hooks build available?  And, what are we missing out on?  Phonegap Build

### ISSUE THREAD

**Issue by uj** [phonegap/phonegap-plugin-push#1570]
PhoneGap Build works really well for building, but does not support hooks, and I assume they never will because they say hooks are unsupported due to security reasons.  So, those of us using phonegap build are stuck with 1.8.4.  Is there any newer build that 1.8.4 without hooks that is still being maintained?  Also, what important features are we missing out on by still using 1.8.4?  I've read there have been ios 10 improvements in 1.9.x but I'm not sure if they are critical.

**Comment by macdonst** [comment]
@uj 1.9.x stream does not need any hooks for iOS or Android. I strongly suggest using the 1.9.x stream for apps supporting iOS 10.

The 2.0.x stream currently needs hooks be we're working on it.
