### ISSUE TITLE
force-start issue on current master, with android

### ISSUE THREAD

**Issue by uj** [phonegap/phonegap-plugin-push#1571]
If the app is closed, and you send a notification, and if the screen is turned on, then it notifies and then it opens the app to the foreground.  Ok.

However, if the screen is turned OFF, and the app is not running, then you send a notification, it notifies and then starts the app in the foreground (with the screen still turned off), so all future notifications will NOT sound a notification because the app is acting like it s running in the foreground even though the screen is off.  If you turn on the screen, go into the app and then go back to the homescreen, then the app is background and it works again.  The on 'notify' still works, just no system notification shows up.

This is a problem because after the first notification starts the app, you will never get more notifications until you go to the app and then back out because it thinks the app is in the foreground after that first notification starts the app while the screen is turned off.

Android 6.0
phonegap-plugin-push 1.9.2 from npm and also from current github master

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
