### ISSUE TITLE
Telerik AppBuilder: Cannot build iOS app because of the plugin

### ISSUE THREAD

**Issue by mralj** [phonegap/phonegap-plugin-push#1572]
### Expected Behaviour
App should build successfully with this plugin included
### Actual Behaviour
When plugin is added to the app, the build fails
### Reproduce Scenario (including but not limited to)
Trying to build the app using Telerik App Builder with plugin included
#### Steps to Reproduce 
/
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.2 
#### Cordova CLI version and cordova platform version

    cordova --version: 6.4.0   
    cordova platform version iOS: 4.3.1
#### Plugin version
1.9.2

#### Logs taken while reproducing problem
Server exception
Project "PushSpikeProject-new-app.tmp.proj" (default targets):
 Warning: Cannot include the following item(s) in your application: .flowconfig. The build system treats items with a leading dot as hidden files or directories and does not process them. If you want to include these items in your application package, rename them and rebuild your app.
 ios Build Tooling revision 2017.01.26.3r
 Build Tooling Hostname administrators-mac-14.local
 Warning: Failed to install 'com.adobe.phonegap.push.PushPlugin':TypeError: Cannot read property 'length' of undefined at /private/tmp/builds/WAtqtO6r8ISLmeqXFt/app/cordova/lib/Podfile.js:151:17 at Array.map (native) at Podfile.write (/private/tmp/builds/WAtqtO6r8ISLmeqXFt/app/cordova/lib/Podfile.js:147:28) at /private/tmp/builds/WAtqtO6r8ISLmeqXFt/app/cordova/Api.js:289:29 at _fulfilled (/private/tmp/builds/WAtqtO6r8ISLmeqXFt/app/cordova/node_modules/q/q.js:834:54) at self.promiseDispatch.done (/private/tmp/builds/WAtqtO6r8ISLmeqXFt/app/cordova/node_modules/q/q.js:863:30) at Promise.promise.promiseDispatch (/private/tmp/builds/WAtqtO6r8ISLmeqXFt/app/cordova/node_modules/q/q.js:796:13) at /private/tmp/builds/WAtqtO6r8ISLmeqXFt/app/cordova/node_modules/q/q.js:604:44 at runSingle (/private/tmp/builds/WAtqtO6r8ISLmeqXFt/app/cordova/node_modules/q/q.js:137:13) at flush (/private/tmp/builds/WAtqtO6r8ISLmeqXFt/app/cordova/node_modules/q/q.js:125:13)
 Warning: Cannot read property 'length' of undefined
 Warning: /Users/builder/BpcTooling/Cordova3/node_modules/cordova-build-utils/bin/install-plugins-3.js:190 throw Error("exit code: " + code); ^ Error: exit code: 1 at Error (native) at ChildProcess.<anonymous> (/Users/builder/BpcTooling/Cordova3/node_modules/cordova-build-utils/bin/install-plugins-3.js:190:14) at emitTwo (events.js:87:13) at ChildProcess.emit (events.js:172:7) at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
 Error: Build failed during execution
 Error: 'Build failed with error code 1'
 Done building project "PushSpikeProject-new-app.tmp.proj" -- FAILED.

**Comment by macdonst** [comment]
@mralj please open a ticket with Telerik.
