### ISSUE TITLE
I am unable to install plugin for ios, xcode version>8 through terminal. There is no document or hint how to add for ios, for android its asking for sender id but dont now how to install for ios. this is not working cordova plugin add phonegap-plugin-push@1.8.1 try to add 1.9.2 or 2.0.x unable to add plugin

### ISSUE THREAD

**Issue by ajay81** [phonegap/phonegap-plugin-push#1574]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
