### ISSUE TITLE
Would the badge updates on IOS as well even when the app is totally closed out? Like it does on Android

### ISSUE THREAD

**Issue by clarklight** [phonegap/phonegap-plugin-push#1575]
### Expected Behaviour
IOS when app is totally closed out, the badge to update when a push notification is received

### Actual Behaviour
Only if the app is in the background/in the foreground the badge number update

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
IOS 10

A quick question, which the documentation didn't 100% answer, for IOS badge, would the badge updates even when the app is totally closed out? It does on Android, but in the document didn't mention if thats the case for IOS.

**Comment by macdonst** [comment]
@clarklight yes it does. iOS handles it as long set the badge property in the payload.
