### ISSUE TITLE
Impliment in Kendo Mobile

### ISSUE THREAD

**Issue by Nagaraj007** [phonegap/phonegap-plugin-push#1578]
Hi,
    I am using Telerik Icenium , i tried this pushPlugin it was working in my app,but now due to change in GCM to FCM i am trying to use "v2.0.0-rc2" , i am getting the error
 "Uncaught ReferenceError: module is not defined" 
 "Uncaught TypeError: PushNotification.init is not a function" any suggestion would help me

**Comment by macdonst** [comment]
@Nagaraj007 Sorry, you'll need to open an issue with Telerik. I don't have the setup or bandwidth to support it.

**Comment by Nagaraj007** [comment]
@mac thanks! i ll check through it
