### ISSUE TITLE
push.on('registration' doesn't work on ios

### ISSUE THREAD

**Issue by sargissaradyan** [phonegap/phonegap-plugin-push#1580]
Hello
I can't get registration id,
The 'registration' event doesn't triggered on iOS

var push = PushNotification.init({
    android: {
        senderID: "12345679"
    },
    ios: {
        alert: "true",
        badge: "true",
        sound: "true"
    }
});

push.on('registration', function(data) {
    console.log(data.registrationId);
});

push.on('notification', function(data) {
  console.log(data.message);
});

push.on('error', function(e) {
    console.log(e.message);
});

**Comment by shawns582** [comment]
any luck with this? notification on iOS were working for me, but the registration event is not triggering any more

**Comment by sargissaradyan** [comment]
I think something went wrong when registering device first time (because app asks permissions for notifications), but after that it didn't asks permission, so i tried this and it helped 

**Resetting the Push Notifications Permissions Alert on iOS**

Delete your app from the device.
Turn the device off completely and turn it back on.
Go to Settings > General > Date & Time and set the date ahead a day or more.
Turn the device off completely again and turn it back on.
