### ISSUE TITLE
 $cordovaPushV5.register() gets empty deviceToken

### ISSUE THREAD

**Issue by obergerdavid** [phonegap/phonegap-plugin-push#1582]
### Expected Behaviour
The phonegap plugin should receive the deviceToken in the register function.

### Actual Behaviour
The phonegap plugin returns an empty string as deviceToken.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
One Plus 3

#### Cordova CLI version and cordova platform version
Cordova Verison 6.4.0
Cordova Platform Android 5.2.2

#### Plugin version
phonegap-plugin-push 1.8.4 "PushPlugin"

#### Sample Code that illustrates the problem
           $cordovaPushV5.initialize({
                "android": {
                    "clearNotifications": false,
                    "senderID" : "XXXXXXXXXXXX"
                }
            });

            $cordovaPushV5.register().then(function (deviceToken) {
                console.log("medtec_push successfully registered \"", deviceToken, "\"");

                // Below code required to configure $cordovaPushV5 notifications emitter.
                // Don't pass function it's not handler.
                $cordovaPushV5.onNotification();
                $cordovaPushV5.onError();

            }, function (error) {
                console.log("medtec_push failed to register");
                console.log("medtec_push error object : ", error);
            });

            $rootScope.$on('$cordovaPushV5:notificationReceived', function(event, data) {
                console.log("medtec_push notification received");
                console.log("medtec_push data object: ", data);
            });

            $rootScope.$on('$cordovaPushV5:errorOccurred', function(event, error) {
                console.log("medtec_push notification error occured");
                console.log("medtec_push event object: ", event);
                console.log("medtec_push error object: ", error);
            });

            // triggered every time error occurs
            $rootScope.$on('$cordovaPushV5:errorOcurred', function(event, e){
                alert("medtec_push error with push plugin");
                // e.message
            });

#### Logs taken while reproducing problem
medtec_push successfully registered ""

--> the received device token should be in the string at the end

**Comment by obergerdavid** [comment]
Update:
I have updated the plugin to version 1.9.2 and the android platform to 6.0.0.
I still get the same logs.

If i start the app in the browser (ionic serve) i get the following error message:
Uncaught ReferenceError: PushNotification is not defined
    at Object.initialize (ng-cordova.min.js:9)
    at app.js:84
    at Array.<anonymous> (ionic.bundle.js:56230)
    at onPlatformReady (ionic.bundle.js:2496)
    at onWindowLoad (ionic.bundle.js:2477)

In my app.js i have the following module definition:
var ctrl = angular.module('medtec', ['ionic', 'ngRoute', 'ngMaterial', 'ngCordova', 'ngCordova.plugins.push_v5',
        'ngAnimate',
        'ngAria',
        'ngMessages',
        'mdPickers'])

Is there something missing or do i have to install a missing dependency?

BR david

**Comment by macdonst** [comment]
@obergerdavid did you setup your variables correctly?

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md#ionic-cloud-build

**Comment by obergerdavid** [comment]
Yes, i set it the way like it was described, altough I get the same error.

Attached are the two files.
[configs.zip](https://github.com/phonegap/phonegap-plugin-push/files/777976/configs.zip)

**Comment by obergerdavid** [comment]
I found a solution for my problem, I just followed this guide:
https://github.com/yafraorg/yafra/wiki/Blog-Ionic-PushV5
