### ISSUE TITLE
[Question] Access data from all notifications in the inbox stack

### ISSUE THREAD

**Issue by lucasbasquerotto** [phonegap/phonegap-plugin-push#1583]
Hi! I want to know if **it is possible to access data from all notifications when using inbox stacking**. The inbox style is working fine, but **when I click the notification I see the data only from the last push notification** (most recent). Also, I don't see any documentation related to accessing data from other notifications.

In my case, I want, for example, to know if the user received more than 1 `new message` notification, and access the data to know if they are from the same talk or more than 1 (because it could be several messages in the same talk, so I need to access the custom data that I've passed, not just know how many messages are in the stack). If it is the same talk, the user would be redirected to that specific talk page, otherwise he/she would be redirected to a talk list (more general) page.

### Expected Behaviour

    Be able to access data from all notifications in the inbox stack. 

### Actual Behaviour

    I'm able to access only data from the last notification.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

    Android 6.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

    Motorola (Moto G2)

#### Cordova CLI version and cordova platform version

    Cordova CLI version: 6.4.0
    Cordova Platform Version Android: 6.1.0

#### Plugin version

    1.9.2

**Thanks for the plugin BTW!**

**Comment by macdonst** [comment]
See issue #314
