### ISSUE TITLE
Error with cocoapods: Command failed with exit code 1

### ISSUE THREAD

**Issue by davidellolio** [phonegap/phonegap-plugin-push#1584]
### Reproduce Scenario (including but not limited to)
I have this error:  pod: Command failed with exit code 1 when I add the platform ios
#### Steps to Reproduce 

1. I have created the project with ionic framework: ionic start --v2 myApp tabs
2. Add the phonegap-plugin-push with ionic plugin add command
3. Add platform ios with cordova-ios 4.3.1
4. Display Error with pod: Command failed with exit code 1
5. I have tried to run "pod repo update" without success.

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.4.0
    cordova platform version ios                     4.3.1
    cocoapods                                                  1.2.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push  1.9.2

I have tried to uninstall the cocoapods but I'm not solve the problem.

Would you have a solution?

Thank you,
David

**Comment by davidellolio** [comment]
I have solved with this commands:

1--> sudo gem uninstall nanaimo
and then
2-->sudo gem install nanaimo

Thank you.

**Comment by ssarathieee** [comment]
Failed to install 'phonegap-plugin-push': Error: pod: Command failed with exit code 1
