### ISSUE TITLE
linking app after installing plugin with version 1.9.2 fails due to unnecessary library

### ISSUE THREAD

**Issue by shankari** [phonegap/phonegap-plugin-push#1585]
### Expected Behaviour
After adding the plugin, the project should build

### Actual Behaviour
Linking fails with error

```
ld: library not found for -lPods-emission
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Reproduce Scenario (including but not limited to)
Add version 1.9.2 (latest) of the plugin and build using xcode
building using the CLI works, building using xcode fails.

#### Steps to Reproduce 
- Check out https://github.com/e-mission/e-mission-phone at CL 93a7c56159479ca6299b81f1a14019f8a7736f4c
(https://github.com/e-mission/e-mission-phone/commit/93a7c56159479ca6299b81f1a14019f8a7736f4c)

Add the push plugin
```
$ ionic plugin add phonegap-plugin-push --variable SENDER_ID=1234567 --save
```

Open the project (`platforms/ios/emission.xcodeproj`) in xcode

Build. Linking fails with error

```
Ld /Users/shankari/Library/Developer/Xcode/DerivedData/emission-ecfgjdufnxtacqffllnskgkyqtez/Build/Products/Debug-iphoneos/emission.app/emission normal arm64
    cd /Users/shankari/e-mission/e-mission-phone/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk -L/Users/shankari/Library/Developer/Xcode/DerivedData/emission-ecfgjdufnxtacqffllnskgkyqtez/Build/Products/Debug-iphoneos -F/Users/shankari/Library/Developer/Xcode/DerivedData/emission-ecfgjdufnxtacqffllnskgkyqtez/Build/Products/Debug-iphoneos -Femission/Plugins/edu.berkeley.eecs.emission.cordova.comm -Femission/Plugins/edu.berkeley.eecs.emission.cordova.datacollection -filelist /Users/shankari/Library/Developer/Xcode/DerivedData/emission-ecfgjdufnxtacqffllnskgkyqtez/Build/Intermediates/emission.build/Debug-iphoneos/emission.build/Objects-normal/arm64/emission.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/shankari/Library/Developer/Xcode/DerivedData/emission-ecfgjdufnxtacqffllnskgkyqtez/Build/Intermediates/emission.build/Debug-iphoneos/emission.build/Objects-normal/arm64/emission_lto.o -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -ObjC -ObjC /Users/shankari/Library/Developer/Xcode/DerivedData/emission-ecfgjdufnxtacqffllnskgkyqtez/Build/Products/Debug-iphoneos/libCordova.a -framework MessageUI -weak_framework Social -framework SystemConfiguration -framework Security -framework Parse -framework Bolts -framework CoreLocation -framework Accounts -framework AudioToolbox -framework CoreMotion -lsqlite3.0 -lPods-emission -Xlinker -dependency_info -Xlinker /Users/shankari/Library/Developer/Xcode/DerivedData/emission-ecfgjdufnxtacqffllnskgkyqtez/Build/Intermediates/emission.build/Debug-iphoneos/emission.build/Objects-normal/arm64/emission_dependency_info.dat -o /Users/shankari/Library/Developer/Xcode/DerivedData/emission-ecfgjdufnxtacqffllnskgkyqtez/Build/Products/Debug-iphoneos/emission.app/emission

ld: library not found for -lPods-emission
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ios, xcode ONLY
compiling via command line works

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
N/A

#### Cordova CLI version and cordova platform version

    cordova --version                                    
    6.5.0

    cordova platform version android                     
    4.3.1
#### Plugin version

    cordova plugin version | grep phonegap-plugin-push 
    1.9.2

**Comment by shankari** [comment]
I know the immediate cause of this issue and a workaround. Adding the pod-based install adds `libPods-emission.a` to the list of linked libraries

<img width="1407" alt="screen shot 2017-02-13 at 4 58 30 pm" src="https://cloud.githubusercontent.com/assets/2423263/22910274/b5274e88-f20d-11e6-884b-53e05e8dac2b.png">

Although the library is present in the build directory

```
C02KT61MFFT0:e-mission-phone shankari$ find platforms/ios -name \*libPod\*
platforms/ios/build/device/libPods-emission.a
```

xcode is not able to link against it, probably because it is actually a symlink to a file in `UninstalledProducts`!!

```
C02KT61MFFT0:e-mission-phone shankari$ ls -al platforms/ios/build/device/libPods-emission.a
lrwxr-xr-x  1 shankari  649427843  214 Feb 13 16:32 platforms/ios/build/device/libPods-emission.a -> /Users/shankari/Library/Developer/Xcode/DerivedData/emission-gebnnulgimvcvxhfcyujnszmzhzg/Build/Intermediates/ArchiveIntermediates/emission/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libPods-emission.a
```

Further, the library appears to be unused. If I remove it manually, the build completes correctly.

<img width="1409" alt="screen shot 2017-02-13 at 5 04 04 pm" src="https://cloud.githubusercontent.com/assets/2423263/22910390/856d1604-f20e-11e6-8514-3700d670d15d.png">

**Comment by shankari** [comment]
Although the workaround is fairly simple, it took several hours to discover. At the very least, the workaround should be documented. It would be better if the setup for the CLI build could be reflected in the project so that it would build right out of the box.

**Comment by shankari** [comment]
Thanks for making this great plugin. Hope this helps somebody!

**Comment by shankari** [comment]
@macdonst is there a reason that this was closed with no comment?

**Comment by macdonst** [comment]
@shankari seems like you were opening the project and now the workspace.

**Comment by shankari** [comment]
I opened `platforms/ios/emission.xcodeproj` and not `platforms/ios/emission.xcworkspace`.
This is consistent with the cordova instructions
https://cordova.apache.org/docs/en/latest/guide/platforms/ios/index.html

> Open the project file from Xcode and make sure the .xcodeproj file is selected in the left panel.

**Comment by jcesarmobile** [comment]
The guide is not updated, just created an issue to update it
https://issues.apache.org/jira/browse/CB-12564
