### ISSUE TITLE
v2.0.0-rc2: .on('notification') event not fired when background notification in Android

### ISSUE THREAD

**Issue by markos92i** [phonegap/phonegap-plugin-push#1587]
### Expected Behaviour
Notification received in background should fire event after tapping on it
### Actual Behaviour
After tapping the notification, app opens but event is not fired
### Reproduce Scenario (including but not limited to)
The app is made with Ionic 2.0.1 and the code launched within platform.ready)= 
#### Steps to Reproduce 
Send notification with the payload shown below.
Tap it from the notification bar and when the app is launched nothing happens, but it should.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy S7
#### Cordova CLI version and cordova platform version

    cordova --version 6.5.0
    cordova platform version android 6.1.2

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push 2.0.0-rc2

#### Sample Push Data Payload
```
{
    "to": "/topics/_all_",
    "notification": {
    	"title": "title notification",
        "body": "body notification"
    },
    "data": {
    	"title": "title data",
        "message": "message data",
      	"app": "MOVAPP_GEN",
        "content-available":  "1"
    }
}
```
#### Sample Code that illustrates the problem
```
let push = PushNotification.init({
	android: { sound: 'true', vibrate: 'true', topics: ['all', '_all_'] },
	ios: { alert: 'true', badge: true, sound: 'true', fcmSandbox: true, topics: ['all', '_all_'] }
});

push.on('registration', (data) => { this.userData.setTokenFire(data.registrationId); this.userData.setPushToken(data.registrationId); });

push.on('notification', (data) => {
	console.log("NOTIFICATION: " + JSON.stringify(data));
	if (data.additionalData.app == constants.APP_ID) { events.publish('app:notification', data); }
	else { utils.sendNotification(data); }
});

push.on('error', (error) => { console.log(error.message); });
```

**Comment by markos92i** [comment]
I've just found that if you just send this payload:
```
{
    "to": "/topics/_all_",
    "data": {
    	"title": "title data",
        "message": "message data",
      	"app": "MOVAPP_GEN",
        "content-available":  "1"
    }
}
```

The notification event is fired twice in android, and the notification doesn't reach iOS at all.

**Comment by macdonst** [comment]
@markos92i yes, that is the way that it works:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

If you send:

```
{
    "to": "/topics/_all_",
    "notification": {
    	"title": "title notification",
        "body": "body notification"
    },
    "data": {
    	"title": "title data",
        "message": "message data",
      	"app": "MOVAPP_GEN",
        "content-available":  "1"
    }
}
```

on Android it will not work. As you discovered, sending:

```
{
    "to": "/topics/_all_",
    "data": {
    	"title": "title data",
        "message": "message data",
      	"app": "MOVAPP_GEN",
        "content-available":  "1"
    }
}
```

will work. The reason you are getting two notifications is because of the "content-available":  "1" setting. This is a signal for your the push plugin to [fire the event in the background](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications).

Using FCM on iOS you will need to send:

```
{
    "to": "/topics/_all_",
    "notification": {
    	"title": "title data",
        "message": "message data",
      	"app": "MOVAPP_GEN"
    }
}
```

It sucks the payload is different on Android and iOS but that is the way Google made it.

**Comment by markos92i** [comment]
It turns out that this plugin "https://github.com/arnesson/cordova-plugin-firebase" DOES fire the event even when you send the "notification" attribute in android. And debugging in the phonegap plugin, it also receives the payload, so its possible to fire the event too.

This has to be a bug, because it makes us to differentiate 2 payloads depending on the platform.

Another problem I'm facing is that if you don't send the "notification" attribute in android, and you receive several notifications, they are all override with the last one, instead of stacking them in the notification bar.

**Comment by ef33zy** [comment]
@markos92i you can use inbox stacking as detailed here: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#inbox-stacking

**Comment by markos92i** [comment]
That works for now, thank you. But still if you take a look at that plugin it manages to work even with the notification attribute.
