### ISSUE TITLE
App crashing after showing the splash screen

### ISSUE THREAD

**Issue by D4rthR4tz3** [phonegap/phonegap-plugin-push#1588]
### Actual Behaviour
The application crashes immediately after the splash screen.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
SM-T813

#### Cordova CLI version and cordova platform version
cordova version: 6.5.0
android platform version: 6.1.2

#### SDK information
Android SDK Platform-Tools: 25.0.3
Android SDK Tools: 25.2.5
Android Support Repository: 43.0.0
Google Repository: 44

#### Plugin version
1.9.2

#### Logs taken while reproducing problem

> FATAL EXCEPTION: pool-2-thread-3
>                                                                   Process: de.awenko.mobile, PID: 26812
>                                                                   java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzw; or its super classes (declaration of 'com.google.android.gms.common.util.zzw' appears in /data/app/de.awenko.mobile-1/base.apk)
>                                                                       at com.google.android.gms.iid.zzd.zzkq(Unknown Source)
>                                                                       at com.google.android.gms.iid.zzd.<init>(Unknown Source)
>                                                                       at com.google.android.gms.iid.zzd.<init>(Unknown Source)
>                                                                       at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
>                                                                       at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
>                                                                       at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:74)
>                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by D4rthR4tz3** [comment]
OK, I've found a solution. I had to set the dependency to the compile com.google.android.gms:play-services-gcm from version 9.8+ to 10.2+.

**Comment by lmuller14** [comment]
I am just experiencing the same issue with plugin version 1.8.4. 
Thanks @D4rthR4tz3, your solution works!

**Comment by sam2x** [comment]
ommg spent 5hours on this... your solution worked for me too, thx!

** I had exactly the same SDK Cordova, and android platform env!!** 

@D4rthR4tz3 how did you figured out the crash log ? i have nothing so detailled in logs, I used the following command : 

    $ adb logcat ActivityManager:I MyApp:D *:S

@macdonst Any ideas why we had to do this change ? Would be nice to be aware of this problem if it happens in the future.

**Comment by macdonst** [comment]
@sam2x it happens because sometimes Google screws up and releases a Google Play Services to the world that does not have the getNoBackupFilesDir method.

**Comment by rickiz** [comment]
@D4rthR4tz3  May I ask how to set the dependency for com.google.android.gms:play-services-gcm?

**Comment by marchuksergii** [comment]
@rickiz **Gradle Scripts** -> **build.gradle(Module: android)**. Find there a dependencies list and set
_compile "com.google.android.gms:play-services-gcm:10.2.0"_

In my case:
![screen shot 2017-03-10 at 16 36 26](https://cloud.githubusercontent.com/assets/12181991/23799051/c685cd8e-05af-11e7-8a12-3e36a61a310f.png)

**Comment by saqueib** [comment]
@D4rthR4tz3 @rickiz I am having the same issue, I have changed the version to 10.2+ `platforms/android/build.gradle` and when I ran `ionic run android` its reverted back to `compile "com.google.android.gms:play-services-gcm:9.8+"` and app still crashes on lauch.

```
Plugins installed 

cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-geolocation 2.4.2 "Geolocation"
cordova-plugin-mauron85-background-geolocation 2.2.5 "CDVBackgroundGeolocation"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.6 "SocialSharing"
cordova-sqlite-storage 2.0.2 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.8.4 "PushPlugin"
```

Please help what I am doing wrong.

```
My system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: 1.8.5
ios-sim version: 5.0.4
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by rickiz** [comment]
try instead of
com.google.android.gms:play-services-gcm:10.2.0

to

com.google.android.gms:play-services-gcm:+

**Comment by saqueib** [comment]
@rickiz didnt worked, its replaced back to `compile "com.google.android.gms:play-services-gcm:9.8+"`.

Am I editing this in right place, I edited this `platforms/android/build.gradle` file.

```
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile(project(path: "CordovaLib", configuration: "debug"))
    releaseCompile(project(path: "CordovaLib", configuration: "release"))
    compile "com.google.android.gms:play-services-location:+"
    compile "com.android.support:support-v4:+"
    compile "com.android.support:support-v4:24.1.1+"
    compile "com.android.support:support-v13:23+"
    compile "com.google.android.gms:play-services-gcm:9.8+"
    compile "me.leolin:ShortcutBadger:1.1.4@aar"
    // SUB-PROJECT DEPENDENCIES END
}
```

what should I do, i am stuck here

**Comment by rickiz** [comment]
i don't think is change under platforms folder

**Comment by saqueib** [comment]
so where should I change this version number, in which file?

**Comment by rickiz** [comment]
I'm not sure. @D4rthR4tz3  should know where to change....

**Comment by marchuksergii** [comment]
@saqueib Are u using Android Studio?

**Comment by saqueib** [comment]
yes, just to see the logcats

**Comment by marchuksergii** [comment]
I updated the version not inside platforms folder but inside Gradle Scripts in Android Studio, as you can see on screenshot. The Android Studio probably reads its own main gradle script and rewrite it inside platform folder. Thats why your version is always old I think. Try to update it inside Studio. Hope it will help.
![screen shot 2017-03-24 at 12 16 31](https://cloud.githubusercontent.com/assets/12181991/24290089/5fcd8e78-108c-11e7-8a3b-ea41af594f74.png)

**Comment by saqueib** [comment]
@marchuksergii changing version to `10.2+` & running from android studio does it 😄

**Comment by marchuksergii** [comment]
@saqueib Glad to hear it 👍

**Comment by rockpriest** [comment]
Hi, I had the same issue. When I ran the app it just crashed. Changing the Version to 10.2+ also solved it. For everyone, who does not used android studio but cordova console:

This setting can be changed in the file project.properties within the folder platforms/android/

Took me over two hours to figure that out. So hopefully this comment helps others. Respectively, I think this problem should be mentioned on the main page, as quite a lot of people seem to run into this issue. 

Cheers

**Comment by stephenandrews** [comment]
Cheers guys!

I was only running into this issue while using **cordova-plugin-background-geolocation**; after removing the plugin the app ran fine, but crashed as soon as this plugin was installed so this could possibly be the culprit. Only found this fix by searching **"background-geolocation"** in the issues for this plugin. Hope this helps
