### ISSUE TITLE
Intel XDK / gradle scripts / gcm

### ISSUE THREAD

**Issue by ramonescamilla** [phonegap/phonegap-plugin-push#1589]
Hello Everybody,

I'm working on an app using Intel XDK framework.  Intel XDK doesn't let you build with gradle scripts but they have a work around on their software site. Heres the link https://software.intel.com/en-us/xdk/faqs/cordova#push-plugin-fix .

I added the Sender Id to the installation and Ive built the apk and installled it on my phone.  I still can't seem to get the notifications from firebase to show up on my phone.  The analytics on from firebase shows 0 notifications sent.  Anybody have any suggestions as to what I could be doing wrong?  

Thanks,

Ramon

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
