### ISSUE TITLE
Error while building for Android 

### ISSUE THREAD

**Issue by pks2k9** [phonegap/phonegap-plugin-push#159]
While trying to run on android device, plugin making build to fail with error

C:\android-sdk\tools\ant\build.xml:573: Failed to resolve library path: C:\android-sdk\com.android.support:support-v13:23+

Any suggestions on how to resolve this issue.

**Comment by ezequielrozen** [comment]
I just did an update and have the same problem

**Comment by alexislg2** [comment]
You need to install Android support

**Comment by macdonst** [comment]
Run the Android SDK manager and install the latest Android Support Library.

**Comment by ezequielrozen** [comment]
@macdonst Yes, I did that, but it still not working. Now I'm stalling Android Support Repository. I have installed the Android Support Library v 23.0.1

**Comment by ezequielrozen** [comment]
Now I have this error while building for Android, after install the latest version of Android Support Repository and Android Support Library:

Execution failed for task ':dexArmv7Debug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/home/ezequielrozen/android-sdk-linux/build-tools/22.0.1/dx --dex --no-optimize --output /home/ezequielrozen/Projects/premiados/platforms/android/build/intermediates/dex/armv7/debug --input-list=/home/ezequielrozen/Projects/premiados/platforms/android/build/intermediates/tmp/dex/armv7/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)

**Comment by ezequielrozen** [comment]
I found this: http://stackoverflow.com/questions/26342444/multiple-dex-files-define-landroid-support-annotation-animres

**Comment by fredgalvao** [comment]
Just to make sure, you should run the `android` sdk manager and let it update pretty much everything it suggests you to do at startup. If you've done that, the android-support thing shouldn't appear anymore (as I think you did :wink:).

Now, it seems like you're either using an older version of this plugin (<= 1.2.3) or you have another plugin that tries to add jars into the classpath which are already there somehow.

**Comment by ezequielrozen** [comment]
I just uninstall facebook connect plugin and the problem disappeared, so maybe there are an incompatibility (again) with this plugin.

**Comment by macdonst** [comment]
@ezequielrozen If you install the facebook connect plugin and then remove the library jar it adds before compiling you should be okay. Folks should go open an issue on the Facebook Connect plugin so that it moves to gradle as well.

**Comment by ezequielrozen** [comment]
@macdonst Which library FacebooK Connect plugin adds after install them?

Thanks for all!

**Comment by fredgalvao** [comment]
@ezequielrozen, if you're using [Wizcorp's plugin](https://github.com/Wizcorp/phonegap-facebook-plugin), I **strongly** recommend you switch over to [jeduan's fork](https://github.com/jeduan/cordova-plugin-facebook4). Too much has been fixed on it to ignore (that includes the dependency management you're dealing with). I have both phonegap-plugin-push 1.3.0 and facebook4 1.4.0 from jeduan installed, everything working properly.

**Comment by macdonst** [comment]
@ezequielrozen if you switch over to jeduan's fork and it fixes the issue for us please let us know so we can close this.

**Comment by app2naklabs** [comment]
I have also having same issue; I am using online tool to build Android apk https://build.phonegap.com/apps/ in this its giving me error and not making android apk. Here's the complete log:

Buildfile: /project/build.xml
-set-mode-check:
-set-debug-files:
-check-env:
 [checkenv] Android SDK Tools Revision 24.3.4
-setup:
     [echo] Project Name: appname
  [gettype] Project Type: Application
-set-debug-mode:
-debug-obfuscation-check:
-pre-build:
-build-setup:
[getbuildtools] Using latest Build Tools: 20.0.0
     [echo] Resolving Build Target for Appname...
[gettarget] Project Target:   Android 5.0.1
[gettarget] API level:        21
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: /project/bin
    [mkdir] Created dir: /project/bin/res
    [mkdir] Created dir: /project/bin/rsObj
    [mkdir] Created dir: /project/bin/rsLibs
    [mkdir] Created dir: /project/gen
    [mkdir] Created dir: /project/bin/classes
    [mkdir] Created dir: /project/bin/dexedLibs
     [echo] ----------
     [echo] Resolving Dependencies for Appname...
BUILD FAILED
/android-sdk/tools/ant/build.xml:573: ../../../../../../android-sdk/com.android.support:support-v13:23+ resolve to a path with no project.properties file for project /project
Total time: 0 seconds*


/project/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error: Project contains at least one plugin that requires a system library. This is not supported with ANT. Please build using gradle.
    at /project/cordova/lib/build.js:169:27
    at _fulfilled (/project/cordova/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/project/cordova/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/project/cordova/node_modules/q/q.js:760:13)
    at /project/cordova/node_modules/q/q.js:574:44
    at flush (/project/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:442:13)

**Comment by macdonst** [comment]
@app2naklabs as mentioned in this projects README and my blog post on 1.3.0 if you are using PhoneGap Build you will need to specify version 1.2.3 to build with this plugin. PGB does not yet support Gradle but they are working on it.

**Comment by app2naklabs** [comment]
Ok thanks for information. I have recently observed that if app is not open (or in background) and if i send push notification then it's not showing me any notification. And If my app is running or in background then it showing me notifications. So can you tell me how to fix this issue. Notifications should be showing even if app is not running or it's offline.

**Comment by macdonst** [comment]
@app2naklabs this is a totally different issue. Please open a new issue if required.

You should be seeing a notification in the shader if the app is in the background or closes. Your notification call back will not be invoked if it is closed/background only when the app is in the foreground. There are issues open to act on background notifications.

**Comment by macdonst** [comment]
https://github.com/phonegap/phonegap-plugin-push#phonegap-build-support
https://github.com/phonegap/phonegap-plugin-push#compiling
