### ISSUE TITLE
Foreground push notification detect click

### ISSUE THREAD

**Issue by aniketgundecha2002** [phonegap/phonegap-plugin-push#1590]
I'am getting push notification in foreground , background , when the app is closed.

Scenario 1 [ when app is completely closed ] :: 
When the app is closed i get the push notification , i open the app while clicking the push notification [coldstart] i redirect the user to the specific page

Scenario 2 [ when app is completely closed ] ::
I receive the push notification but click the app icon to open the app i land on dashboard -- perfect

Scenario 3 [ when app is in background or open ] :: 
I receive push notification when the app is open.. I get immediately redirect.. What i want here if i receive the push notification and the app is open and if the user clicks on the push notification then only he should be redirected

Hope i explained this..

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
