### ISSUE TITLE
App crashes with the latest updates of Android SDK with plugin v-1.9.2

### ISSUE THREAD

**Issue by razam217** [phonegap/phonegap-plugin-push#1591]
### Actual Behaviour
I just updated my sdk packages, cordova and cordova-platforms, and updated phonegap-plugin-push to 1.9.2 and now I can't run my app. It is crashing. Also I can see a exception in my logs:

> 02-17 18:23:49.443 28689-28926/com.abode.abode E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-4
                                                                 Process: com.abode.abode, PID: 28689
                                                                 java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzw; or its super classes (declaration of 'com.google.android.gms.common.util.zzw' appears in /data/app/com.abode.abode-1/base.apk)
                                                                     at com.google.android.gms.iid.zzd.zzkq(Unknown Source)
                                                                     at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                                     at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                                     at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
                                                                     at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
                                                                     at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:74)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     at java.lang.Thread.run(Thread.java:818)
02-17 18:23:49.513 28689-28689/com.abode.abode D/CordovaActivity: Paused the activity.

#### Steps to Reproduce 
Just install latest updates of sdk and try to run on android.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0.1
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy Note III
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.5.0
    cordova platform version android                     # e.g. 6.1.2

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.9.2

**Comment by macdonst** [comment]
@razam217 what version of Google Play Services and Support Library are you building with? I have the latest Android SDK, etc and my app does not crash.

**Comment by razam217** [comment]
Google Play Services: 39
Android Support Repository: 43

**Comment by razam217** [comment]
Node Version 6.9.5

**Comment by pitAlex** [comment]
I confirm its happening to me too after updating to the sdk. It crashes saying:

java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzw; or its super classes (declaration of 'com.google.android.gms.common.util.zzw'

I there anyway to downgrade the sdk until this gets fixed? I've searched high and low but could not find a proper way to do it. Just downgrading the tools will not fix it. It like you need the entire previous sdk.

**Comment by macdonst** [comment]
@razam217 and @pitAlex can you please install the latest from `master` as the quick change I did should fix your issue but since I couldn't reproduce it I can't know for sure and I need you help. Thanks.

**Comment by uj** [comment]
That change seems to cause Phone Gap Build to fail with the following error:

> You have not accepted the license agreements of the following SDK components:
  [SDK Patch Applier v4, Android Support Repository, Google Repository].

Of course, I have no way to accept the license agreement on behalf of PGB.

**Comment by razam217** [comment]
My issue is fixed, before I was using sdk dowloaded manually. When I used the SDK downloaded by Android SDK, the issue fixed, I guess my SDK had something un-necessary packages installed or something like that.

**Comment by razam217** [comment]
I would suggest uninstall Android studio and install it once again, and then try to build your project again. It will download the latest SDK with the minimal required dependencies.

**Comment by pitAlex** [comment]
Its not this that causing the problem, I've tracked it down. Its the google analytics plugin. Somehow that plugin causes conflicts between the google play services version

**Comment by macdonst** [comment]
@pitAlex can you link to the analytics plugin so I can take a look?

-- 
Simon Mac Donald
http://simonmacdonald.com

**Comment by pitAlex** [comment]
I use this one : https://github.com/danwilson/google-analytics-plugin

**Comment by 5an1ty** [comment]
Ah this explains why my app wouldn't run anymore? Can you publish a new version on NPM please?

**Comment by kaynz** [comment]
I can confirm the issue using 1.9.3 and latest android sdk stuff.

This `<framework src="com.google.android.gms:play-services-gcm:+"/>`fixes the problem.

**Comment by 5an1ty** [comment]
@kaynz but how can I use this fix without a new version of phonegap-plugin-push? If I change the plugin.xml I won't see the changes reflected with cordova build or cordova run?

**Comment by fredgalvao** [comment]
If you want to use/test what's been commited without having to wait for an official release, you can always install directly from github:
```sh
cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable SENDER_ID="XXXXXXX"
```

**Comment by macdonst** [comment]
I bumped the plugin to 1.9.4 for folks running into this issue.

**Comment by Jori1** [comment]
Is there any solution to Phonegap Build users?
As far as i know PhoneGap Build does not support 1.9.X-version of this plugin, so i cannot update to 1.9.4 version?

I'm currently using PhoneGap Build CLI-6.3.0 for android and phonegap-plugin-push version 1.8.4.

**Comment by uj** [comment]
Phonegap Build works fine with 1.9.3, I use it myself.  Just don't use 1.9.4 yet until PhoneGap Build has Google Play Services 10+ support.

**Comment by Jori1** [comment]
Actually i just tested my application with push plugin version 1.9.4, cli-6.5.0 and push notifications are working, so what is this Google Play Services 10+ support?

**Comment by uj** [comment]
If it builds successfully in Phonegap Build with 1.9.4, then that means Adobe has added Play Services 10 support to their system.  It wasn't available there a few days ago, so if you say that it built without errors in PGB, then they probably recently updated it.
