### ISSUE TITLE
Missing context when bringing app to foreground from tile notification on UWP

### ISSUE THREAD

**Issue by tfrenken** [phonegap/phonegap-plugin-push#1592]
### Expected Behaviour
According to this post [https://github.com/phonegap/phonegap-plugin-push/issues/1033#issuecomment-238237978](url), the recommended implementation for reacting to clicking on a tile notification on UWP is to add a document listener for "activated". The app should come to foreground, the method should be called, and the push data can be processed.

### Actual Behaviour
The app comes to foreground, the method is called, but we cannot make a reference to the existing app resp. "this" has no reference to the existing app when using Ionic 2 / Angular.

#### Steps to Reproduce 
1. Register phone for push
2. Send app to background
3. Send Push via WNS
4. Click on tile notification

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Windows Phone 10

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Nokia Lumia 640

#### Cordova CLI version and cordova platform version

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.3
Xcode version: Not installed

#### Plugin version
phonegap-plugin-push 1.9.2 "PushPlugin"

#### Sample Push Data Payload
```
<?xml version="1.0" encoding="utf-8"?>
                        <toast '.TemplateToast::SoundDuration($sound).' launch="{&quot;type&quot;:&quot;job&quot;,&quot;title&quot;:&quot;Title&quot;,&quot;message&quot;:&quot;Body&quot;}">
                            <visual>
                                <binding template="ToastText02">
                                    <text id="1">Title</text>
                                    <text id="2">Body</text>                             
                                </binding>
                            </visual>'.$sound.'
                        </toast>
```
#### Sample Code that illustrates the problem
```
document.addEventListener('activated', this.onActivated, false);

  onActivated(context)
  {
    var launchArgs = context ? context.args : null;

    if (launchArgs)
    {
      console.debug("Lauch via tile WNS message ", context);

      //let data : { additionalData : { foreground : boolean}, title : string, message : string};
      let data : any = {};
      data.additionalData = {};
      data.additionalData.foreground=true;
      
      let info = JSON.parse(launchArgs);
      data.title = info.title;
      data.message = info.message;
      data.additionalData.type = info.type;

      this.tempPush = data;
      
      //this line crashes, makes first reference to "old" app context
      this.handlePush(this.tempPush);

   }
  
  }
```
#### Logs taken while reproducing problem
```
Lauch via tile WNS message  [object Event]
main.js (47122,13)
   "Lauch via tile WNS message "
   {
      [functions]: ,
      __proto__: { },
      activatedOperation: { },
      args: "{"type":"job","title":"Title","message":"Body"}",
      arguments: "{"type":"job","title":"Title","message":"Body"}",
      AT_TARGET: 2,
      bubbles: false,
      BUBBLING_PHASE: 3,
      cancelable: false,
      cancelBubble: false,
      CAPTURING_PHASE: 1,
      currentlyShownApplicationViewId: 2147479545,
      currentTarget: null,
      defaultPrevented: false,
      detail: [ ],
      eventPhase: 0,
      isTrusted: false,
      kind: 0,
      prelaunchActivated: false,
      previousExecutionState: 1,
      raw: { },
      returnValue: true,
      splashScreen: { },
      srcElement: null,
      target: null,
      tileId: "xxx",
      timeStamp: 1487577395114,
      type: "activated",
      user: { }
   }

SCRIPT438: Exception is about to be caught by JavaScript library code at line 47132, column 13 in ms-appx-web://xxx/www/build/main.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'handlePush'
main.js (47132,13)

```

**Comment by tfrenken** [comment]
Workaround for now: Store data in Pouchdb and read from notify the "original" app via Obserable about the new data. However, just a workaround.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
