### ISSUE TITLE
auto-increment badges number when receiving push notifications 

### ISSUE THREAD

**Issue by madara134** [phonegap/phonegap-plugin-push#1593]
how to set auto increment badges number when receiving push notifications
this is my code :
![image](https://cloud.githubusercontent.com/assets/11155951/23121614/aac41ba2-f793-11e6-8da2-cb638a509733.png)

I run app frist times it's fine, but next times this.badge it not set, push.setApplicationIconBadgeNumber() only get badge from data ! Thanks

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by madara134** [comment]
i'm sorry my bad @macdonst
