### ISSUE TITLE
On notification handler called after app started, but notification was dismissed when app was force-closed

### ISSUE THREAD

**Issue by laagland** [phonegap/phonegap-plugin-push#1596]
### Expected Behaviour
When the app is force-closed/killed the on notification handler should not be called when a push message is received. No further processing of push data.

### Actual Behaviour
A notification is send to a device where the app is currently not running (was force-closed/killed). On receivement of the notification, the notification is swiped/dismissed. When the app is subsequently started the on-push-notification handler is called.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
HTC Nexus 9

#### Cordova CLI version and cordova platform version

cordova --version = 6.5.0
cordova platform version android = 6.1.0

#### Plugin version

1.9.3

#### Logs taken while reproducing problem
Log-cat shows the message 'PushPlugin: sendExtras: caching extras to send at a later time' when the app is not running. Then on initialize in PushPlugin.java the cached data is send to the app. 

It is a welcome feature that the plugin caches the payload data when the app is not running, but how to completely dismiss the notification when you want to? Or am I missing something here.

Thanks

**Comment by fredgalvao** [comment]
We should code it so that the `dismiss` action is captured and handled accordingly. Such handling should also be configurable, I guess.

**Comment by laagland** [comment]
@fredgalvao or at least a no-cache flag in the payload, so the payload can be discarded when the app is not running

**Comment by fredgalvao** [comment]
That can also be done, and I agree that would solve your case, but I think that if possible, we should implement the full feature and allow people to actually handle the `dismiss` event, which is a nice addition to the API.

**Comment by laagland** [comment]
I was talking this over with the team, and after a more thorough look at the code it seems to me that there are more issues, aside from a dismiss-eventhandler.

We have a use-case (a voip app) where we would like to show the notification only when the app is not running. If the app IS running (background or foreground), the handler should be called called immediately (silent notification). This is not possible at the moment.

According to the payload flowchart when a notification arrives with content-available = 1, but the app is running in the background, the on-notification handler is called. In the code in GCMIntentService.java on line 312 there is no check if the app is in background or is not running at all, so the PushPlugin.sendExtras method will either deliver straight away or cache the data for processing on plugin initialisation. There is currently no way to distinguish between the 2 states.

I can understand you would want to cache the push data when doing a cold-start, so the PusphPlugin.sendEvent can send the data to the app on initialize. But in the current situation this also happens when you omit the cold-start flag.

**Comment by laagland** [comment]
@fredgalvao @macdonst Any further thoughts on this?

Maybe extending the check in GCMIntentService to also check if the app is in the background, but this will prevent the payload from being delivered when the app is not running (only the coldstart flag will force this). This will make the plugin behave like the flowchart suggests. 
Another option would be to set a flag in the payload that will (or will not) discard the payload when the app is not running.

**Comment by fredgalvao** [comment]
I agree that those cases should be discernible, yes, but I'm afraid that's an issue of itself.

**Comment by laagland** [comment]
Do you mean you want me to open a new issue for that?

**Comment by fredgalvao** [comment]
Yes, that's my opinion. By the way, are you interested in contributing with a PR for any of these two enhancements?

**Comment by laagland** [comment]
Yes, of course! I'll open a new issue.

**Comment by laagland** [comment]
Continuing with the dismiss handler. What are the requirements? 

I have a handler implemented that sends a payload to the app with a _dismissed: true_ flag. As of now, it will not start the app if it is not running.

**Comment by laagland** [comment]
@fredgalvao I've committed some changes to my fork. Any input would be appreciated, thanks!

**Comment by fredgalvao** [comment]
Feel free to open a pull request from that branch/fork of yours, it's a lot easier to manage and review code that way. I've sightread it, and looks fine to me, but I'm not that fluent in the android intent terminology so I'd wait until @macdonst has a word with your code.

**Comment by macdonst** [comment]
Will be part of 1.10.0
