### ISSUE TITLE
Phonegap Push Plugin is not working

### ISSUE THREAD

**Issue by Rana-Mukherjee** [phonegap/phonegap-plugin-push#1598]
### Expected Behaviour
Push notification plugin should send notification to the registered device.
### Actual Behaviour
Installed the **"phonegap-plugin-push"** plugin with the registered sender id. Installation and compilation of the project was done successfully, but it was throwing error while running the application. 
It launch the app in the Ripple browser (the app is getting developed in Cordova in Visual Studio 2015), and error message was **"PushNotification.init is undefined."**
During debugging, in the devtools of the browser (the small window launched in the explorer by pressing F12 to view the traffic and other activity of the webpage), this plugin's name was missing under the plugin folder. Although other plugins are available with necessary .js file.
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.1.1
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.9.0

#### Sample Code that illustrates the problem
var pushRegistration = null;
    function registerForPushNotifications() {        
        pushRegistration = PushNotification.init({
            android: { senderID: 'XXXXXXX' },
            ios: { alert: 'true', badge: 'true', sound: 'true' },
            wns: {}
        });

Error message - PushNotification.init is not defined.

**Comment by macdonst** [comment]
@Rana-Mukherjee I'm not sure if I can do anything with this. I'm not actually running a Windows box right now and getting a VM and VS setup would be very time consuming for what I suspect is an issue with ripple that only MS can fix.

**Comment by fredgalvao** [comment]
Make sure you're wrapping the call to `registerForPushNotifications` on a `deviceready` event listener, and also make sure Ripple isn't failing at emulating that event (it has happened to me in the distant past).

**Comment by Rana-Mukherjee** [comment]
@fredgalvao Thanks for responding. 
I am calling registerForPushNotifications method inside the deviceready function only. Also tried to ran the app in actual device, but it is not working. I am stuck in this from last 2 days. Any help will be highly appreciable.

**Comment by Rana-Mukherjee** [comment]
@macdonst Thanks for responding. I guess the issue is not related with the ripple as this code is not running when I installed the apk in real device. I am stuck in this from last 2 days. Any help will be highly appreciable.

**Comment by Rana-Mukherjee** [comment]
In one of my colleague's machine the PushNotification method undefined message is not coming, looks like it is defined over there. But while trying to run that code it is giving error "missing exec:PushNotification.init" in devtools and one alert message is appearing in the ripple with heading test "I Haz Cheeseburger?!?!" and in the body content "PushNotification.init

We seem to be missing some stuff :(

What is kinda cool though you can fill in the textarea to pass a json object to the callback you want to execute"

Don't understand under which condition this message will appear.
