### ISSUE TITLE
Windows documentation

### ISSUE THREAD

**Issue by Martin-Luckow** [phonegap/phonegap-plugin-push#160]
Could you please document the "Windows specific initialization options."?
Is there an example how to register with Azures Notification Hub?

**Comment by fredgalvao** [comment]
As far as the source code and my ability to read it goes, there are no specific windows options right now. Can't speak for the Azure Notification Hub though.

**Comment by macdonst** [comment]
@Martin-Luckow yeah, there is no options to pass into Windows currently. How to register with Azure Notification Hub is out of the purview of this plugin but maybe @rakatyal can point you at some documentation.

**Comment by Martin-Luckow** [comment]
@macdonst: I'm a little bit confused - used to be that :) 
Parsing your slides from PG Day, there is an option "wp": { "channelName": "xyz", }. Was that for wp8 only and is deprecated now?

**Comment by macdonst** [comment]
@Martin-Luckow Yeah, the API has changed a bit since PG Day. Microsoft generously spent some time getting Windows Universal working for this plugin so 'wp' became 'windows'.

**Comment by rakatyal** [comment]
@Martin-Luckow: Yes that option is not in use now. This is a good place to start for the Azure Notification Hub:
https://azure.microsoft.com/en-us/documentation/articles/notification-hubs-windows-store-dotnet-get-started/

**Comment by Martin-Luckow** [comment]
@Raghav: Thank you. I already found and read it. Works fine with c#.
My issue is to implement the c#-code in section „Connect your app to the notification hub„ in JavaScript/AngularJS under Cordova.

**Comment by Martin-Luckow** [comment]
@Simon: And there is no need for the „uccb“ Channel Handler?

In the old plugin, that was the moment when the registration at the Notification Hub happened. Have no idea when to do this in the new plugin.

**Comment by rakatyal** [comment]
@Martin-Luckow: Sorry for the late reply. The 'uccb' function corresponded to the registration handler i.e. the function which gets executed when the registration happened. In this plugin, you can write that code inside:

push.on('registration', function(data) {
        // data.registrationId
});
