### ISSUE TITLE
Ionic cordova project not compiling when using phonegap-push-plugin

### ISSUE THREAD

**Issue by mobigaurav** [phonegap/phonegap-plugin-push#1601]
I am using ionic framework and cordova for my project. Everything was working fine. Suddenly when i did ionic state reset, gulp build and ionic build android i have started getting error from phonegap-push-plugin. It shows following error:

/Users/gauravku/Desktop/FeatureColab/platforms/android/src/com/adobe/phonegap/push/PushHandlerActivity.java:46: error: cannot find symbol

        if(inline && android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.N){
                                                                                      ^
  symbol:   variable N
  location: class VERSION_CODES

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
I have tried all possible ways > updating my android SDKs , checking the android sdk path is correct from CLI.

My Cordova version: 6.5.0
Phonegap-push-plugin version:1.9.4
Android Support Library version is > 23
Google Play Services version  >23
Google Repository version >23
JDK version: 8.0

<img width="704" alt="screen3" src="https://cloud.githubusercontent.com/assets/8948442/23172492/e59e7b56-f823-11e6-944c-e139405f36d2.png">

**Comment by macdonst** [comment]
@mobigaurav you are not building with the latest Android SDK. The `android.os.Build.VERSION_CODES.N` was introduced with API level 24 so you must be building with 23 or earlier. In the `platforms/android/project.properties` check to see what your `target` is set to.

**Comment by mobigaurav** [comment]
Hey , please take a look on below lines. These are content from my project.properties file. Target SDK is set to 25. Build still fails for same reason.

# This file is automatically generated by Android Tools.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must be checked in Version Control Systems.
#
# To customize properties used by the Ant build system edit
# "ant.properties", and override values to adapt the script to your
# project structure.
#
# To enable ProGuard to shrink and obfuscate your code, uncomment this (available properties: sdk.dir, user.home):
#proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt
# Project target.
target=android-25
android.library.reference.1=CordovaLib
cordova.system.library.1=com.android.support:appcompat-v7:23+
cordova.gradle.include.1=com.synconset.imagepicker/ppct-ignorelinterrors.gradle
cordova.gradle.include.2=com.synconset.imagepicker/ppct-androidtarget.gradle
cordova.system.library.2=com.android.support:support-v4:24.1.1+
cordova.system.library.3=com.google.android.gms:play-services-analytics:+
cordova.system.library.4=com.android.support:support-v4:+
cordova.gradle.include.3=phonegap-plugin-push/ppct-push.gradle
cordova.system.library.5=com.android.support:support-v13:23+
cordova.system.library.6=com.google.android.gms:play-services-gcm:10.2+
cordova.system.library.7=me.leolin:ShortcutBadger:1.1.12@aar

**Comment by macdonst** [comment]
@mobigaurav when you run `android` from the command line do you see that API level 25 is installed?

Also, it may be that you need to remove the android platform and add it back in again.

**Comment by mobigaurav** [comment]
Yes i can see API level 25 is installed. Also i tried removing android platform and adding it again but no help.

i am attaching below screenshots for your reference.
![screen4](https://cloud.githubusercontent.com/assets/8948442/23178259/c17b5014-f837-11e6-8494-b36147c56cdf.png)
![screen5](https://cloud.githubusercontent.com/assets/8948442/23178260/c1a14fc6-f837-11e6-9710-e812392beb22.png)

**Comment by macdonst** [comment]
@mobigaurav my best guess is your $ANDROID_HOME variable is pointing to a different location than where you have all the SDK's installed. Also, when I say API 25 I mean this:

![screenshot 2017-02-21 13 17 03](https://cloud.githubusercontent.com/assets/353180/23178385/398649ec-f838-11e6-90a5-aaee9acd9f98.png)

**Comment by mobigaurav** [comment]
@macdonst  I checked again location for ANDROID_HOME and its pointing to correct path. Please see attached screenshots.
![screen7](https://cloud.githubusercontent.com/assets/8948442/23178905/1b328b66-f83a-11e6-9182-335f961cf6d1.png)
![screen8](https://cloud.githubusercontent.com/assets/8948442/23178907/1b5f3148-f83a-11e6-94a4-e3e8322b292f.png)

**Comment by macdonst** [comment]
@mobigaurav everything looks correct. So I have no idea, maybe ask Ionic.

**Comment by ehorodyski** [comment]
Having the same issue.

@macdonst - Why would you think it would be an Ionic problem? Ionic is a JavaScript framework and the error looks to be from when gradle builds this plugin.

**Comment by macdonst** [comment]
@ehorodyski well @mobigaurav mentioned that they were using Ionic to compile. Since I don't have a ton of experience using the Ionic CLI I'm unsure if Ionic pins to a certain level of the Android SDK or not. Since everything else looks to be in order it would be something to check out.

**Comment by ehorodyski** [comment]
@macdonst - I have the same issue on Windows, and it's during the gradle compilation. I'll post more details tomorrow once I have my work laptop with me. 

Has this plugin been tested against the latest `cordova-android` version?

**Comment by macdonst** [comment]
@ehorodyski yup, I'm running 6.1.2 which is the latest and I am a core contributor of cordova-android.

**Comment by mobigaurav** [comment]
@macdonst- I don't see ionic causing this problem , Ionic build application based on ANDROID_HOME path set by user. That's correct in this case. Hopefully we will find out solution for this issue.

**Comment by ehorodyski** [comment]
@macdonst - 

I'm running `cordova build android` and get the following:

```bash
C:\Projects\...\platforms\android\src\com\adobe\phonegap\push\PushHandlerActivity.java:46: error: cannot find symbol
        if(inline && android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.N && !startOnBackground){
                                                                                      ^

  symbol:   variable N
  location: class VERSION_CODES

Note: Some input files use or override a deprecated API.
```
The correct SDK is installed since I can use `android.os.Build.VERSION_CODES.N` in Android Studio. 

I also have the following inside **AndroidManifest.xml** ` <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="25" />`. 

How would one know figure out what path Cordova is picking the Android SDK from?

**Comment by macdonst** [comment]
@mobigaurav I'm sorry that I haven't been more helpful it's just that I don't know how your system is setup. It's obviously a problem where the build scripts can't find API level 25 when building. I don't know why that is as I can't reproduce it. What version of cordova-android is reported when you do:

`cordova platforms`

@ehorodyski just because the SDK is available in Android Studio, doesn't mean it is available at the command line. I've seen issues where folks have two Android SDK's installed. One for Android Studio and a second picked up by the command line which you can check to see where it is pointing by looking at %ANDROID_HOME%.

**Comment by mobigaurav** [comment]
@macdonst : I have attached screenshot.
<img width="753" alt="screen9" src="https://cloud.githubusercontent.com/assets/8948442/23215384/242f6dd2-f8e0-11e6-8da8-a00eaafc23d7.png">

**Comment by ehorodyski** [comment]
@macdonst - Thanks for the quick response and for all the support. I can confirm that the paths do match for Android Studio and Cordova.

Perhaps another plugin is in conflict? I will have to try creating a new project from scratch and see if I still encounter this issue if this is the only plugin.

**Comment by mobigaurav** [comment]
Yes phonegap-plugin-push is fine , i was having other plugin which causes this issue. 'https://github.com/Telerik-Verified-Plugins/ImagePicker' plugin uses android sdk location to install and is not yet updated with latest android version. When i removed this plugin and build the project then everything worked fine. Thanks for all the help!

**Comment by shaibansid** [comment]
@mobigaurav this is exactly what i'm facing from straight several days. Do you got any solution for this issue? I'm using both `https://github.com/Telerik-Verified-Plugins/ImagePicker`  and _phonegap-plugin-push_ Please help me out, i'm stressed out from days!!!!

**Comment by mobigaurav** [comment]
@shaibansid  i have put comments here and 'http://stackoverflow.com/questions/42304714/ionic-cordova-project-not-compiling-when-using-phonegap-push-plugin' as well. You may need to migrate to previous version of phonegap-plugin-push if want to keep image picker plugin as well otherwise remove image picker plugin and then you will be able to use latest version of phonegap-push-plugin.

**Comment by yurik94** [comment]
Same issue. :(

**Comment by mchenx** [comment]
I got the same issue and I do have the API25 sdk installed, the only thing that I don't have is there is NO google API for android-25
![android-sdk-issue](https://cloud.githubusercontent.com/assets/1550186/26756118/584bde64-48ce-11e7-9d31-e530ac9c676f.jpg)

**Comment by yurik94** [comment]
Fixed changing .N with 25

Il 03 giu 2017 20:34, "mchenx" <notifications@github.com> ha scritto:

I got the same issue and I do have the API25 sdk installed, the only thing
that I don't have is there is NO google API for android-25
[image: android-sdk-issue]
<https://cloud.githubusercontent.com/assets/1550186/26756118/584bde64-48ce-11e7-9d31-e530ac9c676f.jpg>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/phonegap/phonegap-plugin-push/issues/1601#issuecomment-305993356>,
or mute the thread

**Comment by mchenx** [comment]
yes, literally using 25 instead of the enum temporarily fixed this issue but it's not a long term solution... if this is not a phonegap-plugin issue, it's a android sdk issue?

**Comment by mfzagal** [comment]
Try Upgrade targetSdk in config.xml

    <preference name="android-targetSdkVersion" value="24" />
