### ISSUE TITLE
cant build ios cordova in xcode with push plugin

### ISSUE THREAD

**Issue by rogerhaw** [phonegap/phonegap-plugin-push#1602]
### Expected Behaviour

Build cordova ios app with push plugin - build successful in xcode

### Actual Behaviour

xcode doesnt build app with plugin (see logs below)

#### Steps to Reproduce 

add latest ios platform, latest push plugin
build app in xcode

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
xcode 8.1
ios 4.3.1
phonegap-plugin-push 1.9.4

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
NA
#### Cordova CLI version and cordova platform version

    cordova --version                   #6.4.0
    cordova platform version ios #4.3.1

#### Plugin version

    phonegap-plugin-push 1.9.4

#### Sample Push Data Payload
NA
#### Sample Code that illustrates the problem
NA
#### Logs taken while reproducing problem

Ld /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator/MyShifts.app/MyShifts normal x86_64
    cd /Users/rhawkins/Projects/inetmob2/cordova/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk -L/Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator -L/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/GGLInstanceID/Libraries -L/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/GoogleCloudMessaging/Libraries -F/Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator -F/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/GoogleIPhoneUtilities/Frameworks -F/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/GoogleInterchangeUtilities/Frameworks/frameworks -F/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/GoogleSymbolUtilities/Frameworks/frameworks -F/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/GoogleUtilities/Frameworks/frameworks -filelist /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Intermediates/MyShifts.build/Debug-iphonesimulator/MyShifts.build/Objects-normal/x86_64/MyShifts.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=8.0 -Xlinker -object_path_lto -Xlinker /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Intermediates/MyShifts.build/Debug-iphonesimulator/MyShifts.build/Objects-normal/x86_64/MyShifts_lto.o -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -ObjC -lGGLInstanceIDLib -lGcmLib -lsqlite3 -lz -framework AddressBook -framework CoreGraphics -framework GoogleIPhoneUtilities -framework GoogleInterchangeUtilities -framework GoogleSymbolUtilities -framework GoogleUtilities -framework SystemConfiguration -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Intermediates/MyShifts.build/Debug-iphonesimulator/MyShifts.build/MyShifts.app.xcent /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator/libCordova.a -framework CoreLocation -lPods-MyShifts -weak_framework ImageIO -framework AVFoundation -framework AddressBook -lsqlite3 -lz -Xlinker -dependency_info -Xlinker /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Intermediates/MyShifts.build/Debug-iphonesimulator/MyShifts.build/Objects-normal/x86_64/MyShifts_dependency_info.dat -o /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator/MyShifts.app/MyShifts

ld: library not found for -lPods-MyShifts

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rogerhaw** [comment]
and these warnings:

Showing Recent Issues

CompileC /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Intermediates/MyShifts.build/Debug-iphonesimulator/MyShifts.build/Objects-normal/x86_64/PushPlugin.o MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

    cd /Users/rhawkins/Projects/inetmob2/cordova/platforms/ios

    export LANG=en_US.US-ASCII

    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/rhawkins/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/rhawkins/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DCOCOAPODS=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -Wno-infinite-recursion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Intermediates/MyShifts.build/Debug-iphonesimulator/MyShifts.build/MyShifts-generated-files.hmap
-I/Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Intermediates/MyShifts.build/Debug-iphonesimulator/MyShifts.build/MyShifts-own-target-headers.hmap -I/Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Intermediates/MyShifts.build/Debug-iphonesimulator/MyShifts.build/MyShifts-all-target-headers.hmap -iquote /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Intermediates/MyShifts.build/Debug-iphonesimulator/MyShifts.build/MyShifts-project-headers.hmap -I/Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator/include -I/Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator/usr/local/lib/include
-I/Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Intermediates/UninstalledProducts/include -I/Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Intermediates/UninstalledProducts/iphonesimulator/include -I/Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator -I/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/Headers/Public -I/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/Headers/Public/GGLInstanceID -I/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/Headers/Public/GoogleCloudMessaging -I/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/Headers/Public/GoogleIPhoneUtilities -I/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/Headers/Public/GoogleInterchangeUtilities
-I/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/Headers/Public/GoogleSymbolUtilities -I/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/Headers/Public/GoogleUtilities -I/Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Intermediates/MyShifts.build/Debug-iphonesimulator/MyShifts.build/DerivedSources/x86_64 -I/Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Intermediates/MyShifts.build/Debug-iphonesimulator/MyShifts.build/DerivedSources -F/Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator -F/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/GoogleIPhoneUtilities/Frameworks -F/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/GoogleInterchangeUtilities/Frameworks/frameworks
-F/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/GoogleSymbolUtilities/Frameworks/frameworks -F/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/GoogleUtilities/Frameworks/frameworks -isystem /Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/Headers/Public -isystem /Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/Headers/Public/GGLInstanceID -isystem /Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/Headers/Public/GoogleCloudMessaging -isystem /Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/Headers/Public/GoogleIPhoneUtilities -isystem /Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/Headers/Public/GoogleInterchangeUtilities -isystem /Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/Headers/Public/GoogleSymbolUtilities -isystem /Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/Pods/Headers/Public/GoogleUtilities -include /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Intermediates/PrecompiledHeaders/MyShifts-Prefix-gmviuctxgjlzrvbidzklrpgnbbxp/MyShifts-Prefix.pch -MMD -MT dependencies -MF /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Intermediates/MyShifts.build/Debug-iphonesimulator/MyShifts.build/Objects-normal/x86_64/PushPlugin.d --serialize-diagnostics /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Intermediates/MyShifts.build/Debug-iphonesimulator/MyShifts.build/Objects-normal/x86_64/PushPlugin.dia -c /Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m -o /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Intermediates/MyShifts.build/Debug-iphonesimulator/MyShifts.build/Objects-normal/x86_64/PushPlugin.o




In file included from /Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:29:

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.h:32:35: warning: cannot find protocol definition for 'GGLInstanceIDDelegate'

@interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate, GCMReceiverDelegate>

                                  ^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.h:30:11: note: protocol 'GGLInstanceIDDelegate' has no definition

@protocol GGLInstanceIDDelegate;

          ^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.h:32:58: warning: cannot find protocol definition for 'GCMReceiverDelegate'

@interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate, GCMReceiverDelegate>

                                                         ^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.h:31:11: note: protocol 'GCMReceiverDelegate' has no definition

@protocol GCMReceiverDelegate;

          ^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:87:39: warning: capturing 'self' strongly in this block is likely to lead to a retain cycle [-Warc-retain-cycles]

            [weakSelf failWithMessage:self.callbackId withMsg:@"" withError:error];

                                      ^~~~

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:56:5: note: block will be retained by an object strongly retained by the captured object

    gcmRegistrationHandler = ^(NSString *registrationToken, NSError *error){

    ^~~~~~~~~~~~~~~~~~~~~~

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:224:9: warning: 'UIRemoteNotificationType' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]

        UIRemoteNotificationType notificationTypes = UIRemoteNotificationTypeNone;

        ^

In module 'UIKit' imported from /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator/include/Cordova/CDVAvailabilityDeprecated.h:20:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:68:32: note: 'UIRemoteNotificationType' has been explicitly marked deprecated here

typedef NS_OPTIONS(NSUInteger, UIRemoteNotificationType) {

                               ^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:224:54: warning: 'UIRemoteNotificationTypeNone' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]

        UIRemoteNotificationType notificationTypes = UIRemoteNotificationTypeNone;

                                                     ^

In module 'UIKit' imported from /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator/include/Cordova/CDVAvailabilityDeprecated.h:20:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:69:5: note: 'UIRemoteNotificationTypeNone' has been explicitly marked deprecated here

    UIRemoteNotificationTypeNone    = 0,

    ^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:233:34: warning: 'UIRemoteNotificationTypeBadge' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]

            notificationTypes |= UIRemoteNotificationTypeBadge;

                                 ^

In module 'UIKit' imported from /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator/include/Cordova/CDVAvailabilityDeprecated.h:20:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:70:5: note: 'UIRemoteNotificationTypeBadge' has been explicitly marked deprecated here

    UIRemoteNotificationTypeBadge   = 1 << 0,

    ^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:241:34: warning: 'UIRemoteNotificationTypeSound' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]

            notificationTypes |= UIRemoteNotificationTypeSound;

                                 ^

In module 'UIKit' imported from /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator/include/Cordova/CDVAvailabilityDeprecated.h:20:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:71:5: note: 'UIRemoteNotificationTypeSound' has been explicitly marked deprecated here

    UIRemoteNotificationTypeSound   = 1 << 1,

    ^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:249:34: warning: 'UIRemoteNotificationTypeAlert' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]

            notificationTypes |= UIRemoteNotificationTypeAlert;

                                 ^

In module 'UIKit' imported from /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator/include/Cordova/CDVAvailabilityDeprecated.h:20:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:72:5: note: 'UIRemoteNotificationTypeAlert' has been explicitly marked deprecated here

    UIRemoteNotificationTypeAlert   = 1 << 2,

    ^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:255:30: warning: 'UIRemoteNotificationTypeNewsstandContentAvailability' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]

        notificationTypes |= UIRemoteNotificationTypeNewsstandContentAvailability;

                             ^

In module 'UIKit' imported from /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator/include/Cordova/CDVAvailabilityDeprecated.h:20:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:73:5: note: 'UIRemoteNotificationTypeNewsstandContentAvailability' has been explicitly marked deprecated here

    UIRemoteNotificationTypeNewsstandContentAvailability = 1 << 3,

    ^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:270:34: warning: 'UIRemoteNotificationTypeNone' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]

        if (notificationTypes == UIRemoteNotificationTypeNone)

                                 ^

In module 'UIKit' imported from /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator/include/Cordova/CDVAvailabilityDeprecated.h:20:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:69:5: note: 'UIRemoteNotificationTypeNone' has been explicitly marked deprecated here

    UIRemoteNotificationTypeNone    = 0,

    ^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:344:15: warning: 'UIRemoteNotificationTypeBadge' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]

             (UIRemoteNotificationTypeBadge | UIRemoteNotificationTypeSound | UIRemoteNotificationTypeAlert)];

              ^

In module 'UIKit' imported from /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator/include/Cordova/CDVAvailabilityDeprecated.h:20:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:70:5: note: 'UIRemoteNotificationTypeBadge' has been explicitly marked deprecated here

    UIRemoteNotificationTypeBadge   = 1 << 0,

    ^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:344:47: warning: 'UIRemoteNotificationTypeSound' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]

             (UIRemoteNotificationTypeBadge | UIRemoteNotificationTypeSound | UIRemoteNotificationTypeAlert)];

                                              ^

In module 'UIKit' imported from /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator/include/Cordova/CDVAvailabilityDeprecated.h:20:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:71:5: note: 'UIRemoteNotificationTypeSound' has been explicitly marked deprecated here

    UIRemoteNotificationTypeSound   = 1 << 1,

    ^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:344:79: warning: 'UIRemoteNotificationTypeAlert' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]

             (UIRemoteNotificationTypeBadge | UIRemoteNotificationTypeSound | UIRemoteNotificationTypeAlert)];

                                                                              ^

In module 'UIKit' imported from /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator/include/Cordova/CDVAvailabilityDeprecated.h:20:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:72:5: note: 'UIRemoteNotificationTypeAlert' has been explicitly marked deprecated here

    UIRemoteNotificationTypeAlert   = 1 << 2,

    ^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:343:48: warning: 'registerForRemoteNotificationTypes:' is deprecated: first deprecated in iOS 8.0 - Use -[UIApplication registerForRemoteNotifications] and UserNotifications Framework's -[UNUserNotificationCenter requestAuthorizationWithOptions:completionHandler:] [-Wdeprecated-declarations]

            [[UIApplication sharedApplication] registerForRemoteNotificationTypes:

                                               ^

In module 'UIKit' imported from /Users/rhawkins/Library/Developer/Xcode/DerivedData/MyShifts-awbjelfzftxvmqaewvsvlqukcbib/Build/Products/Debug-iphonesimulator/include/Cordova/CDVAvailabilityDeprecated.h:20:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:210:1: note: 'registerForRemoteNotificationTypes:' has been explicitly marked deprecated here

- (void)registerForRemoteNotificationTypes:(UIRemoteNotificationType)types NS_DEPRECATED_IOS(3_0, 8_0, "Use -[UIApplication registerForRemoteNotifications] and UserNotifications Framework's -[UNUserNotificationCenter requestAuthorizationWithOptions:completionHandler:]") __TVOS_PROHIBITED;

^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:603:42: warning: undeclared selector 'userHasRemoteNotificationsEnabled' [-Wundeclared-selector]

    if ([appDelegate respondsToSelector:@selector(userHasRemoteNotificationsEnabled)]) {

                                         ^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:604:49: warning: undeclared selector 'userHasRemoteNotificationsEnabled' [-Wundeclared-selector]

        enabled = [appDelegate performSelector:@selector(userHasRemoteNotificationsEnabled)];

                                                ^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:615:9: warning: local declaration of 'callbackId' hides instance variable [-Wshadow-ivar]

    if (callbackId != nil)

        ^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:618:73: warning: local declaration of 'callbackId' hides instance variable [-Wshadow-ivar]

        [self.commandDelegate sendPluginResult:commandResult callbackId:callbackId];

                                                                        ^

/Users/rhawkins/Projects/inetmob2/cordova/platforms/ios/MyShifts/Plugins/phonegap-plugin-push/PushPlugin.m:637:69: warning: local declaration of 'callbackId' hides instance variable [-Wshadow-ivar]

    [self.commandDelegate sendPluginResult:commandResult callbackId:callbackId];

                                                                    ^

19 warnings generated.

**Comment by macdonst** [comment]
@rogerhaw did you open the project or the workspace because you should open the workspace.

**Comment by rogerhaw** [comment]
thx @macdonst 
that was it...
I am not an xcode developer - what is the difference with the workspace and the way this version of the plugin with cocoapods is developed?

**Comment by rogerhaw** [comment]
also do I need to worry about the deprecation warnings and semantic issue warnings?
thx

**Comment by macdonst** [comment]
@rogerhaw a workspace can have multiple projects and the cocoapods are included in a separate project. Ignore the warnings, they are fine.

**Comment by rogerhaw** [comment]
thx for your help!!

**Comment by sonicwong** [comment]
@rogerhaw  I got the same error when build app with xcode manually.
It is ok(no error) to build via CLI.
