### ISSUE TITLE
ios 9.3 not registering: TypeError: undefined is not an object (evaluating 'n.plugins.pushNotification.register')

### ISSUE THREAD

**Issue by gdiodati** [phonegap/phonegap-plugin-push#1603]
### Expected Behaviour
Device should register.
### Actual Behaviour
It fails on deviceReady to register
### Reproduce Scenario (including but not limited to)
Launching app
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Ipad ios 9.3.5
#### Cordova CLI version and cordova platform version
cordova 6.5.0
cordova-ios 4.2.1 and 4.3.1
#### Plugin version
phonegap-plugin-push 1.8.1 and 1.9.2
#### Logs taken while reproducing problem
 ng-cordova.min.js:9:15128TypeError: undefined is not an object (evaluating 'n.plugins.pushNotification.register')

It works perfectly fine on Android.
Please please help!!!

**Comment by macdonst** [comment]
@gdiodati did you add the SENDER_ID variable correctly for Ionic?

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md#ionic-cloud-build

**Comment by gdiodati** [comment]
Yes I did :(

**Comment by gdiodati** [comment]
Anyone? Please?

**Comment by macdonst** [comment]
@gdiodati I was talking to Ionic folks today and 1.9.x is not supported right now. Do you get the same error using 1.8.1?

**Comment by gdiodati** [comment]
@macdonst Yes. Same error on 1.8.1.
