### ISSUE TITLE
White square notification icon in Android Nougat

### ISSUE THREAD

**Issue by LlamaloX** [phonegap/phonegap-plugin-push#1605]
Any reason why in Android Nougat the notification icon is a white square? Icon shows correctly in other versions of Android

**Comment by macdonst** [comment]
![ex1wekt](https://cloud.githubusercontent.com/assets/353180/20806688/ecc9f21a-b7c9-11e6-9f58-e94e693c6b60.png)

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images

**Comment by Barathwaja** [comment]
@macdonst its not working in nougat.. but working in lower versions. Same issue happening for me. and i don't wana push image via server side.

**Comment by macdonst** [comment]
@Barathwaja read the docs above and the links to the Android docs.

**Comment by Barathwaja** [comment]
@macdonst those phonegap plugin are old.. You posted one snapshot of android nougat with a white one notification check you comments in one post. That's what I'm getting and again I'm telling that they are sending payload from server side .. for image too.. 

It's working for all OS other than nougat.

**Comment by Barathwaja** [comment]
@macdonst

check the below image.
Red marked.

![noimage](https://user-images.githubusercontent.com/5066436/30270939-0e22b3bc-970c-11e7-9f50-85c5bf78440c.png)

**Comment by macdonst** [comment]
@Barathwaja please stop commenting on every issue. You are not going to get a different answer. Your problem is clearly explained in the docs, in Android docs and an host of other issues in this plugin. Your icon does not have transparent pixels so that is why it shows up as a white/grey box.
