### ISSUE TITLE
Can't install plugin in iOS with Cocoa

### ISSUE THREAD

**Issue by vinimendes3** [phonegap/phonegap-plugin-push#1606]
I'm trying to install the plugin normally as always installed (it always worked for me in other projects before the entering of Cocoa):

`cordova plugin add phonegap-plugin-push --variable SENDER_ID="MY_SENDER_ID_HERE"`

I always get the following error, and tried many solutions:

![screenshot 2017-02-22 23 34 45](https://cloud.githubusercontent.com/assets/3437722/23242458/a3d4efa4-f957-11e6-9f97-dcd9e4d7544e.png)

I already tried to run as sudo:

`sudo cordova plugin add........`

but it was generating for me another error in a moment of installation: 

> You cannot run CocoaPods as root

Then I'm now trying to install without sudo, in the current situation...

I'm stopped in this scenario trying to continue :/

A few informations:

> Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002

Thanks in advance

**Comment by macdonst** [comment]
@vinimendes3 it's not really a plugin problem, it's more of a setup problem. IIRC you would have to fix it by doing something like this:

```
# To ensure permissions are correct, run this command on Mac or Linux, changing LOGIN to match your account name:
$ sudo chown -R LOGIN /usr/local/lib/node_modules/cordova
```

Also, don't post screenshots of errors, copy and paste those errors. It's way easier to read and you can search on text inside images.

**Comment by vinimendes3** [comment]
@macdonst I tried this but it still remains the error for me. Same error:

`shell.js: internal error
Error: EACCES: permission denied, mkdir '/Users/viniciusmendesdesouza/Dropbox/WorkspaceIonic/RemoteLink_v2/plugins/phonegap-plugin-push'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at mkdirSyncRecursive (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mkdir.js:11:8)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mkdir.js:63:7
    at Array.forEach (native)
    at Object._mkdir (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mkdir.js:48:8)
    at Object.mkdir (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
    at copyPlugin (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:373:15)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:214:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)`

**Comment by macdonst** [comment]
@vinimendes3 try this:

```
cd /Users/viniciusmendesdesouza/Dropbox/WorkspaceIonic
sudo chown -R viniciusmendesdesouza /Users/viniciusmendesdesouza/Dropbox/WorkspaceIonic/RemoteLink_v2
```

**Comment by vinimendes3** [comment]
NIiice! It worked :D 
Thaaanks @macdonst !!
