### ISSUE TITLE
On Android, when opening a notification and the app is closed, nothing happens

### ISSUE THREAD

**Issue by AmitMY** [phonegap/phonegap-plugin-push#1609]
### Expected Behaviour
Like on iOS, the notification should be processable

### Actual Behaviour
On Android, it just ignores the notification, and does not call the "notification" callback. (when outside the app. When inside it works)

### Reproduce Scenario (including but not limited to) & Steps to Reproduce 
- Send a notification with `notification` and `data` using `fcm-push` to an android device, while app is closed, like:
```
{
    to: user.token,
    data: {some: "payload"},
    notification: {
        title: "test",
        tag: "some-tag",
        color: "#fff",
        body: "hey! I am a test notification",
        sound: "default"
    }
}
```
Open the notification, and check if it triggered anything

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
OnePlus (using OnePlus X)

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.5.0
    cordova platform version android           6.1.1

#### Plugin version

1.9.2

#### Sample Push Data Payload
See above

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
No notifications recorded inside the app.

### Notes:
I am using the plugin with Ionic2
Related issue I opened with ionic: https://forum.ionicframework.com/t/notifications-when-app-is-closed/80604/4

**Comment by fredgalvao** [comment]
![Y U NO](http://i.imgur.com/Ex1WEkT.png)

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

**Comment by AmitMY** [comment]
@fredgalvao I wasn't aware it is a payload problem. Thank you ever so much! Will try to search more next time :)

**Comment by fredgalvao** [comment]
I'm glad it solved it for you. Feel free to re-open or create a new issue if you find any further problems.
