### ISSUE TITLE
Option to disable auto-clearing of badge count number on load

### ISSUE THREAD

**Issue by jakenewby** [phonegap/phonegap-plugin-push#161]
Hi there.  I've been using this push plugin in an application I'm building.  It's wonderful and I cannot thank you enough for it. 

That having been said, I've noticed that there is still no option to disable the auto-clearing of the badge count number when the plugin loads for iOS.  I believe this would be a good feature to add to the plugin so that people do not have to continue to 'hack the source'.  

In src/ios/AppDelegate+notification.m: 

```
- (void)applicationDidBecomeActive:(UIApplication *)application {

    NSLog(@"active");

    //zero badge
    application.applicationIconBadgeNumber = 0;
```

Original Source [here](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/AppDelegate%2Bnotification.m#L90).

**Comment by macdonst** [comment]
If you are hacking the source then just submit a PR 😀

**Comment by rubenstolk** [comment]
@macdonst What's the plan for merging #161 into master?

**Comment by macdonst** [comment]
@rubenstolk it doesn't quite work yet. I have to circle back to it.

**Comment by rubenstolk** [comment]
Alright, I also ended up hacking the source code now, I guess this is quite an important one because the current default behavior doesn't give a lot of power to the developer.

**Comment by jakenewby** [comment]
Lovely to see progress here, cheers @macdonst.  I wasn't so much 'hacking the source' as I was commenting out a single line of code, misleading, I know. hah.

**Comment by macdonst** [comment]
@jakenewby yeah, I might need to 'drop down to machine code level' in order to fix this one. The problem I'm having is the AppDelegate code gets called way before init so I might have to remove that altogether.

**Comment by rubenstolk** [comment]
It's probably better to remove it and have it optionally through javascript in deviceready/resume events...

**Comment by macdonst** [comment]
@rubenstolk that's basically where I'm going. If I get some time today I will finish it up. I'm currently at the Cordova Face 2 Face meeting in Redmond.

**Comment by rubenstolk** [comment]
Great, enjoy!

**Comment by macdonst** [comment]
@rubenstolk @jakenewby If you guys can grab the code from `issue161` and give it a try it would be greatly appreciated. It kinda changes the default behaviour for iOS but it seems like the right thing to do.

**Comment by rubenstolk** [comment]
Looks good @macdonst, let me know when you merge it into develop

**Comment by macdonst** [comment]
@rubenstolk pushed to master.
