### ISSUE TITLE
registration id expired

### ISSUE THREAD

**Issue by minamorsali** [phonegap/phonegap-plugin-push#1610]
hello,
when I build program again and I reinstall the app. the registration event run successfully but I already get previous registration id, but when I try too send notification from node.js I got "Not Registered" error...
Why I got this error and how to solve this?
please help me to solve this issue.
thanks a lot

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
