### ISSUE TITLE
v1.9.4 fails to build on meteor@1.4.3.1

### ISSUE THREAD

**Issue by dr-dimitru** [phonegap/phonegap-plugin-push#1611]
### Expected Behaviour
Successful build in Xcode

### Actual Behaviour
Build failed with error:
```
ld: library not found for -lPods-appName
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Reproduce Scenario (including but not limited to)
Add package to meteor project and run on device

#### Steps to Reproduce 
 1. Install [meteor](https://github.com/meteor/meteor)
 2. Run `meteor add-platform ios`
 3. Run `meteor add cordova:phonegap-plugin-push@1.9.4`
 4. Run `meteor run ios-device`

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Device iPhone 5 iOS 10.2.1
iOS Emulator 8.* and higher
`IPHONEOS_DEPLOYMENT_TARGET=8.0`
Xcode Version 8.2.1 (8C1002)

#### Cordova CLI version and cordova platform version

    cordova --version            -> 6.4.0
    cordova platform version ios -> 4.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push  -> 1.9.4

#### Additional info
 1. Please see [this comment](https://github.com/meteor/meteor/issues/8085#issuecomment-282408621) and [this comment](https://github.com/meteor/meteor/issues/8085#issuecomment-282349597)
 2. `phonegap-plugin-push@1.8.4` has no this issue

**Comment by macdonst** [comment]
@dr-dimitru the reason you are getting that build error

```
ld: library not found for -lPods-appName
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

is probably because meteor is building using the .xcodeproj instead of the .xcworkspace which is now required in cordova-ios. You see cordova-ios may now have multiple projects in a single workspace.

You should open an issue on meteor.
