### ISSUE TITLE
Not working in browser platform

### ISSUE THREAD

**Issue by diegobill** [phonegap/phonegap-plugin-push#1612]
### Expected Behaviour

PushNotification is defined

### Actual Behaviour

PushNotification is not defined

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
browser

#### Cordova CLI version and cordova platform version

    cordova 6.5.0
    cordova browser 4.1.0

#### Plugin version

    phonegap-plugin-push 1.9.2 "PushPlugin"

#### Sample Code that illustrates the problem

```
ionPlatform.ready.then(function(device) {
           $rootScope.push = PushNotification.init({
                "android": {
                  "senderID": "XXXXXXXXX" //sender hidden
                },
                "ios": {"alert": "true", "badge": "true", "sound": "true"}, 
                "windows": {},
                "browser": {
                    "pushServiceURL": 'http://push.api.phonegap.com/v1/push'
                }
            });
}
```

#### Logs taken while reproducing problem

```
ReferenceError: PushNotification is not defined
    at m.$scope.registerPushNotification (controllers.js:48)
    at controllers.js:42
    at ionic.bundle.min.js:162
    at m.$eval (ionic.bundle.min.js:176)
    at m.$digest (ionic.bundle.min.js:174)
    at m.$apply (ionic.bundle.min.js:177)
    at g (ionic.bundle.min.js:129)
    at x (ionic.bundle.min.js:134)
    at XMLHttpRequest.v.onload (ionic.bundle.min.js:135)
```

**Comment by macdonst** [comment]
@diegobill I'm not sure it is supposed to work in this situation. The `browser` platform is more for testing in the browser. How are you serving up the code to the browser?

**Comment by diegobill** [comment]
@macdonst, I tested running "ionic serve" on my dev environment

**Comment by eldelasfranelas** [comment]
as far i know this plugin only work on the device, when the ionic.platform is ready.

**Comment by macdonst** [comment]
@diegobill I taked to @ericb from Ionic and the push plugin is not supported when running `ionic serve`.

**Comment by YamanSehzade** [comment]
@diegobill  i think you can use `ionic cordova emulate browser` but i have error too.. 

> core.js:1440 ERROR Error: Uncaught (in promise): Error: Error subscribing for Push notifications.
Error: Error subscribing for Push notifications.

maybe the problem may be related to phonegap-plugin-push browser options
