### ISSUE TITLE
ANDROID pgb crash on init

### ISSUE THREAD

**Issue by shlomicohen007** [phonegap/phonegap-plugin-push#1613]
i have i problom with PGB and push-plugin

when i call init the app crash on android ( ios hevent tested )

`PushNotification.init({
            android: {
                senderID: "****",
                forceShow : true
            },
            ios: {
                alert: "true",
                badge: "true",
                sound: "true"
            }
});`

it was working good until couple of days ago that i compiled the new version
in my config.xml i have this

`<plugin name="phonegap-plugin-push" source="npm" spec="1.9.2">
        <param name="SENDER_ID" value="********" />
</plugin>`

i havent change the plugin version

cordova 6.5.0
i have try 
cordova == 5.4.0
phonegap-plugin-push versions: 1.9.2 , 1.9.0 , 1.8.4

my older version work good so i dont undertnd what when worng

can anybody help?
thanks

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
