### ISSUE TITLE
Not able to get new registerid for Android

### ISSUE THREAD

**Issue by tigergroup** [phonegap/phonegap-plugin-push#1615]
### Expected Behaviour
get the new registerid when listening to pushNotification.on('registration')

### Actual Behaviour
seem like android os has changed the device id on some phone so when retrieving the registerid I get the old registerid.  I would have to delete my app and re-install it to retrieve the new registerid.

### Reproduce Scenario (including but not limited to)
Hard to reproduce.  When trying the retrieve the registerid on the app loads the plugin returns the old registerid so push notification does not work anymore.  I would have to delete the app and reinstall then open the app to get the new registerid.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung

#### Cordova CLI version and cordova platform version

    cordova --version                                    # 6.1.2
    cordova platform version android                     # 6 and above

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@tigergroup can you modify the issue to fill in the missing information?
