### ISSUE TITLE
Custom sound volume

### ISSUE THREAD

**Issue by ppetree** [phonegap/phonegap-plugin-push#1616]
### Expected Behaviour
play sounds at same volume as default sounds

### Actual Behaviour
Can barely hear custom sounds

### Reproduce Scenario (including but not limited to)
Ask for sample file

#### Steps to Reproduce 
Install a custom sound file

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 9.x
iOS 10.x
Android 23+

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Various

#### Cordova CLI version and cordova platform version
5.2

#### Plugin version
1.8.1 on XDK

#### Similar request
[#1176](https://github.com/phonegap/phonegap-plugin-push/issues/1176)

I've adjusted my custom sounds and on a laptop or desktop they play at the same volume as the default sounds on either platform. However when the sounds are actually played on the device they are barely audible.

**Comment by macdonst** [comment]
Sadly, there is no way to adjust the volume of the notification. This behaviour is controlled by the operating system.
