### ISSUE TITLE
Handle payload differently in background or app-closed state

### ISSUE THREAD

**Issue by laagland** [phonegap/phonegap-plugin-push#1617]
Following up on #1596 

When a notification is received the code currently does not distinguish between a background state or closed-state. The notification payload is sent to the app and then either delivered or cached for delivery on next init.

Adding an extra check for this means the payload gets discarded when the app is not running. We can either add a **force-cache** or **no-cache** flag to the payload and handle it accordingly. Depending on preference of the default action, which one should we choose?

**Comment by macdonst** [comment]
@laagland is this a comment on #1596 or a new issue? If it is a new issue please fill out the issue template.

**Comment by laagland** [comment]
@macdonst this is a new issue, discussed in the comments of #1596. @fredgalvao advised to split the issues mentioned there. The issue template is basically the same. But to recollect:

### Expected Behaviour
According to the payload flowchart and the text beneath it, when the plugin receives the notification with content-available set to 1 and the app is not running (force-closed), no further processing should occur.

### Actual Behaviour
In the above situation, the payload is cached and sent to the app on initialisation.

While this could be intended behavior, with the current code there is no method to prevent the caching if you want to.

**Comment by laagland** [comment]
@macdonst what should I do to move this issue forward. I've committed some changes to my fork that I think will handle this use-case.

**Comment by macdonst** [comment]
@laagland well, I think you've done the best thing to move this forward by send a pull request. That is the best way to get anything done in an open source project. I'm stupid busy right now but hope to be able to review today and get this merged over the weekend.

**Comment by laagland** [comment]
@macdonst awesome, thanks for your time!

**Comment by macdonst** [comment]
This will be part of 1.10.0
