### ISSUE TITLE
No notification when app is closed on Android, not at all on iOS.

### ISSUE THREAD

**Issue by Hissvard** [phonegap/phonegap-plugin-push#1618]
### Expected Behaviour
Push Notification gets shown when the app is closed.

### Actual Behaviour
Android: Shown when in foreground or minimized, nothing happens when closed.
iOS: Nothing happens.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1
iOS 9.x.x

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Asus Zenfone 2 Laser ZE550KL
iPhone 6 Plus

#### Cordova CLI version and cordova platform version
6.4.4
   
#### Plugin version
1.9.2

#### Sample Code that illustrates the problem
https://hastebin.com/ucecodepes.php
https://hastebin.com/epofanotew.js

The payload might look quite messy since I've been reading threads and trying things out for two hours now.
What I've noticed is that the registration id I receive on the iOS device is only 64 characters long and contains no other characters apart from lowercase letters and numbers.

**Comment by macdonst** [comment]
@Hissvard you are not sending the correct payload. I document the heck out of it in:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md

For Android send:

```
registration_ids" => $token,
    "data" => [
        "title" => "prova",
        "message" => "prova",
        "notId" => "324234",
        "content-available" => 1,
        "priority" => "high",
        "force-start" => 1,
    ]
```

For iOS send:

```
    "registration_ids" => $token,
    "aps" => [
        "alert" => [
            "title" => "prova",
            "body" => "prova"
        ]
    ],
```

**Comment by Hissvard** [comment]
Thank you for the reply.
I'd originally tried that, then ended up mixing things together trying to get it to work.

I still can't receive notifications while the app is in background on Android, and get a `"error":"InvalidRegistration"` error on iOS which I'm guessing could be solved by <a href="https://github.com/phonegap/phonegap-plugin-push/issues/563#issuecomment-192477863">taking a look at the Apple certification process</a>, although I'm not exactly sure where I should be looking.

**Comment by macdonst** [comment]
@Hissvard when you say `can't receive notifications while the app is in background on Android` do you mean it doesn't show up in the notification shade?

When sending to iOS are you using APNS or GCM?

**Comment by Hissvard** [comment]
It doesn't show up in the notification shade and the `notification` event is not fired, exactly.

How do I know which of the two I'm using?

**Comment by macdonst** [comment]
@Hissvard well the event is not fired normally if the app is forced closed as there is no app to receive the event. If you've force closed the app you should still see the notification in the shade so possibly you are running into:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#huawei-and-xiaomi-phones

How are you sending message to the iOS device?

**Comment by Hissvard** [comment]
Oh, it seems that the problem on Android lies indeed in the fact that the app was not enabled in the "autostart" list. It might be useful to add to the documentation that Asus devices suffer from the same issue.

Not sure I understand the question about the iOS device. I'm sending them <a href="https://hastebin.com/gaquloxado.xml">the same way I do it with Android</a>, with the one exception being the payload sent.
What I get back from that is
```JSON
{
  "multicast_id": "<id_here>",
  "success":0,
  "failure":1,
  "canonical_ids":0,
  "results":
  [
    {
      "error":"InvalidRegistration"
    }
  ]
}
```
Like I said, I think the issue with iOS is that the Registration ID I get is not valid since it does not have the same format the one I get from Android devices does. 
I remember it working up until some time ago and giving the correct token, but then it somehow stopped working for some reason. The app is not currently published to the App Store but using Test Flight.

**Comment by Hissvard** [comment]
I've been encountering the same issue again, up until a few days ago the notification was delivered even when the app was force closed, but I have no idea what changed that made it stop doing so.
This is the payload I'm sending (android):
```
{  
   "registration_ids":[  
      "<id here>"
   ],
   "data":{  
      "title":"12345",
      "image":"<image>",
      "notId":"119",
      "style":"picture",
      "picture":"<picture>",
      "message":"12345",
      "content-available":1,
      "priority":"high",
      "force-start":1,
   }
}
```
Any idea what might be wrong?

**Comment by fredgalvao** [comment]
@Hissvard do you have any logs captured during the send/arrive process? We need more details on it to be able to help.

**Comment by Hissvard** [comment]
Sorry for the late reply.
To be honest I've only ever used Phonegap for app development, so I'm sorry to say that I'm unsure about how to get logs while the app is force closed. How would I go about that?

**Comment by Hissvard** [comment]
Nevermind, it turned out to be some setting I'd changed about app autostart.
