### ISSUE TITLE
onNotification inject $http

### ISSUE THREAD

**Issue by luidiva** [phonegap/phonegap-plugin-push#1619]
Hello,

I'm trying to send **regid** to server via $http inside **onNotification** event.
How can I achieve that with AngularJS 1.3, please?

Thank you.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
