### ISSUE TITLE
I can not do the push notification

### ISSUE THREAD

**Issue by devtosystems** [phonegap/phonegap-plugin-push#162]
Hello, 

The push.on ('notification') method does not run in the example index.js#50 and the documentation has not have any example of how to implement push () with the plugin.

Could help me?

Thank you in advance.

[example/www/js/index.js#L50](https://github.com/phonegap/phonegap-plugin-push/blob/master/example/www/js/index.js#L50)

**Comment by macdonst** [comment]
@devtosystems the `notification` event listener should only get called when your app gets a push. Check out the example/server folder for Ruby scripts to send pushes from GCM and APNS.

**Comment by macdonst** [comment]
Closing, re-open if the problem can be reproduced.
