### ISSUE TITLE
'notification' event triggered when it's not suppose to

### ISSUE THREAD

**Issue by toriqo** [phonegap/phonegap-plugin-push#1622]
When the app is in the background (and NOT suspended) and receives a push notification, if the app icon is tapped or the app is opened from the task list or via 3d touch menu (NOT by tapping the notification), the 'notification' event is fired and whatever is attached to it is executed.
### Expected Behaviour
The app should resume from its last state
### Actual Behaviour
The app executes (in my case) the redirect based on the notification payload
#### Steps to Reproduce 
Open the app, send it to background, receive a push notification, tap the app's icon, NOT the notification
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.2.1
#### Cordova CLI version and cordova platform version
    cordova --version 6.3.1
    cordova platform version ios 4.1.0
#### Plugin version
    phonegap-plugin-push 1.8.4

**Comment by macdonst** [comment]
Please provide the payload you use to reproduce this issue.

**Comment by toriqo** [comment]
message->title = *string*
message->body = *string*
message->contentAvailable = *false*
message->sound = *my_custom_sound*
message->badge = *int*
message->data = ***data***

where ***data*** is an object containing some info i'm basing my redirect on:
```
"data": {
      "type": "friend_request",
      "receiving_user_id": 6920469,
      "sender_user_id": 6921044,
      "sender_username": "Username",
      "sender_image_url": "http://url/to/image.jpg"
}
```

**Comment by macdonst** [comment]
@toriqo so are you using GCM to send to iOS? That is an important distinction. Can you send me the whole payload in JSON format instead of having to decode the above?

**Comment by toriqo** [comment]
no, i'm using apple's apn. here's the payload as json:

```
{
    "aps": {
        "title": "title string",
        "body": "body_string",
        "sound": "custom_sound.m4r",
        "content-available": 0,
        "badge": 1
    },
    "data": {
        "type": "friend_request",
        "receiving_user_id": 12321,
        "sender_user_id": 12334,
        "sender_username": "username",
        "sender_image_url": "http://blablabla.com"
    }
}
```

**Comment by gs-sramesh** [comment]
@macdonst Im using GCM to send notification. This is the JSON:

```
{
	"notification": {
		"title": "Test Notification",
        "body": "This offer expires at 11:30 or whatever"	
	},
  "data":{
        "extra": {
        	"url": "someurl"
        }
    },
  "to": "$someid"
}
```

The ```.on('notification')``` event is not being called.

**Comment by toriqo** [comment]
@gs-sramesh look at my payload above your post. you're missing the `"aps"` index in your JSON object

**Comment by toriqo** [comment]
@gs-sramesh your payload is missing the `aps` dictionary. add it instead of the `"notification"` property

**Comment by macdonst** [comment]
@toriqo a couple of things I noticed. First don't include the `.m4r` part of your sound file's name as the OS will fail when it looks up the resource in the app. Second Apple specifically states not to include `"content-available": 0,` unless it is set to `1` so try sending your push without it and let me know.

@gs-sramesh your payload looks correct for GCM on iOS but you should probably create a new issue rather than confusing it with this one.

**Comment by gs-sramesh** [comment]
@macdonst I did create one few days ago. But no replies on that. I will create on now and post the link here. Could you please look into it. I have tried a lot of different json formats. But no luck.

**Comment by toriqo** [comment]
@macdonst the OS finds the resource and it works WITH the `.m4r` filename extension. it's not working WITHOUT it. also, i get the same behaviour with or without the `"content-available": 0`

**Comment by macdonst** [comment]
So what was the root cause?

**Comment by toriqo** [comment]
the fact that i've added `"content-available": 0` :)
