### ISSUE TITLE
how can i auto expand big picture notification

### ISSUE THREAD

**Issue by zaed-murad** [phonegap/phonegap-plugin-push#1623]
how can i auto expand big picture notification

**Comment by macdonst** [comment]
@zaed-murad short answer, you can't.

From Google's docs:

```
A notification's big view appears only when the notification is expanded, which happens when the notification is at the top of the notification drawer, or when the user expands the notification with a gesture.
```

The best you can do to increase the chances of the image being shown is send it as a [higher priority](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#priority-in-notifications).

**Comment by zaed-murad** [comment]
thank you :+1:
