### ISSUE TITLE
Receive additional data

### ISSUE THREAD

**Issue by jeanrl** [phonegap/phonegap-plugin-push#1625]
I'm using Ionic 2 and sending data in the push message, that's fine, but I'm not able to get that data in the application, but I know they're coming because I'm monitoring through Android Studio:

My code is:

initPushNotification()
{
    var push = Push.init({
      android: {
          senderID: '999999999999'
      },
      ios: {
          alert: 'true',
          badge: true,
          sound: 'true'
      },
      windows: {}
   });
}
    push.on('notification', (data) => {
         alert(JSON.stringify(data));
    });
    push.on('error', (e) => {
      console.log("Erro: ", e.message);
    });

}

But when the message arrives if the application is open nothing happens, if it is closed it plays the audio and it appears, but this Alert when the app is open does not work.

By Android Studio I see that I get the message, it comes like this:

V/PushPlugin: extrasToJSON: {"title":"Title","message":"XXXXXX","additionalData":{"dado1":"0","dado2":"0","google.message_id":"0:1488486182299980%017aec09f9fd7ecd","dado3":"7","coldstart":false,"collapse_key":"do_not_collapse","foreground":true}}

Where am I going wrong?

Thank you.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
