### ISSUE TITLE
push notification custom sound not working

### ISSUE THREAD

**Issue by dmarcus1** [phonegap/phonegap-plugin-push#1626]
### Expected Behaviour
phone plays sound when it receives a push notification if the app is closed.

### Actual Behaviour
the default sound plays when it receives a push

I placed ringtone.mp3 in platforms/android/res/raw. I had to create the raw folder. Here is what I send to FCM
```
{
    "registration_ids": ["my device id"],
    "data": {
        "title": "Ringtone",
        "message": "Plays default ringtone sound",
        "soundname": "ringtone"
    }
}
```

Also if I try sending this to FCM
```
{
    "registration_ids": ["my device id"],
    "data": {
        "title": "Silece",
        "message": "Skips playing any sound",
        "soundname": ""
    }
}
```

the default sound still plays even though no sound should play

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
BLU

#### Plugin version
I tried 1.8.x and 1.9.x

**Comment by macdonst** [comment]
@dmarcus1 can you grab some logs when you reproduce the issue using:

`adb logcat | grep PushPlugin`

**Comment by dmarcus1** [comment]
@macdonst Thanks for getting back to me on this. Here's the output after sending the following to FCM/GCM. The filename for the sound is now test.mp3 and it's in the platforms/android/res/raw folder:

{ "registration_ids": "deviceid", "data": { "title": "Ringtone", "message": "Plays default ringtone sound", "soundname": "test" } }

03-03 16:51:39.933 19866 20050 D PushPlugin_GCMIntentService: onMessage - from: 201193496150
03-03 16:51:39.933 19866 20050 D PushPlugin_GCMIntentService: normalize extras
03-03 16:51:39.933 19866 20050 D PushPlugin_GCMIntentService: key = soundname
03-03 16:51:39.933 19866 20050 D PushPlugin_GCMIntentService: replace key soundname with sound
03-03 16:51:39.933 19866 20050 D PushPlugin_GCMIntentService: key = google.sent_time
03-03 16:51:39.934 19866 20050 D PushPlugin_GCMIntentService: replace key google.sent_time with google.sent_time
03-03 16:51:39.934 19866 20050 D PushPlugin_GCMIntentService: key = title
03-03 16:51:39.934 19866 20050 D PushPlugin_GCMIntentService: replace key title with title
03-03 16:51:39.934 19866 20050 D PushPlugin_GCMIntentService: no locale found for key = title, error Value Ringtone of type java.lang.String cannot be converted to JSONObject
03-03 16:51:39.934 19866 20050 D PushPlugin_GCMIntentService: key = google.message_id
03-03 16:51:39.934 19866 20050 D PushPlugin_GCMIntentService: replace key google.message_id with google.message_id
03-03 16:51:39.934 19866 20050 D PushPlugin_GCMIntentService: key = message
03-03 16:51:39.934 19866 20050 D PushPlugin_GCMIntentService: replace key message with message
03-03 16:51:39.935 19866 20050 D PushPlugin_GCMIntentService: no locale found for key = message, error Value Plays of type java.lang.String cannot be converted to JSONObject
03-03 16:51:39.935 19866 20050 D PushPlugin_GCMIntentService: key = collapse_key
03-03 16:51:39.935 19866 20050 D PushPlugin_GCMIntentService: replace key collapse_key with collapse_key
03-03 16:51:39.935 19866 20050 D PushPlugin_GCMIntentService: background
03-03 16:51:39.935 19866 20050 D PushPlugin_GCMIntentService: message =[Plays default ringtone sound]
03-03 16:51:39.935 19866 20050 D PushPlugin_GCMIntentService: title =[Ringtone]
03-03 16:51:39.935 19866 20050 D PushPlugin_GCMIntentService: contentAvailable =[null]
03-03 16:51:39.935 19866 20050 D PushPlugin_GCMIntentService: forceStart =[null]
03-03 16:51:39.935 19866 20050 D PushPlugin_GCMIntentService: create notification
03-03 16:51:39.935 19866 20050 E PushPlugin_GCMIntentService: Number format exception - Error parsing notId: Invalid int: "null"
03-03 16:51:39.943 19866 20050 D PushPlugin_GCMIntentService: stored icon=ic_stat_onesignal_default
03-03 16:51:39.943 19866 20050 D PushPlugin_GCMIntentService: stored iconColor=red
03-03 16:51:39.943 19866 20050 D PushPlugin_GCMIntentService: stored sound=true
03-03 16:51:39.943 19866 20050 D PushPlugin_GCMIntentService: stored vibrate=true
03-03 16:51:39.944 19866 20050 D PushPlugin_GCMIntentService: using icon from plugin options
03-03 16:51:39.944 19866 20050 D PushPlugin_GCMIntentService: android.resource://com.phonegap.helloworld/raw/test
03-03 16:51:39.945 19866 20050 D PushPlugin_GCMIntentService: create actions: with in-line

**Comment by dmarcus1** [comment]
I also tried { "registration_ids": "deviceid", "data": { "title": "Ringtone", "message": "Plays default ringtone sound", "sound": "test" } }

I replaced soundname with sound. It still sends the push notification, but the sound is always the default sound on my phone.

**Comment by dmarcus1** [comment]
I ran it on an emulator, and the custom sound (test.mp3) plays when I send a push notification. I tried restarting my phone and it still doesn't work. The phone is BLU and it runs Marshmallow Android. I notice that "android.resource://com.phonegap.helloworld/raw/test" was an output in the log file. I opened FCMService.java and made it so that setSound(customsound) always gets called. I tried changing "/raw/test" to "/" + R.raw.test and it still didn't work on my BLU phone.

**Comment by macdonst** [comment]
@dmarcus1 interesting, as it is properly picking up the fact that you want to set the custom source as the log you are seeing is coming from [line 654](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/android/com/adobe/phonegap/push/GCMIntentService.java#L654). I can't actually reproduce this bug so I'm wondering if it is an issue with the Blu phone you are using.

**Comment by dmarcus1** [comment]
Yeah it's probably the Blu phone. It worked well on my simulator.
