### ISSUE TITLE
plugin install after iOS not build

### ISSUE THREAD

**Issue by ironelder** [phonegap/phonegap-plugin-push#1628]
hello.
I'm Test Push Notification, 
This Plugin installed after Xcode Error 
This Error only iOS, 
Android OS is Not Error.

Error Code:
Automatic signing is unable to resolve an issue with the "TestPush" target's entitlements file. Remove the entitlements or switch to manual signing and resolve the issue by downloading a provisioning profile from the developer website.
Provisioning profile "iOS Team Provisioning Profile: *" doesn't include the aps-environment entitlement.
Code signing is required for product type 'Application' in SDK 'iOS 10.2'

I wonder if there was the same problem here.
Thank you :)

**Comment by ironelder** [comment]
App Settings -> Capabilities and flip the switch for Push Notifications to On.
solved :)

**Comment by nickrouty** [comment]
@ironelder thank you much, OneSignal didn't seem to mention needing to do this for their target.

**Comment by hugoblanc** [comment]
https://documentation.onesignal.com/docs/phonegap-sdk-setup
