### ISSUE TITLE
Hi please help me i try to implement ionic push notification 

### ISSUE THREAD

**Issue by sanjaykumarisg** [phonegap/phonegap-plugin-push#1630]
I follow all the steps but did not find any result .

Please help me for making push notification using GCM .

Thanks
Sanjay

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
