### ISSUE TITLE
Custom Icon on Android 7 Nougat working?

### ISSUE THREAD

**Issue by tfrenken** [phonegap/phonegap-plugin-push#1631]
### Expected Behaviour
On Android 7, the plugin should use a custom icon file defined in the init-config, either from the drawables or web assets folder, as deribed under https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images.

Actually my first question is whether someone can really confirm that the icons is displayed on a Nougat device.

### Actual Behaviour
Instead of the defined icon, a white / gray box appears in the notification. I assume that this white box is actually the "normal" app icon which is simply white due to the MD design changes in Nougat. Using an old SDK version (see notes below) solves the problem. 

#### Steps to Reproduce 
1. Use this config to intialize plugin
```
this.push = Push.init({
        android: {
          senderID: "xxx",
          "icon": "icon_small", //or: www/assets/images/icon_small.png
          "vibrate": "true",
          "sound": "true"
        }
      });
```
2. Place file icon_small.png under platforms\android\res\drawables\ and under platforms\android\assets\www\assets\images\
3. Register and send deviceid to server
4. Send notification
5. See that the custom icon is not used / a white box appears

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
7.1.1 (Nougat) 
 
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Nexus 5x

#### Cordova CLI version and cordova platform version
6.4.0
android 6.1.2

#### Plugin version
phonegap-plugin-push 1.9.2 "PushPlugin"

#### Sample Push Data Payload
This is a dump from the array on the php server before sending it to the fcm server:
```
array(6) {
  ["priority"]=>
  string(4) "high"
  ["data"]=>
  array(8) {
    ["title"]=>
    string(11) "Neuigkeiten"
    ["message"]=>
    string(48) "Klicken Sie hier, um die Neuigkeiten zu sehen..."
    ["style"]=>
    string(5) "inbox"
    ["type"]=>
    string(4) "news"
    ["summaryText"]=>
    string(32) "Sie haben %n% Benachrichtigungen"
    ["priority"]=>
    int(1)
    ["sound"]=>
    string(7) "default"
    ["content-available"]=>
    string(1) "1"
  }
  ["notification"]=>
  array(2) {
    ["title"]=>
    string(11) "Neuigkeiten"
    ["body"]=>
    string(48) "Klicken Sie hier, um die Neuigkeiten zu sehen..."
  }
  ["delay_while_idle"]=>
  bool(false)
  ["time_to_live"]=>
  int(0)
  ["registration_ids"]=>
  array(3) {
    [0]=>
    string(152) "ctm6kwGVcfI:APA91bFr_9WpRxAeqXaHnWaZ27CJe6ZpkUttAQvRpFwt3WvF6nvCeFOa7wX_QzdVyay9KtB6MrH6HWNTEEvLN7nltC_n3W3TIWXD5-yLiowk8d_6rfLaLVxpFSngq1A4Y8OIVtyjv3I6"
    [1]=>
    string(152) "eln5eLCfY9I:APA91bE7lNp4B8rUUBVPM5a4xND0RCGX6x3t-Ue1hCMPMP7TgfzNQwQUpe7VBcpghAmYJZkD2NENxXKXmmbP9JT4O6_bIuK7HxjGoaHLnVFokiiIdmtJbHlXwXvs_wdCP3bMRLW01_LP"
    [2]=>
    string(152) "f4h0xXs5Od4:APA91bEzahBclubBDTDQ4UWiys04pfQf_AqBhotbU8YWpAfMyvxRbhuG29Xcski9L6EIC-lK96EN_qEeqHqRAiTRzQcEgD8WqVD7PKn0BR5FGviQq2gtos3eYdkAZw6M2UaDk_qDofT5"
  }
}
```
All notifications are received!

#### Notes ####
- We use ionic 2.0.0
- Putting `<preference name="android-targetSdkVersion" value="20"/>` in the config.xml is a workaround (the app icon then displays in the notification). But this would mean that we have to use the old permission systems which is no real solution for us.
- I have already re-generated the icon file using https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=clipart&source.clipart=ac_unit&source.space.trim=1&source.space.pad=0&name=ic_stat_example and placed the icons in the different drawable folders. Nothing changed. However, the file we used before already worked for a native app on my device and a fallback to the unqualified "drawables" folder should be ok - I guess.
- I verified that the icon file is included in the debug apk, which is deployed to the device

**Comment by macdonst** [comment]
@tfrenken yes, I can confirm it works on Android N. I think the problem is with the payload you are sending. Please try this (basically remove the `notification` array):

```
array(6) {
  ["priority"]=>
  string(4) "high"
  ["data"]=>
  array(8) {
    ["title"]=>
    string(11) "Neuigkeiten"
    ["message"]=>
    string(48) "Klicken Sie hier, um die Neuigkeiten zu sehen..."
    ["style"]=>
    string(5) "inbox"
    ["type"]=>
    string(4) "news"
    ["summaryText"]=>
    string(32) "Sie haben %n% Benachrichtigungen"
    ["priority"]=>
    int(1)
    ["sound"]=>
    string(7) "default"
    ["content-available"]=>
    string(1) "1"
  }
  ["delay_while_idle"]=>
  bool(false)
  ["time_to_live"]=>
  int(0)
  ["registration_ids"]=>
  array(3) {
    [0]=>
    string(152) "ctm6kwGVcfI:APA91bFr_9WpRxAeqXaHnWaZ27CJe6ZpkUttAQvRpFwt3WvF6nvCeFOa7wX_QzdVyay9KtB6MrH6HWNTEEvLN7nltC_n3W3TIWXD5-yLiowk8d_6rfLaLVxpFSngq1A4Y8OIVtyjv3I6"
    [1]=>
    string(152) "eln5eLCfY9I:APA91bE7lNp4B8rUUBVPM5a4xND0RCGX6x3t-Ue1hCMPMP7TgfzNQwQUpe7VBcpghAmYJZkD2NENxXKXmmbP9JT4O6_bIuK7HxjGoaHLnVFokiiIdmtJbHlXwXvs_wdCP3bMRLW01_LP"
    [2]=>
    string(152) "f4h0xXs5Od4:APA91bEzahBclubBDTDQ4UWiys04pfQf_AqBhotbU8YWpAfMyvxRbhuG29Xcski9L6EIC-lK96EN_qEeqHqRAiTRzQcEgD8WqVD7PKn0BR5FGviQq2gtos3eYdkAZw6M2UaDk_qDofT5"
  }
}
```

**Comment by tfrenken** [comment]
@macdonst I can confirm that by omitting the notification array, the custom icon on Android 7 is used! Great, thank you! 

However, removing the notification array leads to iOS not receiving the notification anymore (we use APN via GCM/FCM for iOS). Is there any way to have both systems working properly?

**Comment by macdonst** [comment]
@tfrenken yeah, you will have to segment your notifications. Sending one push to Android devices and another push to iOS devices. I will we could support both with one payload but because of the way the Android OS takes over we have to do it this way. You can read up more on the why here:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

What you'll want to do in your registration event is determine if the device is Android or iOS and let your push notification server know. That way you'll be able to segment your pushes to each platform.

**Comment by tfrenken** [comment]
@macdonst  OK, thank you for the info! As you suggest, I will then determin and send over the platform with the registration event at the server!

**Comment by macdonst** [comment]
@tfrenken also, you can check `cordova.platformId` instead of using the device plugin to figure out what platform you are running on.
