### ISSUE TITLE
Unable to install phonegap-plugin-push in ios app

### ISSUE THREAD

**Issue by hariomtestid** [phonegap/phonegap-plugin-push#1632]
I am new with ionic framework.Currently i am working on ionic ios app. when i install phonegap-plugin-push i am getting error
Failed to install 'phonegap-plugin-push':undefined
Error: /Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)

i have searched it but no solution found yet!

**Comment by macdonst** [comment]
@hariomtestid you are trying to add the plugin to your app as root and CocoaPods will not let you do that.

**Comment by Djinne** [comment]
wow macdonst, you don't say

**Comment by sayWhut** [comment]
You also might need to update CocoaPods

**Comment by Djinne** [comment]
I solved this with the chown command as it was a permission issue where the command was being broken else where....sudo simply wasn't enough
