### ISSUE TITLE
Can't show large icon

### ISSUE THREAD

**Issue by luiggisenna** [phonegap/phonegap-plugin-push#1636]
I know there are many issues about the same topic, but couldn't find any help...

### Expected Behaviour
That is the notification I'm receiving on my app (console.log):
{
   "image":"http://www.site.com/img/icon.png",
   "sound":"default",
   "title":"Title example",
   "message":"Msg example",
   "additionalData":{
        "google.message_id":"XXXX",
        "coldstart":false,
        "collapse_key":"XXXX",
        "foreground":true
   }
}

I'm expecting to see icon.png as a large icon on my notification.

Only used default settings on phonegap-plugin-push coding.

Already tried to use "image":"icon" (expecting to see the same app icon on my notification icon), but with no results.

### Actual Behaviour
Can't see the large icon.

I'm also trying to change "sound" to "ringtone", but it keeps ringing default sound. Know it is another issue, but maybe it's a related issue...

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
I'm using Android 6.0 on my phone.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Motorola XT1078.

#### Cordova CLI version and cordova platform version
    cordova --version                                    # 6.5.0
    cordova platform version android                     #6.1.2

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.9.4

**Comment by macdonst** [comment]
@luiggisenna what does the payload you send to the device look like?

**Comment by luiggisenna** [comment]
Thanks for your prompt reply!

  $payload = array
  (
          'sound'         => 'default',
          'title'         => $title,
          'body'          => $message,
          'icon'          => 'push_icon',
          'color'         => '#7f3390',
          'image'         => 'http://www.site.com/img/icon.png',
  );

  $fields = array
  (
          'registration_ids'      => $deviceTokens,
          'notification'          => $payload
  );

  $headers = array
  (
          'Authorization: key=' . GCM_API_ACCESS_KEY,
          'Content-Type: application/json'
  );

  $ch = curl_init();
  curl_setopt( $ch,CURLOPT_URL, 'https://gcm-http.googleapis.com/gcm/send' );
  curl_setopt( $ch,CURLOPT_POST, true );
  curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
  curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
  curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
  curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fields ) );
  $result = curl_exec($ch );
  curl_close( $ch );

My notification have icon = push_icon on it and I could change the icon color.

I only can't use the large image on it.

If I change sound to ringtone, it keeps ringing default sound.

**Comment by macdonst** [comment]
@luiggisenna please read the docs:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

You need to use `data` not `notification`. Try the below:

```
$payload = array
(
'sound' => 'default',
'title' => $title,
'body' => $message,
'icon' => 'push_icon',
'color' => '#7f3390',
'image' => 'http://www.site.com/img/icon.png',
);

$fields = array
(
'registration_ids' => $deviceTokens,
'data' => $payload
);

$headers = array
(
'Authorization: key=' . GCM_API_ACCESS_KEY,
'Content-Type: application/json'
);

$ch = curl_init();
curl_setopt( $ch,CURLOPT_URL, 'https://gcm-http.googleapis.com/gcm/send' );
curl_setopt( $ch,CURLOPT_POST, true );
curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fields ) );
$result = curl_exec($ch );
curl_close( $ch );
```

**Comment by luiggisenna** [comment]
With "data" I dont receive any notification at all... I receive a success message from GCM when I send the payload, but couldnt receive anything on my device... I've checked in console.log.

**Comment by luiggisenna** [comment]
Actually... after many tests I could finally receive the large icon on my device... but with a huge delay and with no idea of what i have changed on my code. I have just sent notifications with all possible coding combinations and with different messages on it and will wait to see if I receive any of them (so I will know which configuration I have used on the succesfully notification).

I will let you know if I reach to any conclusion. But anyway, when I use "notification" on payload I receive the message instantly. If you have any other idea of what can be happening, let me know.

**Comment by macdonst** [comment]
@luiggisenna as I've explained in the docs for this plugin using `notification` will result in the Android OS taking over and the plugin code will never get called. Use `data` to send the information.

If you are having trouble getting `data` notifications to show up I suggest you try with only the title and body properties and slowly build onto the payload to see what is causing the problem. It could be an issue where the network is slow downloading your remote image.

Also, collecting logs using `adb logcat | grep PushPlugin` is super useful in debugging.

**Comment by luiggisenna** [comment]
Thanks for your advice! I'll follow these steps and let you know!

**Comment by macdonst** [comment]
@luiggisenna any update?

**Comment by luiggisenna** [comment]
@macdonst I had to focus on app launching and just skipped large icons... Will leave to next version. So I couldn't debug to check out what's going on... But I'll give you an update as soon as possible? Do you want to close the issue?

**Comment by macdonst** [comment]
@luiggisenna nope, that's cool. We can leave it open. I'm just reviewing issues after a week off.

**Comment by macdonst** [comment]
Closing for now. @luiggisenna comment if you still have the issue.
