### ISSUE TITLE
App refreshes after (un-)subscribe

### ISSUE THREAD

**Issue by palpatin0** [phonegap/phonegap-plugin-push#1637]
### Expected Behaviour

The app subscribes or unsubscribes for the topic.

### Actual Behaviour

When push.subscribe/push.unsubscribe is called after a button click, the app shows a white screen and refreshes after a few minutes.

#### Platform and Version 

Android 6.0

#### What device vendor

HTC

#### Cordova CLI version and cordova platform version

6.5

#### Plugin version

2.0

#### Sample Code that illustrates the problem

http://pastebin.com/gLKJiWr0

**Comment by macdonst** [comment]
@palpatin0 I can't reproduce this issue. Can you provide some more details?

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
