### ISSUE TITLE
When Does The Device Token Change For APNS and FCM

### ISSUE THREAD

**Issue by dmarcus1** [phonegap/phonegap-plugin-push#1638]
I get that the device token gets stored in localstorage and that the app checks to see if the registrationid changed using the code below. What are all the scenarios that device token could change? Could the device token change if I don't quit out of the app, minimize the app, and then bring the app back up again?

var oldRegId = localStorage.getItem('registrationId');
        if (oldRegId !== data.registrationId) {
            // Save new registration ID
            localStorage.setItem('registrationId', data.registrationId);
            // Post registrationId to your app server as the value has changed
        }

**Comment by macdonst** [comment]
@dmarcus1 the registration ID can change at any time that APNS or FCM/GCM feel like refreshing the tokens. However, that is pretty infrequent. If the app is running you'll get a registration event. If your app is not running then you'll get the updated registration ID then next time it starts.
