### ISSUE TITLE
Support for cordova-plugin-badge to retrive badge count 

### ISSUE THREAD

**Issue by rastafan** [phonegap/phonegap-plugin-push#1639]
### Expected Behaviour
[cordova-plugin-badge](https://github.com/katzer/cordova-plugin-badge) should be able to retrive the badge number set by a push notification via phonegap-plugin-push. 

### Actual Behaviour
[cordova-plugin-badge](https://github.com/katzer/cordova-plugin-badge) can not retrive it.

### Reproduce Scenario (including but not limited to)
App with both phonegap-plugin-push and cordova-plugin-badge

#### Steps to Reproduce 
1. set badge number via push notification
2. using cordova-plugin-badge get/increase/decrease wont use the correct badge count
3. set badge number via cordova-plugin-badge
4. using cordova-plugin-badge get/increase/decrease works correctly

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Any Android version supporting badges

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Any device supporting badges

#### Cordova CLI version and cordova platform version
Cordova: 6.5.0
Android Platform: 6.1.2

#### Plugin version
phonegap-plugin-push : 1.10
cordova-plugin-badge : 0.7.4

This looks like a problem on the cordova-plugin-badge side, but it is in fact a lack of support for it on this side. 
What happens is, this plugin uses ShortcutBadger in order to set the badge count, but it has no "get" method to read it back (as far as i know).
On the other end, cordova-plugin-badge uses SharedPreferences to store and retrieve his badge count, reading and writing to it.

We managed to support that behaviour by adding a small piece of code that writes to SharedPreferences whenever the badge count is set. You can review it [here](https://github.com/rastafan/phonegap-plugin-push/commit/f60955c24dd454d239badf398c6213f849573933).

Is there any other way to do it? Should we make a pull request?

**Comment by macdonst** [comment]
@rastafan what's wrong with using `PushPlugin.getApplicationIconBadgeNumber()`?

**Comment by rastafan** [comment]
Isn't that available on iOS only?

The point is that ShortcutBadger doesn't have any method to retrive the badge numbr set on the application icon, so the only way (afaik) is keeping count of it manually on android. 
The iOS part works fine as it is right now.

**Comment by macdonst** [comment]
@rastafan right, sorry busy day yesterday and I didn't fully express myself. So there is the code that your suggested which should end up in a PR then you should implement `PushPlugin.getApplicationIconBadgeNumber()` on Android to read that value. Make sense?

**Comment by rastafan** [comment]
Oh that's right, i didn't think about that. I'll try that and then report here (or send a PR directly). Thanks a lot.

**Comment by macdonst** [comment]
@rastafan awesome, thanks for looking into this and sending a PR

**Comment by rastafan** [comment]
[Added Pull Request](https://github.com/phonegap/phonegap-plugin-push/pull/1644)

Only thing we noticed is, if you have a badge count set before this PR, the plugin wont be able to retrieve it because there is no SharedPreference containing the badge count. This results in a badge count of 0 until a new notification with badge count arrives. I don't think there is any way around this, unfortunately.

**Comment by macdonst** [comment]
@rastafan PR reviewed and changes requested.
