### ISSUE TITLE
How do I cancel a notification from action button callback

### ISSUE THREAD

**Issue by grrobinson** [phonegap/phonegap-plugin-push#164]
Hello,

I am using phonegap-push-plugin for my application.
On some user action, a notification is sent to another user with 2 action buttons.

Callback for this action buttons are triggered properly but notification is not removed from the stack. So when another user sends a new notification with these two buttons, action callback is still ran on first notification.

My question is : is it possible to cancel the first notification on action callback?
If not, is there another way to force second notification to be taken into account?

Thanks for your help.

**Comment by macdonst** [comment]
@grrobinson what version of the plugin are you using? That should have been fixed with 1.2.2 but if not let me know.

**Comment by grrobinson** [comment]
@macdonst I was using v1.2.0. I changed for v1.2.2 and it works perfectly.
Thanks a lot for your help. I'm closing this issue.
