### ISSUE TITLE
Operability with other Cordova plugins which handle push notifications

### ISSUE THREAD

**Issue by jtreanor** [phonegap/phonegap-plugin-push#1640]
I am one of the maintainers of [Intercom's Cordova plugin](https://github.com/intercom/intercom-cordova). By far the most common issue that our users encounter is that when they install `phonegap-plugin-push`, push notifications don't work correctly. On Android this leads to duplicate notifications and on iOS it can lead to Intercom not opening notifications.

Our solution to date (which is not ideal) has been to provide a fork of `phonegap-plugin-push` that works around these issues (Available here: https://github.com/intercom/phonegap-plugin-push). 

However, I believe that it would be in the interest of the community for `phonegap-plugin-push` to be capable of existing alongside other plugins that use push notifications without interference. This issue is not exclusive to Intercom but applies to all other plugins that handle push notifications.

### Expected Behaviour

Push plugin should co-exist with other plugins which use push notifications.

### Actual Behaviour

Installing `phonegap-plugin-push` alongside other plugins that use push leads to duplicate push notifications and other unexpected behaviour.

#### Steps to Reproduce 

1. Install `phonegap-plugin-push`.
2. Install `cordova-plugin-intercom`.
3. Receive an Android push notification from Intercom. It will be displayed twice (built by both plugins).

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Any

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Any

#### Cordova CLI version and cordova platform version

Any

#### Plugin version

Any

#### Sample Code that illustrates the problem

The changes that were necessary to make in order to work around the issue can be seen [here](https://github.com/phonegap/phonegap-plugin-push/compare/master...intercom:master).

#### Logs taken while reproducing problem

N/A

Please let me know if I can provide any more detail on the issue described here.

**Comment by jtreanor** [comment]
Just to add a little more context here: The underlying issue is that `phonegap-plugin-push` assumes it is responsible for handling all push notifications received by the app.

**Comment by macdonst** [comment]
@jtreanor yeah, I'd be happy to have interoperability between the two plugins and since you know your plugin better than I do pull requests are always welcome.

One recent change which was released as part of 1.10.0 was for the push plugin to only show the notification if the sender ID matched the one set at init time. See: https://github.com/phonegap/phonegap-plugin-push/commit/a0d51e54aac39b8c58e4c67080f174c0228947c9

Does this help work around your issue?

**Comment by jtreanor** [comment]
Thanks @macdonst,

That is certainly a good start, though I suspect it will not solve the full issue. I will dig a little deeper into this to see what solutions I can come up with and open a PR with some changes.

**Comment by macdonst** [comment]
@jtreanor what is the root cause of the double notifications in the shade? I feel if the push plugin and the intercom plugin are using different sender ID's we should be most of the way there.

**Comment by jtreanor** [comment]
@macdonst The duplicate push notifications were caused by `onMessageReceived` in `GCMIntentService` as you have suggested. However, due to the fact that there can only be one `GcmLisenterService` in an app, it must be passed to Intercom from there rather than just ignored.

Additionally, it is quite common for our customers to use the same sender ID for Intercom and the push plugin. We could recommend against this but the problem would resurface when using FCM (since its only possible to use one `google-services.json` file).

I will ask my colleague who is more familiar with this to clarify the detail tomorrow. There is some detail about how Intercom interacts with other push providers on Android [here](https://developers.intercom.com/docs/android-gcm-push-notifications#section-step-7-using-intercom-with-other-gcm-setups-optional).

My current thought is that `phonegap-plugin-push` could be extended so that other plugins could provide some sort of callback to it for handling their notifications.

**Comment by macdonst** [comment]
@jtreanor the simplest and hackiest thing to do would be to implement 'intercomPushClient.isIntercomPush(message)` inside of `onMessageReceived` of `GCMIntentService`. There is probably some key we can depend on in the message object to identify the incoming push as an Intercom one.

The way that you suggest leaves us open for expansion as we could add a way for other plugins to register push handlers with the push plugin. Then let the handler determine if the message should be acted upon or passed on to the default push handling.

Regardless, we should talk more about supporting your use case.

**Comment by jtreanor** [comment]
@macdonst Yeah, that certainly would be the most straightforward. It is easy to identify an Intercom push.

I experiment with a few options and loop you in on what I come up with.

**Comment by macdonst** [comment]
@jtreanor sounds good, happy to add it to the plugin.

**Comment by jtreanor** [comment]
I've done quite a bit of digging here and have managed to work around the conflict on our side. For you interest, the changes are [here](https://github.com/intercom/intercom-cordova/issues/166).

Thanks for being welcoming and helpful in this issue.

**Comment by macdonst** [comment]
@jtreanor alright cool. Glad you worked around it but happy to make changes on this side if you change your mind. I saw in the commit you are using reflection on Android which is too bad you had to go that route.

**Comment by jtreanor** [comment]
@macdonst We are not using reflection in the solution (though we do use `Class.forName()`). I will continue to keep the plugin in mind in future to see if there are any desirable changes to be made.

**Comment by macdonst** [comment]
@jtreanor my mistake, I only looked quickly while on vacation last week 😎
