### ISSUE TITLE
[IOS] [build] Apple Mach-O Linker Error Group: linker command failed with exit code 1

### ISSUE THREAD

**Issue by meliguter** [phonegap/phonegap-plugin-push#1641]
### Expected Behaviour
It should build the App

### Actual Behaviour
It throws this error when trying to build the app in xcode
> Apple Mach-O Linker Error Group

### Reproduce Scenario (including but not limited to)
cordova plugin list:
com.appsflyer.phonegap.plugins.appsflyer 4.0 "AppsFlyer"
cordova-custom-config 2.0.3 "cordova-custom-config"
cordova-plugin-console 1.0.4 "Console"
cordova-plugin-device 1.1.3 "Device"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-firebase 0.1.19 "Google Firebase Plugin"
cordova-plugin-google-analytics 1.6.0 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 1.7.0 "InAppBrowser"
cordova-plugin-splashscreen 4.0.2 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.6 "SocialSharing"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.10.0 "PushPlugin"

#### Steps to Reproduce 
Open Project.xcworkspace
Product -> Build

#### Platform and Version
iOS (anyone)
Xcode Version 8.2.1 (8C1002)

#### Cordova CLI version and cordova platform version

    cordova --version 6.4.0
    cordova platform version android  4.3.0

#### Plugin version

    1.10.0

#### Logs taken while reproducing problem
Details of the files with duplicate symbols. Example:
duplicate symbol _OBJC_METACLASS_$_GtalkGtalkCoreRoot in:
    /Users/app/platforms/ios/Pods/GoogleCloudMessaging/Libraries/libGcmLib.a(GtalkCore.pb.o)
    app/Plugins/cordova-plugin-firebase/FirebaseMessaging.framework/FirebaseMessaging(GtalkCore.pb_ef52fce5cdce4f5a45bcf431c19c98ab.o)

> ld: 33 duplicate symbols for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by macdonst** [comment]
@meliguter you can't use `cordova-plugin-firebase` and `phonegap-plugin-push` together as will result in this error. Look at v2.0.0-rc2 release of this plugin for FCM support.

**Comment by pjwl33** [comment]
Are there any plugins from this list that would be causing a similar issue?

```
com.bez4pieci.cookies 0.0.1 "Cookies"
com.mbppower.camerapreview 0.0.8 "CameraPreview"
com.phonegap.plugin.statusbar 1.1.0 "StatusBar"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.3-dev "Device"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-indexeddb-async 0.0.1 "cordova-plugin-indexeddb-async"
cordova-plugin-network-information 1.1.0 "Network Information"
cordova-plugin-queries-schemes 0.1.1 "App Queries Strings"
cordova-plugin-screen-orientation 1.4.2 "Screen Orientation"
cordova-plugin-splashscreen 4.0.2-dev "Splashscreen"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-transport-security 0.1.2 "App Transport Security"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-webserver 1.0.3 "CordovaWebServer"
cordova-plugin-whitelist 1.3.1 "Whitelist"
jp.wizcorp.phonegap.plugin.wizUtilsPlugin 1.0.1 "Wizard Utils Plugin"
mobi.pdf417.Pdf417Scanner 1.1.5 "Pdf417Scanner"
org.hygieiasoft.cordova.uid 1.1.0 "UID"
org.pluginporo.mqtt_plugin 0.0.1 "MQTT Plugin"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
uk.co.workingedge.phonegap.plugin.istablet 1.1.1 "Is Tablet"
```

**Comment by fredgalvao** [comment]
@pjwl33 Get the name of the binary that the build process is telling you as duplicate and search for it on your `plugins` folder.

Something like this:

```
Details of the files with duplicate symbols. Example:
duplicate symbol OBJC_METACLASS$_GtalkGtalkCoreRoot in:
/Users/app/platforms/ios/Pods/GoogleCloudMessaging/Libraries/libGcmLib.a(GtalkCore.pb.o)
app/Plugins/cordova-plugin-firebase/FirebaseMessaging.framework/FirebaseMessaging(GtalkCore.pb_ef52fce5cdce4f5a45bcf431c19c98ab.o)

> ld: 33 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

You would then run (if on linux/mac):
`grep -REi 'GoogleCloudMessaging|libGcmLib|FirebaseMessaging' ./plugins`
at the root of your cordova project.

That would try to find things inside your plugins that could be referencing either the `FirebaseMessaging` framework directly, the `GoogleCloudMessaging` dependencies directly, or the binary `libGcmLib` directly.

This plugin (phonegap-plugin-push), since 1.9.0, specifies its GCM/FCM dependencies through a cocoapod framework tag through cordova, so that it can coexist any other plugin doing the same. If an outdated plugin tries to do it manually, conflicts like these will rise.

**Comment by pjwl33** [comment]
@fredgalvao thank you very much Fred. I went through the logs of the duplicate symbol plugins and removed them and rebuilt. the plugins had different version or were updated and no-longer needed.

thanks for the advice and solution.

**Comment by fredgalvao** [comment]
I'm glad you managed it.

**Comment by Medesko** [comment]
Hi, 

When I installe phonegap-plugin-push in my ionic cordova project and build with xcode it get this message:

Apple Mach-O Linker Error Group 
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Here is my config : 
`global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 1.3.12
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.0

System:

    ios-deploy : 1.9.0 
    ios-sim    : 5.0.13 
    Node       : v6.11.3
    npm        : 3.10.10 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b `

`
*** LOCAL GEMS ***
cocoapods (1.3.1)
`
Plugin list :
[https://image.ibb.co/hvdUUF/Voila_Capture_2017_09_09_05_59_43_PM.png](url)

**Comment by fredgalvao** [comment]
@Medesko The image you linked doesn't exist. Also, you didn't provide the full log of the error.
```
Apple Mach-O Linker Error Group
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
The above doesn't say anything about the error.

**Comment by mglmgl** [comment]
**Important (since cordova-ios 4.5.0):**

Please note, that the cordova plugin cordova-plugin-console is now part of the cordova-ios platform. So if you're using cordova-ios@4.5.0 or higher absolutely remove cordova-plugin-console!

`cordova plugin rm cordova-plugin-console`

This concerns plain cordova apps and ionic apps as well. 
Further information: [Console-Plugin on GitHub](https://github.com/apache/cordova-plugin-console/blob/master/README.md)
