### ISSUE TITLE
Error trying to build v2.0.0-rc2 in Phonegap Build

### ISSUE THREAD

**Issue by LlamaloX** [phonegap/phonegap-plugin-push#1642]
### Expected Behaviour

Project to be built correctly using v2.0.x branch, just as it is built correctly when using master branch.

### Actual Behaviour

BUILD FAILED

Total time: 1.126 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script '/project/phonegap-plugin-push/employee-push.gradle' line: 12

* What went wrong:
A problem occurred evaluating root project 'project'.
> Plugin with id 'com.google.gms.google-services' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.5.0
    cordova platform version android           6.1.2

#### Plugin version

     phonegap-plugin-push   v2.0.0-rc2 (FCM Branch)

**Comment by jcesarmobile** [comment]
v2.0.x is not supported on Phonegap build as it has two hooks for copying some needed files and hooks don't work on Phonegap build.

**Comment by grapemix** [comment]
Will v2.0.x work in the future on phonegap build? I just want to know the error is temporary or permanent.
Thanks.

**Comment by jcesarmobile** [comment]
Yeah, it will be supported in the future, Cordova is adding `resource-file` tag in the config.xml that will allow to copy the FCM required files to the project without using hooks.

**Comment by eddOrnelas** [comment]
Care to explai how to use `resource-file` tag?

**Comment by jcesarmobile** [comment]
`resource-file` tag is explained in installation docs https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements
It requires cordova 7.x.x or greater
