### ISSUE TITLE
iOS push sound not working.

### ISSUE THREAD

**Issue by progresivoJS** [phonegap/phonegap-plugin-push#1643]
### Expected Behaviour
When push arrives, custom sound rings.

### Actual Behaviour
But its sound is just default.

### Reproduce Scenario (including but not limited to)

I use GCM for ios.
My payload code is following.

```json
{
    "notification":
        {
            "title":"notification",
            "body":"message is arrived!",
            "content_available":true,
            "sound": "general.caf"
        },
    "priority":"high",
    "to":"/topics/111"
}
```

But Only default sound is ringing.... 😭 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ios 9.2.1

#### Cordova CLI version and cordova platform version
cordova CLI 6.4.0

#### Plugin version
1.9.0

**Comment by macdonst** [comment]
@progresivoJS try it with out the '.caf' extension.

**Comment by progresivoJS** [comment]
@macdonst I tried, but no effect.. same situation.

**Comment by progresivoJS** [comment]
![2017-03-22 5 01 23](https://cloud.githubusercontent.com/assets/22091806/24187597/028c9dce-0f21-11e7-9b0c-e22cdb8812d2.png)

I solve this problem.

reference : http://developer.boxcar.io/blog/2014-10-08-notification_sounds/

**Comment by fredgalvao** [comment]
@progresivoJS  Can you tell us exactly what in that screenshot indicates what you did to fix it? It'll be valuable to add it to the docs if it's something that applies to everyone.

**Comment by progresivoJS** [comment]
@fredgalvao In my research, just adding *.caf files to Xcode Project not necessarily guarantees copy bundle resources shown above screenshot.

So, after adding *.caf files to the root of project, assure that *.caf files added to [Build Phases > Copy Bundle Resources]. If these are not added, add *.caf files to [Build Phases > Copy Bundle Resources.]
