### ISSUE TITLE
Register to push after refused

### ISSUE THREAD

**Issue by Lulun10** [phonegap/phonegap-plugin-push#1645]
Hi,

When I load the app for the first time I have the popup for push register. How to register after if the user refuses at first? A call to PushNotification.init in my notification page does not show the window.

I'm on IOS 9.3.5 with cordova 6.5.0 and last version of plugin push.

Thanks.

**Comment by macdonst** [comment]
@Lulun10 this is how you'd do it:

https://developer.apple.com/library/content/technotes/tn2265/_index.html#//apple_ref/doc/uid/DTS40010376-CH1-TNTAG42
