### ISSUE TITLE
Can be plugin v1.x compatible with cordoba-plugin-firebase?

### ISSUE THREAD

**Issue by xmellado** [phonegap/phonegap-plugin-push#1647]
Hi,

I  have push messages in my Ionic 2 app using GCM for Android with this plugin and I want to use Firebase analytics using [cordova-plugin-firebase](https://github.com/arnesson/cordova-plugin-firebase). When both plugins are installed Android platform cannot be build.

For the time being, I am not planning to move my push messaging service to Firebase and I want to stick to version 1.x.

Can both plugins be used at the same time?

Regards,
Xavi

### Expected Behaviour

I want to install in Ionic 2 this plugin and cordoba-plugin-firebase,  and compile the Android platform.

### Actual Behaviour

When both plugins are installed in a Ionic 2 project, Android platform build ends with an error:
```
Error: /Volumes/Data/xavi/work/code/ionic/incubapps/just-today-ionic/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeDebugResources'.
> /Volumes/Data/xavi/work/code/ionic/incubapps/just-today-ionic/platforms/android/res/values/strings.xml: Error: Found item String/google_app_id more than one time
```

platforms/android/res/values/strings.xml:

```
<?xml version='1.0' encoding='utf-8'?>
<resources>
    <string name="app_name">Just Today</string>
    <string name="launcher_name">@string/app_name</string>
    <string name="activity_name">@string/launcher_name</string>
    <string name="google_app_id" translatable="false">XXXXXXXX</string>
    <string name="google_app_id">1:XXXXXXXX:android:XXXXXXXX</string>
    <string name="google_api_key">YYYYYYYY</string>
</resources>
```

The string `google_app_id` is defined twice and causes an error. I'm not an expert and the problem can much deeper and complex, but maybe if phonegap-plugin-push v1.x uses a name like `gcm_app_id` the problem is solved.  

#### Steps to Reproduce 

1) Install latest Ionic CLI 2.2.1.
2) Install Cordova 6.5.0.
3) Create a brand new project with: `ionic start --v2 myApp tabs`.
4) Install `cordoba-plugin-firebase` plugin.
5) Install `phonegap-plugin-push` plugin.
6) Build and run with `ionic run android`.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 5.x and up.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Not relevant.

#### Cordova CLI version and cordova platform version

Ionic info:
```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002
```
cordova platform version android:
```
Installed platforms:
  android 6.1.2
  browser 4.1.0
  ios 4.3.1
```

#### Plugin version

phonegap-plugin-push 1.10.0 "PushPlugin"
cordova-plugin-firebase 0.1.19 "Google Firebase Plugin"

**Comment by macdonst** [comment]
@xmellado sorry, I won't be back porting the changes to the 1.x stream that get rid of the `google_app_id`. You'll have to move to the 2.x stream. Even if we did get rid of the `google_app_id` there is a good chance there would be other conflicts with regards to the GCM and FCM libraries. Furthermore both the push plugin and firebase plugin would both be trying to handle the notifications which would cause issues in your app.

What analytics functions do you want to use?

**Comment by xmellado** [comment]
Hi,
@macdonst I would like to use only the function [logEvent()](https://github.com/arnesson/cordova-plugin-firebase#logevent) from the `cordoba-firebase-plugin`, I don't need anything else. I need to log a set of custom events that we have defined to track user's navigation in our app.

I have tried to import directly Firebase as web project (JavaScript) in Ionic 2, but [analytics](https://firebase.google.com/docs/analytics) are not available for web projects.

Regards,
Xavi

**Comment by performatric** [comment]
I tried to use the version 1.x.x but is not working with Firebase plugin. Ok. But the version 2.x.x-rc4 give me this error:

Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script 'C:\app\platforms\android\phonegap-plugin-push\android-push.gradle' line: 12

* What went wrong:
A problem occurred evaluating root project 'android'.
> Failed to apply plugin [id 'com.google.gms.google-services']
   > For input string: "+"

Please, I need help!

**Comment by morariu** [comment]
@performatric if you browse the issues you'll see that that is not fixed yet, hopefully on the next release.

**Comment by HamzaLJ** [comment]
I am having the same issue with rc5, when it'll be solved ?
