### ISSUE TITLE
$rootScope.$on('cloud:push:notification', function(event, data) not triggering on push

### ISSUE THREAD

**Issue by gagansaini2** [phonegap/phonegap-plugin-push#1648]
### Actual Behaviour

In my App, device is registered with ionicPush when a user log in into the app, so when a notification came $on triggers as expected,but when i close the app and restart it  again $on function stops triggering(but i receives the pushes in my notification shade). So, to trigger push i have to log out ang log in to the app again without closing it.

### Note:

This is my config code, and i want to use  "forceShow": true, as it is necessary!

$ionicCloudProvider.init({
    "core": {
      "app_id": ""
    },
    "push": {
      "sender_id": "",
      "pluginConfig": {
        "android": {
          "iconColor": "#343434",
          "forceShow": true
        }
      }
    }
  });

### Versions 
ionic : 2.2.1
cordova : 6.5.0
android : 6.1.2
phonegap-plugin-push "PushPlugin" :  1.10.0
@ionic/cloud : ^0.15.1
bluebird : ^3.4.7

**Comment by fredgalvao** [comment]
If `log out ang log in to the app again without closing it` solves it, certainly both the root problem and the solution to it is in your login/logout process. I'm fairly sure the plugin is not the one at fault here.

If you can reproduce it with a sample app or code, it'll help identify and fix it, if it is indeed an issue with the plugin.

**Comment by gagansaini2** [comment]
@fredgalvao thanx for the reply,,,

I dont know exactly where the problem is,, but i solved my problem. As $on is not triggering after i restart the app,, so i used **$ionicPush.register()** in my app.run function,, so that the device would get registered every time the app starts.

So i think the problem is with the device registration,, i think when app is get closed and started again **$ionicPush** forgots the token (but the token is saved at localStorage until unregister function gets called) which lead to my problem.

As i dont know this is right solution to problem,,but this fixes it !!
