### ISSUE TITLE
Question: Device tokens

### ISSUE THREAD

**Issue by weneverfail** [phonegap/phonegap-plugin-push#165]
Just a quick question as I've been stuck on this for a while, I can't seem to find any info about obtaining an iOS device token in the documentation or the examples, am I missing something? A short example would be greatly appreciated.

Thanks in advance

**Comment by macdonst** [comment]
@weneverfail if you setup your environment so it builds with push support the 'registration' even with be called with the iOS device token.

http://code.tutsplus.com/tutorials/setting-up-push-notifications-on-ios--cms-21925

**Comment by weneverfail** [comment]
Thanks for the quick response @macdonst!
Quick question, "if you setup your environment so it builds with push support". Does the plugin not provide any means of setting this up? I have to dive into the objective-c files in xCode and add code myself?

**Comment by macdonst** [comment]
@weneverfail The plugin handles all the Objective-C stuff but you still need to register your app with Apple so you can get the correct certificates. Take a look at steps 4 and 5 of the tutorial I linked to.

**Comment by weneverfail** [comment]
@macdonst Yes I understand that, already had it all set up until I received a deprecation warning from PushPlugin. So the following:

```
push.on('registration', function(data) {
    // data.registrationId
});
```
Is registrationId equal to the device token?

**Comment by xavianaxw** [comment]
Yes @weneverfail . data.registrationId is your deviceToken

**Comment by weneverfail** [comment]
Thanks @xavianaxw and @macdonst for your help.
