### ISSUE TITLE
i got wrong registeration id sometimes on my server

### ISSUE THREAD

**Issue by alaa-alshamy** [phonegap/phonegap-plugin-push#1650]
some times i got wrong registeration id on my server, and that's causing the GCM to return "InvalidRegistration" when trying to send notification to that id 

in general cases i got long ids about 152 length and that's right ids , but some times i got about 64 length id and it's Seemingly apns id not GCM

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by alaa-alshamy** [comment]
ok np you are right , i will make a new issue because seemingly i can't reopen this
