### ISSUE TITLE
Android build failure

### ISSUE THREAD

**Issue by rollsroyc3** [phonegap/phonegap-plugin-push#1651]
I am having trouble building Android with this plugin, here is the failure error i get:

https://www.dropbox.com/s/bdshld9ehmtfua2/Screenshot%202017-03-25%2009.40.05.png?dl=0

I found some closed issues relating to this but not sure they help exactly. Any advice on what I am missing here?

https://github.com/phonegap/phonegap-plugin-push/issues/572

**Comment by rollsroyc3** [comment]
Also looking at the installation documentation I need 'Android Support Library version 23 or greater' but my ADM only lists 21.0.2 as the latest, not sure why I cannot update to the latest.

https://www.dropbox.com/s/930kzdy4e0j2cxr/Screenshot%202017-03-25%2009.44.23.png?dl=0

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
