### ISSUE TITLE
Default behavior of Stacking notifications isn't the same as the fcm

### ISSUE THREAD

**Issue by mazyvan** [phonegap/phonegap-plugin-push#1652]
### Expected Behaviour
Non-collapsible messages

### Actual Behaviour
Collapsible messages

### Reproduce Scenario (including but not limited to)
Use this plugin

#### Steps to Reproduce 
..
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
All
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Any
#### Cordova CLI version and cordova platform version
doesn't matters

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.6.0

#### Sample Push Data Payload
```
var message = {
  to: "/topics/cars",
  priority: 'high',
  data: {
    message: 'supercar',
    sound: 'default',
    title: 'Cars',
    priority: 2
  }
};
```

This causes a lot of issues because we are trying to follow the [official fcm docs](https://firebase.google.com/docs/cloud-messaging/concept-options#collapsible_and_non-collapsible_messages) that basically says 

> A non-collapsible message denotes that each individual message is delivered to the device. A non-collapsible message delivers some useful content, as opposed to a "ping" to the mobile app to contact the server to fetch data. Messages are non-collapsible by default except for notification messages, which are always collapsible. 

I think the default behavior must to be changed

**Comment by macdonst** [comment]
@mazyvan sounds valid. I'll look at it in the 2.0.0 branch as that would be a change to behaviour which should only be done during a major version bump.

**Comment by macdonst** [comment]
@mazyvan the docs that you link to with regards to collapsible & non-collapsible messages deal with the server side of FCM not the client side.

_A collapsible message is a message that may be replaced by a new message if it has yet to be delivered to the device._

Basically, FCM will attempt to deliver all non-collapsible messages but if you send a collapsible message with some data and then send a second collapsible message with some new data and the first has not been delivered to the device then only the 2nd message will be delivered.
