### ISSUE TITLE
i got wrong registration ids sometimes on my server

### ISSUE THREAD

**Issue by alaa-alshamy** [phonegap/phonegap-plugin-push#1653]
### Expected Behaviour
I should always got valid registration id

### Actual Behaviour
Sometimes i got short ids about 64 length and seemingly it's apns id 
And Sometimes i got "blacklisted"

That's mean the push.on('registration') firing even if status of registration is not success and give us wrong id because simply i got the value of "data.registrationId" that coming from event and send it to my server

### Reproduce Scenario (including but not limited to)
I don't know because it's not happened in most cases and i actually figured it from my server
some small cases the users has short ids or "blacklisted" string and when i am trying to send notification to them the GCM return "InvalidRegistration"

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
I got short Ids from Ios platform
and i am not sure about "blacklisted"  but i think it's in Android

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
no info sorry 

#### Cordova CLI version and cordova platform version
Cordova cli version : 6.4.0
Cordova ios version : 4.3.1
Cordova android version: 6.1.1

#### Plugin version
1.9.2

#### Sample Push Data Payload
bug not related with push data payload

#### Sample Code that illustrates the problem
no thing i can provide here sorry 

#### Logs taken while reproducing problem
no thing here also because it's not happened in most cases

**Comment by AndreVicenteW** [comment]
It was happend in my app. I had to clean app data to generate a new ID and see that push works. So I put im my code:

               ```
push.unregister(function () {
                    console.log('success unregister');
                    //call init again
                }, function () {
                    console.log('error unregister');
                });
```

**Comment by alaa-alshamy** [comment]
@AndreVicenteW  
but actually it happen in my client's devices, and i just figured it out from my server. so how can i know if i got valid id or not from client side ? so i can then call "unregister and init" again?

**Comment by AndreVicenteW** [comment]
I didn't find way to check, so everytime that user opens the app I unregister the old Id and create a new.
There is a issue similar here https://github.com/phonegap/phonegap-plugin-push/issues/927#issuecomment-235618880

**Comment by macdonst** [comment]
@alaa-alshamy if you get `blacklisted` as a registration ID then you really shouldn't try to send a notification to the that ID. Not sure how to help you without some logs or a reproduction scenario.

**Comment by alaa-alshamy** [comment]
thanks for ur reply @AndreVicenteW , @macdonst 

@macdonst 
i thought maybe u can find a way to trigger "error" event instead of "registration" in those cases that the registration ID not valid 

i mean just successful cases should fire "registration" event

**Comment by macdonst** [comment]
@alaa-alshamy I can only respond with what Apple/Google give me. sorry
