### ISSUE TITLE
App crashes when lanching same as issue #1588

### ISSUE THREAD

**Issue by sid180** [phonegap/phonegap-plugin-push#1659]
### Expected Behaviour
The application crashes immediately after the splash screen.

###Sdk information 
play-service-gcm 10.2.1
Android support library : 23.2.1
Android support repository : 47
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
android , version 7.0
#### (Android) What device vendor 

samsung  s5

#### Cordova CLI version and cordova platform version

    cordova --version   6.5.0
    cordova platform version android    6.0

#### Plugin version

    cordova plugin version  1.10.0

#### Logs taken while reproducing problem
03-30 19:27:23.856: E/AndroidRuntime(13588): FATAL EXCEPTION: pool-2-thread-2
03-30 19:27:23.856: E/AndroidRuntime(13588): Process: com.door.incidentrics, PID: 13588
03-30 19:27:23.856: E/AndroidRuntime(13588): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/util/zzx;
03-30 19:27:23.856: E/AndroidRuntime(13588): 	at com.google.android.gms.iid.zzd.zzeG(Unknown Source)
03-30 19:27:23.856: E/AndroidRuntime(13588): 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
03-30 19:27:23.856: E/AndroidRuntime(13588): 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
03-30 19:27:23.856: E/AndroidRuntime(13588): 	at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
03-30 19:27:23.856: E/AndroidRuntime(13588): 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
03-30 19:27:23.856: E/AndroidRuntime(13588): 	at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:73)
03-30 19:27:23.856: E/AndroidRuntime(13588): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-30 19:27:23.856: E/AndroidRuntime(13588): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-30 19:27:23.856: E/AndroidRuntime(13588): 	at java.lang.Thread.run(Thread.java:818)
03-30 19:27:23.856: E/AndroidRuntime(13588): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.util.zzx" on path: DexPathList[[zip file "/data/app/com.door.incidentrics-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
03-30 19:27:23.856: E/AndroidRuntime(13588): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-30 19:27:23.856: E/AndroidRuntime(13588): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
03-30 19:27:23.856: E/AndroidRuntime(13588): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
03-30 19:27:23.856: E/AndroidRuntime(13588): 	... 9 more
03-30 19:27:23.856: E/AndroidRuntime(13588): 	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.common.util.zzx
03-30 19:27:23.856: E/AndroidRuntime(13588): 		at java.lang.Class.classForName(Native Method)
03-30 19:27:23.856: E/AndroidRuntime(13588): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
03-30 19:27:23.856: E/AndroidRuntime(13588): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
03-30 19:27:23.856: E/AndroidRuntime(13588): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
03-30 19:27:23.856: E/AndroidRuntime(13588): 		... 10 more
03-30 19:27:23.856: E/AndroidRuntime(13588): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by zimski** [comment]
I have the same think as you and I fixed it by  updating the com.google.android.gms:play-services-gcm from version 9.8+ to 10.2+

You can update this at `project-properties` file

**Comment by sid180** [comment]
No luck, same issue

**Comment by sid180** [comment]
Moved project to android studio, Now Every thing working  fine.
