### ISSUE TITLE
Is there an example of how to use options.android.icon?

### ISSUE THREAD

**Issue by lunchbag** [phonegap/phonegap-plugin-push#166]
I can't seem to set the icon for the notification in Android. I've tried using the "@drawable/icon" as well as relative paths. Any guidance would be great. Thanks!

**Comment by fredgalvao** [comment]
You don't need to specify the path from the file, just need to set the file name. Android already knows where to look for resource files in your project.
For example, if you have a file named `icon.png` at the path `platforms/android/res/drawable/icon.png`, you only need to set `options.android.icon = "icon";`.

**Comment by macdonst** [comment]
@lunchbag see the Images section of the README https://github.com/phonegap/phonegap-plugin-push#images
