### ISSUE TITLE
Found item String/google_app_id

### ISSUE THREAD

**Issue by Mystearica** [phonegap/phonegap-plugin-push#1660]
### Expected Behaviour
Should compile the app correctly

### Actual Behaviour
The app is not compiling because of this error: Found item String/google_app_id more than one time

#### Cordova CLI version and cordova platform version
Ionic 2.2.1

#### Plugin version
1.10.0

#### Sample Code that illustrates the problem
In the strings.xml (Android platform) when I use ionic run android, it generates another string with the same id.

    <string name="google_app_id">@string/google_app_id</string>
    <string name="google_app_id" translatable="false">XXXXXXX</string>

I changed the numbers to XXXXXX 

#### Logs taken while reproducing problem
Error: Found item String/google_app_id more than one time

**Comment by macdonst** [comment]
@Mystearica where is the other `google_app_id` coming from?

**Comment by Mystearica** [comment]
@macdonst its coming from firebase plugin. Im using ionic2.
I tried removing the addons and addinng them again in different order, but both add google_app_id.

**Comment by macdonst** [comment]
@Mystearica why do you need to use the Firebase plugin?

**Comment by Mystearica** [comment]
@macdonst well Ionic 2 documentation says that you need that plugin in order to use firebase in your proyect.

**Comment by macdonst** [comment]
@Mystearica link to docs please?

**Comment by Mystearica** [comment]
Here: https://ionicframework.com/docs/native/firebase/

**Comment by macdonst** [comment]
@Mystearica right, well that is an incompatibility between the plugins. It will be solved in the 2.0.0 of this plugin but let me see if there is a way to work around it.

**Comment by Mystearica** [comment]
@macdonst Thank you! I really need to solve this problem, I hope there is any work around.

**Comment by macdonst** [comment]
Note for myself.

Use [edit-config](https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#edit-config) instead.

**Comment by fredgalvao** [comment]
Related note:  `<resource-config>` from 6.2.0 is also an interesting suggestion for users.

**Comment by macdonst** [comment]
Nope, if the is no `google_app_id` in the manifest then adding the plugin gives this error:

```
Error: Unable to graft xml at selector "/resources/string[@name='google_app_id']"
```

It'll have to wait for the 2.0 release.

**Comment by macdonst** [comment]
In release 2.0.0 there will be no adding of 'google_app_id' in the strings.xml file. The inclusion of the Google Services file will be done with `resource-file` tag in config.xml.

**Comment by aswinramakrish** [comment]
@macdonst Any idea when this issue would be fixed / ETA on `2.0.0`? This is a great plugin! I'd really love to use it with Firebase.

**Comment by palbaladejo** [comment]
@aswinramakrish 
`cordova plugin add phonegap-plugin-push@2.0.0-rc3`
Worked for me.

**Comment by macdonst** [comment]
Yeah, folks can start using the release candidates. 

`cordova plugin add phonegap-plugin-push@2.0.0-rc4`

is the latest.
