### ISSUE TITLE
Status of FCM , is it working now?

### ISSUE THREAD

**Issue by v3ss0n** [phonegap/phonegap-plugin-push#1661]
Since GCM is now moving to FCM and not sure it will be supported anymore , is FCM is working well currently now? I am having crashes in android 4.4.4 for  Master branch , on app start.

**Comment by macdonst** [comment]
@v3ss0n try the `v2.0.x` branch which is also available on npm as `v2.0.0-rc2`. Also, for future issues please follow the issues guidelines.

**Comment by v3ss0n** [comment]
Thanks a lot ,i just want to know a quick questions . The crash seems to fixed after clean reinstall.
