### ISSUE TITLE
Action Button are not appearing on Android

### ISSUE THREAD

**Issue by iDroidindia** [phonegap/phonegap-plugin-push#1662]
### Expected Behaviour :
Need to have action Buttons like Accept or Declined after getting the Notification

### Actual Behaviour
The Notification is appearing fine, however the Action buttons are not appearing.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0.1, Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Asus, Checked on Other Device as well

#### Cordova CLI version and cordova platform version
cordova cli -version
6.5.0
cordova  -version
6.5.0
 

#### Plugin version

phonegap-plugin-push 1.10.0 "PushPlugin"

#### Sample Push Data Payload

```
$msg = array
(
'message' => $message,
'title' => $title,
'vibrate' => 1,
'style' => 'picture',
'image' => 'http://idroidindia.com/wp-content/uploads/2015/02/idi_LMS_top_logo2.png',
'picture' => 'http://idroidindia.com/wp-content/uploads/2015/02/idi_LMS_top_logo2.png',
'sound' => 1,
'action' => 'yes'

// you can also add images, additionalData
);
```

#### Sample Code that illustrates the problem

the PHP code is as follows:
----------------------------------------------------------------------------------------------------------------------------
```
<?php

$to="Receiver's  Key";
$title="iDroidIndia Push Message";
$message="Welcome to iDroidIndia.com";
$image='http://idroidindia.com/wp-content/uploads/2015/02/idi_LMS_top_logo2.png';
$picture = 'http://idroidindia.com/wp-content/uploads/2015/02/idi_LMS_top_logo2.png';

$action = " 'icon' => 'tsd', 'title' => 'hello', 'callback' => '', 'foreground' => false, 'inline' => true ";

sendPush($to,$title,$message,$image,$picture);

function sendPush($to,$title,$message)
{
// API access key from Google API's Console
// replace API
define( 'API_ACCESS_KEY', 'My Key');
$registrationIds = array($to);
$msg = array
(
'message' => $message,
'title' => $title,
'vibrate' => 1,
'style' => 'picture',
'image' => 'http://idroidindia.com/wp-content/uploads/2015/02/idi_LMS_top_logo2.png',
'picture' => 'http://idroidindia.com/wp-content/uploads/2015/02/idi_LMS_top_logo2.png',
'sound' => 1,
'action' => 'yes'

// you can also add images, additionalData
);
$fields = array
(
'registration_ids' => $registrationIds,
'data' => $msg,
'actions' => 
    		" 'icon' => 'tsd', 'title' => 'hello', 'callback' => '', 'foreground' => false, 'inline' => true "

);
$headers = array
(
'Authorization: key=' . API_ACCESS_KEY,
'Content-Type: application/json'
);
$ch = curl_init();
curl_setopt( $ch,CURLOPT_URL, 'https://android.googleapis.com/gcm/send' );
curl_setopt( $ch,CURLOPT_POST, true );
curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fields ) );
$result = curl_exec($ch );
curl_close( $ch );
echo $result;
}
?>
```
----------------------------------------------------------------------------------------------------------------------------

URL og the PHP file: http://idroidindia.com/php_info.php

#### Logs taken while reproducing problem
![screenshot_2017-04-01-19-21-24](https://cloud.githubusercontent.com/assets/11772202/24579336/d09e22d6-1710-11e7-8fcf-d71dfc84d4b3.jpg)

Not yet...

Any help would be highly appreciated.

**Comment by macdonst** [comment]
@iDroidindia the `actions` array goes in the `data` section of your payload not at the same level of `data` property. See https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons

**Comment by iDroidindia** [comment]
Ok, my bad....

Its done...Thanks for the help.....
