### ISSUE TITLE
How to display Push notification when the app is in Foreground in iOS?

### ISSUE THREAD

**Issue by Dineshrajaa** [phonegap/phonegap-plugin-push#1667]
### Expected Behaviour
To display push notification when the user is using the app, whenever user clicks the notification "onNotification" event has to be triggered.
### Actual Behaviour
Notification is not being shown on the Notification area but still "onNotification" event is getting triggered.
### Reproduce Scenario (including but not limited to)
User is using the app to create a post, whenever a notification arrives it is not being shown instead onNotification event is getting triggered.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.3.1 (Almost every iOS version)
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
No problem in Android I am using "forceShow"
#### Cordova CLI version and cordova platform version
Cordova version-6.5.0
Cordova-ios version-4.3.1 
    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version
Plugin version-1.9.0
    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@Dineshrajaa this is only possible on Android using the [forceShow](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushnotificationinitoptions) option. If you want this behaviour on iOS you'll need to create the UI yourself when the "onNotification" event is being called.
