### ISSUE TITLE
/Podfile.lock and Manifest.lock + GoogleCloudMessaging.h

### ISSUE THREAD

**Issue by jackdaniel9** [phonegap/phonegap-plugin-push#1668]
Excuse for my english

Hi,

**### Expected Behaviour**
Install Cocoapods in IOS folder project make with Cordova 6.4.0 on MAC

**### Actual Behaviour**
When i build on XCODE 8
/Podfile.lock and Pods/Manifest.lock not found
and
GoogleCloudMessaging.h error file not found

Maybe error with the path  ${PODS_ROOT} ?

**#### Steps to Reproduce** 
I build cordova project with Visual Studio 2015 community (PC). I import my project on MAC OSX and i install Cocoapods in the IOS Folder. I open my project.xcworkspace in XCODE 8 and i build the apps but failed. 

Deintegrate PODS, reinstalle, update, many time...nothing.

In target and in "Build Phase" tab, i modify :
```
diff "${PODS_PODFILE_DIR_PATH}/Podfile.lock" "${PODS_ROOT}/Manifest.lock" > /dev/null
if [ $? != 0 ] ; then
    # print error to STDERR
    echo "error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation." >&2
    exit 1
fi
```

to

```

diff "Podfile.lock" "Pods/Manifest.lock" > /dev/null
if [ $? != 0 ] ; then
    # print error to STDERR
    echo "error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation." >&2
    exit 1
fi
```

Work to resolve podfile et manifest error but i have GoogleCloudMessaging.h error file not found

**#### Cordova CLI version and cordova platform version**

    cordova 6.4.0
    Android and IOS
   Try to build on iphone 5

**#### Plugin version**

      phonegap-plugin-push  1.10.0

**Comment by jackdaniel9** [comment]
in Pushplugin.m

Xcode cannot found this files :
#import "GoogleCloudMessaging.h"
#import "GGLInstanceIDHeaders.h"

**Comment by macdonst** [comment]
@jackdaniel9 are you building the project file or the workspace? You should be using the workspace.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.

**Comment by blumanski** [comment]
Same problem, can that be resolved?

**Comment by blumanski** [comment]
Ionic 1
Platform IOS

Same as above, just that I get "FirebaseInstanceID module not found"
without the path fix, as described by @jackdaniel9 I get a the sandbox error and Podfile not found and Manifest not found.

**Comment by jackdaniel9** [comment]
i recommed to use "cordova-plugin-fcm" now. 

https://github.com/fechanique/cordova-plugin-fcm

**Comment by ostownsville** [comment]
That does work but has invalid archives on upload to apple store... due to, I guess, firebase library need upgrade.
