### ISSUE TITLE
notification description on android getting cut

### ISSUE THREAD

**Issue by mokingguy** [phonegap/phonegap-plugin-push#1671]
### Expected Behaviour

Being able to expand notifications of the text is too large to see all the content

I saw this being an issue on #63 but I don't see support on the docs as to how to do this

### Actual Behaviour

If you send a large text it gets cut off (depends on the device screen size)

### Reproduce Scenario (including but not limited to)
I send this notification using `node-gcm`
```  
  var message = new gcm.Message({
    contentAvailable: true,
    priority: 'high'
  });
  var color = '#e42112'
  message.addNotification({
    title: 'TEST',
    body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    sound: 'default',
    color: color,
    icon: 'ic_noti'
  });
  sender.send(message, {
    registrationTokens: ['cEb9EYpqJ44:APA91bHlT21XbVaNFTdqN9t8d2ehVwymqMbHXtdK02ifLzSYEpNmrOYZ6Goz71uJaia3eddK_ojX_wVjH_56Y7KFtlWA5EKKNg73w0k9ZexwmlNAdFyGRxABGOxlEZHA-AN7f0ZBUWHj']
  }, function(err, response) {
    if (err) {
      console.error(err);
      res.status(500).json(error).end();
    } else {
      console.log("andorid response", response);
      res.status(200).json(response).end();
    }
  });
```
And I get this on my device [image](https://drive.google.com/file/d/0B9OS_eonvthrZUsyYUpPTVBWQXM/view) and I'm not able to expand it
#### Steps to Reproduce 

Send a notification as explained above

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

This was tested on android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

The device was a motorola X play

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.5.0
    cordova platform version android                    6.1.2

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push    1.9.2

#### Sample Push Data Payload

````
{
    title: 'TEST',
    body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    sound: 'default',
    color: color,
    icon: 'ic_noti'
  }
````
#### Sample Code that illustrates the problem
```  
  var message = new gcm.Message({
    contentAvailable: true,
    priority: 'high'
  });
  var color = '#e42112'
  message.addNotification({
    title: 'TEST',
    body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    sound: 'default',
    color: color,
    icon: 'ic_noti'
  });
  sender.send(message, {
    registrationTokens: ['cEb9EYpqJ44:APA91bHlT21XbVaNFTdqN9t8d2ehVwymqMbHXtdK02ifLzSYEpNmrOYZ6Goz71uJaia3eddK_ojX_wVjH_56Y7KFtlWA5EKKNg73w0k9ZexwmlNAdFyGRxABGOxlEZHA-AN7f0ZBUWHj']
  }, function(err, response) {
    if (err) {
      console.error(err);
      res.status(500).json(error).end();
    } else {
      console.log("andorid response", response);
      res.status(200).json(response).end();
    }
  });
```

**Comment by macdonst** [comment]
@mokingguy did you try pulling the notification down to expand it?

**Comment by mokingguy** [comment]
I tried several ways to pull the notification to expand it, I took a couple of videos one with a comparison with a similar notification (sadly i forgot to turn on visible touches) and other with the visible touches


[Comparison with another notification](https://drive.google.com/open?id=0B9OS_eonvthrMVBrUzNrUHpIQjg)

[With visible touches](https://drive.google.com/open?id=0B9OS_eonvthraXc5bG1VYXJReTA)

**Comment by macdonst** [comment]
@mokingguy now that I've got another minute to see what's going on I bet it is because you are using `addNotification` instead of `addData`. Please try that change in your script and let me know.

**Comment by mokingguy** [comment]
Yup, that fixed it. Wonder why if I send it that way it does not create a BigTextView and if it can be solved.

Anyway that did it thank you, you rock!

**Comment by macdonst** [comment]
@mokingguy described here https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

**Comment by dionalfa** [comment]
@mokingguy Hey I want to ask. Is it possible to expand the summaryText in BigPicture notification?

Here is my code (using firebase admin nodeJS SDK):
```
admin.messaging().sendToTopic('someTopic', {
    data: {
      "title": "Big Picture",
      "message": "This is my big picture message",
      "style": "picture",
      "picture": "http://bisnisupdate.com/images/posts/2016/07/01/LABBAIK-CHICKEN.png",
      "summaryText": "How can we expand our chicken business so fast? ready to hear the secret?"
    }
  })
    .then(function (response) {
      res.send(response);
    })
    .catch(function (err) {
      res.send(err);
    });
```

In current condition, when notification is expanded. The image is being show but the text summary is being trunctated / trimmed.
Any workaround to make the summary text is expanded too?
