### ISSUE TITLE
Code In push.on('notification', callback) Is Not Running When App Is Quit Out Of

### ISSUE THREAD

**Issue by dmarcus1** [phonegap/phonegap-plugin-push#1673]
### Expected Behaviour
The app is closed (not in background and not in foreground). I send a push notification to the phone. Then it increases the badge number after 30 seconds if the person doesn't open the app.

### Actual Behaviour
My on push.on('notification', callback) function doesn't get called if the app is closed. It seems to get called once I press on the push notification to open the app. But I want it to get called if the push notification is ignored.

My payload data has content-available set to 0 and it doesn't matter if I set it to 1 because content-available only applies when the app is in the background.

I looked at this diagram which was really helpful and it looks like what I want might not be possible with this plugin. I just want to confirm that this is true.
![image](https://cloud.githubusercontent.com/assets/26162804/24841116/1d8cad1c-1d4a-11e7-9b29-792b0b52f25b.png)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iPhone
iOS 9.2.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
haven't tried Android

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

I'm leaving the rest of the details out because this might be expected behavior. If not, I'll open a new issue and include my code and other details.

**Comment by macdonst** [comment]
@dmarcus1 if your app has been force closed there is no way to have the `on('notification)` event fire because the web view that would run that code is not in memory.

**Comment by fredgalvao** [comment]
Wait, what is [this](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#application-force-closed) about then?

IIRC this should work, with the proper `"force-start": 1` key on the payload.

**Comment by macdonst** [comment]
@fredgalvao user specified ios.

**Comment by fredgalvao** [comment]
Oh right. I keep  forgetting that people don't fill the template correctly, and when I saw `cordova platform version android` at a glance I thought it was android.

**Comment by dmarcus1** [comment]
I just re-read the docs and found that you can send a badge number in the payload. 

    "data": {
    	"title": "Badge Test",
    	"badge": 1
    }

I quit out of the app on the iPhone. Then I sent it a push notification with badge in the payload and it updated the badge number even though the app was closed (not in foreground or background). That's what I need. Thanks for all of your help with this.

**Comment by macdonst** [comment]
@dmarcus1 yeah, that is standard OS behaviour you get for free as long as you set the badge in the payload.

**Comment by dmarcus1** [comment]
Does it only work with OS? I haven't tried sending that payload to android.

**Comment by macdonst** [comment]
@dmarcus1 Android support is via shortcutbadger which is included by the plugin but it does not support all phones/launchers on Android.

**Comment by dmarcus1** [comment]
Okay perfect. That's good enough if it works on all iOS and some Android.

**Comment by MarinoRaul** [comment]
Hello!

how can I increment the badge number icon with this plugin when the app is closed?

Thanks a lot

**Comment by davemarc** [comment]
@MarinoRaul take a look at my previous comment. I got it to work by passing badge as a key in the data.
