### ISSUE TITLE
How to Install on iphone  with phonegap 

### ISSUE THREAD

**Issue by brunoalex** [phonegap/phonegap-plugin-push#1678]
### Expected Behaviour

Iphone should recive notifications

### Actual Behaviour
Iphone dont recive notifications

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

PhoneGap (iOS / Android / Windows)
    cli-6.4.0 (4.3.0 / 6.1.0 / 4.4.3) 

#### Cordova CLI version and cordova platform version

PhoneGap (iOS / Android / Windows)
    cli-6.4.0 (4.3.0 / 6.1.0 / 4.4.3) 

#### Plugin version

phonegap-plugin-push    	npm 	~1.9.2 	

Im using phonegap build and added the plugin ...it registers and gives me the id :38cf2edbec74da4a05c56e12fb2a77a54d000e9e74b5d19b725cd166100e77b1
..
does this means that im all set ? 

do i need to use xcode for anything ? 
i tried to test and send a msg via http://apns-gcm.bryantan.info/
but i get  Error: Pem File cannot be blank. 

can some one helme with the steps to get this working ? 

i did : 

on apple dev:
-create the push certificates 
-create the certificates for the build of the app

-install plugin via cloud on phonegap build 
- i get the reg.id but still cant recive msgs

**Comment by macdonst** [comment]
@brunoalex seems like you are all set if you have received a notification ID but if you are getting an error setting up the remote service to send a push which is outside the scope of this plugin. You'll need to create the .pem file and upload it to your service.
