### ISSUE TITLE
Please clarify the use of content-available in the payload doc

### ISSUE THREAD

**Issue by bardu** [phonegap/phonegap-plugin-push#1679]
I'm referring to issue https://github.com/phonegap/phonegap-plugin-push/issues/820 and https://github.com/phonegap/phonegap-plugin-push/issues/1577

@macdonst It might be helpful for all of us if you could clarify the required form of the `content available` property for both iOS and Android in the payload doc (https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md).

In the doc, there are actually two forms of the property `content_available` and `content-available`, so which is the right one? In the threads mentioned above yourself sometimes use one version or the other.

For the value of this property, there are `"1"`, `1` and `true`, which is the correct one? Is there any different use expected for iOS and Android?

**Comment by macdonst** [comment]
@bardu for Android: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications

for ios: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications-1

Let me know what is not clear.

**Comment by fredgalvao** [comment]
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#use-of-content-available-true

This part mentions `content_available` and `content-available` in a mixed fashion, we could use clarification there. The rest seems okay to me.

**Comment by iparrabb** [comment]
I agree, the comunity needs a clear example of usage for Android and iOS, using FCM and APNS, I follow the examples of the payloads docs but is very difficult to get the expected result.

I have opened #1833 for this reason, I tested with FCM and APNS, works fine except on iOS but I have lost many hours of work for this reason.
