### ISSUE TITLE
Uncaught ReferenceError : module is not defined  at notification.js : 25

### ISSUE THREAD

**Issue by Gabri34** [phonegap/phonegap-plugin-push#1680]
### Expected Behaviour
Hello! I'm new with Cordova, I'm trying to run a simple plugin for my App, in this case I decided to use 'cordova-plugin-dialogs'. I installed the plugin using CLI, then I decided to test beep function. I used the example available in Cordova official site.
Using this line of code:

  <script type="text/javascript">
        document.getElementById('but').addEventListener('click',function hello(){
          navigator.notification.beep(2);
        });

        </script>
I would expect two beeps when I click the button.

<input type='button' value='hi!'  name="prova" id='but'></br>

### Actual Behaviour
When I click the button I only have the error reported  below.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung S3
#### Cordova CLI version and cordova platform version

    cordova --version                                    last version, downloaded two weeks ago
    cordova platform version android                     6.1.2

#### Plugin version

    cordova plugin version (dialogs)  1.3.2

#### Logs taken while reproducing problem

notification.js:25 Uncaught ReferenceError: module is not defined
    at notification.js:25
(anonymous) @ notification.js:25
cordova.js:1469 Uncaught Error: Module cordova-plugin-dialogs.notification does not exist.
    at addEntry (cordova.js:1469)
    at Object.exports.merges (cordova.js:1483)
    at onScriptLoadingComplete (cordova.js:1899)
    at scriptLoadedCallback (cordova.js:1926)
    at HTMLScriptElement.<anonymous> (cordova.js:1882)

**Comment by macdonst** [comment]
@Gabri34 that API is not part of this plugin. Please ask on PhoneGap forums https://forums.adobe.com/community/phonegap
