### ISSUE TITLE
Blue and white LED not working

### ISSUE THREAD

**Issue by LeandroRM** [phonegap/phonegap-plugin-push#1683]
Hi,
I'm trying to send push notifications with led color set to blue, but the led doesn't blink. If I change to white, the led blinks orange. All the other colors work fine.

I noticed that them doesn't work at WhatsApp too.

I'm using the phonegap-push-plugin with the version 1.8.4 and doing tests on an Asus Zenfone 3 with Android 7.0

The payload i used to sent the notification:
{"data":{"badge":0,"data":"Led notification test","ledColor":[0,0,0,255],"title":"Test"},"to":"TOKEN","notId":"1"}

Could anyone explain why of that?

**Comment by macdonst** [comment]
@LeandroRM LED color are not standard on all Android devices so YMMV.
