### ISSUE TITLE
Unable to fetch 2.0.x version of plugin

### ISSUE THREAD

**Issue by centos94** [phonegap/phonegap-plugin-push#1684]
### Expected Behaviour
Fecth plugin via 
_cordova plugin add https://github.com/phonegap/phonegap-plugin-push#07fa81b7a3a62400915ac70b9a24a8
02465a6f95 --variable SENDER_ID="XXXXX"_

### Actual Behaviour
Get following error
_**Error: Failed to fetch plugin https://github.com/phonegap/phonegap-plugin-push via git.
Either there is a connection problems, or plugin spec is incorrect:
        Error: git: Command failed with exit code 128 Error output:
fatal: reference is not a tree: 07fa81b7a3a62400915ac70b9a24a802465a6f95**_

#### Cordova CLI version and cordova platform version

    cordova --version                                    # 6.5.0
    ionic --version                                      # 2.2.2

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   #2.0.x

#### Considerations
Seems like the # 2.0.x is not more a branch.
Is merged to master?

Thanks in advance.

**Comment by jcesarmobile** [comment]
You are not adding from the branch, you are adding from a commit 

To add from the v2.0.x branch use
`cordova plugin add https://github.com/phonegap/phonegap-plugin-push#v2.0.x --variable SENDER_ID="XXXXX"`

**Comment by epetre** [comment]
Is the SENDER_ID required? I read in the installation page that it's not.

**Comment by fredgalvao** [comment]
@epetre  The variable is required, but if you're not using Android you can pass anything into it.

> If you are not creating an Android application you can put in anything for this value.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements

**Comment by macdonst** [comment]
@epetre the SENDER_ID is no required in the 2.0.x branch anymore or the 2.0.0-rc2 release in NPM.

**Comment by epetre** [comment]
ok my mistake, I thought that V2 automatically took it from the google-services file.
