### ISSUE TITLE
Build fails on android

### ISSUE THREAD

**Issue by demym** [phonegap/phonegap-plugin-push#1686]
### Actual Behaviour

cordova run (or build) android fails with the following msg:

Error: /Users/pietroturati/Desktop/demy/PROJECTS/appkwondo/client/jqm/platforms/android/gradlew: Command failed wit
h exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.co
ncurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibil
ityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

This happens after doing cordova platform rm android and then cordova platform add android

Does not happen on a freshly created cordova project;

without push plugin the project builds fine (but after adding the plugin, failing build, removing plugin and rebuilding i have to remove and then add android platform again)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

platform android 6.0.0

#### Cordova CLI version and cordova platform version

    cordova --version   6.4.0
    cordova platform version android   6.0.0

already installed plugins:

android-camera-permission 1.0.0 "Android Camera Permission"
android.support.v4 21.0.1 "Android Support v4"
cordova-plugin-android-permissions 0.10.0 "Permissions"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-audio-recorder-api 0.0.1 "AudioRecorderAPI"
cordova-plugin-badge 0.7.2 "Badges"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-fileopener 1.0.4 "FileOpener"
cordova-plugin-media-capture 1.4.0 "Capture"
cordova-plugin-splashscreen 3.2.1 "Splashscreen"
cordova-plugin-tts 0.2.3 "TTS"
cordova-plugin-velda-devicefeedback 0.0.2 "DeviceFeedback"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-plugin-x-socialsharing 5.0.12 "SocialSharing"
de.appplant.cordova.plugin.local-notification 0.8.2dev "LocalNotification"
org.apache.cordova.camera 0.3.6 "Camera"
org.apache.cordova.device 0.3.0 "Device"
org.solderzzc.base64imagesaverplugin 0.6.0 "Base64ImageSaverPlugin"

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@demym I don't know why you have added `android.support.v4` as that is a really bad idea. They way that plugin works is it directly adds in the jar to the project when it should be added as a framework. That way if multiple plugins need the v4 support jar the framework tag will prevent it from being added twice.

So you need to remove `android.support.v4` plugin from your app and figure out why it was included in the first place.

As well I see you are using `org.apache.cordova.camera' and `org.apache.cordova.device` which are horribly out of date.
