### ISSUE TITLE
push.on(notification) not working on IOS

### ISSUE THREAD

**Issue by hybridapp20161** [phonegap/phonegap-plugin-push#1687]
### Expected Behaviour

After registeration the notification should be dispalyed on app,but it doestnt show the notification.
My app is in foreground

### Actual Behaviour
push.on notification is not getting called.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ios 10.1.1

#### Cordova CLI version and cordova platform version

    cordova --version                                6.3.1
  

plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.8.4

#### Sample Push Data Payload
my push data is not in frontend,receiving from backend

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by lfreneda** [comment]
@hybridapp20161 did you solve this issue?
