### ISSUE TITLE
The icon does not show up on every device!

### ISSUE THREAD

**Issue by anonymuos1** [phonegap/phonegap-plugin-push#1689]
Hi!

I have a problem, because the notification icon (basic android application icon) does not show up on every devices' status bar and neither in the notification list.
Can somebody please take a look at my setting and see if you can figure out what could be the problem?

The icon **shows up** on these devices:
- Xiaomi Redmi Note 4G (android 4.4.4)
- Samsung Galaxy Note 3 (android 5.0)

But it does **not show up** on these ones:
- Xperia M2 Aqua (android 5.1.1)
- Lenovo P70-A (android 5.1)
- Lenovo P1 (android 6.0.1)

I attached a picture, which shows the screen of the Lenovo P70-A (android 5.1) so here you can how the icon does not show up --> [http://i.imgur.com/sa6r0NQ.jpg](http://i.imgur.com/sa6r0NQ.jpg)

**The setting / parameters:**

cordova --version --> 6.5.0
cordova platform version android --> 6.1.2

```
 var push = PushNotification.init({
    android: {
        senderID: "xxxxxxxxx",
    },
    ios: {
      alert: "true",
      badge: "true",
      sound: "true"
    },
    windows: {}
  });
```
```
  <access origin="*" />
  <preference name="webviewbounce" value="false" />
  <preference name="UIWebViewBounce" value="false" />
  <preference name="DisallowOverscroll" value="true" />
  <preference name="SplashScreenDelay" value="2000" />
  <preference name="FadeSplashScreenDuration" value="2000" />
  <preference name="android-minSdkVersion" value="16" />
  <preference name="BackupWebStorage" value="none" />
  <preference name="android-targetSdkVersion" value="23" />
  <preference name="AndroidLaunchMode" value="standard" />
  <preference name="SplashScreen" value="screen" />
  <feature name="StatusBar">
    <param name="ios-package" onload="true" value="CDVStatusBar" />
  </feature>
  <plugin name="cordova-plugin-console" version="1.0.6" />
  <plugin name="cordova-plugin-device" version="1.1.5" />
  <plugin name="cordova-plugin-splashscreen" version="4.0.2" />
  <plugin name="cordova-plugin-statusbar" version="2.2.2" />
  <plugin name="cordova-plugin-inappbrowser" version="1.7.0" />
  <plugin name="cordova-plugin-network-information" version="1.3.2" />
  <plugin name="de.appplant.cordova.plugin.local-notification" version="0.8.4" />
  <plugin name="cordova-plugin-google-analytics" version="1.7.11" />
  <plugin name="cordova-plugin-app-event" version="1.2.0" />
  <plugin name="cordova-plugin-crosswalk-webview" version="2.3.0" />
  <plugin name="cordova-plugin-whitelist" version="1.3.2" />
  <platform name="android">
    <icon src="resources/android/icon/drawable-ldpi-icon.png" density="ldpi" />
    <icon src="resources/android/icon/drawable-mdpi-icon.png" density="mdpi" />
    <icon src="resources/android/icon/drawable-hdpi-icon.png" density="hdpi" />
    <icon src="resources/android/icon/drawable-xhdpi-icon.png" density="xhdpi" />
    <icon src="resources/android/icon/drawable-xxhdpi-icon.png" density="xxhdpi" />
    <icon src="resources/android/icon/drawable-xxxhdpi-icon.png" density="xxxhdpi" />
  </platform>
  <plugin name="phonegap-plugin-push" version="1.10.2">
    <variable name="SENDER_ID" value="xxxxxxxxx" />
  </plugin>
```

Thanks for your help in advance

**Comment by macdonst** [comment]
@anonymuos1 I have been over this about 1 million times and the root cause is documented here:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images

**Comment by anonymuos1** [comment]
If you are suggesting I use the following settings, I tried it but it still does not work:
```
"android": {
		"senderID": "123456789",
		"icon": "phonegap",
		"iconColor": "blue"
	}
```
Since the name of it is icon.png, I set the following:
```
"android": {
		"senderID": "123456789",
		"icon": "icon"
	}
```
I looked through the documentation before I asked my question, but could you please tell me what you think I overlooked? Also, as I mentioned there are a few devices where the icon shows up. How can that happen? It shows up on one device but not the other one? Thank you

**Comment by macdonst** [comment]
@anonymuos1 forgive me being a bit pissy here but sweet merciful crap I have answered this question way too many times. As of Android 5.0 things now follow the Material guidelines which is to make the notification icon completely white. As you can see you are having problems on devices with Android 5+ which the exception of Samsung which does some screwy things with regards to the UI.

As I mention in the docs I linked to you, each pixel in the image you specify is changed to white except for the transparent ones. So I can only assume one of two things 1) you icon does not have transparent pixels or 2) you did not copy the icon into the drawables folder properly.

**Comment by anonymuos1** [comment]
Hello!

My icon does have transparent pixels, so I don't think this could be the source of my problem. I am not sure of the place my icon should be, so I send you the route, so you see where they are and please correct me if they are not where they should be. 

> - platforms\android\res\mipmap-ldpi
> - platforms\android\res\mipmap-mdpi
> - platforms\android\res\mipmap-hdpi
> - platforms\android\res\mipmap-xhdpi
> - platforms\android\res\mipmap-xxhdpi
> - platforms\android\res\mipmap-xxxhdpi

These were created automatically. I looked at the drawable folders, there were no icon files there, only other icon pictures, (ic_action_next_item.png, ic_action_previous_item.png, ic_action_remove.png), so I copied the adequate icon sizes into this folder. 

> - platforms\android\res\drawable-ldpi
> - platforms\android\res\drawable-mdpi
> - platforms\android\res\drawable-hdpi
> - platforms\android\res\drawable-xhdpi
> - platforms\android\res\drawable-xxhdpi
> - platforms\android\res\drawable-xxxhdpi

But even after these changes I still get a white circle as my icon. I have no idea what could still be problem. I tried everything and still no luck.
Thank you for your patience and help.

**Comment by macdonst** [comment]
@anonymuos1 run `adb logcat | grep PushPlugin` while starting up the app to collect logs. See if we can figure out why your icon is not loaded.

**Comment by anonymuos1** [comment]
PS C:\Users\<user>\AppData\Local\Android\sdk\platform-tools>  .\adb.exe logcat | Select-String PushPlugin

V/PushPlugin(24311): execute: action=init
V/PushPlugin(24311): execute: data=[{"android":{"senderID":"<senderid>","icon":"icon"},"ios":{"alert":"true","badge":
"true","sound":"true"},"windows":{}}]
V/PushPlugin(24311): execute: jo={"senderID":"<senderid>","icon":"icon"}
V/PushPlugin(24311): execute: senderID=<senderid>
V/PushPlugin(24311): onRegistered: {"registrationId":"fjiw6CcplsE:APA91bETaw5tp8t2nsp27sQqrtR1i9I1oFQ4xwon8Ve_SSdKQclRf
RTBv41qJzLrKnpT5cEpkRdtwNFuJYzaABDKWMobNHld2z84aVsQsHAGJ573IZA9wI21V4FKh3VAa6gzx7DJx6u2"}
D/PushPlugin(24311): no iconColor option
D/PushPlugin_GCMIntentService(24311): onMessage - from: <senderid>
D/PushPlugin_GCMIntentService(24311): normalize extras
D/PushPlugin_GCMIntentService(24311): key = google.sent_time
D/PushPlugin_GCMIntentService(24311): replace key google.sent_time with google.sent_time
D/PushPlugin_GCMIntentService(24311): key = image
D/PushPlugin_GCMIntentService(24311): replace key image with image
D/PushPlugin_GCMIntentService(24311): key = notId
D/PushPlugin_GCMIntentService(24311): replace key notId with notId
D/PushPlugin_GCMIntentService(24311): key = title
D/PushPlugin_GCMIntentService(24311): replace key title with title
D/PushPlugin_GCMIntentService(24311): no locale found for key = title, error Value test of type java.lang.String cannot
 be converted to JSONObject
D/PushPlugin_GCMIntentService(24311): key = google.message_id
D/PushPlugin_GCMIntentService(24311): replace key google.message_id with google.message_id
D/PushPlugin_GCMIntentService(24311): key = message
D/PushPlugin_GCMIntentService(24311): replace key message with message
D/PushPlugin_GCMIntentService(24311): no locale found for key = message, error Value test of type java.lang.String cann
ot be converted to JSONObject
D/PushPlugin_GCMIntentService(24311): background
D/PushPlugin_GCMIntentService(24311): message =[test message]
D/PushPlugin_GCMIntentService(24311): title =[test]
D/PushPlugin_GCMIntentService(24311): contentAvailable =[null]
D/PushPlugin_GCMIntentService(24311): forceStart =[null]
D/PushPlugin_GCMIntentService(24311): create notification
D/PushPlugin_GCMIntentService(24311): stored icon=icon
D/PushPlugin_GCMIntentService(24311): stored iconColor=null
D/PushPlugin_GCMIntentService(24311): stored sound=true
D/PushPlugin_GCMIntentService(24311): stored vibrate=true
D/PushPlugin_GCMIntentService(24311): using icon from plugin options
D/PushPlugin_GCMIntentService(24311): using assets large-icon from gcm
D/PushPlugin_GCMIntentService(24311): create actions: with in-line

**Comment by macdonst** [comment]
@anonymuos1 looks like it is trying to use the icon from drawables. What does your push payload look like? Can you drop the icon into this issue?

**Comment by anonymuos1** [comment]
Payload:

> array(2) { ["registration_ids"]=> array(1) { [0]=> string(152) "..........." } ["data"]=> array(4) { ["image"]=> string(16) "www/img/icon.png" ["message"]=> string(4) "test message" ["title"]=> string(4) "test" ["notId"]=> int(173) } } 

Icon (xxxhdpi): 
![icon](https://cloud.githubusercontent.com/assets/5244508/25442954/c08ac9ea-2aa6-11e7-99d6-8c4738858c21.png)

**Comment by fredgalvao** [comment]
That icon, according to what @macdonst just explained you and is on the docs, will become a full solid white circle with nothing legible in it.

When you said
> My icon does have transparent pixels

you weren't lying, but you didn't get the point: Every non-transparent pixel will become white, so you need to think/rethink your imagery so that it's clear and remarkable even when all white.

An example/guide on the topic: https://clevertap.com/blog/fixing-notification-icon-for-android-lollipop-and-above/

**Comment by anonymuos1** [comment]
Thank you for all of your help and patience, now I can see what was the problem, I fixed it and now it works. Have a nice day.
