### ISSUE TITLE
Cordova Android 6.2.1 push registration crashes android app

### ISSUE THREAD

**Issue by rogerhaw** [phonegap/phonegap-plugin-push#1696]
### Expected Behaviour
device should register ok and the app continue to work

### Actual Behaviour
if I assign a device id manually app doesnt crash.
if I init push notification and then wait for device to be registered by the service. it never makes it into the register event - device crashes.

I recently had to update to cordova android 6.2.1 and since doing this the above behavior has surfaced.

I've also noticed in this version trying to remove the plugin , then manually remove the config.xml entries they are not added back when adding in the plugin again. As I tried this to see if it would fix this problem.
so there is something broken with this combination of versions.
e.g.
cordova plugin remove phonegap-plugin-push
(manually remove config.xml entry)
cordova plugin add phonegap-plugin-push@1.9.0 --variable SENDER_ID="9999999etc" –-save
doesnt add the config.xml entry back in.
so I suspect the plugin isnt working at all??

#### Steps to Reproduce 
try registering

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.5
    cordova platform version android                     6.2.1

#### Plugin version

phonegap-plugin-push 1.9.0 "PushPlugin"

**Comment by rogerhaw** [comment]
the output of the push init command object is this - this seems weird -the handlers have null as their object? is this expected?
I feel the whole plugin isnt getting compiled in somehow or something even though I dont get an error on calling push.init.... this code causes the app to crash i.e. I assume when it is trying to recieve the register event.

17:51:43.269 PushNotification: push object END [Elapsed: 0 ms]
app.js:1 {"_handlers":{"registration":[null],"notification":[null],"error":[null]},"options":{"android":{"senderID":"xxxxxetc","vibrate":true,"clearBadge":true,"sound":true,"forceShow":false},"ios":{"alert":true,"badge":true,"sound":true,"clearBadge":true},"windows":{}}}

code:

       var options;

                   

                    // set plugin options
                    options = {
                        android: {
                            senderID: "xxxxxetc",
                            vibrate: true,
                            clearBadge: true,
                            sound: true,
                            forceShow: false // dont raise notification if app in foreground - let app handle it...see On notification even foreground processing below
                        },
                        //browser: {
                        //    pushServiceURL: 'http://push.api.phonegap.com/v1/push'
                        //},
                        ios: {
                            alert: true,
                            badge: true,
                            sound: true,
                            clearBadge: true
                        },
                        windows: {}
                    }

                    console.log(options);
                    var push = window.PushNotification.init(options);
                    console.log("PushNotification: push object");
                    console.log(push);

                    
                    if (changed && id) {
                        console..log("PushNotification: unregister");
                        push.unregister(this.onDeRegistrationSuccess, Ext.emptyFn); // Looked at source code for PushPlugin: failure function never called, but must be specified
 
                    } 

                    push.on('registration', function (data) {
                       console..log("PushNotification: registration");

                        // if the registration id's are different then save local and update remote.
                     
                        }
                    });

                    push.on('notification', function (data) {
                        console..log("PushNotification: notification"); 
                    });

                    push.on('error', function (e) {
                        console..log("PushNotification: error");
                        console..log(e);
                        console..log(e.message);
                    });

                   console.log("PushNotification: push object END");
                   console..log(push);

**Comment by rogerhaw** [comment]
I've also noticed that Android 'Android Support Library version 23 or greater' is not longer appearing in the android library sdk manager - dont know if that has anything to do with it either...
I have all other install requirements in place.

**Comment by rogerhaw** [comment]
perhaps I am doing something wrong here - although it was working prior to the upgrade.

in the old push plugin you called a register event and passed a success handler and this returned a device id.

see below.

I am not sure now how the 'register' event gets called... I cannot see in the doco how this is explicitly called?

pushNotification.register(
    tokenHandler,
    errorHandler,
    {
        "badge":"true",
        "sound":"true",
        "alert":"true",
        "ecb":"onNotificationAPN"
    });

**Comment by rogerhaw** [comment]
Ok
I downgraded to android 6.0.0, cordova 6.4.0 and upgraded plugin to v1.10.1
now the registration event fires and the app doesnt crash
I saw there was an issue fixed in recent plugin version for app crashes?
will this fix later android platform version issue as well?
thx

**Comment by macdonst** [comment]
@rogerhaw well without the stack trace I can't say for sure but it is probably an issue with the way Google was releasing their support libraries. They made some mistakes which made them not compatible with all flavours of Android. They are usually pretty quick to fix it.

I'm going to mark this as closed but if you do reproduce it re-open an issue with the stack trace.
