### ISSUE TITLE
Error index.html not found

### ISSUE THREAD

**Issue by jrahma** [phonegap/phonegap-plugin-push#1697]
I am trying to add your plugin to phonegap here:

[https://build.phonegap.com/apps](https://build.phonegap.com/apps)

but I am getting this error:

**Error index.html not found**

Kindly help

Thanks,
[Jassim](https://www.softnames.com)

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
