### ISSUE TITLE
Delay on('notification') Until Another Callback Finishes

### ISSUE THREAD

**Issue by davemarc** [phonegap/phonegap-plugin-push#1699]
Is there a way to delay firing on('notification') until another callback is complete? My other callback checks facebook to see if I'm logged in. Once that's finished, I'd like on('notification') to fire.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
