### ISSUE TITLE
NodeJS 4.1.1 with cordova 5.3.3 will build fail

### ISSUE THREAD

**Issue by bau720123** [phonegap/phonegap-plugin-push#170]
hi @macdonst 
I am using NodeJS 4.1.1 version
here is my Procedure

step 1 (you will got 5.3.3 version for now)
npm install -g cordova

step 2
cordova create -d "cordovatest"

step 3
cd cordovatest

step 4 (you will got 1.3.0 version for now)
cordova plugin add phonegap-plugin-push
or
cordova plugin add https://github.com/phonegap/phonegap-plugin-push

step 5
cordova platforms add android

step 6
cordova build android --debug
or
cordova build android --release

finally build fail，here is my screenshot
![2015-09-27_202555](https://cloud.githubusercontent.com/assets/5110085/10122772/d57052f2-6555-11e5-8693-011d0d666784.jpg)

by the way
if I never did the step 4 at the start，it will build success
but if I did step 4 before，Even I delete the "phonegap-plugin-push"
cordova plugin rm phonegap-plugin-push
and rebuild again，it still buld fail
I don't know why，but it really happen...

**Comment by fredgalvao** [comment]
This is a duplicate of https://github.com/phonegap/phonegap-plugin-push/issues/159 and  https://github.com/phonegap/phonegap-plugin-push/issues/14. You need to update your android sdk manager to get the latest android-support, that's all.

**Comment by bau720123** [comment]
hi @fredgalvao 
thanks your reply
but after I update the sdk manager to all latest
it still the same

by the way
https://github.com/phonegap/phonegap-plugin-push/issues/14
seem not related to my issue

**Comment by bau720123** [comment]
problem solved
thanks

**Comment by ballestas0523** [comment]
Good morning , friend as lograstes solve the problem ?. It is that I also have the same problem and I could not fix it

**Comment by ballestas0523** [comment]
Good morning , friend as lograstes solve the problem ?. It is that I also have the same problem and I could not fix it @bau720123

**Comment by bau720123** [comment]
hi @ballestas0523 
just update the android sdk manager to get the latest android-support
