### ISSUE TITLE
The logging tag can be at most 23 characters, was 40 (PushPlugin_BackgroundActionButtonHandler)

### ISSUE THREAD

**Issue by mikepsinn** [phonegap/phonegap-plugin-push#1702]
I keep getting the error `The logging tag can be at most 23 characters, was 40 (PushPlugin_BackgroundActionButtonHandler)` when I build, making it impossible to use a lint check requirement in my build process. 

Can I shorten this tag and create a pull request?

**Comment by macdonst** [comment]
@mikepsinn I also modified the main PushPlugin.java LOG_TAG to be Push_Plugin so we can do something like `adb logcat | grep Push_` to get all logs from the plugin.

**Comment by mikepsinn** [comment]
Good thinking!
