### ISSUE TITLE
Notification collapse is not working

### ISSUE THREAD

**Issue by kanak-infoObjects** [phonegap/phonegap-plugin-push#1706]
### Expected Behaviour
When multiple notifications are sent using collapse_key and tag in notification config, notifications should get collapsed as per their collapse_key and tag.

### Actual Behaviour
Notifications are not collapsing and each notification is over writing the previous one in the app if previous notification has not been read. 

#### Steps to Reproduce 
1. Send notifications using below curl command -
curl -XPOST -H 'Authorization: Bearer $YOUR_API_KEY' \
-H 'Content-Type: application/json' \
-d '{"tokens": [$YOUR_DEVICE_TOKEN],"profile": "$YOUR_PROFILE_NAME","notification": {"message": "Hello World!","ios": {"message": "Hello iOS!"},"android": {"message": "Hello Android","tag": "fromUser1","collapse_key": "fromUser1"}}}' https://api.ionic.io/push/notifications

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Moto g3
#### Cordova CLI version and cordova platform version

    cordova --version                                    6.5.0
    cordova platform version android           6.5.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push    1.10.2

#### Sample Push Data Payload
```
"notification": {
        "message": "Hello World!",
        "ios": {
            "message": "Hello iOS!"
        },
        "android": {
            "message": "Hello Android",
            "tag": "fromUser1",
            "collapse_key": "fromUser1"
        }
}
```

**Comment by macdonst** [comment]
@kanak-infoObjects what push service are you using? The format of the payload looks a bit odd.

**Comment by kanak-infoObjects** [comment]
We are using phonegap-plugin-push itself. Please check curl query. I have posted full push payload there.

**Comment by macdonst** [comment]
@kanak-infoObjects yes, I realize you are using the push plugin to receive the push notification but how are you sending it. I see your curl above but it does not tell me what service you are hitting as the url is missing.

**Comment by kanak-infoObjects** [comment]
Oh. I am sorry. I missed it. I am hitting 'https://api.ionic.io/push/notifications' url. I have updated curl request above.

**Comment by lokesh-io** [comment]
I am also facing same issue. Is there any solution for this?

**Comment by macdonst** [comment]
@kanak-infoObjects Can you describe in more detail how you expect `collapse_key` & `tag` to work?

**Comment by kanak-infoObjects** [comment]
I want notifications to be shown as follows -
1. First message comes up - '1 new message from Abc'
2. Another message comes up - '2 new messages from Abc'
3. Third message sent by another user - '3 new messages from 2 contacts'

**Comment by macdonst** [comment]
@kanak-infoObjects okay, well `collapse_key` is used the replace the previous notification with the same `collapse_key` if it hasn't been displayed to the users. Say you send a push to a user but GCM can't deliver it and then you send another push to the user with the same `collapse_key` and GCM will see that and not bother to send the earlier message with the same `collapse_key`.

What I think you are looking for is:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#stacking
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#inbox-stacking

**Comment by kanak-infoObjects** [comment]
@macdonst Thanks a lot for above links. This link helped me in stacking notifications on android -
 https://github.com/phonegap/phonegap-plugin-push/issues/482#issuecomment-209644747. 
Though I still couldn't get something like this - '3 messages from 2 contacts'. Any idea on this?
Also, I need to try this on iOS. I will revert back after doing so.

**Comment by macdonst** [comment]
@kanak-infoObjects yeah, if you send in succession…

```
{
    "registration_ids": ["my device id"],
    "data": {
    	"title": "My Title",
    	"message": "My first message",
    	"style": "inbox",
    	"summaryText": "%n% messages from 1 contact"
    }
}

{
    "registration_ids": ["my device id"],
    "data": {
    	"title": "My Title",
    	"message": "My second message",
    	"style": "inbox",
    	"summaryText": "%n% messages from 1 contact"
    }
}

{
    "registration_ids": ["my device id"],
    "data": {
    	"title": "New Contact",
    	"message": "My first message",
    	"style": "inbox",
    	"summaryText": "%n% messages from 2 contacts"
    }
}
```

The first number can be handled by the plugin but the number of contacts has to kept by your application server.

**Comment by nitheshgreddy** [comment]
@macdonst Does inbox stacking work in Android 4.4.4 version? thanks.
