### ISSUE TITLE
MismatchSenderId for Android.

### ISSUE THREAD

**Issue by filippetroviccc** [phonegap/phonegap-plugin-push#1707]
### Expected Behaviour
I should receive push notification on my Android device with simple tittle and message.
### Actual Behaviour
I am getting [ { error: 'MismatchSenderId' } ] alvase.
### Example
I am using node-gcm to send notification and i copied code example from example in this project.
```
var gcm = require('node-gcm');
// Replace these with your own values.
var apiKey = "Server key from firebase";
var deviceID = "Registration ID from device";
var service = new gcm.Sender(apiKey);
var message = new gcm.Message();
message.addData('title', {"locKey": "push_app_title"});
message.addData('message', 'Simple non-localizable text for message!');
// Constant with formatted params
// message.addData('message', {"locKey": "push_message_fox", "locData": ["fox", "dog"]});
service.send(message, { registrationTokens: [ deviceID ] }, function (err, response) {
    if(err) console.error(err);
    else    console.log(response);
});

```
All code that i used for app itself i used this tutorial: http://macdonst.github.io/push-workshop-eu/
But i just used senderID from my Firebase.

**Comment by macdonst** [comment]
@filippetroviccc well the error is correct. Somehow you are using one ID to send and a different ID to register with the server. How are you running the app? If you are following that tutorial and doing `phonegap serve` you'll need to send via the phonegap CLI.

**Comment by filippetroviccc** [comment]
@macdonst thank you for replying so fast, your are right i am using `phonegap serve` and i was using phonegap cli to test code, and everything worked correctly. But i want to send notifications from node. Is that possible?

**Comment by macdonst** [comment]
@filippetroviccc when you use `phonegap serve` it replaces your sender id with one that can work with the CLI and developer apps. We have to do this in order to allow people to test. If you want to send notifications from node you'll need to add the android platform and run it on a device.

The browser platform is for testing your functionality when the on('notification') event is received. Sorry, that's the best I can do.

**Comment by filippetroviccc** [comment]
@macdonst So i need to build my app and install on my device to test if node sends notification?

**Comment by filippetroviccc** [comment]
@macdonst Thank you for help i just solved issue. I just build my app and all worked correctly.
