### ISSUE TITLE
App crushes when using plugin push

### ISSUE THREAD

**Issue by tomavic** [phonegap/phonegap-plugin-push#1708]
I have a phonegap project that requires using your plugin to get device token and recive notification from back-end

The plugin and the app was working fine for over past 10 months, but what happened is from 2 weeks I was not able to open the app.

Every time I build it success, but when I open the app it crushes in first page (the page where I am calling push notification object).

BTW: I didn't change anything in the code 

```
    <plugin name="phonegap-plugin-push" source="npm" spec="~1.8.0">
        <variable name="SENDER_ID" value="430xxxxxxxx" />
    </plugin>
```

```
    <engine name="ios" spec="~4.1.1" />
    <engine name="android" spec="~5.1.1" />
```

![ddddddddddd](https://cloud.githubusercontent.com/assets/17650005/25791152/1429920a-33dc-11e7-8835-2a97ccfba961.PNG)

If there is particular version I should target please advise

**Comment by chinib** [comment]
Hi Tomavic,

I was encountering the same problem. The app just closes as soon as the Push plugin was initiated. It seemed I installed by accident an old version of the push plugin version. 

Please check this by cordova plugins list: 
I got: phonegap-plugin-push 1.8.1 "PushPlugin"

So I got version 1.8.1 while the newest is 1.10.3. When I tried to install the plugin it gives an Unmet project requirements for latest version of phonegap-plugin-push:
    cordova (0.0.0 in project, >=6.4.0 required)
Fetching highest version of phonegap-plugin-push that this project supports: 1.8.1 (latest is 1.10.3)

Hence the unwanted lower version. 

On another project I was successful in installing the new 1.10.3 and the problem went away. I'm now stuck on this project where I have this unmet dependency, any thoughts are appreciated. Cordova version gives 7.0.0.

Hope this gives a notch in the right direction.

**Comment by tomavic** [comment]
Yes , I also have another project and I it's working fine with the old version. But my current project crushes as soon as I open it


**UPDATE:** 

I changed `spec` from `spec="~1.8.0"` to `spec="~1.9.2"` and I am still testing it

**Comment by macdonst** [comment]
Hatem, are you also using Cordova 7?

Simon

**Comment by tomavic** [comment]
@macdonst No, I am using 6.5.0

**Comment by macdonst** [comment]
Okay well I'm in planes most of the day but running "adb logcat | grep
Push" while reproducing the issue will really help in diagnostics.

**Comment by tomavic** [comment]
BTW I have another issue with diagnostics plugin, you can check [here](https://github.com/dpa99c/cordova-diagnostic-plugin/issues/205)

**Comment by tomavic** [comment]
@macdonst in this thread #271 , you mentioned

![image](https://cloud.githubusercontent.com/assets/17650005/25801080/bc48fb10-3409-11e7-814e-666980dfbc4f.png)

but I didn't find any content any example folder

**Comment by tomavic** [comment]
I had changed `plugin.xml` of this plugin. I had changed the this line 
`<framework src="com.android.support:support-v4:+" />`

to 


`<framework src="com.android.support:support-v13:23+"/>`

and I got 

```
BUILD SUCCESSFUL

Total time: 47.879 secs

Command finished with error code 0: cmd /s /c "C:\Users\IM\Desktop\mink-foodiee\platforms\android\gradlew.bat cdvBuildDebug -b C:\Users\IM\Desktop\mink-foodiee\platforms\android\build.gradle -Dorg.gradle.daemon=true -Dorg.gradle.jvmargs=-Xmx2048m -Pandroid.useDeprecatedNdk=true"
```

**Comment by tomavic** [comment]
But still I didn't got it.

What is the reason behind that?

**Comment by macdonst** [comment]
@chinib you are actually running into this bug in Cordova https://issues.apache.org/jira/browse/CB-12773
