### ISSUE TITLE
Push Notification when app is open?

### ISSUE THREAD

**Issue by xavianaxw** [phonegap/phonegap-plugin-push#171]
Hey guys,

I've managed to set up my app to receive push notification when my app is not open. The thing is when the app is open, I get a console log stating 'didReceiveNotification' and 'NotificationReceived' which I'm guessing it is actually indicating that I did in fact receive notifications. However, I'm not getting any response from this code snippet.

```javascript
push.on('notification', function(data) {
        // data.message,
        // data.title,
        // data.count,
        // data.sound,
        // data.image,
        // data.additionalData
        alert(data.message);
      });
```

Digging deeper in PushPlugin.m on line 183 (void)notificationReceived function, I do get a value from notificationMessage but self.callbackId is null. How do I ensure there is a value in callbackId or instead someone can show me how to handle push notification when the app is opened?

```javascript
- (void)notificationReceived {
    NSLog(@"Notification received");
    
    if (notificationMessage && self.callbackId != nil)
    {
        NSMutableDictionary* message = [NSMutableDictionary dictionaryWithCapacity:4];
        // more here
```

As for my response in notificationMessage, I'm pushing my notification with AWS SNS and it looks something like this

```javascript
{
    aps =     {
        alert = hihi;
    };
}
```

**Comment by xavianaxw** [comment]
@macdonst would love your feedback on this. Much appreciated.

**Comment by xavianaxw** [comment]
I've gotten it to work. Careless mistake on my part.

**Comment by fredgalvao** [comment]
@xavianaxw, do you mind sharing the details on how you made it work?

**Comment by xavianaxw** [comment]
Hi @fredgalvao it was merely not calling this part of the code every time the app is opened

    var push = PushNotification.init({ 
      "android": {
        "senderID": "528473325851"
      },
      "ios": {
        "alert": "true", 
        "badge": "true", 
        "sound": "true"
      } 
    });

**Comment by omaismbakop** [comment]
I have same problem, cant receive notification when app is open,  how to solve that, @xavianaxw  can you please send complete example. Thanks

**Comment by xavianaxw** [comment]
@omaismbakop here you go.

```
$rootScope.registerForPushNotification = function(){
    var push = PushNotification.init({
      "android": {
        "senderID": "androidID from console.developers.google.com (browser key if not wrong)"
      },
      "ios": {
        "alert": "true",
        "badge": "true",
        "sound": "true"
      }
    });

    push.on('registration', function(data) {
      // data.registrationId
      // run some sort of API here to keep registrationId should you need
    });

    // when a notification is retrieved
    push.on('notification', function(data) {
      // available parameters for your disposal
      // data.message,
      // data.title,
      // data.count,
      // data.sound,
      // data.image,
      // data.additionalData
      // do what you want here when a notification is retrieved. updateNotification() or whatever
    });

    // when there was an error with setting up your push notification - possibly be certificate issue 
    push.on('error', function(e) {
      // e.message for your disposal
    });
  };
```

**Comment by omaismbakop** [comment]
my code is executing every time when app starts, but i don't receive the notification when app is open.

**Comment by xavianaxw** [comment]
So you're saying you initialize the push notification with `PushNotification.init` but you can't receive notification when the app is open?

Just to check but did the debugger say that your initialization was successful?

**Comment by omaismbakop** [comment]
yes, i confirmed again, it is calling everytime. initialization was successful

**Comment by fredgalvao** [comment]
That is another issue, @omaismbakop . Please create a separated issue so we can get more info on your case and try to solve it.

**Comment by jedofus** [comment]
i've got the same problem, i see in log of my ios device when i click on my notification when app is closed , the notification function, arrives before the register function. So that's  why we unable to recover callbackid...

**Comment by victorcarvalhosp** [comment]
@omaismbakop same problem here... The notification only show if my app is closed or in foreground... You managed this to work open is open?

Thanks!

**Comment by jspivack** [comment]
I had this problem as well. The "forceShow" parameter should be what you need to tweak to receive notifications while the app is open: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md

**Comment by tobeee** [comment]
I'm having this problem on iOS too. Notification comes in when the app is closed, but when the app is open I'm getting nothing!

ForceShow seems to be just for android - does anyone have any idea what might be causing it?
