### ISSUE TITLE
Semantic Issues, Deprecations - Deployment Target 8.0

### ISSUE THREAD

**Issue by mimi-kk** [phonegap/phonegap-plugin-push#1712]
#### Plugin version 
phonegap-plugin-push  1.10.3

#### XCode vesion
8.3.2

#### Deployment target
8.0

### Actual Behaviour

I get 26 issues Semantic Issue, ARC Retain Cycle, Deprecations, Format String Issue after build
How can I fix this?

**Comment by macdonst** [comment]
@mimi-kk yeah, I'm looking at cleaning this stuff up for the 2.0.0 release but PR's are always welcome.

**Comment by macdonst** [comment]
see #1340
