### ISSUE TITLE
Allow to read original APNS token when FCM is active

### ISSUE THREAD

**Issue by miaowang** [phonegap/phonegap-plugin-push#1714]
With the planned move to Firebase Cloud Messaging https://github.com/phonegap/phonegap-plugin-push/issues/929, there will be a crossplatform approach to notifications to iOS and Android devices. When FCM is active, all notification handling will go through FCM and FCM instance ID - no more fiddling around with the APNS token, etc.

However, for iOS, when we have legacy systems that still require the APNS for registration / analytics / migration purposes, there seems to be no way to retrieve that APNS from the phonegap-plugin-push or from FCM. It would be good to have an external access to read the original APNS token that has been retrieved from application:didRegisterForRemoteNotificationsWithDeviceToken:

#### Expected Behaviour
have an external entry point to read the original APNS token

#### Operating System
iOS

#### Plugin version
phonegap-plugin-push 2.0.x

**Comment by macdonst** [comment]
@miaowang I will not be forcing anyone on iOS to use FCM. It will be a configurable option just the way it is right now. So if your app isn't setup for FCM you'll get the old APNS registration ID.

**Comment by miaowang** [comment]
@macdonst Thanks for the clarification. What I am looking for, is that my app will be using FCM on iOS. However, I also need to retrieve the old APNS registration ID to provide it to other legacy libraries/frameworks/pods etc. that don't support FCM yet and still are using plain old APNS. 

As of now (2.0.0-rc2), I cannot find such a way to obtain the old APNS registration ID. If I am wrong, please let me know how I can get it.

I think that the plugin is taking the old APNS registration ID from application:didRegisterForRemoteNotificationsWithDeviceToken: and directly passes it to FCM and I have no way to retrieve it from outside the plugin, am I correct?

**Comment by fredgalvao** [comment]
So you'd like the plugin to work with both APIs underneath native code at the same time (FCM and APNS) under the same javascript api. Is that it?

**Comment by miaowang** [comment]
@fredgalvao kinda yes

Let's assume I use the push-plugin and FCM for my entire app because I prefer FCM over plain APNS anyway. So my server would send a notification to FCM, FCM will send it to APNS, and APNS will send it to my iOS app [1]. Fine.

But now, I want to integrate another iOS framework XYZ. That framework XYZ connects to a different server and also sends me push notifications. It does not support FCM yet, so it requires me to give a plain old APNS registration ID during initialization. However, I cannot retrieve that old APNS registration ID because it was already taken from the push-plugin and I have no way to retrieve it again. Or do I?

[1] https://firebase.googleblog.com/2017/01/debugging-firebase-cloud-messaging-on.html

**Comment by vargaendre** [comment]
Hi,

I am in the very same situation as @miaowang. By default I am using FCM to send pushes, but there's another external system I depend on which requires the APNs tokens. 

It would be really great to be able to get both via this plugin.
Is there a chance for this to happen?

**Comment by ncampuzano** [comment]
Hi! 

@miaowang Can you read APNS ID? I'm need  read APNS ID in iOS app, and in android App I need FCM Id. But always I get FCM ID, in two plataforms. I create #1982 for that. But if you have the awnser I really need it .

**Comment by vargaendre** [comment]
I created a fork https://github.com/vargaendre/phonegap-plugin-push
It returns both APNS and FCM tokens on iOS. There's a token type variable in the callback data which tells you which one it is.
