### ISSUE TITLE
Docs are misleading/incomplete regarding CocoaPods installation/setup steps

### ISSUE THREAD

**Issue by fredgalvao** [phonegap/phonegap-plugin-push#1716]
### Expected Behaviour

`Blank development environment` -> `Read the INSTALLATION docs` -> `Full working cordova+push project`

### Actual Behaviour

`???` -> `???`

Original "thread": https://github.com/phonegap/phonegap-plugin-push/commit/0cbb7a92946ac9febb5ac5960291928d539c0fe6#commitcomment-22063857

# Problem

@shazron @macdonst We need better docs for CocoaPod-related installation steps/dependencies.

**Comment by shazron** [comment]
I'll prepare a PR for this. @macdonst should I also send a PR for v1.x docs?

**Comment by macdonst** [comment]
@shazron that would be great.

**Comment by shazron** [comment]
See #1738 for v1 docs
