### ISSUE TITLE
5 Push Notifications In A Row

### ISSUE THREAD

**Issue by dmarcus1** [phonegap/phonegap-plugin-push#1717]
### Expected Behaviour
I send five push notifications in a row, one right after the other to mimic a phone call. The notification drawer should only have one notification at any given time. This means that the previous push notification has to get replaced with a newer push notification.

### Actual Behaviour
Right now if I send five push notifications in a row, all five show up in the notification drawer.

Also my custom sound is 6 seconds long because on iOS if the phone is locked then the custom sound limit is 30 seconds, but if the phone is unlocked then the limit seems to be about 6 seconds. That's why I have to send 5 push notifications. It's to make sure that the call length is 30 seconds. A problem I have with this is that sometimes one notification overlaps with another, and strange behavior occurs. Sometimes it works well. I want it to be consistent. My code waits 6 seconds before sending the next notification.

#### Steps to Reproduce 
Send five push notifications in a row while the app is quit out of or in the background and check the notification drawer. An app that does this is Facebook Messenger Video Calling.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.3.1

#### Cordova CLI version and cordova platform version
6.5.0

#### Plugin version
1.8.4

#### Sample Push Data Payload
{
	"aps": {
		"alert": "Calling",
		"sound": "sound.caf",
                "content-available": "0"
	}
}

#### Logs taken while reproducing problem
No logs taken

**Comment by macdonst** [comment]
@dmarcus1 you can't use push notifications to do what you want to do. Push notifications have no quality of service guarantees so the 5 pushes you send may arrive in any order, possibly all at the same time or badly delayed. 

It sounds like you are trying to build a VoIP app and you should look at CallKit from Apple.

**Comment by dmarcus1** [comment]
@macdonst Thanks for letting me know about CallKit, but is there a way to solve the first problem? Once I send one push notification it appears in the notification drawer. The next push notification sent should replace the first push notification in the notification drawer. Is there any way to delete a notification from the notification drawer? I can't call clearAllNotifications() if the app is quit out of. I can only call clearAllNotifications() when the app is in the background or in the foreground.

**Comment by fredgalvao** [comment]
@macdonst  I think @dmarcus1 is refering to something similar to `collapse_key`, but for iOS.
