### ISSUE TITLE
Notification click: activity already open

### ISSUE THREAD

**Issue by fgagneten** [phonegap/phonegap-plugin-push#1719]
I have an application with notifications that open a certain activity if I click them. I want that, if I click the notification and the activity is already opened, it's not started again, but just brought to front.

I read in stackoverflow that if solved setting the activity in launch mode "SingleTop".

The problem is that in cordova I only have the mainActivity. Also, I'm not sure if I change in the manifest SingleInstance to SingleTop is a good change (I think that cordova said that we have to use always SingleInstance)

Someone have a solution for that?

Thanks !

**Comment by macdonst** [comment]
@fgagneten no, you want `singleInstance`. Take a look at the docs: https://developer.android.com/guide/topics/manifest/activity-element.html#lmode

`singleInstance` will have the task brought to the front if it already exists so you should be getting the correct behaviour with the default cordova-android settings.
