### ISSUE TITLE
Push IOS

### ISSUE THREAD

**Issue by deluxeuo** [phonegap/phonegap-plugin-push#172]
friends..
  I'm using push for android and is working correctly.

with the same code tried to use in IOS, after setting up my certificates

for IOS I can also use the same SenderID google ??

For IOS configuration is different?

    var push = PushNotification.init({
        "android": {
            "senderID": "xxx"
        },
        "ios": {"alert": "true", "badge": "true", "sound": "true"}, 
        "windows": {} 
    });

I tried to use the same code and have the error in the console xocde

  Push Plugin failed register

**Comment by xavianaxw** [comment]
@deluxeuo from my knowledge, you do not need to use Google's Sender ID for iOS.

Instead, you need to set up your app id, certificates and provisioning profile accordingly. Try checking out this tutorial to do so. 

http://code.tutsplus.com/tutorials/setting-up-push-notifications-on-ios--cms-21925

Cheers

**Comment by deluxeuo** [comment]
I already set up the certificates to push, and he is ok to push.
Now I do not know how to use pushplugin for IOS, in your example does not use pushplugin / right phonegap?

**Comment by xavianaxw** [comment]
@deluxeuo I'm using phonegap-plugin-push for this one. It's a phonegap plugin but I'm building it with Ionic + Cordova 

Are you able to receive your notification?

**Comment by deluxeuo** [comment]
@xavianaxw 

It must use this setting for ios?

would look like?

var push = PushNotification.init({
            "android": {
                "senderID": "741175631277"
            },
            "ios": {"alert": "true", "badge": "true", "sound": "true"}, 
            "windows": {} 
        });
        

When you open the emulator, it request permission to push, but my console have it active
09/28/2015 08: 40: 15,338 AppTruck [719: 29060] Push Plugin failed register

**Comment by xavianaxw** [comment]
@deluxeuo Yes my settings are similar to yours. Have a look below.

```javascript
var push = PushNotification.init({ 
      "android": {
        "senderID": "xxxxxxxxxxxxxx"
      },
      "ios": {
        "alert": "true", 
        "badge": "true", 
        "sound": "true"
      } 
    });
```

Have you tried it on a LIVE device? Because I believe you are unable to register your device for push notification on an emulator. I may be wrong so someone correct me if this is the case.

**Comment by deluxeuo** [comment]
That was it! the unit I can have my Key

What is your push server?
I can not use the same gcm google?

**Comment by xavianaxw** [comment]
@deluxeuo GCM will only be for Google so for iOS you need to set up your certificates like the tutorial I shared with you.

I'm using AWS SNS as my push server.

**Comment by leonardopaiva** [comment]
@deluxeuo maybe this help https://github.com/phonegap/phonegap-plugin-push/issues/124

**Comment by deluxeuo** [comment]
Leonardo.
É Brasileiro ?
Estou em dúvidas como fazer o ios funcionar com GCM

Ja configurei o projeto no xcode para provisionamento push, também no meu developer apple, ja configurei para push.

Entrei no google 
https://developers.google.com/cloud-messaging/ios/client

e configurei o projeto, fiz upload do certificado (p12), e ele gerou um novo key.
Com esse key e o key do meu celular, ao enviar o post para gcm/sender.. ele da InvalidRegistration 

Existe alguma configuração extra?

**Comment by leonardopaiva** [comment]
@deluxeuo não tenho experiência fazendo o push funcionar com GCM para IOS, infelizmente não tenho muito como te ajudar, além de passar esse link, caso tu ainda não tenha visto:
https://github.com/phonegap/phonegap-plugin-push/issues/115

pelo que entendi isso ainda vai ser suportado pelo plugin, tu pode perguntar lá se alguém já conseguiu fazer com gcm.

**Comment by fredgalvao** [comment]
Como o @leonardopaiva disse, esse plugin (e é o mesmo caso pro PushPlugin), não dá suporte ao GCM pra iOS ainda. Acredito que ninguém tenha feito funcionar até agora.

**Comment by macdonst** [comment]
Okay, my Portuguese is beyond poor but I believe the issue has been resolved and @deluxeuo would like to push to iOS via GCM which this plugin does not yet support but is covered by #115.
