### ISSUE TITLE
$cordovaPushV5:notificationReceived event is not been executed

### ISSUE THREAD

**Issue by lfreneda** [phonegap/phonegap-plugin-push#1720]
### Expected Behaviour

Get code executed on `$rootScope.$on('$cordovaPushV5:notificationReceived' ..`

### Actual Behaviour

Push notifications is not executing code on `$rootScope.$on('$cordovaPushV5:notificationReceived', ..`

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 9+

#### Cordova CLI version and cordova platform version

    cordova --version  `6.3.0`
    cordova platform version ios `6.2.0`

#### Plugin version

`1.8.4`

#### Sample Push Data Payload

```
var apn = require("apn");

var options = {
    token: {
        key: "path/APNsAuthKey_XXXXX.p8",
        keyId: "key-id",
        teamId: "team-id"
    },
    production: true
};

var apnProvider = new apn.Provider(options);
var deviceToken = "token..";

var note = new apn.Notification();
note.contentAvailable = true;
note.expiry = Math.floor(Date.now() / 1000) + 3600;
note.sound = "ping.aiff";
note.alert = "Hi there!";
note.payload = {'messageFrom': 'Luiz Freneda'};
note.topic = "my-app-id";

apnProvider.send(note, deviceToken).then(function(result) {
    console.log(JSON.stringify(result));
    apnProvider.shutdown();
});

```

**Comment by fredgalvao** [comment]
You're using version `1.8.4` of the plugin, which is quite old. Do you have the option to update it to `1.10.3`?

Also, you're using Ionic Native to trigger that event on the root scope of angular. Do you have the option to retest it using the push plugin's raw api instead? That would eliminate the possibility of it being an issue with Ionic Native (in which case you'd need to open an issue with the guys at Ionic instead).

**Comment by lfreneda** [comment]
@fredgalvao Thanks for your reply.

I tried to use raw api with version `1.8.4` but I'm getting the same issue.

For android is working fine, this issue is specific with `ios`

The latest version is not an option right now.

Any tips? :(

Valeu demais sz

**Comment by fredgalvao** [comment]
@lfreneda (Boa noite :wink:) Did you get a proper answer (valid `registrationId`) for the register phase?
```js
    $cordovaPushV5.register().then(function(registrationId) {
      // here
    })
```

If so, can you provide logs from xcode for when the notification is sent to the device?

**Comment by fredgalvao** [comment]
Also, I strongly suggest you should try and do one of either:
- use the new ionic native push module instead of using the ngCordova pushNotificationsV5 plugin
- use the raw api from the push plugin itself ([here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md)). it's not so bad, I `promise` (not that we have a promisified api, pun intended).

Why? Because pushNotificationsV5 has not been updated for a year now:
https://github.com/driftyco/ng-cordova/blob/master/src/plugins/push_v5.js

**Comment by fredgalvao** [comment]
Follow-up to my suggestion:
It seems you can (with some work) make the new Ionic Native module work on a ionic v1 app:
https://forum.ionicframework.com/t/how-to-use-ionic-native-in-v1-app/59218/12

**Comment by lfreneda** [comment]
@fredgalvao not sure what fixed exactly, but thanks a lot for your help, u r GOD :angel: 

What fixed to me:

[✓] rewrite using raw api instead ngCordova pushNotificationsV5 wrapper
[✓] updating plugin to latest version
[✓] calling finish after processing push notifications
[✓] adding "content-available": 1 to my payload

``` 
var note = new apn.Notification({
    aps: {
        "alert": "Test background push",
        "content-available": 1,
        "force-start": 1,
        "badge": 1
    },
    notId: 2
});
```

**Comment by fredgalvao** [comment]
I'm glad I could help :wine_glass:
