### ISSUE TITLE
"CocoaPods was not found" when building for android on windows

### ISSUE THREAD

**Issue by mscherer82** [phonegap/phonegap-plugin-push#1721]
I got the following message when I build my app on windows:
```
  While removing plugins phonegap-plugin-push from Cordova project:
  CocoaPods was not found. Please install version 1.0.1 or greater from https://cocoapods.org/
```
As I understand this shouldn't happen on windows, right? The iOS Platform is **not** added to my project.

**Comment by fredgalvao** [comment]
This is a limitation to how cordova/plugman handles the installation/uninstallation process of a plugin.

The thing is:
- this plugin needs CocoaPods for the iOS platform since recently
- if you install the plugin, you're installing it for all available cordova platforms (android, browser, ios, windows)
- you can't pick which platforms you want it installed on
- plugman can't delay/postpone the installation of a foreign platform

At this point you get the error, which is cordova trying to install the plugin for your ios platform, and asking for cocoapods when it shouldn't.

If I'm correct in the assumptions above, it's an issue (feature-request) to be created on cordova itself, not on this plugin (there's nothing we can do, we really need cocoapods for ios).

**Comment by macdonst** [comment]
@shazron can you take a look at this warning message?

**Comment by mscherer82** [comment]
Thank you. It was my mistake thinking the ios platform wasn't added on my windows setup. What I have to do now is to have a different platform setups for android and ios.

**Comment by fredgalvao** [comment]
I'm still interested in @shazron 's answer on this, and seems like @macdonst is too, so I'll reopen this for now.

**Comment by fredgalvao** [comment]
I have been through this recently too, and if there's anything we can do to prevent plugman from failing, that'd be nice for multiplatform development.

**Comment by fredgalvao** [comment]
Follow-up to my scenario:
After installing up-to-date versions of `ruby`, `rubygem` and `git`, I was able to install `cocoapods` on linux normally (which I didn't know was possible/supported until this date). After that, and a `pod setup`, I was able to manipulate this plugin (push) normally under a linux cordova dev environment (*remove, add, prepare*) with close to no hiccups.
The only exception was some `xcuserdata` being generated under my username, which I will never use, but that's supposed to be ignored (.gitignore) anyway, so we're good.

I wonder if such a process can be achieved on a windows dev machine (`(ruby+rubygem+updated_git) -> cocoapods -> profit`)...

Also, I wonder if cordova/plugman really needs cocoapods to work on plugman+prepare levels...

**Comment by shazron** [comment]
The warning will only show if the iOS platform is installed (as @mscherer82 has stated later). Yes, unfortunately, it will do the reqs check if the plugin is installed for the iOS platform no matter what OS platform you are in.

I think it would be a good feature request to "skip" check_reqs for a platform that can't be built on your OS platform. It will be up to the Platform API of the Platform to determine this. We can start with the cordova-ios platform.

Specifically for Cocoapods `check_reqs` check, it should only return negative if the check is negative and the platform is `darwin` (macOS).

**Comment by shazron** [comment]
I'll add a feature request for cordova-ios@4.4.1

**Comment by shazron** [comment]
Filed https://issues.apache.org/jira/browse/CB-12856

**Comment by macdonst** [comment]
I'm going to close this and folks who are interested in the resolution should watch [CB-12856](https://issues.apache.org/jira/browse/CB-12856)

**Comment by andreszs** [comment]
Sorry to reopen the thread, but... while the status at issues.apache.org has been gracefully changed to **Resolved**, and the resolution changed to **Fixed**, the problem persists after installing version 1.10.5 released last month. The error is still thrown under Windows 8.1 when installing the plugin, in other words, nothing has been "_fixed_" nor "_resolved_".

 **Can anyone please explain the criteria used to label issues as fixed while they are clearly persisting?**

**Comment by fredgalvao** [comment]
@andreszs The issue has been marked to Fixed on jira, but the code containing the fix has yet to be released in a new version of cordova-ios.
