### ISSUE TITLE
[QUESTION] Receiving notifications at the same time with delay

### ISSUE THREAD

**Issue by fgagneten** [phonegap/phonegap-plugin-push#1722]
### Scenario:
1) I send a notification to my friend's phone. He didn't receive my notification.
2) Then he send me a notification to my phone, I receive the notification.
3) I send a notification to my friend's phone. He didn't receive my notification.
4) Then he send me a notification to my phone, I receive the notification.
5) I send a notification to my friend's phone. He didn't receive my notification.
6) Then he send me a notification to my phone, I receive the notification.
(no matter if the app is open or in background)

After few minutes, he receives 3 notifications **at the same time**.

He has a Moto G 4 Generation 
### Expected Behaviour
Receive one notification for each push I send
### Actual Behaviour
He receives notifications at the same tieme after a few minutes (with delay)

Those are my function in my php server:

    function sendNotification($registrationIds, $title, $message, $date){
		$log = CargarConfiguracionesIniciales();
		
		$msg =array(
                                        'title'		=> $title,
					'message'   		=> $message,
					'style'				=> "inbox",
					'summaryText'		=> "You have%n% notification",
                    'soundname'			=> "default",
                    'priority'			=> 2,
                    'no-cache'			=> 1,
                    'vibrate'           => 1,
                    'forceShow'         => true,
					'content_available' => 1,
					'typeNotification'	=> (int) 6,
					'date'		=> $date);
		
		$fields = array('registration_ids'  => $registrationIds,
						'data'              => $msg);

		$headers =array('Authorization: key=' . API_ACCESS_KEY,
						'Content-Type: application/json');
		
		return json_encode(enviar($headers, $fields, $log));

	}

**What-s going wrong here?**

Version: **phonegap-plugin-push 1.10.2 "PushPlugin"**

Thanks for helping!

**Comment by macdonst** [comment]
@fgagneten sorry this is not a problem with the push plugin. There is no guarentee in quality of service when you send push notifications. There is nothing I can do in the plugin to get GCM/FCM/APNS to deliver the messages in a timely manner.

**Comment by fgagneten** [comment]
But I received notification at the same time that he sent to me, so... the problem is not related with the services of GCM

**Comment by jcesarmobile** [comment]
The plugin shows the push notifications when they arrive, if you friend's phone display all of them at once after a while it's because of the device receive them all at once, not because the plugin. 
The device or Android version might have some battery saving feature that makes it not receive the push.

You can try to set the priority to "high" or "10", that should wake the device sooner, right now you are using 2, which is bellow normal (5)

**Comment by macdonst** [comment]
@jcesarmobile nope, 2 is maximum priority. https://github.com/phonegap/phonegap-plugin-push/blob/v2.0.x/docs/PAYLOAD.md#priority-in-notifications

@fgagneten you can capture some logs to see if the plugin is delaying the display of the messages but I highly doubt that to be the case.

**Comment by jcesarmobile** [comment]
Ah, sorry, I didn't notice it was part of the payload, but it's still worth looking into the priority param for FCM/GCM when sending the notification from the server to them.

**Comment by macdonst** [comment]
Yes, that would be useful. The `priority` I mentioned is for where it gets
displayed in the notification shade.
