### ISSUE TITLE
Missing Api.js Cordova 7

### ISSUE THREAD

**Issue by napcat** [phonegap/phonegap-plugin-push#1724]
### Expected Behaviour
Install plugin and windows cordova platform.

### Actual Behaviour
Get an error and the platform is not installed.

_Using cordova-fetch for cordova-windows@~5.0.0
Adding phonegap-plugin-push project...
Error: Your phonegap-plugin-push platform does not have Api.js_

### Reproduce Scenario (including but not limited to)
Add platform with the latest cordova version.

#### Steps to Reproduce 
cordova platform add windows
cordova platform add android

#### Cordova CLI version and cordova platform version
Node version: v6.10.2
Cordova version: 7.0.1
Android Cordova platform: 6.3.2
Windows Cordova platform: 5.0.0

#### Plugin version
phonegap-plugin-push 1.10.3 "PushPlugin"

**Comment by macdonst** [comment]
@napcat you get this error when you type `cordova platform add phonegap-plugin-push` when you actually want to type `cordova plugin add phonegap-plugin-push`.

**Comment by evromalarkey** [comment]
I have the same problem, this actually seems to be problem with cordova 7, this happens when you want to install all plugins and platform with `cordova platform add android`

https://stackoverflow.com/questions/43987230/cordova-platform-add-android-gives-error-your-android-platform-does-not-have-ap 
https://stackoverflow.com/questions/44042641/cordova-error-your-ios-platform-does-not-have-api-js

If anyone know how to fix this, I would appreciate it. I can't add CI to my cordova project because of this.

**Comment by Andreas-Halemba** [comment]
I get the same error when i run an cordova prepare

`Unable to load PlatformApi from platform. Error: Cannot find module '~/projects/cordova-app/node_modules/phonegap-plugin-push'
Error: Unhandled "error" event. (The platform "phonegap-plugin-push" does not appear to be a valid cordova platform. It is missing API.js. phonegap-plugin-push not supported.)`

Would be nice to get a hint where to look for.

**Comment by evromalarkey** [comment]
I fixed it with adding --no-fetch to cordova add platform

**Comment by lkrubner** [comment]
Same here.

If I try:

    ionic cordova platform add ios

I initially got:

    Using cordova-fetch for cordova-ios@4.4.0
    
    Adding phonegap-plugin-push project...
    
    Unable to load PlatformApi from platform. Error: Cannot find module     
    '/Users/lkrubner/projects/chet/peero.mobile-dev.2018-03-21/node_modules/phonegap-plugin-push'
    Error: Uncaught, unspecified "error" event. (The platform "phonegap-plugin-push" does not appear to be a valid cordova platform. It is missing API.js. phonegap-plugin-push not supported.)

but now: 


    $ ionic cordova platform add ios
    [WARN] Detected locally installed Ionic CLI, but it's too old--using global CLI.
    > cordova platform add ios --save
    Using cordova-fetch for cordova-ios@4.4.0
    
    Adding ios project...
    
    Creating Cordova project for the iOS platform:
    
    	Path: platforms/ios
    	Package: com.launchdeck.peeroapp
    
    	Name: Peero
    iOS project created with cordova-ios@4.4.0
    
    Installing "cordova-plugin-actionsheet" for ios
    
    Error during processing of action! Attempting to revert...
    
    Failed to install 'cordova-plugin-actionsheet': Error: Uh oh!
    ENOENT: no such file or directory, open '/Users/lkrubner/projects/chet/peero.mobile-dev.2018-03-21/plugins/cordova-plugin-actionsheet/www/ActionSheet.js'



And if I try:

    cordova plugin add phonegap-plugin-push

I get:

    Error during processing of action! Attempting to revert...
    Failed to install 'phonegap-plugin-push': Error: Uh oh!
    ENOENT: no such file or directory, open '/Users/lkrubner/projects/chet/peero.mobile-dev.2018-03-21/plugins/phonegap-plugin-push/www/push.js'

My ionic info:
    
    ionic info
    [WARN] Detected locally installed Ionic CLI, but it's too old--using global CLI.
    [ERROR] Error with ./node_modules/ionic-angular/package.json file: FILE_NOT_FOUND
    
    cli packages: (/usr/local/lib/node_modules)
    
        @ionic/cli-utils  : 1.19.2
        ionic (Ionic CLI) : 3.20.0
    
    global packages:
    
        cordova (Cordova CLI) : 7.1.0 
    
    local packages:
    
        @ionic/app-scripts : 2.1.4
        Cordova Platforms  : android 6.3.0 browser 5.0.3 ios 4.4.0
        Ionic Framework    : not installed
    
    System:
    
        ios-deploy : 1.9.2 
        Node       : v6.5.0
        npm        : 5.8.0 
        OS         : macOS High Sierra
        Xcode      : Xcode 9.2 Build version 9C40b 
    
    Environment Variables:
    
        ANDROID_HOME : not set
    
    Misc:
    
        backend : pro
