### ISSUE TITLE
Provide default for applicationServerKey

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-plugin-push#1725]
### Expected Behaviour

If you forget to include the `browser` option to `init` the Push Plugin should just use proper defaults and not error out.

### Actual Behaviour

If you forget to include the `browser` option to `init` the Push Plugin it throws an error prevent you from getting a registration ID.

#### Steps to Reproduce 

Call PushNotification.init():

```
  var push = PushNotification.init({
    "android": {
        "senderID": "Your GCM ID"
    },
    "ios": {
      "sound": true,
      "alert": true,
      "badge": true
    },
    "windows": {}
  });
```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Browser

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Chrome

#### Cordova CLI version and cordova platform version

    cordova --version 6.5.0
    cordova platform version browser 4.1.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.10.3

#### Sample Push Data Payload

n/a

#### Sample Code that illustrates the problem

see steps to reproduce 

#### Logs taken while reproducing problem

```
push.js:34 Uncaught TypeError: Cannot read property 'applicationServerKey' of undefined
    at new PushNotification (push.js:34)
    at Object.window.PushNotification.init ((index):121)
    at setupPush (my-app.js:352)
    at Channel.deviceIsReady (my-app.js:77)
    at Channel.fire (cordova.js:777)
    at cordova.js:231
```

**Comment by tomilofano** [comment]
Hello @macdonst I had this issue running on the browser.
I understand the reason of this issue but I can't include the browser option to init the Push Plugin.

 ```
 private notifications():void {
    this.platform.ready().then(() => {
      const options: PushOptions = {
       android: {
         senderID: 'XXXXXXXXXXX',
         vibrate: true,
       },
       ios: {
          senderID: XXXXXXXXXXX',
          alert: 'true',
          badge: true,
          sound: 'true'
       },
       windows: {},
       browser: { senderID: 'XXXXXXXXXXX'},
      }; 
```
and I get Compilation error because browser is not assignable: 

```
export interface PushOptions {
    ios?: IOSPushOptions;
    android?: AndroidPushOptions;
    windows?: any;
}
```
The browser is not declared......

Plugin version
```
cordova plugin version | grep phonegap-plugin-push
phonegap-plugin-push 1.10.5 "PushPlugin"
```

Cordova CLI version and cordova platform version
```
cordova --version 7.0.1
cordova platform version browser 4.1.0
```
