### ISSUE TITLE
Lack of force-start functionality on iOS. Suggest more explicit documentation.

### ISSUE THREAD

**Issue by TrevorPage** [phonegap/phonegap-plugin-push#1726]
I have only just realised that the `force-start` option is specific to the Android platform, and no equivalent appears to exist in the iOS source. This didn't occur to me before (even though I now see it's obviously only detailed under the Android section). This might mean a huge headache, because our architecture is based on my (wrong) assumption that messages can always be processed by our application handler on either platform, even if it means force-starting the application.

If I'm correct that only Android provides support for `force-start` then firstly can I suggest adding a very explicit sentence about this in https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#push-message-arrives-with-app-in-background. As I see it, `force-start` essentially adds an additional decision diamond at the bottom-right of the flowchart diagram -- but only for Android.

Secondly, would it be possible to provide some wording regarding why this option isn't available on iOS please? Perhaps it's a platform limitation (the plugin cannot start up the application), or for whatever reason it isn't actually needed on iOS?

**Comment by jcesarmobile** [comment]
On iOS the system receives the push notifications, not your app.
If your app is open, you will get the information, if your app is closed or in background the system will show it on the notification center. 

But I think content-available should wake the app in iOS even if it was fully closed.

**Comment by TrevorPage** [comment]
Thanks @jcesarmobile . I've now realised that the issue I've opened here is related to https://github.com/phonegap/phonegap-plugin-push/issues/158 which I also participated in.

Unfortunately I'm an Android user/developer only, and it's only at this late stage that the iOS developer has raised this. I still don't yet know exactly what the iOS behaviour is.

**Comment by macdonst** [comment]
@TrevorPage if you set content-available to `1` on iOS it should wake up a stopped app to run your code with a max timeout at 30 seconds. Give that a try and let us know. In the meantime, I'll look into your docs suggestions.

**Comment by TrevorPage** [comment]
@macdonst Many thanks. I that in the documentation, but I admit I assumed that it referred to an application that is currently sat in the background, as opposed to stopped/killed. I'll ask our iOS developer to try this.

I admit I'm not familiar with how iOS application lifecycles compare with Android, in terms of when or for how long an application ends up in background state.

If it turns out that an equivalent of `force-start` is needed, do you think it is technically possible on iOS? I do note the hoops you had to jump through to make it work on Android (particularly the Cordova Activity change).

**Comment by macdonst** [comment]
@TrevorPage to the best of my knowledge it is not possible on iOS to create `force-start` functionality.

**Comment by macdonst** [comment]
@TrevorPage I'm not sure how to document this better. The `force-start` functionality is only documented under the Android payload details. It seems redundant to add a section in iOS to say it isn't supported, especially since it would require me to add a bunch of sections under iOS to say a bunch of things are not supported on iOS.

Just trying to figure out the best way to handle this.

**Comment by macdonst** [comment]
@TrevorPage that's good feedback. I should split the section into separate .md files for Android and iOS.

**Comment by snakeman21** [comment]
If it's for VoIP purposes, you can use https://developer.apple.com/documentation/pushkit to wake up your app.

**Comment by macdonst** [comment]
Upon further reflection I'm not going to change the docs to split out Android and iOS as that would break existing links to those doc pages/references.
