### ISSUE TITLE
Ionic 2 push plugin errors on xcode

### ISSUE THREAD

**Issue by devopshimanshu** [phonegap/phonegap-plugin-push#1728]
I am developing an app on Ionic 2 where i have to implement push notification, i have implemented it successfully for android however i am an unable to get the same code working on xcode(iOs). When i compile the file, i get below mentioned 2 errors:

`FieldTasks/Plugins/phonegap-plugin-push/AppDelegate+notification.m:173:60: Property 'types' cannot be found in forward class object 'UIUserNotificationSettings'  `

`/Users/aparna/Desktop/FieldTaskBackup/myApp/platforms/ios/FieldTasks/Plugins/phonegap-plugin-push/AppDelegate+notification.m:173:69: Use of undeclared identifier 'UIUserNotificationTypeNone'; did you mean 'UIRemoteNotificationTypeNone'?`

I have tried many suggestions like npm update, cordova platform remove ios, cordova platform add ios but no luck

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
