### ISSUE TITLE
Has anyone tested this plugin on windows?

### ISSUE THREAD

**Issue by sd-roop** [phonegap/phonegap-plugin-push#173]
Want to know if this Plugin has been verified on Windows? Details and links will be of great help

**Comment by rakatyal** [comment]
@sd-roop: Yes the plugin has been tested on windows. The basic sample usage is mentioned in the Readme. 
For further details and usage you can refer to the msdn documentation here:
https://msdn.microsoft.com/en-us/library/windows/apps/hh913756.aspx
