### ISSUE TITLE
The page is opened 2 times, if you open it from recieve push handler

### ISSUE THREAD

**Issue by razinalexrazinalex** [phonegap/phonegap-plugin-push#1734]
Hello.
My code to handle push notifications:

```
 this.push.rx.notification()
            .subscribe((msg) => {
                this.navCtrl.push(this.ordesPage);
            });
    }
```

I send one push notification, but this code open **TWO** ordesPage.
Why? How can i prevent this?

ps. this only occurs when ordesPage has ion-tabs

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

Actually this looks like a question better asked on the Ionic forums.
