### ISSUE TITLE
Not getting push notifications on iOS devices

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [phonegap/phonegap-plugin-push#1743]
### Message should receive on iOS devices
All notification's status coming enqueued in response of post request of api.ionic.io/push
and notification's status is Locked.  Can anybody please tell where I am wrong, I believe I configured security profiles very well for iOS

Here is the request I made to api.ionic with POST
  https://api.ionic.io/push/notifications
       response  

> 
> 
>     {
>         "data":
>         {
>             "config":
>             {
>                 "tokens":
>                 [
>                     "mytoken"
>                 ],
>                 "profile": "ios_profile",
>                 "notification":
>                 {
>                     "android":
>                     {
>                         "title": "Hey",
>                         "message": "Hello Android!"
>                     },
>                     "title": "Hi",
>                     "message": "Hello world!",
>                     "ios":
>                     {
>                         "title": "Howdy",
>                         "message": "Hello iOS!"
>                     }
>                 }
>             },
>             "uuid": "8274e33f-5919-4f99-ace3-ca453091fed4",
>             "app_id": "21aa4773",
>             "state": "enqueued",
>             "status": "open",
>             "created": "2017-05-26T05:50:29.824964+00:00"
>         },
>         "meta":
>         {
>             "version": "2.0.0-beta.0",
>             "request_id": "190b4293-4355-48b1-c8b9-7e321bf74c0a",
>             "status": 201
>         }
>     }

Get request of
https://api.ionic.io/push/notifications
response

```
{
  "meta": {
    "request_id": "b25833b8-6e87-4ca8-cc5c-9218ac83ce80",
    "status": 200,
    "version": "2.0.0-beta.0"
  },
  "data": [
    {
      "uuid": "8274e33f-5919-4f99-ace3-ca453091fed4",
      "status": "locked",
      "created": "2017-05-26T05:50:29.824964+00:00",
      "app_id": "21aa4773",
      "config": {
        "profile": "ios_profile",
        "tokens": [
          "e0bb97a60ce3a506c13e8fe13acc7c3f8838cacb0039359242c3548dfb32b8a5"
        ],
        "notification": {
          "ios": {
            "title": "Howdy",
            "message": "Hello iOS!"
          },
          "title": "Hi",
          "message": "Hello world!",
          "android": {
            "title": "Hey",
            "message": "Hello Android!"
          }
        }
      },
      "state": "enqueued"
    },
    {
      "uuid": "e7e655f7-ed19-4b25-8fc1-0c22fb561b0b",
      "status": "locked",
      "created": "2017-05-26T05:45:59.340849+00:00",
      "app_id": "21aa4773",
      "config": {
        "profile": "ios_profile",
        "tokens": [
          "e0bb97a60ce3a506c13e8fe13acc7c3f8838cacb0039359242c3548dfb32b8a5"
        ],
        "notification": {
          "ios": {
            "title": "Howdy",
            "message": "Hello iOS!"
          },
          "title": "Hi",
          "message": "Hello world!",
          "android": {
            "title": "Hey",
            "message": "Hello Android!"
          }
        }
      },
      "state": "enqueued"
    },
    
}
```

**Comment by macdonst** [comment]
@Gurjit-ONEBCG you are not following the issue template and I believe this should be a question for the Ionic forums.
