### ISSUE TITLE
The plugin installs npm in my local node_modules

### ISSUE THREAD

**Issue by alexghr** [phonegap/phonegap-plugin-push#1744]
### Expected Behaviour
The `2.0.0-rc3` version of the plugin explicitly depends on the `npm` package ([link]). This needlessly adds complications to my `node_modules/` folder.

Is this an intended change?

### Actual Behaviour
Plugin should not depend on `npm` as that is a global package.

### Reproduce Scenario (including but not limited to)
-

#### Steps to Reproduce 
1. Install plugin
2. npm ls npm

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
-

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
-

#### Cordova CLI version and cordova platform version
-

#### Plugin version
v2.0.0-rc3

#### Sample Push Data Payload
-

#### Sample Code that illustrates the problem
-

#### Logs taken while reproducing problem
-

[link]: https://github.com/phonegap/phonegap-plugin-push/blob/master/package.json#L77

**Comment by macdonst** [comment]
Nope, that looks like a mistake that I will remedy shortly.

**Comment by alexghr** [comment]
Thanks for that! When is it getting released to npm?

**Comment by linguamachina** [comment]
@macdonst Is this likely to see a release soon? This is a major blocker for our project as it breaks `npm shrinkwrap`

**Comment by macdonst** [comment]
@linguamachina let me see if I can post a RC4 on hotel wifi.

**Comment by macdonst** [comment]
@linguamachina I bumped a rc4 you can use.
