### ISSUE TITLE
[android] Notification shown on taskbar even with app in foreground

### ISSUE THREAD

**Issue by andreszs** [phonegap/phonegap-plugin-push#1746]
### Expected Behaviour
**Notification received when app is in foreground**: It must NOT be shown in the notification bar. 

### Actual Behaviour
Notification is incorrectly shown in notification bar even with app currently active.
**It only works correctly if** the app has NOT been closed, or if I have obtained a new registration ID. **After the app is closed with navigator.app.exitApp() the notification is never again handled internally by the app**.

#### Steps to Reproduce 
Create app with latest plugin version 1.10.4 in Visual Studio 2015 and send default push without the content-available parameter.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
    Android 4.2.2, Android 5.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
    Samsung, BLU, Motorola

#### Cordova CLI version and cordova platform version
    6.5.0

#### Plugin version
    1.10.4 

#### Sample Push Data Payload
_PHP array sent as 'data' parameter:_

$data['msgtype'] = utf8_encode('new_msg');
$data['count'] = '0'; // badge counter
$data['title'] = utf8_encode($titulo);
$data['message'] = utf8_encode($texto);
$data['vibrationPattern'] = array(0, 300);

**Comment by macdonst** [comment]
@andreszs you shouldn't ever call `navigator.app.exitApp()`. That was just a bad idea we implemented 7 years ago that I'm still paying for.

You didn't give me the parameters you pass to PushNotification.init().

**Comment by Nelo-cool** [comment]
Okay, if i shouldn't ever call navigator.app.exitApp() then how to send application in background? Without navigator.app.exitApp(). I will push 'Back button' and call wtf?:)

**Comment by macdonst** [comment]
@Nelo-cool yeah, let your user click the back button or home button to put your app in the background. Calling `navigator.app.exitApp()` will finish your activity. It's much better to just put the app in the background and let the Android OS handle it. The app won't be using resources and if Android needs the resources it will garbage collect it for you.

**Comment by Nelo-cool** [comment]
But when i clicked back button in my phone nothing happened:) Application on top) (Android 5)

**Comment by Nelo-cool** [comment]
Thanks for your answers!

**Comment by andreszs** [comment]
Thanks for the feedback, I have implemented the **cordova-plugin-appminimize** plugin.
