### ISSUE TITLE
cordova build ios failing ( Error: Error code 65 for command)

### ISSUE THREAD

**Issue by jrmcdona** [phonegap/phonegap-plugin-push#1747]
Hi-
Installed this plugin today and not able to get "cordova build ios" or "ionic cordova build ios" to compile anymore.   When I look at the logs, I just cannot tell what is going on.  Logs are included below.   Do you think this error has anything to do with the plugin?   I have included my logs and my version info.  

Any pointers would be great.

#### Cordova CLI version and cordova platform version
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v7.4.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.12 

#### Plugin version
 <plugin name="phonegap-plugin-push" spec="^1.10.4">

#### Logs taken while reproducing problem

✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.
        
[ERROR] An error occurred while running cordova build ios (exit code 1):
        
        (truncated) ... /IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a normal armv7\ arm64
            cd /Users/jordanmc/Documents/src/Responder/Microsoft.Responder/platforms/ios/CordovaLib
            export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/jordanmc/Library/Android/sdk/platform-tools/"
            /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static /Users/jordanmc/Library/Developer/Xcode/DerivedData/Responder-fqrtzjccigiirifxumxywaateeeg/Build/Intermediates/ArchiveIntermediates/Responder/IntermediateBuildFilesPath/CordovaLib.build/Debug-iphoneos/CordovaLib.build/Objects-normal/armv7/libCordova.a /Users/jordanmc/Library/Developer/Xcode/DerivedData/Responder-fqrtzjccigiirifxumxywaateeeg/Build/Intermediates/ArchiveIntermediates/Responder/IntermediateBuildFilesPath/CordovaLib.build/Debug-iphoneos/CordovaLib.build/Objects-normal/arm64/libCordova.a -o /Users/jordanmc/Library/Developer/Xcode/DerivedData/Responder-fqrtzjccigiirifxumxywaateeeg/Build/Intermediates/ArchiveIntermediates/Responder/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a
        
        Strip /Users/jordanmc/Library/Developer/Xcode/DerivedData/Responder-fqrtzjccigiirifxumxywaateeeg/Build/Intermediates/ArchiveIntermediates/Responder/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a
            cd /Users/jordanmc/Documents/src/Responder/Microsoft.Responder/platforms/ios/CordovaLib
            export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/jordanmc/Library/Android/sdk/platform-tools/"
            /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -S /Users/jordanmc/Library/Developer/Xcode/DerivedData/Responder-fqrtzjccigiirifxumxywaateeeg/Build/Intermediates/ArchiveIntermediates/Responder/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a
        
        SetOwnerAndGroup jordanmc:staff /Users/jordanmc/Library/Developer/Xcode/DerivedData/Responder-fqrtzjccigiirifxumxywaateeeg/Build/Intermediates/ArchiveIntermediates/Responder/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a
            cd /Users/jordanmc/Documents/src/Responder/Microsoft.Responder/platforms/ios/CordovaLib
            export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/jordanmc/Library/Android/sdk/platform-tools/"
            /usr/sbin/chown -RH jordanmc:staff /Users/jordanmc/Library/Developer/Xcode/DerivedData/Responder-fqrtzjccigiirifxumxywaateeeg/Build/Intermediates/ArchiveIntermediates/Responder/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a
        
        SetMode u+w,go-w,a+rX /Users/jordanmc/Library/Developer/Xcode/DerivedData/Responder-fqrtzjccigiirifxumxywaateeeg/Build/Intermediates/ArchiveIntermediates/Responder/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a
            cd /Users/jordanmc/Documents/src/Responder/Microsoft.Responder/platforms/ios/CordovaLib
            export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/jordanmc/Library/Android/sdk/platform-tools/"
            /bin/chmod -RH u+w,go-w,a+rX /Users/jordanmc/Library/Developer/Xcode/DerivedData/Responder-fqrtzjccigiirifxumxywaateeeg/Build/Intermediates/ArchiveIntermediates/Responder/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a
        
        === BUILD TARGET Responder OF PROJECT Responder WITH CONFIGURATION Debug ===
        
        Check dependencies
        No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "9KBH5RKYEW" with a private key was found.
        Code signing is required for product type 'Application' in SDK 'iOS 10.3'
        
        ** ARCHIVE FAILED **
        
        
        The following build commands failed:
        	Check dependencies
        (1 failure)
        Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/jordanmc/Documents/src/Responder/Microsoft.Responder/platforms/ios/cordova/build-debug.xcconfig,-workspace,Responder.xcworkspace,-scheme,Responder,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,Responder.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/jordanmc/Documents/src/Responder/Microsoft.Responder/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/jordanmc/Documents/src/Responder/Microsoft.Responder/platforms/ios/build/sharedpch

**Comment by juancafe4** [comment]
Open your project in Xcode check automatic sigining. If that does not work remove the ios platform and install cordova-ios 4.4.0 ionic cordova platform ios@4.4.0.

**Comment by fredgalvao** [comment]
@juancafe4 is right.
@jrmcdona Check this section of your logs:
```
No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "9KBH5RKYEW" with a private key was found.
    Code signing is required for product type 'Application' in SDK 'iOS 10.3'
```
That shows your project is not properly configured on the certificate/development_team_id/provisioning_profile.

**Comment by jrmcdona** [comment]
Got past that, I was focused on a different error and didn't realize my provisioning profile was changed after I redone the ios platform and needed a reset.  Will open new issue.  Thanks!

**Comment by brentrichison** [comment]
@juancafe4, switching from 4.5.x to 4.4.0 worked. Can you shed light on as to why it worked?

**Comment by brunolm** [comment]
iOS

- Open `platforms/ios` on XCode
- Find & Replace `io.ionic.starter` in all files for a unique identifier
- Click the project to open settings
- Signing > Select a team
- Go to your device Settings > General > DeviceManagement
  - Trust your account/team
- `ionic cordova run ios --device --livereload`

**Comment by fssrepository** [comment]
How to set this command to cordova cli?

xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

**Comment by bhumin3i** [comment]
@fredgalvao where certificate/development_team_id/provisioning_profile is located?

**Comment by 1pocketaces1** [comment]
@fredgalvao what is the error code 65 exactly? I am getting the same code with "check dependencies" and "archive failed." However, I have made builds before and the only change before this one that failed was I added two page to the app using "ionic generate page [pageName]" and added ModalController to a page (yes I added them in my app.component and app.module)

**Comment by fredgalvao** [comment]
@1pocketaces1 I don't think I can answer that (about the code 65 error, specifically). The issue at hand (the original issue on this thread) was regarding an unconfigured provisioning_profile, or an invalid certificate. If I had to guess, if you really didn't change a single thing on your iOS shell project, I'd say your certificate expired.

**Comment by 1pocketaces1** [comment]
Wow such a simple solution thank you! This is my first app on iOS and I am not used to keeping that updated!
