### ISSUE TITLE
Is possible to get silent notifications using GCM on iOS?

### ISSUE THREAD

**Issue by HectorFGarcia** [phonegap/phonegap-plugin-push#1749]
Docs says you can get silent notifications if you omit the 'alert' propety while you are using APNS, but what if I using GCM? How can I get silent notifications if there isn't any 'alert' property to omit?

**Comment by jcesarmobile** [comment]
content_available is translated into iOS content-available, set it to true to send silent push notifications.

https://developers.google.com/cloud-messaging/ios/client
https://developers.google.com/cloud-messaging/http-server-ref
