### ISSUE TITLE
IOS custom push sound when app is in background

### ISSUE THREAD

**Issue by tmakaro** [phonegap/phonegap-plugin-push#175]
Is having a custom push sound when app is in the background still a problem with this new plugin? The old plugin was never able to do it. The only way I have been able to do it is with a pure objective c program.

**Comment by macdonst** [comment]
@tmakaro Yes, you can play a sound on iOS. Check out issue #17 for more information.

**Comment by tmakaro** [comment]
I can't get it to work. alarm.caf works when app is in the forground only. When the app is in the background, all I get is the standard beep.
Where is my alarm.caf file supposed to be located? Am I running the wrong version?

**Comment by tmakaro** [comment]
It has something to do with what IOS thinks my root folder is and what cordova thinks my root folder is.

The following works when I store alarm.caf in the www folder: (works when app is in forground but not when app is in background)

    {
        "aps": {
            "alert": "test alarm", 
            "sound": "alarm.caf"
        }
    }

     push.on('notification', function (data) {
         if (data.sound) {
             var snd = new Media(data.sound);
             snd.play();
         }
     });

This change below makes it work when the app is in the background but not when it is in the forground:

    {
        "aps": {
            "alert": "test alarm", 
            "sound": "www/alarm.caf"
        }
    }

**Comment by macdonst** [comment]
@tmakaro Yeah, iOS assumes that the sound file is in root folder of your app. Using:

```
{
    "aps": {
        "alert": "test alarm", 
        "sound": "www/alarm.caf"
    }
}

push.on('notification', function (data) {
     if (data.sound) {
         var snd = new Media(data.sound.substring(4));
         snd.play();
     }
 });
```

Should work in both background and foreground.

**Comment by tmakaro** [comment]
@macdonst Yes it does. Thank you!
