### ISSUE TITLE
Display notification when app is in foreground on IOS

### ISSUE THREAD

**Issue by crystal98** [phonegap/phonegap-plugin-push#1750]
### Expected Behaviour
When an app is in foreground, it can receive push notification and display it notification center for ios 10 and above. 
### Actual Behaviour
when app is in foreground and receiving push notification, the notification is not shown
xcode shows many deprecated warning for UIRemoteNotificationType. Ex. 
 'UIRemoteNotificationTypeNone' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ios 10 +
#### Cordova CLI version and cordova platform version

    cordova --version                                    6.4.0
    cordova platform version ios                     4.3.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.10.4

**Comment by fredgalvao** [comment]
As stated in the docs ([source](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md)), foreground events do *not* trigger a notification to be shown on the OS UI

```
# Push message arrives with app in foreground

The push plugin receives the data from the remote push service
and calls all of your notification event handlers.
The message is not displayed in the devices notification center
as that is not normal behaviour for Android or iOS.
```

If you want to show a notification after you receive the event from the plugin, you'll need to handle it yourself with, for example, the [local notifications plugin](https://github.com/katzer/cordova-plugin-local-notifications), or any other html UI you prefer.

**Comment by macdonst** [comment]
@fredgalvao actually this is now possible on iOS10. 

@crystal98 go up vote https://github.com/phonegap/phonegap-plugin-push/issues/421 and add a comment.

**Comment by fredgalvao** [comment]
@macdonst  Will still require the `forceShow` flag, right?

**Comment by crystal98** [comment]
IOS 10 has UserNotitications framework and UIRemoteNotification is deprecated in IOS 8.0. UserNotifications provide methods that allow apps turn on notifications show when apps are in foreground.

**Comment by macdonst** [comment]
@fredgalvao yeah, I would put this behind the forceShow flag.
