### ISSUE TITLE
Problems with phonegap build

### ISSUE THREAD

**Issue by carlosquin** [phonegap/phonegap-plugin-push#1751]
I currently use Phonegap Build:
PhoneGap (iOS / Android / Windows)
cli-6.5.0 (4.3.1 / 6.1.2 / 4.4.3)

But it generates this problem during the build:

> Fetching plugin "https://github.com/phonegap/phonegap-plugin-push.git" via git clone
> Using shallow clone
> Repository "https://github.com/phonegap/phonegap-plugin-push.git" checked out to git ref "master" at "f3e94bb".
> Installing "phonegap-plugin-push" at "2.0.0-rc3" for android
> Plugin doesn't support this project's cordova-android version. cordova-android: 6.1.2, failed version requirement: >=6.2.1
> Skipping 'phonegap-plugin-push' for android

And I did not work with the notifications, until a few weeks ago I worked, but a few days to stop doing it and indicates the errors mentioned above, simply omits it indicating that it is not compatible.

The load in xml was done with:

`<plugin spec="https://github.com/phonegap/phonegap-plugin-push.git" source="git" />`

**Comment by fredgalvao** [comment]
You're installing the plugin with a `spec` pointing to the git repo url, which means it'll install the latest version of the `master` branch from the repository everytime it builds on PhonegapBuild. That means you're getting the newly merged 2.0.x code that is still experimental and not confirmed to be production ready.

Other than that, your specific issue is very clear: your project specifies a `<framework>` tag for Android with a version(6.1.2) lower than what this plugin requires(>=6.2.1).

You need to either:
- upgrade your project to a version of cordova-android that satisfies this plugin's requirements
- downgrade the plugin on your project to a version that allows your version of `cordova-android` such as `1.10.4`.
