### ISSUE TITLE
How to get required senderID for Android?

### ISSUE THREAD

**Issue by rolinger** [phonegap/phonegap-plugin-push#1752]
### Expected Behaviour
auto retrieve sender ID for android.  How else do we get the deviceID?  Using cordova-plugin-sim you can retrieve the users deviceID...but because that has "DANGEROUS" permissions it requires the user to allow it - what happens if the user doesn't allow it?  

### Actual Behaviour
Not able to get deviceID which is to be used as the senderID.  If I don't add the senderID to the plugin returns the error:
`No value for senderID`

### Reproduce Scenario (including but not limited to)
```
function pushNotification() {
  var push = PushNotification.init({
    "android": {
        "senderID" : "usersDeviceID"  // but where from?
    },
   ...
}
```

#### Steps to Reproduce 
See above

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
LG K20 Plus

#### Cordova CLI version and cordova platform version
    Cordova: 6.5.0
    Cordova platform Android: 6.1.2

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by fredgalvao** [comment]
The `senderId` comes from your GCM application setup. It has nothing to do with the device or the user.

**Comment by rolinger** [comment]
I was going off of these instructions: http://macdonst.github.io/push-workshop/module2.html

So what exactly is the GCM ID then?  I can't find the reference now but while researching all this further I came across the "senderID" is the phones deviceID that is why I was using it.  I have already created a FCM API Access Key and use that on my server PHP script to send the message to GCM/FCM to relay the push message to the user device.    Seems I have almost all of it working - except feeding it the wrong senderID.

**Comment by rolinger** [comment]
Hmmmm...I think I found it.

**Comment by rolinger** [comment]
Ok...I think that was it.  However, I have now sent two messages...one from the FCM console and the other from my script - both say completed however my phone has not received any push messages.  The app is running too...yet no messages.  What should I be looking at next?

From FCM Developer Console: 
`Test #4         check Completed       Jun 1, 2017  10:08 PM`

From my PHP script on my server:
`{"multicast_id":5261982594620799590,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1496369445320156%94806eb5f9fd7ecd"}]}`

**Comment by rolinger** [comment]
don't know what happened between last night and today, it wasn't working and I went to bed.  Woke up this morning tested it again and now its working.  Wondering if it had something to do with app/FCM registration being propagated or something...

**Comment by d3w201** [comment]
so what do you put inside the senderID value?

**Comment by raessafathulalim** [comment]
@rolinger 

> don't know what happened between last night and today, it wasn't working and I went to bed. Woke up this morning tested it again and now its working. Wondering if it had something to do with app/FCM registration being propagated or something...

thanks it's work for me! really, i am serious!  I went to bed and  tested it again and now its working.

**Comment by macdonst** [comment]
@d3w201 if you are using version 1.x you need to add the sender ID. See the older docs:

https://github.com/phonegap/phonegap-plugin-push/blob/v1.x/README.md
