### ISSUE TITLE
How to set badge self-increasing on iOS?

### ISSUE THREAD

**Issue by YingshanDeng** [phonegap/phonegap-plugin-push#1753]
How to set badge self-increasing when receive a notification? Thank you!

**Comment by macdonst** [comment]
@YingshanDeng the plugin doesn't handle increasing the badge number automatically it will only set the badge to the value you specify in the APNS payload.

https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html
