### ISSUE TITLE
System Sound as Push Notification Sound

### ISSUE THREAD

**Issue by HainaAlfonso** [phonegap/phonegap-plugin-push#1754]
Hello!

I am developing an application using phonegap and I am having a hard time figuring out how I can use the device's system sound as push notification sound. Customizing the sound is easy as I have made it working on my app already (both working in iOS and android). I am also aware that if I want a sound file to be used as a notification sound, it has to be inside the www folder. But I found this [blog](https://www.hoessl.eu/2015/04/choosing-androids-system-sounds-for-cordova-push-notifications-using-native-configuration-screens/) and made me hope that what I want is possible but the problem is I do not how to implement it in phonegap and make it work in phonegap Build (I'm a newbie). Also, I'm using this [plugin](https://github.com/Hiraqui/cordova-plugin-ringtone) to fetch all the ringtones from a device for display purposes.

I made it work using this code in my index.js by setting the sound in the payload (on the server side) to be empty.
```
push.on('notification', function(data) {
        navigator.notification.confirm(
            data.message,
            function()
            {
                if ((buttonIndex==1) && data.additionalData.url)
                    cordova.InAppBrowser.open(data.additionalData.url, '_blank', 'location=no,toolbar=no'); 
            },
            data.title,
            ['OK', 'Cancel']
        );
         
        if ( data.sound )
        {
            var ringtone_name = localStorage.getItem("ringtone_name");
            if (ringtone_name == "Default")
            {
                var snd = new Media( dict_ringtones[ringtone_name] );
                snd.play();
            }
            else
                cordova.plugins.NativeRingtones.playRingtone( dict_ringtones[ringtone_name] );
        }
    });
```
But the problem here is that it only works if the app is open or in the background. When the app is closed, this doesn't get executed.

Vendor, platform and version: Samsung A8 with android 5.1.1. 
Plugin in config.xml: ( the X's has a value)
```
<plugin name="phonegap-plugin-push" spec="~1.10.3">
        <variable name="SENDER_ID" value="XXXXXXXXXXXX" />
</plugin>
```
Sample Push Data Payload: I am using [this](https://gist.github.com/prime31/5675017) as a reference on the server side. Also I am using firebase cloud messaging.

Please help me!

**Comment by fredgalvao** [comment]
According to the [payload documentation on the sound section for android](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#sound), you're able to send a payload/notification such as:
- on **android**
```json
{
    "registration_ids": ["my device id"],
    "data": {
    	"title": "Default",
    	"message": "Plays default notification sound",
    	"soundname": "default"
    }
}
```
- on **iOS**
```json
{
    "aps": {
        "alert": "Test sound",
        "sound": "default"
    }
}
```

> which will play the phones default notification sound.

**Comment by macdonst** [comment]
Closing as considered answered.
