### ISSUE TITLE
Failed to apply plugin [id 'com.google.gms.google-services']

### ISSUE THREAD

**Issue by Ziv-Barber** [phonegap/phonegap-plugin-push#1756]
The last version making this error:

Failed to apply plugin [id 'com.google.gms.google-services']

Lucky I saved the old version.
Need to stop using the latest version and used only proved saved version of the plugins.

**Comment by jcesarmobile** [comment]
By last you mean last published? last master?

**Comment by felaray** [comment]
same here.can you share old version? thx

**Comment by fredgalvao** [comment]
There's no need to save/shared older versions of this plugin. They're all available on NPM automatically. You just need to
- look at the [releases section](https://github.com/phonegap/phonegap-plugin-push/releases)
- find the version you want (`1.10.4` for example)
- specify it during install time:
`cordova plugin add --save phonegap-plugin-push@1.10.4 --variable SENDER_ID="abc"`

**Comment by felaray** [comment]
nice work,thanks!

**Comment by macdonst** [comment]
Handling this in #1718

**Comment by morariu** [comment]
Hi, is this fixed? I am having the same issue in the last version. Is there a workaround? I can't downgrade since I am getting another error. Thanks

**Comment by Ziv-Barber** [comment]
For Cordova it's better to re-install everything when you want to change an existing plugin.
I'm removing both the platform and plugins folders and then I'm creating again the android and ios platforms and then I'm adding all the plugins. I made a script to do it automatically for my project. Before that I had a lot of problems with removing and adding plugins.
