### ISSUE TITLE
Can't receive notification on IOS

### ISSUE THREAD

**Issue by safouen** [phonegap/phonegap-plugin-push#1757]
I am using FCM to push notification to devices both android and IOS 
every thing works like a charm with the android but the ios I cant receive a single notification 

The response of the FCM is showing that notification is sent successfully : 
{"multicast_id":8213058946209775655,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1496412423120826%7bbd1df4f9fd7ecd"}]}

I have made the APNs Auth key and every thing 
I am using :  
cordova 7.0.1
ios platform  4.4.0
phonegap-plugin-push 2.0.0-rc3

Here is a sample of my code : 

```
> var options = {
      android: { 
        senderID: "senderID"
      },
      ios: {
        alert: true,
        badge: true,
        sound: true,
        fcmSandbox: true
      },
      windows: {}
    };
PushNotification.init(options);
$cordovaPushV5.initialize(options).then(function() {
    // start listening for new notifications
      $cordovaPushV5.onNotification();
    // start listening for errors
      $cordovaPushV5.onError();   
    // register to get registrationId
      $cordovaPushV5.register().then(function(registrationId) {
        Variables.setRegistration(registrationId);
      })
    });
    $rootScope.$on('$cordovaPushV5:notificationReceived', function(event, data){
        if (data.additionalData.destination) {
          if(data.additionalData.destination=="app.gifts"){
            if(Variables.getState()=='up and running'){
              ModuleLoader.update_gifts().then(function(){ $state.go(data.additionalData.destination);})
            }else {
              Variables.setDestination(data.additionalData.destination);
            }
          }
          else if(data.additionalData.destination=="app.season_parker"){
            if(Variables.getState()=='up and running'){
              ModuleLoader.update_season_parker().then(function(){ $state.go(data.additionalData.destination);})
            }else {
              Variables.setDestination(data.additionalData.destination);
            }
          }
        }
    });
```

**Comment by fredgalvao** [comment]
Based on your snippet, I'll say you're using $cordovaPushV5, which is a very old ionic 1.x ngCordova plugin, and it is very outdated. Please see [this comment](https://github.com/phonegap/phonegap-plugin-push/issues/1720#issuecomment-300949343) for more details on issues with that and alternatives.

If you're able to re-reproduce the original issue using a more up-to-date method (this plugin's own API, or IonicNative Push module, for example), feel free post back.

Other than that, you missed the xcode logs that the issue template asks for. Please provide them so we can help you better and sooner.

**Comment by jcesarmobile** [comment]
Also, rc3 is not the latest, I would recommend to try rc4 or even master branch

**Comment by safouen** [comment]
I switched to native push module but it is the same it works on android but not with ios 
Here is the new code : 

` screen.lockOrientation('portrait');
        var options = {
          android: { 
            senderID: "senderID"
          },
          ios: {
            alert: true,
            badge: true,
            sound: true,
            fcmSandbox: true
          },
          windows: {}
        };
        var push = PushNotification.init(options);
        push.on('registration', function(data) {
          Variables.setRegistration(data.registrationId);
        });
        push.on('notification', function(data) {
          if (data.additionalData.destination) {
              if(data.additionalData.destination=="app.gifts"){
                if(Variables.getState()=='up and running'){
                  ModuleLoader.update_gifts().then(function(){ $state.go(data.additionalData.destination);})
                }else {
                  Variables.setDestination(data.additionalData.destination);
                }     
              }
              else if(data.additionalData.destination=="app.season_parker"){
                if(Variables.getState()=='up and running'){
                  ModuleLoader.update_season_parker().then(function(){ $state.go(data.additionalData.destination);})
                }else {
                  Variables.setDestination(data.additionalData.destination);
                }   
              }    
            }
      });`

**Comment by safouen** [comment]
I solved it, 
It was not a problem with the plugin just the way I send the notification I putted the title and the body inside "data" instead of "notification"
