### ISSUE TITLE
Registration Event called only when app Resumes

### ISSUE THREAD

**Issue by kevinbailey1** [phonegap/phonegap-plugin-push#1758]
Happening on iPhone 6S+, iOS version 10.3.2

### Expected Behaviour
When the app is launched I initialize PushNotifications and then register 3 event listeners; registration, notification, and error (see below). After initialize completes the registration event should be fired so I can use the registrationId (store to DB) to use for push notifications. 

### Actual Behaviour
The initialize function fails to complete until I suspend the application and then resume. The app then asks for permissions to allow notifications and finally initialize completes successfully (registration is fired with a valid registrationId).

I had an app working with push notifications for both Android and iOS previously, but when I had to update iOS certificates it broke push notifications. I do not suspect my certificates are bad because if the user goes through the suspend/resume actions then the registration will complete successfully and push notifications will work.

### Reproduce Scenario (including but not limited to)
Have the PushNotifications.init, registration, and notification events registered during deviceready. Open application, suspend application, resume application. You should then be asked to allow permissions to push notifications (press Yes). Registration will now fire.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.3.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPhone 6S+

#### Cordova CLI version and cordova platform version
cordova cli-6.5.0
iOS 4.3.1
Android 6.1.2

#### Plugin version
All plugins used, using PhoneGap Build to build and compile project:
cordova-plugin-device     	        npm	1.1.3	
cordova-plugin-inappbrowser   	npm	1.5.0
cordova-plugin-whitelist   	        npm	1
phonegap-plugin-push   	        npm	1.10.3

#### Sample Push Data Payload
Not relevant

#### Sample Code that illustrates the problem

```
var myApp = angular.module('myApp', ['ngRoute', 'ui.bootstrap', 'ngMask', 'ngLoadingSpinner']).run(['$rootScope', '$location', '$http', function($rootScope, $location, $http){
    document.addEventListener('deviceready', function () {
        try {
            var push = PushNotification.init({
                "android": { "senderID": appSettings.pushSenderID },
                "ios": { "alert": "true", "badge": "true", "sound": "true" },
                "windows": {}
            });

            push.on('registration', function (data) {
                try{
                    $rootScope.$apply(function () { $rootScope.regId = data.registrationId; });
                }
                catch (e) {
                    alert(e.message);
                }            
            });

            push.on('notification', function (data) {
                alert(data.title + " Message: " + data.message);
            });

            push.on('error', function (e) {
                $rootScope.regId = '';
            });
        }
        catch (e) {
            alert('Error during push notification setup: ' + e.message);
        }
    });
}]);
```

#### Logs taken while reproducing problem
I don't know how to obtain these. Everything builds successfully. I could link PhoneGap Build logs if they are of interest.

**Comment by fredgalvao** [comment]
The logs would be obtained during runtime, not during build time. What we want from them are the logs issued during the plugin's native code initialization, which should hint at an issue if it exists.
How are you running/testing your application? I haven't used PGB in years, so I'm not really sure if they give you back an `.ipa` or something, but you should be able to run and debug it somehow, or at least grab runtime logs back from PGB...

**Comment by fredgalvao** [comment]
Also, Markdown tip:
Multi-line blocks of code are surrounded by in-their-own-lines triple backtick, like so:

\```js
code
\```

**Comment by fredgalvao** [comment]
It might be an obvious and useless observation, but your `registration` event handler only tries to trigger a digest on angular through `$rootScope.$apply`. Have you tried issuing a `console.log` or `alert` there instead? If you haven't, I'd say there's a surprisingly high chance you're seeing issues with angular's 1.x lifecycle conflicting with cordova's.

**Comment by kevinbailey1** [comment]
Hi Fred, thanks for the quick reply!

PGB does build into an .ipa. Attached are the logs I received during the building of the .ipa (upon inspection I don't believe they will be any help).
[iOS_ipa_build_log.txt](https://github.com/phonegap/phonegap-plugin-push/files/1051911/iOS_ipa_build_log.txt)

I added an alert inside the registration event which is not firing until the suspend/resume like before.
```
 push.on('registration', function (data) {
    alert("RegId: " + data.registrationId);
    try {
        $rootScope.$apply(function () { $rootScope.regId = data.registrationId; });
    }
    catch (e) {
        alert(e.message);
    }
});
```

I'll work on getting some logs during execution and update this post.

**Comment by kevinbailey1** [comment]
Any other suggestions to try? I am attempting to obtain logs but I have limited access to an iPhone for testing and have not been able to get my hands on any yet (Why does Apple make this so complicated...)

**Comment by mrwheels** [comment]
Hmm... i don't have the answer (yet)  But i would like to let you know you are not alone in this. I'm having the exact same issue. When i open my test app nothing, and when i press the home button i get the iOS popup if i want to recieve push notifications. After i accept the call goes through to apns and i receive  a valid device id. Receiving push notifications also works, but only when the app is suspended in the background. It all feels a bit wonky... I'm still searching for a solution and if i find one i will post iT here. 

Don't give up, and happy coding 😁
