### ISSUE TITLE
From yesterday plugin doesent work. Match with the new release at phonegap build

### ISSUE THREAD

**Issue by jasj** [phonegap/phonegap-plugin-push#1759]
### Expected Behaviour
PushNotification must exist

### Actual Behaviour
PushNotification variable is undefined

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by jcesarmobile** [comment]
Closing as you didn't provide the information on the issue template. Feel free to open a new one with the required information
