### ISSUE TITLE
How do i tell if the user open the app by tapping the notification?

### ISSUE THREAD

**Issue by liuzhen2008** [phonegap/phonegap-plugin-push#176]
I want to navigate to a specific page when user taps a notification to open the app.

But i don't want to trigger the navigation when user has the app running in foreground.

It seems that the notification callback is fired even when the app is in foreground.. So how do i differentiate between the two situations?

**Comment by macdonst** [comment]
@liuzhen2008 when you receive a notification when the app is running the value of `data.additionalData.foreground` is set to `true`. When the app is in the background and the user clicks on the notification shade then the value is `false` when the notification call back is invoked.

**Comment by liuzhen2008** [comment]
WOW so awesome!
