### ISSUE TITLE
fcmSandbox vs gcmSandbox

### ISSUE THREAD

**Issue by ardabeyazoglu** [phonegap/phonegap-plugin-push#1760]
According to docs, we have to use `"fcmSandbox": true` for ios in development builds. However, it doesnt get any notification unless i change it to "gcmSandbox". 

Is there a typo?

EDIT: Plugin version is 1.10.4

**Comment by macdonst** [comment]
@ardabeyazoglu if you are using 1.x then it is `gcmSandbox`. The as yet to be officially released 2.x version of the plugin will use `fcmSandbox`

**Comment by ardabeyazoglu** [comment]
Ok, upgraded and worked. However, i encountered another problem but i will create another issue for that.

**Comment by raugaral** [comment]
On the ts types file only is the "gcmSandbox" attribute. 
The API documentation says: "iOS GCM support. The following properties are used if you want use GCM on iOS." and the property name is ios.fcmSandbox.
What's wrong? The API or ts types file??

https://github.com/phonegap/phonegap-plugin-push/blob/master/types/index.d.ts
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md
