### ISSUE TITLE
Is it possible to get list of current notifications?

### ISSUE THREAD

**Issue by extempl** [phonegap/phonegap-plugin-push#1763]
I mean to be able to do something like this:

get notification
click on the app icon (not notification) as a badge appeared
get all available notifications with data (by resume event) to be able to handle same as notification click.
Also i would like to differ is app were opened by app icon click or by changing opened apps.

**Comment by jcesarmobile** [comment]
No, that's not possible, you should query your server to see the notifications sent but not opened
