### ISSUE TITLE
Ionic: $cordovaPushV5:notificationReceived event not firing in Android or iOS

### ISSUE THREAD

**Issue by chaseyutzy** [phonegap/phonegap-plugin-push#1764]
### Expected Behaviour
Expected the app to handle the event on tap of the push notification. 

### Actual Behaviour
Event is not fired in the foreground or the background. Push notification is received in both OS's.

### Reproduce Scenario (including but not limited to)
Ionic 2
Config.xml: plugin name="phonegap-plugin-push" spec="~1.9.2" 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Testing with iOS 10 device and Android Lollipop device.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Android = Samsung 

#### Cordova CLI version and cordova platform version
Cordova: 6.0.0
Android: 6.5.0
iOS: 4.3.1

#### Plugin version
phonegap-plugin-push 1.9.4 "PushPlugin"

#### Sample Push Data Payload
<pre>
body = {
			"data": {
				"title": "#PushTitle#",
				"body": "#PushMessage#",
				"type": "#PushType#",
				"activeID": "#PushID#",
				"conference": "#PushEventSlug#"
			}, 
			"notification": {
				"title": "#PushTitle#",
				"body": "#PushMessage#",
				"sound": "default"
			}, 
			"to": "/topics/announcements",
			"priority": "high",
			"content_available": true
		}
</pre>

I have also tried without the notification object and it did not fire in Android. iOS does not receive notifications without the notification object.

#### Sample Code that illustrates the problem
<pre>
var options = {
                    android: {
                        senderID: FCMSenderID,
                        topics: ['announcements']
                    },
                    ios: {
                        senderID: FCMSenderID,
                        topics: ['announcements'],
                        alert: true,
                        badge: false,
                        sound: true,
                        gcmSandbox: false

                    },
                    windows: {}
                };

$cordovaPushV5.initialize(options).then(function() {

                    /* Start listening for push notifications */
                    $cordovaPushV5.onNotification();

                    // start listening for errors
                    $cordovaPushV5.onError();

                    // register to get registrationId
                    $cordovaPushV5.register().then(function(registrationId) {

                        /* Set token in user scope. */
                        $scope.user.push_token = registrationId;
                        console.log($scope.user.push_token);

                    });

                });

//Listeners
$rootScope.$on('$cordovaPushV5:notificationReceived', function(event, data) {
... console logs 

</pre>

#### Logs taken while reproducing problem
<pre>
D/PushPlugin_GCMIntentService( 5115): create actions: with in-line
D/PushPlugin_PushHandlerActivity( 5115): not id = 65
V/PushPlugin_PushHandlerActivity( 5115): onCreate
D/PushPlugin_PushHandlerActivity( 5115): callback = null
V/PushPlugin( 5115): sendExtras: caching extras to send at a later time.
D/PushPlugin_PushHandlerActivity( 5115): bringToForeground = true
D/PushPlugin_PushHandlerActivity( 5115): isPushPluginActive = false
D/PushPlugin_PushHandlerActivity( 5115): forceMainActivityReload
D/PushPlugin_GCMIntentService( 5115): onMessage - from: /topics/announcements
D/PushPlugin_GCMIntentService( 5115): normalize extras
D/PushPlugin_GCMIntentService( 5115): key = content-available
D/PushPlugin_GCMIntentService( 5115): replace key content-available with content-available
D/PushPlugin_GCMIntentService( 5115): key = google.sent_time
D/PushPlugin_GCMIntentService( 5115): replace key google.sent_time with google.sent_time
D/PushPlugin_GCMIntentService( 5115): key = activeID
D/PushPlugin_GCMIntentService( 5115): replace key activeID with activeID
D/PushPlugin_GCMIntentService( 5115): key = gcm.notification.content_available
D/PushPlugin_GCMIntentService( 5115): replace key gcm.notification.content_available with content_available
D/PushPlugin_GCMIntentService( 5115): key = body
D/PushPlugin_GCMIntentService( 5115): replace key body with message
D/PushPlugin_GCMIntentService( 5115): no locale found for key = message, error Value Test of type java.lang.String cannot be converted to JSONObject
D/PushPlugin_GCMIntentService( 5115): key = type
D/PushPlugin_GCMIntentService( 5115): replace key type with type
D/PushPlugin_GCMIntentService( 5115): key = notId
D/PushPlugin_GCMIntentService( 5115): replace key notId with notId
D/PushPlugin_GCMIntentService( 5115): key = sound
D/PushPlugin_GCMIntentService( 5115): replace key sound with sound
D/PushPlugin_GCMIntentService( 5115): key = title
D/PushPlugin_GCMIntentService( 5115): replace key title with title
D/PushPlugin_GCMIntentService( 5115): no locale found for key = title, error Value Test of type java.lang.String cannot be converted to JSONObject
D/PushPlugin_GCMIntentService( 5115): key = google.message_id
D/PushPlugin_GCMIntentService( 5115): replace key google.message_id with google.message_id
D/PushPlugin_GCMIntentService( 5115): key = conference
D/PushPlugin_GCMIntentService( 5115): replace key conference with conference
D/PushPlugin_GCMIntentService( 5115): background
D/PushPlugin_GCMIntentService( 5115): message =[Test
D/PushPlugin_GCMIntentService( 5115): ]
D/PushPlugin_GCMIntentService( 5115): title =[Test]
D/PushPlugin_GCMIntentService( 5115): contentAvailable =[true]
D/PushPlugin_GCMIntentService( 5115): forceStart =[null]
D/PushPlugin_GCMIntentService( 5115): create notification
D/PushPlugin_GCMIntentService( 5115): stored icon=null
D/PushPlugin_GCMIntentService( 5115): stored iconColor=null
D/PushPlugin_GCMIntentService( 5115): stored sound=true
D/PushPlugin_GCMIntentService( 5115): stored vibrate=true
D/PushPlugin_GCMIntentService( 5115): no icon resource found - using application icon
D/PushPlugin_GCMIntentService( 5115): create actions: with in-line
D/PushPlugin_PushHandlerActivity( 5115): not id = 66
V/PushPlugin_PushHandlerActivity( 5115): onCreate
D/PushPlugin_PushHandlerActivity( 5115): callback = null
V/PushPlugin( 5115): sendExtras: caching extras to send at a later time.
D/PushPlugin_PushHandlerActivity( 5115): bringToForeground = true
D/PushPlugin_PushHandlerActivity( 5115): isPushPluginActive = false
D/PushPlugin_PushHandlerActivity( 5115): forceMainActivityReload
</pre>

**Comment by macdonst** [comment]
@chaseyutzy try sending this payload:

```
body = {
			"data": {
				"title": "#PushTitle#",
				"body": "#PushMessage#",
				"sound": "default",
				"type": "#PushType#",
				"activeID": "#PushID#",
				"conference": "#PushEventSlug#"
			}, 
			"to": "/topics/announcements",
			"priority": "high",
			"content_available": true
		}
```

**Comment by chaseyutzy** [comment]
The result was I only received notification on Android not iOS, and here is the log from the push notification to Android. Everything works as expected besides the notification received event not firing.

<pre>
D/PushPlugin_GCMIntentService( 8959): onMessage - from: /topics/announcements
D/PushPlugin_GCMIntentService( 8959): normalize extras
D/PushPlugin_GCMIntentService( 8959): key = google.sent_time
D/PushPlugin_GCMIntentService( 8959): replace key google.sent_time with google.sent_time
D/PushPlugin_GCMIntentService( 8959): key = activeID
D/PushPlugin_GCMIntentService( 8959): replace key activeID with activeID
D/PushPlugin_GCMIntentService( 8959): key = gcm.notification.content_available
D/PushPlugin_GCMIntentService( 8959): replace key gcm.notification.content_available with content_available
D/PushPlugin_GCMIntentService( 8959): key = body
D/PushPlugin_GCMIntentService( 8959): replace key body with message
D/PushPlugin_GCMIntentService( 8959): no locale found for key = message, error Value Test of type java.lang.String cannot be converted to JSONObject
D/PushPlugin_GCMIntentService( 8959): key = type
D/PushPlugin_GCMIntentService( 8959): replace key type with type
D/PushPlugin_GCMIntentService( 8959): key = sound
D/PushPlugin_GCMIntentService( 8959): replace key sound with sound
D/PushPlugin_GCMIntentService( 8959): key = title
D/PushPlugin_GCMIntentService( 8959): replace key title with title
D/PushPlugin_GCMIntentService( 8959): no locale found for key = title, error Value Test of type java.lang.String cannot be converted to JSONObject
D/PushPlugin_GCMIntentService( 8959): key = google.message_id
D/PushPlugin_GCMIntentService( 8959): replace key google.message_id with google.message_id
D/PushPlugin_GCMIntentService( 8959): key = conference
D/PushPlugin_GCMIntentService( 8959): replace key conference with conference
D/PushPlugin_GCMIntentService( 8959): background
D/PushPlugin_GCMIntentService( 8959): message =[Test
D/PushPlugin_GCMIntentService( 8959): ]
D/PushPlugin_GCMIntentService( 8959): title =[Test]
D/PushPlugin_GCMIntentService( 8959): contentAvailable =[null]
D/PushPlugin_GCMIntentService( 8959): forceStart =[null]
D/PushPlugin_GCMIntentService( 8959): create notification
E/PushPlugin_GCMIntentService( 8959): Number format exception - Error parsing notId: Invalid int: "null"
D/PushPlugin_GCMIntentService( 8959): stored icon=null
D/PushPlugin_GCMIntentService( 8959): stored iconColor=null
D/PushPlugin_GCMIntentService( 8959): stored sound=true
D/PushPlugin_GCMIntentService( 8959): stored vibrate=true
D/PushPlugin_GCMIntentService( 8959): no icon resource found - using application icon
D/PushPlugin_GCMIntentService( 8959): create actions: with in-line
D/PushPlugin_PushHandlerActivity( 8959): not id = 0
V/PushPlugin_PushHandlerActivity( 8959): onCreate
D/PushPlugin_PushHandlerActivity( 8959): callback = null
V/PushPlugin( 8959): sendExtras: caching extras to send at a later time.
D/PushPlugin_PushHandlerActivity( 8959): bringToForeground = true
D/PushPlugin_PushHandlerActivity( 8959): isPushPluginActive = false
D/PushPlugin_PushHandlerActivity( 8959): forceMainActivityReload
D/PushPlugin_GCMIntentService( 8959): onMessage - from: /topics/announcements
D/PushPlugin_GCMIntentService( 8959): normalize extras
D/PushPlugin_GCMIntentService( 8959): key = google.sent_time
D/PushPlugin_GCMIntentService( 8959): replace key google.sent_time with google.sent_time
D/PushPlugin_GCMIntentService( 8959): key = activeID
D/PushPlugin_GCMIntentService( 8959): replace key activeID with activeID
D/PushPlugin_GCMIntentService( 8959): key = gcm.notification.content_available
D/PushPlugin_GCMIntentService( 8959): replace key gcm.notification.content_available with content_available
D/PushPlugin_GCMIntentService( 8959): key = body
D/PushPlugin_GCMIntentService( 8959): replace key body with message
D/PushPlugin_GCMIntentService( 8959): no locale found for key = message, error Value Test of type java.lang.String cannot be converted to JSONObject
D/PushPlugin_GCMIntentService( 8959): key = type
D/PushPlugin_GCMIntentService( 8959): replace key type with type
D/PushPlugin_GCMIntentService( 8959): key = sound
D/PushPlugin_GCMIntentService( 8959): replace key sound with sound
D/PushPlugin_GCMIntentService( 8959): key = title
D/PushPlugin_GCMIntentService( 8959): replace key title with title
D/PushPlugin_GCMIntentService( 8959): no locale found for key = title, error Value Testing of type java.lang.String cannot be converted to JSONObject
D/PushPlugin_GCMIntentService( 8959): key = google.message_id
D/PushPlugin_GCMIntentService( 8959): replace key google.message_id with google.message_id
D/PushPlugin_GCMIntentService( 8959): key = conference
D/PushPlugin_GCMIntentService( 8959): replace key conference with conference
D/PushPlugin_GCMIntentService( 8959): background
D/PushPlugin_GCMIntentService( 8959): message =[Test
D/PushPlugin_GCMIntentService( 8959): ]
D/PushPlugin_GCMIntentService( 8959): title =[Testing]
D/PushPlugin_GCMIntentService( 8959): contentAvailable =[null]
D/PushPlugin_GCMIntentService( 8959): forceStart =[null]
D/PushPlugin_GCMIntentService( 8959): create notification
E/PushPlugin_GCMIntentService( 8959): Number format exception - Error parsing notId: Invalid int: "null"
D/PushPlugin_GCMIntentService( 8959): stored icon=null
D/PushPlugin_GCMIntentService( 8959): stored iconColor=null
D/PushPlugin_GCMIntentService( 8959): stored sound=true
D/PushPlugin_GCMIntentService( 8959): stored vibrate=true
D/PushPlugin_GCMIntentService( 8959): no icon resource found - using application icon
D/PushPlugin_GCMIntentService( 8959): create actions: with in-line
</pre>

**Comment by chaseyutzy** [comment]
This log is from the app receiving the notification while in the foreground.

**Comment by macdonst** [comment]
@chaseyutzy okay, so with that payload and the app in the foreground you still don't get the `notification` event being fired?

**Comment by fredgalvao** [comment]
By this: 
> The result was I only received notification on Android not iOS

Do you mean it now worked as expected on Android, but NOT on iOS?

You need to send a different payload to android and ios:
The Android side of this plugin expects the payload to be inside the `data` section of the root object.
The iOS side of this plugin expects the payload to be inside the `notification` section of the root object.

This is a known limitation to the 1.x version, caused by the way GCM handles the notifications internally on Android.

**Comment by chaseyutzy** [comment]
I received a notification only on Android, and the event did not fire on either OS when testing the below data payload. I don't mind sending an OS specific payload, but have not been able to get the event to fire with either OS yet.

<pre>
body = {
			"data": {
				"title": "#PushTitle#",
				"body": "#PushMessage#",
				"sound": "default",
				"type": "#PushType#",
				"activeID": "#PushID#",
				"conference": "#PushEventSlug#"
			}, 
			"to": "/topics/announcements",
			"priority": "high",
			"content_available": true
		}
</pre>

**Comment by chaseyutzy** [comment]
Is there any reason the event would not fire on Android using that payload?
