### ISSUE TITLE
Force-Start: 1 Doesn't Work

### ISSUE THREAD

**Issue by snakeman21** [phonegap/phonegap-plugin-push#1766]
### Expected Behaviour
I force quit the app. Then I send a notification that has a payload with force-start:1. I want it to open my app in background mode (or foreground. Doesn't matter either way).

### Actual Behaviour
force-start:1 doesn't open my app in background mode.

#### Steps to Reproduce 
1) Force quit app
2) Send a notification with a payload that has force-start:1
3) App should be open in background mode

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Motorolla (Moto G5 Plus)

#### Cordova CLI version and cordova platform version
6.0.0

#### Plugin version
1.9.0

#### Sample Push Data Payload
"data": {
    	"title": "Force Start",
    	"message": "This notification should restart the app yet it does not",
    	"force-start": 1
    }

#### Sample Code that illustrates the problem
None

#### Logs taken while reproducing problem
None

**Comment by macdonst** [comment]
@snakeman21 try this payload (note the quotes around the 1):

```
"data": {
"title": "Force Start",
"message": "This notification should restart the app yet it does not",
"force-start": "1"
}
```

As well what version of cordova-android are you using? Finally running `adb logcat | grep Push` can really help diagnose these things.

**Comment by snakeman21** [comment]
I am using Phonegap 6.5.0. I actually tried force start with and without quotes around the `1`, but it still doesn't work. Didn't see any output with logcat unfortunately either.

**Comment by macdonst** [comment]
@snakeman21 I need to know what version of cordova-android you are using. Run `phonegap platforms` or `cordova platforms` in your project directory. If you aren't getting any logs then I'm assuming you don't even see the push notification?

**Comment by snakeman21** [comment]
Sorry, Android 6.0. No I do I see the push notifications just fine. I meant to say that I didn't see any output useful for this scenario. The plugin works great for everything else, except for this.

**Comment by macdonst** [comment]
@snakeman21 without some logs I can't debug this. Also, can you please post the output of the command `phonegap platforms`

**Comment by snakeman21** [comment]
I did give you the output, Android 6.0.0. I'm using Android 7.0 on my phone, but Android 6.0.0 is the output of `phonegap platforms` for Cordova Android version. I apologize for any confusion. 

As for the logs, here you go.

```
06-06 13:29:18.441 26847 31335 D PushPlugin_GCMIntentService: onMessage - from: 786202104034
06-06 13:29:18.441 26847 31335 D PushPlugin_GCMIntentService: normalize extras
06-06 13:29:18.441 26847 31335 D PushPlugin_GCMIntentService: key = google.sent_time
06-06 13:29:18.441 26847 31335 D PushPlugin_GCMIntentService: replace key google.sent_time with google.sent_time
06-06 13:29:18.441 26847 31335 D PushPlugin_GCMIntentService: key = force-start
06-06 13:29:18.442 26847 31335 D PushPlugin_GCMIntentService: replace key force-start with force-start
06-06 13:29:18.442 26847 31335 D PushPlugin_GCMIntentService: key = title
06-06 13:29:18.442 26847 31335 D PushPlugin_GCMIntentService: replace key title with title
06-06 13:29:18.442 26847 31335 D PushPlugin_GCMIntentService: no locale found for key = title, error Value haha of type java.lang.String cannot be converted to JSONObject
06-06 13:29:18.442 26847 31335 D PushPlugin_GCMIntentService: key = google.message_id
06-06 13:29:18.442 26847 31335 D PushPlugin_GCMIntentService: replace key google.message_id with google.message_id
06-06 13:29:18.442 26847 31335 D PushPlugin_GCMIntentService: key = message
06-06 13:29:18.442 26847 31335 D PushPlugin_GCMIntentService: replace key message with message
06-06 13:29:18.443 26847 31335 D PushPlugin_GCMIntentService: no locale found for key = message, error Value 123 of type java.lang.Integer cannot be converted to JSONObject
06-06 13:29:18.443 26847 31335 D PushPlugin_GCMIntentService: background
06-06 13:29:18.443 26847 31335 D PushPlugin_GCMIntentService: message =[123]
06-06 13:29:18.443 26847 31335 D PushPlugin_GCMIntentService: title =[haha]
06-06 13:29:18.443 26847 31335 D PushPlugin_GCMIntentService: contentAvailable =[null]
06-06 13:29:18.443 26847 31335 D PushPlugin_GCMIntentService: create notification
06-06 13:29:18.443 26847 31335 E PushPlugin_GCMIntentService: Number format exception - Error parsing notId: null
06-06 13:29:18.446 26847 31335 D PushPlugin_GCMIntentService: stored icon=null
06-06 13:29:18.446 26847 31335 D PushPlugin_GCMIntentService: stored iconColor=null
06-06 13:29:18.447 26847 31335 D PushPlugin_GCMIntentService: stored sound=true
06-06 13:29:18.447 26847 31335 D PushPlugin_GCMIntentService: stored vibrate=true
06-06 13:29:18.447 26847 31335 D PushPlugin_GCMIntentService: no icon resource found - using application icon
06-06 13:29:18.447 26847 31335 D PushPlugin_GCMIntentService: create actions: with in-line
```

**Comment by snakeman21** [comment]
Any thoughts @macdonst?

**Comment by macdonst** [comment]
@snakeman21 did you resolve your issue?

**Comment by snakeman21** [comment]
Hey ya I resolved it, but I'm actually not really sure why. I must have messed something up in my Android folder, because I removed and added the platform again with the same version (Cordova-Android 6.0.0) and now it works. I apologize for raising this false issue. Not sure why it wasn't working.

Also, can you help me out with this problem though? https://github.com/phonegap/phonegap-plugin-push/issues/1779
