### ISSUE TITLE
Ionic 2 Android build fails with error (Can't find google-services.json file)

### ISSUE THREAD

**Issue by morariu** [phonegap/phonegap-plugin-push#1767]
Cordova version 7.010
Ionic 2
plugin version 2.0.0-rc2

I must be missing the obvious but I am having an issue with the following. Quote from your installation guide.

> As of version 2.0.0 the SENDER_ID parameter has been removed at install time. Instead you put your google-services.json (Android) and/or GoogleService-Info.plist in the root folder of your project and then **add the following lines into your plugin.xml**.
> 
> In the platform tag for Android add the resource-file tag:

```
<platform name="android">
  <resource-file src="google-services.json" target="google-services.json" />
</platform>

```
Is this /plugins/phonegap-plugin-push/plugin.xml where I add the reference? In this case obviously google-services.json is not found and my build fails. I've tried putting the google-services.json in plugin folder but build still fails.

Thanks

**Comment by macdonst** [comment]
@morariu first, upgrade to using 2.0.0-rc4 as it removes the hook that copies that file and may cause you some issues. Second, the resource-file tag should be in the android platform tag in your config.xml file. Make those changes and let me know how it goes.

**Comment by morariu** [comment]
Thanks @macdonst now I'm on 2.0.0-rc4
There is a conflict with https://github.com/arnesson/cordova-plugin-firebase such as:
1. If I add the resource-file tag in config.xml I get the **google-services.json" already exists!**
2. If I don't add the resource-file tag anywhere I am getting the following:

```
A problem occurred evaluating root project 'android'.
> Failed to apply plugin [id 'com.google.gms.google-services']
   > For input string: "+"
```

**Comment by macdonst** [comment]
@morariu yeah, those two plugins won't co-exist right now. I should send them a PR request so they stop copying the file via a hook. The second issue you are running into is issue #1718 and I'm trying to figure out a way to fix that.
