### ISSUE TITLE
Troubleshooting notifications not showing, but registration shows successful

### ISSUE THREAD

**Issue by jrmcdona** [phonegap/phonegap-plugin-push#1768]
### Expected Behaviour
Device is registering just fine.  See the logs below.  I see no errors in the code.
Expecting to get the notification.  I have the APNS cert installed on my MAC and also in Azure notifications hub.  I am running via Xcode on my device through USB.

### Actual Behaviour
Device registration in Azure Notification Hubs is removed after sending a test message. 
No notification delivered to the device.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.3

#### Cordova CLI version and cordova platform version

global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v7.4.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.12 

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

#### Sample Push Data Payload
{"aps":{"alert":{"title":null,"body":"Test notification"},"sound":"default","badge":0},"url":null,"data":{}}

#### Sample Code that illustrates the problem
Here is come code but the code isn't throwing errors:
```

import { Component} from '@angular/core';
import { AlertController, Platform } from 'ionic-angular';
import { Push, PushObject, PushOptions } from "@ionic-native/push";
import { NotificationService } from '../../services/notification.service';
import { Dialogs } from '@ionic-native/dialogs';
import { AppPreferences } from '@ionic-native/app-preferences';

@Component({
    selector: 'notification',
    templateUrl: 'notification.html'
})

export class NotificationPage {

    errorMessage: string;
    public deviceToken: string;
    public registrationId: string;
    public isEnabled: boolean=true;
    private settings: AppPreferences;
    private gamertag: string;

    constructor(private notificationService: NotificationService,
        public platform: Platform,
        public push: Push,
        public alertCtrl: AlertController,
        private dialogs: Dialogs,
        private appPreferences: AppPreferences) {
        platform.ready().then(() => {
            this.deviceToken = '';
            //this.updateRegistration('dummy-handle', 'dummy-registrationId');
            //this.registerDevice('dummy');
            this.settings = appPreferences;
            this.getGamertag();
            this.initPushNotification();
        });
    }

    sendTestNotification() {
        console.log('Sending test notification');
        this.isEnabled = false;
        this.notificationService.sendNotification('Test notification', this.gamertag).
            subscribe(
            data => {
                console.log("Sending test notification subscribed " + data);
                this.isEnabled = true;
                return true;
            },
            error => {
                console.error("Error sending test notification: " + error);
            });
    }

    //Initialize push notifications
    initPushNotification() {
        if (!this.platform.is('cordova')) {
            console.warn("Push notifications not initialized. Cordova is not available - Run in physical device");
            return;
        }
        const options: PushOptions = {
            android: {
                senderID: "YOUR_SENDER_ID" //TODO: Complete this!
            },
            ios: {
                alert: "true",
                badge: false,
                sound: "true"
            },
            windows: {}
        };
        const pushObject: PushObject = this.push.init(options);

        pushObject.on('registration').subscribe((data: any) => {
            console.log("device token ->", data.registrationId);
            this.deviceToken = data.registrationId;

            this.registerDevice(data.registrationId);

        });

        pushObject.on('notification').subscribe((notification: any) => {
            console.log('Received a notification', notification);
            this.dialogs.alert(notification.message)
                .then(() => console.log('Dialog dismissed'))
                .catch(e => console.error('Error displaying dialog', e));

        });

        pushObject.on('error').subscribe(error => console.error('Error with Push plugin', error));
    }

    private registerDevice(handle: string) {
        this.notificationService.registerDevice(handle)
            .subscribe(registrationId => {
                this.registrationId = registrationId;
                this.updateRegistration(handle, registrationId);
            },
            err => {
                console.error('Error registering device');
            });
    }

    private updateRegistration(handle: string, registrationId: string) {
        this.notificationService.updateRegistration(handle, registrationId, this.gamertag).
            subscribe(
            data => {
                return true;
            },
            error => {
                console.error("Error updating registration");
            });
    }

    private getGamertag() {

        this.settings.fetch('gamertag').then((res) => {
            this.gamertag = res;
        }).catch(reason => {
            console.error('gamertag failed on home: ', reason);
        });
    }
}
```
#### Logs taken while reproducing problem
**Here are the logs as the device gets registered to allow for push notifications**

2017-06-06 16:58:31.529294-0500 Xbox Ambassadors[1108:276861] Push Plugin register called
2017-06-06 16:58:31.529423-0500 Xbox Ambassadors[1108:276861] PushPlugin.register: setting badge to false
2017-06-06 16:58:31.529441-0500 Xbox Ambassadors[1108:276861] PushPlugin.register: clear badge is set to 0
2017-06-06 16:58:31.529457-0500 Xbox Ambassadors[1108:276861] PushPlugin.register: better button setup
2017-06-06 16:58:31.534594-0500 Xbox Ambassadors[1108:276861] GCM Sender ID (null)
2017-06-06 16:58:31.534660-0500 Xbox Ambassadors[1108:276861] Using APNS Notification
2017-06-06 16:58:31.694066-0500 Xbox Ambassadors[1108:276268] Push Plugin register success: <5fa9db3b 25a608f1 84c629b7 6fc0b74e df1e6579 e04e93ba 33a19e5e ba84401e>
2017-06-06 16:58:31.724372-0500 Xbox Ambassadors[1108:276268] device token -> 5fa9db3b25a608f184c629b76fc0b74edf1e6579e04e93ba33a19e5eba84401e

Any ideas?

**Comment by macdonst** [comment]
@jrmcdona sounds like the classic device is running in dev, server is running in production or vice versa.

**Comment by jrmcdona** [comment]
That was it! Wow that was awesome thanks

**Comment by macdonst** [comment]
@jrmcdona I might have seen that issue before 😉

**Comment by amritk** [comment]
I have a question about this one, how does the server know if you are in production or development if you are using the APNS auth key
![screen shot 2017-06-06 at 6 54 51 pm](https://user-images.githubusercontent.com/2039539/26859036-cf61f660-4ae9-11e7-9341-9ee2baf27cc3.png)

I'm having the same issue and I've set fcmSandbox to both true and false, yet I'm still not receiving any notifications on ios, android is working fine.

**Comment by fredgalvao** [comment]
The certificate used to sign the app (client side) and to send the payload (server-side) are the two *keys* that APNS use to match a notification sent with a possible receiver.

**Comment by amritk** [comment]
@fredgalvao My client is development, but I don't think the certificate for the server specifies production or development since I'm using the auth key instead of certs:
![screen shot 2017-06-06 at 7 10 03 pm](https://user-images.githubusercontent.com/2039539/26859344-de167c42-4aeb-11e7-9107-c2c6c2b281ba.png)
