### ISSUE TITLE
options.ios.sound true or false not working

### ISSUE THREAD

**Issue by Jarvey** [phonegap/phonegap-plugin-push#177]
Hi,

I have two questions:

1. I'm able to receive notifications in my app etc. now I want to add a mute button in my app so you can turn of the push notifications sounds. When I set the options.ios.sound to false I'm still receiving notifications with sound. What I understand from the documentation is you can enable of disable the notification sound with options.ios.sound. Am I doing something wrong or do I misunderstand the documentation?

2. Is there a way to auto increment the badge number when multiple notifications are received with this plugin?

My app is using ionic and I test my app on a real device with iOS 9.

Thanks!
Maik

**Comment by macdonst** [comment]
@Jarvey okay, wow learned something new today. Apparently in iOS there is no way to programmatically turn off sound in your push notifications if you initially register for sounds. Only the user can do this by going to the notifications settings for the app and turning it off. 

The only way I can think of to handle this programmatically is making your server smart enough not to send the sound info when you don't want a sound to be played. So if you give your user some way to turn sound off it should go to your server and store a value not to send sound to that registration ID.

At least that is my understanding but I'd love for someone to independently verify that I'm not wrong in this case.

**Comment by Jarvey** [comment]
@macdonst , thanks for your reply. I already found it strange that your documents indicate it was possible. Also according to my knowledge it is not possible to mute notifications sounds in iOS other than via a notification server.

**Comment by macdonst** [comment]
@Jarvey yeah, I think I'm going to have to update the docs in order to handle this one. I was basing this push plugin off the old one which gave me the false positive.
