### ISSUE TITLE
phonegap build expected to run but fails for winphone

### ISSUE THREAD

**Issue by gfeledi** [phonegap/phonegap-plugin-push#1771]
### Expected Behaviour
phonegap build expected to run but fails for winphone
### Actual Behaviour
 fail for winphone
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
windows
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version
1.10.4
    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

#### Logs taken while reproducing problem
Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "phonegap-plugin-push@1" via npm Installing "phonegap-plugin-push" at "1.10.4" for windows Updating appxmanifests with ToastCapable=true... Failed to install 'phonegap-plugin-push':Error: Cannot find module 'C:\cygwin\tmp\gimlet\2593299\project\platforms\windows\cordova\lib\AppxManifest' at Function.Module._resolveFilename (module.js:337:15) at Function.Module._load (module.js:287:25) at Module.require (module.js:366:17) at require (module.js:385:17) at module.exports (C:\cygwin\tmp\gimlet\2593299\project\cordova\plugins\phonegap-plugin-push\hooks\windows\setToastCapable.js:5:24) at runScriptViaModuleLoader (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pgb-plugman\node_modules\pgb-cordova-lib\src\hooks\HooksRunner.js:187:18) at runScript (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pgb-plugman\node_modules\pgb-cordova-lib\src\hooks\HooksRunner.js:165:16) at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pgb-plugman\node_modules\pgb-cordova-lib\src\hooks\HooksRunner.js:133:20 at _fulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pgb-plugman\node_modules\q\q.js:787:54) at self.promiseDispatch.done (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pgb-plugman\node_modules\q\q.js:816:30) Cannot find module 'C:\cygwin\tmp\gimlet\2593299\project\platforms\windows\cordova\lib\AppxManifest'

**Comment by macdonst** [comment]
the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
