### ISSUE TITLE
Coexisting with cordova-plugin-googleplus is hard

### ISSUE THREAD

**Issue by fredgalvao** [phonegap/phonegap-plugin-push#1772]
### Expected Behaviour

Install both `phonegap-plugin-push` and `cordova-plugin-googleplus` and compile succesfully.

### Actual Behaviour

`cordova-plugin-googleplus 5.1.1`
\+
`phonegap-plugin-push 1.10.3`
\=
```
* What went wrong:
Execution failed for task ':transformClassesWithDexForArmv7Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/zzc;
```

@EddyVerbruggen is bold:
```
<framework src="com.google.android.gms:play-services-auth:+" />
<framework src="com.google.android.gms:play-services-identity:+" />
```
We're not:
```
 <framework src="com.google.android.gms:play-services-gcm:10.2+"/
```

#### Steps to Reproduce 
```sh
cordova create bacon com.bacon Bacon
cd bacon/
cordova platform add androiod
cordova compile #ok
cordova plugin add phonegap-plugin-push --variable SENDER_ID="XXXXXXX"
cordova plugin add cordova-plugin-googleplus --save --variable REVERSED_CLIENT_ID=myreversedclientid
cordova compile
```
#### Cordova CLI version and cordova platform version

`cordova -v` = `7.0.1`
`cordova platform ls` = `android 6.2.3`

## PS

So, how are plugin authors or even android developers supposed to work version management? I've encountered errors caused by bold version declarations like `+` at least 3 times in different plugins this month, with the consequences ranging from multidex exceptions, androidManifest merge issues, and alpha versions leaking into gradle. I'm lost. Please send help.

## PS2

For anyone having the same issue before we've fixed it, a workaround is to change
`cordova.system.library.7=com.google.android.gms:play-services-gcm:10.2+`
to
`cordova.system.library.7=com.google.android.gms:play-services-gcm:11.+`
on `platforms/android/project.properties`. I have not tested all push features with that version change, but I'm hoping it'll just work, for https://developers.google.com/android/guides/releases#june_2017_-_version_1100 shows nothing scary other than deprecations.

**Comment by macdonst** [comment]
@fredgalvao yeah, I'm trying to figure out a way around this. It's probably the biggest blocker from this being released officially as 2.0.0. I've talked to @EddyVerbruggen about it too.

If bumping to GCM 11+ works then I'm happy for us to release a 1.10.5.

**Comment by tgensol** [comment]
@macdonst, It looks like to work well on my side

**Comment by macdonst** [comment]
I pushed a 1.10.5 release to npm. 

@fredgalvao if you find issues like this you know you can make the changes yourself, I trust ya.

**Comment by fredgalvao** [comment]
@macdonst I don't, :wink: , and that's why I ask for input first.

**Comment by macdonst** [comment]
@fredgalvao lol, good stuff. I dont' trust myself either.

**Comment by dpa99c** [comment]
FYI guys: I've hit this issue with other plugins some created a similar Gradle workaround plugin as for the support libraries: [cordova-android-play-services-gradle-release](https://github.com/dpa99c/cordova-android-play-services-gradle-release)
