### ISSUE TITLE
not calling push.on('notification', function(data){}); on receiving notification when the app is in background

### ISSUE THREAD

**Issue by chetangudisagar** [phonegap/phonegap-plugin-push#1773]
I am deploying on android Marsh-mellow for testing.
**Expected Behaviour** -
Alert the notification contents.

**Actual Behaviour** -
No alert messages. Only app is opened with previous screen.

I want to see and store the contents of the Notifications received through **Firebase Console (FCM)** when the app is in background.

Here is my Code -

```
    document.addEventListener("deviceready",onDeviceReady,false);
    function onDeviceReady(){

       var push = PushNotification.init({ "android": {"senderID": "91254247XXXX"}});

       push.on('registration', function(data) {
           console.log(data.registrationId);
           //document.getElementById("gcm_id").innerHTML = data.registrationId;
       });

       push.on('notification', function(data) {

           alert("On Notification function!!");
             // data.message,
            // data.title,
            // data.count,
            // data.sound,
            // data.image,
            // data.additionalData
            console.log("notification event");
            console.log(JSON.stringify(data));
            alert(JSON.stringify(data));
           //Do something 
       });

       push.on('error', function(e) {
           alert(e);
       });
    }
```
When the app is in **foreground** (on screen) I receive the contents (title, message, data, etc.) properly and I am able to see them in alert box directly in the app.

But when app is in **background** (not on screen but running in backround), I get the notification in Notification Area. When I click on the notification received, it is redirecting me to the last opened page in the app.

The function push.on('notification', function(data) {} is not called. No alert messages are shown. Can someone help me fix this?

**Comment by macdonst** [comment]
@chetangudisagar did you read the [Overview](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#overview) and specifically how you can get the [event called when the app is in the background](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications)?

Also, don't use the `alert` dialog as it is a blocking call.

Without your push payload or logs I can't help any more than the above.

**Comment by chetangudisagar** [comment]
Thank you sir,

Since I am using in Firebase Console, How can I set content-available field
in that?

As for as I know there was no option for that. So can you help me with that?

Regards,
Chetan Gudisagar,
Placement Coordinator,
Final Year Undergraduate,
Dept. of Information Technology,
National Institute of Technology Karnataka, Surathkal
<http://nitk.ac.in/>
Contact No - 9538165813

**Comment by macdonst** [comment]
@chetangudisagar you won't be able to use the Firebase Console for testing this as it hides too much from you. You'll need to use another service or write a quick node script. There are many examples of using node to send messages in the PAYLOAD.md docs.
