### ISSUE TITLE
Receive previous push notification in IOS

### ISSUE THREAD

**Issue by jailupatel007** [phonegap/phonegap-plugin-push#1777]
I have some issue in IOS. I get push notification but previous message. Example : I sent to message1 but I do not get message1. After I sent message2 and I get message1. After I sent message3 and get message2. Why I receive previous push notification ?

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
