### ISSUE TITLE
Problem with receiving notification when app is built on phonegap

### ISSUE THREAD

**Issue by filippetroviccc** [phonegap/phonegap-plugin-push#1778]
#### Problem
When i tested my app in phonegap developer app i received notifications normaly but when i build app and install it on my android device notifications dont show. Only when app is in background my device receive notification. 

#### Code where i send notification
```
var fcm = new FCM(apiKey);

var message = {
    to: deviceID,
    data: {
        title: 'Badge Test',
        message: 'Badges, we don\'t need no stinking badges',
        alertId: 'Some data'
        //alertName:'My alert'
    }
};

fcm.send(message, function(err, response){
  if (err) {
    console.log(err);
    console.log("Something has gone wrong!");
  } else {
    console.log("Successfully sent with response: ", response);
  }
});
```

#### Code where i receive

```
push.on('notification', function(data) {
     console.log("notification:  "+data.additionalData.alertId);
     var alertId = data.additionalData.alertId;
     if (alertId) {
       navigator.notification.confirm(
           'Do you wonth to show this  ' + data.additionalData.alertName + '?',
           function(buttonIndex) {
             if (buttonIndex === 1) {
               showAlertById(alertId);
             }
           },
          'New advert',
          ['Yes','No']
        );
     } else {
       navigator.notification.alert(
           data.message,         // message
           null,                 // callback
           data.title,           // title
           'Ok'                  // buttonName
       );
     }
```

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by filippetroviccc** [comment]
Sorry for be not following guidelines. I think this will be better

[https://github.com/phonegap/phonegap-plugin-push/issues/1780](url)
