### ISSUE TITLE
Suggestion: One Unified Notifications Plugin

### ISSUE THREAD

**Issue by snakeman21** [phonegap/phonegap-plugin-push#1781]
I think it would be great for the Cordova community to eventually make this into a complete notifications plugin, rather than just a remote push notifications one. I think adding all the different types of notifications, like local notifications, pushkit, callkit and connectionservice would transform this plugin into an awesome unified notifications experience. There are plenty of great Cordova plugins that could be merged into this repo potentially.

https://github.com/katzer/cordova-plugin-local-notifications
https://github.com/Hitman666/cordova-ios-voip-push
https://github.com/Taracque/ionic-plugin-callkit

**Comment by macdonst** [comment]
@snakeman21 Pull Requests are welcome!
