### ISSUE TITLE
How to register token to firebase on iOS? 

### ISSUE THREAD

**Issue by mariansurdu** [phonegap/phonegap-plugin-push#1783]
I'm using plugin in a ionic 1 application.I want to get a firebase valid token on iOS.Now i receive token from APNS and is not valid for fcm api.Does anyone have an idea?

**Comment by jcesarmobile** [comment]
The v2.x version of the plugin supports FCM.
Use that version, provide the Google-Services.plist file and you should then get the FCM token instead of the FCM one (read the docs about FCM, I might have missed some step)
