### ISSUE TITLE
Registration event not fired when app is built using PhoneGap Build

### ISSUE THREAD

**Issue by dgunwin** [phonegap/phonegap-plugin-push#1784]
I am using the plugin (version 2.0.0-rc4) to register for FCM notifications.  I use the following code:

var push = PushNotification.init({
  android: {
    senderID: MY_ID_HERE
  },
  ios: {
    alert: true,
    sound: true,
    vibration: true,
    badge: true
  }
});

push.on('registration', function(data) {
  // Handle the registration event here
});

When I run the app locally and use the app on the PhoneGap Developer app, the registration event is fired.

But, when I then build the app on PhoneGap Build, the registration event is NOT fired.   (The 'error' event is not fired either.)

Is there any obvious reason why this would be the case?

Thank you.

**Comment by jcesarmobile** [comment]
v2.x.x of the plugin is not supported by Phonegap Build yet.
You'll have to continue using 1.x.x or build your app locally.

**Comment by dgunwin** [comment]
Thanks a lot for the quick reply, and explanation.

Do you know roughly when PhoneGap Build will start supporting v2?

**Comment by jcesarmobile** [comment]
I don't know, but maybe never as v2 needs a hook to work and Phonegap Build doesn't allow to run hooks. 
Maybe Phonegap Build team finds a workaround for it.
Maybe you can upvote this issue https://github.com/phonegap/build/issues/279

**Comment by dgunwin** [comment]
Ok thanks a lot.

I'll build the app locally then...

**Comment by noveweb** [comment]
Hi guys! How can i build the app locally on windows?
Thanks in advance!
