### ISSUE TITLE
cannot find symbol "android.os.Build.VERSION_CODES.M" #1115

### ISSUE THREAD

**Issue by Anilinfo2015** [phonegap/phonegap-plugin-push#1788]
This issue is still there with cordova-android@6.0.0 

![image](https://user-images.githubusercontent.com/10174750/27117774-c6bccec4-50f5-11e7-978d-618b4ef63d9f.png)

**Comment by macdonst** [comment]
@Anilinfo2015 no, this is an issue with your build environment. You need to update to the latest android sdk that includes `Build.VERSION_CODES.N`.
