### ISSUE TITLE
If device restarts, can't receive push notifications until app is opened for the first time

### ISSUE THREAD

**Issue by snakeman21** [phonegap/phonegap-plugin-push#1789]
### Expected Behaviour
The phone should be able to receive a notification immediately, even if it's been restarted.

### Actual Behaviour
 If phone is restarted, can't receive push until opening the app for the first. Then it it works perfectly, even if force quitted.

#### Steps to Reproduce 
1. Restart phone
2. Send push notification to that device 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.3 & Android 7.0 

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPhone & Motorola Moto G5

#### Cordova CLI version and cordova platform version
Cordova-Android: 6.1.1
Cordova-iOS: 4.3.1

#### Plugin version
1.9.0

**Comment by fredgalvao** [comment]
There are three sections of the issue template you did not provide, which are key to even starting to investigate this:
- `Sample Push Data Payload`
- `Sample Code that illustrates the problem`
- `Logs taken while reproducing problem`

Without them, there's nothing we can do but speculate.
