### ISSUE TITLE
How to Handle call back's of push notification using typescript. i followed the steps given in link, but no luck....https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons-1 

### ISSUE THREAD

**Issue by praveen1228** [phonegap/phonegap-plugin-push#1791]
Using Ionic 2 and typescript, created app. when app is in background i got push notification from APNS.

i have two button saying "view" and "ok".

when i click on view app is opening, but its not calling my callback function.

Sample code :-  this.push = Push.init({
      ios: {
        alert: "true",
        badge: false,
        sound: "true",

        categories: {
          invite:
          {
            yes: {
              callback: "Accept", title: "View", foreground: true, destructive: false
            },
            no: {
              callback: "ContineOK", title: "Ok", foreground: false, destructive: false
             }
            // maybe :{
            //    callback: "this.app.ContineOK", title: "Ok", foreground: false, destructive: false
            // }
          }
        }
      }
    })

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
