### ISSUE TITLE
unregister Push in iOS

### ISSUE THREAD

**Issue by rakeshpalivela** [phonegap/phonegap-plugin-push#1792]
#### Cordova CLI version and cordova platform version

    cordova --version                                    6.5.0
    cordova platform version iOS                     # e.g. 4.2.1

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
