### ISSUE TITLE
Push notification does not work when app is closed

### ISSUE THREAD

**Issue by vahidvdn** [phonegap/phonegap-plugin-push#1793]
### Expected Behaviour
Get notification in device when app is closed 

### Actual Behaviour
Works when the app is in background or open

#### Cordova CLI version and cordova platform version
    cordova --version
 (I use ionic cloud build, so I don't know)

    cordova platform version android
6.2.3 (included in config.xml)

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push
1.8.4

#### Sample Push Data Payload
Just using ionic push cloud service

Maybe this would be duplicated, but I couldn't be able to fix this problem.

**Comment by jcesarmobile** [comment]
Latest 1.x version is v1.10.5, try with that, 1.8.4 is very old.

Also, when you don't receive push when the app is closed, it's usually because of the push payload. Do ionic push shows you the payload it sends?

**Comment by vahidvdn** [comment]
> Latest 1.x version is v1.10.5

Ok, I will test with this version.

> Do ionic push shows you the payload it sends?

Yes, I can add any payload in key value format. (Default is: `No payload items.`) Also we can set device options from ionic dashboard.

**Comment by vahidvdn** [comment]
It's not possible to upgrade to the latest version. I use ionic push, so I should use ionic build. Ionic build just upload my `www` directory and install the plugins depends on the `config.xml`. After upgrading it didn't work at all. So, maybe it's not install on ionic build server or related problem.

Is there anything about payload?

**Comment by jcesarmobile** [comment]
You can read this
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

**Comment by vahidvdn** [comment]
@jcesarmobile It's just talking about foreground/background state of application. My issue is about when the app is closed.

**Comment by jcesarmobile** [comment]
The behaviour should be the same on background and closed.
So, it works for you when in background but not when closed?

**Comment by vahidvdn** [comment]
@jcesarmobile Yes exactly. It works fine when it's in background, but doesn't work when I simply close the app.

**Comment by jcesarmobile** [comment]
Anyway, closing this as you are using a very old version of the plugin and the bug might be related to that. 
If v1.10.5 is not working on ionic builder create a new issue about that. 

v1.x.x **should** work on online builders, while v2.x.x **will not** unless they allow hooks

**Comment by vahidvdn** [comment]
Ok, I try to contact with ionic team. Thanks.

**Comment by vahidvdn** [comment]
That's very strange. I installed `OneSignal` plugin and this problem also happened there. I really don't know what is wrong!

**Comment by macdonst** [comment]
@vahidvdn if you kill the app then there is no service running in order to process the incoming push.

**Comment by vahidvdn** [comment]
Oh my god!!! Huawei devices have a feature called `protected apps`. If it's not protected, in normal closing, it kills the app.

Anyway, Thanks guys.
