### ISSUE TITLE
ledColor functionality notification vs data push

### ISSUE THREAD

**Issue by casper5822** [phonegap/phonegap-plugin-push#1794]
I tried to use the ledColor property. It works only if the data notification has the fields: title and message.
I send two pushes to prevent the double message handler firing, so in my case data notification doesn't have the title and message. 
I tried to use the ledColor into the notification push message but it doesn't work.
I tried this on Android 4.4.2 in ionic v1 app.
My question is about the possibility to use ledColor property on the notification message not only in the data push one.
Is this possible or do you know another better way?

Thank you

**Comment by macdonst** [comment]
No, it's not currently possible.
