### ISSUE TITLE
iOS on('notification') not firing

### ISSUE THREAD

**Issue by snakeman21** [phonegap/phonegap-plugin-push#1798]
### Expected Behaviour
When in app, you should be handling your notifications internally, rather than via a remote push notification. I should be able to call `on('notification')` and do stuff. However, even a console.log does not work, so the event is obviously not even firing. Only an issue on iOS, not Android.

### Actual Behaviour
As explained above, I am receiving the native notification dialogue, and nothing in `on('notification')` can fire. Only an issue on iOS, not Android.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.3.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPhone 6

#### Cordova CLI version and cordova platform version
Cordova-iOS: 4.3.1

#### Plugin version
1.9.0

#### Sample Push Data Payload
"data": {
"title": "Hello",
"message": "Cool Message"
}

#### Sample Code that illustrates the problem
No errors thrown in Safari Developer Tools nor in XCode

```
pushObj = PushNotification.init({
					"android": {
							"senderID": "786202104034"
					},
					"browser": {},
					"ios": {
							"sound": true,
							"vibration": true,
							"badge": true,
							"categories": {
						  }
					},
					"windows": {}
			});
```
```
pushObj.on('notification', function(data) {
 alert('I should see this');
});
```

**Comment by snakeman21** [comment]
Never mind. Conflicted with local notifications plugin. Hopefully that will be added to this plugin one day.

**Comment by DavidBriglio** [comment]
@snakeman21 I am experiencing the same behaviour with a similar setup. Can you elaborate on how the local notifications plugin was conflicting?

**Comment by snakeman21** [comment]
I wish I knew the answer, but the reason why it's tough from me to tell is because I also modified Katzer's plugin a bit, so it may have been because of that. I noticed you actually have a few local notification plugins that you made yourself. Are you using the one you forked or just using the other Simple Notification one you made? The reason why I ask is because I ended up making my own simple notification, like the one you made and that seemed to work fine.

Also, did it work after you removed whichever local notification plugin you used? It could be a different plugin that conflicted with it.

**Comment by DavidBriglio** [comment]
I was using my altered version of katzers. Unfortunately it still does not activate the on notification, even when I remove all notification plugins. 

I am still trying to figure this out.

**Comment by DavidBriglio** [comment]
I'm not quite sure what happened with my original testing, but it does seem to be the notification plugin that is causing the issue. Are you able to link to what notification plugin you are currently using that works with push? The one I have created works, but only on iOS10. I need something that will work on lower versions as well.
