### ISSUE TITLE
PushOptions not applying on Background

### ISSUE THREAD

**Issue by ehorodyski** [phonegap/phonegap-plugin-push#1799]
### Expected Behaviour
When I set Android options to `vibrate: true` and `icon: ic_ac_unit`, those settings should be applied to both background and foreground push states.

### Actual Behaviour
When `forceShow: true` is set on Android options, when inside the app and a push is sent, the correct options are used. When the app is in the background, the options are not applied.

### Reproduce Scenario (including but not limited to)
```
var opts = {
        android: {
            senderID: "XXXXXXX",
            sound: true,
            vibrate: true,
            icon: "your_icon",
            forceShow: "true"

        },
        ios: {
            alert: true,
            badge: true,
            sound: true
        }
    };
PushNotification.init(opts);
```
#### Steps to Reproduce
Push a notification while in foreground with the above options, then push a notification when in background with the above options.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.1.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Google Pixel

#### Cordova CLI version and cordova platform version

    cordova --version  **7.0.1**
    cordova platform version android **6.2.3**

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   **1.10.4**

#### Sample Push Data Payload
Done through an API Gateway on AWS. The message gets delivered, however the options are not applied unless the app is in the foreground.

#### Sample Code that illustrates the problem
See above.

#### Logs taken while reproducing problem
On App Init:
```
06-19 10:23:13.163 30931-30990/org.ieee.mobile.mcoe.events V/Push_Plugin: execute: action=hasPermission
06-19 10:23:13.187 30931-30990/org.ieee.mobile.mcoe.events V/Push_Plugin: execute: action=init
06-19 10:23:13.188 30931-30992/org.ieee.mobile.mcoe.events V/Push_Plugin: execute: data=[{"android":{"senderID":"XXXXXXX","sound":true,"vibrate":true,"icon":"ic_ac_unit","forceShow":"true"},"ios":{"alert":true,"badge":true,"sound":true}}]
06-19 10:23:13.188 30931-30992/org.ieee.mobile.mcoe.events V/Push_Plugin: execute: jo={"senderID":"XXXXXXX","sound":true,"vibrate":true,"icon":"ic_ac_unit","forceShow":"true"}
06-19 10:23:13.188 30931-30992/org.ieee.mobile.mcoe.events V/Push_Plugin: execute: senderID=XXXXXXX
06-19 10:23:13.189 30931-30992/org.ieee.mobile.mcoe.events V/Push_Plugin: onRegistered: {"registrationId":"XXXXXXX"}
06-19 10:23:13.191 30931-30992/org.ieee.mobile.mcoe.events D/Push_Plugin: no iconColor option
```
On foreground push:
```
06-19 10:24:17.385 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: onMessage - from: XXXXXXX
06-19 10:24:17.386 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: normalize extras
06-19 10:24:17.387 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: key = google.sent_time
06-19 10:24:17.387 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: replace key google.sent_time with google.sent_time
06-19 10:24:17.388 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: key = icon
06-19 10:24:17.388 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: replace key icon with icon
06-19 10:24:17.388 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: key = vibrate
06-19 10:24:17.388 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: replace key vibrate with vibrate
06-19 10:24:17.388 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: key = google.message_id
06-19 10:24:17.388 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: replace key google.message_id with google.message_id
06-19 10:24:17.388 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: key = notification
06-19 10:24:17.388 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: notifkey = body
06-19 10:24:17.388 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: replace key body with message
06-19 10:24:17.389 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: no locale found for key = message, error Value This of type java.lang.String cannot be converted to JSONObject
06-19 10:24:17.389 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: notifkey = title
06-19 10:24:17.389 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: replace key title with title
06-19 10:24:17.390 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: no locale found for key = title, error Value Broadcast of type java.lang.String cannot be converted to JSONObject
06-19 10:24:17.390 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: key = collapse_key
06-19 10:24:17.390 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: replace key collapse_key with collapse_key
06-19 10:24:17.390 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: foreground force
06-19 10:24:17.390 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: message =[This is a sample broadcast.]
06-19 10:24:17.390 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: title =[Broadcast Title]
06-19 10:24:17.390 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: contentAvailable =[null]
06-19 10:24:17.390 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: forceStart =[null]
06-19 10:24:17.390 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: create notification
06-19 10:24:17.393 30931-32005/org.ieee.mobile.mcoe.events E/Push_GCMIntentService: Number format exception - Error parsing notId: null
06-19 10:24:17.404 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: stored icon=ic_ac_unit
06-19 10:24:17.404 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: stored iconColor=#006699
06-19 10:24:17.404 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: stored sound=true
06-19 10:24:17.404 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: stored vibrate=true
06-19 10:24:17.405 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: using icon from plugin options
06-19 10:24:17.407 30931-32005/org.ieee.mobile.mcoe.events D/Push_GCMIntentService: create actions: with in-line
```
On Background Push
```
06-19 10:25:32.257 30931-30931/org.ieee.mobile.mcoe.events D/CordovaActivity: Paused the activity.
06-19 10:25:32.414 1197-1208/? I/art: Background partial concurrent mark sweep GC freed 181158(11MB) AllocSpace objects, 2(40KB) LOS objects, 30% free, 36MB/52MB, paused 1.116ms total 119.043ms
06-19 10:25:32.649 1197-12583/? D/QCOM PowerHAL: LAUNCH HINT: OFF
06-19 10:25:32.651 30931-30931/org.ieee.mobile.mcoe.events D/CordovaActivity: Stopped the activity.
```

**Comment by fredgalvao** [comment]
Without an example of the payload used on your tests, it's quite hard for us or anyone to reproduce this. Specially as there's a very big and quite common issue that goes off by how GCM handles payload before it hands it over to the plugin, which matches exactly your scenario (of things not working when in the background).

Would you be able to re-test this using a simple node app to send an explicit and known payload?

**Comment by ehorodyski** [comment]
Thanks for such a quick response! So it seems that I could need to replicate the init options in the payload as well? 

I'll be working on this today, so I can send over the payload. _However_, I can only send you an AWS payload, since we use AWS SNS for push notifications. Is that ok? Otherwise, anything I can add to my code to help debug this?

**Comment by fredgalvao** [comment]
You don't need to replicate to the payload what is passed to the `init`, those two things are not related.

We need any form of raw payload, be it the json you send SNS, be it the raw json you send through a node server example, or whatever else you might get.

**Comment by ehorodyski** [comment]
So I can get it working by manually pushing from the SNS console, must be how I configure the payload. Please allow me a few hours to get back to you (at most).

Again, thank you for being so responsive!

**Comment by ehorodyski** [comment]
Ok, I was able to grab a Broadcast (it's the clearest message I have):

```
{
    "Message": "{\"default\":\"This is a sample broadcast.\",\"APNS\":\"{\\\"aps\\\":{\\\"alert\\\":{\\\"body\\\":\\\"This is a sample broadcast.\\\",\\\"title\\\":\\\"Broadcast Title\\\"}}}\",\"GCM\":\"{\\\"notification\\\":{\\\"body\\\":\\\"This is a sample broadcast.\\\",\\\"title\\\":\\\"Broadcast Title\\\"}}\"}",
    "MessageStructure": "json",
    "TopicArn": "arn:aws:sns:XXX:XXX:XXXXXX"
}
```

**Comment by ehorodyski** [comment]
Looks like using the legacy GCM functionality, setting everything inside `data`, works, instead of using the new `notification` payload property. 

I don't know how you'd work around it using the new FCM syntax. 

Closing it, since it's not an issue with the plugin. Again, thank you for all the help!

**Comment by fredgalvao** [comment]
Unfortunately that's exactly what I was expecting it to be. You can read more about it here: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads, but to sum it up:
- on android (GCM or FCM) if you send a payload containing even partially the `notification` section to it, the low-level GCM/FCM api will grab the message and will **not** offload it to the plugin via the needed listeners, and thus this plugin can't work on top of `notification`ish payloads 100%, and that's why you need to use the `data` section instead
- on iOS, you NEED to use the `notification` and **cannot** use the `data` section for the main fields.
