### ISSUE TITLE
iOS badge number

### ISSUE THREAD

**Issue by sebrojas14** [phonegap/phonegap-plugin-push#18]
There's no way to update the app icon badge number, like in the previous version with setApplicationIconBadgeNumber?

**Comment by macdonst** [comment]
@sebrojas14 I added the "setApplicationIconBadgeNumber" back into the JS. I'll update the docs soon. You can test it out by grabbing it from the from this repo.

**Comment by macdonst** [comment]
Fixed for 1.1.0 release.
