### ISSUE TITLE
iOS init option type

### ISSUE THREAD

**Issue by fredgalvao** [phonegap/phonegap-plugin-push#180]
So, all examples and code samples call `.init()` with string options passed on the iOS part, but they're specified as Boolean on README.md. Checking source code I can see that both ways are handled, but shouldn't we either
* pick one way and go with it
or
* be explicit that both ways work
?

**Comment by macdonst** [comment]
@fredgalvao feel free to update the docs on this one.

**Comment by fredgalvao** [comment]
@macdonst  Which approach is the desired one though?

**Comment by macdonst** [comment]
@fredgalvao I believe in defensive programming. So if I'm expecting a boolean `true` I also except the String `"true"` to be valid. Same thing for `false`.
