### ISSUE TITLE
Cannot get push notification from Apple -Invalid Token ID

### ISSUE THREAD

**Issue by hsen-diabsolut** [phonegap/phonegap-plugin-push#1804]
Hello there,
 
I am having some issues with the push notification. I have installed an app called ClickMobile through phonegap framework. It is a non-public app, only available to the partners of that software. Basically it schedules tasks to technicians and the technicians can send messages to the scheduler (very high level).
 
All the installations were done correctly and the app is actually working fine on iPad. It is able to communicate with the server as the tasks and messages can be recieved on iPad with alert when it is open but the push features is not working properly.
 
I did follow this guide: https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AddingCapabilities/AddingCapabilities.html#//apple_ref/doc/uid/TP40012582-CH26-SW6
 
I am only doing adhoc distribution, the APNs certificates were created for the developement environment. All the server ports are open thus it is not a security issue.
 
I have also run test on the .p12 file with PushSharp tool and I get error saying that the token id is invalid but as per the database, it is the correct one.
 
I have redone the excercises many times and the result is still the same. If someone can help me, it will be great.
 
Thanks,
 
Hemadri

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
