### ISSUE TITLE
Push notifications overwrite the most recent one (Android)

### ISSUE THREAD

**Issue by Davegb** [phonegap/phonegap-plugin-push#1805]
### Expected Behaviour

All notifications for my app are displayed in the notification panel.

### Actual Behaviour

Just shows the latest notification for my app because it overwrites the most recent notification.

### Reproduce Scenario (including but not limited to)

Push notifications on Android.

#### Steps to Reproduce 

- Open the app.
- Send it to background.
- Send a notification through the API.
- Send a second notification through the API.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android >= 5.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

No success on any device.

#### Cordova CLI version and cordova platform version

    cordova --version  6.5.0
    cordova platform version android  6.1.2

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push 1.10.1

#### Sample Push Data Payload

```
{
    "tokens": ["0c1de133b0beffb8e6d9584566ecb73f3d39d52cad4529549d44855bc127d238"],
    "profile": "profilesaludmovil",
    "notification": {
        "message": "Individual",
        "ios": {
            "title": "Titulo",
            "message": "Prueba individual salud movil",
            "sound":"ping.aiff"
        },
        "android": {
            "message": "Individual"
        }
    }
}

**Comment by macdonst** [comment]
@Davegb that is actually the expected behaviour. Please read: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#stacking

**Comment by Davegb** [comment]
> @Davegb that is actually the expected behaviour. Please read: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#stacking

Thank you. I tried this and now I'm testing with the following JSON, but happens the same thing.
```
{
    "tokens": ["TOKEN"],
    "profile": "profilesaludmovil",
    "notification": {
        "message": "Individual",
	"notId": 1, //Then I send another with 2 or 3 and replaces the previous one
        "ios": {
            "title": "Titulo iOs",
            "message": "Prueba individual salud movil",
            "sound":"ping.aiff"
        },
        "android": {
            "message": "Individual"
        }
    }
}

**Comment by macdonst** [comment]
@Davegb right, well it seems like you are sending via the Ionic push service and I'm not sure if it supports the `notId` property but I'd try:

```
{
    "tokens": ["TOKEN"],
    "profile": "profilesaludmovil",
    "notification": {
        "message": "Individual",
        "ios": {
            "title": "Titulo iOs",
            "message": "Prueba individual salud movil",
            "sound":"ping.aiff"
        },
        "android": {
            "notId": 1, //Then I send another with 2 or 3 and replaces the previous one
            "message": "Individual"
        }
    }
}
```

**Comment by Davegb** [comment]
@macdonst Thanks a lot! You set me in the right track. This is the structure:
```
{
    "tokens": ["TOKEN"],
    "profile": "profilesaludmovil",
    "notification": {
        "message": "Individual ",
        "ios": {
            "title": "Titulo iOs",
            "message": "Prueba individual salud movil",
            "sound":"ping.aiff"
        },
        "android": {
	     "data": {	
                  "notId": 6, //notId goes inside android.data
            	  "message": "Individual"
	     }
        }
    }
}
