### ISSUE TITLE
When I build the application apk will build properly without any error, But when I install phonegap-plugin-push 

### ISSUE THREAD

**Issue by vishal-bluesys** [phonegap/phonegap-plugin-push#1806]
### Expected Behaviour
Should install and build with the phonegap-plugin-push 
### Actual Behaviour
showing error on build
     :mergeDebugResources FAILED

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':mergeDebugResources'.
        > Error: Failed to crunch file G:\Projects\Manthan\Source files\Frontend\Mobile
        apps\push-notification-example\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.1\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
android 5.0 or >5.0
#### Cordova CLI version and cordova platform version

    cordova --version 7.0.1                                    # e.g. 6.0.0
    cordova platform version android  6.2.1                   # e.g. 4.1.1

#### Plugin version

    cordova plugin version 1.10.5

#### Logs taken while reproducing problem
:mergeDebugResources

Error: Failed to crunch file G:\Projects\Manthan\Source files\Frontend\Mobile apps\push-notification-example\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.1\res\drawable-hdpi-v4\common_google_signin_btn_icon_dark_normal_background.9.png into G:\Projects\Manthan\Source files\Frontend\Mobile apps\push-notification-example\platforms\android\build\intermediates\res\merged\debug\drawable-hdpi-v4\common_google_signin_btn_icon_dark_normal_background.9.png
:mergeDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeDebugResources'.
>

BUILD FAILED

Total time: 1 mins 27.689 secs
Error: Failed to crunch file G:\Projects\Manthan\Source files\Frontend\Mobile apps\push-notification-example\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.1\res\drawable-hdpi-v4\common_google_signin_btn_icon_dark_normal_background.9.png into G:\Projects\Manthan\Source files\Frontend\Mobile apps\push-notification-example\platforms\android\build\intermediates\res\merged\debug\drawable-hdpi-v4\common_google_signin_btn_icon_dark_normal_background.9.png

**Comment by dec** [comment]
Hello @vishal-bluesys ,

I think you must provide a little more information in order to help you: the most information provided about a proble, the best possibility to get the right help.

For example, you said "showing error on build",... but, what the error is exactly? Please, copy here the complete error text: maybe that error message contains enough information in order to try to help you.

**Comment by vishal-bluesys** [comment]
:mergeDebugResources FAILED

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':mergeDebugResources'.
        > Error: Failed to crunch file G:\Projects\Manthan\Source files\Frontend\Mobile
        apps\push-notification-example\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.1\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png

**Comment by dec** [comment]
Hello @vishal-bluesys,

Certainly I find that same error in the past and, believe or not, it's related with a "long path". You did not mentioned it, but I think you are using Microsoft Windows.

What you can do is to place your application in a "root" folder or near to a "root" folder, that is, for example, try to place your application in some folder like: "C:\app".

**Comment by macdonst** [comment]
@dec thanks for helping with this issue.

**Comment by dec** [comment]
You're welcome @vishal-bluesys!
