### ISSUE TITLE
  Big picture and Actions Buttons not showing 

### ISSUE THREAD

**Issue by Arjunender** [phonegap/phonegap-plugin-push#1807]
### Expected Behaviour
Show the picture/action buttons if expanded when style is set to "PICTURE".
### Actual Behaviour
no picture/action button displayed

_# **The same is working fine with older version phonegap-plugin-push 1.8**_
#### Steps to Reproduce 
Sending the below payload to device
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung
#### Cordova CLI version and cordova platform version

cordova (CLI) platform : 6.4.0
 android:minSdkVersion='16' android:targetSdkVersion='25'
#### Plugin version

    cordova plugin version | phonegap-plugin-push v2

#### Sample Push Data Payload
{
  "title"=>"Title",
  "body"=>"Body",
  "style"=>"picture",
   "picture:"=>"https://medicoaid.azurewebsites.net/images/Notification_image.jpg",
'actions' => array(array( "inline": true,'icon' => 'start','title' => 'Start','callback' => 'pushListener.callbacks.view' ), array('icon' => 'cancle','title' => 'Ignore','callback' => 'pushListener.callbacks.cancle', 'foreground' => 'false'))
}
using PHP to push notification

 #### Sample Code that illustrates the problem

**Comment by macdonst** [comment]
@Arjunender I cannot reproduce this problem. Make sure that your payload is in the `data` part of the push not the `notification` part.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
