### ISSUE TITLE
Notification not working when application is completely closed 

### ISSUE THREAD

**Issue by vishal-bluesys** [phonegap/phonegap-plugin-push#1808]
### Expected Behaviour
Should  show notification on Receiving 

### Actual Behaviour
Not showing notification when app is completely closed 
but showing notification when application is working in background
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1 
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Lenovo 
#### Cordova CLI version and cordova platform version

  cordova  --version           :          7.0.1                # e.g. 6.0.0
  cordova platform version android   6.2.3                   # e.g. 4.1.1

#### Plugin version
  phonegap-plugin-push 1.10.5 "PushPlugin"

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
