### ISSUE TITLE
Summary Text is being trimmed in Picture Message

### ISSUE THREAD

**Issue by dionalfa** [phonegap/phonegap-plugin-push#1809]
### Expected Behaviour
When notification is expanded. The image is showed and summary text is expanded too.

### Actual Behaviour
When notification is expanded. The image is showed but summary text is truncated / trimmed.

### Reproduce Scenario (including but not limited to)
Here is my code (using firebase admin nodeJS SDK):
```
admin.messaging().sendToTopic('someTopic', {
    data: {
      "title": "Big Picture",
      "message": "This is my big picture message",
      "style": "picture",
      "picture": "http://bisnisupdate.com/images/posts/2016/07/01/LABBAIK-CHICKEN.png",
      "summaryText": "How can we expand our chicken business so fast? ready to hear the secret?"
    }
  })
    .then(function (response) {
      res.send(response);
    })
    .catch(function (err) {
      res.send(err);
    });
```

#### Steps to Reproduce 
Send notification as explined above.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy S5
#### Cordova CLI version and cordova platform version

    cordova --version  = 7.0.0
    cordova platform version android  = android 6.2.3

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push = 1.10.5

#### Sample Push Data Payload

```
{
    data: {
      "title": "Big Picture",
      "message": "This is my big picture message",
      "style": "picture",
      "picture": "http://bisnisupdate.com/images/posts/2016/07/01/LABBAIK-CHICKEN.png",
      "summaryText": "How can we expand our chicken business so fast? ready to hear the secret?"
    }
  }
```

#### Sample Code that illustrates the problem

```
admin.messaging().sendToTopic('someTopic', {
    data: {
      "title": "Big Picture",
      "message": "This is my big picture message",
      "style": "picture",
      "picture": "http://bisnisupdate.com/images/posts/2016/07/01/LABBAIK-CHICKEN.png",
      "summaryText": "How can we expand our chicken business so fast? ready to hear the secret?"
    }
  })
    .then(function (response) {
      res.send(response);
    })
    .catch(function (err) {
      res.send(err);
    });
```
In current condition, when notification is expanded. The image is being show but the text summary is being trunctated / trimmed.
Any workaround to make the summary text is expanded too?

**Comment by macdonst** [comment]
@dionalfa sorry, you'd have to create a custom view to have multi-line summary text in a big picture message and that is out of scope for this plugin.
