### ISSUE TITLE
Show "InvalidRegistration" when try to send notification in my iOS App

### ISSUE THREAD

**Issue by Neotrixsx** [phonegap/phonegap-plugin-push#1810]
### Expected Behaviour
Notification Landed on iOS and Android App.

### Actual Behaviour
Notification landed successfully on Android, but in iPhone message shown as "InvalidRegistration"
I follow all steps based on plugin doc. I get notification id also but Notification not landed in iOS App.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android:  Android 5.0
iOS: iOS 9.3.1

#### Cordova CLI version and cordova platform version
Cordova CLI: 7.0.1 
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: 1.9.0 
ios-sim version: 5.0.12 

#### Plugin version
cordova plugin version :   v2.0.0-rc5

#### Sample Push Data Payload
           android: {
                    //"icon": "ic_icon",
                    "iconColor": "#30395A",
                    "senderID": 'xxxxxxxx'
                },
                browser: {
                    pushServiceURL: 'http://push.api.phonegap.com/v1/push'
                },
                ios: {
                    "alert": "true",
                    "badge": "true",
                    "sound": "true",
                    "senderID": 'xxxxxxxx',
                    "fcmSandbox": true
                },

#### Logs taken while reproducing problem
2017-06-26 18:43:34.146 Endorsed[1626:425825] FCM Sender ID (null)
2017-06-26 18:43:34.146 Endorsed[1626:425825] Using APNS Notification
2017-06-26 18:43:34.171 Endorsed[1626:425769] Push Plugin register success: <7ca6d1f6 37aca256 bc680735 15e7c998 00364e8d 32b2a310 ce1ed34b d59c999>
2017-06-26 18:43:34.743 Endorsed[1626] <Error> [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
2017-06-26 18:44:26.586 Endorsed[1626:425883] void SendDelegateMessage(NSInvocation *): delegate (webView:runJavaScriptAlertPanelWithMessage:initiatedByFrame:) failed to return after waiting 10 seconds. main run loop mode: kCFRunLoopDefaultMode
2017-06-26 18:44:26.603 Endorsed[1626:425769] notificationDeviceId:7ca6d1fxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Please help me.

**Comment by macdonst** [comment]
@Neotrixsx are you trying to send a FCM message to your iOS device?

**Comment by jcesarmobile** [comment]
The log message is telling you that you didn't configure your app to use FCM.
You have to add the Google-Services.plist file from Firebase console to your app and copy it to the project with a resource-file tag.

**Comment by Neotrixsx** [comment]
@macdonst Yes, I  trying to send a FCM message to your iOS device

**Comment by Neotrixsx** [comment]
@jcesarmobile I follow all steps based on [doc](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#ios-details), and I add Google-Services.plist in my app folder.

**Comment by jcesarmobile** [comment]
You have to put the GoogleService-Info.plist in the root of your project (outside www) and then you have to add `<resource-file src="GoogleService-Info.plist" />` in your `config.xml`, inside the ios platform tag.

That's on the [installation-requirements]( https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements)

**Comment by macdonst** [comment]
@Neotrixsx yes, what @jcesarmobile mentioned is most probably the root cause of the issue. I just wanted to make sure you wanted to send over FCM first.

**Comment by Neotrixsx** [comment]
@macdonst and @jcesarmobile thank you both for your quick response and really you save my day, thanks ones again.
