### ISSUE TITLE
Use getApplicationIconBadgeNumber and setApplicationIconBadgeNumber

### ISSUE THREAD

**Issue by NassB** [phonegap/phonegap-plugin-push#1814]
### Expected Behaviour

I want to use the 2 functions but i didn't found how to implement them into my application.
I used $ionicCloudProvider.init() like in the ionic documentation to initialize the push plugin and not "var push = PushNotification.init()", but in the example the variable push is used so I dont know how to create this variable or an equivalent with the first method init().

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Asus Zenfone 2

#### Cordova CLI version and cordova platform version
cordova 7.0.1
android 6.2.3
ios 4.4.0

#### Plugin version
1.9.4

#### Sample Code that illustrates the problem
`.config(function($ionicCloudProvider) {
  $ionicCloudProvider.init({
....
  });
})`

`.run(function(...){
    push.getApplicationIconBadgeNumber(function(n) {
        console.log('success', n);
    }, function() {
       console.log('error');
    });
}`

**Comment by fredgalvao** [comment]
That is certainly a Ionic issue then, you'll need to ask the guys there to expose the two methods you want to access through their thin layer API.
Either that, or you  need to read the [docs they provide](https://docs.ionic.io/services/push/) completely.
