### ISSUE TITLE
clearBadge not working IOS

### ISSUE THREAD

**Issue by danilo-de-oliveira** [phonegap/phonegap-plugin-push#1815]
### Expected Behaviour
Clear badge when launching app
### Actual Behaviour
When you install the app, the badge appears with a random number. When you start the app, it disappears, however with each push, it appears again. This happens even with the options: ios.badge = false and ios.clearBadge = false.

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 7.0.1
    cordova platform version ios                     # e.g. 4.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.8.0

**Comment by macdonst** [comment]
@danilo-de-oliveira code? logs? push payload?

**Comment by danilo-de-oliveira** [comment]
@macdonst The problem has been fixed. It was lacking to do the treatment through the push payload.
Thank you.
