### ISSUE TITLE
Browser incorrect registration Firebase Cloud Messaging (FCM)

### ISSUE THREAD

**Issue by ajonp** [phonegap/phonegap-plugin-push#1818]
### Expected Behaviour
User token that is captured should work for the browser like it does in Android.
### Actual Behaviour
Fails to correctly register with FCM.
### Reproduce Scenario (including but not limited to)
Storing the token into firebase database (this works just fine and stores key, just like when android version runs).
```
    pushObject.on('registration').subscribe((data: any) => {
      console.log("device token ->", data.registrationId);
      this.userService.setUserToken(uid,data.registrationId);
    });
  setUserToken(uid:string,token:string){
    this.afDB.database.ref(`/users/${uid}/messageTokens/${token}`).set(true);
  }
```

Now from the server side is where the failure occurs.
```
Failure sending notification to cetvGre8mzo:APA91bF3MScgQzNPfX52iuXjc3rS6TWOqpOtRQmoVumPqT0cBx6EaqlK_qFDh0gkDQmgofQea6zYyTDo3xcB5gaEmK-NRoUYFVR8wb0QbuGEsCvIwPSC3AAB2ZAqQfQqGa38wJT4kpJz { Error: The credential used to authenticate this SDK does not have permission to send messages to the device corresponding to the provided registration token. Make sure the credential and registration token both belong to the same Firebase project.
    at FirebaseMessagingError.Error (native)
    at FirebaseMessagingError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:25:28)
    at new FirebaseMessagingError (/user_code/node_modules/firebase-admin/lib/utils/error.js:130:23)
    at Function.FirebaseMessagingError.fromServerError (/user_code/node_modules/firebase-admin/lib/utils/error.js:154:16)
    at /user_code/node_modules/firebase-admin/lib/messaging/messaging.js:80:63
    at Array.forEach (native)
    at mapRawResponseToDevicesResponse (/user_code/node_modules/firebase-admin/lib/messaging/messaging.js:76:26)
    at /user_code/node_modules/firebase-admin/lib/messaging/messaging.js:223:24
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
  errorInfo: 
   { code: 'messaging/mismatched-credential',
     message: 'The credential used to authenticate this SDK does not have permission to send messages to the device corresponding to the provided registration token. Make sure the credential and registration token both belong to the same Firebase project.' } }
```
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Chrome Version 58.0.3029.110 (64-bit)
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
MacOS Sierra 10.12.5
#### Cordova CLI version and cordova platform version

    cordova --version    7.0.1
Installed platforms:
  android 6.2.3
  browser 4.1.0
  ios 4.4.0

#### Plugin version

phonegap-plugin-push 2.0.0-rc5 "PushPlugin"

#### Sample Push Data Payload
    // Notification details.
    const payload = {
      data: {
        title: 'You have a new follower!',
        message: `${follower.displayName} is now following you.`,
        image: follower.photoURL,
        'image-type':'circle',
        id: followerUid
      }
    };
#### Sample Code that illustrates the problem
This is running from Firebase Cloud Functions using NodeJS
```
exports.sendFollowerNotification = functions.database.ref('/followers/{followedUid}/{followerUid}').onWrite(event => {
  const followerUid = event.params.followerUid;
  const followedUid = event.params.followedUid;
  // If un-follow we exit the function.
  if (!event.data.val()) {
    return console.log('User ', followerUid, 'un-followed user', followedUid);
  }
  console.log('We have a new follower UID:', followerUid, 'for user:', followerUid);

  // Get the list of device notification tokens.
  const getDeviceTokensPromise = admin.database().ref(`/users/${followedUid}/messageTokens`).once('value');

  // Get the follower profile.
  const getFollowerProfilePromise = admin.auth().getUser(followerUid);

  return Promise.all([getDeviceTokensPromise, getFollowerProfilePromise]).then(results => {
    const tokensSnapshot = results[0];
    const follower = results[1];

    // Check if there are any device tokens.
    if (!tokensSnapshot.hasChildren()) {
      return console.log('There are no notification tokens to send to.');
    }
    console.log('There are', tokensSnapshot.numChildren(), 'tokens to send notifications to.');
    console.log('Fetched follower profile', follower);

    // Notification details.
    const payload = {
      data: {
        title: 'You have a new follower!',
        message: `${follower.displayName} is now following you.`,
        image: follower.photoURL,
        'image-type':'circle',
        id: followerUid
      }
    };

    // Listing all tokens.
    const tokens = Object.keys(tokensSnapshot.val());

    // Send notifications to all tokens.
    return admin.messaging().sendToDevice(tokens, payload).then(response => {
      // For each message check if there was an error.
      const tokensToRemove = [];
      response.results.forEach((result, index) => {
        const error = result.error;
        if (error) {
          console.error('Failure sending notification to', tokens[index], error);
          // Cleanup the tokens who are not registered anymore.
          if (error.code === 'messaging/invalid-registration-token' ||
            error.code === 'messaging/registration-token-not-registered') {
            tokensToRemove.push(tokensSnapshot.ref.child(tokens[index]).remove());
          }
        }
      });
      return Promise.all(tokensToRemove);
    });
  });
});
```

**Comment by macdonst** [comment]
@ajonp Yeah, when you are running in the browser the service worker that registers with the remote push service uses the project ID `996231231186`. This project is used by our push service so you can send test push messages to the browser via the `phonegap push` command. See this brief tutorial (http://docs.phonegap.com/tutorials/develop/push-notifications/).

**Comment by ajonp** [comment]
@macdonst but why would this work on android and not a browser? I can set my own push id in the manifest for gcm "gcm_sender_id": "103953800507". Is this forcing us to only use phonegap to push notifications?

**Comment by macdonst** [comment]
@ajonp yeah, if you set the gcm sender ID in the manifest you should be able to get it to work as long as you are not running it through `phonegap serve`. You might have to unregister and re-register the service worker though.

**Comment by nissimpradhan** [comment]
@ajonp Did you manage to make it work using your own gcm_sender_id? I tried changing it from '996231231186' to my own sender id but it didn't work. Any pointers would be helpful. Oh and I'm trying to use it on Ionic and not phonegap.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.

**Comment by aviforgit** [comment]
Hi. same here
I used phonegap push plugin in android and it's work fine, but when  I added a new platform - browser  it's creating a registrationId  (getting it at on registration event) but when I'm trying to send  notification to the browser (via fcm console / Microsoft notification hub) it's return me that registrationId is incorrect. Any help will be appreciate :)
