### ISSUE TITLE
Registration fails and registration type: undefined 

### ISSUE THREAD

**Issue by rince1990** [phonegap/phonegap-plugin-push#1820]
This is my first time submiting a issue, if im not doing something correctly , please  let me know

### Expected Behaviour
registration event: XXXXXXX
registration type: GCM, FCM or whatever

### Actual Behaviour
registration event: XXXXXXX
registration type: undefined

#### Steps to Reproduce 
Installed plugin version 1.10.5 , configured with GCM senderID in  both config.xml and index.js, and added code at index.js to register de ID

`    <plugin name="phonegap-plugin-push" spec="~1.10.5">
        <variable name="SENDER_ID" value="xxxxxxxxxx" />
    </plugin>`

```
onDeviceReady: function() {
        console.log('Received Device Ready Event');
        console.log('calling setup push');
        app.setupPush();
    },
    setupPush: function() {
        console.log('calling push init');
        var push = PushNotification.init({
			android: {
				"senderID": "xxxxxxxxxx"
			},
			browser: {
				pushServiceURL: 'http://push.api.phonegap.com/v1/push'
			},
			ios: {
				alert: "true",
				badge: "true",
				sound: "true"
			},
			windows: {}
			});
        console.log('after init');

        push.on('registration', function(data) {
            console.log('registration event: ' + data.registrationId);
	    console.log('data registration type: ' + data.registrationType);

            var oldRegId = localStorage.getItem('registrationId');
            if (oldRegId !== data.registrationId) {
                // Save new registration ID
                localStorage.setItem('registrationId', data.registrationId);
                // Post registrationId to your app server as the value has changed
            }

            var parentElement = document.getElementById('registration');
            var listeningElement = parentElement.querySelector('.waiting');
            var receivedElement = parentElement.querySelector('.received');

            listeningElement.setAttribute('style', 'display:none;');
            receivedElement.setAttribute('style', 'display:block;');
        });

```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.02 (lollipop)

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Sony Xperia z2

#### Cordova CLI version and cordova platform version
phonegap -v 6.5.1
phonegap platform version android 6.2.1

#### Plugin version

    phonegap-plugin-push  1.10.5

####others
I got also this error when executing on Chrome  59.0.3071.115
Uncaught (in promise) Error: Error registering Service Worker

I also think that im not doing something good, because I can change the senderID to anything, and i still get the registrationID but not the registration type, any kind of help would be really appreciated

thank you in advance

**Comment by macdonst** [comment]
@rince1990 The `registrationType` is not implemented in the v1.x stream. The docs for the earlier version of the plugin can be found here:

https://github.com/phonegap/phonegap-plugin-push/blob/v1.x/README.md
