### ISSUE TITLE
"Error converting bytecode to dex"

### ISSUE THREAD

**Issue by stib** [phonegap/phonegap-plugin-push#1822]
### Expected Behaviour
Android should build without Error
### Actual Behaviour
Android Build gives the following error

Error: /Users/xxx/android/gradlew: Command failed with exit code 1 Error output:
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/zzc;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/zzc;
    	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:594)
    	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:552)
    	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:533)
    	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
    	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
    	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
    	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
    	at com.android.dx.command.dexer.Main.run(Main.java:230)
    	at com.android.dx.command.dexer.Main.main(Main.java:199)
    	at com.android.dx.command.Main.main(Main.java:103)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

### Reproduce Scenario (including but not limited to)
ionic run --device --target=<deviceid> android

or just cordova build android

#### Steps to Reproduce 
I had an old 1.9.2 version of this phonegap-plugin-push. I noticed that when I sent a data notification with force-start set to 1 for Android, the app cam in foreground. Noticed that Issue 1404 captured that and was addressed in updated 1.9.2.

I replaced my plugin with the current 1.9.2 but problem persisted. So I updated that to 1.9.4. When trying to compile with 1.9.4 I got the following error. I then tried with 1.10.4 and get the same error.

> A problem occurred configuring root project 'android'.
> 
> You have not accepted the license agreements of the following SDK components:
> 
>   [SDK Patch Applier v4, Google Repository, Android Support Repository].
> 
>   Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.

So I updated Google Repository and Android Support Repository in Android SDK Manager. After updating this I get the new error "Dex: Error converting bytecode to dex"

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.11.6  Android version is not material as the code is not deployed yet.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Nexus (But not relevant for the problem at hand)

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.4.0
    cordova platform version android                     6.0.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.9.4 (also tried 1.10.4)

#### Logs taken while reproducing problem

The code was building and working fine before I moved to 1.9.4 version of plugin and updated the Google repository code.

Appreciate any help.

Thanks,
Sanjay.

**Comment by macdonst** [comment]
@stib you have another plugin including the Google Play jars which is causing the multiple dex error.

**Comment by stib** [comment]
Thank you @macdonst. How do I go about finding that other plugin using Google Play to fix the issue. I take it I need to update that other plugin to use the new Google Play is that correct?

I need to clean up some of the unused plugins but here is the current list of the plugins I currently have

com.googlemaps.ios 1.13.0 "Google Map iOS SDK for Cordova"
com.transistorsoft.cordova.background-geolocation 2.2.0 "BackgroundGeolocation"
cordova-connectivity-monitor 1.2.2 "Connectivity Monitoring"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-background-fetch 4.0.0 "CDVBackgroundFetch"
cordova-plugin-background-mode 0.6.6-dev "BackgroundMode"
cordova-plugin-badge 0.7.3 "Badges"
cordova-plugin-cocoalumberjack 0.0.1 "CocoaLumberjack"
cordova-plugin-console 1.0.1 "Console"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-dialogs 1.3.0 "Notification"
cordova-plugin-google-analytics 1.6.0 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 1.0.2-dev "InAppBrowser"
cordova-plugin-network-information 1.3.0 "Network Information"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-whitelist 1.0.0 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.10.4 "PushPlugin"
plugin.google.maps 1.3.9 "phonegap-googlemaps-plugin"

**Comment by fredgalvao** [comment]
Possible culprits are `cordova-plugin-google-analytics` and `com.googlemaps.ios`, I'd say without further research. You can try creating a new project and installing push and any of them and see if any combination fails.

**Comment by stib** [comment]
Thanks @fredgalvao - I will try that. Though before I go down that path that feels somewhat non-deterministic and am wondering if there is a more deterministic way to figure this out. 

Are there any suggestions about a more deterministic way to find where the conflict is?

**Comment by fredgalvao** [comment]
Might be helpful if you could provide the full output of the `cordova build android` command. With the info I have right now, unfortunately I don't have a deterministic approach.

**Comment by stib** [comment]
Here is more of the relevant piece of the log (removed the earlier part that didn't seem relevant)

:generateDebugSources
:incrementalDebugJavaCompilationSafeguard
:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:compileDebugNdk UP-TO-DATE
:compileDebugSources
:mergeDebugShaders
:compileDebugShaders
:generateDebugAssets
:mergeDebugAssets
:transformClassesWithDexForDebug
Running dex in-process requires build tools 23.0.2.
For faster builds update this project to use the latest build tools.
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/zzc;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/zzc;
    	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:594)
    	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:552)
    	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:533)
    	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
    	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
    	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
    	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
    	at com.android.dx.command.dexer.Main.run(Main.java:230)
    	at com.android.dx.command.dexer.Main.main(Main.java:199)
    	at com.android.dx.command.Main.main(Main.java:103)
    
:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 52.24 secs
Error: /Users/stibrewal/Personal/Projects/GroupTrac-Android/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/zzc;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/zzc;
    	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:594)
    	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:552)
    	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:533)
    	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
    	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
    	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
    	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
    	at com.android.dx.command.dexer.Main.run(Main.java:230)
    	at com.android.dx.command.dexer.Main.main(Main.java:199)
    	at com.android.dx.command.Main.main(Main.java:103)
    

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by fredgalvao** [comment]
Yeah, I can't figure out any specifics from that, unfortunately.

**Comment by macdonst** [comment]
@stib yeah, look for plugins that include Google Play Services stuff via a framework tag to a jar inside of the repo. They should be using the framework tag to get the jars from Gradle.

**Comment by stib** [comment]
Thank you @macdonst. Sorry if this is supposed to be obvious and I am not familiar with it but where exactly do I look for the framework tag to a jar and what exactly is the tag I am looking for? Can you point me to how to do that in other repos using `phonegap-plugin-push` as an example?

I do see that in the `build.gradle` file in platform/android there is an entry under dependencies for
`compile "com.google.android.gms:play-services-gcm:10.2+"` - I believe that was a lower version (9.2+ if I remember correctly) before I upgraded my Play Repository. Should I start a new project and then add plugins one by one and monitor this `build.gradle` file to see which one adds a line like this?

Thank you for any details you can provide in helping track this down.

**Comment by fredgalvao** [comment]
I went through all your plugins, and for all of those I cound find online, the following ones have framework dependencies declared (assuming you're referencing the original one for each of them on npm):

- [cordova-plugin-badge](https://github.com/katzer/cordova-plugin-badge/blob/master/plugin.xml#L85) (which refers to [src/android/badge.gradle](https://github.com/katzer/cordova-plugin-badge/blob/master/src/android/badge.gradle)) **discarded** as this references no google framework, only shorcutBadger, so no chance of conflict.
- [google-analytics-plugin](https://github.com/danwilson/google-analytics-plugin/blob/master/plugin.xml#L54)
- [cordova-background-geolocation-lt](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/plugin.xml#L72-L73) (which refers to an `aar` file and to [src/android/build.gradle](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/src/android/build.gradle))
- [cordova-plugin-googlemaps](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/plugin.xml#L48-L49)
- and this very own plugin on the 1.x branch [here](https://github.com/phonegap/phonegap-plugin-push/blob/v1.x/plugin.xml#L62-L65)

Now:
- google-analytics-plugin declares it with `"com.google.android.gms:play-services-analytics:+"`, which is an open version, which can cause conflicts like the one you're having
- cordova-background-geolocation-lt declares it with `'com.google.android.gms:play-services-location:+'`, which is an open version, which can cause conflicts like the one you're having
- cordova-plugin-googlemaps declares it with
```
<framework src="com.google.android.gms:play-services-maps:11.+" />
<framework src="com.google.android.gms:play-services-location:11.+" />
```
which is a defined version, which is fine
- and this very own plugin declares it with `<framework src="com.google.android.gms:play-services-gcm:11+"/>`, which is a defined version, which is fine (and will play well with cordova-plugin-googlemaps)

So there you have it. Try creating an empty project with the push plugin and either google-analytics-plugin or  cordova-background-geolocation-lt, and see which one fails.

Now, if you're **not** using the latest minor version for each of those plugins, the case could be totally different, as I don't have enough time to scavenge their commit history, and it should be fairly easy for you to upgrade them, **including this push plugin, which had a very important fix regarding coexisting with different versions of the play services sdk on https://github.com/phonegap/phonegap-plugin-push/issues/1772 and is available on version 1.10.5**.

**Comment by stib** [comment]
Thank you @fredgalvao for the detailed analysis of the plugins - it's going above and beyond! Very much appreciate it.

After trying a few combinations `phonegap-plugin-push` with the 1.10.5 version and replacing `google-analytics-plugin` with the latest version removed the dex compilation error.

I am glad to be past that error now. Though my Android device was forced to upgrade Google Play Services - not something I want to force the App users to do but don't think I have much choice here.

Thanks again. Very much appreciate the help from you and @macdonst

We can close this out.
Sanjay.

**Comment by Danielk10** [comment]
Soy increibles gracias
