### ISSUE TITLE
android.permission.WAKE_LOCK still needed?

### ISSUE THREAD

**Issue by pke** [phonegap/phonegap-plugin-push#1823]
I want to keep my apps permission at a bare minimum. Is the "prevent the phone from sleep" permission still required for this plugin to work?

**Comment by fredgalvao** [comment]
I'd say background notifications and content_available notifications require it. There might be a way to only ask for it when needed? Or maybe make it configurable through `init()`.

**Comment by macdonst** [comment]
Yes, it is required for background processing.
