### ISSUE TITLE
iOS: Not able to schedule local notification after adding the plugin

### ISSUE THREAD

**Issue by sparsh0611** [phonegap/phonegap-plugin-push#183]
Even when a local notification is scheduled, didRegisterForRemoteNotificationsWithDeviceToken method of PushPlugin.m gets called and returns an error "Invalid callback id received by sendPluginResult". Because of this, local notification is not scheduled either.
The plugin used for local notification is - 
https://github.com/katzer/cordova-plugin-local-notifications.git

**Comment by fredgalvao** [comment]
If this means the `cordova-plugin-local-notification` plugin doesn't work well with `phonegap-plugin-push`,  I +1 on fixing it. I was counting on being able to use both plugins on my project.

**Comment by macdonst** [comment]
@sparsh0611 interesting, did you open a similar bug on Local Notifications and link to this one?

**Comment by sparsh0611** [comment]
@macdonst No, since the problem started after the previous PushPlugin was deprecated and I switched to this one, I haven't opened the bug on Local Notifications.

**Comment by macdonst** [comment]
@sparsh0611 kk, thx. It's weird that it would pop up now as the iOS code is nearly identical to the old plugin.

**Comment by sparsh0611** [comment]
@macdonst I'm really grateful for your quick response and all the help. I see that you have added the retest label too. But, my business client is continuously asking me about the progress and also when the issue will be resolved. I'll be really thankful if you could let me know the progress or if you have identified the issue. Thanks.

**Comment by dnish** [comment]
Same problem here with Android, it breaks the building when I use both plugins in my project.

**Comment by macdonst** [comment]
@dnish Go +1 this PR on the local notification plugin as it fixes your issue: https://github.com/katzer/cordova-plugin-local-notifications/pull/697

**Comment by sparsh0611** [comment]
Thanks @EdMcBane for the solution and @macdonst for the quick merge!

**Comment by katzer** [comment]
:+1:
