### ISSUE TITLE
React-native project does not run-android

### ISSUE THREAD

**Issue by kletius** [phonegap/phonegap-plugin-push#1830]
The project is created using "react-native init <Project_Name>" and then, I cd into the folder using the cmd and command "react-native run-android" :

```
* Where:
Build file 'C:\Users\*****\Documents\ReactNative\novo\android\app\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Could not create plugin of type 'AppPlugin'.
```
it points a issue in the file build.gradle in line 1, but line 1 contains:

`apply plugin: "com.android.application"`

Thanks in advance.

**Comment by macdonst** [comment]
@kletius supporting this Apache Cordova/PhoneGap plugin inside of a ReactNative project is out of scope of this project. If you are using ReactNative try: https://github.com/zo0r/react-native-push-notification
