### ISSUE TITLE
How to change title of push notification  in ios 

### ISSUE THREAD

**Issue by ajaysaini95700** [phonegap/phonegap-plugin-push#1831]
i have changed title in notification response but still showing my app name on push notification on ios 10. it is working fine on android 
here is my notification response for ios
```
{"additionalData":{"coldstart":false,"notification_type":"promotion","nid":"10789","type":"news_feed_item","foreground":true,"aps":{"alert":"hello","title":"check"}},"message":"hello","title":"check","sound":"default"} 
```

**Comment by macdonst** [comment]
@ajaysaini95700 you can't change the title of the notification on iOS. iOS always uses your apps icon and name as part of the notification.
