### ISSUE TITLE
Uncaught ReferenceError: PushNotification is not defined

### ISSUE THREAD

**Issue by VirtuallyInvincible** [phonegap/phonegap-plugin-push#1832]
### Expected Behaviour
The following code:
```
var push = PushNotification.init({
              android: {
                icon: "/styles/images/vfblack.ico",
                vibrate: "true",
                sound: "true"
              },
              browser: {
              },
              ios: {
              },
              windows: {
              }
            });
```
Does not fail with a ReferenceError

### Actual Behaviour
The above code fails with "Uncaught ReferenceError: PushNotification is not defined"

### Reproduce Scenario (including but not limited to)
I put the code inside a callback that's called when I click on a button. I reach the code with a breakpoint. When the code runs, I get the above error. I did install the package of course. All other plugins I use work fine.

#### Steps to Reproduce 
Install the package and try to run the code above.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy S7

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.1.1
    cordova platform version android                     6.1.1

#### Plugin version

    cordova plugin version 2.0.0-rc5

**Comment by macdonst** [comment]
@VirtuallyInvincible that version of the plugin needs cordova-android 6.2.1 or higher so it fails to install with an error message during prepare time.

**Comment by VirtuallyInvincible** [comment]
Thank you macdonst.
However, I also tried versions 1.8.4, 1.8.2 and 1.8.0 with the same details in the issue, and I still get the same error. According to the documentation, it should work. Why doesn't it?
