### ISSUE TITLE
Uncaught ReferenceError: PushNotification is not defined

### ISSUE THREAD

**Issue by VirtuallyInvincible** [phonegap/phonegap-plugin-push#1834]
### Expected Behaviour
The following code:
var push = PushNotification.init({
              android: {
                icon: "/styles/images/vfblack.ico",
                vibrate: "true",
                sound: "true"
              },
              browser: {
              },
              ios: {
              },
              windows: {
              }
            });
Does not fail with a ReferenceError

### Actual Behaviour
The above code fails with "Uncaught ReferenceError: PushNotification is not defined"

### Reproduce Scenario (including but not limited to)
I put the code inside a callback that's called when I click on a button. I reach the code with a breakpoint. When the code runs, I get the above error. I did install the package of course. All other plugins I use work fine.

#### Steps to Reproduce 
Install the package and try to run the code above.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy S7

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.1.1
    cordova platform version android                     6.1.1

#### Plugin version

    cordova plugin version 2.0.0-rc5

**Comment by macdonst** [comment]
@VirtuallyInvincible you already opened this issue and I answered it #1832

**Comment by VirtuallyInvincible** [comment]
Thanks Simon! But I have also tried to use versions 1.8.4, 1.8.2 and 1.8.0, and I get the same error message. I do see now that I get an error message when installing the plugin. Why?


________________________________
מאת: Simon MacDonald <notifications@github.com>
‏‏נשלח: יום חמישי 06 יולי 2017 17:53
‏‏אל: phonegap/phonegap-plugin-push
עותק: Virtually Invincible; Mention
‏‏נושא: Re: [phonegap/phonegap-plugin-push] Uncaught ReferenceError: PushNotification is not defined (#1834)


Closed #1834<https://github.com/phonegap/phonegap-plugin-push/issues/1834>.
