### ISSUE TITLE
Push Plugin for ANDROID IONIC 2 not working in prod mode, but works in dev mode

### ISSUE THREAD

**Issue by vickycj** [phonegap/phonegap-plugin-push#1837]
#### Cordova CLI version 6.5.0 and cordova platform version 6.5.0

    cordova plugin version | grep phonegap-plugin-push   all versions

![8ebbe](https://user-images.githubusercontent.com/14138377/27926520-549c5252-62a6-11e7-971a-45860c387cfd.png)

**Comment by vickycj** [comment]
If i use minified main.js it is not working .if i use uncompressed version then it is working

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
