### ISSUE TITLE
Error: has no method 'init' on Android

### ISSUE THREAD

**Issue by OgurSeren** [phonegap/phonegap-plugin-push#1838]
Hi,

I am using the Phonegap-plugin-push plugin while compiling in the Devxtreme application. I write to the config.xml file and create a template. I see the push.js file in the template.
When I install the application in the IOS operating system, the push notification is working.
I am installing the application on Samsung phones. It works without error when first powered on. I get **"Object.function () {} has no method 'init'"** error when I exit the application with the back key and open it again.
I am installing the LG (Android 4.4.2 version) phone application. I get the same mistake every time I open the application.

I can not find the main cause of the problem.

**Tested phones:**  LG G5 Adnroid version 4.4.2
                          Samsung Android 5.0.1
cordova cli 6.4.0
My code examples are as follows;

**XML:**

Plugin name = "phonegap-plugin-push" spec = "~ 1.9.0"
    Variable name = "SENDER_ID" value = "XXXXX" 
Plugin

**JS:**

 $ (Document) .on ("deviceready", function () {
        IsDeviceReady = true;
        hidesplashscre the ();
        alert (1);
        Try {
            Var push = PushNotification.init ({
                "Android": {
                    "SenderID": "XXXXXX"
                },
                "Ios": {
                    "Sound": true,
                    "Vibration": true,
                    "Badge": true
                }
            });
            Alert ("init ok!");
            Push.on ('registration', function (data) {
                alert (data.registrationıd);
            });

            Push.on ('notification', function (data) {
                alert (data.messag A);
            });
            Push.on ('error', function (e) {
                alert (e.Message);
            });
        } Catch (e) {
            alert (e);
        }

        $ (Document) .on ("backbutton", function () {
            devexpress.processhardwarebackbutto the ();
        });
    });

**Comment by macdonst** [comment]
@OgurSeren what version of cordova-android are you using? What is the output of `cordova platforms` and `cordova plugins`?

**Comment by OgurSeren** [comment]
@macdonst  Cordova Version: **cli-6.4.0**

android-minSdkVersion **15**
android-targetSdkVersion **22**

**Comment by macdonst** [comment]
@OgurSeren looking over stuff in more detail I think this is a code issue and not a plugin issue. I can't reproduce the behaviour you are seeing so I have to assume something in your code is setting the `push` object to undefined when you kill the app.

**Comment by OgurSeren** [comment]
@macdonst I receive the error I have received on the phones I have specified, have you tested them? We do not get errors on the IOS operating system and some Android phones.

For all operating systems and versions we run the same code.
We do not encounter this error on all devices.
We thought it was a bug related to the plugin that we encountered on several phones.

**Comment by macdonst** [comment]
@OgurSeren nope, I don't have access to unlimited test devices but I have tested this on phones running Android 4.4 and 5.0. Honestly my best guess at this point is a race condition, for some reason those devices don't have the push code setup by the time you want to call it. If you debug the app can you call `init` after the app is set up to run?

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
