### ISSUE TITLE
Notification received only with WIFI

### ISSUE THREAD

**Issue by agarate** [phonegap/phonegap-plugin-push#1840]
Android. The notification is received only with wifi in the same network, with 4g network is not received. What can be?

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
