### ISSUE TITLE
Failed to install plugin

### ISSUE THREAD

**Issue by VirtuallyInvincible** [phonegap/phonegap-plugin-push#1843]
### Expected Behaviour
Plugin installs successfully without error messages

### Actual Behaviour
Installation fails even though the plugin is added to the plugins folder of the project. I get the following in the installation log:
TypeError: Cannot read property 'SENDER_ID' of undefined
    at C:\Users\shaim1\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\6.1.1\node_modules\cordova\node_modules\cordova-lib\src\cordova\plugin.js:155:93
    at Array.filter (native)
    at C:\Users\shaim1\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\6.1.1\node_modules\cordova\node_modules\cordova-lib\src\cordova\plugin.js:153:30
    at _fulfilled (C:\Users\shaim1\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\6.1.1\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\shaim1\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\6.1.1\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\shaim1\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\6.1.1\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\shaim1\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\6.1.1\node_modules\cordova\node_modules\q\q.js:557:44
    at flush (C:\Users\shaim1\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\6.1.1\node_modules\cordova\node_modules\q\q.js:108:17)
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)

### Reproduce Scenario (including but not limited to)
Trying to install version 1.8.0 of the plugin.

#### Steps to Reproduce 
Go to config.xml and tap Plugins -> Custom -> local -> select the folder containing the extracted plugin (after downloading it as zip).

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy S7

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.1.1
    cordova platform version android                     # e.g. 6.1.1

#### Plugin version

    phonegap-plugin-push   1.8.0

**Comment by VirtuallyInvincible** [comment]
Note that the issue is reproduced even though I did add a SENDER_ID (one that I made up - there are no instructions that I know of about how to create one). In the source code of config.xml I see:
<plugin name="phonegap-plugin-push" version="1.8.0" src="C:\Users\shaim1\Downloads\phonegap-plugin-push-1.8.0">
    <variable name="SENDER_ID" value="1:956432534015:android:df211t13n7267439" />
  </plugin>

**Comment by VirtuallyInvincible** [comment]
`<plugin name="phonegap-plugin-push" version="1.8.0" src="C:\Users\shaim1\Downloads\phonegap-plugin-push-1.8.0">
    <variable name="SENDER_ID" value="1:956432534015:android:df211t13n7267439" />
  </plugin>`

**Comment by macdonst** [comment]
@VirtuallyInvincible I have no idea how you are installing this plugin. Your steps to reproduce don't look like anything I've ever done to add a plugin into a project.

Since you are using 1.8.0 you'd be better off looking at that tags documentation:

https://github.com/phonegap/phonegap-plugin-push/blob/v1.8.0/docs/INSTALLATION.md

**Comment by jcesarmobile** [comment]
The sender ID is probably just `956432534015 `.
Why don't you try with a newer version of the plugin?

**Comment by VirtuallyInvincible** [comment]
I didn't want to update the Cordova version of my project initially. That's why I tried with an older version. In older versions you must provide the SENDER ID when installing the plugin or it will fail. After some configuration and updating of my android SDK, I can now use the latest version of the plugin.
