### ISSUE TITLE
Where do you get the third (id) parameter for the finish call

### ISSUE THREAD

**Issue by stib** [phonegap/phonegap-plugin-push#1844]
Hi,

I am probably missing something obvious but can't seem to figure out where do you get the third parameter for the finish call. The API Reference document has the following sample

```
push.finish(function() {
	console.log('success');
}, function() {
	console.log('error');
}, 'push-1');
```
But I don't know where do I get the equivalent of 'push-1' id.

The document doesn't list this as optional parameter - apparently a required parameter. However calling it without the parameter seems to work though I don't know if it has any side effect - like making iOS terminate my App in the background. Digging into it further I see that in push.js there is a default allocation as below

`    if (!id) { id = 'handler'; }`

What does this 'handler' string refer to? Tried looking through the ios code for finish in PushPlugin.m but don't quite understand that language/code there. I want to make sure I am not giving iOS reasons to terminate my app in the background by not calling finish properly. 

Answers to template questions for the ticket, on versions of code I have, didn't seem relevant here so am skipping that. Happy to provide that if that is needed.

Thanks,
Sanjay.

**Comment by macdonst** [comment]
@stib it's documented here: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications-1

Basically you pass a unique ID along as part of the push data and use that to tell the system you are done processing the push notification.

If you don't pass a unique ID to finish it will use the default one. You could get into trouble if you send two background notifications to your iOS app at the same time as it will only be able to tell one the background processing is done. The other will terminate after 30 seconds by the OS.
