### ISSUE TITLE
Failed to install plugin using latest git

### ISSUE THREAD

**Issue by ievhenganchin** [phonegap/phonegap-plugin-push#1845]
### Expected Behaviour
Install should go smooth

### Actual Behaviour
Failed to fetch plugin from 'git+https://github.com/phonegap/phonegap-plugin-push.git'
https://www.screencast.com/t/F5dhYodoSvH

#### Steps to Reproduce 
Get latest Git.
Run 'cordova plugin add phonegap-plugin-push --variable SENDER_ID=XXXXXXXX'

It's really weird issue. Found this one few days ago. Figure out that source of this problem was recently updated Git and rolled back it. Locally all works fine.

But! Yesterday I have uploaded latest build to Ionic.io (Cloud platform is restoring all plugin references on their side, and it looks like they have latest Git - so all my builds are missing your push plugin)

Moreover, tried same scenario on Mac Pro with latest Git - same errors. Git just can't fetch plugin...

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Windows 10, Mac OS Sierra.
Ionic.io cloud services

#### Cordova CLI version and cordova platform version

    cordova --version                                   7.0.1
    cordova platform version android                     6.2.3

#### Plugin version

    Latest one

**Comment by macdonst** [comment]
@ievhenganchin what version of git do you have? Also, this is most probably an issue with cordova and not with the plugin but I want to get more info first.

**Comment by ievhenganchin** [comment]
@macdonst ,

Issue can be reproduced on 2.13.2.
For now I'm using 2.9.2 without any such issues at all.

**Comment by macdonst** [comment]
@ievhenganchin awesome, thanks for the heads up. I'm using 2.10.1 without any issues.

**Comment by macdonst** [comment]
@ievhenganchin what platform did you install 2.13.2 on and how did you get it? The latest I can get for the Mac (not building from src) is 2.13.1 and it doesn't exhibit the above problem.

**Comment by ievhenganchin** [comment]
@macdonst 

Windows 10 x64, from official site

**Comment by ievhenganchin** [comment]
Problem is with latest cordova, not Git itself. You were right. As soon as I run 'cordova platform update android' - installing of your plugin start being impossible.

Full text log of error:

Error: Failed to fetch plugin

        git+https://github.com/phonegap/phonegap-plugin-push.git via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! Error while executing:
        npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t
        https://github.com/phonegap/phonegap-plugin-push.git
        npm ERR!
        npm ERR! fatal: Unable to find remote helper for 'https'
        npm ERR!
        npm ERR! exited with error code: 128

**Comment by impactotecnologico** [comment]
Which is the solution?

**Comment by ievhenganchin** [comment]
Install plugin using cordova only:

"cordova plugin add phonegap-plugin-push ..."
instead of
"ionic cordova plugin add phonegap-plugin-push ..."

Problem was on ionic side.
