### ISSUE TITLE
When receiving force-start, application flashes on screen.

### ISSUE THREAD

**Issue by Moghul** [phonegap/phonegap-plugin-push#1846]
### Expected Behaviour
Application received force-start : 1 flag, it starts in the background, and no one notices what is happening.
### Actual Behaviour
Application received force-start : 1 flag, but the application starts up in foreground and half a second later it moves to the background.
### Reproduce Scenario (including but not limited to)
1 a) Unlock the phone and leave it on the home screen
b) Lock the phone

2) Send a push notification with the following payload:

```
        $arguments = [
            'to' => $notificationKey,
            'data' => [
                'customKey' => 'hidden stuff',
                'force-start' => 1
            ],
            'priority' => 'high',
            'content_available' => true
        ];
```

3 a) see the app briefly appear on screen and disappear
b) Unlock the phone, see the app briefly appear on screen and disappear

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1

iOS yet untested.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Android on Oneplus One

#### Cordova CLI version and cordova platform version
    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1
Cordova version 6.4.0
Android 6.0.0
#### Plugin version
Plugin version 1.9.1
    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

#### Sample Push Data Payload
```
        $arguments = [
            'to' => $notificationKey,
            'data' => [
                'customKey' => 'hidden stuff',
                'force-start' => 1
            ],
            'priority' => 'high',
            'content_available' => true
        ];
```
#### Logs taken while reproducing problem
07-11 13:40:49.451 11498 11515 D PushPlugin_GCMIntentService: onMessage - from: sender id goes here
07-11 13:40:49.451 11498 11515 D PushPlugin_GCMIntentService: normalize extras
07-11 13:40:49.451 11498 11515 D PushPlugin_GCMIntentService: key = google.sent_time
07-11 13:40:49.452 11498 11515 D PushPlugin_GCMIntentService: replace key google.sent_time with google.sent_time
07-11 13:40:49.452 11498 11515 D PushPlugin_GCMIntentService: key = force-start
07-11 13:40:49.452 11498 11515 D PushPlugin_GCMIntentService: replace key force-start with force-start
07-11 13:40:49.452 11498 11515 D PushPlugin_GCMIntentService: key = customKey
07-11 13:40:49.452 11498 11515 D PushPlugin_GCMIntentService: replace key customKey with customKey
07-11 13:40:49.452 11498 11515 D PushPlugin_GCMIntentService: key = gcm.notification.content_available
07-11 13:40:49.452 11498 11515 D PushPlugin_GCMIntentService: replace key gcm.notification.content_available with content_available
07-11 13:40:49.452 11498 11515 D PushPlugin_GCMIntentService: key = google.message_id
07-11 13:40:49.452 11498 11515 D PushPlugin_GCMIntentService: replace key google.message_id with google.message_id
07-11 13:40:49.452 11498 11515 D PushPlugin_GCMIntentService: background
07-11 13:40:49.452 11498 11515 D PushPlugin_GCMIntentService: message =[null]
07-11 13:40:49.452 11498 11515 D PushPlugin_GCMIntentService: title =[null]
07-11 13:40:49.452 11498 11515 D PushPlugin_GCMIntentService: contentAvailable =[true]
07-11 13:40:49.452 11498 11515 D PushPlugin_GCMIntentService: forceStart =[1]
07-11 13:40:49.452 11498 11515 D PushPlugin_GCMIntentService: app is not running but we should start it and put in background
07-11 13:40:49.466  1570  4188 I ActivityManager: START u0 {flg=0x10000000 cmp=my app id/com.adobe.phonegap.push.PushHandlerActivity (has extras)} from uid 10386 on display 0
07-11 13:40:49.491 11498 11498 D PushPlugin_PushHandlerActivity: not id = 0
07-11 13:40:49.491 11498 11498 V PushPlugin_PushHandlerActivity: onCreate
07-11 13:40:49.491 11498 11498 D PushPlugin_PushHandlerActivity: callback = null
07-11 13:40:49.491 11498 11498 D PushPlugin_PushHandlerActivity: bringToForeground = false
07-11 13:40:49.494 11498 11498 V PushPlugin: sendExtras: caching extras to send at a later time.
07-11 13:40:49.796  1570  3724 I WindowManager: Screenshot max retries 4 of Token{4ce7d52 ActivityRecord{b3b5ddd u0 my app id/com.adobe.phonegap.push.PushHandlerActivity t508 f}} appWin=Window{51d4c49 u0 Starting my app id} drawState=3
07-11 13:40:49.797 11498 11498 D PushPlugin_PushHandlerActivity: isPushPluginActive = false
07-11 13:40:49.805  1570  3719 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x14000004 pkg=my app id cmp=my app id/.MainActivity (has extras)} from uid 10386 on display 0
07-11 13:40:49.830 11498 11498 I CordovaLog: Changing log level to DEBUG(3)

I have also looked at other similar threads and I should say that my MainActivity looks normal:

```
public class MainActivity extends CordovaActivity
{
    @Override
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);

        // enable Cordova apps to be started in the background
        Bundle extras = getIntent().getExtras();
        if (extras != null && extras.getBoolean("cdvStartInBackground", false)) {
            moveTaskToBack(true);
        }

        // Set by <content src="index.html" /> in config.xml
        loadUrl(launchUrl);
    }
}
```

Seems to me like there's too much time between the app opening and being forced to the background.

EDIT: I should probably make it clear that other than that, the background force-start functionality works as I would expect it to.

**Comment by macdonst** [comment]
@Moghul sorry there is nothing I can do about it. There is no way to start an app in the background. So what I need to do is start the app and immediately move it to the background. On older phones or phones low on resources may see this flash.

**Comment by Moghul** [comment]
That may be true, but Oneplus One is not very old, and we support much older phones.
