### ISSUE TITLE
PushNotification is not defined after update CLI and plugin version

### ISSUE THREAD

**Issue by madsongr** [phonegap/phonegap-plugin-push#1847]
### Expected Behaviour
No errors on $ionicPlatform.ready();

### Actual Behaviour
Uncaught ReferenceError: PushNotification is not defined

### Reproduce Scenario (including but not limited to)
After updating Intel XDK CLI from 6.2.0 to 6.5.0 and removed Phonegap Plugin Push v1.8.2 to install v2.0.0-rc5 from git repo I get the error mentioned above.

#### Cordova CLI version and cordova platform version

    cordova --version 6.5.0    
    cordova platform version android 6.5.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push  2.0.0-rc5

#### Sample Code that illustrates the problem
      .run(function($ionicPlatform, $state, $ionicPopup) {
      $ionicPlatform.ready(function() {

      onDeviceReady();

      function onDeviceReady(){
    
        var push = PushNotification.init({
            android: {
                senderID: "**************",
                sound: true,
                vibrate: true
            },
            browser: {},
            ios: {
                alert: "true",
                badge: "true",
                sound: "true"
            },
            windows: {}
        });

        push.on('registration', function(data) {
            //data.registrationId;
        }); 

        push.on('notification', function(data) {
            // data.message,
            // data.title,
            // data.count,
            // data.sound,
            // data.image,
            // data.additionalData
           
        });

        push.on('error', function(e) {
            // e.message
        });
       }
      });
      }

#### Logs taken while reproducing problem
Uncaught ReferenceError: PushNotification is not defined
    at onDeviceReady (VM129 app.js:71)
    at VM129 app.js:35
    at Array.<anonymous> (VM125 ionic.bundle.js:56238)
    at Channel.onPlatformReady (VM125 ionic.bundle.js:2496)
    at Channel.subscribe (VM128 cordova.js:715)
    at HTMLDocument.document.addEventListener (VM128 cordova.js:133)
    at onWindowLoad (VM125 ionic.bundle.js:2473)

**Comment by madsongr** [comment]
I´ll test it again but the error disappeared after I add

        "phonegap-plugin-push": {
            "SENDER_ID": "*************",
            "PACKAGE_NAME": "io.cordova.hellocordova"
        }
in android.json and ios.json. I compared them with my backup with v1.8.2 and xdk was not adding that automatically.

**Comment by fredgalvao** [comment]
You should not have to edit those `json` files yourself at all. Either `Intel XDK CLI` is not being completely efficient at installing plugins, or your workspace is somehow missing something that cordova expected to be there.

Can you try creating a  new project with the same cli and adding the plugin?

**Comment by macdonst** [comment]
@madsongr run the command `cordova platform` and make sure the versions you are using match the required versions for 2.0.0. 

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements

**Comment by madsongr** [comment]
@fredgalvao I created a new project and the same issue happened. There are four json files: android.json, ios.json, windows.json and fetch.json. XDK is adding the plugin only in fetch.json:

    "phonegap-plugin-push": {
        "source": {
            "type": "git",
            "url": "https://github.com/phonegap/phonegap-plugin-push",
            "subdir": "."
        },
        "is_top_level": true,
        "variables": {
            "SENDER_ID": "77777777"
        }
    }

Plugin version 1.8.x has already worked fine for me in another xdk projects.

**Comment by madsongr** [comment]
@macdonst it looks like cordova-android version is not ok. When building the project this was the log:

    Fetching plugin "https://github.com/phonegap/phonegap-plugin-push" via git clone
Using shallow clone
    Repository "https://github.com/phonegap/phonegap-plugin-push" checked out to git ref "master" at "2a8e3df".
    Installing "phonegap-plugin-push" at "2.0.0-rc5" for android
    Plugin doesn't support this project's cordova-android version. cordova-android: 6.1.2, failed version 
    requirement: >=6.2.1
    Skipping 'phonegap-plugin-push' for android

**Comment by macdonst** [comment]
@madsongr right, you need to have cordova-android 6.2.1 or better for the 2.x stream.

**Comment by mcarroll92** [comment]
Did the same thing as above user. Updated plugin and CLI and now Push Notification is undefined.

```
$ cordova -v
7.0.1
$ cordova platform
Installed platforms:
  android 6.2.3
  browser 4.1.0

```

**Comment by chrillewoodz** [comment]
I'm still having this problem with android 6.3.0 and plugin 2.1.0..
