### ISSUE TITLE
'notification' event not fired in foreground (Android/Phonegap/AngularJS/Phonegap Developer App)

### ISSUE THREAD

**Issue by simentesempre** [phonegap/phonegap-plugin-push#1849]
### Expected Behaviour
while in foreground 'registration' and 'notification' event fired

### Actual Behaviour
while in foreground 'registration' event is fired but 'notification' event is not

### Reproduce Scenario
I'm building an app using
AngularJS 1.6.4
Phonegap 6.5.2

I'm working on 
Phonegap Developer App 1.7.10

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.1.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Xiaomi

#### Cordova CLI version and cordova platform version
    phonegap --version                                    6.5.2
    phonegap platform version android           6.1.2

#### Plugin version
    phonegap-plugin-push    1.10.5

#### Sample Push Data Payload
I'm using the Phonegap CLI push command for the Phonegap Developer App  http://docs.phonegap.com/references/phonegap-cli/push/
`phonegap push --deviceID [deviceID] --service gcm --payload "{\"data\":{\"title\":\"hello\",\"message\":\"world\"}}"`

#### Sample Code that illustrates the problem
Here the JS code to intiate the plugin
```
function onDeviceReady() {	
	angular.bootstrap(document, ["module"]);
	var push = PushNotification.init({
		"android": {
			senderID:"XXXXXXXX"
		},
		"ios": {
			vibration: true,
			badge: true,
			sound: true
		}
	});
	push.on('registration', function(data) {
		console.log(data.registrationId);
	});
	push.on('notification', function(data) {
		console.log(data.message);
	});
	push.on('error', function(e) {
		console.log(e);
	});
}
document.addEventListener('deviceready', onDeviceReady, true);
```

Here the config.xml
```
<plugin name="phonegap-plugin-push" spec="~1.10.5">
        <variable name="SENDER_ID" value="XXXXXXXXX" />
    </plugin>
```

#### Logs taken while reproducing problem
No logs

**Comment by macdonst** [comment]
@simentesempre hey, sorry for the confusion. Some code got release in 6.5.2 that changes the service type from gcm to fcm for Android. I need to go update our documentation. In the meantime you should be able to use this command for testing:

```
phonegap push --deviceID [deviceID] --service fcm --payload "{\"data\":{\"title\":\"hello\",\"message\":\"world\"}}"
```

**Comment by simentesempre** [comment]
Wow, that was it. Thank you very much @macdonst

**Comment by macdonst** [comment]
@simentesempre no problem, again sorry for the confusion. The transition to FCM has been a bit of a pain. I'm going to leave this issue open until I fix the docs.
