### ISSUE TITLE
Ionic 2, Android notification received but banner not showing on device: " no locale found for key " error

### ISSUE THREAD

**Issue by vishmurale** [phonegap/phonegap-plugin-push#1850]
### Expected Behavior
Expected to see notification banner on Android device 

### Actual Behavior
Don't see notification banner on Android device 

### Reproduce Scenario (including but not limited to)

Using Ionic 2 and node-gcm (to send notifications) 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
LG 

#### Cordova CLI version and cordova platform version
  
    cordova version                                              7.0.1
    cordova platform version android                 6.2.3

#### Plugin version
   phonegap-plugin-push                                   2.0.0-rc5

#### Sample Push Data Payload

So with node-gcm I have the following to create the payload:

```		   
                   var message = new gcm.Message() 

		   message.addData('title', 'HI!!!');

		   message.addData('message', "Hi There");

		  message.addData('sound', 'default');


```

#### Sample Code that illustrates the problem
Here's my ionic 2 code if you'd like to see:

```

      initPushNotification() {

    if (!this.platform.is('cordova')) {
      console.warn("Push notifications not initialized. Cordova is not available - Run in physical device");
      return;
    }
    const options: PushOptions = {
      android: {
        senderID: "****"
      },
      ios: {
        alert: "true",
        badge: false,
        sound: "true"
      },
      windows: {}
    };
    
    const pushObject: PushObject = this.push.init(options);

      pushObject.on('registration').subscribe((data: any) => {
      console.log("device token ->", data.registrationId);
      
      
      if (this.platform.is('android')) {
                  this.api_post.post_id(data.registrationId,true)
                   console.log("running on Android device!");
      }
      else if (this.platform.is('ios')) {
                    this.api_post.post_id(data.registrationId,false)
                    console.log("running on iOS device!");
                
      }
    });
    
    pushObject.on('error').subscribe(error => console.error('Error with Push plugin', error));
    
    }
```

#### Logs taken while reproducing problem

So basically I'm seeing logs like this, somewhat similar to what was seen in issue #1764 when I have the app running in Android Studio:

07-12 19:15:22.563 6703-12769/com.ionicframework.schoolscheduler163274 D/Push_FCMService: onMessage - from: ******
07-12 19:15:22.563 6703-12769/com.ionicframework.schoolscheduler163274 D/Push_FCMService: normalize extras
07-12 19:15:22.563 6703-12769/com.ionicframework.schoolscheduler163274 D/Push_FCMService: key = sound
07-12 19:15:22.563 6703-12769/com.ionicframework.schoolscheduler163274 D/Push_FCMService: replace key sound with sound
07-12 19:15:22.563 6703-12769/com.ionicframework.schoolscheduler163274 D/Push_FCMService: key = title
07-12 19:15:22.563 6703-12769/com.ionicframework.schoolscheduler163274 D/Push_FCMService: replace key title with title
07-12 19:15:22.563 6703-12769/com.ionicframework.schoolscheduler163274 D/Push_FCMService: no locale found for key = title, error Value HI!!! of type java.lang.String cannot be converted to JSONObject
07-12 19:15:22.563 6703-12769/com.ionicframework.schoolscheduler163274 D/Push_FCMService: key = message
07-12 19:15:22.563 6703-12769/com.ionicframework.schoolscheduler163274 D/Push_FCMService: replace key message with message
07-12 19:15:22.563 6703-12769/com.ionicframework.schoolscheduler163274 D/Push_FCMService: no locale found for key = message, error Value Hi of type java.lang.String cannot be converted to JSONObject
07-12 19:15:22.563 6703-12769/com.ionicframework.schoolscheduler163274 D/Push_FCMService: foreground
07-12 19:15:22.563 6703-12769/com.ionicframework.schoolscheduler163274 D/Push_Plugin: convert extras to json
07-12 19:15:22.563 6703-12769/com.ionicframework.schoolscheduler163274 D/Push_Plugin: key = sound
07-12 19:15:22.563 6703-12769/com.ionicframework.schoolscheduler163274 D/Push_Plugin: key = title
07-12 19:15:22.563 6703-12769/com.ionicframework.schoolscheduler163274 D/Push_Plugin: key = message
07-12 19:15:22.563 6703-12769/com.ionicframework.schoolscheduler163274 D/Push_Plugin: key = coldstart
07-12 19:15:22.563 6703-12769/com.ionicframework.schoolscheduler163274 D/Push_Plugin: key = foreground
07-12 19:15:22.563 6703-12769/com.ionicframework.schoolscheduler163274 V/Push_Plugin: extrasToJSON: {"message":"Hi There","additionalData":{"foreground":true,"coldstart":false},"title":"HI!!!","sound":"default"}

Am I creating the payload wrong with node-gcm?

**Comment by macdonst** [comment]
@vishmurale is your app in the foreground or background when you receive the push message?

**Comment by vishmurale** [comment]
@macdonst It was in the foreground. I was monitoring the logs while the app was running.

**Comment by macdonst** [comment]
@vishmurale right and if the app is in the foreground the notification is not shown in the system tray. That only happens when the notification is received while the app is in the background.

**Comment by vishmurale** [comment]
@macdonst The notification doesn't show up even if the app is in the background. Also what do you mean by "system tray"? Even if the app is in the foreground, shouldn't I see the banner at the top when the notification is delivered?

**Comment by technocodz** [comment]
Hi Guys, i am facing the same issue, please let me know if you found any solution

**Comment by mdashiff** [comment]
In Option add foreground: true. It will work
