### ISSUE TITLE
Subscribe on topic in iOS

### ISSUE THREAD

**Issue by Nelo-cool** [phonegap/phonegap-plugin-push#1853]
### Expected Behaviour
After subscribe will be receive push messages
### Actual Behaviour
After successed subscribe (without error) never received messages. But android with same code working or if send for "User segment" in FCM Console - working. But send to topic - not working.

### Reproduce Scenario (including but not limited to)
FCM Console https://console.firebase.google.com
#### Steps to Reproduce 
1. subscribe to topic 'all-android' for Android
3. subscribe to topic 'all-ios' for iOS
2. send to topic 'all-android' message
3. received, good work on android
4. send to topic 'all-ios' message
5. never received messages, bad work on iOS:(
6. send to all user for application - "User segment" in console
7. received, good work on iOS, but this can only in FCM Console.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0
iOS 10.3.2
#### Cordova CLI version and cordova platform version

    cordova --version   7.0.1
    cordova platform version android                     # e.g. 4.1.1
    cordova platform version ios 4.4.0
#### Plugin version

    cordova plugin version | grep phonegap-plugin-push    2.0.0 rc5

#### Sample Code that illustrates the problem
```
let push = PushNotification.init({
            android: {
                iconColor: "#233577"
            },
            ios: {
                alert: "true",
                badge: true,
                sound: 'false'
            },
        });

        let topic = isiOS() ? "all-ios" : "all-android";

        push.subscribe(topic, function () {
           alert('subscribe success: ' + topic);
        }, function (e) {
            alert('subscribe error:');
            alert(e);
        });

        push.on('registration', function (data) {
            alert('registrationId:' + data.registrationId);
        });

        push.on('notification', function (data) {
            alert('push:' + JSON.stringify(data));
        });

        push.on('error', function (e) {
            alert('error: ' + e.message);
        });
````
#### Logs taken while reproducing problem
without logs, but with screen from iOS
![img_0445](https://user-images.githubusercontent.com/902820/28172140-6e272164-67f3-11e7-81c4-d44cb663b7eb.PNG)
![img_0446](https://user-images.githubusercontent.com/902820/28172141-6e29fe98-67f3-11e7-9695-344ec796df10.PNG)

**Comment by jcesarmobile** [comment]
Sorry about that, when I ported from GCM to FCM I didn't try this feature, and on GCM you had to add the topics like this: `"/topics/topic-name"`, but on FCM you pass the topic name directly. I've sent a PR removing it

**Comment by macdonst** [comment]
@jcesarmobile that may have gotten screwed up in a merge because I remember it getting deleted. Thanks for the quick fix.

**Comment by Nelo-cool** [comment]
Thanks for all! But how can i get version with fix?

**Comment by Nelo-cool** [comment]
Oh, good. PR Pull request^^:) Waiting....

**Comment by macdonst** [comment]
@Nelo-cool sorry, I had to take a phone call. Pull the latest from master and let me know if that fixes your issue, it should.

**Comment by Nelo-cool** [comment]
Okay! cordova plugin rm phonegap-push... cordova plugin add
Please wait a few minutes!:)

**Comment by Nelo-cool** [comment]
Doesn't work! But i see in my plugins src:  [pubSub subscribeToTopic:topic];
This is fantastic!:(

**Comment by Nelo-cool** [comment]
![image](https://user-images.githubusercontent.com/902820/28185706-136e1f1a-6821-11e7-832f-823385cd9eb9.png)
this list refresh only 3-5 hours, after create topic. Android topics added, ios no:(

**Comment by jcesarmobile** [comment]
I don't see my topics on the list neither, but if I manually write them, the push arribes to the device.

**Comment by Nelo-cool** [comment]
Hmm, what am I doing wrong?
1. cordova plugin rm phonegap-plugin-push
2. cordova plugin add https://github.com/phonegap/phonegap-plugin-push
3. build
Maybe cached... okay, I'll try again. Thanks!

**Comment by Nelo-cool** [comment]
Hello my guys! Clear all caches, rebuild all, sent, but the push not delivered on device.
maybe i must replace "all-ios" on "/topics/all-ios"? It seems to be there:( 
History:
My code, work right on android and "user segment" for ios:
![image](https://user-images.githubusercontent.com/902820/28238718-7a2c8f56-6962-11e7-82a5-b92eb1eaa2c4.png)
Version plugin and source:
![image](https://user-images.githubusercontent.com/902820/28238727-b8a53dbe-6962-11e7-9ef6-e536f2bd195f.png)
![image](https://user-images.githubusercontent.com/902820/28238736-d960b448-6962-11e7-98ac-80e75916a450.png)
Message:
![image](https://user-images.githubusercontent.com/902820/28238738-085cd696-6963-11e7-8fcf-e136fea5a3a8.png)

Maybe i have wrong when installing plugin?

**Comment by Nelo-cool** [comment]
Try with registrationId for ios -> delivered! But topic not. Trying to...

**Comment by jcesarmobile** [comment]
Can you open the project double clicking on /platforms/ios/yourprojectname.xcworspace and check the plugin code there?
Also, running from there might give some more information, doing that is how I saw that the calls to subscribe to topics where failing

**Comment by Nelo-cool** [comment]
Excuse me, my dear friend, i am busy now, but tomorrow i can try this! Thanks for you!

**Comment by Nelo-cool** [comment]
Hello! In project:
![image](https://user-images.githubusercontent.com/902820/28363285-a2d56648-6c88-11e7-9b7e-d655bace6570.png)
try debugging with breakpoint.

**Comment by Nelo-cool** [comment]
Hmm.. successefully subscribe!
Step 1
![image](https://user-images.githubusercontent.com/902820/28363457-52b3fb2e-6c89-11e7-9d0e-a49286b4659e.png)
Step 2
![image](https://user-images.githubusercontent.com/902820/28363504-78dd2122-6c89-11e7-8c34-b4439400658a.png)

**Comment by Nelo-cool** [comment]
Thanks! I win! Step for win:
1. unsubscribe on topic with trouble!
2. subscribe again
3. work is good!
Thanks for all!

**Comment by robinvalk** [comment]
In addition to @Nelo-cool's comment above. When using a remote content source via https://github.com/TruckMovers/cordova-plugin-remote-injection for example. Do not forget to force quit the app and reopen it.

**Comment by Juanpam** [comment]
@Nelo-cool It would be really nice if you could give a more detailed guide on how you resolved the issue. How do I unsubscribe to the topic with trouble? I got this same problem. I can receive notifications via Token id but not by topics

**Comment by Nelo-cool** [comment]
Hi! Library contains methods for subscribe and unsubscribe topic! On first step call unsubscribe method with topic parameter. After on second step - call subscribe again with your topic and work is good:) as soon as do not call unnecessary unsubscribe method.

**Comment by jaigtz88** [comment]
@Nelo-cool not working for me. @Juanpam , did u solve it?

**Comment by Juanpam** [comment]
I fixed it adding the topics to the configuration object on iOS (topics: ['myTopic'])  and also unsubscribing and subscribing again the topics using the plug in functions. That fixed my problem!

**Comment by jaigtz88** [comment]
@Juanpam sorry, how to do this, adding the topics to the configuration object on iOS (topics: ['myTopic'])?

**Comment by neogenz** [comment]
@Nelo-cool 
Perfect ! Thanks !!! you save my day !

Something like that in my `notification.service.ts` : 

```ts
private subscribeNotificationsTo(topic: string): void {
        this.pushStream.subscribe(topic)
            .then((failNotification: PushNotification) => {
                this.pushStream.unsubscribe(topic); //this is the hook
                this.pushStream.subscribe(topic) //this is the hook
                    .then((notification: PushNotification) => {
                        this.sentToNotificationsCenter(notification);
                    });
            });
    }
```

And after with my payload, the result perfectly work !
