### ISSUE TITLE
Ionic v3 - native push seems to have significantly changed

### ISSUE THREAD

**Issue by uj** [phonegap/phonegap-plugin-push#1854]
### Expected Behaviour
An Ionic v2 project should work in Ionic v3

### Actual Behaviour
Ionic v3 seems to have changed the format of native push so that it no longer matches the plugin documentation

### Reproduce Scenario (including but not limited to)
The following code works properly in Ionic v2:
`push.on('registration', (data) => ... `
In Ionic v3, that causes an error "supplied parameters do not match any signature", and it is required to do this instead:
`push.on('registration').subscribe((data: any) =>`

However, so far I have not been able to get push.finish to work in v3.

This works fine in Ionic v2:
```
push.finish(function()
{console.log("success");},
function() {console.log("failure")},
some_numeric_variable
);
```

However, in Ionic v3, it says "Supplied parameters do not match any signature of call target."

Does anyone have any insight into this?  Why was this changed so much in Ionic v3, and how can I make this work, especially push.finish ?

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Ionic v3.5

#### Cordova CLI version and cordova platform version
7.0.1

#### Plugin version
1.10.5

**Comment by macdonst** [comment]
Sorry @uj you will have to go ask on the Ionic forums as this plugin has nothing to do with the Ionic Native wrapper.
