### ISSUE TITLE
Disable vibration on toggle select

### ISSUE THREAD

**Issue by madsongr** [phonegap/phonegap-plugin-push#1856]
1) Is it possible to create a function to toggle vibrate: true/false on a toggle select? I read the docs but could not find it.

2) The same way with a toggle select, is it possible to stop receiving push notifications? Should I use push.unregister() ?

Thanks in advance.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
