### ISSUE TITLE
PhoneGap Build fails with 2.0.0-rc5

### ISSUE THREAD

**Issue by uj** [phonegap/phonegap-plugin-push#1857]
### Expected Behaviour
Plugin should be included with project build on phonegap build with plugin version 2.0.0-rc5, per a twitter comment I read.

### Actual Behaviour
It gives this error:
Fetching plugin "https://github.com/phonegap/phonegap-plugin-push" via git clone
Using shallow clone
Repository "https://github.com/phonegap/phonegap-plugin-push" checked out to git ref "master" at "781e6f5".
Installing "phonegap-plugin-push" at "2.0.0-rc5" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.1.2, failed version requirement: >=6.2.1
Skipping 'phonegap-plugin-push' for android

**Comment by macdonst** [comment]
@uj yup, I was just talking to the guys about it this week. They don't have the necessary versions of cordova-android and cordova-ios up yet but once they do this plugin can go from release candidate to official.

https://build.phonegap.com/current-support
