### ISSUE TITLE
config.xml

### ISSUE THREAD

**Issue by ArgosHon** [phonegap/phonegap-plugin-push#1859]
Is there somewhere to find an example config.xml for /build.phonegap.com that would work with 2.0.0rc5 ?

**Comment by macdonst** [comment]
@ArgosHon The latest version of this plugin, the 2.x stream, is not yet supported on PGB as it requires cordova-ios 4.4.0+ and cordova-android 6.2.1+

https://build.phonegap.com/current-support

I've talked to the PGB team and they are working on updating the CLI version and cordova versions.

**Comment by jcesarmobile** [comment]
@macdonst in plugin.xml and package.json it requires cordova >=6.4.0, shouldn't it be >=7.0.0?
That way, I think PGB should pick 1.10.x instead of 2.x
