### ISSUE TITLE
Version 1.10.5 fails to tell the differente between Windows and macOS

### ISSUE THREAD

**Issue by andreszs** [phonegap/phonegap-plugin-push#1861]
### Expected Behaviour
Installing version 1.10.5 locally under Visual Studio 2015 and Windows 8.1 should not prompt to install CocoaPods. Is it really that hard to tell the difference between OS platforms? 

### Actual Behaviour
CocoaPods was not found. Please install version 1.0.1 or greater from https://cocoapods.org/

**You are critically misleading developers who already have enough to struggle making notifications work under all platforms, devices and scenarios. Please avoid this in the future, for the love of God.**

#### Cordova CLI version and cordova platform version
6.5.0

#### Plugin version
1.10.5 (missing changes log in GitHub)

**Comment by fredgalvao** [comment]
That has been [reported before](https://github.com/phonegap/phonegap-plugin-push/issues/1721) and is being done/tracked at https://issues.apache.org/jira/browse/CB-12856.
