### ISSUE TITLE
Error: Failed to fetch plugin phonegap-plugin-push@2.0.0 via registry

### ISSUE THREAD

**Issue by madsongr** [phonegap/phonegap-plugin-push#1862]
### Expected Behaviour
Install plugin with cordova comamand line
### Actual Behaviour
Error: Failed to fetch plugin phonegap-plugin-push@2.0.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code ENOENT
### Reproduce Scenario (including but not limited to)
cordova plugin add phonegap-plugin-push is not installing plugin in windows cmd. Reading a post from stackoverflow I tried with npm install phonegap-plugin-push. It works but it seems not to install completely. Console says PushNotification is not definied even after adding required code to package.json and config.xml.
I installed git for windows but the error continues.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Windows 10 Pro

#### Cordova CLI version and cordova platform version

    cordova --version  7.0.1
    cordova platform version android  6.2.2
    nodejs version 6.11.1
    npm version 3.10.10
    ionic version 3.5.0
    git version 2.13.3.windows.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.0.0

#### Sample Code that illustrates the problem
cordova plugin add phonegap-plugin-push command line
#### Logs taken while reproducing problem
Error: Failed to fetch plugin phonegap-plugin-push@2.0.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code ENOENT

**Comment by cristovao-trevisan** [comment]
Same problem here, solved by selecting the current version with:
`cordova plugin add phonegap-plugin-push@2.0.0-rc5`

**Comment by macdonst** [comment]
@madsongr there is no 2.0.0 release. We are at release candidate 5 so 2.0.0-rc5 would be valid.

**Comment by madsongr** [comment]
@cristovao-trevisan it didn´t work for me :(

**Comment by cristovao-trevisan** [comment]
You need to remove the current installed version first. Did you do that?

**Comment by madsongr** [comment]
@macdonst I just tried to install with cordova plugin add phonegap-plugin-push as docs say. Yesterday it was returning 

     Error: Failed to fetch plugin phonegap-plugin-push@1.10.5 via registry.

with the same command

**Comment by madsongr** [comment]
@cristovao-trevisan yes I did

**Comment by macdonst** [comment]
@madsongr did you do a `cordova platform update platform_type`?

**Comment by cristovao-trevisan** [comment]
Yes, I am using the latest version for both cordova and cordova-android, but try running this first:

    cordova plugin add phonegap-plugin-push@latest --save

**Comment by madsongr** [comment]
@macdonst when I did `cordova platform update platform_type` it says

    Error: Failed to fetch platform platform_type
    Probably this is either a connection problem, or platform spec is incorrect.
    Check your connection and platform name/version/URL.
    Error: cmd: Command failed with exit code ENOENT

**Comment by madsongr** [comment]
@cristovao-trevisan same error here :(

**Comment by madsongr** [comment]
I installed phonegap-cli and ran **phonegap plugin add phonegap-plugin-push**.
Is this the expected result?

    Fetching plugin "phonegap-plugin-push@1.10.5" via npm
    Saved plugin info for "phonegap-plugin-push" to config.xml

**Comment by cristovao-trevisan** [comment]
No, you are installing the 1.10.5 version. You need the @2.0.0-rc5 or @latest at the end of the command
