### ISSUE TITLE
Linker error for iOS build

### ISSUE THREAD

**Issue by cristovao-trevisan** [phonegap/phonegap-plugin-push#1863]
Trying to build for iOS using the latest cocoapods (1.2.1) but failed with the following error (from terminal running cordova build ios):

    ld: library not found for -lGoogleToolboxForMac

The Xcode error is:

    Mach-O Linker (id) Error
### Versions

- cordova: 7.0.1
- cordova-ios: 4.4.0
- plugin version: 2.0.0-rc5

### Temporary Solution

Downgrading the cocoapods to 1.0.1 solved the issue, must be some link flag renaming issue

**Comment by Nelo-cool** [comment]
This is true:) But build from xcode, step by step (pods project -> application), buid successefully finished.
Temporary Solution does't work for me.

**Comment by Nelo-cool** [comment]
-Xlinker -final_output -Xlinker /Applications/ГТРК\ «Ивтелерадио».app/ГТРК\ «Ивтелерадио» -fobjc-arc -fobjc-link-runtime -ObjC -ObjC -lGoogleToolboxForMac -lProtobuf -lc++ -lnanopb -lsqlite3 -lz -framework AddressBook -framework FirebaseAnalytics -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseInstanceID -framework FirebaseMessaging -framework FirebaseNanoPB -framework StoreKit -framework SystemConfiguration -ObjC -lGoogleToolboxForMac -lProtobuf -lc++ -lnanopb -lsqlite3 -lz -framework AddressBook -framework FirebaseAnalytics -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseInstanceID -framework FirebaseMessaging -framework FirebaseNanoPB -framework StoreKit -framework SystemConfiguration /Users/vladimir/.taco_home/remote-builds/taco-remote/builds/332/cordovaApp/platforms/ios/build/device/libCordova.a -weak_framework AudioToolbox -framework StoreKit -lz -weak_framework Social -weak_framework MessageUI -Xlinker -dependency_info -Xlinker /Users/vladimir/Library/Developer/Xcode/DerivedData/ГТРК_«Ивтелерадио»-bgfapltdbhhroydvgcpbqebtnryd/Build/Intermediates/ArchiveIntermediates/ГТРК\ «Ивтелерадио»/IntermediateBuildFilesPath/ГТРК\ «Ивтелерадио».build/Release-iphoneos/ГТРК\ «Ивтелерадио».build/Objects-normal/armv7/ГТРК\ «Ивтелерадио»_dependency_info.dat -o /Users/vladimir/Library/Developer/Xcode/DerivedData/ГТРК_«Ивтелерадио»-bgfapltdbhhroydvgcpbqebtnryd/Build/Intermediates/ArchiveIntermediates/ГТРК\ «Ивтелерадио»/IntermediateBuildFilesPath/ГТРК\ «Ивтелерадио».build/Release-iphoneos/ГТРК\ «Ивтелерадио».build/Objects-normal/armv7/ГТРК\ «Ивтелерадио»
ld: warning: directory not found for option '-L/Users/vladimir/Library/Developer/Xcode/DerivedData/ГТРК_«Ивтелерадио»-bgfapltdbhhroydvgcpbqebtnryd/Build/Intermediates/ArchiveIntermediates/ГТРК «Ивтелерадио»/BuildProductsPath/Release-iphoneos/GoogleToolboxForMac'
ld: warning: directory not found for option '-L/Users/vladimir/Library/Developer/Xcode/DerivedData/ГТРК_«Ивтелерадио»-bgfapltdbhhroydvgcpbqebtnryd/Build/Intermediates/ArchiveIntermediates/ГТРК «Ивтелерадио»/BuildProductsPath/Release-iphoneos/Protobuf'
ld: warning: directory not found for option '-L/Users/vladimir/Library/Developer/Xcode/DerivedData/ГТРК_«Ивтелерадио»-bgfapltdbhhroydvgcpbqebtnryd/Build/Intermediates/ArchiveIntermediates/ГТРК «Ивтелерадио»/BuildProductsPath/Release-iphoneos/nanopb'
ld: library not found for -lGoogleToolboxForMac
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by macdonst** [comment]
I would try removing and re-adding the ios platform to your project first.

**Comment by Nelo-cool** [comment]
Try reinstall (cordova platform remove, add ios)
Try reinstall push plugin, but same error:(
But open scheme and check Pods-ГТРК:
![image](https://user-images.githubusercontent.com/902820/28526945-cb3d5606-7091-11e7-8539-addda2f2251f.png)

After build Pods-ГТРК, continue build Application workspace - successefully. But i can't be found IPA file! All directories are empty (3 screen, device is empy and sharedpch is empty too). 
![image](https://user-images.githubusercontent.com/902820/28526987-e426dca0-7091-11e7-9ee3-67e668d616ad.png)
![image](https://user-images.githubusercontent.com/902820/28527020-f5d013c2-7091-11e7-85cf-d572be85ad3c.png)
![image](https://user-images.githubusercontent.com/902820/28527148-5aa38a5e-7092-11e7-9b31-4f7510cb5fc0.png)

**Comment by jcesarmobile** [comment]
I think the problem is related to this Cordova issue https://issues.apache.org/jira/browse/CB-12582

When you install the plugins before adding the platform (or you have them in the config.xml and add the platform), then `libPods-projectName.a` is not added to the project, causing this library not found error.

Workarounds are to add the platform first and install the plugins later, or to manually run `pod install` on projectName/platforms/ios/

**Comment by Nelo-cool** [comment]
THANKS MY DEAR FRIENDS! Pod install and all right! Good day for all!:)

**Comment by Zorgatone** [comment]
@timkim I'm still unable to link `ld: library not found for -lGoogleToolboxForMac` (I even tried to add/remove the ios platform and phonegap-plugin-push, and run `pod install` afterwards inside `platforms/ios`) using this environment (macOS High Sierra with Node JS v6.11.3 and pod v1.1.1):

```
 zorgatone@TR  ~/repos/my-app   ios11-update ●  ionic plugin list
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.8 "Ionic's WKWebView Engine"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-toast 2.6.0 "Toast"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.0.0 "PushPlugin"


{}

```

```
 zorgatone@TR  ~/repos/my-app   ios11-update ●  ionic platform list
{}

Installed platforms:
  android 6.3.0
  ios 4.5.1
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  browser ~4.1.0
  osx ~4.0.1
  webos ~3.7.0

```

**Comment by gnazarkin** [comment]
@Zorgatone same problem as you. Tried pod install, adding and removing platform. You end up resolving it?

**Comment by Zorgatone** [comment]
@gnazarkin I downgraded to 1.8.4 which worked fine without cocoapods 😆

**Comment by lamuertepeluda** [comment]
You should reopen this issue. I'm stuck in the same way as @Zorgatone ! 😞

**Comment by benwyrosdick** [comment]
I am having the same issue

```
$ phonegap platform list

Installed platforms:
  browser 5.0.1
  ios 4.5.2
Available platforms:
  android ~6.3.0
  blackberry10 ~3.8.0 (deprecated)
  osx ~4.0.1
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0
  windows ~5.0.0
  www ^3.12.0
```

**Comment by skoubin** [comment]
I had the same issue when I upgraded to 1.10.5 ( from 1.8.4 ).

I solved it by opening the Xcode project using the **{project-name}..xcworkspace** file instead of the **{project-name}.xcodeproj**. Then I selected my project from the list (not the Pods one) and built it successfully.

My environment:
```
- OS Sierra
- Xcode 9
- Cordova CLI 7.1.0
- Cordova Android 6.3.0
- Cordova  ios 4.5.2
```

**Comment by tobiasmuecksch** [comment]
I just had this issue and was able to fix it by removing and then re-adding phonegap-plugin-push to my project.

`cordova plugin rm phonegap-plugin-push`
`cordova plugin add phonegap-plugin-push`

**Comment by tbassett44** [comment]
We use fastlane/gym to package a release of the app and found that to properly include the pod files we had to update our gym command to point to the workspace (as mentioned above), eg
fastlane gym --workspace "[project]/platforms/ios/[name].xcworkspace" ...
