### ISSUE TITLE
PushPlugin.m:30:9:  fatal error: 'GoogleCloudMessaging.h' file not found

### ISSUE THREAD

**Issue by thimmaiah** [phonegap/phonegap-plugin-push#1864]
### Expected Behaviour
ionic app would compile for ios with the plugin

### Actual Behaviour
Build fails with the logs shown below
```
PushPlugin.m:30:9:
        fatal error: 'GoogleCloudMessaging.h' file not found

```
#### Steps to Reproduce 
install the plugin and compile - it fails

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPhone 6S

#### Cordova CLI version and cordova platform version

    cordova --version 
    7.0.1
    cordova platform version ios
    4.4.0

#### Plugin version
cordova plugin ls
code-push 2.0.1-beta "CodePushAcquisition"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-code-push 1.9.5-beta "CodePush"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-filepath 1.0.2 "FilePath"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-deploy 0.6.7 "IonicDeploy"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.10.5 "PushPlugin"

#### Logs taken while reproducing problem

> cordova build ios
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.
        
[ERROR] An error occurred while running cordova build ios (exit code 1):
        
        (truncated) ... nuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/Care\
        Connuct.build/Debug-iphonesimulator/Care\ Connuct.build/Care\ Connuct-generated-files.hmap
        -I/Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/Care\
        Connuct.build/Debug-iphonesimulator/Care\ Connuct.build/Care\ Connuct-own-target-headers.hmap
        -I/Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/Care\
        Connuct.build/Debug-iphonesimulator/Care\ Connuct.build/Care\ Connuct-all-target-headers.hmap -iquote
        /Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/Care\
        Connuct.build/Debug-iphonesimulator/Care\ Connuct.build/Care\ Connuct-project-headers.hmap
        -I/Users/NehaiMac/work/UberNurseUI/platforms/ios/build/emulator/include
        -I/Users/NehaiMac/work/UberNurseUI/platforms/ios/build/emulator/usr/local/lib/include
        -I/Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/UninstalledProducts/include
        -I/Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/UninstalledProducts/iphonesimulator/include
        -I/Users/NehaiMac/work/UberNurseUI/platforms/ios/build/emulator
        -I/Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/Care\
        Connuct.build/Debug-iphonesimulator/Care\ Connuct.build/DerivedSources/x86_64
        -I/Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/Care\
        Connuct.build/Debug-iphonesimulator/Care\ Connuct.build/DerivedSources
        -F/Users/NehaiMac/work/UberNurseUI/platforms/ios/build/emulator -include
        /Users/NehaiMac/work/UberNurseUI/platforms/ios/build/sharedpch/Care\
        Connuct-Prefix-gmekdsgwcmctcdajieqcbnnmsind/Care\ Connuct-Prefix.pch -MMD -MT dependencies -MF
        /Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/Care\
        Connuct.build/Debug-iphonesimulator/Care\ Connuct.build/Objects-normal/x86_64/PushPlugin.d
        --serialize-diagnostics
        /Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/Care\
        Connuct.build/Debug-iphonesimulator/Care\ Connuct.build/Objects-normal/x86_64/PushPlugin.dia -c
        /Users/NehaiMac/work/UberNurseUI/platforms/ios/Care\ Connuct/Plugins/phonegap-plugin-push/PushPlugin.m -o
        /Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/Care\
        Connuct.build/Debug-iphonesimulator/Care\ Connuct.build/Objects-normal/x86_64/PushPlugin.o
        In file included from /Users/NehaiMac/work/UberNurseUI/platforms/ios/Care
        Connuct/Plugins/phonegap-plugin-push/PushPlugin.m:29:
        /Users/NehaiMac/work/UberNurseUI/platforms/ios/Care Connuct/Plugins/phonegap-plugin-push/PushPlugin.h:32:35:
        warning: cannot find protocol definition for 'GGLInstanceIDDelegate'
        @interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate, GCMReceiverDelegate>
        ^
        /Users/NehaiMac/work/UberNurseUI/platforms/ios/Care Connuct/Plugins/phonegap-plugin-push/PushPlugin.h:30:11:
        note: protocol 'GGLInstanceIDDelegate' has no definition
        @protocol GGLInstanceIDDelegate;
        ^
        /Users/NehaiMac/work/UberNurseUI/platforms/ios/Care Connuct/Plugins/phonegap-plugin-push/PushPlugin.h:32:58:
        warning: cannot find protocol definition for 'GCMReceiverDelegate'
        @interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate, GCMReceiverDelegate>
        ^
        /Users/NehaiMac/work/UberNurseUI/platforms/ios/Care Connuct/Plugins/phonegap-plugin-push/PushPlugin.h:31:11:
        note: protocol 'GCMReceiverDelegate' has no definition
        @protocol GCMReceiverDelegate;
        ^
        /Users/NehaiMac/work/UberNurseUI/platforms/ios/Care Connuct/Plugins/phonegap-plugin-push/PushPlugin.m:30:9:
        fatal error: 'GoogleCloudMessaging.h' file not found
        #import "GoogleCloudMessaging.h"
        ^
        2 warnings and 1 error generated.
        
        ** BUILD FAILED **
        
        
        The following build commands failed:
        CompileC
        /Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/Care\
        Connuct.build/Debug-iphonesimulator/Care\ Connuct.build/Objects-normal/x86_64/PushPlugin.o Care\
        Connuct/Plugins/phonegap-plugin-push/PushPlugin.m normal x86_64 objective-c
        com.apple.compilers.llvm.clang.1_0.compiler
        (1 failure)
        Error: Error code 65 for command: xcodebuild with args:
        -xcconfig,/Users/NehaiMac/work/UberNurseUI/platforms/ios/cordova/build-debug.xcconfig,-workspace,Care
        Connuct.xcworkspace,-scheme,Care Connuct,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS
        Simulator,name=iPhone
        SE,build,CONFIGURATION_BUILD_DIR=/Users/NehaiMac/work/UberNurseUI/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/NehaiMac/work/UberNurseUI/platforms/ios/build/sharedpch

**Comment by thimmaiah** [comment]
Podfile is
```
# DO NOT MODIFY -- auto-generated by Apache Cordova
platform :ios, '8.0'
target 'Care Connuct' do
        project 'Care Connuct.xcodeproj'
        pod 'GoogleCloudMessaging', '~> 1.2.0'
        pod 'GGLInstanceID', '~> 1.2.1'
end
```

I cant see a Podfile.lock being generated though

**Comment by macdonst** [comment]
@thimmaiah do you have cocoapods installed?

**Comment by thimmaiah** [comment]
Yes I do have cocoapods. The problem was that there was a conflict with some other plugins, specifically the ionic-deploy & the camera-preview. I removed them, re-installed ios platform, re installed pods and now it is working. Thank you for responding to my problem, please go ahead and close it
