### ISSUE TITLE
Changing the Notification Sound

### ISSUE THREAD

**Issue by malwatte** [phonegap/phonegap-plugin-push#1865]
How to change the notification sound?
I want to change the notification sound only for our app (I do not want to change the default notification sound selected in device settings, so that sound will not change for other apps). And users can change the notification sound of the app through settings screen of the app. I do not need to use custom sounds, device notification sounds are sufficient.

One example is facebook app.
Any ideas how to do it greatly appreciated.

**Comment by robinvalk** [comment]
Check out the iOS and Android specific details at: https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support

**Comment by malwatte** [comment]
Actually I want to set the sound from the device itself, without setting in the payload.

**Comment by macdonst** [comment]
@malwatte the sound being played is controlled by the payload. If you want to switch the sound from the app then you'll need to get your app to send the registration ID and new sound name to your application server. Then everytime your app server sends to that registration ID it should set the sound in the payload to the one the users wants to hear.

**Comment by malwatte** [comment]
@macdonst After many searches found that it is possible to change notification before it is shown to the user. This is in iOS 10.
https://developer.apple.com/documentation/usernotifications/unnotificationserviceextension
https://code.tutsplus.com/tutorials/ios-10-notification-service-extensions--cms-27550
