### ISSUE TITLE
error: No value for senderID with google-services.json

### ISSUE THREAD

**Issue by d3w201** [phonegap/phonegap-plugin-push#1867]
i have add  "google-services.json" on my cordova project root folder then i add  this line : 
`<resource-file src="google-services.json" target="google-services.json" />`
on my config.xml even in cordova root folder (not in android or ios subfolder) but it continue to ask for senderID... why?

cordova -v = 7.0.1
phonegap-plugin-push -v = 1.10.5 
```

onDeviceReady: function() {
		this.log('[app] lsd deviceready');		

        var push = PushNotification.init({
            android: {}
        });

        push.on('registration', function(data) {
            app.log('lsd registrationId: ' + data.registrationId);
        });

        push.on('notification', function(data) {
            app.log('lsd: ' + data.message);
            app.log('lsd title: ' + data.title);
        });


        push.on('error', function(e) {
            app.log('lsd error: ' + e.message);
        });

```

and that's the log : 

```
/Push_Plugin(29998): execute: action=init
/Push_Plugin(29998): execute: data=[{"android":{}}]
/Push_Plugin(29998): execute: jo={}
/Push_Plugin(29998): execute: Got JSON Exception No value for senderID
/Push_Plugin(29998): no icon option
/Push_Plugin(29998): no iconColor option
[....]
file:///android_asset/www/js/index.js: Line 216 : lsd error: No value for senderID
[INFO:CONSOLE(216)] "lsd error: No value for senderID"
```

**Comment by d3w201** [comment]
maybe i have to put manually the google-services.json on my platform android root folder?

**Comment by macdonst** [comment]
@d3w201 right this is because version 2.x of the plugin reads from `google-services.json` while you are using version 1.x which needs it included in the object passed to the init method. Docs for the older version of the plugin are preserved at:

https://github.com/phonegap/phonegap-plugin-push/tree/v1.x
