### ISSUE TITLE
Fails to register in iOS 10 / aps-environment entitlement

### ISSUE THREAD

**Issue by iowaz** [phonegap/phonegap-plugin-push#1868]
### Expected Behaviour
GCM or APNS token register it and be able to send notifications.

### Actual Behaviour
It fails to register with aps-enviroment error. When I upload the .ipa to Apple Store, it says the enviroment is actually PRODUCTION (see below).

### Reproduce Scenario (including but not limited to)

I tried a few variations, like removing GCM/FCM completly (for using APNS) and exporting with Ad Hoc provisioning profile.

#### Steps to Reproduce 
> Installed CocoaPods.

> ionic cordova plugin add phonegap-plugin-push --variable SENDER_ID=myidhere
> ionic cordova platform add ios
> ionic cordova build ios --prod --release

Then in Xcode:

>Opened .xcworkspace from platforms/ios.
> Set-up my Provisioning Profile for both debug/release (created earlier).
> in Capabilities turned ON for Push Notifications (it didn't show any kinda of alert, just enabled and gotta it), check Remote Notifications.
Then archived it, gotta a "Build Succeded". Uploaded it to Apple Store.

Then in iTunes Store, checked the Activity tab, go to the recently uploaded version, succesfully approved, and gotta that info:
>HomeList.app/HomeList
application-identifier: (my app here)
get-task-allow: false
beta-reports-active: true
aps-environment: **production**
com.apple.developer.team-identifier: (my team id here)

Then back to Xcode, exported the SAME version with option "Save for iOS App Store Deployment", uploaded it to TestObject.com (kinda of a device farm), choose the phone and gotta the error when trying to register.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.0 / iPhone 5

#### Cordova CLI version and cordova platform version

    Cordova: 7.0.1
    iOS: 4.4.0
    Node: v6.11.0
    OS: macOS Sierra
    Xcode: Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim: 5.1.0 
    npm: 3.10.10

#### Plugin version

    1.10.5

#### Sample Code that illustrates the problem
(Using Angular 4 with TypeScript and Ionic Wrapper to Plugin Push)

>const options: PushOptions = {
	android: {
		senderID: '63098252493'
	},
	ios: {
		senderID: '63098252493',
		gcmSandbox: true,
		alert: true,
		badge: true,
		sound: false
	}
};
this.pushObject = this.push.init(options);
this.pushObject.on('registration').subscribe((registration: any) => {
	console.log('Device registered', registration);
	this.push_token = registration.registrationId;
	this.storage.set("push_notification_id", registration.registrationId);
});

#### Logs taken while reproducing problem
>HomeList[314] <Notice>: Push Plugin register called 
HomeList[314] <Notice>: Push Plugin register called 
HomeList[314] <Notice>: PushPlugin.register: setting badge to false 
HomeList[314] <Notice>: PushPlugin.register: clear badge is set to 0 
HomeList[314] <Notice>: PushPlugin.register: better button setup 
HomeList[314] <Notice>: GCM Sender ID 63098252493 
HomeList[314] <Notice>: Using GCM Notification 
HomeList[314] <Notice>: Using GCM Sandbox 
SpringBoard(SpringBoard)[47] <Info>: setting object for key=NotificationCategoryRecords bundleID=<private> object=<private> 
SpringBoard(SpringBoard)[47] <Notice>: **No valid 'aps-environment' entitlement string found for application 'br.com.orangepixel.homelist': (null). Notifications will not be delivered**. 
HomeList[314] <Notice>: Push Plugin register **failed**

**Comment by jcesarmobile** [comment]
If it's in production mode you have to set `gcmSandbox` to `false`

**Comment by iowaz** [comment]
Hi @jcesarmobile , changed it to false, but gotta the same error **(no valid 'aps-environment' entitlement string found for application)**.

![alt title](http://i.imgur.com/0wvi6rn.png "Xcode")


checking the log, I can find some parts where it do something related with push.apple.com and some parts with sandbox.push.apple.com), like that:

```
2017-07-23 12:22:13.000	INFO:	UserEventAgent(UserEventAgent)[22] <Notice>: 2017-07-23 15:22:13 -0700 UserEventAgent[22]: <PCInterfaceUsabilityMonitor: 0x15dccbb0> [NonCellular](en0): isInterfaceUsable? YES reachable YES linkQuality 100 isNetworkCaptive? NO 
2017-07-23 12:22:13.000	INFO:	apsd(PersistentConnection)[82] <Notice>: 2017-07-23 15:22:13 -0700 apsd[82] com.apple.apsd(push.apple.com)-NonCellular: <PCConnectionManager: 0x14e4c710> _adjustPollTimerIfNecessary rightStyle NO isRunning YES isInReconnectMode NO intervalTimer <PCPersistentTimer: 0x14e56ec0> firingIsImminent NO - should Adjust? NO 
2017-07-23 12:22:13.000	INFO:	UserEventAgent(UserEventAgent)[22] <Notice>: 2017-07-23 15:22:13 -0700 UserEventAgent[22]: <PCInterfaceUsabilityMonitor: 0x15dccbb0>: _flushStaleTransitionsOnIvarQueue: old: ( 
2017-07-23 12:22:13.000	INFO:	) new: (
2017-07-23 12:22:13.000	INFO:	apsd(PersistentConnection)[82] <Notice>: 2017-07-23 15:22:13 -0700 apsd[82] com.apple.apsd(sandbox.push.apple.com)-WWAN: <PCConnectionManager: 0x14d54400> _adjustPollTimerIfNecessary rightStyle NO isRunning NO isInReconnectMode NO intervalTimer (null) firingIsImminent NO - should Adjust? NO 
2017-07-23 12:22:13.000	INFO:	UserEventAgent(UserEventAgent)[22] <Notice>: 2017-07-23 15:22:13 -0700 UserEventAgent[22]: <PCInterfaceUsabilityMonitor: 0x15dccbb0> [NonCellular](en0): isInterfaceHistoricallyUsable? YES trackUsability YES offTransitions ( 
2017-07-23 12:22:13.000	INFO:	apsd(PersistentConnection)[82] <Notice>: 2017-07-23 15:22:13 -0700 apsd[82] com.apple.apsd(sandbox.push.apple.com)-NonCellular: <PCConnectionManager: 0x14d9b6c0> _adjustPollTimerIfNecessary rightStyle NO isRunning NO isInReconnectMode NO intervalTimer (null) firingIsImminent NO - should Adjust? NO 
```

Also, I have found the same issue as this guy (details just below): https://stackoverflow.com/questions/42292363/aps-environment-is-always-development
Inside /platforms/ios/HomeList (my app name)/HomeList.entitlements, it's set in development, like that:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>aps-environment</key>
	<string>**development**</string>
</dict>
</plist>
```
If I change it manually to **production**, in Capabilities tab on Xcode it gives a error or sets it back automatically to **development**. Should I do something in Xcode to set the project in production, or archiving it automatically does it?

**Comment by jcesarmobile** [comment]
You can't test push notifications on the simulator.

Also, Cordova doesn't use the .entitlements file, you probably clicked the push notifications switch in Xcode and created it, that might be conflicting with Cordova or with the plugin.

But if you have the .entitlements file and build the app from Xcode then you shouldn't have problems, as the stackoverflow question says, it automatically changes on the built app based on the option you use to build the app.

**Comment by iowaz** [comment]
@jcesarmobile , it isn`t a simulator, its a real device from TestObject.com (I can confirm by the options outside the app)

![alt title](http://i.imgur.com/NLhzRHF.png "Device from TestObject")

**Comment by iowaz** [comment]
Removed the platform and added it again, but this time, didn`t check the Push Notifications on Capabilities tab (since this creates the entitlements file), and gotta the same error.

PS: is the xcode the best way to compile on my machine?

**Comment by iowaz** [comment]
Whoooops!

Just found that TestObject resigns the .ipa file, so that is the probably cause.

Sorry for that.

**Comment by rkjamvi** [comment]
Hi,

I am using PGB and below is my config.xml code, still iOS 10+ devices are not generating device token:

<preference name="phonegap-version" value="cli-6.5.0" />
	<preference name="android-build-tool" value="gradle" />

<plugin name="phonegap-plugin-push" spec="~1.10.5" source="npm"/> 
     
	<config-file platform="ios"  parent="aps-environment">
       <string>production</string>
     </config-file>
 
Please advise if there is something missing in it. This is working great for iOS 9 devices and android all devices.
