### ISSUE TITLE
Version 1.9.0, failed to install phonegap-plugin-push [iOS template]

### ISSUE THREAD

**Issue by pieruz** [phonegap/phonegap-plugin-push#1869]
### Expected Behaviour
I'm using DevExtreme (based on phonegap). I successfully tested the plugin on Android. I'd like to make the same with iOS, creating, at first step, the native template. 

### Actual Behaviour
When I try to build the native template, I get some errors. Here the output:

> Build for ios is started
> 
> Uploading iOS keys...
> 
> Completed
> 
> Uploading an application template...
> 
> Completed
> 
> Building status: pending (13 attempts)
> 
> Building status: error ("plugman install --platform ios --project /tmp/gimlet/2719563/project --plugin phonegap-plugin-push@1.9.0": Fetching plugin "phonegap-plugin-push@1.9.0" via npm
> 
> Installing "phonegap-plugin-push" at "1.9.0" for ios
> 
> Failed to install 'phonegap-plugin-push':undefined undefined )
> 
> Removing iOS keys...
> 
> Completed
> 
> Removing the application template...
> 
> Completed
> 
> Error: Building status: error ("plugman install --platform ios --project /tmp/gimlet/2719563/project --plugin phonegap-plugin-push@1.9.0": Fetching plugin "phonegap-plugin-push@1.9.0" via npm
> 
> Installing "phonegap-plugin-push" at "1.9.0" for ios
> 
> Failed to install 'phonegap-plugin-push':undefined undefined )_

#### Sample Code that illustrates the problem

This is my config.xml file:

```
<widget id="com.devexpress.apptemplate" version="1.0" versionCode="1">
  <name>ApplicationTemplate</name>
  <description>Template</description>
  <preference name="phonegap-version" value="cli-6.4.0" />
  <preference name="permissions" value="none" />
  <preference name="prerendered-icon" value="true" />
  <preference name="android-windowSoftInputMode" value="adjustPan" />
  <preference name="SplashScreen" value="splash" />
  <preference name="SplashScreenDelay" value="60000" />
  <preference name="AutoHideSplashScreen" value="false" />
  <preference name="SplashShowOnlyFirstTime" value="false" />
  <preference name="FadeSplashScreen" value="false" />
  <preference name="ShowSplashScreenSpinner" value="false" />
  <preference name="DisallowOverscroll" value="true" />
  <preference name="StatusBarOverlaysWebView" value="false" />
  <preference name="StatusBarBackgroundColor" value="#000000" />
  <preference name="android-minSdkVersion" value="15" />
  <preference name="android-targetSdkVersion" value="22" />
  <!--<plugin name="cordova-plugin-file" />-->
  <plugin name="cordova-plugin-geolocation" />
  <plugin name="cordova-plugin-splashscreen" onload="true" />
  <plugin name="cordova-plugin-whitelist" />
  <plugin name="cordova-plugin-ios-longpress-fix" />
  <plugin name="cordova-plugin-statusbar" onload="true" />

  <plugin name="phonegap-plugin-push" spec="1.9.0"/>

  <access origin="*" />
</widget>
```

**Comment by pieruz** [comment]
I don't know I can't view the code I posted

**Comment by macdonst** [comment]
@pieruz do you have cocoapods installed?

**Comment by jcesarmobile** [comment]
Also, latest version is 1.10.5, try with that one

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
