### ISSUE TITLE
What is the latest stable and functional version for IOS?

### ISSUE THREAD

**Issue by noveweb** [phonegap/phonegap-plugin-push#1872]
Hi guys!

What is the latest stable and functional version for IOS? I'm using 1.9.4 + cordova cli-6.5.0 + Phonegap cloud builder. The prompt and registration works fine, but not receive any notifications.

Thanks in advance!

**Comment by jcesarmobile** [comment]
1.10.5 should work fine in Phonegap build

**Comment by noveweb** [comment]
All versions is not working on IOS using Phonegap build cli-6.5.0. Only the ONE SIGNAL plugin works for me.

https://documentation.onesignal.com/docs/phonegap-sdk-setup

**Comment by macdonst** [comment]
the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.

**Comment by noveweb** [comment]
I will! Thanks, @macdonst!
