### ISSUE TITLE
GCM Notifications not received on iOS when gcmSandbox is set to false

### ISSUE THREAD

**Issue by stib** [phonegap/phonegap-plugin-push#1874]
### Expected Behaviour
GCM Notifications should be received for Release/Production Build for iOS (I am checking this through XCode)

### Actual Behaviour
GCM Notifications are not received when using gcmSandbox set to false (Checking through XCode)

### Reproduce Scenario (including but not limited to)
When I set the gcmSandbox value to false I stop getting notifications on iPhone but when I set that to true I get the notifications. This behavior is independent of what I set the aps-environment variable to in the entitlements file - same behavior for both "development" and "production" values.

If I am understanding the plugin documentation correctly then when gcmSandbox is set to false and code is built for development then the notifications should not work either but independent of what the aps-environment value is set to, as long as gcmSandbox is true iOS device receives notification and doesn't receive notifications when gcmSandbox is set to false.

Note that Android devices, also registered to the same topic receive the notifications for all combinations so the notifications are actually going out.

#### Steps to Reproduce 
1. Set aps-environment variable to any value - "production" or "development"
2. Set gcmSandbox value to false when calling PushNotification.init
3. Send a notification from another device running the App (Android or iOS)
4. Notice in XCode debug that the notification message is not received on iOS device but in Chrome debug see that notification is received on Android devices

When the gcmSandbox flag is changed to true then the message is received on iOS device.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.2.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
N/A

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.4.0
    cordova platform version android              
Installed platforms:
  android 6.0.0
  ios 4.3.1
#### Plugin version
    cordova plugin version | grep phonegap-plugin-push   1.10.5

Thank you for any help or pointers to debug/resolve the issue.

A related issue I am not clear on is how does Firebase know which of the two uploaded certificates to use given both the Development and Production certificates are uploaded in the Project.

Thanks,
Sanjay.

**Comment by jcesarmobile** [comment]
gcmSandbox doesn't make the app build in development or production, that's something you have to do on Xcode or Cordova CLI.
If you build for development you have to set gcmSandbox to true, and if you build for production you have to set it to false.
As you are building for development and you have set gcmSandbox to false, they don't match and it doesn't work.
