### ISSUE TITLE
Notifications delivered to APN but not displayed on iOS

### ISSUE THREAD

**Issue by lmark83** [phonegap/phonegap-plugin-push#1875]
### Expected Behaviour
Notification delivered to APN and displayed on IOS

### Actual Behaviour
iOS does not display the push notification.

#### Steps to Reproduce 
Send a push notification to the device by using APN.

#### Cordova CLI version and cordova platform version

    cordova --version                                    # 6.5.0
    cordova platform version ios                   # 4.3.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # 1.9.4

#### Sample Push Data Payload

$payload['aps'] = array(
				'alert' => array(
						'body' => "my message"
				),
				'content-available' => 1,
				'badge'=>1,
				'sound' => 'default',
		);

#### Sample Code that illustrates the problem
push.on('notification', function (data) {
			alert("My Notification!");
});

Never invoked.

**Comment by jcesarmobile** [comment]
When you set content-available to 1, that means it's a silent notification so it shouldn't be displayed.
But on notification should receive the data.

You say that it's not displayed, that's expected. 
Is your app in foreground, background or closed? if it's in background or closed I don't think an alert is the best way of testing it.

**Comment by lmark83** [comment]
Thank you for your reply; I'll remove the content-avaiable option from the JSON and push the notification with the application in foreground. Could you suggest me how to test the case of application not in foreground?

Thank you very much for your support.

PS: I'm developing my app using VS2015.

**Comment by lmark83** [comment]
IHi jcesarmobile,

I' ve tried to use different versions of the plugin kn order to het notifications working on iOS 10. The last one is the 1.8.2....but nothing gets displayed on my iPhone.
Do I have to change/configure somenthing in particular? In many forums I've read about something like an entilement file...but I don't  know where to begin from and if it is possible to modify it through the config.xml file.

As I wrote in the previous comment I am developing my app using VS2015 and PhoneGap Build for building.

It would be very kind of you to help me to resolve this issue.

Regards
Marco

**Comment by macdonst** [comment]
@lmark83 if you are using 1.8.x you may need to open the app in Xcode and turn on the entitlements. Since you are using VS I suggest you upgrade to 1.10.x as it should setup things correctly for you.

**Comment by lmark83** [comment]
Thx macdonst. With version 1.10 and new keys generated it works now.
