### ISSUE TITLE
custom icon can not show on background mode

### ISSUE THREAD

**Issue by yelban** [phonegap/phonegap-plugin-push#1876]
### Expected Behaviour
show custom notification icon correctly

### Actual Behaviour
notification icon does not show up on every devices' status bar and neither in the notification list 
**when app on background** (custom icon work fine when app on foreground)

#### Steps to Reproduce 
config.xml
`<resource-file src="icon.png" target="res/drawable/icon.png" />`

put icon.png into project root directory,

www/js/index.js

````
var push = PushNotification.init({
        android: {
            sound: true,
            vibrate: true,
            forceShow: true,
            icon: 'icon',
            iconColor: 'grey'
        },
        ios: {
            alert: true,
            badge: true,
            sound: true
        },
        windows: {}
    });
````

put app to background

send push from firebase console

got only white square icon

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Sony Z3 , Android Emulator

#### Cordova CLI version and cordova platform version

    cordova --version                                    # 7.0.1
    cordova platform version android                     # 6.2.3

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # 2.0.0-rc5 "PushPlugin"

#### Sample Push Data Payload

send notifications from https://console.firebase.google.com/

**Comment by macdonst** [comment]
@yelban sounds like your icon has no transparent pixels in it, which would account for the white square. https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images

**Comment by yelban** [comment]
@macdonst my icon do transparent pixels, the icon display normally when app on foreground mode, the white square only happens app on background mode

icon work fine when app on foreground mode
![screenshot_20170730-100212](https://user-images.githubusercontent.com/981381/28750023-7184e944-750f-11e7-81f1-3603aa61c255.png)

icon become white square when app on background
![screenshot_20170730-100236](https://user-images.githubusercontent.com/981381/28750030-b85e3654-750f-11e7-8b1e-6f35198724ee.png)

the icon do transparent pixels
![image](https://user-images.githubusercontent.com/981381/28750037-e83b29cc-750f-11e7-8fbb-c13086e84245.png)

**Comment by macdonst** [comment]
@yelban okay, in that case I think you are running into this https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

When you send via the Firebase console I believe it put everything in notification, not data.

**Comment by yelban** [comment]
@macdonst Thank you for giving me good advice.
Switch to use Firebase Admin SDK to send payload a as "[PAYLOAD.md#notification-vs-data-payloads](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads)" mentions, icon problem resolved !

Thanks,
Yelban.
