### ISSUE TITLE
ReferenceError: PushNotification is not defined

### ISSUE THREAD

**Issue by edoreld** [phonegap/phonegap-plugin-push#1881]
### Expected Behaviour

PushNotification can be called from the app.

### Actual Behaviour

When trying to use PushNotification, it says it's not defined.

### Reproduce Scenario (including but not limited to)

Install plugin with:
```phonegap plugin add phonegap-plugin-push@2.0.0-rc5 --variable SENDER_ID="***" --save```

Zip the project folder and upload it to PHB. Download the APK file generated by PGB. Install APK on device with ```adb install -r -d <path-to-APK>```. Run application. Try to call PushNotification 

#### Steps to Reproduce 
Debug the app with the Weinre console and try to call PushNotification (or window.PushNotification)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android Version
5.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Wiko

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.5.2
    cordova platform version android                     6.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.0.0-rc5

#### Sample Code that illustrates the problem
```
document.addEventListener('deviceready', function () {
 console.log('EL:loaded_last.js');  
 push = PushNotification.init({
   'android': {
     'senderID': '***'
   },
   'ios': {
     'sound': true,
     'vibration': true,
     'badge': true
   },
   'windows': {}
 });

 push.on('registration', function(data) {
   console.log('registration event: ' + data.registrationId);
   // document.getElementById('regId').innerHTML = data.registrationId;
   var oldRegId = localStorage.getItem('registrationId');
   if (oldRegId !== data.registrationId) {
         // Save new registration ID
         localStorage.setItem('registrationId', data.registrationId);
         // Post registrationId to your app server as the value has changed
         // TODO: save registration ID in table in database

       }
     });

 push.on('notification', function(data) {
  console.log(data.message);
  console.log(data.title);
  console.log(data.count);
  console.log(data.sound);
  console.log(data.image);
  console.log(data.additionalData);
});
 push.on('error', function(e) {
   console.log('push error = ' + e.message);
 });

});  
```

**Comment by macdonst** [comment]
@edoreld sorry the 2.x stream is not supported on PGB right now. The version of cordova-android needed by the plugin is not installable on PGB right now but they are working on it.
