### ISSUE TITLE
Failed to install 'phonegap-plugin-push':undefined undefined

### ISSUE THREAD

**Issue by edoreld** [phonegap/phonegap-plugin-push#1882]
### Expected Behaviour

iOS builds on PGB with phonegap-plugin-push version 2.0.0-rc5 installed and using [the latest cli: 7.0.1](https://medium.com/@wildabeast/phonegap-7-0-1-now-on-build-and-it-includes-some-important-changes-89087fe465f5)

### Actual Behaviour
Builds fails with the following log.
https://pastebin.com/raw/fSHXJXFY

### Reproduce Scenario (including but not limited to)
Set the cli to the newest 7.0.1 in config.xml:
```<preference name='phonegap-version' value='cli-7.0.1' />```
Install phonegap-plugin-push with the following line in config.xml:
```
<plugin name="phonegap-plugin-push" spec="~2.0.0-rc5">
        <variable name="SENDER_ID" value="***" />
</plugin> 
```

#### Steps to Reproduce 
Zip the project folder and upload it to PGB.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
N/A
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
N/A
#### Cordova CLI version and cordova platform version
cli-7.0.1 (4.4.0 / 6.2.3 / 5.0.0)

#### Plugin version
2.0.0-rc5

#### Logs taken while reproducing problem
https://pastebin.com/raw/fSHXJXFY

**Comment by macdonst** [comment]
@edoreld you don't provide the SENDER_ID when using 2.x or greater. You need to include your Google Services file. https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements

Also, the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

Please include an app id of an app that can replicate this issue.

**Comment by miguelcs6** [comment]
To install push you must first install cocoapods. Follow these steps on your terminal in the Ionic project directory.

First remove what you tried to install

ionic plugin remove phonegap-plugin-push
Next install cocoapods

sudo gem install cocoapods
Then you need to sync the cocoapods repo

pod setup
This may take a while
Finally install push

ionic plugin add phonegap-plugin-push --variable SENDER_ID="XXXXXXX"
