### ISSUE TITLE
JSON Exception TIMEOUT - older version of Google Play Services

### ISSUE THREAD

**Issue by phuongwd** [phonegap/phonegap-plugin-push#1886]
Hi guys,

Regarding the issue TIMEOUT, this issue happened on HTC One, Android 4.4.
I saw this note [Got JSON Exception TIMEOUT](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#got-json-exception-timeout)

> If you run this plugin on older versions of Android and you get an error:
> 
> `E/PushPlugin(20077): execute: Got JSON Exception TIMEOUT`
> It means you are running an older version of Google Play Services. You will need to open the Google Play Store app and update your version of Google Play Services.

#### Cordova CLI version and cordova platform version

    cordova --version: 7.0.1
    cordova platform version android: 6.2.3

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push 1.10.5

**Comment by macdonst** [comment]
@phuongwd correct, you if you have an outdated version of Google Play on your device you will have issues receiving push notifications. This is an issue with the device receiving any push notifications not just this plugin.

**Comment by phuongwd** [comment]
@macdonst thank you
