### ISSUE TITLE
Push notification action button callback not getting called in Ionic 2 push

### ISSUE THREAD

**Issue by sundaramoorthyjeeva** [phonegap/phonegap-plugin-push#1887]
### Expected Behaviour
I am the beginner in ionic app development. I am exploring the ionic 2 plugin. Now I took push plugin, My app can receive the notification from FCM and I can get the data from notification. After that I added action button in push notification. I need to call a method from notification action button. 
### Actual Behaviour
Here I placed the my push notification payload and callback name. I dont know where I have to create those callback methods. I assumed I have to place those methods in my root page. Please guide me.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Moto

#### Sample Push Data Payload

```
"data": {
    	"title": "AUX Scrum",
    	"message": "Scrum: Daily touchbase @ 10am Please be on time so we can cover everything on the agenda.",
        "actions": [
    		{ "icon": "approve_icon", "title": "APPROVE", "callback": "MyApp.approve", "foreground": true},
    		{ "icon": "reject_icon", "title": "REJECT", "callback": "MyApp.reject", "foreground": true}
    	]
    }
```

#### Sample Code that illustrates the problem

```
    export class MyApp{
        constructor(){

        }
        approve(){
            alert('approve called');
        }
        reject(){
            alert('reject called');
        }
    }
```

**Comment by macdonst** [comment]
@sundaramoorthyjeeva yeah, the methods `MyApp.approve` and `MyApp.reject` should be addressable from the window object. If you run `adb logcat | grep Push` while reproducing the problem the logs really help.

**Comment by sundaramoorthyjeeva** [comment]
@macdonst Then how to create window object in Ionic 2 by using typescript. Can you give some code snippet of creating action button callbacks in Ionic 2.

**Comment by macdonst** [comment]
@sundaramoorthyjeeva you don't need to create the `window` object, it's part of the browser. I don't often code Ionic based apps so you would be better off asking on the Ionic forums. 

That being said as long as the callback method is addressable you should be good to go.

**Comment by sundaramoorthyjeeva** [comment]
Here I placed the ionic forum conversation which is related to this issue. But solution not arrived yet.
https://forum.ionicframework.com/t/push-notification-action-button-callback-not-getting-called-in-ionic-push/101421/8

**Comment by sundaramoorthyjeeva** [comment]
I reached the solution. Notification action button callback should be like this within your launcher class. (i.e) You have to place the callback within app.component.ts.

    (<any>Window).approve = function (data: any) {
      alert('Approve called); 
    };

    (<any>Window).reject = function (data: any) {
      alert('Reject called);   
    }

**Comment by mpadmaraj** [comment]
action button callback works as expected when the app is running in background. when it is not running my method is not called at all. Is there something additional configuration I need to do to make this work?
