### ISSUE TITLE
IOS FCM push is not received Error! NotRegistered

### ISSUE THREAD

**Issue by sadiaMallickDev** [phonegap/phonegap-plugin-push#1888]
{"multicast_id":5231242532092484133,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"NotRegistered"}]}

**PAYLOAD**
`{"registration_ids":["XXXXXXXXXXX:APA91bEd1hzQXyV0jzM9j7gJzGn7B3MyU14_63ILQ7UBttYhqt6wmzQWPEM0JHrBKfMIbQpQX5XpDl_-XFJ6_k62zatqL9fQ1aVjzyQOMxFZSPay3m2UAhvD_dQLc3A2-XXXXXXXXXXX"],"notification":{"body":"asdasdasd","title":"asdasdd"},"id":"123","data":null,"priority":null,"aps":{"alert":"asdasd","data":null,"moredata":null}}`

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
