### ISSUE TITLE
Has someone managed it to use Google's FCM?

### ISSUE THREAD

**Issue by q00d0** [phonegap/phonegap-plugin-push#1889]
I try since 2 days to send a simple notification to my android phone.
It seems like the documentation is not complete because I can't manage it to get this thing working.

Sending notification via CLI is working fine, but not via FCM.

When I download the example push-plugin it uses version 1.8.4 not 2.0.0.
So I've added it manually as written in the docs, but its still not working.

Has someone a working project with Google'S FCM? If yes: can you provide it please?

**Comment by macdonst** [comment]
@q00d0 I'm sorry that it is not working for you as obviously I've been able to get it to work with FCM. I'd love to be able to help you more and improve the documentation but…

Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
