### ISSUE TITLE
Diference between local notification and push

### ISSUE THREAD

**Issue by wakeupmh** [phonegap/phonegap-plugin-push#189]
what is the diference with cordova-plugin-local-notifications and phonegap-plugin-push?

**Comment by bau720123** [comment]
well @wakeupmh 
please see the readme first

local [Examples of Notification Usage]
https://www.npmjs.com/package/cordova-plugin-local-notifications

push [Register and receive push notifications]
https://github.com/phonegap/phonegap-plugin-push/blob/master/README.md
GCM or APNS ...etc

**Comment by McGern** [comment]
Wow, that was pretty unhelpful.

I am assuming that the end product for both plugins display the small notification on the phone status screen with a title and short message.

If I have a the push plugin installed but want to do notification from within the app, so I need to install the local notification plugins as well?

Or is there some lower level function that phonegap has that will display messages on the screen?

**Comment by fredgalvao** [comment]
`phonegap-push-plugin` allows notifications to be created and shown **by push events sent from a remote server or service**.

`cordova-plugin-local-notifications` allows notifications to be created and shown **by any code on your application, whenever you want**.

**Comment by McGern** [comment]
Thanks for the reply.

Regarding where you say the plugins "allow notifications" do both plugins
implement their own notification layer that do the same thing  i.e. is the
step to make the message actually show on the phone the same?

**Comment by fredgalvao** [comment]
Yes, it is the same common api used to **create and show notifications**: [NotificationBuilder](http://developer.android.com/reference/android/app/Notification.Builder.html).

It would be cool if both plugins would merge for some users, but the way to go IMO is to have plugins that do one thing, and do it well done. If a day comes where both plugins are walking and evolving towards each other, I would agree that the merge is a valid option.

**Comment by McGern** [comment]
Thank you very much for you time and patience Frederico. I am discovering
more each day about how little I know.
