### ISSUE TITLE
Notification & data payload mixed on Android do not work in background 

### ISSUE THREAD

**Issue by ruben82** [phonegap/phonegap-plugin-push#1890]
Hi,
I'm trying to make push notification work on my ionic 3 application. I user firebase to do it and when I send a push notification I create a mixed payload (notification and data payload together) and my expectation is that **on('notification')** is called for iOS and Android both background and foreground app state. But on Android in background doesn't work (**on('notification')** is not called).

There's a [stackoverflow link](https://stackoverflow.com/questions/45440697/ionic-3-send-push-notification-with-firebase-data-vs-notification-payload) for more info

This is my ionic info

> 
    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.2
    Node              : v8.1.3
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy        : 1.9.1 
    ios-sim           : 6.0.0 
    npm               : 5.1.0 

cordova plugin version | grep phonegap-plugin-push  is **phonegap-plugin-push 1.10.5 "PushPlugin"**

Payload sent is

`code 

        $p = array(
         'id'             => $post['id'],
        'title'             => $post['title'],
        'description'       => $post['description'],
        'text'              => $post['text'],
        'image_url'         => $post['image_url']
    );

    $msg = array(
        'title'     => "test",
        'body'      => $post['title'],
        'post'      => $p,
        'vibrate'   => 1,
        'sound'     => "default"
    );

    $fields = array();
    $fields['to']           =  "/topics/news";
    $fields['data']         = $msg;
    $fields["notification"] =  array('title' => 'test', 'body' => $post['title'],  'sound' => 1);`

I read all your documentation about notification and data payload but I think there's a lack.

You wrote for Android:

> My recommended format for your push payload when using this plugin (while it differs from Google's docs) works 100% of the time:

{
    "data" : {
        "title": "Test Notification",
        "body": "This offer expires at 11:30 or whatever",
        "notId": 10,
        "surveyID": "ewtawgreg-gragrag-rgarhthgbad"
    }
}

Ok you're right!! We have to send a data payload to make it work in all app state on Android....but it's not work on iOS.

For iOS you wrote:

> but in order for the same notification event you would need to send your push to GCM iOS in a slight different format:

{
    "registration_ids": ["my device id"],
    "notification": {
        "title": "My Title",
    	"body": "My message"
    }
    "data": {
    	"key1": "data 1",
    	"key2": "data 2"
    }
}

Ok.... this work on iOS but on Android in background state nope... In fact, on('notification') on Android is not called.

So my question is:

What can I do to make work on iOS and Android in background and foreground state??
How could I shape my global payload?

FYI: the payload I wrote above, is used to send notification for native app... and it works on every device and in every app state.

Thanks you for reply

**Comment by fredgalvao** [comment]
Unfortunately there's no current way to send one global uniform payload that works on all covered scenarios on both iOS and Android. You will need to handle/send them separately:
- a `notification` payload to iOS
- a `data` payload to Android

I'm pretty sure everyone would love to be able to pick one and have it work everywhere, but the way GCM/FCM delivers the event to the code on the plugin makes it **apparently impossible** to achieve right now.

**Comment by ruben82** [comment]
Thanks fredgalvao to reply to me.
I thought [a trick that work](https://stackoverflow.com/a/45549941/2192974) using firebase topic condition. Maybe can help
