### ISSUE TITLE
on('notification') not called in background on android

### ISSUE THREAD

**Issue by svnkin** [phonegap/phonegap-plugin-push#1892]
# Expected Behaviour

Call the on('notification') handler on android while the app is closed (not running in background). In the JavaScript callback function set the badge counter on the icon.

# Actual Behaviour

Plugin will receive the push-message, content-available is set to "1" (see logs) but the on('notification') handler is not called. In the logs you can see that the data will be cached for later execution. The callback function will be executed with the data after the app is started.
If the app is running in the background (not closed) the handler works as intended

## Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 6.0.1

## (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Samsung Galaxy S6

## Cordova CLI version and cordova platform version

cordova --version   6.5.0                            
cordova platform version android  6.2.3    
## Plugin version

cordova plugin version | grep phonegap-plugin-push   1.9.4
## Sample Code that illustrates the problem
```
.run(function($ionicPlatform) {
      $ionicPlatform.ready(function() {
      var count = 0;
      function onDeviceReady(){
        var push = PushNotification.init({
            android: {
               senderID: "**************",
               vibrate: false
            },
            ios: {
               alert: true,
               badge: false,
               sound: "false"
            }   
         });
        push.on('notification', function(data) {
            count++;
            push.setApplicationIconBadgeNumber(function () {
                       console.log('success');
                   }, function () {
                       console.log('error');
                   }, count);
         });
}
```
## Logs
I replaced the package name with *** . **** . **** and added some more logs to the java code.
The last event is from the sendEvent methode:

```
PluginResult pluginResult = new PluginResult(PluginResult.Status.OK, _json);
pluginResult.setKeepCallback(true);
if (pushContext != null) {
    Log.d(LOG_TAG,"Send Eventto App");
    pushContext.sendPluginResult(pluginResult);
} else {
    Log.d(LOG_TAG,"Send no Event to Background cause pushContext is null");
}
```

[log.txt](https://github.com/phonegap/phonegap-plugin-push/files/1208142/log.txt)

**Comment by fredgalvao** [comment]
Did you force kill it through the "alt-tab" or through the application center? If so, it's the currently expected default behaviour, as the plugin then doesn't have a webview available to send an event to, and it can't wake it up completely by default.

If you're on cordova-android > 6.x.y, you can achieve it by ([source](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#application-force-closed)):
- making sure you have the necessary code on your main actitivy class
- sending `force-start: 1` on the payload

That will make the plugin try to wake up the webview created by your application and then send the event to it as per the usual flow of events.

Also, you didn't provide the `Sample Push Data Payload` section of the issue template, which would make your issue very hard to debug/reproduce/help, so please don't ignore it next time ;)

**Comment by macdonst** [comment]
@svnkin the explanation by @fredgalvao is on point. If you app is not running in the background there is no webview loaded in memory in order to call the `setApplicationIconBadgeNumber` method. You can try the `force-start: 1` parameter in your payload like @fredgalvao but for no I'm closing this as it is expected behaviour.
