### ISSUE TITLE
Phonegap Build with Firebase

### ISSUE THREAD

**Issue by Marix1** [phonegap/phonegap-plugin-push#1897]
Hello,

i try to use that plugin with Phonegap Build

First i test the "Push Notifications" Template on Phonegap app.

I create a new Firebase Project and added the id in "config.xml" and "index.js"
And added in config:      preference name="android-build-tool" value="gradle" 

After running i get a "Device Push ID"

But sending Messages with firebase console don't work

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
