### ISSUE TITLE
Bug - Can't receive the notification on iOS when being on phonegap-plugin-push 2.0.0

### ISSUE THREAD

**Issue by HamzaLJ** [phonegap/phonegap-plugin-push#1898]
### Expected Behaviour

Receive push notifications on both iOS and Android

### Actual Behaviour

I receive notifications only on Android devices.

After further investigation, I found that the latest version of the plugin generates a deviceToken in the following format : 

`fGjNq8z_tpo:APA91bG86M-RGcWQ48Dg2Ci8AxRKOI7p3wrwK2oyvrPhmMKhxysCiJaGuwXd2c32n2AKOh2zHDbZ_4Yq6STbp4F81F_s0VSxAitJCSO7LUQGMv3iZa7SkaghTN5q9-hDdmeuyCJWSqiX`

(_I believe it's an FCM_ formatting). 

I downgraded to 1.x and the generated token looks like the following:

`2681d24d9d8f566e6bfb5e30b907c4ed37763ce8e1ef16d770daf87d2a9bec6a`

After downgrading, I received the notification in iOS; however, in Android I didn't receive any (by the way, the app crashed too).

So, the conclusion : 

With the version 1.x of the plugin, I can receive notifications on iOS.
With the version 2.x of the plugin, I can receive notifications on Android.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 5.0+, iOS 9.0+

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Samsung Galaxy S6
iPhone 6

#### Cordova CLI version and cordova platform version

    cordova --version : 7.0.1
    cordova platform version : 
                 android 6.2.3
                 ios 4.4.0

#### Plugin version

          Tried with 1.x and 2.x

**Comment by macdonst** [comment]
@HamzaLJ the plugin should only generate a FCM style registration ID if you include the Google-Services.pList file in your config.xml. If you want to use the plugin with APNS then just omit the Google-Services.pList file from your config.xml.

**Comment by HamzaLJ** [comment]
I've tried to delete the reference of Google-Services.pList in config.xml so I can use APNS; however, I am still getting the FCM style registration ID. What should I do ?

**Comment by macdonst** [comment]
@HamzaLJ I'd remove and add the ios platform back into your project to ensure the Google-Services.pList is removed completely. I know that cordova-ios had a bug where it wasn't cleaning up the reference to resource-files.

**Comment by HamzaLJ** [comment]
It worked! Thanks !!
