### ISSUE TITLE
Phonegap Build (desktop app) with Firebase (even i pay money for help)

### ISSUE THREAD

**Issue by Marix1** [phonegap/phonegap-plugin-push#1899]
i try to implement the plugin and created a new firebase project to my app name.
Now i'm testing first via Phonegap desktop app and the "Push Notifications" template.

Added to config.xml:
```
    preference name="android-build-tool" value="gradle" 
    plugin name="phonegap-plugin-push" source="npm" 
        param name="SENDER_ID" value="1063994300861"
   /plugin
```
index.js:
```
       var push = PushNotification.init({
            "android": { "senderID": "1063994300861"  },
            "browser": {},
            "ios": {"sound": true,"vibration": true, "badge": true },
            "windows": {}
        });
```

Then i try to send push messages via the firebase console, but nothing happens

Building via Phonegap Build i take:   spec="~1.9.0"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
### Expected Behaviour
receive push massages

### Actual Behaviour
don't receive push messages

### Reproduce Scenario (including but not limited to)

#### Steps to Reproduce 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4, 5.x, 6.x, 7.x

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Nexus 6P, Note 1,2,3,4,5, Tab S3

#### Cordova CLI version and cordova platform version
PhoneGap (iOS / Android ) cli-6.5.0 (4.3.1 / 6.1.2 ) 

#### Plugin version
phonegap-plugin-push | npm | 2.0.0 |  

#### Sample Push Data Payload

#### Sample Code that illustrates the problem

#### Logs taken while reproducing problem
 Received Device Ready Event
 calling setup push
 calling push init
 after init
Device Push ID: 
dna4Z8AO6E8:APA91bGyssPHBhjATRDYWorrMhMVu9kJ4Ncfa-Gnnn8Y7CP2NtAs806xvwyWzUyN6hmMUhWr0UjpFZKIMoTSyk9Q47AaWgNEKFayMBZVb8dL2baXy_0Yl5mxaezfPKHh46ChqIlJXXGp
registration event: 
dna4Z8AO6E8:APA91bGyssPHBhjATRDYWorrMhMVu9kJ4Ncfa-Gnnn8Y7CP2NtAs806xvwyWzUyN6hmMUhWr0UjpFZKIMoTSyk9Q47AaWgNEKFayMBZVb8dL2baXy_0Yl5mxaezfPKHh46ChqIlJXXGp

**Comment by macdonst** [comment]
@Marix1 are you using the desktop app to serve your project? Are you testing the app in the PhoneGap Developer App?

**Comment by Marix1** [comment]
Yes, i use the desktop developer app with the push template and change the config.xml and the index.js.

At Firebase i create a new project and connect that to my android app 
i try spec 2.0.0 and 1.9.0 and i also make builds - build only spec 1.9.0 work. 
(that stand in the doc too that PG Build support only 1.9.0)

But sending messages over the firebase console don't work.
Not via the developer app and not with build. I debug the build app and the console shows nothing when i fired a notification.

Im wondering that i dont need the .plist file..

**Comment by macdonst** [comment]
@Marix1 correct, you are not supposed to use the Firebase console when testing in the PG Developer App. We can't sign the binary properly on iOS to be able to receive push notifications from anyone. Instead we created a push service that you can use from the command line to test your code inside the PG Dev App.

Check out this tutorial: http://docs.phonegap.com/tutorials/develop/push-notifications/

When you are ready to build your own app then you can use your own FCM project to send push notifications.
