### ISSUE TITLE
Badge on android 

### ISSUE THREAD

**Issue by awebdeveloper** [phonegap/phonegap-plugin-push#190]
Can we add badge support in android 

http://vardhan-justlikethat.blogspot.in/2014/07/android-ios-style-badge-app-icon-for.html

**Comment by macdonst** [comment]
@awebdeveloper well it is possible but I don't have all the necessary devices on hand to test this so I'll have to leave it up to users to see if they really want this feature and collaborators to help implement it.

**Comment by awebdeveloper** [comment]
Why not merge this 

https://github.com/phonegap-build/PushPlugin/pull/414

Or 
You could add for whichever phone u have the community can add for rest

**Comment by macdonst** [comment]
@awebdeveloper if there is enough interest in this feature and people who want to help implement and test I can merge it but it's a lower priority for me. Luckily this is open source plugin so anyone can contribute.

**Comment by harmendejong** [comment]
I have definately interest for this feature! Would be great!

**Comment by CoachRDeveloper** [comment]
That would be awesome. Maybe it can be merged with https://github.com/katzer/cordova-plugin-badge .

**Comment by jimior2** [comment]
I'm hope this, too.

**Comment by CoachRDeveloper** [comment]
I would like to add that it is not out of convenience that I'd want the two plugins to be merged. When the app is in the background and a push message is received, only the JAVA part of the app can take actions (as it does now by showing a notification). The JavaScript part will only be run when the notification is opened and the app becomes active.

**Comment by macdonst** [comment]
@CoachRDeveloper right now on Android you can execute the `on('notification')` handler if your message does not have a message/title. When I implement #293 you'll be able to force the execution of background code even when showing a notification in the shade.

That way you'd be able to call cordova-plugin-badge even when your app is in the background.

**Comment by jterps08** [comment]
+1 for support for badge notifications in Android

**Comment by robinbonnes** [comment]
+1 For this. I wonder why there is still no global API available for this in the Android SDK.

**Comment by vohtaski** [comment]
+1

**Comment by lnaghash** [comment]
+1

**Comment by robinbonnes** [comment]
In the meanwhile I fixed this for non iOS devices by using this plugin: https://github.com/katzer/cordova-plugin-badge

`                push.on('notification', function(data)
                {
                    // Increase badge if not in foreground
                    if(!data.additionalData.foreground)
                    {
                        if(platform == "ios")
                        {
                            push.getApplicationIconBadgeNumber(
                                function(n)
                                {
                                    push.setApplicationIconBadgeNumber(
                                        function() {},
                                        function() {},
                                        (n + 1)
                                    );
                                },
                                function() {}
                            );
                        }
                        else
                        {
                            cordova.plugins.notification.badge.increase();
                        }
                    }

...`

**Comment by parismav87** [comment]
@robinbonnes How did you manage to get this to work while the app is not in the foreground? I copied your code for android, and it doesn't seem to increase the badge number for me. Could you give some more info, like your push.init() function etc?

**Comment by macdonst** [comment]
Badge support for Android will be in release 1.7.0 of this plugin.

**Comment by parismav87** [comment]
@macdonst Thanks! is there an ETA for this?
Great work.

**Comment by macdonst** [comment]
@parismav87 I'm hesitant to give a solid date at this point but before the end of April seems safe. I need to co-ordinate with some other devs on their time.

**Comment by kashyapmukkamala** [comment]
Is this already available on IOS? Cause i cant seem to get this to work

```if(!data.additionalData.foreground) {
                    $cordovaPushV5.getBadgeNumber().then(function(badgeCount) {
                        $cordovaPushV5.setBadgeNumber(badgeCount + 1);
                    });
                } ```

I have tried other flavours of this using `$cordovaBadge` as well, but no use

**Comment by macdonst** [comment]
@kashyapmukkamala not sure if Ionic changes anything but the methods in the plugin should be `setApplicationIconBadgeNumber` and 'getApplicationIconBadgeNumber`.

**Comment by kashyapmukkamala** [comment]
This is what it ends up calling internally, I cant seem to get the badge numbers to update when the app is in background or closed.

**Comment by Suhrahj** [comment]
I managed to make on('notification') work for android with cordova-plugin-badge if the application is on the **background** but if it's closed, on('notification') doesn't work with the badge plugin, because I think as it says on their "wiki" page: [The plugin and its methods are not available before the deviceready event has been fired.](https://github.com/katzer/cordova-plugin-badge/wiki/07.-Samples)

Does anyone have a workaround for this?

**Comment by slorber** [comment]
@macdonst by chance do you know if this will work on Android 6.0? 

It seems this plugin [cordova-plugin-badge](https://github.com/katzer/cordova-plugin-badge/issues) has some recent issues related to Android 6.0 so I'm just wondering

**Comment by mlabarca** [comment]
@siober I have tested it on 6.0 and it does work, but only with phones with a launcher supported by [shortcutbadger](https://github.com/leolin310148/ShortcutBadger) until version 1.1.4 . For example I tried this with a Moto X play with 6.0 with the stock launcher and it didn't work, but it did work once i changed the it to Nova launcher+ teslaunread.

**Comment by slorber** [comment]
@mlabarca sorry i'm not an expert on the subject.

Does it mean it will work most of the time, except on some devices like Motorola which would require user action to make it work?

**Comment by mlabarca** [comment]
@slorber no worries, I'm not an expert either by far; in fact, someone else like @macdonst correct me if I'm wrong:
From what I gather with the tests I've done in various devices, since the badges don't seem to have a lot of native support, It really depends on the launcher in the device. Manufacturers such as LG tend to modify the launcher and add their own features, and shortcutbadger targets many those launchers. So, if most of your users have an LG, samsung or sony phone and they don't change their launcher, the badge should display. But if your users are a horde of Motorola users, then they would need to install another launcher for badges to display. 
Check the supported launchers from shortcutbadger [here](https://github.com/leolin310148/ShortcutBadger#support-launchers) Note that huawei launcher was recently added this week but it probably won't work with phonegap-plugin-push since we are using an older version of the library.

**Comment by slorber** [comment]
hmmm ok thanks. So it does work on most vendors if you don't customize the launcher, and it will also work in Huawei sooner or later as far as I understand.

What about Android stock? I think Google does provide raw uncustomized Android for Nexus 5X and 6P

Anyway, if this badge works most of the time by default on recent phones it should be fine for me. What kind of support % can we expect on recent (last 2 years) devices . Any idea?

**Comment by macdonst** [comment]
@slorber the badge won't work on stock Android. Google does not support it. Basically we support what ShortcutBadger supports as per @mlabarca comment.

**Comment by slorber** [comment]
thanks for these infos :)

**Comment by Krishna25Vrinsoft** [comment]
So we can't display badge number in Android ?

**Comment by jcesarmobile** [comment]
You can only show the badge on some devices that support it, like the devices from sony, samsung, htc, lg, and some other brands, it's not supported on stock android

**Comment by Krishna25Vrinsoft** [comment]
Okay. Thanks a lot. I was running in Motorola device. In Android it is working. Thanks a lot.

**Comment by ravisuryawanshi** [comment]
Hi,

I am getting badge count on the notification bar. I am not sure why it is coming. Can anyone help me?

Thanks
Ravi
![android-badgecount on notifications](https://cloud.githubusercontent.com/assets/12716503/22742687/99edd142-ee3d-11e6-9fe3-b3878786538a.JPG)

**Comment by slorber** [comment]
Couldn't it be related to using a collapseKey on android push notification?

**Comment by ravisuryawanshi** [comment]
Hi Slorber

No,I am not using collapsekey.
