### ISSUE TITLE
Can't have custom notification sound in iOS

### ISSUE THREAD

**Issue by HamzaLJ** [phonegap/phonegap-plugin-push#1900]
### Expected Behaviour

Custom notification sound

### Actual Behaviour

No custom notification sound in iOS

### Reproduce Scenario (including but not limited to)

Follow the same steps in the documentation

#### Steps to Reproduce 

Select a .caf or .aiff file (should be under 30s) and put it in the root folder of your iOS project.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 9.0+

#### Cordova CLI version and cordova platform version

    cordova --version : 7.0.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   : 
    phonegap-plugin-push 2.0.0 "PushPlugin"

#### Sample Push Data Payload

Using **APNS**

        {
		"alert": "Test sound",
		"sound": "ring.caf"
	}

**Comment by macdonst** [comment]
@HamzaLJ do you successfully get your file into the xcode project? Did you ensure that your sound file is of the correct format? See: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#sound-1

**Comment by HamzaLJ** [comment]
@macdonst yes the `.caf` file is placed on the root project of my iOS project `(i.e platforms/ios/ring.caf)` and its in the correct format as per the documentation.
What should I do?

**Comment by macdonst** [comment]
@HamzaLJ if you load the project in XCode do you see `ring.caf` in the project? How did you copy the file to the project to ensure XCode links to it?

**Comment by malwatte** [comment]
@HamzaLJ ,
Try copying the sound file to Resources directory.

**Comment by HamzaLJ** [comment]
@malwatte you mean resources/ios ?

**Comment by malwatte** [comment]
Nope. Platforms/ios/{app name}/resources

Or open the project in xcode. Then drag and drop the file to {project}/resources directory

**Comment by jcesarmobile** [comment]
Just putting the file inside folders is not enough, it has to be associated with the Xcode project.

You can do it as malwatte said on his last comment or put the sound in the root of your project and use a resource-file tag to copy it to the Xcode project. (as for the Google-Services.plist files, check the install docs about it). Be aware that you need Cordova CLI 7.x.x to make resource-file tag work.

**Comment by malwatte** [comment]
@HamzaLJ ,
What I am doing to copy resource files is having an empty plugin and in plugin.xml I have
<source-file src="src/ios/sound.caf" />

This is because I still use Cordova CLI 6.X
I think you can use config.xml to copy resource files if you use 7.X

**Comment by natesreich** [comment]
I am encountering the same issue with custom sounds.

I have tried the following paths:
- / (root)
- /platforms/ios/
- /platforms/ios/appPush/
- /www/
- /www/res/

For the payload, I tried the following:
`phonegap push --deviceID 716b88e2c36172036287d52f81f944de4304b148f63e8c29df88bf63d58d6e53 --service apns --payload "{ \"aps\": { \"alert\": \"Hello World\", \"sound\": \"blip\" } }"`
`phonegap push --deviceID 716b88e2c36172036287d52f81f944de4304b148f63e8c29df88bf63d58d6e53 --service apns --payload "{ \"aps\": { \"alert\": \"Hello World\", \"sound\": \"blip.caf\" } }"`
`phonegap push --deviceID 716b88e2c36172036287d52f81f944de4304b148f63e8c29df88bf63d58d6e53 --service apns --payload "{ \"aps\": { \"alert\": \"Hello World\", \"sound\": \"www\/blip\" } }"`
`phonegap push --deviceID 716b88e2c36172036287d52f81f944de4304b148f63e8c29df88bf63d58d6e53 --service apns --payload "{ \"aps\": { \"alert\": \"Hello World\", \"sound\": \"www\/blip.caf\" } }"`

I also tried adding the following to config.xml under <platform name="ios">:
`<resource-file src="blip.caf" target="www/res/blip.caf" />`

It only plays the default notification sound. What am I missing that I haven't already tested?

Unfortunately, I don't have a Mac so am unable to use Xcode.

I have attached my blip.zip sound file as well.

[blip.zip](https://github.com/phonegap/phonegap-plugin-push/files/1569109/blip.zip)

**Comment by jcesarmobile** [comment]
If you are using Phonegap Developer app to test it won't work. Phonegap Developer app is a compiled app, you can't add files to it after it's compiled.
Also, you should't put www as target, just put the file name on target or Resources/blip.caf
