### ISSUE TITLE
Notification not showing on iOS

### ISSUE THREAD

**Issue by maxdimaz** [phonegap/phonegap-plugin-push#1904]
### Expected Behaviour

Get Notification On Device (iOS)

### Actual Behaviour
I Get Registration ID
`2017-08-15 10:19:30.051 XXX[397:83928] GCM Registration Token: dewAPqVuntU:APA91bEm8zaRsuJ2EdKeFaU8BTp9zUmc78c_KxI1CzbvinYbR4SrX6B8zrD3kBZL7jT95qHSkCDsVE9xB8PeW4RQoZLTN6_SIwClktOih8V4DBgVgzvmHKNJ8bIZAjSW3CGn5tqB9-UC`

Tried to push but didnt get any notification on device 

try using this payload get error "InvalidApnsCredential"
`{
  "registration_ids": [
    "dewAPqVuntU:APA91bEm8zaRsuJ2EdKeFaU8BTp9zUmc78c_KxI1CzbvinYbR4SrX6B8zrD3kBZL7jT95qHSkCDsVE9xB8PeW4RQoZLTN6_SIwClktOih8V4DBgVgzvmHKNJ8bIZAjSW3CGn5tqB9-UC"
  ],
  "notification": {
    "body": "Body Notification",
    "title": "Title Notification"
  },
  "priority": "high",
  "aps": {
    "alert": {
      "title": "Title Alert",
      "body": "Body Alert"
    }
  },
  "badge": 1,
  "sound": "default"
}`

so im using this payload its success submit without error but didn't recieve any notification what the problem?
`{
  "registration_ids": [
    "dewAPqVuntU:APA91bEm8zaRsuJ2EdKeFaU8BTp9zUmc78c_KxI1CzbvinYbR4SrX6B8zrD3kBZL7jT95qHSkCDsVE9xB8PeW4RQoZLTN6_SIwClktOih8V4DBgVgzvmHKNJ8bIZAjSW3CGn5tqB9-UC"
  ],
  "priority": "high",
  "aps": {
    "alert": {
      "title": "Title Alert",
      "body": "Body Alert"
    }
  },
  "badge": 1,
  "sound": "default"
}`

#### Platform and Version 
iOS 8.3.1

#### Cordova CLI version and cordova platform version

    cordova --version                                    # 6.4.2
    cordova platform version ios                     # 4.3.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # 1.10.5 "PushPlugin"

**Comment by macdonst** [comment]
@maxdimaz what push service are you using to send to iOS? Does it use APNS or GCM/FCM? Can you put your init method as a comment?

**Comment by jcesarmobile** [comment]
@macdonst you removed iOS 8 support, right?

**Comment by macdonst** [comment]
@jcesarmobile not in 1.10.5. Regardless, I think the problem is Max is registering with GCM and trying to send via APNS.

**Comment by maxdimaz** [comment]
Oke here's my code for init method
`var push = PushNotification.init({
    "android": {
      "senderID": "xxx"
    },
    "ios": {
      "senderID": "xxxx",
      "gcmSandbox": true,
      "alert": "true",
      "badge": "true",
      "sound": "true"
    }
  });
  push.on("registration",
    function(data) {
      localstorage.setItem("firebaseid", data.registrationId)
      console.log(data.registrationId)
    },
    function(e) {
      console.log("error register firebase")
    }
  );`


Is posible using only GCM/FCM only without APNs on iOS?

**Comment by malwatte** [comment]
@maxdimaz ,
Yes. 
You must create an iOS app in your FCM project. Create APNS certificates in Apple developer console and upload .p12 certificate files to FCM.

**Comment by jcesarmobile** [comment]
@maxdimaz are you using FCM or GCM? 
If you are using 1.10.5, FCM is not supported for iOS, on Android it not officially supported neither but it works.

So, if you want to use FCM on iOS, you have to use the v2 version of the plugin, which doesn't support iOS 8 anymore.

**Comment by macdonst** [comment]
@maxdimaz yeah, your init method indicates you are attempting to use GCM. Did you upload the .p12 certificate to Google so you could send GCM messages to iOS devices?

**Comment by maxdimaz** [comment]
Ok i see the problem ill closed this. Thanks

**Comment by maxdimaz** [comment]
Hi im still get a notification alert but i got the data on background like this,
`
2017-08-24 13:58:16.973 xxx[873:536812] Notification received
2017-08-24 13:58:16.974 xxx[873:536812] Push Plugin key: alert
2017-08-24 13:58:16.974 xxx[873:536812] Push Plugin key: sound
2017-08-24 13:58:16.990 xxx[873:536812] {"additionalData":{"foreground":true,"coldstart":false,"gcm.message_id":"0:1503557895803488%f5156aa3f5156aa3"},"message":"my body","title":"my title","sound":"default"}

`
but there no popup or alert or notification on notification panel. 

i was trying some payload and never get UI notification just data on background

**Comment by malwatte** [comment]
This is the my request to FCM and it works fine in iOS devices (both foreground and background).
{ 
    "data": {
        "type": "some value....",
        "notId": 1
    },
     "notification" : {
          "body" : "Service",
          "title" : "New Service Request",
          "sound": "default"
        },
    "priority":"high",
    "registration_ids" : ["id........"]
}

**Comment by maxdimaz** [comment]
Im using APNs for notification maybe have other payload format?. 
 i was try your payload still didnt recieve notification but i got data on background

**Comment by maxdimaz** [comment]
It work right now the notification show up if the application is minimized on background. how to setup notification showup on opened aplication?

**Comment by malwatte** [comment]
it is easy.
Use notification event.
`push.on('notification', notificationEventHandler);`

in notificationEventHandler check data.additionalData.foreground value to determine if app is opened by tapping on a notification.

```
notificationEventHandler = function(data){
   if(data.additionalData.foreground)
      //push received while app is in foreground. Show a popup or something to the user.
   else 
      //push received while app is in background. App is open by clicking the notification
}
```

**Comment by harinarayan13** [comment]
I am using the latest cordova and the push plugin 2.1.3. I have configured FCM and notification from the console are received on the device. But the notification sent through the sandbox apns api are not received. Please suggest me.

**Comment by malwatte** [comment]
@harinarayan13 ,
What is the response when you call FCM end-point?

**Comment by vvicho** [comment]
Hi, 
I'm having this issue with version 2.1.3, when I send a notification to a device, the push.on('notification..) method is not getting fired. Just to be sure, I am not using FCM for iOS notifications, is this the reason? or does it support APNS as well?
Thanks
