### ISSUE TITLE
Need basic education - GCM/FCM and 2.0.0 plugin support

### ISSUE THREAD

**Issue by worzella** [phonegap/phonegap-plugin-push#1905]
I have been successfully using phonegap-plugin-push for GCM and now
am exploring the new(ish) FCM offering. I have a basic hole in my understanding
that I hope some kind soul will take the time to explain.

Currently, my source server drives the GCM interface/URL
and the notification messages arrive just fine at my 1.10.3 plugin-based mobile device app. 

But now, if I build a 2.0.0 plugin-based app, will it ONLY work with a source
server that is driving the new FCM interface/URL..... or will a source server
that is still driving the GCM interface/URL be able to have the Google push 
service send notifications to the 2.0.0 plugin-based device?

Make sense?

Maybe put another way... I understand the differences of the GCM/FCM connection
between the source server and the Google push service... but does this GCM/FCM 
difference ALSO pertain to the "push service - to - device" interface. 

Hope this is not too dumb a question.

Thanks and kudos to all the folks that work on the phonegap-plugin-push to keep it 
stable and up to date!

PS - Extra credit question... my discussion above uses Google push as an example, 
     but my app also supports APNS using the original binary interface... but I believe I 
     want to migrate to HTTP/2 new interface so same questions apply.

**Comment by macdonst** [comment]
@worzella your GCM server *should* be able to send to a device that registers with FCM and gets a FCM token but YMMV. 

If your iOS app is using APNS you can still use APNS with the version 2.0.0 plugin. Same as the 1.x stream you can decide if you want to use APNS or FCM.
