### ISSUE TITLE
Unable to build iOS...

### ISSUE THREAD

**Issue by nickrouty** [phonegap/phonegap-plugin-push#1906]
### Expected Behaviour
Install the plugin without errors.

### Actual Behaviour
```
$ cordova plugin add phonegap-plugin-push
Installing "phonegap-plugin-push" for android
Subproject Path: CordovaLib
Installing "phonegap-plugin-push" for ios
Failed to install 'phonegap-plugin-push': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/.../platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: pod: Command failed with exit code 1
```

If I try to re-install:
```
$ cordova plugin add phonegap-plugin-push
Plugin "phonegap-plugin-push" already installed on android.
Installing "phonegap-plugin-push" for ios
Error during processing of action! Attempting to revert...
Failed to install 'phonegap-plugin-push': CordovaError: Uh oh!
"/.../platforms/ios/Bagger Dave's/Plugins/phonegap-plugin-push/AppDelegate+notification.m" already exists!
```

Error when attempting to build after adding the plugin:

I also get an error when I uninstall it too:
```
$ cordova plugin remove phonegap-plugin-push
Uninstalling phonegap-plugin-push from android
Subproject Path: CordovaLib
Uninstalling phonegap-plugin-push from ios
Error: pod: Command failed with exit code 1
```
#### Steps to Reproduce 
```cordova plugin add phonegap-plugin-push```

#### Cordova CLI version and cordova platform version
    The latest of everything is installed, re-installed all plugins, removed platforms, re-added, etc.
    cordova --version                                    7.0.1
    cordova platform version android          android 6.2.3 / ios 4.4.0

#### Plugin version
    phonegap-plugin-push 2.0.0 "PushPlugin"

I've tried re-installing cocoapods, pods repo update, pod setup, pod install, etc.

Plot twist. I then installed cordova-plugin-firebase, and now it will build, however I am then getting errors once I am loading it on a device:

```
[Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
2017-08-15 12:00:01.592 App Name Here[8275] <Error> [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
2017-08-15 12:00:01.594595-0700 App Name Here[8275:3343224] [Firebase/Core][I-COR000009] The GOOGLE_APP_ID either in the plist file 'GoogleService-Info.plist' or the one set in the customized options is invalid. If you are using the plist file, use the iOS version of bundle identifier to download the file, and do not manually edit the GOOGLE_APP_ID. You may change your app's bundle identifier to '(null)'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.
2017-08-15 12:00:01.594671-0700 App Name Here[8275:3343174] *** Terminating app due to uncaught exception 'com.firebase.core', reason: 'Configuration fails. It may be caused by an invalid GOOGLE_APP_ID in GoogleService-Info.plist or set in the customized options.'
*** First throw call stack:
(0x18df56fe0 0x18c9b8538 0x18df56f28 0x10019fd50 0x10019f2ec 0x10019f014 0x1000c7c94 0x1940f9e48 0x19430637c 0x19430be24 0x1943208b0 0x1943090b8 0x18fb00884 0x18fb006f0 0x18fb00aa0 0x18df0542c 0x18df04d9c 0x18df029a8 0x18de32da4 0x1940f2fc8 0x1940edc9c 0x1000b3998 0x18ce4159c)
libc++abi.dylib: terminating with uncaught exception of type NSException

This has been fun, but if anyone has some guidance, I'd really appreciate it.

**Comment by macdonst** [comment]
@nickrouty if you do a `cordova platform rm ios` and then `cordova platform add ios` when the cocoapods installed and setup it should run fine. I just set up a new project yesterday.

**Comment by nickrouty** [comment]
@macdonst Does it sound right that I needed to install the cordova-plugin-firebase plugin as well or is that a coincidence that my build was able to at least finish after adding that plugin?

**Comment by Littlejord27** [comment]
I'm having the same issue. I had it working earlier today with deploying, building, and archiving into a full iOS app. Suddenly, I kept giving errors such as "Error: Error code 65 for command" and "The following build commands failed: CopyPlistFile."

I just removed the platform as @macdonst  suggested, and now I'm getting the error @nickrouty  is getting. So, originally, I was getting the CopyPListFile. Now that I removed my platform, whenever I try to add the plugin and platform back, I get "Error: pod: Command failed with exit code 1"

**Comment by macdonst** [comment]
@nickrouty no, you don't need the `cordova-plugin-firebase plugin` in order for this plugin to work.

**Comment by sfaizanh** [comment]
@macdonst if we remove `cordova-plugin-firebase` the how do we use for `Analytics` or other `things on Firebase`

**Comment by KimberleeDArmstrong** [comment]
I am having the same issue.  Was there ever a solution?

**Comment by sfaizanh** [comment]
Still same

**Comment by KimberleeDArmstrong** [comment]
I removed ios platform removed the plugin directory and all references to the plugin in config.xml, package.json, and fetch.json.  Then readded the platform, ran pod setup, then ran pod repo update.  Then tried to install the plugin and same problem.

**Comment by nickrouty** [comment]
I ended up using the One Signal Cordova plugin. It works really well and then you have a GUI as well to trigger the push notifications. The service is free.

**Comment by macdonst** [comment]
Original poster solved their issue.
