### ISSUE TITLE
Init options not setting up custom notification icon. "module is not defined"

### ISSUE THREAD

**Issue by RenanDresch** [phonegap/phonegap-plugin-push#1909]
### Expected Behaviour
When receiving a notification, the icon must be the one from res/drawable 

### Actual Behaviour
When receiving notifications the plugin will not set the custom icon (or icon color) specified into init options and will instead set the default app icon as the notification small icon, resulting into a white square.

When setting a white+alpha icon as the default app icon, it will draw correctly (affirming that the default app icon is being picked not the custom one).

When debugging (android studio to device) the following lines shows up in logcat:

D/SystemWebChromeClient: file:///android_asset/www/js/push.js: Line 348 : Uncaught ReferenceError: module is not defined
I/chromium: [INFO:CONSOLE(348)] "Uncaught ReferenceError: module is not defined", source: file:///android_asset/www/js/push.js (348)

Which refers to the module responsible for setting up init options 

#### Steps to Reproduce 
add to config.xml:
resource-file src="res/drawable/iconname.png" target="res/drawable/iconname.png" /

and specify on my-app.js init:

```
var push = PushNotification.init({
                android: {
                    "icon": "iconname",
                    "iconColor": "blue"
                },
                browser: {
                    pushServiceURL: 'http://push.api.phonegap.com/v1/push'
                },
                ios: {
                    alert: "true",
                    badge: true,
                    sound: 'false'
                },
                windows: {}
});
```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Motorola Moto G X

#### Cordova CLI version and cordova platform version

    cordova --version 7.0.1
    cordova platform version android    6.2.2

#### Plugin version

    2.0.0-rc5

#### Logs taken while reproducing problem
[log.txt](https://github.com/phonegap/phonegap-plugin-push/files/1232503/log.txt)

**Comment by macdonst** [comment]
@RenanDresch it seems really weird you are getting `Uncaught ReferenceError: module is not defined`, that makes me think you are not waiting until you get the `deviceready` event before trying to load the push plugin.

I also, notice in your logs you have an error in your code as it complains about `aler` not being defined. So you should probably clear that up first.

Finally, your logs stop after the initialization of the plugin but don't show the reception of a new push so I can't tell what image the plugin loads when a message comes in. As well your push payload would really help.

**Comment by macdonst** [comment]
@RenanDresch see https://github.com/phonegap/phonegap-plugin-push/blob/v1.x/docs/PAYLOAD.md#notification-vs-data-payloads
