### ISSUE TITLE
PushNotification.init is not function (TypeError) - phonegap built

### ISSUE THREAD

**Issue by herbertvuijk** [phonegap/phonegap-plugin-push#1911]
### Expected Behaviour
When calling PushNotification.init({..}) i'm expect that to work based on the documentation.

### Actual Behaviour
Getting an error that the function is undefined
Did some testing: 
alert(typeof PushNotification.init);
alert(typeof PushNotification);

Results in:
"undefined"
"function" -> Note: PushNotication is defined. The init function is not defined though

Looks likes this issue: https://github.com/phonegap/phonegap-plugin-push/issues/1838. I also tried alerting the same tests with timeout of 10 seconds, everyting completely loaded for sure. results in the same problem

I'm also noticing that no Push permission is asked when installing the app. Maybe that is related? 

Note: push.js is distributed in the APK. I've unzipped the APK and found the push.js. 

### Reproduce Scenario (including but not limited to)
Because it's a phonegap built with Mendix back-end it's not so easy to provide the reproduce steps here.

The phonegap built log is cleary stating that it has built the Phonegap-push-plugin 
Total time: 1.232 secs
Fetching plugin "phonegap-plugin-push@1.9.0" via npm
Installing "phonegap-plugin-push" at "1.9.0" for android
Subproject Path: CordovaLib
Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:clean
:CordovaLib:clean

BUILD SUCCESSFUL

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
 
PhoneGap (iOS / Android / Windows)
cli-6.4.0 (4.3.0 / 6.1.0 / 4.4.3)

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Galaxy S7, Android

#### Plugin version
1.9.0

Used it this way. I also tried 1.10.5 but did go back to 1.9 because that's mentioned in the documentation as a working combination with 6.4.0.

```
 <plugin name="phonegap-plugin-push" source="npm" spec="1.9.0" >
		<param name="SENDER_ID" value="xxx" />
	</plugin>
```

Also have this in my config.xml:

```
        <preference name="android-build-tool" value="gradle" />
```

**Comment by macdonst** [comment]
@herbertvuijk your build log shows it fetching the push plugin but there is not enough there to show it was included properly. What is a "Mendix back-end"? Is that an on-line build tool for Cordova apps?

**Comment by herbertvuijk** [comment]
Hi Macdonst,

Thanks. If I unzip the APK I see this in cordova_plugins.js, among other plugins: 
{
        "id": "phonegap-plugin-push.PushNotification",
        "file": "plugins/phonegap-plugin-push/www/push.js",
        "pluginId": "phonegap-plugin-push",
        "clobbers": [
            "PushNotification"
        ]
    },

Also the assets\www\plugins\phonegap-plugin-push\www\push.js is there and filled. 

Mendix is a application platform that runs the wep-app that is referenced from the Cordova app. I can provide the phonegap built zip and APK if that is of any value?

**Comment by macdonst** [comment]
@herbertvuijk well if the Push Plugin is included I have to assume you are trying to call the `init` method before you get the `deviceready` event or from a page in which the plugin is not loaded. If you post up the zip file somewhere I will take a quick look.

**Comment by herbertvuijk** [comment]
Hi Simon,
Thanks. Figured it out. There was a very old version of some push plugin included as well, which was overwriting the PushNotification object / prototype. Removed it, and now it worked.
