### ISSUE TITLE
Not able to upgrade to 2.0.0

### ISSUE THREAD

**Issue by jayeshanandani** [phonegap/phonegap-plugin-push#1912]
### Expected Behaviour
```cordova plugin add phonegap-plugin-push``` should install version 2.0.0

### Actual Behaviour
```cordova plugin add phonegap-plugin-push``` installs version 1.10.5

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ios 9.3

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.0.1
   cordova ios                                                 4.4.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@jayeshanandani I need better reproduction scenario than the above. I did:

```
$ cordova create ack
$ cordova platform add ios
$ cordova plugin add phonegap-plugin-push
$ cordova plugins 
cordova-plugin-whitelist 1.3.2 "Whitelist"
phonegap-plugin-push 2.0.0 "PushPlugin"
```

**Comment by jayeshanandani** [comment]
@macdonst : I am trying again with fresh setup and will get back in an hour.

**Comment by jayeshanandani** [comment]
Seems to be working.
