### ISSUE TITLE
Per-user sound for a TOPIC?

### ISSUE THREAD

**Issue by uj** [phonegap/phonegap-plugin-push#1916]
This is not an issue with the plugin.  

Sounds works fine when I send the sound filename in the payload, and when I send to individual devices I simply specify that person's desired sound in the payload.  That works great.

However, I'm wondering if it is possible to use a per-user / custom sound for a TOPIC that many people are subscribed to?  Or does everyone that is subscribed to the same topic have to use the same sound since it is specified in the topic's payload?

**Comment by macdonst** [comment]
@uj everyone subscribed to the topic would get the same payload and therefore the same sound would play.
