### ISSUE TITLE
Not showing the message permission for push notification.

### ISSUE THREAD

**Issue by deluxeuo** [phonegap/phonegap-plugin-push#192]
In my IOS 8.1 is not showing the message allowed to send push notification to open the application.

But I have no error, I can register the ID and successfully send push too. But that's a problem for Apple

for iOS 8.4 it appears the alert. But not ios 8.1

**Comment by macdonst** [comment]
@deluxeuo Sorry what message do you mean? The dialog that asks the user to send a Push?

**Comment by deluxeuo** [comment]
The message permission to receive push

I sent my production version with push

But I have several problems, iOS 8.4 can not register key, IOS 9 can register, but does not receive push. IOS 8.1 everything ok

**Comment by macdonst** [comment]
I have no way to reproduce this issue. If anyone has a 8.1 device to help testing that would be great.

**Comment by macdonst** [comment]
Closing, inactivity. Also, we are up to iOS 11.3 now so support 8.1 is not longer required.
