### ISSUE TITLE
Notification doesn't contain "data.count" information to set badge properly

### ISSUE THREAD

**Issue by JaneDawson** [phonegap/phonegap-plugin-push#1920]
### Expected Behaviour
From the documentation:
`Each notification event contains a data.count value which can be used to set the badge to correct number.`
This seems not to be true.

### Actual Behaviour
No `data.count` or `data.additionalData.count` included in the notification.

### Reproduce Scenario (including but not limited to)
Send,  receive and inspect Notification.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Cordova ios 4.4.0 / iOS 10.3.3

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPad Pro 10.5"

#### Cordova CLI version and cordova platform version
cordova --version: 7.0.1

Installed platforms (cordova platform version android):
  android 6.2.3
  ios 4.4.0

#### Plugin version
2.0.0

#### Sample Push Data Payload
```
         payload_silent_iOS = {
                "data":{
                    "msgId": dataInput.msgId,
                    "transactionId": dataInput.transactionId,
                    "notId": event.params.messageId,
                    "priority": "2",
                    "force-start": "1",
                    "content-available": "1",
                    "silent_notification": "true"
                }
            }
```

#### Sample Code that illustrates the problem
```
push.on("notification", data => {
    console.log("XXX Notifcation received. data.: ",data);
    // data doesn't include a count object

    push.setApplicationIconBadgeNumber(
              () => {
                console.log("success");
                push.finish(
                  () => console.log("push.finish() successful"),
                  err => console.log("push.finish() error for notId "+data.additionalData.notId+": ",err),
                  data.additionalData.notId);
              },
              err => {
                console.log("error: ",err)
              },
              data.additionalData.count); 
              // returns undefined, no matter if "data.additionalData.count" or "data.count" 
});

```

#### Logs taken while reproducing problem

**Comment by macdonst** [comment]
@JaneDawson are you using APNS or FCM to send to iOS?

**Comment by JaneDawson** [comment]
FCM

**Comment by JaneDawson** [comment]
@mcdonst: Shouldn't there be the data.count with FCM, as well?

**Comment by macdonst** [comment]
@JaneDawson seems like it should. I will retest when I can, currently on vacation.

**Comment by JaneDawson** [comment]
Thank you, @macdonst.
It looks like the on-notification-handler is not even started at all, when the app is running in background (tested on iPad with iOS 10.3.3). As you can see above, I am using `"content-available": "true"` and `"force-start": "1"`.

I want to show the amount of new notifications in a badge. Unfortunately, I cannot include this number to my payload. It needs to be calculated on the client of the user who is receiving the notification.

Thank you for any suggestions and enjoy your vacation ;-)

**Comment by macdonst** [comment]
@JaneDawson I did another quick look at things and it appears your payload is not 100% correct for sending to FCM/GCM on iOS. Check this out:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#gcm-and-additional-data

**Comment by JaneDawson** [comment]
Hi @macdonst.
Thank you for looking into this. I did read the documentation. Several times, actually ;-)
From my understanding my iOS payload does correspond to the documentation. I'm acutally sending two notifications for iOS. One that's handling the push notification the user is receiving. The second one ("silent") is supposed to wake up the app in background and deals with increasing the badge number - this part currently doesn't work.

These are my two iOS payloads. I would be very happy if you let me know, which part doesn't correspond to the documentation from your point of view:

```
         payload_silent_iOS = {
                "data":{
                    "msgId": dataInput.msgId,
                    "transactionId": dataInput.transactionId,
                    "notId": event.params.messageId,
                    "priority": "2",
                    "force-start": "1",
                    "content-available": "1",
                    "silent_notification": "true"
                }
            }

         payload_iOS = {
                "notification":{
                    "title":"NotificationTitle",
                    "body": "Message"
                },
                "data":{
                    "soundname":"default",
                    "msgId": dataInput.msgId,
                    "transactionId": dataInput.transactionId,
                    "priority": "high",
                    "silent_notification": "false"
                }
            }
```
Your help is very much appreciated - thank you!

**Comment by JaneDawson** [comment]
Any news on this?

**Comment by macdonst** [comment]
@JaneDawson it's amazing how much clarity one can receive when their kids go back to school. I've taken another read through everything here without getting interrupted and I now see what is going on. First the `data.count` property doesn't get automatically set by the push plugin. It is up to your app server to keep track of what the badge number should be and send that down to the application as part of the push payload. 

For the case of the FCM/GCM on iOS the payload would look like:

```
         payload_iOS = {
                "notification":{
                    "title":"NotificationTitle",
                    "body": "Message",
                    "badge": "7" // set to whatever number you want
                },
                "data":{
                    "soundname":"default",
                    "msgId": dataInput.msgId,
                    "transactionId": dataInput.transactionId,
                    "priority": "high",
                    "silent_notification": "false"
                }
            }
```

The OS should properly read the `badge` property and set it for you. The resulting `data.count` property in your push notification event should be `7` in this case.

**Comment by JaneDawson** [comment]
@macdonst: Thank you for your answer. Now everything makes sense... I will try this way...
I would recommend to update the API part of your docs, though, since this part may lead to misunderstandings as happened in my case:

> **count** | number | Indicates what number should show up in the badge. Passing 0 will clear the badge. **Each notification event contains a data.count value which can be used to set the badge to correct number.**

However, knowing that I have to add the badgenumber to my push-notification: Do you have any suggestion, how the backend-server (Firebase in my case) would able to know the amount of PushNotifications the user's phone received, since the user opened my app the last time? I thought this `data.count` property somehow came from the OS, since the OS knows, how many unread push notifications there are...

**Comment by JaneDawson** [comment]
In addition, there still is the thing, that my `on-notification` is not called when the app is running in background, as explained [here](https://github.com/phonegap/phonegap-plugin-push/issues/1920#issuecomment-325435109). Do you have any idea on this, as well?

Furthermore, it may be interesting for you to here, that the users iOS devices only play a sound, when I add the `"sound": "default"` to the _**notification**-part_ instead of the _**data**-part_ of the payload. That wasn't discussed in the documentation as well and took me quite a long time to figure out.

**Comment by maxneuvians** [comment]
I experienced the same issue - `notifications` would not be called when the app was running in the background. Take a look here: 

https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH10-SW8

My issue ended up being that I had not enabled background notifications as an option for the iOS app in the capabilities tab.

**Comment by JaneDawson** [comment]
Thank you, @maxneuvians, that might be the problem. I will try that next week. Thank you!
