### ISSUE TITLE
Android Depedency Error with Push Setup Through Ionic Native

### ISSUE THREAD

**Issue by n08** [phonegap/phonegap-plugin-push#1921]
###

Expected Behaviour
Using Ionic 3.x it is expected that one can use the @ionic-native 
push plugin to send push notifications through Firebase. However, after adding an Android app in Firebase and using the sender Id given in the Firebase console, there is an error when trying to run an app with Push and Firebase as follows:

### Actual Behaviour
An error is created when trying to run on an android device.

```
A problem occurred configuring root project ‘android’.

Could not resolve all dependencies for configuration ':_debugApkCopy'. Could not find com.google.firebase:firebase-messaging:11.0.1. Required by: project : Could not find com.google.firebase:firebase-core:11.0.1. Required by: project :

```

### Reproduce Scenario (including but not limited to)
Google Services, Repistory all updated to latest version in Android Studio.
One proposed solution online is to add lines to build.gradle. However, Ionic forums suggest that this file gets overriden by Ionic at runtime.

Ionic Version 3.7.0
[build_gradle.txt](https://github.com/phonegap/phonegap-plugin-push/files/1253064/build_gradle.txt)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Test Device is Android 7.0 (however, app doesn't run even if phone is disconnected)
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy S6 Edge Series
#### Cordova CLI version and cordova platform version

    cordova --version                                    7.0.1
    cordova platform version android           6.2.3

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   latest(2.0.0 I believe)

#### Sample Code that illustrates the problem

```
[const options: PushOptions = {
   android: {
       senderID: 'XXXXXXXXXX'


   },
   ios: {
       alert: 'true',
       badge: true,
       sound: 'false'
   },
   windows: {}
};
const pushObject: PushObject = this.push.init(options);

pushObject.on('notification').subscribe((notification: any) => {
  if(notification.additionalData.foreground){
  let alert = this.alertCtrl.create({
title: 'New Push Notification',
message: notification.message,
  });
alert.present();
  }
});

pushObject.on('registration').subscribe((registration: any) => console.log('Device registered', registration));

pushObject.on('error').subscribe(error => console.error('Error with Push plugin', error));

}]
```

**Comment by macdonst** [comment]
@n08 do you have the Android Support Repository and Google Repository installed in your build environment?

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#compilation

**Comment by n08** [comment]
@macdonst 

![androidstuff](https://user-images.githubusercontent.com/31357993/29744692-9a6b4104-8aaa-11e7-877e-a2cbdab818d0.png)
Should be installed, yes...

**Comment by macdonst** [comment]
@n08 looks correct. Are you starting the above GUI from inside Android Studio or the command line? Sometimes the Android Studio SDK location and command line SDK location point to different locations. So even though it looks like everything is installed it's not.

**Comment by n08** [comment]
@macdonst This is started from within android studio. How would I go about to check for the error that you indicated?

**Comment by macdonst** [comment]
@n08 check to see if your $ANDROID_HOME environment variable points to the same location that is shown in Android Studio. If it is not then the CLI is picking up a different installation of the Android SDK. You'd have to run `android` or `sdkmanager` from the command line in order to see what's installed.

**Comment by n08** [comment]
@macdonst You were absolutely correct, I had to change my environment variable to the folder in Appdata/android instead of my installation folder. Closing this now

**Comment by jrmeurer** [comment]
This solved the issue for me too! Thanks!

SOLUTION: 
Run `android` and install/update `Android Support Repository` and `Google Repository`
