### ISSUE TITLE
on.notification is never triggered on IOS BACKGROUND

### ISSUE THREAD

**Issue by uj** [phonegap/phonegap-plugin-push#1925]
### Expected Behaviour
on.notification should be triggered if content_available=true 

### Actual Behaviour
on.notification is triggered just fine if the app is running in the foreground, 
but is never triggered if the app is running in the background

### Reproduce Scenario (including but not limited to)
Send this payload through FCM to an IOS device

{
"to":"my_device_token",
"content_available":true,
"priority":"high",
"notId":82888,
"time_to_live":3600,
"data":
     {
      "mydata":"1"
     }
}

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
IOS 10.3

#### Cordova CLI version and cordova platform version
    cordova 7.0.1
    cordova ios 4.4.0

#### Plugin version
current github

**Comment by daleeidd** [comment]
According to the documentation, you should use `content-available`. `content_available` is only for Android and it does not work as well as `content-available` under the `data` property.

Either way, this will not solve the issue as the issue persists for me despite this (and many other variations). I am also using Google FCM.

I did find an oddity worth mentioning to the maintainers. The following will not execute the notification callback:

```php
[
  'condition' => "'platform.android' in topics || 'platform.ios' in topics",
  'notification' => [
    'priority' => 'high',
    'content-available' => 1,
  ],
  'data' => [
    'content-available' => 1,
    'test' => 'hello',
    'notId' => '23232424232',
  ]
];
```

But the following will (added sound property):
```php
[
  'condition' => "'platform.android' in topics || 'platform.ios' in topics",
  'notification' => [
    'priority' => 'high',
    'content-available' => 1,
    'sound' => 'default',
  ],
  'data' => [
    'content-available' => 1,
    'test' => 'hello',
    'notId' => '23232424232',
  ]
];
```

And if both of the above is with the app in the background, the former will do nothing at all, but the latter will play the sound and nothing else (no calling callback). So the device is getting the notification, but the plugin is not processing it correctly.

I would have opened my own ticket, but I think there is enough pertaining to this same issue with Google FCM.

**Comment by uj** [comment]
@daleeidd No, you MUST use content_available: true and it must be outside of the data part if you want to trigger on.notification (The documentation you are reading does not tell you this because that documentation is only for sending to IOS with APNS, not FCM).  If you use FCM, you have to use content_available: true outside of the data part, and this has been confirmed by both the FCM official documentation and also the author of this plugin within the the Issues section of this website.

I found my problem, and I have found that the following DOES work for sending to IOS with FCM!  It triggers on.notification even when the phone screen is turned off:

`			    [
				"to" =>  "some_device_token_here",
				"content_available" =>  true,
				"priority" =>  "high",
				"time_to_live" => 3600,
				"force-start" => 1,
				"notification" =>
					[
					"priority" =>  "high",
					"title" => "title",  (title and body are optional)
					"body" => "message",  (title and body are optional)
					],
					
				"data" => 
				[ 
				"notId" => "some_id_here"
				],
				
				]
				
				`

Also, make sure make sure you are calling on.finish with the notID every time.  Otherwise IOS will kill your app and it will not work until you manually turn the app back on.  If you sometimes see the splashscreen when you open your app (other than the first time you run it obviously), you know that IOS killed it.

I think my problem was because I was putting the notID outside the data part instead of inside the data part.

**Comment by macdonst** [comment]
@uj you are correct about `content_available: true`. Sadly the plugin can only normalize the API on the client level for the server side you will end up sending different payloads based on FCM (Android, FCM (iOS) and APNS.

So your root issue got resolved?

**Comment by uj** [comment]
my issue is currently resolved, yes, 
on.notification is being called in the background on IOS with the above payload.

**Comment by msyahidin** [comment]
actually I have same problem, but on Android. set content_available : true wont solve the problem.
on('notification') never triggered on background.

I am using laravel as api for sending message through fcm to my Ionic 3 app

`
   "cordova": {

        "plugins": {
            "cordova-plugin-geolocation": {},
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-keyboard": {},
            "cordova-plugin-background-mode": {},
            "cordova-plugin-appminimize": {},
            "com.googlemaps.ios": {},
            "phonegap-plugin-push": {},
            "cordova-plugin-googlemaps": {
                "API_KEY_FOR_ANDROID": "token",\
            }
        },
        "platforms": [
            "android"
        ]
    }
`

There is conflict on google maps plugin, but I have solved it. The message was send but the event not triggered on background

**Comment by macdonst** [comment]
Closing as original reporter issue was resolved.
