### ISSUE TITLE
[question] FCM on ios 

### ISSUE THREAD

**Issue by raugaral** [phonegap/phonegap-plugin-push#1926]
### Actual Behaviour
On the ts types file only is the "gcmSandbox" attribute. 
The API documentation says: "iOS GCM support. The following properties are used if you want use GCM on iOS." and the property name is ios.fcmSandbox.
What's wrong? The API or ts types file?? it's necessary this property to do this works on ios? I have problems to register ios devices and receive an id.

https://github.com/phonegap/phonegap-plugin-push/blob/master/types/index.d.ts
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md

#### Cordova CLI version and cordova platform version

Cordova CLI : 7.0.1
 Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.4.0

#### Plugin version

phonegap-plugin-push@2.0.0

**Comment by sobolevan** [comment]
@raugaral I have the same issue. Have you found out?

**Comment by macdonst** [comment]
I updated the types file.
