### ISSUE TITLE
Some features not working on Xiaomi

### ISSUE THREAD

**Issue by kirill001** [phonegap/phonegap-plugin-push#1929]
### Expected Behaviour
I used 'force-start', 'visible', 'style=inbox', 'summaryText', 'actions' and others. I want to use these options and to launch application when it is stopped.
### Actual Behaviour
It's not working on my Xiaomi Redmi 4.  I just have standard notifications with icon, title and message. There are no buttons, no inbox messages and no summary text. Also, I can't receive a notification when the application is stopped. 

#### Platform and Version
Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Xiaomi Redmi 4

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.0.1
    cordova platform version android           6.2.3

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.0.0

#### Sample Code that illustrates the problem
$data = [
            'registration_ids' => $pushRegistrationIds,
            'priority' => 'high',
            'content_available' => true,
            'data' => [
                'title' => 'Title',
                'message' => 'Message',
                'priority' => 2,
                'no-cache' => 1,
                'force-start' => 1,
                'visibility' => 1,
                'style' => 'inbox',
                'summaryText' => 'There are %n% notifications',
                "actions" => [
                    [
                        "icon" => "emailGuests",
                        "title" => "EMAIL GUESTS",
                        "callback" => "app.test",
                        "foreground" => true
                    ],
                    [
                        "icon" => "snooze",
                        "title" => "SNOOZE",
                        "callback" => "app.test",
                        "foreground" => false
                    ]
                ],
                "ledColor" => [0, 0, 255, 0],
                "vibrationPattern"> [2000, 1000, 500, 500],
            ]
        ];

//Curl sending...

==========================

It's not working on my phone, but it works on other devices including other Xiaomi smartphones.
How can I find the cause of the problem?

**Comment by macdonst** [comment]
@kirill001 well I think you've already found the problem, Xiaomi  👀  but if you reproduce the issue while running `adb logcat | grep Push` I might be able to tell you more.

**Comment by kirill001** [comment]
@macdonst Unfortunately, I can't event connect my smartphone to PC. There is an empty list of devices. But if I solve this problem I'll tell you.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
