### ISSUE TITLE
error with plugin facebook

### ISSUE THREAD

**Issue by diegoherrera** [phonegap/phonegap-plugin-push#193]
For weeks I have this error

my plugin is

com.phonegap.plugins.facebookconnect 0.11.0 "Facebook Connect"
cordova-plugin-camera 1.2.0 "Camera"
cordova-plugin-whitelist 1.0.0 "Whitelist"
io.litehelpers.cordova.sqlite 0.7.10 "Cordova sqlite storage plugin"
org.apache.cordova.device 0.3.0 "Device"
org.apache.cordova.file 1.3.3 "File"
org.apache.cordova.file-transfer 0.5.0 "File Transfer"
org.apache.cordova.geolocation 0.3.12 "Geolocation"
org.apache.cordova.network-information 0.2.15 

this is error in buil 

C:\phonegap\tstfaceebook>cordova build android
Discovered plugin "SavePhotoPlugin" in config.xml. Installing to the project
Running command: cmd "/s /c "C:\phonegap\tstfaceebook\platforms\android\cordova\build.bat""
ANDROID_HOME=C:\Buckup Disco\Formacion\Cursos 2015\Curso de Android 2015\Herramientas de Desarrollo\adt-bundle-windows-x86-20140702\adt-bundle-windows-x86-20140702\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.7.0_65
Running: C:\phonegap\tstfaceebook\platforms\android\gradlew cdvBuildDebug -b C:\phonegap\tstfaceebook\platforms\android\build.gradle -Dorg.gradle.daemon=true
:preBuild
:compileDebugNdk UP-TO-DATE
:preDebugBuild
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:compileDebugJava UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:compileLint
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:copyDebugLint UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:mergeDebugProguardFiles UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:preBuild
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:preDebugBuild
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:checkDebugManifest
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:preDebugTestBuild
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:prepareDebugDependencies
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:compileDebugAidl UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:compileDebugRenderscript UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:generateDebugBuildConfig UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:generateDebugAssets UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:mergeDebugAssets UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:generateDebugResValues UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:generateDebugResources UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:mergeDebugResources UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:processDebugManifest UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:processDebugResources UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:generateDebugSources UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:compileDebugJava UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:processDebugJavaRes UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:packageDebugJar UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:compileDebugNdk UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:packageDebugJniLibs UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:packageDebugLocalJar UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:packageDebugRenderscript UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:packageDebugResources UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:bundleDebug UP-TO-DATE
:prepareAndroidComPhonegapPluginsFacebookconnectHellocordovaFacebookLibUnspecifiedDebugLibrary UP-TO-DATE
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:preReleaseBuild
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl UP-TO-DATE
:CordovaLib:compileReleaseRenderscript UP-TO-DATE
:CordovaLib:generateReleaseBuildConfig UP-TO-DATE
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets UP-TO-DATE
:CordovaLib:generateReleaseResValues UP-TO-DATE
:CordovaLib:generateReleaseResources UP-TO-DATE
:CordovaLib:packageReleaseResources UP-TO-DATE
:CordovaLib:processReleaseManifest UP-TO-DATE
:CordovaLib:processReleaseResources UP-TO-DATE
:CordovaLib:generateReleaseSources UP-TO-DATE
:CordovaLib:compileReleaseJava UP-TO-DATE
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:copyReleaseLint UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:mergeReleaseProguardFiles UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:preReleaseBuild
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:checkReleaseManifest
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:prepareAndroidCordovaLibUnspecifiedReleaseLibrary UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:prepareReleaseDependencies
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:compileReleaseAidl UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:compileReleaseRenderscript UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:generateReleaseBuildConfig UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:generateReleaseAssets UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:mergeReleaseAssets UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:generateReleaseResValues UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:generateReleaseResources UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:mergeReleaseResources UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:processReleaseManifest UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:processReleaseResources UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:generateReleaseSources UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:compileReleaseJava UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:processReleaseJavaRes UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:packageReleaseJar UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:compileReleaseNdk UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:packageReleaseJniLibs UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:packageReleaseLocalJar UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:packageReleaseRenderscript UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:packageReleaseResources UP-TO-DATE
:com.phonegap.plugins.facebookconnect:hellocordova-FacebookLib:bundleRelease UP-TO-DATE
:prepareComAndroidSupportSupportV132301Library
:prepareComAndroidSupportSupportV42301Library
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues UP-TO-DATE
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:compileDebugJava
C:\phonegap\tstfaceebook\platforms\android\src\com\adobe\phonegap\push\GCMIntentService.java:483: error: cannot find symbol
            mBuilder.setColor(iconColor);
                    ^
  symbol:   method setColor(int)
  location: variable mBuilder of type Builder
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:compileDebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 22.564 secs

C:\phonegap\tstfaceebook\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "C:\phonegap\tstfaceebook\platforms\android\gradlew cdvBuildDebug -b C:\phonegap\tstfaceebook\platforms\android\build.gradle -Dorg.gradle.daemon=true"
ERROR building one of the platforms: Error: cmd: Command failed with exit code 8
You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 8
    at ChildProcess.whenDone (C:\Users\Bangh\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:139:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

**Comment by macdonst** [comment]
@diegoherrera Read this issue #51 

The Facebook plugin includes an old support jar which doesn't have the setColor method. You'll need to delete that one and include the one that is referenced via this plugins, plugin.xml.

**Comment by diegoherrera** [comment]
i replace support-v4 by support-v13 in plugin facebook but this not work for me.  It has any guide the change process support ?

**Comment by fredgalvao** [comment]
@diegoherrera  Check my comment [here](https://github.com/phonegap/phonegap-plugin-push/issues/159#issuecomment-142369852).

**Comment by macdonst** [comment]
@diegoherrera we really recommend you use this plugin: 

https://github.com/jeduan/cordova-plugin-facebook4

as it properly handles gradle based dependencies and it being updated more frequently. 

If you have an issue compiling the app and you are getting this error:

```
* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library /Users/smacdona/code/bookface/platforms/android/build/intermediates/exploded-aar/com.facebook.android/facebook-android-sdk/4.6.0/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="com.facebook" to force usage
```

Then you can add the following entry into your config.xml file in the android platform tag.

```
<platform name="android">
    <preference name="android-minSdkVersion" value="15"/>
 </platform>
 ```

Give that a shot and report back here. Close the issue if it works for you.

**Comment by diegoherrera** [comment]
hi macdonst , thanks for help.  My problem have solution. first remove the plugin facebook with support-v4, after remove platform android. later add platform android and install the plugin faceebook https://github.com/jeduan/cordova-plugin-facebook4. build my project successfully

**Comment by globexdesigns** [comment]
The problem with jeduan's fork is that its broken on the browser platform (https://github.com/jeduan/cordova-plugin-facebook4/issues/70) which means it's very difficult to work with it when testing the app locally.

Is there any other fork that works with phonegap-plugin-push and Facebook?

**Comment by fredgalvao** [comment]
Not that I know of, @globexdesigns . Jeduan's fork is pretty much the best you'll get no average from the wizcorp repo's network.
