### ISSUE TITLE
Android 8: PushNotification.hasPermission() returns true although push notifications are disabled by the system

### ISSUE THREAD

**Issue by mythos0** [phonegap/phonegap-plugin-push#1930]
### Expected Behaviour

The PushNotification.hasPermission() function **returns false** for the isEnabled property if the push notifications are disabled for this app in the system settings.

### Actual Behaviour

The PushNotification.hasPermission() function **returns true** for the isEnabled property if the push notifications are disabled for this app in the system settings.

#### Steps to Reproduce 

Call PushNotification.hasPermission() after the notifications are disabled for the app in the system settings.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 8.0.0 only
(Android 5 - 7 with the same app is working)

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Google Pixel

#### Cordova CLI version and cordova platform version

    cordova v7.0.1
    cordova platform version android v6.2.3

#### Plugin version

    phonegap-plugin-push   v2.0.0

**Comment by macdonst** [comment]
@mythos0 Thanks, I'll take a look at it. I actually hate that method and wanted to deprecate it, see #811

**Comment by mythos0** [comment]
@macdonst Have you looked into this android bug? Is there a solution to fix this?

**Comment by macdonst** [comment]
@mythos0 nope, I got tied up with a number of things and I'm just sitting down to work on 2.1.0 issues now. Expect some movement soon.

**Comment by macdonst** [comment]
@mythos0 check out the latest from master. Compat now has a great method to do the check which I am very happy to burn some code with 🔥 .

**Comment by macdonst** [comment]
Currently fixed in master, soon to be in release 2.1.0.
