### ISSUE TITLE
Cannot copy GoogleService-info.plist as it already exists

### ISSUE THREAD

**Issue by jayeshanandani** [phonegap/phonegap-plugin-push#1932]
### Expected Behaviour
When running build again file should be replaced.

### Actual Behaviour
It throws error as file is already present.

### Steps to Reproduce
1. Clone a fresh ionic sample repo.
2. Run `ionic cordova build ios --prod`.
3. It will result into error of GoogleMacBox not found.
4. Go into ios project and do `pod instsall`.
5. Try to run `ionic cordova build ios --prod` again.
6. It fails with above stated error.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ios 4.4.0

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.0.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.0.0

**Comment by macdonst** [comment]
Same root cause as #1826
