### ISSUE TITLE
How do you install this plugin for Phonegap Build?

### ISSUE THREAD

**Issue by shortnoticeapp** [phonegap/phonegap-plugin-push#1933]
I added this to my config.xml file:

<gap:plugin name="phonegap-plugin-push" source="npm"/>

Do I need to do anything else? It seems like the code is doing nothing. Again, I am using Phonegap Build. 

Thanks!

**Comment by elijthomas** [comment]
You need to do the following also in your JS to initialise it

var pushNotifications = PushNotification.init({
                            android: {},
                            ios: {
                                alert: "true",
                                badge: "true",
                                sound: "true"
                            }
                    });
                    
                    PushNotification.hasPermission(function(data) {
                        //data
                    });
                    
                    pushNotifications.on('registration', function(data) {
                        // data.registrationId
                    });

                    pushNotifications.on('notification', function(data) {
                        // data.message,
                        // data.title,
                        // data.count,
                        // data.sound,
                        // data.image,
                        // data.additionalData
                    });

                   pushNotifications.on('error', function(e) {
                        //e.message
                    });

**Comment by shortnoticeapp** [comment]
var push = PushNotification.init({
   
  ios: {
    alert: "true",
    badge: true,
    sound: 'false'
  }
});

PushNotification.hasPermission(function(data) {
    if (data.isEnabled) {
        alert('isEnabled');
    }
    alert(data);
});

This is the code I have to run when a user presses a button, but the notification permission message doesn't come up. What am I doing wrong?

**Comment by macdonst** [comment]
@shortnoticeapp read the following links and the next time you open an issue please fill out the issue template.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md#phonegap-build-support

https://blog.phonegap.com/phonegap-7-0-1-now-on-build-and-it-includes-some-important-changes-89087fe465f5
