### ISSUE TITLE
receive data of push message when app ist not running

### ISSUE THREAD

**Issue by Snare92** [phonegap/phonegap-plugin-push#1936]
### Expected Behaviour

Receive the 'data' part of the push message in the on('notification') event handler, without displaying any message in the devices notification center, even when the app ist not in the foreground and not in the background. For example if the user kills the app. This should work on Android and on iOS.

### Actual Behaviour

If i read the docs right, it ist only possible to receive 'data' from the push message when the app ist in the foreground or in the background, not when it is not running. 
Please correct me if I'm wrong, but is there really no possibility to receive a 'silent' push message with data for the app?

**Comment by macdonst** [comment]
@Snare92 if the app has been force quit on Android or iOS then the web view is not resident in memory and therefore there is no JS engine available to run the `on('notification')` event handler.

**Comment by Snare92** [comment]
@macdonst ok I understand that. 
But I have another Question. 
If the app is closed and the smartphone receives a pusch message with a title or a message part, than it is displayed in the devices notification center. 
If the user clicks the notification, the app will be startet an the `on('notification')` gets called. 

So why there isn't the functionality that the app gets startet in the background when the smartphone receives a pusch message without a title or a message part?

**Comment by fredgalvao** [comment]
@Snare92 Such functionality exists, but for android only. Please read the docs on it:
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#application-force-closed

**Comment by Snare92** [comment]
@fredgalvao thanks for the hint, 
I implemented the force start and it works, the app is started, but the `on('notification')` callback is not called. It is only called when the app comes in the foreground. Is this the normal behaviour?
I also add the content-avaiable flag `"content-available": "1"`

**Comment by fredgalvao** [comment]
Would you mind creating a new issue for your case, @Snare92 ? We could use a full issue report with proper log and info to help on that.

**Comment by Snare92** [comment]
@fredgalvao  OK i will do so, What the best way to get a proper Log, I'm quite new to cordova and ionic.

**Comment by fredgalvao** [comment]
https://www.jasonsnider.com/posts/view/using-logcat-with-cordova
