### ISSUE TITLE
Listen event on click in notification when notification is on tray section

### ISSUE THREAD

**Issue by Marcelinne** [phonegap/phonegap-plugin-push#1937]
### Expected Behaviour
When the app is in background, I can not listen the event when I click on notification when the notification is in tray

### Actual Behaviour
With content-available, I can see how the notifications arrives, but when I click on it, I can not get which notification I clicked on, how I can know that?
`
{

    "aps": {

        "alert": "Test background push",

        "content-available": 1

    },

    "notId": 1 // unique ID you generate

}`

### Reproduce Scenario (including but not limited to)
I can reproduce in android, when the app is in background

#### Steps to Reproduce 
1.- Sent different notifications to your cellphone
2.- Click on one of them in tray secction when the app is in background
3.- I can not get which specific notification I clicked on

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Version Android: 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsumg TabS

#### Cordova CLI version and cordova platform version
cordova 7.0.1
cordova platform version android 6.1.2

#### Plugin version
phonegap-plugin-push 1.10.5 "PushPlugin"

#### Sample Push Data Payload
`{

	"where": {

          "deviceType": {

            "$in": [

              "android"

            ]

        }

    },

	"data": {

	  "title": "The testing 1111",

	  "content-available": "1"

	}

}`

#### Sample Code that illustrates the problem
I'm working with ionic2:
`pushObject.on('notification').subscribe((data: any) => {
       console.log("data " + data);
})`

#### Logs taken while reproducing problem
None

**Comment by macdonst** [comment]
@Marcelinne the `on('notification')` event is called and it should include the payload of your push notification. It's up to you to put unique identifying information in the payload.

**Comment by Marcelinne** [comment]
@macdonst I see notification is called, but it is called everytime a notification arrives, I need to know when the user click on a specific notification, how and where I can get this event? that event does not do the `on(notification)`

**Comment by macdonst** [comment]
@Marcelinne when you click on a notification in the system tray does your app open and the `on('notification')` event get called?

**Comment by Marcelinne** [comment]
nop, it is not called, that's why I asking where I can get that event?, thanks in advance =)

**Comment by macdonst** [comment]
@Marcelinne please reproduce the issue while gathering some logs `adb logcat | grep Push`

**Comment by jcesarmobile** [comment]
You shouldn't use `"content-available": 1` when you send an alert, `"content-available": 1` is for **silent** notifications, that is probably related to your problem

**Comment by Marcelinne** [comment]
@jcesarmobile thanks for the advice, I've just tested without alert, and is not working also. I've updated the my example.

**Comment by alex-polosky** [comment]
@Marcelinne, are you still experiencing this issue? I am also experiencing this issue and am unable to figure out how to fix it. No matter what I do, I cannot get the notification even to fire if the app is not open. 

If the app is open, no notification is displayed, and the notification event is fired. This is expected behavior. However, if the app is closed, a notification is displayed (albeit with no sound or vibration; that is a separate issue I am trying to figure out as well). However, upon clicking it, the only thing that happens is that the app is opened (whether a cold start or the last state of the app) and the notification event is not fired.

How do we fix this, and is there a possibility of getting a fully working code sample somewhere?

Thanks!

**Comment by macdonst** [comment]
@alex-polosky if you provide your push payload and some logs I may be able to help.

**Comment by Marcelinne** [comment]
@alex-polosky I didn't have luck to fix this issue, maybe if you have the logs I may helps us, you can add here. I was not able to get my logs because they were mixed with a plugin that I was using https://github.com/taivo/parse-push-plugin, so I'm trying to separete the logs, once I finish to get the logs I'm going to add too.

**Comment by macdonst** [comment]
@Marcelinne if you were using two different plugins to receive pushes it's quite possible that one was getting the incoming push and not passing it along to the other.

**Comment by pawan-mittal** [comment]
@macdonst  I am also facing same issue. when I click on a notification in the system tray my app opens and the on('notification') event is not called.

**Comment by kpwa** [comment]
im expiriencing the same issue. how to fire the event when app is opened from tray icon??

**Comment by alex-polosky** [comment]
@pawan-mittal , @kpwa , and anyone else who might be having this issue:

Take a look at the last two comments I made in #2152 . I attempted to provide a simple demo of what to send, and a simple explanation of what's happening. Take a look at it and see if it helps.
