### ISSUE TITLE
Invalid Push Token for iOS

### ISSUE THREAD

**Issue by casper123** [phonegap/phonegap-plugin-push#1938]
### Expected Behaviour
I should be getting correct push token on registeration

### Actual Behaviour
I do the the push token but when I try to send push notification through APNS, I get an error invalid push token

### Reproduce Scenario (including but not limited to)
Installed push plugin on iOS using ionic framework
I Got registerationId and saved in database
But when i send push notification through APNs I get invalid push token error.

p.s: Im on sandbox environment

```
abdulwahab@Abduls-MacBook-Air.local:~/Documents/mobileapps/hcApp$ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.5.0-dev
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v8.4.0
    npm               : 5.3.0 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 
```

**Comment by macdonst** [comment]
@casper123 what does the PushNotification.init() method look like in your code. Can you post an example of the push token that is invalid?

**Comment by casper123** [comment]
Sure, this is my code. Everything works perfect on android and i also get valid push token and also receive all push notifications on android successfully. But for iOS, I get invalid device token error

```
const options: PushOptions = {
        android: {
          senderID: '857170981039',
          forceShow: true
        },
        ios: {
          alert: 'true',
          badge: true,
          sound: 'true'
        },
        windows: {}
      };
      
      const pushObject: PushObject = this.push.init(options);

      if(localStorage.getItem('gcm_id') == null) 
      {
        pushObject.on('registration').subscribe(
          (registration: any) => {
            if(localStorage.getItem('gcm_id')) {
              console.log('gcm_id exist');
            }
            else {
              localStorage.setItem('gcm_id', registration.registrationId);
              console.log(registration.registrationId);
            }
          }
        );
      }

      pushObject.on('error').subscribe(error => console.error('Error with Push plugin', error));
      pushObject.on('notification').subscribe(
        (notification: any) => {
          console.log('Received a notification', notification);
          if(this.userProvider.isLoggedIn()) {
            this.nav.push(RideDetail,{id:notification.additionalData.customerProperty});
          }
          else {
            console.log('not logged in');
            ;
            
          }
        }
      );
```

That's the sample push token I've received

`cSlnmnmFYVo:APA91bGMTNFNGxQCVduWW98TgRFBJ0t-KwwOQRvy15akheG2IS0WctfN7Ox3ckTOm5_8Z3qAihpNvKEb91hOgP_8-2AxeOy3G2RTVtXQPwONdk5XZAJvfRVE8O1A03vt03Z7w5953jKX
`
I can also upload .pem file for your convenience if required

**Comment by macdonst** [comment]
@casper123 okay, you've stated you are trying to send via APNS but what I see is a registration token that is FCM/GCM. Do you deliver a `GoogleService-Info.plist` in the ios part of the config.xml?

**Comment by casper123** [comment]
Yes i did add the plist file but I want to send push notifications through apns. Is there a work around for this? Because i get build error if I don't include plist file

**Comment by macdonst** [comment]
@casper123 if you want to send via APNS, then omit the plist file. You should not be getting a build error on iOS if you don't include it. I'd be interested to hear more about that.

**Comment by casper123** [comment]
Okay i'll look into it now and get back to you

**Comment by josechristym** [comment]
@macdonst Awesone, I was trying to get this work for past two days. I removed googlesevices_infor.plist from my file. Now it is working great!. Thanks for your answer.

**Comment by spdeepak92** [comment]
@josechristym Did you use same server side code for both ios and android ?? . my token look like 1024efc9cce208270a47d26d82b959ab07219ae3c2e7...1d3c14e49d8229546

**Comment by casper123** [comment]
Okay I did the following and it worked now

1. deleted info.plist from from project root
2. remove ios platform
3. added ios platform
4. build ios

After that i got correct apns id

**Comment by gewoonderrik** [comment]
Thanks @casper123! That did the trick. I just wish I had found out earlier!
