### ISSUE TITLE
Notifications when app is running

### ISSUE THREAD

**Issue by RenanRosa** [phonegap/phonegap-plugin-push#1939]
Hi folks!

I have a question, when the app is running while a notification is send, the notification doesn't show up.
So, is there a way to get the notification and show it when the app is running?

For example,
push.on('notification', function (data) {
 //alert(data);
}

**Comment by sherlockgomes** [comment]
Renan, when the app is running, you need do implement the solution for you business case. Like show a local notification or execute some action.
