### ISSUE TITLE
Custom Icon not shown up with corrrect payload Ionic 3

### ISSUE THREAD

**Issue by Prashant454** [phonegap/phonegap-plugin-push#1940]
### Expected Behaviour

Custom Icon must be applied
### Actual Behaviour
Default icon is shown

#### Cordova CLI version and cordova platform version

    cordova --version         7.0.1

   Installed platforms:
  android 6.2.3
  browser 4.1.0
#### Plugin version

phonegap-plugin-push 2.0.0 "PushPlugin"

#### Sample Push Data Payload
{
    "to": "/topics/members",
    "data": {
        "title": "all member hello",
        "body": "how are you",
        "sound": "default",
        "image": "www/assets/img/icon.png",
        "image-type": "circle",
        "force-start": 1
    },
    "notification": {
        "title": "all member hello",
        "body": "how are you",
        "sound": "default",
        "image": "www/assets/img/icon.png",
        "image-type": "circle",
        "force-start": 1
    }
}

#### Sample Code that illustrates the problem
 public static function sendNotification($title,$content,$token,$receiveTypeID) {
    	//return  url("images/icon.png");
      if($title){
        $noti=array('title'=>$title,
                    'body'=>$content,
              'sound'=>'default',
	        "image"=> "www/assets/img/icon.png"
	        ,"image-type"=>"circle"
        ,"force-start"=> 1);

        if($receiveTypeID==1) {
	        $fields = array( 'to' => '/topics/all', 'data' => $noti, 'notification' => $noti );
        }
        elseif($receiveTypeID==2) {
          $fields = array('to'=>'/topics/members','data'=>$noti,'notification'=>$noti);
        } else if($receiveTypeID==4) {
          $fields = array('to'=>'/topics/vendors','data'=>$noti,'notification'=>$noti);
        } else if($receiveTypeID==0) { //FOR SINGLE USER OR EMPLOYEE
          $fcmIDAry=array($token);
          $fields = array('registration_ids'=>$fcmIDAry,'data'=>$noti,'notification'=>$noti);
        } else {
          return NULL;
        }
        return $fields;
        $headers = array('Authorization: key='.FCM::API_KEY,'Content-Type: application/json');

        $ch = curl_init();
        curl_setopt( $ch,CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send' );
        curl_setopt( $ch,CURLOPT_POST, true );
        curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
        curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
        curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
        curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fields ) );
        $result = curl_exec($ch );
        curl_close( $ch );

        $object = json_decode($result,true);
        // if($object['success'] > 0){
            return $object;
        // }
      }
    }
#### Logs taken while reproducing problem
09-06 11:13:15.577 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: onMessage - from: /topics/members
09-06 11:13:15.577 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: normalize extras
09-06 11:13:15.577 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: key = force-start
09-06 11:13:15.578 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: replace key force-start with force-start
09-06 11:13:15.578 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: key = image-type
09-06 11:13:15.578 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: replace key image-type with image-type
09-06 11:13:15.581 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: key = body
09-06 11:13:15.591 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: replace key body with message
09-06 11:13:15.591 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: no locale found for key = message, error Value how of type java.lang.String cannot be converted to JSONObject
09-06 11:13:15.591 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: key = image
09-06 11:13:15.592 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: replace key image with image
09-06 11:13:15.592 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: key = sound
09-06 11:13:15.592 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: replace key sound with sound
09-06 11:13:15.592 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: key = title
09-06 11:13:15.592 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: replace key title with title
09-06 11:13:15.593 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: no locale found for key = title, error Value all of type java.lang.String cannot be converted to JSONObject
09-06 11:13:15.593 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: key = message
09-06 11:13:15.593 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: replace key message with message
09-06 11:13:15.593 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: no locale found for key = message, error Value how of type java.lang.String cannot be converted to JSONObject
09-06 11:13:15.593 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_FCMService: foreground
09-06 11:13:15.593 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_Plugin: convert extras to json
09-06 11:13:15.593 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_Plugin: key = force-start
09-06 11:13:15.593 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_Plugin: key = image-type
09-06 11:13:15.593 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_Plugin: key = image
09-06 11:13:15.594 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_Plugin: key = sound
09-06 11:13:15.594 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_Plugin: key = title
09-06 11:13:15.594 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_Plugin: key = message
09-06 11:13:15.594 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_Plugin: key = coldstart
09-06 11:13:15.594 16494-18907/com.tribeappsoft.credaimaharashtra D/Push_Plugin: key = foreground
09-06 11:13:15.594 16494-18907/com.tribeappsoft.credaimaharashtra V/Push_Plugin: extrasToJSON: {"image":"www\/assets\/img\/icon.png","sound":"default","title":"all member hello","message":"how are you","additionalData":{"force-start":"1","image-type":"circle","coldstart":false,"foreground":true}}
09-06 11:13:15.606 16494-16494/com.tribeappsoft.credaimaharashtra D/WebView: evaluateJavascript=cordova.callbackFromNative('PushNotification46963468',true,1,[{"image":"www\/assets\/img\/icon.png","sound":"default","title":"all member hello","message":"how are you","additionalData":{"force-start":"1","image-type":"circle","coldstart":false,"foreground":true}}],true);

**Comment by macdonst** [comment]
@Prashant454 re-test with this payload:

```
{
"to": "/topics/members",
"data": {
"title": "all member hello",
"body": "how are you",
"sound": "default",
"image": "www/assets/img/icon.png",
"image-type": "circle",
"force-start": 1
}
}
```

**Comment by Prashant454** [comment]
Thanks.Its working with given payload.
Can I always use this payload with sending all details in data array?

**Comment by macdonst** [comment]
@Prashant454 yeah, read up on why this is the case at: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads
