### ISSUE TITLE
Invalid Push Token for iOS

### ISSUE THREAD

**Issue by manishkr01** [phonegap/phonegap-plugin-push#1942]
I am working on ionic FCM push notification for ios. 
I got FCM Id ("d670c5d68c8fc137c53684b711c5efc97f348d7666514cfd4e9f529d28ee79f3");
But, while sending a message from FCM a console. It throws error "invalid registration token. Check the token format".

for Android this plugin working fine.

**Comment by macdonst** [comment]
@manishkr01 that is not a FCM/GCM token. That is a APNS token.

Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
