### ISSUE TITLE
push.setApplicationIconBadgeNumber Missing

### ISSUE THREAD

**Issue by PinkPanda17** [phonegap/phonegap-plugin-push#1944]
Well I am using this for quite a while now , my version before was 1.8.2 and this code is working perfectly:

                    Push.push.setApplicationIconBadgeNumber(() => {
                        console.log('Push.setBadge: ', activityBadgeCount);
                    }, (e) => {
                        console.log('Push.setApplicationIconBadgeNumber: Error', e.message);
                    }, activityBadgeCount);

just now , i Updated my phonegap-plugin-push to 2.0.0 but when i console.log(Push)

Push.push does not exist , any thoughts about this? where is it placed?

by the way i am importing Push from meteor/raix:push , Is this the cause?

**Comment by macdonst** [comment]
@PinkPanda17 Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
