### ISSUE TITLE
phonegap push plugin for IOS :  [{"error":"InvalidApnsCredential"}] : Please help

### ISSUE THREAD

**Issue by spdeepak92** [phonegap/phonegap-plugin-push#1946]
Uploaded APNs Authentication Key . 
My Token look like : dlrAl1Sm5HM:APA91bHcdwRsPTX67ucNi5qLldSyylOxeFn9JUWJMHEhmUvO4QHdGaXxWcvve4bnlXHVBqRw-Z0I9MlBVE5LP1Bs1tch5aMu......................dspf8de-PStjW
 
PUSH : 

    PushNotification.init({
            android: {
                senderID: "82....46911",
                sound: "true",
                vibrate: "true",
                forceShow: "true"
            },
            browser: {
                pushServiceURL: 'https://fcm.googleapis.com/fcm/send'
            },
            ios: {
                senderID: "82....46911",
                gcmSandbox: "true",
                alert: "true",
                badge: "true",
                sound: "true"
            },
            windows: {}
        });

**Comment by jcesarmobile** [comment]
Which plugin version are you using?

I think "Invalid credentials" message is pretty clear, you didn't upload your push certificates correctly to FCM/GCM

**Comment by spdeepak92** [comment]
uploaded both development and production certificate on FCM. 
My problem is , when i changed NOTIFICATION TO DATA on below file it successfully runs. 
OUTPUT : {"multicast_id":7286737411636881331,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1504871655462284%a69a7507f9fd7ecd"}]}

<?php
	define( 'API_ACCESS_KEY', 'AIzaSyB7pyO......tsoCU5df9c4' );
	
	
	$registrationIds = array("dlrAl1Sm5HM:APA91bH.......PStjW" );
	
	// prep the bundle
	$msg = array
	(
	    'message'       => 'here is a message. message',
	    'title'         => 'This is a title. title',
	    'subtitle'      => 'This is a subtitle. subtitle',
	    'tickerText'    => 'Ticker text here...Ticker text here...Ticker text here',
	    'vibrate'   => 1,
	    'sound'     => 1
	);
	
	$fields = array
	(
	    'registration_ids'  => $registrationIds,
	    'data'      => $msg
	);
	
	$headers = array
	(
	    'Authorization: key=' . API_ACCESS_KEY,
	    'Content-Type: application/json'
	);
	
	$ch = curl_init();
	curl_setopt( $ch,CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send' );
	curl_setopt( $ch,CURLOPT_POST, true );
	curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
	curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
	curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
	curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fields ) );
	$result = curl_exec($ch );
	curl_close( $ch );
	
	echo $result;

?>

ON NOTIFICATION : 

{"multicast_id":6683234922071643775,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"InvalidApnsCredential"}]}

**Comment by macdonst** [comment]
@spdeepak92 send this payload for an example to an iOS device running FCM:

```
{
    "registration_ids": ["my device id"],
    "notification": {
        "title": "My Title",
    	"body": "My message"
    },
    "priority": "high"
}
```

**Comment by spdeepak92** [comment]
@macdonst  Thanks for your reply. It solved.
But my main problem is that i didn't turned on PUSH NOTIFICATION in my XCODE and it works only when simulating my device through XCODE, not on phonegap app though
Thanks anyway
