### ISSUE TITLE
Phone gap plugin not working with clevertap plugin ..

### ISSUE THREAD

**Issue by coder-hunt** [phonegap/phonegap-plugin-push#1947]
We are using phonegap plugin to get the notfication data in ionic2 but there are some dependency issue that we are facing ,
The reason to use phonegap plugin because we want to render push notification to the specific page based on the data which we have passed from the clevertap notification .

Here is the errors :

 FAILURE: Build failed with an exception.
        
        * Where:
        Script '/var/www/html/jp_app/platforms/android/phonegap-plugin-push/app2-push.gradle' line: 38
        
        * What went wrong:
        A problem occurred evaluating root project 'android'.
        > Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
            > For input string: "+"
   
So there is any alternate to push notification in ionic frameworks(Hybrid) or any other suggestion to implement this ..

Thanks and Regards
Pushpendra Kumar

**Comment by macdonst** [comment]
@coder-hunt same root cause as #1718. Waiting for a cordova release so I can fix it.
