### ISSUE TITLE
iOS - Incorrect token from data.registrationId

### ISSUE THREAD

**Issue by AlexDag** [phonegap/phonegap-plugin-push#1948]
hi, I have strange issue for using push plugin on test platform>Testflight, HockeyApp.
Locally, from XCode , app runs well, but submitted to the test platforms data.registrationId returns another format of token.
Example:
from Xcode > f3d0136c55bc3554f5e027564f35bc2ab3c65c8d0279cedab6..
from Hockey/TestFligth>
fRBnckSevZg:APA91bG1QEf9VqZyuLJ3u98-xs5uhmYeX_hXM6...
dpKzb9GdQS0:APA91bEPRogB1wYZer3Zs3xC-LNeDGk-zuYQoo..

As result , PushNotifications did not receive by ios Clients.

Any advice , please?
thanks

**Comment by macdonst** [comment]
@AlexDag Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
