### ISSUE TITLE
Implement notification channels

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-plugin-push#1949]
### Expected Behaviour

Expect notifications to be displayed when your app targets sdk 26 (Android O)

### Actual Behaviour

Notification is not shown.

#### Steps to Reproduce 

Set your targetSdkVersion to 26, build your app and send a push notification.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 8.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

All

#### Cordova CLI version and cordova platform version

    cordova --version                                    # 7.0.1
    cordova platform version android          # 6.3.0-dev

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # 2.0.0

#### Sample Push Data Payload

```
{
    "data" : {
        "title": "Test Notification",
        "body": "This offer expires at 11:30 or whatever",
        "notId": 10,
        "surveyID": "ewtawgreg-gragrag-rgarhthgbad"
    }
}
```

#### Sample Code that illustrates the problem

```
var push = PushNotification.init({
	android: {
	},
    browser: {
        pushServiceURL: 'http://push.api.phonegap.com/v1/push'
    },
	ios: {
		alert: "true",
		badge: true,
		sound: 'false'
	},
	windows: {}
});
```

#### Logs taken while reproducing problem

N/A

**Comment by macdonst** [comment]
Started working on this. A bit of a PITA as there is not compat library for this right now.

**Comment by macdonst** [comment]
Currently in master and planned to be part of a 2.1.0 release. Update your SDK's to Android O everyone as you'll need it to build.

**Comment by fredgalvao** [comment]
I made some comments/regards on the commit itself. If/when you have the time to go through them, specially on the *channel attributes/constants* topic, we should update the type definition files accordingly for all that sweet typescript/ionic sugar.

**Comment by macdonst** [comment]
@fredgalvao okay I kinda feel like this one is done now. Lemme know if you see anything else. I've created a new issue for the .ts file update.
