### ISSUE TITLE
not getting notifications on the Android device

### ISSUE THREAD

**Issue by lucorn** [phonegap/phonegap-plugin-push#195]
Hi,

I am able to get the push notifications delivered to the app when the app is in the foreground. However, I don’t see any notification on my Android device when the app is in the background or closed. Do I need to set up certain permissions in order to get the notifications in the notification area for Android?

Thank you

**Comment by macdonst** [comment]
@lucorn You should see the notifications in Android notification shade when the app is in the background. All the permissions required should be setup when the plugin is installed.

**Comment by lucorn** [comment]
I confirm that I do get it when the app is in the background. However, I do not see any notification when the app is closed. Does the plugin unregisters upon app exit?

**Comment by macdonst** [comment]
@lucorn You are running into issue #167 please go +1 that issue and I'm closing this as a duplicate.
