### ISSUE TITLE
In android, the push.on('error', function(){}) won't be triggered if the device has no google service installed or has network problem for connecting to google server

### ISSUE THREAD

**Issue by xiaoaowanghu** [phonegap/phonegap-plugin-push#1952]
### Expected Behaviour
Will trigger the 'error' event when any error happened when init the PushNotification

### Actual Behaviour
No thing happend

### Reproduce Scenario (including but not limited to)
Paste some logs here:
For push plugin:
V/Push_Plugin( 7822): execute: data=[{"browser":{"pushServiceURL":"http:\/\/push.api.phonegap.com\/v1\/push"},"android":{},"ios":{"sound":"true","aler
t":"true","badge":"true"},"windows":{}}]
V/Push_Plugin( 7822): execute: jo={}
V/Push_Plugin( 7822): execute: senderID=647571745247
E/Push_Plugin( 7822): execute: Got IO Exception MISSING_INSTANCEID_SERVICE
D/Push_Plugin( 7822): no icon option
D/Push_Plugin( 7822): no iconColor option

For app log:
only got:
I/chromium( 7822): [INFO:CONSOLE(312)] "Error in Error callbackId: PushNotification1062511891 : ReferenceError: data is not defined", source: file:///android_asset/www/cordova.js (312)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
not only xiaomi oppo, I think the others should be the same.

#### Cordova CLI version and cordova platform version

    cordova --version                                 7.0.1
    cordova platform version android        6.2.3

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.0.0

#### Logs taken while reproducing problem:

For push plugin log:
V/Push_Plugin( 7822): execute: data=[{"browser":{"pushServiceURL":"http:\/\/push.api.phonegap.com\/v1\/push"},"android":{},"ios":{"sound":"true","aler
t":"true","badge":"true"},"windows":{}}]
V/Push_Plugin( 7822): execute: jo={}
V/Push_Plugin( 7822): execute: senderID=647571745247
E/Push_Plugin( 7822): execute: Got IO Exception MISSING_INSTANCEID_SERVICE
D/Push_Plugin( 7822): no icon option
D/Push_Plugin( 7822): no iconColor option

For app log:
only got:
I/chromium( 7822): [INFO:CONSOLE(312)] "Error in Error callbackId: PushNotification1062511891 : ReferenceError: data is not defined", source: file:///android_asset/www/cordova.js (312)

**Comment by xiaoaowanghu** [comment]
add the args parameter in cordova.js:
"callbackFromNative callbackId=PushNotification154804083 isSuccess=false status=9 args=["MISSING_INSTANCEID_SERVICE"]", source: file:///android_asset/www/cordova.js

**Comment by xiaoaowanghu** [comment]
hi macdonst, is there a way to fix it quickly? it's urgent for me. I'm not familiar with plugin coding, can you help to tell me which file(s) I can look into it for trying to fix.

**Comment by macdonst** [comment]
@xiaoaowanghu well it is hitting this line: https://github.com/phonegap/phonegap-plugin-push/blob/7d22655fe9de630ee75299f21135be76960c8cc2/src/android/com/adobe/phonegap/push/PushPlugin.java#L100 which is sending back an error to the push plugin. The error callback is registered here: https://github.com/phonegap/phonegap-plugin-push/blob/master/src/js/push.js#L67 and the implementation is here: https://github.com/phonegap/phonegap-plugin-push/blob/master/src/js/push.js#L60 and that should fire an error event.

**Comment by xiaoaowanghu** [comment]
Ha, I need to say sorry. It's not a bug of this plugin. It's a bug in my error event handler. Actually the first statement is to log the error, but I used the wrong viriable name. so the exception was thrown  up  to codovajs. And I didn't see the log so I thought the error event wasn't triggered. 

Thanks for your help, macdonst!
