### ISSUE TITLE
Blackberry Problem

### ISSUE THREAD

**Issue by wo-github** [phonegap/phonegap-plugin-push#1956]
We have Version 1.10.5 in our Android App and a Blackberry Device receive no Pushmessages.
Does someone know, if this Plugin works with Android on Blackberry?
We send the Pushmessage via node with this package
https://www.npmjs.com/package/node-gcm

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
