### ISSUE TITLE
PushNotification is not defined in some devices

### ISSUE THREAD

**Issue by ankurvr** [phonegap/phonegap-plugin-push#196]
I am using this plugin for push notification stuff.
But i am facing the issue which shown in screen shot below.
It's working fine on my android 5.1 device but not it 4.4 or 4.4+ devices.
In 4.4+ devices it's showing error which shown in screenshot.

Help will be appreciated
Thanks

![pushplugin](https://cloud.githubusercontent.com/assets/3338156/10263010/338d5682-69fc-11e5-9e02-01728eb3d679.png)

**Comment by macdonst** [comment]
@ankurvr So, none of the code in that stack trace has anything to do with the push plugin and I have no idea how you are including it in your project so I can't be of much help unless you give me a better idea of what is going on.

**Comment by ankurvr** [comment]
@macdonst Thanks for reply. This issue to resolved. It was not plugin issue. It was loading time and use time order issue. Sorry about this. You can close this issue.

**Comment by macdonst** [comment]
@ankurvr kk, thanks for responding.
