### ISSUE TITLE
Question: How to force to use APNS on IOS.

### ISSUE THREAD

**Issue by xiaoaowanghu** [phonegap/phonegap-plugin-push#1960]
Hi sir, I want to only use APNS on IOS. I searched the relative questions before, found your reply below:
"@miaowang I will not be forcing anyone on iOS to use FCM. It will be a configurable option just the way it is right now. So if your app isn't setup for FCM you'll get the old APNS registration ID. "

I want to know how to configure it to only use the APNS? And what does the "setup FCM" mean. Does it mean the app will ask the user to input a google account? If the user doesn't input, then the apple will use the APNS? Is there a way to use the APNS as default which don't need user to do anything.
Thanks.

**Comment by macdonst** [comment]
@xiaoaowanghu if you don't add the GoogleServices-Info.plist to your project the plugin will use APNS by default.
