### ISSUE TITLE
Ionic FCM plugin to display badge number on app icon

### ISSUE THREAD

**Issue by akhilsanker** [phonegap/phonegap-plugin-push#1964]
### Expected Behaviour
To show the number of unread received notification as the badge count on the app icon when new notification is received

### Actual Behaviour
Shows the badge count only after opening the notification,either tapping the notification from the tray if app in background or when notification is received in foreground

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung

#### Cordova CLI version and cordova platform version

    cordova --version             7.0.1
    cordova platform version android       6.2.3

#### Sample Code that illustrates the problem
  document.addEventListener('deviceready', function () {
  }, false);
     cordova.plugins.notification.badge.configure({ autoClear: true });
    var check_fcm_loaded = setInterval(function(){
      FCMPlugin.onNotification(function(data){
        cordova.plugins.notification.badge.set(data.badge); 
        cordova.plugins.notification.badge.configure({ autoClear: true });        
        if(data.wasTapped == true){
          alert( JSON.stringify(data) );
          cordova.plugins.notification.badge.configure({ autoClear: true });
        }else{
          alert( JSON.stringify(data) );
          cordova.plugins.notification.badge.clear();
        } 
      });
    }, 2000);

**Comment by macdonst** [comment]
@akhilsanker you are getting this plugin confused with:

https://github.com/fechanique/cordova-plugin-fcm
https://github.com/katzer/cordova-plugin-badge

This plugin has limited badge support using shortcutbadger as a dependency.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#badges
