### ISSUE TITLE
How to access PushNotification instance on other pages

### ISSUE THREAD

**Issue by yydmay** [phonegap/phonegap-plugin-push#1965]
This may not be related directly to the plugin itself, I am seeking advice on how to use the plugin in real world.
I have multi page Cordova app. On login page, I call var push = PushNotification.init to get a registration token; call push.on('notification', function(data)  to register event handlers, then I navigate to next page, all event handlers are lost. I'll need to register a new event hander for 'notification' event, now how do I access push instance without calling init function again?

**Comment by macdonst** [comment]
@yydmay don't navigate to new pages. It gets around the exact problem you are running into when all of your JS is removed from memory. Look into the single page architecture pattern.
