### ISSUE TITLE
App not receive notification when app killed on iOS

### ISSUE THREAD

**Issue by Spillo17** [phonegap/phonegap-plugin-push#1966]
I'm able to receive notification when app is in foreground and background and I can get custom data from notification.

When I kill the app, I receive the banner with notification title and message but the app don't receive it and I unable to get my custom data in the notification, after killing also on background stop working correctly.

But if I click on notification banner data are correctly got, in app killed and backgorund.

I've devices with iOS 11 and iOS 10.3 the problem is same in both versions.

#### Cordova CLI version and cordova platform version

7.0.1 & 4.4.0

#### Plugin version

1.10.5

#### Sample Push Data Payload

```
{
    "notification": {
        "title": "title",
        "body": "message",
        "content-available": 1
    },
    "content_available": true,
    "data": {
        "parmas1": "params1",
        "parmas2": "params2"
    },
    "registration_ids": ["reg-id"]
}
```

**Comment by uj** [comment]
That is expected behavior.  If the app is killed, it will no longer respond to push notifications.  The OS itself will still display the notifications, but your app will not receive them because it is not running.  That is how IOS works.  Also, that is documented somewhere around here.

**Comment by macdonst** [comment]
@Spillo17 sorry, if you force quit the app then there is no web view to run the JS and handle your notification. This is the expected behaviour.

**Comment by Spillo17** [comment]
You don't understand if I kill the app, and when I reopen the app notification doesn't work even if app is in background, it was working before 10.3..

**Comment by pluzmedia** [comment]
@uj i don't kill app but OS is killing the app after idle

**Comment by leandroz** [comment]
@macdonst you are wrong, if the implementation is correctly done, iOS will wake your application and allow you to run Javascript, check a plugin like: https://github.com/transistorsoft/cordova-background-geolocation-lt

**Comment by leandroz** [comment]
@uj yes a callback is executed with the location and you have some time to complete the background task and then it goes out again.

Apart from that, maybe storing the notification on sqlite or similar and then making it available the next time the app is opened?

**Comment by uj** [comment]
@leandroz Ok, i see what you are referring to now.  However, that is specific for geofencing at the core OS level.  So, for this method to work with other plugins, they would also have to use geofencing in that same manner to get the app to restart, right?

**Comment by uj** [comment]
@pluzmedia ios should not be killing your app after idle, that doesn't make sense.  Is it possible that you are running past 30 seconds with background tasks or not calling finish()?

**Comment by leandroz** [comment]
@uj the OS has the right to kill an app that is in the background if it needs resources, so your app can be killed at anytime. You don't need geofencing but background tasks, that way you are will be started to run the background task, in this case it would be to store the notification on sqlite. It needs to be done on native because even though you can run Javascript, you can't use plugins as device ready won't fire.
