### ISSUE TITLE
I can not get the record (key) for some IOS

### ISSUE THREAD

**Issue by deluxeuo** [phonegap/phonegap-plugin-push#197]
Some IOS versions in production I can not get (RegistrationId), my IOS 8.1 does not work, but rather in 8.4. The Way implements the push affect me?

I'm doing well

onDeviceReady: function () {
    
    networkState checkConnection = var ();
    
    if (networkState == Connection.NONE) {
        showAlert ();
    }
    else {
        
        var push PushNotification.init = ({
                                         "android": {
                                         "SenderID": "1111"
                                         },
                                         "ios": {"alert": "true", "badge", "true", "sound": "true"},
                                         "windows": {}
                                         });
        
        push.on ('registration', function (data) {
                keyFoodTruck = data.registrationId;
                savePush (keyFood);
                });
        
    }
}
};

It's correct?

What is the key difference in the console
example:

Central [1060: 268 303] Push Plugin register success: <89c4d141 57d8fcc5 75,910,711 9f6325a9 f11e5d77 ede81e73 26d2a224 d0c48da9>

For the key that pushplugin returns?

My SenderID and GCM google, it interfere?

**Comment by macdonst** [comment]
@deluxeuo No, the sender ID from the Android side will not interfere with iOS. The iOS code never reads the Android options object. To clarify, you are using the same code and on 8.1 you don't get the registration ID but on 8.4 you do?

**Comment by deluxeuo** [comment]
Exactly. The same code in some IOS work others do not. My IOS 8.1 and is not working, and working in 8.4, 9.02 as work ..

**Comment by patuku-roy** [comment]
@macdonst I have similar problem with @deluxeuo ... I'm lucky, the first time triggering `init` function, my iphone asking for permission. After that, all `data` parameter pass to success callback is `undefined` and the plugin never asking the permission anymore even I removed the app from my iphone. Any idea about this? I'm using iphone 5 and iOS 8.4.1

**Comment by macdonst** [comment]
I have no way of reproducing this issue so if anyone has a 8.1 device kicking around help would be appreciated.

**Comment by macdonst** [comment]
Closing, inactivity. Also, we are up to iOS 11.3 now so support 8.1 is not longer required.
