### ISSUE TITLE
No custom sound plays when notification is forced in foreground.

### ISSUE THREAD

**Issue by SharUpOff** [phonegap/phonegap-plugin-push#1970]
### Expected Behaviour

Notification sound specified in Payload plays when activity is in foreground and notification is received.

### Actual Behaviour

Default system notification sound plays when notification is forced in foreground.

#### Steps to Reproduce

1. Create cordova application with phonegap-plugin-push.
    
    ```bash
    cordova plugin add phonegap-plugin-push
    ````

2. Enable sound and forceShow options:

    ```javascript
    PushNotification.init({
        android: {
            sound: true,
            forceShow: true
        }
    });
    ```

2. Add custom notification sound:
    
    ```xml
    <platform name="android">
        <resource-file src="res/raw/custom.wav" target="res/raw/custom.wav" />
    </platform>
    ```

3. Run app, leave it in foreground then send notification:

    According to [fcm documentation](https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support):
    
    ```json
    {
        "title": "Sound",
        "body": "Custom",
        "sound": "custom"
    }
    ```

#### Platform and Version

- Android 4.2.2
- Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

- Sony

#### Cordova CLI version and cordova platform version

cordova
- 7.0.1

Installed platforms:
- android 6.2.3

#### Plugin version

phonegap-plugin-push 2.0.0 "PushPlugin"

#### Sample Push Data Payload

According to [fcm documentation](https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support):

```json
{
    "title": "Sound",
    "body": "Custom",
    "sound": "custom"
}
```

#### Sample Code that illustrates the problem

```javascript
PushNotification.init({
    android: {
        sound: true,
        forceShow: true
    }
});
```
#### Logs taken while reproducing problem

```java
D/Push_FCMService(*): onMessage - from: ************
D/Push_FCMService(*): normalize extras
D/Push_FCMService(*): key = message
D/Push_FCMService(*): replace key message with message
D/Push_FCMService(*): no locale found for key = message, error Value Custom of type java.lang.String cannot be converted to JSONObject
D/Push_FCMService(*): key = title
D/Push_FCMService(*): replace key title with title
D/Push_FCMService(*): no locale found for key = title, error Value Sound of type java.lang.String cannot be converted to JSONObject
D/Push_FCMService(*): foreground force
D/Push_FCMService(*): message =[Custom]
D/Push_FCMService(*): title =[Sound]
D/Push_FCMService(*): contentAvailable =[null]
D/Push_FCMService(*): forceStart =[null]
D/Push_FCMService(*): create notification
E/Push_FCMService(*): Number format exception - Error parsing notId: Invalid int: "null"
D/Push_FCMService(*): stored icon=null
D/Push_FCMService(*): stored iconColor=null
D/Push_FCMService(*): stored sound=true
D/Push_FCMService(*): stored vibrate=true
D/Push_FCMService(*): no icon resource found - using application icon
D/Push_FCMService(*): create actions: with in-line
```

**Comment by macdonst** [comment]
Currently fixed in master, soon to be in release 2.1.0.

**Comment by ChrisCosy** [comment]
Hello,

playing custom sounds works well for me. But how can I play android system sounds with the fcm plugin  ? I picked up the path from a tone via pickRingtone, but when I receive the push it does not play.

Thanks

**Comment by jmrvm801** [comment]
Hi,

I can't add customs sounds because when I build the app, doesn't add the res/raw/test.wav to the apk. 

Here is my config.xml
<platform name="android">
		<resource-file src="res/raw/test.wav" target="res/raw/test.wav" />
	</platform>

I just add custom.wav into project/res/raw/test.wav and project/www/res/raw/test.wav and nothing happend. Any idea? Thank you

**Comment by jmrvm801** [comment]
@ChrisCosy  Here is the official documentation about firebase: https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support

**Comment by macdonst** [comment]
@jmrvm801 if you are using cordova-android 7.0 or greater the path has changed, for instance:

```
<resource-file src="ack.mp3" target="app/src/main/res/raw/ack.mp3" />
```
