### ISSUE TITLE
Unsubscribe from topic duplicated action

### ISSUE THREAD

**Issue by Chuckytuh** [phonegap/phonegap-plugin-push#1973]
### Expected Behaviour
Only one call to `FirebaseMessaging.getInstance().unsubscribeFromTopic(topic);`
### Actual Behaviour

`FirebaseMessaging.getInstance().unsubscribeFromTopic(topic);` is being called twice when unsubscribing a topic.

**Comment by macdonst** [comment]
Currently fixed in master, soon to be in release 2.1.0.
