### ISSUE TITLE
Windows 10 toast notification args not correcly set

### ISSUE THREAD

**Issue by giuseppelt** [phonegap/phonegap-plugin-push#1975]
I created a pull request to fix this

### Expected Behaviour
Launch args populated

### Actual Behaviour
No data set for launch args

### Reproduce Scenario (including but not limited to)
Just receiving a toast

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Windows 10

#### Plugin version
2.0.0

**Comment by macdonst** [comment]
Currently fixed in master, soon to be in release 2.1.0.
