### ISSUE TITLE
Get GCM Id in Android but not FCM in iOS

### ISSUE THREAD

**Issue by ncampuzano** [phonegap/phonegap-plugin-push#1982]
### Expected Behaviour
When I'm in iOS app I want the .on('notification') event return Push Plugin register and when I'm in Android get GCM Id as normally.

I get with this event this token:
`FCM Registration Token: cqs2H3ED5u8:APA91bEVQGi0SfbC1Yau1xN_PJB0SOmB50PgHMNG2zCqw4bzWfLruXfqKoIT7DeJnz5K37CqQLIs9F-CXfwurC-UhZjfLNUvnEfCZDpIleW_6xGZYZKokNcIPouGHdvdSnVMhHu6mITh`

But I want 
`Push Plugin register success: <5c27c9a8 87e28030 735f8bc7 e27ab8de e6d6538f c9759e70 26c306a6 fa0ac2cc>` 
This token

### Actual Behaviour
In Android and iOS I get GCM and FCM register respectively
#### Cordova CLI version and cordova platform version

    cordova --version                                    7.0.1
    cordova platform version android                     6.2.3

#### Plugin version
phonegap-plugin-push   2.0.0

**Comment by macdonst** [comment]
@ncampuzano I don't understand your question. Do you mean you want to use APNS on iOS but you are getting a FCM token?

**Comment by ncampuzano** [comment]
Yes! I see in the Xcode log theses tokens, but in the .on(‘registration’) I only get FCM token, my issue is similar to #1714

**Comment by macdonst** [comment]
@ncampuzano do you want to send to iOS using APNS or FCM?

**Comment by ncampuzano** [comment]
To iOS I need APNS

**Comment by macdonst** [comment]
@ncampuzano right, so don't deliver the `GoogleService-Info.plist` on iOS and it will default to APNS.

**Comment by ncampuzano** [comment]
But if I’m only remove GoogleService-Info.plist but google-service.json it’s keeps, in Android he use FCM and in Apple use APNS?

**Comment by macdonst** [comment]
@ncampuzano I updated the docs to make it more clear. 

Yes, when you remove the GoogleService-Info.plist from iOS it uses APNS but as long as you keep delivering google-service.json it uses FCM. Actually, Android won't work without the google-service.json file.

You will probably have to remove the ios platform and add it again. There is a bug in cordova-ios that doesn't remove resource files correctly.

**Comment by ncampuzano** [comment]
It's perfect. Removing GoogleService-Info.plist use iOS APNS. Close it 👍

**Comment by kyale-mwendwa** [comment]
if i remove GoogleService-Info.plist from the path 'platform/ios/app/resources/resources/' it will not build as it looks for that file. So how do i go about your suggested solution ?

**Comment by ncampuzano** [comment]
But you removed the reference to GoogleService-Info.plist on Config.xml?
