### ISSUE TITLE
Notification not showing on Samsung S8+

### ISSUE THREAD

**Issue by yohio** [phonegap/phonegap-plugin-push#1985]
### Expected Behaviour
Using the meteor method to trigger a push notification works on multiple Android devices that run version 6 and 7 without any issue.
Meteor Method called -> notification generated on the web server -> notification appears on the user when the app is active/in the background/swiped off of the active app.

The expectation is that the notification will appear in all life-cycles of the app except when the app is force-killed/stopped which then nothing should happen

#### Steps to Reproduce 
Running the method fires the notification and all devices iOS (version 10 and below) or Android (version 6 and 7) work fine with the exception of a single device which is the Samsung S8+ that is running version 7.0 with Samsung Experience version 8.1, that device doesn't get the notification in all the life-cycles stated above (app is active or in the background).
Google is claiming the notification was sent successfully.
Trying to turn off the battery optimization on the app and all other settings that might block this resulted in failure to receive the push notification

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Using MeteorJS for the server and web-service, OnsenUI + React for mobile app, Raix:push (latest) which uses phonegap-plugin-push@1.6.4 
Android 7.0 with Samsung Experience version 8.1 on the Samsung S8+

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung S8+

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.4.0
    cordova platform version android                    6.1.1

#### Plugin version

    cordova plugin version 1.6.4

**Comment by macdonst** [comment]
@yohio I don't have that device so it's going to be hard for me to test. Can you get some logs from the device? As well what is your push payload? Finally, that's a pretty old version of the plugin to be using on Android 7.

**Comment by yohio** [comment]
@macdonst thanks for the quick reply, for the payload we use this `Push.send({ 
            from, 
            query, 
            payload: { 
                priority: 'high',        
                link 
            }, 
            text: cleanMessage, 
            title, 
            "force-start":1, 
            "content-available":1
        });` as for the plugin version we are using that version because we are building on Meteor and using the [raix:push](https://github.com/raix/push) Meteor package which has a dependency on the 1.6.4 (although I've seen some comments here and there that shows it is supporting the 1.8.2 version. 
I'll try to get some logs from the device and post them here one I get those.
Thanks!

**Comment by macdonst** [comment]
@yohio yeah, I'd need to see some logs from the device.

**Comment by yohio** [comment]
@macdonst, we just tested on another Samsung S8, this time push notification was received, we are going to continue looking and trying to find what is the underline cause of this, once we have a better idea of a replication process that works on specific devices or events we will create another issue. 
Thanks!

**Comment by macdonst** [comment]
@yohio okay, I'll close this for now.
