### ISSUE TITLE
FCM Sender ID (null)

### ISSUE THREAD

**Issue by 1N50MN14** [phonegap/phonegap-plugin-push#1986]
### Expected Behaviour
`GoogleService-Info.plist` is correctly placed in the root folder, `<resource-file src="GoogleService-Info.plist" />` is correctly placed under the iOS platform. The plugin is expected to use FCM.

### Actual Behaviour
Uses APNS instead

#### Steps to Reproduce 
Install the plugin and follow the instructions ;)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 11

#### Cordova CLI version and cordova platform version
Cordova 7.01

#### Plugin version
Github latest (2.0.0)

#### Logs taken while reproducing problem
2017-10-01 02:02:18.849202+0200 APP[1185:294928] FCM Sender ID (null)
2017-10-01 02:02:18.849241+0200 APP[1185:294928] Using APNS Notification

My push config:
```javascript
  var push = PushNotification.init({
      "android": {
        "senderID": senderId
      },
      "ios": {
        "gcmSandbox": false, //also attempted setting this to true, as well as use fcmSandbox
        "alert": true,
        "badge": true,
        "sound": true
      }
  });
```

**Comment by speedfl** [comment]
For your issue try to put in your config : 
```
<resource-file src="GoogleService-Info.plist" target="GoogleService-Info.plist"/>
```

**Comment by 1N50MN14** [comment]
@speedfl I have that correctly set as mentioned in the issue description

**Comment by speedfl** [comment]
Yes but I had this issue as well. I was missing the ```target``` part

**Comment by speedfl** [comment]
Then don't put senderID as it is deprecated in 2.0.0

**Comment by 1N50MN14** [comment]
I'm not using it for iOS :)

**Comment by macdonst** [comment]
@1N50MN14 do you see the GoogleService-Info.plist file in your `platforms/ios` folder? Does it included a FCM Sender ID? What version of cordova-ios are you using?

**Comment by 1N50MN14** [comment]
@macdonst I'm using cordova-ios `4.5.1`, yes I do have GoogleService-Info.plist properly located under `platforms/ios`, I wonder if I should attempt to re-add the platform...

**Comment by 1N50MN14** [comment]
@macdonst Ok re-adding iOS seemed to have solved this issue.. only thing now is that push notifications are not arriving, no errors or logs from xcode, payload is correct...

**Comment by 1N50MN14** [comment]
@macdonst Ok I think I figured it out, it's FCM data messages which are not arriving.. push messages arrive correctly

**Comment by macdonst** [comment]
@1N50MN14 yeah, that's documented here: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#gcm-and-additional-data

**Comment by 1N50MN14** [comment]
@macdonst Yeah I think my issue is different because I'm sending a *data only* FCM message without the notification attribute, following https://firebase.google.com/docs/cloud-messaging/concept-options#data_messages, the payload is correct but the plugin is not intercepting it...

**Comment by 1N50MN14** [comment]
@macdonst Yup, I can confirm this is the case, if you send a sample payload:
```javascript
{
   "to" : "XXX",
   "data" : {
     "foo" : "bar",
     }
 }
```
It won't arrive the device, however, if you add the `notification` attribute then it's treated as push message and arrives as expected.

**Comment by macdonst** [comment]
@1N50MN14 when sending to Android use `data` and to iOS use `notification` when going over FCM.

**Comment by 1N50MN14** [comment]
@macdonst Sorry for my naive question, I'm using FCM on both Android and iOS. How does the plugin, on either platform, distinguish between a notification message and a data message? In the case of data messages I'm using that to send some information to the app which I do not wish to notify the user of.

**Comment by 1N50MN14** [comment]
(notification & data messages as in FCM terms)
