### ISSUE TITLE
ionic v3.9.2 build fail

### ISSUE THREAD

**Issue by THEDOWNCOUNTRY** [phonegap/phonegap-plugin-push#1987]
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_1pnsrt2e6ek8d478clgl49vpx.run(C:\Pearl\KV\RIDERDEMO\platforms\android\build.gradle:140)

BUILD FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Pearl\KV\RIDERDEMO\platforms\android\phonegap-plugin-push\kapvoom-push.gradle' line: 38

* What went wrong:
A problem occurred evaluating root project 'android'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Total time: 10.661 secs
Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script 'C:\Pearl\KV\RIDERDEMO\platforms\android\phonegap-plugin-push\kapvoom-push.gradle' line: 38

* What went wrong:
A problem occurred evaluating root project 'android'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

[ERROR] An error occurred while running cordova run android (exit code 1).

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
