### ISSUE TITLE
IOS problems receiving notificarions, how to resolve

### ISSUE THREAD

**Issue by edudesouza** [phonegap/phonegap-plugin-push#1990]
Sorry to not follow the template, but I think posting here I will help others that got the same problem as me.

This is a cake recipe, follow step by step, otherwise the cake will not cook as expected.

1 ... Apple developer
Go to Identifiers, click in the desired App, click edit and setp up Development SSL Certificate and Production SSL Certificate
Go to  Keys, click in All, generate a .p8 cerificate

2 ... Firebase
Go to Configuration, Add new App, upload you .p8 certificate
Download the GoogleService-Info.plist and put it on the www folder (I am compiling with PhoneGap Build on the cloud)

Note: I my case, if I generate the .p8 certificate without having set dev and prod certificates, nothing happens

3 ... The App side
Must have: `<resource-file src="GoogleService-Info.plist" />` on the config.xml under `<platform name="ios">`

Must have: `<variable name="SENDER_ID" value="X:XXXXXXX:ios:XXXXXXX" />`under `<plugin name="phonegap-plugin-push" spec="~1.10.0">` on the config.xml

Check the plugin folder: fetch.json must have: 
```
"phonegap-plugin-push": {
        "source": {
            "type": "registry",
            "id": "phonegap-plugin-push@^2.0.0"
        },
        "is_top_level": true,
        "variables": {}
    }
```

Also in plugin folder, must have ios.json, and inside it must have:

```
"installed_plugins": {
... some plugins, and
        "phonegap-plugin-push": {
            "PACKAGE_NAME": "com.omc.app"
        }
    },
```

The trick part ... in your index file:

```
var push = PushNotification.init({
"android": {"senderID": "692263627680", icon : "icon"},
"ios":  {"senderID": "692263627680", "sound": true,"alert": true,"badge": true, gcmSandbox: true}
});
```

senderID, must have!
gcmSandbox: true, this is the trick part, since you are testing, probably you are compiling an app with a development certificate.

If you are using a dev certificate, you must have set up  a APN with dev certificate, and also must register your user on Firebase as a dev, using gcmSandbox: true

Other wise your app will register the user on Firebase to be called in the production environment.

This is the case when you got the registrationid but when sending a message you got Not Registered. In this scenario you are sending a message to someone on the prod APN .... daaaah, it took me weeks to discover.

On the server side (php, in my case), sending a message:

```
$fields = array(
    'notification' => array(
        "title"=>"1234",
        "body"=>"1234",
        "force-start" => 1,
        "content-available"=>1
    ),
    'to'=>$registration_id,
    'priority'=>'high',
    'restricted_package_name'=>'com.omc.app'    
);
```

Try this recipe, and sleep well, Cheers!

**Comment by macdonst** [comment]
@edudesouza if you think you can help improve the docs then please send a PR. There are a few issues with what I see above though. For instance if you are using version 2.0.0 of the plugin there is no need to add:

```
<variable name="SENDER_ID" value="X:XXXXXXX:ios:XXXXXXX" />
```

In 2.0.0 it will read the sender ID from the `GoogleService-Info.plist` file.

It seems like you have confused the 1.10.0 and 2.0.0 plugin instructions. The instructions on how to install a 1.10.0 version are available at: https://github.com/phonegap/phonegap-plugin-push/blob/v1.x/docs/INSTALLATION.md

**Comment by edudesouza** [comment]
Just an update, my app got publish on App Store, everything working as a charm ...
The only change I did was:
```
var push = PushNotification.init({
"android": {"senderID": "692263627680", icon : "icon"},
"ios":  {"senderID": "692263627680", "sound": true,"alert": true,"badge": true, gcmSandbox: false}
});
```

**Comment by RizwanZaheer** [comment]
Hi @edudesouza,
Where I put this code because When I put this code in app.js file and then build using phonegap cloud build. App is Successfully install on device but in log it shows me *PushNotification* is not defined but still getting the static test push Notification from Firebase. What I'm doing wrong? 
or how I can handle this plugin Api using own logic?
 
 ```
var push = PushNotification.init({
    android: {
      senderID: 665717578642
    },
    ios: {
      senderID: 692263627680, sound: true, alert: true, badge: true
    }
  });
```

**Comment by edudesouza** [comment]
Put that on your index file, just after
document.addEventListener('deviceready', function (){ ...
