### ISSUE TITLE
Do notifications on Kindle Fire FireOS work? (in my case, no)

### ISSUE THREAD

**Issue by viking2917** [phonegap/phonegap-plugin-push#1991]
### Expected Behaviour

Notifications should fire on Kindle Fire OS. (I do not know if the FireOS platform is supported or not - the documentation isn't entirely clear on this point). I use the Firebase Cloud Messaging SenderID on Android. It's not clear from the documentation whether any additional steps are required for FireOS, or whether it will even work.

### Actual Behaviour

I have an app that does notifications quite well on iOS and Android devices. When I try it on a Kindle Fire device, when the register function is called, it never returns, e.g. in the following code block, no console statement in any branch below is printed.

```
$cordovaPushV5.register()
    .catch(function(response){
	console.log('push register - failed!'); 
    })
	.then(function(registrationId) {   // register to get registrationId
	    console.log('register returned');
	}, function (err) {
	    console.log("Register error " + err);
	});
```

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Amazon Kindle Fire HDX 8.9 (4th Generation), FIreOS 5.3.3.0

#### Cordova CLI version and cordova platform version
cordova --version  
7.0.1

cordova platform version android  
Installed platforms:
  android 6.2.3
  ios 4.4.0
Available platforms: 
  blackberry10 ~3.8.0 (deprecated)
  browser ~4.1.0
  osx ~4.0.1
  webos ~3.7.0

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version
cordova plugin version | grep phonegap-plugin-push
phonegap-plugin-push 1.10.4 "PushPlugin"

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

#### Logs taken while reproducing problem
Attached is an android log file. Two things that caught my eye:
```

I/com.amazon.identity.auth.device.appid.AbstractAppIdentifier(11053): Finding API Key for com.ionicframework.<myapp>
D/VendorDisplayManagerGlobalCallback(11335): callGetInstance: nil
I/com.amazon.identity.auth.device.utils.ThirdPartyResourceParser(11053): Unable to get api key asset document: api_key.txt
W/com.amazon.identity.auth.device.utils.ThirdPartyResourceParser(11053): Unable to get API Key from Assests
I/com.amazon.identity.auth.device.utils.ThirdPartyResourceParser(11053): Attempting to parse API Key from meta data in Android manifest
I/com.amazon.identity.auth.device.utils.ThirdPartyResourceParser(11053): Attempting to parse API Key from meta data in Android manifest
I/com.amazon.identity.auth.device.appid.APIKeyDecoder(11053): Begin decoding API Key for packageName=com.ionicframework.bookship
D/com.amazon.identity.auth.device.appid.APIKeyDecoder.PII(11053): ApiKey/PackageName is null. pkg=com.ionicframework.<myapp>:<obscured>
W/com.amazon.identity.auth.device.appid.APIKeyDecoder(11053): Unable to decode APIKEy for pkg=com.ionicframework.<myapp>
```

and

```
V/Push_Plugin(10934): execute: action=init
V/Push_Plugin(10934): execute: data=[{"android":{"senderID":"440123924572"},"ios":{"alert":"true","badge":"true","sound":"true"},"windows":{}}]
V/Push_Plugin(10934): execute: jo={"senderID":"440123924572"}
V/Push_Plugin(10934): execute: senderID=440123924572
D/SystemWebChromeClient(10934): http://192.168.1.145:8101/: Line 28 : push initialization done
I/chromium(10934): [INFO:CONSOLE(28)] "push initialization done"
W/InstanceID/Rpc(10934): Failed to resolve IID implementation package, falling back
W/PackageManager( 1619): com.google.android.gms is not installed for user 0
W/InstanceID/Rpc(10934): Google Play services is missing, unable to get tokens
E/Push_Plugin(10934): execute: Got JSON Exception MISSING_INSTANCEID_SERVICE
D/Push_Plugin(10934): no icon option
D/Push_Plugin(10934): no iconColor option

```

Suggests that perhaps this Plugin won't work on FireOS, as potential Google libraries are missing? But I am not quite sure....

[FireFail.log](https://github.com/phonegap/phonegap-plugin-push/files/1349818/FireFail.log)

**Comment by macdonst** [comment]
@viking2917 your FireOS doesn't have Google Play Services installed and that's the root of the problem.

```
W/InstanceID/Rpc(10934): Google Play services is missing, unable to get tokens
```

**Comment by viking2917** [comment]
@macdonst Thank you Simon! Is it your understanding that is normal for FireOS? I see that there is a  cordova plugin that installs the services, suggesting it's normal they are not installed and some other means are necessary. Is there a particular reason not to just use the plugin, if you have experience in this area?

**Comment by viking2917** [comment]
Actually @macdonst thanks for your help again, but never mind my question for now. I will go do my homework about the best way to install the services.

**Comment by viking2917** [comment]
so, @macdonst, for clarity - is FireOS supported in this plugin as a matter of policy, or no? (i.e if I manage to get Google Play Services installed on a FireOS device will it work?) I'm having trouble figuring out how to get the services onto the device via my app, and if it's simply not going to work in general, it might be worth a note in the platforms section that while Android is Supported, FireOS is not).

Thanks for your help!
