### ISSUE TITLE
Unresolved Merge Conflict in master branch

### ISSUE THREAD

**Issue by olastor** [phonegap/phonegap-plugin-push#1994]
I accidently found it at https://github.com/phonegap/phonegap-plugin-push/blob/master/src/android/com/adobe/phonegap/push/FCMService.java#L636 . I thought this might not be intended to be there and just wanted to let you know if so.

**Comment by macdonst** [comment]
@olastor thanks, I appreciate the heads up. I've switched over to VS Code and I messed up on a merge.
