### ISSUE TITLE
My app is background(i am using other apps other wise nothing) then GCM come but i am clicking on this GCM notification icon then can't be open application please help me. App is kill that time came GCM and click on this App is opened

### ISSUE THREAD

**Issue by rajapurerajv** [phonegap/phonegap-plugin-push#1995]
My app is background(i am using other apps other wise nothing) then GCM come but i am clicking on this GCM notification icon then can;t be open application please help me

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by rajapurerajv** [comment]
thank you. prbome is solved :)
