### ISSUE TITLE
Can't compile 

### ISSUE THREAD

**Issue by juanredondo** [phonegap/phonegap-plugin-push#1997]
### Expected Behaviour
Compile
### Actual Behaviour
Error

Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\Users\jredondo\Source\NMT.BaresCuenca\NMT.BaresCuenca\platforms\android\src\com\adobe\phonegap\push\FCMService.java:5: error: cannot find symbol
import android.app.NotificationChannel;
                  ^
  symbol:   class NotificationChannel
  location: package android.app
C:\Users\jredondo\Source\NMT.BaresCuenca\NMT.BaresCuenca\platforms\android\src\com\adobe\phonegap\push\PushPlugin.java:5: error: cannot find symbol
import android.app.NotificationChannel;
                  ^
  symbol:   class NotificationChannel
  location: package android.app
C:\Users\jredondo\Source\NMT.BaresCuenca\NMT.BaresCuenca\platforms\android\src\com\adobe\phonegap\push\FCMService.java:383: error: cannot find symbol
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                                                    ^
  symbol:   variable O
  location: class VERSION_CODES
C:\Users\jredondo\Source\NMT.BaresCuenca\NMT.BaresCuenca\platforms\android\src\com\adobe\phonegap\push\FCMService.java:390: error: cannot find symbol
        List<NotificationChannel> channels = mNotificationManager.getNotificationChannels();
             ^
  symbol:   class NotificationChannel
  location: class FCMService
C:\Users\jredondo\Source\NMT.BaresCuenca\NMT.BaresCuenca\platforms\android\src\com\adobe\phonegap\push\FCMService.java:390: error: cannot find symbol
        List<NotificationChannel> channels = mNotificationManager.getNotificationChannels();
                                                                 ^
  symbol:   method getNotificationChannels()
  location: variable mNotificationManager of type NotificationManager
C:\Users\jredondo\Source\NMT.BaresCuenca\NMT.BaresCuenca\platforms\android\src\com\adobe\phonegap\push\PushPlugin.java:60: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                                                        ^
  symbol:   variable O
  location: class VERSION_CODES
C:\Users\jredondo\Source\NMT.BaresCuenca\NMT.BaresCuenca\platforms\android\src\com\adobe\phonegap\push\PushPlugin.java:96: error: cannot find symbol
                NotificationChannel mChannel =
                ^
  symbol:   class NotificationChannel
  location: class PushPlugin
C:\Users\jredondo\Source\NMT.BaresCuenca\NMT.BaresCuenca\platforms\android\src\com\adobe\phonegap\push\PushPlugin.java:97: error: cannot find symbol
                        new NotificationChannel(getApplicationContext().getPackageName() + DEFAULT_CHANNEL_ID,
                            ^
  symbol:   class NotificationChannel
  location: class PushPlugin
C:\Users\jredondo\Source\NMT.BaresCuenca\NMT.BaresCuenca\platforms\android\src\com\adobe\phonegap\push\PushPlugin.java:107: error: cannot find symbol
        notificationManager.deleteNotificationChannel(getApplicationContext().getPackageName() + channel.getString(CHANNEL_ID));
                           ^
  symbol:   method deleteNotificationChannel(String)
  location: variable notificationManager of type NotificationManager
C:\Users\jredondo\Source\NMT.BaresCuenca\NMT.BaresCuenca\platforms\android\src\com\adobe\phonegap\push\PushPlugin.java:113: error: cannot find symbol
        NotificationChannel mChannel = new NotificationChannel(packageName + channel.getString(CHANNEL_ID),
        ^
  symbol:   class NotificationChannel
  location: class PushPlugin
C:\Users\jredondo\Source\NMT.BaresCuenca\NMT.BaresCuenca\platforms\android\src\com\adobe\phonegap\push\PushPlugin.java:113: error: cannot find symbol
        NotificationChannel mChannel = new NotificationChannel(packageName + channel.getString(CHANNEL_ID),
                                           ^
  symbol:   class NotificationChannel
  location: class PushPlugin
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
11 errors

FAILURE: Build failed with an exception.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.0
#### Cordova CLI version and cordova platform version

    cordova --version                                    7.0.1
    cordova platform version android          6.2.2

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.0.0

**Comment by macdonst** [comment]
@juanredondo if you are building from `master` you will need to have the Android N SDK installed.

**Comment by Hirbod** [comment]
@macdonst I have installed Android N (24) and up, but I also receive this error.

**Comment by juanredondo** [comment]
I have to install the last  Android SDK, build  and build-tools ,  remove
the plataform and add It again, in order to compile

**Comment by mayurm-virtueinfo** [comment]
I am having the same issue with Android-0 Phonegap-push-plugin.
Another issues is that in FCMService.java, onMessageReceived is called multiple time in only Android-8 while in other os like Naught(7), Marshmallow(6) working fine.
Here is the link of my stack question : https://stackoverflow.com/questions/43275049/marshmallow-6-0-1-onmessagereceived-called-multiple-times.

I have also opened the with in Phonegap-push-plugin with Seemon McDonald : #2143.
But i didnot find any solution yet.
