### ISSUE TITLE
Impossible to build ios application

### ISSUE THREAD

**Issue by ahar** [phonegap/phonegap-plugin-push#1999]
### Expected Behaviour
Build application through xCode after successful archiving using cordova.
### Actual Behaviour
iOS Build fails. Android works fine
### Reproduce Scenario (including but not limited to)
Try to build iOS application.
#### Steps to Reproduce 
try to build using cordova: 
cordova clean ios && cordova build ios --debug --device -d --buildConfig=build.json
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ios@4.4.0
android@6.2.3

#### Cordova CLI version and cordova platform version

    cordova --version    7.0.1                                # e.g. 6.0.0
    cordova platform version android       6.2.3              # e.g. 4.1.1
    cordova platform version ios       4.4.0              # e.g. 4.1.1

#### Plugin version
    cordova plugin version | grep phonegap-plugin-push 1.10.4, 1.10.5  # e.g. 1.5.3

#### Logs taken while reproducing problem

ourProjectName Group
Deprecations Group
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-actionsheet/ActionSheet.h:7:31: 'UIActionSheet' is deprecated: first deprecated in iOS 8.3 - UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-actionsheet/ActionSheet.m:177:22: 'UIActionSheet' is deprecated: first deprecated in iOS 8.3 - UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-actionsheet/ActionSheet.m:83:44: 'UIActionSheet' is deprecated: first deprecated in iOS 8.3 - UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-dialogs/CDVNotification.h:34:27: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-dialogs/CDVNotification.m:172:20: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-dialogs/CDVNotification.m:193:30: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-dialogs/CDVNotification.m:51:55: 'applicationFrame' is deprecated: first deprecated in iOS 9.0 - Use -[UIScreen bounds]
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-inappbrowser/CDVInAppBrowser.m:500:48: 'setStatusBarStyle:' is deprecated: first deprecated in iOS 9.0 - Use -[UIViewController preferredStatusBarStyle]
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-inappbrowser/CDVInAppBrowser.m:663:75: 'UIBarButtonItemStyleBordered' is deprecated: first deprecated in iOS 8.0 - Use UIBarButtonItemStylePlain when minimum deployment target is iOS7 or later
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-inappbrowser/CDVInAppBrowser.m:855:44: 'setStatusBarStyle:' is deprecated: first deprecated in iOS 9.0 - Use -[UIViewController preferredStatusBarStyle]
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-appsflyer-sdk/AppsFlyerPlugin.m:154:39: 'trackEvent:withValue:' is deprecated
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-appsflyer-sdk/AppsFlyerPlugin.m:286:13: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-device-orientation/CDVCompass.m:74:42: 'headingAvailable' is deprecated: first deprecated in iOS 4.0
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVFile.m:589:35: 'stringByReplacingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByRemovingPercentEncoding instead, which always uses the recommended UTF-8 encoding.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVFile.m:590:25: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVLocalFilesystem.m:128:43: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:193:5: 'ALAssetsLibraryAssetForURLResultBlock' is deprecated: first deprecated in iOS 9.0 - Use fetchAssetsWithLocalIdentifiers:options: on PHAsset to fetch assets by local identifier (or to lookup PHAssets by a previously known ALAssetPropertyAssetURL use fetchAssetsWithALAssetURLs:options:) from the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:196:65: 'defaultRepresentation' is deprecated: first deprecated in iOS 9.0 - Use PHImageRequestOptions with the PHImageManager from the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:197:84: 'size' is deprecated: first deprecated in iOS 9.0 - Use requestImageDataForAsset:options:resultHandler: on PHImageManager to request image data for a PHAsset from the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:199:58: 'getBytes:fromOffset:length:error:' is deprecated: first deprecated in iOS 9.0 - Use requestImageDataForAsset:options:resultHandler: on PHImageManager to request image data for a PHAsset from the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:201:138: 'UTI' is deprecated: first deprecated in iOS 9.0 - Use requestImageDataForAsset:options:resultHandler: on PHImageManager for a PHAsset to request image data from the Photos framework and check the dataUTI passed to your result handler instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:193:59: 'ALAsset' is deprecated: first deprecated in iOS 9.0 - Use PHAsset from the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:196:13: 'ALAssetRepresentation' is deprecated: first deprecated in iOS 9.0 - Use PHImageRequestOptions with the PHImageManager from the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:209:5: 'ALAssetsLibraryAccessFailureBlock' is deprecated: first deprecated in iOS 9.0 - Use the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:215:56: 'ALAssetsLibrary' is deprecated: first deprecated in iOS 9.0 - Use PHPhotoLibrary from the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:216:20: 'assetForURL:resultBlock:failureBlock:' is deprecated: first deprecated in iOS 9.0 - Use fetchAssetsWithLocalIdentifiers:options: on PHAsset to fetch assets by local identifier (or to lookup PHAssets by a previously known ALAssetPropertyAssetURL use fetchAssetsWithALAssetURLs:options:) from the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:224:5: 'ALAssetsLibraryAssetForURLResultBlock' is deprecated: first deprecated in iOS 9.0 - Use fetchAssetsWithLocalIdentifiers:options: on PHAsset to fetch assets by local identifier (or to lookup PHAssets by a previously known ALAssetPropertyAssetURL use fetchAssetsWithALAssetURLs:options:) from the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:228:65: 'defaultRepresentation' is deprecated: first deprecated in iOS 9.0 - Use PHImageRequestOptions with the PHImageManager from the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:231:55: 'filename' is deprecated: first deprecated in iOS 9.0 - Use the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:234:60: 'ALAssetPropertyDate' is deprecated: first deprecated in iOS 9.0 - Use the creationDate property on a PHAsset from the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:234:43: 'valueForProperty:' is deprecated: first deprecated in iOS 9.0 - Use PHAsset class properties from the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:224:59: 'ALAsset' is deprecated: first deprecated in iOS 9.0 - Use PHAsset from the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:228:13: 'ALAssetRepresentation' is deprecated: first deprecated in iOS 9.0 - Use PHImageRequestOptions with the PHImageManager from the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:229:91: 'size' is deprecated: first deprecated in iOS 9.0 - Use requestImageDataForAsset:options:resultHandler: on PHImageManager to request image data for a PHAsset from the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:244:5: 'ALAssetsLibraryAccessFailureBlock' is deprecated: first deprecated in iOS 9.0 - Use the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:249:56: 'ALAssetsLibrary' is deprecated: first deprecated in iOS 9.0 - Use PHPhotoLibrary from the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file/CDVAssetLibraryFilesystem.m:250:20: 'assetForURL:resultBlock:failureBlock:' is deprecated: first deprecated in iOS 9.0 - Use fetchAssetsWithLocalIdentifiers:options: on PHAsset to fetch assets by local identifier (or to lookup PHAssets by a previously known ALAssetPropertyAssetURL use fetchAssetsWithALAssetURLs:options:) from the Photos framework instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file-transfer/CDVFileTransfer.m:98:36: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file-transfer/CDVFileTransfer.m:390:52: 'initWithRequest:delegate:startImmediately:' is deprecated: first deprecated in iOS 9.0 - Use NSURLSession (see NSURLSession.h)
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file-transfer/CDVFileTransfer.m:491:52: 'initWithRequest:delegate:startImmediately:' is deprecated: first deprecated in iOS 9.0 - Use NSURLSession (see NSURLSession.h)
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-file-transfer/CDVFileTransfer.m:581:40: 'connectionWithRequest:delegate:' is deprecated: first deprecated in iOS 9.0 - Use NSURLSession (see NSURLSession.h)
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-statusbar/CDVStatusBar.m:281:44: 'setStatusBarStyle:' is deprecated: first deprecated in iOS 9.0 - Use -[UIViewController preferredStatusBarStyle]
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-statusbar/CDVStatusBar.m:378:14: 'setStatusBarHidden:' is deprecated: first deprecated in iOS 9.0 - Use -[UIViewController prefersStatusBarHidden]
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-statusbar/CDVStatusBar.m:411:14: 'setStatusBarHidden:' is deprecated: first deprecated in iOS 9.0 - Use -[UIViewController prefersStatusBarHidden]
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-statusbar/CDVStatusBar.m:481:48: 'applicationFrame' is deprecated: first deprecated in iOS 9.0 - Use -[UIScreen bounds]
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-themeablebrowser/CDVThemeableBrowser.m:1303:22: 'UIActionSheet' is deprecated: first deprecated in iOS 8.3 - UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-themeablebrowser/CDVThemeableBrowser.m:1283:13: 'UIActionSheet' is deprecated: first deprecated in iOS 8.3 - UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-themeablebrowser/CDVThemeableBrowser.m:1319:44: 'setStatusBarStyle:' is deprecated: first deprecated in iOS 9.0 - Use -[UIViewController preferredStatusBarStyle]
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-wkwebview-engine/CDVWKWebViewEngine.m:77:19: 'mediaPlaybackRequiresUserAction' is deprecated: first deprecated in iOS 9.0
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-wkwebview-engine/CDVWKWebViewEngine.m:79:19: 'mediaPlaybackAllowsAirPlay' is deprecated: first deprecated in iOS 9.0
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-wkwebview-engine/CDVWKWebViewEngine.m:394:91: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-x-socialsharing/NSString+SSURLEncoding.m:7:27: 'CFURLCreateStringByAddingPercentEscapes' is deprecated: first deprecated in iOS 9.0 - Use [NSString stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid).
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-x-socialsharing/SocialSharing.m:16:3: 'UIPopoverController' is deprecated: first deprecated in iOS 9.0 - UIPopoverController is deprecated. Popovers are now implemented as UIViewController presentations. Use a modal presentation style of UIModalPresentationPopover and UIPopoverPresentationController.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-x-socialsharing/SocialSharing.m:790:28: 'UIPopoverController' is deprecated: first deprecated in iOS 9.0 - UIPopoverController is deprecated. Popovers are now implemented as UIViewController presentations. Use a modal presentation style of UIModalPresentationPopover and UIPopoverPresentationController.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-x-socialsharing/SocialSharing.m:796:45: 'UIPopoverController' is deprecated: first deprecated in iOS 9.0 - UIPopoverController is deprecated. Popovers are now implemented as UIViewController presentations. Use a modal presentation style of UIModalPresentationPopover and UIPopoverPresentationController.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-x-socialsharing/SocialSharing.m:165:46: 'UIPopoverController' is deprecated: first deprecated in iOS 9.0 - UIPopoverController is deprecated. Popovers are now implemented as UIViewController presentations. Use a modal presentation style of UIModalPresentationPopover and UIPopoverPresentationController.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-x-socialsharing/SocialSharing.m:209:9: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-x-socialsharing/SocialSharing.m:328:7: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-x-socialsharing/SocialSharing.m:647:50: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.m:224:9: 'UIRemoteNotificationType' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.m:224:54: 'UIRemoteNotificationTypeNone' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.m:233:34: 'UIRemoteNotificationTypeBadge' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.m:241:34: 'UIRemoteNotificationTypeSound' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.m:249:34: 'UIRemoteNotificationTypeAlert' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.m:255:30: 'UIRemoteNotificationTypeNewsstandContentAvailability' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.m:270:34: 'UIRemoteNotificationTypeNone' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.m:344:15: 'UIRemoteNotificationTypeBadge' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.m:344:47: 'UIRemoteNotificationTypeSound' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.m:344:79: 'UIRemoteNotificationTypeAlert' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.m:343:48: 'registerForRemoteNotificationTypes:' is deprecated: first deprecated in iOS 8.0 - Use -[UIApplication registerForRemoteNotifications] and UserNotifications Framework's -[UNUserNotificationCenter requestAuthorizationWithOptions:completionHandler:]
Value Conversion Issue Group
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-actionsheet/ActionSheet.m:39:82: Implicit conversion loses integer precision: 'unsigned long' to 'int'
Format String Issue Group
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-inappbrowser/CDVInAppBrowser.m:791:19: Null passed to a callee that requires a non-null argument
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-media/CDVSound.m:694:60: Null passed to a callee that requires a non-null argument
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-themeablebrowser/CDVThemeableBrowser.m:1162:19: Null passed to a callee that requires a non-null argument
Semantic Issue Group
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-inappbrowser/CDVInAppBrowser.m:958:1: Conflicting return type in implementation of 'supportedInterfaceOrientations': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned long')
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-inappbrowser/CDVInAppBrowser.m:1087:1: Conflicting return type in implementation of 'supportedInterfaceOrientations': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned long')
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-themeablebrowser/CDVThemeableBrowser.m:1523:1: Conflicting return type in implementation of 'supportedInterfaceOrientations': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned long')
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-themeablebrowser/CDVThemeableBrowser.m:1615:1: Conflicting return type in implementation of 'supportedInterfaceOrientations': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned long')
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.h:32:35: Cannot find protocol definition for 'GGLInstanceIDDelegate'
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.h:32:58: Cannot find protocol definition for 'GCMReceiverDelegate'
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.m:603:42: Undeclared selector 'userHasRemoteNotificationsEnabled'
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.m:604:49: Undeclared selector 'userHasRemoteNotificationsEnabled'
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.m:615:9: Local declaration of 'callbackId' hides instance variable
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.m:618:73: Local declaration of 'callbackId' hides instance variable
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.m:637:69: Local declaration of 'callbackId' hides instance variable
Unused Entity Issue Group
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-geolocation/CDVLocation.m:85:10: Unused variable 'locationServicesEnabledInstancePropertyAvailable'
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/cordova-plugin-media/CDVSound.m:689:27: Unused variable 'audioSettings'
ARC Retain Cycle Group
/Users/username/IdeaProjects/ourProjectName-bam/mobile/phonegap/platforms/ios/ourProjectName/Plugins/phonegap-plugin-push/PushPlugin.m:87:39: Capturing 'self' strongly in this block is likely to lead to a retain cycle
Apple Mach-O Linker Error Group
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ahar** [comment]
The error in xCode looks like:
ld: library not found for -lPods-OurProjectName
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by macdonst** [comment]
@ahar are you opening the project or the workspace. You should be using the workspace…always.
