### ISSUE TITLE
Android: Notification icon problem

### ISSUE THREAD

**Issue by sebrojas14** [phonegap/phonegap-plugin-push#20]
In lollipop, My notification look like this:

In the notification bar, it's a white square (with the old plugin, the same app icon was used here):

![screenshot_2015-06-19-13-36-53](https://cloud.githubusercontent.com/assets/1771574/8260337/99415342-1688-11e5-95b1-6b2536210cf6.png)

Notification bar expanded, a circle with the app icon inside (there's no way make somethinh better, like the other apps?):

![screenshot_2015-06-19-13-37-00](https://cloud.githubusercontent.com/assets/1771574/8260352/a901b31c-1688-11e5-9e6d-e10d069649ad.png)

**Comment by macdonst** [comment]
@sebrojas14 upon having the chance to look into this bug I believe it not to be a bug. In Android Lollipop there were changes to the notifications so all icons show up as white. See the following url: https://developer.android.com/design/patterns/notifications.html

I think the best way forward for you is to add a transparency to your icon so that it your icon shows up as a silhouette of a person. Potentially we need to add another icon into cordova/phonegap.

**Comment by sebrojas14** [comment]
Yes, you're right. But I need the app icon to have a white background. So, you would be nice a a way to specify a different icon for notifications, or even better, the option of use icons with badge like skype and inbox in the image

**Comment by macdonst** [comment]
@sebrojas14 so the way that it works on Android is you can specify a small icon and large icon in the notification. As you can see in this screen shot:

![Screenshot](https://dl.dropboxusercontent.com/u/887989/2015-06-22%2017.27.08.png)

You can see the PhoneGap Enterprise is the large icon and the cordova build bot is the small icon. I can add in the large icon support but we don't have a good way of specifying it right now. I'm changing this to an enhancement for now.

**Comment by sebrojas14** [comment]
So for now, is not possible to specify a different icon for the notifications?

**Comment by macdonst** [comment]
@sebrojas14 no, not at the moment but my plan is to add a option in the android setup to provide an icon to use instead of the main app icon. If not icon is provide it will use the main app icon as a fallback.

**Comment by sebrojas14** [comment]
I'll wait for it! thank you

**Comment by ivanmayes** [comment]
+1 this would be extremely helpful, white square are no fun!

**Comment by michael-may** [comment]
+1

Tested the TargetSDK workaround and it brings the full icon back for now at least.

In your config.xml:
<platform name="android">
     ...
     <preference name="android-targetSdkVersion" value="19"/>
</platform>

**Comment by Deminetix** [comment]
+1 Waiting for this also, we switched to this plugin because the PushPlugin repo is insanely outdated.

**Comment by Deminetix** [comment]
The target SDK workaround is not a very graceful fix.

**Comment by macdonst** [comment]
This is coming tonight or tomorrow. I just need to document it:

**Large icon support**
supports url, asset or drawable

**Small icon support**
Set the drawable via the Android options. Defaults to app icon if nothing is passed in. As well, you can set the background color for the icon.

![New hotness](https://photos-3.dropbox.com/t/2/AADylaquj34CL37EbToRhvMR3enXxSuzqCABtSSWJ2Bkhw/12/887989/png/32x32/1/1437688800/0/2/2015-07-23%2020.35.40.png/CLWZNiABIAIgAyAEIAUgBiAHKAEoAigH/lP7XzMbHmqoQFc1DcGMmx1FIHd2K5OH_M_JDFkWHg9M?size=1280x960&size_mode=2)

**Comment by sebrojas14** [comment]
Nice! And what is the icon used in the notification bar?

**Comment by macdonst** [comment]
@sebrojas14 the small icon, specified at init time.

**Comment by macdonst** [comment]
![2015-07-24 02 17 55](https://cloud.githubusercontent.com/assets/353180/8866900/2df0ab06-3190-11e5-9a81-fdb85bb0f5a4.png)
![2015-07-24 02 20 02](https://cloud.githubusercontent.com/assets/353180/8866901/2df19052-3190-11e5-8c16-a355c59209f3.png)
![2015-07-24 02 34 41](https://cloud.githubusercontent.com/assets/353180/8866903/2df48028-3190-11e5-8176-fe8b3f7c5aab.png)
![2015-07-24 02 46 58](https://cloud.githubusercontent.com/assets/353180/8866902/2df3276e-3190-11e5-842a-c8cd95615ab0.png)
![2015-07-24 02 52 00](https://cloud.githubusercontent.com/assets/353180/8866899/2df00c3c-3190-11e5-8552-96201fb4424b.png)

**Comment by sebrojas14** [comment]
Sorry, I was asking for the status bar.

**Comment by macdonst** [comment]
@sebrojas14 Yes, when you specify an icon via init it is used in the status bar as well. I just pushed the code so try it out and I'm planning on bumping the plugin version shortly. Much thanks to @Deminetix for his assistance on this issue.

**Comment by Deminetix** [comment]
@macdonst did you miss my PR?

**Comment by Deminetix** [comment]
Oh sorry, I missed that. Hope its helfpul to peeps :)

**Comment by macdonst** [comment]
@Deminetix no, I didn't miss it. I used it but changed it up a bit. Again, I really appreciate you contributing to this plugin so keep at it.

**Comment by kentmw** [comment]
Just as a note to those like me using Phonegap Build to build your apk's, PGB currently doesn't let you add or copy images to the /res directory and because the NotificationBuilder specifically (at least in Lolipop and lower versions) requires a resource id, PGB users can not produce white/transparent icons unless your app icon itself fits the system icon/small icon/notification banner specifications.

Extra thoughts: I tried to fool PGB using qualifiers to the app icon and/or splash screen images to no avail. Also, it looks like in API level 23 (or code named M after Lolipop), you can generate icons programatically so you could pull an image in from www/ directory.

It looks like exploding your apk using a tool like apktool, adding the image to the res directory, and rebuilding it with -c flag is the only option - except perhaps dropping phonegap build altogether.

**Comment by kishorpawar** [comment]
@macdonst I am setting image for smallicon in init, and image is present in assets folder, still I am getting white square, logs read as follows

D/PushPlugin_GCMIntentService(29859): stored icon=www/assets/images/NI44
D/PushPlugin_GCMIntentService(29859): stored iconColor=#C53D27
D/PushPlugin_GCMIntentService(29859): stored sound=true
D/PushPlugin_GCMIntentService(29859): stored vibrate=true
D/PushPlugin_GCMIntentService(29859): using localIcon from plugin options www/assets/images/NI44
D/PushPlugin_GCMIntentService(29859): no icon resource found - using application icon

**Comment by bguvenis** [comment]
What about the small blue icon on the bottom right of "Large Icon - Loaded from drawables folder"? How do you set that? I see a white square inside a turquois circle. I want to give an image for that, or clear it for good.

**Comment by rohit121** [comment]
Post android Lollipop release android has changed the guidelines for displaying notification icons in the Notification bar.
The official documentation says "Update or remove assets that involve color. The system ignores all non-alpha channels in action icons and in the main notification icon. You should assume that these icons will be alpha-only. The system draws notification icons in white and action icons in dark gray.”
Now what that means in lay man terms is "Convert all parts of the image that you don’t want to show to transparent pixels. All colors and non transparent pixels are displayed in white"

You can see how to do this in detail with screenshots here
https://blog.clevertap.com/fixing-notification-icon-for-android-lollipop-and-above/

Hope that helps

**Comment by pke** [comment]
I am using an icon with alpha channel now but the cordova build process for android modifies the icon and removes the alpha channel.
