### ISSUE TITLE
iOS getting wrong push token in production

### ISSUE THREAD

**Issue by phillipplum** [phonegap/phonegap-plugin-push#2001]
Hello,
I'm getting wrong push tokens from iOS in the app store version. All iOS push tokens are wrong and I always get the info: BadDeviceToken. I get this error when sending the token to sandbox and to production. In Apple Developer Push is enabled but not configured because we using auth key. 

### Expected Behaviour
Getting right iOS push token.

### Actual Behaviour
Get push token that is not valid. (Info from apn: BadDeviceToken in production and sandbox)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS (testet in iOS 10.0.0 and iOS 10.0.2)

#### Cordova CLI version and cordova platform version

    cordova --version                                    #7.0.1
    cordova platform version android                     #4.4.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   #2.0.0

#### Sample Code that illustrates the problem
    $cordovaPushV5.initialize(options).then(function() {
    	$log.log('$push initialize resolve');
    	$cordovaPushV5.onNotification();
    	$cordovaPushV5.onError();
    
    	$cordovaPushV5.register().then(
		function(registrationId) {
			$log.log('$push register with ID: ' + registrationId);
		},
		function(error) {
			$log.error(error);
		}
	);
    });

**Comment by macdonst** [comment]
@phillipplum what does your device token look like?

**Comment by pke** [comment]
@macdonst can you see based on the token for which env it was created? Because we have a similar problem that we want to test notifications in testflight and with ad-hoc deploys to registered developer devices. However the server needs to know for which env the token was created.

**Comment by macdonst** [comment]
@pke No but the reason I asked was I  suspect he was trying to use a APNS token with a GCM/FCM service. In that case it's really easy to tell the difference.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
