### ISSUE TITLE
Cannot get push notifications when I deploy to phone

### ISSUE THREAD

**Issue by vijayb** [phonegap/phonegap-plugin-push#2002]
I've managed to get the plugin working for Android, pretty seamlessly (thanks guys for building it!) but am having a hell of a time getting it working in iOS. I've managed to get the app built and deploy to my phone using xCode but when I send a push notification using Firebase notification console nothing shows up on the phone.

I've turned the "push notification" tab in xCode to on. I have a GoogleService-Info.plist in my working directory and I have code in my controller to handle push notifications (and they're received correctly in the controller in Android).

Could you guys let me know what other common things I might be missing that's preventing me from receiving notifications in app and what strategies I could use to debug this?

Thanks again for building it and maintaining it for the community.

**Comment by vijayb** [comment]
Some extra info in case it's helpful: when I start my app it does successfully ask me for permission to accept push notifications. So I think the plugin is working in some sense. But it's just not seeing the messages from Firebase. I'm guessing some signing issue is happening but I'm not sure where to start looking for how to fix this

**Comment by vijayb** [comment]
I finally figured it out. It was a certificate issue. I'm a part of a dev team and there were several certificates, plus I needed to use the development certificate, then convert it to p12 format to test using Pusher. Many steps later I finally got a push notification to show up on my phone. STill quite amazed how much more convoluted and difficult this is for iOS versus Android. Thanks once again for the plugin guys

**Comment by fredgalvao** [comment]
As with 80% of the issues on iOS, this was a certificate one... I wish we could aleviate this kind of trouble.

**Comment by vijayb** [comment]
Thanks @fredgalvao ! Yes, I wish this had been much easier. Android took less than an hour. Figuring out iOS took days.

Quick question for you: do you know if I build a release candidate of my Ionic app and sign with a production certificate whether I can use Pusher to test push notifications when I deploy locally to my phone (so I can be sure it's working before submitting to the app store)?

thanks

**Comment by fredgalvao** [comment]
IIRC (I'm not the one who messes around full-time on iOS on my project), you need to setup your AdHoc certificate/provisioning profile, so that you can "properly sign" for push functionality without using production context.
Other than that I'm as lost as you.
