### ISSUE TITLE
Does the 1.9 branch support FCM at all?

### ISSUE THREAD

**Issue by DanRobinsonRV** [phonegap/phonegap-plugin-push#2003]
Sorry if this is a stupid question, but I'm trying to get this plugin working with Adobe's PhoneGap Build, and I noticed in the docs that PhoneGap Build only supports up to v1.9 of the plugin. However, the docs also seem to suggest that the plugin only moved from the old GCM to FCM with 2.0, and it doesn't seem possible to register a new GCM account any more.

Does this mean that people who use PhoneGap Build are unable to use this plugin until the v2 branch is supported, or am I missing something?

**Comment by jcesarmobile** [comment]
1.9.x has GCM code, but appears to work fine on Android even when using FCM.
