### ISSUE TITLE
Android: this plugin clears all notifications after switching to background, even non-push notifications

### ISSUE THREAD

**Issue by shawnlan** [phonegap/phonegap-plugin-push#2005]
My app uses `cordova-plugin-music-controls`. It displays an ongoing notification with music controls.

This plugin will clear that notification when switching to the background.

I know I can set `android.clearNotifications` to `false`. But I would like to keep this option.

I think this plugin shouldn't clear other non-push notifications. Otherwise there could be a conflict.

**Comment by macdonst** [comment]
@shawnlan I need more info. 

Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
