### ISSUE TITLE
Error while adding ionic cordova platform add  ios

### ISSUE THREAD

**Issue by abmnukmr** [phonegap/phonegap-plugin-push#2006]
Failed to install 'phonegap-plugin-push': undefined
        Error:     WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
             Consider adding the following to ~/.profile:
        
             export LANG=en_US.UTF-8
             
        /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as 
        root. (CLAide::Help)
        
        Usage:

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
