### ISSUE TITLE
displaying multiple notifications with different notId when app is in foreground

### ISSUE THREAD

**Issue by VaishaliRavindran** [phonegap/phonegap-plugin-push#2010]
Hello,
I am having notifications with different notId and when I select a notification the corresponding actions are executed correctly, But other notifications with different notIds are disappearing from notification tray in android when app is in foreground

 **Expected Behaviour**
notifications with other notIds, that are not selected must be displayed in notification tray, when app is in foreground
 **Actual Behaviour**
All the notifications are removed from notification tray

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0.2
Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Android moto-g2 and redmi note 3

#### Cordova CLI version and cordova platform version

    cordova --version                                    # 7.0.1
    cordova platform version android           # 6.2.3

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # 2.0.0

**Comment by fredgalvao** [comment]
@VaishaliRavindran Have you tried reading/changing the value of android.clearNotifications on your init options?
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#android

**Comment by VaishaliRavindran** [comment]
@fredgalvao  Setting the value of android.clearNotifications to 'false'  does the work. The notifications with different notIds that are not selected are not removed from notification tray. Thanks :)
