### ISSUE TITLE
On(‘notification’,.... not called When iOS app in foreground and notification displayed as banner

### ISSUE THREAD

**Issue by debe78** [phonegap/phonegap-plugin-push#2013]
Expected Behaviour
 Call On(‘notification’,....  when iOS app in foreground

 Actual Behaviour
On(‘notification’,.... not called When iOS app in foreground and notification displayed as banner.

App in foreground The notification si displayed as native banner and on(‘notification’,...) is not called.
I have logged each Method on iOS src folder and no one is called.
With App in background or closed plugin run as aspected.
Probably the problem is Cordova-ios and iOS>10. 
Do you use UserNotifications framework?
Any idea?

 Platform and Version 
   iPhone 5s iOS 10
   iPhone 8p iOS 11
  
 Cordova CLI version and cordova platform version
   Cordova-iOS 4.5.1
   Push-plugin 2.0.0 but also push-plugin 1.9.x
   APNs notification system 

Thanks
Enrico

**Comment by macdonst** [comment]
@debe78 can you give me a more detailed reproduction scenario? What is you init method looking like? How do you get it to display in the banner when the app is in the foreground?

**Comment by debe78** [comment]
Hi,

INIT METHOD:
----------------------------------------------------------------------------------
registraPush: function(){
    var me=this;
    var senderId= //GET SEND ID FROM APP CONFIGURATION   
    me.setPush(pushtemp = PushNotification.init(
          { "android": {
            "senderID": senderId,
            "sound": true,
            "vibrate": true            
          },
           "ios": {
             "alert": true, 
             "badge": true, 
             "sound": true,
             "clearBadge": true             
           }}));
    me.getPush().on('registration', function(data) {      
      var token=data.registrationId;
      // SEND TOKEN TO MY SERVICE SERVER
    });
    me.getPush().on('notification', function(data) {
        //DO SOMETINGH ON THE APP VIEW      
      if (Ext && Ext.os.is.iOS && data && data.additionalData && 
          !data.additionalData.foreground && data.additionalData['content-available']) {
          Ext.defer(function(){           
              me.getPush().finish(function(){}, 
                                  function(){}, 'push1');
          },25000);    
      }});
    me.getPush().on('error', function(e) {      
      //LOG ERRORE PUSH
    });     
    return me.getPush();
  }

----------------------------------------------------------------------------------
JSON SENDED TO APNs
----------------------------------------------------------------------------------
{"aps":{"alert":"TEST MESSAGE TO SEND APP","sound":"default","badge":1}}

The problem is only with IOS, with Android run as aspected.

THANKS
Enrico

**Comment by macdonst** [comment]
@debe78 what other plugins are you using in your app?

**Comment by debe78** [comment]
@macdonst  this is the list from my config.xml:

<plugin name="com.eightz.mobile.cordova.plugin.android.referrer" spec="https://github.com/debe78/debe78-android-referrer-plugin" />
    <plugin name="cordova-open" spec="^1.0.12" />
    <plugin name="cordova-plugin-app-event" spec="^1.2.1" />
    <plugin name="cordova-plugin-app-preferences" spec="^0.99.3" />
    <plugin name="cordova-plugin-calendar" spec="^4.6.0">
        <variable name="CALENDAR_USAGE_DESCRIPTION" value="SOME DESCRIPTION" />
    </plugin>
    <plugin name="cordova-plugin-camera" spec="^2.4.1">
        <variable name="CAMERA_USAGE_DESCRIPTION" value="SOME DESCRIPTION" />
        <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="SOME DESCRIPTION" />
    </plugin>
    <plugin name="cordova-plugin-compat" spec="^1.2.0" />
    <plugin name="cordova-plugin-config-alert" spec="^1.0.0" />
    <plugin name="cordova-plugin-device" spec="^1.1.6" />
    <plugin name="cordova-plugin-file" spec="^4.3.3" />
    <plugin name="cordova-plugin-file-transfer" spec="^1.6.3" />
    <plugin name="cordova-plugin-inappbrowser" spec="^1.7.1" />
    <plugin name="cordova-plugin-network-information" spec="^1.3.3" />
    <plugin name="cordova-plugin-screen-orientation" spec="^2.0.1" />
    <plugin name="cordova-plugin-splashscreen" spec="^4.0.3" />
    <plugin name="cordova-plugin-statusbar" spec="^2.2.3" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.2" />
    <plugin name="cordova-save-image-gallery" spec="0.0.26" />
    <plugin name="cordova-sqlite-storage" spec="^2.0.4" />
    <plugin name="de.appplant.cordova.plugin.local-notification" spec="^0.8.5" />
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
    <plugin name="phonegap-plugin-mobile-accessibility" spec="^1.0.5" />
    <plugin name="phonegap-plugin-push" spec="^2.0.0" />

Thanks

**Comment by debe78** [comment]
<plugin name="com.eightz.mobile.cordova.plugin.android.referrer" spec="https://github.com/debe78/debe78-android-referrer-plugin" />
    <plugin name="cordova-open" spec="^1.0.12" />
    <plugin name="cordova-plugin-app-event" spec="^1.2.1" />
    <plugin name="cordova-plugin-app-preferences" spec="^0.99.3" />
    <plugin name="cordova-plugin-calendar" spec="^4.6.0">
        <variable name="CALENDAR_USAGE_DESCRIPTION" value="SOME DESCRIPTION" />
    </plugin>
    <plugin name="cordova-plugin-camera" spec="^2.4.1">
        <variable name="CAMERA_USAGE_DESCRIPTION" value="SOME DESCRIPTION" />
        <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="SOME DESCRIPTION" />
    </plugin>
    <plugin name="cordova-plugin-compat" spec="^1.2.0" />
    <plugin name="cordova-plugin-config-alert" spec="^1.0.0" />
    <plugin name="cordova-plugin-device" spec="^1.1.6" />
    <plugin name="cordova-plugin-file" spec="^4.3.3" />
    <plugin name="cordova-plugin-file-transfer" spec="^1.6.3" />
    <plugin name="cordova-plugin-inappbrowser" spec="^1.7.1" />
    <plugin name="cordova-plugin-network-information" spec="^1.3.3" />
    <plugin name="cordova-plugin-screen-orientation" spec="^2.0.1" />
    <plugin name="cordova-plugin-splashscreen" spec="^4.0.3" />
    <plugin name="cordova-plugin-statusbar" spec="^2.2.3" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.2" />
    <plugin name="cordova-save-image-gallery" spec="0.0.26" />
    <plugin name="cordova-sqlite-storage" spec="^2.0.4" />
    <plugin name="de.appplant.cordova.plugin.local-notification" spec="^0.8.5" />
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
    <plugin name="phonegap-plugin-mobile-accessibility" spec="^1.0.5" />
    <plugin name="phonegap-plugin-push" spec="^2.0.0" />

**Comment by debe78** [comment]
Hi,
@macdonst  this is the list from my config.xml:

plugin name="com.eightz.mobile.cordova.plugin.android.referrer" spec="https://github.com/debe78/debe78-android-referrer-plugin"
plugin name="cordova-open" spec="^1.0.12" 
plugin name="cordova-plugin-app-event" spec="^1.2.1" 
plugin name="cordova-plugin-app-preferences" spec="^0.99.3" 
plugin name="cordova-plugin-calendar" spec="^4.6.0"
plugin name="cordova-plugin-camera" spec="^2.4.1"
plugin name="cordova-plugin-compat" spec="^1.2.0" 
plugin name="cordova-plugin-config-alert" spec="^1.0.0" 
plugin name="cordova-plugin-device" spec="^1.1.6" 
plugin name="cordova-plugin-file" spec="^4.3.3" 
plugin name="cordova-plugin-file-transfer" spec="^1.6.3" 
plugin name="cordova-plugin-inappbrowser" spec="^1.7.1" 
plugin name="cordova-plugin-network-information" spec="^1.3.3" 
plugin name="cordova-plugin-screen-orientation" spec="^2.0.1" 
plugin name="cordova-plugin-splashscreen" spec="^4.0.3" 
plugin name="cordova-plugin-statusbar" spec="^2.2.3" 
plugin name="cordova-plugin-whitelist" spec="^1.3.2" 
plugin name="cordova-save-image-gallery" spec="0.0.26" 
plugin name="cordova-sqlite-storage" spec="^2.0.4" 
plugin name="de.appplant.cordova.plugin.local-notification" spec="^0.8.5" 
plugin name="ionic-plugin-keyboard" spec="^2.2.1" 
plugin name="phonegap-plugin-mobile-accessibility" spec="^1.0.5" 
plugin name="phonegap-plugin-push" spec="^2.0.0" 

Thanks

**Comment by macdonst** [comment]
@debe78 I'm pretty sure if you take `de.appplant.cordova.plugin.local-notification` out of your app the problem will go away. The two plugins do not play nice as `de.appplant.cordova.plugin.local-notification` takes over the didReceiveNotification method.

**Comment by debe78** [comment]
@macdonst you right, removing local  notification plugin the push notification run as expected.
The last version of local notification 0.8.5 conflicts with your plugin.
Now I have the problem.... How can this two plugins work toghether? Is it possible use only your plugin also to manage local notification?
Thanks

**Comment by macdonst** [comment]
@debe78 as far as I know the two plugins can't work together. At least the way the local notification plugin is currently written. It takes over the display of notifications. You should probably check the issues on that repo.
