### ISSUE TITLE
GCM to FCM migration guide?

### ISSUE THREAD

**Issue by Defcon0** [phonegap/phonegap-plugin-push#2018]
Hello,

I realize, migrating to FCM for our upcoming app is a good idea for being future-proof.

Now is there any migration guide concerning this plugin and GCM to FCM instead?

Thanks in advance.

Bye

**Comment by macdonst** [comment]
@Defcon0 there are a bunch of documents on Google. https://developers.google.com/cloud-messaging/faq.

Basically, if you start using 2.0.0 of this plugin you'll want to get google-services.json/plist file from google, deliver it via config.xml tags and remove senderID from init. That last step is not even needed as it is ignored by the plugin.

**Comment by Defcon0** [comment]
Thanks for that: What might be useful also for other users: At first I didn't know where to get the google-services.json/plist files. There's absolutely no hint for that in the docs. Might be good if we had a text in there like "You can create and download google-services.json in the Google FCM Console.".
