### ISSUE TITLE
device token fails on iOS 10+ with PGB (cli 5.6.0)

### ISSUE THREAD

**Issue by rkjamvi** [phonegap/phonegap-plugin-push#2019]
### Expected Behaviour
iOS device token register for APNS

### Actual Behaviour
Error on registering device.

Hi,

I am using PGB and below is my config.xml code (attached), still iOS 10+ devices are not generating device token:

<preference name="phonegap-version" value="cli-6.5.0" />
<preference name="android-build-tool" value="gradle" />

<plugin name="phonegap-plugin-push" spec="~1.10.5" source="npm"/> 

<config-file platform="ios"  parent="aps-environment">
   <string>production</string>
 </config-file>

Please advise if there is something missing in it. This is working great for iOS 9 devices and android all devices.

**Comment by macdonst** [comment]
@rkjamvi  the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
