### ISSUE TITLE
Clean way to detect "Don't Allow" of push notification permissions on iOS?

### ISSUE THREAD

**Issue by benmcmaster** [phonegap/phonegap-plugin-push#202]
Is there a good way to detect if the user denied push notification permissions? (iOS)

In the old PushPlugin I was using a set timeout. Basically if the registration function doesn't come back I assume there was an error. It's hacky. Do we still have to do that? I wish there was a better way.

Here is an example of using a setTimeout in the old PushPlugin:
http://stackoverflow.com/questions/25844812/cordova-how-to-detect-if-push-notifications-are-disabled-on-the-device

**Comment by macdonst** [comment]
@benmcmaster no, there really isn't. The way iOS works is you can check to see if the application has been registered for push notifications or not but there is no way to tell if they haven't yet approved the app for push or if they have denied permission for push. I'll have to have more of a think on it.

**Comment by benmcmaster** [comment]
@macdonst yeah, I figured as much. Doing the setTimeout is working ok for me. If registration event never fires I can assume push notifications are not working for that user.

**Comment by Hirbod** [comment]
@macdonst here you find many working concepts how to realize this.
I think it should be possible to provide a .hasPushPermission() or something like that.

http://stackoverflow.com/questions/1535403/determine-on-iphone-if-user-has-enabled-push-notifications

**Comment by tyronedougherty** [comment]
+1, would be a great addition to the plugin. :smile:

**Comment by eladmoshe** [comment]
+1

**Comment by zwacky** [comment]
+1

**Comment by zwacky** [comment]
i forked this feature here, only iOS at the moment. it should have < ios8 and >= ios8 support.

https://github.com/zwacky/phonegap-plugin-push

usage:

```
window.PushNotification.hasPermission((isEnabled) => {
    if (isEnabled) {
        var push = window.PushNotification.init({
            ...
        });
    }
});
```

**Comment by macdonst** [comment]
@zwacky Pull requests are more than welcome.

**Comment by zwacky** [comment]
will do when i got android ready

**Comment by macdonst** [comment]
:+1: 

might be a bit slow to respond as I'm off to EU in a few hours on a business trip.

**Comment by bau720123** [comment]
hi all
for now it is already a plugin can to this thing
https://www.npmjs.com/package/com.nrswolf.cordova.push-notifications-status

**Comment by zwacky** [comment]
true, @bau720123. although it only covers iOS.

**Comment by bau720123** [comment]
thanks @zwacky 
maybe wait @macdonst to merge yours

**Comment by stinju** [comment]
@zwacky et al, would it be useful to return sound/alert/badge booleans as well for iOS?  It is platform-specific, but probably useful in many developer contexts.

**Comment by fabiocaccamo** [comment]
+1

**Comment by macdonst** [comment]
Handled by PR #305

**Comment by macdonst** [comment]
Merged into master.
