### ISSUE TITLE
Right way to catch the registration id Android/IOS

### ISSUE THREAD

**Issue by MateusAndrade** [phonegap/phonegap-plugin-push#2021]
### Expected Behaviour

Hash from Firebase generated with success, but i cant get the registration id, How can i catch the value on Android and IOS?

### Actual Behaviour

Device get registered, but when i try to call Push.on('registration') it throws the following error: Uncaught TypeError: PushNotification.on is not a function

### Reproduce Scenario (including but not limited to)

When i try to call PushNotification.init it gets a JS error, not generating my hash

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 7.0 

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Samsung

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 7.0.0
    cordova platform version android                     # e.g. 6.2.3

#### Plugin version

  phonegap-plugin-push   # e.g. 2.0.0

#### Sample Push Data Payload

 ```
   PushNotification.init({
        android: {
          senderID: "x",
           alert: "true",
           badge: 'true',
           sound: 'true',
           clearNotifications: 'true',
           vibrate: 'true'
        },
        browser: {
            pushServiceURL: 'http://push.api.phonegap.com/v1/push'
        },
        ios: {
          senderID: "x",
           alert: "true",
           badge: 'true',
           sound: 'true',
           clearNotifications: 'true',
           vibrate: 'true'
        },
        windows: {}
    });

    PushNotification.on('registration', function(data) {

      console.log(JSON.stringify(data));

      localStorage.setItem("hash",JSON.stringify(data));
    });

```
#### Logs taken while reproducing problem

10-18 16:53:20.579 31754-31754/com.telesinformatica.terminalprofissional I/chromium: [INFO:CONSOLE(384)] "Uncaught TypeError: PushNotification.on is not a function", source: file:///android_asset/www/js/controller/ControllerIndex.js (384)

**Comment by macdonst** [comment]
@MateusAndrade you're code is wrong. `PushNotification.init` returns and instance of the plugin and you register your event listeners on that instance. Your code should be written:

```
var push = PushNotification.init({
       android: {
         senderID: "x",
          alert: "true",
          badge: 'true',
          sound: 'true',
          clearNotifications: 'true',
          vibrate: 'true'
       },
       browser: {
           pushServiceURL: 'http://push.api.phonegap.com/v1/push'
       },
       ios: {
         senderID: "x",
          alert: "true",
          badge: 'true',
          sound: 'true',
          clearNotifications: 'true',
          vibrate: 'true'
       },
       windows: {}
   });

   push.on('registration', function(data) {

     console.log(JSON.stringify(data));

     localStorage.setItem("hash",JSON.stringify(data));
   });
```

**Comment by MateusAndrade** [comment]
LOL, i didnt see this, it works now. Thanks! =D
