### ISSUE TITLE
Action Buttons not working on iOS 11.1

### ISSUE THREAD

**Issue by dmnkgrc** [phonegap/phonegap-plugin-push#2023]
### Expected Behaviour
When I click on an action button this should trigger the function associated with that button.

### Actual Behaviour

When I send a PN that looks like this:
```
{
  additionalData: {
      category: "alert",
      id: "38615",
      coldstart: false,
      incident_id: 1680,
      foreground: false,
      content-available: 1,
      incident_response_id: 14855,
      type: "alert"
  },
  message: "P1 Fire ITESM Campus Querétaro [Default]",
  sound: "full_alarm.wav"
}
``` 
Nothing happens, not even an error, the Xcode console logs [CATransaction synchronize] called within transaction when clicking the action button.
On android the action buttons work perfectly.

#### Steps to Reproduce
- Send a push notification with a category.
- The push notification and action buttons are shown.
- Click on any of the action buttons.
- Nothing happens except the log mentioned above. 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 11.1

#### Cordova CLI version and cordova platform version

   Cordova CLI: 7.0.1
    Cordova iOS:  4.4.0
#### Plugin version

  2.0.0

#### Sample Push Data Payload
```
{
  additionalData: {
      category: "alert",
      id: "38615",
      coldstart: false,
      incident_id: 1680,
      foreground: false,
      content-available: 1,
      incident_response_id: 14855,
      type: "alert"
  },
  message: "P1 Fire ITESM Campus Querétaro [Default]",
  sound: "full_alarm.wav"
} 
```
#### Sample Code that illustrates the problem
I am using the plugin with ionic 3.9.2
```
(<any>window)['acceptIncident'] = (data: any) => {
  console.log('this is not executed');
  this.pushObject.finish().then(() => {
    console.log('processing of push data is finished');
  }).catch((err: any) => {
    console.log(err);
  });
};
const pushOptions: PushOptions = {
            android: {
                senderID: config.pushNotifications.android.senderID,
            },
            ios: {
                alert: 'true',
                badge: false,
                sound: 'true',
                categories: {
                    alert: {
                        yes: {
                            callback: 'acceptIncident',
                            title: 'Accept',
                            foreground: false,
                            destructive: false
                        },
                        no: {
                            callback: 'rejectIncident',
                            title: 'Reject',
                            foreground: false,
                            destructive: true
                        }
                    }
                }
            },
            windows: {}
};

this.pushObject = this.push.init(pushOptions);
```

#### Logs taken while reproducing problem
When notification arrives:
![part1](https://user-images.githubusercontent.com/4812676/31789367-8c7af83a-b4d7-11e7-9a88-b59e07a4d76e.jpg)
When I click on an action button:
![part2](https://user-images.githubusercontent.com/4812676/31789374-9567ccb6-b4d7-11e7-9b64-4eb622a66de9.jpg)

**Comment by macdonst** [comment]
@dmnkgrc the push payload you are sending seems off. It should look something like:

```
{
	"aps": {
		"alert": "This is a notification that will be displayed ASAP.",
		"category": "invite"
	},
    "notId": "1"
}
```

**Comment by dmnkgrc** [comment]
I am sending it through the Houston gem and everything else seems to work fine. Do you think the payload might be the problem?

**Comment by dmnkgrc** [comment]
I tried also with the apn node module, but the notification is received the same way, the notifications looks as your example above before sending it, but when received the additionalData key is present instead

**Comment by macdonst** [comment]
@dmnkgrc that's okay it's supposed to end up in the `additionalData` section. As long as you are sending it in the above format it should be fine. Did you try swiping on the notification to reveal the buttons?

**Comment by dmnkgrc** [comment]
@macdonst The buttons do show, but when I click on them nothing happens

**Comment by macdonst** [comment]
@dmnkgrc is `acceptIncident` callable from window? That is if you type `windows.acceptIncident` in console does it execute?

**Comment by dmnkgrc** [comment]
@macdonst yes, if I type `window.acceptIncident` the function is displayed

**Comment by macdonst** [comment]
@dmnkgrc sorry, I can't reproduce this.

**Comment by lajos93** [comment]
@dmnkgrc Did you manage to fix this issue?

**Comment by dmnkgrc** [comment]
@lajos93 No, not yet :(

**Comment by dmnkgrc** [comment]
@macdonst I don't know if this helps in any way, but after some debugging I can see that the handleActionWithIdentifier function is not being triggered by the action button clicked, I also updated my Ionic wrapper to work with the version 2.1.0 of the plugin:
```
 this.pushObject.on('acceptIncident').subscribe((data: NotificationEventResponse) => {
            // Code here
            this.pushObject.finish().then(() => {
                console.log('processing of push data is finished');
            }).catch((err: any) => {
                console.log(err);
            });
        });
```
This works great on Android, but sadly doesn't work on iOS

**Comment by dmnkgrc** [comment]
@macdonst  After some more debugging the problem was the APNs certificate, it was a development certificate and when we changed it to production action buttons worked.

**Comment by macdonst** [comment]
@dmnkgrc 99.98% of the time it seems to be the production/development certificate issue when it comes to iOS. I find it confusing, lots of others find it confusing but Apple persists with it. 

🤷‍♂️
