### ISSUE TITLE
Push V2.1 same device after close app and reopen it got another new RegisterID (Token)

### ISSUE THREAD

**Issue by jamesinsummer** [phonegap/phonegap-plugin-push#2025]
### Install APP open it, got a new RID, close and re-open got another second RegisterID,
Close and reopen again, got the same RID as second one and so on.

#### Cordova CLI version and cordova platform version

    phonegap --version                                    # e.g. 7.1.1
    phonegap cordova platform version android                     # e.g. 7.1.0 / Android 6.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   #2.1.0

**Comment by macdonst** [comment]
@jamesinsummer do you get a different ID everytime you open the app or did it just happen once?

**Comment by jamesinsummer** [comment]
Just happen at second times. Then the rest all get as same as the second RegisterID.

**Comment by macdonst** [comment]
@jamesinsummer not sure what to tell you. If you are able to get a registration ID and receive pushes I'm not sure this is a bug.

**Comment by jamesinsummer** [comment]
Thanks for reply, 
it is ok, I can switch it back to 1.10.5
Thanks again.

**Comment by jcesarmobile** [comment]
@jamesinsummer what @macdonst is trying to tell you is that tokens can change, so it's not really a bug unless you are unable to get push notifications when you send them to the new token.

**Comment by jamesinsummer** [comment]
@jcesarmobile Except got 2 RegisterIDs, V2.1 work very well.
But my APP just need a rid, therefore, 1.10.5 still my best choice so far.

**Comment by macdonst** [comment]
Okay, as long as you are happy I will close this issue.

**Comment by codinronan** [comment]
Issues is closed but for future reference: 

Your app is supposed to update the stored token when a new token is generated. I personally use Firebase auth which makes this invisible to me (this is the primary reason I use it actually) but it happens frequently. Almost anything can trigger an update of the token so you need to be prepared to update them.

You don't actually need to go all-in with Firebase auth. I only use it to store the device tokens for push notifications by passing the auth calls through a second step in the Firebase API. Then I can publish notifications directly from the FCM dashboard.

**Comment by jamesinsummer** [comment]
@jcesarmobile Except got 2 RegisterIDs, V2.1 work very well.
But my APP just need a rid, therefore, 1.10.5 still my best choice so far.

**Comment by jamesinsummer** [comment]
To whom might face same issue,
After build APK, you wont get second RegisterID.
So, I switch to V2.1 
Nice plugin, Thanks the developer.
