### ISSUE TITLE
Redirect to a specific page When i cilck push notification

### ISSUE THREAD

**Issue by bouine** [phonegap/phonegap-plugin-push#2026]
hello guys,
how i can use click_action in this plugin or in ionic 2 
I need an example for click_action to understand  
thanks

**Comment by macdonst** [comment]
#1274 

Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
