### ISSUE TITLE
Unable to add v2.1.0 to my project -> cordova 7.1.0 is required and in place but plugin complains about it being missing

### ISSUE THREAD

**Issue by Defcon0** [phonegap/phonegap-plugin-push#2028]
### Expected Behaviour

v2.1.0 added to project

### Actual Behaviour

v2.1.0 not added to project:

Plugin doesn't support this project's cordova version. cordova: 7.0.1, failed version requirement: >=7.1.0

But indeed I have cordova 7.1.0 (cordova -v shows that).

#### Steps to Reproduce

cordova plugin add phonegap-plugin-push@2.1.0

#### Cordova CLI version and cordova platform version

    cordova --version: 7.1.0
    cordova platform version android: 6.3.0

**Comment by macdonst** [comment]
@Defcon0 can you do a `which cordova` to see where it is getting picked up from? Also, check node_modules to see if an older cordova version is installed in there.

**Comment by Defcon0** [comment]
@macdonst You pointed me into the right direction. There was a local cordova installed in node_modules in the project directory.

Why it had been in there is pretty unclear for me though, I always install cordova globally.

I removed the dir, removed cordova globally and reinstalled it again and then it worked.

**Comment by LioH** [comment]
Hi,
I have the same problem, using `which cordova` it say `/usr/local/bin/cordova`. 
I still got the same problem. Can I delete the node_modules directory ?
