### ISSUE TITLE
IOS registration get error

### ISSUE THREAD

**Issue by sonlexuan** [phonegap/phonegap-plugin-push#2029]
It used to work extremely well before. But now I cannot firgue out why it always push.on('error',)
### Expected Behaviour
RegistrationId
### Actual Behaviour
{"line":80,"column:50","sourceURL":"file//var/containers/Bundle/Application/836BAB7A-E623-4068-B5C6-1FB8FF2F90DB/APP/www/plugins/phonegap-plugin-push/www/push.js"}

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
IOS 11.0.2

#### Cordova CLI version and cordova platform version
 @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.2

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    Cordova Platforms : android 6.2.3 ios 4.4.0
    Ionic Framework   : ionic1 1.3.3

System:

    Node : v6.11.0
    npm  : 3.10.10
    OS   : Windows 10

#### Plugin version

phonegap-plugin-push 2.0.0 "PushPlugin"

#### Sample Code that illustrates the problem
```
var push = PushNotification.init({
            android: {
                "senderID": "625138483858",
                "badge": "true",
                "forceShow": "false",
                "sound": "true"
            },
            browser: {
                pushServiceURL: 'http://push.api.phonegap.com/v1/push'
            },
            ios: {
                "alert": "true",
                "badge": "true",
                "sound": "true"
            },
            windows: {}
        });

        push.on('registration', function (data) {
            console.log(data.registrationId);
            user.registration_id = data.registrationId;
            if (ionic.Platform.isIOS()) {
                user.push_noti_token = data.registrationId;
            } else {
                user.registration_id = data.registrationId;
            }
            $http.post(SOCKET_API + 'storeRegID', { 'userInfo': user }).success(function (res) {
                console.log(JSON.stringify(res));
            });
        });

        push.on('notification', function (data) {
            console.log(data);
            if (data.additionalData && !data.additionalData.foreground) {
                
            }
            if (data.count) {
                push.setApplicationIconBadgeNumber(function () {
                    console.log('success');
                }, function () {
                    console.log('error');
                }, data.count);
            }
        });

        push.on('error', function (e) {
            console.log(JSON.stringify(e));
        });
```

**Comment by macdonst** [comment]
@sonlexuan what platform are you running on?

**Comment by sonlexuan** [comment]
2017-10-24 11:49:45.739234+0700 TXP-Chat[9661:5805241] Push Plugin register called
2017-10-24 11:49:45.739279+0700 TXP-Chat[9661:5805241] PushPlugin.register: setting badge to false
2017-10-24 11:49:45.739288+0700 TXP-Chat[9661:5805241] PushPlugin.register: clear badge is set to 0
2017-10-24 11:49:45.739304+0700 TXP-Chat[9661:5805241] PushPlugin.register: better button setup
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIApplication registerUserNotificationSettings:]
PID: 9661, TID: 5805241, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   TXP-Chat                            0x0000000100146860 __19-[PushPlugin init:]_block_invoke + 3468
5   libdispatch.dylib                   0x000000010152549c _dispatch_call_block_and_release + 24
6   libdispatch.dylib                   0x000000010152545c _dispatch_client_callout + 16
7   libdispatch.dylib                   0x000000010153156c _dispatch_queue_override_invoke + 980
8   libdispatch.dylib                   0x0000000101536b54 _dispatch_root_queue_drain + 616
9   libdispatch.dylib                   0x0000000101536880 _dispatch_worker_thread3 + 136
10  libsystem_pthread.dylib             0x00000001855fb130 _pthread_wqthread + 1268
11  libsystem_pthread.dylib             0x00000001855fac30 start_wqthread + 4
2017-10-24 11:49:45.746086+0700 TXP-Chat[9661:5805241] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication registerUserNotificationSettings:]
PID: 9661, TID: 5805241, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   TXP-Chat                            0x0000000100146860 __19-[PushPlugin init:]_block_invoke + 3468
5   libdispatch.dylib                   0x000000010152549c _dispatch_call_block_and_release + 24
6   libdispatch.dylib                   0x000000010152545c _dispatch_client_callout + 16
7   libdispatch.dylib                   0x000000010153156c _dispatch_queue_override_invoke + 980
8   libdispatch.dylib                   0x0000000101536b54 _dispatch_root_queue_drain + 616
9   libdispatch.dylib                   0x0000000101536880 _dispatch_worker_thread3 + 136
10  libsystem_pthread.dylib             0x00000001855fb130 _pthread_wqthread + 1268
11  libsystem_pthread.dylib             0x00000001855fac30 start_wqthread + 4
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIApplication registerForRemoteNotifications]
PID: 9661, TID: 5805241, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   TXP-Chat                            0x00000001001468ac __19-[PushPlugin init:]_block_invoke + 3544
5   libdispatch.dylib                   0x000000010152549c _dispatch_call_block_and_release + 24
6   libdispatch.dylib                   0x000000010152545c _dispatch_client_callout + 16
7   libdispatch.dylib                   0x000000010153156c _dispatch_queue_override_invoke + 980
8   libdispatch.dylib                   0x0000000101536b54 _dispatch_root_queue_drain + 616
9   libdispatch.dylib                   0x0000000101536880 _dispatch_worker_thread3 + 136
10  libsystem_pthread.dylib             0x00000001855fb130 _pthread_wqthread + 1268
11  libsystem_pthread.dylib             0x00000001855fac30 start_wqthread + 4
2017-10-24 11:49:48.060746+0700 TXP-Chat[9661:5805241] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication registerForRemoteNotifications]
PID: 9661, TID: 5805241, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   TXP-Chat                            0x00000001001468ac __19-[PushPlugin init:]_block_invoke + 3544
5   libdispatch.dylib                   0x000000010152549c _dispatch_call_block_and_release + 24
6   libdispatch.dylib                   0x000000010152545c _dispatch_client_callout + 16
7   libdispatch.dylib                   0x000000010153156c _dispatch_queue_override_invoke + 980
8   libdispatch.dylib                   0x0000000101536b54 _dispatch_root_queue_drain + 616
9   libdispatch.dylib                   0x0000000101536880 _dispatch_worker_thread3 + 136
10  libsystem_pthread.dylib             0x00000001855fb130 _pthread_wqthread + 1268
11  libsystem_pthread.dylib             0x00000001855fac30 start_wqthread + 4
2017-10-24 11:49:48.183584+0700 TXP-Chat[9661:5805241] FCM Sender ID (null)
2017-10-24 11:49:48.183917+0700 TXP-Chat[9661:5805241] Using APNS Notification
2017-10-24 11:49:48.220488+0700 TXP-Chat[9661:5803229] Push Plugin register failed
2017-10-24 11:49:48.374507+0700 TXP-Chat[9661:5805690] [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
2017-10-24 11:49:48.374 TXP-Chat[9661] <Error> [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
2017-10-24 11:50:03.236585+0700 TXP-Chat[9661:5803229] active
2017-10-24 11:50:03.236630+0700 TXP-Chat[9661:5803229] PushPlugin skip clear badge
2017-10-24 11:50:03.237281+0700 TXP-Chat[9661:5803229] {"line":80,"column":50,"sourceURL":"file:///var/containers/Bundle/Application/87E60A70-24B5-459B-BBCF-DFD2A4287489/TXP-Chat.app/www/plugins/phonegap-plugin-push/www/push.js"}
2017-10-24 11:50:05.284581+0700 TXP-Chat[9661:5803229] active
2017-10-24 11:50:05.284722+0700 TXP-Chat[9661:5803229] PushPlugin skip clear badge

**Comment by macdonst** [comment]
@sonlexuan please try updating to 2.1.0. The error logs seem to indicate this is issue #1988

**Comment by sonlexuan** [comment]
Thank @macdonst.
I finally fixxed this isue when remove this version and back to 1.9.4
I’ll try new version 2.1.0 and hope it work perfectly :D
