### ISSUE TITLE
 Action button does not work without change in plugin's library

### ISSUE THREAD

**Issue by manuvalentim** [phonegap/phonegap-plugin-push#2030]
### Expected Behaviour

When you click an action button, an event associated with its button is expected to be triggered. Like for example, social sharing or open an external link. But for this to happen you need to change the plugin's library. 
How can I do this without changing the phonegap push plugin library?

### Actual Behaviour
For action buttons to work, you need to change a library. I wonder if there is a better way to do this.

```
{
    "to":"/topics/alldevices", 
      "data": {
    	"title": "title message",
    	"message": "message body",
    	"icon":"icon",
    	"color":"#000000",
    	"image":"www/assets/logo.png",   
 "picture":"https://www.coachusa.com/sites/default/files/styles/service_block/public/basic_page/block/images/Meadowlands-Bus-Schedule.jpg?itok=jZBELTg9",
    	"style":"picture",
    	"content-available": 1,
    	"actions": [
        	{ 
            "icon": "open_link", 
	    "title": "Access link", 
            "callback": "access-link", 
            "foreground": "true",
            "link_href": "http://www.site.com.br/"
            },
                    	{ 
            "icon": "share", 
            "title": "Share", 
            "callback": "social-sharing", 
            "foreground": "true",
            "link_href": "http://www.site.com.br/"
            }
        ]
   
    }		
  }
}

`export declare type PushEvent = 'registration' | 'error' | 'notification' | 'link-access' | 'social-sharing';`

```

```
      pushObject.on('link-access').subscribe((data) =>{
          const url = data[0].additionalData.actions[0].link_href;
          window.open(url)
     })
```
```
     pushObject.on('notification').subscribe((data) =>{
        console.log(success)
     })
     
```
```
      pushObject.on('social-sharing').subscribe((data) =>{
       const url = data[0].additionalData.actions[1].link_href;
       const link_picture = data[0].additionalData.picture;
       this.sharing(link_picture, url);
     })     
```

#### Steps to Reproduce 
**Steps**

- Send a push notification with a topic.
- The push notification and action buttons are shown.
- Click on any of the action buttons.
- Open a new link or share. But for this to happen you need to change the plugin's library

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.0.1
    cordova platform version android                     android 6.2.3

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   phonegap-plugin-push 2.0.0 "PushPlugin"

**Comment by fredgalvao** [comment]
(Boa noite!)

@manuvalentim I'm not sure what you're refering to, exactly.

>But for this to happen

By `this`, which one do you mean?:
- the code to compile with proper type definitions on the `.on()` calls (with regards to the `PushEvent` type)
- the code to actually run your action for you (say share or open an external link)

**Comment by macdonst** [comment]
@manuvalentim I don't understand your question. Can you add some more details?

**Comment by loffler** [comment]
I think OP wanted to say, that when we want to define a callback for specific action button, using e.g. `pushObject.on('link-access').subscribe(...)`, 

we got the following error when building the app:
_Argument of type "link-access" is not assignable to parameter of type 'PushEvent'._

Therefore one must redefine the PushEvent with
`export declare type PushEvent = 'registration' | 'error' | 'notification' | 'link-access' ;`
to avoid that error.

**Comment by macdonst** [comment]
@manuvalentim @loffler OIC, it's an issue with the wrapper that Ionic puts around the push plugin. You'll need to create an issue with Ionic.
