### ISSUE TITLE
how many notifications were opened by touch

### ISSUE THREAD

**Issue by manuvalentim** [phonegap/phonegap-plugin-push#2032]
### Expected Behaviour
How do I know that a notification was opened by touch?
I want to receive a value by clicking on the notification. But I won't  receive any value to calculate how many messages were opened.

### Actual Behaviour
Clicking on a notification just open the app. 
 
#### Cordova CLI version and cordova platform version

cordova --version                                    7.0.1
cordova platform version android                     android 6.2.3

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   phonegap-plugin-push 2.0.0 "PushPlugin"

**Comment by macdonst** [comment]
@manuvalentim the best thing to do is to look at `data.additionalData.foreground`. If the value is set to `false` then you know the user tapped the notification in the shade and the app was opened. 

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#callback-parameters-3

It's also smart to add a `notId` property in your payload so you can uniquely identify which notification was tapped.

**Comment by manuvalentim** [comment]
@macdonst Thank you! 
I'm a new problem now. Every time I click on the notification, it closes my app. 
Can you tell me what could be causing this?

**Comment by macdonst** [comment]
@manuvalentim please create a new issue for this and fill out the entire issue template. Logs from the device would be crucial in figuring out what is going on.
