### ISSUE TITLE
A confusing part in the Android section of the installation document

### ISSUE THREAD

**Issue by tamakisquare** [phonegap/phonegap-plugin-push#2033]
Excerpt from _INSTALLATION.md_:
> As of version 2.0.0 the plugin has been switched to using pinned version of Gradle libraries. You will need to ensure that you have installed the following items through the Android SDK Manager:
> 
> Android Support Library version 25.1.0
> FirebaseMessaging Library version 9.8.0

I just upgraded from 1.10 to 2.1.0. Above is part of the installation document for Android, which I skipped because I couldn't find Android Support Library or FirebaseMessaging Library in Android SDK Manager. To my surprise, push notification for my app still works perfectly on Android devices.

This makes me wonder whether this part of the installation document is necessary or even obsolete. Thoughts?

**Comment by macdonst** [comment]
![screenshot 2017-11-20 16 25 33](https://user-images.githubusercontent.com/353180/33042340-7ea60aaa-ce0f-11e7-99f7-4631e4c3d7be.png)
