### ISSUE TITLE
Plugin doesn't support this project's cordova version.

### ISSUE THREAD

**Issue by LioH** [phonegap/phonegap-plugin-push#2034]
### Expected Behaviour
When compiling on PhoneGap Build, the phonegpa-plugin-push is skipped because of an old version of Cordova. But the version I have is the latest one.

Fetching plugin "phonegap-plugin-push@~2.1.0" via npm
Installing "phonegap-plugin-push" at "2.1.0" for android
Plugin doesn't support this project's cordova version. cordova: 7.0.2, failed version requirement: >=7.1.0
Skipping 'phonegap-plugin-push' for android

### Actual Behaviour
PhoneGap Build doens't compile the plugin :(

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
android 6.3.0

#### Cordova CLI version and cordova platform version
    cordova --version                                 7.1.0
    cordova platform version android                     android ~6.3.0

#### Plugin version
    phonegap-plugin-push 2.1.0 "PushPlugin"

**Comment by dmnkgrc** [comment]
@LioH I think that that is your global cordova version, check your package.json, probably there you have cordova version 7.0.2

**Comment by LioH** [comment]
My package-lock.json (in the root) said this : 
`"cordova": {
      "version": "7.1.0",
      "resolved": "https://registry.npmjs.org/cordova/-/cordova-7.1.0.tgz",
      "integrity": "sha1-VZ9TlOZBRcm23YGAD+tljVCHsJY=",
      "requires": {
        "configstore": "2.1.0",
        "cordova-common": "2.1.1",
        "cordova-lib": "7.1.0",
        "editor": "1.0.0",
        "insight": "0.8.2",
        "nopt": "3.0.1",
        "q": "1.0.1",
        "update-notifier": "0.5.0"
      }`

Seems to be the latest version ?

**Comment by dmnkgrc** [comment]
mmm, run npm list and npm list -g, one of them should have the wrong version

**Comment by vincentfierant** [comment]
Could this be referring to the "cordova-ios" package? It was recently updated to 4.5.0 and I got the same message as the above after upgrading to 4.5.0.

**Comment by LioH** [comment]
npm list -g gives cordova@7.1.0
I don't think I have cordova inside the phonegap projet, possible ?

I tried to remove phonegap, cordova, delete the projet, started a new project from scratch, deleted the phonegap build project, and re-install everything with cordova first. I got the exact same problem.

`npm install -g cordova
/usr/local/bin/cordova -> /usr/local/lib/node_modules/cordova/bin/cordova
+ cordova@7.1.0

npm install -g phonegap
Success: "/usr/local/lib/node_modules/phonegap/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
+ phonegap@7.1.1

which phonegap
/usr/local/bin/phonegap

which cordova 
/usr/local/bin/cordova`

I'ml lost :(

**Comment by macdonst** [comment]
@LioH the currently supported versions of cordova on PGB can be found here:

https://build.phonegap.com/current-support

as you can see it does not yet support cordova 7.1.0 or cordova-android 6.3.0. The PGB team is working on it but for now when building on PGB you'll need to use 2.0.0.
