### ISSUE TITLE
Can't resolve all parameters for Push: (?, ?).

### ISSUE THREAD

**Issue by babajipokharkar** [phonegap/phonegap-plugin-push#2035]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
Please fill out the issue template
