### ISSUE TITLE
App does not open when I tap the notification

### ISSUE THREAD

**Issue by devfelipereis** [phonegap/phonegap-plugin-push#2036]
### Expected Behaviour
Open the app when I tap the notification.

### Actual Behaviour
The app does not open and the notification disappear.

#### Steps to Reproduce 
I just installed the plugin, did some configs and launch the app. Then I close the app and sent a notification to the device using the **registrationId**.

My push configs:

```
var pushConfigs = {
                android: {
                    senderID: XXXXXXXXX
                },
                ios: {
                    badge: true,
                    sound: true
                }
            };
```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.1.2
Android 4.3

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Motorola Moto x2 (7.1.2)
Sansung GT-I9300 (4.3)

#### Cordova CLI version and cordova platform version

    cordova --version  -> 6.5.0
    cordova platform version android ->  6.1.2

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push -> 1.10.5

I was also testing with 1.9.4

#### Sample Push Data Payload
I'm using https://cordova-plugin-fcm.appspot.com/ to test. 

#### Logs taken while reproducing problem

> 10-26 14:26:23.145 30133 26903 I ActivityManager: START u0 {act=FCM_PLUGIN_ACTIVITY flg=0x10000000 pkg=XXXXXXX (has extras)} from uid 10210 on display 0
10-26 14:26:23.151 31727 31727 D LogHelper: MXMNotificationListener - removed notification: MYAPPIDXXX
10-26 14:26:23.152 31727 31727 I LogHelper: MXMNotificationListener - sendNotificationRemoved: StatusBarNotification(pkg=XXXXXX user=UserHandle{0} id=0 tag=GCM-Notification:154696852 key=0|XXXXXX|0|GCM-Notification:154696852|10210: Notification(pri=0 contentView=null vibrate=null sound=content://settings/system/notification_sound defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE))
10-26 14:26:23.159 30133 26849 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@ad294e8 attribute=null, token = android.os.BinderProxy@3f08d41
10-26 14:26:23.477 30133 30150 I ActivityManager: Setting hasTopUi=false for pid=30536
10-26 14:26:23.479 30536 30536 D PhoneStatusBar: disable: < expand icons* alerts system_info* back home recent clock search quick_settings >
10-26 14:26:26.990 26978 27029 I ThermalEngine: Sensor:batt_therm:37800 mC
10-26 14:26:27.080 26978 27030 I ThermalEngine: Sensor:chg_therm:35000 mC

**Comment by macdonst** [comment]
@devfelipereis so the site you are using to do testing is probably sending everything in the `notification` part of the payload, not `data`. Please read: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

You will be better off using a node script or curl to do your testing.
