### ISSUE TITLE
2.0.0 GCM android suppport [Question]

### ISSUE THREAD

**Issue by bolivir** [phonegap/phonegap-plugin-push#2037]
Hi, 

Does version> 2.0.0 still support GCM for android? Because its always throwing me a error about the google-services.json file.

**Comment by macdonst** [comment]
@bolivir the 2.0.0 release uses FCM. If you have an old GCM project you'll still be able to send to that SENDER_ID but the plugin will need to read the info from a google-services.json file that you download from Google.
