### ISSUE TITLE
Push notification not working in iOS 10.3.2 and above

### ISSUE THREAD

**Issue by etakh** [phonegap/phonegap-plugin-push#2041]
Hi,

my environment below.

**Platform and Version** 
iOS 10.3.2

**Cordova CLI version and cordova platform version**
cordova --version                                    7.0.1
cordova platform version ios                   4.3.1

**Plugin version**
cordova plugin version | grep phonegap-plugin-push   1.9.4

I am using APNS production certificate and turned on push notifications in Xcode project target capabilities but still, I am unable to receive push notification in my iPhone6. Can anyone give a hint or solution for this?

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
