### ISSUE TITLE
cannot build project in xcode9

### ISSUE THREAD

**Issue by MateusAndrade** [phonegap/phonegap-plugin-push#2045]
### Actual Behaviour

When i run cordova build ios, using the plugin with the version 2.1.0 i get the following error:

`** BUILD FAILED **
The following build commands failed:
	CopyPlistFile /Users/telesinfo/documents/TerminalCordovaIOS/platforms/ios/build/emulator/Terminal\ Profissional.app/GoogleService-Info.plist /Users/telesinfo/Documents/Documents/TerminalCordovaIOS/platforms/ios/Terminal\ Profissional/Resources/GoogleService-Info.plist
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/telesinfo/documents/TerminalCordovaIOS/platforms/ios/cordova/build-debug.xcconfig,-workspace,Terminal Profissional.xcworkspace,-scheme,Terminal Profissional,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone X,build,CONFIGURATION_BUILD_DIR=/Users/telesinfo/documents/TerminalCordovaIOS/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/telesinfo/documents/TerminalCordovaIOS/platforms/ios/build/sharedpch`

I place my GoogleService-Info.plist inside my root folder, and added the <resource-file> for ios.

I checked and i got cocoa pods installed on my last version, but my ruby and gem version looks older than recommended:

```
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
2.0.14.1
```

Maybe this would be the problem?

**Comment by MateusAndrade** [comment]
I update my cordova version and ios ios to the latest version and i fixed that error, but when i try to build after running: 

`cd platforms/ios && pod install`

I get this error:

`** BUILD FAILED **


The following build commands failed:
	CompileC /Users/telesinfo/Library/Developer/Xcode/DerivedData/Terminal_Profissional-cjsfmeajkepssybsrksluxglykhr/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Protobuf.build/Objects-normal/x86_64/Any.pbobjc.o Protobuf/objectivec/google/protobuf/Any.pbobjc.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/telesinfo/Library/Developer/Xcode/DerivedData/Terminal_Profissional-cjsfmeajkepssybsrksluxglykhr/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Protobuf.build/Objects-normal/x86_64/Empty.pbobjc.o Protobuf/objectivec/google/protobuf/Empty.pbobjc.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/telesinfo/documents/TerminalCordovaIOS/platforms/ios/cordova/build-debug.xcconfig,-workspace,Terminal Profissional.xcworkspace,-scheme,Terminal Profissional,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone X,build,CONFIGURATION_BUILD_DIR=/Users/telesinfo/documents/TerminalCordovaIOS/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/telesinfo/documents/TerminalCordovaIOS/platforms/ios/build/sharedpch`

Maybe it would be my ruby and gem version( both of them looks deprecated, but until today i dont get any problem )?

**Comment by MateusAndrade** [comment]
I successfull run my app, through terminal and received a test notification doing this:

`pod setup`

To ensure that the pods are installed i used `cd platforms/ios && pod install` and then i build my app without problems. I can even run on device and send notifications. If you have any problem try to update your ruby installation, brew, etc. If you have the plugin already added try removing him and adding again.

But i got another problem: when i open my project on xcode i got the following error:

`ld: warning: directory not found for option '-L/Users/telesinfo/Library/Developer/Xcode/DerivedData/Terminal_Profissional-digtzcrgasivqvfaepdjsedttmpv/Build/Intermediates.noindex/ArchiveIntermediates/Terminal Profissional/BuildProductsPath/Release-iphoneos/GoogleToolboxForMac'
ld: warning: directory not found for option '-L/Users/telesinfo/Library/Developer/Xcode/DerivedData/Terminal_Profissional-digtzcrgasivqvfaepdjsedttmpv/Build/Intermediates.noindex/ArchiveIntermediates/Terminal Profissional/BuildProductsPath/Release-iphoneos/Protobuf'
ld: warning: directory not found for option '-L/Users/telesinfo/Library/Developer/Xcode/DerivedData/Terminal_Profissional-digtzcrgasivqvfaepdjsedttmpv/Build/Intermediates.noindex/ArchiveIntermediates/Terminal Profissional/BuildProductsPath/Release-iphoneos/nanopb'
ld: library not found for -lGoogleToolboxForMac
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I tried doing a pod install inside ios project, but at this time i dont get success fixing this error. What can i do to fix this?

**Comment by macdonst** [comment]
@MateusAndrade are you opening the project or the workspace? When opening the app in Xcode always use the workspace as it includes the app project and cocoapod project.

**Comment by MateusAndrade** [comment]
@macdonst i was importing the project. I imported the workspace and now its works without problems, thanks. =D

**Comment by macdonst** [comment]
@MateusAndrade no problem, you are not the first person to have this happen to them.

**Comment by MateusAndrade** [comment]
@macdonst i see this on some searchs, maybe it would be good to specify on the installation this problem. 

Another thing: i dont find nothing about migrating from the version 1.X to 2.X, did you have some docs about this?

**Comment by macdonst** [comment]
Re-opening so I will remember to write the docs.

**Comment by MateusAndrade** [comment]
@macdonst I would be glad if i can help with the docs.  =D

**Comment by macdonst** [comment]
@MateusAndrade pull requests are always welcome.

**Comment by napcat** [comment]
Thank you for this report...

I'm having the same error 65. I was removing and installing plugin one by one, and it error 65 appear when the push plugin was installed. I will try to do a "pod install" inside the platform/ios directory and see if it fix the situation.

**Comment by MateusAndrade** [comment]
@napcat try doing a cordova clean, followed by a pod install. At least, import the **Workspace** on xcode, not the project. Since some Cordova version(or even the plugin) importing the .project doenst work well.

Hope it helps. :)
