### ISSUE TITLE
push.on no any js action in android 5.1

### ISSUE THREAD

**Issue by aihosting** [phonegap/phonegap-plugin-push#2048]
```
 <engine name="android" spec="^6.3.0" />
    <engine name="browser" spec="^5.0.1" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.2" />
    <plugin name="phonegap-plugin-push" spec="^2.1.0">
        <variable name="FCM_VERSION" value="11.0.1" />
```

push.on no any action in android 5.1
and no show any error alert
i test in nox emulator 4.4 show error = PHONE_REGISTRATION_ERROR
in samsung gt-i8262 5.1 no alert any error and no any action ,but jquery is work
test in android studio emulator 4.x 5.x 6.x is fine , can show the registration token 
test in other china phone android 4.2 can work

my index.js file

````
document.addEventListener("deviceready",onDeviceReady,false);

function onDeviceReady(){

var push = PushNotification.init({
android: { senderID: xxxxxxxxxx
},
ios: {
alert: "true",
badge: "true",
sound: "true"
},
windows: {}
});

push.on('registration', function(data) { alert(data.registrationId);
$("#regid").val(data.registrationId);
console.log('registration event: ' + data.registrationId);
});
push.on('notification', function(data) {
});
push.on('error', function(e) {
            alert("push error = " + e.message);
});
}


$(document).ready(function() {
$("#deviceready").click(function() {
var regid=$("#regid").val();  window.alert(regid); 
$.ajax({
url: "http://192.168.1.88/work/push.php",
type: "POST",
dataType:'text',
data: {postjs:1,regid:regid},
success: function(data){alert(data);} });
}); 

});  
```
`

**Comment by macdonst** [comment]
@aihosting testing the in emulator is not valid. It should be done on a real phone. If your phone does not include Google Play Services you will not be able to use this plugin.

**Comment by aihosting** [comment]
@macdonst  hi  but the android5.1 phone is got google play service, other app like wechat can receive push..   and the nox emulator got google play service too
do u know how can show the error log in app frontend?

**Comment by macdonst** [comment]
@aihosting better idea, run `adb logcat | grep Push` to see what is going on.

**Comment by aihosting** [comment]
@macdonst   is got any api requirement of push 2.1?
cause my android is 5.1 but my api version is 16(android4.1)..  my rom is update myself

**Comment by macdonst** [comment]
@aihosting I've tested from Android 4.4 and up. Don't have devices running anything earlier than that. Like I said, logs would really help.

**Comment by aihosting** [comment]
@macdonst   hi i cant run adb logcat | grep Push  this command 
and i connect by phone and debug by android studio but cant see the adb log of push error
no any log about this push/irebase, other log got show
![untitled](https://user-images.githubusercontent.com/16357853/32615222-2b13147c-c5aa-11e7-86f8-fb92c1a3b278.png)

**Comment by aihosting** [comment]
@macdonst   hi now i can see the log got my device fcm token
but it not show in device js alert ,it show in log only
and when i send via fcm console, it cannot receive the push message
i send with php ,php say  {"multicast_id":5012478364900741472,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1510301990060231%fc8b4fcefc8b4fce"}]}


11-10 16:18:11.960 16501-16501/ai4.aihosting.ai4 D/CordovaBridge: Ignoring exec() from previous page load.
11-10 16:18:12.060 16501-16530/ai4.aihosting.ai4 D/Push_InsIdService: Refreshed token: fFICPAPndgE:APA91bEfi4sqwnKWFyDEdABn2zD8RNlTf0Ns6QtMzogJWMCFVZ4opw67I_KWoh0CJGIUHcXvLrB26vcgls0V_3-u0pCUpViUfVZc1_gFugpJF49cG26bofdnh9ExufUelBdDivCY0kDG
11-10 16:18:13.990 16501-16519/ai4.aihosting.ai4 D/FA: Logging event (FE): session_start(_s), Bundle[{firebase_event_origin(_o)=auto, firebase_screen_id(_si)=-107365783512037303, firebase_screen_class(_sc)=MainActivity}]
11-10 16:18:14.060 16501-16519/ai4.aihosting.ai4 D/FA: Connected to remote service
11-10 16:18:57.250 16501-16501/ai4.aihosting.ai4 D/HorizontalFling: OverScroller.fling() velocityX=0, ro.fling.distance.coef=1.0
11-10 16:18:57.250 16501-16501/ai4.aihosting.ai4 D/HorizontalFling: SplineOverScroller.fling() getSplineFlingDistance(velocity)=0.0, getSplineFlingDuration(velocity)=0, mFinal=0
11-10 16:18:57.260 16501-16501/ai4.aihosting.ai4 D/HorizontalFling: SplineOverScroller.fling() getSplineFlingDistance(velocity)=0.0, getSplineFlingDuration(velocity)=0, mFinal=0
11-10 16:19:24.060 16501-16501/ai4.aihosting.ai4 I/dalvikvm: Could not find method android.app.NotificationManager.getNotificationChannels, referenced from method com.adobe.phonegap.push.FCMService.createNotification
11-10 16:19:24.060 16501-16501/ai4.aihosting.ai4 W/dalvikvm: VFY: unable to resolve virtual method 340: Landroid/app/NotificationManager;.getNotificationChannels ()Ljava/util/List;
11-10 16:19:24.060 16501-16501/ai4.aihosting.ai4 D/dalvikvm: VFY: replacing opcode 0x74 at 0x0200
11-10 16:19:24.080 16501-16680/ai4.aihosting.ai4 I/dalvikvm: Could not find method android.app.Notification$Builder.setColor, referenced from method com.google.firebase.messaging.zza.zza
11-10 16:19:24.080 16501-16680/ai4.aihosting.ai4 W/dalvikvm: VFY: unable to resolve virtual method 259: Landroid/app/Notification$Builder;.setColor (I)Landroid/app/Notification$Builder;
11-10 16:19:24.080 16501-16680/ai4.aihosting.ai4 D/dalvikvm: VFY: replacing opcode 0x6e at 0x0034
11-10 16:19:24.090 16501-16680/ai4.aihosting.ai4 I/dalvikvm: Could not find method android.content.Context.getSystemService, referenced from method com.google.firebase.messaging.zza.zzhs
11-10 16:19:24.090 16501-16680/ai4.aihosting.ai4 W/dalvikvm: VFY: unable to resolve virtual method 592: Landroid/content/Context;.getSystemService (Ljava/lang/Class;)Ljava/lang/Object;
11-10 16:19:24.090 16501-16680/ai4.aihosting.ai4 D/dalvikvm: VFY: replacing opcode 0x6e at 0x000d
11-10 16:19:24.130 16501-16680/ai4.aihosting.ai4 D/Push_FCMService: onMessage - from: 781758474110
11-10 16:19:31.580 16501-16520/ai4.aihosting.ai4 D/webview: blockWebkitViewMessage= false

**Comment by macdonst** [comment]
@aihosting try forcing an update of the Play Store and Play Services on your device. I see a bunch of errors about missing methods.

**Comment by aihosting** [comment]
@macdonst   hi try uninstall update cannot, and reinstal update also cannot
but i go try fcm test app in playstore, that can success register token and show the token in app
so i think this plugin or cordova got some bug in lower api device

**Comment by macdonst** [comment]
@aihosting is a library mis-match problem. Version 2.x of this plugin uses FCM. When you see logs like:

```
16680/ai4.aihosting.ai4 I/dalvikvm: Could not find method android.app.Notification$Builder.setColor, referenced from method com.google.firebase.messaging.zza.zza
11-10 16:19:24.080 16501-16680/ai4.aihosting.ai4 W/dalvikvm: VFY: unable to resolve virtual method 259: Landroid/app/Notification$Builder;.setColor (I)Landroid/app/Notification$Builder;
11-10 16:19:24.080 16501-16680/ai4.aihosting.ai4 D/dalvikvm: VFY: replacing opcode 0x6e at 0x0034
11-10 16:19:24.090 16501
```

where the JVM can't find methods it means the library on the device is out of date. Upgrading the libs on device should fix this problem.

**Comment by aihosting** [comment]
https://play.google.com/store/apps/details?id=com.yu.firebase.quickstart.fcm 
but i go try install this from playstore, no problem  can show the token...

**Comment by macdonst** [comment]
@aihosting I have no idea what that app uses in the background. All I can tell you is that your device is complaining about missing methods in the FCM library.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
