### ISSUE TITLE
Led is not working, vibration is not working

### ISSUE THREAD

**Issue by sdavidg** [phonegap/phonegap-plugin-push#2049]
### Expected Behaviour
Led and vibration should work

### Actual Behaviour
Led and vibration are not working

### Reproduce Scenario

	var paramsHeader = {};
	paramsHeader["Authorization"] = "key=xxx";
	paramsHeader["Content-Type"] = "application/json";
	
	var paramsCuerpo = {};
	paramsCuerpo["to"] = "yyy";
	paramsCuerpo["notification"] = {
		"title": "Title",
		"body": "Body"
		ledColor: [0, 0, 255, 0],
		vibrationPattern: [2000, 1000, 500]
	};
	
	$.ajax({
		url: "https://fcm.googleapis.com/fcm/send",
		type: 'post',
		dataType: 'json',
		beforeSend: function (xhrObj)
		{
			for(var i in paramsHeader)
			{
				xhrObj.setRequestHeader(i, paramsHeader[i]);
			}
		},
		data: JSON.stringify(paramsCuerpo),
	});

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
 Xiaomi Redmi Note 4, Android 7.0
 bq Aquaris M5, Android 6.0.1
iPhone 8,2,  iOS 11.0.3

#### Cordova CLI version and cordova platform version
    cordova --version = 7.1.0
    cordova platform version android = android 6.3.0

#### Plugin version
    phonegap-plugin-push 2.1.0

**Comment by macdonst** [comment]
@sdavidg try using:

```
paramsCuerpo["data"] = {
	"title": "Title",
	"body": "Body"
	ledColor: [0, 0, 255, 0],
	vibrationPattern: [2000, 1000, 500]
};
```

instead as per: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

**Comment by sdavidg** [comment]
Thanks, works fine
