### ISSUE TITLE
ServiceWorker.js Folder Instead of File

### ISSUE THREAD

**Issue by MaxLFarrell** [phonegap/phonegap-plugin-push#2052]
### Expected Behaviour
ServiceWorker.js placed in root www directory on build
### Actual Behaviour
ServiceWorker.js place in www/ServiceWorker.js/ServiceWorker.js
### Reproduce Scenario (including but not limited to)
1. Add plugin to project
2. Build
#### Steps to Reproduce 
Seen above
#### Platform
Browser
#### Cordova CLI version and cordova platform version

    cordova --version                                    7.1.0
    cordova platform version browser                     5.0.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.0.0

**Comment by macdonst** [comment]
@MaxLFarrell can you run `cordova platforms` so I can see what version of the browser platform you are using?

**Comment by MaxLFarrell** [comment]
```
Installed platforms:
  android 6.3.0
  browser 5.0.1
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  ios ~4.5.1
  osx ~4.0.1
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0
  windows ~5.0.0
  www ^3.12.0
```

**Comment by macdonst** [comment]
@MaxLFarrell this is a bug in the newly release cordova-browser platform. I've create a JIRA issue for it at:

https://issues.apache.org/jira/browse/CB-13562

Can you please go vote for it there? 

Once it gets fixed in the browser platform I will update this plugin to use the new version. Sadly, as of now I don't have a work around as adding the earlier cordova-browser platform is not possible.

**Comment by MaxLFarrell** [comment]
Done, I have voted and am watching, thank you.

**Comment by macdonst** [comment]
@MaxLFarrell thanks for reporting this, hopefully we can get it fixed quickly. Unfortunately my sample project had an older version of cordova-browser already installed so it slipped past me.

**Comment by macdonst** [comment]
@MaxLFarrell bug got fixed in cordova-browser and as soon as their is a new release I'll update this plugin to use it as a dependency.

**Comment by MaxLFarrell** [comment]
Great thank you!

**Comment by MaxLFarrell** [comment]
Any update on this?

**Comment by macdonst** [comment]
@MaxLFarrell working on it but, and I honestly can't believe this but it looks like we need to update cordova-lib.
