### ISSUE TITLE
can NOT install phonegap-plugin-push in Shanghai, China

### ISSUE THREAD

**Issue by nodejscss** [phonegap/phonegap-plugin-push#2053]
In order to install phonegap-plugin-push, there must be two file, 
    google-services.json and GoogleService-Info.plist, that generated by FCM.
And the FCM is from firebase.google.com. However, many many many people, including me, 
can NOT access the firebase.google.com in China .

So, how to install the phonegap-plugin-push in China ?

**Comment by nodejscss** [comment]
It is STRONGLY suggested that FCM should be dparted from phonegap-plugin-push like as phonegap-plugin-scan which can be installed alone.

If anyone wants FCM, he may install phonegap-plugin-fcm or phonegap-plugin-firebase. And he need NOT install phonegap-plugin-push.

So, Please dpart FCM or firebase from phonegap-plugin-push. Please.

**Comment by macdonst** [comment]
@nodejscss sorry the FCM library is a requirement to be able to receive push messages on Android. I would be interested in hearing more about how one receives a push on an Android device in China. Do manufacturers implement their own push services?

**Comment by jcesarmobile** [comment]
You can install v1.10.5 of the plugin, that uses GCM instead of FCM, but not sure if GCM is available in china, and as far as I know you can't create new projects there.

**Comment by nodejscss** [comment]
Yes. GCM is also not avaliable in China.

I think that you can use the FCM library to receive push message on Android, but do not use google-services.json and GoogleService-Info.plist. I can implement the server to register device token and send push message to device.

**Comment by macdonst** [comment]
@nodejscss sorry but the plugin relies on a library from Google with reads google-services.json and GoogleService-Info.plist to setup the communication with the push service.
