### ISSUE TITLE
Notification autoclears when using content-available

### ISSUE THREAD

**Issue by echonox** [phonegap/phonegap-plugin-push#2054]
### Expected Behaviour
The Notification should not autoclear it self when using content-available to fire onNotification event when the notification is received

### Actual Behaviour
The Notification autoclears it self when using content-available to fire onNotification event when the notification is received

### Reproduce Scenario (including but not limited to)
send "content-available": "1" from backend to the app

#### Steps to Reproduce 
- run the app in background
- send "content-available": "1" including message for the push notification from backend

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung
#### Cordova CLI version and cordova platform version

    cordova --version   7.1.0                                 # e.g. 6.0.0
    cordova platform version android        6.3.0             # e.g. 4.1.1

#### Plugin version
2.1.0

#### Sample Push Data Payload

`{"title":"Sample Title",
"message":"The content message",
"additionalData":{
         "content-available":"1"
}}`

**Comment by macdonst** [comment]
@echonox have you tried setting `clearNotifications` to false in the init options?

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushnotificationinitoptions

**Comment by echonox** [comment]
@macdonst  I tried it but it does not work

**Comment by echonox** [comment]
@macdonst the notification is first shown and then after a second or so it gets cleared

**Comment by echonox** [comment]
@macdonst after further debugging I've found out that the local notification plugin was clearing the notification closing the issue!
