### ISSUE TITLE
on('notification') event triggered and notification auto clears when force-starting app

### ISSUE THREAD

**Issue by echonox** [phonegap/phonegap-plugin-push#2055]
### Expected Behaviour
The on('notification') event should not be triggered when force-starting killed app after receiving the notification and should not auto clear the notification

### Actual Behaviour
The on('notification') event gets triggered and the Notification autoclears it self when starting killed app using "force-start": 1

### Reproduce Scenario (including but not limited to)
send "force-start": 1 from backend to the app

#### Steps to Reproduce 
- kill the app
- send "force-start": 1 from backend
- also include message for the push notification
-> app gets started and the on('notification') event gets triggered
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung
#### Cordova CLI version and cordova platform version

    cordova --version   7.1.0                                 # e.g. 6.0.0
    cordova platform version android        6.3.0             # e.g. 4.1.1

#### Plugin version
2.1.0

#### Sample Push Data Payload

`{"title":"Sample Title",
"message":"The content message",
"additionalData":{
         "force-start":"1"
}}`

**Comment by macdonst** [comment]
@echonox how is this different from #2054

**Comment by echonox** [comment]
@macdonst content-available should trigger on('notification') but not clear the notification and force-start should not trigger the on('nottification'), they are similar, but they are caused by different parameters, thats I why I opened separate issues

**Comment by macdonst** [comment]
@echonox if force-start is in the payload the notification will start the app and the call `on('notification')`.

**Comment by echonox** [comment]
@macdonst can we somehow prevent the on notification to be called?

**Comment by echonox** [comment]
@macdonst also in this case the notification gets auto cleared

**Comment by echonox** [comment]
@macdonst after further debugging I've found out that the local notification plugin was clearing the notification closing the issue!
