### ISSUE TITLE
App starts in foreground on receiving a force-start notification

### ISSUE THREAD

**Issue by echonox** [phonegap/phonegap-plugin-push#2056]
### Expected Behaviour
The App should start in background using "force-start" parameter
### Actual Behaviour
The app starts in foreground
### Reproduce Scenario (including but not limited to)

I initialize the plugin with this config:
`{ "android": {"senderID": "{senderId}", forceShow: true, clearNotifications: false}`

**The goal of the repro is to simulate: app killed by the android os (to free up resources)**
#### Steps to Reproduce 
- Go to settings
- developer options
- and prevent that activities are kept in background
-  open the app
- tap the home button
-> the app will be killed
- send a push notification using "force-start": 1 parameter
- the push notification is received
-> the app starts in foreground

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android Marshmallow 6.0.1
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung
#### Cordova CLI version and cordova platform version

    cordova --version       7.1.0                  
    cordova platform version android       6.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push  2.1.0

#### Logs taken while reproducing problem
I did a bit debugging and even though the plugin says that the app will start in background the main activity does not receive the "cdvStartInBackground" Extra which i guess makes the app start in foreground

**Comment by echonox** [comment]
@macdonst can you repro?

**Comment by macdonst** [comment]
@echonox what do you actually want to happen in this case? If that developer option is on then the app would be killed if it is put in the background by force-start. I'm not sure it's worthwhile to put a bunch of effort into this issue considering it's not recommend for users to run with this option turned on normally.

**Comment by echonox** [comment]
@macdonst  the idea is to simulate, force kill by the android os, thats why i use that setting in developer option

**Comment by macdonst** [comment]
@echonox can you try turning that switch off, starting the app, noting the registration ID, swiping the app away in the task runner (i.e. force kill), then sending a push to the app? That is more of a real world test.

**Comment by mikepsinn** [comment]
To work around this, I added a function to my user object to make sure it only uses force-start on the 1st notification.

```
    /**
     * Can only use force start on first notification on Android or it brings the app to the foreground
     * @return int
     */
    public function getForceStartForPushNotification(){
        if($this->forceStartOnPush === 0){return 0;}
        $this->forceStartOnPush = 0;
        return 1;
    }
```
Then in the push function:
```
    private function getPostFields(){
        $pushData = (array) $this->getPushData();
        $pushData['foreground'] = false; // event handler will be called without the app being brought to the foreground
        $pushData['content-available'] = 1; 
        $pushData['force-start'] = $this->getUser()->getForceStartForPushNotification(); 
        $postFields['data'] = $pushData;
        $postFields['to'] = $this->getDeviceTokenObject()->deviceToken;
        return $this->postFields = json_encode($postFields);
    }
```
