### ISSUE TITLE
Why does this bookstore not work with PhoneGap Build 7.1?

### ISSUE THREAD

**Issue by SectionOne** [phonegap/phonegap-plugin-push#2057]
### Actual Behaviour
Upon upgrading the Phonegap version, the library stopped working and I no longer get the GCM Regid

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Phonegap Build 7.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy S6 Edge Plus

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

<plugin name="phonegap-plugin-push" spec="~1.4.5" source="npm" />

Thank you and I hope you can guide me

**Comment by macdonst** [comment]
@SectionOne the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
