### ISSUE TITLE
I'm getting MismatchSenderId when try to send notification

### ISSUE THREAD

**Issue by ximiodev** [phonegap/phonegap-plugin-push#2058]
### Expected Behaviour
send a notification to an android phone

### Actual Behaviour
PHonegapcli

### Reproduce Scenario (including but not limited to)

the registration event unveiled me a registrationId, and when I try to use it to send a notification using curl (curl_setopt ($ ch, CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send');) I returned {"multicast_id" : 8990045162552064429, "success": 0, "failure": 1, "canonical_ids": 0, "results": [{"error": "MismatchSenderId"}]}

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android (ANY)

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung gallaxy j7 and samsng GT-S5301

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

phonegap-plugin-push   2.0.0

#### Logs taken while reproducing problem

in phonegap I urge you like this:
var push = PushNotification.init ({
"android": {}
});

in the config.xml I added this line:

```
<platform name = "android">
<resource-file src = "google-services.json" target = "google-services.json" />
</ platform>
```

(that file I downloaded it from firebase and I put it in the root where is the config.xml)

**Comment by macdonst** [comment]
@ximiodev the problem is exactly what is returned from your attempt to send a push. The device registers with one SENDER_ID but the api key (and FCM project) you are using is under a different SENDER_ID.
