### ISSUE TITLE
Inline replies for iOS on the roadmap?

### ISSUE THREAD

**Issue by danielcrk** [phonegap/phonegap-plugin-push#2060]
Hi! Is inline replies for iOS somewhere on the roadmap for this plugin?

Thanks!

**Comment by macdonst** [comment]
#1273

**Comment by danielcrk** [comment]
So your answer is linking to an over a year old issue - which doesn't contain the answer. Thanks!

**Comment by macdonst** [comment]
@danielcrk thanks for the passive aggressive comment! Open source software maintainers really appreciate that. 

I mean it's not like you:

a) didn't bother to take the time to fill out the issue template and 
b) didn't bother to search the past issues to see if it had been already reported and comment on that issue

Maintaining an open source project takes up a lot of time and I can't get to every feature. Pull Requests are always welcome from the community though!

**Comment by jcesarmobile** [comment]
Doesn't answer the "is it on the roadmap?" question, but it's open and he said it was a good idea. Also added the feature label.

So, is it on the roadmap? well, I don't think there is even an official roadmap.

PRs are always welcomed.
