### ISSUE TITLE
Localization in message not working after PR #1666 (Android)

### ISSUE THREAD

**Issue by kelvinhokk** [phonegap/phonegap-plugin-push#2061]
### Expected Behaviour

According to the documentation in PAYLOAD.md, localisation should happen properly with the localisation key to the actual message.
```
{
    "registration_ids": ["my device id"],
    "data": {
        "message": {"locKey": "push_message_fox", "locData": ["fox", "dog"]}
    }
}
```
### Actual Behaviour

After changes due to PR #1666 and Issue #1663, messages are not localised properly anymore.  The result of the payload after passing through the onMessage will be an empty extra in the above example.

### Reproduce Scenario (including but not limited to)

Send a payload 
```
{
    "registration_ids": ["my device id"],
    "data": {
        "message": {"locKey": "push_message_fox", "locData": ["fox", "dog"]}
    }
}
```
#### Steps to Reproduce 

Use the latest phonegap-push-plugin 2.1.0

Reverting to the old method in normalizeExtras prior to PR #1666 will localise message correctly.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Android. All

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.1.0
    cordova platform version android          6.3.0

#### Plugin version

2.1.0

#### Sample Push Data Payload

{
    "registration_ids": ["my device id"],
    "data": {
        "message": {"locKey": "push_message_fox", "locData": ["fox", "dog"]}
    }
}

#### Analysis

Relevant section in normalizeExtras method.

```
      if (key.equals(PARSE_COM_DATA) || key.equals(MESSAGE) || key.equals(messageKey)) {
        Object json = extras.get(key);
        // Make sure data is json object stringified
        if (json instanceof String && ((String) json).startsWith("{")) {
          try {
            // If object contains message keys promote each value to the root of the bundle
            JSONObject data = new JSONObject((String) json);
            if (data.has(ALERT) || data.has(MESSAGE) || data.has(BODY) || data.has(TITLE) || data.has(messageKey) || data.has(titleKey)) {
              // data has locKey and locData and does not fall in this block.
              // ...
            }
          } catch (JSONException e) {
          }
        } else {
          // data is JSON and does not fall in this block
          String newKey = normalizeKey(key, messageKey, titleKey);
          Log.d(LOG_TAG, "replace key " + key + " with " + newKey);
          replaceKey(context, key, newKey, extras, newExtras);
        }
      } else if (key.equals(("notification"))) {
        //.. "data" node does not fall here.        

      // This is the change made by PR#1666
      // See issue #1663
      } else {
        // as a result of the change, message does not get localized because it does not fall in here.
        String newKey = normalizeKey(key, messageKey, titleKey);
        Log.d(LOG_TAG, "replace key " + key + " with " + newKey);
        replaceKey(context, key, newKey, extras, newExtras);
      }
```

**Comment by macdonst** [comment]
@kelvinhokk merged the change, I'll do a new release to pull in the fix soon.
