### ISSUE TITLE
Background notifications not opening application to foreground

### ISSUE THREAD

**Issue by Nick-Ewer** [phonegap/phonegap-plugin-push#2063]
### Expected Behaviour
When app is in background, opening a notification should open the app to foreground and run onNotification

### Actual Behaviour
App does run onNotificaiton, but app does not appear in foreground. App no longer exists in active app tray, however opening the app from the icon (which would expect a cold start given that the app does not appear to be running) will instead open to the expected notification page.

#### Steps to Reproduce 
- Receive push notification while app is active in the background
- Open notification

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8.0.0, Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Google Pixel (v1), Nexus 5

#### Cordova CLI version and cordova platform version
cordova 7.1.0, cordova-android 6.3.0

#### Plugin version
2.1.0

#### Sample Push Data Payload

Payload data from server to GCM:
```
data: {
          title: 'New Comment',
          message: "Test user replied to comment #33.",
          route: "/comments/5a0dc34573e39c35760722d4",
          notId: 653
          image: 'icon',
          soundname: 'default'
        }
```

Data received in app by onNotification handler
```
data: {
  additionalData: {
    coldstart : true
    content-available :  "1"
    foreground :  false
    notId : "653"
    priority : "high"
    route: "/comments/5a0dc34573e39c35760722d4"
  },
  image : "icon"
  message : "Test user replied to comment #33."
  sound : "default"
  title : "New Comment"
}
```

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem

Possibly Irrelevant:

```
[ 11-17 14:35:18.335 18134:18150 W/AndroidGcmController ]
Unable to handle inbound message: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.android.chrome/com.google.ipc.invalidation.ticl.android2.TiclService (has extras) }: app is in background uid UidRecord{526e247 u0a56 RCVR idle procs:1 seq(0,0,0)}
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.android.chrome/com.google.ipc.invalidation.ticl.android2.TiclService (has extras) }: app is in background uid UidRecord{526e247 u0a56 RCVR idle procs:1 seq(0,0,0)}
  at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
  at android.app.ContextImpl.startService(ContextImpl.java:1461)
  at android.content.ContextWrapper.startService(ContextWrapper.java:644)
  at org.chromium.chrome.browser.services.gcm.ChromeGcmListenerService.onMessageReceived(ChromeGcmListenerService.java:59)
  at com.google.android.gms.gcm.O.handleIntent(Unknown Source:10)
  at com.google.firebase.z.M.run(Unknown Source:3)
  at java.util.concurrent.ThreadPoolExecutor.ru
```

**Comment by macdonst** [comment]
@Nick-Ewer can you check to see if this applies to you? 

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#clicking-notification-does-not-bring-app-to-foreground

**Comment by Nick-Ewer** [comment]
Perfect, works great now. Thanks!
