### ISSUE TITLE
Disable multiple select files photos in iOS devices

### ISSUE THREAD

**Issue by DhanasekaranGit** [phonegap/phonegap-plugin-push#2064]
I have used the in html page & run the device for iOS.

`<input` type="file" value="name" accept="image/*"/>`

But iOS have upload the multiple on device.

How to restrict the single file upload in iOS device for jquery or javascript.

Tell the solution for single file upload code in **iPad & iPhone devices**.

**Comment by macdonst** [comment]
@DhanasekaranGit sorry, this issue has nothing to do with this plugin. Please ask on the PhoneGap forums: https://forums.adobe.com/community/phonegap
