### ISSUE TITLE
PushNotification is undefined

### ISSUE THREAD

**Issue by k-yle** [phonegap/phonegap-plugin-push#2067]
### Expected Behaviour
`PushNotification` should be an object. 

It used to work fine (last time I used it was ~2 weeks ago)

### Actual Behaviour
`PushNotification` is `undefined`. 

#### Steps to Reproduce 
`cordova plugin add phonegap-plugin-push`     
...
`cordova prepare`

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
```sh
λ cordova plugins
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-statusbar 1.0.1 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
phonegap-plugin-barcodescanner 6.0.8 "BarcodeScanner"
phonegap-plugin-push 2.1.0 "PushPlugin"
```
config.xml:
```xml
    <platform name="android">
        <preference name="android-minSdkVersion" value="16" />
        ...
        <resource-file src="google-services.json" target="google-services.json" />
    </platform>
    ...
    <plugin name="phonegap-plugin-push" spec="^2.1.0">
        <variable name="FCM_VERSION" value="11.0.1" />
        <variable name="SENDER_ID" value="1:.............:android:............................" />
    </plugin>
```
I've included a `google-services.json` file.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung S7

#### Cordova CLI version and cordova platform version
```sh
λ cordova -v
7.1.0
```

```sh
λ cordova platform version android
Installed platforms:
  android 6.3.0
  browser 5.0.1
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  ios ~4.5.1
  osx ~4.0.1
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0
  windows ~5.0.0
  www ^3.12.0
```
#### Plugin version
```sh
λ cordova plugin version | FINDSTR phonegap-plugin-push
phonegap-plugin-push 2.1.0 "PushPlugin"
```

#### Sample Push Data Payload
n/a

#### Sample Code that illustrates the problem
```js
document.addEventListener('deviceready', () => {
    alert(typeof PushNotification); // 'undefined'
});
```

#### Logs taken while reproducing problem
no logs matching "`Push`":
```sh
λ adb logcat | FINDSTR Push
```

**Comment by neverflatz** [comment]
Same problem here , need solution

**Comment by macdonst** [comment]
@k-yle well without seeing logs it's hard to diagnose but in this case the logs would be when the app is built.

However, you should probably look at removing:

```
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
```

from your app. Crosswalk because it's not needed post Android 5.0 and the FCM one because it might conflict with this one.

**Comment by neverflatz** [comment]
@macdonst im not using crosswalk and fcm tok . But pusnotif is undefined :(

**Comment by macdonst** [comment]
@neverflatz yeah, you need to give me more info.

**Comment by neverflatz** [comment]
@k-yle 
```
<?xml version='1.0' encoding='utf-8'?>
<widget id="XXXX" version="2.3.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>XXXX</name>
    <description>
       XXX
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        XXXX
    </author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name='phonegap-version' value='cli-7.0.1' />
    <preference name='pgb-builder-version' value='2' />
    <platform name="android">
        <preference name="android-minSdkVersion" value="16" />
        <allow-intent href="market:*" />
        **<resource-file src="google-services.json" target="google-services.json" />**
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <preference name="BackupWebStorage" value="none" />
        **<resource-file src="GoogleService-Info.plist" />**
    </platform>
    
    <icon src="img/icon2.png" />
    <icon src="img/drawable-ldpi/icon2.png" platform="android" qualifier="ldpi" />
    <icon src="img/drawable-mdpi/icon2.png" platform="android" qualifier="mdpi" />
    <icon src="img/drawable-hdpi/icon2.png" platform="android" qualifier="hdpi" />
    <icon src="img/drawable-xhdpi/icon2.png" platform="android" qualifier="xhdpi" />
    <icon src="img/drawable-xxhdpi/icon2.png" platform="android" qualifier="xxhdpi" />
    <icon src="img/drawable-xxxhdpi/icon2.png" platform="android" qualifier="xxxhdpi" />
    
 
 
    <preference name="DisallowOverscroll" value="true" />
    <plugin name="cordova-plugin-whitelist" spec="~1.2.0" />
    <plugin name="cordova-plugin-console" spec="~1.0.1" />
    <plugin name="cordova-plugin-statusbar" spec="~1.0.1" />
    <plugin name="cordova-plugin-camera" spec="~2.3.1" />
    <plugin name="cordova-sqlite-storage"  spec="~1.2.1"/>
    <plugin name="cordova-plugin-geolocation" spec="~2.4.1" />
    <preference name="android-build-tool" value="gradle" />
    **<plugin name="phonegap-plugin-push" spec="~2.1.0" />**
    <plugin name="cordova-plugin-network-information" spec="~1.3.1" />
    <plugin name="cordova-plugin-file-transfer" spec="~1.6.1" />
    <plugin name="cordova-plugin-inappbrowser" spec="~1.7.1" />
    <plugin name="cordova-plugin-file" spec="~4.3.1" />
    <plugin name="cordova-plugin-mauron85-background-geolocation" source="npm" spec="~2.2.5">
        <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="11.0.1" />
    </plugin>
</widget>

```

**Comment by neverflatz** [comment]
@macdonst  its works like a charm when i remove mauron bacground location ... 
its like conflict with google play service version , any solution?

**Comment by macdonst** [comment]
@neverflatz right, so the error must show up when you build the app. What do those logs look like?

**Comment by neverflatz** [comment]
@macdonst 
`* Where:
Build file '/project/build.gradle' line: 258

* What went wrong:
A problem occurred evaluating root project 'project'.
> Could not get unknown property 'GOOGLE_PLAY_SERVICES_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.459 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Build file '/project/build.gradle' line: 258

* What went wrong:
A problem occurred evaluating root project 'project'.
> Could not get unknown property 'GOOGLE_PLAY_SERVICES_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
`

**Comment by k-yle** [comment]
@macdonst I removed `cordova-plugin-crosswalk-webview` and `cordova-plugin-fcm` [as you suggested](https://github.com/phonegap/phonegap-plugin-push/issues/2067#issuecomment-346235824), and everything works again. 
Thank you very much!

**Comment by neverflatz** [comment]
@k-yle  congrats, mine still conflict with mauron-background geoolocation .. :(

**Comment by neverflatz** [comment]
@macdonst  whats this push v2.0.0 google play services it is 11.0.1 ?? 
This is mauron says `For compatibility with other plugins you may also set specific google play version. Following example will lock google play services to version 11.0.1 for compatibility with phonegap-plugin-push. Note: Always consult documentation of other plugins to figure out correct GOOGLE_PLAY_SERVICES_VERSION.`

i tried it but no luck

**Comment by macdonst** [comment]
@k-yle np, I'm going to close this issue then.

@neverflatz can you open a new issue that specifically calls out the incompatibility between the two plugins? Please fill out the full issue template.
