### ISSUE TITLE
phonegap-plugin-push ionic 1 can't receive notification

### ISSUE THREAD

**Issue by S3r3n4** [phonegap/phonegap-plugin-push#2069]
### Reproduce Scenario (including but not limited to)
Hi everybody,
I'm new to use phonegap-plugin-push with ionic v1, I am finding this problem: when I send a notification my device does not receive it. The registration part works and I get the device tocken, but after that I don't receive notifications or errors when I send a notification by server. I'm sure the server sends a correct notification.

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.0.1
    cordova platform version android                     6.2.3

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.0.0

#### Sample Code that illustrates the problem
my code:
app.js

             `.run(function ($ionicPlatform, $window, $rootScope,ToastService,LocalStorageHelper) {
                $ionicPlatform.ready(function () {

        if (window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
            cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
            cordova.plugins.Keyboard.disableScroll(true);

        }
        if (window.StatusBar) {

            StatusBar.styleDefault();
        }

        const push = PushNotification.init({
            android: {
                senderID: "MY FIREBASE PROJECT ID", 
                sound: "true",
                vibrate: "true",
                icon: "phonegap",
                iconColor: "blue"
            },
            browser: {
                pushServiceURL: 'http://push.api.phonegap.com/v1/push'
            },
            ios: {
                alert: "true",
                badge: "true",
                sound: "true"
            },
            windows: {}
        });

        push.hasPermission((data) => {
            console.log('hasPermission data=')
            if (data.isEnabled) {
                console.log('isEnabled');
            }
        });

        push.on('registration', (data) => {
            // data.registrationId
            console.log('*****************')
            console.log('push success data=',data);
            console.log('*****************')
            LocalStorageHelper.setDeviceToken(data.registrationId)
        });

        push.on('notification', (data) => {
            // data.message,
            // data.title,
            // data.count,
            // data.sound,
            // data.image,
            // data.additionalData
            console.log('*****************')
            console.log('push notification data=',data);
            console.log('*****************')
        });

        push.on('error', (e) => {
            // e.message
            console.log('*****************')
            console.log('push Error data=',data);
            console.log('*****************')
        });

    });}`

      

config.xml

        ` <plugin name="phonegap-plugin-push" spec="^2.0.0"/>           
           <platform name="android">
           <resource-file src="google-services.json" target="google-services.json" />
            </platform>
           <platform name="ios">
           <resource-file src="GoogleService-Info.plist" />
            </platform>`

pakage-json

     `"plugins": {
        "cordova-plugin-inappbrowser": {},
        "cordova-plugin-whitelist": {},
        "cordova-plugin-x-toast": {},
        "phonegap-plugin-barcodescanner": {
            "CAMERA_USAGE_DESCRIPTION": ""
        },
        "cordova-plugin-camera": {
            "CAMERA_USAGE_DESCRIPTION": " ",
            "PHOTOLIBRARY_USAGE_DESCRIPTION": " "
        },
        "cordova-plugin-file": {},
        "cordova-plugin-file-transfer": {},
        "cordova-plugin-email-composer": {},
        "phonegap-plugin-push": {}
    }

Thanks in advance!

**Comment by macdonst** [comment]
@S3r3n4 what does your payload look like? What do you see when running `adb logcat | grep Push`?

**Comment by S3r3n4** [comment]
hi, thanks for your reply! 
After running adb logcat | grep Push I get:

11-22 17:33:09.873  8389  8407 D SPPClientService: PushLog.txt file is not deleted.
11-22 17:33:09.873  8389  8407 D SPPClientService: PushLog.txt file is not deleted.
11-22 17:33:09.873  8389  8407 D SPPClientService: ============PushLog. stop!
11-22 17:35:03.233  9610  9665 D Push_InsIdService: Refreshed token: elYnb3z9Jjo:APA91bFkXpsrAHeIfGsMeHmJcc0hS2pAdGUfg5IB6SMW7j6b0lE6Ev3DDG9B6oNCDrvoUUUrkMfbtw9GoAhE1msWeU9fTVzU6-o5Nt7rWLepaUGwsK3-6PP5MZ7v11433eRoi5Dnb9xk
11-22 17:35:05.403  9610  9734 V Push_Plugin: execute: action=hasPermission
11-22 17:35:05.473  9610  9734 V Push_Plugin: execute: action=init
11-22 17:35:05.473  9610  9735 V Push_Plugin: execute: data=[{"android":{"senderID":"pjoon.com:platform-storeden"},"browser":{"pushServiceURL":"http:\/\/push.api.phonegap.com\/v1\/push"},"ios":{"alert":"true","badge":"true","sound":"true"},"windows":{}}]
11-22 17:35:05.473  9610  9735 V Push_Plugin: execute: jo={"senderID":"pjoon.com:platform-storeden"}
11-22 17:35:05.473  9610  9735 V Push_Plugin: execute: senderID=1005267570499
11-22 17:35:05.473  9610  9735 V Push_Plugin: onRegistered: {"registrationId":"elYnb3z9Jjo:APA91bFkXpsrAHeIfGsMeHmJcc0hS2pAdGUfg5IB6SMW7j6b0lE6Ev3DDG9B6oNCDrvoUUUrkMfbtw9GoAhE1msWeU9fTVzU6-o5Nt7rWLepaUGwsK3-6PP5MZ7v11433eRoi5Dnb9xk","registrationType":"FCM"}
11-22 17:35:05.473  9610  9735 D Push_Plugin: no icon option
11-22 17:35:05.473  9610  9735 D Push_Plugin: no iconColor option

**Comment by macdonst** [comment]
@S3r3n4 Yeah, so you are getting the registration ID fine. What logs, if any do you see when you send the push to the device? Also, I need to see your payload.

**Comment by S3r3n4** [comment]
I had try to catch the log when notification arrives on device but adb logcat |grep Push not write log.
I don't have the payload sent because i haven't access to the sender server

**Comment by macdonst** [comment]
@S3r3n4 how are you sending the push.

**Comment by S3r3n4** [comment]
I use the website connected to old app, I send a message from website.
After that on the old app i get a notification.
I would see the notification on new app.

**Comment by macdonst** [comment]
@S3r3n4 I'm not getting the necessary info I need in order to help you. Without more information they only think I can guess at is that your app is registering with a different project than the website is setting pushes to.

**Comment by S3r3n4** [comment]
Hi, 
I had found the correct project, but now when I send the notification the app crashes without any error.
The adb logcat | greap push give me this when this app starts: 

11-27 10:13:10.661  1108  1108 I GservicesProvider: Gservices pushing to system: true; secure/global: true
11-27 10:13:11.001   820  4785 I ActivityManager: Killing 28238:com.sec.spp.push/u0a58 (adj 15): DHA:empty #37
11-27 10:13:11.011   820  1745 D ActivityManager: isAutoRunBlockedApp:: com.sec.spp.push, Auto Run ON
11-27 10:24:12.671  4235  4362 V Push_Plugin: execute: data=[{"android":{"senderID":"289396574454"},"browser":{"pushServiceURL":"http:\/\/push.api.phonegap.com\/v1\/push"},"ios":{"alert":"true","badge":"true","sound":"true"},"windows":{}}]
11-27 10:24:12.681  4235  4235 D SystemWebChromeClient: file:///android_asset/www/js/app.js: Line 85 : push success data=
11-27 10:24:12.681  4235  4235 I chromium: [INFO:CONSOLE(85)] "push success data=", source: file:///android_asset/www/js/app.js (85)

What can I do to resolve the problem?

**Comment by S3r3n4** [comment]
To use phonegap-plugin-push I need install also cordova-plugin-fcm?

**Comment by macdonst** [comment]
@S3r3n4 no, in fact that would be really bad as the two plugins would conflict with each other.

**Comment by S3r3n4** [comment]
Ok, thanks so much, what can I do to find the reason of crash of my app?

**Comment by S3r3n4** [comment]
Hi,
now the plugin works! :) I had change some configuration of cordova plugin facebook4, maybe the  two plugins was conflict but I'm not sure of that.
Thanks so much for your help!!! :)

**Comment by macdonst** [comment]
@S3r3n4 https://github.com/phonegap/phonegap-plugin-push/blob/9afac3882d93f445f800be681b1ac491ececd7ff/docs/INSTALLATION.md#co-existing-with-facebook-plugin
