### ISSUE TITLE
Background notification will trigger twice event for ' push.on('notification', callback) '

### ISSUE THREAD

**Issue by xiaoaowanghu** [phonegap/phonegap-plugin-push#2072]
### Reproduce Scenario (including but not limited to)
send background notification to moble 
as
{
"data": {
    	"title": "Test Push",
    	"body": "xxxxx",
    	"content-available": "1",
        "soundname":"default"
    }
}

Let the app run in background, After mobile receive the notification, click on the notification bar, then the app go to foreground. And will find the onnotification event triggered twice. Is this as design?

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4.4

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.0.1
    cordova platform version android          6.2.2

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.0.0

#### Sample Push Data Payload
{
"data": {
    	"title": "Test Push",
    	"body": "xxxxx",
    	"content-available": "1",
        "soundname":"default"
    }
}

**Comment by macdonst** [comment]
@xiaoaowanghu yes, it's by design. You'd need to add a `notId` or some unique data to let your app know that the notification was already handled.
