### ISSUE TITLE
Registration subscribtion fires 2 times.

### ISSUE THREAD

**Issue by bolivir** [phonegap/phonegap-plugin-push#2073]
### Expected Behaviour
When the user starts the app, it shows the permission dialog (IOS) for push notifications. If the user hits deny or allow we dont trigger the registration event again.

### Actual Behaviour
When the user starts the app, it shows the permission dialog (IOS) for push notifications. When i look at the xcode debugger i see Push Plugin register success : <token> without performing any action on the permission popup.
Tapping allow in the permission popup performs the same result as before and triggers the registration again because i see the following message again in the console Push Plugin register success : <token>.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
IOS 11

**Comment by macdonst** [comment]
Same as #1438, please comment on that issue.
