### ISSUE TITLE
Can`t received in IOS

### ISSUE THREAD

**Issue by NazarKalytiuk** [phonegap/phonegap-plugin-push#2074]
### Expected Behaviour
Notification must be received in IOS
### Actual Behaviour
Token is well registered but no notification received in background and in foreground. In android everything is working.
#### Steps to Reproduce 
* Open app
* You can see registrationId in alert
* Can`t receive push notifications
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
    IOS 11.0.1
#### Cordova CLI version and cordova platform version

    cordova --version                        7.0.1
    cordova platform version ios              4.4.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.0.0

#### Sample Push Data Payload
I tried use console.firebase.com and postman
```
{
 "to" : "registrationId",
 "notification" : {
 "body" : "Test",
 "title" : "Test"
 "content_available" : true,
 "priority" : "high",
 }
}
```
#### Sample Code that illustrates the problem
```
onDeviceReady: function () {
        this.receivedEvent('deviceready');
        var push = PushNotification.init({
            android: {},
            browser: {
                pushServiceURL: 'http://push.api.phonegap.com/v1/push'
            },
            ios: {
                alert: "true",
                badge: true,
                sound: 'false'
            },
            windows: {}
        });
         push.on('registration', (data) => {
                 alert(JSON.stringify(data.registrationId));
         }
}
```

**Comment by macdonst** [comment]
@NazarKalytiuk Need some more information:

1. What does your registration ID look like?
2. Are you trying to send via prod or dev?
3. What do the logs look like in Xcode?

**Comment by NazarKalytiuk** [comment]
@macdonst 1. e1_3d_ZdC3s:APA91bHDlPFsey68LKfAIVhM7NexL1qhy3rC7nd4IGm0gc9dqz8Pvo6SWP_u4boNs74VOC8ICVSQUYcnzvpsK-fXSPtfQp3DSstd-Q0qMwyd7gTgVz_Kpuug05eBPyP-N409Gnh46g55
2. Prod via build.phonegap.com
3. no logs, because I use build.phonegap.com

**Comment by macdonst** [comment]
@NazarKalytiuk what I said in this comment holds true for you as well:

https://github.com/phonegap/phonegap-plugin-push/issues/2078#issuecomment-347212551

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
