### ISSUE TITLE
Plugin Install Error

### ISSUE THREAD

**Issue by qwe123wsx** [phonegap/phonegap-plugin-push#2075]
Using Phonegap 7.1.1, when i run phonegap plugin add phonegap-plugin-push

#### Plugin version
2.1.1

#### Logs taken while reproducing problem
Failed to install 'phonegap-plugin-push': Error [ERR_UNHANDLED_ERROR]: Unhandled error. (The platform "browser" does not appear to be a valid cordova platform. It is missing API.js. browser not supported.)

**Comment by macdonst** [comment]
@qwe123wsx remove your browser platform, install the latest, then try to install the plugin
