### ISSUE TITLE
Clear push notifications using Clear All notification button on Status bar , push.on('notification') not triggering

### ISSUE THREAD

**Issue by praveenpds** [phonegap/phonegap-plugin-push#2076]
### Expected Behaviour
Any Notifications received for App will be in Status bar and that can be cleared any time by Clear All button

For all notifications  pushObject.on('notification') should trigger

### Actual Behaviour

1 - Clear All  Push notifications, app is not able to trigger  pushObject.on('notification') 
2- Click on Any push notifiction  pushObject.on('notification'). not triggering 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Motog4plus ( not tested other cells)
#### Cordova CLI version and cordova platform version

phonegap-plugin-push": "1.10.5"
"@ionic-native/push": "4.2.1",.

Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.0
Angular Core: 5.0.0
Angular Compiler CLI: 5.0.0
Node: 6.10.3

**Comment by macdonst** [comment]
@praveenpds sorry that's not how the plugin is supposed to operate. If you click the "clear all" button on Android the notifications will be dismissed and no events will be fired. The events only fire on user interaction or when you use the background (i.e. content-available) property.
