### ISSUE TITLE
Click on Pushnotification , Application launched but pushObject.on('notification'). not triggering

### ISSUE THREAD

**Issue by praveenpds** [phonegap/phonegap-plugin-push#2077]
### Expected Behaviour
Push notification received when App is minimized and clicking on Notification, app should launch and 
pushObject.on('notification').  should trigger

### Actual Behaviour

Push notification received by phone when app is minimized and clicking on Push notification, its launches App, but pushObject.on('notification'). not triggering

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 7

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Motog4plus ( not tested other cells)

#### Cordova CLI version and cordova platform version
phonegap-plugin-push": "1.10.5"
"@ionic-native/push": "4.2.1",
Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.0
Angular Core: 5.0.0
Angular Compiler CLI: 5.0.0
Node: 6.10.3

Payload

```json
{
   "to":"fCMtoken",
   "notification":{
      "title":"Alert",
      "body":"Vehicle"
   },
   "data":{
      "notificationObject":{
         "Vehicle":"Vehicle xxxx serviced "
      },
      "summary":{
         "driverName":"Praveen",
         "vehicleId":108
      }
   }
}
```
JS 

initPushNofiticationRegistrationProcess() {
    
        const pushObject: PushObject = this.push.init({
            android: {
                senderID: SENDER_ID,
                vibrate: true
            },
            ios: {
            },
            windows: {}
        }); 

        this.push.hasPermission().then(data => {
            console.log(data);
            if (data.isEnabled) {
                console.log('isEnabled');
            } else {
                this.showInfoToaster('Notification is blocked by User !!! Please Enable');
            }
        }).catch(err => {
            console.log(err);
        })

        pushObject.on('registration').subscribe((response) => {
            console.log('token', response['registrationId']);
        });

        pushObject.on('notification').subscribe((response) => {
            pushObject.getApplicationIconBadgeNumber().then(c => {
                console.log(c);
            })
            this.events.publish('notification');
        });

        pushObject.on('error').subscribe((e) => {
            console.error('push notifi-error', e['message']);          
        });
    }

**Comment by fredgalvao** [comment]
According to you, your payload is:
```json
{
   "to":"fCMtoken",
   "notification":{
      "title":"Alert",
      "body":"Vehicle"
   },
   "data":{
      "notificationObject":{
         "Vehicle":"Vehicle xxxx serviced "
      },
      "summary":{
         "driverName":"Praveen",
         "vehicleId":108
      }
   }
}
```

But according to [the docs on the payload section for android](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads):
> If you send a payload with a mix of notification & data objects like this:
...
When your app is in the foreground any on('notification') handlers you have registered will be called. If your app is in the background, the notification will show up in the system tray. **Clicking on the notification in the system tray will start the app and your on('notification') handler will not be called as messages that have notification payloads will not cause the plugins onMessageReceived method to be called**.

So, to make your payload work on all use cases, you need to use the recommended format (from the docs), which is to **not** use a `notification` section, and instead send everything on the `data` section.

Make note, this only applies to Android. The docs have all the details on the differences between APNS/GCM/FCM payloads to both platforms, but we welcome suggestions to improve readability there.

I'm closing this, but if after using the recommended format the issue still applies, feel free to reopen with  more details.

**Comment by praveenpds** [comment]
Tried the below format , added user info in 'data' section as said in the doc , still the app is not responding   for  "  on('notification')  "
 
{
   "to":"fCMtoken",
   "notification":{
      "title":"Alert",
      "body":"Vehicle"
   },
   "data":{
       "driverName":"Praveen",
         "vehicleId":108,
        "notificationObject":{
                "Vehicle":"Vehicle xxxx serviced "
        },
      "summary":{
         "driverName":"Praveen",
         "vehicleId":108
      }
   }
}

**Comment by fredgalvao** [comment]
I still see the `notification` section on your payload. The point was/is exactly to remove that, and only use the `data` section.

**Comment by praveenpds** [comment]
Tried removing the notification section and kept all user info  in 'data' key, 

due to this change Push notification had failed to appear on system tray.

Without appearing on system tray how user will navigate to app ?

Do I need to fire simultaniously two different payload one for data n one for notification ??

Thanks in Advance

**Comment by macdonst** [comment]
@praveenpds this payload should show up in the tray:

```
{
   "to":"fCMtoken",
   "data":{
      "title":"Alert",
      "body":"Vehicle",
      "driverName":"Praveen",
      "vehicleId":108,
      "notificationObject":{
         "Vehicle":"Vehicle xxxx serviced "
      },
      "summary":{
         "driverName":"Praveen",
         "vehicleId":108
      }
   }
}
```

If you are not seeing this payload show up in the tray we'll need to see the logs from `adb logcat | grep Push` when you send a push to the device.

**Comment by praveenpds** [comment]
Super it works fine :)
