### ISSUE TITLE
Could not get unknown property 'FCM_VERSION'

### ISSUE THREAD

**Issue by kevinmarsden88** [phonegap/phonegap-plugin-push#2079]
### Reproduce Scenario (including but not limited to)

Install the plugin in an ionic project via : 
$ ionic cordova plugin add phonegap-plugin-push
$ npm install --save @ionic-native/push

Then build : 
ionic cordova build android --release

Result : 

FAILURE: Build failed with an exception.

* Where:
Build file '..\build.gradle' line: 263

* What went wrong:
A problem occurred evaluating root project 'android'.
> Could not get unknown property 'FCM_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

#### Cordova CLI version and cordova platform version

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.1
    npm  : 5.5.1
    OS   : Windows 10

#### Plugin version

    2.1.1

**Comment by macdonst** [comment]
@kevinmarsden88 in order to do the variable replacement in the framework tag you must be using [cordova-commons 2.1.0](http://cordova.apache.org/news/2017/09/05/cordova-common-2.1.0.html) or greater. It doesn't seem like the version of ionic you are using has picked up this dependency. Probably better off asking on the Ionic Forums.

**Comment by kevinmarsden88** [comment]
Steps to resolve : 
1) Remove package.json and package-lock.json as well as node_modules folder.
2) Run NPM install after updating dependencies as follows : 
 "dependencies": {
    "@angular/common": "5.0.1",
    "@angular/compiler": "5.0.1",
    "@angular/compiler-cli": "5.0.1",
    "@angular/core": "5.0.1",
    "@angular/forms": "5.0.1",
    "@angular/http": "5.0.1",
    "@angular/platform-browser": "5.0.1",
    "@angular/platform-browser-dynamic": "5.0.1",
    "@ionic-native/camera": "^4.4.2",
    "@ionic-native/core": "4.4.2",
    "@ionic-native/device": "^4.4.2",
    "@ionic-native/diagnostic": "^4.4.0",
    "@ionic-native/file": "^4.4.2",
    "@ionic-native/file-opener": "^4.3.3",
    "@ionic-native/push": "^4.4.2",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/status-bar": "4.4.0",
    "@ionic/storage": "2.1.3",
    "cordova-android": "6.3.0",
    "cordova-plugin-camera": "^3.0.0",
    "cordova-plugin-device": "^1.1.7",
    "cordova-plugin-file": "^5.0.0",
    "cordova-plugin-file-opener2": "^2.0.19",
    "cordova-plugin-filechooser": "^1.0.1",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.3.0",
    "cordova-plugin-whitelist": "^1.3.1",
    "cordova-sqlite-storage": "^2.1.2",
    "cordova.plugins.diagnostic": "^3.7.2",
    "ionic-angular": "^3.9.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "phonegap-plugin-push": "^2.1.1",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.2",
    "typescript": "2.4.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-sqlite-storage": {},
      "cordova-plugin-whitelist": {},
      "ionic-plugin-keyboard": {},
      "cordova-plugin-file-opener2": {},
      "cordova-plugin-filechooser": {},
      "cordova.plugins.diagnostic": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-file": {},
      "cordova-plugin-camera": {},
      "cordova-plugin-device": {},
      "phonegap-plugin-push": {
        "FCM_VERSION": "11.0.1"
      },
      "cordova-plugin-ionic-webview": {}
    },
    "platforms": [
      "android"
    ]
3) Drag and drop a copy of your google-services.json file(https://support.google.com/firebase/answer/7015592?hl=en) to your android platform folder.
4) Remove the android platform to clear out old gradle script : 
ionic cordova platform rm android
5) Build the project : 
ionic cordova build android --release

Thank you @macdonst for pointing me in the right direction,oh and one more tip for anyone reading this,if all else fails install the plugin in a clean project generated with the latest CLI and see if it works there !
