### ISSUE TITLE
Ability to call unregister without calling init first

### ISSUE THREAD

**Issue by Papipo** [phonegap/phonegap-plugin-push#208]
Is it possible to unregister a device without registering it first?
I have this preference pane with a checkbox to "Receive notifications", and when set to false, it's supposed to call unregister().

The problem is that in order to do that, it has to call init() first, and since they run concurrently, it unregisters and quickly registers again.

Thanks.

**Comment by lmmfranco** [comment]
+1

**Comment by QimatLuo** [comment]
+1

**Comment by vitorOta** [comment]
+1
