### ISSUE TITLE
Android: default sound for single notification is playing repeatedly every approx 60 seconds

### ISSUE THREAD

**Issue by yogeshwar238** [phonegap/phonegap-plugin-push#2080]
#### Steps to Reproduce: 
1.Send Single push notification from cloud
2. Notification is received by mobile app, custom sound is played then immediately after that default sound is getting played for every 60 seconds

#### Cordova CLI version and cordova platform version: cordova cli 

    cordova --version : 7.0.1                              
    cordova platform version android   : 6.1.2              

#### Sample Push Data Payload:
{"sound":"coin","title":"ABCD","message":"MeassgeTest:27/11/17 20:03:00","additionalData":{"TestPart":"1","content-available":"1","username":"XYZ","code":"CL","text":"TestUserMessageText","user":"51","timestamp":"1511812996","event":"TestEvent","group":"TEstGroup","verbose":"User Quick","google.message_id":"0:aphaNumericString","vibrationPattern":[0,2000,0,2000],"ledColor":[0,255,0,0],"coldstart":true,"foreground":false,"affects-partition":"1"}}

#### Sample Code that illustrates the problem
  var options = {
            android: {
                senderID: senderId,
                sound: 'default',
                vibrate: true,
                clearBadge: true
            },
            ios: {
                alert: "true",
                sound: "true",
                clearBadge: true
            },
            windows: {}
        };

#### Logs taken while reproducing problem:
data notification:{"sound":"coin","title":"ABCD","message":"MeassgeTest:27/11/17 20:03:00","additionalData":{"TestPart":"1","content-available":"1","username":"XYZ","code":"CL","text":"TestUserMessageText","user":"51","timestamp":"1511812996","event":"TestEvent","group":"TEstGroup","verbose":"User Quick","google.message_id":"0:aphaNumericString","vibrationPattern":[0,2000,0,2000],"ledColor":[0,255,0,0],"coldstart":true,"foreground":false,"affects-partition":"1"}}

**Comment by macdonst** [comment]
@yogeshwar238 a few clarifying questions:

1. What does the actual payload you send look like, not what your receive?
2. Can you run `adb logcat | grep Push` while receiving the message to gather logs?

**Comment by dotnetdreamer** [comment]
i am having same issue. The notification keeps popuping up (repeating itself) only in android. @yogeshwar238  did you get any luck on this ?

**Comment by yogeshwar238** [comment]
Sorry for delayed response. Issue is now resolved at my end.

It was cause of Samsung device. it has setting to remind unread notifications periodically. 
I set it to off.

**Comment by dotnetdreamer** [comment]
@yogeshwar238 no. I am getting it in OnePlus also. I pushed 3 notifications. One to iPhone 6s, Note 5, and One Plus 3. Android devices are pushing it again and again, not just sound but also notification even if Wifi is off! but iphone works fine.

**Comment by yogeshwar238** [comment]
@dotnetdreamer. 
For android devices, please check settings/Accessibilty/Notification reminder ON
This solved my issue.  Hope yours too.

**Comment by dotnetdreamer** [comment]
@yogeshwar238 its off. I tried the cordova fcm plugin also. It seems to be an issue with FCM server or android....every message i send using REST api, its showing in device again and again even if i turn of WIFI.

**Comment by jbae1024** [comment]
i have same problem

**Comment by macdonst** [comment]
Closing as original issue reported by @yogeshwar238 is resolved and @dotnetdreamer has the issue using more than one plugin so it is not this plugin's issue. More likely related to the device itself.
