### ISSUE TITLE
when i add ios is .init it is not working at all neither in android

### ISSUE THREAD

**Issue by sana4591** [phonegap/phonegap-plugin-push#2083]
when I add IOS in .init code is not working at all neither in android
my code is uploaded.

[phonegap.zip](https://github.com/phonegap/phonegap-plugin-push/files/1513494/phonegap.zip)

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
