### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by datastone** [phonegap/phonegap-plugin-push#2086]
### Expected Behaviour

debug build on android

### Actual Behaviour

Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script platforms\android\phonegap-plugin-push\starter-push.gradle' line: 38

A problem occurred evaluating root project 'android'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"

#### Cordova CLI version and cordova platform version

    cordova --version                                     7.1.0
    cordova platform version android                      6.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push  ^2.1.1

**Comment by hardcpp** [comment]
+1

**Comment by macdonst** [comment]
@datastone can you run `cordova plugins` so I can see what plugins you are using? In push plugin 2.1.1 we specify a FCM version of 11.0.1 so it's not coming from this plugin. It must be coming from another plugin you are including.

**Comment by macdonst** [comment]
@hardcpp not sure if you know but "+1" on issues are not very useful. If you want to vote up an issue you can use the [emoji reactions](https://github.com/blog/2119-pull-request-and-issue-reactions) to achieve the same thing.

**Comment by datastone** [comment]
@macdonst 
```
cordova plugins
```
com-sarriaroman-photoviewer 1.1.11 "PhotoViewer"
cordova-plugin-appminimize 1.0 "AppMinimize"
cordova-plugin-camera 3.0.0 "Camera"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.1.0 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"

**Comment by macdonst** [comment]
@datastone can you do me a favour and remove `cordova-plugin-googlemaps` from your app and build with `phonegap-plugin-push`. I believe that it is this line:

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/plugin.xml#L157

That is causing your problem. Upon confirmation, I'll look at sending a PR to that plugin.

@matteobattista for your project, same thing but remove `cordova-admob-sdk` instead.

**Comment by matteobattista** [comment]
@macdonst thanks for your reply... If I remove cordova-plugin-admob-free (with cordova-admob-sdk), my project build ok!
How can i fix this? Is it possible to have this two plugin at the same time?
Thank you

**Comment by datastone** [comment]
@macdonst it works. please update the google maps plugin.
please give me the fix version of google map plugin

**Comment by macdonst** [comment]
@datastone & @matteobattista I will have to send PR's to the other plugins in order to have them play nicely with the push plugin.

**Comment by macdonst** [comment]
@matteobattista I sent a PR, please feel free to give it a 👍  to let the dev know it's a wanted update.

**Comment by macdonst** [comment]
@datastone I sent a PR, please feel free to give it a 👍  to let the dev know it's a wanted update:

https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/1938

**Comment by macdonst** [comment]
@datastone the maintainer of the googlemaps plugin doesn't seem to be interested in compatibility or accepting my PR. 

https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1937

You may have to build off of my fork.

https://github.com/macdonst/cordova-plugin-googlemaps/

**Comment by wf9a5m75** [comment]
@macdonst Can you guarantee to follow the version up forever? If no, you should not provide the repo as solution. The JS developer should do on their own risk.

**Comment by macdonst** [comment]
@wf9a5m75 nope, I'm hoping we can come to some kind of a agreement. I was offering up my fork so @datastone could get unstuck with building the app.

**Comment by matteobattista** [comment]
Thanks to @macdonst, the new cordova-plugin-admob-free version (0.13.0) fix the issue.

**Comment by macdonst** [comment]
@matteobattista glad it's working for you. If you run into other plugins that have the same problem working with the push plugin please let me know by creating a new issue and I'll send PR to their maintainers.

@datastone sorry, but @wf9a5m75 is not going to merge my PR so you will have to either use my fork for now or better you create your own fork that tracks changes.
