### ISSUE TITLE
Push template app works on iOS but not on Android

### ISSUE THREAD

**Issue by josegrad** [phonegap/phonegap-plugin-push#2089]
The steps here http://docs.phonegap.com/tutorials/develop/push-notifications/ work fine with iOS.

However with Android it just doesn't work

```
setupPush: function() {
        console.log('calling push init');  <------ STAYS HERE
        var push = PushNotification.init({
            "android": {
                "senderID": "XXXXXXXX"
            },
            "browser": {},
            "ios": {
                "sound": true,
                "vibration": true,
                "badge": true
            },
            "windows": {}
        });
        console.log('after init');
```

PushNotification.init never returns. 
I've tried with 2 different Android devices with the same result.

Why the Push template works just fine on iOS but fails on Android?

**Comment by macdonst** [comment]
@josegrad before I look into this can you tell me what version of the PhoneGap Developer App you are using?

**Comment by josegrad** [comment]
Thanks macdonst.

The version of PhoneGap Developer is 1.8.2 (both on Android and on iOS), installed today. 
Yesterday I installed the Phonegap Desktop app for Mac.

So pretty much a fresh install of all the tools. Following line by line the push tutorial works fine only on iOS.

**Comment by macdonst** [comment]
@josegrad it's broken in 1.8.2. Follow this issue to see the workaround and get notified when it is fixed. 

https://github.com/phonegap/phonegap-app-developer/issues/516
