### ISSUE TITLE
Getting error in pushnotification.init function

### ISSUE THREAD

**Issue by kanishkamehta801** [phonegap/phonegap-plugin-push#2091]
Hello Team,

I am getting an error in pushnotification.init function. The error is in push.js file.
Error says in below line in push.js: var e = (typeof msg === 'string') ? new Error(msg) : msg;

Here is my sample code:

function onDeviceReady(){
        var push = PushNotification.init({
                                     ios: {
                                     alert: "true",
                                     badge: "true",
                                     sound: "true"
                                     }
            });

    push.on('registration', function(data) {
                console.log(JSON.stringify(data));
                });

    push.on('error', function(e) {
            console.log("On error = "+JSON.stringify(e));
            });
}

I am not getting registration id but getting "On error" console.
Please tell me the solution for it.

Thanks in advance!

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
