### ISSUE TITLE
No notification received on Oppo,Mi when app is removed from Ram Even if force start is enabled

### ISSUE THREAD

**Issue by Prashant454** [phonegap/phonegap-plugin-push#2095]
### Expected Behaviour
When force start is enabled Must receive a notification on Oppo,Mi when app is removed from Ram 

### Actual Behaviour
No notification received on Oppo,Mi when app is removed from Ram Even if force start is enabled

### Cordova CLI version and cordova platform version

cordova --version                                   7.0.1
cordova platform version android     
Installed platforms:
android 6.2.3
browser 4.1.0

Plugin version

cordova plugin version | grep phonegap-plugin-push   
Sample Push Data Payload

{
    "title": "New Update Available",
    "body": "EventsPage",
    "sound": "default",
    "image": "www/assets/img/icon.png",
    "style": "picture",
    "picture": "http://im.rediff.com/news/2014/aug/25bmc.jpg",
    "page": "EventsPage",
    "image-type": "circle",
    "content-available": 1,
    "force-start": 1,
    "summaryText": "EventsPage",
    "click_action": "FCM_PLUGIN_ACTIVITY",
    "notId": 7248,
    "surveyID": "ewtawgreg-gragrag-rgarhthgbad"
}

**Comment by macdonst** [comment]
@Prashant454 sorry, I won't be able to test this as I don't have the device. One thing I'd suggest you take a look at is these docs: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#huawei-and-xiaomi-phones. The Oppo might have the same type of setting.

**Comment by StevenVygo** [comment]
https://www.forbes.com/sites/bensin/2017/07/28/how-to-fix-push-notifications-on-oppo-phones/#7bbf13181735  - Check out this article. Some of our users are experiencing the same issues on Oppo phones and I believe this could be the cause.
