### ISSUE TITLE
Error: Variable(s) missing: SENDER_ID

### ISSUE THREAD

**Issue by anto-christo** [phonegap/phonegap-plugin-push#2099]
Added the below code to config.xml

`<preference name="android-build-tool" value="gradle" />
    <plugin name="phonegap-plugin-push" spec="npm">
        <variable name="SENDER_ID" value="xxxxxxxxxxx" />
    </plugin>`

Executed `phonegap build android` in command line. But getting this error.

`Failed to install 'phonegap-plugin-push': Error: Variable(s) missing: SENDER_ID
Error: Variable(s) missing: SENDER_ID`

**Comment by macdonst** [comment]
@anto-christo the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
