### ISSUE TITLE
PushNotification not defined

### ISSUE THREAD

**Issue by FernandoMedin** [phonegap/phonegap-plugin-push#21]
Hi. Using almost the same code in example e got an error message saying that. I got this errro puting a Try before "var push". 
The code:
"""
        try{
            var push = PushNotification.init({
                "android": { "senderID": "xxxxx" }
            });
        }catch(err){
            alert("Error: " + err.message);
        }
"""
In config XML I've add the lines: 
"""
    feature name="PushNotification" 
        param name="android-package" value="com.adobe.phonegap.push.PushPlugin"/
    /feature
"""
I'm doing something wrong? Thanks.

**Comment by macdonst** [comment]
@FernandoMedin that's not the correct plugin ID. The plugin ID for this package is "phonegap-plugin-push". If you are running the PhoneGap 5.0 command line then doing a:

`phonegap pluging add phonegap-plugin-push` 

it will setup your config.xml for you. Let me know if this doesn't resolve things for you.

**Comment by FernandoMedin** [comment]
@macdonst thanks for the reply! But, I'm getting the same error. I just tested using phonegap-build. Should I use the command line to build the app?
At this time I just ran the command line in a new project and edit index.js to put the "Try".

Thanks.

**Comment by macdonst** [comment]
@FernandoMedin I don't think the plugin has been uploaded to PhoneGap Build. If you are using PhoneGap/Cordova CLI 5+ then:

```
phonegap create pushtest
phonegap platform add android
phonegap plugin add phonegap-plugin-push
// edit the html/js
phonegap run android
```

Substitue ios for android if you want to test iOS.

**Comment by FernandoMedin** [comment]
@macdonst, that works! The problem was with phonegap build so. Anyway, thank you very much! Any ideia if the plugin will be available in phonegap build?

**Comment by macdonst** [comment]
@FernandoMedin I'm going to close this issue then as you have a work around. I'm off this week but putting in a few bug fixes as I have time. Hope to have the next version on PG Build be early next week. I'll create an issue for it.

**Comment by gongfan99** [comment]
Is this module in phonegap build yet? I have tried phonegap build and PushNotification is undefined.

**Comment by macdonst** [comment]
@gongfan99 https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md

**Comment by gongfan99** [comment]
@macdonst Thanks. It works nicely with phonegap build.

Just to benefit anyone who has the same issue and ends up here. What I did wrong was that I should manually bootstrap Angular in the "deviceready" callback, like this:

```javascript
angular.module("myApp", [ ... ]);

angular.element(document).ready(function () {
	if (window.cordova) {
		document.addEventListener('deviceready', function () {
			angular.bootstrap(document, ['myApp']);
		}, false);
	} else {
		angular.bootstrap(document, ['myApp']);
	}
});
```

And the "ng-app" tag need to be removed from the index.html to prevent auto bootstrap.
