### ISSUE TITLE
Error -505 from google play store

### ISSUE THREAD

**Issue by creator1134** [phonegap/phonegap-plugin-push#2102]
### Expected Behaviour
should not show error -505 while installing the app
### Reproduce Scenario (including but not limited to)
install accenture vahini
then install etms buddy both apps using push plugin
#### Steps to Reproduce 
installing any APP with pushPlugin then again installing another app  with pushplugin. 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
above version 4.4

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Any

#### Cordova CLI version and cordova platform version

    cordova --version                                            7.0.1
    cordova platform version android                  android 6.2.3

#### Plugin version

  1.10.5

**Comment by macdonst** [comment]
@creator1134 I suspect that the app developer did not choose a unique application ID and that is why the two apps are conflicting. If that is the case there is nothing the plugin can do about it.

When I search in the play store I don't find those apps can you give me links to them in the Play Store?

**Comment by creator1134** [comment]
--Accenture Vahini
https://play.google.com/store/apps/details?id=com.accenture.vaahinihttps://play.google.com/store/apps/details?id=com.accenture.vaahini

--etms buddy
https://play.google.com/store/apps/details?id=xdk.intel.cordova.template.eTMSBuddy



and by "unique application ID" were you refering to "package name" or something else.

**Comment by macdonst** [comment]
@creator1134 I don't have access to the first app in my region so I can't check it. There is a really good chance that the root cause of the issue is #1362. I don't think there is anything I can do about this issue as I don't have control over those apps to make any changes.
