### ISSUE TITLE
Keeping Google Cloud Message alive

### ISSUE THREAD

**Issue by liquid36** [phonegap/phonegap-plugin-push#2103]
Hello,
I want to know if you consider any solutions or inprovement about keeping GCM connection alive? 

There are many threads on this subject, suggesting somethings like this:

```
context.sendBroadcast(new Intent("com.google.android.intent.action.GTALK_HEARTBEAT"));
context.sendBroadcast(new Intent("com.google.android.intent.action.MCS_HEARTBEAT"));
```

**Comment by macdonst** [comment]
@liquid36 Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
