### ISSUE TITLE
How to set the Badge count in iOS when the App is not running

### ISSUE THREAD

**Issue by stib** [phonegap/phonegap-plugin-push#2105]
Hi,

I am trying to figure out a way to set badge count when the App is in the background or is not running at all (killed by the User). I have tried to dig around but don't find anything for iOS.

I see from the documentation that I can set that for Android using this data payload

```
    "data": {
    	"title": "Badge Test",
    	"message": "Badges, we don't need no stinking badges",
    	"badge": 7
    }
```
where the number against the badge key will be set against the App icon for devices that support that.

However I am not clear on how to do that for iOS. I see ways to do that by setting content-available and processing the message when the App is in background and calling the function `setApplicationIconBadgeNumber`  from the code to set the badge count but if the App is not running in the background then how do I set the badge count for iOS through data in the push notification I send to the device? 

The description for the function `setApplicationIconBadgeNumber` says "Set the badge count visible when the app is not running". I must be missing something obvious here because how do I call that function to set a badge count provided in the message when the App is not running?

Thank you for your help and pointers.

Sanjay.

**Comment by jcesarmobile** [comment]
To set the iOS badge you can send it on the payload like this:

```
{
    "aps" : {
        "alert" : "You got 9 emails.",
        "badge" : 9
    }
}
```

**Comment by stib** [comment]
Thank you @jcesarmobile. I am using GCM and I have tried payload like below but that didn't change/set the badge number. Do I need to do anything different or is this supposed to work?

```
{
            "notification": {
                "title": "Badge Message",
                "body": "Show badge count"
            },
            "data": {
                "badge": 12
            }
}
```

**Comment by jcesarmobile** [comment]
I think it should go inside notification, but better check GCM docs.
