### ISSUE TITLE
Chrome: 504 Gateway Time-out

### ISSUE THREAD

**Issue by natesreich** [phonegap/phonegap-plugin-push#2106]
### Expected Behaviour
As per the following, a notification should have appeared in Chrome: http://docs.phonegap.com/tutorials/develop/push-notifications/

(It works fine for my iOS device)

### Actual Behaviour
- When localhost:3000 is loaded in Chrome, the following registration event is received:

> [phonegap] [console.log] registration event: dXixHNnr3TI:APA91bHnSwpFH7w3Jsyz2E2iS2OF6aS9g1aFtJVbG8gDvYVbnqNsqTHapipY0FOSQ-gdst1dFp3cNOipSXbAO8KqNldXhj7G87Oe_u39yEk6FoHfYrdhxCpRvAM7_d2JSbJ3Qc10m-bv
> [phonegap] 200 http://push.api.phonegap.com/v1/push/keys
> [phonegap] 200 /ServiceWorker.js
> [phonegap] 200 /css/index.css

- In a separate PhoneGap CLI terminal, the following was entered:

> phonegap push --deviceID dXixHNnr3TI:APA91bHnSwpFH7w3Jsyz2E2iS2OF6aS9g1aFtJVbG8gDvYVbnqNsqTHapipY0FOSQ-gdst1dFp3cNOipSXbAO8KqNldXhj7G87Oe_u39yEk6FoHfYrdhxCpRvAM7_d2JSbJ3Qc10m-bv --service fcm --payload "{ \"data\": { \"title\": \"Hello\", \"message\": \"World\"} }"

(I also attempted it with "gcm")

- After a bit of a wait, the following response is received in the terminal:

```
body: <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
```

#### Steps to Reproduce 
- Load localhost:3000 in Chrome and "Allow Notifications"
- Note the device ID from the registration event recorded in either the PhoneGap or Chrome console log
- In a new PhoneGap terminal window, try to send a push notification:

> phonegap push --deviceID **[DEVICE ID GOES HERE]** --service gcm --payload "{ \"data\": { \"title\": \"Hello\", \"message\": \"World\"} }"

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Phone CLI Version: 7.1.1
OS: Windows 10
Chrome: 62.0.3202.94 (64-Bit)

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
N/A

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.1.1
    cordova platform version android                     N/A

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   ~1.8.0

#### Sample Push Data Payload
> phonegap push --deviceID **[DEVICE ID GOES HERE]** --service gcm --payload "{ \"data\": { \"title\": \"Hello\", \"message\": \"World\"} }"

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
Please refer to the "Actual Behaviour" above.

**Comment by macdonst** [comment]
@natesreich while doing some testing on this I ran into a problem where the new cordova-browser creates a manifest.json file. The push plugin needs to add some properties to the file. I'm going to have to write a node script to combine the files.

**Comment by natesreich** [comment]
@macdonst So you were able to replicate the issue? Please let me know if I can help with anything.

**Comment by macdonst** [comment]
@natesreich no, I haven't been able to reproduce it yet because cordova-browser 5.0 causes another issue I need to work around.

**Comment by macdonst** [comment]
@natesreich I've fixed #2109 and I can't reproduce your issue. Can you try updating the version of the plugin you are using?

**Comment by natesreich** [comment]
@macdonst I am unsure how to update the plugin to the latest version. When I run the following command:

`cordova-check-plugins --update=auto --force-update`

It tells me that 1.8.4 is the latest version and my plugin is up-to-date:

```
plugin: phonegap-plugin-push
source: npm://phonegap-plugin-push@~1.8.0
installed version: 1.8.4
remote version: 1.8.4
```

As a workaround, what I did is download the latest version from the v2 branch and manually replaced plugins/phonegap-plugin-push with it. I then ran cordova-check-plugins again and confirmed it recognized the new version:

```
******************************************************
* Installed plugin version newer than remote default *
******************************************************

plugin: phonegap-plugin-push
source: npm://phonegap-plugin-push@~1.8.0
installed version: 2.1.2
remote version: 1.8.4
```

Once again, I tried serving a push to the browser via both "fcm" and "gcm":

> phonegap push --deviceID **[DEVICE ID GOES HERE]** --service gcm --payload "{ "data": { "title": "Hello", "message": "World"} }"

It did absolutely nothing this time. It just got stuck and there was no 504 gateway timeout until I cancelled the task after a few minutes.

It's worth noting that when I enter "phonegap serve", I see the following error in the console log:

`[phonegap] [console.log] Error: exec proxy not found for :: StatusBar :: _ready`

Could that be the issue?

**Comment by natesreich** [comment]
In an attempt to start from scratch, I did the following:

$ phonegap create myApp --template push
$ cd myApp
$ phonegap platform add browser
$ phonegap plugin add cordova-plugin-console
$ phonegap plugin add cordova-plugin-dialogs
$ phonegap plugin add https://github.com/apache/cordova-plugin-statusbar.git
$ phonegap plugin add cordova-plugin-whitelist
$ phonegap plugin add https://github.com/phonegap/phonegap-plugin-push.git
$ phonegap build
$ phonegap serve

The following error is gone:
`[phonegap] [console.log] Error: exec proxy not found for :: StatusBar :: _ready
`

However, I am now getting this error in Chrome's Console Log:
```
Error: Error subscribing for Push notifications.
    at push.js:82
```

I noticed there is now a 303 HTTP status code in CMD for ServiceWorker.js:
`[phonegap] 303 /ServiceWorker.js`

In Chrome's Console Log, I also get "Failed to Load Response Data" for this: http://localhost:3000/ServiceWorker.js

**Comment by macdonst** [comment]
@natesreich huh, not sure why that `cordova-check-plugins` script would report 1.8.4 as the latest as we are at 2.1.2.

For the statusbar log:

```
[phonegap] [console.log] Error: exec proxy not found for :: StatusBar :: _ready
```

Ignore it. We should have removed that a long time ago. It just means that when you try to set the status bar color in chrome it is ignored as there is no method to do that in Chrome Desktop.

When you see:

```
Error: Error subscribing for Push notifications.
    at push.js:82
```

You are running into issue #2109 which I have fixed but not pushed a new release of the plugin.

Finally the:

```
[phonegap] 303 /ServiceWorker.js
```

is caused by [CB-13562](https://issues.apache.org/jira/browse/CB-13562) in the cordova-browser component. Again it has been fixed but not released. We are going through the Apache voting process soon.

**Comment by natesreich** [comment]
@macdonst 

> Ignore it. We should have removed that a long time ago. It just means that when you try to set the status bar color in chrome it is ignored as there is no method to do that in Chrome Desktop.

Unfortunately, this is likely what is causing the 504 timeout error: https://forums.adobe.com/thread/2303975

It is why I pulled the latest version of the Cordova Statusbar Plugin in my steps (which then triggered Issue #2109):
> $ phonegap plugin add https://github.com/apache/cordova-plugin-statusbar.git

As you were unable to recreate my issue though, I am curious what you are doing differently from my steps? Here are my steps again:

> $ phonegap create myApp --template push
> $ cd myApp
> $ phonegap platform add browser
> $ phonegap plugin add cordova-plugin-console
> $ phonegap plugin add cordova-plugin-dialogs
> $ phonegap plugin add https://github.com/apache/cordova-plugin-statusbar.git
> $ phonegap plugin add cordova-plugin-whitelist
> $ phonegap plugin add https://github.com/phonegap/phonegap-plugin-push.git
> $ phonegap build
> $ phonegap serve

For now, I had given up on testing inside the browser. If there's a change I can make to the above steps to get things working, it would certainly save me a lot of time in the testing.

Thank you for your help!

**Comment by eduardoalvara2** [comment]
Hi, I am having the same error, when I run:
`$ phonegap push --deviceID [DEVICE ID GOES HERE] --service fcm --payload "{ \"data\": { \"title\": \"Hello\", \"message\": \"World\"} }"`

I receive:

```
body: <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
```
