### ISSUE TITLE
Push icon on PGB

### ISSUE THREAD

**Issue by MBuchalik** [phonegap/phonegap-plugin-push#2107]
### Expected Behaviour

A custom icon should be shown when recieving a push message.

### Actual Behaviour

On PGB with builder 2, the application's icon is shown.

#### Steps to Reproduce 

According to the docs (https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md), you can use the locales folder to copy the icon file into the res/ folder. This works when using
``` XML
<preference name="phonegap-version" value="cli-7.0.1" />
<preference name="pgb-builder-version" value="1" />
```
However, on
``` XML
<preference name="phonegap-version" value="cli-7.0.1" />
<preference name="pgb-builder-version" value="2" />
```
this doesn't seem to work anymore. I have put the files into
locales/android/drawable-hdpi/ic_notification.png (and into drawable-mdpi, drawable-xhdpi, drawable-xxhdpi, drawable-xxxhdpi).

When unzipping the .apk file, you can find the hdpi icon in the res/drawable-hdpi-v4/ folder when using builder1. On builder2, the file is missing. This also applies to the other icons in the respective folders.

So I guess PGB doesn't support the locales folder anymore (which is pretty unfortunate).
Is there another way to move the icon into the necessary folder?
Or: Is it somehow possible to pick an icon from the www folder? I am currently initializing the push notifications using
```
"android": {
    "senderID": (my sender ID),
    "icon": "ic_notification",
    "iconColor": (some color)
},
```

Is it possible to pick the icon from the www folder? If so: How should the path be adjusted to make it work properly?
I hope that there is simply a different setting in this plugin that could help me out here. Please tell me if you need additional details about my configuration.

Looking forward to your reply. :smiley:

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Tested on an Android 5.0 device.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Samsung

#### Cordova CLI version and cordova platform version

PGB 7.0.1 with builder 2. On builder 1, it works perfectly.

#### Plugin version

1.10.5

#### Sample Push Data Payload

(imho not needed)

#### Sample Code that illustrates the problem

(see above)

#### Logs taken while reproducing problem

(no logs were taken)

**Comment by macdonst** [comment]
@MBuchalik the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

Please include an app id of an app that can replicate this issue.

**Comment by MBuchalik** [comment]
@macdonst I have already asked a related question on the PGB forum (https://forums.adobe.com/thread/2417785). Since I did not get a reply, I am currently trying to remove the need for the locales folder from my app. That's why I asked the question above - I was hoping that there is an alternative method (maybe to use the push icon from the www folder). 😄

**Comment by macdonst** [comment]
@MBuchalik nope because the icon has to be findable by the OS so it needs to be in the res folder of your app where it is addressable. The OS has no way of reaching into your apps `www` folder to use an icon.

**Comment by MBuchalik** [comment]
@macdonst OK, thanks for the info! 👍 
Well then I can just hope that the PGB team will fix the locales folder (or the fact that the resource file tag doesn't work in the config.xml, even if it was reported to be supported) :smile:
