### ISSUE TITLE
Need code and steps for push notification using phonegap build

### ISSUE THREAD

**Issue by hemaswaminadhan** [phonegap/phonegap-plugin-push#2108]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@hemaswaminadhan the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

Please include an app id of an app that can replicate this issue.
