### ISSUE TITLE
Custom text when asking for user's permission to receive notifications?

### ISSUE THREAD

**Issue by JaneDawson** [phonegap/phonegap-plugin-push#2113]
Is it possible to add a custom text when the user is asked for the permission to receive notifications?

Using a geolocation plugin for example, I use the following part in my `config.xml` to add a custom message to the permission request for the user's location:

```
<edit-config file="*-Info.plist" mode="merge" target="NSLocationWhenInUseUsageDescription">
        <string>This is necessary for......</string>
</edit-config>
```

**Comment by jcesarmobile** [comment]
No, it's not possible.
What some people do is to show a custom dialog before calling the init, but that will ask twice, one for the custom dialog and another for the push permission dialog, I think that's worse.

**Comment by JaneDawson** [comment]
OK. Thank you for the quick response, @jcesarmobile.

**Comment by macdonst** [comment]
@JaneDawson @jcesarmobile analytics show that if you explain why you need to enable push notifications before that system dialog pops up the number of users who answer yes increases from 40% to 60%. So even though the double dialog is not awesome it is useful.
