### ISSUE TITLE
Look into using cordova-support-google-services to run Google Services Gradle plugin

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-plugin-push#2114]
### Expected Behaviour

That this plugin works well with other plugins that require Google Services Gradle plugin to be run

### Actual Behaviour

There are some other plugins that also run Google Services Gradle plugin and if both attempt this the build will fail.

#### Steps to Reproduce 

Add `cordova-plugin-fcm` to a project with this plugin and try to build.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Any

#### Cordova CLI version and cordova platform version

Any

#### Plugin version

2.0.0+

#### Sample Push Data Payload

n/a

#### Sample Code that illustrates the problem

n/a

#### Logs taken while reproducing problem

```
What went wrong: A problem occurred configuring root project android. Cannot add task :processDebugGoogleServices' as a task with that name already exists.
```

**Comment by jcesarmobile** [comment]
Shouldn't this be fixed at cordova-android level?

**Comment by macdonst** [comment]
@jcesarmobile probably
