### ISSUE TITLE
Error with push plugin, no value for android

### ISSUE THREAD

**Issue by datastone** [phonegap/phonegap-plugin-push#2119]
### Expected Behaviour
debugg run
### Actual Behaviour
![capture](https://user-images.githubusercontent.com/12507143/34351276-9cdb2624-ea41-11e7-9ca7-0ad51dd74ee9.PNG)

Latest versions of cordova and ionic, angular

Code 
```
const options: PushOptions = {
   android: {},
   ios: {
       alert: 'true',
       badge: true,
       sound: 'false'
   },
   windows: {},
   browser: {
   }
};

const pushObject: PushObject = this.push.init(options);
```

@macdonst

**Comment by fredgalvao** [comment]
What's that `this.push` object like? That smells like something not coming from the plugin code itself.

**Comment by fredgalvao** [comment]
Also, please provide the remaining information from the issue template. Logs, plugin version, at the *very least*.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
