### ISSUE TITLE
iOS Can I use APNs Auth Key with this plugin?

### ISSUE THREAD

**Issue by ArtKuz** [phonegap/phonegap-plugin-push#2121]
Hello!
iOS Can I use APNs Auth Key with this plugin?
I generate *.p8 file and send to server.
Should I somehow indicate in the app that I have APNs Auth Key?
How APNs Auth Key choose app from accaunt?

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
