### ISSUE TITLE
Inbox Stacking & Picture Not Working

### ISSUE THREAD

**Issue by seagate25** [phonegap/phonegap-plugin-push#2122]
### Expected Behaviour
In last saturday, December 24th, i send notifications directly from firebase console with custom param "style": "inbox" and "summaryText": "There %n% notifications", that's working and looks like in documentation.

### Actual Behaviour
But on this day, December 28th, i added the custom param in the API and directly from firebase console, inbox stacking doesn't work, not only inbox, picture style too, not working.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4.4

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Sony

#### Cordova CLI version and cordova platform version

    cordova --version                                   7.1.0
    cordova platform version android          6.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.1.2

#### Sample Push Data Payload

message: "Amrizal Admin - oy↵",
title: "Sistem Monitoring Pelayanan",
additionalData: Object
{
  coldstart: true
  content-available: "1",
  foreground: false,
  style: "inbox",
  summaryText: "There are %n% notifications",
  tableName: "t_trx_trouble_ticket_detail"
}

**Comment by seagate25** [comment]
how is it @PhoneGapCI ?

**Comment by macdonst** [comment]
@seagate25 the Firebase console tends to put everything in the `notification` section of the push. You need to send it in `data`. Can you read:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

and try sending via a node script instead of the Firebase console?

**Comment by seagate25** [comment]
@macdonst but return from firebase console is same with return of my API. no property "notification" in firebase console return.

i have not tried via a node script.

**Comment by seagate25** [comment]
@macdonst i don't what happen with firebase or with the plugin. Today the parameter "style" and "summaryText" show inbox stacking. I don't know, is the gcm / firebase doing maintenence or not.

I think this issue was solved.
