### ISSUE TITLE
Automatically collected events

### ISSUE THREAD

**Issue by amitzw** [phonegap/phonegap-plugin-push#2124]
When I send a push notification using the Firebase console I get auto generated events like notification_receive, notification_dismiss, notification_foreground, notification_open.
I would like to manually create the same events when using the fcm API.
Creating notification_foreground and notification_open is not a problem since I can identify them inside the   push.on('notification') event of the plugin.
How can I identify when a notification is received and when a notification is dismissed in the code?

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by amitzw** [comment]
I did not follow the issue template because this is not a bug desciption just a question about plugin usage. There is no expected behaviour, steps to reproduce etc..
Not sure what I should have done.
