### ISSUE TITLE
Phonegap-plugin-push 2.1.2 working fine in emulator but not working in android device

### ISSUE THREAD

**Issue by PareshIT83** [phonegap/phonegap-plugin-push#2126]
### Expected Behaviour
PushNotification defined in device
### Actual Behaviour
    var push = PushNotification.init({ "android": { "senderID": "xxxxxxxx"} });

errror : PushNotification is not defined
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Platform Android 7.0.0
Platform browser 5.0.3
#### Cordova CLI version and cordova platform version

    cordova --version                                  8.0.0
    cordova platform version android             7.0.0
#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.1.2

#### Sample Push Data Payload
 var push = PushNotification.init({ "android": { "senderID": "xxxxxxxxxxxxxxxxx"} });
   
       <platform name="android">
        <resource-file src="google-services.json" target="app/google-services.json" />
    </platform>
    <plugin name="phonegap-plugin-push" spec="~2.1.2">
        <variable name="FCM_VERSION" value="11.0.1" />
    </plugin>

#### Sample Code that illustrates the problem
 var push = PushNotification.init({ "android": { "senderID": "xxxxxxxxxxxxxx"} });

**Comment by macdonst** [comment]
@PareshIT83 it seems like the plugin is not being delivered to the Android platform directory. Can you a) send me the logs of your `cordova build android` and b) verify that the directory `platforms/android/app/src/main/assets/www/plugins/phonegap-plugin-push` exists and it contains the .js file for the push plugin? 

Additionally, you don't need to pass senderID into the init method anymore.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
