### ISSUE TITLE
push.on('notification') event should be called twice, once when the notification is received and a second time when the notification is opened.

### ISSUE THREAD

**Issue by amitzw** [phonegap/phonegap-plugin-push#2128]
### Expected Behaviour
push.on('notification') event should be called twice for API calls with content-available, once when the notification is received and a second time when the notification is opened.
### Actual Behaviour
push.on('notification') is only called once when the notification is opened.
#### Steps to Reproduce 
send a notification from fcm API.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.1.1
#### Cordova CLI version and cordova platform version
cordova 7.1.0
cordova-ios 4.5.4
#### Plugin version

    2.1.2

#### Sample Push Data Payload
**FCM:**

 {
	"to": "/topics/ios-test",
	"content-available": 1,
	"priority": "high",
	"notification": {
		"title": "test",
		"body": "test body"
	},
	"data": {
		"content-available": 1,
		"notId": 4,
		"force-start": 1
	}
 }

I tried both "content-available": 1 and "content-available": true

**Comment by macdonst** [comment]
@amitzw try the following payload. The content-available should be in a different location in the payload when sending to iOS via FCM:

```
{
"to": "/topics/ios-test",
"content-available": 1,
"priority": "high",
"notification": {
"title": "test",
"body": "test body"
},
"data": {
"notId": 4,
"force-start": 1
},
"content_available": "true"
}
```

Also, note that it is `content_available` in this case.

https://firebase.google.com/docs/cloud-messaging/http-server-ref

**Comment by amitzw** [comment]
I tried that today. 
It seems to be working when the app is in the background, but when the app is closed I am not getting the push.on("notification") event to run on notification receive. I verified that I have Background App Refresh enabled on my device. I am using iOS 10.1.1 on an iPhone 6 device.
My goal is to send analytics events regarding the number of devices that opened the notification and the number of devices that received the notification. Fot that I need the push.on("notification") event to be called twice.

**Comment by macdonst** [comment]
@amitzw unfortunately, if the app is completely closed then there is no webview resident in memory that can run the Javascript code to call `push.on("notification")`. You've bumped into a limitation of the hybrid approach to app development.

**Comment by amitzw** [comment]
When I said the app is closed I meant it is not in the recent apps menu.
I am not sure if iOS keeps the app running or not. I do have background app refresh enabled.
Shouldn't I get 30 seconds of run time and get the push.on("notification") invoked?
If not than what is the purpose of content-available on iOS?
