### ISSUE TITLE
Receiving a notification "outside app" while in it?

### ISSUE THREAD

**Issue by marcus-chr** [phonegap/phonegap-plugin-push#213]
Is it possible to implement a function that always handles the notification "outside" the app even if the user is currently using it? Clicking on the notification could re-open the app and then call on event "notification".

As far as I know this needs to be handled with native code and cannot be implemented "backend".

**Comment by ajinkyamarathe** [comment]
Yes i have similar problem. please help.....

**Comment by macdonst** [comment]
@marcus-chr Are you talking about what is described in Issue #93? If so please close this issue and add you comments to that issue.

**Comment by marcus-chr** [comment]
@macdonst No, I don't think it's the same. This issue is about having the same "process" of receiving push notifications whether or not it is in background or foreground mode. Today it works like this:

Background:
1. Push shown in a banner/alert etc
2. User taps on notification
3. App starts
4. Event 'notification' is run

Foreground (user has the app opened):
1. Event 'notification' is run

I would like the foreground mode to work as the background. Maybe it doesn't necessarily need to re-open the app but at least do step 1,2 and 4 (instead of only 4). Let me know if this was clear or not :-)

**Comment by macdonst** [comment]
@marcus-chr so this https://github.com/phonegap/phonegap-plugin-push/pull/178 which has been merged and will be in the next release.

**Comment by marcus-chr** [comment]
Oh, I'm sorry. Should I close this issue now then?

**Comment by macdonst** [comment]
Yup
