### ISSUE TITLE
Delete the firebase instance when unregistering the firebase token

### ISSUE THREAD

**Issue by ccorcos** [phonegap/phonegap-plugin-push#2130]
### Expected Behaviour

When I call `Push.unregister(() => {}, () => {})`, I would expect this plugin to call `[[FIRInstanceID instanceID] deleteIDWithHandler]` to actually unregister the application token with Firebase ([example](https://github.com/arnesson/cordova-plugin-firebase/blob/master/src/ios/FirebasePlugin.m#L180)). That way, when I try to send a message to this token, firebase will respond with `messaging/registration-token-not-registered`. 

### Actual Behaviour

We simply [disable the ability to receive notifications](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/PushPlugin.m#L122) but Firebase will respond as if the message succeeded.

```
"cordova": "7.1.0",
<engine name="ios" spec="4.5.4" />
"name": "phonegap-plugin-push",   "version": "2.1.2",
```

**Comment by macdonst** [comment]
@ccorcos please update your issue to match the issue template.
