### ISSUE TITLE
Cold starting app from a notification never fires event on iOS

### ISSUE THREAD

**Issue by ccorcos** [phonegap/phonegap-plugin-push#2132]
### Expected Behaviour

If the app is closed (not just in the background but closed), when you tap a notification on iOS the `push.on("notification")` event should fire once the app is launched and initialized.

### Actual Behaviour

No event.

```
"cordova": "7.1.0",
<engine name="ios" spec="4.5.4" />
"name": "phonegap-plugin-push",   "version": "2.1.2",
```

**Comment by macdonst** [comment]
@ccorcos please update your issue to match the issue template.
