### ISSUE TITLE
when i add plugin have error!

### ISSUE THREAD

**Issue by githubkyo** [phonegap/phonegap-plugin-push#2133]
(node:6936) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Cordova
Error: Failed to fetch plugin phonegap-plugin-push@2.1.2 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: C:\Program Files (x86)\Nodist\bin\npm.exe: Command failed with exit code 1 Error output:
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name ""2.1.2"": Tags may not have any characters that encodeURIComponent encode
s.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
