### ISSUE TITLE
Push Notification not received in Android 8(oreo)

### ISSUE THREAD

**Issue by mahesh-vi** [phonegap/phonegap-plugin-push#2134]
I use this plugin in my ionic-1 project. I am unable to received any push notification in android 8 and my app also crash while i send notification from server.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
