### ISSUE TITLE
Got error "compileDebugJavaWithJavac" deploy to android

### ISSUE THREAD

**Issue by armespavong** [phonegap/phonegap-plugin-push#2135]
### Expected Behaviour

I want to deploy to android from ionic cordova

### Actual Behaviour

I got error
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 7.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Samsung Galaxy S8

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.1.0
    cordova platform version android                     6.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.1.2

#### Logs taken while reproducing problem

Error: cmd: Command failed with exit code 1 Error output:
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:52: error: cannot access zzb
public class FCMService extends FirebaseMessagingService implements PushConstants {
       ^
  class file for com.google.firebase.iid.zzb not found
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:71: error: method does not override or implement a method from a supertype
  @Override
  ^
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:74: error: cannot access zza
    String from = message.getFrom();
                         ^
  class file for com.google.android.gms.common.internal.safeparcel.zza not found
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:80: error: cannot find symbol
      extras.putString(TITLE, message.getNotification().getTitle());
                       ^
  symbol:   variable TITLE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:81: error: cannot find symbol
      extras.putString(MESSAGE, message.getNotification().getBody());
                       ^
  symbol:   variable MESSAGE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:82: error: cannot find symbol
      extras.putString(SOUND, message.getNotification().getSound());
                       ^
  symbol:   variable SOUND
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:83: error: cannot find symbol
      extras.putString(ICON, message.getNotification().getIcon());
                       ^
  symbol:   variable ICON
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:84: error: cannot find symbol
      extras.putString(COLOR, message.getNotification().getColor());
                       ^
  symbol:   variable COLOR
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:91: error: cannot find symbol
      Context applicationContext = getApplicationContext();
                                   ^
  symbol:   method getApplicationContext()
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:95: error: cannot find symbol
      boolean forceShow = prefs.getBoolean(FORCE_SHOW, false);
                                           ^
  symbol:   variable FORCE_SHOW
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:96: error: cannot find symbol
      boolean clearBadge = prefs.getBoolean(CLEAR_BADGE, false);
                                            ^
  symbol:   variable CLEAR_BADGE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:97: error: cannot find symbol
      String messageKey = prefs.getString(MESSAGE_KEY, MESSAGE);
                                          ^
  symbol:   variable MESSAGE_KEY
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:97: error: cannot find symbol
      String messageKey = prefs.getString(MESSAGE_KEY, MESSAGE);
                                                       ^
  symbol:   variable MESSAGE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:98: error: cannot find symbol
      String titleKey = prefs.getString(TITLE_KEY, TITLE);
                                        ^
  symbol:   variable TITLE_KEY
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:98: error: cannot find symbol
      String titleKey = prefs.getString(TITLE_KEY, TITLE);
                                                   ^
  symbol:   variable TITLE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:103: error: cannot find symbol
        PushPlugin.setApplicationIconBadgeNumber(getApplicationContext(), 0);
                                                 ^
  symbol:   method getApplicationContext()
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:109: error: cannot find symbol
        extras.putBoolean(FOREGROUND, true);
                          ^
  symbol:   variable FOREGROUND
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:110: error: cannot find symbol
        extras.putBoolean(COLDSTART, false);
                          ^
  symbol:   variable COLDSTART
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:116: error: cannot find symbol
        extras.putBoolean(FOREGROUND, true);
                          ^
  symbol:   variable FOREGROUND
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:117: error: cannot find symbol
        extras.putBoolean(COLDSTART, false);
                          ^
  symbol:   variable COLDSTART
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:124: error: cannot find symbol
        extras.putBoolean(FOREGROUND, false);
                          ^
  symbol:   variable FOREGROUND
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:125: error: cannot find symbol
        extras.putBoolean(COLDSTART, PushPlugin.isActive());
                          ^
  symbol:   variable COLDSTART
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:156: error: cannot find symbol
    if (key.equals(TITLE) || key.equals(MESSAGE) || key.equals(SUMMARY_TEXT)) {
                   ^
  symbol:   variable TITLE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:156: error: cannot find symbol
    if (key.equals(TITLE) || key.equals(MESSAGE) || key.equals(SUMMARY_TEXT)) {
                                        ^
  symbol:   variable MESSAGE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:156: error: cannot find symbol
    if (key.equals(TITLE) || key.equals(MESSAGE) || key.equals(SUMMARY_TEXT)) {
                                                               ^
  symbol:   variable SUMMARY_TEXT
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:160: error: cannot find symbol
        String localeKey = localeObject.getString(LOC_KEY);
                                                  ^
  symbol:   variable LOC_KEY
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:163: error: cannot find symbol
        if (!localeObject.isNull(LOC_DATA)) {
                                 ^
  symbol:   variable LOC_DATA
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:164: error: cannot find symbol
          String localeData = localeObject.getString(LOC_DATA);
                                                     ^
  symbol:   variable LOC_DATA
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:197: error: cannot find symbol
    if (key.equals(BODY) || key.equals(ALERT) || key.equals(MP_MESSAGE) || key.equals(GCM_NOTIFICATION_BODY)
                   ^
  symbol:   variable BODY
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:197: error: cannot find symbol
    if (key.equals(BODY) || key.equals(ALERT) || key.equals(MP_MESSAGE) || key.equals(GCM_NOTIFICATION_BODY)
                                       ^
  symbol:   variable ALERT
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:197: error: cannot find symbol
    if (key.equals(BODY) || key.equals(ALERT) || key.equals(MP_MESSAGE) || key.equals(GCM_NOTIFICATION_BODY)
                                                            ^
  symbol:   variable MP_MESSAGE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:197: error: cannot find symbol
    if (key.equals(BODY) || key.equals(ALERT) || key.equals(MP_MESSAGE) || key.equals(GCM_NOTIFICATION_BODY)
                                                                                      ^
  symbol:   variable GCM_NOTIFICATION_BODY
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:198: error: cannot find symbol
        || key.equals(TWILIO_BODY) || key.equals(messageKey)) {
                      ^
  symbol:   variable TWILIO_BODY
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:199: error: cannot find symbol
      return MESSAGE;
             ^
  symbol:   variable MESSAGE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:200: error: cannot find symbol
    } else if (key.equals(TWILIO_TITLE) || key.equals(SUBJECT) || key.equals(titleKey)) {
                          ^
  symbol:   variable TWILIO_TITLE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:200: error: cannot find symbol
    } else if (key.equals(TWILIO_TITLE) || key.equals(SUBJECT) || key.equals(titleKey)) {
                                                      ^
  symbol:   variable SUBJECT
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:201: error: cannot find symbol
      return TITLE;
             ^
  symbol:   variable TITLE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:202: error: cannot find symbol
    } else if (key.equals(MSGCNT) || key.equals(BADGE)) {
                          ^
  symbol:   variable MSGCNT
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:202: error: cannot find symbol
    } else if (key.equals(MSGCNT) || key.equals(BADGE)) {
                                                ^
  symbol:   variable BADGE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:203: error: cannot find symbol
      return COUNT;
             ^
  symbol:   variable COUNT
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:204: error: cannot find symbol
    } else if (key.equals(SOUNDNAME) || key.equals(TWILIO_SOUND)) {
                          ^
  symbol:   variable SOUNDNAME
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:204: error: cannot find symbol
    } else if (key.equals(SOUNDNAME) || key.equals(TWILIO_SOUND)) {
                                                   ^
  symbol:   variable TWILIO_SOUND
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:205: error: cannot find symbol
      return SOUND;
             ^
  symbol:   variable SOUND
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:206: error: cannot find symbol
    } else if (key.startsWith(GCM_NOTIFICATION)) {
                              ^
  symbol:   variable GCM_NOTIFICATION
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:207: error: cannot find symbol
      return key.substring(GCM_NOTIFICATION.length() + 1, key.length());
                           ^
  symbol:   variable GCM_NOTIFICATION
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:208: error: cannot find symbol
    } else if (key.startsWith(GCM_N)) {
                              ^
  symbol:   variable GCM_N
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:209: error: cannot find symbol
      return key.substring(GCM_N.length() + 1, key.length());
                           ^
  symbol:   variable GCM_N
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:210: error: cannot find symbol
    } else if (key.startsWith(UA_PREFIX)) {
                              ^
  symbol:   variable UA_PREFIX
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:211: error: cannot find symbol
      key = key.substring(UA_PREFIX.length() + 1, key.length());
                          ^
  symbol:   variable UA_PREFIX
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:233: error: cannot find symbol
      if (key.equals(PARSE_COM_DATA) || key.equals(MESSAGE) || key.equals(messageKey)) {
                     ^
  symbol:   variable PARSE_COM_DATA
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:233: error: cannot find symbol
      if (key.equals(PARSE_COM_DATA) || key.equals(MESSAGE) || key.equals(messageKey)) {
                                                   ^
  symbol:   variable MESSAGE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:241: error: cannot find symbol
            if (data.has(ALERT) || data.has(MESSAGE) || data.has(BODY) || data.has(TITLE) || data.has(messageKey)
                         ^
  symbol:   variable ALERT
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:241: error: cannot find symbol
            if (data.has(ALERT) || data.has(MESSAGE) || data.has(BODY) || data.has(TITLE) || data.has(messageKey)
                                            ^
  symbol:   variable MESSAGE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:241: error: cannot find symbol
            if (data.has(ALERT) || data.has(MESSAGE) || data.has(BODY) || data.has(TITLE) || data.has(messageKey)
                                                                 ^
  symbol:   variable BODY
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:241: error: cannot find symbol
            if (data.has(ALERT) || data.has(MESSAGE) || data.has(BODY) || data.has(TITLE) || data.has(messageKey)
                                                                                   ^
  symbol:   variable TITLE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:256: error: cannot find symbol
            else if (data.has(LOC_KEY) || data.has(LOC_DATA)) {
                              ^
  symbol:   variable LOC_KEY
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:256: error: cannot find symbol
            else if (data.has(LOC_KEY) || data.has(LOC_DATA)) {
                                                   ^
  symbol:   variable LOC_DATA
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:303: error: cannot find symbol
    String msgcnt = extras.getString(COUNT);
                                     ^
  symbol:   variable COUNT
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:319: error: cannot find symbol
    String message = extras.getString(MESSAGE);
                                      ^
  symbol:   variable MESSAGE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:320: error: cannot find symbol
    String title = extras.getString(TITLE);
                                    ^
  symbol:   variable TITLE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:321: error: cannot find symbol
    String contentAvailable = extras.getString(CONTENT_AVAILABLE);
                                               ^
  symbol:   variable CONTENT_AVAILABLE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:322: error: cannot find symbol
    String forceStart = extras.getString(FORCE_START);
                                         ^
  symbol:   variable FORCE_START
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:339: error: cannot find symbol
        extras.putString(TITLE, getAppName(this));
                         ^
  symbol:   variable TITLE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:339: error: cannot find symbol
        extras.putString(TITLE, getAppName(this));
                                           ^
  symbol:   variable this
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:347: error: cannot find symbol
      Intent intent = new Intent(this, PushHandlerActivity.class);
                                 ^
  symbol:   variable this
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:349: error: cannot find symbol
      intent.putExtra(PUSH_BUNDLE, extras);
                      ^
  symbol:   variable PUSH_BUNDLE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:350: error: cannot find symbol
      intent.putExtra(START_IN_BACKGROUND, true);
                      ^
  symbol:   variable START_IN_BACKGROUND
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:351: error: cannot find symbol
      intent.putExtra(FOREGROUND, false);
                      ^
  symbol:   variable FOREGROUND
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:352: error: cannot find symbol
      startActivity(intent);
      ^
  symbol:   method startActivity(Intent)
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:361: error: cannot find symbol
    NotificationManager mNotificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
                                                                     ^
  symbol:   method getSystemService(String)
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:362: error: cannot find symbol
    String appName = getAppName(this);
                                ^
  symbol:   variable this
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:366: error: cannot find symbol
    int notId = parseInt(NOT_ID, extras);
                         ^
  symbol:   variable NOT_ID
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:367: error: cannot find symbol
    Intent notificationIntent = new Intent(this, PushHandlerActivity.class);
                                           ^
  symbol:   variable this
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:369: error: cannot find symbol
    notificationIntent.putExtra(PUSH_BUNDLE, extras);
                                ^
  symbol:   variable PUSH_BUNDLE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:370: error: cannot find symbol
    notificationIntent.putExtra(NOT_ID, notId);
                                ^
  symbol:   variable NOT_ID
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:373: error: cannot find symbol
    PendingIntent contentIntent = PendingIntent.getActivity(this, requestCode, notificationIntent,
                                                            ^
  symbol:   variable this
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:376: error: cannot find symbol
    Intent dismissedNotificationIntent = new Intent(this, PushDismissedHandler.class);
                                                    ^
  symbol:   variable this
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:377: error: cannot find symbol
    dismissedNotificationIntent.putExtra(PUSH_BUNDLE, extras);
                                         ^
  symbol:   variable PUSH_BUNDLE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:378: error: cannot find symbol
    dismissedNotificationIntent.putExtra(NOT_ID, notId);
                                         ^
  symbol:   variable NOT_ID
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:379: error: cannot find symbol
    dismissedNotificationIntent.putExtra(DISMISSED, true);
                                         ^
  symbol:   variable DISMISSED
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:380: error: cannot find symbol
    dismissedNotificationIntent.setAction(PUSH_DISMISSED);
                                          ^
  symbol:   variable PUSH_DISMISSED
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:383: error: cannot find symbol
    PendingIntent deleteIntent = PendingIntent.getBroadcast(this, requestCode, dismissedNotificationIntent,
                                                            ^
  symbol:   variable this
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:389: error: cannot find symbol
      String channelID = extras.getString(ANDROID_CHANNEL_ID);
                                          ^
  symbol:   variable ANDROID_CHANNEL_ID
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:400: error: cannot find symbol
          channelID = extras.getString(ANDROID_CHANNEL_ID, DEFAULT_CHANNEL_ID);
                                       ^
  symbol:   variable ANDROID_CHANNEL_ID
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:400: error: cannot find symbol
          channelID = extras.getString(ANDROID_CHANNEL_ID, DEFAULT_CHANNEL_ID);
                                                           ^
  symbol:   variable DEFAULT_CHANNEL_ID
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:411: error: cannot find symbol
        .setTicker(fromHtml(extras.getString(TITLE))).setContentIntent(contentIntent).setDeleteIntent(deleteIntent)
                                             ^
  symbol:   variable TITLE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:410: error: cannot find symbol
    mBuilder.setWhen(System.currentTimeMillis()).setContentTitle(fromHtml(extras.getString(TITLE)))
                                                                                           ^
  symbol:   variable TITLE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:415: error: cannot find symbol
    String localIcon = prefs.getString(ICON, null);
                                       ^
  symbol:   variable ICON
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:416: error: cannot find symbol
    String localIconColor = prefs.getString(ICON_COLOR, null);
                                            ^
  symbol:   variable ICON_COLOR
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:417: error: cannot find symbol
    boolean soundOption = prefs.getBoolean(SOUND, true);
                                           ^
  symbol:   variable SOUND
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:418: error: cannot find symbol
    boolean vibrateOption = prefs.getBoolean(VIBRATE, true);
                                             ^
  symbol:   variable VIBRATE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:437: error: cannot find symbol
    setNotificationIconColor(extras.getString(COLOR), mBuilder, localIconColor);
                                              ^
  symbol:   variable COLOR
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:513: error: cannot find symbol
    intent.putExtra(CALLBACK, callback);
                    ^
  symbol:   variable CALLBACK
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:514: error: cannot find symbol
    intent.putExtra(PUSH_BUNDLE, extras);
                    ^
  symbol:   variable PUSH_BUNDLE
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:515: error: cannot find symbol
    intent.putExtra(FOREGROUND, foreground);
                    ^
  symbol:   variable FOREGROUND
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:516: error: cannot find symbol
    intent.putExtra(NOT_ID, notId);
                    ^
  symbol:   variable NOT_ID
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:522: error: cannot find symbol
    String actions = extras.getString(ACTIONS);
                                      ^
  symbol:   variable ACTIONS
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:534: error: cannot find symbol
          Log.d(LOG_TAG, "adding callback = " + action.getString(CALLBACK));
                                                                 ^
  symbol:   variable CALLBACK
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:535: error: cannot find symbol
          boolean foreground = action.optBoolean(FOREGROUND, true);
                                                 ^
  symbol:   variable FOREGROUND
  location: class FCMService
D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\FCMService.java:543: error: cannot find symbol
              intent = new Intent(this, PushHandlerActivity.class);
                                  ^
  symbol:   variable this
  location: class FCMService
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\Apps\skynet-client-crypto\platforms\android\src\com\adobe\phonegap\push\PushPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
100 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by macdonst** [comment]
@armespavong looks like you are missing the FCM library in your setup. Go into the Android SDK manager and install the updates.

**Comment by Lenndev** [comment]
@macdonst  any what the solution for this error could be?:


```
(node:53662) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: /Users/me/Documents/projects/approotfolder/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/me/Documents/projects/approotfolder/platforms/android/app/src/main/java/com/adobe/phonegap/push/FCMService.java:393: error: constructor Builder in class Builder cannot be applied to given types;
        mBuilder = new NotificationCompat.Builder(context, channelID);
                   ^
  required: Context
  found: Context,String
  reason: actual and formal argument lists differ in length
/Users/me/Documents/projects/approotfolder/platforms/android/app/src/main/java/com/adobe/phonegap/push/FCMService.java:403: error: constructor Builder in class Builder cannot be applied to given types;
        mBuilder = new NotificationCompat.Builder(context, channelID);
                   ^
  required: Context
  found: Context,String
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
```

**Comment by Lenndev** [comment]
Oke! so for me the solution was to update cordova-android-support-gradle-release to the latest version (i was using 0.0.2). removed the plugin and ran `cordova plugin add cordova-android-support-gradle-release@latest --save` after that, it built.
