### ISSUE TITLE
Android 8 : Please compatible with Android 8 (Oreo)

### ISSUE THREAD

**Issue by mayurm-virtueinfo** [phonegap/phonegap-plugin-push#2139]
### Right now i am not receiving any notification with Android 8(Oreo) Compatibility.
I am getting the following errro. in my Android Studio Logcat.

W/GCM-DMM: Force release of GOOGLE_C2DM lock
01-09 11:41:53.913 26675-28784/com.helthallc.HelthaTS W/EnhancedIntentService: Service took too long to process intent: com.google.android.c2dm.intent.RECEIVE App may get closed.

**Comment by macdonst** [comment]
@mayurm-virtueinfo this plugin does support Oreo. There is nowhere near enough information in this issue for me to help.

So sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
