### ISSUE TITLE
Unexpected behavior of push when push arrive and open through app icon 

### ISSUE THREAD

**Issue by jakute** [phonegap/phonegap-plugin-push#2146]
### Expected Behaviour

When its in foreground it prints alert 2
When app is killed and push arrive then click push print alert 3
When app is killed and push arrive then click app icon print alert 3 
When app is in background and push arrive then click push print alert 3 
When app is in background and push arrive then click app icon print alert 1

### Actual Behaviour

When its in foreground it prints alert 2
When app is killed and push arrive then click push print alert 3 and alert 1 **problem
When app is killed and push arrive then click app icon print alert 3 
When app is in background and push arrive then click push print alert 3 and alert 1 **problem
When app is in background and push arrive then click app icon print alert 1

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

samsung

#### Cordova CLI version and cordova platform version

    cordova --version                                    # 7.1.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # 2.1.2

#### Sample Push Data Payload

const message2 = {

    to: deviceID,
   
    "data" : {
         "title": "Nuevo softwqare 4",
         "body": "hola cabeza de papa",
         "content-available" : 1,
     
         "notId":5, 

     }
};

#### Sample Code that illustrates the problem

pushObject.on('notification').subscribe((notification: any) => {
        
    
      if(notification.additionalData.coldstart){
        alert("1");
      }else if (notification.additionalData.foreground){
        alert("2");
      }else{
        alert("3");
      }

      
  });

**Comment by macdonst** [comment]
@jakute when you set `content-available: 1` you will have the push event called once when the app is in the background and a second time when you click on the push. This is by design so what you describe is the intended result.

**Comment by jakute** [comment]
Thanks very much, i have read it but i was thinking this was an issue from another thing. Im going to do it with option 3 the different Id`s. 

thanks!
