### ISSUE TITLE
Receiving multiple notifications but i only send one 

### ISSUE THREAD

**Issue by jakute** [phonegap/phonegap-plugin-push#2148]
### Expected Behaviour

notification should be received one time

### Actual Behaviour

notification keep coming with no interval of time 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

samsung

#### Cordova CLI version and cordova platform version

    cordova --version                                    # 8.0.0
    cordova platform version android                     # 6.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # 2.1.2

BTW fc_version is 11.6.2

#### Sample Push Data Payload

```
const message2 = {

to: deviceID,

"data" : {
     "title": "Nuevo softwqare 4",
     "body": "hola cabeza de papa",
     "content-available" : 1,
 
     "notId":5, 

 }
};
```

#### Sample Code that illustrates the problem

Not sure if its the code or same plugin .....

```
pushObject.on('notification').subscribe((notification: any) => {

  if(notification.additionalData.coldstart){
    alert("1");
  }else if (notification.additionalData.foreground){
    alert("2");
  }else{
    alert("3");
  }
});
```

**Comment by macdonst** [comment]
@jakute how is this different from #2146? Your description of what is happening is not very informative. That is, I need more details.

**Comment by jakute** [comment]
Hello! its a problem that appears today, yesterday we send push notification via node.js and php and everything works just fine but today many notifications arrived (we send just one)... this is like #2097 but i put FCM_VERSION in 11.6.2 and nothing happens..... please let me know wich details else do you need ( it was working fine 2 days ago)

**Comment by macdonst** [comment]
@jakute reproduce the problem while running `adb logcat | grep Push`

**Comment by jakute** [comment]
i can't reproduce it... im with a big black cloud :(

**Comment by macdonst** [comment]
@jakute I'm thinking that it was a server side issue. I'm going to close this issue but if it re-occurs please comment on this issue with logs.
