### ISSUE TITLE
Do I need to use Firebase?

### ISSUE THREAD

**Issue by F1LT3R** [phonegap/phonegap-plugin-push#2149]
Hi there, I'm reading through your installation documentation and it mentions Cocopods and Firebase. Is this library designed to be used with Firebase/Cocopods specifically?

If I am planning to use Amazon SNS, should I be looking for a different Cordova plugin?

**Comment by macdonst** [comment]
@F1LT3R you can use this plugin with APNS or with FCM on iOS. You still need to setup Cocoapods to install the plugin. This plugin works well with Amazon SNS BTW. Since you are planning on using it to send the push messages I suggest FCM on Android and APNS on iOS.

**Comment by F1LT3R** [comment]
Thanks, @macdonst - good to hear things are working well with AWS SNS.

**Comment by F1LT3R** [comment]
Hi @macdonst, it seems like Xcode will not build my app without Firebase. @jcesarmobile is suggesting that I have to use Firebase with this plugin: https://github.com/phonegap/phonegap-plugin-push/issues/1737

**Comment by jcesarmobile** [comment]
No, I mean that you can't build the app without Firebase and CocoaPods, but you don't have to use it.

**Comment by F1LT3R** [comment]
Ah, makes sense. Thanks, @jcesarmobile
