### ISSUE TITLE
on('notification') not firing on android when background

### ISSUE THREAD

**Issue by sarawutl** [phonegap/phonegap-plugin-push#2150]
### Expected Behaviour
After I  push notification, I should be able to handle the event on('notification').

### Actual Behaviour
on('notification') not firing in android, iOS is working fine

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung S8

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.1.0
    cordova platform version android                     6.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.1.2

#### Sample Push Data Payload
```json
{
	"notification": {
		"title": "Test I am Number 1",
		"body": "Test at 50",
		"content-available": true
	},
	"data": {
		"symbol": "THB_XRP",
		"orderType": "LIMIT",
		"strategyName": "I am Number 1",
		"amount": "0.3",
		"side": "B",
		"brokerId": 1,
		"rate": "50",
		"pairingId": 25,
		"content-available": true,
		"createAt": 1516090612290
	},
	"to": "/topics/abc",
	"priority": "high",
	"notId": 1516090612305
}
```

**Comment by fredgalvao** [comment]
tl:dr; You can't/shouldn't provide a `notification` section to Android payloads.

Please read the sections/pages that follow on the plugin documentation.

https://github.com/phonegap/phonegap-plugin-push/blob/master/README.md :

> This does not mean you will be able to send a single push message and have it arrive on devices running different operating systems. By default Android uses FCM and iOS uses APNS and their payloads are significantly different. Even if you are using FCM for both Android and iOS there are differences in the payload required for the plugin to work correctly. *For Android always put your push payload in the data section of the push notification*. For more information on why that is the case read *Notification vs Data Payload*.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads :

> My recommended format for your push payload when using this plugin (while it differs from Google's docs) works 100% of the time:

```json
{
    "data" : {
        "title": "Test Notification",
        "body": "This offer expires at 11:30 or whatever",
        "notId": 10,
        "surveyID": "ewtawgreg-gragrag-rgarhthgbad"
    }
}
```

**Comment by sarawutl** [comment]
not working,

I want fire on('notification') in background, no click on the notification in the system tray
