### ISSUE TITLE
start android application when notification is received.

### ISSUE THREAD

**Issue by mmagdy-sigma** [phonegap/phonegap-plugin-push#2151]
### Expected Behaviour
Android application starts in foreground when notification is received.

### Actual Behaviour
app starts in background

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
LG

#### Cordova CLI version and cordova platform version

    cordova --version                                            8.0.0
    cordova platform version android                    android 7.0.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.1.2

Can I start my application when notification is received ?

**Comment by macdonst** [comment]
@mmagdy-sigma You are not supposed to start your app in the foreground when you receive a push notification as per Android UI guidelines. If you fork this plugin and look at the `force-start` option for Android and modify it so it doesn't put the app in the background but I won't be implementing it.

**Comment by mmagdy-sigma** [comment]
@macdonst thank you.

**Comment by mmagdy-sigma** [comment]
@macdonst  can you guide me how to edit it to execute the desired behavior ?
