### ISSUE TITLE
iOS 11+: notifications arrives without sound on inactive app state

### ISSUE THREAD

**Issue by ElleDriver** [phonegap/phonegap-plugin-push#2154]
### Expected Behaviour
Emit sound when notification arrives
### Actual Behaviour
No sound
### Reproduce Scenario (including but not limited to)
iPhone iOS 11+. Receive notification (Azure notification).
#### Steps to Reproduce 
Send app to background and wait to becomes inactive, then receive notification (Azure Notification).
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Everything worked fine on iOS 10, played sound selected previously by user in app. Stop working on iOS 11+

#### Cordova CLI version and cordova platform version

    cordova --version- 7.0.1

#### Plugin version

    cordova plugin version  1.10.3

#### Sample Push Data Payload

	'{ "aps": {"alert": "'+message+'","message": "'+message+'", "content-available": 1}}';

The above code works on iOS10.

**Comment by ElleDriver** [comment]
(Sorry, I don't know if you need anything else.)

**Comment by macdonst** [comment]
@ElleDriver one thing I notice is that you are not specifying a sound to be played in your payload. Can you try:

```
'{ "aps": {"alert": "'+message+'","message": "'+message+'", "content-available": 1, "sound": "default"}}';
```

and let me know the result as per https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#sound-1

Also, 1.10.3 is kinda old for iOS 11 support and you might want to look at 2.x stream.

**Comment by ElleDriver** [comment]
Sending ""sound": "default"" in payload now emits sound. (Not needed in iOS 10, don't know why) 
Thank you so much!

**Comment by macdonst** [comment]
@ElleDriver kk, closing as resolved.
