### ISSUE TITLE
Installation Problem on iOS with Ionic

### ISSUE THREAD

**Issue by wo-github** [phonegap/phonegap-plugin-push#2155]
Expected Behaviour

install with cordova plugin add phonegap-plugin-push --variable SENDER_ID="xxxxx" should work

Actual Behaviour

The installation produce the following error:
Error: /bin/sh: /usr/local/bin/pod: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory

Cordova CLI version and cordova platform version

    cordova --version            7.1.0
    cordova platform version ios    4.5.4

Plugin version

    try to install the newest version 2.1.2

**Comment by wo-github** [comment]
The solution was:
sudo gem install cocoapods
pod setup

**Comment by jcesarmobile** [comment]
That's in the installation docs https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#cocoapods

also, the SENDER_ID variable is no longer needed and will be ignored in the version 2.x.x of the plugin
