### ISSUE TITLE
Trying to install on Ionic project

### ISSUE THREAD

**Issue by vmagalhaes** [phonegap/phonegap-plugin-push#2156]
### Expected Behaviour

Work

### Actual Behaviour

Doesn't work

### Reproduce Scenario (including but not limited to)

```ts
 // app.component.ts

  initializeApp() {
    this.platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      this.statusBar.styleDefault();
      this.splashScreen.hide();

      const options: PushOptions = {
        android: { senderID: '256624249194' },
        ios: {
            alert: 'true',
            badge: true,
            sound: 'false'
        },
        browser: {
          pushServiceURL: 'http://push.api.phonegap.com/v1/push'
        }
      };

      const pushObject: PushObject = this.push.init(options);

      pushObject.on('notification').subscribe((notification: any) => {
        console.log(notification)
        let youralert = this.alertCtrl.create({
          title: 'New Push notification',
          message: notification.message
        });
        youralert.present();
      });
    });
  }
```

```xml
// config.xml

<plugin name="phonegap-plugin-push" spec="~2.1.2">
   <variable name="SENDER_ID" value="256624249194" />
</plugin>

<platform name="android">
<resource-file src="google-services.json" target="google-services.json" />
</platform>
```
```json
"cordova": {
            "plugins": {
                "phonegap-plugin-push": {
                    "SENDER_ID": "256624249194"
                },
```

And the google-service.json are in app/google-services.json

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 7

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Moto G4 PLus

#### Cordova CLI version and cordova platform version

    cordova --version                                   6.3.0
    cordova platform version android                    4.1.1

#### Plugin version

    "phonegap-plugin-push": "^2.1.2",

////////////////

![image](https://user-images.githubusercontent.com/14242447/35152260-d020d0b8-fd08-11e7-9794-c92b321a2550.png)

And when I send the message nothing happen,
I'm doing something wrong? I don't no :/

**Comment by alexdragneel** [comment]
Hello,
What is the import of this.push ?

**Comment by vmagalhaes** [comment]
@alexdragneel 
 
My app.component

`import { Component, ViewChild } from '@angular/core';
import { Nav, Platform, AlertController } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import { Push, PushObject, PushOptions } from '@ionic-native/push';
import { Device } from '@ionic-native/device';

import { HomePage } from '../pages/home/home';
import { ListPage } from '../pages/list/list';

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  @ViewChild(Nav) nav: Nav;

  rootPage: any = ListPage;

  pages: Array<{title: string, component: any}>;

  constructor(
    public platform: Platform,
    public statusBar: StatusBar,
    public splashScreen: SplashScreen,
    public alertCtrl: AlertController,
    private push: Push,
    private device: Device
  ) {
    this.initializeApp();

    // used for an example of ngFor and navigation
    this.pages = [
      { title: 'Ínicio', component: HomePage },
      { title: 'Lista', component: ListPage }
    ];

  }

  initializeApp() {
    this.platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      this.statusBar.styleDefault();
      this.splashScreen.hide();

      const options: PushOptions = {
        android: { senderID: '256624249194' },
        ios: {
            alert: 'true',
            badge: true,
            sound: 'false'
        },
        browser: {
          pushServiceURL: 'http://push.api.phonegap.com/v1/push'
        }
      };

      const pushObject: PushObject = this.push.init(options);

      pushObject.on('notification').subscribe((notification: any) => {
        console.log(notification)
        let youralert = this.alertCtrl.create({
          title: 'New Push notification',
          message: notification.message
        });
        youralert.present();
      });
    });
  }

  openPage(page) {
    // Reset the content nav to have just this page
    // we wouldn't want the back button to show in this scenario
    this.nav.setRoot(page.component);
  }
}
`

**Comment by vmagalhaes** [comment]
@alexdragneel The import is to init the push

**Comment by alexdragneel** [comment]
@vmagalhaes For me, this plugin does't have export module, where do you see it ?
import { Push, PushObject, PushOptions } from '';

**Comment by vmagalhaes** [comment]
@alexdragneel here, https://ionicframework.com/docs/native/push/

**Comment by alexdragneel** [comment]
Ok good ! So I check and it works for me.
You need a token from the device to send it a notification. You can get it by : 
pushObject.on('registration').subscribe((registration: any) => {
        pushToken = registration.registrationId;
 });
After all, you nedd to use server functions (Exemple : I do it with cloud firebase functions) to send a notifications from a device to another device or use (Exemple : Firebase website notification) to send device from website to device.

**Comment by macdonst** [comment]
@vmagalhaes did you get his resolved?

**Comment by vmagalhaes** [comment]
@alexdragneel @macdonst not yet, I'm sending the FCM Notifications but nothing happen. I think it's all right but doesn't work :/

**Comment by macdonst** [comment]
@vmagalhaes logs while reproducing the issue would help, `adb logcat | grep Push`

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
