### ISSUE TITLE
2.1.2 doesn't work on PG builder latest

### ISSUE THREAD

**Issue by eyalish** [phonegap/phonegap-plugin-push#2157]
### Expected Behaviour
To compile good on PG
### Actual Behaviour
Error log by PG builder

Fetching plugin "phonegap-plugin-push@~2.1.0" via npm
Installing "phonegap-plugin-push" at "2.1.2" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.2.3, failed version requirement: >=6.3.0
Skipping 'phonegap-plugin-push' for android

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 7.0.1
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # 2.1.2

**Comment by macdonst** [comment]
@eyalish the answer is right there in the error message:

```
Plugin doesn't support this project's cordova-android version. cordova-android: 6.2.3, failed version 
```

You are using cordova-android 6.2.3 and the plugin needs 6.3.0 or greater. Just update your version of cordova-android.

**Comment by macdonst** [comment]
@eyalish the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.

**Comment by fabmesto** [comment]
I have same problem. I asked in the forum but no one answers -__-
https://forums.adobe.com/thread/2442749

**Comment by bitterdev** [comment]
Same here https://forums.adobe.com/message/10133577

Still no solution or workaround ? :(

**Comment by eyalish** [comment]
Okay I was told to try with BitBucket Git clone.
I could not yet get this to work well.
I've worked with this question:
https://stackoverflow.com/questions/39754798/firebase-push-notifications-with-phonegap-build-using-cordova-plugin-fcm
