### ISSUE TITLE
Facing "6 duplicate symbols for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation)"

### ISSUE THREAD

**Issue by manojpatel0217** [phonegap/phonegap-plugin-push#2159]
Hi,
When I changed in config.XML the project name and tried to build ios project then the "linker command failed with exit code 1 (use -v to see invocation)" problem is showing in Xcode. 

Plugin which are in my project:

com.dbaq.cordova.contactsPhoneNumbers 0.0.9 "Contacts Phone Numbers"
com.synconset.imagepicker 2.1.8 "ImagePicker"
cordova-plugin-add-swift-support 1.6.2 "AddSwiftSupport"
cordova-plugin-badge 0.8.1 "Badges"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-contacts 2.3.1 "Contacts"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-email 1.2.6 "EmailComposer"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googleplus 5.1.1 "Google SignIn"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-nativegeocoder 1.0.2 "NativeGeocoder"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-request-location-accuracy 2.2.2 "Request Location Accuracy"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova.plugins.diagnostic 3.6.7 "Diagnostic"
es6-promise-plugin 4.1.0 "Promise"
info.protonet.imageresizer 0.1.1 "Image Resizer"
ionic-plugin-keyboard 2.2.1 "Keyboard"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
onesignal-cordova-plugin 2.2.5 "OneSignal Push Notifications"

My development information is as follows:
![screen shot 2018-01-24 at 5 54 44 pm](https://user-images.githubusercontent.com/27670324/35332064-b4ec549a-012f-11e8-81e2-b9c004920872.png)

cli packages: 

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.1.1

System:

    ios-deploy : 1.9.1 
    Node       : v6.10.3
    npm        : 3.10.10 
    OS         : macOS
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy

Can someone please help this issue
Regards
Manoj Patel

**Comment by jcesarmobile** [comment]
That class is from com.synconset.imagepicker, maybe another plugin is using the same class name. Anyway, it has nothing to do with push plugin, closing

**Comment by manojpatel0217** [comment]
@jcesarmobile  i removed com.synconset.imagepicker now it working fine. 
Thank you
