### ISSUE TITLE
iOS 10+ is now showing Push Notification when app is in Foreground.

### ISSUE THREAD

**Issue by DKrein** [phonegap/phonegap-plugin-push#2161]
### Expected Behaviour
When push message arrives with app in foreground:
The message is not displayed in the devices' notification center, as that is not normal behaviour for Android or iOS.

### Actual Behaviour
In iOS 10+ the push messages are being show even in foreground.

### Reproduce Scenario (including but not limited to)
Push a message to an app in foreground.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10+

#### Cordova CLI version and cordova platform version

cordova --version: 6.5.0

cordova platform version:
 android 6.3.0
 ios 4.5.4

#### Plugin version

    phonegap-plugin-push 2.1.2 "PushPlugin"

#### Sample Push Data Payload

{ "aps": { "alert": "Test", 'title' =>  'Test Title',  "sound": "default" } }

**Comment by macdonst** [comment]
@DKrein I can't reproduce this and this seems kinda impossible on iOS. Are you sure you are sending the push to the right app? Perhaps you have two apps on your device that have registered with your push service?

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
