### ISSUE TITLE
Are Diogo Local Notifications use Internally?

### ISSUE THREAD

**Issue by F1LT3R** [phonegap/phonegap-plugin-push#2162]
I have a couple of quick questions:

1. Does`phonegap-plugin-push` use `diogo.cordova.plugin.local-notifications` internally?
2. If it does, can I still use this codebase in my app?

Eg: Can I do the following after installing `phonegap-plugin-push` ?

```javascript
        cordova.plugins.notification.local.schedule({
	    id: 1,
	    title: "Please Put Down Your Weapon",
	    message: "You have 20 seconds to comply",
	    firstAt: new Date(),
	    data: {
	    	foo: "bar"
	    }
	});
```

**Comment by macdonst** [comment]
@F1LT3R 1) no, it does not 2) I don't see why not but I haven't done it so YMMV

**Comment by F1LT3R** [comment]
Thanks
