### ISSUE TITLE
iOs not calling on('registration') on first run.

### ISSUE THREAD

**Issue by fsanzv** [phonegap/phonegap-plugin-push#2164]
### Expected Behaviour
'registration' event should be called every time you open the app.

### Actual Behaviour
The first time you run the app in iOs you get push permissions dialog but 'registration' event is not called. If you open the app again, it gets called and you get the registrationId.

### Reproduce Scenario (including but not limited to)
I have added console.logs to show every steep taken in the code related to push plugin and init is being called correctly but 'registration' event is not called when I run for the first time the app. The second and successive times it gets called correctly.

#### Steps to Reproduce 
Run an Ionic App with Push plugin in iOs with command: `ionic cordova run ios --device -lc`

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 11.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iOs emulator (iPhone X)

#### Cordova CLI version and cordova platform version

    cordova --version: 7.1.0
    cordova platform version ios: 4.5.4

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push: 2.1.2

#### Sample Push Data Payload
-

#### Sample Code that illustrates the problem
```javascript
  init() {
    const pushOptions: PushOptions = {
      android: {
        icon: 'push_icon',
        iconColor: '#dd9933',
        senderID: 'Firebase/GCM Sender ID'
      },
      ios: {
          alert: 'true',
          badge: true,
          sound: 'false'
      }
    };
    const pushObject: PushObject = this.push.init(pushOptions);
    console.log('Initialized push notifications');

    pushObject.on('registration').subscribe(registrationData => {
      console.log('on(registration) called!');
      this.handleRegistration(registrationData)
    });

    pushObject.on('notification').subscribe(notificationData => {
      this.handleNotification(notificationData)
    });
  }
```
##### First run:
[12:13:54]  console.log: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
[12:13:55]  console.log: Ionic Native: deviceready event fired after 1659 ms
[12:13:55]  console.log: Initializing push notifications
[12:13:55]  console.log: Initialized push notifications

##### Second run:
[12:16:50]  console.log: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
[12:16:51]  console.log: Ionic Native: deviceready event fired after 992 ms
[12:16:51]  console.log: Initializing push notifications
[12:16:51]  console.log: Initialized push notifications
[12:16:51]  console.log: on(registration) called!
[12:16:51]  console.info: Push Token received: elY-RDq2EVk:APA91bHGXODogVmrMYc...

**Comment by macdonst** [comment]
@fsanzv you should get a registration event after you okay the push dialog permission.

**Comment by fsanzv** [comment]
@macdonst This is the expected behaviour, but instead of it, I'm not getting the registration event in the first run, only in second and successives run I get the registration event.

**Comment by jaybloke** [comment]
Also experiencing a similar issue on iOS simulator. The permission dialog appears, and immediately after the on('error') event is called with the following [not particularly helpful] error message:

> {"line":62,"column":50,"sourceURL":"http://192.168.0.6:8100/plugins/phonegap-plugin-push/www/push.js"}

After clicking the 'Allow' button on the dialog, the registration event is never triggered - even though permission has been granted.

Code excerpt:
```

  private askPermission() {

    const options: PushOptions = {
      android: {
        senderID: ENV.push.android.senderID
      },
      ios: {
        alert: 'true',
        badge: true,
        sound: 'false'
      }
    }
    console.log('initializing');
    const pushObject: PushObject = this.push.init(options);
    console.log('initialized');
 
    pushObject.on('registration').subscribe(
      (data: RegistrationEventResponse) => {
        console.log('registered');
        this.savePushToken(data.registrationId);
      }
    )

    pushObject.on('error').subscribe(
      (error: EventResponse) => {
        console.log('error', JSON.stringify(error));
        this.pushError();
      }
    )
    
  }

```

I have an almost identical set up to @fsanzv , except for phonegap-plugin-push - I'm using version 2.1.3

**Comment by macdonst** [comment]
@jaybloke you can't test push on the simulator. You need to use a real device.

**Comment by jaybloke** [comment]
Thanks @macdonst - knew the notifications wouldn't work on the sim, but didn't realise that registration was outlawed too.

Thanks for putting me out of my misery!

**Comment by fsanzv** [comment]
We are having this issue only in simulator, in real devices works as expected.

Thank you @macdonst.
