### ISSUE TITLE
Unable to build an ionic 3 app in xcode using phonegap-plugin-push - err: library not found for -lGoogleToolboxForMac

### ISSUE THREAD

**Issue by EventfulG** [phonegap/phonegap-plugin-push#2165]
Hi,

I'm unable to to build an ionic 3 app in xcode using phonegap-plugin-push - err: library not found for -lGoogleToolboxForMac.
I successfuly added the plugin and iOs platform.
But in xcode on build I get 1 error:

    ld: library not found for -lGoogleToolboxForMac
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

I research this error and followed the instruction from this link   https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#library-not-found-for--lgoogletoolboxformac but with no success.

==============================================

My technologies:

    cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

Global packages:
    
    cordova (Cordova CLI) : 7.1.0 

Local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-sim : 5.0.13 
    Node    : v7.3.0
    npm     : 3.10.10 
    OS      : macOS High Sierra
    Xcode   : Xcode 9.2 Build version 9C40b 

Thanks a lot!

**Comment by jcesarmobile** [comment]
open the .xcworkspace instead of the .xcodeproj

**Comment by Yashaswini** [comment]
I am facing same issue and none of the solutions mentioned above works for me. 
Is there any help w.r.t to this. I have tried installing pod inside platforms and building from .xcworkspace.  Would appreciate any guidance with this.

**Comment by shllg** [comment]
👍
