### ISSUE TITLE
Problems with PhoneGap Build

### ISSUE THREAD

**Issue by bitterdev** [phonegap/phonegap-plugin-push#2168]
Hello,

i am using the plugin in combination with FCM (Firebase Cloud Messaging). When i use the latest version 2.1.2 and build locally everything works as expected. Means i am able to get the device token and receive push notifications.

But when i try to build my project on PhoneGap Build i am not able to get this running.

I have tried out [the latest four](https://build.phonegap.com/current-support) Phonegap versions from PhoneGap Build.

Here are my results:

**Building with Version cli-6.5.0:**
- Compiling Succesfull.
- Not able to get device token. (No Events will be fired)

_Same behaivour for latest plugin version 2.1.2 and for 2.0.0 branch._

**Building with Version cli-7.0.1 and above:**
- Compiling Error. "Cant find google-services.json....."

_Same behaivour for latest plugin version 2.1.2 and for 2.0.0 branch._

Of course i have already added a resource file tag under platform liek this:
`<resource-file src="google-services.json" />`

Also tried with a target-attribute with MANY different variations.

Is this a known issue? Is there a fix in work? IPA cloud build seems to be working but not tested of functionallity.

**Which is the last PhoneGap-Build-Compatible Version with FCM support? And which PhoneGap Version i have to use ?**

**Comment by macdonst** [comment]
@bitterdev the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
