### ISSUE TITLE
push plugin says it is not installed (ionic3)

### ISSUE THREAD

**Issue by Michazzz** [phonegap/phonegap-plugin-push#2169]
### Expected Behaviour
Successfull device registration by the phonegap-push-plugin

### Actual Behaviour

> Native: tried calling PushNotification.init, but the PushNotification plugin is not installed.
> pluginWarn @ main.js:58006

### Reproduce Scenario (including but not limited to)
Install plugin via instruction available here: [https://ionicframework.com/docs/native/push/](url)

run command: ionic cordova run android --device

check the logs in Google Chrome tab: chrome://inspect

#### Steps to Reproduce 

Same as above

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy Note 4

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.0.1
    cordova platform version android           6.4.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push           2.1.2

#### Sample Push Data Payload
Not need to reproduce right now.

#### Sample Code that illustrates the problem
The code tag not working properly.... 
```
  private pushInit() {
    let pushObject = this.push.init({
      android: {
        senderID: "559622574607",
        sound: 'true',
        forceShow: true,
      },
      ios: {
        alert: 'true',
        badge: true,
        sound: 'false'
      }
    });

    pushObject.on('registration').subscribe((registration: any) => console.log('Device registered', registration));
  }
```

#### Logs taken while reproducing problem

> deviceready has not fired after 5 seconds.
main.js:143816 Ionic Native: deviceready event fired after 3970 ms
main.js:58006 Native: tried calling PushNotification.init, but the PushNotification plugin is not installed.
pluginWarn @ main.js:58006
SQLitePlugin.js:175 OPEN database: _ionicstorage
SQLitePlugin.js:106 new transaction is queued, waiting for open operation to finish
SQLitePlugin.js:179 OPEN database: _ionicstorage - OK
SQLitePlugin.js:80 DB opened: _ionicstorage

**Comment by macdonst** [comment]
@Michazzz I think you are going to have to open an issue on the Ionic forums. I don't generally do Ionic work so I'm not sure why the plugin wouldn't be installed but it's probably something that happens long before run time.

**Comment by ullasframer** [comment]
Facing the same issue.  Even added push.haspermission, but for that also it gives same error ,Native: tried calling Push.hasPermission, but the Push plugin is not installed

**Comment by jcesarmobile** [comment]
Latest version of the plugin requires cordova-android 7.1.0 and CLI 8.0.0.
As you are using old CLI and cordova-android versions you'll have to install an older version of the plugin. 2.0.0 supports CLI 7.0.0+ and cordova-android 6.2.1+

**Comment by ullasframer** [comment]
Yes , please find details as below

 `cordova platform version android`
**Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0**

and 

`cordova` -v
**8.0.0**

**Comment by jcesarmobile** [comment]
My answer was for Michazzz
For you, you can install 2.1.3.

Always check the engines section of the package.json

https://github.com/phonegap/phonegap-plugin-push/blob/master/package.json#L33-L66

The strange thing is, this should be automatically done by npm/cordova, if you try to install an unsupported version it should install the compatible one based in your CLI/platform

**Comment by ullasframer** [comment]
Thanks @jcesarmobile , tried with 2.1.3 , it didnt work , here is my log 


**03-22 17:56:28.062 32273 32273 I chromium: [INFO:CONSOLE(47546)] "Native: tried calling Push.hasPermission, but the Push plugin is not installed.", source: file:///android_asset/www/build/main.js (47546)
03-22 17:56:28.062 32273 32273 I chromium: [INFO:CONSOLE(47552)] "Install the Push plugin: 'ionic cordova plugin add phonegap-plugin-push'", source: file:///android_asset/www/build/main.js (47552)
03-22 17:56:28.063 32273 32273 I chromium: [INFO:CONSOLE(84647)] "Notification init start", source: file:///android_asset/www/build/main.js (84647)
03-22 17:56:28.066 32273 32273 I chromium: [INFO:CONSOLE(47546)] "Native: tried calling PushNotification.init, but the PushNotification plugin is not installed.", source: file:///android_asset/www/build/main.js (47546)
03-22 17:56:28.071 32273 32273 I chromium: [INFO:CONSOLE(84700)] "Notification init end", source: file:///android_asset/www/build/main.js (84700)
03-22 17:56:28.088 32273 32273 I chromium: [INFO:CONSOLE(1370)] "ERROR", source: file:///android_asset/www/build/main.js (1370)**

**Comment by ullasframer** [comment]
I dont see  push plugin folder inside /**/appName/platforms/android/platform_www/plugins. 
For other plugin like Camera ,Map ,geolocation etc there are folders .

**Comment by lsantaniello** [comment]
I have the same problem. Did you have solve the issue? Please shame me the fix.
Thanks
