### ISSUE TITLE
GCMIntentService.java:472: error: cannot find symbol iconColor

### ISSUE THREAD

**Issue by Ziv-Barber** [phonegap/phonegap-plugin-push#217]
\platforms\android\src\com\adobe\phonegap\push\GCMIntentService.java:472: error: cannot find symbol
            mBuilder.setColor(iconColor);

(Cordova Android @4.0.2)

**Comment by macdonst** [comment]
@Ziv-Barber https://github.com/phonegap/phonegap-plugin-push#compiling

**Comment by lobobobo** [comment]
+1 same issue

**Comment by lobobobo** [comment]
+1 same issue
GC MIntentService.java:565: error: cannot find symbol mBuilder.setColor(iconColor);

**Comment by Ziv-Barber** [comment]
You need to replace the google-play-services.jar with the last one from the Android SDK and then I'll work for you.
