### ISSUE TITLE
Calling PushObject.subscribe() within a loop, only first iteration executes.

### ISSUE THREAD

**Issue by rbrand21** [phonegap/phonegap-plugin-push#2170]
### Expected Behaviour
```
      for(let bill of bills){
        console.log("Bill: " + bill.key)
        this.notifSub.addBillNotificationSubscription(bill.key)
      }

  addBillNotificationSubscription(topic: string){
    console.log("Adding a bill notification subscription for topic: " + topic);
    this.pushObject.subscribe(topic).then((res:any)=>{
      console.log("Success")
    }).catch((error:any)=>{
      console.log("Failed")
    })
}
```

I expect that I would be able to add as many topic subscriptions as I wanted.
Only the first iteration ever gets executed.

### Actual Behaviour
When adding in a debugger; statement, it appears that something has failed, but I never see any error messages in the log.
It should be noted that I was able to successfully subscribe to one topic and successfully generated notifications for that one topic using a firebase function.

### Reproduce Scenario (including but not limited to)
Try calling PushObject.subscribe on each element in list

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Testing on Ionic web based. 

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1
Cordova version 7.1.0
#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@rbrand21 hmm…it might be a problem with the function being async. You call subscribe again before the first one completes. Try using this method of iterating through the array instead.

```
function subscribeToBills(bills) {
    const subscribeToBill = function(bills) {
        console.log("length = " + bills.length);
        // No bills left, stop subscribing
        if (bills.length == 0) {
            console.log("All bills subscribed");
            return;
        }
    
        let bill = bills.pop();
        this.pushObject.subscribe(bill).then((res:any)=>{
          subscribeToBill(bills);
          console.log("Success")
        }).catch((error:any)=>{
          subscribeToBill(bills);
          console.log("Failed")
        });
    };
    
    subscribeToBill(bills);
}
```

It waits for each async function to complete before going off to the next subscription.

**Comment by rbrand21** [comment]
@macdonst Thank you for the response! I added your code to my project and tried it and am still getting the same behavior where the loop either gets stuck or terminates. "length = 5" is printed and then nothing else afterwards

**Comment by rbrand21** [comment]
I'm calling subscribeToBills inside of an onNext from another subscribe method (it's a db call to retrieve the list of bills), although I'm not really sure that makes a difference. The list of bills is successfully retrieved.

**Comment by rbrand21** [comment]
@macdonst So, the originally proposed solution actually works on mobile. I guess it just doesn't work on the web app. Will dig some more eventually and come back with my findings.

**Comment by macdonst** [comment]
Closing as original issue was fixed.
