### ISSUE TITLE
Can not install alongside cordova-plugin-local-notifications?

### ISSUE THREAD

**Issue by F1LT3R** [phonegap/phonegap-plugin-push#2172]
### Expected Behaviour

I expect that I would be able to install `phonegap-plugin-push` alongside a local notifications plugin like [cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications) or [diogo-cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications).

### Actual Behaviour

When I try to install `cordova-plugin-local-notifications` I get the following error:

```shell
cordova plugin add cordova-plugin-local-notification
Installing "cordova-plugin-local-notification" for android
Plugin dependency "cordova-plugin-device@2.0.1" already fetched, using that version.
Dependent plugin "cordova-plugin-device" already installed on android.
Installing "cordova-plugin-badge" for android
ANDROID_HOME=/Users/al/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home
Subproject Path: CordovaLib
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_e7q7xu77c64yhyymaeq14jt1.run(/Users/al/repos/my-org/my-org-cordova-platform/cordova-platform/platforms/android/build.gradle:143)
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
:clean
:CordovaLib:clean

BUILD SUCCESSFUL

Total time: 1.542 secs
Subproject Path: CordovaLib
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-local-notification': CordovaError: Uh oh!
"/Users/al/repos/my-org/my-org-cordova-platform/cordova-platform/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java" already exists!
    at copyNewFile (/Users/al/repos/my-org/my-org-cordova-platform/cordova-platform/platforms/android/cordova/lib/pluginHandlers.js:245:45)
    at install (/Users/al/repos/my-org/my-org-cordova-platform/cordova-platform/platforms/android/cordova/lib/pluginHandlers.js:43:17)
    at ActionStack.process (/Users/al/repos/my-org/my-org-cordova-platform/cordova-platform/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/al/repos/my-org/my-org-cordova-platform/cordova-platform/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/al/repos/my-org/my-org-cordova-platform/cordova-platform/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /Users/al/repos/my-org/my-org-cordova-platform/cordova-platform/platforms/android/cordova/Api.js:243:74
    at _fulfilled (/Users/al/repos/my-org/my-org-cordova-platform/cordova-platform/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/al/repos/my-org/my-org-cordova-platform/cordova-platform/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/al/repos/my-org/my-org-cordova-platform/cordova-platform/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /Users/al/repos/my-org/my-org-cordova-platform/cordova-platform/platforms/android/cordova/node_modules/q/q.js:570:49
(node:54463) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Uh oh!
"/Users/al/repos/my-org/my-org-cordova-platform/cordova-platform/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java" already exists!
(node:54463) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### Steps to Reproduce 

- Start a new app.
- Add `phonegap-plugin-push`
- Try installing `cordova-plugin-local-notifications`

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
 
NA

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

NA

#### Cordova CLI version and cordova platform version

cordova: 8.0.0

Installed platforms:
  android 6.3.0
  ios 4.5.4
Available platforms:
  browser ~5.0.1
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

#### Plugin version

phonegap-plugin-push 2.1.2 "PushPlugin"

**Comment by F1LT3R** [comment]
It seems like a shared resource between `phonegap-plugin-push` and other local notification plugins causes problems.

```shell
"cordova-plugin-device" is required by (cordova-plugin-code-push) and cannot be removed (hint: use -f or --force)
```

Full log...

```shell
cordova plugin remove diogo.cordova.plugin.local-notification
Uninstalling diogo.cordova.plugin.local-notification from android
Subproject Path: CordovaLib
Uninstalling diogo.cordova.plugin.local-notification from ios
Removing "diogo.cordova.plugin.local-notification"
"cordova-plugin-device" is required by (cordova-plugin-code-push) and cannot be removed (hint: use -f or --force)
(node:54989) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError
(node:54989) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Am I missing something? Can you use create notifications from `phonegap-plugin-push`? Why would `phonegap-plugin-push` use a local notification resource?

**Comment by macdonst** [comment]
@F1LT3R this isn't a problem with the push plugin. The id of this plugin is `phonegap-plugin-push` not `cordova-plugin-code-push` so the error you are seeing above is not caused by this plugin. 

The package `cordova-plugin-local-notifications` is badly, badly out of date and you should not use it. The package `cordova-plugin-local-notification` is the one kept up to date by the maintainer.

I feel like you did a `cordova plugin add cordova-plugin-local-notification` one time and a `cordova plugin add cordova-plugin-local-notifications` another time which is why you get that "LocalNotification.java already exists" error.

Check by running `cordova plugins`.

**Comment by F1LT3R** [comment]
Will do, thanks for the clarity @macdonst

**Comment by F1LT3R** [comment]
Interestingly, `cordova-plugin-local-notification` (singular)  from the CLI is one and the same as `cordova-plugin-local-notifications` (plural) in GitHub (See: [https://github.com/katzer/cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications).

And [npmjs diogo-cordova-plugin-local-notifications](www.npmjs.com/package/diogo-cordova-plugin-local-notifications) also points to [github.com/katzer/cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications).

That confused the heck out of me.

**Comment by F1LT3R** [comment]
Thanks, @macdonst Your suggestion worked perfectly.
