### ISSUE TITLE
phonegap-plugin-push ERROR : undefined

### ISSUE THREAD

**Issue by bhumin3i** [phonegap/phonegap-plugin-push#2173]
Discovered plugin "phonegap-plugin-push" in config.xml. Adding it to the project

Installing "phonegap-plugin-push" for ios

Failed to install 'phonegap-plugin-push': undefined

Failed to restore plugin "phonegap-plugin-push" from config.xml. You might need to try adding it again. Error: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /Users/rac/Desktop/Bhumin/RTI/blankRTI/node_modules/.bin in PATH, mode 040777
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)

Usage:

    $ pod COMMAND

      CocoaPods, the Cocoa library package manager.

Commands:

    + cache      Manipulate the CocoaPods cache
    + env        Display pod environment
    + init       Generate a Podfile for the current directory
    + install    Install project dependencies according to versions from a
                 Podfile.lock
    + ipc        Inter-process communication
    + lib        Develop pods
    + list       List pods
    + outdated   Show outdated project dependencies
    + repo       Manage spec-repositories
    + setup      Setup the CocoaPods environment
    + spec       Manage pod specs
    + update     Update outdated project dependencies and create new Podfile.lock

Options:

    --silent     Show nothing
    --version    Show the version of the tool
    --verbose    Show more debugging information
    --no-ansi    Show output without ANSI codes
    --help       Show help banner of specified command
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:47:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'

Discovered plugin "cordova-plugin-geolocation" in config.xml. Adding it to the project

Installing "cordova-plugin-geolocation" for ios

Adding cordova-plugin-geolocation to package.json

Saved plugin info for "cordova-plugin-geolocation" to config.xml

--save flag or autosave detected
Saving ios@~4.5.4 into config.xml file ...
[ERROR] Exception:

**Comment by macdonst** [comment]
@bhumin3i the root cause of the problem is right there in the error messages "You cannot run CocoaPods as root". Don't try and add the plugin as the `root` user.
