### ISSUE TITLE
Can't build with Cordova 8 and Cordova-android 7

### ISSUE THREAD

**Issue by sebj54** [phonegap/phonegap-plugin-push#2175]
### Expected Behaviour
Success on `cordova run` or `cordova build` commands.

### Actual Behaviour
Got this error:

```
[...]
:app:processDebugGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it.
   Searched Location:
  C:\Users\sebas\sites\my-cordova-project\platforms\android\app\src\debug\google-services.json18 actionable tasks: 18 executed

  C:\Users\sebas\sites\my-cordova-project\platforms\android\app\google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 51s
```

### Reproduce Scenario (including but not limited to)
Create a new Cordova project or upgrade your android platform to version 7.

#### Steps to Reproduce 
Just launch `cordova build` after that.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android API 26.

#### Cordova CLI version and cordova platform version
Cordova 8.0.0 and Cordova-android 7.0.0.

#### Plugin version
2.1.2

### Additional information
It worked well before upgrading Cordova and Android platform. With Android platform version 7, the project structure changed to be like in Android Studio (source: https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html).

**Comment by jcesarmobile** [comment]
Can you share your resource-file entry to copy the google-services.json file?

**Comment by macdonst** [comment]
@sebj54 if you are using cordova-android 7 or greater then you need to copy google-services.json file to a different location as per the installation instructions:

```
<platform name="android">
  <resource-file src="google-services.json" target="app/google-services.json" />
</platform>
```

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements

**Comment by sebj54** [comment]
@macdonst Oh, my bad, I haven't checked the documentation after the update!
I confirm that it works great with the `app/` prefix in config.xml.

Thanks for your help!
