### ISSUE TITLE
on('registration') not fired after on('unregister')

### ISSUE THREAD

**Issue by Lenndev** [phonegap/phonegap-plugin-push#2177]
### Expected Behaviour
User has activated/registered for push notifications
User decides to deactivate/unregister for push notifications
User decides to reactivate/register for push notifications again
I expect a new on('registration') to be fired after an  push.unregister was fired.

### Actual Behaviour
The push.unregister works every time, but the on('registration') after an push.unregister is not fired, script is stuck.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
 android 6.0.1 and  ios 11.2.5 
 
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iphone 7 
lg nexus 5
#### Cordova CLI version and cordova platform version

    cordova --version                                    8.0.0
Installed platforms:
  android 7.0.0
  ios 4.5.4

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   phonegap-plugin-push 2.1.2 "PushPlugin"

#### Sample Code that illustrates the problem
```
'use-strict'
class Push{
     constructor(config){
         this.push = PushNotification.init(config);
        }
register()
    {
        return new Promise((resolve, reject) => {

            console.log("[push ] register");//this log i see, after that... nothing
            if (this.push) {//this.push = 
                this.push.on('registration', (data) => {
                    console.info("[Push] registered! ",data);
                    return resolve(data.registrationId);
                });

                //todo problem lies here... registration is not fired at all times on (at least) android
            } else {
                console.error('push register: no PushNotification instance found');
                return reject('no PushNotification instance found');
            }
        });
    }
}

 /**
     * unregister device for push notification
     * @returns {Promise}
     */
    unregister()
    {
        return new Promise((resolve, reject) => {
            this.resetBadgeNumber();
            this.clearAllNotifications();

            this.push.unregister(
                () => {
                    console.debug('Unregistered successfully');
                    this.token = null;
                    // this.push.off('registration');
                    // this.push.off('notification');
                    return resolve();
                },
                () => {
                    console.error('Unregister failed');
                    return reject('[Push] unregister failed');
                }
            );

        });
    }
```

**Comment by fredgalvao** [comment]
Do you call `(<Push> p).register()` again when the user re-enables push notifications? As it's an event handler/listener, you don't need to **register it again**, so I'd recommend not doing so. However, even if that's the case, it shouldn't prevent you from receiving the events back again (twice, if you're registering another event listener on reactivation).

Do you have access to the logs? The issue template has a section for that, and you either missed it or ignored it, and without the logs it might be hard to know where to start.

**Comment by Lenndev** [comment]
yea i call `(<Push> p).register()` again after unregister(); initially `(<Push> p).register()` works ```
this.push.on('registration', (data) => {
                    console.info("[Push] registered! ",data);
                    return resolve(data.registrationId);
                });
```
is called and i get the data.registrationId. but if i run `(<Push> p).register()` again after an unregister, i do not get inside the callback method of the  `this.push.on('registration')` event;

I did see the logs section, but i didn't find it usefull in this case, since it wouldn't log anything except `console.log("[push ] register")` and then nothing (where i expect `console.info("[Push] registered! ",data);`

**Comment by fredgalvao** [comment]
I wasn't talking about web logs, but native ones instead. `adb logcat | grep Push`  is the way to get them. Try to reproduce the whole scenario while loging that, and then share the logs here.

**Comment by fredgalvao** [comment]
> but what do you think i should do to enable/disable push on user input? cause i have this switch input to turn push notifications on/off. so if the user turned it off i don't want push notifications to be received. or should i manage this in the API? check a boolean? what do you recommend?

I didn't mean you shouldn't **unregister**, but instead meant that you don't need to **re-register the event handler** when the user decides to reactivate push notifications. You already have the original function attached to that event, you only need to listen to it whenever it changes.

**Comment by Lenndev** [comment]
ah oke. But is there a PushNotifications.register() method then?
ill have look at the system logs for you

**Comment by Lenndev** [comment]
@fredgalvao could you tell me how you would handle this situation where the user should be able to toggle push notifications?

**Comment by fredgalvao** [comment]
For the initial registration, I call `.init` and `on('registration')`, and then call `.on('notification')` too. As soon as the `registration` event triggers, I send a request to my backend to register this device/installation/registrationId as a valid push notification target (with platform details to differ between iOS/APNS and Android/GCM targets.

When the user disables notifications, I call `unregister` on the plugin API and then I send a request to my backend to signal that this user's registrationId is not to be considered a valid push notification target anymore.

If the user then decides to re-enable notifications, I re-execute the whole process from the start:
```ts
//reinitializes the API and create a new object, leaving the old one free to die through garbage collect
push = P.init(...)
push.on('registration', () => {...})
push.on('notification', () => {...})
```

**Comment by fredgalvao** [comment]
@macdonst I'm starting to question if this is the expected behaviour instead of a bug. Can you help us?

**Comment by Lenndev** [comment]
@fredgalvao  Ah thanks for your response. My flow is quite the same except i only init PushNotifications once (first time only) then check if userdata.push == true, to decide if it needs to be "activated". So I might reinit the whole thing then... Although you would expect that it should be possible to init once and register/unregister multiple times... right?

**Comment by macdonst** [comment]
@Lenndev if you call `unregister` you will have to call `init` again. The `init` function is the one that requests a new token from the remote push service.

**Comment by fredgalvao** [comment]
So yeah, it's the expected behaviour. I didn't get the question at first glance, but now it's clear.

@Lenndev Feel free to reopen the issue if you can't solve it by reinitializing the plugin API.

**Comment by fredgalvao** [comment]
@Lenndev and @macdonst Please see if 58e87593e749d5c6da2a45906a8c7c9309d6b09a fixes the confusion.
