### ISSUE TITLE
Failed to install 'phonegap-plugin-push': undefined iOS @ionic 2

### ISSUE THREAD

**Issue by bhandaribhumin** [phonegap/phonegap-plugin-push#2179]
$pod --version  
 1.1.1

$ionic info 

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : browser 5.0.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node  : v8.9.3
    npm   : 5.5.1 
    OS    : macOS High Sierra
    Xcode : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

ERROR while $ sudo ionic cordova platform add ios 

Installing "phonegap-plugin-push" for ios
Failed to install 'phonegap-plugin-push': undefined
(node:1840) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)

Usage:

    $ pod COMMAND

      CocoaPods, the Cocoa library package manager.

Commands:

    + cache      Manipulate the CocoaPods cache
    + env        Display pod environment
    + init       Generate a Podfile for the current directory
    + install    Install project dependencies according to versions from a
                 Podfile.lock
    + ipc        Inter-process communication
    + lib        Develop pods
    + list       List pods
    + outdated   Show outdated project dependencies
    + repo       Manage spec-repositories
    + setup      Setup the CocoaPods environment
    + spec       Manage pod specs
    + update     Update outdated project dependencies and create new Podfile.lock

Options:

    --silent     Show nothing
    --version    Show the version of the tool
    --verbose    Show more debugging information
    --no-ansi    Show output without ANSI codes
    --help       Show help banner of specified command
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:47:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:22:in `load'
	from /usr/local/bin/pod:22:in `<main>'

(node:1840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

======= NOTE =====

without  sudo  Error: EACCES: permission denied, 

Please help me on this

**Comment by jcesarmobile** [comment]
You have to fix your project permissions, sorry, we can't help you with that.
You shouldn't use sudo with any cordova/phonegap/npm command.

**Comment by bhandaribhumin** [comment]
Hi @jcesarmobile  now I'm able to used $ionic cordova platform add ios
but after Cloning into 'master'... screen will be stuck 

iOS project created with cordova-ios@4.5.4

Installing "cordova-plugin-device" for ios

Installing "cordova-plugin-ionic-keyboard" for ios

Installing "cordova-plugin-ionic-webview" for ios

Installing "cordova-plugin-splashscreen" for ios

Installing "cordova-plugin-whitelist" for ios

Installing "phonegap-plugin-push" for ios

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:141: warning: Insecure world writable dir /Users/bhuminb/Desktop/Projects/BLANKTest/node_modules/.bin in PATH, mode 040777

Cloning into 'master'...

Stuck screen after cmd+c it stop.
