### ISSUE TITLE
Send FCM Push Notification using FCM v1 API

### ISSUE THREAD

**Issue by lucasbasquerotto** [phonegap/phonegap-plugin-push#2181]
I just want to have some feedback to know if using the FCM v1 API ([https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages)), instead of the legacy API ([https://firebase.google.com/docs/cloud-messaging/http-server-ref](https://firebase.google.com/docs/cloud-messaging/http-server-ref)) to send push notifications works properly with the push plugin.

Using the new API I can send to both Android and iOS in the same payload, with the data sent in the format:

```
{
  "data": { ... },
  "android": { ... },
  "webpush": { ... },
  "apns": { ... },

  // Union field target can be only one of the following:
  "token": string,
  "topic": string,
  "condition": string,
  // End of list of possible types for union field target.
}
```

I tested sending a message like the following:

```
POST https://fcm.googleapis.com/v1/projects/logical-utility-XXXXXX/messages:send
{
    "message": {
        "data": {
            "body": "Test push notification.",
            "content-available": "1",
            "myData": "someJson",
            "notId": "1",
            "style": "inbox",
            "summaryText": "%n% new notifications",
            "tag": "1",
            "title": "New Notification"
        },
        "token": "XXXXXX"
    }
}
```

and everything worked fine.

Because this change is only in the back-end I don't see why it would have conflicts with this plugin, but I would like to know if there is some edge case.

**Comment by macdonst** [comment]
@lucasbasquerotto if you send a message like this:

```
POST https://fcm.googleapis.com/v1/projects/logical-utility-XXXXXX/messages:send
{
    "message": {
        "data": {
            "body": "Test push notification.",
            "content-available": "1",
            "myData": "someJson",
            "notId": "1",
            "style": "inbox",
            "summaryText": "%n% new notifications",
            "tag": "1",
            "title": "New Notification"
        },
        "token": "XXXXXX"
    }
}```

I would suspect that it will work amazingly for Android but not iOS. If you were sending to an iOS app registered to receive FCM messages you'd need to tweak the payload:

```
POST https://fcm.googleapis.com/v1/projects/logical-utility-XXXXXX/messages:send
{
    "message": {
        "notification": {
            "body": "Test push notification.",
            "title": "New Notification"
        },
        "data": {
            "content-available": "1",
            "myData": "someJson",
            "notId": "1",
            "style": "inbox",
            "summaryText": "%n% new notifications",
            "tag": "1",
        },
        "token": "XXXXXX"
    }
}
```

Because the FCM libraries we use on iOS expect the message to be in `notification` not `data`. But on Android because of the way `onMessageReceived` is fired we need everything in `data`.

**Comment by lucasbasquerotto** [comment]
@macdonst Thanks for the answer. I have only Android devices to test for now, so I created a generic payload. To support both Android and iOS, I would do something like:

```
POST https://fcm.googleapis.com/v1/projects/logical-utility-XXXXXX/messages:send
{
    "message": {
        "token": "XXXXXX",
        //"topic": "my-topic",
		
        // When the token belongs to an Android device, or when sending to a topic:
        "android": {
            "data": {
                "notId": "1",
                "tag": "1",
                "title": "New Notification",
                "body": "Test push notification.",
                "content-available": "1",
                "style": "inbox",
                "summaryText": "%n% new notifications",
                "myData": "someJson"
            }
        },
		
        // When the token belongs to an iOS device, or when sending to a topic:
        "apns": {
            "payload": {
                "notId": "1",
                "aps": {
                    "thread-id": "1",
                    "alert": {
                        "title": "New Notification",
                        "body": "Test push notification."
                    },
                    "moredata": "Do more stuff",
                    "content-available": 1
                },
                "myData": "someJson"
            }
        }
    }
}
```

The `apns` field receives an [ApnsConfig](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#ApnsConfig) object, that is like:

```
{
  "headers": {
    string: string,
    ...
  },
  "payload": {
    object
  },
}
```

The `payload` field is described as follows:

> APNs payload as a JSON object, including both aps dictionary and custom payload. See [Payload Key Reference](https://goo.gl/32Pl5W).

The data I've sent worked for Android (both sending to a specific device using the token, or to a topic). Unfortunately I don't have an iOS device with me at the moment to test if this will work for iOS though.
