### ISSUE TITLE
iOS Notifications not being received after project update

### ISSUE THREAD

**Issue by richardshergold** [phonegap/phonegap-plugin-push#2182]
### Background

I have recently upgraded our Ionic project which was receiving Push Notifications ok.  As part of the upgrade my Cordova CLI was upgraded to 8.0.0, the Cordova iOS platform to 4.5.4 and the version of this plugin to 1.10.6 (we have to use version 1 of the plugin because we are not yet using FCM for Android)

### Expected Behaviour

Notifications should be received on iOS device

### Actual Behaviour

Having upgraded our we aren't getting any notifications - even though we have checked the server and the token is being set correctly and the notification is being sent correctly through APNS.

#### Test Devices
Various iOS devices running iOS 11.x

#### Cordova CLI version and cordova platform version

    cordova --version                      8.0.0
    cordova platform version ios    4.5.4           

#### Plugin version

    phonegap-plugin-push 1.10.5
    I tried downgrading back to 1.10.5 but it made no difference.

### Here is my full Ionic info output:

cli packages: (/Users/richardshergold/IonicProjects/myApp/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    Node       : v6.11.4
    npm        : 5.5.1
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

### Here is my list of plugins:

cordova-plugin-advanced-http 1.9.1 "Advanced HTTP plugin"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-calendar 4.6.0 "Calendar"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-touch-id 3.3.1 "Touch ID"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.4 "Cordova WKWebView Engine"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.10.5 "PushPlugin"

Any idea why this might not be working?

**Comment by fredgalvao** [comment]
Can you provide the payload and logcat logs on a reproduced scenario?

**Comment by iDroidindia** [comment]
We are also facing the similar issue. We are able to receive the GCM ID but unable to receive the Notification  on iO device. The Payload which we are suing is as follows:

<?php

//GCM IDs -- Need  to use readl one which we get via GCM
		 
$to="drfLud82JN0:87687689798798708yrthyhgfhnfgnnmjghjgdsfsgfy6756756757-Jr0hEdvQBN5pkYpOy2cSlPJHOJVx0f1rvYxUSrMnuigdfghfhfgjhgjkhkhjkyuiytut45645654safsfssdfgrnntrnthfhf";

$payload = '{"body" => "Data", "title" => "Test Title", "icon" => "new"}';
  
		//Sending Data to various devices
		sendPush($to,$payload);		

		function sendPush($to,$title)
		{
	
				// API Access key from Google API's Console
				// Replace API Key
				define( 'API_ACCESS_KEY', 'AIzakhjkhkhSyA81n1XIw_987ghhjgjhgjkjlkjljklkjljkl0');			 
				$registrationIds = array($to);
				 
				$fields = array
				(
					'registration_ids' => $registrationIds,
  					'priority' => 'normal',
					'notification' => $message

				);
				$headers = array
				(
					'Authorization: key=' . API_ACCESS_KEY,
					'Content-Type: application/json'
				);

				$ch = curl_init();
				curl_setopt( $ch,CURLOPT_URL, 'https://android.googleapis.com/gcm/send' );
				curl_setopt( $ch,CURLOPT_POST, true );
				curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
				curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
				curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
				curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fields ) );
				$result = curl_exec($ch );
				curl_close( $ch );

				echo $result; 
	 

		}
		function al() {
					echo "AL" ;
				}
		function cl() {
					echo "CL"	;
				}

		?>
		<html>
			<body></body>
		</html>

**Comment by richardshergold** [comment]
All working now - we had an issue on our server
