### ISSUE TITLE
When I want to create apk in the android studio, I get this error; Error:Error converting bytecode to dex: Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzeu;

### ISSUE THREAD

**Issue by isacoskun** [phonegap/phonegap-plugin-push#2188]
Error:Execution failed for task ':app:transformDexWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.android.dx.command.Main with arguments {--dex --num-threads=4 --output C:\DanlaBilic\app\build\intermediates\transforms\dex\release\0 --min-sdk-version 16 C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\25.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\5.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\38.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\20.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\0.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\11.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\17.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\54.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\6.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\4.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\26.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\13.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\32.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\39.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\10.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\23.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\53.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\14.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\9.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\18.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\57.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\27.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\40.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\31.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\19.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\49.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\22.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\30.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\58.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\28.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\2.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\8.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\15.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\52.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\51.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\56.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\21.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\34.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\24.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\3.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\59.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\7.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\16.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\55.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\29.jar C:\DanlaBilic\app\build\intermediates\transforms\preDex\release\12.jar}

*************************************************************************************
This is my .grandle
*************************************************************************************
 buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {

    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.google.firebase:firebase-database:11.8.0'
    implementation 'com.android.support:cardview-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.google.firebase:firebase-auth:11.8.0'
    implementation 'com.google.firebase:firebase-storage:11.8.0'
    implementation 'com.google.firebase:firebase-messaging:11.8.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    implementation 'com.github.bumptech.glide:glide:4.0.0-RC1'
    implementation 'com.github.jetradarmobile:android-snowfall:1.1.6'
    compile 'com.facebook.android:audience-network-sdk:4.27.0'

}
apply plugin: 'com.google.gms.google-services'

************************************************************************************************

What is the problem ?
Thank you for your help

**Comment by macdonst** [comment]
@isacoskun Please, please follow the issue template. 

Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
