### ISSUE TITLE
file not found 

### ISSUE THREAD

**Issue by ajayadglobal360** [phonegap/phonegap-plugin-push#2189]
fatal error: 'google/protobuf/Empty.pbobjc.h' file not found
 #import "google/protobuf/Empty.pbobjc.h"
i have also done
cd platforms/ios
pod install
but still getting this error plz guide me if anyone fixed this issue

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
