### ISSUE TITLE
Clear One Notification (Android)

### ISSUE THREAD

**Issue by DavidBriglio** [phonegap/phonegap-plugin-push#2191]
### Expected Behaviour
To have a method that will clear one single notification, on the Android platform.

### Actual Behaviour
There only exists a `clearAllNotifications` method that will remove all notifications.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android (all)

**None of the other fields apply to this.**

---

I would like to make a PR that will add single notification removal support for the android platform. This is specifically in regard to clearing ongoing notifications. If there are multiple notifications being displayed, and you want to remove an ongoing notification your only option is to remove all notifications.

**Comment by macdonst** [comment]
Android and iOS support in 3.0.0.
