### ISSUE TITLE
Push Notification , Redirect on page, by clicking on notification from notification tray 

### ISSUE THREAD

**Issue by pradosh05** [phonegap/phonegap-plugin-push#2196]
I am using phonegap-plugin-push plugin for FCM push notification,

Here I am able to get notification when app is running in background or app is in active status notification is working fine in this state.

But when app is in background state and any notificaiton came in that condition if any user click on the notificaiotn he must be redirect on any spacific page, for this I try so many way but its not working . 

I am using following code to initialize notification

var push = PushNotification.init({
    android: {
        senderID: '436009364694',
        alert: true,
        badge: true,
        icon: 'icon',
	    sound: true,
	    vibrate: true
    },
    ios: {
        alert: "true",
        badge: "true",
        sound: "true",
        vibrate: true,
	    clearBadge: true
    },
    windows: {}
});

And I am using following code to trigger the notification

push.on('notification', function(data) {
});

above code is only working when app is in running state but its not working when app is in background, 

Any one know how to trigger click event if app in background state

**Comment by bhandaribhumin** [comment]
Same issue I’m facing anyone please help me on this for ionic 2/3

**Comment by bhumin3i** [comment]
@pradosh05  getting same issue ;(. any solution?


```
    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.2
    npm  : 5.6.0
    OS   : Windows 7

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

```

**Comment by macdonst** [comment]
EVERYONE PLEASE FOLLOW THE ISSUE TEMPLATE WHEN OPENING A NEW ISSUE!!!

@pradosh05 I have written a small tutorial on how to redirect you app to a new page based on data in the push notification:

http://macdonst.github.io/push-workshop/module7.html

You can use this as a basis for what you want to do.

**Comment by pradosh05** [comment]
@macdonst Thanks for the reply , but response is not coming inside push.on('notification', function(data) {})

**Comment by macdonst** [comment]
@pradosh05 what does your push payload look like?

**Comment by pradosh05** [comment]
@macdonst macdo  this is my payload.  {
to: "----device id  here",
priority: "high",
restricted_package_name: "",
notification: {
eventid: "",
types: "",
body: "You've successfully attended the 'dfgdsfg' event and soon you will receive the point.",
title: "Event attend confirmation",
icon: "myicon",
badge: 1,
sound: "default"
}
}

**Comment by macdonst** [comment]
@pradosh05 well there is your problem right there. You are running into the `notification` vs `data` problem that I have answered many times during issue and have documented. Please let me know how I can make it more clear.

Change your payload to:

```
{
to: "----device id  here",
priority: "high",
restricted_package_name: "",
data: {
  eventid: "",
  types: "",
  body: "You've successfully attended the 'dfgdsfg' event and soon you will receive the point.",
  title: "Event attend confirmation",
  icon: "myicon",
  badge: 1,
  sound: "default"
  }
}
```

and re-test. 

Read up  on the why here:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

**Comment by pradosh05** [comment]
@macdonst Thanks a lot , it working ,

**Comment by bhandaribhumin** [comment]
hi @macdonst 

I have same problem how I solve this my code Is : 

`pushsetup() {
    const options: PushOptions = {
      android: {
        senderID: 'xxxxxxxx'
      },
      ios: {
        alert: 'true',
        badge: true,
        sound: 'false'
      },
      windows: {}
    };
    const pushObject: PushObject = this.push.init(options);
    pushObject.on('notification').subscribe((notification: any) => {
      console.log('on notification',notification);
      if (notification.additionalData.foreground) {
        console.log('on if');
        this.badgeCount++;
        this.events.publish('notification:DisplaybadgeCount',this.badgeCount);
       // if application open, show popup
        let confirmAlert = this.alertCtrl.create({
          title: 'New Notification',
          message: notification.message,
          buttons: [{
            text: 'Ignore',
            role: 'cancel'
          }, {
            text: 'View',
            handler: () => {
              this.nav.push('NotificationsPage', { message: notification.message });
            }
          }]
        });
        confirmAlert.present();
        //this.nav.push('NotificationsPage', { message: notification.message });
      } else {
        console.log('on else');
       this.nav.push('NotificationsPage', { message: notification.message });
       console.log('Push notification clicked');
      }
    });
    
    pushObject.on('registration').subscribe((registration: any) => {
      //do whatever you want with the registration ID
      console.log('registration', registration);
      this.localStore.setDeviceToken(registration);
    });
    pushObject.on('error').subscribe(error => alert('Error with connection ' + error));
  }`

**Comment by bhandaribhumin** [comment]
@macdonst  your given solution payload I can't see  "content-available": '1'  , so how it's fix?

**Comment by macdonst** [comment]
@bhandaribhumin you shouldn't need to set content-available to 1 if you are clicking on the notification in the shade but if you really need it. It would be:

```
{
to: "----device id  here",
priority: "high",
restricted_package_name: "",
data: {
  eventid: "",
  types: "",
  body: "You've successfully attended the 'dfgdsfg' event and soon you will receive the point.",
  title: "Event attend confirmation",
  icon: "myicon",
  badge: 1,
  sound: "default",
  "content-available": "1"
  }
}

```

**Comment by smadapathi** [comment]
@macdonst I am using firebase console to send message to app. I still face this issue, would like to know how to differentiate `notification` vs `data` in firebase console. Thanks in advance!

**Comment by smadapathi** [comment]
@bhandaribhumin i am trying to achieve similar functionality as yours, were you able to make it work? If so, please let me know what you have done.

**Comment by smadapathi** [comment]
@macdonst @bhandaribhumin instead of using firebase console to send notification, I sent notification using firebase admin SDK (nodejs) and it is working fine as expected. Thanks all!

**Comment by bhandaribhumin** [comment]
@smadapathi  great 

I'm using below PAYLOAD for sending notification on iOS and android it's working for me.
 
var anroidTemplate = {
                "notification": {
                    "body": "$(message)",
                    "title": "$(title)",
                },
                "data": {
                    "message": "$(message)",
                    "meetingName": "$(meetingname)",
                    "meetingRoom": "$(meetingroom)",
                    "organizer": "$(orgaizername)",
                    "startdateTime": "$(startdateTime)",
                    "enddateTime": "$(enddateTime)"
                }
            };
            var iostemplate = {
                "aps": { "alert": "$(message)" },
                "meetingName": "$(meetingname)",
                "meetingRoom": "$(meetingroom)",
                "organizer": "$(orgaizername)",
                "startdateTime": "$(startdateTime)",
                "enddateTime": "$(enddateTime)"
            };
