### ISSUE TITLE
Migrating 1.8.1 to 2.0.0 and GCM to FCM and iOS not receiving notifications

### ISSUE THREAD

**Issue by ppetree** [phonegap/phonegap-plugin-push#2199]
### Expected Behaviour
Register to receive push notifications
Receive Push Notifications

### Actual Behaviour
Not registering on ios
Nothing received on ios

### Reproduce Scenario (including but not limited to)
Upgrading from 1.8.1 to 2.0.0 and migrating from GCM to FCM
(I have to do this with three projects)

#### Steps to Reproduce 
Install push-plugin 2.0.0
Register device
Send a push notification via FCM
Wait until the priest says ashes to ashes, dust to dust

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 9.3, iOS 10.x, iOS 11.x
iPhone 4c, 5s, 6, iPad

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Android Samsung 4.x and LG 6.x

#### Cordova CLI version and cordova platform version
PGB 7.1

#### Plugin version
2.0.0

#### Sample Push Data Payload
```
{"priority":"normal","notification":{"body":"Push registration sucessful","title":"Welcome!","sound":"default"},"to":["dYToNuNWN9g:..."]}
```

#### Logs taken while reproducing problem
Server logs show all push notifications successfully sent.

*These warnings produced during PGB for iOS*

```
iphoneos/CoolApp.build/DerivedSources -F/project/build -F/project/Pods/FirebaseAnalytics/Frameworks -F/project/Pods/FirebaseCore/Frameworks -F/project/Pods/FirebaseInstanceID/Frameworks -F/project/Pods/FirebaseMessaging/Frameworks -isystem /project/Pods/Headers/Public -isystem /project/Pods/Headers/Public/FirebaseAnalytics -isystem /project/Pods/Headers/Public/FirebaseCore -isystem /project/Pods/Headers/Public/FirebaseInstanceID -isystem /project/Pods/Headers/Public/FirebaseMessaging -isystem /project/Pods/Headers/Public/GoogleToolboxForMac -isystem /project/Pods/Headers/Public/Protobuf -isystem /project/Pods/Headers/Public/nanopb -isystem /project/Pods/Headers/Public -isystem /project/Pods/Headers/Public/FirebaseAnalytics -isystem /project/Pods/Headers/Public/FirebaseCore -isystem /project/Pods/Headers/Public/FirebaseInstanceID -isystem /project/Pods/Headers/Public/FirebaseMessaging -isystem /project/Pods/Headers/Public/GoogleToolboxForMac -isystem /project/Pods/Headers/Public/Protobuf -isystem /project/Pods/Headers/Public/nanopb -include /private/project/build/sharedpch/CoolApp-Prefix-aijvbldpbkbuffawcxktldblvurv/CoolApp-Prefix.pch -MMD -MT dependencies -MF /Library/Developer/Xcode/DerivedData/CoolApp-fjyqdhfekxkxpqcmeonyehhlsnrv/Build/Intermediates.noindex/ArchiveIntermediates/CoolApp/IntermediateBuildFilesPath/CoolApp.build/Release-iphoneos/CoolApp.build/Objects-normal/armv7/PushPlugin.d --serialize-diagnostics /Library/Developer/Xcode/DerivedData/CoolApp-fjyqdhfekxkxpqcmeonyehhlsnrv/Build/Intermediates.noindex/ArchiveIntermediates/CoolApp/IntermediateBuildFilesPath/CoolApp.build/Release-iphoneos/CoolApp.build/Objects-normal/armv7/PushPlugin.dia -c /project/CoolApp/Plugins/phonegap-plugin-push/PushPlugin.m -o /Library/Developer/Xcode/DerivedData/CoolApp-fjyqdhfekxkxpqcmeonyehhlsnrv/Build/Intermediates.noindex/ArchiveIntermediates/CoolApp/IntermediateBuildFilesPath/CoolApp.build/Release-iphoneos/CoolApp.build/Objects-normal/armv7/PushPlugin.o
/project/CoolApp/Plugins/phonegap-plugin-push/PushPlugin.m:529:42: warning: undeclared selector 'userHasRemoteNotificationsEnabled' [-Wundeclared-selector]
    if ([appDelegate respondsToSelector:@selector(userHasRemoteNotificationsEnabled)]) {
                                         ^
/project/CoolApp/Plugins/phonegap-plugin-push/PushPlugin.m:530:49: warning: undeclared selector 'userHasRemoteNotificationsEnabled' [-Wundeclared-selector]
        enabled = [appDelegate performSelector:@selector(userHasRemoteNotificationsEnabled)];
                                                ^
/project/CoolApp/Plugins/phonegap-plugin-push/PushPlugin.m:530:17: warning: incompatible pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from 'id' [-Wint-conversion]
        enabled = [appDelegate performSelector:@selector(userHasRemoteNotificationsEnabled)];
                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 warnings generated.
```

Other comments:

Your docs are wrong... 

```
<platform name="android">
  <resource-file src="google-services.json" target="app/google-services.json" />
</platform>
```

Will create an error on the android build and the plugin will NOT be included.  However, changing the target as shown below will include the plugin in the build.

```
<resource-file src="google-services.json" target="src/release/google-services.json" />
```

**Comment by macdonst** [comment]
@ppetree okay, there is a lot to unpack here. First this isn't the place to ask for help with PGB. You do that on the PGB forum. https://forums.adobe.com/community/phonegap/build

Second, if you are not getting the registration event it is usually a problem with the certificates not being correct. If you can show some logs in Xcode that is really helpful in debugging this issue.

When moving from 1.8 to 2.0 did you intend to switch from APNS to FCM on iOS? You don't have to, you can still stick with APNS. One of the reasons that I ask is that you don't mention delivering an `GoogleService-Info.plist` file.

As for the docs being wrong. They are not. You are using PGB 7.1 which does not have cordova-android 7. That's not introduce until PGB 8.0 so you should just be able to use:

```
<platform name="android">
  <resource-file src="google-services.json" target="google-services.json" />
</platform>
```

**Comment by ppetree** [comment]
I'm not asking for PGB help.  These warnings, I believe, are generated by your code... is that not correct?

The GoogleService-Info.plist is included.  I'm using FCM, so would switching not be the appropriate thing to do?

It is registering, just not receiving notifications.  Should I not include the google-services.plist to force google/fcm to send via apns?

**Comment by macdonst** [comment]
@ppetree yup, those warnings are in the push plugin but they are just warning not errors so they can be ignored. 

It's up to you. The plugin will support APNS or FCM. If you are getting a registration ID but no push messages it is usually a problem with the certificates. Either signed with dev and sending to prod or vice versa.
