### ISSUE TITLE
ionic 3 App Crash in Android 4.4

### ISSUE THREAD

**Issue by jayeshkorat18** [phonegap/phonegap-plugin-push#2202]
### Android app not working in Android 4.4

When we open app in `Android 4.4` app crash on start up and give message `unfortunately, app has stopped.`

After i debug app with connect to android studio and it's show the actual error as following.

#### Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.firefuze.android-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.firefuze.android-1, /vendor/lib, /system/lib]]  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
   
----------------------------                                                        
### I have use following plugin for my app                                                                      
com-badrit-base64 0.2.0 "Base64"
com.hutchind.cordova.plugins.streamingmedia 0.1.4 "StreamingMedia"
cordova-clipboard 1.1.1 "Clipboard"
cordova-plugin-calendar 5.0.0 "Calendar"
cordova-plugin-camera 3.0.0 "Camera"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.1.2 "PushPlugin"
twitter-connect-plugin 0.6.0 "Twitter Connect"

#### Cordova CLI version and cordova platform version

    cordova --version  : 8.0.0                                  
    cordova platform version android : android 6.4.0                 

Please guide how we can Fix the issue

**Comment by macdonst** [comment]
@jayeshkorat18 see #2129
