### ISSUE TITLE
In ios app, unable to Receive a Notification when app is in foreground

### ISSUE THREAD

**Issue by Prashant454** [phonegap/phonegap-plugin-push#2206]
### Expected Behaviour
Should Receive a Notification when app is in foreground
### Actual Behaviour
does nothing not even a log is printed
#### Steps to Reproduce 
open app and try to send fcm 
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ios 9.0
#### Cordova CLI version and cordova platform version

    cordova --version                                    7.0.1
    cordova platform version ios                      ios 4.4.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

#### Sample Push Data Payload
{
"title": "New Update Available",
"body": "EventsPage",
"sound": "default",
"image": "www/assets/img/icon.png",
"style": "picture",
"picture": "http://im.rediff.com/news/2014/aug/25bmc.jpg",
"page": "EventsPage",
"image-type": "circle",
"content-available": 1,
"force-start": 1,
"summaryText": "EventsPage",
"click_action": "FCM_PLUGIN_ACTIVITY",
"notId": 7248,
"surveyID": "ewtawgreg-gragrag-rgarhthgbad"
}
#### Sample Code that illustrates the problem

```
pushObject.on('notification').subscribe((notification: any) => {

        //working
        // this.localNotifications.schedule({
        //   id: 1,
        //   text: 'Single ILocalNotification',
        //   sound: this.platform.is('android')? 'file://sound.mp3': 'file://beep.caf',
        //   data: { secret: 'dd' }
        // });

        // this.events.publish('notification:arrived', {count:1,page:notification.additionalData.page});
        console.log('1noti' + JSON.stringify(notification));

        if(MyApp.notiID!=notification.additionalData.notId) {
          this.events.publish('notification:arrived', {count:1,page:notification.additionalData.page});
          console.log('2noti' + notification.additionalData.notId);
          MyApp.notiID=notification.additionalData.notId;

          var noti1 = {
            title: notification.title,
            description: notification.message,
            notificationType: notification.additionalData.notificationType,
            page: notification.additionalData.page,
            data: notification.additionalData,
            photoPath: notification.additionalData.picture,
            updatedOn: new Date(),
            viewed: 1,
            notID:0
          };
          this.storage.get('Notifications').then((data) => {
            if (data != null) {
              this.Notifications = data;
              noti1['notID'] = data.length + 1;
              this.Notifications.push(noti1);
              this.storage.set('Notifications', this.Notifications);
            }
            else{
              this.Notifications=[];
              noti1['notID'] = 1;
              this.Notifications.push(noti1);
              this.storage.set('Notifications', this.Notifications);
            }

          });
        }

        if (notification.additionalData.foreground == true)
        {

          let alert = this.alertCtrl.create({
            title: 'New Notification',
            message: notification.title,
            buttons: [
              {
                text: 'Close',
                role: 'cancel',
                handler: () => {
                  // console.log('Cancel clicked');
                }
              },
              {
                text: 'View',
                handler: () => {
                  // user tapped on notification
                  // alert('tapped');
                  this.app.getActiveNav().push(notification.additionalData.page,{data:notification.additionalData});
                  this.storage.set('curNotification', '');
                }

              }
            ]
          });
          alert.present();

        }

        else if (notification.additionalData.foreground == false &&
          notification.additionalData.coldstart == true){
          this.storage.set('curNotification',notification.additionalData);
        }

      }
```

#### Logs taken while reproducing problem
Even if this log says notification received but wont call On('notification') event
2018-02-17 15:44:43.292 Credai Maharashtra[721:121911] didReceiveNotification with fetchCompletionHandler
2018-02-17 15:44:43.292 Credai Maharashtra[721:121911] app active
2018-02-17 15:44:43.293 Credai Maharashtra[721:121911] Notification received
2018-02-17 15:44:43.293 Credai Maharashtra[721:121911] Push Plugin key: badge
2018-02-17 15:44:43.293 Credai Maharashtra[721:121911] Push Plugin key: sound
2018-02-17 15:44:43.293 Credai Maharashtra[721:121911] Push Plugin key: alert

**Comment by macdonst** [comment]
@Prashant454 what do you see in the console logs when you inspect the app in Safari?

**Comment by Prashant454** [comment]
I didn't see anything in safari console
But xcode shows this 

2018-02-17 15:44:43.292 Credai Maharashtra[721:121911] didReceiveNotification with fetchCompletionHandler
2018-02-17 15:44:43.292 Credai Maharashtra[721:121911] app active
2018-02-17 15:44:43.293 Credai Maharashtra[721:121911] Notification received
2018-02-17 15:44:43.293 Credai Maharashtra[721:121911] Push Plugin key: badge
2018-02-17 15:44:43.293 Credai Maharashtra[721:121911] Push Plugin key: sound
2018-02-17 15:44:43.293 Credai Maharashtra[721:121911] Push Plugin key: alert

**Comment by packruler** [comment]
I have this same problem with:
iOS 11.2
cordova 8.0.0
cordova platform version ios 4.5.4

**Comment by macdonst** [comment]
@Prashant454 try this type of payload on iOS:

```
{
    "registration_ids": ["my device id"],
    "notification": {
"title": "New Update Available",
"body": "EventsPage",
    }
    "data": {
"notId": 7248,
"surveyID": "ewtawgreg-gragrag-rgarhthgbad"
    }
}
```

**Comment by Prashant454** [comment]
I have tried with this payload not working in foreground. In background works fine

{
    "registration_ids": ["my device id"],
    "notification": {
"title": "New Update Available",
"body": "EventsPage",
    }
    "data": {
"notId": 7248,
"surveyID": "ewtawgreg-gragrag-rgarhthgbad"
    }
}

**Comment by Prashant454** [comment]
I have uninstalled cordova ios 4.5.4 and installed 4.4.0 and refollow steps from scratch.
 its working fine now.

**Comment by pinturic** [comment]
I am having the same problem.
Is reverting ios cordova-ios the only solution?
