### ISSUE TITLE
security Issues in PushHandlerActivity

### ISSUE THREAD

**Issue by abhibeta** [phonegap/phonegap-plugin-push#2207]
Hi 

I am using this plugin and My penetration team has reported below issues under severe category.
I need to understand implication of these 

1. **Issue** The activity “com.adobe.phonegap.push.PushHandlerActivity” is shared with other apps on the device leaving it vulnerable to attack from malicious apps 
**Mitigation step** : Set the activity to False to ensure it can only be launched only by components of the same application
**Result** : Changing the property results in the notification not being received. So we cannot change the property if the notification is needed.

**Comment by fredgalvao** [comment]
@abhibeta We've gone through that once before, and the solution was https://github.com/phonegap/phonegap-plugin-push/pull/1362. Even though we use the same `android:name`, we use custom (based on the applicationId, which is unique by definition) to generate the permission name, so afaik the issue you're describing **should not be an issue**.

I'm not an expert on android internal workings and component lifecycle, so I can't say for sure, but please take a moment to check the PR I linked and see if that's still the case.

**Comment by macdonst** [comment]
@abhibeta I will look into your issues shortly but I just want to point out that what you have done is very irresponsible. If you find a security bug or possible bug in an software product whether it is open or closed source the first step is to contact the maintainer/company before going public. Your "penetration team" should have informed you that a process usually exists.

This website explains it way better than I can: http://howdoireportavuln.com/

Additionally, I've quickly read your 4 bug reports and none of them follow the issue guidelines which makes things way more difficult for me. Adding to that difficulty the issues do not point our exact source code lines but rather vague Android security issues.

All in all, if you want quicker responses when dealing this this type of issue you should follow the accepted industry wide process and provide enough details.

**Comment by abhibeta** [comment]
Thanks Macdonst. 
I did reached company and they say its default code from plugin and its setting, so there is nothing they can do from their end .

I am adding file and line no. where bug is reported .
Location: AndroidManifest.xml
Line no.: 144

**Comment by macdonst** [comment]
@abhibeta what company did you reach out to? They did not reach out to me nor Adobe. Also they are not being 100% truthful as this is an open source project with the source available. They could have always sent a pull request or contacted me about the issue.

**Comment by macdonst** [comment]
@abhibeta your example seems to be referring to a really old version of the plugin, that is, before #1362 was merged back in November of 2016. Please upgrade the version of the push plugin you are using to avoid this security warning.

**Comment by abhibeta** [comment]
Thanks @macdonst I will update plugin to version suggested and validate.
