### ISSUE TITLE
Security Issue in Broadcast Receiver

### ISSUE THREAD

**Issue by abhibeta** [phonegap/phonegap-plugin-push#2208]
Hi 

My security team has reported below issue under severe category, please help me understand implication for same 

**Issue:** Broadcast Receiver:(com.adboe.android.gms.gcm.GcmReceiver) is not protected {android :exported= true}
**Mitigation Step** : Unprotected broadcast receiver , check the permission defined on the application and ensure it is set to signature , this ensure only applications signed with the same certificate can obtain the permission
**Result** : Changing the property results in the notification not being received. So we cannot change the property if the notification is needed.

**Comment by abhibeta** [comment]
Bug reported in 
File: AndroidManifest.xml
Line no.: 151

**Comment by macdonst** [comment]
@abhibeta this appears to be referring to the 1.x stream of the plugin. Please upgrade to 2.x stream as it no longer uses the GcmReceiver.

As well this is the recommended way of setting up your app to receive GCM push messages. Read these Google docs for more info:

https://developers.google.com/cloud-messaging/android/client

**Comment by abhibeta** [comment]
Thanks @macdonst I will update plugin to version suggested and validate.
