### ISSUE TITLE
Use of an  insecure Random Number Generator

### ISSUE THREAD

**Issue by abhibeta** [phonegap/phonegap-plugin-push#2209]
Hi 

My security team has reported below issue under severe category , please help me understand implications and solutions 

**Issue** : The App uses an insecure Random Number Generator
**Mitigation Step** : Implement a cryptographic pseudo random number generators which can generate an output that is more difficult to predict
**Result**: These are default codes of the cordova and plugin . Same cannot be changed.

**Comment by abhibeta** [comment]
Bug Reported in 

File : com/adobe/phonegap/push/GCMIntentService
Line no.: 3569

**Comment by macdonst** [comment]
@abhibeta that doesn't actually point to the offending source code but at least it's a hint as to what class is being used.

**Comment by macdonst** [comment]
@abhibeta fixed the issue and it will be in the 2.1.4 release.

**Comment by abhibeta** [comment]
Thanks macdonst.
When can we expect this release.

**Comment by macdonst** [comment]
@abhibeta fixed in 2.2.0 which is out now

**Comment by abhibeta** [comment]
Thanks Simon
