### ISSUE TITLE
Implicit Intent: local intent used to create instance of PendingIntent

### ISSUE THREAD

**Issue by abhibeta** [phonegap/phonegap-plugin-push#2210]
Hi 

Below issue is reported under severe category by my security team , please help me understand implication for same 

**Issue** : Implicit Intent: local intent used to create instance of PendingIntent
**Mitigation Step :** 

To avoid intent interception and intent spoofing which can lead to leak of sensitive information and forging of an intent ensure the below recommendations are adhered
Avoid use of implicit intents for communication between the components of a single app
Explicitly set the value of android: exported for each component in your manifest
If you don’t want to accept intents from untrusted applications always validate your input
Make use of permissions when appropriate

**Result** : These are default codes of the cordova and plugin . Same cannot be changed.

**Comment by abhibeta** [comment]
Bug Reported in 
File: com/google/android/gms/common/zzc.java
Line no.: 138

**Comment by macdonst** [comment]
@abhibeta I can't do anything about this issue as the code you are referencing is part of a Google library.
