### ISSUE TITLE
Module is not defined, pushnotification.init is not a function

### ISSUE THREAD

**Issue by cmfazlyns** [phonegap/phonegap-plugin-push#2212]
# PushNotification Unable to register with GCM

It throws me a error message like this:
![screenshot 3](https://user-images.githubusercontent.com/36625592/36406961-8ee29964-15af-11e8-921f-34174f877588.png)

My Code: 
```
`    document.addEventListener( 'deviceready', onDeviceReady.bind( this ), false );

    function onDeviceReady() {
        document.addEventListener( 'pause', onPause.bind( this ), false );
        document.addEventListener('resume', onResume.bind(this), false);

        var pushOptions = {
            android: {
                senderId: 'XXXXXXX'
            },
            ios: {
                alert: true,
                badge: true,
                sound: true
            },
            windows: {
            }
        };
        pushHandler = PushNotification.init(pushOptions);

        pushHandler.on('registration', function (data) {
            registrationId = data.registrationId;
            // For cross-platform, you can use the device plugin to determine the device
            // Best is to use device.platform
            var name = 'gcm'; // For android - default
            if (device.platform.toLowerCase() === 'ios')
                name = 'apns';
            if (device.platform.toLowerCase().substring(0, 3) === 'win')
                name = 'wns';
            client.push.register(name, registrationId);
            alert(registrationId);
        });

        pushHandler.on('notification', function (data) {
            // data is an object and is whatever is sent by the PNS - check the format
            // for your particular PNS
        });

        pushHandler.on('error', function (error) {
            // Handle errors
        });
    };`
```

Note: I double checked the sender id , further i linked push.js below cordova.js and tried and later removed it tried but same error keeps coming.
![screenshot 4](https://user-images.githubusercontent.com/36625592/36407020-f6f5d386-15af-11e8-83ca-f4ba9abd4908.png)

Error Message After unlinking push.js
![screenshot 5](https://user-images.githubusercontent.com/36625592/36407042-18becfc2-15b0-11e8-8630-10845b7abf24.png)

My config.xml
![screenshot 6](https://user-images.githubusercontent.com/36625592/36407080-8b72d8e2-15b0-11e8-8f4f-08b3404e5f58.png)

**Comment by macdonst** [comment]
@cmfazlyns you don't include the push.js directly in your app. You let cordova take care of picking up the plugin from config.xml and loading the push.js code dynamically.

**Comment by cmfazlyns** [comment]
I tried without including push.js but sames error keeps coming

**Comment by cmfazlyns** [comment]
Furhet, I found that cordova does not load push.js dynamically.
![screenshot 7](https://user-images.githubusercontent.com/36625592/36408359-c29abc8c-15b9-11e8-820e-5b6e38690619.png)
![screenshot 8](https://user-images.githubusercontent.com/36625592/36408360-c2cbe74e-15b9-11e8-8d66-e60589a1298b.png)
![screenshot 9](https://user-images.githubusercontent.com/36625592/36408362-c2fedcb2-15b9-11e8-9d54-8316739c5512.png)

**Comment by cmfazlyns** [comment]
But plugin available in 'plugin' folder

![screenshot 10](https://user-images.githubusercontent.com/36625592/36408436-25e5e3d4-15ba-11e8-996b-2bd32b305971.png)

**Comment by macdonst** [comment]
@cmfazlyns then the plugin version you are using probably doesn't support the version of cordova you are using but I can't tell for sure because you didn't fill out the issue template.
