### ISSUE TITLE
Cannot read property 'on' of undefined - android - push 2.0.0

### ISSUE THREAD

**Issue by JeroenNieuwenhuis** [phonegap/phonegap-plugin-push#2213]
I installed version 2.0.0 with the cli, placed google-services.json in my project root. I have this in my config.xml:
```
platform name="android">
   <allow-intent href="market:*" />
   <resource-file src="google-services.json" target="google-services.json" />
</platform>
<platform name="ios">
    <allow-intent href="itms:*" />
    <allow-intent href="itms-apps:*" />
    <resource-file src="GoogleService-Info.plist" />
</platform>
...
<plugin name="phonegap-plugin-push" spec="~2.0.0" />
```

In onDeviceReady:
```
const push = PushNotification.init({
	android: {},
	browser: {
		pushServiceURL: 'http://push.api.phonegap.com/v1/push'
	},
	ios: {
		alert: "true",
		badge: "true",
		sound: "true"
	},
	windows: {}
});

 app.push.on('registration', function(data) {
	 console.log("registration event: " + data.registrationId);
	 document.getElementById("regId").innerHTML = data.registrationId;
	 var oldRegId = localStorage.getItem('registrationId');
	 if (oldRegId !== data.registrationId) {
		 // Save new registration ID
		 localStorage.setItem('registrationId', data.registrationId);
		 // Post registrationId to your app server as the value has changed
	 }
});
```

I'm getting an error on ` app.push.on('registration', function(data) {` because push is undefined, but I don't know why.

I'm using an Oneplus X with Android 6.0.1.
Phonegap 7.11
Installed platforms:
  android 6.3.0
  browser 5.0.3

phonegap plugin version
cordova-plugin-battery-status 1.2.5 "Battery"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-media-capture 1.4.3 "Capture"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-vibration 2.1.6 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
phonegap-plugin-push 2.0.0 "PushPlugin"

**Comment by jcesarmobile** [comment]
Looking at your code, you are not adding push to app, so why do you use app.push.on?
Try with just push.on

**Comment by JeroenNieuwenhuis** [comment]
I am an idiot.
