### ISSUE TITLE
Can we override DND (Do not disturb) mode for our app notification sound setting

### ISSUE THREAD

**Issue by razam217** [phonegap/phonegap-plugin-push#2214]
### Expected Behaviour
When "Do not disturb" mode is ON, I want to get my app notification with sound, so that the user should be always alerted. Is there a way to do that, or is it possible to add a functionality like overriding DND mode?
 
### Actual Behaviour
When DO NOT DISTURB mode is ON, sound of my app notification gets muted.

**Comment by jcesarmobile** [comment]
This is something the user can do, but not the developer, if not every developer would use it and ruin the DND mode
