### ISSUE TITLE
 Error installing the plugin

### ISSUE THREAD

**Issue by roger93** [phonegap/phonegap-plugin-push#2215]
Hello everyone, it turns out that they are new, installing this plugin, I have read the documentation and I have set to work.

It turns out that I installed the plugin (cordova plugin add phonegap-plugin-push)
And I've put the google file in the root of my project and I've set up the following line
`<resource-file src="google-services.json" target="google-services.json" /> `
 
Am currently using Cordova version 7.0.1 and android version 6.2.1
But what I do not have anything clear is what to put in the js file so that I can receive the notifications I have been looking through the internet and I found the following code this code because it does not work that I do wrong?

Because I do not get the notifications if I'm sending them from the firebase panel

`/*-----------------Devices App And Push Modification----------*/ 
const push = PushNotification.init({ 
    android: { 
        alert: "true", 
        badge: "true", 
        sound: "true" 
    }, 
    ios: { 
        alert: "true", 
        badge: "true", 
        sound: "true" 
    }, 
    windows: {} 
}); 
push.on('registration', (data) => { 
     alert(data.registrationId +' test'); 
}); 
push.on('notification', (data) => { 
     alert(data.title + data.message+'hello word'); 
}); 
push.on('error', (e) => { 

    alert(e.message +'error hello word'); 

    // e.message 

}); `

![captura de pantalla 2018-02-21 a las 10 13 04](https://user-images.githubusercontent.com/7825926/36471785-09649d7c-16f0-11e8-8a97-51f68322672e.png)
![captura de pantalla 2018-02-21 a las 10 12 41](https://user-images.githubusercontent.com/7825926/36471786-0982f056-16f0-11e8-8c6d-b99b74af7c62.png)
![captura de pantalla 2018-02-21 a las 10 12 27](https://user-images.githubusercontent.com/7825926/36471787-09a1aff0-16f0-11e8-9926-7aa48e01fc98.png)
![captura de pantalla 2018-02-21 a las 10 12 09](https://user-images.githubusercontent.com/7825926/36471789-09be8102-16f0-11e8-89bb-bef90a029e5b.png)
![captura de pantalla 2018-02-21 a las 10 11 48](https://user-images.githubusercontent.com/7825926/36471790-09d9f180-16f0-11e8-8931-8982252300dc.png)

**Comment by jcesarmobile** [comment]
Latest version of the plugin requires cordova-android 6.3.0 or newer and CLI 7.1.0 or newer.
If you can't update, then you'll have to downgrade the plugin version to 2.0.0.

**Comment by roger93** [comment]
Hello again how can I update to these versions

And the code is fine ??
