### ISSUE TITLE
push.on('registration', not fired in iOS

### ISSUE THREAD

**Issue by cordova2018** [phonegap/phonegap-plugin-push#2218]
cordova 7.1.0               
cordova platform 6.3.0 android                   
phonegap-plugin-push 2.1.3

index.js:

onDeviceReady: function() { 	
		app.push = PushNotification.init({
			android: {},
			ios: {
				"sound": true,
				"vibration": true,
				"badge": true
			},
			windows: {}
		});
	app.push.on('registration', function(data) {
	 alert(data.registrationId);    
	});
	app.push.on('error', function(e) {    
		alert(e.message);
	});
	app.push.on('notification', function(data) {
		alert(data.message);
	});
      
	  alert("last msg");
    }

log:

Push Plugin register called
PushPlugin.register: setting badge to false
PushPlugin.register: clear badge is set to 0
PushPlugin.register: better button setup
FCM Sender ID (null)
Using APNS Notification
active
PushPlugin skip clear badge

**Comment by cordova2018** [comment]
PushPlugin skip clear badge
Resetting plugins due to page load.
Finished load of: file:///var/containers/Bundle/Application/4BB51A79-506Capp/www/index.html
void SendDelegateMessage(NSInvocation *): delegate (webView:runJavaScriptAlertPanelWithMessage:initiatedByFrame:) failed to return after waiting 10 seconds. main run loop mode: kCFRunLoopDefaultMode
Push Plugin register called
PushPlugin.register: setting badge to false
PushPlugin.register: clear badge is set to 0
PushPlugin.register: better button setup
FCM Sender ID (null)
Using APNS Notification
active
PushPlugin skip clear badge

**Comment by cordova2018** [comment]
Push Plugin register called
PushPlugin.register: setting badge to false
PushPlugin.register: clear badge is set to 0
PushPlugin.register: better button setup
FCM Sender ID (null)
Using APNS Notification

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
