### ISSUE TITLE
Does Not Update App Permission

### ISSUE THREAD

**Issue by ehorodyski** [phonegap/phonegap-plugin-push#2219]
### Expected Behaviour
I expect a way to disable/enable notifications for the app, which persists to the system's app settings.

### Actual Behaviour
The plugin asks permission once. If a user goes to their iOS Settings and disables notifications for the app, there is no way for the application to update the setting.

#### Steps to Reproduce 
1. Create an app that asks for Notification Permission (uses the plugin).
2. The user selects "Allow".
3. The user goes into iOS Settings, finds the app settings, and disables Notifications.
4. There is no way to re-ask permission for Notifications from within the app.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 11.2.x

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by jcesarmobile** [comment]
This can't be done, iOS will only ask once, there is no way of asking again.

You can use `hasPermission` method to check the permissions status at any time, and then probably use another plugin to take the user to the app settings page where they can enable the notifications if he wants.
