### ISSUE TITLE
Can I get Notification for IOS by don't use parameters "notification" for send Body or Title ?

### ISSUE THREAD

**Issue by Kittipotgithub** [phonegap/phonegap-plugin-push#2220]
Can I use other parameters ? Because If I use "notification parameters" Web and Android background notification are not working
I use FCM for push notification

**Comment by macdonst** [comment]
@Kittipotgithub Please read the docs:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

**Comment by tominou** [comment]
@macdonst So there is no way to send a payload that would work on both iOS and Android, am i right?
