### ISSUE TITLE
[Android 7.0] Hundreds of crash reports on Play console

### ISSUE THREAD

**Issue by tominou** [phonegap/phonegap-plugin-push#2223]
Android 7+

-  Samsung Galaxy S7 (herolte), 4096MB RAM, Android 7.0
-  Samsung Galaxy A5(2016) (a5xelte), 2048MB RAM, Android 7.0
-  Huawei P10 lite (HWWAS-H), 4096MB RAM, Android 7.0
-  Samsung Galaxy J7(2016) (j7xelte), 2048MB RAM, Android 7.0
-  Samsung Galaxy J7(2016) (j7xelte), 2048MB RAM, Android 7.0
- Huawei Mate 8 (HWNXT), 4096MB RAM, Android 7.0
- Samsung Galaxy S7 Edge (hero2lte), 4096MB RAM, Android 7.0
- Huawei P10 (HWVTR), 4096MB RAM, Android 7.0
- OnePlus OnePlus3 (OnePlus3), 6144MB RAM, Android 8.0
-  **and many more**

cordova --version 8.0.0
cordova platform version android 7.1.0
cordova plugin version | grep phonegap-plugin-push 2.2.2

I can not reproduce the crashes personally, but i have hundreds of crash reports on my Play Console since I pushed the update. Reports are identical.

Here it is:

```
java.lang.IllegalStateException: 
  at com.google.firebase.FirebaseApp.getInstance (Unknown Source)
  at com.google.firebase.iid.FirebaseInstanceId.getInstance (Unknown Source)
  at com.adobe.phonegap.push.PushPlugin$1.run (PushPlugin.java:182)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
  at java.lang.Thread.run (Thread.java:762)
```

It seems FirebaseInstanceId is called before being initiated, is that right?

Thank you in advance

**Comment by macdonst** [comment]
@tominou sorry I can't reproduce it either and I don't have any of those devices.

**Comment by eikooc** [comment]
I'll just add devices that are affected from my ANR report as well:

- OnePlus OnePlus5 (OnePlus5), 6144MB RAM, Android 8.0
- OnePlus OnePlus3 (OnePlus3), 6144MB RAM, Android 8.0
- Asus ZenPad 10 (Z300M) (P00C_2), 1024MB RAM, Android 7.0

So it seems it is not exclusively on Android 7.0. It also happens on Android 8.0.

**Comment by lincolnthree** [comment]
I am also seeing these crashes consistently.
