### ISSUE TITLE
Not an issue just doubt will it possible to received notification in background  

### ISSUE THREAD

**Issue by SunilPatel2** [phonegap/phonegap-plugin-push#2224]
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

{
    "data" : {
        "title": "Test Notification",
        "body": "This offer expires at 11:30 or whatever",
        "notId": 10,
        "surveyID": "ewtawgreg-gragrag-rgarhthgbad"
    }
}

here data I'm sending from server every thing work fine.

Here Dock Says

When your app is in the foreground any on('notification') handlers you have registered will be called. If your app is in the background, then the notification will show up in the system tray. Clicking on the notification in the system tray will start the app, and your on('notification') handler will be called with the following data:

{
    "message": "This offer expires at 11:30 or whatever",
    "title": "Test Notification",
    "additionalData": {
        "surveyID": "ewtawgreg-gragrag-rgarhthgbad"
    }
}

**Will it possible to received notification data without tapping on notification when app is in background on Android device** 

**if we don't click on notification data will not pass to the App**

**Comment by macdonst** [comment]
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications

**Comment by SunilPatel2** [comment]
thnx 
const message = {
    "to": deviceID,
    "data": {
        "info": 'super secret info',
        "content-available": '1'
    }
};
I'm sending this type of push from server every thing work fine as expected 
only one issued I'm facing 
when app is close if I received any kind of push 
after app start push.on('notification',() => {}) called two times don't know why.
