### ISSUE TITLE
Error running Android: cordova build android fails, compileSdkVersion not specified

### ISSUE THREAD

**Issue by Nerrickk** [phonegap/phonegap-plugin-push#2225]
Can't build Android using "cordova build android", removing phonegap-plugin-push resolves this issue. iOS builds fine. Have tried removing other plugins to verify any compatibility issues and found none. I have tried adding `<preference name="android-compileSdkVersion" value="26" />` to config.xml, and that did not work either.

Versions:
cordova v8.0.0
android v7.0.0
phonegap-plugin-push v2.1.3

Stack Trace:
https://pastebin.com/8j5DpbNS

**Comment by fredgalvao** [comment]
There is no such preference as `android-compileSdkVersion`, but instead `android-targetSdkVersion`, which is just as fine considering it's good practice to have both on the same value.
For reference: https://cordova.apache.org/docs/en/latest/config_ref/index.html.

**Comment by Nerrickk** [comment]
I have both minSdkVersion and targetSdkVersion specified. The build failed before I added android-compileSdkVersion, I added it in an attempt to fix the issue.

**Comment by mahmoudhsein** [comment]
@Nerrickk  I have the same issue..
Did you find a solution?

**Comment by Nerrickk** [comment]
@mahmoudhsein Unfortunately no, still trying to find a work around.

**Comment by safrazik** [comment]
I'm having the same issue. @Nerrickk or @mahmoudhsein any news?

**Comment by macdonst** [comment]
Looking at the pastebin of this build log the build tools are not even finding gradle so it is an issue with the way your tools are setup.
