### ISSUE TITLE
Xiaomi Devices and Badge Count

### ISSUE THREAD

**Issue by rhapsodyv** [phonegap/phonegap-plugin-push#2228]
Hi,

ShortcutBadger says that to support Xioami Miui > 6, the code must follow their example on this page:
https://github.com/leolin310148/ShortcutBadger/wiki/Xiaomi-Device-Support

Original code here:
https://github.com/phonegap/phonegap-plugin-push/blob/c7d8fce6a6dfbd3d59abe0eef671cee67f5c7ffa/src/android/com/adobe/phonegap/push/PushPlugin.java#L445

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by rhapsodyv** [comment]
Sorry, really.  You are right, I was in a rush and missed the guidelines. I will submit again, but in a right way!
Thanks 👍
