### ISSUE TITLE
ios notification action buttons?

### ISSUE THREAD

**Issue by liuzhen2008** [phonegap/phonegap-plugin-push#223]
I suppose it is something we don't have support at the moment for ios?

Someone needs to submit PR for that?

**Comment by erictonussi** [comment]
+1 on this

**Comment by Hirbod** [comment]
+1

**Comment by jterps08** [comment]
+1

**Comment by macdonst** [comment]
Yup, I want to do this. Will have to wait for a 1.5.0 release but if anyone wants to take a stab at it then PR's are welcome.

**Comment by macdonst** [comment]
Pushed some working code into the v1.5.x branch.

**Comment by slash-84** [comment]
+1

**Comment by macdonst** [comment]
![img_0072](https://cloud.githubusercontent.com/assets/353180/11899041/6e422aba-a56a-11e5-9c34-e74b1d23c3c3.PNG)

**Comment by macdonst** [comment]
Merged into master.
