### ISSUE TITLE
PushNotification.hasPermission() does not work in the browser

### ISSUE THREAD

**Issue by ntamas** [phonegap/phonegap-plugin-push#2230]
### Expected Behaviour

`PushNotification.hasPermission()` should return an object of the form `{ isEnabled: true }` or `{ isEnabled: false }` to make it API-compatible with the other platforms (Android, iOS etc).

### Actual Behaviour

`PushNotification.hasPermission()` returns `true` unconditionally (not even `{ isEnabled: true }`).

#### Steps to Reproduce 

Run the following code in the browser:

```js
PushNotification.hasPermission(function (result) {
    console.log(result);
})
```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Any desktop browser (tested on Firefox 58 and Chrome 64)

#### Cordova CLI version and cordova platform version

Cordova 8.0.0
Cordova browser platform 5.0.3

#### Plugin version

2.1.3

#### Sample Code that illustrates the problem

```js
PushNotification.hasPermission(function (result) {
    console.log(result);
})
```

#### Logs taken while reproducing problem

```
true
```

#### Recommendation

I believe that a minimal implementation of the `hasPermission()` function on the browser platform should at least check whether the notification permission is granted:

```
hasPermission: function(successCallback, errorCallback) {
        const granted = Notification && Notification.permission === 'granted'
        successCallback({ isEnabled: granted });
},
```

**Comment by macdonst** [comment]
@ntamas yeah, that is a real good point and you seem to have a handle on how to implement the fix. PR's are always welcome.

**Comment by ntamas** [comment]
Great, I will prepare a PR soon then.

**Comment by macdonst** [comment]
@ntamas this will be out in the next release.

**Comment by ntamas** [comment]
Awesome, thanks a lot!
