### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by caereservices** [phonegap/phonegap-plugin-push#2237]
Command:

cordova plugin add phonegap-plugin-push

Result:

Installing "phonegap-plugin-push" for ios
(node:26454) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): code: engine.platform or engine.scriptSrc is not defined in custom engine "cordova-browser" from plugin "phonegap-plugin-push" for ios warn

The plugin isn't installed

    cordova --version                                   8.0.0
    cordova platform version ios                 4.5.4

I got the same error when use git URL

**Comment by kilatib** [comment]
Same issue 

> `cordova platform add android@7.1.0           
Using cordova-fetch for cordova-android@7.1.0
(node:67214) UnhandledPromiseRejectionWarning: CordovaError: Platform android already added.
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/platform/addHelper.js:149:35
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at process._tickCallback (internal/process/next_tick.js:150:11)
(node:67214) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:67214) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

`
cordova 8.0.0.
------------------------------------------------------------
Gradle 4.5.1
------------------------------------------------------------

Build time:   2018-02-05 13:22:49 UTC
Revision:     37007e1c012001ff09973e0bd095139239ecd3b3

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_152 (Oracle Corporation 25.152-b16)
OS:           Mac OS X 10.13.3 x86_64`

`
> cordova plugin rm phonegap-plugin-push 
>  cordova plugin add phonegap-plugin-push      
Installing "phonegap-plugin-push" for android
(node:67803) UnhandledPromiseRejectionWarning: CordovaError: warn
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:238:23
    at Array.forEach (<anonymous>)
    at getEngines (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:216:13)
    at Function.runInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:293:22)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:79:35
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:810:14
    at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:108:17)
(node:67803) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:67803) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by rdesimone** [comment]
Yes, version `2.2.0` cannot be installed. `2.1.3` works.

```
cordova 8.0.0
android 7.1.0
ios 4.5.4
````
Installations for both platforms (`ios` and `android`) fail independently.

**Comment by macdonst** [comment]
Mea culpa everyone. Apparently my workspace had a development version of cordova linked that supports limiting the version of cordova-browser. I will be releasing a 2.2.1 momentarily.

**Comment by macdonst** [comment]
Sorry everyone, 2.2.1 has been pushed to npm. Let me know if there are any more problems.

**Comment by Bengejd** [comment]
Still having this issue with 2.2.1

**Comment by Bengejd** [comment]
> ionic cordova plugin add phonegap-plugin-push
> cordova plugin add phonegap-plugin-push --save
Installing "phonegap-plugin-push" for ios

(node:46384) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: warn
(node:46384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rdesimone** [comment]
it works - @Bengejd try `cordova plugin add phonegap-plugin-push@latest`

**Comment by Bengejd** [comment]
> ionic cordova plugin add phonegap-plugin-push@latest
> cordova plugin add phonegap-plugin-push@latest --save
Installing "phonegap-plugin-push" for ios

(node:46433) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: warn
(node:46433) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Bengejd** [comment]
Same thing happens if I try to remove the plugin? 

> ionic cordova plugin rm phonegap-plugin-push
> cordova plugin remove phonegap-plugin-push --save
Uninstalling phonegap-plugin-push from ios

Error during processing of action! Attempting to revert...

(node:46467) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Uh oh!
Cannot find module '/Users/bengejd/WebstormProjects/SocialPnt/platforms/ios/pods.json'
(node:46467) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Bengejd** [comment]
I think I fixed the error. I deleted the phonegap-plugin-push folder from the `plugins` folder, and then ran `ionic cordova platform rm ios` and then `ionic cordova platform add ios` and it seemes to have fixed the issue.

**Comment by kilatib** [comment]
yes, problem we resolved for me. Thank you

**Comment by bhandaribhumin** [comment]
@bengejd we remove plugin or not from package json?
