### ISSUE TITLE
cordova app crashes when trying to register push Notification

### ISSUE THREAD

**Issue by bar-c** [phonegap/phonegap-plugin-push#2239]
### Expected Behaviour
Register the device when the app starts obtaining a registrationId

### Actual Behaviour
If we change the device's date forwards eg.: Mar 01nd 2018, the registration  fails, executing the push.on('error') message.
If we set the device's date backwards from today's date eg.: Feb 28th 2018, it works.  Until Feb 28th 2018 it worked. Is there any relation between changing dates and the validity of the registrationId?

### Reproduce Scenario (including but not limited to)
Initialize the plugin following the README example code:

this.registerPushNotification = function(cb) {

        function onPushPlugin() {
            try {
                if (window.plugins) {
            var push = PushNotification.init({
                "android": {
                    "senderID": ANDROID_SENDER_ID,
                    "clearNotifications": "true"
                },
                "ios": {
                    "senderID": IOS_SENDER_ID,
                    "alert": true,
                    "sound": true,
                    "badge": true,
                    "gcmSandbox": true
                },
                "windows": {}
            });
            push.on('registration', function(data) {
                util.setAPN(data.registrationId);
                console.log("[DEBUG] Device Registration event (idAPN): " + data.registrationId);
                console.log('---> idAPN: ' + util.getAPN());
                cb();
            });
            push.on('notification', function(data) {
                var notificationEvent = new CustomEvent("onNotification", { "detail": data });
                notificationEvent.detail = data;
                console.log("[DEBUG] Device Notification event: ", data);
                document.dispatchEvent(notificationEvent);
                push.finish(function() {
                    console.log("[DEBUG] Push-Success");
                }, function() {
                    console.error("[ERROR] Push-Finish");
                });
            });
            push.on('error', function(e) {
                console.error("[ERROR] Push-error: ", e);
                cb();
            });
                } else {
                    errorHandler("[DEBUG] No plugin");
        }
            } catch (err) {
                console.log('[DEBUG] Ha ocurrido el siguiente error en la pagina' + err);
                errorHandler(err);
            }
        }

            onPushPlugin();

        function errorHandler(error) {
            console.log('Error: ' , error);
            cb();
        }
    };

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.0/6.0.1/4.4.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Tested on androids : Samsung S7/S8 and Motorola (moto g)

#### Cordova CLI version and cordova platform version

   cordova --version                                    8.0.0
cordova platform version android            6.4.0

#### Plugin version

cordova plugin version | grep phonegap-plugin-push   1.10.63

#### Sample Code that illustrates the problem
code above

**Comment by macdonst** [comment]
@bar-c I'm confused. You are setting the date of your phone to a time in the future and you are not able to get a registration ID? That seems like it would be an issue with the remote FCM service rejecting your registration because of the time/date stamp.

**Comment by bar-c** [comment]
@macdonst 
No, that is not the case. 
In several devices, after several days of having entered the application for the last time and having obtained the registrationID, when trying a new registration to Firebase it failed. This case was given on a device on March 1, 2018. That is, until February 28, 2018, the Firebase registry didn't fail but on March 1, 2018 it did (the date of the device wasn't change at all by the owner, it was the current day). 

A test that the user made was to move the date of the device to February 28, 2018 and re-enter the application (register again to Firebase) and in this test the registration was successful.

That brings me back to the question, is there any relationship between the device date, the registrationID and the device registration with Firebase?

**Comment by macdonst** [comment]
@bar-c I'm still confused. So the app doesn't crash? The title of the issue is mis-leading then.

What message are you getting in the error callback when the issue occurs? What is in logcat when you reproduce the issue?

I'm not aware of any issues with registering with Firebase on March 1st but perhaps there was a problem with the service.

**Comment by bar-c** [comment]
@macdonst 
Yes, the app crashes but that crash doesn't happen when the device date is setting for February 28, 2018 (when the crash was at March 1, 2018).

When the error occurs the log that we are getting is:
02-27 15:59:13.438 22963-23066/? V/PushPlugin: execute: action=init
02-27 15:59:13.445 22963-23067/? V/PushPlugin: execute: data=[{"android":{"senderID":"672354874469","clearNotifications":"true"},"ios":{"senderID":"224298373384","alert":true,"sound":true,"badge":true,"gcmSandbox":true},"windows":{}}]
02-27 15:59:13.445 22963-23067/? V/PushPlugin: execute: jo={"senderID":"672354874469","clearNotifications":"true"}
02-27 15:59:13.445 22963-23067/? V/PushPlugin: execute: senderID=672354874469
02-27 15:59:13.556 3495-16554/? W/Conscrypt: Could not set socket write timeout:
02-27 15:59:13.568 3495-16554/? W/Conscrypt:    java.lang.reflect.Method.invoke(Native Method)
02-27 15:59:13.568 3495-16554/? W/Conscrypt:    com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@11975446:13)
02-27 15:59:13.631 3495-16554/? W/Conscrypt: Could not set socket write timeout:
02-27 15:59:13.632 3495-16554/? W/Conscrypt:    java.lang.reflect.Method.invoke(Native Method)
02-27 15:59:13.632 3495-16554/? W/Conscrypt:    com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@11975446:13)
02-27 15:59:14.025 22875-23039/? I/AppStateLogger: Reporting sticky state as: true
02-27 15:59:14.061 2268-3084/? I/ActivityManager: Start proc 23125:com.facebook.katana:notification/u0a229 for service com.facebook.katana/com.facebook.rti.push.service.FbnsService
02-27 15:59:14.066 22875-22888/? D/AppStateLogger: Successfully dumped app state to log file
02-27 15:59:14.139 23125-23125/? V/CatchMeIfYouCan: initializing CMIYC, flags = 0x00000000
02-27 15:59:14.141 23125-23125/? D/ExceptionHandlerManager: initializing exception handler manager, prioritized=true
02-27 15:59:14.147 23125-23139/? D/AppStateLogger: Attempting to open app state logging file
02-27 15:59:14.148 23125-23125/? I/AppStateLoggerExceptionHandler: Installed uncaught exception handler for app state logging
02-27 15:59:14.152 22963-23067/? E/PushPlugin: execute: **Got JSON Exception RST**
02-27 15:59:14.156 23125-23139/? D/AppStateLogger: Successfully opened app state logging file: /data/user/0/com.facebook.katana/app_state_logs/com.facebook.katana_notification_41835c50-def7-d294-8182-9e5be1058d7e.txt
02-27 15:59:14.158 22963-23067/? D/PushPlugin: no icon option
02-27 15:59:14.158 22963-23067/? D/PushPlugin: no iconColor option
02-27 15:59:14.166 23125-23125/? D/ACRA: ACRA init; reportURL: https://b-www.facebook.com/mobile/android_crash_logs/
02-27 15:59:14.168 23125-23125/? D/ACRA: ACRA is enabled for process com.facebook.katana:notification, initializing...
02-27 15:59:14.174 22963-22963/? D/SystemWebChromeClient: file:///android_asset/www/common/service/pushNotification/pushNotification.js: Line 110 : **[ERROR] Push-error: RST**
02-27 15:59:14.174 22963-22963/? I/chromium: [INFO:CONSOLE(110)] "**[ERROR] Push-error: RST**", source: file:///android_asset/www/common/service/pushNotification/pushNotification.js (110)

sorry for the misunderstanding with the title of the issue

**Comment by macdonst** [comment]
@bar-c okay, so what you are saying is if you set the devices date/time to a point in the future and try to register with the remote push service it crashes?
