### ISSUE TITLE
'registration' event not firing on windows phone

### ISSUE THREAD

**Issue by zahirdhada** [phonegap/phonegap-plugin-push#224]
I am developing a cross platform mobile application using phonegap 3.6.3 and jquery mobile. I am using phonegap-plugin-push to receive push notifications for my app. The plugin works fine with android and ios, but doesn't seem to work with windows phone. After calling 'init' with default options given in the example, I am not receiving 'registration' or 'error' event. Any solutions?

**Comment by rakatyal** [comment]
Hi @zahirdhada, 
Can you please tell me what you are using to build the application? Also which windows phone version is it?

**Comment by bau720123** [comment]
duplicate with my before post
https://github.com/phonegap/phonegap-plugin-push/issues/56

**Comment by zahirdhada** [comment]
@bau720123 thank you. I am also using online PhoneGap Build. Is there any way to make it work?

**Comment by bau720123** [comment]
hi @zahirdhada 
for now this plugin have no wp8 version indeed
if someone can made a PR
or...
use the old pushplugin
https://www.npmjs.com/package/cordova-plugin-pushplugin
https://www.npmjs.com/package/megaplan-plugin-push

but the old is stop to maintaince
