### ISSUE TITLE
duplicate entry: android/support/v13/view/DragAndDropPermissionsCompat.class

### ISSUE THREAD

**Issue by nprail** [phonegap/phonegap-plugin-push#2243]
`phonegap-plugin-push` seems to be conflicting with two other plugins. I have been fighting this odd issue for days now and I have no idea what the problem is. 

### Expected Behaviour
The build should pass. 

### Actual Behaviour
The build fails with this error message:
```
BUILD FAILED

Total time: 45.755 secs
Execution failed for task ':transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v13/view/DragAndDropPermissionsCompat.class
```
#### Steps to Reproduce 
Create a new Cordova project:
```bash
cordova create test
cd test
```

Install `cordova-android@6.3.0`
```bash
cordova platform add android@6.3.0
```

Install the following plugins:
```bash
cordova plugin add phonegap-plugin-push@2.1.3 
cordova plugin add cordova-plugin-crosswalk-webview@2.4.0
cordova plugin add cordova-plugin-file-opener2@2.0.19
```
Both of those other plugins alone will cause the issue but they work just fine together without the push plugin.

Add your `google-services.json` file so you don't get errors about that. 

Attempt to build (it shouldn't work):
```bash
cordova build android
```

Now remove `phonegap-plugin-push` and build again (it should work):
```bash
cordova plugin rm phonegap-plugin-push
cordova build android
```

#### Cordova CLI version and cordova platform version

    cordova --version                                    8.0.0
    cordova platform version android                     6.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.1.3

#### Android SDK packages installed:
  |Path                              | Version|
  |-------                           | -------|
  |build-tools;27.0.3                | 27.0.3|
  |emulator                          | 27.1.10|
  |extras;android;m2repository       | 47.0.0|
  |extras;google;g...e_play_services | 46|
  |extras;google;m2repository        | 58|
  |patcher;v4                        | 1|
  |platform-tools                    | 27.0.1|
  |platforms;android-26              | 2|
  |platforms;android-27              | 1|
  |tools                             | 26.0.1|

**Comment by nprail** [comment]
The solution in [this comment](https://github.com/phonegap/phonegap-plugin-push/issues/2229#issuecomment-369510785) on #2229 seems to fix the problem!

I'm going to leave the issue open though because the solution is only a workaround.

**Comment by alaa-alshamy** [comment]
update this plugin to 2.2.1 solved this issue for me

**Comment by nprail** [comment]
I believe that solved the issue for me too but unfortunately, that is not a viable option. 2.2.1 requires `cordova-android` 7.1.0 which I cannot upgrade to because of lack of compatibility with other plugins.

**Comment by cbjerg** [comment]
Upgrading til 2.2.1 fixed my problems as well

**Comment by alaa-alshamy** [comment]
@nprail oh really ?!! where did u read that ? i checked all changes and can't find something like that 

because if that true i will have a big problem too

**Comment by rravindranaik111** [comment]
@alaa-alshamy : Did you try it ? If yes which parameter you changed ?
I mean in config.xml file

<plugin name="phonegap-plugin-push" spec="^2.1.3">
        <variable name="FCM_VERSION" value="11.6.2" />
        <variable name="SENDER_ID" value="xxxxxxxxxxxxxxxx" />
    </plugin>

Did you changed spec version of this plugin ?

**Comment by alaa-alshamy** [comment]
yep sure i tried that, u can make so in several ways u can remove the plugin and reinstall it or u can change the spec in the config.xml and run 'cordova prepare' or whatever u have to reinstall the plugins 

@nprail and yea if what did u say true it should throw an error i think but i installed the plugin and made a build successfully

**Comment by macdonst** [comment]
@nprail same root cause as #2229. I was travelling all weekend so I didn't get a chance to reproduce. I'll try to get to the bottom of it today or tomorrow.
