### ISSUE TITLE
Samsung devices not displaying icon colour

### ISSUE THREAD

**Issue by FranceJ** [phonegap/phonegap-plugin-push#2244]
### Expected Behaviour
Push notification on Samsung devices will colour push icon the `iconColor` specified in `pushNotification.init`

### Actual Behaviour
The push icon instead keeps the default white line colouration on the Samsung devices we've tested on (Samsung 8, Samsung 7). Example:

![screenshot_20180302-135046](https://user-images.githubusercontent.com/17236079/36916321-94f5e00c-1e21-11e8-8b53-67bc59ca7c69.jpg)
![screenshot_20180302-135023](https://user-images.githubusercontent.com/17236079/36916323-95b20386-1e21-11e8-8c27-f78d6b5f9b25.jpg)

Example from LG G6 with correct colouring and identical settings:

![screenshot_2018-03-02-13-55-23](https://user-images.githubusercontent.com/17236079/36916365-af5f750c-1e21-11e8-95bd-b1412248b463.png)

### Reproduce Scenario (including but not limited to)
Send the push notification using node GCM and the data payload listed below. The notification sends correctly and is received by the device.

#### Steps to Reproduce 
Set node GCM with payload provided and push plugin with the Android object provided in `pushNotification.init`

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.0 and Samsung 8.1 for the Samsung 8 device

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung 7 and Samsung 8. Other devices display the icon colour correctly, including LG G6, MOTO Z2PLAY.

#### Cordova CLI version and cordova platform version

    cordova --version                              8.0.0
    cordova platform version android    6.4.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.10.5

#### Sample Push Data Payload
```
var androidMessage = new gcm.Message({
        priority: 'high',
        data: {
            message: text,
            title: title,
            style: 'inbox',
            summaryText: 'There are %n% urgent Alerts',
            ledColor: [0,222,114,0],
            image: 'platforms/android/res/drawable-hdpi/ic_stat_alabs.png'
        }
    });

    androidMessage.addData('originID', locationID);
    androidMessage.addData('defaultAction', 'showEmpire');
    androidMessage.addData('actions', [ createActionButton('showProperty', 'View Property') ] );
```
#### Sample Code that illustrates the problem
```
android: {
				senderID: "XXXXXXXXXXX",
				icon: "ic_stat_alabs",
				iconColor: "#EF610E",
				clearNotifications: true
			},
```
#### Logs taken while reproducing problem
from `adb logcat | grep Push`:
[scratch.txt](https://github.com/phonegap/phonegap-plugin-push/files/1776242/scratch.txt)

**Comment by macdonst** [comment]
@FranceJ I don't have that Samsung device so I cannot reproduce. I don't see any errors in the logs so I'm not sure what to tell you right now other than please try using the 2.x version of the plugin to see if the issue persists.

**Comment by FranceJ** [comment]
I managed to fix this without upgrading by editing my hook for the icon image to target every drawable directory listed here: https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar.html.

So, this was 100% the fault of my implementation and is solved now. Thanks again for having a look!

**Comment by Marix1** [comment]
can you tell me what did you do?

i have the same problem that white icons are white on white background

**Comment by AdrianoGeraldeli** [comment]
Segue solução:

Criar o icone com as medidas LDPI (18 x 18) - MDPI ( 24 x 24) - HDPI (36 x 36) - xhdpi (48 x 48)
e colocar no config.xml 

        <resource-file src="res/drawable-hdpi/notification.png" target="res/drawable-hdpi/notification.png" />
        <resource-file src="res/drawable-ldpi/notification.png" target="res/drawable-ldpi/notification.png" />
        <resource-file src="res/drawable-mdpi/notification.png" target="res/drawable-mdpi/notification.png" />
        <resource-file src="res/drawable-xhdpi/notification.png" target="res/drawable-xhdpi/notification.png" />
