### ISSUE TITLE
Android Notifications fail if other channels are already setup

### ISSUE THREAD

**Issue by dpeacock** [phonegap/phonegap-plugin-push#2248]
### Expected Behaviour
The plug-in should allow for other plug-ins already having channels.  It should create a new channel if it doesn't yet have one.

### Actual Behaviour
It only checks to see if any channels exist, not our channel explicitly.  This causes us not to create a channel and the notifications not to display.

### Reproduce Scenario (including but not limited to)
You will need another plug-in that is using notification channels.  If this plug-in initializes first then we will fail to create our channel in createDefaultNotificationChannelIfNeeded as we only check to see if the size is 0.

#### Steps to Reproduce 
See above.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Occured in Android 8.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
OnePlus 5

#### Cordova CLI version and cordova platform version
    cordova --version                                    8.0.0
    cordova platform version android                     6.4.0
#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.1.3

**Comment by macdonst** [comment]
@dpeacock this will be included in the next release.
