### ISSUE TITLE
Apple rejected my app update because of VoIP introduced with phonegap-plugin-push v2.2.0

### ISSUE THREAD

**Issue by peterpeterparker** [phonegap/phonegap-plugin-push#2251]
### Expected Behaviour

No references to VoIP in Info.plist if VoIP is not used

### Actual Behaviour

In v2.2.0 VoIP suppor was added into `phonegap-plugin-push` (https://github.com/phonegap/phonegap-plugin-push/commit/69e86d98b1e05d1efcaed4be3c50c394fb782ea0) which has for effect that a reference is somehow even if not used added to Info.plist

#### Steps to Reproduce 

Update to `phonegap-plugin-push` to v2.2.0
Don't touch anything
Submit your app to Apple

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

cli packages: (/Users/me/Documents/projects/myproj/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.1.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 5.0.13 
    Node              : v9.4.0
    npm               : 5.6.0 
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/me/Library/Android/sdk

Misc:

    backend : pro

#### Apple

> Guideline 2.5.4 - Performance - Software Requirements
> 
> Your app declares support for VoIP in the UIBackgroundModes key in your Info.plist, but it does not include any Voice over IP services.
> 
> Next Steps
> 
> To resolve this issue, please revise your app to either add VoIP features or remove the "voip" setting from the UIBackgroundModes key.
> 
> We recognize that VoIP can provide "keep alive" functionality that is useful for many app features. However, using VoIP in this manner is not the intended purpose of VoIP.

**Comment by macdonst** [comment]
Yeah, that makes sense. The fix will be to remove the voice setting from
plugin.
xml and put it in config.xml only when needed.

**Comment by fabmesto** [comment]
Hi, in the meantime the bug is fixed as I can do to get me to approve app by Apple?

**Comment by peterpeterparker** [comment]
@fabmesto I downgraded to the previous version I used, v2.1.0, submitted a new build and my update was accepted

ps: since I have updated everything to be up-to-date, I can't build my Android platform with v2.1.0 anymore, only with v2.2.0 😂 I pushed then this version in the play store, no problem there

**Comment by macdonst** [comment]
**Workaround**: Just open the project in Xcode and remove the `voip` string from `remote-notification` in `UIBackgroundModes ` of your pList.

**Comment by macdonst** [comment]
@peterpeterparker can you try my latest from the `master` branch? I've removed the `voip` from plugin.xml and uses of `voip` will need to add it in config.xml.

**Comment by peterpeterparker** [comment]
@macdonst firstly, thx for taking care of that issue so quickly, really appreciated 👍 

I just tried to remove and add the plugin from the `master` branch, looks good to me. I didn't resubmitted my app, of course, but I could confirm that after having added it I can't see any `VoIP` references in my `-Info.plist` file

    <key>UIBackgroundModes</key>
    <array>
      <string>remote-notification</string>
    </array>

**Comment by cbjerg** [comment]
I use the plugin with phonegap-build - which takes it straight from npm. Any way you could update4 the npm package to omit the voip? My apps are also being rejected

**Comment by peterpeterparker** [comment]
@cbjerg you could follow the workaround described above by @macdonst

edit your -Info.plist and remove `VoIP` and you should be fine. The `UIBackgroundModes` key without `VoIP` looks like in this file as I described above in my previous comment

**Comment by cbjerg** [comment]
@peterpeterparker my apps are built using cordova, from an Angular application. I don't know of a way to open them in Xcode?

**Comment by peterpeterparker** [comment]
@cbjerg my App is a Ionic/Cordova too. no need to open Xcode.  Just edit a file called `yourappname-Info.plist` under `./platform/ios/yourappname/`

**Comment by jcesarmobile** [comment]
@cbjerg even when using Phonegap Build, you can still install from github using the github url as spec

Try like this:
`<plugin name="phonegap-plugin-push" spec="https://github.com/phonegap/phonegap-plugin-push.git" />`

**Comment by cbjerg** [comment]
Thank you @jcesarmobile - I couldn't quite get the other solution to work for me.

**Comment by macdonst** [comment]
I have published a 2.2.2 version of the plugin which includes the fix for this issue.
