### ISSUE TITLE
Plugin doesn't support this project's cordova-android version

### ISSUE THREAD

**Issue by kareraisu** [phonegap/phonegap-plugin-push#2252]
Hello there!
First of all thank you for your work.
Due to the breaking change in the android project file structure introduced in cordova-android 7.x, several of my plugins would fail to install, therefore I decided to downgrade back to 6.4.0, but then I cannot install this plugin. I tried with several plugin versions down to 1.9.0 and could not get it to install. I need to be able to use this plugin with cordova-android 6.4.0.
Is it possible?

**Comment by macdonst** [comment]
@kareraisu any version of this plugin less than 2.2.0 should work with cordova-android 6.4.0. 

Which plugins are failing to install. I'd rather push things forward rather then be held back.

**Comment by kareraisu** [comment]
@macdonst Thank you for the quick response. Turns out I was missing the 'v' in the version number and `cordova plugin add` command silently ignores the version if it isn't found, using the last version instead. Sorry for the fuss.

Now I am struggling with the `Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin'] For input string: "+"` issue, but that's another story.

**Comment by macdonst** [comment]
@kareraisu see #1718
