### ISSUE TITLE
bug install

### ISSUE THREAD

**Issue by roger93** [phonegap/phonegap-plugin-push#2257]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by jcesarmobile** [comment]
Closing as invalid, please, fill the template and explain the problem

**Comment by roger93** [comment]
I was creating it. It's all set.

**Comment by jcesarmobile** [comment]
looks like pod command failed, do you have CocoaPods installed?

**Comment by roger93** [comment]
How can I know if it's installed?

**Comment by jcesarmobile** [comment]
If you ask that question, you probably don't have it installed.
if you run `pod --version` and don't get the version installed, then it's not installed.

Again, in the link I provided, you have more information about CocoaPods (how to install, use and troubleshoot errors)

**Comment by roger93** [comment]
I have installed version 1.4.0 but now I'm getting another error 

![captura de pantalla 2018-03-12 a las 10 00 23](https://user-images.githubusercontent.com/7825926/37274273-70bdede8-25dc-11e8-91f5-409f33aff830.png)

The error only passes me the ios I have erased the platform and created it again and remains the same 

there is a solution in the page that you weighed me but it is not solved

**Comment by roger93** [comment]
It's already fixed The solution was what I put in the documentation but I threw an error I restarted the mac and reinstalled it and it worked again thanks a lot for your time.
