### ISSUE TITLE
Clicking on one notification closes all other notification IOS

### ISSUE THREAD

**Issue by lampofdrog** [phonegap/phonegap-plugin-push#2258]
### Expected Behaviour
not clear all notification list

### Actual Behaviour
Clicking on one notification closes all other notification 

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

#### Sample Push Data Payload

$body['aps'] = array(
                'alert' => "title",
                'data'=> "data",
                "badge"=>1,
                'sound' => 'default',
                );

**Comment by macdonst** [comment]
@lampofdrog are you actually using 1.5.3? I'd suggest upgrading to the latest as things tend to change in iOS.

**Comment by lampofdrog** [comment]
@macdonst i am using push version 1.8.0, and i had this issues when i click on one push all others cleares automatically? is there any solution to attribute an id to the push ? plz help me fix this issues?

thank you very much @macdonst

**Comment by macdonst** [comment]
@lampofdrog it's actually by design. When you start the app it dismisses all the notifications:

https://github.com/phonegap/phonegap-plugin-push/blob/14afb94126acb51a6f10a2094f7f391f2f17dee5/src/ios/AppDelegate%2Bnotification.m#L192
