### ISSUE TITLE
Android App crashing on receiving notification in foreground  

### ISSUE THREAD

**Issue by bhumin3i** [phonegap/phonegap-plugin-push#2261]
Android app is crashing in foreground and in background not able to get the push notification. 
Push plugin version :  Tried 2.1.3 and 2.2.2 
Reproducing the same issue in both the versions.
Please help!

My environment details 
    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.1.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.2
    npm  : 5.6.0
    OS   : Windows 7

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by macdonst** [comment]
@bhumin3i please fill out the issue template. You didn't show any code, the push payload, a reproduction scenario or most importantly the logs of the crash.

Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by bhumin3i** [comment]
@macdonst  v 2.1.2  is working fine

**Comment by bhumin3i** [comment]
@macdonst  after install v2.2.2 app still hang my PAYLOAD is

 data" : {
                     "title": "Test Notification",
                     "body": notificationData.message
                     }
         };

**Comment by macdonst** [comment]
@bhumin3i what do you see in `adb logcat` when you send a push to the app?

**Comment by bhumin3i** [comment]
@macdonst  adb logcat : 

[Terminal.log](https://github.com/phonegap/phonegap-plugin-push/files/1870528/Terminal.log)

**Comment by bhumin3i** [comment]
@macdonst any update?
