### ISSUE TITLE
Skipping plugin installation

### ISSUE THREAD

**Issue by aneeskodappana** [phonegap/phonegap-plugin-push#2269]
### Expected Behaviour
Plugin installation
### Actual Behaviour
Skipping Installation of push plugin

```
Installing "phonegap-plugin-push" for android

Plugin doesn't support this project's cordova-android version. cordova-android: 6.3.0, failed version requirement: >=7.1.0

Skipping 'phonegap-plugin-push' for android
Adding phonegap-plugin-push to package.json

Saved plugin info for "phonegap-plugin-push" to config.xml
```

### Reproduce Scenario (including but not limited to)
```
ionic cordova plugin add phonegap-plugin-push
```

```
npm install --save @ionic-native/push
```

```
ionic cordova run android
```
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung
#### Cordova CLI version and cordova platform version

    cordova --version                                    7.1.0 (global)
    cordova platform version android                     android 6.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.2.2

**Comment by jcesarmobile** [comment]
Latest version of the plugin requires cordova-android 7.1.0

**Comment by aneeskodappana** [comment]
@jcesarmobile  the default installation of the latest ionic is come with cordova-android 6.30. is it possible to update the cordova-anroid to 7.1.0

**Comment by jcesarmobile** [comment]
try with `ionic cordova platform rm android` and the `ionic cordova platform add android@7.1.0`

**Comment by aneeskodappana** [comment]
build process failed

**Comment by aneeskodappana** [comment]
I fix it by changing the minSdk from 16 to 19 in config.xml

**Comment by aneeskodappana** [comment]
I fix it by changing the minSdk from 16 to 19 in config.xml
