### ISSUE TITLE
compatibility cordova-plugin-googlemaps

### ISSUE THREAD

**Issue by tmwebs** [phonegap/phonegap-plugin-push#2270]
#### Cordova CLI version and cordova platform version

    cordova --version                                    8.0.0
    cordova platform version android           7.0.0

#### Plugin version

    phonegap-plugin-push 2.1.3 "PushPlugin"

When I use the plugin phonegap-plugin-push with the plugin cordova-plugin-googlemaps I receive the following error when building on Android:

A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"

But if you unite cordova-plugin-googlemaps, the notifications work correctly. Any idea why it is incompatible?

Thank you very much

**Comment by jcesarmobile** [comment]
Update both plugins, you are using old versions.
