### ISSUE TITLE
close app

### ISSUE THREAD

**Issue by tmwebs** [phonegap/phonegap-plugin-push#2273]
#### Cordova CLI version and cordova platform version

    cordova --version                                    8.0.0
    cordova platform version android                     7.1.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.2.2

#### Logs taken while reproducing problem

When I send a notification from PHP, the application is closed, my PHP code is:

```
$deviceID = "XXX-GP29HrPg:APA91bGx8drHX4Rw65vsNL6yHUCzC9TnnSvbuqPF3BufsoWkfeOoyu5o5N5Z7mGEkcXWUlvboNFIu9q6-ByVYk8cKJJ--hdfa9WGT9Cz8eBFPaWVLyeq5d9VK_WIpwNTKbH_scBF9Rvq";

$message = array (
   'to' => $deviceID,
   'data' => array(
      'title'=> 'Large Icon',
      'message'=> 'Loaded from drawables folder.'
   )
);

$headers = array(
    'Content-Type:application/json',
    'Authorization:key=XXXXDvHJ9LFcnYix_NJ0vSzEAL0HrjP3DedIQ'
);

$ch = curl_init();

curl_setopt_array($ch, array(
   CURLOPT_URL => 'https://fcm.googleapis.com/fcm/send',
   CURLOPT_HTTPHEADER => $headers,
   CURLOPT_POST => true,
   CURLOPT_RETURNTRANSFER => true,
   CURLOPT_POSTFIELDS => json_encode($message)
));
$response = curl_exec($ch);
curl_close($ch);

```

The answer he gives me is:
```
{"multicast_id":6275185096060247961,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1521619488363056%a712a457f9fd7ecd"}]}
```

It gives the notification as sent, but the result is that the APP closes

![captura de pantalla 2018-03-21 a las 9 18 45](https://user-images.githubusercontent.com/12540076/37699692-ee0dd3d6-2ce8-11e8-91cd-c126b52d6948.png)

Thanks you.

**Comment by macdonst** [comment]
@tmwebs what is the stack trace in `adb logcat` when the app crashes?

**Comment by tmwebs** [comment]
I could solve it, the problem was that I had:

```
compile "com.google.android.gms:play-services-maps:11.8.0"
compile "com.google.android.gms:play-services-location:11.8.0"
compile "com.google.firebase:firebase-messaging:11.6.2"

```
and I changed to:

```
compile "com.google.android.gms:play-services-maps:11.6.2"
compile "com.google.android.gms:play-services-location:11.6.2"
compile "com.google.firebase:firebase-messaging:11.6.2"

```

thanks you.

**Comment by saurabhDuzumaki** [comment]
Thanks. I had the exact same issue and it was solved by updating dependencies as mentioned in previous comment. But instead of downgrading other two dependencies, updating 
`compile "com.google.firebase:firebase-messaging:11.6.2"` 
to
`compile "com.google.firebase:firebase-messaging:11.8.0"` 
worked for me.
