### ISSUE TITLE
We are planning to deploy app. in Baidu store in China. WIll push.on ('error') be fired if I try to login from China where there are no google services installed ? / no n/w connectivity ?

### ISSUE THREAD

**Issue by Anand1907** [phonegap/phonegap-plugin-push#2277]
### Expected Behaviour
push.on('error') needs to be fired.

### Actual Behaviour
push.on('error') needs to be fired. Has to be tested

#### Steps to Reproduce 
In baidu store, china , 
on registering for push notfication through GCM , will push.on('error') , be fired ?? 

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@Anand1907 that's a really good question. I have not been able to test that but it should error out when the gcm libraries are not detected.
