### ISSUE TITLE
Ionic 3 + phonegap-plugin-push: SERVICE_NOT_AVAILABLE

### ISSUE THREAD

**Issue by anatoly-spb** [phonegap/phonegap-plugin-push#2278]
I have simple application https://github.com/ionic-team/ionic/issues/14213 

### Expected Behaviour
I want to register on FCM server

### Actual Behaviour

When I run it I got:
```
03-22 17:08:10.394 5302-5319/ru.rlisystems.mobile.rms E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
03-22 17:08:22.565 5302-5370/ru.rlisystems.mobile.rms E/dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method com.adobe.phonegap.push.PushPlugin.createChannel
03-22 17:08:22.716 5302-5385/ru.rlisystems.mobile.rms E/Push_Plugin: execute: Got IO Exception SERVICE_NOT_AVAILABLE
03-22 17:09:10.462 5302-5319/ru.rlisystems.mobile.rms E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
03-22 17:11:10.529 5302-5319/ru.rlisystems.mobile.rms E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
03-22 17:15:10.584 5302-5319/ru.rlisystems.mobile.rms E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
03-22 17:23:10.652 5302-5319/ru.rlisystems.mobile.rms E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
```
#### Steps to Reproduce 

```

>ionic start dummy blank # no for all questions

>cd dummy

>ionic cordova platform add android

>ionic cordova plugin add phonegap-plugin-push --variable SENDER_ID=XXXXXXXXXX
..
    cordova-android (6.3.0 in project, >=7.1.0 required)
    Fetching highest version of phonegap-plugin-push that this project supports: 2.1.3 (latest is 2.2.2)
..

>copy ..\XXXXXXXXXX\google-service.json .\

> fix config.xml to use google-service.json:
    <platform name="android">
+        <resource-file src="google-services.json" target="google-services.json" />

>ionic cordova plugin add cordova-android-support-gradle-release

>ionic cordova run android
03-22 17:08:22.716 5302-5385/ru.rlisystems.mobile.rms E/Push_Plugin: execute: Got IO Exception SERVICE_NOT_AVAILABLE
03-22 17:09:10.462 5302-5319/ru.rlisystems.mobile.rms E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
03-22 17:11:10.529 5302-5319/ru.rlisystems.mobile.rms E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 4.4.2 

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Huawei T1-701u

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 7.1.0
    cordova platform version android                     # e.g. 6.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 2.1.3

#### Sample Code that illustrates the problem

```
const options: PushOptions = {
      android: {
        senderID: "XXXXXXXXXXXXXXX",
        clearNotifications: false
      },
      ios: {
        alert: 'true',
        badge: true,
        sound: 'false'
      },
      windows: {}
    };

    const pushObject: PushObject = this.pushObject = push.init(options);

    pushObject.on('registration').subscribe((registration: any) => {
      console.log('Device registered', JSON.stringify(registration))
      this.dataService.invoke(app_USR_mobiletoken_set,
        {
          token_code: this.registrationId = registration.registrationId
        },
        {}
      ).then(r => {
      }).catch(e => {
        console.error("Cannot registered device: " + (e.msg ? e.msg : e))
      })
    });

    pushObject.on('notification').subscribe((notification: any) => {
      this.add(notification);
    });

    pushObject.on('error').subscribe((error) =>{
        //!!!!!!!!!!!!!!!!!!! I got error here !!!!!!!!!!!!!!!!!!!!!!!!!
        alert('Error with Push plugin' + error);
    );
```
#### Logs taken while reproducing problem

```
03-22 17:08:10.394 5302-5319/ru.rlisystems.mobile.rms E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
03-22 17:08:22.565 5302-5370/ru.rlisystems.mobile.rms E/dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method com.adobe.phonegap.push.PushPlugin.createChannel
03-22 17:08:22.716 5302-5385/ru.rlisystems.mobile.rms E/Push_Plugin: execute: Got IO Exception SERVICE_NOT_AVAILABLE
03-22 17:09:10.462 5302-5319/ru.rlisystems.mobile.rms E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
03-22 17:11:10.529 5302-5319/ru.rlisystems.mobile.rms E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
03-22 17:15:10.584 5302-5319/ru.rlisystems.mobile.rms E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
```

**Comment by anatoly-spb** [comment]
I have reverted to `phonegap-plugin-push@2.1.2` with `FCM_VERSION=11.0.1` and now everything works fine:
```
ionic cordova plugin remove phonegap-plugin-push
ionic cordova plugin add phonegap-plugin-push@2.1.2 --variable SENDER_ID=XXXXXX --FCM_VERSION=11.0.1
```

**Comment by anatoly-spb** [comment]
@macdonst why do you close issue?

**Comment by macdonst** [comment]
@anatoly-spb because you said you fixed it by changing the fcm version. Which is something the plugin supports.

**Comment by anatoly-spb** [comment]
@macdonst if you invoke `npm install` the `phonegap-plugin-push@2.1.3` will replaced automatically `phonegap-plugin-push@2.1.2`. As the result phonegap-plugin-push must fix version 2.1.2 for cordova-android 6.3.0, because the 2.1.3 does not work.

**Comment by macdonst** [comment]
@anatoly-spb I'm not sure what you mean by "npm install the phonegap-plugin-push@2.1.3 will replace automatically phonegap-plugin-push@2.1.2". You can control the version of the push plugin by editing your config.xml and you can also set the version of fcm used in config.xml so I'm not sure what you want me to fix.

**Comment by anatoly-spb** [comment]
@macdonst I took one day to investigate and fix problem. I have showed the reproduced scenario. As you see
```
ionic cordova plugin add phonegap-plugin-push --variable SENDER_ID=XXXXXXXXXX
```
added wrong version of plugin. If you do not freeze 2.1.2 for cordova-android 6.3.0 other people still will have problem with 6.3.0.

**Comment by CristianDeluxe** [comment]
I have this problem too, with:

MacOS **10.13.4**
Cordova Version: **8.0.0**
Cordova platform version android **7.1.0**
phonegap-plugin-push **2.2.2** "PushPlugin"

Some errors
`
E/Push_Plugin: execute: Got IO Exception SERVICE_NOT_AVAILABLE
W/MessengerIpcClient: Invalid interface descriptor: com.google.android.gms.iid.IMessengerCompat
E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
`

**Comment by anatoly-spb** [comment]
@CristianDeluxe 2.2.2 does not work, use 2.1.2 instead. 
@macdonst as you can see you closed real issue.

**Comment by macdonst** [comment]
@CristianDeluxe it is probably a mis-match with other play services/fcm versions included from other plugins. I would need more information on your particular setup.

**Comment by CristianDeluxe** [comment]
A list of all plugins installed:

```
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.3.2 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-push 2.2.2 "PushPlugin"
```

In IOS push is working ok, tell me if you need more info.

**Comment by CristianDeluxe** [comment]
I can confirm that downgrading to 2.1.2 fixes the error as stated by @anatoly-spb, no other actions were required.

remove android platform
remove push plugin
add push plugin v2.1.2
add android platform

All working.

**Comment by macdonst** [comment]
@CristianDeluxe yeah, 2.1.3 updates the version of the FCM library the plugin uses. I believe it is that update that is causing some problems. The `cordova-plugin-x-socialsharing` pins a pretty old version of the support library and that's where I think the problem shows up.

**Comment by AlphaCreative** [comment]
I'm having the same issue with version 2.2.1 of the plugin.  Here is my plugin list:

- cordova-background-geolocation 2.10.1 "BackgroundGeolocation"
- cordova-plugin-app-event 1.2.1 "Application Events"
- cordova-plugin-background-fetch 5.2.1 "CDVBackgroundFetch"
- cordova-plugin-badge 0.7.2 "Badges"
- cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
- cordova-plugin-device 1.1.4 "Device"
- cordova-plugin-dialogs 1.3.1 "Notification"
- cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
- cordova-plugin-splashscreen 5.0.2 "Splashscreen"
- cordova-plugin-statusbar 2.4.1 "StatusBar"
- cordova-plugin-whitelist 1.3.3 "Whitelist"
- cordova-sqlite-storage 2.3.1 "Cordova sqlite storage plugin"
- es6-promise-plugin 4.2.2 "Promise"
- phonegap-plugin-push 2.2.1 "PushPlugin"
