### ISSUE TITLE
Android - Can't build the project when having phonegap-plugin-push installed "error: cannot find symbol"

### ISSUE THREAD

**Issue by HamzaLJ** [phonegap/phonegap-plugin-push#2279]
### Expected Behaviour

It should build without errors

### Actual Behaviour

     `      UP-TO-DATE
      :compileReleaseJavaWithJavac

      :compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
      /Users/Hamza/Desktop/del/platforms/android/src/com/adobe/phonegap/push/PushPlugin.java:5: error: cannot find symbol
      import android.app.NotificationChannel;
                        ^
        symbol:   class NotificationChannel
        location: package android.app
      /Users/Hamza/Desktop/del/platforms/android/src/com/adobe/phonegap/push/PushPlugin.java:38: error: package me.leolin.shortcutbadger does not exist

      import me.leolin.shortcutbadger.ShortcutBadger;
                                     ^
      /Users/Hamza/Desktop/del/platforms/android/src/com/adobe/phonegap/push/FCMService.java:5: error: cannot find symbol
      import android.app.NotificationChannel;
                        ^
        symbol:   class NotificationChannel
        location: package android.app
      /Users/Hamza/Desktop/del/platforms/android/src/com/adobe/phonegap/push/PushPlugin.java:63: error: cannot find symbol
          if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                                                          ^
        symbol:   variable O
        location: class VERSION_CODES
      /Users/Hamza/Desktop/del/platforms/android/src/com/adobe/phonegap/push/PushPlugin.java:66: error: cannot find symbol
            List<NotificationChannel> notificationChannels = notificationManager.getNotificationChannels();
                 ^
        symbol:   class NotificationChannel

        location: class PushPlugin
      /Users/Hamza/Desktop/del/platforms/android/src/com/adobe/phonegap/push/PushPlugin.java:66: error: cannot find symbol
            List<NotificationChannel> notificationChannels = notificationManager.getNotificationChannels();
                                                                                ^
        symbol:   method getNotificationChannels()
        location: variable notificationManager of type NotificationManager
      /Users/Hamza/Desktop/del/platforms/android/src/com/adobe/phonegap/push/PushPlugin.java:67: error: cannot find symbol
            for (NotificationChannel notificationChannel : notificationChannels) {
                 ^
        symbol:   class NotificationChannel
        location: class PushPlugin
      /Users/Hamza/Desktop/del/platforms/android/src/com/adobe/phonegap/push/PushPlugin.java:80: error: cannot find symbol
          if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                                                          ^`

#### Steps to Reproduce 

**project.properties**

       target=android-23
       android.library.reference.1=CordovaLib
       cordova.gradle.include.1=cordova-plugin-mauron85-background-geolocation/starter-logtofile.gradle
       cordova.system.library.1=com.google.android.gms:play-services-location:11.8.0
       cordova.system.library.2=com.android.support:support-v4:23.0.0
       cordova.system.library.3=com.google.firebase:firebase-messaging:11.8.0
       cordova.gradle.include.2=phonegap-plugin-push/app-push.gradle

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 7.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

N/A

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.1.0
    cordova platform version android                       android 6.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   phonegap-plugin-push 2.1.0 "PushPlugin"

**Comment by macdonst** [comment]
@HamzaLJ well there is something very wrong with your build environment. You can't even find `Build.VERSION_CODES.O`. Go into your SDK manager and update all the dependencies and try to build again.

**Comment by HamzaLJ** [comment]
All the dependencies are up to date; however the push plugin is throwing errors. 
By the way, I've tried to uninstall the plugin, and I was able to successfully build.

Here is a screenshot from Android Studio:
https://ibb.co/dR5VQS

**Comment by jcesarmobile** [comment]
Your problem is you are targeting SDK 23, the plugin requires to target SDK 27

**Comment by HamzaLJ** [comment]
@jcesarmobile when switching to SDK27, I get the following : 


Error: /Users/Hamza/Desktop/del/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/Hamza/Desktop/del/platforms/android/src/com/adobe/phonegap/push/PushPlugin.java:38: error: package me.leolin.shortcutbadger does not exist
import me.leolin.shortcutbadger.ShortcutBadger;
                               ^
/Users/Hamza/Desktop/del/platforms/android/src/com/adobe/phonegap/push/PushPlugin.java:445: error: cannot find symbol
      ShortcutBadger.applyCount(context, badgeCount);
      ^
  symbol:   variable ShortcutBadger
  location: class PushPlugin
/Users/Hamza/Desktop/del/platforms/android/src/com/adobe/phonegap/push/PushPlugin.java:447: error: cannot find symbol
      ShortcutBadger.removeCount(context);
      ^
  symbol:   variable ShortcutBadger
  location: class PushPlugin
/Users/Hamza/Desktop/del/platforms/android/src/com/adobe/phonegap/push/FCMService.java:388: error: constructor Builder in class Builder cannot be applied to given types;
        mBuilder = new NotificationCompat.Builder(context, channelID);
                   ^
  required: Context
  found: Context,String
  reason: actual and formal argument lists differ in length
/Users/Hamza/Desktop/del/platforms/android/src/com/adobe/phonegap/push/FCMService.java:398: error: constructor Builder in class Builder cannot be applied to given types;
        mBuilder = new NotificationCompat.Builder(context, channelID);
                   ^
  required: Context
  found: Context,String
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by macdonst** [comment]
Thanks for spotting the @jcesarmobile

>

**Comment by HamzaLJ** [comment]
@macdonst it reduced the numbers of errors; however, I still can't get rid of them...

**Comment by macdonst** [comment]
@HamzaLJ sorry man, if you are still having problems I'd remove and re-add the Android platform.
