### ISSUE TITLE
Error in Success callbackId: PushNotification478999427 : TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by graceaffi** [phonegap/phonegap-plugin-push#2280]
### Expected Behaviour
when i with phonegap with app developer i am getting above Error
### Actual Behaviour
` Error in Success callbackId: PushNotification1454691342 : TypeError: Cannot read property 'querySelector' of null`
### Reproduce Scenario (including but not limited to)
Sending a notification to  Android device while device is open
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1.1
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Moto G (3d generation)
#### Plugin version
phonegap-plugin-push version 1.8.0

**Comment by jcesarmobile** [comment]
There is no querySelector code in the plugin, that should be yours
