### ISSUE TITLE
No notification when app not in foreground

### ISSUE THREAD

**Issue by bastaware** [phonegap/phonegap-plugin-push#2281]
### Expected Behaviour
Notification should be displayed in system tray when application is in background

### Actual Behaviour
No notification is displayed when app is not in foreground

### Reproduce Scenario (including but not limited to)
No notifications appear when application is in background, only when in foreground. Looking at the log, the message is delivered. It works fine on my Nexus 9 (Android 7.1.1)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung 8 Plus

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.1.0
    cordova platform version android         6.4.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   = phonegap-plugin-push 1.10.6 "PushPlugin"

#### Sample Push Data Payload
message: "1234"
title: "Test title"

#### Sample Code that illustrates the problem
Using java com.google.android.gcm.server

Message message = new Message.Builder().collapseKey("0").delayWhileIdle(true).addData("message","1234").addData("title", "Test title").build();
sender.send(message, messageId, 1);

#### Logs taken while reproducing problem
**Log while app is in background:**

03-24 01:07:31.748 21542-22083/com.test.app D/Push_GCMIntentService: onMessage - from: 494450416336
03-24 01:07:31.751 21542-22083/com.test.app D/Push_GCMIntentService: normalize extras
03-24 01:07:31.751 21542-22083/com.test.app D/Push_GCMIntentService: key = google.sent_time
03-24 01:07:31.752 21542-22083/com.test.app D/Push_GCMIntentService: replace key google.sent_time with google.sent_time
03-24 01:07:31.752 21542-22083/com.test.app D/Push_GCMIntentService: key = google.ttl
03-24 01:07:31.752 21542-22083/com.test.app D/Push_GCMIntentService: replace key google.ttl with google.ttl
03-24 01:07:31.753 21542-22083/com.test.app D/Push_GCMIntentService: key = title
03-24 01:07:31.753 21542-22083/com.test.app D/Push_GCMIntentService: replace key title with title
03-24 01:07:31.755 21542-22083/com.test.app D/Push_GCMIntentService: no locale found for key = title, error Value Test of type java.lang.String cannot be converted to JSONObject
03-24 01:07:31.755 21542-22083/com.test.app D/Push_GCMIntentService: key = google.message_id
03-24 01:07:31.756 21542-22083/com.test.app D/Push_GCMIntentService: replace key google.message_id with google.message_id
03-24 01:07:31.756 21542-22083/com.test.app D/Push_GCMIntentService: key = message
03-24 01:07:31.756 21542-22083/com.test.app D/Push_GCMIntentService: replace key message with message
03-24 01:07:31.758 21542-22083/com.test.app D/Push_GCMIntentService: no locale found for key = message, error Value 1234serv of type java.lang.String cannot be converted to JSONObject
03-24 01:07:31.758 21542-22083/com.test.app D/Push_GCMIntentService: key = collapse_key
03-24 01:07:31.758 21542-22083/com.test.app D/Push_GCMIntentService: replace key collapse_key with collapse_key
03-24 01:07:31.759 21542-22083/com.test.app D/Push_GCMIntentService: background
03-24 01:07:31.764 21542-22083/com.test.app D/Push_GCMIntentService: message =[1234serv]
03-24 01:07:31.764 21542-22083/com.test.app D/Push_GCMIntentService: title =[Test title]
03-24 01:07:31.764 21542-22083/com.test.app D/Push_GCMIntentService: contentAvailable =[null]
03-24 01:07:31.765 21542-22083/com.test.app D/Push_GCMIntentService: forceStart =[null]
03-24 01:07:31.765 21542-22083/com.test.app D/Push_GCMIntentService: create notification
03-24 01:07:31.767 21542-22083/com.test.app E/Push_GCMIntentService: Number format exception - Error parsing notId: s == null
03-24 01:07:31.828 21542-21548/com.test.app I/zygote64: Method exceeds compiler instruction limit: 25337 in void org.ccil.cowan.tagsoup.HTMLSchema.<init>()
03-24 01:07:31.850 21542-22083/com.test.app D/Push_GCMIntentService: stored icon=null
03-24 01:07:31.850 21542-22083/com.test.app D/Push_GCMIntentService: stored iconColor=null
03-24 01:07:31.850 21542-22083/com.test.app D/Push_GCMIntentService: stored sound=true
03-24 01:07:31.850 21542-22083/com.test.app D/Push_GCMIntentService: stored vibrate=true
03-24 01:07:31.850 21542-22083/com.test.app D/Push_GCMIntentService: no icon resource found - using application icon
03-24 01:07:31.865 21542-22083/com.test.app D/Push_GCMIntentService: create actions: with in-line
03-24 01:07:31.871 21542-22083/com.test.app W/Notification: Use of stream types is deprecated for operations other than volume control
03-24 01:07:31.872 21542-22083/com.test.app W/Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case

**Log while app is in foreground**

3-24 01:04:31.742 21542-22083/com.test.app D/Push_GCMIntentService: onMessage - from: 494450416336
03-24 01:04:31.745 21542-22083/com.test.app D/Push_GCMIntentService: normalize extras
03-24 01:04:31.745 21542-22083/com.test.app D/Push_GCMIntentService: key = google.sent_time
03-24 01:04:31.745 21542-22083/com.test.app D/Push_GCMIntentService: replace key google.sent_time with google.sent_time
03-24 01:04:31.746 21542-22083/com.test.app D/Push_GCMIntentService: key = google.ttl
03-24 01:04:31.746 21542-22083/com.test.app D/Push_GCMIntentService: replace key google.ttl with google.ttl
03-24 01:04:31.746 21542-22083/com.test.app D/Push_GCMIntentService: key = title
03-24 01:04:31.746 21542-22083/com.test.app D/Push_GCMIntentService: replace key title with title
03-24 01:04:31.747 21542-22083/com.test.app D/Push_GCMIntentService: no locale found for key = title, error Value Test of type java.lang.String cannot be converted to JSONObject
03-24 01:04:31.748 21542-22083/com.test.app D/Push_GCMIntentService: key = google.message_id
03-24 01:04:31.748 21542-22083/com.test.app D/Push_GCMIntentService: replace key google.message_id with google.message_id
03-24 01:04:31.748 21542-22083/com.test.app D/Push_GCMIntentService: key = message
03-24 01:04:31.748 21542-22083/com.test.app D/Push_GCMIntentService: replace key message with message
03-24 01:04:31.749 21542-22083/com.test.app D/Push_GCMIntentService: no locale found for key = message, error Value 1234 of type java.lang.Integer cannot be converted to JSONObject
03-24 01:04:31.749 21542-22083/com.test.app D/Push_GCMIntentService: key = collapse_key
03-24 01:04:31.749 21542-22083/com.test.app D/Push_GCMIntentService: replace key collapse_key with collapse_key
03-24 01:04:31.749 21542-22083/com.test.app D/Push_GCMIntentService: key = foreground
03-24 01:04:31.749 21542-22083/com.test.app D/Push_GCMIntentService: replace key foreground with foreground
03-24 01:04:31.749 21542-22083/com.test.app D/Push_GCMIntentService: foreground
03-24 01:04:31.750 21542-22083/com.test.app D/Push_Plugin: convert extras to json
03-24 01:04:31.750 21542-22083/com.test.app D/Push_Plugin: key = google.sent_time
03-24 01:04:31.750 21542-22083/com.test.app D/Push_Plugin: key = google.ttl
03-24 01:04:31.750 21542-22083/com.test.app D/Push_Plugin: key = title
03-24 01:04:31.750 21542-22083/com.test.app D/Push_Plugin: key = google.message_id
03-24 01:04:31.750 21542-22083/com.test.app D/Push_Plugin: key = message
03-24 01:04:31.750 21542-22083/com.test.app D/Push_Plugin: key = coldstart
03-24 01:04:31.750 21542-22083/com.test.app D/Push_Plugin: key = collapse_key
03-24 01:04:31.750 21542-22083/com.test.app D/Push_Plugin: key = foreground
03-24 01:04:31.751 21542-22083/com.test.app V/Push_Plugin: extrasToJSON: {"title":"Test title","message":"1234","additionalData":{"google.message_id":"0:1521849870053115%b71cbd2a00000030","coldstart":false,"collapse_key":"0","foreground":true}}
03-24 01:04:31.825 21542-21542/com.test.app D/ScrollView: initGoToTop

Message received when app is open: [screenshot](https://imgur.com/a/TxgHD)

Maybe cloned https://github.com/phonegap/phonegap-plugin-push/issues/1894

**Comment by macdonst** [comment]
@bastaware can you send me an example of your push payload?

**Comment by bastaware** [comment]
This is toString on the Java Message object. Don't know if that's enough?

Message(collapseKey=0, delayWhileIdle=true, data: {message=hello,title=Test title,notId=0})

The **notId** was added, because I saw a problem in the log (not in the one attached) parsing 'notId' gave exception. This disappeared when I added the notId entry.

This is the actual code:

`				Message message = new Message.Builder().collapseKey("" + collapseKey).delayWhileIdle(true).addData("message", messageText).addData("title", messageTitle).addData("notId", "0").build();
				String themessage = message.toString();
				System.out.println("The message:" + themessage);
				Result result = sender.send(message, messageId, 1);
`

**Comment by sreenivas1901** [comment]
Even I am facing a similar issue. I am using v2.1.3 of the plugin with cordova-android v6.3.0... I have tested on Android 8+ and Android 7+. When the notification is triggered with the application in foreground or background, I get the notification as expected. When the same notification is triggered with the application cleared from memory (swipe close from recent apps), no notification is received (no notification in the system tray). I am not getting any logs which kind of implies that the plugin is not invoked at all in this case. However, as per my understanding, the notification should be handled by the default Android notification handler, which is not happening. Not sure what the issue is. Any help is much appreciated.

PS: I'm passing the payload in data, and not notification.

**Comment by macdonst** [comment]
@bastaware it seems like you are testing on Android 8 with push plugin 1.10.6. Because of changes in Android 8 you will need to update to the v2.x version of the plugin.

@sreenivas1901 the OS should pass the incoming data to the FCMService class of the plugin to have it displayed. Logs would help.

**Comment by Christina-Popova** [comment]
> it seems like you are testing on Android 8 with push plugin 1.10.6. Because of changes in Android 8 you will need to update to the v2.x version of the plugin.
> 
I have the same issue with Android 8 and push plugin 1.10.7.
@macdonst, If there any way to use GSM instead FCM with  Android 8 or only the v2.x version?

**Comment by macdonst** [comment]
@Christina-Popova the migration from GCM to FCM is not hard. It's mostly setting up a project on Google just like GCM. Then you download a json file to add it to your app.

**Comment by Christina-Popova** [comment]
@macdonst Thanks for the quick reply. We've already released application in Play market which is using GSM. If we migrate to FCM, will sending push notification via GSM still work? Cause we need some time to testing FCM before new release!

**Comment by macdonst** [comment]
@Christina-Popova you mean GCM (Google Cloud Messaging) not GSM (Groupe Spécial Mobile) right? 

Whoever is in charge of your GCM app on Google probably got an email today saying that GCM is deprecated and you should upgrade to FCM. A quote from the email: 

> The GCM server and client APIs are deprecated and will be removed as soon as April 11, 2019.  We recommend you upgrade sooner rather than later so you can start taking advantage of the new features in FCM today.

The migration from GCM to FCM is not terrible on the server side. For our node service we just switched a package and it worked the same. On the client side you'd need to upgrade the plugin version and include the GoogleServices-info.json file in your app.

Google spells it out here:

https://developers.google.com/cloud-messaging/android/android-migrate-fcm?utm_medium=email&utm_source=msa

You'd need to take care of 1 & 4 but the v2 plugin has already done 2 & 3 for you.

**Comment by bastaware** [comment]
Gosh! It really was that easy to switch to FCM. I didn't even change anything on the server. Thanks!
