### ISSUE TITLE
cordova-android version requirement mistake?

### ISSUE THREAD

**Issue by oliverjanik** [phonegap/phonegap-plugin-push#2284]
I think there's been a mistake. Version 2.2.0 bumped cordova-android requirements to 7.1 even though it still says cordova 7.1 which comes with cordova-android 6.3

The change was done in this commit: https://github.com/phonegap/phonegap-plugin-push/commit/68884671116c9f1e23de0b9cba583a2a008516ed#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Was that a mistake?

This gives me an error when installing the plugin for android on cordova 7.1 because I can never fulfill that requirement.

```
Plugin doesn't support this project's cordova-android version. cordova-android: 6.3.0, failed version requirement: >=7.1.0
Skipping 'phonegap-plugin-push' for android
```

**Comment by macdonst** [comment]
@oliverjanik no, it wasn't a mistake. There is a fix in cordova-android 7.1.0 that is needed for 2.2.0. Just because cordova pins a version of a platform it doesn't mean you can't install a later version. Just update the cordova-android version in your config.xml.

**Comment by oliverjanik** [comment]
Thanks for the info, what fix are you referring to, if you don't mind?

**Comment by macdonst** [comment]
https://github.com/apache/cordova-android/commit/3a339ba37fc979d5abec809ff085a2d410c48d99
