### ISSUE TITLE
Ionic 2: Push notification action button callback not getting called when app is not running

### ISSUE THREAD

**Issue by mpadmaraj** [phonegap/phonegap-plugin-push#2285]
### Expected Behaviour
Callback method provided should be called. The inline reply should be passed to the callback.
### Actual Behaviour
The the app is not running at all, callback is not called. When it is running in background it works as expected.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Redmi Note4
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

#### Sample Push Data Payload
`"actions": [
      {
        "icon": "reply",
        "title": "reply",
        "callback": "post",
        "foreground": true,
        "inline": true,
        "replyLabel": "Enter your reply here"
      }
    ]`
#### Sample Code that illustrates the problem
In the index.d.ts I added my callback
`export declare type PushEvent = 'registration' | 'error' | 'notification' | 'post';`
Then in my code I have something like this:
`   this.pushObject.on('post').subscribe(data => {
      console.log(JSON.stringify(data));
   });`

**Comment by macdonst** [comment]
@mpadmaraj if there is no app in the background there is no web view in memory in order to run the action button callback. There's no way to get for this to work other than setting the force-start property. 

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#application-force-closed
