### ISSUE TITLE
Fatal exception when getting instance id on android (was working fine last week)

### ISSUE THREAD

**Issue by andyce1010** [phonegap/phonegap-plugin-push#2286]
### Expected Behaviour
Instance id should be returned without error

### Actual Behaviour
The app crashes with the error below.

### Reproduce Scenario (including but not limited to)
Error occurs upon starting cordova app.

#### Steps to Reproduce 
Build and run the app.

Note: Builds of my app created before 21/03/2018 are working fine, but if I rebuild the exact same codebase I get the above errors, so i suspect something broken is being pulled into the build.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.0 

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung 

#### Cordova CLI version and cordova platform version
    cordova --version                                    # e.g. 6.0.0
6.5.0
    cordova platform version android          # e.g. 4.1.1
6.4.0 

#### Plugin version

cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3
1.10.6

#### Logs taken while reproducing problem
FATAL EXCEPTION: pool-1-thread-2
03-26 09:48:08.508: E/AndroidRuntime(3998): Process: XXXXX, PID: 3998
03-26 09:48:08.508: E/AndroidRuntime(3998): java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzv; or its super classes (declaration of 'com.google.android.gms.common.util.zzv' appears in /data/app/XXXXXXXX)
03-26 09:48:08.508: E/AndroidRuntime(3998): 	at com.google.android.gms.iid.zzo.<init>(Unknown Source:35)
03-26 09:48:08.508: E/AndroidRuntime(3998): 	at com.google.android.gms.iid.zzo.<init>(Unknown Source:3)
03-26 09:48:08.508: E/AndroidRuntime(3998): 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source:24)
03-26 09:48:08.508: E/AndroidRuntime(3998): 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source:1)
03-26 09:48:08.508: E/AndroidRuntime(3998): 	at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:73)
03-26 09:48:08.508: E/AndroidRuntime(3998): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-26 09:48:08.508: E/AndroidRuntime(3998): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-26 09:48:08.508: E/AndroidRuntime(3998): 	at java.lang.Thread.run(Thread.java:764)

**Comment by macdonst** [comment]
@andyce1010 yeah, it might be because of an update by Google. I just released a 1.10.7 after merging https://github.com/phonegap/phonegap-plugin-push/pull/2275. Can you upgrade and try to reproduce?

**Comment by andyce1010** [comment]
@macdonst Yeah that's working fine now thanks.

Do you know if there a way that I can prevent this issue from happening again? It worries me that my build may suddenly break, and I'll have to wait for another package update.

**Comment by macdonst** [comment]
@andyce1010 well the problem is Google upgrades the libraries and breaks stuff. I wish I had better news than that.
