### ISSUE TITLE
cordova (8.0.0 in project, >100 required)

### ISSUE THREAD

**Issue by fizdalf** [phonegap/phonegap-plugin-push#2287]
### Expected Behaviour
latest version of the plugin to be installed
### Actual Behaviour
I get a notice saying:

> Unmet project requirements for latest version of phonegap-plugin-push:
>cordova (8.0.0 in project, >100 required)
>Fetching highest version of phonegap-plugin-push that this project supports: 1.10.7 (latest is 2.2.2)

If I let the installation move forward and try to build in Xcode I get the following:

> library not found for -lPods-Metro Plumbers App

### Reproduce Scenario (including but not limited to)
I'm using ionic to generate a v1 project with Cordova.... so 

1. `ionic start test tabs --cordova --type=ionic1`
2. `cd test`
3. `ionic cordova  plugin add phonegap-plugin-push`
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
MacOS 10.13.3
#### Cordova CLI version and cordova platform version
  Cordova version 8.0.0
#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

#### Logs taken while reproducing problem

**Comment by macdonst** [comment]
@fizdalf I forgot to update the `latest` tag when I published a 1.x version. I just updated npm. Can you try again and let me know if the problem is resolved.

**Comment by fizdalf** [comment]
Installed correctly now, I still had to run the installation of the cocoa pods manually though.

Sorry for the delay in the the answer, and thanks for your effort and prompt response!!
