### ISSUE TITLE
erro phonegap build 'com.google.android.gms.license'

### ISSUE THREAD

**Issue by lalacontrin** [phonegap/phonegap-plugin-push#2288]
I try buil my project, but I have this error, 

Execution failed for task ':processReleaseResources'.
> Error: more than one library with package name 'com.google.android.gms.license'.

I comment all my others plugin and error persist, but why I comment phonegap-plugin-push the project  working.

I try new v1 version 1.10.7

phonegap-version: 7.1.0

Phonega-push-plugin: 1.10.7 (I need v1)

ANDROID_SUPPORT_VERSION: 21.+

FCM_VERSION: 11.+

PLAY_SERVICES_VERSION: 11.+

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by lalacontrin** [comment]
ok, I try other submission...
tks
