### ISSUE TITLE
Android 8, onNotification JS event not fired from notification received in background

### ISSUE THREAD

**Issue by chaceburnette** [phonegap/phonegap-plugin-push#2289]
### Expected Behaviour
Background notification is received.  Tapping the notification opens the app and fires the `onNotification` event.

### Actual Behaviour
The `onNotification` event is never fired

### Reproduce Scenario (including but not limited to)
Problem encountered on multiple android 8 devices.
Several android 7 devices tested and working as expected.

#### Cordova CLI version and cordova platform version
cordova version 7.1
cordova android version 6.3.0

#### Plugin version
1.10.7

#### Sample Push Data Payload
    "GCM": {
        "notification": {
            "text" : message,
            "sound" : sound_value,
            "icon" : "status_icon"
        },
        "data": { 
            "message" : message,
            "sound" : sound_value,
            "options" : options 
        },
        "priority" : "high"
    }

**Comment by macdonst** [comment]
@chaceburnette read the docs please, we've been over this multiple times.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

**Comment by chaceburnette** [comment]
@macdonst thanks but i already tried that.  I was finally able to get a message about null notification channels, which means I guess we need to update to 2.1 of the plugin and that this does not work with 1.10.7.....

**Comment by macdonst** [comment]
@chaceburnette ah yes, the 1.x stream does not have support for Android 8 which requires a message channel.

**Comment by etyp** [comment]
@macdonst is there any potential for patching the 1.x stream to support message channels?

We've been trying to update to 2.x but have separate issues where `PushNotification` isn't getting defined (obviously a config issue on our side).

**Comment by macdonst** [comment]
@etyp I've got no plans to patch 1.x with support for message channels. If someone wants to take it on I will gladly review the PR. Patching 1.x which only uses GCM seems to be a bad idea as Google has switched to FCM and strongly urges folks to use FCM instead.

**Comment by etyp** [comment]
@mac89 got it, makes sense. It seems like on the 2.x stream (where `PushNotification` never gets defined) we're getting the following:

```
W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.our.app flg=0x4000010 (has extras) } to com.android.musicfx/.Compatibility$Receiver
```
And
```
E FirebaseInstanceId: Failed to start service while in background: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.firebase.INSTANCE_ID_EVENT pkg=com.google.android.gm cmp=com.google.android.gm/com.google.firebase.iid.FirebaseInstanceIdService (has extras) }: app is in background uid UidRecord{99da545 u0a87 TRNB idle change:uncached procs:1 seq(0,0,0)}
```

I'd rather not open an issue on this repo if the above isn't relevant - do you have any ides what could cause this? Or should I open a separate issue?

(note: I've quadruple checked the [installation docs + requirements](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md) and we seem to match them..)
