### ISSUE TITLE
erro phonegap build 'com.google.android.gms.license'

### ISSUE THREAD

**Issue by lalacontrin** [phonegap/phonegap-plugin-push#2291]
### Expected Behaviour
generate build wich phonegap build

### Actual Behaviour
don't generate build wich phonegap build
log return error:
Execution failed for task ':processReleaseResources'.
Error: more than one library with package name 'com.google.android.gms.license'.

### Reproduce Scenario (including but not limited to)

    <name>Kozinhar</name>
    <description>
        Livro de Receita Digital, com um gerador de Lista de compras
        Aplicativo ideal para você que adora cozinha, o KoopCook é mais que um aplicativo é uma filosofia de que cozinhar faz bem.
        Você pode gerenciar suas receitas, gerar lista de compras e ainda colocar observações a cada preparo, tudo para que cozinha seja ainda mais gostoso.
    </description>
    <author email="programadora@agenciadream.com">
        Agencia Dream
    </author>
    <content src="index.html" />
    <preference name="phonegap-version" value="cli-7.1.0" />
    <preference name="permissions" value="none" />
    <preference name="orientation" value="portrait" />
    <preference name="webviewbounce" value="true" />
    <preference name="prerendered-icon" value="true" />
    <preference name="stay-in-webview" value="false" />
    <preference name="ios-statusbarstyle" value="black-opaque" />
    <preference name="detect-data-types" value="true" />
    <preference name="exit-on-suspend" value="false" />
    <preference name="show-splash-screen-spinner" value="true" />
    <preference name="auto-hide-splash-screen" value="true" />
    <preference name="disable-cursor" value="false" />
    <preference name="android-minSdkVersion" value="21" />
    <preference name="android-targetSdkVersion" value="21" />
    <preference name="android-installLocation" value="auto" />
    <preference name="AndroidPersistentFileLocation" value="Compatibility" />
    <plugin name="cordova-android-support-gradle-release" spec="^1.2.1">
        <variable name="ANDROID_SUPPORT_VERSION" value="21.+" />
    </plugin>
    <plugin name="cordova-plugin-camera" source="npm" spec="~2.1.1" />
    <plugin name="cordova-plugin-media-capture" source="npm" spec="~1.2.0" />
    <plugin name="cordova-plugin-device" source="npm" spec="~1.1.1" />
    <plugin name="cordova-plugin-dialogs" source="npm" spec="~1.2.0" />
    <plugin name="cordova-plugin-file" source="npm" spec="~4.1.1" />
    <plugin name="cordova-plugin-file-transfer" source="npm" spec="~1.5.0" />
    <plugin name="cordova-plugin-inappbrowser" source="npm" spec="~1.3.0" />
    <plugin name="cordova-plugin-media" source="npm" spec="~2.2.0" />
    <plugin name="cordova-plugin-network-information" source="npm" spec="~1.2.0" />
    <plugin name="cordova-plugin-splashscreen" source="npm" spec="~3.2.1" />
    <plugin name="cordova-plugin-statusbar" source="npm" spec="~2.1.2" />
    <plugin name="cordova-plugin-whitelist" source="npm" spec="~1.2.1" />
    <preference name="android-build-tool" value="gradle" />
    <icon src="icon.png" />
    <splash src="splash.png" />
    <platform name="android">
        <feature name="BarcodeScanner">
            <param name="android-package" value="com.phonegap.plugins.barcodescanner.BarcodeScanner" />
        </feature>
        <feature name="Camera">
            <param name="android-package" value="org.apache.cordova.CameraLauncher" />
        </feature>
        <splash density="ldpi" src="200x320.png" />
        <splash density="mdpi" src="320x480.png" />
        <splash density="hdpi" src="480x800.png" />
        <splash density="xhdpi" src="720x1280.png" />
        <splash density="xxhdpi" src="960x1600.png" />
        <splash density="xxxhdpi" src="1280x1920.png" />
        <icon density="ldpi" src="www/res/icon/android/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="www/res/icon/android/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="www/res/icon/android/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="www/res/icon/android/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="www/res/icon/android/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="www/res/icon/android/drawable-xxxhdpi-icon.png" />
        <icon density="ldpi" src="www/res/icon/android/drawable-ldpi/icon.png" target="www/res/drawable-ldpi/icon-small.png" />
        <icon density="mdpi" src="www/res/icon/android/drawable-mdpi/icon.png" target="www/res/drawable-mdpi/icon-small.png" />
        <icon density="hdpi" src="www/res/icon/android/drawable-hdpi/icon.png" target="www/res/drawable-hdpi/icon-small.png" />
        <icon density="xhdpi" src="www/res/icon/android/drawable-xhdpi/icon.png" target="www/res/drawable-xhdpi/icon-small.png" />
        <icon density="xxhdpi" src="www/res/icon/android/drawable-xxhdpi/icon.png" target="www/res/drawable-xxhdpi/icon-small.png" />
        <icon density="xxxhdpi" src="www/res/icon/android/drawable-xxxhdpi/icon.png" target="www/res/drawable-xxxhdpi/icon-small.png" />
        <resource-file src="google-services.json" target="google-services.json" />
        <resource-file src="www/res/icon/android/drawable/icon.png" target="www/res/drawable/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-ldpi/icon.png" target="www/res/drawable-ldpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-mdpi/icon.png" target="www/res/drawable-mdpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-hdpi/icon.png" target="www/res/drawable-hdpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-xhdpi/icon.png" target="www/res/drawable-xhdpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-xxhdpi/icon.png" target="www/res/drawable-xxhdpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-xxxhdpi/icon.png" target="www/res/drawable-xxxhdpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable/icon.png" target="res/drawable/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-ldpi/icon.png" target="www/res/drawable-ldpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-mdpi/icon.png" target="www/res/drawable-mdpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-hdpi/icon.png" target="www/res/drawable-hdpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-xhdpi/icon.png" target="www/res/drawable-xhdpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-xxhdpi/icon.png" target="www/res/drawable-xxhdpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-xxxhdpi/icon.png" target="www/res/drawable-xxxhdpi/myicon.png" />
    </platform>
    <platform name="ios">
        <resource-file src="GoogleService-Info.plist" />
        <icon height="57" platform="ios" src="www/res/icon/ios/icon-57.png" width="57" />
        <icon height="114" platform="ios" src="www/res/icon/ios/icon@2x.png" width="114" />
        <icon height="40" platform="ios" src="www/res/icon/ios/icon-40.png" width="40" />
        <icon height="80" platform="ios" src="www/res/icon/ios/icon-40@2x.png" width="80" />
        <icon height="50" platform="ios" src="www/res/icon/ios/icon-50.png" width="50" />
        <icon height="100" platform="ios" src="www/res/icon/ios/icon-50@2x.png" width="100" />
        <icon height="60" platform="ios" src="www/res/icon/ios/icon-60.png" width="60" />
        <icon height="120" platform="ios" src="www/res/icon/ios/icon-60@2x.png" width="120" />
        <icon height="180" platform="ios" src="www/res/icon/ios/icon-60@3x.png" width="180" />
        <icon height="72" platform="ios" src="www/res/icon/ios/icon-72.png" width="72" />
        <icon height="144" platform="ios" src="www/res/icon/ios/icon-72@2x.png" width="144" />
        <icon height="76" platform="ios" src="www/res/icon/ios/icon-76.png" width="76" />
        <icon height="152" platform="ios" src="www/res/icon/ios/icon-76@2x.png" width="152" />
        <icon height="29" platform="ios" src="www/res/icon/ios/icon-small.png" width="29" />
        <icon height="58" platform="ios" src="www/res/icon/ios/icon-small@2x.png" width="58" />
        <icon height="87" platform="ios" src="www/res/icon/ios/icon-small@3x.png" width="87" />
        <splash height="568" src="320x568.png" width="320" />
        <splash height="1136" src="640x1136.png" width="640" />
        <splash height="1334" src="750x1334.png" width="750" />
        <splash height="2208" src="1242x2208.png" width="1242" />
        <splash height="2048" src="1536x2048.png" width="1536" />
        <splash height="1024" src="768x1024.png" width="768" />
        <splash height="960" src="640x960.png" width="640" />
        <splash height="480" src="320x480.png" width="320" />
        <feature name="BarcodeScanner">
            <param name="ios-package" value="CDVBarcodeScanner" />
        </feature>
        <config-file parent="NSCameraUsageDescription" platform="ios" target="*-Info.plist">
            <string>Change reseller profile image and insert picture in receives</string>
        </config-file>
        <config-file parent="NSPhotoLibraryUsageDescription" platform="ios" target="*-Info.plist">
            <string>Change reseller profile image and insert picture in receives</string>
        </config-file>
    </platform>
    <access origin="*" />
    <allow-navigation href="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <plugin name="cordova-plugin-appinfo" spec="~2.1.2" />
    <plugin name="cordova-plugin-x-socialsharing" spec="https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin.git" />
    <plugin name="ionic-plugin-keyboard" spec="~2.2.1" />
    <plugin name="phonegap-plugin-barcodescanner" spec="https://github.com/phonegap/phonegap-plugin-barcodescanner.git">
        <param name="CAMERA_USAGE_DESCRIPTION" value="Combinar Ingredientes" />
    </plugin>
    <plugin name="cordova-plugin-facebook4" source="npm" spec="1.7.4">
        <variable name="APP_ID" value="1792703991047652" />
        <variable name="APP_NAME" value="koopcook" />
    </plugin>
    <plugin name="cordova-android-play-services-gradle-release" spec="~1.2.1">
        <variable name="PLAY_SERVICES_VERSION" value="11.+" />
    </plugin>
    <plugin name="phonegap-plugin-push" spec="~1.10.7">
        <param name="SENDER_ID" value="796999857612" />
    </plugin> 

#### Steps to Reproduce 
try compile this config xml in phonegap build

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Not try because buil not generate

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Not try because buil not generate

#### Cordova CLI version and cordova platform version
    cordova --version                                    # cli-7.1.0
    cordova platform version android                     # e.g. 6.3.0 

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # 1.10.7

#### Sample Code that illustrates the problem

    <name>Kozinhar</name>
    <description>
        Livro de Receita Digital, com um gerador de Lista de compras
        Aplicativo ideal para você que adora cozinha, o KoopCook é mais que um aplicativo é uma filosofia de que cozinhar faz bem.
        Você pode gerenciar suas receitas, gerar lista de compras e ainda colocar observações a cada preparo, tudo para que cozinha seja ainda mais gostoso.
    </description>
    <author email="programadora@agenciadream.com">
        Agencia Dream
    </author>
    <content src="index.html" />
    <preference name="phonegap-version" value="cli-7.1.0" />
    <preference name="permissions" value="none" />
    <preference name="orientation" value="portrait" />
    <preference name="webviewbounce" value="true" />
    <preference name="prerendered-icon" value="true" />
    <preference name="stay-in-webview" value="false" />
    <preference name="ios-statusbarstyle" value="black-opaque" />
    <preference name="detect-data-types" value="true" />
    <preference name="exit-on-suspend" value="false" />
    <preference name="show-splash-screen-spinner" value="true" />
    <preference name="auto-hide-splash-screen" value="true" />
    <preference name="disable-cursor" value="false" />
    <preference name="android-minSdkVersion" value="21" />
    <preference name="android-targetSdkVersion" value="21" />
    <preference name="android-installLocation" value="auto" />
    <preference name="AndroidPersistentFileLocation" value="Compatibility" />
    <plugin name="cordova-android-support-gradle-release" spec="^1.2.1">
        <variable name="ANDROID_SUPPORT_VERSION" value="21.+" />
    </plugin>
    <plugin name="cordova-plugin-camera" source="npm" spec="~2.1.1" />
    <plugin name="cordova-plugin-media-capture" source="npm" spec="~1.2.0" />
    <plugin name="cordova-plugin-device" source="npm" spec="~1.1.1" />
    <plugin name="cordova-plugin-dialogs" source="npm" spec="~1.2.0" />
    <plugin name="cordova-plugin-file" source="npm" spec="~4.1.1" />
    <plugin name="cordova-plugin-file-transfer" source="npm" spec="~1.5.0" />
    <plugin name="cordova-plugin-inappbrowser" source="npm" spec="~1.3.0" />
    <plugin name="cordova-plugin-media" source="npm" spec="~2.2.0" />
    <plugin name="cordova-plugin-network-information" source="npm" spec="~1.2.0" />
    <plugin name="cordova-plugin-splashscreen" source="npm" spec="~3.2.1" />
    <plugin name="cordova-plugin-statusbar" source="npm" spec="~2.1.2" />
    <plugin name="cordova-plugin-whitelist" source="npm" spec="~1.2.1" />
    <preference name="android-build-tool" value="gradle" />
    <icon src="icon.png" />
    <splash src="splash.png" />
    <platform name="android">
        <feature name="BarcodeScanner">
            <param name="android-package" value="com.phonegap.plugins.barcodescanner.BarcodeScanner" />
        </feature>
        <feature name="Camera">
            <param name="android-package" value="org.apache.cordova.CameraLauncher" />
        </feature>
        <splash density="ldpi" src="200x320.png" />
        <splash density="mdpi" src="320x480.png" />
        <splash density="hdpi" src="480x800.png" />
        <splash density="xhdpi" src="720x1280.png" />
        <splash density="xxhdpi" src="960x1600.png" />
        <splash density="xxxhdpi" src="1280x1920.png" />
        <icon density="ldpi" src="www/res/icon/android/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="www/res/icon/android/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="www/res/icon/android/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="www/res/icon/android/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="www/res/icon/android/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="www/res/icon/android/drawable-xxxhdpi-icon.png" />
        <icon density="ldpi" src="www/res/icon/android/drawable-ldpi/icon.png" target="www/res/drawable-ldpi/icon-small.png" />
        <icon density="mdpi" src="www/res/icon/android/drawable-mdpi/icon.png" target="www/res/drawable-mdpi/icon-small.png" />
        <icon density="hdpi" src="www/res/icon/android/drawable-hdpi/icon.png" target="www/res/drawable-hdpi/icon-small.png" />
        <icon density="xhdpi" src="www/res/icon/android/drawable-xhdpi/icon.png" target="www/res/drawable-xhdpi/icon-small.png" />
        <icon density="xxhdpi" src="www/res/icon/android/drawable-xxhdpi/icon.png" target="www/res/drawable-xxhdpi/icon-small.png" />
        <icon density="xxxhdpi" src="www/res/icon/android/drawable-xxxhdpi/icon.png" target="www/res/drawable-xxxhdpi/icon-small.png" />
        <resource-file src="google-services.json" target="google-services.json" />
        <resource-file src="www/res/icon/android/drawable/icon.png" target="www/res/drawable/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-ldpi/icon.png" target="www/res/drawable-ldpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-mdpi/icon.png" target="www/res/drawable-mdpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-hdpi/icon.png" target="www/res/drawable-hdpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-xhdpi/icon.png" target="www/res/drawable-xhdpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-xxhdpi/icon.png" target="www/res/drawable-xxhdpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-xxxhdpi/icon.png" target="www/res/drawable-xxxhdpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable/icon.png" target="res/drawable/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-ldpi/icon.png" target="www/res/drawable-ldpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-mdpi/icon.png" target="www/res/drawable-mdpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-hdpi/icon.png" target="www/res/drawable-hdpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-xhdpi/icon.png" target="www/res/drawable-xhdpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-xxhdpi/icon.png" target="www/res/drawable-xxhdpi/myicon.png" />
        <resource-file src="www/res/icon/android/drawable-xxxhdpi/icon.png" target="www/res/drawable-xxxhdpi/myicon.png" />
    </platform>
    <platform name="ios">
        <resource-file src="GoogleService-Info.plist" />
        <icon height="57" platform="ios" src="www/res/icon/ios/icon-57.png" width="57" />
        <icon height="114" platform="ios" src="www/res/icon/ios/icon@2x.png" width="114" />
        <icon height="40" platform="ios" src="www/res/icon/ios/icon-40.png" width="40" />
        <icon height="80" platform="ios" src="www/res/icon/ios/icon-40@2x.png" width="80" />
        <icon height="50" platform="ios" src="www/res/icon/ios/icon-50.png" width="50" />
        <icon height="100" platform="ios" src="www/res/icon/ios/icon-50@2x.png" width="100" />
        <icon height="60" platform="ios" src="www/res/icon/ios/icon-60.png" width="60" />
        <icon height="120" platform="ios" src="www/res/icon/ios/icon-60@2x.png" width="120" />
        <icon height="180" platform="ios" src="www/res/icon/ios/icon-60@3x.png" width="180" />
        <icon height="72" platform="ios" src="www/res/icon/ios/icon-72.png" width="72" />
        <icon height="144" platform="ios" src="www/res/icon/ios/icon-72@2x.png" width="144" />
        <icon height="76" platform="ios" src="www/res/icon/ios/icon-76.png" width="76" />
        <icon height="152" platform="ios" src="www/res/icon/ios/icon-76@2x.png" width="152" />
        <icon height="29" platform="ios" src="www/res/icon/ios/icon-small.png" width="29" />
        <icon height="58" platform="ios" src="www/res/icon/ios/icon-small@2x.png" width="58" />
        <icon height="87" platform="ios" src="www/res/icon/ios/icon-small@3x.png" width="87" />
        <splash height="568" src="320x568.png" width="320" />
        <splash height="1136" src="640x1136.png" width="640" />
        <splash height="1334" src="750x1334.png" width="750" />
        <splash height="2208" src="1242x2208.png" width="1242" />
        <splash height="2048" src="1536x2048.png" width="1536" />
        <splash height="1024" src="768x1024.png" width="768" />
        <splash height="960" src="640x960.png" width="640" />
        <splash height="480" src="320x480.png" width="320" />
        <feature name="BarcodeScanner">
            <param name="ios-package" value="CDVBarcodeScanner" />
        </feature>
        <config-file parent="NSCameraUsageDescription" platform="ios" target="*-Info.plist">
            <string>Change reseller profile image and insert picture in receives</string>
        </config-file>
        <config-file parent="NSPhotoLibraryUsageDescription" platform="ios" target="*-Info.plist">
            <string>Change reseller profile image and insert picture in receives</string>
        </config-file>
    </platform>
    <access origin="*" />
    <allow-navigation href="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <plugin name="cordova-plugin-appinfo" spec="~2.1.2" />
    <plugin name="cordova-plugin-x-socialsharing" spec="https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin.git" />
    <plugin name="ionic-plugin-keyboard" spec="~2.2.1" />
    <plugin name="phonegap-plugin-barcodescanner" spec="https://github.com/phonegap/phonegap-plugin-barcodescanner.git">
        <param name="CAMERA_USAGE_DESCRIPTION" value="Combinar Ingredientes" />
    </plugin>
    <plugin name="cordova-plugin-facebook4" source="npm" spec="1.7.4">
        <variable name="APP_ID" value="1792703991047652" />
        <variable name="APP_NAME" value="koopcook" />
    </plugin>
    <plugin name="cordova-android-play-services-gradle-release" spec="~1.2.1">
        <variable name="PLAY_SERVICES_VERSION" value="11.+" />
    </plugin>
    <plugin name="phonegap-plugin-push" spec="~1.10.7">
        <param name="SENDER_ID" value="796999857612" />
    </plugin> 

#### Logs taken while reproducing problem

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> Error: more than one library with package name 'com.google.android.gms.license'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.169 secs
Error: /gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> Error: more than one library with package name 'com.google.android.gms.license'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by macdonst** [comment]
@lalacontrin the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

Please include an app id of an app that can replicate this issue.

**Comment by lalacontrin** [comment]
I try but don't have answer. and the problem is wich plugin, because I comment the 'phonegap-plugin-push' and build work, I uncomented and stop work again

**Comment by lalacontrin** [comment]
I solved my problem..

**Comment by Hissvard** [comment]
How did you solve it?
