### ISSUE TITLE
gcm_defaultSenderId resource not found

### ISSUE THREAD

**Issue by etyp** [phonegap/phonegap-plugin-push#2295]
### Expected Behaviour
When adding `google-services.json` to my `config.xml`, including it in my project directory, and calling `PushNotification.init({...})`, I would expect it to successfully register.

### Actual Behaviour
Calling `PushNotification.init({...})` throws exception `Resources NotFoundException String resource ID #0x0`.

After stepping through in Android Studio I'm finding that calling `getStringResourceByName` for `gcm_defaultSenderId` results in the resource not being found. I figured that moving to FCM would mean not needing any GCM resources?

How can I either make sure this gets set or skip it?

#### Steps to Reproduce 
1. Create new cordova project
2. Add plugins at the following versions:
```
cordova-plugin-console@1.1.0
cordova-plugin-device@2.0.1
cordova-plugin-googleplus@5.2.2
cordova-plugin-meteor-webapp@1.6.0
phonegap-plugin-push@2.1.3
```
3. Configure `phonegap-plugin-push` to use `"SENDER_ID": "1:123456789123:android:ABCDEFGHIZJKLMNOP"` (replaced with actual id from my Firebase project)
4. Manually override the generated `project.properties` file to avoid build issue:
```
target=android-26
android.library.reference.1=CordovaLib
cordova.gradle.include.1=cordova-plugin-meteor-webapp/hive-build-extras.gradle
cordova.system.library.1=com.squareup.okhttp3:okhttp:3.9.1
cordova.system.library.2=com.android.support:support-v13:27.+
cordova.system.library.3=me.leolin:ShortcutBadger:1.1.17@aar
cordova.system.library.4=com.google.firebase:firebase-messaging:11.8.0
cordova.gradle.include.2=phonegap-plugin-push/hive-push.gradle
cordova.system.library.5=com.google.android.gms:play-services-auth:11.8.0
cordova.system.library.6=com.google.android.gms:play-services-identity:11.8.0
```
5. Add `google-services.json` file (downloaded from [Firebase console for my app](https://console.firebase.google.com/u/0/project/SOMEAPP/settings/) to `/platforms/android`
6. Include resource tag to `config.xml` pointing to the `google-services.json` file:
```
<platform name="android">
  <resource-file src="google-services.json" target="google-services.json" />
</platform>
```
7. Build app, run function to call:
```
PushNotification.init({
  android: {
    sound: true,
    vibrate: true,
  },
});
```

Will throw a resource not found exception.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8.1.0
Play Services completely up to date

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Google Pixel 1

#### Cordova CLI version and cordova platform version

    cordova --version  = 8.0.0
    cordova platform version android   = 6.4.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push = 2.1.3

#### Logs taken while reproducing problem
From logcat:
```
04-01 14:47:58.845  9014  9219 E Push_Plugin: execute: Got Resources NotFoundException String resource ID #0x0
04-01 14:47:58.847  9014  9219 D Push_Plugin: no icon option
04-01 14:47:58.848  9014  9219 D Push_Plugin: no iconColor option
04-01 14:47:58.874  9014  9014 D SystemWebChromeClient: http://localhost:12432/app/app.js?hash=d02fa7985ced228043756d6a3361ee6e69f4e72a: Line 107 : Error: String resource ID #0x0
04-01 14:47:58.874  9014  9014 I chromium: [INFO:CONSOLE(107)] "Error: String resource ID #0x0", source: http://localhost:12432/app/app.js?hash=d02fa7985ced228043756d6a3361ee6e69f4e72a (107)
```

#### Notes
Because we use Meteor, we're unable to easily update to the latest version of Cordova Android - so for now the latest version we can use in the 2.x stream is `2.1.3`.

I can provide exact steps to reproduce the issue using Meteor - or even push my sample app to Github to test against. Let me know if that would help.

**Comment by macdonst** [comment]
@etyp during the build do you see the GoogleServicesPlugin execute? It should pick up the correct values from google-services.json and add them to your project. If you are not seeing it in your build logs check by doing:

```
grep -l -R gcm_defaultSenderId platforms/android/
```

it should list the files that property shows up in. Pay particular attention to `values.xml`.

**Comment by etyp** [comment]
@macdonst Nope, not seeing it in `values.xml`. Here's the output of the grep:

```
platforms/android//build/intermediates/classes/debug/com/adobe/phonegap/push/PushConstants.class
platforms/android//build/intermediates/incremental-verifier/debug/com/adobe/phonegap/push/PushConstants.class
platforms/android//build/intermediates/transforms/dexBuilder/debug/141/com/adobe/phonegap/push/PushConstants.dex
platforms/android//build/intermediates/transforms/dexMerger/debug/1/classes.dex
platforms/android//build/intermediates/transforms/dexMerger/debug/11/classes.dex
platforms/android//build/intermediates/transforms/externalLibsDexMerger/debug/0/classes.dex
platforms/android//build/intermediates/transforms/instantRun/debug/0/com/adobe/phonegap/push/PushConstants.class
platforms/android//build/intermediates/transforms/instantRunSlicer/debug/0/com/adobe/phonegap/push/PushConstants.class
platforms/android//src/com/adobe/phonegap/push/PushConstants.java
```

**Comment by etyp** [comment]
@macdonst So I managed to get Firebase to initialize successfully (sigh...finally), but it was by following the instructions for setting up [Google Play Services](https://developers.google.com/android/guides/setup), then setting up [Firebase](https://firebase.google.com/docs/android/setup) all by modifying by build.gradle (android module) through Android Studio.

I by no means know what I'm doing when it comes to Android development, so I'm wondering how (if at all possible) I might be able to achieve the same thing using just Cordova.

Right now, I've done the following in `build.gradle`:

1. Added classpaths for `com.android.tools.build:gradle:3.1.0` and `com.google.gms:google-services:3.2.0` at the top of `build.gradle`:

```
apply plugin: 'com.android.application'

buildscript {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
        google()
    }

    // Switch the Android Gradle plugin version requirement depending on the
    // installed version of Gradle. This dependency is documented at
    // http://tools.android.com/tech-docs/new-build-system/version-compatibility
    // and https://issues.apache.org/jira/browse/CB-8143
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'
        classpath 'com.google.gms:google-services:3.2.0'
    }
}
```

2. Forced the Graddle wrapper to version `4.4.0`:

```
task wrapper(type: Wrapper) {
    gradleVersion = '4.4.0'
}
```

3. Manually updated my dependencies to the following:

```
dependencies {
    implementation fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    implementation(project(path: "CordovaLib"))
    compile "com.squareup.okhttp3:okhttp:3.9.1"
    compile "com.android.support:support-v13:27.+"
    implementation "com.google.android.gms:play-services-auth:12.0.1"
    implementation "com.google.android.gms:play-services-identity:12.0.1"
    compile "me.leolin:ShortcutBadger:1.1.17@aar"
    compile "com.google.firebase:firebase-messaging:12.0.1"
    // SUB-PROJECT DEPENDENCIES END
}
```

4. Called apply plugin at the bottom of the `build.gradle`:

```
apply plugin: 'com.google.gms.google-services'
```

......

Any idea why this would work but my previous setup would not?

**Comment by macdonst** [comment]
@etyp not sure, the push.gradle file in this repo which is included as part of the plugin should setup what's needed for the Google Play Services plugin. I don't build with with Meteor so I'm not sure if that's causing an issue.

**Comment by etyp** [comment]
@macdonst got it, thanks for the nudge towards making sure `values.xml` is populated.

Meteor builds cordova in a pretty rigid way (for a reason, I supposed) and I found that the steps above are good enough for now since we don't build to Play Store too regularly. Going to close this out.

If anybody else using Meteor gets stuck with this (common issue because of a required [Google+ plugin](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/) when using Meteor Google Accounts package), feel free to ping me and I can share steps to resolve.

Also https://github.com/phonegap/phonegap-plugin-push/issues/1800 seems to be same issue. Will share documented steps to resolve soon. Closing this out in the meantime.

**Comment by macdonst** [comment]
@etyp feel free to send a PR to docs if you think it'll help other people.

**Comment by etyp** [comment]
@macdonst will do - I'll do best endeavors and hopefully those with more experience setting up `build.gradle` files can fill in the gaps where I'm falling short

**Comment by Sewdn** [comment]
@etyp could you please look into the problem described here:
https://github.com/raix/push/issues/334

This is directly related to this issue and since you have been able to work around, I'm very interested in how you did this. I suppose your approach involves customizing the `config.xml` and adding `possible build-extras.gradle` files declared by cordova plugins after the meteor build process?

**Comment by etyp** [comment]
@sewdn yeah I can share my markdown file instructions there. There's a recent PR merged by mdg which simplifies the steps a bit as well.

**Comment by Sewdn** [comment]
@etyp you mean the ability to declare resources for cordova builds from within mobile-config.js?
https://github.com/meteor/meteor/pull/9748

**Comment by etyp** [comment]
@sewdn yes sir, that's the one
