### ISSUE TITLE
Typescript types are out of date

### ISSUE THREAD

**Issue by oliverjanik** [phonegap/phonegap-plugin-push#2297]
Types here: 

https://github.com/phonegap/phonegap-plugin-push/blob/master/types/index.d.ts

require SenderID which does not exist according to the docs here:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md

**Comment by fredgalvao** [comment]
@oliverjanik Thanks for the detail.
This is a duplicate of https://github.com/phonegap/phonegap-plugin-push/issues/1536, will close this and focus on that one.
