### ISSUE TITLE
App crashes when trying to register push notifications - Plugin version 1.10.5

### ISSUE THREAD

**Issue by emyymk** [phonegap/phonegap-plugin-push#2298]
### Expected Behaviour

App doesn't crash, device is registered for push notifications

### Actual Behaviour

App crashes.

### Reproduce Scenario (including but not limited to)

The app crashes when trying to register the device.

#### Steps to Reproduce 

Just try to register push notifications. 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 7.1.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Samsung S8

#### Cordova CLI version and cordova platform version

Cordova CLI Version 7.1.0
Cordova Platform Android Version 6.4.0

#### Plugin version

1.10.5

#### Sample Push Data Payload

No payload required

#### Sample Code that illustrates the problem

var push_app = {
    initialize: function() {
        // this.bindEvents();
    },
    // Bind Event Listeners
    // Bind any events that are required on startup. Common events are:
    // 'load', 'deviceready', 'offline', and 'online'.
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    // deviceready Event Handler
    // The scope of 'this' is the event. In order to call the 'receivedEvent'
    // function, we must explicitly call 'app.receivedEvent(...);'
    onDeviceReady: function() {
        console.log('Received Device Ready Event');
        console.log('calling setup push');
    },
    setupPush: function() {
        console.log('calling push init');
        var push = PushNotification.init({
            "android": {
                "senderID": "XXXXXXXXX",
                "sound": true,
                "clearBadge": true
            },
            "browser": {
                "pushServiceURL": 'http://push.api.phonegap.com/v1/push'
            },
            "ios": {
                "alert": true,
                "sound": true,
                "vibration": true,
                "badge": true,
                "clearBadge": true
            },
            "windows": {}
        });
        console.log('after init');

        .....

#### Logs taken while reproducing problem

04-03 22:19:54.689 14599 14905 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-3
04-03 22:19:54.689 14599 14905 E AndroidRuntime: java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzv; or its super classes (declaration of 'com.google.android.gms.common.util.zzv' appears in /data/app/xxxxxx/base.apk)

#### grade.build

dependencies {
    implementation fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    implementation(project(path: "CordovaLib"))
    compile "com.google.android.gms:play-services-analytics:+"
    compile "com.android.support:support-v13:23+"
    compile "com.google.android.gms:play-services-gcm:11+"
    compile "me.leolin:ShortcutBadger:1.1.14@aar"
    compile "com.squareup.okhttp3:okhttp:3+"
    // SUB-PROJECT DEPENDENCIES END
}

Please let me know if you need more information. Thanks!

**Comment by Spillo17** [comment]
Take a look to this: https://github.com/phonegap/phonegap-plugin-push/issues/2267

**Comment by emyymk** [comment]
Thank you, Spillo17. 

Resolved with macdonst sugestion. 

In my config.xml, I set:
 
>     <plugin name="phonegap-plugin-push">
>        <variable name="ANDROID_SUPPORT_V13_VERSION" value="27.+" />
>        <variable name="FCM_VERSION" value="11.6.2" />
>     </plugin>
