### ISSUE TITLE
ios not receiving push notification 

### ISSUE THREAD

**Issue by bhumin3i** [phonegap/phonegap-plugin-push#2300]
push notification register successfully but not coming any push notification on my iOS device but android working charm 

#### Cordova CLI version and cordova platform version

    cordova  8.0.0
    cordova platform  iOS: 4.5.4

#### Plugin version

 phonegap-plugin-push 2.2.2 "PushPlugin"

#### Sample Push Data Payload

 data" : {
                     "title": "Test Notification",
                     "body": notificationData.message
                     }
         };

#### Sample Code that illustrates the problem

    pushObject.on('notification').subscribe((notification: any) => {
      console.log('on notification', notification);

    });
> pod install

```
Using FirebaseAnalytics (4.1.0)
Using FirebaseCore (4.0.17)
Using FirebaseInstanceID (2.0.9)
Using FirebaseMessaging (2.0.8)
Using GoogleToolboxForMac (2.1.3)
Using Protobuf (3.5.0)
Using nanopb (0.3.8)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 7 total pods installed.
```

xcode  capabilities setting look like 

![screen shot 2018-04-05 at 7 56 39 pm](https://user-images.githubusercontent.com/25737987/38372094-a83a01a2-390b-11e8-9923-49726874e9a1.png)

![screen shot 2018-04-05 at 7 58 09 pm](https://user-images.githubusercontent.com/25737987/38372125-b8c1a548-390b-11e8-81f8-255032afacc2.png)

**Comment by bhandaribhumin** [comment]
@macdonst I’m using APNS

**Comment by bhandaribhumin** [comment]
@macdonst Android working..... before update v2.2.2 nothing change in payload 
V2.1.3 is working fine in both platforms ios and android

**Comment by macdonst** [comment]
@bhumin3i if you are using APNS on iOS then the push format should be:

```
{
	"aps": {
		"alert": "Test sound",
		"sound": "sub.caf"
	}
}
```

**Comment by bhandaribhumin** [comment]
@macdonst sorry I forgot to add push option object but it’s looks like 

{
	android: {
	},
    browser: {
        pushServiceURL: 'http://push.api.phonegap.com/v1/push'
    },
	ios: {
		alert: "true",
		badge: "true",
		sound: "true"
	},
	windows: {}
}

**Comment by bhumin3i** [comment]
@macdonst I'm using 

"aps": {
                   "alert": "$(message)",
                   "badge": +1,
                   "content-available": "1",
                   "title": "$(title)",
                   "message": "$(message)",
                   "meetingName": "$(meetingname)",
                   "meetingRoom": "$(meetingroom)",
                   "organizer": "$(orgaizername)",
                   "startdateTime": "$(startdateTime)",
                   "enddateTime": "$(enddateTime)"
               }

but still same did not receive notification

**Comment by macdonst** [comment]
@bhumin3i can you get the logs from Xcode?

**Comment by bhumin3i** [comment]
I couldn't find any logs in Xcode and also when I try to send push notification through my admin panel  
my iOS device is getting de-register automatically.

**Comment by macdonst** [comment]
@bhumin3i at this point any logs from Xcode would help.

**Comment by macdonst** [comment]
@bhumin3i generally when you aren't receiving notifications on iOS it ends up being a mis-match between development and production certs.
