### ISSUE TITLE
Question: how to not use FCM for iOS and keep using APNS?

### ISSUE THREAD

**Issue by MarcoEidinger** [phonegap/phonegap-plugin-push#2302]
Is it possible with latest plugin version (v2.2.2) not to use FCM for iOS and keep using APNS? If yes, how to do so? If no, which plugin version is recommended to use? Also, would CocoaPods then still be required? Seems CocoaPods is needed just for CocoaPods installation of the Firebase Cloud Messaging library.

**Comment by jcesarmobile** [comment]
If you don't add the FCM .plist file it will use APNs

CocoaPods is still required because it will install FCM code despite it won't use it, we can't make the install a conditional thing as Cordova install the plugin as a whole.
