### ISSUE TITLE
[Dude] Wake up app on Notification

### ISSUE THREAD

**Issue by marcoas** [phonegap/phonegap-plugin-push#2303]
(Translated by Google)

[For Android only]

When the APP is in background, and a notification is received ...
Can it be achieved, that the APP wake up and be visible to the user?

Without showing the notification in the bar.

Thanks

**Comment by marcoas** [comment]
In the meantime...

I leave a plugin that, at least, helped me

https://github.com/YimasoftLiuGuanJun/cordova-bring-to-front

**Comment by macdonst** [comment]
@marcoas no, it is not possible with this plugin only. Also, it's not recommended behaviour by Apple or Google so I would suggest you don't do it.
