### ISSUE TITLE
Android Crashes on Receiving Notification

### ISSUE THREAD

**Issue by Unicorn808** [phonegap/phonegap-plugin-push#2304]
### Expected Behaviour
The app displays a notification
### Actual Behaviour
The app receives a notification and crashes immediately after.
### Reproduce Scenario (including but not limited to)
Using cordova android and the googleplus plugin the app crashes when I run it, as when the device is ready, I send the registration id to my backend and my backend sends a notification to the app.
#### Steps to Reproduce 
1. Install cordova-plugin-googleplus
2. Install phonegap-plugin-push
3. Install cordova android@7.1.0
4. Add code to handle incoming notifications
5. Send a notification.
#### Platform and Version
Android 7.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Pixel 2 Emulator and The Essential phone. 
#### Cordova CLI version and cordova platform version

    cordova --version                                    # 8.00
    cordova platform version android                     # 7.1.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # 2.2.2

#### Sample Push Data Payload
    const message = new gcm.Message();
	message.addData('title', 'Hello, World');
	message.addData('body', 'This is a notification that will be displayed ASAP.');
#### Sample Code that illustrates the problem
    app.push.on('notification', function(data) {
			console.log('notification event');
			//alert('Notification!' + data.title + data.message)
		});
#### Logs taken while reproducing problem
There are no logs in console, and if there are more I need, please tell me how to get them.

I have also upgraded gradle to 4.4 and the Android Gradle Plugin as suggested in #2129 
My google play version is 12.2.21

Let me know if there is anything else I need!

**Comment by fredgalvao** [comment]
Without the logs, I'm afraid it'll be very hard to figure anything out.

**Comment by Unicorn808** [comment]
@fredgalvao hence my question on how to get them. If you could give me a command or guide or something that would be great.

**Comment by macdonst** [comment]
@Unicorn808 well if you run `adb logcat` and reproduce the problem it should point to what is crashing. 

I did a quick look at the Google Plus plugin from @EddyVerbruggen and it is using Play Services 11.8.0 but the push plugin 2.2.2 is using 11.6.2. What I would try first is go to your config.xml and look for where the FCM_VERSION is set and change it to 11.8.0, re-compile, deploy and test. If you can still crash the app we'll need the logs.

**Comment by Unicorn808** [comment]
I changed the FMC_VERSION and it still crashed when running, so here are the logs:

Not sure where to specifically copy/paste, so I just pasted everything left in my terminal: 

https://gist.github.com/Unicorn808/e5b84893b4c4849d9eaefe637eae000a

**Comment by macdonst** [comment]
@Unicorn808 I'm seeing:

```
04-06 08:56:33.247 14992 15097 E AndroidRuntime: java.lang.IncompatibleClassChangeError: Superclass com.google.android.gms.internal.zzbej of com.google.firebase.messaging.RemoteMessage is declared final (declaration of 'com.google.firebase.messaging.RemoteMessage' appears in /data/app/com.swoopit.android-o6kOQHpbZeT-k91QNIreKw==/base.apk:classes2.dex)
```

which is usually a mis-match of play services versions. Can you post the dependencies section of platform/android/app/build.gradle? It should look something like this:

```
dependencies {
    implementation fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    implementation(project(path: ":CordovaLib"))
    compile "com.android.support:support-v13:26.+"
    compile "me.leolin:ShortcutBadger:1.1.17@aar"
    compile "com.google.firebase:firebase-messaging:11.6.2"
    // SUB-PROJECT DEPENDENCIES END
}
```

**Comment by Unicorn808** [comment]
Here we are: 

    dependencies {
    implementation fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    implementation(project(path: ":CordovaLib"))
    compile "com.google.android.gms:play-services-auth:11.8.0"
    compile "com.google.android.gms:play-services-identity:11.8.0"
    compile "com.android.support:support-v13:27.+"
    compile "me.leolin:ShortcutBadger:1.1.17@aar"
    compile "com.google.firebase:firebase-messaging:11.6.2"
     // SUB-PROJECT DEPENDENCIES END
    }

**Comment by Unicorn808** [comment]
All right, that fixed the problem! But now the code here isn't being run.

    app.push.on('notification', function(data) {
			console.log('notification event');
			alert('Notification!' + data.title + data.message)
		});

According to my backend it successfully sent a notification, though none showed up.

**Comment by macdonst** [comment]
@Unicorn808 the notification event handler isn't called until you click on the notification or if you send the content-available setting as part of your push payload. Also, I really recommend not testing push in the emulator. It really is something that should be done on a device.
