### ISSUE TITLE
I doesn't get push notification

### ISSUE THREAD

**Issue by developuser** [phonegap/phonegap-plugin-push#2309]
### Expected Behaviour
i want to get push notification in notification bar instead of alert.by using the following code i just receive the notification only as a alert. but i want to display it as a notification in both foreground and background
### Actual Behaviour
the push notification are shown only in
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
android 7.0
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

#### Sample Code that illustrates the problem
angular.module('starter', ['ionic', 'starter.controllers','ngCordova'])

.run(function($ionicPlatform,$rootScope,$cordovaPushV5,$http,$cordovaStatusbar) {
  
  $ionicPlatform.ready(function() {

    // register push notification and get local push token
    localStorage.myPush = ''; // I use a localStorage variable to persist the token
    $cordovaPushV5.initialize(  // important to initialize with the multidevice structure !!
        {
            android: {
                senderID: "618235948846"
            },
            ios: {
                alert: 'true',
                badge: true,
                sound: 'false',
                clearBadge: true
            },
            windows: {}
        }
    ).then(function (result) {
        $cordovaPushV5.onNotification();
        $cordovaPushV5.onError();
        $cordovaPushV5.register().then(function (resultreg) {
            localStorage.myPush = resultreg;
            console.log(localStorage.myPush);
            alert(localStorage.myPush);
            $http({
            method : "GET",
             url : "http://vtst.cloudapp.net/balaji_test/cp/gcm/register_user.php?name=test&email=test@mail.com&regId="+localStorage.myPush
            }).then(function mySucces(response) {}, function myError(response) {});
            // SEND THE TOKEN TO THE SERVER, best associated with your device id and user
        }, function (err) {
            // handle error
        });
    });
});

  $rootScope.$on('$cordovaPushV5:notificationReceived', function(event, data) {  // use two variables here, event and data !!!
    if (data.additionalData.foreground === false) {
      
      console.log(data.message);
      navigator.notification.alert(data.message);
        // do something if the app is in foreground while receiving to push - handle in app push handling
    } else {
      //alert(data.additionalData.price);
        console.log(data.message);
      navigator.notification.alert(data.message);
       // handle push messages while app is in background or not started
    }
    if (Device.isOniOS()) {
        if (data.additionalData.badge) {
            $cordovaPushV5.setBadgeNumber(NewNumber).then(function (result) {
                // OK
            }, function (err) {
                // handle error
            });
        }
    }

    $cordovaPushV5.finish().then(function (result) {
        // OK finished - works only with the dev-next version of pushV5.js in ngCordova as of February 8, 2016
    }, function (err) {
        // handle error
    });
});

$rootScope.$on('$cordovaPushV5:errorOccurred', function(event, error) {
    // handle error
});
})

**Comment by macdonst** [comment]
@developuser then you need to set `forceShow` to `true` in the init.

```
$cordovaPushV5.initialize(  // important to initialize with the multidevice structure !!
    {
        android: {
            senderID: "618235948846",
            forceShow: true
        },
        ios: {
            alert: 'true',
            badge: true,
            sound: 'false',
            clearBadge: true
        },
        windows: {}
    }
)
```

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#android
