### ISSUE TITLE
 error: cannot find symbol String token = InstanceID.getInstance(getApplicationContext()).getToken(senderID, GCM);

### ISSUE THREAD

**Issue by Kunze** [phonegap/phonegap-plugin-push#231]
After install plugin my build does not work anymore:

http://postimg.org/image/j6k9a46td/

How can I solve this?

**Comment by macdonst** [comment]
@Kunze The README talks about how to setup your system to build on Android.

https://github.com/phonegap/phonegap-plugin-push#compiling

**Comment by Kunze** [comment]
Thanks for you reply.
Everything is according to requirements.
