### ISSUE TITLE
Phonegap Build Error (Online Service) - Could not find any version that matches com.google.android.gms:play-services-gcm:12+

### ISSUE THREAD

**Issue by BhavikaP** [phonegap/phonegap-plugin-push#2312]
### Build Error

BUILD FAILED

Total time: 1.288 secs
Command finished with error code 1: /project/gradlew cdvBuildDebug,-b,/project/build.gradle,-Dorg.gradle.daemon=true,-Dorg.gradle.jvmargs=-Xmx2048m,-Pandroid.useDeprecatedNdk=true
Error: /project/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find any version that matches com.google.android.gms:play-services-gcm:12+.
     Versions that do not match:
         11.0.4
         11.0.2
         11.0.1
         11.0.0
         10.2.6
         + 18 more
     Required by:
         project :

### config.xml
```
<preference name="phonegap-version" value="cli-6.5.0" /> 
<plugin name="phonegap-plugin-push" spec="~1.10.5">
	<param name="SENDER_ID" value="123456789" />
</plugin>
<plugin name="cordova-plugin-google-analytics" source="npm"> 
	<param name="ios-package" value="UniversalAnalyticsPlugin" />
	<param name="android-package" value="com.danielcwilson.plugins.analytics.UniversalAnalyticsPlugin" />
</plugin>
```

### Comment
Is there a fix for the above?
Thanks

**Comment by macdonst** [comment]
@BhavikaP the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.

**Comment by BhavikaP** [comment]
Thanks  @macdonst 
Is this a PG Build issue? Because I was able to successfully compile an App a week ago.
Would you know if they are aware of it and there is a solution to fix it.

**Comment by BhavikaP** [comment]
Was able to resolve the issue by using an older version of the plugin.
