### ISSUE TITLE
GoogleCloudMessaging has been deprecated in favor of FirebaseMessaging

### ISSUE THREAD

**Issue by Piero87** [phonegap/phonegap-plugin-push#2313]
Hi,
I have:

Cordova Version 6.5.0
Cordova iOS Platform Version 4.5.1

When i add this:
cordova plugin add phonegap-plugin-push@1.9.0

I get this message:

Installing "phonegap-plugin-push" for ios

[!] GoogleCloudMessaging has been deprecated in favor of FirebaseMessaging

Anyone knows how I can fix it?

**Comment by jcesarmobile** [comment]
That seems just a warning, Google has deprecated GCM, you have one year to move to FCM.
The v2.x version of the plugin uses FCM, so you just have to update your server to use FCM and then update the plugin to latest v2.

**Comment by Piero87** [comment]
@jcesarmobile thanks for you answer, there is a way to hide warning?

**Comment by jcesarmobile** [comment]
you can close your eyes when the warning appears or you can use v2.x version of the plugin
