### ISSUE TITLE
Not receiving FCM Push Notification on Android Oreo 8+

### ISSUE THREAD

**Issue by Upperfoot** [phonegap/phonegap-plugin-push#2315]
### Expected Behaviour

App correctly receives notification when omitting the 'notification' object from the Server Request to create an FCM push notification

### Actual Behaviour

Omitting the 'notification' object causes the app to not receive the FCM push notification.

But if I include the notification object in the FCM Push request it is received.

### Reproduce Scenario (including but not limited to)

Omit the notification object from the request to the FCM Push endpoint. On devices that are >= 8.0 the push notification will not be received, but devices that are < 8.0 receive the notification.

Include the notification object to the FCM Push endpoint. And all devices receive it.

#### Steps to Reproduce 

See above.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 8.0
Android 8.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Samsung S9
Samsung S8 Plus

#### Cordova CLI version and cordova platform version

    cordova --version (7.1.0)
    cordova platform version android (6.3.0)

#### Plugin version

    cordova plugin version (2.2.2)

#### Sample Push Data Payload

With notification omitted from request

`{"registration_ids":["--OMITTED--"],"data":{"soundname":"beep","title":"test","body":"test","type":"command_notification","uuid":"-OMITTED--"},"time_to_live":120}`

With notification included on request

`{"registration_ids":["--OMITTED--"],"notification":{"title":"test","body":"test","sound":"beep.wav"},"data":{"soundname":"beep","title":"test","body":"test","type":"command_notification","uuid":"--OMITTED--"},"time_to_live":120}`

#### Sample Code that illustrates the problem

N/A

#### Logs taken while reproducing problem

N/A

**Comment by macdonst** [comment]
@Upperfoot are you sure you are using cordova-android 6.3.0? Cause the plugin v2.2.2 won't even install on that version of cordova-android. You'd need cordova-android 7.1.0 or greater for v2.2.2.

For testing can you send this payload:

```
{"registration_ids":["--OMITTED--"],
"data":{"soundname":"beep","title":"test","body":"test","type":"command_notification","uuid":"--OMITTED--"},"time_to_live":120}
```

while running `adb logcat | grep Push` to capture any errors.

**Comment by Upperfoot** [comment]
We are stuck on 6.3.0 at the moment because some plugins that we require for our app have not been made compatible as of yet (BlinkID being one of them).

We have cherry-picked the commit https://github.com/phonegap/phonegap-plugin-push/commit/eaec03b3978fc029f95af7e221654a30a60802d8 and that fixed the problem!

Happy Friday the 13th!

**Comment by macdonst** [comment]
@Upperfoot looks like BlinkID was updated to support cordova-android 7+ about 4 months ago.
