### ISSUE TITLE
Plugins conflicts with older cordova-android

### ISSUE THREAD

**Issue by adappter** [phonegap/phonegap-plugin-push#2316]
### Expected Behaviour
Compile Android Project without error

### Actual Behaviour
I get an error where on cordova platform add android the plugin is skipping
I need the Version 6.4.0 because other plugins like cordova-plugin-device are not up to date and can't find the AndroidManifest.xml because in the new cordova-android version the manifest is at another directory.

#### Steps to Reproduce 
build with cordova android version 6.4.0
add the plugin and try to build or add the platform

#### Cordova CLI version and cordova platform version

    cordova                           8.0.0
    cordova-android        6.4.0

#### Plugin version
 2.2.2

#### Logs taken while reproducing problem
Plugin doesn't support this project's cordova-android version. cordova-android: 6.4.0, failed version requirement: >=7.1.0
Skipping 'phonegap-plugin-push' for android

**Comment by jcesarmobile** [comment]
Sorry, we need 7.1.0 because of other fixes, so if you want to use a previous version you'll have to backport the changes you need.

**Comment by macdonst** [comment]
@adappter I'd rather you tell me what plugins need to get updated. This plugin is relying on newer features of cordova-android so it the latest will keep it's requirement of >=7.1.0.

**Comment by AlphaCreative** [comment]
What version of this plugin introduced the dependency on cordova-android 7.1.0?  The documentation still says 6.2 or greater: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md
I'm having this same problem.  I need the fix for Issue 2051, but I have other plugins that don't support cordova-android 7.x.

**Comment by jcesarmobile** [comment]
You can check that in the package.json
https://github.com/phonegap/phonegap-plugin-push/blob/master/package.json#L62

**Comment by macdonst** [comment]
@AlphaCreative thanks for the heads up, I updated the installation table.
