### ISSUE TITLE
Error lGoogleToolboxForMac

### ISSUE THREAD

**Issue by roger93** [phonegap/phonegap-plugin-push#2318]
Hello I installed the phonegap-plugin-push plugin and when I started the xcode to upload it to the store I got an error 

`ld: library not found for -lGoogleToolboxForMac
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I have read the documentation and there is a section that reports the error but it does not work for me. 

Cordova -v:  7.1.0
Cordova platform ios 4.5.4
pod --version 1.4.0

how can I fix it?

**Comment by jcesarmobile** [comment]
Make sure you are opening the .xcworkspace and not the .xcodeproj
Also, run pod install from platforms/ios

Also, when creating an issue, follow the template, and explain exactly what you did, not "I did something I saw somewhere and didn't work"

**Comment by djodjonx** [comment]
Go to build phases in your project at Link Binary with Libraries and libPods-PROJECTNAME.a and libGoogleToolboxForMac.a
