### ISSUE TITLE
Cordova-Android Version Issue

### ISSUE THREAD

**Issue by paperKeys** [phonegap/phonegap-plugin-push#2321]
I am having trouble with this plugin since the recent release. I was able to use the plugin until the android requirement changed. Now I cannot add the push plugin on a basic cordova app. I am getting a message stating the Android Manifest file cannot be found. This file location has changed in cordova-android 7.1. Suggestions?

### Expected Behaviour
phonegap-plugin-push installs to a cordova project

### Actual Behaviour
phonegap-plugin-push fails to install to a cordova Android project, but installs to cordova iOS project

### Reproduce Scenario (including but not limited to)
Add cordova version 7 or higher
Add android version 7.1 as required by phonegap-plugin-push version 2.2.2
Install fails

#### Steps to Reproduce 
Add cordova version 7 or higher
Add android version 7.1 as required by phonegap-plugin-push version 2.2.2
Attempt to install new phonegap version
Install fails

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Cordova 7/8
Cordova-Android 7.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
N/A

#### Cordova CLI version and cordova platform version
Cordova 7/8
Cordova-Android 7.1

#### Plugin version
latest, 2.2.2

#### Sample Push Data Payload
N/A

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
Failed to install 'phonegap-plugin-push': Error: ENOENT: no such file or directory, open 'C:\Development\platforms\android\AndroidManifest.xml'

Thank you

**Comment by macdonst** [comment]
@paperKeys what is the exact version of cordova that you are using? Are you adding the plugin to a new app or an existing app?

**Comment by jcesarmobile** [comment]
This is part fault of cordova-android and part fault of another plugin you are using.

Is usually caused by plugins using source-file tag for images, when this happens a res folder is created in platforms/android/, and when the res folder is there, cordova-android thinks it's an eclipse project, so it search for AndroidManifest.xml in the old location, but the file is not there because it's an Android Studio project and the location changed.

**Comment by macdonst** [comment]
@jcesarmobile but maybe if we figure out the other plugin causing the problem we can send a PR to change the source-file tags to resource-file tags?

**Comment by jcesarmobile** [comment]
I think we should fix cordova-android to avoid this false positives as there is no way of being an Eclipse project, there is only Android Studio projects now. And make sure source-file tag keeps working the same way it worked in previous versions

**Comment by paperKeys** [comment]
thank you for the quick replies. this is an existing app and I had push working before this frustratingly enough.

cordova -v is 7.1.

i have the following plugins:
cordova-plugin-camera
cordova-plugin-device
cordova-plugin-file
cordova-plugin-image-picker

**Comment by paperKeys** [comment]
cordova-plugin-camera@4.0.2
cordova-plugin-device@2.0.1
cordova-plugin-file@6.0.1
cordova-plugin-image-picker@1.1.1

**Comment by paperKeys** [comment]
jcesarmobile - I think you may be on to something there. I have had reference errors where the project is searching for image files in that location you described. should I just remove the res folder?

what would be a recommended order of operations here?

**Comment by macdonst** [comment]
@paperKeys it's the `cordova-plugin-image-picker` which isn't up to date with the latest version of cordova-android.

https://github.com/wymsee/cordova-imagePicker/blob/master/plugin.xml#L86

**Comment by paperKeys** [comment]
that was absolutely the issue. i removed the image picker plugin and was able to add the push plugin without issue.

thank you and your team for designing and maintaining this plugin, and following up on support requests the way you do. I really like this plugin and chose it because of the maintenance and support you offer. your team really helped me out on this one.
