### ISSUE TITLE
localStorage registrationId is empty

### ISSUE THREAD

**Issue by DanTheMan-NL** [phonegap/phonegap-plugin-push#2323]
### Expected Behaviour
Open app, register device in firebase and show me the device id.

### Actual Behaviour
App is registrered in firebase (device is shown in firebase console) but I can't get the device id. localStorage.getItem('registrationId') is not set.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android KitKat 4.4.2 device is used to test APK.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung S4 mini

#### Cordova CLI version and cordova platform version

    cordova --version 8.0.0
    phonegap -version 8.0.0
    cordova platform version android 7.1.0

#### Plugin version

phonegap-plugin-push   2.2.2

#### Sample Code that illustrates the problem
index.js:
```
var app = {
    // Application Constructor
    initialize: function() {
        this.bindEvents();
    },
    // Bind Event Listeners
    //
    // Bind any events that are required on startup. Common events are:
    // 'load', 'deviceready', 'offline', and 'online'.
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    // deviceready Event Handler
    //
    // The scope of 'this' is the event. In order to call the 'receivedEvent'
    // function, we must explicitly call 'app.receivedEvent(...);'
    onDeviceReady: function() {
        app.receivedEvent('deviceready');
		app.setupPush();
    },
	setupPush: function() {
        console.log('calling push init');
        var push = PushNotification.init({
            "android": {
                "senderID": "XXXXX", // removed for example
				"sound": true,
                "vibration": true,
                "badge": true
            },
            "browser": {},
            "ios": {
				"senderID": "XXXXXXXX",
                "sound": true,
                "vibration": true,
                "badge": true
            },
            "windows": {}
        });
        console.log('after init');
    
        push.on('registration', function(data) {
            console.log('registration event: ' + data.registrationId);
    
            var oldRegId = localStorage.getItem('registrationId');
            if (oldRegId !== data.registrationId) {
                // Save new registration ID
                localStorage.setItem('registrationId', data.registrationId);
                // Post registrationId to your app server as the value has changed
            }
			
        });
    
        push.on('error', function(e) {
            console.log("push error = " + e.message);
        });
    
        push.on('notification', function(data) {
            console.log('notification event');
            navigator.notification.alert(
                data.message,         // message
                null,                 // callback
                data.title,           // title
                'Ok'                  // buttonName
            );
       });
    },
    // Update DOM on a Received Event
    receivedEvent: function(id) {
        var parentElement = document.getElementById(id);
        //var listeningElement = parentElement.querySelector('.listening');
        //var receivedElement = parentElement.querySelector('.received');

        //listeningElement.setAttribute('style', 'display:none;');
        //receivedElement.setAttribute('style', 'display:block;');

        console.log('Received Event: ' + id);
    }
};
```

in app:
```
$(document).ready(function() {
	
	var RegId = localStorage.getItem('registrationId');
	alert(RegId);

});
```

google-services.json is in root folder and loaded in config.xml

**Comment by macdonst** [comment]
@DanTheMan-NL without some logs or a reproduction scenario I can't really help you. My question is does the `registration` event ever get fired?

**Comment by DanTheMan-NL** [comment]
Hello Simon,

I guess so because why else would I see my phone in the firebase console? Could you please tell me where to find the logs or how to show a reproduction? I can't show you my app because it's not in production yet and after I've build my apk and run it on my device no logs are shown.

Can I use this push notification in the developer app too or does this only work after I've installed my apk?

**Comment by DanTheMan-NL** [comment]
I've installed Android Studio and used Logcat and this error keeps showing, anyone know what it is?

E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE

I have the current file of google-services.json in my root folder next to config.xml.
My config.xml reads:
<plugin name="phonegap-plugin-push" spec="^2.2.2">
        <variable name="ANDROID_SUPPORT_V13_VERSION" value="27.+" />
        <variable name="FCM_VERSION" value="11.6.2" />
    </plugin>

**Comment by jcesarmobile** [comment]
do you have a resource-file tag or hook that copies your google-services.json to the android project? just putting it in the root is not enough

**Comment by DanTheMan-NL** [comment]
Oh, I'm sorry, Yes. This is in my config.xml:
```
<platform name="android">
<resource-file src="google-services.json" target="app/google-services.json" />
</platform>
```

**Comment by DanTheMan-NL** [comment]
Ah never mind, I found this thread and downgrading to 2.1.2 fixed the problem (SERVICE_NOT_AVAILABLE):
https://github.com/phonegap/phonegap-plugin-push/issues/2278

There is something in the latest release that causes this problem.

**Comment by macdonst** [comment]
@DanTheMan-NL it's more likely that another plugin you are using and this push plugin are conflicting with the support libraries they include. I'm glad you fixed your problem by downgrading though.

**Comment by DanTheMan-NL** [comment]
I doubt it because I have limited plugin's in my app:
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-whitelist 1.3.3 "Whitelist"
phonegap-plugin-push 2.1.2 "PushPlugin"

Is there a way for me to know what plugin might have caused it or how to solve this? Because eventually I have to upgrade this plugin.

**Comment by macdonst** [comment]
@DanTheMan-NL no, none of those plugins seem to be an issue. That is they should not cause a conflict. As I said earlier reproducing the problem with logs is the way to go.
