### ISSUE TITLE
Invalid data, chunk must be a string or buffer, not object on phonegap-plugin-push installation

### ISSUE THREAD

**Issue by santosh-hegde** [phonegap/phonegap-plugin-push#2327]
### Actual Behaviour

```
Plugin "phonegap-plugin-push" already installed on android.
Plugin "phonegap-plugin-push" already installed on browser.
Adding phonegap-plugin-push to package.json
Saved plugin info for "phonegap-plugin-push" to config.xml
(node:77521) UnhandledPromiseRejectionWarning: TypeError: Invalid data, chunk must be a string or buffer, not object
    at WriteStream.Socket.write (net.js:714:11)
    at WriteStream.stream.write (/Users/Santosh/.nvm/versions/node/v8.11.1/lib/node_modules/cordova/node_modules/ansi/lib/newlines.js:36:21)
    at Object.<anonymous> (/Users/Projects/test/tss/plugins/cordova-plugin-fcm/scripts/fcm_config_files_process.js:80:24)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
(node:77521) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:77521) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
#### Steps to Reproduce 
```
cordova platform add android@~7.1.0
cordova plugin add phonegap-plugin-push
```

#### Cordova CLI version and cordova platform version

    cordova --version   :8.0.0                             
    cordova platform version android    :    7.1.1   

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@santosh-hegde as you can see in the stack trace this error is actually coming from cordova-plugin-fcm. Please open an issue on their repository:

```
    at Object.<anonymous> (/Users/Projects/test/tss/plugins/cordova-plugin-fcm/scripts/fcm_config_files_process.js:80:24)
```

**Comment by santosh-hegde** [comment]
@macdonst, This was working until last night. When I updated my project, `phonegap-plugin-push ` forcing me to upgrade to android cordova 7.1.0.
`cordova-plugin-fcm` last updated 11 months ago. I don't think its FCM issue.

**Comment by macdonst** [comment]
@santosh-hegde well all I can tell you is what I see in the error message you posted which is `plugins/cordova-plugin-fcm/scripts/fcm_config_files_process.js:80:24`. That says an error is being thrown from column 24 of line 80 of the file fcm_config_files_process.js which has been included by the `cordova-plugin-fcm` plugin. 

If you just upgraded your project to cordova-android 7.1.0 then the `cordova-plugin-fcm` plugin probably has an issue with that version of cordova-android. 

As you said that plugin hasn't been touched in 11 months so I think it's abandoned. I sent a PR to the repo 2 weeks ago to fix some stuff but it has gone unmaintained.

You should probably re-evaluate what you are using `cordova-plugin-fcm` for. If you can live without it remove it from your project, if you can't then you'll need to downgrade to an earlier version of cordova-android and the push plugin.

**Comment by santosh-hegde** [comment]
@macdonst ,
When I downgrade to cordova-android to 6.5 and install `ionic cordova plugin add phonegap-plugin-push`,

I'm getting the below error.
```
Installing "phonegap-plugin-push" for android

Plugin doesn't support this project's cordova version. cordova: 6.5.0, failed version requirement: >=7.1.0
```

How can I make it work?. I'm fine with older version. But phonegap is not letting me.

**Comment by macdonst** [comment]
@santosh-hegde when you run:

```
ionic cordova plugin add phonegap-plugin-push
```

it will always pick the latest version. You need to specify an earlier version like:

```
ionic cordova plugin add phonegap-plugin-push@2.1.0
```
