### ISSUE TITLE
What if the user denies the push notification permissions request?

### ISSUE THREAD

**Issue by tyronedougherty** [phonegap/phonegap-plugin-push#233]
Hi, is there any way to tell if the user has specifically denied the push notification permission (iOS or Android)?

So far I have been unable to find a way to tell whether a user has denied the permission or a general registration error has occurred. Is there a way or is this feature missing from the plugin?

Thank you!

**Comment by macdonst** [comment]
I think this is a duplicate of #202

**Comment by macdonst** [comment]
@tyronedougherty please add comments +1 to #202
