### ISSUE TITLE
How to enable browser notification

### ISSUE THREAD

**Issue by santosh-hegde** [phonegap/phonegap-plugin-push#2330]
### Expected Behaviour
The browser should receive notification along with phone
### Actual Behaviour
No notification received

#### Cordova CLI version and cordova platform version

    cordova --version                               8.0.0
    cordova platform version browser     5.0.3                    

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push 2.2.2  # e.g. 1.5.3

```
 const options: PushOptions = {
            android: {
                senderID: '1999999965',
                forceShow: true,
                // icon: "screen",
                // iconColor: "blue"
            },
            browser: {
                pushServiceURL: 'http://push.api.phonegap.com/v1/push'
            }
        };

        const pushObject: PushObject = this.push.init(options);
```
How to send notification to browser?
I can see the registration ID. But notification is not coming in browser.

**Comment by santosh-hegde** [comment]
@macdonst ,
Currently, I pushing using FCM on my android devices. Will it work if I send through FCM?
If not, what is the other way to send to the browsers?

**Comment by macdonst** [comment]
@santosh-hegde the cordova-browser platform is there so you can test your app in the browser before deploying to a device. If you want to test receiving pushes in the browser you can use the PhoneGap Push Service. See the tutorial here: http://docs.phonegap.com/tutorials/develop/push-notifications/

**Comment by santosh-hegde** [comment]
@macdonst ,
Is it not possible to integrate with Google Firebase. I'm using that to send notifications.
It would be great if I can push notification to both platforms together.

**Comment by macdonst** [comment]
@santosh-hegde no, the cordova-browser platform and the push plugin are not written in such a way to make this easy. The plugin registers with our FCM app and our push service.
