### ISSUE TITLE
PushNotification not defined even after adding plugin

### ISSUE THREAD

**Issue by edufruit** [phonegap/phonegap-plugin-push#2331]
<script type="text/javascript" src="cordova.js"></script>
	<script type="text/javascript" src="push.js"></script>

										var push = PushNotification.init({
										  "android": {
											"senderID": "xxxxxxxxxxx"
										  },
										  // "browser": {},
										  // "ios": {
											// "sound": true,
											// "vibration": true,
											// "badge": true
										  // },
										  // "windows": {}
										});
										 
										push.on('registration', function(data) {
											alert('registration event: ' + data.registrationId);
											console.log('registration event: ' + data.registrationId);

										  var oldRegId = localStorage.getItem('registrationId');
										  if (oldRegId !== data.registrationId) {
											// Save new registration ID
											localStorage.setItem('registrationId', data.registrationId);
											// Post registrationId to your app server as the value has changed
										  }

										  var parentElement = document.getElementById('registration');
										  var listeningElement = parentElement.querySelector('.waiting');
										  var receivedElement = parentElement.querySelector('.received');

										  listeningElement.setAttribute('style', 'display:none;');
										  receivedElement.setAttribute('style', 'display:block;');
										});
										 
										push.on('error', function(e) {
											alert("push error = " + e.message);
											console.log("push error = " + e.message);
										});
										 
										 
										 
										push.on('notification', function(data) {
										  console.log('notification event');
										  navigator.notification.alert(
											data.message,         // message
											null,                 // callback
											data.title,           // title
											'Ok'                  // buttonName
										  );
										});
					   
config.xml : 

	
		<plugin name="phonegap-plugin-push" spec="2.0.0" />

**Comment by jcesarmobile** [comment]
You have to follow the template, you are missing all the required information as Cordova CLI version and cordova-android version
