### ISSUE TITLE
Error : PushNotification not defined even after adding plugin

### ISSUE THREAD

**Issue by edufruit** [phonegap/phonegap-plugin-push#2333]
**config.xml :** 
  
		
		<preference name="DisallowOverscroll" value="true" />
		<preference name="AndroidPersistentFileLocation" value="Compatibility" />
		<preference name="android-minSdkVersion" value="14" />
		<preference name="loadUrlTimeoutValue" value="700000" /> 
		<preference name="android-minSdkVersion" value="15" />
 
	   <plugin name="cordova-plugin-googleplus" source="npm" spec="5.2.1"></plugin> 
 
 
		<feature name="NetworkStatus">
			<param name="android-package" value="org.apache.cordova.networkinformation.NetworkManager" />
		</feature> 
  
		<platform name="android"> 
			<resource-file src="google-services.json" target="google-services.json" />
		</platform>
	  
	
		<plugin name="phonegap-plugin-push" spec="2.0.0" /> 
		<plugin name="cordova-plugin-firebase" spec="0.1.20" /> 
		 
	  <content src="index.html" />  
		
		 
		 

**index.html**
 
										var push = PushNotification.init({
										  "android": {
											"senderID": "xxxxxxxxxxx"
										  },
										  // "browser": {},
										  // "ios": {
											// "sound": true,
											// "vibration": true,
											// "badge": true
										  // },
										  // "windows": {}
										});
										 
										push.on('registration', function(data) {
											alert('registration event: ' + data.registrationId);
											console.log('registration event: ' + data.registrationId);

										  var oldRegId = localStorage.getItem('registrationId');
										  if (oldRegId !== data.registrationId) {
											// Save new registration ID
											localStorage.setItem('registrationId', data.registrationId);
											// Post registrationId to your app server as the value has changed
										  }

										  var parentElement = document.getElementById('registration');
										  var listeningElement = parentElement.querySelector('.waiting');
										  var receivedElement = parentElement.querySelector('.received');

										  listeningElement.setAttribute('style', 'display:none;');
										  receivedElement.setAttribute('style', 'display:block;');
										});
										 
										push.on('error', function(e) {
											alert("push error = " + e.message);
											console.log("push error = " + e.message);
										});
										 
										 
										 
										push.on('notification', function(data) {
										  console.log('notification event');
										  navigator.notification.alert(
											data.message,         // message
											null,                 // callback
											data.title,           // title
											'Ok'                  // buttonName
										  );
										});

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by edufruit** [comment]
I have updated my post. Kindly guide.

**Comment by edufruit** [comment]
which version shall I use then?

**Comment by jcesarmobile** [comment]
use the 8.0.0 CLI and 2.1.3 plugin
or if you don't want to update the CLI, then use 1.11.1 plugin, but that version is supposed to be used for GCM, not FCM, so update the CLI

**Comment by edufruit** [comment]
I need to use google plus plugin also and this notification plugin also, but using both of them build gives error : **Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin'] > For input string: "+"**

**Comment by edufruit** [comment]
When I use 5.3.0 of googleplus plugin then it works and build succeeds, but then on sending notifications  a pop up appears in the phone and says App has stopped ...Close App. <plugin name="cordova-plugin-googleplus" source="npm" spec="5.3.0"></plugin>
