### ISSUE TITLE
Error : PushNotification not defined in PhoneGap Build

### ISSUE THREAD

**Issue by edufruit** [phonegap/phonegap-plugin-push#2334]
**Expected Behaviour**
Should show notifications on firing from firebase console : [https://cordova-plugin-fcm.appspot.com/](https://cordova-plugin-fcm.appspot.com/)

**Actual Behaviour**
Gives PushNotification not defined error.

**Platform & Version** : PhoneGap Build for Android Platform
Testing it on Samsung

**Cordova CLI version and cordova platform version**
cordova --version                                    #  cli-6.5.0  
cordova platform version android                     # 6.1.2  

**Plugin version** 
2.0.0   =>	`<plugin name="phonegap-plugin-push" spec="2.0.0" /> `

 **config.xml :** 
  
		
		<preference name="DisallowOverscroll" value="true" />
		<preference name="AndroidPersistentFileLocation" value="Compatibility" />
		<preference name="android-minSdkVersion" value="14" />
		<preference name="loadUrlTimeoutValue" value="700000" /> 
		<preference name="android-minSdkVersion" value="15" />
 
	   <plugin name="cordova-plugin-googleplus" source="npm" spec="5.2.1"></plugin> 
 
 
		<feature name="NetworkStatus">
			<param name="android-package" value="org.apache.cordova.networkinformation.NetworkManager" />
		</feature> 
  
		<platform name="android"> 
			<resource-file src="google-services.json" target="google-services.json" />
		</platform>
	  
	
		<plugin name="phonegap-plugin-push" spec="2.0.0" /> 
		<plugin name="cordova-plugin-firebase" spec="0.1.20" /> 
		 
	  <content src="index.html" />  
		
		 
		 

**index.html**
 
										var push = PushNotification.init({
										  "android": {
											"senderID": "xxxxxxxxxxx"
										  },
										  // "browser": {},
										  // "ios": {
											// "sound": true,
											// "vibration": true,
											// "badge": true
										  // },
										  // "windows": {}
										});
										 
										push.on('registration', function(data) {
											alert('registration event: ' + data.registrationId);
											console.log('registration event: ' + data.registrationId);

										  var oldRegId = localStorage.getItem('registrationId');
										  if (oldRegId !== data.registrationId) {
											// Save new registration ID
											localStorage.setItem('registrationId', data.registrationId);
											// Post registrationId to your app server as the value has changed
										  }

										  var parentElement = document.getElementById('registration');
										  var listeningElement = parentElement.querySelector('.waiting');
										  var receivedElement = parentElement.querySelector('.received');

										  listeningElement.setAttribute('style', 'display:none;');
										  receivedElement.setAttribute('style', 'display:block;');
										});
										 
										push.on('error', function(e) {
											alert("push error = " + e.message);
											console.log("push error = " + e.message);
										});
										 
										 
										 
										push.on('notification', function(data) {
										  console.log('notification event');
										  navigator.notification.alert(
											data.message,         // message
											null,                 // callback
											data.title,           // title
											'Ok'                  // buttonName
										  );
										});

**Comment by macdonst** [comment]
@edufruit the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

Please include an app id of an app that can replicate this issue.
