### ISSUE TITLE
Voip not available as push option in ios PushOptions.

### ISSUE THREAD

**Issue by jatins52** [phonegap/phonegap-plugin-push#2336]
How can I generate voip tokens? Are these different from normal push tokens ? I get an error for voip is not a property of IOS push options.

How can I add voip notifications in my app.

**Comment by macdonst** [comment]
@fredgalvao yeah, it was supposed to link to:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#ios-voip-notifications

**Comment by jatins52** [comment]
@macdonst I have read the document and also updated my plugin version from 2.1.3 to 2.2.2. 
But I am still getting bellow error:
'voip' does not exist in type 'IOSPushOptions'

My code is:
const options: PushOptions = {
android: {
        sound: 'ringtone'
},
ios: {
        voip: true
}
}

const pushObject: PushObject = this.push.init(options);

// Below this notification listeners

Can you please elaborate more what is the mistake I am making
