### ISSUE TITLE
Phongap Build with cli-7.1.0 - gradle error

### ISSUE THREAD

**Issue by Marix1** [phonegap/phonegap-plugin-push#2337]
Phongap Build with cli-7.1.0 

BUILD FAILED

Error: /gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.

**Comment by macdonst** [comment]
@Marix1 the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
