### ISSUE TITLE
timeToLive not working Ionic

### ISSUE THREAD

**Issue by wilberparedes** [phonegap/phonegap-plugin-push#2340]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 8.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

#### code 
         $data = array(
                  'registration_ids' => $arrayId,
                  'timeToLive' => 1,
                   'data' => $payload,
                   'priority' => 'high'
             );

**Comment by jcesarmobile** [comment]
timeToLive is the time to live in the server, if it's not received before that time expires, then it won't receive it, but it doesn't delete the ones that were received when the time expired if they weren't opened.

**Comment by wilberparedes** [comment]
@jcesarmobile  so, With what code can I do this?

**Comment by jcesarmobile** [comment]
¯\_(ツ)_/¯

I'm not sure it's supported. But as I said in your previous issue, this is for reporting issues, not for asking questions.

**Comment by wilberparedes** [comment]
do not lose anything with respond, likewise thank you very much!
