### ISSUE TITLE
Registration fails on Android 4.4 only

### ISSUE THREAD

**Issue by AlphaCreative** [phonegap/phonegap-plugin-push#2342]
### Expected Behaviour
Successful registration

### Actual Behaviour
Registration failed : "SERVICE_NOT_AVAILABLE"

### Reproduce Scenario (including but not limited to)
Try to register on Android API 19

#### Steps to Reproduce 
Create Android API 19 emulator and Android API 21 emulator using AVD Manager
Deploy build to both emulators
Register for push on 21 it is successful.  Register for push on 19 and it fails with "SERVICE_NOT_AVAILABLE"

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android API 19

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
AVD Emulator Nexus 5X device

#### Cordova CLI version and cordova platform version

    cordova --version   8.0.0
    cordova platform version android   7.1.0

#### Plugin version
2.2.2

#### Sample Push Data Payload
NA

#### Sample Code that illustrates the problem
var push = PushNotification.init({
            android: {
            },
            ios: {
                alert: "true",
                badge: "true",
                sound: "true"
            }
        });
        push.on('registration', function(data) {
            console.log('registration', data);
        });
        push.on('error', function(e) {
            console.log('push error', e.message);
            console.log(e);
            // e.message
        });

**Comment by macdonst** [comment]
@AlphaCreative sorry, we don't support the android emulator. It is recommended to test on a real device. For what it's worth I can't reproduce on my Nexus 5 running Android 4.4.

**Comment by andreszs** [comment]
I'm also suddenly getting this `SERVICE_NOT_AVAILABLE` on Android 4.4.2 (Samsung GT-I9190) now, but remarkably it's still working on Android 4.1.2 (Samsung GT-I6810) and Android 5 and 6. I can assure this problem didn't happen before May 25.
Did you find any solution?

**Environment:**
cordova 7.1.0
cordova-android 6.3.0
phonegap-plugin-push 2.1.3

**Note**: The the older plugin from the app created with cordova 6.5.0 still works perfectly as well on the same phone, so it's not a problem with the device but with the plugin.

**Comment by cmartin81** [comment]
I also have the same problem. I get SERVICE_NOT_AVAILABLE on my live 4.4.4 device

**Comment by andreszs** [comment]
@cmartin81  ensure you have a compatible **cordova** and **cordova-android** versions, otherwise you'll get that error.

Notice that cordova-android 6.4.0 and newer have DROPPED support for Android < API 19, so you'll want to keep cordova-android 6.3.0 by all means (and cordova 7.1.0 at most)

**Comment by cmartin81** [comment]
@andreszs I'm using cordova-android 7.1.0 which support android 4.4.4. And still getting the SERVICE_NOT_AVAILABLE error.

**Comment by jonatarussi** [comment]
I am getting the same error in Android 4.4.2 and 4.4.4

**Comment by razam217** [comment]
Did someone find solution to this bug? I'm also facing the same issue:
corodva 7.1.0
cordova-android 6.3.0
plugin 2.1.3
Android 4.4.2
Error: SERVICE_NOT_AVAILABLE

**Comment by razam217** [comment]
I've found a solution:
I simply changed com.google.firebase from 11.6.2 - 11.8.0 and 
com.google.android.gms:play-services-location from 11.6.2 - 11.8.0 and everything is working fine.
