### ISSUE TITLE
Not receiving push notifications in Android app built with PhoneGap Build 

### ISSUE THREAD

**Issue by jamminjames** [phonegap/phonegap-plugin-push#2343]
### Expected Behaviour
I have an Android app built with PhoneGap Build, and I believe I have followed all the instructions for that, but no notifications are coming through yet. I have the plugin in the config.xml file, and the .json file from Firebase in the root of the app.

I’m not clear on what to include in a javascript file. I've found some examples, and tried different ones, see below. Any help would be appreciated. Thank you!

### Actual Behaviour
Notifications not coming through.

### Reproduce Scenario (including but not limited to)
Sent test notifications via Firebase, but no notifications show up.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
LG

#### Cordova CLI version and cordova platform version
    cordova --version 7.1.0
    cordova platform version android  5.0

#### Plugin version
    cordova plugin version | grep phonegap-plugin-push 1.11.1 
   (I'm not actually using a version number in config.xml, so it should be using the latest.)

#### Sample Push Data Payload
I'm using the Firebase Console to send push notifications.

#### Sample Code that illustrates the problem
This is what I have in the app to set up the plugin. 
In config.xml:
```
<plugin name="phonegap-plugin-push" source="npm" />
<platform name="android">
    <resource-file src="google-services.json" target="google-services.json" />
</platform>
```

In the root folder, I've placed the google-services.json file.

The js file (called in the index.html file) I'm using contains this:
```
var app = {
    // Application Constructor
    initialize: function() {
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
    },

    // deviceready Event Handler
    //
    // Bind any cordova events here. Common events are:
    // 'pause', 'resume', etc.
    onDeviceReady: function() {
        this.receivedEvent('deviceready');
    },

    // Update DOM on a Received Event
    receivedEvent: function(id) {
        console.log('device is ready');

        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');

        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');

        try {
            var pn = PushNotification;
            console.log('PushNotification is defined');
        }
        catch (e) {
            console.log('PushNotification is not defined');
        }
        const push = PushNotification.init({
            android: {
				icon: 'res/icon/androidicons/androidicon48.png',
				iconColor: 'blue'
			},
			browser: {
				pushServiceURL: 'http://push.api.phonegap.com/v1/push'
			},
			ios: {
				alert: 'true',
				badge: 'true',
				sound: 'false'
			},
			windows: {}
		});

        push.on('registration', function(data) {
            console.log('registered');
            console.log(JSON.stringify(data, null, 4));
        });

        push.on('notification', function(data) {
            console.log('notified');
            console.log(JSON.stringify(data, null, 4));
        });

        push.on('error', function(e) {
            console.log('error');
            console.log(e.toString());
        });
    }
};

app.initialize();
```
#### Logs taken while reproducing problem
I tried to record any errors via the PhoneGap Build debugger, but nothing showed in the console.

**Comment by macdonst** [comment]
@jamminjames version 1.11.1 does not use FCM so even if you include the `google-services.json` it will never be read. Since you are not passing in a SENDER_ID which is the way we used to specify things in the [v1.x stream](https://github.com/phonegap/phonegap-plugin-push/tree/v1.x). So your choices are either upgrade to the 2.x steam of the plugin or read the 1.x docs and pass in the sender ID. The right answer is upgrade to 2.x though.

**Comment by jamminjames** [comment]
@macdonst I thought I was using the latest version. In my config.xml file, I don't specify a version, so shouldn't it use the latest? The line in config is:
`<plugin name="phonegap-plugin-push" source="npm" />`
Sorry I put the version 1.11.1 in the issue description, I thought that was the latest.
