### ISSUE TITLE
where can i get the callback function when user tap on push notification in notification bar. Please help me out.

### ISSUE THREAD

**Issue by shri1983** [phonegap/phonegap-plugin-push#2344]
### Expected Behaviour
where can i get the callback function when user tap on push notification in notification bar.
### Actual Behaviour
app launches and land on home screen
### Reproduce Scenario (including but not limited to)
Just click on notification
#### Steps to Reproduce 
Just click on notification message
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android version @7.1.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Mi note 5
#### Cordova CLI version and cordova platform version

    cordova --version                                    8.0.0
    cordova platform version android            7.1.0

**Comment by macdonst** [comment]
@shri1983 the [on('notification')](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushonnotification-callback) event will be fired and the callback you registered to handle the event will be called.

**Comment by shri1983** [comment]
thanks for your response. But it is called only when the app is in foreground ie when app is in the background the on('notification') event is not fired. Please suggest for the same. Thanks in advanced.

**Comment by GermainChavigny** [comment]
I had this problem too, resolved when I removed the "notification" parameter in the notification payload sent by the server, I don't know what your payload look likes ?

**BUT**, now the problem is that the notification is completely ignored on IOS !

```
    $notif = array(
        "to" => "XXX",
        "priority" => "high",

        /* If uncommented, the notification is sent on IOS but the problem on Android reappears.
        "notification" => array(
            "title" => "My title",
        ),
        */
            
        "data" => array(
            "title" => "My title",
            "message" => "My message",
            "myExtraParam" => "..."
        )
    );
```

**Comment by macdonst** [comment]
@GermainChavigny you have to use `data` to FCM on Android and `notification` to FCM on iOS.

**Comment by shri1983** [comment]
Thanks for your time. Will implement same.
