### ISSUE TITLE
(iOS) Badge not updated when app is not running

### ISSUE THREAD

**Issue by ethanbud5** [phonegap/phonegap-plugin-push#2346]
### Expected Behaviour
I expect that when I send a push notification to my app that it will always update my badge regardless of the state it is in. (i.e. background, foreground, not running)
### Actual Behaviour
When the app is forced quit (double click home button and swipe up to close) it will still receive notifications, but they will not update badge count.
### Reproduce Scenario (including but not limited to)
Force quit app and send push notification that includes badge count in payload.
#### Cordova CLI version and cordova platform version

Using PhoneGap Build

#### Plugin version

    cordova plugin version   1.6.0

#### Sample Push Data Payload
    $body['aps'] = array(
	'alert' => array(
		'body' => $finalmessage,
	),
	'badge' => 1,
	'sound' => 'default',
	'content-available' => 1
	)
#### Sample Code that illustrates the problem
push.on('notification', function(data) {
    push.setApplicationIconBadgeNumber(function() {
        console.log('icon success');
    }, function() {
        console.log('icon error');
    }, data.count);
    
    push.finish(function() {
        console.log("processing of push data is finished");
    });
});

**Comment by macdonst** [comment]
@ethanbud5 you'd think that but when the app is force quit iOS does not automatically star the app. It stays in a non-running state so the badge number will not get set. Sorry, this is an iOS thing I can't change.

**Comment by ethanbud5** [comment]
@macdonst Ok thanks.
