### ISSUE TITLE
Help with Android 8 Channels?

### ISSUE THREAD

**Issue by jamminjames** [phonegap/phonegap-plugin-push#2347]
What needs to be done to indicate Channels, so that notifications are delivered to Android 8 devices? From what I can gather, at least a default channel must be indicated, or the push won't be delivered. How do you do that with this plugin? Is it done in the initializing js, and if so, how? Thank you.

**Comment by macdonst** [comment]
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-channels

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushnotificationcreatechannelsuccesshandler-failurehandler-channel
