### ISSUE TITLE
Not receiving push notifications in Android app

### ISSUE THREAD

**Issue by Zarwlar** [phonegap/phonegap-plugin-push#2348]
### Expected Behaviour

Brief:
Receive FCM notification when sending to user segment devices with Firebase Console.

Detail:
I have an Android app built with PhoneGap Build, and I believe I have followed all the instructions for that, but no notifications are coming through yet. I have the plugin in the config.xml file, and the google-services.json file from Firebase in the root of the app.

### Actual Behaviour

Notifications accept status completed, but not coming through.
![image](https://user-images.githubusercontent.com/26929933/39506327-0c6c044e-4e02-11e8-8ee5-1e131a144894.png)

#### Steps to Reproduce

All my actions step by step.

1. Create phonegap app.
`phonegap create . --template hello-world`

2. Add phonegap push notification plugin.
`phonegap plugin add phonegap-plugin-push`

3. Create new firebase project.
3.1. Convinced that the firebase app id and the config.xml app id are equal.
3.2. Create android app.
3.3. Download google-services.json and move it to root project folder.
3.4. Add info about google-services.json to the config.xml file.
```
	<platform name="android">
	        <resource-file src="google-services.json" target="google-services.json" />
	</platform>
```
3.5. Add info about sender id to the config.xml file.
```
    <plugin name="phonegap-plugin-push" spec="~2.2.2">
        <variable name="SENDER_ID" value="<MY_SENDER_ID>" />
    </plugin>
```

4. Modify js file.
```
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    // deviceready Event Handler
    //
    // The scope of 'this' is the event. In order to call the 'receivedEvent'
    // function, we must explicitly call 'app.receivedEvent(...);'
    onDeviceReady: function() {
        app.receivedEvent('deviceready');
        const push = PushNotification.init({
            android: {
              senderID: <MY_SENDER_ID>
            }
          });
          push.on('notification', (data) => {
            // const result = document.getElementById('result');
            // result.innerText = data.message;
        });
    },
```

5. Create zip file of project folder.
6. Upload zip file to PhoneGap Build.
7. Download apk file to my phone.
8. Install apk.
9. Send notification with the Firebase Console.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

OnePlus 2

#### Cordova CLI version and cordova platform version

    cordova --version                                    # 8.0.0
    cordova platform version android                     # ~7.0.0

#### Plugin version

    phonegap-plugin-push 2.2.2 "PushPlugin"

#### Sample Push Data Payload

I'm using the Firebase Console to send push notifications.

#### Sample Code that illustrates the problem

The code was previously specified.

#### Logs taken while reproducing problem

I haven't logs.

**Comment by jamminjames** [comment]
Same problem here, also using Phonegap Build.

**Comment by jcesarmobile** [comment]
Latest version of the plugin requires cordova-android 7.1.0, which is not supported by PGB yet, so you have to pin 2.1.3 version of the plugin, and also make sure you are using CLI 7.1.0 or 8.0.0 as default is 6.5.0
