### ISSUE TITLE
Permissions for Android

### ISSUE THREAD

**Issue by xyboox** [phonegap/phonegap-plugin-push#2349]
### Expected Behaviour
On new app install, push notifications permission request should be displayed.

### Actual Behaviour
Permission is assumed "true" by default.

### Reproduce Scenario (including but not limited to)
Install app with plugin installed. On first run, app will request for permission. Uninstall app and re-install it. Permission request is not being displayed. It works though on iOS.

#### Steps to Reproduce 
Please see above.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8.1.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Google Pixel

#### Cordova CLI version and cordova platform version

    cordova --version                                   8.0.0
    cordova platform version android         7.1.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.2.2

#### Sample Push Data Payload
not relevant

#### Sample Code that illustrates the problem
not relevant 

#### Logs taken while reproducing problem
not relevant

**Comment by jcesarmobile** [comment]
You say the first time you get the permission prompt, but if you uninstall and reinstall it doesn't ask the second time?
Are you sure about it? as far as I know, Android doesn't prompt about push permissions, so it shouldn't prompt the first time.

**Comment by xyboox** [comment]
Actually @jcesarmobile you're right. I was under the impression that it did asked after the very first install. Just checked on a device it wasn't installed at all before and the permission is assumed default "true". Thanks for pointing this out!
