### ISSUE TITLE
Handle notif expiration ?

### ISSUE THREAD

**Issue by HugoHeneault** [phonegap/phonegap-plugin-push#2354]
### Expected Behaviour
I'm looking for a way to set an expiry date for the notifications. 

### Actual Behaviour
I didn't find anything in the docs about it. 😭 
There seems to be a way of doing it for APNS (apns-expiration, as said here: https://stackoverflow.com/a/30190838/1847249) and time-to-live for android (https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message)

I might have some time to create a PR but I'm quite new in cordova plugins so... 🤔

**Comment by jcesarmobile** [comment]
That doesn't really have to do with the plugin, those are for the Push payload you sent from your server to APNs and FCM, so better look into the docs of the library/tool/service you use for sending the push

**Comment by HugoHeneault** [comment]
@jcesarmobile Oh yes you're totally right!! Sorry for that.
It might be nice to add it in the docs. I just don't know where...

**Comment by HugoHeneault** [comment]
Ok I understand. Thanks for your time! 🍻
