### ISSUE TITLE
Existing Notification gets replaced with new on Android

### ISSUE THREAD

**Issue by echonox** [phonegap/phonegap-plugin-push#2356]
### Expected Behaviour
New Notification should not replace existing push notification
### Actual Behaviour
If there is already a push notification in the notification centre when new notification arrives, the existing notification gets replaced with the new one
### Reproduce Scenario (including but not limited to)
Send a simple push notification to android
#### Steps to Reproduce 
Send a simple push notification to android
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1 and Android 8.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy S5, Xiaomi A1
#### Cordova CLI version and cordova platform version

    cordova --version                                   8.0.0
    cordova platform version android          7.1.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.2.2

#### Sample Push Data Payload
{
message: "Hello World"
}

**Comment by macdonst** [comment]
@echonox that is by design. Please read the docs on [Stacking](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#stacking).
