### ISSUE TITLE
Building with Phonegap Build, says 'plugin doesn't support cli 7.1.0

### ISSUE THREAD

**Issue by jamminjames** [phonegap/phonegap-plugin-push#2361]
### Expected Behaviour
Build with Phonegap Build, using cli 7.1.0.

### Actual Behaviour
In the build log, it says:
```
Installing "phonegap-plugin-push" at "2.2.2" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.3.0, failed version requirement: >=7.1.0
Skipping 'phonegap-plugin-push' for android
```
#### Steps to Reproduce 
In config.xml, I use cli 7.1.0, including this line:
`<preference name='phonegap-version' value='cli-7.1.0' />`

In plugins, I have:
```
<plugin name="phonegap-plugin-push" source="npm" />
<plugin name="cordova-plugin-admob-free" source="npm" />
<plugin name="cordova-support-google-services" source="npm" />
```
... using cordova-support-google-services to sync google services versions used by admob and phonegap-plugin-push, otherwise, doesn't build at all.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
LG

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.1.0
    cordova platform version android            4.4 and above

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.2.2

#### Sample Push Data Payload
Using Firebase console, sending basic push.

#### Logs taken while reproducing problem
```
Installing "phonegap-plugin-push" at "2.2.2" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.3.0, failed version requirement: >=7.1.0
Skipping 'phonegap-plugin-push' for android
```

**Comment by macdonst** [comment]
@jamminjames you are using the latest push plugin which requires cordova-android 7.1.0 or greater but your app is using cordova-android 6.3.0.

```
Plugin doesn't support this project's cordova-android version. cordova-android: 6.3.0, failed version requirement: >=7.1.0
```

**Comment by jamminjames** [comment]
@macdonst No, that's not the case. I am using 7.1.0. But in Phonegap Build, for some reason, it's saying that, only for your plugin. As noted, I have this line in the config.xml, which is for 7.1.0:
`<preference name='phonegap-version' value='cli-7.1.0' />`
This doesn't happen for any other plugin, so it seems it must be related to something in your code, yes?

**Comment by jamminjames** [comment]
Okay, I guess it's just a confusing numbering system PGB is using. I think the highest Android it will build for is 7.0, using cli-8.0, is that correct? If so, is there a version of the push plugin that can work with Android 7.0, rather than 7.1? Better yet, is there a 2+ version that will work with Android 6.3?

**Comment by macdonst** [comment]
@jamminjames https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements

**Comment by jamminjames** [comment]
Okay, tried 2.1.2, but still getting build errors. A [discussion I found here](https://github.com/dpa99c/cordova-android-play-services-gradle-release/issues/7) says that this plugin does not include GoogleServicesPlugin in the proper way, and this is why it doesn't work with some other plugins. They say:

> The cause is phonegap-plugin-push since it uses a Gradle class instead of a string to include the GoogleServicesPlugin which leads to pulling in a different version of com.google.android.gms in a way which this plugin (and cordova-google-api-version) are unable to override. See [this discussion](https://github.com/dpa99c/cordova-plugin-request-location-accuracy/issues/35#issuecomment-325690966) for more info.

Why does this plugin use this, as they say "hack," and why not do it the conventional way, and avoid these conflicts?

**Comment by macdonst** [comment]
@jamminjames that's been changed in a later release but the reason it was done like that previously because of the problem with updating the Gradle classpath in a secondary gradle file in cordova-android.

Since this is a problem with PGB I have to let you know the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

Please include an app id of an app that can replicate this issue.
