### ISSUE TITLE
Notifications not received when rebuilt app in closed state

### ISSUE THREAD

**Issue by acahinton** [phonegap/phonegap-plugin-push#2362]
### Expected Behaviour
Notification should appear in Android tray when app is closed

### Actual Behaviour
Works for a test app (background and closed) built in Ionic/Cordova but when changing the widget id and name only (sender id stays the same) and releasing to production app they only appear when app is in the background not closed

(This may well not be related to the plugin but any advice would be much appreciated!)

### Reproduce Scenario (including but not limited to)
Release to test app, change just the id and name and release prod app - test notifications

Notifications received in test app when closed or in background
Notification received in prod app only when in background

#### Steps to Reproduce 
As above

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8.0.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
OnePlus A3003

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.1.0
    cordova platform version android           6.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.11.1

#### Sample Push Data Payload
{
    "notification": {
        "title": "Test Notification",
        "body": "body"},    
"to":"regid"
}

#### Sample Code that illustrates the problem
No code changes involved between working test app and prod app

Only on('registration') implemented as only this is required for the app

#### Logs taken while reproducing problem
Are there Android logs I should be looking at that don't know about or haven't stumbled across during my week of trying to resolve?

**Comment by macdonst** [comment]
@acahinton version 1.x of this plugin does not support Android 8. You need to upgrade to v2.x

**Comment by acahinton** [comment]
thanks @macdonst - will go the upgrade route...
