### ISSUE TITLE
Installing older plugin version

### ISSUE THREAD

**Issue by anjildhamala** [phonegap/phonegap-plugin-push#2366]
### Expected Behaviour
Installation of 1.8.0 version of the plugin

### Actual Behaviour
I think it is trying to fetch the latest version of the plugin.

### Reproduce Scenario (including but not limited to)
Cordova version other than 7.1.0
Cordova-android version other than 7.1.0
Cordova-ios version other than 4.5.0 

#### Steps to Reproduce 
cordova plugin add phonegap-plugin-push@1.8.0

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
currently installed cordova-android 5.1.1
currently installed cordova-ios 4.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
just installation. Mac terminal

#### Cordova CLI version and cordova platform version
cordova version was 6.5.0 but upgraded  to 7.1.0 to suppress the first error that barks that the cordova version must be greater or equal to 7.1.0. 

#### Plugin version
well, trying to install 1.8.0

#### Sample Push Data Payload
n/a
#### Sample Code that illustrates the problem
n/a
#### Logs taken while reproducing problem
Plugin doesn't support this project's cordova-android version. cordova-android: 5.1.1, failed version requirement: >=7.1.0
Skipping 'phonegap-plugin-push' for android
Installing "phonegap-plugin-push" for ios
Plugin doesn't support this project's cordova-ios version. cordova-ios: 4.0.1, failed version requirement: >=4.5.0
Skipping 'phonegap-plugin-push' for ios
Adding phonegap-plugin-push to package.json
Saved plugin info for "phonegap-plugin-push" to config.xml

Any help is appreciated.

**Comment by fredgalvao** [comment]
Your logs explain it all. You either use an updated version of everything matching (platforms, plugins, cli), or you pick a very old version to support your also-very-old cordova-android@5.1.1 and cordova-ios@4.0.1.
There is not much, if at all, we can do to help you there.

If I misread your issue and intent, please feel free to reopen it with more details.

**Comment by anjildhamala** [comment]
@fredgalvao I believe I was asking about the ability to install an older version of the plugin. Does the plugin not support @versionNumber install? Why does it try to fetch the latest version when I'm performing "cordova plugin add phonegap-plugin-push@1.8.0"?

**Comment by jcesarmobile** [comment]
It should install that version, but if that fails it's a Cordova issue, not a plugin issue

**Comment by fredgalvao** [comment]
@anjildhamala Have you tried removing and adding it again with the specified version?

To be clear, it definitely should install the version you're asking. If not, then one of the following is to blame:
- npm
- config.xml
- cordova

**Comment by anjildhamala** [comment]
I have. I tried a whole day yesterday to get it working. My main issue was class not found on Android. On IOS, it seem to be working fine. Anyways, I was trying to install it in OSX when I posted the question. Later I tried in windows command prompt and I was able to install a specific older version. Not sure if it is the OS to blame.
