### ISSUE TITLE
Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']    > For input string: "+"

### ISSUE THREAD

**Issue by Vickypr1902** [phonegap/phonegap-plugin-push#2370]
### Expected Behaviour
To Build apk or run in emulator
### Actual Behaviour
Throws an error
#### Cordova CLI version and cordova platform version

    cordova --version                                    #  8.0.0

    cordova platform version android:                     
#Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0 

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3
#card.io.cordova.mobilesdk 2.1.0 "CardIO"
com-sarriaroman-photoviewer 1.1.16 "PhotoViewer"
com.paypal.cordova.mobilesdk 3.5.0 "PayPalMobile"
cordova-plugin-calendar 5.0.0 "Calendar"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-firebase 1.0.4 "Google Firebase Plugin"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.1 "NativeStorage"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.6.2 "Toast"
cordova-sqlite-storage 2.3.1 "Cordova sqlite storage plugin"

**Comment by jcesarmobile** [comment]
I don't see phonegap-plugin-push in your list of plugins

**Comment by Vickypr1902** [comment]
Now I've added but still got the same error.

card.io.cordova.mobilesdk 2.1.0 "CardIO"
com-sarriaroman-photoviewer 1.1.16 "PhotoViewer"
com.paypal.cordova.mobilesdk 3.5.0 "PayPalMobile"
cordova-plugin-calendar 5.0.0 "Calendar"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-firebase 1.0.4 "Google Firebase Plugin"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.1 "NativeStorage"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.6.2 "Toast"
cordova-sqlite-storage 2.3.1 "Cordova sqlite storage plugin"
phonegap-plugin-push 2.1.3 "PushPlugin"

**Comment by jcesarmobile** [comment]
but you had the error before adding the plugin, so I don't think it's related to the plugin. Probably caused by fcm or firebase plugin

**Comment by Vickypr1902** [comment]
I know but i'm stuck and unable to find a solution. It's been a week and nothing yet.
