### ISSUE TITLE
[ionic] onNotification event doesn't work except the 1st time only!!!

### ISSUE THREAD

**Issue by hnguyen48206** [phonegap/phonegap-plugin-push#2373]
I've been using phonegap push plugin for an ionic app of mine just fine for around 1 month or so and now it just decides not to cooperate anymore. The code part related to the push functionality hasn't been changed a single bit since the last time that everything was just as how I expected it would be. 

-Expected processing behaviors: a notification comes, OnNotification event should be triggered to check whether the app is in foreground or background/cold-start. For foreground, a pop-up would appear on top of the current app and it keeps going from there. For the background, the user needs to click on it in the notification center to be navigated to a specific component/page.

-Current problem: the notification appears in the notification center no matter if the app is in fore or back-ground. Another thing is nothing happens even when you click on it.

I have tried to remove the plugin, remove the platform and reinstall them all but it's still the same. I'm on phonegap-plugin-push 2.1.3 and the Android platform is 7.0.0

Any help would be so much appreciated.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
