### ISSUE TITLE
Handle correctly push

### ISSUE THREAD

**Issue by ttibau** [phonegap/phonegap-plugin-push#2375]
Hello guys, 
I'm using firebase API to send notifications. When the app is **closed**, the device received the message correctly. But when the app is **open** or **minimized** I can handle the notification in console, but isn't showing in app, only if I close the app i receive the push. 
Can someone help me? Thanks

```
 @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

System:

    Node : v10.0.0
    npm  : 5.6.0
    OS   : macOS High Sierra
```

```
    "phonegap-plugin-push": "^2.2.2",
```

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
