### ISSUE TITLE
Handle correctly push

### ISSUE THREAD

**Issue by ttibau** [phonegap/phonegap-plugin-push#2376]
### Expected Behaviour
I hoped the notification open when the app is **open** or **minimized** 
### Actual Behaviour
Take the notification in console, but when te app is **open** or **minimized** the notification do not showing on the screen.

### Reproduce Scenario (including but not limited to)
I'm using firebase API to send notifications. When the app is closed, the device received the message correctly. But when the app is open or minimized I can handle the notification in console, but isn't showing in app, only if I close the app i receive the push.
Can someone help me? Thanks

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8.0.0
#### Cordova CLI version and cordova platform version

   cordova version: 8.0.0
   android: 7.1.0
#### Plugin version

    2.2.2

**Comment by jcesarmobile** [comment]
you can use `forceShow` to force showing the push notification, default is false and that calls onNotification so you can handle as you wish. https://github.com/phonegap/phonegap-plugin-push/blob/cb85fbf69c2c7d64a3b0d403517e6c1c533aa0a2/docs/API.md#android
