### ISSUE TITLE
Cannot find where or how to do Action button call back anywhere

### ISSUE THREAD

**Issue by Nick-lab** [phonegap/phonegap-plugin-push#2378]
Cannot figure out how to setup callback functions for action buttons information regarding this is split and segmented online and different pgp plugins are setup different ways including different versions of this plugin, so I am completely confused on what needs to be done to setup for this functionality where do i put the callbacks to allow them to run and how are they setup? using ionic 3 cordova

### Expected *Behavior
Docs to help me.
### Actual Behaviour
Docs seem to be very bland and does not explain or even go over callbacks on action buttons
### Reproduce Scenario (including but not limited to)
Just take a look at the docs
#### Steps to Reproduce 
Go look at any other documentation then come back and look at this plugins documentation and see the difference.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
n/a
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
n/a
#### Cordova CLI version and cordova platform version
n/a

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.1.3

#### Sample Push Data Payload
n/a
#### Sample Code that illustrates the problem
n/a
#### Logs taken while reproducing problem
n/a

**Comment by Nick-lab** [comment]
yes i have the notifications sending correctly already with the action buttons but what about the call backs ??

**Comment by Nick-lab** [comment]
i'm sorry iv'e been on this issue for a day now. what is this PushNotification object? i cant seem to import it from @ionic-native/push.

**Comment by Moghul** [comment]
After you install the plugin, PushNotification should be a global variable you can access. If you're using modules with imports, I don't know how to do it.

If the modules complain that it doesn't exist, see if it exists in one of your .html pages in a <script> tag. If it doesn't, the plugin isn't working right/ isn't installed right.

If it's there, google how to import global variables into modules.

**Comment by macdonst** [comment]
@Nick-lab as @Moghul said the `push` object is the one returned from `PushNotification.init()`. Then you can register event an event listener with the name of the `callback` you provide when setting up the action buttons.

I'm concerned that this might actually be a problem with the Ionic wrapper around this plugin. When you do:

```
const pushObject: PushObject = this.push.init(options);

pushObject.on('emailGuests').subscribe((notification: any) => console.log('action button clicked', notification));
```

Can you successfully register an event listener for `emailGuests`?
