### ISSUE TITLE
How to get "res/drawable/icon.png" wonking on Android below 8.1

### ISSUE THREAD

**Issue by Marix1** [phonegap/phonegap-plugin-push#2379]
On Android 8,1 the custom 92px  res/drawable/icon.png  is displayed.

But on Android 7.x and lower the colored App icon is shown.

Is there an option that allows it to be displayed there as well??

I used Phonegap Build with cli.7.1.0 and push plugin 2.0.0

**Comment by macdonst** [comment]
the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.

**Comment by Marix1** [comment]
Thats weird..

today with the compiled app from yesterday Android 8.0 and 7.x is now took the  res/drawable/icon.png

It seem that it need a while...
