### ISSUE TITLE
Cannot Find module Phonegap-plugin-push

### ISSUE THREAD

**Issue by Nick-lab** [phonegap/phonegap-plugin-push#2382]
### Expected Behaviour
``ionic cordova build ios`` to run
### Actual Behaviour
error comes up 
```
[09:13:43]  typescript: src/app/app.component.ts, line: 7 
            Cannot find module '@ionic-native/push'. 

       L6:  import { Badge } from '@ionic-native/badge';
       L7:  import { Push, PushObject, PushOptions } from '@ionic-native/push'; <----
       L8:  import { DataManager } from '../services/DataManager';

[09:13:43]  typescript: src/app/app.module.ts, line: 22 
            Cannot find module '@ionic-native/push'. 

      L21:  import { Contacts } from '@ionic-native/contacts';
      L22:  import { Push } from '@ionic-native/push'; <----
      L23:  import { Badge } from '@ionic-native/badge';
```
### Reproduce Scenario (including but not limited to)
not to sure
#### Steps to Reproduce 
not to sure
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Platform Issue: IOS
Android Platform is running fine.
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.9.4
    npm        : 5.6.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3 Build version 9E145 
```

#### Cordova CLI version and cordova platform version
```
    cordova --version                                   8.0.0
    cordova platform version android                    n/a
```
#### Plugin version

    cordova plugin version | grep phonegap-plugin-push  @latest / unspecified / @2.1.3

#### Sample Push Data Payload
n/a
#### Sample Code that illustrates the problem
n/a
#### Logs taken while reproducing problem
n/a

**Comment by macdonst** [comment]
@Nick-lab you'll need to ask the Ionic team for support.

**Comment by Nick-lab** [comment]
@macdonst okay thanks for all the help :)

**Comment by macdonst** [comment]
@Nick-lab don't be sarcastic to open source project maintainers. Maintaining projects like this takes a lot of time. In the case of your error it is clearly coming from the Ionic CLI. I don't have a great deal of experience with Ionic nor do I work for them so I think I'm justified in saying you should ask them for support.

**Comment by Nick-lab** [comment]
i'm sorry i have been having a rough week and been having tonnes of issues switching push notification system to this plugin all for the action buttons i'm in unfamiliar water with pods in IOS. your time is appreciated for sure because without people like you pushing this industry forwards where would we be? anyway i'm not too sure if ill get any help from ionic team but thanks anyway

**Comment by macdonst** [comment]
@Nick-lab if you don't get help from Ionic come back here an open a new issue. Other than that check out some of the common cocoapod problems: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#cocoapods

**Comment by Nick-lab** [comment]
@macdonst yea iv'e been through the docs multiple times to no avail but thanks anyway.

**Comment by Nick-lab** [comment]
. . . . . . . WOW . . . @macdonst i never ran ``npm install --save @ionic-native/push`` kill me END MY SUFFERING
