### ISSUE TITLE
Plugin installation fails after 2.2.3 release for existing apps

### ISSUE THREAD

**Issue by MichaelMarner** [phonegap/phonegap-plugin-push#2383]
### Expected Behaviour
Assuming semantic versioning, releasing a patch release 2.2.3 would not cause existing apps to stop building.

### Actual Behaviour
Existing apps configured to user phonegap-plugin-push `^2.2.0` will stop working. The plugin will fail to install because 2.2.3 introduced a dependency on `cordova-support-google-services`:

```
Installing "phonegap-plugin-push" for android

Failed to get module path for cordova-support-google-services. Make sure it is installed manually via NPM.
```

#### Steps to Reproduce 

1. Have an app that has been working for a long time with phonegap-plugin-push `^2.2.0`
2. Try to do a fresh build today, npm will fetch `2.2.3` and will fail to install the plugin because of the missing dependency

I'm not sure if this plugin is using strict semver versioning, but this patch release breaks existing apps as described above. They will need to be changed to use an exact version (2.2.2), or install this new dependency.

In addition, there is currently no documentation for the change in installation requirements for new apps.

**Comment by MichaelMarner** [comment]
Here is the relevant PR that added this dependency:

https://github.com/phonegap/phonegap-plugin-push/pull/2293

**Comment by macdonst** [comment]
@MichaelMarner Can you give me more details on `do a fresh build`? I'm trying to reproduce the issue but haven't hit upon the correct incantation.

**Comment by MichaelMarner** [comment]
This error came from our CI machines but I also replicated it locally. In this case a fresh build means:

1. Checkout source code from git
2. `npm install`
3. `cordova platform add android` (or iOS)

Fails when installing the push plugin with the error noted above.

**Comment by MichaelMarner** [comment]
Hey thanks for your time but I think this may have been an issue with our CI environment or some kind of caching issue. I've spent a bit of time looking into it and have found the google support plugin being added automatically when adding the platform:

```
Discovered plugin "phonegap-plugin-push" in config.xml. Adding it to the project
Installing "phonegap-plugin-push" for android
Installing "cordova-support-google-services" for android
```

Sorry for the mis-report.

**Comment by macdonst** [comment]
@MichaelMarner okay, no problem. I'm just glad it got sorted for you.
