### ISSUE TITLE
Is it possible to update PHONEGAP_BUILD.md?

### ISSUE THREAD

**Issue by vgalisson** [phonegap/phonegap-plugin-push#2388]
This is not really an issue but more a request for clarification. (I was not sure where I should ask for this)

On the [PHONEGAP_BUILD.md](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md) , it is stated that PhoneGap Build support version 1.9.0 and I've found on [phonegap.com blog](https://blog.phonegap.com/phonegap-7-0-1-now-on-build-and-it-includes-some-important-changes-89087fe465f5) that the 2.0.0 version is also supported.

I was wondering if you could update the PHONEGAP_BUILD.md to the latest support ?

Thanks in advance and have a nice day !

**Comment by macdonst** [comment]
@vgalisson yeah, that is a confusing line. I've just removed it. PGB supports the latest version of the plugin. Originally I added that line as PGB didn't support later versions of the plugin but that's long been fixed.

**Comment by jcesarmobile** [comment]
Not really latest as latest require cordova-android 7.1.0, which is not available on PGB yet, so you have to use a version <2.2.0

**Comment by vgalisson** [comment]
@jcesarmobile that's what I thought, thanks

**Comment by macdonst** [comment]
I reached out to the PGB team to find out what's up. I'll report back later.

**Comment by jcesarmobile** [comment]
@macdonst there is nothing "wrong" with PGB, as far as I know it only allows to configure the CLI version, not the  engine version. So, as latest CLI (8.0.0), pins cordova-android 7.0.0. there is no way of using cordova-android 7.1.0 until a new CLI is released and added to PGB.

**Comment by macdonst** [comment]
@jcesarmobile yeah, I'm asking when the new cordova-android will be supported.

**Comment by jcesarmobile** [comment]
It needs a new CLI which doesn't exist yet as latest pin cordova-android 7.0.0, unless they can pin a different version from the default one
