### ISSUE TITLE
Migrating to latest version of this plugin

### ISSUE THREAD

**Issue by stib** [phonegap/phonegap-plugin-push#2390]
#### Cordova CLI version and cordova platform version

    cordova --version                                    7.1.0
    cordova platform version android (6.3.0) iOS (4.5.4)

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.10.5

I noticed that more recent versions of Android are not getting push notifications through my App using 1.10.5 version of this plugin. Reading through the issues on this forum I understand I need to upgrade the plugin. I have two questions.

1. What is the version I can upgrade to without having to make too many changes to my App and have notifications work in more recent Android versions? Can I move to the most recent version 2.2.2, or perhaps 2.2.3 released a few days back? Or are there any significant changes required in moving to 2.x version from 1.10.x.
2. Do I need to move from GCM to FCM to use a more recent version of this plugin? On a related note, and sorry for the basic nature of this question, how do I know if my App is using GCM or FCM? Part of the reason I ask is because when I go to Firebase to try to migrate the project to FCM (as indicated in a FireCast video) I don't see that as an option which makes me wonder if I am already using FCM.

I understand that GCM won't work after April 2019 so, if needed, I am looking to move to FCM sooner than later.

Thanks,
Sanjay.

**Comment by mattheuspirovani** [comment]
Try to upgrade to 1.10.6, it works for me...

**Comment by macdonst** [comment]
@stib if by recent versions of Android you mean Android 8+ then yes, support for message channels which are required by Android 8 are introduced in the 2.1.0 version of the plugin. 

1) There are no API level changes with the plugin. Instead of passing a SENDER_ID in at run time you need to supply a google-services.json file at build time.
2) You should still be able to send a GCM push to a device registered for FCM but upgrading the project to FCM is not terribly difficult. If you are going to Firebase you are probably already using FCM. Are you able to generate a google-services.json file from that project?

**Comment by stib** [comment]
@macdonst thank you for the info. I generated the google-services.json file a while back and have that in my project. The changes I see from Installation section of your documentation for the plugin are

1. Add this to the ios section of the config.xml
```
<platform name="ios">
  <resource-file src="GoogleService-Info.plist" />
</platform>
```
This file has been use from the beginning so I am assuming the addition to the config.xml is a requirement for the new version of the plugin
2. Add this to the android section of the config.xml
```
<platform name="android">
  <resource-file src="google-services.json" target="app/google-services.json" />
</platform>
```
Same as Info.plist - don't have this in config.xml and will add - assuming it is a requirement for the new version of the plugin
3. I have this in package.json already so that should be good
```
    {
      "variables": {
        "SENDER_ID": "XXXX"
      },
      "locator": "phonegap-plugin-push"
    },
```
Is there anything else I need to do, besides the three things above, to make sure I am using the new version of plugin correctly and also using FCM? On a related note, how do I know if I the plugin is using GCM or FCM?

Thank you for your thoughts.
Sanjay.

**Comment by macdonst** [comment]
@stib you only need to do 1 and 2. Adding the resource file lines into your config.xml will deliver the file to the right spot.

**Comment by stib** [comment]
Thanks @macdonst 

1. Should I remove the entry in package.json (3 above) or leave it there or it doesn't matter? It's been there so far.
2. I don't see an app directory in my ionic App (it's ionic v1). So where should google-services.json target for android point to?
3. If I have different Firebase projects for Development and Production what's the best way to switch the google-services.json and GoogleService-Info.plist files above?
4. Trying to understand how to make sure or find out if I am using GCM or FCM. Would be great if you have any pointers on that.

Thank you for your help.
Sanjay.

**Comment by macdonst** [comment]
@stib I think you are going to need to ask for help on the Ionic forums. There CLI works slightly differently than the Cordova/PhoneGap one.

**Comment by stib** [comment]
@macdonst to make sure I am not mixing things, are you referring to asking for help on Ionic forum with respect to where the google-services.json target for android should point to? Or were you referring to something else?

I hope I am not the first Ionic v1 user trying to use the updated version of this plugin.

**Comment by macdonst** [comment]
@stib I'm sure you are not but I don't know the Ionic CLI that well. I'm not sure if the resource file paths are 100% correct.
