### ISSUE TITLE
Plugin not chosing the right version on installation

### ISSUE THREAD

**Issue by andreszs** [phonegap/phonegap-plugin-push#2391]
### Expected Behaviour
Plugin installation should detect that the current environment is using cordova 6.5.0 and cordova-android 6.3.0 then proceed to install plugin version [1.11.1](https://github.com/phonegap/phonegap-plugin-push/releases/tag/v1.11.1) accordingly to the [Requirements](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements) table.

### Actual Behaviour
Plugin fails to locate a compatible version and proceeds installing the latest one (see log below)

#### Steps to Reproduce 

- Create new blank apache cordova app with CLI 6.5.0 and install its android platform (6.3.0).
- Install plugin normally.

#### Cordova CLI version and cordova platform version

- cordova 6.5.0
- cordova-android 6.3.0.

#### Logs taken while reproducing problem

```
Warning: Unmet project requirements for latest version of phonegap-plugin-push:
Calling plugman.fetch on plugin "phonegap-plugin-push"
Warning:     cordova-android (6.3.0 in project, >=7.1.0 required)
Warning:     cordova (6.5.0 in project, >=7.1.0 required)
Warning: Current project does not satisfy the engine requirements specified by any version of phonegap-plugin-push. Fetching latest version of plugin anyway (may be incompatible)
```

**Comment by macdonst** [comment]
@andreszs that's not the way the requirements table works. That's just me letting you know what versions of cordova are required by this plugin. The fix for pulling in the correct version of the plugin depending on what's in plugin.xml would be done in cordova proper.
