### ISSUE TITLE
FirebaseMessagingService() not called in background / Closed when push is sent with Firebase Functions

### ISSUE THREAD

**Issue by Martindgadr** [phonegap/phonegap-plugin-push#2394]
**Expected Behaviour**
Push notification arrived passing for FirebaseMessagingService() implemented class

**Actual Behaviour**
Push is received but it's not calling FirebaseMessagingService() implemented class, in order to run an specific logic inside this. Push is OK but not pass throw this class, it's estrange. 
Push is implemented in Firebase Function with: 
return admin.messaging().sendToDevice(tokens, payload, options)

**Steps to Reproduce** 
1) App runs, write Firestore database and trigger firebase functions service. 
2) first step run logic on it and push notification, notification is sent to corresponding device (token)
3) Notification arrive but not calling  FirebaseMessagingService() if APP is closed or in background.

**Platform and Version**
I run this on Android phones. 3 different versions: Android 5.0 L (lollipop), 6.0 M (Marshmallow), Android 8 (oreo)

**What device vendor**
- Samsung  
- Motorola 

**Sample Push Data Payload**
        let payload = {
            notification: {
                title: dataNode.title,
                body: dataNode.message,
                sound: 'default',
                content_available: 'true',
                badge: '1'
            }
        }

        const options = {
            priority: "high",
            timeToLive: 60 * 60 * 24 //24 hours
        }

**Sample Code that illustrates the problem**
Code is running OK, Push is receive into device but only works in Foreground mode. FirebaseMessagingService() implemented class only runs when app is running.

#### Logs taken while reproducing problem
N/C

**Comment by macdonst** [comment]
@Martindgadr it's explained here:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

Use `data` instead of `notification` for your push payload.
