### ISSUE TITLE
Sending using AWS Pinpoint Console Not Working

### ISSUE THREAD

**Issue by l1nknyto** [phonegap/phonegap-plugin-push#2397]
Hi all,

First of all, sorry if i am wrong for asking in here. I dont know where else to ask.

The problem is when i try to send direct message especially campaign message using AWS Pinpoint Console, i didn't receive any notification in my device. Although aws said message successfully sent.

But i am able to send push notification using aws-sdk library using AWS.Pinpoint.sendMessages. But with attributes RawContent. I cannot send if i am using the standard AWS.Pinpoint request message attributes, like title, body, data.
And there are no custom payload / raw content options in aws pinpoint console.

Is there any way to transform incoming data in phonegap-plugin-push, so it can be compatible with aws push notification format?

Any ideas are appreciated.

Thanks

### Expected Behaviour
Push notification from aws is showing in device.

### Actual Behaviour
Push notification from aws is not showing in device.

### Reproduce Scenario (including but not limited to)
Send using aws pinpoint console

#### Cordova CLI version and cordova platform version
    cordova --version                                    8.0.0
    cordova platform version android           6.4.0

#### Plugin version
    cordova plugin version | grep phonegap-plugin-push   2.1.3

**Comment by macdonst** [comment]
@l1nknyto no, you really need to send the push in the format this plugin will understand. For android is is a bit non standard but most push services can accommodate this. Have you collected logs on device to see if the push makes it to the device? `adb logcat | grep Push`

**Comment by l1nknyto** [comment]
@macdonst thanks for the clue.

Here the logs device after i send message from aws pinpoint console.

06-04 23:43:54.594 22694 22764 D Push_FCMService: onMessage - from: 632028123391
06-04 23:43:54.633 22694 22764 D Push_FCMService: normalize extras
06-04 23:43:54.633 22694 22764 D Push_FCMService: key = pinpoint.openApp
06-04 23:43:54.634 22694 22764 D Push_FCMService: replace key pinpoint.openApp with pinpoint.openApp
06-04 23:43:54.634 22694 22764 D Push_FCMService: key = pinpoint.notification.title
06-04 23:43:54.634 22694 22764 D Push_FCMService: replace key pinpoint.notification.title with pinpoint.notification.title
06-04 23:43:54.634 22694 22764 D Push_FCMService: key = pinpoint.notification.body
06-04 23:43:54.634 22694 22764 D Push_FCMService: replace key pinpoint.notification.body with pinpoint.notification.body
06-04 23:43:54.635 22694 22764 D Push_FCMService: key = pinpoint.campaign.campaign_id
06-04 23:43:54.635 22694 22764 D Push_FCMService: replace key pinpoint.campaign.campaign_id with pinpoint.campaign.campaign_id
06-04 23:43:54.635 22694 22764 D Push_FCMService: key = pinpoint.notification.silentPush
06-04 23:43:54.635 22694 22764 D Push_FCMService: replace key pinpoint.notification.silentPush with pinpoint.notification.silentPush
06-04 23:43:54.636 22694 22764 D Push_FCMService: background
06-04 23:43:54.636 22694 22764 D Push_FCMService: message =[null]
06-04 23:43:54.636 22694 22764 D Push_FCMService: title =[null]
06-04 23:43:54.636 22694 22764 D Push_FCMService: contentAvailable =[null]
06-04 23:43:54.637 22694 22764 D Push_FCMService: forceStart =[null]

So what next that i have to do?

**Comment by macdonst** [comment]
@l1nknyto ooof, yeah there you go. You can see that Amazon Pinpoint is sending the payload with `pinpoint.notification` as the prefix to important attributes like `title` and `body`. We'd need to add something into [this section of the code](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/android/com/adobe/phonegap/push/FCMService.java#L196) in order to normalize the keys.

**Comment by l1nknyto** [comment]
Owh , so `pinpoint.notification.title` or `pinpoint.notification.body` need to replace with this plugin canonical value.

I haven't code for cordova plugin before.
Can we make create a mapping for those value (and others keys) in config.xml?

**Comment by macdonst** [comment]
@l1nknyto basically you'd need to add an else clause in the code I linked to above like so:

```java
    } else if (key.startsWith("pinpoint.notification")) {
      return key.substring("pinpoint.notification".length() + 1, key.length());
    }
```

That should normalize all the keys coming from Amazon Pinpoint. It would be awesome if you could take this on with a PR as you are already setup to test the fix.

**Comment by l1nknyto** [comment]
@macdonst ok, thanks for your help

**Comment by macdonst** [comment]
@l1nknyto merged your PR. Please install the plugin from master and give it a test. Let me know how that works for you and I'll do a point release.

**Comment by l1nknyto** [comment]
@macdonst i am done with test using plugin from master.
It works fine.
Thanks

**Comment by l1nknyto** [comment]
@macdonst sorry to reopened

I trying to send "Picture Messages" using aws pinpoint console.
Picture is not showing . I am try to normalizeKey again but no successfull.
AWS is sending "pinpoint.notification.imageUrl", i already change into :

```
  "style": "picture",
  "picture": "http://someimage.jpg",
```
Here is some changes that i made

```
private String normalizeKey(String key, String messageKey, String titleKey, Bundle newExtras) {
  ...
  } else if (key.equals("pinpoint.notification.imageUrl")) {
    newExtras.putString(STYLE, STYLE_PICTURE);
    return PICTURE;
  ...

private void setNotificationMessage(int notId, Bundle extras, NotificationCompat.Builder mBuilder) {
  ...
  } else if (STYLE_PICTURE.equals(style)) {
    // i am success to enter here, but picture still not showing
   Log.d(LOG_TAG, "PICTURE : " + extras.getString(PICTURE)); // image url value is exists

```

What else that i have been missing?
Thanks

**Comment by macdonst** [comment]
@l1nknyto yeah, send a PR for the fix for picture messages.

For opening a url you just handle it in the `on('notification')` event. Find the url in `data.additionalData.url` and set the `document.location.href` accordingly or whatever method your app uses to move to a new page.

**Comment by l1nknyto** [comment]
ok, thank you for the info.

i am done sent a PR.

Thanks.

**Comment by macdonst** [comment]
@l1nknyto merged and closing again. I should be doing a new release soon.
