### ISSUE TITLE
Event not fired when in background

### ISSUE THREAD

**Issue by lucadegasperi** [phonegap/phonegap-plugin-push#24]
Hello,

I'm developing an iOS app and the notifications appear on the device regularly, problem is the application badge doesn't appear, despite it being in the notification payload. Logging in the lldb console reveals that the function never gets called when in background.

Do I need to set any flag or move the plugin outside the device ready event?

I'm running iOS 7.1 on an iPhone 4.

**Comment by macdonst** [comment]
@lucadegasperi I can't seem to reproduce this problem. When I send:

```
{
    "aps" : {
        "alert" : "You got your emails.",
        "badge" : 9
    }
}
```

The badge is correctly updated. However, I have noticed if I put quotes around the number 9 then it does not work as we are expecting a number not a string.

**Comment by lucadegasperi** [comment]
I mean, are there differences between iOS7 and iOS8 way of handling notifications? because the notification pops on the device but no badge is set.

**Comment by macdonst** [comment]
@lucadegasperi it should work the same. My iOS 7 device is at home right now so I can't test until tomorrow.

**Comment by lucadegasperi** [comment]
Thanks :) if it works i would love to see the code you used to make the test. Thanks again!

**Comment by macdonst** [comment]
@lucadegasperi Yeah, I was able to reproduce it. I'll be checking in a fix shortly and will get a new release out this week.
