### ISSUE TITLE
Invalid Device Token Generated

### ISSUE THREAD

**Issue by mitesh140888** [phonegap/phonegap-plugin-push#2400]
### Expected Behaviour
iOS device id should be in length of 64 characters

### Actual Behaviour
iOS device is in length of 152 characters

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS (10.3.3)

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPhone 5,4

#### Cordova CLI version and cordova platform version

cordova vesion 6.3.1 

#### Plugin version

phonegap push notification version 2.2.3   

#### Sample Code that illustrates the problem
var  push = PushNotification.init({
 ios: {
             senderID": "1111111XXXXX",
            "gcmSandbox": "true",
            "alert": "true",
            "badge": "true",
            "sound": "true"
	} });

 push.on('registration', function (data) {
              alert(data.registrationId);
            });

 I am using below technologies 
=========================
1. Firebase Cloud Messaging
2. APNS

on alert i am getting below token id which shows invalid when sending Notification through APNS
TokenId: 
 flyd2p6r6kU:APA91bH8tS96lYItuIh_2aqrLGxbi9s6D0NOBLPoYia-hBV7n1bGI4o2bJxaCea4iu3AtSeKOuSl7dUFtJB2xlUlfolJSBWhKpL8cumGFb34gTTwMjaKccBexPDPWfqYxgXnETsKB0lC

above token id is of length 152, but it should be 64 in length

Thanks.

**Comment by jcesarmobile** [comment]
If you use FCM you get a FCM token, not an APNs token.
FCM tokens look like that.

**Comment by mitesh140888** [comment]
Hey jcesarmobile, Thanks for your reply.

Now I have setup FCM, and i am testing notification using above token id.
Using Firebase Message Composer, i was able to send notification successfully. (No Error)

But Notification is not receiving in my iOS device.

What can be the problem here???

I have used below code for receiving notification.

push.on('notification', function(data) {
  alert(data.title);
 alert(data.message)
});

**Comment by mitesh140888** [comment]
Thanks jcesarmobile

in iOS its working now.

Please close this.
