### ISSUE TITLE
Facing issue when generating build

### ISSUE THREAD

**Issue by vaishalivc** [phonegap/phonegap-plugin-push#2406]
Here I am having my ionic project with fire-base configuration, also I want to test that application in Android device, so I use command: ionic cordova build Android --prod. When I try to generate Android build, it through an error which is written below:

    [12:07:49]  lint finished in 3.15 s
    publishNonDefault is deprecated and has no effect anymore. All variants are now published.

    +-----------------------------------------------------------------
    | cordova-android-play-services-gradle-release: 15.+
    +-----------------------------------------------------------------
    Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
    The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
            at build_ans61jsqxp3a561faadhq188o.run(D:\ionicProjects\ionicFirebase\platforms\android\app\build.gradle:146)

    FAILURE: Build failed with an exception.

    * Where:
    Script 'D:\ionicProjects\ionicFirebase\platforms\android\cordova-support-google-services\starter-build.gradle' line: 16

    * What went wrong:
    A problem occurred evaluating project ':app'.
    > Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
       > For input string: "+"

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 0s
    (node:8196) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
    FAILURE: Build failed with an exception.

    * Where:
    Script 'D:\ionicProjects\ionicFirebase\platforms\android\cordova-support-google-services\starter-build.gradle' line: 16

    * What went wrong:
    A problem occurred evaluating project ':app'.
    > Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
       > For input string: "+"

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 0s
        at ChildProcess.whenDone (D:\ionicProjects\ionicFirebase\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
        at ChildProcess.emit (events.js:160:13)
        at maybeClose (internal/child_process.js:943:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
    (node:8196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
    (node:8196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jcesarmobile** [comment]
Closing as the issue doesn't follow the template and I'm pretty sure the + problem was already fixed on latest version

**Comment by vaishalivc** [comment]
i'll implement that solution but its not work for me
