### ISSUE TITLE
Facing issue when generating build

### ISSUE THREAD

**Issue by vaishalivc** [phonegap/phonegap-plugin-push#2407]
Here I am having my ionic project with fire-base configuration, also I want to test that application in Android device, so I use command: ionic cordova build Android --prod. When I try to generate Android build, it through an error which is written below:

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\ionicProjects\ionicFirebase\platforms\android\app\build.gradle' line: 96

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not find com.android.tools.build:gradle:11.6.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/11.6.0/gradle-11.6.0.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/11.6.0/gradle-11.6.0.jar
         https://repo1.maven.org/maven2/com/android/tools/build/gradle/11.6.0/gradle-11.6.0.pom
         https://repo1.maven.org/maven2/com/android/tools/build/gradle/11.6.0/gradle-11.6.0.jar
     Required by:
         unspecified:unspecified:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
    at ChildProcess.whenDone (D:\ionicProjects\ionicFirebase\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
(node:6100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jcesarmobile** [comment]
Closing as it doesn't follow the issue template.

Your problem is probably there

`Build file 'D:\ionicProjects\ionicFirebase\platforms\android\app\build.gradle' line: 96`
