### ISSUE TITLE
Plugin throwing build error in Andriod and IOS platform

### ISSUE THREAD

**Issue by Gamerakki** [phonegap/phonegap-plugin-push#2408]
### Expected Behaviour
The plugin should allow the platform to run properly
### Actual Behaviour
The build fail in Android and ios
FOR IOS 👍 
** BUILD FAILED **

The following build commands failed:
	Ld build/emulator/Common\ Areas.app/Common\ Areas normal x86_64
(1 failure)
(node:8865) UnhandledPromiseRejectionWarning: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/admin/Projects/commonarea/commonareas-phonegap/platforms/ios/cordova/build-debug.xcconfig,-workspace,Common Areas.xcworkspace,-scheme,Common Areas,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone X,build,CONFIGURATION_BUILD_DIR=/Users/admin/Projects/commonarea/commonareas-phonegap/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/admin/Projects/commonarea/commonareas-phonegap/platforms/ios/build/sharedpch
(node:8865) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8865) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Reproduce Scenario (including but not limited to)
Install the plugin for platform ios@4.5.4
cordova 7.0.0
#### Steps to Reproduce 
run the cordova command for installing the plugin
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8.0 and ios 11.2
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Mi A1
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1
cordova version 7.0.0 
cordova android versions 6.4.0
cordova ios 4.5.4
#### Plugin version
plugin verision 2.1.3
    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@Gamerakki please upgrade to cordova CLI 7.1.0. Plugin 2.1.x or higher [requires it](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements). If that fixes the issue please close this issue.

**Comment by gersonmontenegro** [comment]
I have cordova 8.0.0 and still I got this message:
```
Plugin doesn't support this project's cordova-android version. cordova-android: 7.0.0, failed version requirement: >=7.1.0
Skipping 'phonegap-plugin-push' for android
```
When I execute cordova -v, I got:
8.0.0
What can be?

**Comment by macdonst** [comment]
@gersonmontenegro do `cordova platforms` and you will see you have cordova-android 7.0.0. You would need to do:

```
cordova platform rm android
cordova platform add android@7.1.0
```

Then try adding the push plugin to your repo.

**Comment by Gamerakki** [comment]
@macdonst Thnx you for reply its working now so closing this issue
