### ISSUE TITLE
Error PushNotification is not defined

### ISSUE THREAD

**Issue by mitesh140888** [phonegap/phonegap-plugin-push#2410]
### Expected Behaviour
Device Token id i.e. RegistrationId should be created

### Actual Behaviour
PushNotification is not defined

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4.2

#### Cordova CLI version and cordova platform version
Cordova version 6.3.1

#### Plugin version
phonegap-plugin-push latest version

#### Sample Code that illustrates the problem
on debug its show error as  PushNotification not defined

var pushNotification = PushNotification.init({
                                           android: {
                                           senderID: "1234567890",   
                                           icon: 'logo.png',   
                                           iconColor: '#248BD0' 
                                           }
     });

pushNotification.on('registration', function (data) {
    alert(data.registrationId);
});

**Comment by Zyostes** [comment]
I just had this error.
I solved it when I put PushNotification init in onDeviceReady cordova function. Did you try ?

**Comment by jcesarmobile** [comment]
You are using an old cordova version, so the plugin is not being installed because it requires a new Cordova to work.
Update Cordova or downgrade the plugin to a compatible version
