### ISSUE TITLE
Build fails when using plugin because multidex.jar and common.jar cannot be resolved

### ISSUE THREAD

**Issue by LachlanRidley** [phonegap/phonegap-plugin-push#2412]
### Expected Behaviour

App is build

### Actual Behaviour

App is not built because it cannot find required .jar files.

#### Steps to Reproduce 

1. Create new Cordova project.
2. Add Android@7.1.0: `cordova platform add android@7.1.0`
3. Supply project with `google-services.json`
4. Add phonegap-push-plugin: `cordova plugin add phonegap-plugin-push`
5. Build app: `cordova build android`

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

n/a

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

n/a

#### Cordova CLI version and cordova platform version

    cordova --version: 8.0.0
    cordova platform version android: android 7.1.0

#### Plugin version

    phonegap-plugin-push 2.2.3 "PushPlugin"

#### Sample Push Data Payload

n/a

#### Sample Code that illustrates the problem

n/a

#### Logs taken while reproducing problem

    * What went wrong:
    Could not resolve all files for configuration ':app:debugCompileClasspath'.
    > Could not find multidex.jar (com.android.support:multidex:1.0.2).
      Searched in the following locations:
          https://jcenter.bintray.com/com/android/support/multidex/1.0.2/multidex-1.0.2.jar
    > Could not find common.jar (android.arch.core:common:1.1.0).
      Searched in the following locations:
          https://jcenter.bintray.com/android/arch/core/common/1.1.0/common-1.1.0.jar

**Comment by phonic** [comment]
I have had the same problem, I guess, it depends on cordova platform 7.1.0. 

So, try to remove platform and plugin directory and rebuild everything from scratch by running cordova platform add android@7.0.0 and build your project again.

**Comment by macdonst** [comment]
@LachlanRidley I started a new project from scratch using the same version of the cordova CLI and following your steps. Unfortunately, I can't reproduce it. I checked jcenter and those packages are available.

**Comment by phonic** [comment]
@macdonst @LachlanRidley  Ive started a new project using all the same versions of tools and I do get the same error message! I've tested around with different plugin and cordova versions but the effect is always the same. Maybe its some android sdk related problem?

**Comment by WHI-CH** [comment]
Having the same issue with Phonegap Build (even though it still worked yesterday).
Phonegap Build doesn't yet support android 7.1.0 (newest version = 7.0.0), but the build worked with spec="2.1.3" until today :(

**Comment by phonic** [comment]
Found a solution.

The order of repositories in the build.gradle (maven and jcenter) seems to be wrong. Change the order so that maven is in place before jcenter. Then your project builds successfully...

Don't know how to solve that without manually editing. Whats necessary to build up the repos in the correct order?

Heres my buildscript from build.gradle after changing the repo order:

`buildscript {
    repositories {
        maven {
            url "https://maven.google.com"
        }
		jcenter()        
    }
    dependencies {

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}

allprojects {
    repositories {
		maven {
            url "https://maven.google.com"
        }
        jcenter()        
    }
    //This replaces project.properties w.r.t. build settings
    project.ext {
      defaultBuildToolsVersion="27.0.1" //String
      defaultMinSdkVersion=19 //Integer - Minimum requirement is Android 4.4
      defaultTargetSdkVersion=27 //Integer - We ALWAYS target the latest by default
      defaultCompileSdkVersion=27 //Integer - We ALWAYS compile with the latest by default
    }
}`

**Comment by macdonst** [comment]
@WHI-CH PGB does not support 2.2.x stream of this plugin as it doesn't yet have cordova-android 7.1.0. You are stuck on 2.1.x.

**Comment by WHI-CH** [comment]
Yes, that's what I was saying ;)
Until yesterday a build with spec 2.1.3 worked

**Comment by phonic** [comment]
@macdonst germany

**Comment by WHI-CH** [comment]
@macdonst Austria

**Comment by macdonst** [comment]
@phonic and I'm in Canada. 

My build.gradle is:

```
repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
```

for both `buildscript` and `allprojects`.

**Comment by LachlanRidley** [comment]
Will try out some of these solutions later and report back with findings :)

@macdonst I'm in New Zealand.

**Comment by LachlanRidley** [comment]
@phonic Tested this solution and it works perfectly!

**Comment by pandazii** [comment]
Put maven above jcenter()
Works for me :)

```
   jcenter()
        maven {
            url "https://maven.google.com"
        }
```

**Comment by macdonst** [comment]
**ALL:** Apparently this is an issue with jcenter. 

https://twitter.com/bintray/status/1004974875851685888

There's nothing I can do to fix it in this plugin but I have raised on issue on cordova-android.

https://issues.apache.org/jira/browse/CB-14127

**Comment by jcesarmobile** [comment]
Cool @macdonst, I was going to create the issue, but you were faster.
I've sent a PR https://github.com/apache/cordova-android/pull/450

**Comment by macdonst** [comment]
👍
