### ISSUE TITLE
How to monitor token refresh

### ISSUE THREAD

**Issue by kkaczmarzyk** [phonegap/phonegap-plugin-push#2415]
As it is stated here https://firebase.google.com/docs/cloud-messaging/js/client#monitor-token-refresh firebase token can be changed but i don't see anything in API that helps to deal with it. How to approach this?

**Comment by macdonst** [comment]
@kkaczmarzyk the `on('registration')` event is fired if there is a token refresh. Each time you get a `registration` event you need to check to see if the value is different than the one you previously had. If so, send it to the server.
