### ISSUE TITLE
Event ask permissions

### ISSUE THREAD

**Issue by tmwebs** [phonegap/phonegap-plugin-push#2420]
### Expected Behaviour
I hope to call the PushNotification.init function after allowing notification on iOS

### Actual Behaviour
When my application starts for the first time, I do not get the registrationId because it runs before I 
agree to allow notifications

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
cordova iOS 4.5.4

#### Cordova CLI version and cordova platform version
    cordova --version                               8.0.0
    cordova platform version iOS            4.5.4

#### Plugin version

    phonegap-plugin-push   2.2.3

My question is if there is an event that runs once I agree to allow notifications to be able to call PushNotification.init again. Thanks

**Comment by Limoli** [comment]
It's PushNotification.init that triggers the popup in iOS to allow the push notification permission.

**Comment by tmwebs** [comment]
then, how can I recover call push.on ('registration', function (data) {}) once I have agreed to allow notifications in the popup?

**Comment by Limoli** [comment]
As I have experienced, the flow is the following:
- init() triggers permission popup and returns you the push object
- after the init you register the events (registration, notification, error)
If the permission is allowed, the registration will execute the handler of registration event.

**Comment by tmwebs** [comment]
I'll put my case:

<pre>
  document.addEventListener("deviceready", function() {
      setupPush();
  });

  function setupPush(){
    var push = PushNotification.init({
        "android": {
            "senderID": "491XXXXX8069"
        },
        "browser": {},
        "ios": {
            "sound": true,
            "vibration": true,
            "badge": true
        },
        "windows": {} 
    });

    push.on('registration', function(data) {
      console.log('----> registration event: ' + data.registrationId);
      var oldRegId = localStorage.getItem('uppilates_registrationId');
      if (oldRegId !== data.registrationId) {
          localStorage.setItem('uppilates_registrationId', data.registrationId);
      }
    });

    push.on('error', function(e) {
      console.log("----> push error = " + e.message);
    });

    push.on('notification', function(data) {
      navigator.notification.alert(
          data.message,         // message
          null,                 // callback
          data.title,           // title
          'Ok'                  // buttonName
      );
   });
  }//setupPush
</pre>

When you start the APP, call init, it shows me the popup to allow notifications, then, without having clicked on anything in the popup, it does not show me the registration event, I have to call setupPush just before doing the login so that if you give me the registration event

**Comment by Limoli** [comment]
Of course the registration is triggered if you allow permission!

**Comment by tmwebs** [comment]
Ok, I allow the permission and it does not execute registration, it does not show in the console the id, the data.registrationId

**Comment by macdonst** [comment]
@tmwebs you should see the registration event fired after you agree to permissions to receive push notifications. Just out of curiosity, are you testing on the iOS simulator? That won't work because push is not supported in the simulator.

**Comment by tmwebs** [comment]
Yes, I'm testing in the Xcode simulator

**Comment by macdonst** [comment]
@tmwebs all tests in the simulator are invalid as it doesn't support push notifications. You have to test them on a real device. I'm going to close this issue now.

**Comment by tmwebs** [comment]
OK thanks
