### ISSUE TITLE
Update com.google.firebase:firebase-messaging to 17?

### ISSUE THREAD

**Issue by chemerisuk** [phonegap/phonegap-plugin-push#2423]
Recently google updated `google-services plugin` to version 4. The reason of such update was to rollback version ranges they've introduced before (read "Version Ranges Removed" at https://developers.google.com/android/guides/releases). As a part of release they've dropped support for play service libraries lower version 14 (read https://firebase.google.com/support/release-notes/android).

I released version 1.2 of `cordova-support-google-services` that upgrades `google-services plugin` library to version 4. Personally I haven't had any issue with version ranges, but it's possible for other people.

Not sure if this project is capable with `com.google.firebase:firebase-messaging:17.0.0` because now the library version fixed in `plugin.xml`. On the other hand it's good to update source code to the latest version... What do you think? Then I'll submit a PR for `cordova-support-google-services` version update.

**Comment by macdonst** [comment]
@chemerisuk yeah, go ahead and submit a PR to update the dependencies. The FCM version defaults to 11.6.2 but it can be overridden by using variable property in config.xml.

**Comment by chemerisuk** [comment]
@macdonst PR was submitted https://github.com/phonegap/phonegap-plugin-push/pull/2425
