### ISSUE TITLE
What plugin version is needed to use FCM rather than APNS?

### ISSUE THREAD

**Issue by andreszs** [phonegap/phonegap-plugin-push#2428]
According to the README:

> By default, on iOS, the plugin will register with APNS. If you want to use FCM on iOS, in the platform tag for iOS add the resource-file tag

I have the plugin 1.11.1 and the `<resource-file src="GoogleService-Info.plist" />` tag in config.xml but the plugin still registers with APNS, not FCM. Does this work with a newer plugin version only? Which one?

**Comment by macdonst** [comment]
@andreszs FCM support is in the 2.x stream of the plugin. v1.x of the plugin connects to APNS or GCM.
