### ISSUE TITLE
Open right page when callback was clicked

### ISSUE THREAD

**Issue by ttibau** [phonegap/phonegap-plugin-push#2429]
### Expected Behaviour
When user click in some button on notification, open the right page for this callback
### Actual Behaviour
The notification handled with
```js
push.on('callback').subscribe((notiication) =>
    this.router.navigate(['/flightSearchResults');
 })
```
### Reproduce Scenario (including but not limited to)
When app is closed and user click on the button, the app doesn't open.
When app is open and user click on the button, the page doesn't change.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.3.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Xiaomi Mi6 
#### Cordova CLI version and cordova platform version

    cordova --version
```8.0.0```

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push
```2.2.2```

#### Sample Push Data Payload

```
{
    "to": "xxx",
    
    "content_available": true,
    "data": {
        "title": "Sua chance de viajar é de 92%",
        "message": "Gostaria de alterar sua jogada?",
        "click_action": "FCM_Acao_principal", 
        "actions": [
          { "icon": "emailGuests", "title": "Sim", "callback": "app.emailGuests", "foreground": true},
          { "icon": "snooze", "title": "Comprar Agora", "callback": "app.comprarAgora", "foreground": false},
          { "icon": "snoozez", "title": "Melhorar Jogada", "callback": "app.melhorarJogada", "foreground": false}
    ]        
  }
}
```

**Comment by ttibau** [comment]
@fredgalvao  (Inhaê menn 🥇)

The `callback` value I put as an example, I am capturing a push and it is yes calling this event.

**Comment by fredgalvao** [comment]
So, if it's indeed calling the event you want, what's the issue then?

**Comment by macdonst** [comment]
@ttibau the action button for `app.comprarAgora` is set to foreground false so it won't bring the app to the foreground. Try setting that to true if you want the app to open and navigate to the correct page.

**Comment by ttibau** [comment]
@macdonst Thanks! It's Works.  ❤️ 
When I set **true** in **foreground** the action that's works! 
`{ "icon": "snoozez", "title": "Comprar agora", "callback": "app.comprarAgora", "foreground": true}
`
