### ISSUE TITLE
Not getting registration id on second launch (iOS)

### ISSUE THREAD

**Issue by jcesarmobile** [phonegap/phonegap-plugin-push#2436]
### Expected Behaviour
Always get registration id
### Actual Behaviour
Only getting registration id on first launch when accepting push permission
### Reproduce Scenario (including but not limited to)
create an app, add the plugin from github and call `PushNotification.init` and listen for push.on('registration')
#### Steps to Reproduce 
create an app, add the plugin from github and call `PushNotification.init` and listen for push.on('registration')

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
only tested on iOS 10.3.3

#### Cordova CLI version and cordova platform version

    cordova --version                                 8.0.0
    cordova platform version ios               ios 4.5.4

#### Plugin version
master branch (shown as 2.2.3)

#### Sample Push Data Payload
not applicable 

#### Sample Code that illustrates the problem
```
push.on('registration', function (data) {
    console.log(data.registrationId);
    console.log(data.registrationType);
});
```

#### Logs taken while reproducing problem
there is no log about the registration id neither on Xcode console

**Comment by macdonst** [comment]
Merged into master will be part of 3.0.0
