### ISSUE TITLE
Execution failed for task ':app:processDebugGoogleServices'

### ISSUE THREAD

**Issue by devil82426** [phonegap/phonegap-plugin-push#2439]
### Expected Behaviour
Work fine
### Actual Behaviour
Can not build successfully
#### Steps to Reproduce 
When I install and set up the config.xml file
<resource-file src="google-services.json" target="app/google-services.json" />
And then I build it,but get this error.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
ASUS
#### Cordova CLI version and cordova platform version

    cordova --version     8.0.0
    cordova platform version android     7.0.0
    node 9.6.1
    npm 5.7.1
    gradle 4.8
   

#### Plugin version

cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-whitelist 1.3.3 "Whitelist"
phonegap-plugin-barcodescanner 8.0.0 "BarcodeScanner"
phonegap-plugin-push 2.1.2 "PushPlugin"

#### Sample Code that illustrates the problem
I run this code
cordova run android --device

#### Logs taken while reproducing problem

`Parsing json file: /Users/devilmax/Desktop/testcordova/Anew/platforms/android/app/google-services.json
:app:processDebugGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'io.guava.wangnew'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
21 actionable tasks: 4 executed, 17 up-to-date
(node:58620) UnhandledPromiseRejectionWarning: Error: /Users/devilmax/Desktop/testcordova/Anew/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'io.guava.wangnew'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
    at ChildProcess.whenDone (/Users/devilmax/Desktop/testcordova/Anew/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:127:13)
    at maybeClose (internal/child_process.js:933:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:127:13)
    at Pipe._handle.close [as _onclose] (net.js:550:12)
(node:58620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:58620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

------
Has anyone known how to fix it? thank you!

**Comment by macdonst** [comment]
For those of you wondering what the resolution was, the package name in the google-services.json file `io.guava.wangnew` has to match the one in config.xml.
