### ISSUE TITLE
 on(notification) method not working when App is in foreground (only Android)

### ISSUE THREAD

**Issue by Juliocbr** [phonegap/phonegap-plugin-push#2440]
### Expected Behaviour

Receive notification when the app is active on Android. But method on(notification) is not working

### Actual Behaviour

Only notification is received if the app in Android is in the background. In iOS works well. Previously, I was able to receive push notifications without problems in Android, but I don't know if FCM updated something that is causing this problem.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 8.1.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Nexus 5X

#### Cordova CLI version and cordova platform version

cordova (Cordova CLI) : 7.1.0
ionic (Ionic CLI): 3.20.0
cordova android 6.4.0

#### Plugin version

phonegap-plugin-push: 2.1.3

#### Sample Code that illustrates the problem

```
initPushNotification() {
        if (!this.platform.is('cordova')) {
            console.warn('Push notifications not initialized. Cordova is not available - Run in physical device');
            return;
        }

        const options: PushOptions = {
            android: {
                senderID: '435244853402'
            },
            ios: {
                alert: 'true',
                badge: true,
                sound: 'true'
            },
            windows: {}
        };
        
        const pushObject: PushObject = this.push.init(options);
    
        pushObject.on('registration').subscribe(data => {
            console.log("device token: " + data.registrationId);
            this.storage.set('deviceToken', data.registrationId);
        });
    
        pushObject.on('notification').subscribe(data => {
            console.log(JSON.stringify(data));
        
            this.alertCtrl.create({
                buttons: ['OK'],
                title: data.title || null,
                message: data.message
            }).present();
        });
    
        pushObject.on('error').subscribe((e) => {
            console.error(e.message);
            console.error(JSON.stringify(e));
        });
    }
```
 I don't know if this issue is fixed in last version 2.2.3, but versions > 2.1.3 require cordova android version >= 7 and these versions have problems with some plugins that I use.

**Note:** I'm sending notifications through the FCM console so the message format is being sent correctly.

**Comment by macdonst** [comment]
@Juliocbr I'm pretty sure you are running into the [data vs notification](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads) issue. The FCM console puts stuff in `notification` which screws up this plugin. 

You can confirm this by running `adb logcat | grep Push` and reproducing the problem. Those logs should tell us if the plugin's FCM Service gets called.

Alternatively you can try testing by using a node-fcm script. The PAYLOAD.md doc has a bunch of examples.

**Comment by Juliocbr** [comment]
@macdonst I send this message to FCM:

**URL:**
POST https://fcm.googleapis.com/fcm/send

**HEADERS:**
Content-Type: application/json
Authorization: key=SERVER_KEY

**BODY:**
```
{
  "notification":{
    "title":"NOTIFICATION TITLE",
    "body":"NOTIFICATION BODY",
    "badge":"2"
  },
  "data":{
    "title":"NOTIFICATION TITLE",
    "message":"NOTIFICATION BODY",
    "count":"5"
  },
    "to":"device_token",
    "priority":"high"
}
```

Previously, this message worked well in background and foreground in Android. I try different options in [data vs notification](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads) but nothing works in foreground.

**Comment by macdonst** [comment]
@Juliocbr whelp, if you have `notification` in the payload the OS takes over. If you want the plugin to handle the push then use:

```
{
  "data":{
    "title":"NOTIFICATION TITLE",
    "message":"NOTIFICATION BODY",
    "count":"5"
  },
    "to":"device_token",
    "priority":"high"
}
```

Try that and let me know.

**Comment by Juliocbr** [comment]
@macdonst I managed to solve the problem of notifications in the foreground, removed the phonegap-pulgin-push and the android platform and reinstalled them. The body of the notification that brings the notification and the data were fine.
For some strange reason I could only receive notifications in the background, but doing the previous steps came back to work in the foreground.
Thanks for the help =)
