### ISSUE TITLE
After Installing version 2.0.0 my apps icon changed

### ISSUE THREAD

**Issue by samarroy** [phonegap/phonegap-plugin-push#2447]
### Expected Behaviour
It must show my apps icon
### Actual Behaviour
Apps icon changed when I minimize the app or when notification come cordova default icon showing. Also when I am sending push notification from server PHP then device not getting message though I am getting success message from FCM server.

Please help me on this.

Thanks 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Cordova 7.0 and Android 6.3.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Redmi and Moto G Series
#### Cordova CLI version and cordova platform version

    cordova --version              7.0.0                    
    cordova platform version android          6.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.0.0

**Comment by macdonst** [comment]
@samarroy I don't believe this is a problem with the plugin as it has nothing to do with the app's icon. As well I cannot reproduce this issue with a new project.
