### ISSUE TITLE
iOS Closed-App Click Action No Callback

### ISSUE THREAD

**Issue by Nick-lab** [phonegap/phonegap-plugin-push#2448]
### Expected Behaviour
If app is force closed and action button is pressed call back should be called.
### Actual Behaviour
In iOS the action button is not called if the app is force closed. Android works as expected.
### Reproduce Scenario (including but not limited to)
Setup action buttons with server sending required data e.g 
    iOS -
`notification: {
    click_action: '<click_action_name>'
}`
   Android -
`data: {
   actions: [
      { 'icon': 'something', 'title':'title of button', 'callback': 'callback', 'foreground':'false' },
      . . .
   ]
}`
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 11.4
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
n/a
#### Cordova CLI version and cordova platform version

    cordova --version                                   8.0.0
    cordova platform version android         n/a

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.2.3

#### Sample Code that illustrates the problem
```
 const options: PushOptions = {
        android: {
          clearBadge: true,
        },
        ios: {
          alert: 'true',
          badge: true,
          sound: true,
          categories: {
            okay: {
              yes: {
                callback: 'okay',
                title: 'Yes',
                foreground: false,
                destructive: false
              }
            },
            checkin: {
              yes: {
                callback: 'checkin',
                title: 'Ok',
                foreground: false,
                destructive: false
              }
            },
            clear: {
              yes: {
                callback: 'clear',
                title: 'Ok',
                foreground: false,
                destructive: false
              }
            }
          }
        },
        windows: {},
        browser: {
          pushServiceURL: 'http://push.api.phonegap.com/v1/push'
        }
      };

      const pushObject: PushObject = this.push.init(options);

      pushObject.on('checkin').subscribe((data: any) => {
        this.pushes = [];
        this.checkin(data.additionalData.info.notification, data.additionalData.info.push_id);
      });
```
#### Logs taken while reproducing problem
n/a

**Comment by Nick-lab** [comment]
hey just checking its been almost a month since opening this task.

**Comment by jcesarmobile** [comment]
🤷‍♂️

**Comment by dmnkgrc** [comment]
@Nick-lab I was able to fix this using the latest version of https://github.com/ionic-team/cordova-plugin-ionic-webview and adding <preference name="WKSuspendInBackground" value="false" /> to my config.xml, I hope this is helpful for you

**Comment by rychter** [comment]
++

**Comment by Nick-lab** [comment]
also for anybody that needs help with this check the requirements of @ionic-native/core to phonegap-plugin-push
