### ISSUE TITLE
Android- push event handler OR callbacks are called when new push received when app is in foreground

### ISSUE THREAD

**Issue by shri1983** [phonegap/phonegap-plugin-push#2453]
Hi,
Thanks in advanced. Please help me out for this problem. i don't want to call pushObject.on('notification') events when app is in foreground.

### Expected Behaviour
push event handler should not be called when new push message received when app is in foreground.
### Actual Behaviour
push event handler are called when new push received when app is in foreground
### Reproduce Scenario (including but not limited to)
Just send push message when app is in foreground and see pushObject.on('notification') is called
#### Steps to Reproduce 
Just send push message when app is in foreground and see pushObject.on('notification') is called
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.1.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Mi Not 4 (Android 6.0.1)
#### Cordova CLI version and cordova platform version

    cordova --version                                   8.0.0
    cordova platform version android                    android 7.1.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # 2.2.2

#### Sample Push Data Payload
{
  "message": "This offer expires at 11:30 or whatever",
  "title": "Test Notification",
  "additionalData": {
    "id": "class_id"
  }
}
#### Sample Code that illustrates the problem
 pushObject.on('notification').subscribe((notification: any) => {

      this.storage.get('showPush').then((val) => {

        if (val) {
          console.log('Your age is', val);
          console.log('New notification!', JSON.stringify(notification));

          let room_id = notification.additionalData.room_id;
          console.log(notification.additionalData.room_id);
          this.navCtrl.push(DetailsPage, { room_id: room_id });

        }
      });

    }

    );
#### Logs taken while reproducing problem
Not available

**Comment by macdonst** [comment]
@shri1983 sorry but calling the `notification` handler when the app is in the foreground is by design and we won't be changing it. You can choose not to do anything with the event though. If you check if `data.additionalData.foreground === true` in the notification handler you can choose to do nothing and exit the callback.

**Comment by shri1983** [comment]
Thanks for your response and time.
I have Implemented the same and its working fine now. But whenever i minimize the app by pressing home button, notifications received but when i tap on the message nothing happened. It should launch the app again or invoke the current page where i minimized the app. Please suggest.
