### ISSUE TITLE
Tapping on the notification doesn't open the app.

### ISSUE THREAD

**Issue by elicym** [phonegap/phonegap-plugin-push#2458]
### Expected Behaviour
Tapping on the notification should bring the app to the foreground.

### Actual Behaviour
The app continues to run in the background, invisibly.

### Reproduce Scenario (including but not limited to)
Any notification using 'data' has this issue. When I use 'notification' it works fine.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
google emulator

#### Cordova CLI version and cordova platform version
    cordova --version                                               8.0.0                         
    cordova platform version android                      6.4.0

#### Plugin version
    2.1.2

#### Sample Push Data Payload
{
	"data":{"title":"t1","message":"b1"},
	"to":"e9NiePIP65c:AP..."
}

#### Logs taken while reproducing problem
07-03 09:29:23.537  1658  1668 W ActivityManager: startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { flg=0x24000000 cmp=org.giftoflife.swabapp/com.adobe.phonegap.push.PushHandlerActivity (has extras) }
07-03 09:29:23.544  1658  1864 E ActivityManager: applyOptionsLocked: Unknown animationType=0
07-03 09:29:23.551  1658  3854 D WificondControl: Scan result ready event
07-03 09:29:23.556  3195  3195 D Push_HandlerActivity: not id = 0
07-03 09:29:23.557  3195  3195 V Push_HandlerActivity: onCreate
07-03 09:29:23.557  3195  3195 D Push_HandlerActivity: callback = null
07-03 09:29:23.557  3195  3195 D Push_HandlerActivity: dismissed = false
07-03 09:29:23.557  3195  3195 D Push_Plugin: convert extras to json
07-03 09:29:23.557  3195  3195 D Push_Plugin: key = actionCallback
07-03 09:29:23.558  3195  3195 D Push_Plugin: key = title
07-03 09:29:23.558  3195  3195 D Push_Plugin: key = dismissed
07-03 09:29:23.558  3195  3195 D Push_Plugin: key = message
07-03 09:29:23.558  3195  3195 D Push_Plugin: key = coldstart
07-03 09:29:23.558  3195  3195 D Push_Plugin: key = foreground
07-03 09:29:23.558  3195  3195 V Push_Plugin: extrasToJSON: {"title":"t1","message":"b1","additionalData":{"dismissed":false,"coldstart":false,"foreground":false}}
07-03 09:29:23.558  3195  3195 D Push_HandlerActivity: bringToForeground = true
07-03 09:29:23.560  3195  3234 D com.facebook.FacebookSdk: getGraphApiVersion: v3.0
07-03 09:29:23.567  1421  1421 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
07-03 09:29:23.570  3195  3195 D Push_HandlerActivity: isPushPluginActive = true
07-03 09:29:23.570  3195  3195 D Push_HandlerActivity: don't want main activity
07-03 09:29:23.628  1658  1679 E ViewRootImpl[swabapp]: Attempting to destroy the window while drawing!
07-03 09:29:23.628  1658  1679 E ViewRootImpl[swabapp]:   window=android.view.ViewRootImpl@83b4931, title=Splash Screen org.giftoflife.swabapp
07-03 09:29:23.634  1658  1864 I WindowManager: Failed to capture screenshot of Token{7be1eaf ActivityRecord{f1b668e u0 org.giftoflife.swabapp/com.adobe.phonegap.push.PushHandlerActivity t120 f}} appWin=Window{3861ac0 u0 Splash Screen org.giftoflife.swabapp} drawState=1

#### Other
AndroidLaunchMode is set to singleTop.

**Comment by macdonst** [comment]
@elicym Don't test on the emulator, use a real device. When sending to an Android 8 device you will need to specify the message channel. 

I'm going to mark this bug as invalid until you test using a real device.
