### ISSUE TITLE
Plugin doesn't work on android

### ISSUE THREAD

**Issue by Makumba666** [phonegap/phonegap-plugin-push#246]
Hi all,
Unfortunately this plugin does not work for me. There are no errors - push.on('error') is never trigerred,. Even more I was able to get registration token, send it to server and store in database. Problem is I can't send notification to phone. It does not seems to accept anything.  I am using php and curl to send notification (something like this: https://gist.github.com/prime31/5675017) and although there are no curl errors, device never receives anything.
Any advice?

**Comment by macdonst** [comment]
@Makumba666 it should be working then. So your 'notification' event is never called? Try running:

```
adb logcat | grep PushPlugin
```

to see what the plugin receives.

**Comment by Makumba666** [comment]
Sorry, but I don't know how to run it. I am c++ programmer and have zero experience in mobile development and to speed things up decided to use cordova instead messing with android studio and especially XCode. So, I have project in Visual Studio. Is it possible to run above commands from there?

**Comment by macdonst** [comment]
@Makumba666 no clue as I don't use Visual Studio. Google how to find android log information in Visual Studio. You are interested in the "PushPlugin" log tag.

**Comment by sebastiandanilonr** [comment]
@macdonst My problem it's similar on Android. I get the registration id and store it to the database, when i send a notification (using node) the notification reaches the phone, then i touch the notification but when the app opens none of the actions on the 'notification' event happen.

**Comment by mohitmayank** [comment]
you guys can use
https://play.google.com/store/apps/details?id=org.jtb.alogcat&hl=en

**Comment by macdonst** [comment]
@Makumba666 please re-open if you still have the problem on 1.4.0 and can provide a reproduction scenario.

**Comment by shuyye** [comment]
I still have the problem, I have migrated from the deprecated push plugin and I could get the token but I cannot send any notifications to it... even the token seems different and seems like a few characters has been added to it... Not sure if it's the plugin or an Android thing, but i'll have to go back to the deprecated plugin until this one will get stable... Soon I hope!

**Comment by macdonst** [comment]
@shuyye the reason the token is different is I have moved from the deprecated GCM way of getting the token to the new Instance ID way as recommended by Google. I have not had any problems being able to send notifications to 5 different Android devices I have on hand.

**Comment by shuyye** [comment]
@macdonst thanks for the response, much appreciated!

I think it may have something to do with using the old GCM js file sender that I have used with the previous plugin, I will try using the files from the examples it was probably a mistake on my behalf if so..
