### ISSUE TITLE
Push notification does not work on iOS

### ISSUE THREAD

**Issue by tmwebs** [phonegap/phonegap-plugin-push#2460]
### Expected Behaviour
Receive push notifications on iOS and Android

### Actual Behaviour
I have created an APP in iOS and Android, in Android it works correctly, but in iOS the notification does not arrive

### Reproduce Scenario (including but not limited to)
I am using Firebase, I have created the iOS certificates and on the https://pushtry.com page I have tried them and they are good at connecting.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 11

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPhone 6S

#### Cordova CLI version and cordova platform version

    cordova --version                                     8.0.0
    cordova platform version ios                  4.5.4

#### Plugin version

    phonegap-plugin-push 2.2.3 "PushPlugin"

#### Sample Push Data Payload
    cont push = PushNotification.init({
              "android": {
                  "senderID": "XXXXXXXX"
              },
              "browser": {},
              "ios": {
                  "sound": true,
                  "vibration": true,
                  "badge": true
              },
              "windows": {} 
          });
    push.on('registration', function(data) {
        console.log('----> registration event: ' + data.registrationId);
    });
    push.on('notification', function(data) {
            navigator.notification.alert(
                  data.message,         // message
                  null,                 // callback
                  data.title,           // title
                  'Ok'                  // buttonName
            );
    });

#### ERROR
The registration id opts correctly, but the notification does not arrive in iOS. Thank you

**Comment by jcesarmobile** [comment]
How does your token looks like?
Did you upload your certificate to firebase?
Did you app the google-services plist file to your app?

**Comment by tmwebs** [comment]
How does your token looks like?:

    fKvy5-nR4es:APA91bESiHQ_rkETVgedhLCZaHJF1QpLTLADeoPDT93o-cR3TbjMR9mDZ4TALoKEymqyP8dvTvWhCh9_CyqYdw9OG3Hz3pSAxLmJA0dhyyvqy3PBbmUa-An_ZtT9wlIAf3406BV0PG6eqhfTb42rXnGms2K9ivcQug

Did you upload your certificate to firebase?

    No, No, I try to upload the .p12 file but it tells me that it can not be read, however with
    openssl s_client -connect gateway.push.apple.com:2195 -cert TestPushCert.pem -key    TestPushKey.pem

    it tells me that the connection is correct

Did you app the google-services plist file to your app?

    Yes

**Comment by jcesarmobile** [comment]
You can't send push from Firebase if you don't upload the certificate there, if Firebase can't send the push notifications, then you won't receive them. 
It's not a plugin problem. Closing.

**Comment by tmwebs** [comment]
He uploaded the APNs authentication key and Cloud Messaging has worked, but since php is still not reaching iOS: 

    Connected to APNS 
    Resource id #3
    Message sent correctly: 175
