### ISSUE TITLE
Method to call latest push plugin functions in angularjs version 1.x.x

### ISSUE THREAD

**Issue by RajDW** [phonegap/phonegap-plugin-push#2461]
I'm using angularJS v1.x for my hybrid app.
The old push-plugin version was working perfectly. But I want to use FCM so I updated the plugin and migrated the google project to FCM.

Now, referring the latest push plugin api document it instructs to use

`const push = PushNotification.init({...`

But `const` and the pattern `(data)=>` is not used in angularjs 1.x.

Kindly, provide an alternative way or translation of this api.

Thanks

**Comment by macdonst** [comment]
@RajDW then you'd just use ES5 style JS like:

```
var push = PushNotification.init({...
```

and `function(data) { … }`

**Comment by RajDW** [comment]
Thanks a lot.

I have added `google-service.json` file to the root folder of the project.
But still `PushNotification.init({...` is not responding. 
I'm using Onsen UI, Cordova Version : 6.2.0
If I use try catch on init function it just says **ERROR**
PushPlugin version 1 was working perfectly.....

Should I add some thing to my config.xml ?

Below is my project structure :
![screenshot at jul 04 13-08-24](https://user-images.githubusercontent.com/40794549/42263342-5f07a78e-7f8b-11e8-9bfc-7bdf34f671d1.png)
