### ISSUE TITLE
While pressed home button and tap on push message, nothing happened. It should invoke the application

### ISSUE THREAD

**Issue by shri1983** [phonegap/phonegap-plugin-push#2463]
Hi,
Thanks in advanced.
Whenever i minimize the app by pressing home button, notifications received but when i tap on the message nothing happened. It should launch the app again or invoke the current page where i minimized the app. Please suggest.

**Expected Behaviour**
push event handler should not be called when new push message received when app is in foreground.

**Actual Behaviour**
push event handler are called when new push received when app is in foreground

**Reproduce Scenario (including but not limited to)**
Just send push message when app is in foreground and see pushObject.on('notification') is called

**Steps to Reproduce**
Just send push message when app is in foreground and see pushObject.on('notification') is called

**Platform and Version (eg. Android 5.0 or iOS 9.2.1)**
Android 7.1.0

(Android) What device vendor (e.g. Samsung, HTC, Sony...)
Mi Not 4 (Android 6.0.1)

**Cordova CLI version and cordova platform version**
cordova --version                                   8.0.0
cordova platform version android                    android 7.1.0
Plugin version
cordova plugin version | grep phonegap-plugin-push   # 2.2.2

**Sample Push Data Payload**
```
{
"message": "This offer expires at 11:30 or whatever",
"title": "Test Notification",
"additionalData": {
"id": "class_id"
}
}
```

**Sample Code that illustrates the problem**
```
pushObject.on('notification').subscribe((notification: any) => {

  this.storage.get('showPush').then((val) => {

    if (val) {
      console.log('Your age is', val);
      console.log('New notification!', JSON.stringify(notification));

      let room_id = notification.additionalData.room_id;
      console.log(notification.additionalData.room_id);
      this.navCtrl.push(DetailsPage, { room_id: room_id });

    }
  });

}

);
```

**Logs taken while reproducing problem**
Not available

**Comment by macdonst** [comment]
@shri1983 check out the info on Chinese manufactured Android phones:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#chinese-android-phones

Also, I need to see the payload you are sending, not the one you received. Log would really help in this case.

**Comment by shri1983** [comment]
Hi Mac,
Thanks for your response. Here is the information that you have requested:
Actual;  When i tap on push message, it called pushObject.on('notification') callback from background.
Expected: It should invoke my application.

Logs:  When i tap on push message
detail.","additionalData":{"pushFor":"ROOMPUBLISH","dismissed":false,"room_id":" avalid room id","coldstart":false,"foreground":false}}

And Payload that we are sending is:
PayloadData {
data [
"title": "hi has been published.",
"message": "hi has been published. Please click to view room detail.",
 "pushFor": "ROOMPUBLISH",
 "room_id": "43e85674b65f8a3"

]
}

Also I examined the link that you have send, but this link explained the problem when we force close the application, but in my case i am not force closing instead just minimize the app by pressing hardware home button.

**Comment by macdonst** [comment]
@shri1983 can you open the AndroidManifest.xml and tell me what launchMode is set to?

**Comment by shri1983** [comment]
Hi Mac,
Thanks for your valuable time and response.
My launch mode is android:launchMode="singleInstance". Please suggest what launch mode we should use for this.
and below is my android manifest <application> tag code:

 <application android:hardwareAccelerated="true" android:icon="@mipmap/icon" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleInstance" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name="com.sarriaroman.PhotoViewer.PhotoActivity" android:theme="@android:style/Theme.Holo.NoActionBar.Fullscreen" />
        <service android:name="de.appplant.cordova.plugin.background.ForegroundService" />
        <provider android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true" android:name="org.apache.cordova.camera.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/camera_provider_paths" />
        </provider>
        <provider android:authorities="com.digivive.lecture.DocumentViewerPlugin.fileprovider" android:exported="false" android:grantUriPermissions="true" android:name="de.sitewaerts.cordova.documentviewer.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/documentviewer_file_paths" />
        </provider>
        <provider android:authorities="${applicationId}.opener.provider" android:exported="false" android:grantUriPermissions="true" android:name="io.github.pwlin.cordova.plugins.fileopener2.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/opener_paths" />
        </provider>
        <provider android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true" android:name="de.appplant.cordova.plugin.notification.util.AssetProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/localnotification_provider_paths" />
        </provider>
        <receiver android:exported="false" android:name="de.appplant.cordova.plugin.localnotification.TriggerReceiver" />
        <receiver android:exported="false" android:name="de.appplant.cordova.plugin.localnotification.ClearReceiver" />
        <activity android:exported="false" android:launchMode="singleInstance" android:name="de.appplant.cordova.plugin.localnotification.ClickReceiver" android:theme="@android:style/Theme.Translucent" />
        <receiver android:directBootAware="true" android:exported="false" android:name="de.appplant.cordova.plugin.localnotification.RestoreReceiver">
            <intent-filter>
                <action android:name="android.intent.action.LOCKED_BOOT_COMPLETED" />
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <activity android:exported="true" android:name="com.adobe.phonegap.push.PushHandlerActivity" android:permission="${applicationId}.permission.PushHandlerActivity" />
        <receiver android:name="com.adobe.phonegap.push.BackgroundActionButtonHandler" />
        <receiver android:name="com.adobe.phonegap.push.PushDismissedHandler" />
        <service android:name="com.adobe.phonegap.push.FCMService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service android:name="com.adobe.phonegap.push.PushInstanceIDListenerService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
    </application>

**Comment by jcesarmobile** [comment]
See https://github.com/phonegap/phonegap-plugin-push/issues/1690
