### ISSUE TITLE
Android icon

### ISSUE THREAD

**Issue by tmwebs** [phonegap/phonegap-plugin-push#2464]
### Expected Behaviour

See the push notifications icon on Android

### Actual Behaviour

The icon is not seen in Android

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 5.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Alcatel

#### Cordova CLI version and cordova platform version

    cordova --version                                    8.0.0
    cordova platform version android           7.1.0

#### Plugin version

    phonegap-plugin-push 2.2.3 "PushPlugin"

#### Sample Push Data Payload
    push = PushNotification.init({
      "android": {
          "senderID": "XXXXXXXX",
          "icon": "logo",
          "iconColor": 'blue'
      }
    });
#### Sample Image

<img width="336" alt="captura de pantalla 2018-07-04 a las 12 37 39" src="https://user-images.githubusercontent.com/12540076/42272669-32235c76-7f87-11e8-9ce0-99aed9705244.png"> 

<img width="336" alt="captura de pantalla 2018-07-04 a las 12 37 51" src="https://user-images.githubusercontent.com/12540076/42272684-3bccdb1c-7f87-11e8-82ce-2836fa1159ff.png">

![captura de pantalla 2018-07-04 a las 12 34 10](https://user-images.githubusercontent.com/12540076/42272691-40c81a64-7f87-11e8-9e22-dcab9273477f.png)

**Comment by jayj** [comment]
The notification icon should have a transparent background.

Android makes all non-transparent parts of the icon white. That's why you see a white square (see: https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar for more)

**Comment by macdonst** [comment]
@tmwebs yup, @jayj is 💯 right. Read up on: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images
