### ISSUE TITLE
phonegap-plugin-push v2.0.0 is not working in monaca angularjs v1.x.x

### ISSUE THREAD

**Issue by RajDW** [phonegap/phonegap-plugin-push#2468]
I have added `google-service.json` file to the root folder of the project.
But still `PushNotification.init({...` is not responding. 
I'm using Onsen UI, Cordova Version : 6.2.0
If I use try catch on init function it just says **ERROR**
PushPlugin version 1 was working perfectly.....

Should I add some thing to my config.xml ?

Below is my project structure :
![screenshot at jul 04 13-08-24](https://user-images.githubusercontent.com/40794549/42263342-5f07a78e-7f8b-11e8-9bfc-7bdf34f671d1.png)

**CONFIG.XML**
`<?xml version="1.0" encoding="UTF-8"?>`
`<widget xmlns="http://www.w3.org/ns/widgets" id="com.hello.world" version="1.0.1">`
 ` <name>Hello World</name>`
`  <description>Made By Raj</description>`
`  <author/>`
`  <content src="index.html"/>`
 ` <allow-navigation href="*"/>`
  `<allow-intent href="itms:*"/>`
  `<allow-intent href="itms-apps:*"/>`
  `<preference name="loglevel" value="DEBUG"/>`
  `<preference name="AndroidLaunchMode" value="singleTop"/>`
  `<preference name="ErrorUrl" value=""/>`
  `<preference name="SplashScreen" value="screen"/>`
  `<preference name="AllowInlineMediaPlayback" value="false"/>`
  `<preference name="BackupWebStorage" value="cloud"/>`
  `<preference name="KeyboardDisplayRequiresUserAction" value="true"/>`
  `<preference name="MediaPlaybackRequiresUserAction" value="false"/>`
  `<preference name="SuppressesIncrementalRendering" value="false"/>`
 ` <preference name="TopActivityIndicator" value="gray"/>`
 ` <preference name="GapBetweenPages" value="0"/>`
 ` <preference name="PageLength" value="0"/>`
 ` <preference name="PaginationBreakingMode" value="page"/>`
 ` <preference name="PaginationMode" value="unpaginated"/>`
 ` <feature name="LocalStorage">`
   ` <param name="ios-package" value="CDVLocalStorage"/>`
  `</feature>`
  `<preference name="UIWebViewDecelerationSpeed" value="normal"/>`
  `<preference name="WindowsStorePublisherName" value="My Name"/>`
  
  `<preference name="monaca:targetFamilyiPhone" value="1"/>`
  `<preference name="monaca:targetFamilyiPad" value="1"/>`
  `<platform name="ios">`
   ` <icon src="/res/ios/icon/icon.png" width="57" height="57"/>`
   ` <icon src="/res/ios/icon/icon@2x.png" width="114" height="114"/>`
   ` <icon src="/res/ios/icon/icon-72.png" width="72" height="72"/>`
   ` <icon src="/res/ios/icon/icon-72@2x.png" width="144" height="144"/>`
   ` <icon src="/res/ios/icon/icon-60.png" width="60" height="60"/>`
   ` <icon src="/res/ios/icon/icon-60@2x.png" width="120" height="120"/>`
   ` <icon src="/res/ios/icon/icon-60@3x.png" width="180" height="180"/>`
   ` <icon src="/res/ios/icon/icon-76.png" width="76" height="76"/>`
   ` <icon src="/res/ios/icon/icon-76@2x.png" width="152" height="152"/>`
   ` <icon src="/res/ios/icon/icon-40.png" width="40" height="40"/>`
   ` <icon src="/res/ios/icon/icon-40@2x.png" width="80" height="80"/>`
   ` <icon src="/res/ios/icon/icon-50.png" width="50" height="50"/>`
   ` <icon src="/res/ios/icon/icon-50@2x.png" width="100" height="100"/>`
   ` <icon src="/res/ios/icon/icon-small.png" width="29" height="29"/>`
   ` <icon src="/res/ios/icon/icon-small@2x.png" width="58" height="58"/>`
   ` <icon src="/res/ios/icon/icon-small@3x.png" width="87" height="87"/>`
    `<icon src="/res/ios/icon/icon-83.5@2x~ipad.png" width="167" height="167"/>`
    `<splash src="/res/ios/screen/Default~iphone.png" width="320" height="480"/>`
    `<splash src="/res/ios/screen/Default@2x~iphone.png" width="640" height="960"/>`
    `<splash src="/res/ios/screen/Default-568h@2x~iphone.png" width="640" height="1136"/>`
    `<splash src="/res/ios/screen/Default-667h.png" width="750" height="1334"/>`
    `<splash src="/res/ios/screen/Default-736h.png" width="1242" height="2208"/>`
    `<splash src="/res/ios/screen/Default-Landscape-736h.png" width="2208" height="1242"/>`
    `<splash src="/res/ios/screen/Default-Portrait~ipad.png" width="768" height="1024"/>`
    `<splash src="/res/ios/screen/Default-Landscape~ipad.png" width="1024" height="768"/>`
    `<splash src="/res/ios/screen/Default-Portrait@2x~ipad.png" width="1536" height="2048"/>`
    `<splash src="/res/ios/screen/Default-Landscape@2x~ipad.png" width="2048" height="1536"/>`
    `<icon src="/res/ios/icon/icon.png" width="57" height="57"/>`
    `<icon src="/res/ios/icon/icon@2x.png" width="114" height="114"/>`
    `<icon src="/res/ios/icon/icon-72.png" width="72" height="72"/>`
    `<icon src="/res/ios/icon/icon-72@2x.png" width="144" height="144"/>`
    `<icon src="/res/ios/icon/icon-60.png" width="60" height="60"/>`
    `<icon src="/res/ios/icon/icon-60@2x.png" width="120" height="120"/>`
    `<icon src="/res/ios/icon/icon-60@3x.png" width="180" height="180"/>`
    `<icon src="/res/ios/icon/icon-76.png" width="76" height="76"/>`
    `<icon src="/res/ios/icon/icon-76@2x.png" width="152" height="152"/>`
    `<icon src="/res/ios/icon/icon-40.png" width="40" height="40"/>`
    `<icon src="/res/ios/icon/icon-40@2x.png" width="80" height="80"/>`
    `<icon src="/res/ios/icon/icon-50.png" width="50" height="50"/>`
    `<icon src="/res/ios/icon/icon-50@2x.png" width="100" height="100"/>`
    `<icon src="/res/ios/icon/icon-small.png" width="29" height="29"/>`
    `<icon src="/res/ios/icon/icon-small@2x.png" width="58" height="58"/>`
    `<icon src="/res/ios/icon/icon-small@3x.png" width="87" height="87"/>`
    `<icon src="/res/ios/icon/icon-83.5@2x~ipad.png" width="167" height="167"/>`
    `<splash src="/res/ios/screen/Default~iphone.png" width="320" height="480"/>`
    `<splash src="/res/ios/screen/Default@2x~iphone.png" width="640" height="960"/>`
    `<splash src="/res/ios/screen/Default-568h@2x~iphone.png" width="640" height="1136"/>`
    `<splash src="/res/ios/screen/Default-667h.png" width="750" height="1334"/>`
    `<splash src="/res/ios/screen/Default-736h.png" width="1242" height="2208"/>`
    `<splash src="/res/ios/screen/Default-Landscape-736h.png" width="2208" height="1242"/>`
    `<splash src="/res/ios/screen/Default-Portrait~ipad.png" width="768" height="1024"/>`
    `<splash src="/res/ios/screen/Default-Landscape~ipad.png" width="1024" height="768"/>`
    `<splash src="/res/ios/screen/Default-Portrait@2x~ipad.png" width="1536" height="2048"/>`
    `<splash src="/res/ios/screen/Default-Landscape@2x~ipad.png" width="2048" height="1536"/>`
    `<config-file platform="ios" parent="CFBundleLocalizations" target="*-Info.plist">`
     ` <array>`
      `  <string>en</string>`
      `</array>`
    `</config-file>`
  `</platform>`
 ` <platform name="android">`
  `  <resource-file src="google-services.json" target="google-services.json" />`
  `</platform>`
  `<plugin name="phonegap-plugin-push" spec="~2.2.0">`
   ` <variable name="FCM_VERSION" value="15.0.0" />`
  `</plugin>`
  `<platform name="android">`
   ` <icon src="/res/android/icon/ldpi.png" density="ldpi"/>`
   ` <icon src="/res/android/icon/mdpi.png" density="mdpi"/>`
   ` <icon src="/res/android/icon/hdpi.png" density="hdpi"/>`
   ` <icon src="/res/android/icon/xhdpi.png" density="xhdpi"/>`
   ` <icon src="/res/android/icon/xxhdpi.png" density="xxhdpi"/>`
   ` <icon src="/res/android/icon/xxxhdpi.png" density="xxxhdpi"/>`
   ` <splash src="/res/android/screen/splash-port-ldpi.png" density="port-ldpi"/>`
    `<splash src="/res/android/screen/splash-port-mdpi.png" density="port-mdpi"/>`
    `<splash src="/res/android/screen/splash-port-hdpi.png" density="port-hdpi"/>`
    `<splash src="/res/android/screen/splash-port-xhdpi.png" density="port-xhdpi"/>`
    `<splash src="/res/android/screen/splash-port-xxhdpi.png" density="port-xxhdpi"/>`
    `<splash src="/res/android/screen/splash-port-xxxhdpi.png" density="port-xxxhdpi"/>`
    `<icon src="/res/android/icon/ldpi.png" density="ldpi"/>`
    `<icon src="/res/android/icon/mdpi.png" density="mdpi"/>`
    `<icon src="/res/android/icon/hdpi.png" density="hdpi"/>`
    `<icon src="/res/android/icon/xhdpi.png" density="xhdpi"/>`
    `<icon src="/res/android/icon/xxhdpi.png" density="xxhdpi"/>`
    `<icon src="/res/android/icon/xxxhdpi.png" density="xxxhdpi"/>`
    `<splash src="/res/android/screen/splash-port-ldpi.png" density="port-ldpi"/>`
    `<splash src="/res/android/screen/splash-port-mdpi.png" density="port-mdpi"/>`
    `<splash src="/res/android/screen/splash-port-hdpi.png" density="port-hdpi"/>`
    `<splash src="/res/android/screen/splash-port-xhdpi.png" density="port-xhdpi"/>`
    `<splash src="/res/android/screen/splash-port-xxhdpi.png" density="port-xxhdpi"/>`
    `<splash src="/res/android/screen/splash-port-xxxhdpi.png" density="port-xxxhdpi"/>`
  `</platform>`
  `<platform name="windows">`
   ` <icon src="/res/winrt/icon/package_logo_winrt.png" target="StoreLogo"/>`
   ` <icon src="/res/winrt/icon/app_logo_winrt.png" target="Square150x150Logo"/>`
   ` <icon src="/res/winrt/icon/app_small_logo_winrt.png" target="Square30x30Logo"/>`
   ` <icon src="/res/winrt/icon/app_tile_wide_logo_winrt.png" target="Wide315x150Logo"/>`
   ` <splash src="/res/winrt/screen/app_splash_screen_winrt.png" width="620" height="300"/>`
   ` <icon src="/res/winrt/icon/package_logo_winrt.png" target="StoreLogo"/>`
   ` <icon src="/res/winrt/icon/app_logo_winrt.png" target="Square150x150Logo"/>`
   ` <icon src="/res/winrt/icon/app_small_logo_winrt.png" target="Square30x30Logo"/>`
   ` <icon src="/res/winrt/icon/app_tile_wide_logo_winrt.png" target="Wide315x150Logo"/>`
    `<splash src="/res/winrt/screen/app_splash_screen_winrt.png" width="620" height="300"/>`
 ` </platform>`
 ` <platform name="chrome">`
  `  <icon src="/platforms/chrome/icon.png" width="128" height="128"/>`
   ` <icon src="/platforms/chrome/icon.png" width="128" height="128"/>`
 ` </platform>`
 ` <preference name="FadeSplashScreenDuration" value="250000"/>`
 ` <preference name="ios-XCBuildConfiguration-TARGETED_DEVICE_FAMILY" value="1,2"/>`
 ` <preference name="AutoHideSplashScreen" value="true"/>`
 ` <preference name="FadeSplashScreen" value="false"/>`
 ` <preference name="ShowSplashScreenSpinner" value="false"/>`
 ` <preference name="EnableViewportScale" value="false"/>`
 ` <access origin="*"/>`
 ` <preference name="KeepRunning" value="true"/>`
 ` <preference name="monaca:AndroidIsPackageNameSeparate" value="false"/>`
 ` <preference name="DisallowOverscroll" value="true"/>`
 ` <preference name="Orientation" value="portrait"/>`
 ` <preference name="SplashScreenDelay" value="0"/>`
 ` <preference name="Fullscreen" value="false"/>`
`</widget>`

**Comment by jcesarmobile** [comment]
Version >= 2 of the plugin requires cordova >= 7.0.0

**Comment by RajDW** [comment]
Thanks. 
I have found the solution. For cordova 6.5.0, phonegap-plugin-push version 1.10.6 and 1.10.5 are compatible none others does. Greater versions > 1.10.6 says gradle 4 depreciated.
