### ISSUE TITLE
PushNotifications is undefined

### ISSUE THREAD

**Issue by NilanKent** [phonegap/phonegap-plugin-push#2470]
### Expected Behaviour
get registrationId
### Actual Behaviour
PushNotification is not defined
### Reproduce Scenario (including but not limited to)
PushNotification.init alert throw error with 'PushNotification is not defined'
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Huawei
#### Cordova CLI version and cordova platform version
    cordova --version   7.1.0
    cordova platform version android   7.1.0
    cordova platform version ios 4.5.0

I added version android with 'cordova platform add android@7.1.0'
I added version ios with 'cordova platform add ios@4.5.0'
I added version cocoapods with 'cordova plugin add cordova-plugin-cocoapod-support --save'

have i added the requirements well, right?

i've too the google-services and .plist in root
#### Plugin version
    phonegap-plugin-push   2.2.0
#### Sample Code that illustrates the problem
config.xml
```
<widget id="xxx" version="xxx" xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0">
    <name>xxx</name>
    <description>xxx </description>
    <author email="xxx" href="xxx">xxx </author>
    <content src="index.html" />
    <preference name="phonegap-version" value="cli-7.1.0" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="android-minSdkVersion" value="15" />
    <preference name="android-targetSdkVersion" value="26" />
    <preference name="ios-configuration" value="production" />
    <preference name="StatusBarOverlaysWebView" value="false" />
    <preference name="StatusBarBackgroundColor" value="#ee6e73" />
    <preference name="StatusBarStyle" value="blacktranslucent" />
    <preference name="xwalkMultipleApk" value="false" />
    <plugin name="cordova-plugin-whitelist" spec="1.2.2" />
    <plugin name="cordova-plugin-barcodescanner" spec="^0.7.4" />
    <plugin name="cordova-plugin-x-socialsharing" spec="^5.3.2" />
    <plugin name="phonegap-plugin-push" spec="~2.2.0">
        <variable name="SENDER_ID" value="xxx" />
    </plugin>
    <platform name="android">
        <resource-file src="google-services.json" target="app/google-services.json" />
    </platform>
    <platform name="ios">
        <resource-file src="GoogleService-Info.plist" />
    </platform>
    <platform name="android">
        <allow-intent href="*" />
        <allow-navigation href="*" />
        <access origin="*" />
    </platform>
    <platform name="ios">
        <allow-intent href="*" />
        <allow-navigation href="*" />
        <access origin="*" />
    </platform>
    <platform name="android">
        icons paths
    </platform>
    <platform name="ios">
        icons paths
    </platform>
    <engine name="android" spec="~7.1.0" />
    <engine name="ios" spec="~4.5.0" />
    <plugin name="cordova-plugin-cocoapod-support" spec="^1.5.0" />
</widget>
```
index.html
```
<script type="text/javascript" src="cordova.js"></script>
<script type="text/javascript" src="js/firebase.js"></script>        
```
firebase,js
```
var firebase = {
   // Application Constructor
   initialize: function () {
      this.bindEvents();
   },
   // Bind Event Listeners
   //
   // Bind any events that are required on startup. Common events are:
   // 'load', 'deviceready', 'offline', and 'online'.
   bindEvents: function () {
      document.addEventListener('deviceready', this.onDeviceReady, false);
   },
   // deviceready Event Handler
   //
   // The scope of 'this' is the event. In order to call the 'receivedEvent'
   // function, we must explicitly call 'firebase.receivedEvent(...);'
   onDeviceReady: function () {
      console.log('Received Device Ready Event');
      console.log('calling setup push');
      firebase.setupPush();
   },
   setupPush: function () {
      console.log('calling push init');
      try {
         var push = PushNotification.init({
            "android": {
               "senderID": "xxx"
            },
            browser: {
               pushServiceURL: 'http://push.api.phonegap.com/v1/push'
            },
            "ios": {
               "sound": true,
               "vibration": true,
               "badge": true
            }
         });
      } catch (exception) {
         alert(exception);
      }
      console.log('after init');

      push.on('registration', function (data) {
         alert('registration event: ' + data.registrationId);

         var oldRegId = localStorage.getItem('id_firebase');
         if (oldRegId !== data.registrationId) {
            // Save new registration ID
            localStorage.setItem('id_firebase', data.registrationId);
            // Post registrationId to your app server as the value has changed
         }

      });

      push.on('error', function (e) {
         alert("push error = " + e.message);
         updateFirebaseMensaje(e.message);
      });

      push.on('notification', function (data) {
         alert('notification event');
         navigator.notification.alert(
                 data.message, // message
                 null, // callback
                 data.title, // title
                 'Ok'                  // buttonName
                 );
      });
   }
};

```

**Comment by macdonst** [comment]
@NilanKent it looks correct. Can you make sure your `platforms/android/app/src/main/assets/www/plugins/phonegap-plugin-push/www/push.js` file exists?

**Comment by macdonst** [comment]
@NilanKent double check that `phonegap-plugin-push` is in the `cordova_plugins.js` file. It seems really weird that the file is included but not loaded. You are doing the right thing waiting for `deviceready` before trying to setup PushNotification.

**Comment by NilanKent** [comment]
@macdonst hi, is in
![captura](https://user-images.githubusercontent.com/40631070/42443162-0a47969c-836d-11e8-88da-407d4910cc15.JPG)
and no working yet.
Yep, is weird, because version 1.8 works correctly, the problem is updating it to 2.2.3.

On the other hand, is there any way to create a new project with version 2.2.3 and thus be able to compare them?
Because `$ phonegap create myApp --template push` add the version 1.8

Thanks and sorry for bothering with the problem

**Comment by macdonst** [comment]
@NilanKent it makes no sense as everything seems to be setup correctly. I have no idea what is going wrong.

**Comment by Andrew-cp3** [comment]
Hi all,
I've the same issue "PushNotification is not defined" when i call PushNotification.init() on Android 4.4 and 8.0 (PhoneGap 6.1.2).

**Comment by jcesarmobile** [comment]
It's not the same issue, your problem is your phonegap version is very old and the plugin fails to install. For the OP the plugins seems to be installed.

**Comment by Andrew-cp3** [comment]
Thanks for your reply jcesarmobile,
but I use build-phonegap that automatically installs that version.
PhoneGap (iOS / Android / Windows) => cli-6.5.0 (4.3.1 / 6.1.2 / 4.4.3)
There are no errors in the build-log.

**Comment by jcesarmobile** [comment]
On Phonegap Build you can't use latest version of the plugin as it requires cordova-android 7.1.0, which is not available on Phonegap Build yet.

I have this sample app that works fine on Phonegap Build, it uses phonegap-plugin-push ~2.1.2
https://github.com/jcesarmobile/phonegap-plugin-push-sample

**Comment by NilanKent** [comment]
@macdonst ok, no prob, thanks and sorry for bothering with the problem

@jcesarmobile i'll download the sample and i'll compare both projects. Tnx for reply

**Comment by jcesarmobile** [comment]
@NilaKent, my answer was for Andrew-cp3 as he is using an old version of Phonegap, so the plugin fails to install and that's why it's undefined in his case.
I have no clue why it also happens to you as it seems to be installed.

**Comment by NilanKent** [comment]
@jcesarmobile yep, i know, only i want to see the difference and try to find the mistake ^_^

**Comment by Andrew-cp3** [comment]
Thanks @jcesarmobile.
I've tried with Phonegap Android 7.0.0, but I received the same issue. So needed at least the 7.1.0 as you wrote.
