### ISSUE TITLE
iOS don't receive notifications when app is open

### ISSUE THREAD

**Issue by tomilenko** [phonegap/phonegap-plugin-push#2471]
I have a problem with receiving the notification when app is open in ios. The notifications are received correctly in the background. But it is not receiving in `push.on('notification')`. Can anyone help me with it?

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 11.4

#### Cordova CLI version and cordova platform version

    cordova --version  8.0.0
    cordova platform version iOS 4.5.4

#### Plugin version

    phonegap-plugin-push 2.2.2 "PushPlugin"

#### Sample Push Data Payload

```
{
"notification": {
    "body": "body msg",
    "title": "test",
    "foreground": "true",
    "payload": {
      "event": "message",
      "count": 3
    }
  },
  "registration_ids": [
    "DEVICE-TOKEN"
  ]
}
```

#### Sample Code that illustrates the problem
The code from example passed into `$ionicPlatform.ready()` or into `deviceready`
```
var push = PushNotification.init({
                    android: {
                    },
                    ios: {
                        alert: "true",
                        badge: "true",
                        sound: "true"
                    },
                    windows: {}
                });
                
                push.on('registration', function(data) {
                    console.log("registration: " + data.registrationId);
                    // data.registrationId
                });
                
                push.on('notification', function(data) {
                    console.log("notification-notification-notification-notification");
                });
                
                push.on('error', function(e) {
                    console.log("error");
                });
```

**Comment by tomilenko** [comment]
Any updates here?

**Comment by jcesarmobile** [comment]
That payload is not right, you have to use aps instead of notification, title and body should go inside an alert. See
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification
