### ISSUE TITLE
Error while parsing timestamp in GCM event

### ISSUE THREAD

**Issue by marcelaraujo** [phonegap/phonegap-plugin-push#2473]
### Expected Behaviour
Emit notification event with payload data
### Actual Behaviour
No event emitted

#### Steps to Reproduce 
Just send any message
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android > 6
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
All
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 8.0.0
    cordova platform version android                     # e.g. 7.0.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 2.1.3

#### Sample Code that illustrates the problem
```
<?php
use Kreait\Firebase\Messaging\Notification;

$title = 'My Notification Title';
$body = 'My Notification Body';
$notification = Notification::fromArray([
    'title' => $title,
    'body' => $body
]);
$notification = Notification::create($title, $body);
$notification = Notification::create()
    ->withTitle($title)
    ->withBody($body);
```
#### Logs taken while reproducing problem

![screen shot 2018-07-05 at 15 04 25](https://user-images.githubusercontent.com/421794/42340042-3ecffdba-8065-11e8-97cd-3b042cf21847.png)

**Comment by macdonst** [comment]
@marcelaraujo I can't reproduce this issue. Can you try using a node script instead of your PHP library? The [PAYLOAD.md](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md) doc has lots of examples.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
