### ISSUE TITLE
Handle picture messages sent via Firebase Console

### ISSUE THREAD

**Issue by EmreErdogan** [phonegap/phonegap-plugin-push#2474]
### Expected Behaviour
Should be nice to parse custom data and recognize picture notifications
### Actual Behaviour
Shows the notification in the tray as a regular notification
### Reproduce Scenario (including but not limited to)
There is a notification composer on Firebase Console page. See **Steps to Reproduce** below
#### Steps to Reproduce 
1. Go to [Firebase console](https://console.firebase.google.com/?hl=en)
2. Select your project
3. Click **Cloud Messaging** on the **Grow** section on the left menu
4. Click **New message**
5. Fill **Message text**, select **Target**, enter **Title**
6. Click **Advanced options**
7. Add the following key-value pairs
**style:** picture
**picture:** http://36.media.tumblr.com/c066cc2238103856c9ac506faa6f3bc2/tumblr_nmstmqtuo81tssmyno1_1280.jpg
**summaryText:** The internet is built on cat pictures
8. Click **Send message**

![console firebase google com](https://user-images.githubusercontent.com/2360385/42344741-eff2c3ee-80a5-11e8-9534-0b28df9b1dbb.png)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0.2
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy Alpha
#### Cordova CLI version and cordova platform version
Cordova CLI: 8.0.0
Cordova Android: 7.0.0
#### Plugin version
2.1.3

---

When sending with **fcm-node** as below, the plugin successfully shows picture notification in the tray, but if I try to send a picture notification from Firebase Console, my device just shows the title and the message body, but not the picture.

Sample fcm-node compliant code:

```
const message = {
  to: deviceID,
  data: {
    title: 'Test Push',
    message: 'Push number 1',
    info: 'super secret 
    style: "picture",
    picture: "http://36.media.tumblr.com/c066cc2238103856c9ac506faa6f3bc2/tumblr_nmstmqtuo81tssmyno1_1280.jpg",
    summaryText: "The internet is built on cat pictures"
  }
};
```
**Important additional note:** Picture is shown if the notification is received when the app is in foreground and `forceShow` option is set to true. But it is not shown when I put the app to background or close it completely.

**Comment by macdonst** [comment]
@EmreErdogan the firebase console probably puts something in the `notification` portion of the payload which causes no end of issues for the plugin. Can you try testing outside of the firebase console or collect some logs?

**Comment by EmreErdogan** [comment]
@macdonst Thanks for the reply. Everything's fine outside of Firebase Console, so I wonder what kind of logs gathered outside of Firebase Console would help.

As I stated, I achieved to get picture notifications work as expected by sending notifications by using node-fcm. The reason I use Firebase Console its support for scheduled notifications and event tracking. If you saw the footnote in my issue report you'd notice that the plugin can handle picture messages when the app is in foreground and `forceShow` setting is set to true.

Thanks again for your efforts.

**Comment by macdonst** [comment]
@EmreErdogan yup, if you use the Firebase console it adds stuff to the `notification` section of the payload which causes the OS to take over and the plugin doesn't get to read the information in order to figure out what picture to display. Read up on [Notification vs Data payloads](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads). I wish I could fix this but I can't as `onMessageReceived` never gets called.
