### ISSUE TITLE
Not working on emulator

### ISSUE THREAD

**Issue by Saurabh995** [phonegap/phonegap-plugin-push#248]
Throws following error when it tries to register the app with gcm

Unable to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gsf (has extras) } U=0: not found

Please help

**Comment by macdonst** [comment]
@Saurabh995 what type of emulator are you using Android or Google? The emulator needs to be of target "Google" in order for there to be play services installed. Best bet is to use a device.

**Comment by Saurabh995** [comment]
I am using Android emulator and the target is "Google API 21". I am successfully receiving the registration-id . But notifications don't appear even when the app is in background.

**Comment by macdonst** [comment]
@Saurabh995 what are you sending for the payload?

**Comment by macdonst** [comment]
@Saurabh995 please re-open if you can reproduce with 1.4.0 and have a reproduction scenario I can test.
