### ISSUE TITLE
Push notification s not working with phonegap-push-plugin with FCM 

### ISSUE THREAD

**Issue by SweetyKothari** [phonegap/phonegap-plugin-push#2481]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by jcesarmobile** [comment]
You have to provide the required information, this issue is invalid
