### ISSUE TITLE
Is this plugin will send puah notification to browser in angular app

### ISSUE THREAD

**Issue by maqboolshah** [phonegap/phonegap-plugin-push#2484]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@maqboolshah the browser portion of this plugin is used for testing push notifications. It's not really intended as a production tool. Instead the plugin is providing a JS API for both Android and iOS.
