### ISSUE TITLE
Error: Source path does not exist: google-services.json

### ISSUE THREAD

**Issue by SaadRegal** [phonegap/phonegap-plugin-push#2490]
### Expected Behaviour
BUILD SUCCESSFUL on `cordova run android`
### Actual Behaviour
This error shows up 

    (node:25856) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Source path does not exist: google-services.json

#### Steps to Reproduce 
Using the following command `ionic cordova run android` 
#### Platform and Version
Android API 27
Android 7.0.0
#### Cordova CLI version and cordova platform version
Cordova 8.0.0
IONIC 3.20.0

#### Plugin version
phonegap-plugin-push 2.1.3 "PushPlugin"

#### (config.xml) Resource-file entry of  google-services.json
    <platform name="android">
        <resource-file src="google-services.json" target="app/google-services.json" />
    </platform>

#### Path to google-services.json
    platforms\android\app

**Comment by jcesarmobile** [comment]
You have to put the google-services.json in the root of your project (outside www folder, at the same level), and then the resource-file tag will copy it to platforms/android/app/

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
