### ISSUE TITLE
Android White Push Notification Icon

### ISSUE THREAD

**Issue by Jimisfou** [phonegap/phonegap-plugin-push#2491]
### Expected Behaviour
App Icon
### Actual Behaviour
White Icon
### Reproduce Scenario (including but not limited to)
I have change the app icon to a transparent icon.
I have put transparent icons inside the drawer folder
I have initialize PushNotification like this:
 android: {
     alert	: "true",
     badge	: true,
     vibrate	: "true",
     sound	: "true",
     icon:  'notify_icon',
     iconColor: '#66CC00'
},
ios: {
     alert	: "true",
     badge	: true,
     sound	: "true"
}

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Xiaomi Redmi Note 4
#### Cordova CLI version and cordova platform version

Phonegap Build: cli-8.0.0

#### Plugin version

   phonegap-plugin-push: 2.1.2

**Comment by macdonst** [comment]
@Jimisfou What 👏 does 👏 your 👏 push 👏 payload 👏 look 👏 like👏

**Comment by fredgalvao** [comment]
Also this: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images

**Comment by Jimisfou** [comment]
Hello @macdonst . My Payload is the above:
Notification = new NotificationPayload
                    {
                        Title = request.Title,
                        Body = request.Message
                    }

I have to add the image in the payload?

**Comment by macdonst** [comment]
@Jimisfou what package do you use to send the push notification? I'm looking for the raw payload that is being sent to FCM/GCM.

**Comment by Jimisfou** [comment]
Hello @macdonst . 
In my server I use c# in order to send the push notifications.
I use this library : https://github.com/bmak91/fcm-push-notification

This library use the above code to make the payload: 
```
var notification = new NotificationMessage
            {
                DryRun = request.DryRun,
                RegistrationIds = userTokens.Select(r => r.Token).ToList(),
                TimeToLive = Math.Max(0, ttl),
                Notification = new NotificationPayload
                {
                    Title = request.Title,
                    Body = request.Message
                },
                Data = request.Data
            };

            var jsonPayload = await Task.Run(() =>
                JsonConvert.SerializeObject(
                    notification,
                    Formatting.None,
                    new JsonSerializerSettings
                    {
                        ContractResolver = new SnakeCasePropertyNameContractResolver()
                    }
                )
            );
```

**Comment by macdonst** [comment]
@Jimisfou yup, you are running into the [Notification vs Data](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads) payload issue. You need to send everything in `data` not `notification`.

Here's what the code should probably look like, mind you I've never used the package:

```
var notification = new NotificationMessage
            {
                DryRun = request.DryRun,
                RegistrationIds = userTokens.Select(r => r.Token).ToList(),
                TimeToLive = Math.Max(0, ttl),
                Data = request.Data
                Data.Title = request.Title,
                Data.Body = request.Message
            };

            var jsonPayload = await Task.Run(() =>
                JsonConvert.SerializeObject(
                    notification,
                    Formatting.None,
                    new JsonSerializerSettings
                    {
                        ContractResolver = new SnakeCasePropertyNameContractResolver()
                    }
                )
            );
```

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
