### ISSUE TITLE
FCM support for iOS

### ISSUE THREAD

**Issue by nilsvant** [phonegap/phonegap-plugin-push#2494]
### Expected Behaviour
Plugin generates an FCM token, an messages are handled with the plugin.

### Actual Behaviour
Plugin generates APNS tokens, and therefore messages will not be received from FCM  under iOS

### Reproduce Scenario (including but not limited to)
Install plugin on cordova 7.1.x with plugin version 2.2

#### Steps to Reproduce 
Install plugin on cordova 7.1.x with plugin version 2.2

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 11.4

#### Cordova CLI version and cordova platform version

    cordova 7.1

#### Plugin version

 phonegap-plugin-push 2.2 

#### Sample Push Data Payload

{
 "to" : "duJFvfFlXa4:APA91bHHizDr9P3L0LE-oFZfBaS-NheNptPe4x5mzy8JS72jGDmownMEa2oP-0VtB3Xnfh4TwjzEWbWC7BW6NcGyzzd0wcbps66SOQG78ZIqnQGFJI0eQV7PUg7PRMrZy09f8Enc3Yh_yx1nqxJ4ziNbbn4tUsASHQ",
  "content_available": true,
 "data" : {
     "body" : "First Notification",
     "title": "Collapsing A",
     "key_1" : "Data for key one",
 }
}

**Comment by macdonst** [comment]
@nilsvant did you deliver the `GoogleService-Info.plist` file? 

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements

**Comment by nilsvant** [comment]
I did not see that part. Sorry about that. Then I think this issue can be marked as resolved.
