### ISSUE TITLE
set custom sound on my app isnt work

### ISSUE THREAD

**Issue by dsemerida** [phonegap/phonegap-plugin-push#2496]
Im trying to set custom sound on my project when i use this plugin of notification , i have been read aboutn if i set the sound on res/raw and but not work, im test with gmc node and my code on this section is `var message = new gcm.Message({
      collapseKey: "applice",
      delayWhileIdle: true,
      timeToLive: 3,
      data: {
      score: "4x8",
    	contents : "http://www.news-magazine.com/world-week/21659772"
      },
      notification: {
		title: "Hola amigo",
		sound:"custom",
    	alert:"true",
		icon: "ic_launcher",
		body: "This is a notification that will be displayed\r\nif your app is in the background."
	}
    });`

are there some to help me?

**Comment by jcesarmobile** [comment]
You have to provide all the data requested on the template and as it’s about the sound, also provide information about the custom sound, like format, where did you put the file, etc.
