### ISSUE TITLE
push.on('notification',... not working

### ISSUE THREAD

**Issue by orchoban** [phonegap/phonegap-plugin-push#2497]
Hey, I have a problem with the notification. 
Itws worked in the past and apparently I spoiled something. 

The registration working every time I sign in to the app, but I don't get notification from push.on('notification', function (data) {
alert("new notification");
}

*Client Side: 
https://github.com/orchoban/SerDive-www/blob/master/js/pushNotification.js 
*PlugIn Cordova-Phonegap: 
https://github.com/orchoban/SerDive-www/blob/master/config.xml

 *My Server Side-(API):
(C#.NET): PushSharp plugIn
 updatePushId():line1699 &RunPushNotification():line 1646 
https://github.com/orchoban/SerDive-WebService/blob/master/App_Code/WebService.cs 

Thanks for the help.

**Comment by jcesarmobile** [comment]
First of all, you have to use the template and provide all the required information.
Second, you plugin version is very old, there are a lot of chances that google changed something and  made that version incompatible.
