### ISSUE TITLE
Build failure adding plugin to cordova 8.0.0 project

### ISSUE THREAD

**Issue by andrea-nina** [phonegap/phonegap-plugin-push#2499]
### Expected Behaviour
BUILD SUCCESS

### Actual Behaviour
BUILD FAILED in 1s
(node:12300) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

What went wrong:
A problem occurred configuring project ':app'.
Cannot add task ':app:processDebugGoogleServices' as a task with that name already exists.

### Reproduce Scenario (including but not limited to)
Creating hello sample project with cordova 8.0.0 and adding plugin (after enabling Firebase), the build process fails.

#### Steps to Reproduce 

1. Create classic sample cordova project:  **cordova create hello com.example.hello HelloWorld**
2. Add android platform: **cordova platform add android**
3. Manually add Firebase downloading google-services.json and putting it in the root directory
4. Add tag `<resource-file` src="google-services.json" target="app/google-services.json" `/>` to platform android tag in confix.xml of the project
5. add plugin: **cordova plugin add phonegap-plugin-push**
It installs the pugin but with an older version: 2.1.3 instead of 2.2.3

> Unmet project requirements for latest version of phonegap-plugin-push:
cordova-android (7.0.0 in project, >=7.1.0 required)
Fetching highest version of phonegap-plugin-push that this project supports: 2.1.3 (latest is 2.2.3)
6.  try to build: **cordova build android**
BUILD FAILED

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 8.0

#### Cordova CLI version and cordova platform version

    cordova --version                          8.0.0
    cordova platform version android           7.0.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

Version 2.1.3

#### Logs taken while reproducing problem

Android Studio project detected
ANDROID_HOME=C:\Android\newsdk
JAVA_HOME=C:\PROGRA~1\Java\JDK18~1.0_1
studio
Subproject Path: CordovaLib
Subproject Path: app
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_4hyhikkzj0alrgb5k5ie3f8ro.run(C:\Development\Apps\Test\Test2\hello\platforms\android\app\build.gradle:144)
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot add task ':app:processDebugGoogleServices' as a task with that name already exists.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
(node:17948) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot add task ':app:processDebugGoogleServices' as a task with that name already exists.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
    at ChildProcess.whenDone (C:\Development\Apps\Test\Test2\hello\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:17948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17948) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jcesarmobile** [comment]
You have to use cordova-android 7.1.1 instead of 7.0.0
