### ISSUE TITLE
Does this have the same issue like the original PushPlugin on phonegap-build?

### ISSUE THREAD

**Issue by incorelabs** [phonegap/phonegap-plugin-push#25]
On the PushPlugin, i.e. https://github.com/phonegap-build/PushPlugin, I had a really strange issue on Android Phones. iOS does not have this issue, android does. The issue is as follows:

I used to call the register() function to register with GCM.

```javascript
var pageHome = {
    pushNotification: window.plugins.pushNotification,
    initPush: function() {
        pageHome.pushNotification.register(pageHome.successHandler, pageHome.errorHandler, {
            "senderID" : "1234567890",
            "ecb" : "pageHome.onNotificationGCM"
        });
    },
    onNotificationGCM: function(e) {
        switch(e.event) {
            case 'registered':
                // Just a random check for the regid.
                if (e.regid.length > 0) {
                    // Get the pushToken from localStorage.
                    var pushToken = localStorage.getItem("pushToken");
                    // Check if the registration has already happened and whether the already stored pushToken is the same as the new registration id (e.regid) coming as a result of re-registration with the GCM server
                    if(pushToken == null || pushToken != e.regid) {
                        // If the device has NOT registered or the device id has changed then only register again.
                        $.ajax({
                            url: 'https://xyz.com/register',
                            type: 'POST',
                            dataType: 'json',
                            data: {regId : e.regid},
                            success: function(data) {
                                // If stored on my own server, then only save it to localStorage.
                                localStorage.setItem("pushToken", e.regid);
                            },
                            error: function(error) {
                            }
                        });
                    }
                }
                break;

            case 'message':
                navigator.notification.alert(e.payload.message, app.alertDismissed, e.payload.title, 'Dismiss');
                break;
        }
    }
}
```
The problem I have been facing for long is that more than one android device has the same registration id. I mean the registration id is not unique for different devices. Multiple devices have the same registration id. This is quite weird and I have been facing this issue with that plugin. Will this plugin solve this error? Or is this error due to Google GCM servers? In all my apps I have this issue..

**Comment by macdonst** [comment]
@incorelabs multiple devices should have different registration ID's. I have never heard of this happening before. Please try reproducing it with this plugin but again, this should never happen.

**Comment by incorelabs** [comment]
Thank-you @macdonst for looking into it. This problem has plagued all my apps and till date I do not know what I am doing wrong. Coz how can two devices have the same id? Moreover, I've seen 35 devices have the same id. Which was hilarious. 

Is anything wrong with the code above? I hope the error is not due to my code. I've written down the code I use to register with GCM and store the received registration id on our third party server. For the "Sender ID" I use the one I have on my Google Cloud Messaging Project and the corresponding API is on our server.

**Comment by macdonst** [comment]
@incorelabs I don't see anything wrong with the code above. Are all the devices the same HW type?

**Comment by incorelabs** [comment]
I really doubt, that all devices have the same HW type. We do not keep track of the device details other than the registration id of the device. Apart from the HW type reason could there be any other possible reason why this happen in the first place?

**Comment by macdonst** [comment]
@incorelabs No, I can't think of a reason why this would be the case. Can you reproduce the issue with this plugin? If so can you provide me with the reproduction scenario?

**Comment by incorelabs** [comment]
I'll try reproducing the issue with this new plugin and revert back to you with the reproduction. But the reproduction will take time, I'm off work these days. Will get back with the results by mid-August.

**Comment by macdonst** [comment]
Closing, no feedback.
