### ISSUE TITLE
OneSignal is not working with Admob plugin in phonegap build 

### ISSUE THREAD

**Issue by sai12346** [phonegap/phonegap-plugin-push#2504]
Hello,

OneSignal is not working with Admob plugin in phonegap build .But it both work successfulyy separate.
OneSignal-Cordova-Example-mastertest.zip

Issue :same player id is getting for each installation(and this playerid is not valid).But after removing admob plugin we get different player id for each instalation.please helpppppppp

**Comment by sai12346** [comment]
this issue in phonegap ios

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
