### ISSUE TITLE
Upgrading from 1.9.2 - 2.2.3 - Notification not received - Android

### ISSUE THREAD

**Issue by pauljcurtis** [phonegap/phonegap-plugin-push#2506]
### Expected Behaviour
To receive notification on the device
### Actual Behaviour
Notification not being received on the device
### Reproduce Scenario (including but not limited to)
Send push notification from our website, which works to a device running phonegap-plugin-push 1.9.2.
#### Steps to Reproduce 
No really possible at this point - Hopefully the answer will be straight forward
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
android 7 & Android 8
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Sonxy Xperia Z5
#### Cordova CLI version and cordova platform version
    cordova --version  8.0.0                               
    Android CLI 7.1.0           

#### Plugin version
 phonegap-plugin-push  2.2.3

#### Sample Push Data Payload
 'message' 	=> $copy,
	'title' =>  $club_name. ' - ' . $title,
	'pushtitle'	=> $club_name. ' - ' . $title,
	'body' => $copy,
	'pushtype'	=> 'push notification',
	'vibrate'	=> 1,
	'sound'		=> 'default',
	'icon' => 'pushicon',
	'ledColor' => "[0,255,130,27]",
	'color' => '#ff8200',
	'url' => 'notifications',
	'content-available' => 1,
	'count'=> 1,
	'notId' => uniqid(),
	"style"=> "inbox",
        "summaryText"=> "There are %n% notifications",
	"android_channel_id" => "PushPluginChannel"

**Comment by jcesarmobile** [comment]
Did you also updated the endpoints to where you send the push to?
v 2.x.x of the plugin uses FCM, while v 1.x.x uses GCM, so changes on the server are also required

**Comment by pauljcurtis** [comment]
Thanks. Yes, I've been using FCM for some time 'https://fcm.googleapis.com/fcm/send'

**Comment by pauljcurtis** [comment]
Additional information: I've just tried to send a test message from Firebase Cloud Messaging to a single device. It failed on Android. (I've not updated the iOS app, yet !). Would this point to an incorrect token being generated?

**Comment by pauljcurtis** [comment]
My stupid mistake. I'd downloaded the google-services.json for a different project. So I'm closing this. thanks for the help.
