### ISSUE TITLE
Delete Android channel and recreate it in order to change sound file???

### ISSUE THREAD

**Issue by uj** [phonegap/phonegap-plugin-push#2507]
This probably isn't a bug, but perhaps a misunderstanding on my part.

I call .createChannel id=PushPluginChannel with a sound file A
I call .listChannels and it shows PushPluginChannel
I call .init and then do a push.  It notifies properly with sound file A
Good so far!

Now, I want to change to sound file B, so I do this:

I call .deleteChannel id=PushPluginChannel
I call .listChannels and it shows there are no channels
I call .createChannel id=PushPluginChannel with a sound file B
I call .listChannels and it shows PushPluginChannel
I call .init and then do a push.  It notifies properly with the original sound file A, not B.

Is this the proper behavior?  Or should I be able to delete a channel are recreate it with a different sound?

**Comment by macdonst** [comment]
@uj that should be the way to do it. Unfortunately, that is the way the [NotificationChannel](https://developer.android.com/reference/android/app/NotificationChannel.html#setSound(android.net.Uri,%20android.media.AudioAttributes)) class works.

Can you please fill out the rest of the issue template so I know what version of the plugin, android, etc you are using.

**Comment by uj** [comment]
Ok, I see in the google document that you referred to, that even if you delete and recreate a channel, you still can never change the sound again because the OS will remember the deleted channel.  It will be stuck with that sound forever.  The only way to ever change the sound is to uninstall and reinstall the app.  Deleting a channel really just hides it.

But, now that I know that, I can workaround it.  That's fine.

That being answered, I assume you no longer need my versions, but here they are anyway:

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Moto G6

#### Cordova CLI version and cordova platform version
Cordova CLI 8
Cordova-android 7.1.1

#### Plugin version

Current github master on Aug-1-2018

**Comment by ggiordan** [comment]
I wish I had found this BEFORE I spend a few hours trying to figure out what I was doing wrong :-)
The google documentation, once you dig around, is really clear, once the channel is created, that's it, it looks like the only thing you can change after that is the name and priority.

"If you create a new channel with this same id, the deleted channel will be un-deleted with all of the same settings it had before it was deleted."

They seem to be urging folks to drive people to the app notification settings versus doing it yourself.
I guess I see their point, but it really limits the usefulness for those who want to lots of custom tones.

@macdonst - can you clarify the documentation a bit to be very clear that once you create the channel, you cannot change it.  I'd also suggest clarifying the "default channel" that you need to make any changes before calling init the FIRST TIME, after that, you can't change it without removing the app.  :-(

**Comment by uj** [comment]
You have to create the channel BEFORE init.  Also, there is always the PushPluginChannel created that uses default values.  You can see if the channels are being created by opening per-app notification settings in your phone settings.  It will show all of the channels, and it will show what sound they are using.

I would suggest not trying to change the sound on PushPluginChannel because if you have ever deployed your app in the past and did't set the sound on PushPluginChannel, then you cannot change the sound on that one anyway (unless you uninstall/reinstall).  So, use PushPluginChannel for default, and create new channels for each of your custom sounds.



Create the Channel(s):

```
		setTimeout(
		(this.Push as any).createChannel(
		  () => {
			console.log('Successfully created channel-one');
		  },
		  () => {
			console.log('Error creating channel-one');
		  },
		  {
			id: 'channel-one',
			description: 'This is Channel One',
			importance: 5,
			vibration: true,
			visibility: 1,
			sound: 'channel_one'
		  }
		).then(() => console.log('createChannel finished')),10
		);		
		
		setTimeout(
		(this.Push as any).createChannel(
		  () => {
			console.log('Successfully created channel-two');
		  },
		  () => {
			console.log('Error creating channel-two');
		  },
		  {
			id: 'channel-two',
			description: 'This is Channel Two',
			importance: 5,
			vibration: true,
			visibility: 1,
			sound: 'channel_two'
		  }
		).then(() => console.log('createChannel finished')),10
		);	
```

Push Init:

```
		let push = (this.Push as any).init(
			{
			android: 
				{
				senderID: "############",
				"clearNotifications": "false",
				"vibrate": "true",
				"sound": "true",
				"icon": "icon",
				"forceShow": "true",
				"iconColor": "blue"
				},
			ios: 
				{
				senderID: "#############",
				gcmSandbox: false,
				alert: "true",
				badge: "true",
				sound: "true"
				},
			windows: 
				{
				}
			});
```



PAYLOAD:

This is in PHP, but you can see what you need to.  Remember that Android 7 and below use the sound/soundname an Android 8 and above use android_channel_id.  It's okay to include both for all phones, because the phone will simply ignore any fields that it doesn't need.

```
						$push_output = 
						'{' .
						'"to": "' . $devicetoken . '",' .
						'"priority": "high",' .
						'"data": ' .
						'{' .
						'"title": $title,' .
						'"body": "' . $message . '",' .
						'"style": "inbox",' .
						'"summaryText": "You have %n% new messages",' .
						'"soundname": "' . $mysound_file . '",' .
						'"sound": "' . $mysound_file . '",' .
						'"priority": 2,' .
						'"content-available": "1",' .
						'"force-start": 1,' .
						'"android_channel_id": "' . $android_channel_id  . '",' .
						'"visibility": 1' .
						'}, ' .
						'"time_to_live" : 3600' .
						'}'
						;	
```

**Comment by Lenndev** [comment]
@uj  thank you very much for your explanation. at first it did not work, then i found out that i was using the wrong file path as target for the audio file xS 

so for everyone interested in this: 

`<resource-file src="src/assets/sounds/<soundfilename>.mp3" target="app/src/main/res/raw/<soundfilename>.mp3" />`

this in combination with above explanation works!  :D :D :D 🎆
