### ISSUE TITLE
Not receiving notifications from server - OK from Firebase Console

### ISSUE THREAD

**Issue by pauljcurtis** [phonegap/phonegap-plugin-push#2508]
### Expected Behaviour
To receive notification on device
### Actual Behaviour
Not receiving notifications
### Reproduce Scenario (including but not limited to)
Can't really reproduce. My app receives notifications in foreground & background when sending  a test notification via Firebase Console but I'm not receiving any notification when sending through our website. I've added 'android_channel_id' to the payload.

The same code works for devices running v 1.9.2 so I'm assuming it's something to do with the 'android_channel_id' ? Maybe?

Endpoint is 'https://fcm.googleapis.com/fcm/send'

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Sony Xperia z5 compact
#### Cordova CLI version and cordova platform version
    cordova --version   8.0.0
    cordova platform version android  7.1.1

#### Plugin version
 phonegap-plugin-push  2.2.3

#### Sample Push Data Payload
'title' =>  'Some title',
	'message' => 'some message',
	'android_channel_id' => 'PushPluginChannel',
	'priority'=> '2',
	'content-available' => 1

**Comment by pauljcurtis** [comment]
08-02 13:28:20.677 26075 26134 V Push_Plugin: execute: action=init
08-02 13:28:20.678 26075 26137 V Push_Plugin: execute: data=[{"android":{"senderID":"**********","icon":"pushicon","iconColor":"#FFFFFF","forceShow":true,"alert":true},"ios":{"alert":true,"badge":true,"sound":true,"senderID":"814471264227","gcmSandbox":false,"clearBadge":true,"forceShow":true}}]
08-02 13:28:20.678 26075 26137 V Push_Plugin: execute: jo={"senderID":"**********","icon":"pushicon","iconColor":"#FFFFFF","forceShow":true,"alert":true}
08-02 13:28:20.679 26075 26137 V Push_Plugin: execute: senderID=**********
08-02 13:28:20.679 26075 26137 V Push_Plugin: onRegistered: {"registrationId":"fyROgfq4VGg:APA91bHkFmtKaMpPKkDN9XRv1HoK3ekLuArmsprhdEC4ujLWDWpAKpnVi5uT9-XIFWl12fd7xkVE_u_kgjIa65ry60OBj9f1gXxEh3neU8pF38HpnHIBmV3E9RqhAxj3XMkOEUrVC2zJIiydZPjQuHBnzS2Yst3XaQ","registrationType":"FCM"}

**Comment by macdonst** [comment]
And what do you see in the logs when you send a message to that
registration ID?

**Comment by pauljcurtis** [comment]
**With test sent from my site**
08-02 13:32:08.861 26075 27334 D Push_FCMService: onMessage - from: removed
08-02 13:32:08.863 26075 27334 D Push_FCMService: sender id = removed
08-02 13:32:08.864 26075 27334 D Push_FCMService: normalize extras
08-02 13:32:08.866 26075 27334 D Push_FCMService: foreground force
08-02 13:32:08.867 26075 27334 D Push_FCMService: message =[null]
08-02 13:32:08.867 26075 27334 D Push_FCMService: title =[null]
08-02 13:32:08.867 26075 27334 D Push_FCMService: contentAvailable =[null]
08-02 13:32:08.867 26075 27334 D Push_FCMService: forceStart =[null]


**With test sent from Firebase**
08-02 13:58:12.823 26075  2245 D Push_FCMService: onMessage - from: _removed_
08-02 13:58:12.823 26075  2245 D Push_FCMService: sender id = _removed_
08-02 13:58:12.824 26075  2245 D Push_FCMService: normalize extras
08-02 13:58:12.824 26075  2245 D Push_FCMService: key = icon
08-02 13:58:12.824 26075  2245 D Push_FCMService: replace key icon with icon
08-02 13:58:12.824 26075  2245 D Push_FCMService: key = color
08-02 13:58:12.824 26075  2245 D Push_FCMService: replace key color with color
08-02 13:58:12.824 26075  2245 D Push_FCMService: key = sound
08-02 13:58:12.824 26075  2245 D Push_FCMService: replace key sound with sound
08-02 13:58:12.824 26075  2245 D Push_FCMService: key = title
08-02 13:58:12.824 26075  2245 D Push_FCMService: replace key title with title
08-02 13:58:12.825 26075  2245 D Push_FCMService: no locale found for key = title, error Value Push of type java.lang.String cannot be converted to JSONObject
08-02 13:58:12.825 26075  2245 D Push_FCMService: key = message
08-02 13:58:12.825 26075  2245 D Push_FCMService: replace key message with message
08-02 13:58:12.825 26075  2245 D Push_FCMService: no locale found for key = message, error Value Foreground of type java.lang.String cannot be converted to JSONObject
08-02 13:58:12.826 26075  2245 D Push_FCMService: foreground force
08-02 13:58:12.826 26075  2245 D Push_FCMService: message =[Foreground test message]
08-02 13:58:12.826 26075  2245 D Push_FCMService: title =[Push title]
08-02 13:58:12.826 26075  2245 D Push_FCMService: contentAvailable =[null]
08-02 13:58:12.826 26075  2245 D Push_FCMService: forceStart =[null]
08-02 13:58:12.826 26075  2245 D Push_FCMService: create notification
08-02 13:58:12.826 26075  2245 E Push_FCMService: Number format exception - Error parsing notId: null
08-02 13:58:12.834 26075  2245 D Push_FCMService: stored icon=pushicon
08-02 13:58:12.834 26075  2245 D Push_FCMService: stored iconColor=#FFFFFF
08-02 13:58:12.834 26075  2245 D Push_FCMService: stored sound=true
08-02 13:58:12.834 26075  2245 D Push_FCMService: stored vibrate=true
08-02 13:58:12.834 26075  2245 D Push_FCMService: using icon from plugin options
08-02 13:58:12.836 26075  2245 D Push_FCMService: create actions: with in-line

**Comment by macdonst** [comment]
Can you post your full payload you send to your server?

**Comment by pauljcurtis** [comment]
@macdonst 

Here's what I'm sending from the server. As I mentioned previously this all works if sending to plugin v 1.9.2

$message = "TEST";
$androidarr = array
(
	'title' =>  'TEST',
	'message' => $message,
	'priority'=> '2',
	'content-available' => 1,
	'notId' => uniqid(),
	'sound'	=> 'default',
	'url' => 'notifications',
);
/* The array below I've put in to test. There's no notification reaching the device with or without this array */

$notification = array
(
	'title' =>  'TEST',
	'message' => $message,
	'content-available' => 1
	);

$data = array(	
'notification'=> $notification,
'data'=> $androidarr
);

$fcm = new FCMPushMessage($apiKey);
$fcm->setDevices($devices);
$removes = $fcm->send($message,$data);

**Comment by macdonst** [comment]
@pauljcurtis well stuff is making it to the plugin but it's not being displayed properly due to [Notification vs Data payloads](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads).

Try putting everything in `data`, i.e. get rid of `notification`:

```
$message = "TEST";
$androidarr = array
(
'title' => 'TEST',
'message' => $message,
'priority'=> '2',
'content-available' => 1,
'notId' => uniqid(),
'sound'	=> 'default',
'url' => 'notifications',
);

$data = array(
'data'=> $androidarr
);

$fcm = new FCMPushMessage($apiKey);
$fcm->setDevices($devices);
$removes = $fcm->send($message,$data);
```

I'm not familiar with the method you are using to send the push. Is it some PHP script? The line:

```
$fcm->send($message,$data);
```

looks like it could cause a problem.

**Comment by pauljcurtis** [comment]
I've been through my code and took out any reference to notification. I can receive push notifications now... troubles is I've got loads coming through. It looks like they're repeating.

Not to worry. I'll sort that out.

Thanks for your time.
