### ISSUE TITLE
Post phonegap-plugin-push installation error log

### ISSUE THREAD

**Issue by nathanmercieca0011** [phonegap/phonegap-plugin-push#2510]
### Expected Behaviour
Simple implementation of the phonegap-plugin-push plugin.
### Actual Behaviour
No longer allowing successful build.
### Cordova CLI version and cordova platform version
8
### Plugin version
The latest applicable to the 2nd of August 2018.
### Sample Code that illustrates the problem
```
FAILURE: Build failed with an exception.
* Where:
Script '/phonegap-plugin-push/[MY_APP_NAME]-push.gradle' line: 6
* What went wrong:
A problem occurred evaluating script.
> /app/AndroidManifest.xml (No such file or directory)
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
```
### Current Plugins
`<plugin name="cordova-plugin-admob-simple" spec="3.3.4"/>`
`<plugin name="cordova-plugin-badge" spec="0.8.7"/>`
`<plugin name="cordova-plugin-camera" spec="4.0.2"/>`
`<plugin name="cordova-plugin-file-transfer" spec="1.7.1"/>`
`<plugin name="cordova-plugin-inappbrowser" spec="2.0.2"/>`
`<plugin name="cordova-plugin-screen-orientation" spec="3.0.1"/>`
`<plugin name="cordova-plugin-splashscreen" spec="5.0.2"/>`
`<plugin name="cordova-plugin-whitelist" spec="1.3.3"/>`
`<plugin name="phonegap-plugin-barcodescanner"/>`
`<plugin name="cordova-plugin-geolocation"/>`
`<plugin name="cordova-plugin-globalization"/>`
`<plugin name="cordova-plugin-file"/>`
`<plugin name="cordova-plugin-gallery-refresh"/>`
`<plugin name="cordova-plugin-contacts"/>`
`<plugin name="cordova-plugin-localization-strings"/>`
`<plugin name="cordova-plugin-statusbar"/>`
`<plugin name="phonegap-plugin-push" spec="2.0.0"/>`

### Actions leading up to error and fail to build
- Searched the internet for a notification plugin;
- Found this one, added the plugin to my config.xml;
- Created Firebase account and input sender id to jquery etc;
- Added necessary jquery code to effectuate the plugin;
- Completed the php page to send notification;
- Added the following 2 pieces to my config.xml:
    `<platform name="android">`
        `<resource-file src="google-services.json" target="app/google-services.json" />`
    `</platform>`
    `<platform name="ios">`
        `<resource-file src="GoogleService-Info.plist" />`
    `</platform>`
- Downloaded the json file from Firebase and put it in the above directy;
- Ran app on a Samsung and iPhone (via phonegap app)...worked perfectly;
- Zipped app;
- Uploaded to build; and
- Voilà, error!

**Comment by macdonst** [comment]
@nathanmercieca0011 based upon this line:

```
/app/AndroidManifest.xml (No such file or directory)
```

it seems like you are using an older version of cordova-android that does not support the AndroidStudio style paths. Please give the installation instructions another once over: 

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements

Since you didn't tell me what version of cordova-android you are using that's my best bet.

**Comment by nathanmercieca0011** [comment]
Salut / Hi @macdonst 
I'm using phonegap, I've never had to know what Cordova-Android is so far, what does it mean? The CLI I'm using is 8. Does it also help that the app is at version 1.7 with 7 successfully phonegap build and this being the only time that came up?

**Comment by nathanmercieca0011** [comment]
Hi @jcesarmobile 
In my config I've got:
`<preference name="phonegap-version" value="cli-8.0.0" />`

**Comment by jcesarmobile** [comment]
Ok, so you are using Phonegap Build.

Latest version of the plugin requires cordova-android 7.1.0 or greater, which is not available on Phonegap Build yet. You'll have to use version 2.1.3 of the plugin or older

**Comment by nathanmercieca0011** [comment]
It tried to install at 2.1.3, but a new error arised:

```
A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"
```

**Comment by jcesarmobile** [comment]
That's a conflict with a plugin.
It's fixed on our side, but you can't use latest version, so you'll have to build locally or use another plugin.
