### ISSUE TITLE
GCM migrate to FCM Problem

### ISSUE THREAD

**Issue by ersatishverma** [phonegap/phonegap-plugin-push#2515]
Hi
Actually, this is not an issue It's a Question.

At present, we are using GCM and would like to migrate to FCM. 

As per the FCM guidelines, we will have to include a `google-service.json` file in each app and this is unique to each app according to there package. 

The issue is that we have a platform that generates mobile applications on the fly using phonegap and we have existing customers who have already used our services to create thier applications and we have around 5000 apps that our customers are already using. Basically, it is not easy and practical to create and add`google-service.json` to all our existing apps individually acording to there pakage Id beacuse each app package id is diffrent and its dynamically created.

 Can you please guide us as how do we do it for the existing apps as migrating to new system because it is not very fexible to go google acount and create each app `google-service.json` file.

One more thing is how do we implement it for our new apps as well. 

Do you have any API or something using which we can create `google-service.json` file and add it individually to each app in runtime.

Please help!
Many Thanks in advance...

**Comment by jcesarmobile** [comment]
It's not our requirement, it's a Google requirement when migrating from GCM to FCM.
