### ISSUE TITLE
Compatibility with Android@6...

### ISSUE THREAD

**Issue by joaolori** [phonegap/phonegap-plugin-push#2517]
### Expected Behaviour
Compatibility with Android version 6.4 . I cannot migrate to 7 cause other plugins are also not compatible with android 7

### Actual Behaviour
Native: tried calling PushNotification.init, but the PushNotification plugin is not installed.

#### Cordova CLI version and cordova platform version

    cordova --version                                   8.0.0
    cordova platform version android                   android 6.4.0

#### Plugin version

    cordova plugin version  phonegap-plugin-push 2.2.1

**Comment by jcesarmobile** [comment]
Sorry, we can't do that, the plugin requires cordova-android >= 7.1.0 because of a bug.

**Comment by joaolori** [comment]
How can i check the compatibility of the remaining plugins regarding android version? any npm command available?


cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-document-viewer 0.9.10 "SitewaertsDocumentViewer"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-facebook4 2.2.0 "Facebook Connect"
cordova-plugin-googleplus 5.3.0 "Google SignIn"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.1 "SocialSharing"
cordova-plugin-youtube-video-player 1.0.6 "CordovaYoutubeVideoPlayer"
es6-promise-plugin 4.2.2 "Promise"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
phonegap-plugin-push 2.1.3 "PushPlugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.1 "Launch Navigator"
