### ISSUE TITLE
When click on push notification the app event doesn't fire.

### ISSUE THREAD

**Issue by saidhn** [phonegap/phonegap-plugin-push#2519]
### Expected Behaviour
$rootScope.$on('$cordovaPushV5:notificationReceived', function(event, data){...
This event should be fired if the app is closed then opened by clicking on push notification
### Actual Behaviour
$rootScope.$on('$cordovaPushV5:notificationReceived', function(event, data){
Is not fired if the app is closed then opened by clicking on push notification
#### Steps to Reproduce 
having this code inside app.js file and inside .run

$ionicPlatform.on("deviceready", function(){
	if (window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
    }
    if (window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleDefault();
    }
	var options = {
    	android: {
    	  senderID: GCM_SENDER_ID
    	},
      ios: {
        alert: "true",
        badge: "true",
        sound: "true"
      },
      windows: {}
    };
    var current_platform = "",
        token = "";
    // initialize
    $cordovaPushV5.initialize(options).then(function() {
      // start listening for new notifications
      $cordovaPushV5.onNotification();
      // start listening for errors
      $cordovaPushV5.onError();

      // register to get registrationId
      $cordovaPushV5.register().then(function(data) {
	  
	  SubscriptionService.saveDeviceToken(data);
        if(ionic.Platform.isIOS()){
          current_platform = "ios";
          token = data;
          // token = data.registrationId;
        }
        else if(ionic.Platform.isAndroid()){
          current_platform = "android";
          token = data;
        }		
        WpPushServer.storeDeviceToken(current_platform, token);
      });
    });
	// triggered every time notification received
	// this event should fire when clicking on push notification.
    $rootScope.$on('$cordovaPushV5:notificationReceived', function(event, data){
      //data param will have the following params which you can use.
      // data.message,
      // data.title,
      // data.count,
      // data.sound,
      // data.image,
      // data.additionalData
	  
      //use this to navigate to a specific post:
      if(data.additionalData)
         {
           $ionicHistory.nextViewOptions({
             disableAnimate: true
           });
		   
		   
		   if(typeof data.additionalData.id != 'undefined' && !data.additionalData.foreground){
			   $state.go("app.mycategories").then(function(){
					$state.go("app.postNotification", { postId: data.additionalData.id });
			   });
		   }
         }
    });

    // triggered every time error occurs
    $rootScope.$on('$cordovaPushV5:errorOcurred', function(event, e){
      // e.message
	  console.log(JSON.stringify(data, null, 4));
    });
});
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android Samsung Galaxy J7
Emulator with Nexus 5 Android v7.1.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Android v7.1.1
Android v5.1

#### Cordova CLI version and cordova platform version
    cordova --version    8.0.0
    cordova platform version android      android 6.4.0

#### Plugin version
    cordova plugin version | grep phonegap-plugin-push   v1.10.0

#### Sample Push Data Payload
{
    "sound": "default",
    "title": "Title",
    "message": "Message",
    "additionalData": {
        "id": "78069",
        "icon": "ico.png",
        "google.message_id": "0:1533821135376304%92d0408c92d0408c",
        "google.priority": "high",
        "coldstart": false,
        "collapse_key": "com.app",
        "foreground": true
    }
}
#### Sample Code that illustrates the problem
$ionicPlatform.on("deviceready", function(){
	if (window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
    }
    if (window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleDefault();
    }
	var options = {
    	android: {
    	  senderID: GCM_SENDER_ID
    	},
      ios: {
        alert: "true",
        badge: "true",
        sound: "true"
      },
      windows: {}
    };
    var current_platform = "",
        token = "";
    // initialize
    $cordovaPushV5.initialize(options).then(function() {
      // start listening for new notifications
      $cordovaPushV5.onNotification();
      // start listening for errors
      $cordovaPushV5.onError();

      // register to get registrationId
      $cordovaPushV5.register().then(function(data) {
	  
	  SubscriptionService.saveDeviceToken(data);
        if(ionic.Platform.isIOS()){
          current_platform = "ios";
          token = data;
          // token = data.registrationId;
        }
        else if(ionic.Platform.isAndroid()){
          current_platform = "android";
          token = data;
        }		
        WpPushServer.storeDeviceToken(current_platform, token);
      });
    });
	// triggered every time notification received
	// this event should fire when clicking on push notification.
    $rootScope.$on('$cordovaPushV5:notificationReceived', function(event, data){
      //data param will have the following params which you can use.
      // data.message,
      // data.title,
      // data.count,
      // data.sound,
      // data.image,
      // data.additionalData
	  
      //use this to navigate to a specific post:
      if(data.additionalData)
         {
           $ionicHistory.nextViewOptions({
             disableAnimate: true
           });
		   
		   
		   if(typeof data.additionalData.id != 'undefined' && !data.additionalData.foreground){
			   $state.go("app.mycategories").then(function(){
					$state.go("app.postNotification", { postId: data.additionalData.id });
			   });
		   }
         }
    });

    // triggered every time error occurs
    $rootScope.$on('$cordovaPushV5:errorOcurred', function(event, e){
      // e.message
	  console.log(JSON.stringify(data, null, 4));
    });
});

**Comment by macdonst** [comment]
@saidhn I think you should open a ticket with Ionic. We don't support the `$cordovaPushV5` wrapper here, that is an Ionic thing.
