### ISSUE TITLE
Cordova run android not working 

### ISSUE THREAD

**Issue by raqib007** [phonegap/phonegap-plugin-push#2522]
* Where:
Script '***\platforms\android\phonegap-plugin-push\starter-push.gradle' line: 35

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"

My Project.Properties:

target=android-26
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=cordova-plugin-firebase/starter-build.gradle
cordova.system.library.1=com.google.gms:google-services:+
cordova.system.library.2=com.google.android.gms:play-services-tagmanager:+
cordova.system.library.3=com.google.firebase:firebase-core:+
cordova.system.library.4=com.google.firebase:firebase-messaging:+
cordova.system.library.5=com.google.firebase:firebase-crash:+
cordova.system.library.6=com.google.firebase:firebase-config:+
cordova.system.library.7=com.google.firebase:firebase-perf:+
cordova.system.library.8=com.android.support:support-v13:26.+
cordova.system.library.9=me.leolin:ShortcutBadger:1.1.17@aar
cordova.system.library.10=com.google.firebase:firebase-messaging:11.6.2
cordova.gradle.include.2=phonegap-plugin-push/starter-push.gradle

Please help ... stuck on this for two days...........

**Comment by macdonst** [comment]
#1718
