### ISSUE TITLE
Invalid data, chunk must be a string or buffer, not object

### ISSUE THREAD

**Issue by veronesecoms** [phonegap/phonegap-plugin-push#2528]
### Expected Behaviour
Open application normally after installing phonegap-plugin-push
### Actual Behaviour
After the ionic cordova run android, I get that build to find the successful success, however, the process continues to run but my application don't open. If i do a CTRL + C I get the following message:

Invalid data, chunk must be a string or buffer, not object

#### Steps to Reproduce 

I run: 

> $ ionic cordova plugin add phonegap-plugin-push
> $ npm install --save @ionic-native/push

So i try ionic cordova run android and i get one message that i don't have a google-services.json.
Ok, i go to the firebase google site and download my google-services.json and put in the same location of my build.gradle:

C:\Users\jsoftwares1\Desktop\Ionic\jcapp\appIonic\platforms\android\app

So now this message disappear, but now when i run ionic cordova run android my application don't launch and i get the message that i put in actual behavior

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 4.4.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Asus
#### Cordova CLI version and cordova platform version

    cordova --version                                    **8.0.0**
    cordova platform version android:

Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

#### Plugin version

    cordova plugin version:

cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-sim 1.3.3 "SIM"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.3 "Cordova sqlite storage plugin"
phonegap-plugin-push 2.1.3 "PushPlugin"

#### Logs taken while reproducing problem
> BUILD SUCCESSFUL in 13s
> 47 actionable tasks: 4 executed, 43 up-to-date
> Built the following apk(s):
>         C:\Users\jsoftwares1\Desktop\Ionic\jcapp\appIonic\platforms\android\app\build\outputs\apk\debug\app-debug.apk
> ANDROID_HOME=C:\Users\jsoftwares1\Desktop\tools\lib
> JAVA_HOME=C:\Program Files\Java\jdk1.8.0_181
> No target specified, deploying to device 'EBAZB6009385'.
> none
> Skipping build...
> Built the following apk(s):
>         C:\Users\jsoftwares1\Desktop\Ionic\jcapp\appIonic\platforms\android\app\build\outputs\apk\debug\app-debug.apk
> Using apk: C:\Users\jsoftwares1\Desktop\Ionic\jcapp\appIonic\platforms\android\app\build\outputs\apk\debug\app-debug.apk
> Package name: japp.jcontrole
> net.js:704
>     throw new TypeError(
>     ^
> 
> TypeError: Invalid data, chunk must be a string or buffer, not object
>     at WriteStream.Socket.write (net.js:704:11)
>     at process.<anonymous> (C:\Users\jsoftwares1\AppData\Roaming\npm\node_modules\ionic\bin\ionic:9:63)
>     at emitTwo (events.js:126:13)
>     at process.emit (events.js:214:7)
>     at emitPendingUnhandledRejections (internal/process/promises.js:108:22)
>     at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by macdonst** [comment]
@veronesecoms that error seems to be coming straight from Ionic so you should probably ask them on their forums.

**Comment by veronesecoms** [comment]
My application worked before installing phonegap-plugin-push

**Comment by veronesecoms** [comment]
after i installed this plugin, this problem appear

**Comment by macdonst** [comment]
@veronesecoms I understand but I believe it is a problem in `@ionic-native/push`.
