### ISSUE TITLE
Receiving Two Notifications - clicking one and being able to read the other after the first one has been read

### ISSUE THREAD

**Issue by GavinClarke** [phonegap/phonegap-plugin-push#253]
I am receiving two notifications, i was wondering if it is possible to press one of the notifications, then when the app reads the notification you click, can you then read the second notification from inside the app? i might have explained that badly

**Comment by macdonst** [comment]
@GavinClarke No, you did not explain it badly. Basically when you start the app you want to get notification events for all of the notifications in the shade. That's not really how things are designed. You get the event for the notification you click. You can decide if you want to clear the pending notifications on app startup. 

If you want to get notifications in your app regardless if it is in the background check issue #93.
