### ISSUE TITLE
Android build fail: Could not find com.google.firebase:firebase-core:15.0.1.

### ISSUE THREAD

**Issue by crawft** [phonegap/phonegap-plugin-push#2530]
I know this can't be a general issue but I need advice as I've searched everywhere and can't find a solution to this. My FCM version is still set to the default 11.6.2 in config, so it's unclear where this dependency is coming from.

I'm trying to use with ionic but as soon as I install this plugin my build fails. Removing the plugin makes the build succeed again.

My Google repository and play services are up to date.

### Expected Behaviour

Android builds

### Actual Behaviour

Doesn't build

#### Steps to Reproduce 

Install plugin, ionic cordova build android

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.1.0
    cordova platform version android           6.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.1.3

#### Logs taken while reproducing problem

A problem occurred configuring root project 'android'.
> 
Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find com.google.firebase:firebase-core:15.0.1.
     Required by:
         project :

**Comment by macdonst** [comment]
@crawft what other plugins are you using in your app? If you have it set to 11.6.2 in the config for this plugin it must be coming from another plugin.

**Comment by crawft** [comment]
I did think that but all I had to do to get my build working again was remove phonegap-plugin-push .

It does tally with the play services version referenced by the google maps plugin:

`
cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-geolocation": {
        "GEOLOCATION_USAGE_DESCRIPTION": "<CUT>"
      },
      "cordova-plugin-googlemaps": {
        "API_KEY_FOR_ANDROID": "<CUT>",
        "API_KEY_FOR_IOS": "<CUT>",
        "PLAY_SERVICES_VERSION": "15.0.1",
        "ANDROID_SUPPORT_V4_VERSION": "26.1.0"
      },
      "cordova-plugin-local-notification": {},
      "cordova-plugin-add-swift-support": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-advanced-http": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-file": {},
      "cordova-plugin-crop": {},
      "ionic-plugin-deeplinks": {
       <CUT>
      },
      "cordova-plugin-x-socialsharing": {},
      "cordova-plugin-camera": {},
      "cordova-plugin-youtube-video-player": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-screen-orientation": {}
`

**Comment by macdonst** [comment]
@crawft yeah, the default in this plugin and google maps don't agree. You'll just need to set the FCM_VERSION to 15.0.1 when you add this plugin to your project.

```
cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable FCM_VERSION=15.0.1.
```

**Comment by crawft** [comment]
Ok so that just caused another unmet dependency, for firebase-messaging:15.0.1.

I ended up doing some digging in the repos referenced in the project to find out why it couldn't find these things and there's a simple answer - if you check at https://dl.google.com/dl/android/maven2/index.html, there is no 15.0.1 of these libraries! Removing and reinstalling the plugin with a version of 15.0.2 gave me an error about google-services.json not being in any of the expected places, so I copied it to /platforms/android and the build now works...

Whether I can now successfully use the plugin will be another story... : )

**Comment by esol1** [comment]
I'm having the same issue and the steps to reproduce are pretty simple:

 1. Create new project
 2. cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable FCM_VERSION=15.0.2
 3. cordova plugin add cordova-plugin-googlemaps --variable
    API_KEY_FOR_ANDROID="123"  --variable API_KEY_FOR_IOS="ABC" ionic
 4. cordova platform add android@latest --variable PLAY_SERVICES_VERSION=15.0.2
 5. cordova build android

> Could not resolve all files for configuration
> ':app:debugCompileClasspath'.
> Could not find com.google.firebase:firebase-messaging:15.0.2.   Searched in the following locations:
>     file:/Users/[user]/Library/Android/sdk/extras/android/m2repository/com/google/firebase/firebase-messaging/15.0.2/firebase-messaging-15.0.2.jar
>     https://jcenter.bintray.com/com/google/firebase/firebase-messaging/15.0.2/firebase-messaging-15.0.2.pom
>      https://jcenter.bintray.com/com/google/firebase/firebase-messaging/15.0.2/firebase-messaging-15.0.2.jar
>   https://maven.google.com/com/google/firebase/firebase-messaging/15.0.2/firebase-messaging-15.0.2.pom

If those files could be located, i'm certain that this would build.  Any ideas?

**Comment by macdonst** [comment]
@esol1 I'd go in and run update in Android Studio to make sure you have all the latest tools.

**Comment by esol1** [comment]
@macdonst : Out of curiosity, are you able to build using my steps?  I've tried repeatedly and there is always an issue with firebase-messaging.  I'm sure the issue is my side but I'd feel better knowing that someone else can get this to work on their own machine.

**Comment by adrenaline15** [comment]
Hey there,

I got a similar problem with the following setup:

If im using the _phongegap-plugin-push_ in conjunction with the _cordova-plugin-googlemaps_ I'm also getting following error message:

> ` All firebase libraries must be either above or below 14.0.0`

The only possible workaround I found was to manually edit the `project.properties`-file in the folder:
> platforms/android

Changing the value/number of the firebase-messaging-library:
> cordova.system.library.6=com.google.firebase:firebase-messaging:11.6.2

to something above `14`:
> cordova.system.library.6=com.google.firebase:firebase-messaging:15.0.2

__________________

I was trying the approach @esol1 mentioned and ran into following issue while running the command:
> cordova platform add android@7.1.0 --variable PLAY_SERVICES_VERSION=15.0.2

Failed to install 'phonegap-plugin-push': CordovaError: Version of installed plugin: "cordova-support-google-services@1.1.0" does not satisfy dependency plugin requirement "cordova-support-google-services@~1.2.0". Try --force to use installed plugin as dependency.

**Comment by esol1** [comment]
@adrenaline15: When combining the Push plugin with the GoogleMaps plugin, the minimum version must be 15.0.1 because that is what the GoogleMaps plugin requires.  It should be possible to use 15.0.1 with the Push plugin but the messaging libraries won't be found and the build will fail.

**Comment by halie412** [comment]
Hello i have the same issue when i try to use phonegap-push-plugin with cordova-plugin-googlemaps at same app, i try phonegap-push-plugin with variable --variable FCM_VERSION=15.0.1 but get this error:

> cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable FCM_VERSION=15.0.1

> Failed to install 'phonegap-plugin-push': CordovaError: Version of installed plugin: "cordova-support-google-services@1.1.0" does not satisfy dependency plugin requirement "cordova-support-google-services@~1.2.0". Try --force to use installed plugin as dependency.

I also try adding the android platform with variable PLAY_SERVICES_VERSION 15.0.1

> cordova platform add android@7.1.0 --variable PLAY_SERVICES_VERSION=15.0.1

I also try to update manually cordova-support-google-services to 1.2.1 but didn´t work

Any solution yet?

**Comment by github-jorgem** [comment]
I had the same problem. I managed to resolve this by manually editing the `platforms/android/app/build.grade` file. I updated `com.google.firebase:firebase-messaging:X.X.X` to `com.google.firebase:firebase-messaging:17.3.4`. Apparently, as of Oct 18 2018, `17.3.4` is the latest.

````
dependencies {
   ... [truncated] ...
  compile "com.google.firebase:firebase-messaging:17.3.4"
}
````
