### ISSUE TITLE
Apple rejected the application when submit on Store when I enabled ios.voip with error Your app declares support for VoIP in the UIBackgroundModes key in your Info.plist, but it does not include any Voice over IP services.

### ISSUE THREAD

**Issue by phamminhvu** [phonegap/phonegap-plugin-push#2531]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by jcesarmobile** [comment]
Do you use VOIP services? if you do, then talk with Apple people and tell them you have VOIP functionality. If you don't, then don't enable the VOIP background mode.

**Comment by jcesarmobile** [comment]
You can't do that, Apple doesn't allow it, it has nothing to do with the plugin, but with Apple rules.

**Comment by phamminhvu** [comment]
Hi @jcesarmobile 

Could you suggest me some open source VoIP service for integration?

Thank you very much!
