### ISSUE TITLE
Apple rejected the app when use VoIp Push with reason: Your app declares support for VoIP in the UIBackgroundModes key in your Info.plist, but it does not include any Voice over IP services.

### ISSUE THREAD

**Issue by phamminhvu** [phonegap/phonegap-plugin-push#2532]
### Expected Behaviour
I would like to use VoIp Push notification. and Apple must approve the app.
### Actual Behaviour
Apple reject the app
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
#2531
