### ISSUE TITLE
How to use FCM for iOS?

### ISSUE THREAD

**Issue by fapowell** [phonegap/phonegap-plugin-push#2535]
In the documentation, there is a section titled: "iOS GCM support" under .init() that provides two properties that "are used if you want use GCM on iOS".  I set the first one -- ios.fcmSandbox -- since we want to use iOS through FCM.  However, it doesn't appear that FCM is being used.  How do I select FCM as the service to use on init?

I should note that I am getting an "Invalid registration token. Check the token format." When trying to push.  It seems that I'm not getting an FCM token in .on('registration')

Thanks!

**Comment by macdonst** [comment]
@fapowell please read the installation instructions with regards to the plist file you need to deliver for FCM support. Also…

Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
