### ISSUE TITLE
Cannot build android on version 2.1.3

### ISSUE THREAD

**Issue by burtontanner** [phonegap/phonegap-plugin-push#2537]
### Expected Behaviour
the project will build on android

### Actual Behaviour
the project will not build

### Reproduce Scenario (including but not limited to)
install push plugin and try to build

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
android 7.0.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
any
#### Cordova CLI version and cordova platform version

    cordova --version                                    8.0.0
    cordova platform version android                     7.0.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.1.3

#### Logs taken while reproducing problem
(node:79798) UnhandledPromiseRejectionWarning: Error: Source path does not exist: google-services.json

**Comment by jcesarmobile** [comment]
As the error says, you need the google-services.json file

**Comment by burtontanner** [comment]
@jcesarmobile I didn't need that file before this plugin. Could you tell me what I need to put in this file? Or could your plugin create this file on installation?

**Comment by jcesarmobile** [comment]
You have to download it from firebase console, it’s a requirement for push notifications, it contains information about your project and google provides it after project creation (on firebase console)
