### ISSUE TITLE
Android PushHandlerActivity -> onCreate(Bundle savedInstanceState)

### ISSUE THREAD

**Issue by rainchen163** [phonegap/phonegap-plugin-push#2538]
###      I show that in this source code,  there is follow code, use the finish(); before dismissed, I don't understand it. Is that means this will finish before run to the backgroud? 
       finish();

      if(!dismissed) {
            Log.d(LOG_TAG, "isPushPluginActive = " + isPushPluginActive);
            if (!isPushPluginActive && foreground && inline) {
                Log.d(LOG_TAG, "forceMainActivityReload");
                forceMainActivityReload(false);
            } else if(startOnBackground) {
                Log.d(LOG_TAG, "startOnBackgroundTrue");
                forceMainActivityReload(true);
            } else {
                Log.d(LOG_TAG, "don't want main activity");
            }
        }

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
