### ISSUE TITLE
Plugin doesn't support this project's cordova-android version. cordova-android: 6.3.0, failed version requirement: >=7.1.0

### ISSUE THREAD

**Issue by Neustart** [phonegap/phonegap-plugin-push#2539]
### Actual Behaviour
I am using Ionic v1 and I can't add phonegap-plugin-push plugin.

#### Steps to Reproduce 
`cordova platform add android@6.3.0`
`cordova plugin add phonegap-plugin-push@2.1.2`
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0
#### Cordova CLI version and cordova platform version

    cordova --version                                    # 6.4.0
    cordova platform version android                     # android 6.3.0

#### Plugin version
phonegap-plugin-push 2.2.3 "PushPlugin" // I removed this plugin by rm command but each time see such version here

#### Logs taken while reproducing problem
```
cordova plugin add phonegap-plugin-push@2.1.2
Installing "phonegap-plugin-push" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.3.0, failed version requirement: >=7.1.0
Skipping 'phonegap-plugin-push' for android
Plugin "phonegap-plugin-push" already installed on browser.
Adding phonegap-plugin-push to package.json
Saved plugin info for "phonegap-plugin-push" to config.xml
```

**Comment by macdonst** [comment]
@Neustart you are using cordova 6.4.0 but the plugin needs 7.1.0 or later. So you'll need to update your version of the cordova cli.

**Comment by Neustart** [comment]
@macdonst I can't use > 7.1. I have a lot of dependencies related on version 6.4.0 which are haven't back compatibility with >7.4. That's why I using not the latest build of this plugin. Which version I can use without problem with 6.4.0 or 6.3.0 ? I tried all of them without success

**Comment by jcesarmobile** [comment]
Try the last 2.1.x

**Comment by macdonst** [comment]
@Neustart that's a really old version of cordova. The last plugin version to support it is 1.9.x as per https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements
