### ISSUE TITLE
Android isn't displaying the notification when the app is closed or in background

### ISSUE THREAD

**Issue by jlamim** [phonegap/phonegap-plugin-push#254]
I developed an app that is using push notification services, but when he is in background or closed, in the Android, the push notifications isn't displayed. 

In the iOS, the notifications are displayed in foreground and background mode.

The fact of not working in Android, is a limitation of plugin or limitation of Android?

**Comment by macdonst** [comment]
@jlamim when the app is in the foreground the 'notification' callback should be invoked. When the app is in the background you should see it in the notification shade provided by the OS. Are you not seeing it in the notification shade?

**Comment by jlamim** [comment]
@macdonst 
No notification is received when the app is in the background. I monitored using the "Monitor" to see if it showed anything at console.log command, but nothing happens.

This link has the code I use to retrieve notifications:

http://pastebin.com/6z1MitDS

**Comment by macdonst** [comment]
@jlamim that is by design. When you send a message to the app and it is in the foreground your 'notification' event will be called. If your app is in the background then the 'notification' event is not called, instead you get a notification in the shade of your phone.

Issue #93 talks about having the 'notification' event called when the app is in the background.

**Comment by jlamim** [comment]
@macdonst Yes, but talks about notification in iOS, and my problem is in Android, specifically.

**Comment by macdonst** [comment]
@jlamim if you don't send a title/message as part of the push on Android it will call your notification event handler. Try it now :)

**Comment by macdonst** [comment]
@jlamim please re-open if you can still reproduce this problem with release 1.4.0 and can provide me a reproduction scenario.

**Comment by Truedison** [comment]
@macdonst What do you mean by title/message as part of the push on Android? My code is working on all screnarios for IOs, But for android I dont have luck in android when the app is closed thanks.
