### ISSUE TITLE
 Error: spawn EACCES     

### ISSUE THREAD

**Issue by Selma-Casteloes** [phonegap/phonegap-plugin-push#2544]
### Expected Behaviour
Able to install the plugin
### Actual Behaviour
No able to install the plugin
### Reproduce Scenario (including but not limited to)
Just "run npm run cordova plugin add phonegap-plugin-push " and you will get an error
#### Steps to Reproduce 

Just "cordova plugin add phonegap-plugin-push " and you will get the error below

Subproject Path: CordovaLib
Failed to install 'phonegap-plugin-push': Error: spawn EACCES
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

ANDROID_HOME=/Users/sc601u/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home
Subproject Path: CordovaLib

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Galaxy S9

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.0.0
    cordova platform version android                     android@6.4.0"

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by jcesarmobile** [comment]
The command is cordova plugin add phonegap-plugin-push

**Comment by Selma-Casteloes** [comment]
I get the same thing running "cordova plugin add phonegap-plugin-push"  @jcesarmobile

**Comment by jcesarmobile** [comment]
Still not a plugin issue, looks like a permission issue, so check your npm permissions, project permissions, etc. Avoid using sudo when creating projects or running cordova commands

**Comment by jcesarmobile** [comment]
Still not a plugin issue, looks like a permission issue, so check your npm permissions, project permissions, etc. Avoid using sudo when creating projects or running cordova commands
