### ISSUE TITLE
Notification Channels Docs Differ

### ISSUE THREAD

**Issue by Nick-lab** [phonegap/phonegap-plugin-push#2546]
### Expected Behaviour
Expected Behavior of Notification Channel Create
### Actual Behaviour
`PushNotification.createChannel();` expects 1 argument not 3 so success and error callbacks don't go in the function call. I tested adding them to the Promise portion but doesn't like the success variable.

so either i'm using the wrong imported object or the docs are different from the build.

### Reproduce Scenario (including but not limited to)
npm install latest phonegap-plugin-push v2.2.3

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
N/A
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
N/A
#### Cordova CLI version and cordova platform version

    cordova: 8.0.0
    cordova platform version android: 7.0.0
#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

#### Sample Push Data Payload
N/A
#### Sample Code that illustrates the problem

    cosntructor(private push: Push){ 
        if (platform.is('android')) {
        var channelId = 'appdefault';
        push.createChannel(
          () => {
            console.log('success');
          },
          () => {
            console.log('error');
          },
          {
            id: 'testchannel1',
            description: 'My first test channel',
            importance: 3,
            vibration: true
          }
        );
        // this is my attempt at using it the way it says
        // push.createChannel( { options: object } ).then((err: any) => { });
      }
    }

#### Logs taken while reproducing problem
N/A

**Comment by Nick-lab** [comment]
well darn guys 4 days and nothing back??

**Comment by jcesarmobile** [comment]
Are you paying for premium support or something?

Also, of those 4 days, 2 were weekend.

I think you have very high expectations on free open source projects/plugins. Considering there are another 199 open issues, 4 days is nothing.

**Comment by jcesarmobile** [comment]
BTW, are you using typescript? where did you get the types from? probably the problem is there

**Comment by Nick-lab** [comment]
its not like i'm reporting a bug @jcesarmobile  i'm just wondering the correct format of the notification channel object. i dont want to crowd the issues inbox about stupid little stuff like why the PushNotification.createChannel function doesn't take 3 arguments but thats what the Documents say it takes and its not taking those arguments in practice.

**Comment by Nick-lab** [comment]
the types came from the npm package. soooo i guess what your saying is yes there is an issue with the phonegap-plugin-push types file

**Comment by jcesarmobile** [comment]
The types don't even have createChannel, so yes, there are problems with the types. 
The js method takes the 3 params.

**Comment by Nick-lab** [comment]
hmmm well that explains some except . . .
![image](https://user-images.githubusercontent.com/32395162/45638272-b9284280-ba7a-11e8-93ed-621c8550fb8e.png)

**Comment by jcesarmobile** [comment]
So you are using ionic-native types, not the plugin ones.

So you have to do it the ionic-native way, just pass the channel, the then part should contain your current success callback, and add a catch for the error one

```
this.push.createChannel({
 id: "testchannel1",
 description: "My first test channel",
 // The importance property goes from 1 = Lowest, 2 = Low, 3 = Normal, 4 = High and 5 = Highest.
 importance: 3
}).then(() => console.log('Channel created'));
````
Ionic native wraps the callbacks into a promise, that's why it only has one param instead of the 3 the js API has.

**Comment by Nick-lab** [comment]
unfortunately i might have to open a new issue for this as the way the createChannel is setup and tested is the Correct way to do it and is still not working for Android O.
