### ISSUE TITLE
on("notification") not called when iOS app in foreground

### ISSUE THREAD

**Issue by rudiminty** [phonegap/phonegap-plugin-push#2547]
When I receive a push notification on iOS while the app is in the foreground, the on("notification") function should be triggered.

When the app is in the foreground, the push notification is received and displayed as a normal notification in the notification centre and does not trigger the on("notification") function.
When I select the notification however, it does trigger the on("notification") function with the push notification payload.
The behaviour works as expected on Android.

When I run my app using cli-6.5.0 on the plugin version 1.11.1 then it works as expected, but not when using cli-7.5.0 with plugin version 1.11.1 or 2.1.2.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
cli-7.1.0 (iOS 4.5.4 / Android 6.3.0)

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Testing on iPhone 6s with iOS 11.1

#### Plugin version

    plugin versions tested 1.11.1 & 2.1.2 with the same issue.

#### Sample Code that illustrates the problem
        try {
            push = PushNotification.init({
                "android": {
                    "senderID": "XXX",
                    "forceShow": false,
                    "sound": true,
                    "vibrate": true
                },
                "ios": {
                    alert: true,
                    badge: true,
                    sound: true
                },
                "windows": {}
               
            });
        } catch (exc) {
            mobile.alert('Error Initializing Push Notifications: ' + exc.message);
            push = false;
        }
            if (push) {
                push.on("registration", function (data) {
                    // registration info here
                });

                push.on("error", function (e) {
                    mobile.alert("Push Notification Error: " + e.message);
                });

                push.on("notification", function (data) {
                    mobile.alert('NOTIFICATION [' + JSON.stringify(data) + '] processing...');
                    // logic goes here
                });

            }

**Comment by rudiminty** [comment]
With some more tests, I actually notice that when the app is open in the foreground, and a push notification is received and I select the message, the data being passed to the on("notification") function indicates "foreground":false while the app is most definitely open.

**Comment by umeshiyer** [comment]
rudiminty
Do you have katzer's local notification plugin also included in your project?

**Comment by macdonst** [comment]
@rudiminty you shouldn't see the notification in the shade when the app is in the foreground. As @umeshiyer asked are you using the local notification plugin?

**Comment by rudiminty** [comment]
Thanks for the responses.

@umeshiyer , no not using local notification plugin. 

I have however by means of elimination noticed that the plugin cordova-plugin-mauron85-background-geolocation is most probably the cause with this specific issue perhaps contributing: https://github.com/mauron85/react-native-background-geolocation/pull/268#issuecomment-421388413
