### ISSUE TITLE
 How can I redirect to a page by clicking on the ionic push notifications while the mobile application is in the background? 

### ISSUE THREAD

**Issue by joelgo** [phonegap/phonegap-plugin-push#2548]
This code works when the application is in the foreground, but not when it is in the background. What can I do to redirect me to a specific page of the application in ionic 3 for android and ios.

@Injectable()
export class NotifyService {
    
    constructor(private push: Push, public alertCtrl: AlertController, public app: App) {

    }

    initPushNotification(){
        // to initialize push notifications
        const options: PushOptions = {
            android: {
                senderID:'your_id_proyect',
                sound: true,
                forceShow: true,
                vibrate: true,
                icon: 'icon',
                iconColor: 'color'
            },
            ios: {
                alert: 'true',
                badge: true,
                sound: 'false'
            },
            windows: {},
            browser: {
                pushServiceURL: 'http://push.api.phonegap.com/v1/push'
            }
        };
        const pushObject: PushObject = this.push.init(options);

        pushObject.on('notification').subscribe((notification: any) =>
            {

                if(notification.message=='Ha realizado una solicitud de permiso'){
                    this.app.getActiveNavs()[0].push(RequestPage);
                }

                if(notification.message=='Aceptó la solicitud de permiso'){

                    this.app.getActiveNavs()[0].push(RequestPage);
                }

                if(notification.message=='Rechazo la solicitud de permiso'){
                   /* var nav = this.app.getActiveNav();
                    nav.setRoot(RejectedPage); */
                    this.app.getActiveNavs()[0].push(RejectedPage);
                }

            }
        );
        pushObject.on('error').subscribe(error => console.error('Error with Push plugin', error));
    }

}

**Comment by macdonst** [comment]
@joelgo if you want it to happen when the app is in the background then you need to send a background notification:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications-1

**Comment by joelgo** [comment]
I added it as the tutorial says but likewise the application when it is in the background after receiving the notification and clicking on it just opens the app but does not execute on (Notification); where I have a function that redirects me to a specific page.


tokens_and.append(item['token'])
                extra = {'body': mensaje, 'title': name, 'color': 'Blue', 'icon': 'drawable-ldpi-icon.png'}
                dataRaw_android = {
                    "notification": extra,
                    "registration_ids": tokens_and,
                    "content_available": "1"
                }

**Comment by 2gen** [comment]
@joelgo Having the same problem. Did you find a solution?

**Comment by joelgo** [comment]
[image: image.png]



Of course, yes, for android apply the following and it works normal.
