### ISSUE TITLE
coldstart not set properly on Android

### ISSUE THREAD

**Issue by gkustas** [phonegap/phonegap-plugin-push#2549]
### Expected Behaviour
When the app is launched by the user tapping the notification, I expect one notification with coldstart=true
When the app is already launched and in the background or foreground when a notification is received, I expect one notification with coldstart=false

### Actual Behaviour
When app is launched by user tapping notification, I receive two notifications: the first one has coldstart=false, the second coldstart=true

When the app is already launched and in the background I receive one notification with coldstart=true

When the app is already launched and in the foreground I receive one notification with coldstart=false (as expected)

### Reproduce Scenario (including but not limited to)
Send push notifications to android device while app is not running, running in the background or running in the foreground

#### Steps to Reproduce
All push notifications behave the same way, independent of the payload

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy S6

#### Cordova CLI version and cordova platform version

    cordova  (Phonegap CLI) -- 7.1.0
    cordova platform version android -- 6.3.0

#### Plugin version

   2.1.2

#### Sample Push Data Payload
When app is not running (launched by tap on notification):

addl data: {"notificationTypeID":"1","content-available":"1","custom":{"eventID":0,"reservationID":26461889,"invitationID":1674},"notificationID":"3054","subscriptionID":"dLozID9tGFE:APA91bE5vdhA80yrN5QM76n4oOB7kBCqu4MoXF1sUHYgHN5_CrSWPLTr_1sLFKzVrvHfAT2lfb9gyyRMmwCX1SMgDvl_MPEgKz0P50oSILLibaLSPOxuyqlwjFJnhtZt4wtNexlB5qKx","coldstart":false,"foreground":false}}

addl data: {"notificationTypeID":"1","content-available":"1","custom":{"eventID":0,"reservationID":26461889,"invitationID":1674},"dismissed":false,"notificationID":"3054","subscriptionID":"dLozID9tGFE:APA91bE5vdhA80yrN5QM76n4oOB7kBCqu4MoXF1sUHYgHN5_CrSWPLTr_1sLFKzVrvHfAT2lfb9gyyRMmwCX1SMgDvl_MPEgKz0P50oSILLibaLSPOxuyqlwjFJnhtZt4wtNexlB5qKx","coldstart":true,"foreground":false}}

When app is in background:

addl data: {"notificationTypeID":"1","content-available":"1","custom":{"eventID":0,"reservationID":26461889,"invitationID":1674},"notificationID":"3045","subscriptionID":"dLozID9tGFE:APA91bE5vdhA80yrN5QM76n4oOB7kBCqu4MoXF1sUHYgHN5_CrSWPLTr_1sLFKzVrvHfAT2lfb9gyyRMmwCX1SMgDvl_MPEgKz0P50oSILLibaLSPOxuyqlwjFJnhtZt4wtNexlB5qKx","coldstart":true,"foreground":false}}

When app is in foreground:

addl data: {"notificationTypeID":"1","content-available":"1","custom":{"eventID":0,"reservationID":26461889,"invitationID":1674},"notificationID":"3063","subscriptionID":"dLozID9tGFE:APA91bE5vdhA80yrN5QM76n4oOB7kBCqu4MoXF1sUHYgHN5_CrSWPLTr_1sLFKzVrvHfAT2lfb9gyyRMmwCX1SMgDvl_MPEgKz0P50oSILLibaLSPOxuyqlwjFJnhtZt4wtNexlB5qKx","coldstart":false,"foreground":true}}

#### Sample Code that illustrates the problem
Which code would help with this?

#### Logs taken while reproducing problem

Where can I find log files that may help you?

**Comment by macdonst** [comment]
@gkustas this looks like proper behaviour. You are sending `content-available: 1` which wakes up the app and you get `coldstart: true` for the first notification event, then you click on the notification in the shade and the second notification event is `coldstart: false` as the app has already been started in the background.
