### ISSUE TITLE
Notification in background doesn't open an app

### ISSUE THREAD

**Issue by d-mh** [phonegap/phonegap-plugin-push#2551]
### Expected Behaviour
Clicking on notification should open an app and call on('notification') event. I would like to wait for user to click for notification, then app is opening and on('notification') event is triggered.  I don't want to use content-available options.

### Actual Behaviour
When app is closed or is in background I am receiving notification in status bar, after clicking on it nothing happens - app is not opened. In foreground mode where app is open I am receiving notification with data successfully. 

#### Steps to Reproduce 

Launch mode in AndroidManifest.xml: android:launchMode="singleTop" 

I tried with "notification": {"title": "title", "body":"body"} payload - it opened an app, but on('notification') event was not triggered. 

#### Cordova CLI version and cordova platform version

    cordova --version                                    8.0.0
    cordova platform version android                     7.1.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.2.3

#### Sample Push Data Payload
{
  "payload": {
    "services": {
      "apns": {
        "aps": {
          "alert": {
            "title": "Test notification for DM",
            "body": "Test notification for DM"
          },
          "badge": 1,
          "sound": "default"
        },
        "queryParams": {},
        "title": "Test notification for DM",
        "body": "Test notification for DM",
        "entityName": "contacts",
        "entityID": "300000007365680"
      },
      "fcm": {
        "data": {
          "queryParams": {},
          "title": "Test notification for DM",
          "message": "Test notification for DM",
          "entityName": "contacts",
          "entityID": "300000007365680"
        }
      }
    }
  }
}

#### Logs taken while reproducing problem

WHEN IN BACKGROUND - APP IS NOT OPENED

V/Push_Plugin(24292): execute: action=init
V/Push_Plugin(24292): execute: data=[{"android":{"icon":"fapp-icon","iconColor":"#FF0000"}}]
V/Push_Plugin(24292): execute: jo={"icon":"fapp-icon","iconColor":"#FF0000"}
V/Push_Plugin(24292): execute: senderID=292929820186
V/Push_Plugin(24292): onRegistered: {"registrationId":"reg id here","registrationType":"FCM"}
D/Push_FCMService(24292): onMessage - from: 292929820186
D/Push_FCMService(24292): sender id = 292929820186
D/Push_FCMService(24292): normalize extras
D/Push_FCMService(24292): key = entityID
D/Push_FCMService(24292): replace key entityID with entityID
D/Push_FCMService(24292): key = entityName
D/Push_FCMService(24292): replace key entityName with entityName
D/Push_FCMService(24292): key = queryParams
D/Push_FCMService(24292): replace key queryParams with queryParams
D/Push_FCMService(24292): key = notId
D/Push_FCMService(24292): replace key notId with notId
D/Push_FCMService(24292): key = title
D/Push_FCMService(24292): replace key title with title
D/Push_FCMService(24292): no locale found for key = title, error Value Test of type java.lang.String cannot be converted to JSONObject
D/Push_FCMService(24292): key = message
D/Push_FCMService(24292): replace key message with message
D/Push_FCMService(24292): no locale found for key = message, error Value Test of type java.lang.String cannot be converted to JSONObject
D/Push_FCMService(24292): background
D/Push_FCMService(24292): message =[Test notification for DM]
D/Push_FCMService(24292): title =[Test notification for DM]
D/Push_FCMService(24292): contentAvailable =[null]
D/Push_FCMService(24292): forceStart =[null]
D/Push_FCMService(24292): create notification
D/Push_FCMService(24292): stored icon=fapp-icon
D/Push_FCMService(24292): stored iconColor=#FF0000
D/Push_FCMService(24292): stored sound=true
D/Push_FCMService(24292): stored vibrate=true
D/Push_FCMService(24292): using icon from plugin options
D/Push_FCMService(24292): no icon resource found - using application icon
D/Push_FCMService(24292): create actions: with in-line
I/ActivityManager(  816): START u0 {flg=0x24000000 cmp=com.fapp.fappapp/com.adobe.phonegap.push.PushHandlerActivity (has extras)} from uid 10234 on display 0

WHEN IN FOREGROUND - WORKING

D/Push_FCMService(24292): onMessage - from: 292929820186
D/Push_FCMService(24292): sender id = 292929820186
D/Push_FCMService(24292): normalize extras
D/Push_FCMService(24292): key = entityID
D/Push_FCMService(24292): replace key entityID with entityID
D/Push_FCMService(24292): key = entityName
D/Push_FCMService(24292): replace key entityName with entityName
D/Push_FCMService(24292): key = queryParams
D/Push_FCMService(24292): replace key queryParams with queryParams
D/Push_FCMService(24292): key = notId
D/Push_FCMService(24292): replace key notId with notId
D/Push_FCMService(24292): key = title
D/Push_FCMService(24292): replace key title with title
D/Push_FCMService(24292): no locale found for key = title, error Value Test of type java.lang.String cannot be converted to JSONObject
D/Push_FCMService(24292): key = message
D/Push_FCMService(24292): replace key message with message
D/Push_FCMService(24292): no locale found for key = message, error Value Test of type java.lang.String cannot be converted to JSONObject
D/Push_FCMService(24292): foreground
D/Push_Plugin(24292): convert extras to json
D/Push_Plugin(24292): key = entityID
D/Push_Plugin(24292): key = entityName
D/Push_Plugin(24292): key = queryParams
D/Push_Plugin(24292): key = notId
D/Push_Plugin(24292): key = title
D/Push_Plugin(24292): key = message
D/Push_Plugin(24292): key = coldstart
D/Push_Plugin(24292): key = foreground
V/Push_Plugin(24292): extrasToJSON: {"title":"Test notification for DM","message":"Test notification for DM","additionalData":{"entityID":"300000007365680","entityName":"contacts","queryParams":{},"notId":"10","coldstart":false,"foreground":true}}

V/Push_Plugin(24292): execute: action=setApplicationIconBadgeNumber
V/Push_Plugin(24292): setApplicationIconBadgeNumber: data=[{"badge":0}]

**Comment by macdonst** [comment]
@d-mh it doesn't look like `PushHandlerActivity` is ever called. What version of Android are you using? What device is this?

**Comment by d-mh** [comment]
I have solved that - thats right, PushHandlerActivity was not called as this line was removed by cordova from AndroidManifest.xml:
`<activity android:exported="true" android:name="com.adobe.phonegap.push.PushHandlerActivity" android:permission="${applicationId}.permission.PushHandlerActivity" />`

I don't know why, but after multiple cordova run android - cordova deleted lines related to push plugin.

Right know I will use Android Studio ...

Thanks.
