### ISSUE TITLE
UI API called from background thread

### ISSUE THREAD

**Issue by desmeit** [phonegap/phonegap-plugin-push#2554]
IOS 11.4.1
Cordova 4.5.5
push plugin 2.2.3

I get the following error in Xcode:

`UI API called from background thread: -[UIApplication setApplicationIconBadgeNumber:] must be used from main thread only`

It should be fixed in version 2.1.0, as it written here:

https://github.com/phonegap/phonegap-plugin-push/issues/1988

but the issue still occurs.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
