### ISSUE TITLE
inline reply does not fire as expected

### ISSUE THREAD

**Issue by sprahl** [phonegap/phonegap-plugin-push#2555]
Hello experts,
I am probably asking a very basic question here.
I have found out that action buttons with ther callback='mycallback' fire in push.on('mycallback', data => {});.
My question here is how to get an action button with inline=true to fire.

I get the notification just fine, can click the button with the label "replyLabel" payload but nothing appears to happen once I click the send button.
If I then send a Notification without inline: true, I can access the text I typed.

The problem, therefore, appears to be that while inline:false opens the app and allows me to access the data, inline:true only allows me to enter text but does not open the app and thus allow me to access the data I need.

Any help would be greatly appreciated!

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by sprahl** [comment]
Sorry about that, guess I'll read the guidelines next. Still, thank you very much for maintaining the plugin. I like it very much.
Greetings

⁣Viele Grüße,
Stefan Prahl​
