### ISSUE TITLE
Not getting registration ID on .apk, but works on phonegap while developing

### ISSUE THREAD

**Issue by pedrofidalgomrs** [phonegap/phonegap-plugin-push#2557]
So i have this on my app.js: 

```
$$(document).on('deviceready', function() {

const push = PushNotification.init({
            android: {
            },
            browser: {
                pushServiceURL: 'http://push.api.phonegap.com/v1/push'
            },
            ios: {
                alert: "true",
                badge: "true",
                sound: "true"
            },
            windows: {}
        });
        
        push.on('registration', (data) => {
            alert(data.registrationId);
            var registrationId=data.registrationId;
                var dataString ="id_usuario="+registrationId;
                if($.trim(registrationId).length>0){
                    $.ajax({
                        type: "POST",
                        url: "https://pizzarte.com/app/registarid.php",
                        data: dataString,
                        crossDomain: true,
                        cache: false,
                    })
                }
        });
    
        push.on('notification', (data) => {

        });
        
        push.on('error', (e) => {

        });
});
```

I dont have anything on the notification function, because im only storing the registrationID on my database, to then use php to send notifications. While testing with the phonegap app, on my phone, i get the alert with the registrationID and it stores on the database.

When i compile the .apk, and run the apk on my phone, when i open the app, there is no alert at all, and of course it doenst store on the database because it isn't getting the registration ID. What am i doing wrong?

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
