### ISSUE TITLE
Can we fire the Permissions prompt again?

### ISSUE THREAD

**Issue by davelinares** [phonegap/phonegap-plugin-push#2559]
Let me explain a scenario:

1 - Your app starts and the prompt to allow notifications is declined by the user.
2- After 1 week, the user wants to allow the notifications

I can control with hasPermission==false and the question is... Can we fire the Permissions promt again? Or user needs to go to ios settings to revert the notifications status? 

Thank you!

**Comment by jcesarmobile** [comment]
No, you can't, the permission is requested by the system and the system only ask once.

He can always change the settings in settings app. How would you know he changed his mind?
If you can certainly know that he changed his mind, all you can do is open settings app to make it a bit easier
