### ISSUE TITLE
Add sample icon

### ISSUE THREAD

**Issue by rubenstolk** [phonegap/phonegap-plugin-push#256]
Like a lot of other people I'm having trouble getting the notification icon in the STATUS BAR to work. According to the documentation it should work by specifying this in the `init` function, however I just keep getting a white/gray square there.

Perhaps someone can provide a sample project where this is working properly?

**Comment by macdonst** [comment]
@rubenstolk does the icon you specify in init have any transparency?

**Comment by rubenstolk** [comment]
@macdonst Yes it does, it it not supposed to have?

**Comment by macdonst** [comment]
@rubenstolk Android 5.0 and later will take your icon and completely white wash the icon, i.e. replace each non-white pixel with a white pixel except for the transparent pixels. It's explained here:

https://github.com/phonegap/phonegap-plugin-push#images
https://www.google.com/design/spec/style/icons.html#

You can use the attached phonegap icon which has transparency as know working test icon. 

![phonegap-logo-simple](https://cloud.githubusercontent.com/assets/353180/10667362/02778722-78a5-11e5-8fb2-7a2598136f2d.png)

You'll need to copy the image to `<project>/platforms/android/res/drawable`, rename it `phonegap.png` and call init with the following parameter:

```
var push = PushNotification.init({ 
        "android": { 
            "senderID": "Your Sender ID", "icon": "phonegap", "iconColor": "blue"}, 
        "ios": {"alert": "true", "badge": "true", "sound": "true"}, "windows": {} 
    });
```

and then you should get an icon that doesn't look like a white square in the status bar.

**Comment by rubenstolk** [comment]
Right, so I had an icon with only white and transparent, if I understand correctly, I have to make everything that is transparent black... Will try that!

**Comment by macdonst** [comment]
@rubenstolk can you send me your icon so I can take a look?

**Comment by rubenstolk** [comment]
Give me 10 minutes, it seems the actual issue was that I was using `drawables` folder instead of `drawable`. Trying my way out now and will let you know!

**Comment by Fr4ncx** [comment]
@macdonst  Not work for me.. ` if (ionic.Platform.isAndroid()) {
        config = {
          "senderID": "290439193995",
          "icon": "phonegap",
          "iconColor": "blue"
        };
      }`
what am I doing wrong ? :S

**Comment by macdonst** [comment]
@Fr4ncx well is the "phonegap.png" file copied to platforms/android/res/drawables?

**Comment by Fr4ncx** [comment]
yes but not work for me..

**Comment by gianpaj** [comment]
It's in the `drawable` directory. for example `platforms/android/res/drawable/notification.png`

then:
```ts
     const pushOpt: PushOptions = {
        android: {
          senderID: PUSH_SENDER_ID,
          // image file should be located in the Android drawables folder
          icon: 'notification',
          iconColor: '#484848'
        }
      };
```

See the source code: 
https://github.com/phonegap/phonegap-plugin-push/blob/630907cf3d8802bcd5d91b6bd768c989f6ef897a/src/android/com/adobe/phonegap/push/PushConstants.java#L19
https://github.com/phonegap/phonegap-plugin-push/blob/3acdfa338d7a8b56ec4dc73c50aa9917ecb3be7c/src/android/com/adobe/phonegap/push/GCMIntentService.java#L506

I made a PR to fix this confusion in the Docs: https://github.com/phonegap/phonegap-plugin-push/pull/1711
