### ISSUE TITLE
[Android] Background Notification Cannot Be Processed After Going to Background for Some Time

### ISSUE THREAD

**Issue by edmondchui** [phonegap/phonegap-plugin-push#2563]
### Expected Behaviour

Background notification sent via FCM should be processed in the following scenarios:

1. When the app is put in to background and showing up in Recent Apps.
2. When the app is force closed in the background.

### Actual Behaviour

1. Background notification is processed successfully within 5 min after being put into background. However, when going idle in the background for 10 min, subsequent background notification cannot be processed.
2. Background notification is processed successfully when the app is force closed in the background.

### Reproduce Scenario (including but not limited to)

The following `data` payload is used in both scenarios described in the **Actual Behaviour** section

```json
data: {
  "content-available": 1,
  "force-start": 1,
  "no-cache": 1,
  "notId": 1234
}
```

#### Steps to Reproduce 

1. Start the cordova app and put it in background.
2. Send an FCM notification (I'm using the Ruby gem `andpush`) within 3 min of the app going to background.
    > The background notification is processed properly.
3. Wait for 10 min and send another FCM notification
    > The background notification is not processed.
4. Force close the cordova app in the background by pressing the Recent Apps button and swipe the app.
5. send another FCM notification
    > The app is waken up and processes the background notification successfully.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 7.1 and Android 8.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Nexus 6p (Android 8.0), Asus ZenPad 3s 10, 

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    > 8.0.0
    cordova platform version android                     # e.g. 4.1.1
    > Installed platforms:
        android 7.1.0
        ios 4.5.5

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3
    > 2.2.3

#### Sample Push Data Payload

```json
{
  "to": "<registration token>",
  "data": {
    "content-available": 1,
    "force-start": 1,
    "no-cache": 1,
    "notId": 1234,
    "textMessage": "Notification Processed"
}
```

#### Sample Code that illustrates the problem

Use `cordova-plugin-local-notifications` to show the data in incoming FCM notification

```js
var pushNotificationOptions = {
  android: {
    senderID: <FCM Project Number>,
    forceShow: false
  },
  ios: {
    alert: true,
    badge: true,
    sound: true
  }
};

var push = PushNotification.init(pushNotificationOptions);

push.on('notification', function(data) {
  makeServerApiCall();  // Send HTTP request to server.
  cordova.plugins.notification.local.schedule(
    {
      text: data.additionalData.textMessage
    }
  );
});
```

#### Logs taken while reproducing problem

N/A.

**Comment by seang96** [comment]
It is reproducible on my OnePlus 5t running on 8.1.0. 

Things I noticed:

1. On Step 3, logs did not produce the normal log outputs for mapping the keys.
2. If you skip to step 4 and force close the app, the first notification will go through and future ones will log mappings, but no notification will be shown.
3. On step 5 the app actually opens in the foreground. I see this as insanely obtrusive for starting back up. Does it absolutely need to do this?

**Comment by edmondchui** [comment]
@seang96 In Step 5 my app does not open in the foreground. It stays in the background for subsequent FCM notifications.

**Comment by seang96** [comment]
@edmondchui interesting, I wonder why this occurs for me then.

**Comment by seang96** [comment]
I fixed my issue. Set `forceShow: false` to `forceShow: true`. 

Also try to install the plugin locally through my repo here [https://github.com/seang96/phonegap-plugin-push](https://github.com/seang96/phonegap-plugin-push) it fixes the issue I was having where it would restart the application in the foreground.

**Comment by edmondchui** [comment]
After more testing, I found out that the notification is received on Android even when the app has been idle in the background for over 10 min. The false alarm was caused by the Android OS that doesn't send the server call response to the app until the app goes to foreground again. That is a separate issue so I'm closing this issue now.
