### ISSUE TITLE
requesting registration id null

### ISSUE THREAD

**Issue by eros2187** [phonegap/phonegap-plugin-push#2564]
**I'm using an example I plan:**

`
var app = {
    // Application Constructor
    initialize: function() {
        this.bindEvents();
    },
    // Bind Event Listeners
    //
    // Bind any events that are required on startup. Common events are:
    // 'load', 'deviceready', 'offline', and 'online'.
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    // deviceready Event Handler
    //
    // The scope of 'this' is the event. In order to call the 'receivedEvent'
    // function, we must explicitly call 'app.receivedEvent(...);'
    onDeviceReady: function() {
        console.log('Received Device Ready Event');
        console.log('calling setup push');
        app.setupPush();
    },
    setupPush: function() {
        console.log('calling push init');
        var push = PushNotification.init({
            "android": {
                "senderID": "XXXXXXXX"
            },
            "browser": {},
            "ios": {
                "sound": true,
                "vibration": true,
                "badge": true
            },
            "windows": {}
        });
        console.log('after init');

        push.on('registration', function(data) {
            console.log('registration event: ' + data.registrationId);

            var oldRegId = localStorage.getItem('registrationId');
            if (oldRegId !== data.registrationId) {
                // Save new registration ID
                localStorage.setItem('registrationId', data.registrationId);
                // Post registrationId to your app server as the value has changed
            }

            var parentElement = document.getElementById('registration');
            var listeningElement = parentElement.querySelector('.waiting');
            var receivedElement = parentElement.querySelector('.received');

            listeningElement.setAttribute('style', 'display:none;');
            receivedElement.setAttribute('style', 'display:block;');
        });

        push.on('error', function(e) {
            console.log("push error = " + e.message);
        });

        push.on('notification', function(data) {
            console.log('notification event');
            navigator.notification.alert(
                data.message,         // message
                null,                 // callback
                data.title,           // title
                'Ok'                  // buttonName
            );
       });
    }
};
`
when I start app I can not receive in tokens
**but only with a phongap emulator receive tokens!!**
### **[How can I solve?]([url](url))**

**Comment by eros2187** [comment]
I'm sorry I can know why you close the posts? Is it possible to have an answer that is closed? !!

**Comment by eros2187** [comment]
I'm sorry I can know why you close the posts? Is it possible to have an answer that is closed? !!

**Comment by eros2187** [comment]
@jcesarmobile  I'm sorry I can know why you close the posts? Is it possible to have an answer that is closed? !!

**Comment by jcesarmobile** [comment]
Yeah, @macdonst told you in the first one and you keep ignoring him, so we keep closing

> Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.
> 
> I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.
> 
> https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
