### ISSUE TITLE
Phonegap + plugin push + FCM

### ISSUE THREAD

**Issue by fasma89** [phonegap/phonegap-plugin-push#2568]
Hello . I have a question. I've succesfully installed the phonegap-plugin-push to my android application. I receive the messages that im sending from the FCM page , but i want the clients of my app to receive notifications, when for example, there is a new lesson for them, as my application is created for.So how can i achieve that ? I have the javascript code which through AJAX asks my php file if there is a new lesson from my database , but how can i implement this into this plugin??

**Comment by macdonst** [comment]
@fasma89 that's out of scope of this plugin. It's up to you to implement the server side. You need to execute your php code to talk to FCM to send the notification which this plugin will handle.
