### ISSUE TITLE
Upgrade CGM to FCM

### ISSUE THREAD

**Issue by eleva** [phonegap/phonegap-plugin-push#2580]
#### Cordova CLI version and cordova platform version

    Ionic Framework Version                   1.3.5
    Ionic CLI Version                                1.7.16
    ios-deploy version                             1.9.2 
    cordova --version                                   6.2.0
    cordova platform version android                  5.1.1
    cordova platform version ios                  4.1.1

#### Plugin version

    cordova plugin version            2.1.0

#### Problem

Hi guys,

I need some clarification about the FCM integration on the plugin.

I followed the documentation to upgrade the plugin to the newest version (2.1.0), but checking on the code I notice that the new implementation still calls the old instances used by GCM:

ex:

public class PushInstanceIDListenerService extends InstanceIDListenerService implements PushConstants {
    public static final String LOG_TAG = "PushPlugin_PushInstanceIDListenerService";

    @Override
    public void onTokenRefresh() {
        SharedPreferences sharedPref = 
        getApplicationContext().getSharedPreferences(COM_ADOBE_PHONEGAP_PUSH, 
        Context.MODE_PRIVATE);
        String senderID = sharedPref.getString(SENDER_ID, "");
        if (!"".equals(senderID)) {
            Intent intent = new Intent(this, RegistrationIntentService.class);
                startService(intent);
        }
    }
}

According to the [migration guide](https://developers.google.com/cloud-messaging/android/android-migrate-iid-service) by Google, this call should be changed to (or something similar):

public class MyInstanceIDListenerService (PushInstanceIDListenerService) extends FirebaseInstanceIdService {

  /**
   * Called if InstanceID token is updated. This may occur if the security of
   * the previous token had been compromised. Note that this is also called
   * when the InstanceID token is initially generated, so this is where
   * you retrieve the token.
   */
  // [START refresh_token]
  @Override
  public void onTokenRefresh() {
      // Get updated InstanceID token.
      String refreshedToken = FirebaseInstanceId.getInstance().getToken();
      Log.d(TAG, "Refreshed token: " + refreshedToken);
      // TODO: Implement this method to send any registration to your app's servers.
      sendRegistrationToServer(refreshedToken);
  }

}

Which makes sense considering that this last call actually refers to the Firebase service. 

There are other instances that need change to be in line with the new implementation for FCM. 

I wonder if we need to do this changes on our app before GCM gets deprecated or it's already been implemented on the new version of the plugin or it'll be implemented on a future release? I'm kind of confused about it, and worried that our app won't be able to handle notifications after GCM gets deprecated (As of April 10, 2018, Google has deprecated GCM. The GCM server and client APIs are deprecated and will be removed as soon as April 11, 2019. Migrate GCM apps to Firebase Cloud Messaging (FCM), which inherits the reliable and scalable GCM infrastructure, plus many new features. See the migration guide to learn more).

Please let me know if there is something else I need to do on my app to handle notifications through FCM or the plugin will be able to handle them after GCM get deprecated. 

Thanks

**Comment by jcesarmobile** [comment]
You are not using latest version of the code, latest version looks like what you have mentioned
https://github.com/phonegap/phonegap-plugin-push/blob/master/src/android/com/adobe/phonegap/push/PushInstanceIDListenerService.java

**Comment by eleva** [comment]
You are right,

for some reason the command kept downloading the version 2.1.0

Thanks
