### ISSUE TITLE
Unable to load PlatformApi from platform

### ISSUE THREAD

**Issue by jpike88** [phonegap/phonegap-plugin-push#2582]
I get this error on a fresh ```cordova prepare ios``` command.

```
$(npm bin)/cordova prepare ios
Discovered platform "ios@^4.5.5" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-ios@^4.5.5
Adding phonegap-plugin-push project...
Unable to load PlatformApi from platform. Error: Cannot find module '/Users/joshua/Projects/plantguard/client/cordova/node_modules/phonegap-plugin-push'
Error: Unhandled error. (The platform "phonegap-plugin-push" does not appear to be a valid cordova platform. It is missing API.js. phonegap-plugin-push not supported.)
No platforms added to this project. Please use `cordova platform add <platform>`.
```

**Comment by jpike88** [comment]
Using ```cordova-ios@4.5.5```, ```cordova@8.1.1```

If I do the command again, it seems to go ahead.

This issue does not occur with other plugins.

**Comment by jpike88** [comment]
Nope, it's listed as a plugin in my config.xml

**Comment by jcesarmobile** [comment]
Can you provide your config.xml and package.json? 
Also try updating cordova to 8.1.2 that was just released

**Comment by jpike88** [comment]
I found the culprit.

Intercom actually forked this repo a while ago, and have failed to keep it up to date. Why they'd fork it like that is beyond me, the proper approach would have been to update this repo with a couple of simple hooks that would have allowed them to chat to it. Sorry to bother you

**Comment by jpike88** [comment]
So my next step is figuring out a way forward for bringing intercom's fork back into the main repo.

https://github.com/intercom/phonegap-plugin-push

Those two commits look contained to the android code, and look like they could be easily solved by a version of phonegap-plugin-push that broadcasts data to the intercom activity or some sort of subscription handler (I'm not that familiar with android). Your thoughts?

**Comment by macdonst** [comment]
@jpike88 I can't see adding vendor specific code to the plugin. Intercom would be better of listening to the `notification` and `registration` events and calling their own plugin.

**Comment by jpike88** [comment]
That’s what I meant. I was asking specifically if what they’re trying is already supported by this library. Can what they’re doing specifically be done with the existing events? Could you take a look at the commit they made?

**Comment by jpike88** [comment]
@macdonst can you please do me a favour, and unlock this issue?

https://github.com/phonegap/phonegap-plugin-push/issues/1640

This issue is where the intercom guys decided to just fork it off. I'd like to figure out a way to properly resolve it this side.

What would be the proper way to do this? I guess there are two options from my little knowledge:

1. Expose a way to register a handler
2. Broadcast an event with the push notification's data
