### ISSUE TITLE
ios 12 co xcode 10 does not work

### ISSUE THREAD

**Issue by rodacapera** [phonegap/phonegap-plugin-push#2586]
update to ios 12 and xcode 9 I demanded to update to xxode 10 now when I compile everything seems to be fine but the notifications never arrive and I do not have any error message I have tried with all versions of the phonegap-plugin-push also with cordova 7.1.0 and 8 do not know what to do someone please help me

**Comment by macdonst** [comment]
@rodacapera cordova-ios does not currently support Xcode 10. We are going to have to wait until the below ticket is fixed before the push plugin can support it.

https://github.com/apache/cordova-ios/issues/407

**Comment by oscarabilleira** [comment]
Same problem here... build in xcode “legacy mode” or “modern mode” no error shown, the device is registered but no notifcation is recieved.

**Comment by gregor-srdic** [comment]
same problem :S

**Comment by gregor-srdic** [comment]
seems like  setting the **FirebaseAppDelegateProxyEnabled** value to **YES** in info.plist might help
