### ISSUE TITLE
Forcing display of Push Notification when App is open

### ISSUE THREAD

**Issue by rikkuporta** [phonegap/phonegap-plugin-push#2589]
So Push works great, but thats jsut a small question because I cant seem to figure it out:
How do I show a Push Notification in the Drawer when the App is open? DO I have to use something like local-push-notification on android?
Notifcations are there when the ap is closed/backgrounded tho :)

**Comment by fredgalvao** [comment]
See the `forceShow` option [on the docs](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#android).
