### ISSUE TITLE
Instance ID as Parameter

### ISSUE THREAD

**Issue by labteco** [phonegap/phonegap-plugin-push#259]
hey,
after you updated this plugin the registration ID schema has changed. 

Before:
APA91bg......
Now:
coX-XX **:** APA91bg....

every thing works fine, but could you explain why this is happend?
could be the first line the [Instance ID](https://developers.google.com/instance-id)? 

when this is only the token of the [Instance ID](https://developers.google.com/instance-id), is it possible to get this Instance ID as callback parameter? It would be really nice, if it where possible to store this ID on the server side.

Thanks a lot!

**Comment by macdonst** [comment]
@labteco I don't actually understand your question. Can you provide more information?

**Comment by macdonst** [comment]
Closing, no input for almost a month.
