### ISSUE TITLE
Error From App Store App

### ISSUE THREAD

**Issue by KimberleeDArmstrong** [phonegap/phonegap-plugin-push#2590]
#### Cordova CLI version and cordova platform version
C02VX1GWG8WN:SmartCE ka87029$ cordova -version
8.1.1 (cordova-lib@8.1.0)
C02VX1GWG8WN:SmartCE ka87029$ cordova platform 
Installed platforms:
  ios 4.5.5
Available platforms: 
  android ~7.1.1
  browser ~5.0.1
  osx ~4.0.1
  windows ~6.0.0

   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 8.1.1 → 8.1.2    │
   │   Run npm i -g cordova to update    │
   │                                     │
   ╰─────────────────────────────────────╯

#### Plugin version

   C02VX1GWG8WN:SmartCE ka87029$ cordova plugin ls
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-googlemaps 2.3.11 "cordova-plugin-googlemaps"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-whitelist 1.3.3 "Whitelist"
phonegap-plugin-contentsync 1.3.1 "content-sync"
phonegap-plugin-push 1.8.1 "PushPlugin"

#### Sample Code that illustrates the problem

```
function initializePushes() {	
	var origDeviceToken=localStorage.devicetoken;
	push = PushNotification.init({
		"android": {
			"senderID": params.prmCustAppGoogleSenderId
		},
		"ios": {"alert": "true", "badge": "true", "sound": "true"}, 
		"windows": {} 
	});
	
	push.setApplicationIconBadgeNumber(function(){console.log("clear badge");}, function(){console.log("failed to clear badge");},0);
	
	push.on('registration', function(data) {
		alert('Registration = '+JSON.stringify(data));
		console.log("registration event");
		console.log(JSON.stringify(data));
		if (localStorage.getItem('devicetoken') == null) {
			freshDownload=true;
		}
		console.log("*****localDeviceToken:"+localStorage.devicetoken + "   *****IncomingDeviceToken: "+data.registrationId);
		localStorage.setItem('devicetoken',data.registrationId);
	});

	push.on('notification', function(data) {
		console.log("notification event");
		push.setApplicationIconBadgeNumber(function(){console.log("clear badge");}, function(){console.log("failed to clear badge");},0);
		console.log(JSON.stringify(data));	
		$('#connectionmessage').css({'top':(parseInt(($(window).height())/2)-50)+'px','left':(parseInt(($(window).width())/2)-300)+'px',width:'600px'});
		$('#connectionmessage').html(data.message);
		$('#connectionmessage').show();
		setTimeout(function() { $('#connectionmessage').fadeOut('slow'); }, 4000);
		$.mobile.changePage( "#notifications_page", { role: "page" } );
		//push.setApplicationIconBadgeNumber(successHandler, errorHandler, 1);

	});

	push.on('error', function(e) {
	alert("Error = "+JSON.stringify(e));
	});        

}
```
![image1 3](https://user-images.githubusercontent.com/9216004/47177962-7a86e180-d2df-11e8-87db-70d1cad20d9d.png)

**Comment by macdonst** [comment]
@KimberleeDArmstrong if you open that file and look at line 57, column 54 what do you see?

**Comment by KimberleeDArmstrong** [comment]
I updated the plugin to 1.9.4 and the issue is no longer happening.  Unfortunately I don't have the same push.js so I can't see whats on that line.  I will close this issue.
