### ISSUE TITLE
phonegap-plugin-push + cordova-plugin-googleplus = cordova-plugin-googleplus not working on android

### ISSUE THREAD

**Issue by Loboboboboboo** [phonegap/phonegap-plugin-push#2591]
### Expected Behaviour

When clicking to login with Google a dialog opens to login.

### Actual Behaviour

When clicking to login with Google no dialog opens to login.

### Reproduce Scenario (including but not limited to)

Using phonegap build, and these plugs in my config.xml:

cordova-plugin-googleplus
cordova-android-firebase-gradle-release
phonegap-plugin-push

If I remove phonegap-plugin-push cordova-plugin-googleplus works fine.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 5.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

All

#### Cordova CLI version and cordova platform version

    cordova --version  6.0.0
    cordova platform version android  4.1.1

#### Plugin version

    phonegap-plugin-push 2.0.0

**Comment by CoverID** [comment]
try using FCM_VERSION that compatible with cordova-plugin-googleplus plugin when installing phonegap-plugin-push
my plugin version:
```
cordova-plugin-googleplus@5.3.1
phonegap-plugin-push@2.2.3

when installing push plugin:
cordova plugin add phonegap-plugin-push --variable FCM_VERSION=11.8.0
```
the FCM version installed depends on your googleplus version

**Comment by Loboboboboboo** [comment]
Thanks! This worked!

**Comment by Loboboboboboo** [comment]
Weirdly phonegap-plugin-push@2.2.3 does not return the registrationId now:

`     app.push.on('registration', function(data) {
        });`

Reverting back to 2.0.0 does work, but the problem above remains - any ideas why 2.2.3 wouldn't be working? 

Thanks!
