### ISSUE TITLE
Cordova IOS 4.5.5 and Cordova CLI 8.0.0 FCM send response is "NotRegistered"

### ISSUE THREAD

**Issue by bugrakolcak** [phonegap/phonegap-plugin-push#2594]
### Actual Behaviour
The ios app gets registrationId successfuly and registration type is FCM.

But when i try to send push notifications via https://fcm.googleapis.com/fcm/send the responses are  "InvalidRegistration" for first time and then always "NotRegistered".

Works fine on android.

![xcodepluginresponse](https://user-images.githubusercontent.com/13950347/47297217-281a2d80-d61d-11e8-8971-a7d3550ed60e.PNG)

### Reproduce Scenario
First i added plugin.
Then created FCM project and added app informations.
After that Created auth key from developer.apple.
Uploaded key to FCM.
Downloaded google-services.json and GoogleService-Info.plist file to root of my app.
Added

![configlines](https://user-images.githubusercontent.com/13950347/47297720-9d3a3280-d61e-11e8-8d98-a1e9de77e774.PNG)

lines to "config.xml".
After build added "pod 'Firebase/Core'" line to podFile.
Then installed pods via "pod install" from terminal.
Installed app by XCode from opening "myApp.xcworkspace" file.
And run.

#### Cordova CLI version

    cordova CLI                                    # 8.0.0

#### Sample Push Data Payload
![postmanresponse](https://user-images.githubusercontent.com/13950347/47296634-8e05b580-d61b-11e8-8902-1d62bd763ef4.PNG)

Also tried to create new app from scratch and responses are same as above.

Kind of stuck and don't know what to do.

Thanks.

**Comment by malwatte** [comment]
This happened to me as well. I updated macOS to mojave and xcode to 10. Luckily I kept a copy of xcode 9 and I am using it for the development at the moment. Not sure what the issue is though.

**Comment by malwatte** [comment]
I think similar to https://github.com/phonegap/phonegap-plugin-push/issues/2518
See the comments

**Comment by bugrakolcak** [comment]
> I think similar to #2518
> See the comments

Sorry for the late response. 
I tried to change build system to Legacy Build System from xcode File>Workspace settings.
It works fine now thank you for your answer.
Kind a saved me.:)

Have nice day.
