### ISSUE TITLE
Is there any way of using multiple Google-services.json file

### ISSUE THREAD

**Issue by Darshan-Chauhan** [phonegap/phonegap-plugin-push#2597]
Hi,

I've a project in which I need to add 2 `google-services.json` files.
One for debug and one for release.

I've seen following firebase documentation about configuring multiple projects.
- [Firebse supporting different environments](https://firebase.google.com/docs/configure/)

I wanted to know is there any way to achieve that using this plugin?

Thanks

**Comment by jcesarmobile** [comment]
Closing as it's out of the scope of the plugin.

You can have a cordova hook or npm script that copies the right one based on the build type.

**Comment by Darshan-Chauhan** [comment]
Thanks @jcesarmobile , I'll add a hook. :)
