### ISSUE TITLE
how to unregister?

### ISSUE THREAD

**Issue by FaisalAriyanto** [phonegap/phonegap-plugin-push#260]
var push = PushNotification.init({"android": { "senderID": "1033490905871" },"ios": { "alert": "true", "badge": "true", "sound": "true" }, "windows": {}});

push.unregister(function() {
                            alert("success");
                      }, 
                       function() {
                             alert("error");
                       });

why im still get push in background? pliss help me :(

**Comment by macdonst** [comment]
@FaisalAriyanto Did you remove your registration ID from the server that sends the push? It takes a bit before GCM/APNS invalidate the token.

**Comment by adyz** [comment]
I have a question too: What does the unregister function really do? 
If I don't change my server setting, on unregister, should I:
-  still get the notifications, and on re register I will get a new registration ID
-  don't receive the notification and on reregister the notifications will be allowed and I get the same registration ID
- both above

Any thoughts on this? I am confused here.


Thanks,
Adrian

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
