### ISSUE TITLE
Gradle build suddenly failing after last week

### ISSUE THREAD

**Issue by lokiribeiro** [phonegap/phonegap-plugin-push#2601]
### Expected Behaviour
Build should successfully finish
### Actual Behaviour
Now encountering build error all of a sudden without changing anything in the android platform when I build.

It now shows:
 While building Cordova app for platform Android:
   Error: cmd: Command failed with exit code 1 Error output:
   FAILURE: Build failed with an exception.

   * Where:
   Script
   'C:\wamp\ympapp\.meteor\local\cordova-build\platforms\android\phonegap-plugin-push\l51m1ewcn24d-push.gradle'
   line: 38

   * What went wrong:
   A problem occurred evaluating root project 'android'.
   > Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"

   * Try:
   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
   output.

   * Get more help at https://help.gradle.org

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android

**Comment by jcesarmobile** [comment]
This plugin doesn’t use the +, so it’s caused by another one or you are using an old version
