### ISSUE TITLE
Delay in 5mins for push notification on Galaxy S8 when the device is sleep

### ISSUE THREAD

**Issue by phamminhvu** [phonegap/phonegap-plugin-push#2603]
### Expected Behaviour
No delay for receiving push notification
### Actual Behaviour
Delay in 5mins before receiving the push notificaition
### Reproduce Scenario (including but not limited to)
1. move the app to background
2. turn off screen ( or close the cover front)
3. waiting in 5-10mins
4. Send a push notification
5. Waiting in 5mins the push notification will be arrived
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8 (API 26)

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
SamSung Galaxy S8
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
8.0.0
    cordova platform version android                     # e.g. 4.1.1
6.3.0
#### Plugin version
2.1.0
    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by jcesarmobile** [comment]
This is not a problem on the plugins. Google doesn't guarantee that the push will arrive, and in a lot of cases it might take time to get the push on the device as when the phone goes to background only the OS can wake it up to check the push.

**Comment by phamminhvu** [comment]
@hi @jcesarmobile 
Could we make a code to wake up by using code?
PowerManager pm = (PowerManager)context.getSystemService(Context.POWER_SERVICE);
    boolean isScreenOn = pm.isScreenOn();
    Log.e("screen on.................................", ""+isScreenOn);
    if(isScreenOn==false)
    {
        WakeLock wl = pm.newWakeLock(PowerManager.FULL_WAKE_LOCK |PowerManager.ACQUIRE_CAUSES_WAKEUP |PowerManager.ON_AFTER_RELEASE,"MyLock");
        wl.acquire(10000);
        WakeLock wl_cpu = pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"MyCpuLock");

        wl_cpu.acquire(10000);
    }

Thank you for your response!
