### ISSUE TITLE
Version 1.8.4 no longer gets device id  ios

### ISSUE THREAD

**Issue by pke** [phonegap/phonegap-plugin-push#2606]
### Expected Behaviour

Recompiling a working app Version that used to work with 1.8.4 results in the app no longer getting a device token. That's with the newest xcode that has to be used for app store releases. 

Are there any incompatibilities known with the constellation 1.8.4, cordova 6 and newest xcode?

**Comment by macdonst** [comment]
@pke yeah, the latest Xcode is causing problems with cordova apps. You need to watch this thread:

https://github.com/apache/cordova-ios/issues/407
