### ISSUE TITLE
Data and Notification Payload together

### ISSUE THREAD

**Issue by gmoraiz** [phonegap/phonegap-plugin-push#2609]
SummaryText and style works only in "data" payload?

I would like a single payload for ios and android, but iOS doens't understand payload data.

I tried targeting them with the "apns" for ios and "data" for android, but it did not work

**Comment by macdonst** [comment]
@gmoraiz I can't fix that issue. Please read https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads for the background.
