### ISSUE TITLE
Run callback when clicking of notification body

### ISSUE THREAD

**Issue by Papipo** [phonegap/phonegap-plugin-push#261]
It would be nice to be able to call a function when the notification body is clicked.

I have this app with a tabbed ui, and each tab holds different media types (pics, videos, blog posts...), thus when the user gets a "new video" notification, I would like the app to just display the video instead of opening the app.

**Comment by macdonst** [comment]
@Papipo when you click on a notification in the shader the app is started and your on "notification" event handler is called. Then you can look at the data in your push and just play the video. Does this not accomplish the task you want?

**Comment by Papipo** [comment]
Sorry, I thought that this callback was fired when the device received the notification. Now I see that if the app is already open, the callback is called, and if the app is closed, it works as you said.

Thanks and sorry for bothering.
