### ISSUE TITLE
Fix ios push notifications via Firebase

### ISSUE THREAD

**Issue by marticols** [phonegap/phonegap-plugin-push#2610]
I was trying to use phonegap-plugin-push@2. 1.2 for been able to send push notfications with IOS via FCM. When I have tried to build it with the PhoneGap Build, it throws an error that coudn't be found.

For fixing the problem I have used: 
```
<preference name="phonegap-version" value="cli-8.0.0" />
<plugin name="phonegap-plugin-push" spec="~2.1.2">
        <variable name="FCM_VERSION" value="11.0.1" />
</plugin>
<engine name="android" spec="~7.0.0" />
<engine name="ios" spec="~4.0.0" />
```
Then, PhoneGap Build doesn't get the GoogleService-Info. plist file for been able to get the FCM token:
For fixing this:
`<resource-file src="res/GoogleService-Info.plist" />`

An then place the file at www/res/ directory.

**Comment by macdonst** [comment]
@marticols the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
