### ISSUE TITLE
How to Change Android Sender Name

### ISSUE THREAD

**Issue by ehorodyski** [phonegap/phonegap-plugin-push#2618]
### Expected Behaviour

To have my app's name show up in Android Settings/notification tab when long-pressing a notification (or being asked if I want to dismiss them in the future).

### Actual Behaviour

The name `PhoneGap PushPlugin` is shown.

![screenshot_20181107-081838](https://user-images.githubusercontent.com/6395078/48133837-12844500-e266-11e8-8ae2-5a774f9b2ebd.png)

**Comment by macdonst** [comment]
https://cordova.apache.org/docs/en/latest/config_ref/#name

**Comment by ehorodyski** [comment]
It's not taking the app's configured name...I am running **2.1.3**, could that be it?
