### ISSUE TITLE
SIzes for Notification Icons on Android

### ISSUE THREAD

**Issue by mluria** [phonegap/phonegap-plugin-push#262]
I understand from the documentation that these need to be in the drawable directory, but it's unclear to me what the size needs to be.

In http://iconhandbook.co.uk/reference/chart/android/

I see the following sizes, but I don't know if they are correct, and I don't understand what 22 x 22 and 24 x 24 means.
Notification icons

I created some icons using: 
https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_stat_example

but they look pretty bad, and are very small, though they sort of work. though the sizes are 24x38, 32x50, etc.

22 × 22 area in 24 × 24 (mdpi)
33 × 33 area in 36 × 36 (hdpi)
44 × 44 area in 48 × 48 (xhdpi)
66 × 66 area in 72 × 72 (xxhdpi)
88 × 88 area in 96 × 96 (xxxhdpi)
.png    These are used to represent application notifications in the status bar. They should be flat (no gradients), white and face-on perspective

Also, I haven't gotten anything to work when push from the server in terms of images, again, maybe again because I don't understand the sizes issues, though I'm not sure how that would work in the push message, since it would be the same size on all sizes of android.

I tried both an image in the 'www/image/mynotify.png'  and a jpg via 'http', but neither seem to work.  In both cases, the images I was able to get before, do not appear, when these images are sent (using node-gcm), so I know it's doing something.

Can someone tell me what I am doing wrong?

![ic_stat_image_tag_faces](https://cloud.githubusercontent.com/assets/293190/10731497/67771ed8-7bfe-11e5-9c05-9e5581c22d46.png)

**Comment by mluria** [comment]
I guess this is not really a bug report, but perhpas the documentation could be improved, for people like me, who have limited Android experience.

**Comment by macdonst** [comment]
@mluria are you trying to set the small image or large image? It would help if I could see what you are sending from node-gcm code. Also, if you have the image available via http can you give me the URL so I can test?

**Comment by mluria** [comment]
Initially, I'm just trying to set the small icon with the phonegap-plugin-push, 
using:
    var push = PushNotification.init({
        ios: {alert: true}
      , android: {
            senderID: "259xxxxxxx",
            iconColor: "blue",
            icon: 'ic_stat_image_tag_faces'
        }
    });

on the node-gcn side, I called:

var gcmSender = new gcm.Sender('AI.........................');

function sendNotificationAndroid(token, messageText) {
    var registrationIds = [token];
    var data = {
        title: 'New Message',
        message: messageText,
        icon: 'http://pbs.twimg.com/profile_images/3673913008/1f3ddd9b5806763ec5b8c83a78386397_normal.jpeg'
    };
    var message = new gcm.Message({
        data: data
    });
    gcmSender.send(message, registrationIds, function (err, result) {
        var text = ' Token: ' + token + ' Message: ' + messageText;
        if (err) {
            console.log('Error sending to Android: ' + err + text);
        }
        else {
            console.log("Sent Android Message" + text);
        }
    });
}

**Comment by macdonst** [comment]
@mluria so, for the regular icon you specify during the init method please make sure it that `ic_stat_image_tag_faces` is in your res\drawable folder of your Android project.

When you send an image along as as part of your notification payload you use the `image` property, not `icon`. See the "Large Icon, remotely loaded" section of https://github.com/phonegap/phonegap-plugin-push#images

Please close this issue if the above comments resolve your problem.

**Comment by mluria** [comment]
Thanks, you were right about using image instead of icon.
It does say icon in the documentation in:
https://github.com/ToothlessGear/node-gcm

I still don't understand the problems at the beginning of my post referring to the sizes of the android notification images. 
Also, I see that some applications have very large images, how does that work?

**Comment by macdonst** [comment]
@mluria can you take a screen shot so I can see what you are running into?

**Comment by mluria** [comment]
sure.  But first what are the standard sizes for the notification icons?

**Comment by mluria** [comment]
OK, So I tried a few more tests.

I created some icons as above.  

notify is about 4K 64x100 png.  On a nexus 4 is should have been coming from xhdpi (according to http://blog.blundell-apps.com/list-of-android-devices-with-pixel-density-buckets/), but I tried various sizes, and I put them in all the directories simultaneously, drawable-hdpi,drawable-xhdpi, and it didn't make any difference how big the image was it always came out small.
via the image object in the push notification, I tried with 3 options, one with none, one with www/img/balloon.png, and one with a image from twitter.  The screenshots are also included.

How do I make the image bigger?

![balloon](https://cloud.githubusercontent.com/assets/293190/10759525/682a66d8-7cc0-11e5-8063-4d582c055b2f.png)
![notify](https://cloud.githubusercontent.com/assets/293190/10759539/700df3ce-7cc0-11e5-90b0-221d3350da86.png)
![ss-httpimage](https://cloud.githubusercontent.com/assets/293190/10760008/2daf6898-7cc3-11e5-9c9d-e9bfd4da60cc.png)
![ss-imagefromapp](https://cloud.githubusercontent.com/assets/293190/10760009/2db24cc0-7cc3-11e5-9dd0-35efcd5f0f70.png)
![ss-smaller](https://cloud.githubusercontent.com/assets/293190/10760006/2daf0ea2-7cc3-11e5-985c-0d6c5aa96fe4.png)
![ss-wwwimage](https://cloud.githubusercontent.com/assets/293190/10760007/2daf1d02-7cc3-11e5-9061-274f027f3e6d.png)

**Comment by mluria** [comment]
Tried it with version 1.0.4, with the same results.

**Comment by fredgalvao** [comment]
@mluria Did you mean **1.4.0**?

**Comment by mluria** [comment]
Yes, sorry.  1.4.0

I didn't mean to minimize the achievement here, it seems like a big release, but it didn't solve my problem.

**Comment by fredgalvao** [comment]
No need to be sorry. The thing is, this release did not change anything related to icon handling, so it's expected that nothing changes. As for the icons, the general guidelines are located [here](https://www.google.com/design/spec/style/icons.html) for android, and you should follow that (if you're not doing it already :wink:).

As an example, if you want to try and mimic the frame, [this is the icon I use on my application](https://cloud.githubusercontent.com/assets/616464/10770173/00acb586-7cd1-11e5-803a-a3f8682a474d.png) (it's a transparent image with white content, it might look empty if you don't have a see-through grid enabled.

**Comment by macdonst** [comment]
@mluria I actually don't see the problem here. Your screen shots look good with the image at the correct size. Check out Android's docs on notifications.

http://developer.android.com/design/patterns/notifications.html

**Comment by mluria** [comment]
sorry, I think the notification looks weird,  I can't figure out how to make the icon within the shaded area bigger.  I've scoured though the documentation, but whatever size I choose, the icon is still really small.  Is there documentation somewhere about the size of the push notification icon?

![screen shot 2015-11-02 at 3 30 56 pm](https://cloud.githubusercontent.com/assets/293190/10882849/c3867156-8176-11e5-94d2-cb64ea5903e6.png)

**Comment by bau720123** [comment]
hi @mluria 
maybe you can use png 96X96
try it

**Comment by nkeeslin** [comment]
I'm having the same issue with the small image inside a larger shaded area.  I can't figure out how to change it anywhere.  I've tried changing the size of the image I use and it hasn't changed anything

**Comment by GOURAV-MORE** [comment]
set android-targetSdkVersion less than 21..

In your config.xml:

<platform name="android">
   ...
   <preference name="android-targetSdkVersion" value="19"/>
</platform>

**Comment by GOURAV-MORE** [comment]
set the targetSdkVersion less than 21

In your config.xml:
<platform name="android">
   <preference name="android-targetSdkVersion" value="19"/>
</platform>
