### ISSUE TITLE
Push notification not received iOS

### ISSUE THREAD

**Issue by PioMarioJonathan** [phonegap/phonegap-plugin-push#2620]
### Expected Behaviour
I expect iOS device (iPhone) shows me push notifications with default sound alert.

### Actual Behaviour
iOS device doesn't show push notifications. The same functionality works fine on Android.

### Reproduce Scenario (including but not limited to)
I installed phonegap-plugin-push into my Ionic project app that works fine on Android but it seems to not do the same on iOS.

I configured Firebase Cloud Messaging (FCM) to send push notifications to clients app and I've already set all settings for Apple Dev, including:

- Create and enable App ID for push notifications on developer.apple.com;
- Create and upload SSL certificates for authentication on developer.apple.com;
- Generate and download APNs Key from developer.apple.com;
- Added my iPhone onto developer devices on developer.apple.com;
- Download and install provisioning profile on my Mac;
- Create and enable iOS project on console.firebase.google.com uploading APNs Key and certificates;
- Download and install GoogleServices-Info.plist for the above settings and put it into root folder of Ionic project.

I can build and run application on iOS device (both with Ionic CLI and Xcode) and during the first run iPhone shows me the alert in order to grant or revoke permissions for push notifications. In device settings, my app is listed into notification system settings (with permissions: “badge, sounds, banner” enabled).

I checked if GoogleServices-Info.plist is correctly included into application and settings are loaded by device. IS_GCM_ENABLED key is set TRUE.

Everything should work at this point but none is shown onto device.

I discovered that function .on('registration') works fine even on iOS but .on('notification') function never fires. My server system sends notification payload (in fact on Android device I don't have this problem) to Firebase Server, but then everything is lost.

I assumed the problem was with payload format, I tried all solutions found on web but none worked for me.

#### Steps to Reproduce 
See above.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iPhone: 5S
with iOS: 11.2.1

#### Cordova CLI version and cordova platform version
cordova: 8.1.2
cordova-lib: 8.1.1

android platform: 7.1.1
iOS platform: 4.5.5

#### Plugin version
phnoegap-plugin-push: 2.2.3

#### Sample Push Data Payload
The latest payload version I tried:
```ts
            {
                "to": tok,
                "collapse_key": "Auxiliapp",

                "notification": {
                    "title": "My title",
                    "body": "My message",
                    "sound": "default",
                    "badge": "0"
                },

                // iOS
                "aps": {
                    "alert": "Test background push",
                    "content-available": 1
                },
                // Android
                "data": {  // you can send only notification or only data(or include both)
                    "title":    `${user.name} ${user.surname}`,
                    "message":   mess.content,
                    "soundname": "default"
                }
            }
```
I tried to send payload without notification body, but not worked too.

#### Sample Code that illustrates the problem
App - client side
```ts
platform.ready().then( _ => { 
        if (platform.is("cordova")) {
          push.hasPermission()
            .then( enabled => {
              console.log("Notifiche push: ", enabled);
            })
    
            const options: PushOptions = {
              android: {
                sound: 'true',
                vibrate: 'true'
              },
              ios: {
                  alert: 'true',
                  badge: 'true',
                  sound: 'true'
              },
              windows: {}
            };
            
            this.pushObject = this.push.init(options);
    
            this.pushObject.on('notification').subscribe( n => this.synch_delivers());

            this.pushObject.on('registration')
              .switchMap( reg => {
                console.log(`Arrivata registrazione!`, reg);
                if (this.userService.logged_in.value) return Observable.of(reg);
                else return Observable.of(reg).combineLatest(this.userService.logged_in.filter(is_logged => is_logged))
                  .map( ([reg, is_logged]) => reg)
              })
              .subscribe( registration => {
               console.log(`${log_prefix}`, registration);
               this.send_fcm_token(userService.logged_user.contact_id, registration.registrationId)
              .subscribe( c => console.log(`${log_prefix} FCM Token inviato`));  
            });

            this.pushObject.on('error').subscribe( error => {
              console.log(`Errore durante la configurazione delle notifiche push: ${JSON.stringify(error)}`);
            })
        }
      });
```
------------------

Server side
```ts
const  send_fcm_push = (message: any): Promise<any> => {

    return new Promise( (resolve, reject) => {
        console.log("Sending push message:");
        console.log(message);

        fcm.send(message, function(err: any, response: any) {
            if (err) {
                console.log("Something has gone wrong!");
                reject(err);
            } else {
                console.log("Successfully sent with response: ", response);
                resolve(response);
            }
        });

    });
};

const do_notify = tokens.map( tok =>
            send_fcm_push( {
                "to": tok,
                "collapse_key": "Auxiliapp",

                "notification": {
                    "title": "My title",
                    "body": "My message",
                    "sound": "default",
                    "badge": "0"
                },

                // notifica iOS
                "aps": {
                    "alert": "Test background push",
                    "content-available": 1
                },
                // notifica Android
                "data": {  // you can send only notification or only data(or include both)
                    "title":    `${user.name} ${user.surname}`,
                    "message":   mess.content,
                    "soundname": "default"
                }
            }).catch( error => console.log("Invio notifica push fallito: ", error))
        );

        return Promise.all(do_notify);
```

**Comment by fredgalvao** [comment]
Have you checked the docs on FCM on iOS? https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#fcm-and-additional-data

That will mention that for it to work, and I quote:
> but in order for the same notification event you would need to send your push to FCM iOS in a slight different format:
```json
{
    "registration_ids": ["my device id"],
    "notification": {
        "title": "My Title",
    	"body": "My message"
    },
    "data": {
    	"key1": "data 1",
    	"key2": "data 2"
    }
}
```
> The title and body need to be in the notification part of the payload in order for the OS to pick them up correctly. Everything else should be in the data part of the payload.

That makes it clear, hopefully, that there's no `aps` section on the payload for FCM on iOS. Also, title and body goes into the `notification` part and nowhere else.

Also make sure you read https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads to understand that, because of the fact that the only recommendation that succeeds every use-case on Android is to use a `data-only` payload, without the `notification` section.

And by reading those two sections of the docs, hopefully it'll be clear that you can't satisfy both FCM_iOS (needs data and notification sections) and FCM_Android (needs data-only) at the same time with the same payload. You'll have to send separate payloads to each platform.

If my assumptions were in any way correct, and the docs couldn't make them clear enough on their own, **please** help us improve the docs so that they reflect this sad truth.

**Comment by macdonst** [comment]
@PioMarioJonathan a lot of times this ends up being the app registering with the production push service when you are sending via the dev push service. Please make sure your certs match up on the device and on the server. 

Other than logs from Xcode reproducing the issue help.

**Comment by PioMarioJonathan** [comment]
@fredgalvao , your solution IS the REAL ONE that WORKS! I don't know how to thank you, really! :-D

Anyway, coming from Ionic reference of phonegap-plugin-push ( https://ionicframework.com/docs/native/push/ ) there's no links for best practises for a very common issue about iOS - I surfed the Web and I wasn't alone.

I suppose it could be possible to explain completely how to enable FCM notification via phonegap-plugin-push and iOS devices - a full guide that helps to setup a working notification flow.

Thank you again! :-)

**Comment by fredgalvao** [comment]
@PioMarioJonathan The thing is, we have extensivelly documented these circunstamces on the docs (as you could see by the links), but it still fails to deliver this understanding to users. I suppose we could rewrite the docs, or make a big warning on the main repo page, but I don't think that's the propper solution.

That's why we always ask users to help us improve the docs. This is the most common mistake ever, and users still seem to either not read or not understand the docs.

**Comment by tbeata** [comment]
@PioMarioJonathan Could you show me the payload you've sent?
