### ISSUE TITLE
Android app crashes on load - phonegap-plugin-push - 1.10.5

### ISSUE THREAD

**Issue by BhavikaP** [phonegap/phonegap-plugin-push#2624]
### Expected Behaviour

App loads and saves registration id in localstorage

### Actual Behaviour

App crashes on load.

If I don't specify the Sender ID in the code - then the app atleast open and throws an error no Sender ID found. 

But if i define the Sender ID as below - the App just crashes immediately on opening.

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version
```xml
	<plugin name="cordova-plugin-whitelist" source="npm" spec="~1.3.3" />
	<plugin name="cordova-plugin-device" source="npm" spec="~1.1.1" />
	<plugin name="cordova-plugin-inappbrowser" source="npm" spec="~1.3.0" />
	<plugin name="cordova-plugin-splashscreen" source="npm" spec="~3.2.1" />
	<preference name="android-build-tool" value="gradle" />
	<plugin name="phonegap-plugin-push" spec="~1.10.5">
		 <param name="SENDER_ID" value="257737864164" />
	</plugin>
	<plugin name="cordova-plugin-google-analytics" source="npm" spec="1.8.3"> 
		<param name="ios-package" value="UniversalAnalyticsPlugin" />
		<param name="android-package" value="com.danielcwilson.plugins.analytics.UniversalAnalyticsPlugin" />
	</plugin>
	
	<!-- to enable individual permissions use the following examples -->
	<preference name="permissions" value="none"/>
    <feature name="http://api.phonegap.com/1.0/network" />

	<!-- Customize your app and platform with the preference element. -->
    <preference name="phonegap-version" value="cli-6.5.0" /> 
	<preference name="orientation" value="default" />
    <preference name="target-device" value="universal" />
    <preference name="fullscreen" value="true" />
    <preference name="webviewbounce" value="true" />
    <preference name="prerendered-icon" value="true" />
    <preference name="stay-in-webview" value="false" />
    <preference name="detect-data-types" value="true" />
    <preference name="exit-on-suspend" value="false" />
    <preference name="show-splash-screen-spinner" value="true" />
    <preference name="auto-hide-splash-screen" value="true" />
	<preference name="detect-data-types" value="false" />`
```

#### Sample Code that illustrates the problem
```js
// google project id for application
var googleProjectID = "XXXXX";

var app = {
    // Application Constructor
    initialize: function() {
        this.bindEvents();
    },
    // Bind Event Listeners
    //
    // Bind any events that are required on startup. Common events are:
    // 'load', 'deviceready', 'offline', and 'online'.
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    // deviceready Event Handler
    //
    // The scope of 'this' is the event. In order to call the 'receivedEvent'
    // function, we must explicity call 'app.receivedEvent(...);'
    onDeviceReady: function() {
        app.receivedEvent('deviceready');
		try {
			//Push Notification
			push = PushNotification.init({ android: {senderID: googleProjectID}, ios: {alert: "true",badge: "true",sound: "true"}});
			push.on('registration', function(data) {
				window.localStorage.setItem("app_register_id", data.registrationId);
				alert("Device Registered = " + data.registrationId);
			});
			push.on('notification', function(data) {
				alert(data.title+" Message: " +data.message);
			});
			push.on('error', function(error) {
				alert("PushNotification error : " + error);
			});
		}
		catch(err) {
			alert("Device Ready error : " + err);
		}
    },
    // Update DOM on a Received Event
    receivedEvent: function(id) {
		try {
			//Google Analyics
			window.ga.startTrackerWithId('UA-51916723-1', 30);
			window.ga.trackView("#searchpage");
		}
		catch(err) {
			alert("receivedEvent error : " + err);
		}
    }
};
```
#### Logs taken while reproducing problem

11-13 12:47:50.589 13675 13774 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-2
11-13 12:47:50.589 13675 13774 E AndroidRuntime: Process: au.org.cancervic.trials, PID: 13675
11-13 12:47:50.589 13675 13774 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/util/zzv;
11-13 12:47:50.589 13675 13774 E AndroidRuntime: 	at com.google.android.gms.iid.zzo.<init>(Unknown Source:34)
11-13 12:47:50.589 13675 13774 E AndroidRuntime: 	at com.google.android.gms.iid.zzo.<init>(Unknown Source:2)
11-13 12:47:50.589 13675 13774 E AndroidRuntime: 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source:22)
11-13 12:47:50.589 13675 13774 E AndroidRuntime: 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source:1)
11-13 12:47:50.589 13675 13774 E AndroidRuntime: 	at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:73)
11-13 12:47:50.589 13675 13774 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
11-13 12:47:50.589 13675 13774 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
11-13 12:47:50.589 13675 13774 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
11-13 12:47:50.589 13675 13774 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.util.zzv" on path: DexPathList[[zip file "/data/app/au.org.cancervic.trials-Vmyf9nbIpm6Ie-jC5u5-6g==/base.apk"],nativeLibraryDirectories=[/data/app/au.org.cancervic.trials-Vmyf9nbIpm6Ie-jC5u5-6g==/lib/arm64, /system/lib64, /system/vendor/lib64]]
11-13 12:47:50.589 13675 13774 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
11-13 12:47:50.589 13675 13774 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
11-13 12:47:50.589 13675 13774 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-13 12:47:50.589 13675 13774 E AndroidRuntime: 	... 8 more
11-13 12:47:50.651  5264  5280 E PhoneWindow_APM : : isCalledPackage return true
11-13 12:47:50.734 13675 13675 E ViewRootImpl: sendUserActionEvent() returned.
11-13 12:47:50.800  2111  2111 E PBSessionCacheImpl: sessionId[9285817246849284] not persisted.
11-13 12:47:50.836  7131 13785 E Launcher.WallpaperUtils: check bitmap.recycle() on releaseWallpaperDrawable
11-13 12:47:51.235  5264  5282 E KernelUidCpuTimeReader: Failed to read uid_cputime: /proc/uid_cputime/show_uid_stat (No such file or directory)
11-13 12:47:51.244  5264  5282 E KernelUidCpuTimeReader: failed to remove uid from uid_cputime module
11-13 12:47:51.244  5264  5282 E KernelUidCpuTimeReader: java.io.FileNotFoundException: /proc/uid_cputime/remove_uid_range (No such file or directory)
11-13 12:47:51.244  5264  5282 E KernelUidCpuTimeReader: 	at java.io.FileOutputStream.open0(Native Method)
11-13 12:47:51.244  5264  5282 E KernelUidCpuTimeReader: 	at java.io.FileOutputStream.open(FileOutputStream.java:287)
11-13 12:47:51.244  5264  5282 E KernelUidCpuTimeReader: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
11-13 12:47:51.244  5264  5282 E KernelUidCpuTimeReader: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:110)
11-13 12:47:51.244  5264  5282 E KernelUidCpuTimeReader: 	at java.io.FileWriter.<init>(FileWriter.java:63)
11-13 12:47:51.244  5264  5282 E KernelUidCpuTimeReader: 	at com.android.internal.os.KernelUidCpuTimeReader.removeUid(KernelUidCpuTimeReader.java:139)
11-13 12:47:51.244  5264  5282 E KernelUidCpuTimeReader: 	at com.android.internal.os.BatteryStatsImpl.removeIsolatedUidLocked(BatteryStatsImpl.java:3964)
11-13 12:47:51.244  5264  5282 E KernelUidCpuTimeReader: 	at com.android.server.am.BatteryStatsService$BatteryStatsHandler.handleMessage(BatteryStatsService.java:149)
11-13 12:47:51.244  5264  5282 E KernelUidCpuTimeReader: 	at android.os.Handler.dispatchMessage(Handler.java:105)
11-13 12:47:51.244  5264  5282 E KernelUidCpuTimeReader: 	at android.os.Looper.loop(Looper.java:164)
11-13 12:47:51.244  5264  5282 E KernelUidCpuTimeReader: 	at android.os.HandlerThread.run(HandlerThread.java:65)
11-13 12:47:51.244  5264  5282 E KernelUidCpuTimeReader: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
11-13 12:47:51.944 12469 12469 E adbd    : recv: OPEN 000002bd 00000000 00f9:73 68 65 6C 6C 3A 67 65 74 70 72 6F 70 20 72 6F 2E 70 72 6F 64 75 63 74 2E 6D 6F 64 65 6C 0A 65 63 68 6F 20 3D 3D 3D 3D 3D 3D 3D 3D 20 6F 75 74 70 75 74 20 73 65 70 61 72 61 74 6F 72 20 3D 3D 3D 3D 3D 3D 3D 3D 0A 64 75 6D 70 73 79 73 20 77 69 6E 64 6F 77 20 70 6F 6C 69 63 79 0A 65 63 68 6F 20 3D 3D 3D 3D 3D 3D 3D 3D 20 6F 75 74 70 75 74 20 73 65 70 61 72 61 74 6F 72 20 3D 3D 3D 3D 3D 3D 3D 3D 0A 70 73 0A 65 63 68 6F 20 3D 3D 3D 3D 3D 3D 3D 3D 20 6F 75 74 70 75 74 20 73 65 70 61 72 61 74 6F 72 20 3D 3D 3D 3D 3D 3D 3D 3D 0A 63 61 74 20 2F 70 72 6F 63 2F 6E 65 74 2F 75 6E 69 78 0A 65 63 68 6F 20 3D 3D 3D 3D 3D 3D 3D 3D 20 6F 75 74 70 75 74 20 73 65 70 61 72 61 74 6F 72 20 3D 3D 3D 3D 3D 3D 3D 3D 0A 64 75 6D 70 73 79 73 20 75 73 65 72 0A 00 
11-13 12:47:51.944 12469 12469 E adbd    : service_to_fd: shell:getprop ro.product.model
11-13 12:47:51.945 12469 12469 E adbd    : echo ======== output separator ========
11-13 12:47:51.945 12469 12469 E adbd    : dumpsys window policy
11-13 12:47:51.945 12469 12469 E adbd    : echo ======== output separator ========
11-13 12:47:51.945 12469 12469 E adbd    : ps
11-13 12:47:51.945 12469 12469 E adbd    : echo ======== output separator ========
11-13 12:47:51.945 12469 12469 E adbd    : cat /proc/net/unix
11-13 12:47:51.945 12469 12469 E adbd    : echo ======== output separator ========
11-13 12:47:51.945 12469 12469 E adbd    : dumpsys user
11-13 12:47:51.945 12469 12469 E adbd    : 
11-13 12:47:52.166 12469 12469 E adbd    : recv: OPEN 000002be 00000000 002c:6C 6F 63 61 6C 61 62 73 74 72 61 63 74 3A 77 65 62 76 69 65 77 5F 64 65 76 74 6F 6F 6C 73 5F 72 65 6D 6F 74 65 5F 31 33 36 37 35 00 
11-13 12:47:52.166 12469 12469 E adbd    : service_to_fd: localabstract:webview_devtools_remote_13675
11-13 12:47:52.168 12469 12469 E adbd    : recv: OPEN 000002bf 00000000 002c:6C 6F 63 61 6C 61 62 73 74 72 61 63 74 3A 77 65 62 76 69 65 77 5F 64 65 76 74 6F 6F 6C 73 5F 72 65 6D 6F 74 65 5F 31 33 36 37 35 00 
11-13 12:47:52.168 12469 12469 E adbd    : service_to_fd: localabstract:webview_devtools_remote_13675
11-13 12:47:54.963 12469 12469 E adbd    : recv: OPEN 000002c1 00000000 00f9:73 68 65 6C 6C 3A 67 65 74 70 72 6F 70 20 72 6F 2E 70 72 6F 64 75 63 74 2E 6D 6F 64 65 6C 0A 65 63 68 6F 20 3D 3D 3D 3D 3D 3D 3D 3D 20 6F 75 74 70 75 74 20 73 65 70 61 72 61 74 6F 72 20 3D 3D 3D 3D 3D 3D 3D 3D 0A 64 75 6D 70 73 79 73 20 77 69 6E 64 6F 77 20 70 6F 6C 69 63 79 0A 65 63 68 6F 20 3D 3D 3D 3D 3D 3D 3D 3D 20 6F 75 74 70 75 74 20 73 65 70 61 72 61 74 6F 72 20 3D 3D 3D 3D 3D 3D 3D 3D 0A 70 73 0A 65 63 68 6F 20 3D 3D 3D 3D 3D 3D 3D 3D 20 6F 75 74 70 75 74 20 73 65 70 61 72 61 74 6F 72 20 3D 3D 3D 3D 3D 3D 3D 3D 0A 63 61 74 20 2F 70 72 6F 63 2F 6E 65 74 2F 75 6E 69 78 0A 65 63 68 6F 20 3D 3D 3D 3D 3D 3D 3D 3D 20 6F 75 74 70 75 74 20 73 65 70 61 72 61 74 6F 72 20 3D 3D 3D 3D 3D 3D 3D 3D 0A 64 75 6D 70 73 79 73 20 75 73 65 72 0A 00 
11-13 12:47:54.964 12469 12469 E adbd    : service_to_fd: shell:getprop ro.product.model
11-13 12:47:54.964 12469 12469 E adbd    : echo ======== output separator ========
11-13 12:47:54.964 12469 12469 E adbd    : dumpsys window policy
11-13 12:47:54.964 12469 12469 E adbd    : echo ======== output separator ========
11-13 12:47:54.964 12469 12469 E adbd    : ps
11-13 12:47:54.964 12469 12469 E adbd    : echo ======== output separator ========
11-13 12:47:54.964 12469 12469 E adbd    : cat /proc/net/unix
11-13 12:47:54.964 12469 12469 E adbd    : echo ======== output separator ========
11-13 12:47:54.964 12469 12469 E adbd    : dumpsys user
11-13 12:47:54.965 12469 12469 E adbd    : 
11-13 12:47:55.161 12469 12469 E adbd    : recv: OPEN 000002c2 00000000 002c:6C 6F 63 61 6C 61 62 73 74 72 61 63 74 3A 77 65 62 76 69 65 77 5F 64 65 76 74 6F 6F 6C 73 5F 72 65 6D 6F 74 65 5F 31 33 36 37 35 00 
11-13 12:47:55.161 12469 12469 E adbd    : service_to_fd: localabstract:webview_devtools_remote_13675
11-13 12:47:55.166 12469 12469 E adbd    : recv: OPEN 000002c3 00000000 002c:6C 6F 63 61 6C 61 62 73 74 72 61 63 74 3A 77 65 62 76 69 65 77 5F 64 65 76 74 6F 6F 6C 73 5F 72 65 6D 6F 74 65 5F 31 33 36 37 35 00 
11-13 12:47:55.166 12469 12469 E adbd    : service_to_fd: localabstract:webview_devtools_remote_13675
11-13 12:47:57.432  5264  6706 E memtrack: Couldn't load memtrack module
11-13 12:47:57.983 12469 12469 E adbd    : recv: OPEN 000002c5 00000000 00f9:73 68 65 6C 6C 3A 67 65 74 70 72 6F 70 20 72 6F 2E 70 72 6F 64 75 63 74 2E 6D 6F 64 65 6C 0A 65 63 68 6F 20 3D 3D 3D 3D 3D 3D 3D 3D 20 6F 75 74 70 75 74 20 73 65 70 61 72 61 74 6F 72 20 3D 3D 3D 3D 3D 3D 3D 3D 0A 64 75 6D 70 73 79 73 20 77 69 6E 64 6F 77 20 70 6F 6C 69 63 79 0A 65 63 68 6F 20 3D 3D 3D 3D 3D 3D 3D 3D 20 6F 75 74 70 75 74 20 73 65 70 61 72 61 74 6F 72 20 3D 3D 3D 3D 3D 3D 3D 3D 0A 70 73 0A 65 63 68 6F 20 3D 3D 3D 3D 3D 3D 3D 3D 20 6F 75 74 70 75 74 20 73 65 70 61 72 61 74 6F 72 20 3D 3D 3D 3D 3D 3D 3D 3D 0A 63 61 74 20 2F 70 72 6F 63 2F 6E 65 74 2F 75 6E 69 78 0A 65 63 68 6F 20 3D 3D 3D 3D 3D 3D 3D 3D 20 6F 75 74 70 75 74 20 73 65 70 61 72 61 74 6F 72 20 3D 3D 3D 3D 3D 3D 3D 3D 0A 64 75 6D 70 73 79 73 20 75 73 65 72 0A 00

**Comment by BhavikaP** [comment]
Any help resolving the above issue will be greatly appreciated. Thanks.

**Comment by jcesarmobile** [comment]
Sorry, we don’t support 1.x.x version of the plugin anymore, switch to lates 2.x.x
