### ISSUE TITLE
Cordova does not know push

### ISSUE THREAD

**Issue by samall76** [phonegap/phonegap-plugin-push#2628]
I'm testing with the delivered Phonegap sample push application. When I try to send the first push notification the error: "Cordova does not know push" appear. 

![screen](https://user-images.githubusercontent.com/45182670/48734073-aaaa0300-ec44-11e8-9c97-bd494a1c3dc3.png)
Can someone help me?

**Comment by macdonst** [comment]
@samall76 they discontinued the push service and took the push command out of the CLI.

https://blog.phonegap.com/discontinuing-the-phonegap-push-service-540251bfc98
