### ISSUE TITLE
Notifications don't work on iPad Air - iOS 11.4.1

### ISSUE THREAD

**Issue by brunojs02** [phonegap/phonegap-plugin-push#2633]
### Expected Behaviour
Notifications work on iPad after installed using Xcode.

### Actual Behaviour
On start my app by the first time, don't show ask permission for notifications, and there's nothing that I can update by settings, follow images below:

![image](https://user-images.githubusercontent.com/7714813/48950200-876fa400-ef21-11e8-9a11-0fdc0248ef6d.png)

As u can see, theres no option to allow or disallow push notifications.

### Reproduce Scenario (including but not limited to)
Allow push notifications to my app identify in apple dev account.
Create a key to export to firebase account.
Export the key to firebase account.
I terminal I run the following commands: 
ionic Cordova platform add iOS
ionic Cordova prepare iOS --prod
After I open the .xcworkspace in Xcode
Add the provision profile to keychains
Add the dev and prod certifies to keychains
Plugin the iPad to computer
Build and run

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 11.4.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPad Air

#### Cordova CLI version and cordova platform version

    cordova --version                                    8.0.0
    cordova platform version iOS                 4.5.5

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.1.3

#### Sample Push Data Payload
Im using firebase console.

#### Sample Code that illustrates the problem

this.push.hasPermission().then((res) => {

      if (res.isEnabled) { // the value of this is false
        const options: PushOptions = {
          android: {
            icon: 'notificacao',
            iconColor: '#FF9C12'
          },
          ios: {
            alert: 'true',
            badge: true,
            sound: 'true'
          }
        };

        const pushObject: PushObject = this.push.init(options);
        pushObject.on('registration').subscribe((data) => { // this is called at some point, even if you are in the condition to have permission to notify
          if (localStorage.getItem('registrationId') === null || localStorage.getItem('registrationId') !== data.registrationId) {
            localStorage.setItem('registrationId', data.registrationId);
          }
        });

        pushObject.on('notification').subscribe(() => {
          this.events.publish('updateLiberacoes');
          pushObject.clearAllNotifications();
        });

      }
    });
#### Logs taken while reproducing problem
I don't know if it is important, but in the Xcode console, I get the follow warning:
THREAD WARNING: ['PushNotification'] took '23.944824' ms. Plugin should use a background thread.

**Comment by jcesarmobile** [comment]
You are calling init only if they are enabled, but they are not enabled unless you call init
