### ISSUE TITLE
Library conflict with cordova-plugin-googlemaps

### ISSUE THREAD

**Issue by ggiordan** [phonegap/phonegap-plugin-push#2634]
### Expected Behaviour
Clean build
### Actual Behaviour
```
D:\rovermobile>cordova build   android
cordova-custom-config: Skipping auto-restore of config file backup(s)
Android Studio project detected
ANDROID_HOME=C:\Program Files (x86)\Android\android-sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_181
Reading build config file: D:\rovermobile\build.json
studio
Subproject Path: CordovaLib
Subproject Path: app
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
FAILURE: Build failed with an exception.

* Where:
        at build_6vin49prfigu5ku9ei16m3dih.run(D:\rovermobile\platforms\android\app\build.gradle:151)
Script 'D:\rovermobile\platforms\android\cordova-support-google-services\rovermobilegap-build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > All firebase libraries must be either above or below 14.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script 'D:\rovermobile\platforms\android\cordova-support-google-services\rovermobilegap-build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > All firebase libraries must be either above or below 14.0.0
```
### Reproduce Scenario (including but not limited to)
I have these plugins:
D:\rovermobile>cordova plugin list
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ios-non-exempt-encryption 1.0.0 "ITSAppUsesNonExemptEncryption false"
cordova-plugin-media 5.0.2 "Media"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-sim 1.3.3 "SIM"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-support-google-services 1.1.0 "cordova-support-google-services"
phonegap-plugin-multidex 1.0.0 "Multidex"
phonegap-plugin-push 2.2.3 "PushPlugin"

#### Steps to Reproduce 
If I remove either of the plugins  cordova-plugin-googlemaps or phonegap-plugin-push

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
D:\rovermobile>cordova platform list
Installed platforms:
  android 7.1.4
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
n/a
#### Cordova CLI version and cordova platform version
D:\rovermobile>cordova --version
8.1.2 (cordova-lib@8.1.1)

#### Plugin version
phonegap-plugin-push 2.2.3 "PushPlugin"

#### Sample Push Data Payload
n/a
#### Sample Code that illustrates the problem
n/a

**Comment by ggiordan** [comment]
I just found this:  https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1937
I see the spirited discussion, I don't understand the solution, or is there one?

**Comment by ggiordan** [comment]
ok, I got it to build, I did the following (is there a better way?)
1) edit config.xml
```xml
    <plugin name="cordova-plugin-googlemaps" spec="^2.4.6">
        <variable name="PLAY_SERVICES_VERSION" value="15.0.1" />
        <variable name="FCM_VERSION" value="15.0.1" />
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
    </plugin>
    <plugin name="phonegap-plugin-push" spec="^2.2.3">
        <variable name="ANDROID_SUPPORT_V13_VERSION" value="27.+" />
        <variable name="FCM_VERSION" value="15.0.0" />
    </plugin>
```
2) edit plugin.xml
```xml
    <preference name="ANDROID_SUPPORT_V13_VERSION" default="27.+"/>
    <preference name="FCM_VERSION" default="15.0.0"/>
    <framework src="com.android.support:support-v13:$ANDROID_SUPPORT_V13_VERSION"/>
```
3) remove android platform
4) add android platform back in
5) build works.... <phew>

So, I guess, at the core, I answered my own question, can I get this to work... short answer is "Yes", but the steps seemed a bit murky to me.
Is there a shorter path to get this to work?  Or, if I insist on using both of these plugins, do I update my internal documentation to reflect these steps?

thank you so much for your work and your patience with all my silly questions!

**Comment by jcesarmobile** [comment]
You have to make the versions match as you did, you find have to edit the plugin.xml. Buy you have to remove and re add the platform after the version changes
