### ISSUE TITLE
I want to show notification when app is foreground

### ISSUE THREAD

**Issue by chavesgu** [phonegap/phonegap-plugin-push#2636]
### Expected Behaviour
show notification when app is foreground
### Actual Behaviour
it doesn't show notification when app is foreground
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ios 12
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version ios                     # e.g. 4.5.5

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.8.1

**Comment by fredgalvao** [comment]
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#android
`android.forceShow`

Also, your issue template is 99% empty, please provide more information next time.

**Comment by fredgalvao** [comment]
You can always use https://github.com/phonegap/phonegap-plugin-local-notification to trigger a local notification while on foreground inside your `.on('notification')` handler.

**Comment by chavesgu** [comment]
> You can always use https://github.com/phonegap/phonegap-plugin-local-notification to trigger a local notification while on foreground inside your `.on('notification')` handler.

i test this way, but there is some bug in this plugin,

now   i  use Objective-C to  change plugin code   to solve this problem

thanks for your reply
