### ISSUE TITLE
Permission prompt triggered without calling init

### ISSUE THREAD

**Issue by noctivityinc** [phonegap/phonegap-plugin-push#2637]
### Expected Behaviour
The user will NOT be prompted for permissions until `init` is called using the plugin in ionic cordova

### Actual Behaviour
The user is presented with a prompt for permissions (oddly to make phone calls on Android) the moment the Push plugin is included in any class.

### Reproduce Scenario (including but not limited to)
Create an ionic 3 cordova project and include the `Push` module in any class.  Load that page and you will be prompted regardless of calling `init`

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

```
Ionic:

   ionic (Ionic CLI)  : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic 5.2.7, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.5, (and 28 other plugins)

System:

   ios-deploy : 1.9.2
   NodeJS     : v11.2.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61

Android:

   Phone: Pixel
   Android: 8.1
```

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
```
Android:

   Phone: Pixel
   Android: 8.1
```
#### Cordova CLI version and cordova platform version

```
Ionic:

   ionic (Ionic CLI)  : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1
```

#### Plugin version

`"phonegap-plugin-push": "git+https://github.com/phonegap/phonegap-plugin-push.git",`

**Comment by jcesarmobile** [comment]
Push plugin doesn't require or request any permission on Android, not sure where that is coming from, but not from the push plugin
