### ISSUE TITLE
library not found for -lGoogleToolboxForMac

### ISSUE THREAD

**Issue by karigarweb** [phonegap/phonegap-plugin-push#2638]
### Expected Behaviour
We should able to build app for Archiving and uploading to app store

### Actual Behaviour
App build completing successfully from cli & even in X-Code for simulators but fails during archiving process

### Reproduce Scenario (including but not limited to)
I did all basic troubleshooting including steps mentioned on following URL:
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#library-not-found-for--lgoogletoolboxformac

This was not an issue before we ran few updates today. Gone over #2246, #1737, #2165 & #2318 but not able to resolve this one.

Even tried manual pod install and got following results:

`Analyzing dependencies
Downloading dependencies
Using FirebaseAnalytics (4.2.0)
Using FirebaseCore (4.0.20)
Using FirebaseInstanceID (2.0.10)
Using FirebaseMessaging (2.0.8)
Using GoogleToolboxForMac (2.1.4)
Using Protobuf (3.6.1)
Using nanopb (0.3.901)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 7 total pods installed.
`

#### Steps to Reproduce 
Simply try to Archive the product on Xcode.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS Generic Device

#### Cordova CLI version and cordova platform version

    cordova --version: 8.1.2                                  
    cordova platform version ios: 4.5.5           

#### Plugin version
2.2.3

#### Logs taken while reproducing problem
`ld: warning: directory not found for option '-L/Users/USERNAME/Library/Developer/Xcode/DerivedData/APPNAME-elbgvzzgxxbctiatqxezighamhnb/Build/Intermediates.noindex/ArchiveIntermediates/The Grapplers Guide/BuildProductsPath/Release-iphoneos/GoogleToolboxForMac'
ld: warning: directory not found for option '-L/Users/USERNAME/Library/Developer/Xcode/DerivedData/APPNAME-elbgvzzgxxbctiatqxezighamhnb/Build/Intermediates.noindex/ArchiveIntermediates/APPNAME/BuildProductsPath/Release-iphoneos/Protobuf'
ld: warning: directory not found for option '-L/Users/USERNAME/Library/Developer/Xcode/DerivedData/APPNAME-elbgvzzgxxbctiatqxezighamhnb/Build/Intermediates.noindex/ArchiveIntermediates/APPNAME/BuildProductsPath/Release-iphoneos/nanopb'
ld: library not found for -lGoogleToolboxForMac
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by jcesarmobile** [comment]
This is a Cordova bug and has been answered thousands of times

**Comment by karigarweb** [comment]
Thanks for prompt reply @jcesarmobile but as I mentioned in my report that all the basic troubleshooting process was following and I looked into previous reported issues as well.

Also simply removing push plugin allows us to build and archive the app successfully. Why that might be happening?

**Comment by brunojs02** [comment]
make the process again.. and after u run 'pod install', open .xcworkspace instead .xcproject!!
