### ISSUE TITLE
Receive Notifications in Background on Windows

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-plugin-push#264]
See Issue #93 for history

Basically, when a raw notification is received and the app is in the background then the `on('notification')` event hander should be called.

**Comment by rdesimone** [comment]
Could you please give an update on this issue? As far as I understand this is needed to trigger a tab on the notification. Actually push.on('notification', function(data) does not fire when a user tabs the notification. IMO this is a must feature and needed for various scenarios. Thanks a lot!

**Comment by macdonst** [comment]
@rdesimone I'm waiting for @rakatyal to get some time to take a look.

**Comment by rdesimone** [comment]
@macdonst thanks!

**Comment by rakatyal** [comment]
@rdesimone: Unfortunately we are not working on this currently but we plan to come back to it probably in the next month.

**Comment by rdesimone** [comment]
@rakatyal For our app we managed to trigger the tap on notification by listening to the 'activated' event and reading the launch args which are included in the toast. For cold start we have actually a very ugly working hack by modifying cordova.js.

`var activationHandler = function (e) {
                var args = e.detail.arguments;
                window.localStorage.setItem("launch-args", args); // ugly hack
                var actType = e.detail.type;
                platform.activationContext = { type: actType, args: args };
                cordova.fireDocumentEvent('activated', platform.activationContext, true);
};`
We write the launch args into local storage. As on cold start 'activated' fires before 'deviceready', we check after 'deviceready' if launch args are available. The local storage solution is a hack, but it was not possible to add a working event listener outside of onWinJSReady = function() {...}. Trying with:

`Windows.UI.WebUI.WebUIApplication.addEventListener("activated", resumingHandler, false);`
and
`WinJS.Application.addEventListener("activated", resumingHandler, false);`

It is possible to receive the event but the launch args are empty where ever these listener are placed in the code. Maybe these finding help also for implementing the background notifications. Do you have any idea for a more elegant solution? Thanks!

**Comment by rdesimone** [comment]
For cold start I found a nicer solution without a hack: 
`var launchArgs = cordova.require('cordova/platform').activationContext.args ;`
