### ISSUE TITLE
"unfortunately app has stopped"

### ISSUE THREAD

**Issue by IchigoK** [phonegap/phonegap-plugin-push#2643]
### Expected Behaviour
App Open.
### Actual Behaviour
I'm recevi this message "unfortunately app has stopped", after compile my app.

#### Steps to Reproduce 
1. Install Documentation of plugin
2. run android << dont receive error
3. app dont start >> "unfortunately app has stopped"

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Tabled  Samsung Android 4.2

#### Cordova CLI version and cordova platform version
    phonegap --version                                    8.0.0
    phonegap platform version android                   7.0.0

#### Plugin version
    phonegap plugin version | grep phonegap-plugin-push   2.0.0
> <plugin name="phonegap-plugin-push" spec="~2.0.0">
>        <variable name="FCM_VERSION" value="15.0.0" />
>  </plugin>

**Comment by IchigoK** [comment]
in android >= 5.1 it's work normally

**Comment by jcesarmobile** [comment]
Latest version of the plugin only supports cordova-android 7.1.x, which only supports Android 4.4+

**Comment by IchigoK** [comment]
how do i work for < 4.4.x? with android **7.0.0**
