### ISSUE TITLE
Getting error while building the android project

### ISSUE THREAD

**Issue by ckvnahsik** [phonegap/phonegap-plugin-push#2645]
* What went wrong:
Could not resolve all files for configuration ':debugCompileClasspath'.
> FAILED
Could not find firebase-iid-interop.aar (com.google.firebase:firebase-iid-interop:16.0.0).
  Searched in the following locations:
      https://jcenter.bintray.com/com/google/firebase/firebase-iid-interop/16.0.0/firebase-iid-interop-16.0.0.aar
> Could not find play-services-basement.aar (com.google.android.gms:play-services-basement:15.0.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.1/play-services-basement-15.0.1.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

----------------------------------------------------------------------------------------------------------

I am using Cordova 8.1 
android 6.4.0

These are the plugins 
"cordova-plugin-device" spec="^2.0.2" 
"cordova-plugin-device-motion" spec="^2.0.1"
"cordova-plugin-device-orientation" spec="^2.0.1"
"cordova-plugin-dialogs" spec="^2.0.1" 
"cordova-plugin-geolocation" spec="^4.0.1"
"cordova-plugin-globalization" spec="^1.11.0" 
"cordova-plugin-image-picker" spec="^1.1.3"
"cordova-plugin-media-capture" spec="^3.0.2" 
"cordova-plugin-network-information" spec="^2.0.1" 
"cordova-plugin-splashscreen" spec="^5.0.2"
"cordova-plugin-statusbar" spec="^2.4.2"
"cordova-plugin-vibration" spec="^3.1.0"
"cordova-plugin-whitelist" spec="^1.3.3"
"cordova-plugin-app-version" spec="^0.1.9" 
"cordova-plugin-camera" spec="^4.0.3"
"cordova-plugin-contacts" spec="^3.0.1"
"cordova-plugin-android-permissions" spec="^1.0.0"
"cordova-plugin-appcenter-analytics" spec="^0.1.8"
"cordova-plugin-appcenter-crashes" spec="^0.1.8"
"cordova-plugin-appcenter-shared" spec="^0.1.8"
"cordova-plugin-appcenter-push" spec="^0.1.8" 
"cordova-plugin-file-transfer" spec="^1.7.1"
"cordova-plugin-file" spec="^6.0.1"
"cordova-plugin-media" spec="^5.0.2"
"cordova-plugin-battery-status" spec="^2.0.2"
"cordova-plugin-inappbrowser" spec="^3.0.0"
"phonegap-plugin-barcodescanner" spec="^8.0.1" --- "ANDROID_SUPPORT_V4_VERSION" value="27.1.1"
"cordova-android-support-gradle-release" spec="2.0.1" -- "ANDROID_SUPPORT_VERSION" value="27.+"
"cordova-support-google-services" spec="1.1.0" 
"phonegap-plugin-push" spec="2.1.3" --- "FCM_VERSION" value="11.6.2"

**Comment by ckvnahsik** [comment]
I am using Cordova 8.1 
android 6.4.0

These are the plugins 

<plugin name="cordova-plugin-device" spec="^2.0.2" />
    <plugin name="cordova-plugin-device-motion" spec="^2.0.1" />
    <plugin name="cordova-plugin-device-orientation" spec="^2.0.1" />
    <plugin name="cordova-plugin-dialogs" spec="^2.0.1" />
    <plugin name="cordova-plugin-geolocation" spec="^4.0.1" />
    <plugin name="cordova-plugin-globalization" spec="^1.11.0" />
    <plugin name="cordova-plugin-image-picker" spec="^1.1.3" />
    <plugin name="cordova-plugin-media-capture" spec="^3.0.2" />
    <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
    <plugin name="cordova-plugin-splashscreen" spec="^5.0.2" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.2" />
    <plugin name="cordova-plugin-vibration" spec="^3.1.0" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="cordova-plugin-app-version" spec="^0.1.9" />
    <plugin name="cordova-plugin-camera" spec="^4.0.3" />
    <plugin name="cordova-plugin-contacts" spec="^3.0.1" />
    <plugin name="cordova-plugin-android-permissions" spec="^1.0.0" />
    <plugin name="cordova-plugin-appcenter-analytics" spec="^0.1.8" />
    <plugin name="cordova-plugin-appcenter-crashes" spec="^0.1.8" />
    <plugin name="cordova-plugin-appcenter-shared" spec="^0.1.8" />
    <plugin name="cordova-plugin-appcenter-push" spec="^0.1.8" />
    <plugin name="cordova-plugin-file-transfer" spec="^1.7.1" />
    <plugin name="cordova-plugin-file" spec="^6.0.1" />
    <plugin name="cordova-plugin-media" spec="^5.0.2" />
    <plugin name="cordova-plugin-battery-status" spec="^2.0.2" />
    <plugin name="cordova-plugin-inappbrowser" spec="^3.0.0" />
    <plugin name="phonegap-plugin-barcodescanner" spec="^8.0.1">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.1.1" />
    </plugin>
    <plugin name="cordova-android-support-gradle-release" spec="2.0.1">
        <variable name="ANDROID_SUPPORT_VERSION" value="27.+" />
    </plugin>
    <plugin name="cordova-support-google-services" spec="1.1.0" />
    <plugin name="phonegap-plugin-push" spec="2.1.3">
        <variable name="SENDER_ID" value="xxxxxxxxxxxxxxxxxxxxxx" />
        <variable name="FCM_VERSION" value="11.6.2" />
    </plugin>

**Comment by Artfloriani** [comment]
This seems to be an issue with JCenter, and some libraries were unpublished without being added to Google's Maven reposity. Follow-up: 
https://issuetracker.google.com/issues/120759347#comment30

**Comment by jcesarmobile** [comment]
Yeah, it was a Google problem, should be fixed by now
