### ISSUE TITLE
Custom sounds on iOS 12 with v1.10

### ISSUE THREAD

**Issue by nonsenseless** [phonegap/phonegap-plugin-push#2648]
I've filled out the details to best of my abilities, but the reason for my filing this is that I came across a post where somebody mentioned that v1.10 was kind of old for iOS 10, and I was wondering if it's possible that the v1.10 just doesn't work with iOS 12 for custom sounds? Android worked perfectly fine out of the box.

Any advice would be appreciated!

### Expected Behaviour
When specifying a sound payload, the notification should play it. When using the 'default' sound, the default sound should play.

### Actual Behaviour
The phone vibrates on receipt of the push notification but no sound plays. When the sound key is omitted, the phone does not vibrate. I think it's probably telling that even the Default notification sound doesn't seem to play.

### Reproduce Scenario (including but not limited to)
The plugin is initialized using:

    var push = PushNotification.init({
      android: {
        senderID: "XXXXXXXX"
      },
      ios: {
        sound: true,
        alert: true,
        badge: true,
        clearBadge: true
      }
    });

I have tried placing the sound file in the root of the iOS project, in the Resources folder, and even in the CDVNotification.bundle.  

I've tried the following payload formats: 
{"aps": {"alert":"Testing.. (1)",sound":"default", "badge": 1} }
{"aps": {"alert":"Testing.. (1)",sound":"yougotmail.caf", "badge": 1} }
{"aps": {"alert":"Testing.. (1)",sound":"yougotmail", "badge": 1} }

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 12.0.1

#### Cordova CLI version and cordova platform version

cordova 7.1.0
cordova-ios 4.5.5

#### Plugin version

    1.10.7

#### Logs taken while reproducing problem
default	16:54:45.376303 -0600	coreduetd	Received notification event for nearby devices changed!
default	16:54:45.515401 -0600	SpringBoard	Received incoming message on topic com.app.code at priority 10
default	16:54:45.518727 -0600	SpringBoard	[com.app.code] Received remote notification request 7BEF-9F83 [ hasAlertContent: 1, hasSound: 1 hasBadge: 1 hasContentAvailable: 0 hasMutableContent: 0 ]
default	16:54:45.519548 -0600	SpringBoard	[com.app.code] Deliver push notification request 7BEF-9F83
default	16:54:45.521620 -0600	SpringBoard	[com.app.code] Badge can be set for notification 7BEF-9F83: 1 [ canBadge: 1 badgeNumber: 1 ]
default	16:54:45.523712 -0600	SpringBoard	[com.app.code] Setting badge to 1 [ old badge: 1 ]
default	16:54:45.524252 -0600	SpringBoard	[com.app.code] Saving notification 7BEF-9F83: 1 [ hasAlertContent: 1, shouldPresentAlert: 1 isTransient: 0 ]
default	16:54:45.531862 -0600	SpringBoard	Saving notification list at /var/mobile/Library/SpringBoard/PushStore/com.app.code.pushstore with 23 items
default	16:54:45.578118 -0600	SpringBoard	[com.app.code] Adding notification 7BEF-9F83 to destinations 14 [ hasAlertContent: 1, shouldPresentAlert: 1 hasSound: 1 shouldPlaySound: 1 ]
default	16:54:45.581230 -0600	SpringBoard	[com.app.code] Load 0 pending notification dictionaries
default	16:54:45.582198 -0600	SpringBoard	[com.app.code] Saved push notification 7BEF-9F83 to store
default	16:54:45.586560 -0600	SpringBoard	[com.app.code] Sending 1 delivered notifications to 1 connections
default	16:54:45.648560 -0600	bulletindistributord	BLTBulletinDistributor addBulletin: <private> (publisherMatchID: <private>) forFeed: 59 playLightsAndSirens: YES turnsOnDisplay: YES willPresentNotification: 0
default	16:54:45.658069 -0600	coreduetd	Received notification event for nearby devices changed!
default	16:54:45.659334 -0600	coreduetd	Received notification event for nearby devices changed!
default	16:54:45.660708 -0600	coreduetd	Received notification event for nearby devices changed!
default	16:54:45.707533 -0600	SpringBoard	Observer for NCBulletinNotificationSource: Delivering ADD bulletin: E48C151A-290B-48E8-A81A-250858B30D7D
default	16:54:45.708177 -0600	SpringBoard	<private> adding bulletin 7BEF-9F83 for feed 59
default	16:54:45.714007 -0600	SpringBoard	Posting notification id: 7BEF-9F83; section: com.app.code; thread: A9B7-1713; category: ; timestamp: 2018-12-09 22:54:45 +0000; actions: [ minimal: 0 (0 text), default: 0 (0 text) ]; destinations: [ {(
    BulletinDestinationCoverSheet,
    BulletinDestinationBanner,
    BulletinDestinationNotificationCenter,
    BulletinDestinationLockScreen
)} ]
default	16:54:45.714250 -0600	SpringBoard	Alerting on post for request 7BEF-9F83. uiLocked=1 activeAlertDestinations=1 shouldSuppressAlert=0
default	16:54:45.714682 -0600	SpringBoard	Sound can be played for notification 7BEF-9F83: 1 [ hasRequest: 1 hasSound: 1 canPlaySound: 1 isQuietModeEnabledAndActive: 0 overridesQuietMode: 0 isInLostMode: 0 isDeviceUILocked: 1 alertsWhenLocked: 1 ]
default	16:54:45.715106 -0600	SpringBoard	Play sound for notification 7BEF-9F83
default	16:54:45.715609 -0600	SpringBoard	currentToneIdentifierForAlertType:TLAlertTypeAppNotification ==> texttone:App Notification
default	16:54:45.716230 -0600	SpringBoard	SBSoundController: played sound - environments=1 -> <SBUISound: 0x13dce3c70>
{  SoundType: ToneAlert
   hasCompletionBlock: NO
    Alert Configuration: <TLAlertConfiguration: 0x13dc141e0; type = app notification>

}
default	16:54:45.716427 -0600	SpringBoard	_soundForToneIdentifier texttone:App Notification ==> <TLSystemSound: 0x13db9ad90; soundFileURL = file:///System/Library/Audio/UISounds/sms-received1.caf; soundID = 1015>
default	16:54:45.716529 -0600	SpringBoard	Screen can be turned on for notification 7BEF-9F83: 1 [ hasRequest: 1 canTurnOnDisplay: 1 isQuietModeEnabledAndActive: 0 overridesQuietMode: 0 caseIsEnabledAndLatched: 0 isInLostMode: 0 isDeviceUILocked: 1 alertsWhenLocked: 1 sentToLockScreenDestination: 1 sentToBannerDestination: 1 ]
default	16:54:45.716996 -0600	SpringBoard	Turn on screen for notification 7BEF-9F83 [ overridesPocketMode: 0 screenIsOn: 0 ]
default	16:54:45.723782 -0600	SpringBoard	<TLAlertSystemSoundController: 0x13c9d0230>: _playAlert:(<TLAlert: 0x13b1e0370; configuration = <TLAlertConfiguration: 0x13dc141e0; type = app notification>; toneIdentifier = texttone:App Notification; vibrationIdentifier = Built-In-System-Sound-ID-Vibration>). Sound: <TLSystemSound: 0x13db9ad90; soundFileURL = file:///System/Library/Audio/UISounds/sms-received1.caf; soundID = 1015>.
default	16:54:45.723969 -0600	SpringBoard	TLAlertSystemSoundController: +_optionsForSystemSoundAlert:(<TLAlert: 0x13b1e0370; configuration = <TLAlertConfiguration: 0x13dc141e0; type = app notification>; toneIdentifier = texttone:App Notification; vibrationIdentifier = Built-In-System-Sound-ID-Vibration>). kAudioServicesPlaySystemSoundOptionBehaviorKey => 1.
default	16:54:45.724158 -0600	SpringBoard	<TLAlertSystemSoundController: 0x13c9d0230>: _playAlert:(<TLAlert: 0x13b1e0370; configuration = <TLAlertConfiguration: 0x13dc141e0; type = app notification>; toneIdentifier = texttone:App Notification; vibrationIdentifier = Built-In-System-Sound-ID-Vibration>). Calling AudioServicesPlaySystemSoundWithOptions for soundID: 1015.
default	16:54:45.733925 -0600	duetexpertd	Observer for ATXBBNotificationManager: Delivering ADD bulletin: E48C151A-290B-48E8-A81A-250858B30D7D
default	16:54:45.735883 -0600	duetexpertd	Observer for ATXBBNotificationManager: finished with bulletin E48C151A-290B-48E8-A81A-250858B30D7D, transactionID 1
default	16:54:45.736245 -0600	coreduetd	Received notification event for nearby devices changed!
default	16:54:45.762934 -0600	SpringBoard	Posting notification 7BEF-9F83 to destination SBDashBoardNotificationDispatcher
default	16:54:45.763423 -0600	SpringBoard	Destination SBDashBoardNotificationDispatcher received notification 7BEF-9F83
default	16:54:45.763658 -0600	SpringBoard	Destination SBDashBoardMainPageContentViewController posting notification 7BEF-9F83 to SBDashBoardCombinedListViewController
default	16:54:45.764099 -0600	SpringBoard	Destination SBDashBoardCombinedListViewController posting notification 7BEF-9F83 to NCNotificationCombinedListViewController
default	16:54:45.785747 -0600	SpringBoard	Notification 7BEF-9F83 has been intercepted, not posting to the alerts queue
default	16:54:46.016121 -0600	kernel	virtual void AppleH4DisplayPipe::set_frame_notification_gated(bool, bool): Value underrun for CRC ref counter
default	16:54:46.112458 -0600	SpringBoard	Animating backlight to factor 0.01 with duration 0.00 source:12 (notification)
default	16:54:46.172341 -0600	SpringBoard	<private> - updateIdleTimerForReason:"NCNotificationTurnOnScreen"]
default	16:54:46.234620 -0600	SpringBoard	<TLAlertSystemSoundController: 0x13c9d0230>: _playAlert:(<TLAlert: 0x13b1e0370; configuration = <TLAlertConfiguration: 0x13dc141e0; type = app notification>; toneIdentifier = texttone:App Notification; vibrationIdentifier = Built-In-System-Sound-ID-Vibration>). Running completion block for AudioServicesPlaySystemSoundWithOptions for soundID: 1015.
default	16:54:46.285980 -0600	SpringBoard	Got notification that a deferred screen unblank has completed
default	16:54:46.286895 -0600	SpringBoard	Animating backlight to factor 1.00 with duration 0.09 source:12 (notification)
default	16:54:46.609762 -0600	CommCenter	#I FBSDisplayLayoutUpdateHandler: 5. app got notification state: new counter=181
default	16:54:46.635498 -0600	coreduetd	Received notification event for nearby devices changed!
default	16:54:46.641785 -0600	locationd	Client com.apple.springboard (0x11a819600) is subscribing to notification kCLConnectionMessageGyroBiasEstimation
default	16:54:46.792551 -0600	passd	PDNotificationStreamManager (com.apple.notifyd.matching): Observers existed to handle notification <private>.
default	16:54:46.803107 -0600	coreduetd	Received notification event for nearby devices changed!
default	16:54:52.273423 -0600	NPKCompanionAgent	Notice: Received XPC events stream handler callback for distributed notification name <private>, object (null), userInfo (null)
default	16:54:52.283387 -0600	NPKCompanionAgent	Notice: Relevant passes changed (notification <private>), fetching...
default	16:54:56.258873 -0600	CommCenter	#I FBSDisplayLayoutUpdateHandler: 5. app got notification state: new counter=182
default	16:54:56.482759 -0600	SpringBoard	Got notification that a deferred screen unblank has completed
default	16:54:56.555179 -0600	passd	PDNotificationStreamManager (com.apple.notifyd.matching): Observers existed to handle notification <private>.
default	16:54:56.597452 -0600	coreduetd	Received notification event for nearby devices changed!
default	16:54:56.597606 -0600	coreduetd	Received notification event for nearby devices changed!
default	16:54:57.180569 -0600	coreduetd	Received notification event for nearby devices changed!

**Comment by jcesarmobile** [comment]
We don't support 1.x.x version of the plugin anymore.

Also in your payload your sound key has only one " in all examples, not sure if related
