### ISSUE TITLE
Could not find com.google.gms:google-services:3.2.0

### ISSUE THREAD

**Issue by wambowams** [phonegap/phonegap-plugin-push#2650]
### Expected Behaviour
The build should run as expected.

### Actual Behaviour
The build stops with following error:
` 
Where: Build file 'D:\programmierung\arbeit\notifier\app\BOSNotifierV2.App.Frontend\platforms\android\app\build.gradle' line: 97

What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not find com.google.gms:google-services:3.2.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/gms/google-services/3.2.0/google-services-3.2.0.pom
         https://jcenter.bintray.com/com/google/gms/google-services/3.2.0/google-services-3.2.0.jar
         https://repo1.maven.org/maven2/com/google/gms/google-services/3.2.0/google-services-3.2.0.pom
         https://repo1.maven.org/maven2/com/google/gms/google-services/3.2.0/google-services-3.2.0.jar
     Required by:
         unspecified:unspecified:unspecified

`
#### Steps to Reproduce 
Updating from cordova plugin 1.11.1 to version 2.2.3. 
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android SDK 26
#### Cordova CLI version and cordova platform version

   Ionic:

   ionic (Ionic CLI)  : 4.5.0 (C:\Users\wambo\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 17 other plugins)

System:

 (C:\Users\wambo\AppData\Local\Android\android-sdk)
   NodeJS            : v8.11.2 (D:\programme\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10

#### Plugin version

    cordova-android-play-services-gradle-release 1.4.6 "cordova-android-play-services-gradle-release"
    cordova-android-support-gradle-release 2.0.1 "cordova-android-support-gradle-release"
    cordova-open-native-settings 1.5.2 "Native settings"
    cordova-plugin-appcenter-analytics 0.1.9 "App Center Analytics for Cordova"
    cordova-plugin-appcenter-crashes 0.1.9 "App Center Crashes for Cordova"
    cordova-plugin-appcenter-shared 0.1.9 "App Center shared code for Cordova"
    cordova-plugin-device 2.0.2 "Device"
    cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
    cordova-plugin-ionic-webview 2.3.1 "cordova-plugin-ionic-webview"
    cordova-plugin-mauron85-background-geolocation 2.3.6 "CDVBackgroundGeolocation"
    cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
    cordova-plugin-network-information 2.0.1 "Network Information"
    cordova-plugin-qrscanner 2.6.0 "QRScanner"
    cordova-plugin-splashscreen 5.0.2 "Splashscreen"
    cordova-plugin-statusbar 2.4.2 "StatusBar"
    cordova-plugin-whitelist 1.3.3 "Whitelist"
    cordova-sqlite-storage 2.5.2 "Cordova sqlite storage plugin"
    cordova-support-google-services 1.1.0 "cordova-support-google-services"
    phonegap-plugin-multidex 1.0.0 "Multidex"
    phonegap-plugin-push 2.2.3 "PushPlugin"

**Comment by fredgalvao** [comment]
It's a Google issue.

Solutions, workarounds and details at:
https://twitter.com/ReleasesHub/status/1072175946747256832
https://issuetracker.google.com/issues/120759347
https://github.com/google/ExoPlayer/issues/5225
