### ISSUE TITLE
phonegup android build failed 

### ISSUE THREAD

**Issue by DimiUA** [phonegap/phonegap-plugin-push#2651]
Gudday, 
i'm facing with issue when building new version of android app.  Last successful build was about  month ago. When i removing plugin(phonegap-plugin-push) from my config.xml file, app build successfully. When i returning it back, again receive build error. I have try to include plugin `<plugin name="cordova-android-support-gradle-release" source="npm" />`, but not helped.
It seems like

> https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml
> https://jcenter.bintray.com/com/android/tools/build/gradle/

are not existing anymore, can it be fixed on my side? Or what need to do to make successful build with phonegap-plugin-push ?

### Expected Behaviour
Successful PhoneGap Build

### Actual Behaviour
FAILURE: Build failed with an exception.
* Where:
Build file '/build.gradle' line: 115
* What went wrong:
A problem occurred evaluating root project 'www_android'.
> Could not resolve all dependencies for configuration 'classpath'.
   > Could not find any matches for com.android.tools.build:gradle:+ as no versions of com.android.tools.build:gradle are available.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml
         https://jcenter.bintray.com/com/android/tools/build/gradle/
         file:/.m2/repository/com/android/tools/build/gradle/maven-metadata.xml
         file:/.m2/repository/com/android/tools/build/gradle/
     Required by:
         unspecified:unspecified:unspecified

#### Cordova CLI version and cordova platform version   

> PhoneGap (iOS / Android / Windows)
> cli-7.1.0 (4.5.4 / 6.3.0 / 5.0.0)
  

#### Plugin version
    `<plugin name="phonegap-plugin-push" source="npm" spec="2.1.2">`

#### Sample Code that illustrates the problem
On my config.xml file
    `<preference name="DisallowOverscroll" value="true" />
    <preference name="Orientation" value="portrait" />
    <preference name="android-minSdkVersion" value="18" />  
    <preference name="android-targetSdkVersion" value="26" />
    <preference name="multiDexEnabled" value="true" />     
    <preference name="deployment-target" value="10.2" />
    <preference name="StatusBarOverlaysWebView" value="false" />
    <preference name="StatusBarStyle" value="blacktranslucent" />
    <preference name="phonegap-version" value="cli-7.1.0" />

    <preference name="android-build-tool" value="gradle" />
    <plugin name="phonegap-plugin-push" source="npm" spec="2.1.2">
        <variable name="SENDER_ID" value="***" />
    </plugin>
    <platform name="android">
      <resource-file src="google-services.json" target="google-services.json" />
    </platform>

    <plugin name="cordova-plugin-statusbar" source="npm" spec="2.1.3" />
    <plugin name="cordova-plugin-device" source="npm" spec="2.0.2" />
    <plugin name="cordova-plugin-buildinfo" source="npm" spec="2.0.2" />    
    <plugin name="cordova-plugin-dialogs" source="npm" spec="1.2.1" />
    <plugin name="cordova-plugin-whitelist" source="npm" spec="1.2.1" />
    <plugin name="cordova-plugin-splashscreen" source="npm" spec="5.0.2" />
    <plugin name="cordova-plugin-camera" source="npm" spec="4.0.3"  />
    <plugin spec="https://github.com/phonegap/phonegap-mobile-accessibility.git" source="git" />
    <plugin name="cordova-android-support-gradle-release" source="npm" />`
*** - i hided my sender id

#### Logs taken while reproducing problem

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/build.gradle' line: 115
> 
> * What went wrong:
> A problem occurred evaluating root project 'www_android'.
> > Could not resolve all dependencies for configuration 'classpath'.
>    > Could not find any matches for com.android.tools.build:gradle:+ as no versions of com.android.tools.build:gradle are available.
>      Searched in the following locations:
>          https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml
>          https://jcenter.bintray.com/com/android/tools/build/gradle/
>          file:/.m2/repository/com/android/tools/build/gradle/maven-metadata.xml
>          file:/.m2/repository/com/android/tools/build/gradle/
>      Required by:
>          unspecified:unspecified:unspecified
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
>     at ChildProcess.whenDone (/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by JohEngstrom** [comment]
I have the same issue since yesterday. I think we just have to wait until Google fix this issue.

https://issuetracker.google.com/issues/120759347

**Comment by jcesarmobile** [comment]
yeah, it's a google problem
