### ISSUE TITLE
PGB: building an android app with phonegap-plugin-push versions 2.x?

### ISSUE THREAD

**Issue by ppetree** [phonegap/phonegap-plugin-push#2652]
What is the latest version of this plugin that works with FCM and can be built on PGB?

### Expected Behaviour
App builds, plugin is included

### Actual Behaviour
App builds, plugin is NOT included

### Reproduce Scenario (including but not limited to)
Build using the latest version of plugin-push on PGB.

#### Steps to Reproduce 
Known issue

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Any

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Any

#### Cordova CLI version and cordova platform version
I've tried:
```
    <preference name="android-build-tool" value="gradle" />
    <preference name="phonegap-version" value="cli-7.1.0" />
```
and
```
    <preference name="android-build-tool" value="gradle" />
    <preference name="phonegap-version" value="cli-7.1.0" />
    <preference name='pgb-builder-version' value='2' />
```
and
```
    <preference name="android-build-tool" value="gradle" />
    <preference name="phonegap-version" value="cli-8.0.0" />
```
and
```
    <preference name="android-build-tool" value="gradle" />
    <preference name="phonegap-version" value="cli-8.0.0" />
    <preference name='pgb-builder-version' value='2' />
```
#### Plugin version
`<plugin name="phonegap-plugin-push" source="npm" spec="2.2.3">`

#### Sample Push Data Payload
Can't get that far

#### Sample Code that illustrates the problem
None needed.

#### Logs taken while reproducing problem
Fetching plugin "phonegap-plugin-push@2.2.3" via npm
Installing "phonegap-plugin-push" at "2.2.3" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 7.0.0, failed version requirement: >=7.1.0

**Comment by brunojs02** [comment]
run: 
- phonegap plugin rm phonegap-plugin-push
- phonegap plugin add phonegap-plugin-push@2.1.3

**Comment by jcesarmobile** [comment]
You can't use latest version of the plugin until Phonegap build is updated to use latest Cordova CLI

**Comment by ppetree** [comment]
You certainly didn't answer my question.  What IS the latest version that CAN be used that works WITH FCM?

**Comment by jcesarmobile** [comment]
but brunojs02 did

**Comment by ppetree** [comment]
Sorry, missed that.

**Comment by brunojs02** [comment]
2.1.3, because this version use cordova platform version android 7.0.0 that is the same used by PGB!

**Comment by ppetree** [comment]
None of these three work.
`    <plugin name="phonegap-plugin-push" source="pgb" spec="2.1.3">
    <plugin name="phonegap-plugin-push" source="npm" spec="2.1.3">
    <plugin name="phonegap-plugin-push" spec="2.1.3">
`

Tried with these settings:
```
    <preference name="android-build-tool" value="gradle" />
    <preference name="phonegap-version" value="cli-8.0.0" />
    <preference name='pgb-builder-version' value='2' />
```
and
```
    <preference name="android-build-tool" value="gradle" />
    <preference name="phonegap-version" value="cli-8.0.0" />
```

**Comment by jcesarmobile** [comment]
I built this sample app long ago
https://github.com/jcesarmobile/phonegap-plugin-push-sample

It uses 
```
<plugin name="phonegap-plugin-push" spec="~2.1.2">
    <variable name="FCM_VERSION" value="11.0.1" />
</plugin>
```
And worked last time I compiled it.

**Comment by ppetree** [comment]
BTW, going back to 2.2.3 the app does build without all the gradle errors.... just back to square one.

**Comment by jcesarmobile** [comment]
FYI, there is a problem with google libraries on maven that is probably causing the
> Could not find any matches for com.android.tools.build:gradle:+ as no versions of com.android.tools.build:gradle are available.

https://issuetracker.google.com/issues/120759347

**Comment by ppetree** [comment]
(With phonegap, there's always something.... been doing this since cordova 1.8 and it's exhausting. The powers that be need to learn what a piton is and how to anchor the platform at each level of the ascent.)

**Comment by jcesarmobile** [comment]
It’s not phonegap’s fault, it’s Google’s fault, it also fails if you build locally, or if you don’t use phonegap (i.e, in native apps)
