### ISSUE TITLE
cant find upgrade instuctions from 1.5.x to 1.11.x

### ISSUE THREAD

**Issue by guykatz** [phonegap/phonegap-plugin-push#2658]
### Expected Behaviour
Hi; after years of using 1.5.x I am trying to upgrade to 1.11.x (cant use 2.x.x yet).
back in the day I remember there were some breaking changes around the 1.6/1.8 release but I cant find the upgrade instuctions/release notes.
note that browsing forums I see that some people use the sender ID in the plugin param. I guess 1.5.3 did not mandate this as it worked well without. even after adding it nothing changed.
but again, I cant find upgrade instructions.

### Actual Behaviour
dropping in 1.11 instead of 1.5 does not seem to work our of the box
server pushes notification and receives ok from GCM (server code was not changed at all of course)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

android 9 latest on my phone.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
essential phone

#### Cordova CLI version and cordova platform version
phonegap build env.
phonegap cli-8.0.0.

#### Plugin version
1.11.1
(<gap:plugin name="phonegap-plugin-push" source="npm" version="1.11.1"/>)

#### Sample Push Data Payload
Message(timeToLive=10800, data: {title=mysite.com,message=the message 2 and 1.2-3.4,ledColor=[0,255,255,0]})
#### Sample Code that illustrates the problem
```
		registerDeviceForPush: function () {
				if(Utils.isCordova()){
					try{ 
							window.pushPluginV2 = PushNotification.init({
								android: {
									senderID: "xxx"
								},
								ios: {
									alert: "true",
									badge: "true",
									sound: "true",
									clearBadge: "true"
								}
							});
							window.pushPluginV2.on('registration', function(data) {
								if(data.registrationId){
									//compare stored push reg id with new one and only if not the same update the xwave server
....some sync with server code here (works - I can see in server when pushregId changes)
									}
								}
							});
							window.pushPluginV2.on('notification', function(data) {
	//some code that I am not sure is important here. I am trying to get the notification to the notification tray
							});
							
							window.pushPluginV2.on('error', function(e) {
								//prompt something
							});
					}catch(err){
						//prompt something
					}
				}else{
					if(console){
						console.log('not in native mode. skipping push registration process');
					}
				}
		},
```

#### Logs taken while reproducing problem
no error on push side, 
push registration ok on client side
no notification received though

**Comment by jcesarmobile** [comment]
Sorry, we don’t support 1.x anymore
