### ISSUE TITLE
on('registration') does not fire under android API 26

### ISSUE THREAD

**Issue by angel1st** [phonegap/phonegap-plugin-push#2662]
### Expected Behaviour
To get `on('registration')` fired once `PushNotification.init` is done. Please note the very same code works flawlessly on API 27.

### Actual Behaviour
`on('registration'` never been fired, hence the device cannot be registered to accept push notifications.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8.0, API 26

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Android emulator Nexus 5

#### Cordova CLI version and cordova platform version

    cordova --version                                    8.1.2 (cordova-lib@8.1.1)
    cordova platform version android                     android 7.1.4

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.2.3

#### Sample Push Data Payload

```
var payload = {
                    "data": {
                        "title": "Test Notification",
                        "body": message,
                        "surveyID": "ewtawgreg-gragrag-rgarhthgbad"
                    }
                };
```

#### Logs taken while reproducing problem

> 12-26 15:20:31.928 26566 28398 E GCM     : Missing checkin config file
12-26 15:20:31.996 26566 28398 W GCM     : GCM FAILED TO INITIALIZE - missing checkin
12-26 15:20:32.327 24962 27231 W zygote64: Long monitor contention with owner Binder:24962_11 (26021) at boolean com.android.server.am.ActivityManagerService.unbindService(android.app.IServiceConnection)(ActivityManagerService.java:18305) waiters=0 in boolean com.android.server.am.ActivityManagerService.stopServiceToken(android.content.ComponentName, android.os.IBinder, int) for 600ms
12-26 15:20:32.678 28276 28276 I Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
12-26 15:20:32.683 24962 25962 W zygote64: Long monitor contention with owner Binder:24962_8 (25375) at boolean com.android.server.am.ActivityManagerService.unbindService(android.app.IServiceConnection)(ActivityManagerService.java:18305) waiters=0 in void com.android.server.am.ActivityManagerService.serviceDoneExecuting(android.os.IBinder, int, int, int) for 326ms
12-26 15:20:32.684 28276 28551 E Push_Plugin: execute: Got IO Exception AUTHENTICATION_FAILED
12-26 15:20:32.685 28276 28551 D Push_Plugin: no icon option
12-26 15:20:32.685 28276 28551 D Push_Plugin: no iconColor option

**Comment by wambowams** [comment]
Do you have added the google-services.json? You although have to move it to your android platform app folder. You can use the config.xml for this with:
`<resource-file src="google-services.json" target="app/google-services.json" />`

**Comment by angel1st** [comment]
`google-services.json` is placed into `app` sub folder. As I stated above, the very same build works flawlessly on emulator with API 27.

**Comment by macdonst** [comment]
@angel1st are you reproducing this problem on an emulator? If so I suspect the emulator does not have play services installed. Please test on a real device.

**Comment by angel1st** [comment]
thanks, @macdonst - it seems your suggestion is the right one. I have no issue to start the app on the device with Android 7.0 where API is supposedly 24/25.
Any hint how I can install the right google play services version on the emulator, so I can test it properly over there?

**Comment by macdonst** [comment]
Yeah, I'm going to close this as we don't support emulator issues. Same thing on iOS where you can't test push in the simulator.

**Comment by angel1st** [comment]
@macdonst - is there a way to handle this case properly, since it might happen on a real device as well? I mean - the plugin to throw an exception for instance, since now it simply hangs the app.
