### ISSUE TITLE
Ios rich push notifications with media content?

### ISSUE THREAD

**Issue by prabhjotAppmobi** [phonegap/phonegap-plugin-push#2663]
Is there any functionality offered by plugin which support rich push notifications? We wanted to show a big image in notification. We are sending following JSON for APNS push but image is not received.

```
{
	"aps": {
		"alert": "Hello!",
		"sound": "default",
		"image": "https://i.imgur.com/t4WGJQx.jpg",
		"mutable-content": 1,
		"badge": 1
	},
	"data": {
		"attachment-url": "https://i.imgur.com/t4WGJQx.jpg"
	}
}
```

We would be glad to have any help!

**Comment by macdonst** [comment]
@prabhjotAppmobi currently not supported as I need changes in cordova-ios for it to work. See #1347
