### ISSUE TITLE
PushNotification is not defined

### ISSUE THREAD

**Issue by SedCore** [phonegap/phonegap-plugin-push#2665]
### Expected Behaviour
Get registration ID
### Actual Behaviour
PushNotification is not defined
### Reproduce Scenario (including but not limited to)
I get this alert on error throw : "PushNotification is not defined" at line of PushNotification.init
(I'm building with Cordova CLI)
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy A7
#### Cordova CLI version and cordova platform version

    cordova --version                                    # 8.0.0
    cordova platform version android                     # 7.0.0

#### Plugin version

    phonegap-plugin-push    # e.g. 2.1.2

#### Sample Code that illustrates the problem
In config.xml :

```
<platform name="android">
        <allow-intent href="market:*" />
        <resource-file src="google-services.json" target="app/google-services.json" />
        <preference name="loadUrlTimeoutValue" value="700000" />
    </platform>
```

In JS file :
```
document.addEventListener("deviceready", notifications(), false);
	
//NOTIFICATIONS
function notifications(){
	try{
		var push = cordova.PushNotification.init({
			 "android": {}
		});
		push.on('registration', function(data){
			 alert('data registration id :'+data.registrationId);
			 alert('data registration type:'+data.registrationType);
		});
	}
	catch(err) {
		alert("error : " + err);
	}
}
```

**Comment by jcesarmobile** [comment]
Make sure you are using latest cordova-android and that the plugin is installed. This error happens when the plugin is not installed
