### ISSUE TITLE
App freezes when this plugin and cordova call are installed 

### ISSUE THREAD

**Issue by bpowell15** [phonegap/phonegap-plugin-push#2666]
I am having trouble implementing this plugin at the same time as the CordovaCall plugin at this link... 
https://github.com/WebsiteBeaver/CordovaCall

Anytime I try to boot the app with both plugins installed, device ready is fired by ionic, but the app freezes and never loads. 

There is no obvious error message. I have reached out on their github but have not received any feedback. If any one here has any input, direction, or hints on how to debug this, it would be greatly appreciated. 

Thanks

**Comment by macdonst** [comment]
@bpowell15 Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
