### ISSUE TITLE
Install failed duplicate permission c2d message

### ISSUE THREAD

**Issue by LucasNova** [phonegap/phonegap-plugin-push#267]
Hello, i have two android cordova application on Android 5.0(important) with [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push). When i try install second application "cordova run android", and i have another installed, cordova tell me next error:

ERROR: Failed to launch application on device: ERROR: Failed to install apk to device:  pkg: /data/local/tmp/android-debug.apk
Failure [INSTALL_FAILED_DUPLICATE_PERMISSION perm=com.company.firstapp.permission.C2D_MESSAGE pkg=com.company.secondapp]

If i try remove plugin from second app, then running done successful

**Comment by macdonst** [comment]
@LucasNova did you provide different package names for both apps? The plugin.xml should add that permission based on your package name.

<permission android:name="$PACKAGE_NAME.permission.C2D_MESSAGE" android:protectionLevel="signature" />

**Comment by LucasNova** [comment]
@macdonst yes, package names is different. Remind, i can run app without plugin. I see problem now like this: if plugin was installed on another package, then you can't run/install new app with this plugin. I could be wrong. I check this only on android 5.0 version on two devices, Asus zenFone 2 and HTC one M9, and have same trouble.

**Comment by smdvdsn** [comment]
Can  you open the platforms/android/AndroidManifest.xml files from the two projects and search for the other package name in each. So in app one's manifest file search for app two's package and then do the same in the other file.

Also did you create app two by copying app one or was it a fresh cordova create? I've seen this once before when using the same directory to create another app with a new package name etc. Just changing config.xml. Doing cordova platform rm android & cordova platform add android solved it for me.

**Comment by macdonst** [comment]
@LucasNova Yes, what @smdvdsn said is most likely your problem. You have the same package name for permission in two different AndroidManifest.xml files.

**Comment by macdonst** [comment]
Closing, no input for almost a month.
