### ISSUE TITLE
iOS is not showing any alert style nor sound option for push notifications

### ISSUE THREAD

**Issue by pliablepixels** [phonegap/phonegap-plugin-push#268]
Hi folks, I have integrated this plugin into an ionic app. The problem I am facing is that when I go to Notification center, I don't see any option to configure the display style or enable sound! But everything else works - I get notifications etc.

I am in IOS 9.1 (had the same problem with 9.0.1)

Here is how the app looks in notification settings: (Note no sound or style option)
![twqe6](https://cloud.githubusercontent.com/assets/4116654/10766945/41bbdd16-7cb0-11e5-9aa3-34d365822015.png)

Here is how I am initializing the plugin - this is happening in a factory - the code is not directly inside app.js. I don't think that should matter. When I run the app the first time, it prompts me for enabling push notifications and I say yes.

Any clues on where to look?

**Comment by macdonst** [comment]
@pliablepixels what do you pass to the init method?

**Comment by pliablepixels** [comment]
@macdonst I'm sorry - looks like I forgot to add that code

```
var push = PushNotification.init(
                    { "android": 
                     {"senderID":zm.gcmSenderId,
                      "icon":"ic_stat_notification"
                     }
                    },
                     
                     { "ios": 
                     {"alert": "true", 
                      "badge": "true", 
                      "sound": "true"}
                    }  
````

**Comment by pliablepixels** [comment]
Well guess what? If I stuff in both android and iOS into the same init (like the example shows), these options are not displayed. But if I separate them out - i.e only do iOS for iOS and Android for Android depending on platform everything works!

**Comment by macdonst** [comment]
@pliablepixels you didn't format your JSON properly. This should work:

```
var push = PushNotification.init({
    "android":  {
        "senderID":zm.gcmSenderId,
        "icon":"ic_stat_notification"
    },
    "ios": {
        "alert": "true", 
        "badge": "true", 
        "sound": "true"
    }
});
```

**Comment by pliablepixels** [comment]
@macdonst oh goodness - you are correct! Thank you!
