### ISSUE TITLE
Not receiving notifications on android oreo

### ISSUE THREAD

**Issue by cmohanraj10** [phonegap/phonegap-plugin-push#2682]
We developed our app using Phonegap. We are sending push notifications using this plugin and its works great for both android & iOS. 

But its not working on android version 8(Oreo).  I found this link through research.

https://developer.android.com/training/notify-user/channels#kotlin

Any idea?

**Comment by AhmedRaafat13** [comment]
what is ur plugin version ?

**Comment by macdonst** [comment]
@cmohanraj10 make sure you are using the latest version of the plugin.

https://github.com/phonegap/phonegap-plugin-push/blob/2f45c0dd7520da1f6bb4b86c15c747dec0cfef1c/docs/PAYLOAD.md#notification-channels
