### ISSUE TITLE
com.android.tools.build:gradle are available

### ISSUE THREAD

**Issue by lxbbright** [phonegap/phonegap-plugin-push#2685]
I am unable to build the project on phonegap build when using the bellow specified version of the plugin, phonegap-plugin-push   2.1.x I need this version because it has a fix for working on Android 8 and I can't use the versions above it like 2.2.x because they require phonegap-version cli-8.0.0 and I can't use that because I still need the mobile app to work on android 5.0.

The issue I'm getting when I try to use phonegap build to build the app is:
 Could not find any matches for com.android.tools.build:gradle:+ as no versions of 
 com.android.tools.build:gradle are available

This is the exact same issue happening on this link:
https://forums.adobe.com/message/10804391

but I'm able to use this solution because I'm using phonegap build with a config.xml file that downloads the plugin sources on its server side.

#### Platform and Version 
 Android 5.0 
 android-minSdkVersion is set to 21 on the config.xml
 and android-targetSdkVersion is set to 26

####  What device vendor
 This issue is happening on any android devices using android 8

#### Cordova CLI version and cordova platform version
   phonegap-version  is  cli-7.1.0

#### Plugin version
     phonegap-plugin-push   2.1.3
    I can only use version 2.1.x because

**Comment by macdonst** [comment]
@lxbbright the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.

**Comment by lxbbright** [comment]
@macdonst thank you for responding. I do not thing this issue is as a result of a fault in phonegap. I think this issue is cause by a fault in this plugin that is specific to version 2.1.x.
It seems that the paths that included the "com.android.tools.build:gradle:" were moved or removed. and the has to be a change in the build gradle file to point to the right path. but I am unable to make this change since I'm using config.xml to get the plugin and use it as is. 

This is the log I am getting.
Could not find any matches for com.android.tools.build:gradle:+ as no versions of
com.android.tools.build:gradle are available
