### ISSUE TITLE
We developed our app using Phonegap. We are sending push notifications using this plugin and its works great for android But its not working on android version 8(Oreo). phonegap plugin version 1.8.0

### ISSUE THREAD

**Issue by shakhertyagi** [phonegap/phonegap-plugin-push#2688]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@shakhertyagi Android 8 (Oreo) introduced changes in the notification system which are not support in the 1.x stream of the plugin. Please update to the latest version of the plugin.
