### ISSUE TITLE
Build in IntelXDK

### ISSUE THREAD

**Issue by tassyo** [phonegap/phonegap-plugin-push#269]
Hi,
Version Deprecated pushPlugin the building in intel XDK was good, and next version idk, not building my application more. 
Please, this version not build intel xdk?

compileReleaseJava.../pushApp/platforms/android/src/com/adobe/phonegap/push/PushInstanceIDListenerService.java:7: error: package com.google.android.gms.iid does not exist
import com.google.android.gms.iid.InstanceID;

**Comment by macdonst** [comment]
@tassyo Does Intel XDK support Gradle? Cause it seems like they don't have the Google Play Services framework installed.

**Comment by tassyo** [comment]
@macdonst  good night, what would be the way forward? take much to push the cross application, please some indication?

**Comment by macdonst** [comment]
@tassyo I'm sorry, I don't understand what you are asking. If the Intel XDK does not support Gradle you'll have to either use an older version of the plugin, 1.2.3, or ask Intel for support.

**Comment by macdonst** [comment]
@tassyo the IntelXDK build service does not include Google Play Services so you will need to build locally or use version 1.2.3 of this plugin.

**Comment by tassyo** [comment]
where obtain version 1.2.3

**Comment by tassyo** [comment]
@macdonst Okay, i will test and return sucess or fail,  thank you so much!
