### ISSUE TITLE
Error installing phonegap-push plugin to an existing Ionic app that has firebase-analytics plugin already installed (see steps to replicate issue)

### ISSUE THREAD

**Issue by nachiketkmaat** [phonegap/phonegap-plugin-push#2690]
### Expected Behaviour
Ionic phonegap push should get installed without any error

### Actual Behaviour
Ionic phonegap push does not get installed due to an error
![image](https://user-images.githubusercontent.com/47029078/51743528-ec32b080-20c2-11e9-8778-05e23ea112a2.png)

#### Steps to Reproduce 
Steps:

Run -> ionic start TestP
Go to TestP folder
Run -> ionic cordova plugin add cordova-plugin-firebase-analytics
Run -> npm install --save @ionic-native/firebase-analytics
Run -> ionic cordova platform add android
Run -> ionic cordova plugin add phonegap-plugin-push

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Environment:
Node: v10.14.1
Ionic: v4.6.0
npm: 6.4.1
Angular CLI: 7.1.2
Angular: 5.2.11

#### Plugin version

    cordova plugin version 2.2.x

**Comment by macdonst** [comment]
@nachiketkmaat please ask questions about why it doesn't build using ionic on the ionic forums.
