### ISSUE TITLE
PhoneGap Build fails, "compileSdkVersion not specified" in the error log

### ISSUE THREAD

**Issue by mredbishop** [phonegap/phonegap-plugin-push#2692]
### Expected Behaviour
PhoneGap build builds the APK.

### Actual Behaviour
It doesn't, instead throwing "compileSdkVersion not specified" in the error log.

### Reproduce Scenario (including but not limited to)
Adding phonegap-plugin-push to my project immediately causes this. Taking it out builds fine.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5+

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Any

#### Cordova CLI version and cordova platform version
    PhoneGap build 7.1.2

#### Plugin version
    latest

This issue was raised previously but closed with no solution. It's obviously still there but difficult to reproduce for some reason. If there is any additional data I can provide to help?

**Comment by macdonst** [comment]
@mredbishop the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
