### ISSUE TITLE
conflicting with cordova-background-geolocation-lt

### ISSUE THREAD

**Issue by cissemy** [phonegap/phonegap-plugin-push#2693]
Hi,
My geolocation   cordova-background-geolocation-lt  stop working everytime install phonegap-plugin-push.
It happens on android devices.
I am using phonegap cli-7.1.0
Thanks

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
