### ISSUE TITLE
Service_not_available Android 4.4

### ISSUE THREAD

**Issue by CodingAnonymous** [phonegap/phonegap-plugin-push#2700]
### Expected Behaviour
Register the device push id

### Actual Behaviour
Doesn't call the register function on Android 4.4, just on Android 6.0 and higher (so the code is fine)
On Android 4.4 it calls the on error function with the error message: SERVICE_NOT_AVAILABLE

#### Platform and Version
Android 4.4.2

#### (Android) What device vendor
Samsung Galaxy S4

#### Cordova CLI version and cordova platform version

    cli version 8.1.1
    phonegap-andoid 7.1.2

#### Plugin version

    plugin version 2.2.3

#### Sample Code that illustrates the problem

        const push = PushNotification.init({
          android: {
            "senderID": "XXXXX"
          },
            browser: {
                pushServiceURL: 'http://push.api.phonegap.com/v1/push'
            },
          ios: {
            alert: "true",
            badge: "true",
            sound: "true",
            clearBadge: "true",
          },
          windows: {}
        });

        push.on('registration', function (data) {
          console.log('Push Reg: ' + data.registrationId);
        });

**Comment by osricwong** [comment]
Hi, @CodingAnonymous,

I got same issue, do you have any solutions?

Thanks.
