### ISSUE TITLE
push.js Not added to application template file(URGENT!!! My app has been removed!)

### ISSUE THREAD

**Issue by serenogur** [phonegap/phonegap-plugin-push#2711]
### Creating a push.js file in the plugin file when I create an application template in devextreme

Devextreme also creates the splashscreen plugin file when I create the application template, but the push.js file is not added

> 
**I'm writing plugin names in the config.xml file. I'm using the Create an application template command. creates a template file. There is splashscreen.js inside the template file but push.js does not come up. Unfortunately, my application does not work when I upload it to the phone.**

#### code written to plugin in config.xml file;
   <plugin name="cordova-plugin-splashscreen" onload="true" />
  <plugin name="phonegap-plugin-push" spec="~2.2.3">
    <variable name="SENDER_ID" value="xxxx" />
 </plugin>

My Config.xml file;
![configxml](https://user-images.githubusercontent.com/20146414/52886505-8a2b0f80-3185-11e9-9709-9ba0a766ccfa.PNG)
MY AppTemplate folder;
![apptemplatefolder](https://user-images.githubusercontent.com/20146414/52886565-c199bc00-3185-11e9-839e-d1e7bd43006d.PNG)

**Comment by omerkoseoglu** [comment]
I have the same problem. I'm bored now.

Turkish translation: DevExtreme’in taaaaaa

**Comment by serenogur** [comment]
plugin version 1.9.0 and phonegap version cli.6.5.0 when I publish my project is working properly. But the only shortage does not work in background notifications on Android 8.0.0 versions.
This is a big problem for me.
To eliminate this, I upgraded the phonegap version to 7.1.0 and the plugin version to 2.1.0. However, this way when I install the phonegap builder a google-service.json file can not be found says. The google_service.json file is found in the main directory of the project. But is not publish.

**Comment by serenogur** [comment]
Hi, my problem is solved. The application was a distress caused by the directory structure I sent during the installation of the phonegap builder.
