### ISSUE TITLE
Unable to build due to `version of the google-services` conflict

### ISSUE THREAD

**Issue by john-doherty** [phonegap/phonegap-plugin-push#2716]
### Expected Behaviour

Build project in Android Studio

### Actual Behaviour

Build fails with error:

`Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.8.0`

### Reproduce Scenario (including but not limited to)

Attempt to build the project in Android Studio after running `cordova plugin add phonegap-plugin-push`

#### Cordova CLI version and cordova platform version

    cordova --version                                    # 8.0.0
    cordova platform version android          # 7.1.4

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # 2.2.3

**Comment by VitorAndrioli** [comment]
Above the error message you pasted here, you'll probably find something like

> Found play-services-identity:11.8.0, but version 11.6.2 is needed for the google-services plugin.
> Found play-services-auth:11.8.0, but version 11.6.2 is needed for the google-services plugin.
> Found play-services-analytics:11.0.1, but version 11.6.2 is needed for the google-services plugin.

I followed the instructions [here](https://stackoverflow.com/a/54196698/6286159) to update what the messages above was indicating needed a different version.

Not sure it's the best solution, but it worked for me here.

**Comment by brad** [comment]
I can confirm the workaround suggested by @VitorAndrioli works. I had this error:
> Found play-services-analytics:11.0.1, but version 11.6.2 is needed for the google-services plugin.


I opened `platforms/android/project.properties` and changed this line:
```
cordova.system.library.1=com.google.android.gms:play-services-analytics:11.0.1
```

to this:
```
cordova.system.library.1=com.google.android.gms:play-services-analytics:11.6.2
```

and the build works now!

**Comment by john-doherty** [comment]
Thanks @VitorAndrioli, that solved the problem
