### ISSUE TITLE
Phonegap can't get iOS push notification on device

### ISSUE THREAD

**Issue by linkas45** [phonegap/phonegap-plugin-push#272]
I'm building a Cordova hybrid application, which uses push notification plugin - https://github.com/phonegap/phonegap-plugin-push. For Android part I use gcm and for iOS I use APNs. Everything works with Android devices. I can send APN to server and it shows that everything is okay, but I can't get it on my iPhone device. I can get iPhone registration id and I send my notification directly to that device, but function, which is responsible for handling notification, doesn't react. I also tried to re-install the plugin, but that didn't help.

How I am receiving my notification in js:
```javascript
    var push = PushNotification.init({
        "android": {
            "senderID": "xx"
        },
        "ios": {"alert": "true", "badge": "true", "sound": "true"}, 
        "windows": {} 
    });

    push.on('registration', function(data) {
        //I can get registration id here
        alert(JSON.stringify(data));
    });

    push.on('notification', function(data) {
        //this place doesn't work
        alert("notification event");
        alert(JSON.stringify(data));
    });

    push.on('error', function(e) {
        alert("push error");
   });
```
This is how I send my notification to server in php:
```php
$deviceToken = 'xxx';
$passphrase = 'xx';
$message = 'My first push notification!';
$ctx = stream_context_create();
stream_context_set_option($ctx, 'ssl', 'local_cert', 'ck.pem');
stream_context_set_option($ctx, 'ssl', 'passphrase', $passphrase);
$fp = stream_socket_client(
    'ssl://gateway.sandbox.push.apple.com:2195', $err,
    $errstr, 60, STREAM_CLIENT_CONNECT|STREAM_CLIENT_PERSISTENT, $ctx);

if (!$fp)
    exit("Failed to connect: $err $errstr" . PHP_EOL);
echo 'Connected to APNS' . PHP_EOL;
$body['aps'] = array(
    'alert' => $message,
    'sound' => 'default'
    );
$payload = json_encode($body);
$msg = chr(0) . pack('n', 32) . pack('H*', $deviceToken) . pack('n', strlen($payload)) . $payload;
$result = fwrite($fp, $msg, strlen($msg));
if (!$result)
    echo 'Message not delivered' . PHP_EOL;
else
    echo 'Message successfully delivered' . PHP_EOL;
fclose($fp);
```
This outputs that 'Message successfully delivered'. Is there a chance that this doesn't work on iOS 9? (I have tested just on one device) Maybe there are some other ideas why it doesn't work?

**Comment by macdonst** [comment]
@linkas45 I've tested iOS 9 support on two separate devices with no issues. Debugging push on iOS is hard. Did you make sure that your app is using the same cert (both development) as the server?

**Comment by bmwsedee** [comment]
Same here, tested on a number of iOS 9 devices without any problems. Did
notice that Apple doesn't truly support push notifications on a simulated
device, you will need a physical device to test the notifications.
I've also noticed the app loggs some stuff to the output part of xCode when
running the code on a device; are there any errors found there?

On Wed, Oct 28, 2015 at 4:08 PM linkas45 <notifications@github.com> wrote:

> I'm building a Cordova hybrid application, which uses push notification
> plugin - https://github.com/phonegap/phonegap-plugin-push. For Android
> part I use gcm and for iOS I use APNs. Everything works with Android
> devices. I can send APN to server and it shows that everything is okay, but
> I can't get it on my iPhone device. I can get iPhone registration id and I
> send my notification directly to that device, but function, which is
> responsible for handling notification, doesn't react. I also tried to
> re-install the plugin, but that didn't help.
>
> How I am receiving my notification in js:
>
>     var push = PushNotification.init({
>         "android": {
>             "senderID": "xx"
>         },
>         "ios": {"alert": "true", "badge": "true", "sound": "true"},
>         "windows": {}
>     });
>
>     push.on('registration', function(data) {
>         //I can get registration id here
>         alert(JSON.stringify(data));
>     });
>
>     push.on('notification', function(data) {
>         //this place doesn't work
>         alert("notification event");
>         alert(JSON.stringify(data));
>     });
>
>     push.on('error', function(e) {
>         alert("push error");
>    });
>
> This is how I send my notification to server in php:
>
> $deviceToken = 'xxx';$passphrase = 'xx';$message = 'My first push notification!';$ctx = stream_context_create();stream_context_set_option($ctx, 'ssl', 'local_cert', 'ck.pem');stream_context_set_option($ctx, 'ssl', 'passphrase', $passphrase);$fp = stream_socket_client(    'ssl://gateway.sandbox.push.apple.com:2195', $err,    $errstr, 60, STREAM_CLIENT_CONNECT|STREAM_CLIENT_PERSISTENT, $ctx);if (!$fp)    exit("Failed to connect: $err $errstr" . PHP_EOL);echo 'Connected to APNS' . PHP_EOL;$body['aps'] = array(    'alert' => $message,    'sound' => 'default'    );$payload = json_encode($body);$msg = chr(0) . pack('n', 32) . pack('H*', $deviceToken) . pack('n', strlen($payload)) . $payload;$result = fwrite($fp, $msg, strlen($msg));if (!$result)    echo 'Message not delivered' . PHP_EOL;else    echo 'Message successfully delivered' . PHP_EOL;fclose($fp);
>
> This outputs that 'Message successfully delivered'. Is there a chance that
> this doesn't work on iOS 9? (I have tested just on one device) Maybe there
> are some other ideas why it doesn't work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-plugin-push/issues/272>.
>
-- 

Met vriendelijke groet,
Ben Sedee
06-20883935

**Comment by brambogaerts** [comment]
I am having the exact same problem. Tested on iOS 9.0.2 and iOS 9.1, I've even generated new certificates and installed them. The registration works, but the `notification` event does not fire...

**Comment by danieltheodosius** [comment]
In my case, everytime I install the application, the notification setting in iOS 9.0.2 for the application is always off. So if I register the plugin when it is off, I would not get any notification.

I need to manually enable notification to the application before register the plugin in order to receive notification.

**Comment by linkas45** [comment]
Thank you @macdonst! I am not sure what but it was something wrong with certificates. I was completely sure that everything is okay with them but I re-done all the certificates stuff and now it works! Thanks once again, you saved my a day.

**Comment by brambogaerts** [comment]
@linkas45 could you define the exact steps you took to solve the issue? I was not able to fix it by regenerating certificates...

**Comment by linkas45** [comment]
@brambogaerts I followed this tutorial http://www.raywenderlich.com/32960/apple-push-notification-services-in-ios-6-tutorial-part-1 very very carefully, reading everything. I saved all the files into one folder (I think I might messed them with other files when the application wasn't working) and when I tested, the code was the same and notification came up
