### ISSUE TITLE
Open Specific View when Opening App from Notification

### ISSUE THREAD

**Issue by softBarbarian** [phonegap/phonegap-plugin-push#275]
Is there a way to Open Specific View when Opening App from Notification?

Thanks a lot

**Comment by macdonst** [comment]
@softBarbarian I think you basically want to do the same thing that is detailed in issue #81. You don't have to use a `url` you can use any key. You can decide how to redirect to a new view based upon incoming push notification data. Does this answer your question?

**Comment by macdonst** [comment]
Closing, no input for almost a month.
