### ISSUE TITLE
No Notification sound, When i manually turn on in notification setting than its play sound

### ISSUE THREAD

**Issue by sajal8759** [phonegap/phonegap-plugin-push#2754]
No Notification sound, When I manually turn on in notification setting than its play sound. How to turn on it automatically

**Comment by shyamal890** [comment]
I too am facing the same issue with Ionic 4 app.

**Comment by shyamal890** [comment]
I too am facing the same issue.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
