### ISSUE TITLE
Android: FCM (Firebase Cloud Messaging) Push notification not working in Cordova Android version 8.0.0 

### ISSUE THREAD

**Issue by bvk070** [phonegap/phonegap-plugin-push#2759]
### Expected Behaviour
Push notification should receive

### Actual Behaviour
Push notification is not received and showing below error
`{
    "multicast_id": 9219371754327097795,
    "success": 0,
    "failure": 1,
    "canonical_ids": 0,
    "results": [
        {
            "error": "MismatchSenderId"
        }
    ]
}`

#### Steps to Reproduce 
Corodva 9.0.0
Android 7.1.4
FCM Push notification is working well.

Corodva 9.0.0
Android 8.0.0
FCM Push notification is failing and giving "MismatchSenderId" error.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android P

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Emulator

#### Cordova CLI version and cordova platform version

    cordova --version                                               9.0.0
    cordova platform version android                     8.0.0

#### Sample Push Data Payload

POST: https://fcm.googleapis.com/fcm/send

**Headers:**
Content-Type: application/json
Authorization: key=AAAAHSYA0VE:APA91bExuGKBm9BWy1ZRPuo_abBi665cfa7IQ9QRoUHPCI7G2nj-xCcis-MZcqKEsH4ONthI26A4u0o1-0kO5Q79Lb9gMXc1Qyer0y9lqXBhgvoopbkGm-fWVYcpWe4LDGASX6bY4vn5

**Body JSON raw:**
{
 "to" : "ff5xPJWU0cA:APA91bE4HEftSTvi4-vNHmzHm9Ascwqnb5a_Lce6yI2PUFxLa7bi8EN5zx4fktYTXhsVV4tno9bYgh4GoVWYsjag36LmWFq93HLJlio1J4aMC9FuBVOlcvZJWn2XJNKxtAC00ImHzfpY",
 "collapse_key" : "type_a",
 "notification" : {
     "body" : "Body of Your Notification",
     "title": "Title of Your Notification"
 },
 "data" : {
     "body" : "Body of Your Notification in Data",
     "title": "Title of Your Notification in Title",
     "key_1" : "Value for key_1",
     "key_2" : "Value for key_2"
 }
}

#### Logs taken while reproducing problem

`{
    "multicast_id": 9219371754327097795,
    "success": 0,
    "failure": 1,
    "canonical_ids": 0,
    "results": [
        {
            "error": "MismatchSenderId"
        }
    ]
}`

**Comment by sulaymankhan** [comment]
@bvk070 Check this solution out https://github.com/phonegap/phonegap-plugin-push/pull/2369 or you can pull this fork https://github.com/Moghul/phonegap-plugin-push

**Comment by CSobol** [comment]
#2369 will fix this. Maybe one day the maintainers will actually accept the pull request.
