### ISSUE TITLE
'Registration' Event Not Firing (iOS)

### ISSUE THREAD

**Issue by jw8** [phonegap/phonegap-plugin-push#2764]
The "error" event is being triggered instead of the "registration" event.

    var push = PushNotification.init({
    android: {
    },
    browser: {
        pushServiceURL: 'http://push.api.phonegap.com/v1/push'
    },
    ios: {
        alert: "true",
        badge: "false",
        sound: "false"
    },
    windows: {}
    });

    push.on('registration', function(data){
    console.log("registration event data: " + JSON.stringify(data));
    });

    push.on('notification', function(data){
    console.log("notification event data: " + JSON.stringify(data));
    });

    push.on('error', function(e){
    console.log("error event e: " + JSON.stringify(e));
    });

The error I receive is line:62, column:50 in push.js

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
