### ISSUE TITLE
Question APN message format

### ISSUE THREAD

**Issue by colonna-mike** [phonegap/phonegap-plugin-push#277]
First I apologizes if this is the wrong forum for this.

For android I have a PHP message array setup like this (works great)

	$msg = array
	(
	       'title'			=> $title,
		'message' 		=> $message,
		'image'         	=> $image,
		'userid'  		=> $userid,
		'familyid'  		=> $familyid,
		'postid'  		=> $postid,
		'type'  		=> $type,
		'notId'        	 	=> $postid,
		'postuserid'   		=> $postuserid,
		'commentid'             => $commentid,
		'additionalData'        =>  array(
		        'userid'      => $userid,
		        'familyid'    => $familyid,
		        'postid'      => $postid,
		        'type'        => $type,
		        'postuserid'  => $postuserid,
		        'commentid'   => $commentid
		    )
		
	);

But for apple I'm a little confused  on how to add the additionalData to the APN payload.
Looking at the apple docs now. but still a little confused. if anyone as gotten this to work could you share the payload PHP array?.

here is what I have so far:

    $payload['aps'] = array(
                            	   'alert' =>  array(
                                    'title' => $title,
                                    'body '  => $message,
                                    'content-available1': '1',
                                    'badge' => '1', 
                                    'sound' => 'default',
                                    'additionalData'           =>  array(
                                  		        'userid'         => $userid,
                                  		        'familyid'       => $familyid,
                                  		        'postid'         => $postid,
                                  		        'type'           => $type,
                                  		        'postuserid'     => $postuserid,
                                  		        'commentid'      => $commentid
                                  		    )
                                ) 
                            
                            
                           );

**Comment by macdonst** [comment]
@colonna-mike any key you put in the `aps` array will be put in `data.additionalData`. I just try and make sure that all the cross platform keys like `message` and `title` are available right from `data`. 

So using your PHP as an example as the base:

```
$payload['aps'] = array(
                               'alert' =>  array(
                                    'title' => $title,
                                    'body '  => $message
                               ),
                               'content-available': '1',
                               'badge' => '1', 
                               'sound' => 'default',
                               
                               'userid'         => $userid,
                               'familyid'       => $familyid,
                               'postid'         => $postid,
                               'type'           => $type,
                               'postuserid'     => $postuserid,
                               'commentid'      => $commentid
                            );
```

One thing I noticed is that your `alert` array accidentally added everything in it but it should only have the `title` and `body` as per https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html#//apple_ref/doc/uid/TP40008194-CH100-SW1

Second your `content-available` property was mis-spelled.

Anyway, sending that data from PHP should get your `on('notification')` handler called with the following JSON:

```
{
    title: $title,
    message: $message,
    sound: 'default',
    count: '1',
    additionalData: {
        userid: $userid,
        familyid: $familyid,
        postid: $postid,
        type: $type,
        postuserid: $postuserid,
        commentid: $commentid,
        content-available: '1'
    }
}
```

Make sense?

**Comment by colonna-mike** [comment]
Yes it does thank you! And thank you for this plugin....

**Comment by macdonst** [comment]
@colonna-mike de nada, going to close now. Re-open if there are issues with this.
