### ISSUE TITLE
Update cordova-support-google-services

### ISSUE THREAD

**Issue by jpike88** [phonegap/phonegap-plugin-push#2779]

**Comment by mateusduraes** [comment]
Can you guys please create a release?

The last commit was in **dec 2018**, but the last release was in **may 2018**... and we also have the cordova-support-google-services update commited in **july 2018**

**Comment by andreag-incomedia** [comment]
> Can you guys please create a release?
> 
> The last commit was in **dec 2018**, but the last release was in **may 2018**... and we also have the cordova-support-google-services updated committed in **july 2018**

without this it is not possible to implement lasted version of plugin "Firebase Analytics"

**Comment by thearaks** [comment]
Please make a release with an updated _cordova-support-google-services_ version!
**This has become a blocking issue and needs to be solved ASAP!**

**Comment by jpike88** [comment]
@purplecabbage can someone from PhoneGap definitively weigh in here?

**Comment by thearaks** [comment]
@purplecabbage @jpike88 Any news on this?
Should we tag someone else like _macdonst_ who made the last releases?
