### ISSUE TITLE
Get notification into ionic app after clearing app data from setting

### ISSUE THREAD

**Issue by krunal9421** [phonegap/phonegap-plugin-push#2785]
I am using ionic native push notification for sending a notification into an app using firebase. But when I clear app data of my app from setting page, still I am getting notification into my mobile.

Can anyone help me out with this?

**Comment by urlexnilz** [comment]
Use .unregister() like this:

				this.pushObject.unregister().then(
					() => {
						console.log('successfully unsubscribed from ALL topics (deleted data)');
					},
					e => {
						console.log('error during "unsubscription" from ALL topics (deleted data): ' + JSON.stringify(e));

					}
				);
