### ISSUE TITLE
Question: iOS not running push.on('notification') code

### ISSUE THREAD

**Issue by inferno1005** [phonegap/phonegap-plugin-push#279]
I am having trouble getting the iOS version of my ionic app to run custom code whenever a push notification comes through. 

I am receiving the push, and it is showing up in the notification shade. 
I'm using ionic's push platform (it is in alpha) documented here 
http://docs.ionic.io/docs/push-sending-push

The curl request I am sending is 
`curl -u PRIVATE_KEY_HERE: -H "Content-Type: application/json" -H "X-Ionic-Application-Id: APP_ID_HERE" https://push.ionic.io/api/v1/push -d '{"tokens": ["TOKEN_HERE"],"production": false, "notification":{  "alert":"asdf", "title": "asdfsadf", "android": {"payload": {}}, "ios": { "badge":0,   "content-available":"1"}}}'
`
I have tried different json with this curl request and it doesn't seem to change the problem. `

The same  code is working on android, so I feel like it is some strangeness going on with iOS. 
Any ideas would be much appreciated!

**Comment by macdonst** [comment]
@inferno1005 What version of the plugin are you using? 

When you send the notification when the app is in the foreground is the `push.on('notification')` event handler being run? If so can you look at `data.additionalData.content-available` to see if it is set.

**Comment by inferno1005** [comment]
@macdonst The latest version 1.4.0, yes when the app is in the foreground the `push.on('notification')` event handler is being run. 
The contents of the whole data variable in the notification handler is
` {count: 0, additionalData: {foreground: true}, message: "asdf"}`

**Comment by macdonst** [comment]
@inferno1005 well there is the problem. The `content-available` property doesn't seem to be getting through. If it doesn't arrive on the device then there is no signal for iOS to wake up the app and run the `notification` event. 

If you look at the docs you linked Ionic seems to use `"contentAvailable": true` instead of `content-available: 1`. Can you try with that and report back.

**Comment by inferno1005** [comment]
switching to `"contentAvailable":true` yields the exact same results as the `"content-available":1` . Pretty much every combination of content available has been tested, and none of them get through to the data object.

**Comment by peterschmidler** [comment]
I have a similar issue. When the app is in foreground, everything works as expected. When the app is in background or closed the notification doesn't get through, though. My payload looks like this 
![image](https://cloud.githubusercontent.com/assets/234022/10847414/8de359cc-7f16-11e5-8706-2fa895591bc5.png)

**Comment by macdonst** [comment]
@peterschmidler are you using Ionic as well for sending your push?

**Comment by peterschmidler** [comment]
@macdonst No I'm sending directly via apn.

**Comment by peterschmidler** [comment]
Actually it stopped working a few weeks ago while using https://github.com/phonegap-build/PushPlugin I switched to this plugin, but the problem remained.

**Comment by macdonst** [comment]
@peterschmidler then it seems to problem wouldn't be with the plugin but the way in which you are sending the notification.

**Comment by peterschmidler** [comment]
Possibly. It seems that the issue appeared after upgrading xCode (I'm on 7.1 now).

**Comment by macdonst** [comment]
@peterschmidler you might want to update your certs and mobile provisioning profiles.

**Comment by peterschmidler** [comment]
I'll try that. Thanks.

**Comment by ericb** [comment]
@inferno1005 content available needs to be sent as `contentAvailable: 1` in the `ios` specific portion of the request data. Here is an example:

```javascript
{
  "alert": "test message",
  "ios": {
    "contentAvailable": 1
  }
}
```

**Comment by macdonst** [comment]
Closing, no input for almost a month.

**Comment by andreyavram** [comment]
Hi,
How about sending "content-available" to Android? The flag doesn't seem to get through.. Tried every combination above.
Thanks!
