### ISSUE TITLE
phonegap-plugin-push and firebase-analytics are not compatible together

### ISSUE THREAD

**Issue by rphiller** [phonegap/phonegap-plugin-push#2796]
### Expected Behaviour

That you can install both together in same Project.

### Actual Behaviour

Firstly both plugins depend on same plugin: "cordova-support-google-services"
"phonegap-plugin-push" needs "cordova-support-google-services@~1.1.0"
"firebase-analytics" needs "cordova-support-google-services@^1.3.0"

Secondly after installing one of them, no matter which, there comes this error (in my case on firebase)

> Installing "cordova-plugin-firebase-analytics" for ios
> Running command: pod install --verbose
> Failed to install 'cordova-plugin-firebase-analytics': Error: pod: Command failed with exit code 1

Has anyone have done simiular expecience?

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

cordova-android: ^8.0.0
cordova-ios: ^5.0.1
cordova: 9.0.0

#### Plugin version

phonegap-plugin-push 2.2.3 
cordova-plugin-firebase-analytics: 3.0.0

**Comment by ConnorMcGill** [comment]
I'm dealing with the exact same problem myself, any luck finding a solution?

**Comment by evezzaro** [comment]
please keep me posted. we need this fix urgent. thanks

**Comment by Greg4572** [comment]
Hey, i dont know if this will help you but i also had an issue where different plugins where installing different versions of "cordova-support-google-services" during the build process. I found these 3 plugins that "force" cordova-support-google-services onto a single version which solved my issue. 

[cordova-android-support-gradle-release](https://www.npmjs.com/package/cordova-android-support-gradle-release)
[cordova-android-firebase-gradle-release](https://www.npmjs.com/package/cordova-android-firebase-gradle-release?activeTab=readme)
[cordova-android-play-services-gradle-release](https://github.com/dpa99c/cordova-android-play-services-gradle-release)

I hope this helps.

**Comment by evezzaro** [comment]
Hi guys, I tried the solution @Greg4572 proposed, but i couldn't get this plugins to work with Firebase. Do you guys have any news about this?

System Info:

Ionic:

   ionic (Ionic CLI) : 4.12.0 (/Users/elevasrl/.nvm/versions/node/v11.9.0/lib/node_modules/ionic)
   Ionic Framework   : ionic1 1.3.4
   @ionic/v1-toolkit : 1.0.22

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0, ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 36 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/elevasrl/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v11.9.0 (/Users/elevasrl/.nvm/versions/node/v11.9.0/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 11.0 Build version 11A420a


The output i get on building is this:


Task :app:compileDebugJavaWithJavac FAILED
/Users/elevasrl/Desktop/GITHUB/YachtNeeds-App/platforms/android/app/src/main/java/com/adobe/phonegap/push/PushPlugin.java:15: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat
  location: package android.support.v4.app
/Users/elevasrl/Desktop/GITHUB/YachtNeeds-App/platforms/android/app/src/main/java/com/adobe/phonegap/push/PushPlugin.java:16: error: cannot find symbol
import android.support.v4.app.NotificationManagerCompat;
                             ^
  symbol:   class NotificationManagerCompat
  location: package android.support.v4.app
/Users/elevasrl/Desktop/GITHUB/YachtNeeds-App/platforms/android/app/src/main/java/com/adobe/phonegap/push/FCMService.java:26: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat
  location: package android.support.v4.app
/Users/elevasrl/Desktop/GITHUB/YachtNeeds-App/platforms/android/app/src/main/java/com/adobe/phonegap/push/FCMService.java:27: error: package android.support.v4.app.NotificationCompat does not exist
import android.support.v4.app.NotificationCompat.WearableExtender;
                                                ^
/Users/elevasrl/Desktop/GITHUB/YachtNeeds-App/platforms/android/app/src/main/java/com/adobe/phonegap/push/FCMService.java:28: error: cannot find symbol
import android.support.v4.app.RemoteInput;
                        

...... MORE ......

Do you guys have any other solutions for this?

Thanks,

**Comment by Aggror** [comment]
@Greg4572 Would you mind sharing the config.xml part where your plugins/version/engine tags are listed? Thanks in advance.

**Comment by Greg4572** [comment]
@Aggror I have attached my config.xml in a text file as i cant seem to be able to post it as a comment. Sorry if it looks like a mess, but it works so i try not to mess with it to much. I hope this helps you in some way.
[GithubComment.txt](https://github.com/phonegap/phonegap-plugin-push/files/3761366/GithubComment.txt)

**Comment by Aggror** [comment]
@Greg4572 First of: thank you for responding. That is always appreciated.
With your changes my app suddenly build, but unfortunately the window.FirebasePlugin remains null when starting my app. Still, no build errors is already an improvement.

**Comment by Greg4572** [comment]
@Aggror Great, I'm glad i could help out in some form. As for the window.FirebasePlugin issue you are experiencing, I haven't used the Firebase Plugin before so i cant help much with that. What i can suggest, is that if you are trying to access it on launch, make sure the device is ready before trying to call it. I hope you are able to find a solution for this.
