### ISSUE TITLE
Question: about Led in Notifications

### ISSUE THREAD

**Issue by arthur791004** [phonegap/phonegap-plugin-push#280]
Hi, 
I set Led in Notifications in push notification object, but my app received without led...
Do I have to do other things? My android version is 4.2.2

Thanks

**Comment by macdonst** [comment]
@arthur791004 does you device have an LED? I know it's a dumb question but just need to check.

**Comment by arthur791004** [comment]
Yes, my device is LG G2 and it can receice LED from line, FB and so on.

**Comment by arthur791004** [comment]
sorry, I found my LED config had been turned off sometime but I forgot.
close this issue, thanks
