### ISSUE TITLE
Plugin fails to install with error: Failed to install 'phonegap-plugin-push': CordovaError: Cannot find plugin.xml for plugin "cordova-support-google-services".

### ISSUE THREAD

**Issue by deepakrout** [phonegap/phonegap-plugin-push#2815]
### Expected Behaviour
cordova plugin add phonegap-plugin-push --save ; should install the plugin 

### Actual Behaviour
Throwing error: 

`Failed to install 'phonegap-plugin-push': CordovaError: Cannot find plugin.xml for plugin "cordova-support-google-services". Please try adding it again.
    at new PluginInfo (/Users/der9078/.nvm/versions/node/v10.12.0/lib/node_modules/cordova/node_modules/cordova-common/src/PluginInfo/PluginInfo.js:422:15)
    at installDependency (/Users/der9078/.nvm/versions/node/v10.12.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:510:26)
    at /Users/der9078/.nvm/versions/node/v10.12.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:403:36
    at process._tickCallback (internal/process/next_tick.js:68:7)
Failed to restore plugin "phonegap-plugin-push" from config.xml. You might need to try adding it again. Error: Cannot find plugin.xml for plugin "cordova-support-google-services". Please try adding it again.
`

### Reproduce Scenario (including but not limited to)
cordova plugin add phonegap-plugin-push --save

### Environment Versions

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

global packages:

    cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1) 

local packages:

    @ionic/app-scripts : 3.2.3
    Cordova Platforms  : android 8.0.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.2 
    ios-sim           : 8.0.2 
    Node              : v10.12.0
    npm               : 6.4.1 
    OS                : macOS
    Xcode             : Xcode 10.3 Build version 10G8 

Misc:

    backend : pro

#### Plugin version
   2.2.0
    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by pabloleone** [comment]
Remove the plugin folder `cordova-support-google-services` and the execute again `ionic cordova prepare`. The system will calculate the dependencies again and install the right version.

**Comment by deepakrout** [comment]
Thank you for the response! This was a strange problem. Happened only one particular branch of the project. Other branches seem to be fine. I am closing this issue.

**Comment by frrodriguez** [comment]
That solution don`t works for me...
In my case i have the plugin-push dependency by commit hash.

When i do `cordova prepare` my output is:
`Installing "phonegap-plugin-push" for android
Failed to install 'phonegap-plugin-push': CordovaError: Cannot find plugin.xml for plugin "cordova-support-google-services". Please try adding it again.`
...
`Failed to restore plugin "phonegap-plugin-push" from config.xml. You might need to try adding it again. Error: Cannot find plugin.xml for plugin "cordova-support-google-services". Please try adding it again.`

And when i go to the `cordova-support-google-services` plugin project folder just contains a `.project` file

I solved it seeing the dependency used in the plugin and adding it manually to my config.xml:



    <plugin name="cordova-support-google-services" spec="~1.2.0" /> 
    <plugin name="phonegap-plugin-push" spec="https://github.com/phonegap/phonegap-plugin-push#87ded60288958eba250a89f92b696b89287c8706">

And then when i run `cordova prepare` the output is:
`Plugin dependency "cordova-support-google-services@1.2.1" already fetched, using that version.`

And it works now
