### ISSUE TITLE
phonegap plugin push + Cordova AdMob plugin error more than one library.

### ISSUE THREAD

**Issue by YeltsinReyes** [phonegap/phonegap-plugin-push#283]
I am using these two together plugin and I get the following error:
"Error more than one library wirh package name com.google.android.gms"
how I can fix this?

**Comment by ivanthecrazy** [comment]
+1
:processArmv7DebugManifest
/Users/IvanTheCrazy/Projects/ScratchItUp/platforms/android/AndroidManifest.xml:14:66 Error:
	Attribute meta-data#com.google.android.gms.version@value value=(7327000) from AndroidManifest.xml:14:66
	is also present at com.google.android.gms:play-services-basement:8.1.0:23:13 value=(@integer/google_play_services_version)
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:14:9 to override
:processArmv7DebugManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugManifest'.
> Manifest merger failed : Attribute meta-data#com.google.android.gms.version@value value=(7327000) from AndroidManifest.xml:14:66
  	is also present at com.google.android.gms:play-services-basement:8.1.0:23:13 value=(@integer/google_play_services_version)
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:14:9 to override

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by macdonst** [comment]
@YeltsinReyes @ivanthecrazy URL to the admob plugin you are using? I'm pretty sure the problem is they are including a dependency to google play services incorrectly. Let me know the plugin so I can send them a PR.

**Comment by YeltsinReyes** [comment]
@macdonst This is the plugin that I'm using https://github.com/appfeel/admob-google-cordova/

**Comment by macdonst** [comment]
@YeltsinReyes I open a PR on it: 

https://github.com/appfeel/admob-google-cordova/pull/32

**Comment by ivanthecrazy** [comment]
@macdonst I'm using this one: https://github.com/admob-google/admob-phonegap

**Comment by macdonst** [comment]
@ivanthecrazy sent a PR for that repo as well.

https://github.com/admob-google/admob-phonegap/pull/2

**Comment by ivanthecrazy** [comment]
Thanks @macdonst
