### ISSUE TITLE
1.4.0 version from PGB that build error only in Android

### ISSUE THREAD

**Issue by bau720123** [phonegap/phonegap-plugin-push#284]
hi @macdonst 
I am using PGB cli 5.2.0 + only your 1.4.0 version plugin (no other 3rd plugin installed)
for now the build for Android have another wrong message
![2015-10-30_165538](https://cloud.githubusercontent.com/assets/5110085/10841766/1b9e4eb0-7f27-11e5-9ee9-3874ff1771f0.jpg)
![2015-10-30_165706](https://cloud.githubusercontent.com/assets/5110085/10841781/47e629de-7f27-11e5-83ce-386641403cc9.jpg)

**Comment by CoachRDeveloper** [comment]
+1, having the same problem. Version 1.3.0 works btw...

**Comment by evgd** [comment]
+1

**Comment by frederikbosch** [comment]
+1

**Comment by macdonst** [comment]
Awesome, this worked two days ago but as of this morning I can reproduce. I will talk to the PGB team.

**Comment by frederikbosch** [comment]
Also confirm that 1.3.0 indeed works. It is 1.4.0 specifically.

**Comment by macdonst** [comment]
Yes, I know what the problem is. Moving to Google Play Services framework in 1.4.0 instead of including the gcm.jar has caused the issue. Talking to PGB team as they come online.

**Comment by bau720123** [comment]
thanks @macdonst 
waiting for your good news...

**Comment by bau720123** [comment]
hi @macdonst 
good news
for now Android build success again
I am worry about if someday will build fail again XD
anyway...close this issue first
if happen again，I will post a new one

**Comment by macdonst** [comment]
@bau720123 yeah, the build team resolved this for us.
