### ISSUE TITLE
Integrate push notification in phonegap build

### ISSUE THREAD

**Issue by JayTh** [phonegap/phonegap-plugin-push#285]
I am trying to set push notification in phonegap build app using <a href="https://wordpress.org/plugins/push-notifications-for-wp/" >Push Notifications for WordPress (Lite) plugin</a>.

I did like this example <a href="https://github.com/phonegap/phonegap-plugin-push/tree/master/example" >phonegap-plugin-push</a>.

I moved all the files of server directory to www and made a app build. From that build I am getting registration id from index.js file. I had putted senderID, client key and client secure key into the app build.

Now I want to put that registration id into pushADM.js file but I am getting undefined value because pushADM.js runs before index.js.

so could anyone please suggest me some ways to handle the file execution.

Thanks.

**Comment by maxlinux2000** [comment]
Please, could you help me? I have the same problem.
Here you can see a working example of an ionic app working perfectly with the  Push Notifications for WordPress (Lite) plugin. http://wphc.julienrenaux.fr/ 

But My app is not using angularjs.

Do you resolve this problem?
