### ISSUE TITLE
iOS: No notification if app closed

### ISSUE THREAD

**Issue by kaynz** [phonegap/phonegap-plugin-push#286]
Hi,

I just installed 1.4.0 of this plugin but unfortunately notifications are not shown (iOS related notifications, not JS related). Receiving push messages is working since I get console output if app is running.

I'm initializing the plugin with following code:

PushNotification.init({
          android: {senderID: id, icon: 'icon'},
          ios: {alert: true, badge: true, sound: true}
        });

all notifications are allowed in the in-iOS-app-settings.

anyone who has the same problem or even better: a fix?

**Comment by macdonst** [comment]
@kaynz so when you say closed do you mean the app is in the back ground or do you mean force closed from the task switcher?

**Comment by kaynz** [comment]
I tried both. Same result.

**Comment by kaynz** [comment]
Didnt mean to close this.

**Comment by inferno1005** [comment]
What does your payload look like?

**Comment by colonna-mike** [comment]
same here my from my ipad but I'm using 1.2.4 not 1.4 here the payload beging sent:

 {"aps":{"alert":{"title":"Mikes Test","body ":"Cole Colonna Added a new post"},"content-available":1,"badge":"1","sound":"default","userid":"114","familyid":"107","postid":"2102","type":"post","postuserid":"114","commentid":""}}

**Comment by macdonst** [comment]
@colonna-mike background notifications on iOS weren't introduced until version 1.4.0. In your case on 1.2.3 this will add a notification to the shade but not call your `on('notification')` event handler.

**Comment by colonna-mike** [comment]
@macdonst that's good to know I'll try to update but I'm not even getting the shade. But this is old version I'm using I'll update but had have issue trying to get the plugin complied. that's why I'm still wai on the old versions.

**Comment by kaynz** [comment]
My payload:
{"aps":{"alert":"xxxxx","sound":"default","category":"msg"}}

**Comment by kaynz** [comment]
I just noticed that my

_pushNotification.on('registration', function (data) {}

is never being called on iOS

**Comment by kaynz** [comment]
Retested, same error. iOS 9 btw.

**Comment by macdonst** [comment]
@kaynz it sounds like you are not setup correctly to receive notifications if you never get the 'registration' event. Do you ever get the pop up asking to allow notifications?

**Comment by kaynz** [comment]
@macdonst my setup is very simple and works pretty good on android.

Just found this in my xcode log:

2015-11-05 15:47:10.367 app[828:573908] Push Plugin register called
2015-11-05 15:47:10.367 app[828:573908] PushPlugin.register: setting badge to false
2015-11-05 15:47:10.368 app[828:573908] PushPlugin.register: clear badge is set to 0
2015-11-05 15:47:10.384 app[828:573646] Push Plugin register failed

The JS output of following is empty (it prints Error {] in Safari)

_push.on('error', function (e) {
          console.warn(e);
        });

**Comment by colonna-mike** [comment]
@macdonst  just more info . For my iPad I get the notification I'd and i  get the message to allow notifications on the IPad.  I have check to make sure that the notification settings is on in the iPad preferences. But no notification shows. Not sure if this helps
.

**Comment by kaynz** [comment]
@macdonst any news on this? Do you need further informations from me?

**Comment by colonna-mike** [comment]
@macdonst just tested 1.4.3 and not getting any notification? I'm now wondering  if its my payload:

{"aps":
 {"alert":{
 "title":"Carol And Mikes",
 "body ": "Mike added a comment to a post"
}, "content-available":1,
 "badge":"1",
 "sound":"default",
 "userid":"87",
 "familyid":"89",
 "postid":"2312",
 "type":"comment",
 "postuserid":"87",
 "commentid":"1284"}
 }

thanks for your help

**Comment by karthikeyan-perpetua** [comment]
@kaynz 

I'm also facing the same issue .

Push Plugin register called
PushPlugin.register: setting badge to false
PushPlugin.register: clear badge is set to 0
Push Plugin register failed

I'm waiting for your response.

Thanks in advance

**Comment by ianisted** [comment]
I'm getting this very error. Not sure what I've done wrong. Currently testing in the simulator using example code. Init and set badge number, it's causing problems.

Do I _need_ to unregister notifications after use?

**Comment by kaynz** [comment]
@ianisted emulator is not supported

**Comment by kaynz** [comment]
btw. my solution was to execute rm -rf plugins/ before adding platform. So every platform rm forces me to rm -rf plugins/ - otherwise this plugin is not installed in my ios project =/
I made a grunt task which simplifies this for me.
