### ISSUE TITLE
Push notification in IPad with IOS 9.3.4 is not working

### ISSUE THREAD

**Issue by tgmitra1978** [phonegap/phonegap-plugin-push#2862]
### Expected Behaviour
Expecting to receive push notification same as other latest version of IOS

### Actual Behaviour
Not receiving any notification on IPAD with IOS 9.3.4

### Reproduce Scenario (including but not limited to)
Just use the app on IPAD 9.3.4

#### Steps to Reproduce 
Run the app and then send push notification, all other OS version ( 12+) and Android any version notification working except on this

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
IOS 9.3.4

#### Cordova CLI version and cordova platform version

    cordova --version                                    
    9.0.0 (cordova-lib@9.0.1)
    
   cordova platform version android                     
Installed platforms:
  android 8.0.0
  ios 5.0.1
Available platforms: 
  browser ^6.0.0
  electron ^1.0.0
  osx ^5.0.0
  windows ^7.0.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   
    phonegap-plugin-push 2.3.0 "PushPlugin"

**Comment by jcesarmobile** [comment]
2.3.0 doesn't support iOS 9.
It should have been 3.0.0 and it should have documented that iOS 9 wasn't supported. I reported that long ago.
https://github.com/phonegap/phonegap-plugin-push/issues/2835
