### ISSUE TITLE
Cannot get device token

### ISSUE THREAD

**Issue by chris087** [phonegap/phonegap-plugin-push#287]
Previous version had a function to get device token, its gone.. So this plugin is unusable? Because device token is required.. ! (Ios)

**Comment by chris087** [comment]
Its now called the Registration ID ! (for other users, who are confused..

push.on('registration', function(data) {
            console.log("registration event");
            console.log(data);
            
    });

**Comment by macdonst** [comment]
Is this a problem or can I just close this?

**Comment by chris087** [comment]
Can be closed, but I was confused, because the device token is now called " Registration ID" )..
