### ISSUE TITLE
Cordova will all build fail that only in Android

### ISSUE THREAD

**Issue by chetanahire00** [phonegap/phonegap-plugin-push#288]
Hello sir,
I am trying to build app after phonegap-plugin-push this plugin installation.then give following app build timing error for android platform.

 
![pushpluginerror](https://cloud.githubusercontent.com/assets/8254087/10864136/1cebdb64-800a-11e5-9565-42183087ddc9.png)

**Comment by macdonst** [comment]
@chetanahire00 https://github.com/phonegap/phonegap-plugin-push#compiling
