### ISSUE TITLE
push.on("registration") is not fired on iOS 13.3.1

### ISSUE THREAD

**Issue by mgoetz85** [phonegap/phonegap-plugin-push#2881]
### Expected Behaviour
When initializing the plugin, the app asks for permissions and afterwards the method push.on("registration") is fired.

### Actual Behaviour
The app asks for permission but push.on("registration") is not fired under iOS 13.3.1

### Reproduce Scenario (including but not limited to)
Existing app which worked fine / as expected under iOS 13.3
Upon deviceready the plugin is called but push.on("registration") is not fired (it should have an alert(data.registrationId)). The same app works fine under iOS 13.3. 

#### Steps to Reproduce 
as described above

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 13.3.1

#### Cordova CLI version and cordova platform version
cli-9.0.0
PhoneGap Build

#### Plugin version
87a8132 (2.3.0)

#### Sample Code that illustrates the problem
`		push.on("registration", (data) => {
			deviceToken = data.registrationId;
			registerDevice(data.registrationId);
		});`

**Comment by mgoetz85** [comment]
I do not really know why, but it is working again although I did not change anything

**Comment by etiennea** [comment]
I have this! It is not firing from xcode but my appstore version is firing.
