### ISSUE TITLE
Token format IOS 13 

### ISSUE THREAD

**Issue by anhpt86** [phonegap/phonegap-plugin-push#2899]
Hi ,

I'm getting the incorrect ios token like this {length=32,bytes=0x2936b8f014b120c8b09287086dd5837f...bb1f7af2eb2ccea2}
with below enviroment. By some reason I have to work on Meteor version 1.2.4.7 and cannot upgrade version

#### Cordova CLI version and cordova platform version
    cordova --version : 7.1.0
    cordova platform version ios: 4.2.1

#### Plugin version
    cordova plugin version | grep phonegap-plugin-push: 1.8.4 - I have to work on this version by Meteor version

Have anyone get the same issue?

**Comment by nvjmul** [comment]
This is a problem I also had whilst working on ios 13 and my problem was fixed by updating the plugin to the latest version. Didnt find any other work around, I think ios 13 handles the tokens differently as to the previous ios versions, not sure but using the latest plugin definitely fixed it. :)

**Comment by jcesarmobile** [comment]
yeah, it was fixed in 2.3.0 version, so you have to update
