### ISSUE TITLE
iOS only reads out "aps" payload

### ISSUE THREAD

**Issue by boboldehampsink** [phonegap/phonegap-plugin-push#29]
Custom payloads that are siblings of `aps` are allowed by Apple and should be added to message.additionalData. Now only children of `aps` are allowed.

**Comment by boboldehampsink** [comment]
I think this is a bug rather than an enhancement. This is because you can't add additional data to the aps object at all, so additionalData won't work for iOS right now.

**Comment by macdonst** [comment]
@boboldehampsink Can you add in an example of the data you are sending that is not ending up in additionalData for me? Not adverse to switching this to a bug.

**Comment by boboldehampsink** [comment]
The [examples for JSON Payloads](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html#//apple_ref/doc/uid/TP40008194-CH100-SW15), i.e. the `acme2` example described, is not getting in additionalData

**Comment by macdonst** [comment]
@boboldehampsink kk, just wanted to make sure we are on the same page.

**Comment by macdonst** [comment]
Fixed for release 1.1.0

**Comment by boboldehampsink** [comment]
Awesome, thanks
