### ISSUE TITLE
Android 5.0 lockscreen notifications

### ISSUE THREAD

**Issue by shuyye** [phonegap/phonegap-plugin-push#290]
I'm sorry for opening a ticket on it, but I was wondering whether the plugin supports push notifications to lockscreen to Android 5.0+? Is there something in particular that needs to be done like adding some permission to androidManifest.xml or so?

It's an important feature for my client and that is the reason why i'm now migrating from the deprecated push notifications plugin, hoping that this feature is implemented with this plugin... 

I would be extremely grateful for any assistance, much thanks!

**Comment by macdonst** [comment]
Yes, notifications show up on the lock screen on Android 5.0. Please test it out and let me know if there is any missing functionality but I will close this for now.
