### ISSUE TITLE
Reregister on Android

### ISSUE THREAD

**Issue by Riesling11** [phonegap/phonegap-plugin-push#291]
Hi, I am using this cool plugin in version 1.4.0 and an Samsung S6 Edge Android 5.1.1 and have the following problem:

The first time everything worked as expected, then I tried to unregister via the unregister() function and than reregister a bit later by calling the init function again. Within the on-register event I got the same registrationId as before. When I am now sending a push notification to the GCM server via PHP I get the following error code: "NotRegistered". Killing and restarting the app doesnt work either, I always get the same registrationID as response from the on-register event and this registration seems to be marked as invalid somehow on the google-server-side. Any tips what I can to avoid this?

I need this unregister/register functionality to give users control in their app-settings to enable and disable push notifications whenever they like.

Thanks for your help,
Philipp

**Comment by macdonst** [comment]
@Riesling11 that's odd according to Google if you call:

`InstanceID.getInstance(getApplicationContext()).deleteInstanceID();` 

as per: 

https://developers.google.com/instance-id/guides/android-implementation#delete_tokens_and_product_names

then the next time you call `getInstance` then you should get a brand new Instance ID. Some investigation is warranted here.

**Comment by macdonst** [comment]
@Riesling11 well crap, I see my bug already. I should be able to fix this today or tomorrow and get a 1.4.1 out soon.

**Comment by macdonst** [comment]
@Riesling11 fixed in 1.4.1 which has been pushed to NPM

**Comment by Riesling11** [comment]
perfect - it works - thanks a lot
