### ISSUE TITLE
data.registrationId is empty string "" on register event callback

### ISSUE THREAD

**Issue by kentmw** [phonegap/phonegap-plugin-push#295]
For Android, I was receiving an empty string "" on the register callback. Everytime I initialized the plugin, it would consistently return an empty string. When I un-installed the app and re-installed it, I received an actual token.

I don't know why this would occur, but I wanted to report it. 

I think it has to do with the fact that register call in PushPlugin.java uses SharedPreferences to return a stored registration id. If, for some reason, both of the top two if statements fail in the following code block, it will just rely on (hope that there is) a stored registration id.

See PushPlugin.java:
```
// first time run get new token
if ("".equals(savedSenderID) && "".equals(savedRegID)) {
  token = InstanceID.getInstance(getApplicationContext()).getToken(senderID, GCM);
}
// new sender ID, re-register
else if (!savedSenderID.equals(senderID)) {
  token = InstanceID.getInstance(getApplicationContext()).getToken(senderID, GCM);
}
 // use the saved one
else {
  token = sharedPref.getString(REGISTRATION_ID, "");
}
```

**Comment by macdonst** [comment]
@kentmw fixed in 1.4.1 which has been pushed to NPM
