### ISSUE TITLE
Always calling "push.on('error', function(e)"

### ISSUE THREAD

**Issue by sulthanallaudeen** [phonegap/phonegap-plugin-push#297]
I did the following steps 
i.e., 
1. Create an empty cordova project
2. Added android platform
3. Added :: cordova plugin add phonegap-plugin-push
4. Copied the example->www and copied to project's www location

When i run the project in mobile it is always showing the `requested` in the screen, 

So for the testing i did like this 

onDeviceReady: function() {
	alert('app started');
	var push = PushNotification.init({ "android": {"senderID": "12345679"},
         "ios": {"alert": "true", "badge": "true", "sound": "true"}, 
		 "windows": {},
		 } );

-> This alert showed succesfully

push.on('registration', function(data) {
            console.log("registration event");
            document.getElementById("regId").innerHTML = data.registrationId;
			alert('got gcm :'+data.registrationId);
        });

-> This alert was not shown

push.on('error', function(e) {
            console.log("push error");
			alert("push error");
        });

-> and this alert was showing always 

What should i do now, Should i do anything else to get the GCM ID ?

**Comment by bau720123** [comment]
hi @sulthanallaudeen 
are you using Android，if yes
you should get your own "senderID"
the "12345679" just a "fake" sample

according to this
https://developers.google.com/cloud-messaging/gcm
A unique numerical value created when you configure your API project (given as "Project Number" in the Google Developers Console). The sender ID is used in the registration process to identify an app server that is permitted to send messages to the client app.

**Comment by sulthanallaudeen** [comment]
@bau720123  Thanks. 

Even after i updated the numeric with a project id , i am still getting that error. 

(I even enabled the cloud messaging )

**Comment by bau720123** [comment]
you should print the "e" to see what the error is
```
push.on('error', function(e) {
console.log(e);
});
```

**Comment by sulthanallaudeen** [comment]
@bau720123 

I tried like this 

Suppose if this is my Project ID : '567470612744'

var push = PushNotification.init({ "android": {"senderID": "567470612744"},

var push = PushNotification.init({ "android": {"senderID": 567470612744},

Both didn't worked out :(

**Comment by sulthanallaudeen** [comment]
In the 

var push = PushNotification.init({ "android": {"senderID": "567470612744"},
         "ios": {"alert": "true", "badge": "true", "sound": "true"}, 
		 "windows": {},
		 } );

For android should i do like this 

var push = PushNotification.init({ "android": {"senderID": "567470612784"},
         "ios": {"alert": "true", "badge": "true", "sound": "true"}, 
         "android": {"alert": "true", "badge": "true", "sound": "true"}, 
		 "windows": {},
		 } );

To get the gcm ?

**Comment by sulthanallaudeen** [comment]
@bau720123  It is alerting that "No value for senderID"

Though i have given my project id as 

var push = PushNotification.init({ "android": {"senderID": "567470612744"},

and even in 

var push = PushNotification.init({ "android": {"senderID": 567470612744},

**Comment by sulthanallaudeen** [comment]
@bau720123  I am getting this error 

"Empty GCM ID Recived from GCM"

Any clue for this ?

**Comment by bau720123** [comment]
hi @sulthanallaudeen 
are you sure your "Google Cloud Messaging for Android" is enable ?
what plugin version are you using ? 1.4.1 ?
did you use any OAuth 2.0 token in your google "console.developers.google.com" ?

**Comment by bmwsedee** [comment]
@sulthanallaudeen This is my 'init', for reference:
```javascript
var push = PushNotification.init({
        "android": {
            "senderID": senderID
        },
        "ios": {"alert": "true", "badge": "true", "sound": "true"},
        "windows": {}
});
```
where `senderID` is a String containing my senderID.

Furthermore: where are you testing your code? On a physical device, or on an emulator?

**Comment by sulthanallaudeen** [comment]
@bau720123  Yes i am sure that 'Google Cloud Messaging for Android' is enabled.
and i am using the latest plugin, 
I am not using oath token..

Few times i am getting TIMEOUT as error

**Comment by sulthanallaudeen** [comment]
@bmwsedee  I should not use " - Double quotes to the senderID right

i.e.,
If my Project id is 749837433,

then it should be 
 "senderID": 749837433

Isn't it ?

**Comment by bmwsedee** [comment]
@sulthanallaudeen I've got:
```javascript
var senderID = "749837433";
```
defined, so it's quoted in my code.

**Comment by sulthanallaudeen** [comment]
@bmwsedee Thanks i did the same .

Ahm, when i quoted and installed the fresh app, i am getting this error 

"Empty registration ID received from GCM"..


What would be the issue

**Comment by bmwsedee** [comment]
@sulthanallaudeen Depends, I guess. Just to be sure, but I take it the packagename you used to register for Google Cloud Messaging and the name you're using in your app (in config.xml) are the same?
What kind of device are you testing your code on?

**Comment by sulthanallaudeen** [comment]
@bmwsedee  They are different, do the package name that i register in Google Cloud Messaging and the project i create in cordova needs to be same ?

**Comment by bmwsedee** [comment]
@sulthanallaudeen Never actually tried it with different package names, but it would be my guess that they need to be samen. Maybe @macdonst knows the details of this, but would it be a problem to change the package name of your cordova project, if only for testing purposes?

**Comment by bau720123** [comment]
hi @sulthanallaudeen 
according to this
http://stackoverflow.com/questions/11341305/android-gcm-gcmregistrar-gives-empty-registration-id

Empty String comes when device is not registered successfully. There may be following reasons for it-
Put you GCM code in "application package". [You can make another package with same name of application package]
Put all permissions properly.

**Comment by sulthanallaudeen** [comment]
@bmwsedee  @bau720123 I even tried now with same project name and package name... 

Now getting the same error : "Empty registration ID received from GCM"

**Comment by bmwsedee** [comment]
@sulthanallaudeen And what about the device you're testing this on?

**Comment by sulthanallaudeen** [comment]
@bmwsedee 
I am testing on a real device (and not emulator)

I am trying with Android 5.01 version

**Comment by bmwsedee** [comment]
@sulthanallaudeen Have you seen the logcat-log of your application when trying to get a registrationId? Could be there is some error in there

**Comment by sulthanallaudeen** [comment]
@bmwsedee 


As these operations wants to be done in mobile, i am just generating apk and installing it in mobile. 

Does the only way to see logcat is by connecting the device with machine ?

Or is there any other way to debug it ?

**Comment by bmwsedee** [comment]
@sulthanallaudeen Possibly there is some way of reading the logs from your mobile device itself, but I leave the device attached to my machine myself, so I can read the logs when I need to.

**Comment by sulthanallaudeen** [comment]
@bmwsedee 

Ok, i will try to connect the device and read the logcat and let you know shortly :)

**Comment by sulthanallaudeen** [comment]
@macdonst  I am getting Empty Registration ID in few cases what could be the issue

**Comment by sulthanallaudeen** [comment]
It was partially solved, so i am closing this ticket

**Comment by mariohmol** [comment]
I have the same problem using a emulator, this emulator has a google account registered (reading email and all working good).. any ideas?

**Comment by bmwsedee** [comment]
What Android version are you running? And what is the target of your emulator? Your best bet is to test push-notifications on a real device, not on an emulator.

**Comment by mariohmol** [comment]
thanks for answering.. i removed the api lvl 19 e created a new lvl 21 and worked...
