### ISSUE TITLE
Android action button callback not triggered  

### ISSUE THREAD

**Issue by stewartmegaw** [phonegap/phonegap-plugin-push#298]
Firstly, great plugin. Much improved over the last.

When receiving a push notification with one action button:
The icon and title both display in the notification but when I click the action button (not main body of notification) two unexpected results occur:
1) The action callback is ignored and the regular notification callback is triggered.
2) The notification remains in the shade even though the app is now in the foreground.

1) I have clearly defined my callback function so can't see any problems there.
2) The notification in shade eventually disappears if I either place the app in background or click the notification again.

Tested using latest plugin 1.4.1
Android 5.0 ZenPhone 2

**Comment by macdonst** [comment]
@stewartmegaw can you post the payload you are sending from GCM to the device so I can test?

**Comment by stewartmegaw** [comment]
{
    "registration_ids": ["fOrCjNuH4tg:APA91bEazxEGrgZbWWakr9VrNzWh-AwZcX6bNCTlaWiz5KQ4ZeVdQbTPYnCHiziWFTQTkahwtyh7FVU-aUgEFmW-QvrYrjruGw_r0AmF7Q-2oVxKdiE1cX3hhfajihqnxT79zaVdm0Lj"],
    "data": {
        "id": 100042,
        "type": "New trip",
        "message": "Charlie Fall planned a trip to Fiji",
        "title": "New trip",
        "deep_link": "notif_type%3Dfriend_new_trip%26user_from%3D3893582%26identifier%3Dsolr_3893582_5639604a95a9f%26accommodation%3D1",
        "actions": [{
            "icon": "accomm",
            "title": "OFFER ACCOMMODATION",
            "callback": "proa"
        }]
    }
}

This is the json my php script is sending to GCM via the following curl commands:
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($post));
$result = curl_exec($ch);

These commands do send the notification. And I can't see a problem with the json above (fyi i logged it as a string using json_encode function). And function proa is declared globally in my index.html.

**Comment by bau720123** [comment]
hi @macdonst 
I have the same problem (1.4.2 version)
I use php to send a notification to GCM and I really receive a notification in my phone (Android 4.4.2)

here is my php payload
```
$fields = array('registration_ids' => 'my registration_id', 
 'data' => array(
 'title' => 'my title'
 'message' => 'the message',
 'style' => 'inbox', 
 'summaryText' => 'here have %n% messages', 
 'actions' => array(array('icon' => 'emailGuests','title' => 'bottom1','callback' => 'app.actions_left'), array('icon' => 'snooze','title' => 'bottom2','callback' => 'app.actions_right')),
 'image' => 'the image http url',
 'notId' =>'the notid', 
 'payload' => 'the others'
 )
 );
``

here is my javascript
```
push.on('registration', function(data)
{
//will trigger
});

push.on('notification', function(data)
{
//will trigger
});

function actions_left()
{
alert('left'); //not trigger
}

function actions_right()
{
alert('right'); //not trigger
}
```

**Comment by bau720123** [comment]
solve in
https://github.com/phonegap/phonegap-plugin-push/issues/274

**Comment by sumeeranalabs** [comment]
hi bau720123,
can u expalined me in detailed?i am stuck here from a week on callback function.
