### ISSUE TITLE
1.4.x not showing notification on Android

### ISSUE THREAD

**Issue by AdriVanHoudt** [phonegap/phonegap-plugin-push#299]
Sending the exact same payload. 1.3 works fine, 1.4 just call the `.on('notification, fn)` with all keys in `additionalData`

**Comment by AdriVanHoudt** [comment]
so after changing `body` to `message` I get
```js
{
    "image": "urltopicture.jpg",
    "message": "test",
    "additionalData": {
        "summaryText": "There are %n% new notifications",
        "gcm.notification.notId": "121",
        "gcm.notification.title": "Title 1",
        "id": "121",
        "tag": "121",
        "style": "inbox",
        "coldstart": false,
        "collapse_key": "org.company.app",
        "foreground": false
    }
}
```

The `message` should be `body` see https://developers.google.com/cloud-messaging/concept-options#notifications_and_data_messages
Also not sure why title and notId are not being properly parsed?

**Comment by AdriVanHoudt** [comment]
Shouldn't this break for more people? :O

**Comment by macdonst** [comment]
@AdriVanHoudt can you send me an example of data you are sending to GCM. That will really help me debugging this.

**Comment by smdvdsn** [comment]
Also @AdriVanHoudt do you see different results if the app is closed vs forground vs background

@macdonst I suspect this is caused by the GcmListenerService code. I think that it displays the notification if there is a gcm.notification.title or gcm.notification.body key in the message. I wonder if it is bypassing our normlize in those cases?

**Comment by AdriVanHoudt** [comment]
@smdvdsn I see nothing, only difference is that when in foreground it immediately handles the message and otherwise it waits for the app to open

this is (roughly, I use a lib which accepts the registration ids as a different param) what I send to gcm:
```js
{
    data: undefined,
    notification: {
        title: 'Title 1',
        body: 'test',
        image: 'http: //urltopicture.jpg',
        id: 121,
        tag: 121,
        style: 'inbox',
        summaryText: 'Thereare%n%newnotifications',
        notId: 121
    }
}
```

**Comment by macdonst** [comment]
@AdriVanHoudt thanks, I can reproduce it now using node-gcm to send a push with your test data. Stay tuned.

**Comment by AdriVanHoudt** [comment]
Cool, I will, also debugging this myself (at least trying :D)

**Comment by macdonst** [comment]
@AdriVanHoudt it's something weird when we iterate through the key set of the extras coming in from GCM. For some reason we skip a few.

**Comment by AdriVanHoudt** [comment]
jup managed to get this out of debugger:
```js
D/PushPlugin_GCMIntentService(26109): onMessage - from: 128469695999
D/PushPlugin_GCMIntentService(26109): mormalize extras
D/PushPlugin_GCMIntentService(26109): key = gcm.notification.image
D/PushPlugin_GCMIntentService(26109): replace key gcm.notification.image with image
D/PushPlugin_GCMIntentService(26109): key = gcm.notification.style
D/PushPlugin_GCMIntentService(26109): replace key gcm.notification.style with style
D/PushPlugin_GCMIntentService(26109): key = gcm.notification.summaryText
D/PushPlugin_GCMIntentService(26109): replace key gcm.notification.summaryText with summaryText
D/PushPlugin_GCMIntentService(26109): key = image
D/PushPlugin_GCMIntentService(26109): key = style
D/PushPlugin_GCMIntentService(26109): key = gcm.notification.body
D/PushPlugin_GCMIntentService(26109): replace key gcm.notification.body with body
D/PushPlugin_GCMIntentService(26109): key = gcm.notification.tag
D/PushPlugin_GCMIntentService(26109): replace key gcm.notification.tag with tag
D/PushPlugin_GCMIntentService(26109): key = gcm.notification.id
D/PushPlugin_GCMIntentService(26109): replace key gcm.notification.id with id
D/PushPlugin_GCMIntentService(26109): key = collapse_key
```

**Comment by macdonst** [comment]
@AdriVanHoudt @smdvdsn I'm pretty sure it is a concurrent modification problem. When the `body` property is replaced with `message` it screws up the iterator we are using. Testing a fix now.

**Comment by macdonst** [comment]
@AdriVanHoudt @smdvdsn Yup, that was it. Can you test branch `issue299`. I'm getting on a plane for Europe in a couple of hours and would like to push a fix if possible but it would be good if someone else took a look at this as well.

**Comment by AdriVanHoudt** [comment]
on it

**Comment by AdriVanHoudt** [comment]
it is working now, big thank you @macdonst for fixing this so quickly, you doing a patch release now?

**Comment by macdonst** [comment]
Yes, I will do a patch and release to NPM in the next 10 minutes. It didn't surface in my testing as I wasn't mixing data and notification.

**Comment by macdonst** [comment]
@AdriVanHoudt published version 1.4.2

**Comment by Telemakhos** [comment]
This should be in the readme or in a visible place... I've spent several hours until I found this fix...

**Comment by AdriVanHoudt** [comment]
How so? This fix is to make it working like it should/like in the readme

**Comment by Telemakhos** [comment]
I mean, just adding a little section with notices for regressions and breaking changes in the readme (the first thing one reads when arrives to the repo) so newcomers don't spend 5 hours banging their heads against the wall before realising they have to install the plugin via git clone.

**Comment by AdriVanHoudt** [comment]
This fix was published as 1.4.1 so need to git clone, are you allowing pathes in your config.xml? I have it set at 1.4.x. It is possible you need to reinstall the plugin to get the right version

**Comment by Telemakhos** [comment]
I've been using this plugin only since yesterday. First I installed the plugin via 

```cordova plugin add phonegap-plugin-push``` (stable) 

and I wasn't receiving the notifications, then after finding this issue I finally installed with

 ```cordova plugin add https://github.com/phonegap/phonegap-plugin-push``` (unstable)

and started working. I was just just suggesting to include a section with references to major breaking changes (like this one) in the readme of the repo, maybe pointing out to the corresponding issues...

**Comment by AdriVanHoudt** [comment]
hmm weird I have `<plugin name="phonegap-plugin-push" spec="1.4.x" />` in my config.xml and that works fine. I personally see no point in listing issues in the readme, this is fixed if you still have a problem I would suggest opening another issue about the fix not working when installing via the cordova command line

**Comment by macdonst** [comment]
@Telemakhos Yeah, I don't think we need to add it to the README as it is already fixed. Whenever I do a minor release I do a blog post with all the changes/fixes.

It's really odd that `cordova plugin add phonegap-plugin-push` did you get you the latest 1.4.2 release which includes the fix. Can you try again and do `cordova plugin ls` to see what version it installs?
