### ISSUE TITLE
Cannot register on iOS

### ISSUE THREAD

**Issue by martinfilliau** [phonegap/phonegap-plugin-push#30]
I've tried the code below on two different iPhone running iOS 8.4 and the error callback is always called twice, with the value being constantly `{}`.

The code runs after `deviceready` is fired, and works fine on Android.

```javascript
var plugin = PushNotification.init({ "android": {"senderID": "XX"},
                       "ios": {'badge': true, 'sound': true, 'alert': true}});

plugin.on('registration', function (data) {
  alert("Registration: " + JSON.stringify(data));
});

plugin.on('notification', function (data) {
  alert("Notification: " + JSON.stringify(data));
});

plugin.on('error', function (e) {
  alert("Error: " + JSON.stringify(e));
 });
```

Any idea what could possibly be wrong?

**Comment by boboldehampsink** [comment]
You should use a development certificate with push capabilities when you build

**Comment by martinfilliau** [comment]
The certificate is supposed to have push capabilities, but I'll double check.

**Comment by boboldehampsink** [comment]
Make sure your project is set to use this certificate when building

**Comment by macdonst** [comment]
@martinfilliau I can't reproduce this. As @boboldehampsink mentions it is probably due to a cert issue with iOS. Gawd knows I struggle with those certs :)

**Comment by martinfilliau** [comment]
Yep we were indeed using the wrong certificate...
Thanks for the fast reply!
