### ISSUE TITLE
Amazon-Fireos and Blackberry 10 support

### ISSUE THREAD

**Issue by paulhovey** [phonegap/phonegap-plugin-push#300]
The project this is based on, https://github.com/phonegap-build/PushPlugin , supported Amazon Fireos platforms, as well as Blackberry 10 push support.  Are either of those going to be included in this plugin?  I want to use the updated code here, without removing support for past platforms (and doing a manual install each time).  Is there a reason they weren't included?

**Comment by macdonst** [comment]
@paulhovey sadly I don't have the time nor the necessary hardware to do the testing for Amazon/BB10. The old code from the previous plugin is in a amazon/blackberry branch. At this point I need someone with Amazon/BB knowledge to contribute a PR to add the support.

**Comment by paulhovey** [comment]
Hi @macdonst -

I understand, I wish I could help instead of just requesting.  Thanks for the response.
