### ISSUE TITLE
[just a question] about the led color

### ISSUE THREAD

**Issue by bau720123** [phonegap/phonegap-plugin-push#302]
hi @alexislg2 (led color author) and @macdonst 
according to this
https://github.com/phonegap/phonegap-plugin-push#led-in-notifications
ledcolor is work perfect
and...
it told me that [0, 0, 255, 0] seem like a green color
so I use this website attempting change the color
http://www.ifreesite.com/color/
finally I found [0, 4, 0, 255] seem like blue
so I use this value and send a notification again
but still receive a green ledcolor

is it because the hardware(phone) that must support this feature，otherwise，always the default (green)
if yes，is there a site or page can show the support list

**Comment by fredgalvao** [comment]
I don't think such a compatibility list exists.
[The android docs](http://developer.android.com/intl/pt-br/reference/android/app/Notification.Builder.html#setLights(int, int, int)) state that:
> Not all devices will honor all (or even any) of these values.

**Comment by bau720123** [comment]
thanks @fredgalvao reply
HAHA
I am just wonder，if I want to see the led color (default green) change to other color (maybe blue)，which phone or tablet should I bought it ?
