### ISSUE TITLE
when the words equal or more than 8 lines...it will cut the "summaryText"

### ISSUE THREAD

**Issue by bau720123** [phonegap/phonegap-plugin-push#303]
all in the screenshot
![screenshot_2015-11-04-15-12-47](https://cloud.githubusercontent.com/assets/5110085/10932796/ae423dc2-830e-11e5-9785-1f3611a8f2f8.jpg)

**Comment by bau720123** [comment]
hi @macdonst 
just ask
anything update about above ?

**Comment by macdonst** [comment]
@bau720123 sorry, I can't reproduce. I've tried it on a bunch of my phones.

**Comment by bau720123** [comment]
hi @macdonst 
thanks your reply
I just check once again
seem only occur in Android 4.4.2 (Android 4 version)
Android 6 have no this problem...
