### ISSUE TITLE
Android - After unregister and reregister no notifications

### ISSUE THREAD

**Issue by adyz** [phonegap/phonegap-plugin-push#304]
After un-register -- I don't receive any notifications further -- This is what I want.

		if(typeof vv.push === 'undefined') {
			vv.pushinit();
		}

		vv.push.unregister(successHandler, errorHandler);

When I want to enable push notifications back I call back the init function

	vv.push = PushNotification.init({

		"android": {
			"senderID": vv.params.googleGCMProjectNumber,
		},
		"ios": {
			"alert": "true",
			"badge": "true",
			"sound": "true"
		}
	});

	/*
	 * When registration is done, store the registration ID;
	 */
	vv.push.on('registration', function(data) {....

When I reregister, I get the same registrationID, but I don't receive the notifications.

I this the proper way to handle the push notification enable?

Thanks

**Comment by bau720123** [comment]
hi @adyz 
according to this I post
https://github.com/phonegap/phonegap-plugin-push/issues/296
1.4.2 verison
in Android，it will get a new data.registrationId
this is why you can't receive a notification，because you should use a new data.registrationId to send notification

**Comment by adyz** [comment]
I understand, but I get the same one on `vv.push.on('registration', function(data) {...`
Should I get a new one? If so, how can I do that?

**Comment by adyz** [comment]
Looks like I get different id in in 1.4.2 -- I was using 1.4.0.

Thanks

**Comment by zwacky** [comment]
sorry, misreferenced this.
