### ISSUE TITLE
[just a question] about the priority

### ISSUE THREAD

**Issue by bau720123** [phonegap/phonegap-plugin-push#306]
hi @alexislg2 (priority author) and @macdonst 
according to this
https://github.com/phonegap/phonegap-plugin-push#priority-in-notifications
could I ask what the priority true meaning ?
2 > 1 > 0 > -1 > -2
what the any different to show in my phone ?

**Comment by macdonst** [comment]
@bau720123 read up on it here:

http://developer.android.com/intl/pt-br/reference/android/app/Notification.html#PRIORITY_DEFAULT

**Comment by bau720123** [comment]
hi @macdonst 
thanks your document
very clear
the document told us that "priority" feature "Added in API level 16"
well...according to this
http://developer.android.com/intl/pt-br/guide/topics/manifest/uses-sdk-element.html#ApiLevels
you can find a table that list and describe the api level with the Android version
api level 16 is Android 4.1, 4.1.1

is it mean our Android initial system must equal or greater than Android 4.1, 4.1.1 ? right ?
your document also told us "The UI may choose to show these items different size, or at a different position in notification lists"，if have a screenshot can show this，it will more better

**Comment by fredgalvao** [comment]
You're right on your first assumption, you need to have an android version of 16(api level) or higher for these settings to work (it doesn't mean it will crash on lower versions, it'll just be a no-op function).

On your last question, it's up to the OS to determine what it'll do with each priority, not to the developer. For example, the UI from Samsung devices might do things differently than the UI from LG.

**Comment by bau720123** [comment]
hi @fredgalvao 
very clear again
close it
