### ISSUE TITLE
Install plugin error, unexpected token.

### ISSUE THREAD

**Issue by ikermart** [phonegap/phonegap-plugin-push#307]
I'm having an issue trying to add a plugin like this:

cordova plugin add https://github.com/phonegap/phonegap-plugin-push

Error:
Repository "https://github.com/phonegap/phonegap-plugin-push" checked out to git ref "master".
SyntaxError: Unexpected token }
    at Object.parse (native)
    at getJson (/home/.nvm/versions/node/v0.12.4/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/metadata.js:29:31)

**Comment by fredgalvao** [comment]
What is the output of running the following in your machine?
`cordova -v`
`cordova platform ls`

**Comment by ikermart** [comment]
cordova -v
5.3.3
cordova platform ls
Installed platforms: android 3.7.1

**Comment by fredgalvao** [comment]
Can you try adding it through npm instead of git?
Like this:
`cordova plugin add phonegap-plugin-push`

**Comment by ikermart** [comment]
Same error message.

**Comment by macdonst** [comment]
@ikermart re-open if still a problem.
