### ISSUE TITLE
Is it possible to add badge on Android portion.

### ISSUE THREAD

**Issue by jimior2** [phonegap/phonegap-plugin-push#308]
Would it possible to add set badge number like push.setApplicationIconBadgeNumber and support Android portion, I know there's a badge plugin out there called " cordova-plugin-badge", but if this support also that we don't need to install another to do badge.  :+1:

**Comment by fredgalvao** [comment]
I'm closing this as a duplicate of https://github.com/phonegap/phonegap-plugin-push/issues/190, you're invited to +1 on that issue so that it gets the desired attention.

**Comment by jimior2** [comment]
@fredgalvao Thanks. +1 already.
