### ISSUE TITLE
Programmatically register

### ISSUE THREAD

**Issue by boboldehampsink** [phonegap/phonegap-plugin-push#31]
Hi,

I have this switch that lets you "unregister" your device. However, when switched by mistake, switching it back should bring op the "Allow push notifications" alert again. There's no way to do that now.

I'd like to see a "register" function added, so I can register a device programmatically

**Comment by macdonst** [comment]
@boboldehampsink I'm confused why this is needed. Can't you just call `init` again?

**Comment by sebrojas14** [comment]
Definitlly is no clear...init do the register no?

**Comment by macdonst** [comment]
@sebrojas14 Yeah, the init method starts the registration process.
