### ISSUE TITLE
Parse.com support?

### ISSUE THREAD

**Issue by lpotapczuk** [phonegap/phonegap-plugin-push#310]
Hey guys,

I am having an issue with receiving notifications send through Parse.com. I was wondering if the plugin has a support for the notifications send through their service?

Thanks
Lukasz

**Comment by macdonst** [comment]
@lpotapczuk support was added for Parse but there may still be bugs. Please provide more details so we can help you.

**Comment by vection** [comment]
I am using the plugin in connection with Parse.com push notifications and it works.

**Comment by Mojo90** [comment]
for me it does work as well

**Comment by macdonst** [comment]
Details...

**Comment by gortok** [comment]
I need to open source the changes I made to the new push notifications plugin to get it to work with Parse.com; I'll do that and link to it.

**Comment by lpotapczuk** [comment]
Hey guys, 

I am sorry for late answer - been super busy at work. I will add details during this weekend

**Comment by YourPrivateCoder** [comment]
Hi. @Mojo90 @vection 

Could you please help me a little about parse.com support. Right now I am using parse push plugin https://github.com/avivais/phonegap-parse-plugin , but this one doesn't have callback methods available so I am trying to migrate to this library here. 

But as I understand Parse installationId is parse own logic and phonegap-plugin-push gives me some other registrationId that Parse doesn't like.

So I would be happy if you can guide me how did you set up phonegap-plugin-push for parse.com app.
I am using ionic / android platform.

**Comment by vection** [comment]
Hi @YourPrivateCoder,

since the JS SDK from Parse.com does not support Installations yet, I am using a REST POST request to install the device token. All goes as follows:

```
push = PushNotification.init({
      "android": {"senderID": "-----------", vibrate: false},
      "ios": {"alert": "true", "badge": "true", "sound": "true"}} );

    push.on('registration', function(data) {
        data = { deviceType: "ios", deviceToken:token }
      return $http.post('https://api.parse.com/1/installations', data,
      {
        "headers" : {
        "Content-Type" : "application/json",
        "X-Parse-Application-Id" : "---------------------------------------------",
        "X-Parse-REST-API-Key" :"--------------------------------------------"}
      })
      .success(function(res, status, headers, config) {
      var installationId = res.objectId
      console.log("Registering NEW device successfull")
      console.log("Saving: " + installationId)
      })
      .error(function(res, status, headers, config) {
        console.log("Ups, we are screwed!")
    })

    })
```

Now this is Parse specific and actually does not necessarily belong here but it might be a nice example for people using this plugin. Good luck with it.

**Comment by YourPrivateCoder** [comment]
@vection Thank you for your answer, and I got the idea, but still same problem.

I put my google developer Project number as senderID, it generates registrationId, use right api keys and it gives me this error: 

code: 114, error: "deviceToken may not be set for deviceType android"
As I want to still send notification from parse.com and not set up GCM.

Do you have any suggestions, what I am doing wrong? This is not very well covered are in parse nor here... 

Thanks

**Comment by vection** [comment]
In that case I am using
```javascript
if(ionic.Platform.isAndroid()){
      regdata = {
        deviceType: "android",
       deviceToken:token, pushType:"gcm", GCMSenderId: "----------" }
    }
```

This works for me. Have you set up the push backend correctly?

**Comment by YourPrivateCoder** [comment]
@vection thank you, yes, backend was working with different push library, this seems more advanced.

Alright, I actually got this working, feels just bit strange, registering GCM (the same way you are) and still send push from parse.com, and it does arrive.

Just one more question, am I right, that in this case parse doesn't register installationId? And just saves senderId and device token?

**Comment by vection** [comment]
So I am saving the installationId after creating the Installation on the client side via local storage. Later, if the device token has changed, I am updating the installation object with the installationId with another post request.
I don´t know if this is the best method but it´s a workaround for the missing "Installation" support in the Parse JS SDK.

**Comment by YourPrivateCoder** [comment]
@vection

I got this working nice now and actually even don't save installationId. 
I will post it here if someone needs it as well.

            var push = PushNotification.init({
                "android": {
                    "senderID": "XXXXXXSenderId"
                }
            });

            push.on('registration', function(data) {
                var token = data.registrationId;
                // coreservice.deviceToken = token; //comment it out for similar service like aproach
                var reqData = {
                    "deviceType": "android",
                    "deviceToken": token,
                    "pushType": "gcm",
                    "GCMSenderId": "XXXXXXSenderId"
                }
                return $http.post('https://api.parse.com/1/installations', reqData , {
                        "headers": {
                            "Content-Type": "application/json",
                            "X-Parse-Application-Id": "XXXXXXXX",
                            "X-Parse-REST-API-Key": "XXXXXXXX"
                        }
                    })
                    .success(function(res, status, headers, config) {
                        console.log("Registering NEW device successfull");
                    })
                    .error(function(res, status, headers, config) {
                        console.log("Something went wrong");
                    });
            });

What happens is parse saves only senderId and deviceToken.
So I save device token to service. When user loggs in, I send deviceToken to my cloud code function that finds my device and save user (pointer) next to that.

And then I have just afterSave function for one table that queries Installation table with user object and sends it out. So only what's needed is deviceToken.

**Comment by stewartmccoy** [comment]
This issue should probably be closed since the OP has not followed up with details and also since Parse.com is shutting down.

**Comment by mymanga** [comment]
I tried both examples above and i get the collowing error on android;
```
05-15 08:48:53.871 14054-14054/com.example.test I/chromium: [INFO:CONSOLE(312)] "Error in Success callbackId: PushNotification1712974319 : ReferenceError: $http is not defined", source: file:///android_asset/www/cordova.js (312)
05-15 08:48:53.876 14054-14054/com.example.test I/chromium: [INFO:CONSOLE(314)] "Uncaught ReferenceError: $http is not defined", source: file:///android_asset/www/cordova.js (314)
```

**Comment by gortok** [comment]
@mymanga you're probably not injecting $http; can you link me to a complete repro of your issue?

**Comment by mymanga** [comment]
https://github.com/mymanga/parsepush

**Comment by mymanga** [comment]
https://github.com/mymanga/parsepush
