### ISSUE TITLE
Callback issue

### ISSUE THREAD

**Issue by Saurabh995** [phonegap/phonegap-plugin-push#311]
push.on('notification',function(data){
    
    
        // data.title,
        // data.count,
        // data.sound,
        // data.image,
        // data.additionalData
    alert(data.title);}            this function is not triggered when the app is closed . But it works when app is opened.

**Comment by macdonst** [comment]
@Saurabh995 this is by design. Please read:

https://github.com/phonegap/phonegap-plugin-push#background-notifications
https://github.com/phonegap/phonegap-plugin-push#background-notifications-1

to learn how to get this function to trigger when the app is in the background.
