### ISSUE TITLE
Getting "Error : Empty registration ID received from GCM"

### ISSUE THREAD

**Issue by sulthanallaudeen** [phonegap/phonegap-plugin-push#315]
I have installed this plugin and using the example directly, it was working good yesterday and previous day, from today morning i am always getting this error whenever the app is opened

"Error: Empty registration ID received from GCM"

I have checked the SDK, and the GCM is enabled in Google Console but i don't know why i am getting this error.

What is the mistake i am doing and how can i fix it ?

**Comment by macdonst** [comment]
@sulthanallaudeen this is possibly a bug but without a more detailed reproduction scenario it's hard for me to say what's going on. Can you provide me more details?

Also, if you completely uninstall and re-install the app does the issue go away?

**Comment by sulthanallaudeen** [comment]
@macdonst  Ok, i wil update the question with more details soon. Thanks

**Comment by mariohmol** [comment]
i had this same issue..

i created a new emulator.. using google api lvl 21 in a MacOS enviroment.. 

and worked.. =)

**Comment by macdonst** [comment]
The Android emulator doesn't have Google Play Services so this'll never work.

When creating an emulator use the Google API version that does have Play Services.

Better yet test with a device.
