### ISSUE TITLE
Small icon not working

### ISSUE THREAD

**Issue by albertleao** [phonegap/phonegap-plugin-push#316]
Hello.

Push plugin has been working great for me until i recently updated cordova to 5.2 and the pushplugin to 1.4.2.

After my upgrade, my push notifications and large icons still worked, but my small icon is always just a white square. 

 var push = PushNotification.init({
                                        "android": {"senderID": "###", "icon" : 'ic_message_white_24dp.png', "iconColor" : "blue"},
                                        "ios": {}, 
                                        "windows": {} 
                                    });

I have the ic_message_white_24dp.png in my platform/res/drawables folder and still get nothing. The small icon background color is working correctly with "blue"

**Comment by fredgalvao** [comment]
I don't know if it would matter, but all examples I know specify the `icon` property **without the extension name**. Please try again with the following code and report back:

```js
var push = PushNotification.init({
    "android": {
        "senderID": "###",
        "icon" : 'ic_message_white_24dp',
        "iconColor" : "blue"
    },
    "ios": {}, 
    "windows": {} 
});
```

**Comment by albertleao** [comment]
You are correct. I created a pull request to add that to the documentation. Thank you very much.
