### ISSUE TITLE
Not showing notification?

### ISSUE THREAD

**Issue by guilhermegm** [phonegap/phonegap-plugin-push#319]
I send a notification from my backend and my app is receiving the following data:

{"additionalData":{"msg":{"title":"Large Icon","message":"Loaded from drawables folder"},"collapse_key":"message","foreground":false}}

But no notification appears. Why?

thanks!

**Comment by fredgalvao** [comment]
Whatever you're adding to the "msg" property of the params on your request, add it directly to the params object.

Your object right now might look something like: 
```json
{
    "msg": {
        "title": "Large Icon",
        "message": "Loaded from drawables folder"
    }
}
``` 
but you actually want it to be like this:
 
```json
{
    "title": "Large Icon",
    "message": "Loaded from drawables folder"
}
```

**Comment by macdonst** [comment]
@fredgalvao is correct. If there is not title or message attribute then the notification won't be shown in the shade.

**Comment by guilhermegm** [comment]
@fredgalvao Thank you, it works. My fault =)
