### ISSUE TITLE
[INSTALL_FAILED_CONFLICTING_PROVIDER]

### ISSUE THREAD

**Issue by GctKaelinllc** [phonegap/phonegap-plugin-push#320]
Hi,

I have installed this plugin in the two different apps, apps are working fine in different devices. But if we try to install the both app on the single device then it shown the below mentioned url.
Please help me to resolve this issue. 

ERROR: Failed to launch application on device: ERROR: Failed to install apk to d
evice:  pkg: /data/local/tmp/android-debug.apk
Failure [INSTALL_FAILED_CONFLICTING_PROVIDER]

**Comment by smdvdsn** [comment]
Is the app that you are seeing the error with already on the device? If so first uninstall and then try again.

**Comment by GctKaelinllc** [comment]
I have two different apps and have to install the both app on the same device. 
If I install only one app at a time then work perfectly but my requirement is to run both on the same device.

**Comment by smdvdsn** [comment]
What version of the plugin are you using? I've seen this issue before but in my case I already had the app that was causing the issue installed on the device. Uninstalling first was enough to fix for me.

Also what other plugins are you using?
Was the second app created by copying the first?

**Comment by GctKaelinllc** [comment]
I am using plugin version 1.4.2 in cordova 5.3.3. 
I have checked  each scenario by removing all the plugin etc.
Today, I also have tested it to create separate new fresh app and installed the plugin in both apps. The same issue occurs if we try to install both apps in the same device.

**Comment by smdvdsn** [comment]
Can you try uninstalling all old versions of any apps with the plugin from your device. And then try to install your two apps again.

**Comment by GctKaelinllc** [comment]
Yes, I have tried. but no luck

**Comment by smdvdsn** [comment]
Are you able to show me the AndroidManifest.xml files from the two projects?

**Comment by GctKaelinllc** [comment]
Yes, Please see the attached

**Comment by GctKaelinllc** [comment]
Yes, Please download from the below mentioned url
https://drive.google.com/file/d/0B9yxq8hJMPKiVFM2and6QUFQdHc/view?usp=sharing

**Comment by smdvdsn** [comment]
They look fine? I'm at a loss on this one I'm afraid. Are you sure that there are no other apps installed on your device that might have similar package name?

Could you try creating two new apps that have completely different package names com.mytestpackage and com.someotherpackage for example? Just to see if you can get them to install.

I can confirm that this plugin works with multiple apps. I have at least three of my apps using this plugin installed on my device. Both debug builds and installs from the play store.

The times I've seen this issue the app was already on the device (usually a debug build) so uninstalling fixed it for me.

**Comment by GctKaelinllc** [comment]
I already have tried this, But will try again.

**Comment by smdvdsn** [comment]
I also found this https://code.google.com/p/android/issues/detail?id=189079 basically they are saying that another app has declared the same provider authorities as google play services and this is causing the issue. I'm not sure if this is the case here but have you tried installing your two apps on a different device or even on the emulator?

**Comment by fredgalvao** [comment]
Might be worth trying to rename the classes registered as providers/listeners, if that's the case, @smdvdsn .

**Comment by GctKaelinllc** [comment]
I have tried to install both apps in more than 4 devices. But every time same error occured

**Comment by smdvdsn** [comment]
What version of play services do you have installed? Could this be your issue? https://code.google.com/p/analytics-issues/issues/detail?id=784

**Comment by suspiration** [comment]
I too ran into this same issue.  Since using this new plugin, I had to upgrade Google Play Services to a higher version.  Because of a change in Google's AndroidManifest.xml (https://code.google.com/p/android/issues/detail?id=193567), it gives INSTALL_FAILED_CONFLICTING_PROVIDER error when installing multiple app on the same device.  

Simple fix is to add applicationId under defaultConfig in build.gradle.  Hope this helps.

**Comment by macdonst** [comment]
@suspiration Thanks, that is very valuable information. I'll have to see if we can automate it.

**Comment by smdvdsn** [comment]
@macdonst Perhaps this would be better in Cordova Android core project. I imagine that any plugin using play framework could have this issue.

**Comment by macdonst** [comment]
@smdvdsn sorry, what do you mean? Adding play services to Android core?

**Comment by smdvdsn** [comment]
@macdonst sorry no I mean we should suggest that cordova android add the applicationId property to the default build.gradle

**Comment by GctKaelinllc** [comment]
@suspiration Thanks for your help. I have just added applicationid in the build.gradle under defaultconfig and both app work perfectly.
eg: applicationId "com.application.name"

**Comment by ld0rman** [comment]
I had this problem and had to roll back to phonegap-plugin-push 1.3.0 in order to solve error

**Comment by macdonst** [comment]
Re-opening this as it really needs to get fixed either by this plugin or cordova-android.

**Comment by macdonst** [comment]
I've automated this with `push.gradle`, as of version 1.4.4 it will add the `applicationId` for you so you don't see this error anymore.

**Comment by wetok** [comment]
Hi, I'm getting this error in 1.5.3. Is it possible to fix this via config.xml (I'm using PhoneGap)

**Comment by shaoner** [comment]
Hi,

@macdonst : commit 48c4a56731f079474bca588af17702cd502f2a16 removes the push.gradle file used to resolve this issue.

**Comment by markono** [comment]
Hi, since push.gradle file was removed, is there any new solution for INSTALL_FAILED_CONFLICTING_PROVIDER error on version 1.6.1 ?

Thanks.

**Comment by ericb** [comment]
I was experiencing this issue until I updated cordova. You can also explicitly set the `applicationId` as stated above.

**Comment by markono** [comment]
Thanks @ericb ,
latest cordova update resolves the problem.

**Comment by jmgcheng-freemight** [comment]
@ericb 
i've added applicationId in the build.gradle platforms\android\CordovaLib\build.gradle and now i'm having error "Library projects cannot set applicationId."

@markono 
i've already updated my cordova and ionic. still there's an error.

is this bug already fix?

**Comment by ekaram** [comment]
@markono which version of cordova? i was already on 4.1.1 and am  experiencing this issue

**Comment by lavarith** [comment]
This is still a problem using the adobe online build system. It isn't clear how to resolve this.

**Comment by axemclion** [comment]
Looks like this is fixed in [CB-10014](https://issues.apache.org/jira/browse/CB-10014] and a [corresponding commit](https://github.com/apache/cordova-android/commit/fb9cf60c4100d5bc6f9320747611da1ca0ced289).

We could get do away with the [commit](https://github.com/phonegap/phonegap-plugin-push/commit/15b76632ac2849f1cb2f48e75a5292dfaa97de7f). 


This commit is causing the plugins to be unusable with [react-native-cordova-plugin](http://github.com/axemclion/react-native-cordova-plugin). The fundamental issue is that ReactNative includes plugins as libraries, while Cordova simply changes build files to make plugins a part of the main project. A library cannot have an `applicationID` and thus, this library can only be used when included in a main project as a result of computing `applicationID` in gradle. 

A library cannot really set an applicationID and hence ,

**Comment by darshanar** [comment]
i have added Zopim sdk in build.gradle, I m getting "Failure [INSTALL_FAILED_CONFLICTING_PROVIDER]" , 
As above mention solution applicationID should be in gradle file, my applicationID is already in build.gradle still i m facing the issue.
