### ISSUE TITLE
Background notification does not working in 1.4.x

### ISSUE THREAD

**Issue by sonrebmax** [phonegap/phonegap-plugin-push#324]
For Android 5.0 with phonegap-plugin-push 1.4.2 - notification background is not working, but 1.3.0 is fine working... When app is open, did not get any notification, after closed app (minimzed) and clicked notification that push.on('notification') is fired. Anyone has the same problem? 

Now I am working with phonegap-plugin-push 1.3.0...

**Comment by stinju** [comment]
If I understand correctly, I believe I am having the same issue.  On android, when the app is in the background, an incoming notification will trigger GCMIntentService.onMessageReceived, buzz the app, open the app, but will not trigger my listener (via push.on('notification') in js) to the "notification" event.

**Comment by stinju** [comment]
FYI, downgrading to 1.3.0 also seems to resolve the issue for me.

**Comment by macdonst** [comment]
I'm not sure that I understand your problem. Here is the way it should work.

**App Open**

With the app open your `on('notification')` event handler will always be called. You will not see anything in the notification shade unless you set `options.android.forceShow` to `true`.

**App in Background**

With the app open you will see a notification in the shade as long as your payload from GCM has a title or message component. Your `on('notification')` will not be called in this case. If the user clicks on the notification in the shade your app will start and your `on('notification')` event handler will be called.

If you do not provide a title/message in the payload from GCM then your `on('notification')` event handler will be called as it is assume this is a silent or data only notification.

**App Close (ie not running)**

You are pretty screwed at this point. Need to work on some code to restart the GCM service if the app is killed.

Please let me know if you are running into a problem in any of the above scenarios or if you have a new scenario.

**Comment by stinju** [comment]
This is what is not true for me with 1.4.2: 

> If the user clicks on the notification in the shade your app will start and your on('notification') event handler will be called.

The app starts, but the event handler is not called.  Not completely sure that is the same scenario as sonrebmax.

**Comment by stinju** [comment]
Also, note that if the app is not in the background (no instance running), clicking on the notification in the shade will open the app and in fact call the notification event handler correctly.  The issue I have is strictly when the app is in the background.  I'm using a Moto G on Android 4.4.4, Cordova Android 4.1.1, phonegap-plugin-push 1.4.2.

**Comment by sonrebmax** [comment]
> App Open
> 
> With the app open your on('notification') event handler will always be called. You will not see anything in the notification shade unless you set options.android.forceShow to true.

I done with this options.android.forceShow to true. As I wrote working fine in 1.3.0 not in 1.4.x (I checked 1.4.0 and 1.4.2)

**Comment by stinju** [comment]
@sonrebmax is your issue when the app is open or when the app is in the background?  If we are talking about different things, I'll create a separate thread.

**Comment by sonrebmax** [comment]
I wrote 
> .. When app is open, did not get any notification, after closed app (minimzed) and clicked notification that push.on('notification') is fired.

**Comment by stinju** [comment]
Would you be able to elaborate on that statement a little bit?  Might help me (and maybe @macdonst) understand a little bit more.

**Comment by sonrebmax** [comment]
@macdonst do you understand what I mean? (my english is not good)

**Comment by sonrebmax** [comment]
> App Open
> With the app open your on('notification') event handler will always be called. You will not see anything in the notification shade unless you set options.android.forceShow to true.

in 1.3.0  = OK
in 1.4.2 = does not working - only showing push notification (on('notification') not called in app, so I must to click a push notification then on('notification') is called

> App in Background
> With the app open you will see a notification in the shade as long as your payload from GCM has a title or message component. Your on('notification') will not be called in this case. If the user clicks on the notification in the shade your app will start and your on('notification') event handler will be called.

in 1.3.0  = OK
in 1.4.2 = OK

> If you do not provide a title/message in the payload from GCM then your on('notification') event handler will be called as it is assume this is a silent or data only notification.

in 1.3.0 = does not working
in 1.4.2 = OK (interesting feature)

**Comment by ballenjr** [comment]
Hello @macdonst,

I am trying to prove/use your comment and the readme instructions regarding silent notifications.

I think that some of the confusion may be coming from the various server side implementations.

For instance: the problem that I am having is that when I pass notification: {}, which is where I normally put my title and message properties, I am not getting the onnotification to fire while my app is running, on the other side, in the background.

Can you offer any clarification as to what else may be happening when gcm takes this format or the proper format that gcm will properly deliver? My server logs indicate that it is accepted but since I never get anything back I am unsure if it was mangled somehow to prevent final delivery. 

Or any insight within the assumption that gcm did perform final delivery and this plugins expected final result was what got mangled during transit?

**Comment by ballenjr** [comment]
Nevermind, it appears that the issue was related to other conflicts that I monkey patched with stuff like library overrides. I got rid of the conflicting playservices plugin and now everything is working as it should.

**Comment by ZoRDoK** [comment]
Same problem - silent notifications not received with 1.4+ 

I post them with curl string from google docs - successfull answer but nothing on phone.
