### ISSUE TITLE
[iOS]push.on('registration') doesnt call back

### ISSUE THREAD

**Issue by bAstimc** [phonegap/phonegap-plugin-push#325]
Hi,
I got the problem that the device is registered and also display the notification. But I can't use the Callback function from push.on('registration')  to receive the data.registrationId and additional Data.It just doesn't fire the registration event. 

```javascript
var push = PushNotification.init({ 
  "android": {
    "senderID": "123MYID"
  },
  "ios": {
    "alert": "true",
    "badge": "true",
    "sound": "true"
  }, 
  "windows": {} 
});

push.on('registration', function(data) {
        console.log('REGISTER DEVICE: '+data.registrationId);
});
```
Any clues? :(

**Comment by fredgalvao** [comment]
What do you mean by "display the notification":
- An alert asking the user permission to send him push notifications
- A push notification you sent from your server or a third party service

**Comment by matejkramny** [comment]
```
push.on('registration', function(data) {
        console.log('REGISTER DEVICE: '+data.registrationId);
});
``` 

never gets called. Hope thats clear enough

**Comment by matejkramny** [comment]
For me the ios native dialog appeared, but 'registration' event never fired

**Comment by bAstimc** [comment]
The ios dialog appeared and accepted it. And I received the notifications I sent from the server. 
Well the console calls the native registration and the myDevice's ID but it never fires the javascript registration so I can't get the ID to work with in JS. 
Basicly as @matejkramny told.

**Comment by matejkramny** [comment]
However, when I set a safari breakpoint, it was indeed called.. For some reason the console.log wasn't delivered to safari.

**Comment by macdonst** [comment]
@bAstimc it would be worth running the app in Xcode to see the logs from the native side. They might give us a better clue. You are running the app on a real device right? Not a simulator.

@matejkramny so you are getting the event just not seeing the console.log? Maybe change something in the DOM to make sure the event is received.

**Comment by matejkramny** [comment]
Yeah idk what the issue was, but i set up a breakpoint in safari and it got called. That was enough debugging for me to know this isn't an issue.

**Comment by bAstimc** [comment]
@macdonst yeah I'm running it on XCode + iPhone

and I receive:
Push Plugin register called
Push Plugin register success: <MYID>
Notification received
Push Plugin key: badge


...but not my Logs in registration :(

**Comment by bAstimc** [comment]
Ok I got my mistake. I added into my:

document.addEventListener('deviceready', function () {
... });
and it worked.

**Comment by bAstimc** [comment]
Ok now I don't get the stuff from the notification. So I could grab the information. Well it doesn't show up in logs.  Even in the EventListener it isn't working.

´´´javascript
push.on('notification', function(data) {
      // data.message,
      // data.title,
      // data.count,
      // data.sound,
      // data.image,
      // data.additionalData
      push.finish(function() {
        console.log("processing of push data is finished");
      });
      console.log(data.title+' msg: '+data.message);
    });
´´´

**Comment by kaynz** [comment]
#286

**Comment by macdonst** [comment]
@bAstimc I'm going to close this as your new problem doesn't agree with the title of this issue. If you are still having problem getting a notification open a new issue.
