### ISSUE TITLE
Can't find variable PushNotification

### ISSUE THREAD

**Issue by BishoyA** [phonegap/phonegap-plugin-push#328]
Hello,

I wanted to use this plugin with my phonegap application, it wasn't working, so I decided to build the exact same example provided in the examples/www but it's also not working, (I tested using the Phonegap developer app for ios https://itunes.apple.com/de/app/phonegap-developer/id843536693?mt=8)

I debug it by showing the JS errors in an alert using this:

```window.onerror = function(msg, url, linenumber) {
            alert('Error message: '+msg+'\nURL: '+url+'\nLine Number: '+linenumber);
            return true;
        }```
I get the following error:

ReferenceError: Can't find variable: PushNotification in index.js Line Number:40

Here are the steps I folllowed:

1. create a new cordova project ´phonegap create test´
1. `phonegap platform add ios`
1. `phonegap plugin add phonegap-plugin-push`
1. I copy the files inside `examples/www` to the project's www.
1. added the debugging code to the index.js
1. phonegap build
1. phonegap serve
1. tested it on my phonegap developper app.

am I doing it wrong?

**Comment by macdonst** [comment]
@BishoyA Yes, the PhoneGap Developer App currently does not support the PushNotification plugin. That is, the native code required for the push plugin is not compiled into that app. It is on my to do list to add it to the dev app so that people can test easier.

**Comment by BishoyA** [comment]
Okay, yes thanks for your answer! I was able to test it on a mac using `cordova run ios` using the ios-sim.

**Comment by BishoyA** [comment]
Okay, as an update, this one also failed, I had to do a live device test anyway..

**Comment by macdonst** [comment]
Correct push notifications don't work on the ios-sim.

**Comment by himanshutecstub** [comment]
Same issue try to build on https://build.phonegap.com with below code
```
<engine name="cordova" version=">=6.4.0"/>
<engine name="ios" version="~4.3.0"/>
```
```
<plugin name="phonegap-plugin-push">
   <param name="SENDER_ID" value="ID" />
</plugin>
```
