### ISSUE TITLE
GCM provides different registratinId in iOS and Android

### ISSUE THREAD

**Issue by dorraba** [phonegap/phonegap-plugin-push#329]
I am using phonegap with the phonegap-plugin-push plugin and when I try to register with an Android device I get the following registrationId:

c1p9kF2DLDc:APA91bEPdXIW-_5myCTr_QrHcCD2UGrLOMe82jB84LMmaqXhkTrMRoTdvi-u2NXG9_Qe9mv5SwpSzvtdIe33bPh8m7Kcv_x6PHMihF-syBxs-KSTVhCU7EWysl8a-F61hAJ_zqVBGQTr

and when I try the same with iOS device I get the following registrationId

8bf6bfde4482880e3ac51cb790215124b26192d57bfeb7772a3f4c6edc58711d

When I try to send a notification with the key I got from my android device, everything works great, but when I try to send a notification to my iOS device I get a response of INVALID_REGISTRATION from GCM.

I have done everything in that was wrote in the GCM website, got a development certificate from apple developer and registered it in GCM and everything went well.

Does anyone has an idea?

**Comment by macdonst** [comment]
@dorraba what version of the plugin are you using? The latest 1.4.2 does not support registering with GCM from iOS. There is a fork to provide that functionality but it hasn't been merged at this point.

**Comment by bAstimc** [comment]
The thing is that you need cocoapods etc: https://developers.google.com/cloud-messaging/ios/client
I tried it with another plugin and only destroyed my project. 
I hope it will be merged soon.

**Comment by gamaralf** [comment]
@macdonst I am interested in using only GCM to deliver notifications to IOS and Android. 

Which fork provides this functionality?

**Comment by macdonst** [comment]
@gamaralf see this PR https://github.com/phonegap/phonegap-plugin-push/pull/282
