### ISSUE TITLE
app closed launch function??

### ISSUE THREAD

**Issue by eros2187** [phonegap/phonegap-plugin-push#333]
hello I wanted to know if it was possible to launch a function of timing and make it run even if the app is closed ?
there is a plugin as it does wotzapp that remains always open to speak!!
thank you

**Comment by nicoabie** [comment]
To launch it where? If the app is closed you don't have access to the webview. Could you elaborate?

**Comment by EternallLight** [comment]
Hello,
I have probably a similar question. 
Is it possible to launch the app if it is closed on receiving a notification? I tried the high with notifications with high priority - unfortunately, it does not help.

**Comment by nicoabie** [comment]
If the app is not running (the plugin's webview is null) it caches the notification payload data [see here](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/android/com/adobe/phonegap/push/PushPlugin.java#L185)
When the user taps on the notification that launches the app and when you register the notifications callback you are going to receive the cached payload. Is that not working for you?

**Comment by EternallLight** [comment]
Nicolás, thanks for your quick response.
Sure, it's working. However, in our case, we need to get the app running immediately without a notification (no 'title' or 'body' to specify in the payload) - say, for an incoming call, which is supposed to fire once the app gets loaded. I thought it's a default behaviour for all high priority notifications, but it seems that I was wrong.

**Comment by nicoabie** [comment]
I think I see what you mean, but I don't know if that is possible check [this link](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html) about content-available flag.
I'm not sure if you can put the app in foreground.
There is some work being done on android to emulate that behavior aswell [this issue](https://github.com/phonegap/phonegap-plugin-push/issues/293)

**Comment by EternallLight** [comment]
From [this changes](https://github.com/phonegap/phonegap-plugin-push/commit/2b156daf2a2e0b9943fda03e1a6f52632e891394), I see that the behaviour with "content-available: 1" is the same as now with no "title" and "body" keys. Unfortunately, it does not instantly launch the application if it is closed - the notification gets delivered to JavaScript only on the next app run.

**Comment by nicoabie** [comment]
Yes exactly, I don't know if it is possible to launch it without user interaction.

**Comment by EternallLight** [comment]
Well, Skype somehow does that unless force closed. Now I'm trying to figure out how.

**Comment by nicoabie** [comment]
True, keep us updated with your findings ;)

**Comment by EternallLight** [comment]
Works! :)
What I did is added a new parameter, "force_launch". If received a message with "force_launch": 1, it restarts the PushHandlerActivity, onCreate method of which restarts the MainActivity. This makes the app start if it was closed or move to foreground if it was hidden. I can push the changes if you need them.

**Comment by nicoabie** [comment]
Please do so @EternallLight, then some work will need to be done on the other platforms but it is a good start to begin with! Thanks.
@macdonst do you agree?

**Comment by EternallLight** [comment]
I've [made a fork](https://github.com/EternallLight/phonegap-plugin-push) and committed my changes there. Not sure what branch I have to make a pull request for. Since it's done only for one platform, it might be a good idea to create a separate branch for this, wait until another platforms will be ready, and merge it to the next release branch.

**Comment by macdonst** [comment]
@EternallLight please just submit a PR for it. Sometimes what is possible for one platform is not possible for another, no sense depriving folks of the new functionality.

**Comment by EternallLight** [comment]
@macdonst I've just submited a pull request, please check it out.
