### ISSUE TITLE
No notification at all

### ISSUE THREAD

**Issue by riccardoSocialcities** [phonegap/phonegap-plugin-push#336]
Helllo guys,
i am moving from the old push notification plugin to this one, but i can't success in showing the actual notification.

I am using the example provided in this repo but without results. 
The registration works, but not the notification event (i got a sucess answer from the gcm endpoint, so i guess that the notification arrived to my device but for some reason it wont show). 

Is this working for you?
I am testing on a Samsung tablet with Android 5.1.1 and i tested the latest version of the plugin and the 1.3.0

Thanks!

**Comment by bau720123** [comment]
hi @riccardoSocialcities 
the latest for now is 1.4.2

**Comment by macdonst** [comment]
@riccardoSocialcities getting a success answer from the gcm endpoint only means that gcm has successfully gotten the message, not the device.

What payload are you sending to the device? Can you run `adb logcat | grep PushPlugin` from the command line to see if the plugin is receiving the message. Is your app open or minimized when you send the push? An open app should get the `on('notification')` event handler called, a minimized one should get a notification in the shade if a title or message are provided.

**Comment by macdonst** [comment]
@riccardoSocialcities re-open if still a problem.
