### ISSUE TITLE
No Call to registration event

### ISSUE THREAD

**Issue by PvanHengel** [phonegap/phonegap-plugin-push#339]
I am trying to use this plugin from Monaca, which is using cordova 4.1.0 i believe.  I am running ios 9.  When the app starts it is making the proper call to init, no failures or errors.  I can also update the badge counts, but for some reason I cant get the registration id (device token) back so I can test pushing a notification to the app.  I have tried from 2 different devices and get the exact same result.  Been trying for hours to get this to work, i wonder if there is a bug with the latest build?

**Comment by fredgalvao** [comment]
Are you trying on real devices or is that on emulators?

**Comment by macdonst** [comment]
@PvanHengel what you describe is usually a problem with certificates. Can you run the app in Xcode to see it's logs?

**Comment by andreialecu** [comment]
I had the same issue and it was driving me crazy. After some debugging, I noticed that the logs from the device said something among the lines that `Plugin 'PushPlugin' not found or is not a CDVPlugin`, even though it was there in the xcode project.

I think this happened because I ran `cordova plugin remove` on the old, deprecated push plugin and the two somehow conflicted. What fixed it for me was to remove/readd this plugin once again.

**Comment by karthikeyan-perpetua** [comment]
Hi @macdonst 

This my code 

  var push = PushNotification.init({
            "android": {
                "senderID": "**********"
            },
            "ios": {"alert": "true", "badge": "true", "sound": "true"}, 
            "windows": {} 
        });
        
        push.on('registration', function(data) {
            console.log("registration event");
            document.getElementById("regId").innerHTML = data.registrationId;
            console.log(JSON.stringify(data));
            alert(data.registrationId);
        });


I have received following error on Xcode  - 
Push Plugin register called
PushPlugin.register: setting badge to false
PushPlugin.register: clear badge is set to 0
Push Plugin register failed

**Comment by macdonst** [comment]
@PvanHengel re-open if it is still a problem
