### ISSUE TITLE
Forcing registration

### ISSUE THREAD

**Issue by ghost** [phonegap/phonegap-plugin-push#341]
I was wondering if there is a way to force my app to register again after it has been deregistered.

At the moment my application has a toggle to enable or disable push notifications,
I would like my app to reregister itself if users enable push notifications after they have disabled it.
Right now this only works when the app is restarted, since the PushNotification.init is called after the splash screen loads.

I have written a workaround that prompts the user to restart the app after they've changed the setting, but I would like a cleaner way to do this without restarting the application.

Thanks in advance

**Comment by macdonst** [comment]
You just need to call PushNotification.init() any time you want to re-register.
