### ISSUE TITLE
on("notification") dont fire when the app its open

### ISSUE THREAD

**Issue by Menusito** [phonegap/phonegap-plugin-push#351]
hello im trying to catch the push notification when the app its open but the event on("notification") just work when the app its closet.

if i touch the notification when the app its on background nothing happens like when its open.

**Comment by avielfedida** [comment]
Hi, I was thinking same as you that the problem is with the plugin, take a look at the post I made it will clear things up: https://github.com/phonegap/phonegap-plugin-push/issues/335

**Comment by Menusito** [comment]
i finally found the problem and its just with ios6, android crosswalk and ios>7 works well. but ios6 dont support the callback .on("notification")
