### ISSUE TITLE
on registration callback getting called repeatedly.

### ISSUE THREAD

**Issue by efanurag** [phonegap/phonegap-plugin-push#353]
I put a console in handler for registration success. which is printing repeatedly.

**Comment by macdonst** [comment]
@efanurag not even close to enough information for a meaningful answer.

**Comment by efanurag** [comment]
@macdonst Sorry for bothering you with in sufficient information.

I have written a JavaScript function which is supposed to call when the registration request for receiving cloud notification for ios is successful.

This callback function is getting called repeatedly like it is called in loop on iOS. Though the same function is working fine on Android and is called only once for GCM registration.

**Comment by macdonst** [comment]
@efanurag what version of the plugin are you using? What version of iOS is exhibiting this problem? Can you show your code?

**Comment by kishorpawar** [comment]
@macdonst I just added plugin to app by 
Cordova plugin add <github URL to plugin>.

On deviceready event I am doing

var push = Pushnotification.init(<options>);

push.on('register', onRegister);
push.on('notification', onNotification);

and onRegister is defined as follow.

function onRegister(data){
     console.log(data);
}

Now data is getting printed indefinitely.

Please bear with me, I am writing this on my phone and I am off to work, so whatever I can recall I wrote it here.

Hope you understand the problem I am facing.

**Comment by kishorpawar** [comment]
Ios version is 9.1

**Comment by kishorpawar** [comment]
phonegap-plugin-push 1.4.2 "PushPlugin"

**Comment by kishorpawar** [comment]
Simon happy to say that your plugin is fine, the culprit is another Cordova plugin.

**Comment by macdonst** [comment]
@kishorpawar & @efanurag can this issue be closed then? 

Also, what is the other plugin causing the issues?

**Comment by kishorpawar** [comment]
Yes, You can close this issue.

Somehow the callback for onRegister was getting called indefinitely when we add that plugin.
