### ISSUE TITLE
Conflict when compiling with com.google.maps

### ISSUE THREAD

**Issue by ballenjr** [phonegap/phonegap-plugin-push#355]
I have traced it back to com.google.playservices which is a dependency of com.google.maps(https://github.com/wf9a5m75/phonegap-googlemaps-plugin/). 

Is is possible to defer to the playservices if present?

Version: 1.4.3

Specific error is:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processX86DebugResources'.
> Error: more than one library with package name 'com.google.android.gms'
  You can temporarily disable this error with android.enforceUniquePackageName=false
  However, this is temporary and will be enforced in 1.0
```

**Comment by ballenjr** [comment]
I already tried namespacing the playservices plugin. But that didn't work. For some reason the maps plugin can't find the library/framework. I think it might be wrapping it but I'm not sure why.

**Comment by ballenjr** [comment]
Nevermind, I updated to the latest version now curated by @Hirbod and removed the offensive playservices plugin and now it compiles.

**Comment by ballenjr** [comment]
Thanks for all of the commits. Can't wait for clustering. I'll see if I can drum up some donations.

**Comment by macdonst** [comment]
Yeah, if you use version 1.2.8 or greater of phonegap-googlemaps-plugin you won't have this problem.
