### ISSUE TITLE
xcode build fails with phonegap-plugin-push

### ISSUE THREAD

**Issue by yzargari** [phonegap/phonegap-plugin-push#358]
Hi guys,

I'm working on a phonegap project for a while for Android and the phonegap-plugin-push works very well. I'm now starting to build and test for iOS and am having trouble compiling with phonegap-plugin-push enabled. If I remove the plugin, the project compiles with no problem.

In xcode, the error message says ARC Semantic Issue at line 154:
No visible @interface for 'UIApplication' declares the selector 'currentUserNotificationSettings'

Phonegap CLI v5.3.7
phonegap-plugin-push v1.4.3
platform: ios 3.9.2
Xcodec 5.1.1 on Mac OS X 10.8.4

Target device tested is iPhone 4 with iOS 7.1.2.

I'm not sure if its a bug or its me who doesn't know what he's doing :-/ (building for iOS is new to me)

Thanks,
Joseph.

**Comment by macdonst** [comment]
@yzargari please upgrade to Xcode 7.

**Comment by yzargari** [comment]
I was afraid that might be the answer (I'm on an old Mac that can't be upgraded beyond Mountain Lion, which means I can't go beyond Xcode 5.1.1). I'll borrow a newer Mac from someone and try it out...
