### ISSUE TITLE
v1.4.4 - Error: Cannot evaluate module 23+

### ISSUE THREAD

**Issue by omaxlive** [phonegap/phonegap-plugin-push#363]
I have this error after installing the plugin, any idea why?

Error:A problem occurred configuring root project 'android'.
> Cannot evaluate module 23+ : Configuration with name 'default' not found.

More info:
phonegap-plugin-push 1.4.4 "PushPlugin"

I'm using ionic I've tried installing in both ways with the same result:
1: ionic plugin add phonegap-plugin-push
2: phonegap plugin add phonegap-plugin-push   

![captura de pantalla 2015-11-20 a las 12 58 39](https://cloud.githubusercontent.com/assets/3239132/11299365/7b9e307c-8f86-11e5-8de2-4b721fa42afc.png)

**Comment by macdonst** [comment]
@omaxlive how are you building this? I can't reproduce when building from the command line.

**Comment by omaxlive** [comment]
@macdonst  I'm building from Android studio, I never had this problem with other plugins.
Similar issue: 
- http://stackoverflow.com/questions/22547364/configuration-with-name-default-not-found-android-studio
- http://stackoverflow.com/questions/22743582/error-configuration-with-name-default-not-found-in-android-studio

**Comment by macdonst** [comment]
@omaxlive I've built a project with the CLI and inside Android Studio and can't reproduce your issue. 

The "23+" probably refers to "com.android.support:support-v13:23+", do you have Android Support Library and Repository installed?

**Comment by omaxlive** [comment]
@macdonst Yes it's updated... I tried with a new project and it works fine, so I don't what is the problem. Maybe the cordova version? do you know how to get the cordova version of the project?

**Comment by bau720123** [comment]
hi @omaxlive 
use this line in your command line
```
cordova -v
```

**Comment by macdonst** [comment]
@omaxlive I'd try deleting the platforms directory in your project and starting again by doing a:

`cordova platform add android`

**Comment by macdonst** [comment]
Re-open if still a problem.
