### ISSUE TITLE
Global object "PushNotification" is an empty function on Android

### ISSUE THREAD

**Issue by vilhelmjosander** [phonegap/phonegap-plugin-push#365]
Hi,

I have a problem getting this to work on my android device (Android 4.4.2). Everything works fine on iOS but on Android the global PushNotification object is not an object, just an empty function:

https://www.dropbox.com/s/jxfgpwaurntmhpk/Screenshot%202015-11-20%2016.05.48.png?dl=0

I am using cordova version 5.1.1 and installed the plugin using "cordova plugin add phonegap-plugin-push".

Any ideas on this issue?

**Comment by macdonst** [comment]
@vilhelmjosander are you trying to call the init method before the "deviceready" event occurs?

**Comment by vilhelmjosander** [comment]
@macdonst No, I have an ember initializer which doesnt advance the application until the deviceready-event is fired. 

Also, you have to log in to the application before the init method is called. So the deviceready-event should always have been fired before the init-method.

**Comment by vilhelmjosander** [comment]
@macdonst My bad, I updated from the old push-plugin and forgot to remove the old PushNotification.js from my index.html. Sorry about that!
