### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by kfmaurice** [phonegap/phonegap-plugin-push#367]
Hi there,

first of all, many thanks for the plugin. I'm doing some hybrid development for IPhone and had an issue while building a project with your plugin. I got in fact the following error from the **AppDelegate+Notification.m** file:

> Method definition for 'application:didReceiveRemoteNotification:' not found

What I did to fix it was simply to change the definition for the didReceiveRemoteNotification handler in **AppDelegate+Notification.h** i.e.

```- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler;```

As I actually have no experience with Objective C but rather with JavaScript and C#, I just thought you should know and check whether this change won't raise other issues somewhere else. Anyway, my current setup for the development is:

* Latest version of your plugin
* OS El Capitan
* XCode 7.1
* Ionic CLI Version 1.7.7
* Cordova 5.3.3
* IPhone 4s device

Cheers,

Maurice

**Comment by macdonst** [comment]
@kfmaurice thanks for the heads up, it's just a build warning not an error but I've pushed a fix.
