### ISSUE TITLE
register event not getting called 

### ISSUE THREAD

**Issue by teledna** [phonegap/phonegap-plugin-push#370]
i have the following code in onDeviceReady methd

var push = PushNotification.init({ "android": {"senderID": "12345679"},
         "ios": {"alert": "true", "badge": "true", "sound": "true"}, "windows": {} } );

    push.on('registration', function(data) {
        alert(data.registrationId);
    });

    push.on('notification', function(data) {
       
    });

But registration event is not getting called. We are testing on ios 9 device

**Comment by macdonst** [comment]
@teledna did you setup your certificates correctly with Apple?

**Comment by teledna** [comment]
Thanks for your reply.Its working

**Comment by grmmph** [comment]
Hey.
I'm facing the same problem. Can you please explain what you did that made it work? If it was indeed related to apple certification, can you let me know what fixed that for you?

**Comment by teledna** [comment]
We have upgraded our cordova version to 5.0
