### ISSUE TITLE
Background push notifications not working on iOS

### ISSUE THREAD

**Issue by elliotdennis** [phonegap/phonegap-plugin-push#372]
I've been using version 1.4 of this plugin and I cannot seem to get notifications to work in the background. The plugin works perfectly fine in the foreground, but will not wake my app up to complete the push.on('notification') event in the background. Any advice would be appreciated!

My payload is like:
{ 
   "aps": {
        "alert": "Some alert",
        "badge": "1",
        "message": "some message",
        "userid": "3",
        "category": "message",
        "content-available": "1"
   }
}

**Comment by rodneyworkman291** [comment]
+1

**Comment by macdonst** [comment]
Small but important difference with the payload. iOS requires the value of `content-available` to be a integer. So send:

```
{
  "aps": {
    "alert": "Some alert",
    "badge": "1",
    "message": "some message",
    "userid": "3",
    "category": "message",
    "content-available": "1"
  }
}
```

and it should work, at least it just did for me :)

**Comment by elliotdennis** [comment]
I tried that as well, still no luck. The notification only works if you are in the app or you click on the notification in the shade.

**Comment by macdonst** [comment]
@elliotdennis try running the app from within Xcode to see what the logs are saying.

**Comment by elliotdennis** [comment]
I ran the app within Xcode, but it didn't call the push.on('registration') method, so no luck there.

**Comment by macdonst** [comment]
@elliotdennis how are you sending the push? I've successfully been able to do this via Amazon SNS and node-apn. Also, if you can't get the `registration` event in Xcode then something is really wrong.

**Comment by elliotdennis** [comment]
I've been using pushsharp for sending the apn, since I am using C# web api for the server-side code. But I also tested using a mac application called "Easy APNs Provider". Both have yielded the same result. Also, whenever I build the app through phonegap build, I have no problem getting the registration event to fire, only have that issue whenever I run it in Xcode.

**Comment by fredgalvao** [comment]
You're most probably running into certificate and provisioning profile errors then, considering that PhonegapBuild is able to make it work (probably caused by the fact that you have the right certificates/provisioning profiles configured at PhonegapBuild, but not in your XCode).

**Comment by adrianowead** [comment]
Hi, this problem still exists?
I'm trying but still not working push notification on ios when app is closed.

It are working prefectly when app is in foreground, but not in background.

Anyone can help me?

I'm sending the push from a PHP server, my certificates are ok, my payload is like this:

```javascript
{
  "aps": {
    "alert": "Some alert",
    "badge": "1",
    "message": "some message",
    "content-available": 1
  }
}
```

But the devices never receive, the alert and badges does not work.

I think that problem, is because te app are only in development, we not send to Apple Store.

I not use the phonegap build, I'm running with:

cordova build ios

And build and install on device with xcode.

In xcode, is enabled push notifications and remote notifications.

Any ideas?

**Comment by macdonst** [comment]
@adrianowead I cannot reproduce your problem. How do you know the app does not receive the push message in the background? Do you see it in the shader when you send it because your push above should also trigger the OS'es UI.

**Comment by adrianowead** [comment]
@macdonst 
Thank you very much, for your attention.

I tried for days to solve this problem, do not know exactly what the problem was.

But I deleted everything, the platform folder and plugins.

I reinstalled all of the project and is now working properly.
