### ISSUE TITLE
run error in cordova 5.4.0

### ISSUE THREAD

**Issue by FaisalAriyanto** [phonegap/phonegap-plugin-push#373]
im upgrade my cordova and reinstall this plugin but error

...\platforms\android\build\intermediates\explo
ded-aar\com.google.android.gms\play-services-base\7.8.0\res\drawable-xhdpi\commo
n_signin_btn_icon_disabled_focus_light.9.png -o 

...\platforms\andro
id\build\intermediates\res\debug\drawable-xhdpi-v4\common_signin_btn_icon_disabl
ed_focus_light.9.png
Error Code:
        42
Output:

...\platforms\android\build\intermediates\exploded-aar\com.
google.android.gms\play-services-base\7.8.0\res\drawable-xhdpi\common_signin_btn
_icon_disabled_focus_light.9.png ERROR: Unable to open PNG file

why?

**Comment by macdonst** [comment]
@FaisalAriyanto no idea. I would suggest that you remove your platforms directory and re-add it using `phonegap platform add android` then try building again.

**Comment by macdonst** [comment]
If this is still a problem then re-open
