### ISSUE TITLE
New android permission model

### ISSUE THREAD

**Issue by fredgalvao** [phonegap/phonegap-plugin-push#376]
With all of these released [`Android Marshmallow`, `cordova-android@5.0.0`, **all official cordova plugins updated**], we need to make sure we're up to date with the new permission model for android 6.0.
I'm not a plugin developer, nor am I sure that we even need to do any change, but better safe than sorry, so:

Does the following code require us to update our `PushPlugin.java`?

```xml
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
<uses-permission android:name="android.permission.VIBRATE"/>
<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
<permission android:name="$PACKAGE_NAME.permission.C2D_MESSAGE" android:protectionLevel="signature" />
<uses-permission android:name="$PACKAGE_NAME.permission.C2D_MESSAGE" />
```

[Android permission documentation](http://developer.android.com/intl/pt-br/training/permissions/requesting.html)
[cordova-android@5.0](https://cordova.apache.org/announcements/2015/11/09/cordova-android-5.0.0.html)
[cordova-android plugin documentation updated](http://cordova.apache.org/docs/en/latest/guide/platforms/android/plugin.html)

**Comment by macdonst** [comment]
@fredgalvao I believe that all of those permissions are `NORMAL` and do not require that we prompt the user. I have installed an app with push onto an Android M device and it ran fine however, I should double check it was targeting sdk 23.

**Comment by macdonst** [comment]
Tested with Cordova Android 5.0.0 and there are no permission issues.
