### ISSUE TITLE
Error is coming on v1.4.4

### ISSUE THREAD

**Issue by madhabnath** [phonegap/phonegap-plugin-push#378]
I have installed as per steps provided on the plugin.

It gives currently 52 errors related mostly with the following type -

![image](https://cloud.githubusercontent.com/assets/16030963/11420376/bc3a10fc-9453-11e5-8d1c-cfccde8b2815.png)

![image](https://cloud.githubusercontent.com/assets/16030963/11420696/ce47d782-9455-11e5-9c06-4324a8876f3b.png)

I have updated the SDK Manager with the latest version and issue is still coming -

![image](https://cloud.githubusercontent.com/assets/16030963/11420405/ed53be9a-9453-11e5-832f-0bab34bcdcf6.png)

I have also checked the Manifest.xml and config.xml file and they seems fine as per the plugin installation guideline.

![image](https://cloud.githubusercontent.com/assets/16030963/11420491/6c165292-9454-11e5-81b5-9a3ec5760332.png)

![image](https://cloud.githubusercontent.com/assets/16030963/11420502/7f9726ac-9454-11e5-9488-49e6d4dac5a7.png)

I have checked the build.gradle file too and it also seems fine -

![image](https://cloud.githubusercontent.com/assets/16030963/11420443/28cb600e-9454-11e5-8ae3-09e484bad076.png)

Please let me know, if anybody have any suggestion on the same.

**Comment by fredgalvao** [comment]
Can you build your project through the command line?

I have come to **not** trust Intellij IDEA or Android Studio with gradle stuff with some recent updats, so I'd rather trust a true error from `cordova compile android` itself.

**Comment by omaxlive** [comment]
I was able to solve this, is it solved? if not, I can explain

**Comment by madhabnath** [comment]
No, problem still persists. Can you please explain?

**Comment by omaxlive** [comment]
Okey, go to: 
- File > Project Structure --> 
- Modules: android. the "Dependencies" tab
- Press the plus button to add a "Library dependency" ("com.android.support:support-v4:23.1.1" and com.google.android.gms:play-services:8.3.0)
![captura de pantalla 2015-12-01 a las 11 48 12 1](https://cloud.githubusercontent.com/assets/3239132/11498909/a349f422-9822-11e5-8d4a-6d4153550342.png)

**Comment by madhabnath** [comment]
If you check my build.gradle settings, I had already added these dependency. I will try to fresh install the latest version of Android Studio and try to configure it through Gradle Build system now. Hope it will show some result.

**Comment by omaxlive** [comment]
@madhabnath Perfect! I will wait your feedback.

**Comment by macdonst** [comment]
closing, re-open if still a problem
