### ISSUE TITLE
Platform support

### ISSUE THREAD

**Issue by fredgalvao** [phonegap/phonegap-plugin-push#379]
We have no specification on what version we support for any of the supported platforms, and the cordova version specified is very old ([23 Jul 2013](https://cordova.apache.org/blog/releases/2013/07/23/cordova-3.html)).

I was digging, and found that gradle support, which we count on, started being mentioned at [`cordova 3.6`](https://github.com/apache/cordova-docs/blob/master/www/_posts/2014-09-08-cordova-361.md). However, we state in `plugin.xml` that we only require it to be higher than **3.0.0**.
Digging deeper, the docs state that gradle started being used as the main build system only on [`cordova-android@4.0.0`](https://github.com/apache/cordova-docs/blob/master/www/docs/en/5.0.0/guide/platforms/android/tools.md).
Is this assumption safe? Shouldn't we bump them to the following?

```xml
<engine name="cordova" version=">=3.6.3" />
<engine name="cordova-android" version=">=4.0.0" />
```

**Comment by macdonst** [comment]
Change made

**Comment by derwaldgeist** [comment]
A question on this: As stated in Issue #405, I am trying to use this plugin in combination with Meteor 1.1, which is still on cordova-android 3.6.4. Because the latest version 1.4.5 added a requirement for cordova-android 4.0.0, the build failed. So I tried version 1.4.4, but got the error message below.

I tracked down the change to plugin.xml to understand why this restriction had been added and found this issue here. You state that the change was made because Gradle requires 4.0.0. On the homepage of the Telerik push notification plugin (https://github.com/Telerik-Verified-Plugins/PushNotification) I read that it is also using Gradle, but this would be available since cordova-android 3.6.0.

So I am wondering if my error message is related to Gradle (I don't know this technology), or anything else is going wrong with my build? It's missing a file named local.properties.

Here's the full message:

```
/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Error during processing of action! Attempting to revert...
Failed to install 'phonegap-plugin-push':Error: Uh oh!
ENOENT, no such file or directory
'/Users/waldgeist/Documents/Development/htdocs/aiddogs/webapp/.meteor/local/cordova-build/platforms/android/local.properties'
at Object.fs.openSync (fs.js:439:18)
at Object.fs.readFileSync (fs.js:290:15)
at Object.createEditor
(/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/properties-parser/index.js:328:39)
at Object.module.exports.getProjectSdkDir
(/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:172:49)
at module.exports.framework.install
(/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:120:46)
at Object.ActionStack.process
(/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:72:25)
at handleInstall
(/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:591:20)
at
/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:340:28
at _fulfilled
(/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:787:54)
at self.promiseDispatch.done
(/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:816:30)
Error: Uh oh!
ENOENT, no such file or directory
'/Users/waldgeist/Documents/Development/htdocs/aiddogs/webapp/.meteor/local/cordova-build/platforms/android/local.properties'
at Object.fs.openSync (fs.js:439:18)
at Object.fs.readFileSync (fs.js:290:15)
at Object.createEditor
(/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/properties-parser/index.js:328:39)
at Object.module.exports.getProjectSdkDir
(/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:172:49)
at module.exports.framework.install
(/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:120:46)
at Object.ActionStack.process
(/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:72:25)
at handleInstall
(/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:591:20)
at
/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:340:28
at _fulfilled
(/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:787:54)
at self.promiseDispatch.done
(/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:816:30)


Installing "phonegap-plugin-push" for android
```

**Comment by fredgalvao** [comment]
@derwaldgeist  That doesn't look like anything related to gradle issues. Actually, that's a completely new issue on cordova for me.

In the subject of supporting them, gradle builds have existed in cordova since early cordova-android 3.x.y ([3.6.3 to be precise](https://cordova.apache.org/announcements/2014/09/08/cordova-361.html)) versions, but they were very unstable and incomplete. I wouldn't trust them before 4.0.0 for a serious build with plugins like phonegap-plugin-push or any facebook plugin. That's mainly the reason we bumped the requirements.

Also, cordova-android 3.x.y is already on maintenance lifecycle, and will be deprecated soon, as per the ["3 release deprecation policy"](https://wiki.apache.org/cordova/DeprecationPolicy), so unfortunately (or fortunately) you shouldn't hang on to it much longer.

**Comment by derwaldgeist** [comment]
@fredgalvao Thanks a lot for your quick and detailed reply. So I assume this error is more related to Meteor. I will try an update to Meteor 1.2 now, but this had caused so many problems due to other reasons that I tried to postpone it as long as possible. Obviously, now is the time to get started :-)

**Comment by macdonst** [comment]
@derwaldgeist it actually looks like an ant build issue which confirms that the plugin is not compatible with the older cordova-android.

**Comment by derwaldgeist** [comment]
Thanks for your replies. I updated my Meteor app to Meteor 1.2 in the meantime (which uses a more recent Cordova plugin), and the plugin is working now.
