### ISSUE TITLE
Errors with receiving push notifications (iOS)

### ISSUE THREAD

**Issue by tyronedougherty** [phonegap/phonegap-plugin-push#385]
My initialize function runs well and calls the registration event fine, however, after I begin listening for notifications like so:
```
push.on('notification', function(data){
    console.log(data);
});
```

I begin to get js errors, my angular app does not resolve the controller/view and when a notification is sent I see the output in the terminal:

```
didReceiveNotification with fetchCompletionHandler
app active
Notification received
Push Plugin key: alert
Push Plugin key: badge
Push Plugin key: sound
```

However my callback is not called.

Anyone got any idea what's going on here? Many thanks!

------------------------------------------

Device is running iOS9.1
Cordova version 5.4.0
I installed with
```
cordova plugin add phonegap-plugin-push
```

**Comment by macdonst** [comment]
@tyronedougherty what JS errors are you seeing? Cause it really looks like the message is being received by the native side.

**Comment by tyronedougherty** [comment]
@macdonst Hi, I've determined my problem to be an unrelated issue due to the order in which my initialization happened and then the subsequent listening. I've rectified the issue by making the listening take place after the plugin initialization. Thanks for your help regardless! :)

**Comment by lftakakura** [comment]
I think I'm having the exact same problem.
My code is like this right now:
<pre><code>
        var push = PushNotification.init({
            "android": {"senderID": "123456789"},
            "ios": {"alert": "true", "badge": "true", "sound": "true"}, 
            "windows": {} 
        });
        
        push.on('registration', function(data) {
            console.log("registration event");
            console.log(data.registrationId);
            // send registration id to server!!
            writeServices.updateUser(user, 'reg_id', data.registrationId);
        });

        push.on('notification', function(data) {
            alert('PUSH');
            console.log(data);
            if (!data.additionalData.foreground) {
              $state.go(data.additionalData.to_state);
            }
            // open notification dialog
            // popupProvider.alertPopup('Nova notificação', data.aditionalData.body);
        });
</code></pre>

the alert("PUSH") is being called, but apparently there is no data inside the notification event, so the console.log(data) is not working. I'm also seeing the same output as @tyronedougherty on Xcode.

**Comment by clarklight** [comment]
I am not even getting that alert('PUSH'); called. I get the registration process working fine. Everything worked fine on IOS8.
Does APNS push still works with Development cert?? My php script is saying message delivery successful but with a code of 122, no documentation say what 122 is...

**Comment by tyronedougherty** [comment]
These issues don't appear to be related to mine. Mine was the fact that the init was not getting called before the notification watch handler.

Not sure what is going on with yours but I'd double check that the init method is getting called before watching for notifications.
