### ISSUE TITLE
Register event not getting called on ios

### ISSUE THREAD

**Issue by dhavalmaru** [phonegap/phonegap-plugin-push#386]
We are trying push notification for IOS but Register event is not getting called

My code:
```js
var push = PushNotification.init({
    "ios": {
        "alert": "true",
        "badge": "true",
        "sound": "true"
    }
});

push.on('registration', function(data) {
    alert(data.registrationId);
});
```
Please help me out with this

**Comment by macdonst** [comment]
@dhavalmaru not a lot of info here. Did you setup your iOS certificates properly? Are you testing on an device or simulator cause it will not work on a simulator.

**Comment by dhavalmaru** [comment]
Yes I have setup certificates properly. When I checked my log it is displaying only one line "PushPlugin skip clear badge" and then nothing happens

**Comment by luco** [comment]
+1 Here

**Comment by macdonst** [comment]
@dhavalmaru Did you add an on('error') handler? Can you possibly run it in Xcode to see more log messages?

**Comment by varunvarde2007** [comment]
+1 here getting same issue. Trying to get the error log

**Comment by varunvarde2007** [comment]
Sorry to Bump but any updates on this?

**Comment by fabianoo** [comment]
I'm having the same issue as @varunvarde2007: iOS 9.1, ready event is firing, works on Android, etc.

I tried to get error logs, alerts, etc, but no success. Apparently it fails at the init function.

Any ideas?

**Comment by macdonst** [comment]
All this really seems like a problem with your certificate/mobileprovisioning files. Please run the project from platforms/ios in Xcode and check the logs there to see if anything is reported. I've tried to reproduce on iOS 8.4.1 - iPhone 6+, 9.0, iPod and 9.1 iPad Air 2 and I'm getting the registration event just fine.

**Comment by fabianoo** [comment]
I forgot to come back and give back my answer. I overcame this issue by copying manually the iOS classes of the plugin to the Xcode project and then importing the source in AppDelegate. After this, it worked just fine.

**Comment by csga5000** [comment]
My code is:

```javascript
var app = {
	initialize: function() {
		this.bindEvents()
	},
	bindEvents: function() {
		document.addEventListener('deviceready', this.onDeviceReady, false)
	},
	onDeviceReady: function() {
		console.log("Device is ready!");
		var push = PushNotification.init({
			android: {
				senderID: '8295356133'
			},
			ios: {
				badge: true,
				sound: true,
				alert: true
			},
			windows: {}
		})

		var mylogshouldwork = console.log;

		push.on('registration ', function(data){
			console.log("Reigstered: " + deviceToken)
			mylogshouldwork("Reigstered: " + deviceToken)
			alert("Reigstered: " + deviceToken)
		})

		push.on('error', function(data) {
			console.log("error callback apparently!!!");
			console.log(data);
		});
	}
}

app.initialize()
```

Console output:
Device is ready!

This is on Android, unlike the other posts here.

**Comment by macdonst** [comment]
@csga5000 are you testing on a real device or simulator?

**Comment by csga5000** [comment]
Real device

**Comment by macdonst** [comment]
@csga5000 run `adb logcat | grep PushPlugin` when you start up the app to see if there are any clues there.

**Comment by fabianoo** [comment]
@csga5000 If you do not get any logs from logcat (as @macdonst  said), try to re-add e full rebuild the project.

**Comment by csga5000** [comment]
Log

```
D/PushPlugin(20050): no icon option
D/PushPlugin(20050): no iconColor option
V/PushPlugin(21225): execute: action=init
V/PushPlugin(21225): execute: data=[{"android":{"senderID":"<mysenderid>"},"ios":{"badge":true,"sound":true,"alert":true},"windows":{}}]
V/PushPlugin(21225): execute: jo={"senderID":"<mysenderid>"}
V/PushPlugin(21225): execute: senderID=8295356133
V/PushPlugin(21225): onRegistered: {"registrationId":"cax7dBBOyBY:APA91bHZedMpMtN0lWo8Zy-RaijCTTQTUB4A2Fb3qdzfBjAVSSWloHMSsZWloTeJbsrJ1MYWFAVULhqk_I2JYDdS9fk3k4hjku2Aa766plW657c9atJIXNfo7cwtEgijllHN3T-YHEUP"}
D/PushPlugin(21225): no icon option
D/PushPlugin(21225): no iconColor option
V/PushPlugin(25649): execute: action=init
V/PushPlugin(25649): execute: data=[{"android":{"senderID":"<mysenderid>"},"ios":{"badge":true,"sound":true,"alert":true},"windows":{}}]
V/PushPlugin(25649): execute: jo={"senderID":"<mysenderid>"}
V/PushPlugin(25649): execute: senderID=8295356133
V/PushPlugin(25649): onRegistered: {"registrationId":"cax7dBBOyBY:APA91bHZedMpMtN0lWo8Zy-RaijCTTQTUB4A2Fb3qdzfBjAVSSWloHMSsZWloTeJbsrJ1MYWFAVULhqk_I2JYDdS9fk3k4hjku2Aa766plW657c9atJIXNfo7cwtEgijllHN3T-YHEUP"}
D/PushPlugin(25649): no icon option
D/PushPlugin(25649): no iconColor option

```

Which is helpful, it has "onRegistered" but in the JS I still got: Device is ready!

Note: <mysenderid> is my actual sender id.  I've removed all places where I listed it, because I would guess I don't want that information public.

**Comment by csga5000** [comment]
A little bit of debugging in my end...

It seems like the plugin is working fine...


After the device is registered:
PushPlugin execute line 92 is executed
PushPlugin sendEvent line 195 is executed

Then the plugin result is passed along through a couple cordova classes:

```java
webView.sendPluginResult(pluginResult, callbackId);
```
Gets executed with:  callbackId: "PushNotification1171235816" pluginResult: org.apache.cordova.PluginResult@4371

Then finally in addPluginResult in the NativeToJsMessageQueue class the message that was created is enqued (without force encode using eval) on line 240.

So... I would think something must be wrong with my javascript/cordova/plugin setup

**Comment by fredgalvao** [comment]
Well, to be fair, you haven't registered for the `notification` event, so there's no way you'll be notified when a notification arrives.

**Comment by csga5000** [comment]
@fredgalvao That's not the issue, this is getting the device token.  The code I mentioned is all triggered by the token being registered in the java, but the callback I have for .on('registered') in javascript is never getting called.

**Comment by fabianoo** [comment]
@csga5000 There is a white space on your code here:

    push.on('registration ', function(data){

Did you copy and paste it?

**Comment by csga5000** [comment]
@fabianoo ... Yes that does appear to be the case.  I checked the spelling of that word a few times, but... fail.  That moment when you spend forever trying to figure a problem out and your problem is a single space.  Or some slight different in formatting.

**Comment by fabianoo** [comment]
It is hell, man! In these moments it is nice to have someone else looking/reviewing your code.

I'm glad it helped. :wink:

Regards

**Comment by dolcom87** [comment]
I have the same issue as @dhavalmaru. Register event is not called in the iOS. I tried replace the certificates and provisioning profiles, but it's still unsuccessful

**Comment by dolcom87** [comment]
@dhavalmaru do you solve this problem?

**Comment by dolcom87** [comment]
@fabianoo could you tell me more? How you solved this problem? What do you import in AppDelegate?

**Comment by fabianoo** [comment]
Hello, @dolcom87. Sorry for the delay, but I had a couple of hard weeks.

Are you still facing the same problem? Please, answer me some questions, if you still do:

1) When you run it on a device, debugging by XCode, is there any log by the Push Plugin?

2) Is there this folder _platforms/ios/{project}/Plugins/phonegap-plugin-push/_ with 4 source files inside?

3) May you post here the code of the following files?
- _platforms/ios/{project}/Classes/AppDelegate.m_
- _platforms/ios/CordovaLib/Classes/CDVPlugin.m_

Best Regards,
Fabiano

**Comment by dolcom87** [comment]
@fabianoo thx for your answer. I've already solved it

**Comment by afraniohonorio** [comment]
@dolcom87 How did you solve it?

**Comment by dolcom87** [comment]
@afraniohonorio the problem of my app was not in the plugin. But if it will help you check the next folder and file of your project:
- platforms/ios/www/plugins
- platforms/ios/www/cordova_plugins.js
if it's not exists, then copy manually them from `platforms/ios/platform_www/` and it should work if your problem in it

**Comment by 19akash91** [comment]
i am added cordova plugin add "phonegap-plugin-push" this plugin but not call registration method and error method plz help me

code is here : 

var push = PushNotification.init({
                      android: {
                          senderID: "*********"
                      },
                      ios: {
                          alert: "true",
                          badge: "true",
                          sound: "true"
                      },
                      windows: {}
                  });
                  //alert("push is : "+push);
               //var push = Scopes.get('push');
          push.on('registration', function(data) {alert("in push registration");
                      device=data.registrationId;
                      localStorage.setItem('device_id',device);
                       alert("device id is : "+localStorage.getItem('device_id'));
         });
           push.on('notification', function(data) {
            });
          push.on('error', function(e) {
                                   // e.message
                                   alert("ErrorCallback "+e.message);
          });
     }

**Comment by mkurzweil** [comment]
I'm facing the same problem, everything on android works fine, but it looks like that the registration part will be skipped. @dolcom87 I checked it and there is everything in the ios/.. folder

**Comment by PriyankaRose** [comment]
@afraniohonorio yes we have the 4 files in the mentioned folders. Could you please post the complete answer? It will be helpful for most of the people.

**Comment by PriyankaRose** [comment]
@mkurzweil check whether you enabled push notifications in capabilities tab.

**Comment by roysG** [comment]
same bug, any updates?

**Comment by martygriffin** [comment]
+1

**Comment by andreidiaconescu** [comment]
the same things happens for mee to, on Android:
the event 'registration' is never getting called, so i cannot get the token.
I am using Ionic. the code looks like:

        $ionicPlatform.ready(function () {
            console.log('initialising GCM/APNS app registration for notifications token');
            var push = PushNotification.init({
                android: {
                    senderID: "a37d6c52"
                },
                ios: {
                    alert: true,
                    badge: true,
                    sound: true
                },
                windows: {}
            });

            push.on('registration', function (data) {
                console.log('GCM/APNS app registration EVENT');
                console.log('GCM/APNS app registration for notifications token data received: ' + JSON.stringify(data));
                var token = data.registrationId;

            });

            push.on('error', function (data) {
                console.log("GCM/APNS error event: "+JSON.stringify(data));
            });
        });



Can someone help me a little please ?

**Comment by varunvarde2007** [comment]
The sender Id seems incorrect for Android

**Comment by andreidiaconescu** [comment]
Thank you very much man, you are right.
I corrected the sender id, and now the registration gets called and i get the token.
Thank you !

**Comment by varunvarde2007** [comment]
Thanks happy to help

**Comment by bandhavya** [comment]
I have the same issue. 

My code

var push = $window.PushNotification.init(
                  {
                     ios: {
                         alert: "true",
                         badge: true,
                         sound: 'false'
                     },
                     windows: {}
                     });
                
                push.on('registration', function(data) {
                        alert('iOS reg..');
                        });

registration event is never called.

**Comment by mkurzweil** [comment]
In my case I had to add `gcmSandbox: "false"` to the iOS part.
And as @PriyankaRose mentioned did you enabled push notifications in the capabilities tab?

**Comment by bandhavya** [comment]
Im using APNS and not gcm so I think gcmSandox key is not required
