### ISSUE TITLE
Background notification OK, but event "notification" never called

### ISSUE THREAD

**Issue by cmillauriaux** [phonegap/phonegap-plugin-push#387]
Hi everyone,

I installed the plugins and configure android notifications, but, when i send a notification from my server (node-gcm), the notification is shown in the navbar like the application is in the background. If i click in this notification, nothing happened. The most important is if i add a console.log instruction in the "notification" event, nothins is print in the console. So, i think my notification message is never catch by the plugin. Any idea ?

Server message : 
``` javascript
var message = new gcm.Message({
      collapseKey: "applice",
      delayWhileIdle: true,
      timeToLive: 3,
      notification: {
        title: "Hello, World",
        icon: "icon",
        message: "This is a notification that will be displayed ASAP."
      }
    });
```
Client side : 
``` javascript
self.push = PushNotification.init({
        android: {
          senderID: "blablablabla"
        }
      });

      self.push.on('registration', function(data) {
        console.log('REGISTRATION : ' + JSON.stringify(data));
        if (data && data.registrationId && data.registrationId.length >
          0) {
          // Call token server update
        }
      });

      self.push.on('notification', function(data) {
        console.log('MESSAGE : ' + JSON.stringify(data));
        // Call client user refresh
      });
```

**Comment by macdonst** [comment]
@cmillauriaux trying sending this instead and let me know what you find. I recently discovered that Google will just eat messages sent using the "notification" property and not pass them on to the push handler.

```
var message = new gcm.Message({
      collapseKey: "applice",
      delayWhileIdle: true,
      timeToLive: 3,
      data: {
        title: "Hello, World",
        icon: "icon",
        message: "This is a notification that will be displayed ASAP."
      }
    });
```

**Comment by cmillauriaux** [comment]
@macdonst you're my hero ! Thanks a lot !

I searched desperatly on the plugin side, but it was on the server side. You saved my day !

**Comment by macdonst** [comment]
@cmillauriaux sorry about that, I need to document it better cc: @fredgalvao

**Comment by fredgalvao** [comment]
@macdonst  Funny thing, neither of these are technically wrong.

[Check node-gcm's usage doc](https://github.com/ToothlessGear/node-gcm#usage) and the [official docs on gcm](https://developers.google.com/cloud-messaging/http-server-ref#downstream-http-messages-json), and you'll see that `data` and `notification` are both declared.

- `data`: is supposed to hold extra info, that is passed to the intent on android or to the `AppDelegate application:didReceiveRemoteNotification:` event on iOS. `message`, `title` or `icon` are not supposed to live on this object.
- `notification`: has [its own scheme](https://developers.google.com/cloud-messaging/http-server-ref#notification-payload-support)

Now, if what you said is that for some reason we cannot trust in the `notification` object, I think this should be reported as a bug to google or we're missing something about the handler stuff.

**Comment by fredgalvao** [comment]
Oh, I guess I understand now. There is a distinction between `data payload` and `notifications payload` on the docs. [Source](https://developers.google.com/cloud-messaging/concept-options).

Notification payload

    GCM automatically displays the message to end user devices on behalf of the client app.
    Notifications have a pre-defined set of user-visible keys.
Data payload

    Client app is responsible for processing data messages.
    Data messages have only custom key/value pairs.

So, I'm assuming that we want to handle everything by ourselves, which leaves us requiring the `data payload` in every situation.

    Use data messages when you want to handle the display or process the messages on your Android client app,
    or if you want to send messages to iOS devices when there is a direct GCM connection.


I'll update the docs with a topic on this soon.

**Comment by macdonst** [comment]
@fredgalvao Yup, I found that out while writing a service to send messages using node-gcm. It really tripped me up for awhile. Yes, we will need to be more opinionated and have people use the `data` property in their payload instead of `notification`.

**Comment by fredgalvao** [comment]
@macdonst , does your comment [here](https://github.com/phonegap/phonegap-plugin-push/issues/115#issuecomment-162749334) has anything to do with this? From what I understood, we cannot simply tell users to ignore the `notification` object.

**Comment by macdonst** [comment]
@fredgalvao Yeah, there is an issue with data/notification in that Android and iOS don't treat them the same. I opened #401 to do some testing in the 1.5.x branch. They really should work the same.

**Comment by harslanhafeez** [comment]
I think their is strange issue with this.
When send notification using node-gcm as
gcm.Message( {
            collapseKey: 'applice',
            priority: 'high',
            contentAvailable: true,
            delayWhileIdle: true,
            timeToLive: 3,
            data: {
                dataTitle: 'News ....',
                dataMessage: optional.text,
                image: '',
               optional:'blabla',
               other:'blabla'
            },
            notification: {
                title: 'News',
                icon: "www/image/edjunction",
                body: some text
            }
        });
Android shows one perfect notification in Tray(when click on notification data  section not passed to app) and  No Vibrate No sound

 But if data object contain keys title and message like 
data: {
                title: 'News ....',
                message: optional.text,
                image: '',
                optional:'....'
            }
 Android is showing two notification trays one from data object and other one is App Name. In this case Vibration and sound both works.

**Comment by MichaelJCole** [comment]
FYI: https://github.com/ToothlessGear/node-gcm#gcm-client-compatibility lists this as an open bug (Jan 2016).  

Is it still open?

**Comment by macdonst** [comment]
@MichaelJCole send everything in the `data` part of the payload, not the `notifcation` part.

**Comment by sam2x** [comment]
Hey, anyone experiencing my case : 

- When using data part only, i got sound + only title (no message, nor body) 
- When using notification part, i got title + body of the notification, but no sounds....
