### ISSUE TITLE
Getting Empty image on Picture Notification

### ISSUE THREAD

**Issue by manikumarkv** [phonegap/phonegap-plugin-push#388]
i am getting empty image notification. I am new to use this plugin

Note : I am getting this JSON on received

{"title":"title text message",
"message":" Coupon Image",
"additionalData":
 {
 "picture":"http://11.11.11/Images/UploadedImages/graphicImages/graphic-notification66.jpg",
"style":"picture",
"coldstart":false,
"foreground":false
 }

Can you please help me .... ?

**Comment by macdonst** [comment]
@manikumarkv the picture message only shows up on Android when the app is in the background. You just pull down on the notification to reveal the picture. Also, the URL for your picture doesn't look quite correct.

**Comment by manikumarkv** [comment]
@macdonst Thanks for your reply. 

i gave wrong image url path wantedly on my post. 

even when the app is running i got the same issue. can you suggest me where i can debug this 

![not](https://cloud.githubusercontent.com/assets/3167768/11506007/232b960a-9873-11e5-8af8-2ef2997dd24a.jpg)

**Comment by macdonst** [comment]
@manikumarkv can you try using http://36.media.tumblr.com/c066cc2238103856c9ac506faa6f3bc2/tumblr_nmstmqtuo81tssmyno1_1280.jpg which I am able to get to work to rule out that it isn't something to do with your picture?

**Comment by manikumarkv** [comment]
Yes.. i tried it.

i am getting notification in some deceives correctly(Moto G) 
for the same notification i am getting

**Comment by manikumarkv** [comment]
@macdonst i tried it as you mentioned 

I am testing on multiple devices

i am getting notification correctly for some devices(Moto G- Android 5.1)
at the same notification i am not getting  notification for some devices(HTC Desire 626 -- Android 5.1)
