### ISSUE TITLE
Sound mutes automatically

### ISSUE THREAD

**Issue by ntakos** [phonegap/phonegap-plugin-push#390]
Hi, 

Im developing an app similar to Shazam, whereby the device will listen to the music, retrieve the song, and then play it back on the device.

The issue I have is after the device successfully finds the song, it will play the music back for 1 second, and then mute itself. This is only happening on IOS, as Android is working fine. 

Any suggestion? Ive run out of ideas. 

Any help is appreciated. Thank you

**Comment by macdonst** [comment]
@ntakos what does this have to do with the push plugin?
