### ISSUE TITLE
Using Plugin in Visual Studio 2015 with Windows Phone 8.1, Getting error on cordova-android Version?

### ISSUE THREAD

**Issue by tetreault** [phonegap/phonegap-plugin-push#394]
Hello, 

I'm trying to port someone's Cordova app to a Nokia Lumia phone running Windows 8.1. The project is using Cordova version 4.3.1, 32 bit Windows 8.1 Enterprise Evaluation running through VMWare.   This project is already up and running in iOS and Android using the deprecated prior version of the plugin (it was done last year). We discovered that PushPlugin was not working when we build for Windows Phone 8 in VS2015. 

Our starting point was noticing that we weren't having any functionality occur after `push_notification = window.plugins.pushNotification;`. That lead me to the PushPlugin repo, which then lead me here. I installed this new plugin via the config.xml interface in VS2015 and everything seemed fine. When I try building the project out of curiosity to see what happens (not expecting it to work right out the gate) I am now greeted with the following error upon building: 

``` 
Plugin "phonegap-plugin-push" fetched.
1>  Calling plugman.install on plugin "C:\Users\IEUser\Desktop\TestApp\Test\plugins\phonegap-plugin-push" for platform ....
1>  Installing "phonegap-plugin-push" for android
1>  Running command: C:\Users\IEUser\Desktop\TestApp\Test\platforms\android\cordova\version.bat
1>  Command finished with error code 0: C:\Users\IEUser\Desktop\TestApp\Test\platforms\android\cordova\version.bat
1>  Failed to install 'phonegap-plugin-push':CordovaError: Plugin doesn't support this project's cordova-android version. cordova-android: 3.7.2, failed version requirement: >=4.0.0
1>      at checkEngines (C:\Users\IEUser\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:116:29)
1>      at C:\Users\IEUser\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:289:16
1>      at _fulfilled (C:\Users\IEUser\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:787:54)
1>      at self.promiseDispatch.done (C:\Users\IEUser\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:816:30)
1>      at Promise.promise.promiseDispatch (C:\Users\IEUser\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:749:13)
1>      at C:\Users\IEUser\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:557:44
1>      at flush (C:\Users\IEUser\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:108:17)
1>      at doNTCallback0 (node.js:419:9)
1>      at process._tickCallback (node.js:348:13)
1>  CordovaError: Plugin doesn't support this project's cordova-android version. cordova-android: 3.7.2, failed version requirement: >=4.0.0
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped                   ==========
```

Why would I be getting an error on the Cordova Android version when building for Windows?

**Comment by fredgalvao** [comment]
The error is not actually happening on build-time, but on install-time, which is when cordova realizes that this plugin (`phonegap-plugin-push`) requires a `cordova-android` version higher than **4.0.0** so that we can build with gradle (this plugin requires gradle builds to manage it's dependencies). Unfortunately your project still has `cordova-android@3.7.2`.

I'm afraid cordova will not let you install this plugin for windows only, so you'll need to upgrade your project's `cordova-android` to make them all work in harmony.

**Comment by tetreault** [comment]
@fredgalvao Thanks for the response! Sorry for the naivety but do you think you might be able to point me to where I update this cordova-android version? In the config.xml I see that it uses 4.3.1 and i've been looking around for any mention of a version under 4.0.0 in the project but have failed to find any. If you might be able to point me in the right direction or if i could provide additional info, that'd be extremely helpful.

**Comment by tetreault** [comment]
Worst case scenario I could make a clean project with the same version of cordova (4.3.1) and then add in push notifications and test it out and then port over the other crap from the project that I need. It wouldn't be the end of the world but I'm definitely open to anything faster/more efficient.

**Comment by fredgalvao** [comment]
### What is a version
So, a little bit of confusion here so I'll try to clarify:

A few years ago, cordova was actually split into multiple independent projects, and a whole **cordova application** has many versions involved since then.

The version you mentioned, `4.3.1`, refers to the cli/lib version. This is the **main cordova version number**, and refers to the cordova command line interface and common internal workings (this is the one you install with `npm install -g cordova`). The release note on that version is located [here](https://cordova.apache.org/news/2015/06/04/tools-release.html).

Other than that, we have:
- a lot of low-level modules/projects, which we don't need to look into or care about right now (like cordova-commons, plugman, cordova-docs, etc)
- platform projects which we need to care a lot (this is the one fetched when you do `cordova platform add ...`)
- plugin projects, which we also need to care about (this is the one fetched when you do `cordova plugin add ...`)

You can see the platforms you have installed and their versions by running `cordova platform ls` on your project's root. And then, you can see the plugins you have installed and their versions by running `cordova plugin ls`, also on your project's root.

A plugin, such as `phonegap-plugin-push`, needs to be checked for version dependencies on all of these levels (cli, platforms, and possible plugin dependencies).  If you check the [docs on platform support](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PLATFORM_SUPPORT.md) or the `plugin.xml` file, you'll see some of these version dependencies: 
```xml
<engines>
    <engine name="cordova" version=">=3.6.3" />
    <engine name="cordova-android" version=">=4.0.0" />
</engines>
```

In the end, for this plugin to work, we need gradle builds to be supported, and thus we need `cordova-android@4.0.0` at least (release notes [here](https://cordova.apache.org/announcements/2015/04/15/cordova-android-4.0.0.html)).


### Upgrading cordova-android
To upgrade your project, you have 2 options (I'd rather use the later):

- `cordova platform update android` (there are details on this approach on the release notes mentioned above)
- `cordova platform rm android && cordova platform add android` (this is safer, but will most probably destroy any customizations you might have done to the `platforms/android` folder manually)

**Comment by tetreault** [comment]
Thank you for the excellent response! Again, I really appreciate the help troubleshooting - its been a bit hard finding the information that I've needed on StackOverflow. Now, when I run ```cordova platform rm android && cordova platform add android``` I receive the same error, though its erroring out on ```cordova-plugin-whitelist``` now. Here's the output in the console: 

```
C:\Users\IEUser\Desktop\BeDeltaTest\BeDeltaTest>cordova platform rm android && cordova platform add android
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: io.cordova.myappef62bf
        Name: TestApp
        Android target: android-21
Copying template files...
Project successfully created.
Installing "cordova-plugin-whitelist" for android
Failed to install 'cordova-plugin-whitelist':CordovaError: Plugin doesn't support this project's cordova-android version. cordova-android: 3.7.2, failed version requirement: >=4.0.0-dev
    at checkEngines (C:\Users\IEUser\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:116:29)
    at C:\Users\IEUser\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:289:16
    at _fulfilled (C:\Users\IEUser\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\IEUser\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\IEUser\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\IEUser\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:557:44
    at flush (C:\Users\IEUser\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
Plugin doesn't support this project's cordova-android version. cordova-android:3.7.2, failed version requirement: >=4.0.0-dev
```

So it seems as though I'm not even able to update the Android platform? 

If I run ```cordova platform ls``` I do indeed see the version marked as 3.7.2. In the Cordova docs to update to 4.0.0 it even says you can do ```cordova platform update android``` but even that is showing me the following: 

```
Updating Android project...
Android project is now at version 3.7.2
If you updated from a pre-3.2.0 version and use an IDE, we now require that you import the CordovaLib library project. 
```

Something seems odd here, no?

**Comment by fredgalvao** [comment]
Indeed, something smells. Please try the following:

`cordova platform rm --save android`
`cordova prepare`
`cordova platform add --save android@4.1.1`

**Comment by tetreault** [comment]
@fredgalvao 

So I ran that command and it installed 4.1.1 correctly and saved it to the config.xml file! I ran ```cordova platform ls``` and see it points to android 4.1.1. 

```
C:\Users\IEUser\Desktop\TestApp\TestApp>cordova platform rm --save android
Removing android from config.xml file ...

C:\Users\IEUser\Desktop\TestApp\TestApp>cordova prepare

C:\Users\IEUser\Desktop\TestApp\TestApp>cordova platform add --save android@4.1.1
npm http GET https://registry.npmjs.org/cordova-android/4.1.1
npm http 200 https://registry.npmjs.org/cordova-android/4.1.1
npm http GET https://registry.npmjs.org/cordova-android/-/cordova-android-4.1.1.tgz
npm http 200 https://registry.npmjs.org/cordova-android/-/cordova-android-4.1.1.tgz
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: io.cordova.myappef62bf
        Name: TestApp
        Activity: MainActivity
        Android target: android-22
Copying template files...
Android project created with cordova-android@4.1.1
Installing "cordova-plugin-whitelist" for android
Installing "org.apache.cordova.device" for android
Installing "org.apache.cordova.file" for android
Installing "org.apache.cordova.file-transfer" for android
Installing "org.apache.cordova.inappbrowser" for android
Installing "org.apache.cordova.network-information" for android
Installing "org.apache.cordova.splashscreen" for android
Installing "org.apache.cordova.statusbar" for android
Installing "phonegap-plugin-push" for android
--save flag or autosave detected
Saving android@4.1.1 into config.xml file ...

C:\Users\IEUser\Desktop\TestApp\TestApp>cordova platform ls
Installed platforms: android 4.1.1, windows, wp8
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, windows8
```

Now, with our new android platform I tried rebuilding the project in VS2015 and I unfortunately receive a build error on ```resolving dependencies for configuration ':_debugCompile'.```

Here's the full output: 

```
1>------ Rebuild All started: Project: TestApp, Configuration: Debug Windows Phone 8 ------
1>  ANDROID_HOME=C:\Program Files\Android\android-sdk
1>  JAVA_HOME=C:\Program Files\Java\jdk1.7.0_55
1>  Running: C:\Users\IEUser\Desktop\TestApp\TestApp\platforms\android\gradlew clean -b C:\Users\IEUser\Desktop\TestApp\TestApp\platforms\android\build.gradle -Dorg.gradle.daemon=true
1>
1>  FAILURE: Build failed with an exception.
1>
1>  * What went wrong:
1>  A problem occurred configuring root project 'android'.
1>  > Could not resolve all dependencies for configuration ':_debugCompile'.
1>     > Could not find any version that matches com.google.android.gms:play-services-gcm:+.
1>       Searched in the following locations:
1>           https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
1>           https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/
1>           file:/C:/Program Files/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
1>           file:/C:/Program Files/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/
1>       Required by:
1>           :android:unspecified
1>
1>  * Try:
1>  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
1>
1>  BUILD FAILED
1>
1>  Total time: 4.969 secs
1>  Picked up _JAVA_OPTIONS: -Xmx512M
1>
1>  C:\Users\IEUser\Desktop\TestApp\TestApp\platforms\android\cordova\node_modules\q\q.js:126
1>                      throw e;
1>                      ^
1>  Error code 1 for command: cmd with args: /s /c "C:\Users\IEUser\Desktop\TestApp\TestApp\platforms\android\gradlew clean -b C:\Users\IEUser\Desktop\TestApp\TestApp\platforms\android\build.gradle -Dorg.gradle.daemon=true"
1>C:\Program Files\MSBuild\Microsoft\VisualStudio\v14.0\ApacheCordovaTools\vs-mda-targets\Microsoft.MDA.FileMirroring.targets(354,5): error MSB3073: The command "platforms\android\cordova\clean.bat" exited with code 1.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

Any ideas? I feel like we're a step closer, now that we have the right platform version, yet prior to this I was able to build and deploy the app to the Nokia Lumia (despite it obviously not working).

**Comment by macdonst** [comment]
@tetreault make sure you have all the latest Android tools installed and your $ANDROID_HOME variable is set correctly.

**Comment by fredgalvao** [comment]
We're now on the territory of our docs on this plugin, check the [details on installation](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#android-details).

**Comment by tetreault** [comment]
@macdonst Thanks for the heads up on that, I have up to Android SDK 23, so I suppose I should update anyways to the most recent one. And @fredgalvao thanks for the prompt responses and troubleshooting help. I'll have a go at updating the SDK and will refer back to all the installation instructions. Thanks again guys!

**Comment by vikas0vanvi** [comment]
Hello tetreault  , have come across any solution to this problem ? i am facing same issue

**Comment by tetreault** [comment]
Hey @vikas0vanvi - I ended up getting sort of frustrated with phonegap for the Windows Phone and ended up implementing push notification in C# since we were using the Parse service. However, now Parse is dissolving their services soooooo looks like I'll have some work to do in the future replacing that.

**Comment by fredgalvao** [comment]
@vikas0vanvi the solution to all issues pointed out by @tetreault were solved by comments made by me (he just didn't do a final follow-up). Just read the issue's comments and you should find your fix. If not, please create a new issue.
