### ISSUE TITLE
On iOS 9 the badge does not clear

### ISSUE THREAD

**Issue by adyz** [phonegap/phonegap-plugin-push#395]
My initialization code:

		"ios": {
			"alert": "true",
			"badge": "true",
			"sound": "true",
			"clearBadge": true
		}

This should clear the red badge from the add icon then the app is launched, but it's not. Any ideas?

Thanks

**Comment by macdonst** [comment]
@adyz I can't reproduce this problem at all.

**Comment by adyz** [comment]
@macdonst Thanks for retesting.


Normally, if I use the code above should clear the red badge, right? Or do I need to use the `push.setApplicationIconBadgeNumber(successHandler, errorHandler, count)` function too and set the count to `0`?

Thanks!

**Comment by macdonst** [comment]
@adyz correct, if you set clearBadge to true you don't need to do anything with setApplicationIconBadgeNumber. Each time the app comes into the foreground the badge should be cleared.

**Comment by adyz** [comment]
Our app is live now in the app store, the badge does not clear. Tested on multiple devices with iOS > 9

**Comment by didbarbosa** [comment]
I had the same issue,
"clearBadge": true fixed it

**Comment by adyz** [comment]
My bad here, I thought that once the plugin initialized, it's not necessary to initialize every time the app is closed and reopened.
