### ISSUE TITLE
Push Plugin register failed

### ISSUE THREAD

**Issue by muvaffak** [phonegap/phonegap-plugin-push#399]
Hi,

I'm trying to add that plugin to my phonegap ios app. But there doesn't seem to be installation guides for ios. I'm searching through internet and all I find is related with the deprecated version. Still I try them, but no luck.

I installed it normal way, phonegap plugin add ... But it says "Push Plugin register failed" in the console. 
Here is my code:

```
var push = PushNotification.init({
            ios: {
                alert: 'true',
                badge: 'true',
                sound: 'false'
            },
            windows: {}
        });
        push.on('registration', function (data) {
            console.log("apns id: " + data.registrationId);
        });
```
Edit: Trying on iOS 8.4.1 iPod Touch 6th gen.

**Comment by macdonst** [comment]
@muvaffak Do you get the dialog the first time you try to register that asks to give your app permission to receive pushes? Just wondering if you have your iOS certificates setup correctly.

**Comment by fredgalvao** [comment]
Also, @muvaffak , we don't have installation docs for iOS because there is nothing else to do after you run `cordova plugin add ...`. Might as well improve the docs on this part, anyway.

**Comment by muvaffak** [comment]
It was asking but i found out the problem. I had chosen ios distribution provisioning file, when i changed it to development it worked.

Like this detail, i think there should be a guide which also includes other certification steps.
