### ISSUE TITLE
Register method not working

### ISSUE THREAD

**Issue by jroji** [phonegap/phonegap-plugin-push#4]
Hi, im trying to register a device trough the register method, following your example, but when i call it, the Xcode logs only shows "Push Plugin register called" but no "Push Plugin register success". Cant get the iOS token and complete a successfully register process. Im trying with and iPAD with iOS 8.1.1 and Xcode 6.3.1

if u could help would be great ;)

**Comment by ma-pe** [comment]
I can confirm this issue with on target device: iPhone 5, IOS 8.1.3
Works fine with iPad 4 - iOS 8.0 and iPhone 6+ - iOS 8.3

Xcode is at Version 6.3.1 for all of them

**Comment by ma-pe** [comment]
Update: iPhone 5S - iOS 8.1.2 works fine as well...

Just iPhone 5 - iOS 8.1.3 is calling the PushPlugin but neither entering the success or the fail method.
Any thoughts on that?

**Comment by macdonst** [comment]
@gbenvenuti Thanks for the pull request. I should have been using a clean device when I originally tested this.

**Comment by ma-pe** [comment]
As I mentioned above, the issue is still present, even using the new code: iPhone 5 - IOS 8.1.3

**Comment by macdonst** [comment]
@ma-pe I cannot reproduce.
