### ISSUE TITLE
Make sure iOS/Android can receive the same GCM payload

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-plugin-push#401]
Before releasing 1.5.0 make sure a single push to GCM can reach and Android and iOS device and they behave relatively the same. That is, notification event handler is triggered/push data in notification shade.

**Comment by macdonst** [comment]
Remember to use "body" property in "notification" object not "message".

**Comment by fredgalvao** [comment]
Should this be in the docs?
