### ISSUE TITLE
Android : Action Button Icons don't display, 

### ISSUE THREAD

**Issue by tssutha** [phonegap/phonegap-plugin-push#403]
I followed the given payload guidelines to add action buttons, everything works fine except push notification doesn't display any icons for action buttons. 

Given links about how to copy the icon files to res/drawable folder seems outdated!! I could not figure out how and where to copy the custom icons for action buttons. 
![image](https://cloud.githubusercontent.com/assets/2877714/11685103/9ae6b826-9e9c-11e5-9a8b-67e268ee3aef.png)

Tried to execute the hook script as well, but no help.
module.exports = function (ctx) {
    // make sure android platform is part of build 
    if (ctx.opts.platforms.indexOf('android') < 0) {
        return;
    }

    var filestocopy = [
        {
            "res/icons/android/newitems.png":
            "platforms/android/res/drawable/new.ico"
        },
         {
             "res/icons/android/important.png":
             "platforms/android/res/drawable/important.png"
         },
    ];
    var fs = require('fs');
    var path = require('path'); 
    // no need to configure below
    var rootdir = process.argv[2];
 
    filestocopy.forEach(function(obj) {
        Object.keys(obj).forEach(function(key) {
            var val = obj[key];
            var srcfile = path.join(rootdir, key);
            var destfile = path.join(rootdir, val);
            console.log("src :" + srcfile + "  -- des :" + destfile);
            //console.log("copying "+srcfile+" to "+destfile);
            var destdir = path.dirname(destfile);
            if (fs.existsSync(srcfile) && fs.existsSync(destdir)) {
                fs.createReadStream(srcfile).pipe(
                   fs.createWriteStream(destfile));
                console.log("src :" + srcfile + "  -- des :" + destfile);
            }
        });
    });
};

**Comment by nicoabie** [comment]
Do you have any adb output? Where are the links about how to copy the icon files to res/drawable folder?

**Comment by tssutha** [comment]
Here is the suggested link http://devgirl.org/2013/11/12/three-hooks-your-cordovaphonegap-project-needs/
It was posted in Nov 2013, I am not sure the folder structures are still valid for latest platforms. 
I use Visual Studio cordova tools (CTP 3.1) for development.

**Comment by macdonst** [comment]
@tssutha Can you post an example of the payload you send to the device which shows the Action buttons?

**Comment by tssutha** [comment]
I use the PushSharp library at my server side.

 "data": {
    "notId": 1,
    "title": "This is the title",
    "message": "This is 5 new documents to read.",
    "actions": [
      {
        "icon": "importantItems",
        "title": "IMPORTANT",
        "callback": "window.onOpenImportantItems"
      },
      {
        "icon": "newItems",
        "title": "NEW ITEMS",
        "callback": "window.onOpenNewItems"
      }
    ],
    "style": "inbox",
    "summaryText": "There are %n% notifications",
    "sound": "beep.wav",
    "count": 2
  }

I have the similar issue for notification sound as well... I am not sure where to copy the sound files 
res/drawable or res/raw, there is not clear information about the custom file location. It seems possible to do in Java applications, but could not figure out how to do it with Cordova apps. 

Appreciate your help.

**Comment by macdonst** [comment]
@tssutha looking at you copy functionality you are copying `newitems.png` to `new.ico` and `important.png` to `important.png`. But then in your payload you call the icons `importantItmes` and `newItems`. So those names don't match anything in the res/drawable folder.

**Comment by tssutha** [comment]
Sorry, that was my mistake, i copied the code at different time, that' why it seems like a mismatch
anyways here is the actual code and payload, but it is not working at all, the notification sound also not working. 

Is there any way to play a default sound for android?

Payload 

 "data": {
    "notId": 0,
    "title": "This is the title",
    "message": "This is 7719 notification.",
    "actions": [
      {
        "icon": "ic_important_black_24dp.png",
        "title": "IMPORTANT",
        "callback": "window.onOpenImportantItems"
      },
      {
        "icon": "ic_fiber_new_black_24dp.png",
        "title": "NEW ITEMS",
        "callback": "window.onOpenNewItems"
      }
    ],
    "style": "inbox",
    "summaryText": "There are %n% notifications",
    "image": "https://dl.dropboxusercontent.com/u/887989/antshot.png",
    "sound": "beep.wav",
    "count": 2
  }
}

Hook Script 
module.exports = function (ctx) {
    // make sure android platform is part of build 
    if (ctx.opts.platforms.indexOf('android') < 0) {
        return;
    }

    var filestocopy = [
        {
            "res/icons/android/ic_fiber_new_black_24dp.png":
            "platforms/android/res/drawable/ic_fiber_new_black_24dp.png"
        },
         {
             "res/icons/android/ic_important_black_24dp.png":
             "platforms/android/res/drawable/ic_important_black_24dp.png"
         },
    ];


    var fs = require('fs');
    var path = require('path');
 
    // no need to configure below
    var rootdir = process.argv[2];
 
    filestocopy.forEach(function(obj) {
        Object.keys(obj).forEach(function(key) {
            var val = obj[key];
            var srcfile = path.join(rootdir, key);
            var destfile = path.join(rootdir, val);
            console.log("src :" + srcfile + "  -- des :" + destfile);
            //console.log("copying "+srcfile+" to "+destfile);
            var destdir = path.dirname(destfile);
            if (fs.existsSync(srcfile) && fs.existsSync(destdir)) {
                fs.createReadStream(srcfile).pipe(
                   fs.createWriteStream(destfile));
                console.log("src :" + srcfile + "  -- des :" + destfile);
            }
        });
    });
};

**Comment by macdonst** [comment]
@tssutha remove the extensions (.png/.wav) from the payload you send to the device. Android just searches res for the file name of any extension.

**Comment by tssutha** [comment]
Still not working... is that android folder structure has changed? does it look at different folder structure based on resolution ?

**Comment by macdonst** [comment]
@tssutha did you get this resolved?

**Comment by schmoofer** [comment]
+1

**Comment by macdonst** [comment]
@tssutha did you get this resolved?

**Comment by chetankabra** [comment]
can you let me know where you have put the callback function in your application

**Comment by macdonst** [comment]
@chetankabra you can put you call back where ever you want as long as it is addressable from the `window` object. so `app.accept` would be the `accept` function in the `app` object.

Also, I'm closing this as the original requester did not respond for 3 months.
