### ISSUE TITLE
Last version to support cordova-android < 4.0?

### ISSUE THREAD

**Issue by derwaldgeist** [phonegap/phonegap-plugin-push#405]
I would like to use this plugin in combination with Meteor 1.1, which has an embedded cordova that is still on cordova-android 3.6.4. So I get an installation error with the latest 1.4.5 release of this plugin, as it introduced an additional restriction to cordova-android > 4.0.0 in the plugin.xml file.

As I can see, version 1.4.4 did not contain this restriction. Is it safe to use this version instead, or was the restriction added due to problems with cordova-android < 4.0.0? If so, which version would you recommend for this older cordova-android?

Thanks in advance for your reply. Tom

**Comment by macdonst** [comment]
@derwaldgeist technically, 1.4.5 should still work with cordova-android < 4 but I don't have the time to test that far back. You may want to check if a later version of meteor uses a version of cordova-android >=4.
