### ISSUE TITLE
iOS: notification event is not fired when in foreground

### ISSUE THREAD

**Issue by vasanthv** [phonegap/phonegap-plugin-push#406]
Hello,

I am using phonegap build version 3.7.0 and the notification is shown when the app is in background, but when the app is in foreground the "notification" event is not fired. Any idea whats wrong?

Thanks in advance.

Vasanth

**Comment by macdonst** [comment]
@vasanthv I'm confused there is no version 3.7.0 of this plugin. Can you send a link to the plugin you are using?

**Comment by vasanthv** [comment]
@macdonst sorry for the confusion. I meant the phonegap version 3.7.0.

**Comment by macdonst** [comment]
@vasanthv okay, cool. BTW do you mean you don't see the notification in the shade when the app is in the foreground?

**Comment by vasanthv** [comment]
@macdonst No i said the notification event is not fired.

But I got is solved. Its a genuine mistake from my side.

**Comment by macdonst** [comment]
@vasanthv kk, just making sure.

**Comment by vasanthv** [comment]
@macdonst Thanks for your time. Sorry for the trouble ;)

**Comment by tolomir** [comment]
@vasanthv Hi there! I'm stuck with the same problem! I'm receiving notifications while in background or even if the app is completely closed, but not while in foreground! How did you solve it? 
Thanks!

**Comment by eddiekollar** [comment]
+1 Also trying to figure out how to detect if a push notification is received while app is in foreground
