### ISSUE TITLE
iOS: Error in PushNotification.init after app update

### ISSUE THREAD

**Issue by vasanthv** [phonegap/phonegap-plugin-push#408]
Hello,

I am implementing push notification and it works perfectly in the first time after app install. Once I update the app with a new version "PushNotification.init" gives some error and no error is also thrown at the "error" event. 

Is it only for me?

**Comment by nicoabie** [comment]
Care to give some information regarding environment, steps and description of "some error"?

**Comment by vasanthv** [comment]
Phonegap build version:3.7.0
iOS: 9.2

I am running the app in the device I couldn't see any logs. Javascript didn't run anything placed after this line.

**Comment by nicoabie** [comment]
Use this:
```
try {
  var push = PushNotification.init({ android: { senderID: "12345679" },
  ios: { alert: "true", badge: "true", sound: "true", clearBadge: "true" }});
} catch(error){
  alert(error)
}
```

**Comment by fredgalvao** [comment]
Also, what do you mean by "only after **updating the app**"?

**Comment by vasanthv** [comment]
@nicoabie I get the following error in catch.

"ReferenceError: Can't find variable: PushNotification"

**Comment by vasanthv** [comment]
@fredgalvao updating the app with a new version over the old version.

**Comment by nicoabie** [comment]
@vasanthv which is the command you run to update the app?

**Comment by vasanthv** [comment]
@nicoabie I just re-install the app on top of the already installed app.

**Comment by vasanthv** [comment]
Putting the "PushNotification.init" inside the phonegap "deviceready" event solved the problem.

Thanks

**Comment by valix85** [comment]
i ha ve a problem on ios, 
[507:58209] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["PushNotification509927292","PushNotification","init",[{"ios":{"sound":true,"badge":true},"android":{"iconColor":"#ec7416"}}]]

i'm not able to use push notification...in android work's very well
