### ISSUE TITLE
[docs] detail on deviceready dependency

### ISSUE THREAD

**Issue by fredgalvao** [phonegap/phonegap-plugin-push#410]
Update docs so that it's explicit that we need to wait for `deviceready` before `PushNotification.init` can be called. (See https://github.com/phonegap/phonegap-plugin-push/issues/408, among many others)

**Comment by macdonst** [comment]
@fredgalvao Really? Oh well sure but every PhoneGap/Cordova method must be called after `deviceready`.

**Comment by fredgalvao** [comment]
Me too, but the number of issues created related to this is yet more shocking. As is for another number of topics, but oh well.

**Comment by macdonst** [comment]
@fredgalvao I added in a note but feel free to expand upon the explanation.
