### ISSUE TITLE
notification is still showing on notification shade (android)

### ISSUE THREAD

**Issue by jeffortdev** [phonegap/phonegap-plugin-push#411]
First load of the application, as expected when receiving push notifications behaves like so.

app is closed: show on notification shade, push.on('notification') is never fired
app is open: doesn't show on notification shade, push.on('notification') is fired.

but on succeeding load of the application, when app is open shows on the notification shade and does not fire push.on('notification')

is there something I need to do?

thanks

**Comment by macdonst** [comment]
@jeffortdev How are you loading the app a second time? It seems odd like perhaps you have two instances of the app running.

**Comment by jeffortdev** [comment]
@macdonst by second time i mean, closing the app first(swiped off) then opening it again. one thing I noticed when running on a phone with low ram it doesn't show on the notification shade when the app is open(expected behavior). Kinda like it is saved on the localstorage which sometimes do not persist.

**Comment by jeffortdev** [comment]
@macdonst BTW, forceshow is set to default which is false, so push.on('notificaiton') should be fired and notification should not show on the shade right?

**Comment by macdonst** [comment]
@jeffortdev correct but if you force close the app you could possibly kill the service that retrieves the push. If you put together a detailed reproduction scenario that would help us debug.

**Comment by jeffortdev** [comment]
@macdonst thanks for the reply, I have not tried force closing the application, 
this is what i send to gcm using advanced rest client

{
"to": "someid",
"data": {
    "title": "title",
    "message": "message"
     }
}  

and on my device 

var push = PushNotification.init({
 "android": {
                        "senderID" : "asdfjkl;"
                   }
});

when the my application is freshly installed, and is running in foreground for the first time. there is no notification in the shade and the on('notification') event is fired which is expected. 

but if you close it (hold home button then swipe it off). then run it again, it behaves as if it is in the background(notification in the shade, on('notificaiton') is never fired).

on one of the phones I have tested which has low ram (using facebook app and other app that is running services in the background) which is below 100MB left, it is behaving normally(no notification in the shade on('notificaiton') is fired).
but when i clear up the services that are using the ram, on 200mb up available ram, it somehow behaves as if it was on the background.

**Comment by jeffortdev** [comment]
I am so sorry, i am closing this as i found out my service for push is not being called. Im so sorry for wasting your time @macdonst .

**Comment by macdonst** [comment]
@jeffortdev no problem, btw when you hold down the home button and swipe left the app you are killing it.
