### ISSUE TITLE
Changelog neglected

### ISSUE THREAD

**Issue by Manduro** [phonegap/phonegap-plugin-push#412]
Could we please have an up to date changelog? It's scary to update a plugin when there's no way to know what has changed.

**Comment by bau720123** [comment]
+1

**Comment by macdonst** [comment]
@Manduro then you should be scared of 90% of the plugins out there as most don't have CHANGELOG's. I generally only update the CHANGELOG on minor releases not bug fixes. If you want to see what's new then look at the commits.

**Comment by Manduro** [comment]
Neat, thanks!
