### ISSUE TITLE
Clearing notifications on Android

### ISSUE THREAD

**Issue by netomia** [phonegap/phonegap-plugin-push#413]
Is there a way to send a background-push to clear existing notifications on Android?

I've been able to do this with iOS by sending a {badge:0} only payload.

But a simular option seems to be missing for Android.

I tried the suggestions mentioned here without any luck:
https://github.com/phonegap/phonegap-plugin-push/issues/346#issuecomment-157315490

**Comment by macdonst** [comment]
Duplicate of #346
