### ISSUE TITLE
Sample application or documentation for integration with Amazon SNS?

### ISSUE THREAD

**Issue by derwaldgeist** [phonegap/phonegap-plugin-push#415]
For some hours now, I am trying to use this plugin in combination with the Amazon SNS service, but unfortunately without success.

I am able to retrieve the device token on my Android device, using the "Android key" created in Google's dev console. The phonegap plugin docs say that you should use the project ID (and also Amazon's docs say this), but if I try to use this ID, I only get the error message "Service not available". The Android Key works, however, so I am assuming this has changed somehow but hasn't been reflected in the docs.

As I said, I can create a device token, but I cannot send a push notification message to the app afterwards. I set-up an e-mail event handler for failure messages, and the e-mails I get from AWS are like follows:

```
{"DeliveryAttempts":1,"EndpointArn":"arn:aws:sns:eu-west-1:583754915260:endpoint/GCM/io.guzz.mobileapp/7a2bec9f-a1ee-308f-b90b-a93f048b0cfc","EventType":"DeliveryFailure","FailureMessage":"gcm behaved in an unexpected way","FailureType":"DeliveryFailedPerm","MessageId":"0e245d48-75ab-5880-8e45-13ad4fbcbe81","Resource":"arn:aws:sns:eu-west-1:583754915260:app/GCM/io.guzz.mobileapp","Service":"SNS","Time":"2015-12-11T20:53:43.269Z"}
```

I googled a lot, but could not find any satisfying answer what is going wrong here. The message suggests that the permissions are not correct, but I have no idea what should be changed. I am using the Server API key at Amazon, maybe this is not correct?!

On iOS, the situation is quite similar. I can get a device token, but if I try to send a message using SNS, I get a failure e-mail with this content:

```
{"DeliveryAttempts":1,"EndpointArn":"arn:aws:sns:eu-west-1:583754915260:endpoint/APNS_SANDBOX/guzz/2ae40754-6ab7-3857-8a4f-31a407d68857","EventType":"DeliveryFailure","FailureMessage":"Platform token associated with the endpoint is not valid","FailureType":"InvalidPlatformToken","MessageId":"c258cb94-0e26-5762-a09d-8571337ca9c4","Resource":"arn:aws:sns:eu-west-1:583754915260:app/APNS_SANDBOX/guzz","Service":"SNS","Time":"2015-12-11T21:07:39.676Z"}
```

I'm quite sure I've followed the instructions from Amazon and Apple, although Amazon's docs seemed to be outdated as it was suggesting to convert the p12 cert files to pem files, which does not seem to be necessary anymore.

I don't think that all of this is really a problem / bug in the cordova plugin, but I am completely lost in hyperspace now. Do you happen to know any good tutorial about how to get started with a concrete notification backend like Amazon SNS in combination with this plugin?

**Comment by macdonst** [comment]
@derwaldgeist I've successfully sent from Amazon SNS to apps running this plugin on Android and iOS. When I get a chance I'll try and write up something.

**Comment by derwaldgeist** [comment]
@macdonst Tanks for your quick reply!

At least I have already found out what the problem with iOS was. The Amazon docs were quite outdated and explained that you should convert your cert and key as .pem files. But when I opened the Amazon console, it was expecting a .p12 file. Since the only file I had exported in this format according to the Amazon docs was the private key, I uploaded this one.

But what you actually need is a .p12 file that *combines* both the certificate and the private key in one .p12 file. Creating this is a bit counter-intuitive as well, as you have to select both the private key and the certificate (which is a child object in Apples key chain app) and then export both. After I did this and imported this .p12 file, push notifications are working fine.

The second information I was missing in any documentation so far is that you also need a dedicated provisioning profile for your app. This was something I read here:

http://www.raywenderlich.com/32960/apple-push-notification-services-in-ios-6-tutorial-part-1

According to this document, a normal team provisioning profile is not enough, since it won't enable push notifications. I'm not sure if this is correct, but I am now also using a special provisioning profile, and maybe this contributed to my success :-)

For Google I am still trying to find out what's the problem. What I don't understand here: The docs state that you should use the project ID as the sender ID. But if I try this, no device token is generated. This only works if I use the Android API key instead as the sender ID. But I only get the device token then, but push notifications won't work. Maybe you need both?!

**Comment by derwaldgeist** [comment]
Update: I now created a new project for Google CGM, and suddenly it worked with the project ID instead of the API key. I don't know exactly why, sind I did everything like the first time, but at least it is working now...

**Comment by hugoramos** [comment]
@derwaldgeist I`m facing the same situation. I followed the same tutorials and now I am able to send push notification via SNS (website) to iOS, but not Android.

But my major question is: Did you manage to get your device to create an endpoint by itself?!
What I did was copy and paste the devicetoken and manually create an endpoint using SNS website.

Until I don't figure it out, I am storing the device token at database user's table.

**Comment by derwaldgeist** [comment]
I eventually gave up using SNS. As I am on Meteor, I am now using the raix:push package that uses this phonegap plugin under the hood. And I had to configure it with both the API key and the project number.

**Comment by hugoramos** [comment]
@derwaldgeist Not exactly what I expected to hear... I`m afraid I`ll have to quit SNS as well.

**Comment by hugoramos** [comment]
@macdonst Could you provide us some feedback about what you did to make it work? 
My project is in Ionic.

**Comment by sankp** [comment]
Is there any step by step document available to use SNS in .NET to send push on Phonegap app ?

**Comment by hugoramos** [comment]
Sorry guys. I did manage to accomplish this but I forgot to write here.

Thats what I did:

1. I store user device token when user opens my app.
 Code in Ionic app.js

`    .run(function($http, $ionicPlatform, $cordovaPush) {
        $ionicPlatform.ready(function() {

            var push = PushNotification.init({
                android: {
                    senderID: "567575375777"
                },
                ios: {
                    alert: "true",
                    badge: "true",
                    sound: "true"
                },
                windows: {}
            });

            push.on('registration', function(data) {
                window.localStorage['deviceToken'] = data.registrationId;
            });

            push.on('notification', function(data) {
            });

            push.on('error', function(e) {
                window.localStorage['deviceToken'] = e.message;
            });
        })
    })
`

2. After that, I store in my database the user device token I just got.

Mobile code stops here.

Begins my system code.

1. When my service (it is a window service that reads some tables and decides to send or not a push message to users) decides to send a push message to user HUGO, for instance. I use ask to my database whats the user token.

* If the user doesnt have a token stored I cant do anything.  STOP HERE.

2. If the user has a token, I ask if the user has a ARN.

2.1 If the user doestnt have a ARN. I ask to AWS whats his ARN (using this class bellow) and I store it.

3. Now, that I have user device ARN, I just send the message. 

4. Thats all.

I hope to help someone in need.
Thank you, guys!

`    
using Amazon.SimpleNotificationService;
using Amazon.SimpleNotificationService.Model;
using myapp.Domain;
using myapp.Business;
using myapp.Utils;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace myapp.Service.PushManager
{
public class SNS
    {
        static string ARN_APNS_SANDBOX = "arn:aws:sns:sa-east-1:XXX:app/APNS_SANDBOX/myapp";
        static string ARN_APNS = "arn:aws:sns:sa-east-1:XXX:app/APNS/myapp";
        static string ARN_GCM = "arn:aws:sns:sa-east-1:XXX:app/GCM/myapp";

        static string SERVICE_URL = "sns.sa-east-1.amazonaws.com";

        static AmazonSimpleNotificationServiceConfig SNSConfig = new AmazonSimpleNotificationServiceConfig()
        {
            ServiceURL = SERVICE_URL,
            RegionEndpoint = Amazon.RegionEndpoint.SAEast1
        };

        AmazonSimpleNotificationServiceClient snsClient = new AmazonSimpleNotificationServiceClient(SNSConfig);

        UserBUS userBUS = new UserBUS();
        PushQueueBUS pushQueueBUS = new PushQueueBUS();

        public void sendPush(PushQueue push)
        {
            try
          {
                if (!string.IsNullOrEmpty(push.User.DeviceToken) || !string.IsNullOrEmpty(push.User.DeviceArn))
                {
                    if (string.IsNullOrEmpty(push.User.DeviceArn))
                    {
                        if (!string.IsNullOrEmpty(push.User.DeviceToken))
                        {
                            var arn = CreateArn(push.User.DeviceToken);

                            push.User.DeviceArn = arn;

                            userBUS.Save(push.User);
                        }
                    }
                    else
                    {
                        ArnValidateCheck(push.User.DeviceArn);
                    }

                    Publish(push.User.DeviceArn, push.Message);

                    push.SendDate = DateTime.Now;
                }
                else
                {
                    push.Error = DateTime.Now + " - User without token in system database";
                }
            }
            catch (AmazonSimpleNotificationServiceException ex)
            {
                push.Error = DateTime.Now + " - " + ex.Message;
            }
            catch (Exception e)
            {
                push.Error = DateTime.Now + " - " + e.Message;
            }
            finally
            {
                pushQueueBUS.Save(push);
            }
        }

        private void ArnValidateCheck(string arn)
        {
            var request = new GetEndpointAttributesRequest()
            {
                EndpointArn = arn
            };

            var attributes = snsClient.GetEndpointAttributes(request);

            var active = attributes.Attributes.Where(p => p.Key == "Enabled").FirstOrDefault();

            if (active.Value == "false")
            {
                ActivateArn(arn);
            }
        }

        private void ActivateArn(string arn)
        {
            var attributes = new Dictionary<string, string>();
            attributes.Add("Enabled", "true");

            var request = new SetEndpointAttributesRequest()
            {
                Attributes = attributes,
                EndpointArn = arn
            };

            snsClient.SetEndpointAttributes(request);
        }

        private string CreateArn(string token)
        {
            try
            {


                var request = new CreatePlatformEndpointRequest
                {
                    PlatformApplicationArn = GetArnByToken(token),
                    Token = token
                };

                var endpoint = snsClient.CreatePlatformEndpoint(request);

                return endpoint.EndpointArn;
            }
            catch (AmazonSimpleNotificationServiceException ex)
            {
                throw ex;
            }
            catch (Exception e)
            {
                throw e;
            }
        }

        private string GetArnByToken(string token)
        {
            if (token != null && token.Length < 70)
            {
                return ARN_APNS;
            }
            else
            {
                return ARN_GCM;
            }
        }

        private void Publish(string arn, string message)
        {
            try
            {
                mensagem = message.Replace(@"\n", "\n");

                var request = new PublishRequest()
                {
                    TargetArn = arn,
                    MessageStructure = "json",
                    Message = new AmazonSNSMessage(message, string.Empty).SerializeToJSON()
                };

                var resposta = snsClient.Publish(request);

            }
            catch (AmazonSimpleNotificationServiceException ex)
            {
                throw ex;
            }
            catch (Exception e)
            {
                throw e;
            }
        }
    }
}
`

* I had to translate my from portuguese. Maybe you find some typo.

**Comment by sankp** [comment]
Hello @hugoramos. Do you mind uploading your sample app somewhere and share it ?
I am looking for .net side of the app.

**Comment by sankp** [comment]
@derwaldgeist, @hugoramos I am trying to use Phonegap app for Android and server side .net to send Push Notification. So far i was using Parse but as it is going to shut down and i don't have time to manage it by my own so instead of looking migration i am looking for alternative. So far pubnub and SNS are in my radar. I am able to implement PubNub but SNS there is no proper step by step documentation available. Is there any good code sample documentation available to do this ?

**Comment by derwaldgeist** [comment]
As stated above, I gave up using SNS, so I unfortunately can't help. I'm closing this issue now, in order to avoid further confusion :-)
