### ISSUE TITLE
using in Ionic

### ISSUE THREAD

**Issue by hansgill** [phonegap/phonegap-plugin-push#416]
Sorry in-advance if this is a dumb question. I'm new to Cordova + Angular + Ionic.

So I came via the deprecated PushPlugin page. I am using Ionic and previously I was using $cordovaPush when bringing in the module into my angular app.

What is the name of the module when referencing it in our angular/ionic app? Here is how I was bringing in the previous deprecated version.

```coffeescript
angular.module('services').factory 'Bootstrap', ($http, $q, $cordovaNetwork, $cordovaPush, urls, messageService, User)->
```

**Comment by nicoabie** [comment]
PushNotification but it is not registered as an injectable angular module. It lives on window. Use it inside your factory without any injection for it.

**Comment by hansgill** [comment]
Thanks @nicoabie that did the job.
