### ISSUE TITLE
Phonegap Build Issues for 1.4.X

### ISSUE THREAD

**Issue by offyourleash** [phonegap/phonegap-plugin-push#417]
Hi!

I had issued this post about a week ago on the Phonegap Build community forum. The feedback I received over there was good, however, didn't overall solve my problem. 

Please see the link 

http://community.phonegap.com/nitobi/topics/error-from-pushplugin-1-4-x-on-android

If anyone here uses PGB and can get PushPlugin to work past version 1.2.3 and knows how, and would let me know, that would be great :)

Thanks.

P.S Developers, This module is truly brilliant. Even version 1.2.3 is great. I had spent many hours tirelessly working on Push integration in the past but the latest versions of this module takes the pain out of it. Thanks so much for that!

**Comment by fredgalvao** [comment]
After Phonegap Build stated that gradle builds were stabilized and supported, I don't there's anything specific you need to do to make it work.

A detail though: version 1.2.3 didn't use gradle to build, so you would need to go back to `ant` builds on PGB if you wanted to use that version.

Other than that, I'd ask you to post the complete output of the compilation process for android, maybe there's some hidden detail there that I didn't see at the link you posted.

Also, are you able to compile it yourself locally successfully?

**Comment by offyourleash** [comment]
Thanks Fredgalvao

The issue looks like it has been resolved over the past few days. The Phonegap Build team may have responded to it as an issue. Whats more Gradle is not default as far as I can see which may cause confusion.

<preference name="android-build-tool" value="gradle" />

Is required in config.xml as Phonegap Build seems to have reverted back to ant as default.

I'm going to implement some of the new features found in the Plugin and if it seems like I have further issues I will follow your advice on building locally and send further details. Thanks!

Regards James

**Comment by macdonst** [comment]
@offyourleash we'll add something to the docs about specifying gradle as the build tool and I'll mention it to the PGB team.

**Comment by offyourleash** [comment]
Thanks Simon!

A little more detail on the issue, which i'll raise over at the PGB as well is that the debug output shows as follows.

`Fetching plugin "phonegap-plugin-push@1.4.5" via npm`
`Installing "phonegap-plugin-push" for android`

Issued with 

```html
<plugin name="phonegap-plugin-push" spec="1.4.5" />
```

Although I feel that `source=npm` should still work. However, PGB has recently changed conventions on this over to using `spec=`.

What the main problem is the install output. With all these settings put in place. IE Selecting version 1.4.X and seeing the debug output 1.4.X version being compiled. PGB's installed plugin screen still reflects the following screenshot (which could be isolated to me but I felt with publishing just in case).

![screenshot-pushplugin](https://cloud.githubusercontent.com/assets/16272529/11770663/f79428c2-a24f-11e5-9020-783ee727e010.png)

So you basically you just have to ignore that output.

Thanks!

**Comment by jessemonroy650** [comment]
@offyourleash
your confusion with using the plugin configuration is not new. The blogger even acknowledge as much. 

This is the confusing blog:
http://phonegap.com/blog/2015/11/19/config_xml_changes_part_two/

Here is the less confusing documentation:
http://docs.build.phonegap.com/en_US/configuring_plugins.md.html#_including_a_plugin_in_your_project
