### ISSUE TITLE
Distinguish between 'android' or 'ios' on registration event

### ISSUE THREAD

**Issue by tolomir** [phonegap/phonegap-plugin-push#418]
Hi, I want to register APNToken and GCMToken separately depending on the device. Is there any way to make this difference in the registration event? In the 'data' parameter just comes the 'registrationId' but not the OS of the device. 
Thanks!

**Comment by nicoabie** [comment]
No, for that you can use the cordova-plugin-device

**Comment by fredgalvao** [comment]
You can query the `device` plugin mentioned by @nicoabie  so that you know which platform is associated with each `registrationId`.

**Comment by macdonst** [comment]
@tolomir yes, please use `cordova-plugin-device` to determine what platform you are running on and respond accordingly.

**Comment by tolomir** [comment]
Thank you all! @nicoabie @fredgalvao @macdonst
