### ISSUE TITLE
Notifications not received while app in use (ios)

### ISSUE THREAD

**Issue by tolomir** [phonegap/phonegap-plugin-push#421]
Hi! 
I receive notifications while the application is in background or even if it is closed but if the application is in use I just receive the log event in Xcode but I don't see the alert in the device!
Is there any way to force the alert to be shown while the application is in use?
Thanks!

**Comment by macdonst** [comment]
@tolomir when an app is in the foreground on iOS the plugin does not show the alert as per iOS UI guidelines. Instead the `on('notification')` event handler is called. Currently there is no, `forceShow` option for iOS like there is for Android.

**Comment by Hirbod** [comment]
@macdonst 
I guess there are so many people trying to achieve what WhatsApp is doing. While inside the app, you might to show there is a new message in another chatroom for example.

I know it's not the main purpose of this plugin to display message banners, but it would be nice.

Well, @EddyVerbruggen was so kind to implement the click and data feature for his Toast-Plugin. (still not customizable design) but I guess, you should be able to achieve what you need.
https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin/issues/20

Just listen `on('notification)` and check the payload if the message was received while in `foreground`, create a toast, position top, add a click handler and pass your data. You should be able to achieve what you want.

I still hope that this plugin will give us the ability to show native-in-app-banners one time, with the native look and feel like it was an original one.

**Comment by AdriVanHoudt** [comment]
I did a PR for this https://github.com/phonegap/phonegap-plugin-push/pull/383, not complete I think but a start

**Comment by macdonst** [comment]
@AdriVanHoudt is the PR ready to be merged?

**Comment by AdriVanHoudt** [comment]
@macdonst honestly, no, it definitely needs a review since I am not a iOS dev

**Comment by cdorner** [comment]
+1

**Comment by AdriVanHoudt** [comment]
@cdorner you can speed this up by reviewing the PR or testing it and see if it fits your needs

**Comment by ashah-kaira** [comment]
+1

**Comment by eddiekollar** [comment]
+1

**Comment by Sundin** [comment]
+1!!!

**Comment by crystal98** [comment]
+1
is there any update on this request?

**Comment by macdonst** [comment]
@crystal98 nope, I haven't been able to get to it. PR #383 did not accomplish the forceShow capability on iOS. The ability to show a notification while the app is running only works in iOS 10.

PR's are always welcome.

**Comment by Govi59** [comment]
Hello there!
I would like to know if today the "iOS forceShow" function has been done. :slightly_smiling_face: 
If not, I've heard about a solution for iOS 10, but I really don't know how to implement it in my app...
Thanks!

**Comment by macdonst** [comment]
@Govi59 no, it is not yet implemented.

**Comment by crystal98** [comment]
Hello,

Do you have a time line when "iOS forceShow" function will be implemented?

**Comment by Vaishnavi-optisol** [comment]
Hi,

Any update on this for iOS forceshow option like in android?

**Comment by moulanaaidi** [comment]
+1

**Comment by macdonst** [comment]
Apple doesn't make this possible for remote notifications. If you want to accomplish this you'll need to have the `on('notification')` event handler call https://github.com/katzer/cordova-plugin-local-notifications
