### ISSUE TITLE
Clicking on one notification closes all other notification (on Android, phonegap-plugin-push v1.4.5)

### ISSUE THREAD

**Issue by yoav-zibin** [phonegap/phonegap-plugin-push#423]
Hi,
I use notId to prevent collapsing notifications (and I don't want to use the summary mechanism to merge notifications).
The problem is that clicking on one notifications, clears all the other notifications.
Is there some flag/setting that will keep the other notifications open?

The reason I want to keep the other notifications open, is that I send data with the notifications, and when you close the notifications I lose all the data.
My use-case is as follows: I have a game (TicTacToe), and each notification is a move done by some opponent (or an invite to a new match). I attach the game state as additionalData with the notification, so if you click on a notification when you're in airplane mode, you will still see the game. Therefore, if you have several notifications, I don't want to clear all notifications when you press on one individual notification :)

**Comment by macdonst** [comment]
@yoav-zibin did you try setting `clearNotifications` to false? 

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#android

**Comment by yoav-zibin** [comment]
No I didn't, I feel stupid for missing it, thanks :)  I looked at payload options instead.
Trying it out now...

**Comment by macdonst** [comment]
@yoav-zibin close the issue if it fixes your problem.

**Comment by fredgalvao** [comment]
@macdonst  Does `{clearNotifications: false}` also prevent the app from **dismissing all remaining notifications when any of them is interacted with**? If so, it should to be documented that way.

**Comment by yoav-zibin** [comment]
Works for my use-case like a charm :)
If the user clicked on a single notification, only that one disappears.
Thanks!

**Comment by Buddikazz** [comment]
After click on sencond notification third notification disapear
