### ISSUE TITLE
I added the plugin and i got this error while build

### ISSUE THREAD

**Issue by codecrab-studios** [phonegap/phonegap-plugin-push#424]
![screen shot 2015-12-15 at 11 15 36 am](https://cloud.githubusercontent.com/assets/16228380/11803086/445b5798-a31d-11e5-8034-fab6020e7231.png)

**Comment by macdonst** [comment]
@codecrab-studios https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#compilation

**Comment by codecrab-studios** [comment]
Hi mac.. i already have these Updated!

**Comment by codecrab-studios** [comment]
![screen shot 2015-12-15 at 11 27 35 am](https://cloud.githubusercontent.com/assets/16228380/11803235/dc6b3eda-a31e-11e5-9f09-85ae40b9c927.png)

have a look at this!

**Comment by codecrab-studios** [comment]
I see something now.. Play Services are not Installed.. Let me install it!

**Comment by codecrab-studios** [comment]
its still giving me the same error!

**Comment by codecrab-studios** [comment]
![screen shot 2015-12-15 at 11 35 55 am](https://cloud.githubusercontent.com/assets/16228380/11803342/065a2a7a-a320-11e5-9f25-c2e64c419712.png)
What wrong am i going Sir?

**Comment by codecrab-studios** [comment]
I am just searching for a plugin that will let me read the Notifications, I am using Parse notifications, Device Registrations etc is done already.. and getting Pushes too..  what i am left is just to read the Push Notifications Payload Data that is recieved from the Parse.com

**Comment by codecrab-studios** [comment]
Can you suggest me something on that!

**Comment by codecrab-studios** [comment]
I am using Ionic Framework too

**Comment by codecrab-studios** [comment]
After removing this plugin it builds fine.. !!

**Comment by fredgalvao** [comment]
Seems like you either have a rogue plugin installed alongside, or you have some weird bad plugin installation, for I can see you have other uncommon warnings about duplicate permissions on your AndroidManifest.xml related to push notification receipt.

Is it possible you could reinstall the plugin or the android platform?

**Comment by macdonst** [comment]
@codecrab-studios your build environment can't find [GoogleCloudMessaging.INSTANCE_ID_SCOPE](https://developers.google.com/android/reference/com/google/android/gms/gcm/GoogleCloudMessaging.html#INSTANCE_ID_SCOPE) which means generally means your Android environment is not setup correctly. You should make sure when this plugin gets added to your project that the build.gradle file includes the Google Play package for GCM.

**Comment by shprink** [comment]
I have the same problem, my Android env is setup correctly. I remove the old push plugin and install this one instead. It is not work anymore.

```
/Users/shprink/Sites/WPHC/wordpress-hybrid-client/platforms/android/src/com/adobe/phonegap/push/RegistrationIntentService.java:30: error: cannot find symbol
                    GoogleCloudMessaging.INSTANCE_ID_SCOPE, null);
```

**Comment by shprink** [comment]
Here is my settings:

* Android Support Library version 23.1.1
* Android Support Repository version 25
* Google Play Services version 28
* Google Repository version 23

**Comment by shprink** [comment]
I had to rollback to v1.2.3 to make it work.

**Comment by macdonst** [comment]
Try removing your platforms directory and re-adding Android to your project.

**Comment by shprink** [comment]
I remove everything everytime, it does not change the fact that > 1.2.3 I have the error

**Comment by shprink** [comment]
If it can help you the project is open source I could create a branch for you to try

**Comment by macdonst** [comment]
@shprink you can send me the link but I suspect it won't matter as my build can find that GCM library. I'm pretty sure it is an issue with your environment but add a link here and I will try it.

**Comment by shprink** [comment]
If it is not related to these settings:

```
Android Support Library version 23.1.1
Android Support Repository version 25
Google Play Services version 28
Google Repository version 23
```

What are we missing then?

**Comment by macdonst** [comment]
@shprink It's 100% related to Google Play Services version 28 & Google Repository version 23. When you build the app it can't find Google Play Services (or the correct version) for some reason. Make sure your $ANDROID_HOME environment variable is set to what you expect it to be.

**Comment by shprink** [comment]
I am making dozens of apps a year, do not worry $ANDROID_HOME is fine :P

**Comment by nicoabie** [comment]
I had the same error. But in my case it was caused by a short memory of vagrant's VM. I don't know if you are using it @codecrab-studios or @shprink

**Comment by shprink** [comment]
Nope, I am on OSX

**Comment by gabrielbazan7** [comment]
I have the same issue. Any idea? I am on OSX.

**Comment by shprink** [comment]
Using 1.2.3 till we get the solution

**Comment by macdonst** [comment]
All, I have two OSX device and I cannot reproduce the error on either so I'm not sure what I can do in this case. My only recommendation at this point is to delete your platforms and plugins directories and re-add the platform and plugins. If anyone comes up with a solution please document it in this issue and I'll add it to the docs.

**Comment by shprink** [comment]
> delete your platforms and plugins directories and re-add the platform and plugins

I have done that several times, nothing changed. This is definetly a problem with our machine configuration, nothing to do with this plugin. Thanks for your time @macdonst  :)

**Comment by macdonst** [comment]
@shprink when you figure it out please let me know.

**Comment by mapeveri** [comment]
Is there a solution to this issue?. I have same problema.

Thanks!

**Comment by gabrielbazan7** [comment]
I am using 1.2.3 : cordova plugin add phonegap-plugin-push@1.2.3 . It works perfectly for me, however i still have that issue with recent versions.

**Comment by mapeveri** [comment]
@gabrielbazan7 I have find solution for build correctly. 

In my case

1. Remove plugin google+
2. Remove plugin facebook.
3. Remove plugin google-play-services if this exists.

After, add plugin facebook, but jeduan fork, add plugin google+ and finally execute ionic build android.

This works, but not found google+ plugin because there is google-play-services. If added google-plat-services plugin, display error: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#multidex

Any idea?.

Sorry for my English :)

Thanks!

**Comment by codecrab-studios** [comment]
I did event used v1.2.3, but still its not working..
Please help!

![screen shot 2016-01-15 at 11 16 14 pm](https://cloud.githubusercontent.com/assets/16228380/12360434/01e97208-bbde-11e5-9662-31ba768cf2ba.png)

**Comment by macdonst** [comment]
@codecrab-studios you are using two plugins that both include the same jar. You are better off using the latest code and fixing the issue where your environment can't find the `GoogleCloudMessaging` library.

**Comment by codecrab-studios** [comment]
I just did some tests: 
I have two plugins :    

1. phonegap-plugin-push
2. phonegap-facebook-plugin

Test 1:    I removed both plugins and the build was fine
Test 2:   Added "phonegap-facebook-plugin" again and got the Build Error
Test 3:  Removed "phonegap-facebook-plugin" and added "phonegap-plugin-push" and Build was fine.

What should i do now, I need to have Facebook login plugin for sure!

**Comment by macdonst** [comment]
@codecrab-studios are you using the recommend plugin as per the docs?

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#co-existing-with-facebook-plugin

**Comment by codecrab-studios** [comment]
yes i do!

**Comment by codecrab-studios** [comment]
but i think i removed it earlier ! and just used phonegap-facebook-plugin

**Comment by codecrab-studios** [comment]
i think i got you now..what you saying.. 

https://github.com/Wizcorp/phonegap-facebook-plugin   - this is the plugin i did add earlier

and i think i need to install recommended plugin


and I did it... the Build is great now 

Thanks!
