### ISSUE TITLE
[ios] "the right way" to swizzle

### ISSUE THREAD

**Issue by athibaud** [phonegap/phonegap-plugin-push#427]
it seems using `method_exchangeImplementations()` can have some [undesired implications](https://blog.newrelic.com/2014/04/16/right-way-to-swizzle/) and the *right* way to do method swizzling is to use `method_setImplementation()`

shouldn't run into the implications described in that article seeing the use of this plugin is more of a *standalone application* use rather than *library* use but still.
i could implement and pr this if needed.

cheers

**Comment by macdonst** [comment]
PR merged

**Comment by athibaud** [comment]
i imagine you mean this pr https://github.com/phonegap/phonegap-plugin-push/pull/426 (thanks for merging :-)) but the code still uses `method_exchangeImplementations()` rather than `method_setImplementation()`

the pr i'm referring too in **this** issue does not yet exist :-)

**Comment by macdonst** [comment]
@athibaud my bad
