### ISSUE TITLE
Intermittent Notification?

### ISSUE THREAD

**Issue by DjEmet** [phonegap/phonegap-plugin-push#431]
Hi guys. During the testing of the plugin in my app, I experienced a strange bug. Initially, the notifications was shown correctly (in Android OS with GCM, tested directly on device), but sometimes in these last few days, I'm receiving a message via **console.log(data.additionalData)**:

> Error in Success callbackId: PushNotification TypeError: Cannot call method 'toString' of undefined". 

When I receive this message, the push in the device is not shown (but the registration and the data received back by the GCM is ok, proved by the log). 
I googled around and just in one case a guy found the solution, regardless in that case a missing data in the sent payload (ex. he settled the push in the js with a title, but was missing in the payload script). I tried in that way, just removing some data that should been the cause of the error. Strangely, in some cases it worked, but n others not. For example, I removed from my payload an "image" data (cause still in dev state, the path settled is incorrect, etc.) and it worked. But the second time I tried to call the push, it doesn't worked. Same, trying for all the remains data elements and vice-versa (the same data that initially were causing the issue, in a second time worked correctly).

It seems that the cause could be in some way related to that, but by the error received I'm not really sure that it can involve the plugin itself.

I attach my payload script:

    <?php

        $id_registrazione = "REG_ID"; 
        $url = "https://android.googleapis.com/gcm/send"; 
     
        @define("GOOGLE_API_KEY", "API_KEY"); 
     
        $registrazione_id = array($id_registrazione); 
        $notifica = array(
            
            "title" => "Assistenza tecnica", 
            "message" => "Localizzazione avviata", 
            "count" => 1, 
            "image" => "../img/icons/kk_icon_push_xhdpi.9.png", <---TEMP PATH - TO CORRECT
            "ledColor" => [128, 0, 128, 0], 
            "priority" => 2
            
        ); 
        $campi = array('registration_ids' => $registrazione_id, 'data' => $notifica); 
        $headers = array('Authorization: key=' . GOOGLE_API_KEY, 'Content-Type: application/json'); 
     
        $richiesta = @curl_init(); 
     
        @curl_setopt($richiesta, CURLOPT_URL, $url); 
        @curl_setopt($richiesta, CURLOPT_POST, true); 
        @curl_setopt($richiesta, CURLOPT_HTTPHEADER, $headers); 
        @curl_setopt($richiesta, CURLOPT_RETURNTRANSFER, true); 
        @curl_setopt($richiesta, CURLOPT_SSL_VERIFYPEER, false); 
        @curl_setopt($richiesta, CURLOPT_POSTFIELDS, @json_encode($campi)); 
     
        $risultato = @curl_exec($richiesta); 
     
        @curl_close($richiesta); 
        
        echo $risultato;

    ?>

Thanks for the help.

**Comment by macdonst** [comment]
@DjEmet there appears to be an error in your code. The intermittent part is probably due to the difference in data you send to your app. In a success callback there is a `undefined`. Can you show the code you use to handle the push?

**Comment by DjEmet** [comment]
Sure, here it go:

- The app simply must send a push on the device when the geolocalization starts:

        $(document).on("pagecreate", "#assistenza_tecnica", function() { 
    
        // listeners added justo to be fired only on a specified page
    
        document.addEventListener("deviceready", assistenza, false); 
        document.addEventListener("deviceready", avvisoPush, false); 
    
        });
    
        function avvisoPush() {
            
            notificaPush = PushNotification.init({ 
        
                "android": {
                    
                    "senderID": "857035142299", 
                    "icon": "../img/icons/kk_icon_push_mdpi.9.png", // This could be the cause?
                    "iconColor": "white", 
                    "sound": "true", 
                    "vibrate": "true", 
                    "clearNotifications": "true" 
                 },
                "ios": {}, 
                "windows": {} 
                
            });
                    
            notificaPush.on('registration', function(data) { 
                    
               registrazioneId = data.registrationId; // assign the value to a support variable to be send through another function

            });
            
            notificaPush.on("notification", function(data) {
                
                      
            });
            
            notificaPush.on('error', function(e) { 
            
                new $.nd2Toast({  // These are parts of a framework objects
            
                    message : "Registrazione fallita"
            
                });
                
                timer = setTimeout(function() {
                    
                    new $.nd2Toast({ 
           
                        message : e.message
                    
                    });
        
                }, 3000); 
                            
            });
            
        }
    
        [... Other stuff...]
    
        // Geolocation function (partial - Google Maps JS API)
    
        function geolocalizza() {
            
            if (navigator.geolocation) { 
                            
                // When the geoloc. starts, it sends the registration ID via ajax POST to the PHP payload script in a remote server
    
                $.ajax({
                            
                    url: 'http://www.karaliskonnection.com/php/push.php',
                    
                    data: {
                        
                        id_registrazione : registrazioneId 
                        
                    },
                    
                    type: 'POST',             
                    async: 'true', 
                    
                });  
                          
              [... Other stuff...] 
                
            }    
            
        }
        
        [... Other stuff...]
    
The payload script is the same I previously posted.

**Comment by macdonst** [comment]
@DjEmet The path to the icon you are sending is incorrect. It should refer to an image in the res/drawables directories on Android and not include the file extension. Your `on('notification')` method did not contain anything and I suspect that is where there error occurs.

**Comment by DjEmet** [comment]
Sorry the on('notification') was my fault in copy/paste. It was a container just for the console.log debug checking.
Thanks for suggestion. I'll try once more by removing the icon for now. I'll post the result.

**Comment by macdonst** [comment]
@DjEmet if your `on('notification')` check to see if you are trying to access something in `data.additionalData` as those values are not guaranteed to be there.

**Comment by DjEmet** [comment]
Pretty strange, just tried by removing the icon data both in payload and js and I'm still receiving the same error. I'm just trying to remove one by one all the data by exclusion, but nothing. With this notification event setting:

    notificaPush.on("notification", function(data) {
        
        console.log(data.message);
        console.log(data.title);
        console.log(data.count);
        console.log(data.sound);
        console.log(data.image);
        console.log(data.additionalData);  
              
    });

It's returning:

    Localizzazione avviata //msg
    Assistenza tecnica //title
    1 //count
    Error in Success callbackId: PushNotification1435124094 : TypeError: Cannot call method 'toString' of undefined //add. Data

**Comment by macdonst** [comment]
@DjEmet Try:

```
notificaPush.on("notification", function(data) {

    console.log(data.message);
    console.log(data.title);
    console.log(data.count);
    console.log(data.sound);
    console.log(data.image);
    if (data.additionalData) {
        console.log(data.additionalData);  
    } else {
        console.log('no additional data');
    }
});
```

**Comment by DjEmet** [comment]
Same result. No push and still that error.

**Comment by fredgalvao** [comment]
Instead of trying each property, can you try this:

```js
notificaPush.on("notification", function(data) {
    console.log(JSON.stringify(data, null, 4));
});
```

**Comment by DjEmet** [comment]
Ok I'll try it and let you know asap.

**Comment by macdonst** [comment]
@DjEmet bump

**Comment by DjEmet** [comment]
Sorry, I was away for vacancy. I tried the @fredgalvao solution but still the same for now.

**Comment by macdonst** [comment]
@DjEmet I can't reproduce this using node-gcm to send the push. I'm sending this data:

```
{
      "data": {
            "title": "Hello, World",
            "message": "my message",
            "count": 1,
            "image": "ic_launcher",
            "ledColor": [128,0,128,0],
            "priority": 2
        }
    }
}
```

and getting this in my app:

```
{
  "count": "1",
  "image": "ic_launcher",
  "title": "Hello, World",
  "message": "my message",
  "additionalData": {
    "priority": "2",
    "ledColor": [
      128,
      0,
      128,
      0
    ],
    "collapse_key": "do_not_collapse",
    "foreground": true
  }
}
```

**Comment by DjEmet** [comment]
Same here but with POSTMAN. Payload message is received (as the console confirm) but the push is not fired:

Payload test

    {       
      "registration_ids":["..."],
      "data": {
        "message" : "ciao",
        "title" : "prova"
      } 
    }

POSTMAN response

    {
      "multicast_id": 7642194737942182279,
      "success": 1,
      "failure": 0,
      "canonical_ids": 0,
      "results": [
        {
          "message_id": "0:1452241034178014%8488840df9fd7ecd"
        }
      ]
    }

Console debugger

    {
        "message": "ciao",
        "additionalData": {
            "foreground": true,
            "collapse_key": "do_not_collapse"
        },
        "title": "prova"
    }

App - No push

**Comment by DjEmet** [comment]
Ok after few days of tries, I noticed that in the Developer Console credential settings of the API, there was a point "." inside the IP filter field. By removing it in the first time, the notification pushed twice as well. But after them, the problem reappeared. 
I spent many days to search on the code and I found that the registration ID now is not sent in a valid form. The output:

    {"multicast_id":6952570674829247932,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"InvalidRegistration"}]}

I checked both client than server side codes. Actually, the app works in this way: by pressing a button, the ID is sent via AJAX POST:
  
    $.ajax({
                    
            url: 'http://www.karaliskonnection.com/app/push.php',
            
            data: {
                
                id_registrazione : registrazioneId // registrazioneId is acquired by assigning it the plugin data.registrationId parameter - on registration event
         
            },
            
            type: 'POST',             
            async: 'true'
            
        });

To a PHP script on a remote private server (the one posted above) that manage the payload request to GCM, but the $_POST seems to appear empty. So the ID is not being sent to GCM. By printing the $_POST status, it's confirmed with this console output (print_r($_POST)):

    Array
    (
    )
    1

       /*

               Tried with these forms too as well with no result - in AJAX call:

              'id_registrazione' : registrazioneId

              data: 'id_registrazione=' + registrazioneId
               
             regId = {'id_registrazione' : registrazioneId } ; // First declaring...
            [...]
             data: JSON.stringify(regId) // ...Then in call

            */

I spent many days to google the net in search of a solution. Tried to modify the AJAX request in many formatting variations (by declaring content-type, using JSON formatting/stringify/etc.) - as I reported above - with no result.
The strange thing, is that I'm using the same technique to do other stuff inside the same app, with no problem like this one. In those cases, the AJAX calls works well in sending and returning JSON format, so I think that POST in php remote config shouldn't be the problem. It's possible that it could be the value of variable itself? String parameter? It's pretty weird, because other people on the net shows how they works like this, in many examples, with no problems. Either case, it makes no sense.
The last try that I did today, is to verify some sort of blocking policy by the whitelisting plugin, but in both cases - by filtering and unfiltering content - the problem persists.

Any suggestion? Thanks all.

**Comment by fredgalvao** [comment]
You said the `registrationId` isn't coming in a valid form. Can you give an example of a scenario like that?
Also, can you `console.log(registrazioneId)` right before you try to do that `$.ajax`?

**Comment by DjEmet** [comment]
Sure. This is the output from the console triggered before and after the calling:

    adding homepage.js // Some Phonegap framework/Template stuff
    ID (Before sending - Client-Side): cnDutYb1fqI:APA91bF8jsBQFGyRlZvIuy9pe34FACKNm2d-FRaeFLNjupYgVnxPYOROGwtYK7cAHh8E9Awu63cneUyyXEYslqyP113Rdi0l9rZzQ8MdzMuhKUo5Bnl5aJmo_0DDbcOEprZiOOgoJh-B
    adding homepage.js // Same as above
    Response: {"multicast_id":4914063500542674974,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"InvalidRegistration"}]}
    ID (Server-Side -> 'registrazioneId' value): // <--- Empty (no value shown)
    POST check (Server-Side/print_r function): Array
    (
    )
    1 // As the ID on the server POST array appears empty.
    ID (After sending / Client-Side): cnDutYb1fqI:APA91bF8jsBQFGyRlZvIuy9pe34FACKNm2d-FRaeFLNjupYgVnxPYOROGwtYK7cAHh8E9Awu63cneUyyXEYslqyP113Rdi0l9rZzQ8MdzMuhKUo5Bnl5aJmo_0DDbcOEprZiOOgoJh-B

Seems that something get wrong: in the moment in which the value is sent to be assigned to POST, or POST is not allocating nothing. Or both?

**Comment by fredgalvao** [comment]
Well, if the `registrationId` value coming from the `registration` event is fine (as it is, stated and proved by you), then the reason that the `registrazioneId` is empty is something else, most probably some code of yours. There's nothing this plugin could do to prevent a simple variable assignment to work, we couldn't fail on that even if we tried.

Now, I can't explain what's preventing your POST request to actually work, but I'm almost sure this issue will disapear when you fix the assignment mentioned above.

**Comment by macdonst** [comment]
@DjEmet yeah, this is a problem with your registration code. From earlier example you posted it doesn't look like`registrazioneId` is declared anywhere so hoisting is happening. Try this instead, where the global variables are defined:

```
$(document).on("pagecreate", "#assistenza_tecnica", function() { 

// listeners added justo to be fired only on a specified page

document.addEventListener("deviceready", assistenza, false); 
document.addEventListener("deviceready", avvisoPush, false); 

});

// define global variables
var notificaPush;
var registrazioneId;

function avvisoPush() {

    notificaPush = PushNotification.init({ 

        "android": {

            "senderID": "XXXXXXXX", 
            "icon": "../img/icons/kk_icon_push_mdpi.9.png", // This could be the cause?
            "iconColor": "white", 
            "sound": "true", 
            "vibrate": "true", 
            "clearNotifications": "true" 
         },
        "ios": {}, 
        "windows": {} 

    });

    notificaPush.on('registration', function(data) { 

       registrazioneId = data.registrationId; // assign the value to a support variable to be send through another function

    });


    notificaPush.on('error', function(e) { 

        new $.nd2Toast({  // These are parts of a framework objects

            message : "Registrazione fallita"

        });

        timer = setTimeout(function() {

            new $.nd2Toast({ 

                message : e.message

            });

        }, 3000); 

    });

}

[... Other stuff...]

// Geolocation function (partial - Google Maps JS API)

function geolocalizza() {

    if (navigator.geolocation) { 

        // When the geoloc. starts, it sends the registration ID via ajax POST to the PHP payload script in a remote server

        $.ajax({

            url: 'http://www.karaliskonnection.com/php/push.php',

            data: {

                id_registrazione : registrazioneId 

            },

            type: 'POST',             
            async: 'true', 

        });  
                  
      [... Other stuff...] 

    }    

}

[... Other stuff...]
```

**Comment by DjEmet** [comment]
I don't know why but in my previous post, as you noticed, I didn't included the declaration line. As your example reflects, this is my var section right now:

    // listeners ...

    var defaultLatLng = new google.maps.LatLng(39.223723, 9.121014); 
    var latlng, indirizzo, pulsante, notificaPush, registrazioneId, timer, markers = null; 

    // ... push plugin functions

As you can see, both ```notificaPush``` and ```registrazioneId``` are declared and initialized too. To avoid any code incongruities, I tried to declare apart both without the ***null*** init (such as your suggestion). But the result still the same. 

Then, I tried with LocalStorage:

    // First
    [...]
     notificaPush.on('registration', function(data) { 
            
       registrazioneId = data.registrationId; 
       window.localStorage.setItem("registrazioneId", registrazioneId);
       [...]

    // Then..

    function geolocalizza() {
            
    if (navigator.geolocation) {
                    
        $.ajax({
                    
            url: 'http://www.karaliskonnection.com/app/push.php',
            
            data: {
                
                id_registrazione : window.localStorage.getItem("registrazioneId")
                
            },
      [...]

And nothing too.
Same trying to put AJAX calling inside the registration event itself (in case of some sort of bad scoping about ```registrazioneId```). Or by using directly the ```data.registrationId value```. They both fail.

At last, I tried to send the payload straight from js. During the testing I noticed a strange thing. During the POST sending via POSTMAN external app, the app was receiving the pushes instantly with no problem. In that moment, the deviceready event related to the plugin initialization was not fired, so basically the app didn't initialized a new push object and received the ```registrationId```. But, in the moment in which I opened the page that fires the plugin initialization - then tried to send the payload - no pushes weren't received.

Now I'm trying to destructure the logic of my app in order to see if the problem is the definition of the plugin initialization in the same scope of the payload AJAX calling. I'll post ASAP my results to see if something will change.

**Comment by DjEmet** [comment]
Ok guys, problem solved.

The POST error returned by checking the request done to the remote php payload script, is still present, but the app is receiving the pushes in the right way now.

Basically, seems that putting the plugin initialization in the same script where was present the one concerning the Google Maps API, wasn't a good idea. Apparently, that was blocking the notifications to be received. That answer to the question about why, in the first time, I was receiving intermittent pushes (Ok sometimes, others not). I moved only the plugin initialization code portion from there to another dedicated script. And boom! Pushes works now.

But actually I don't understand why a ```$.post``` check - as I mentioned above - done just after the calling, still returns an invalid registration ID error. The script now is working as well as the project designed for. The calling done to the remote script returns ID error. If I try with POSTMAN or other stuff, it returns OK. Very strange.

So, thanks guys for your work, patience and help. Really appreciated.
