### ISSUE TITLE
Foreground variable must be configurable via GCM Data

### ISSUE THREAD

**Issue by mahavirnahata** [phonegap/phonegap-plugin-push#432]
Hi,

I am using PushPlugin and i noticed that Notifications are not generated when app is in use, I am requesting this feature where we can configure whether generate notifications always or when app is not in foreground, and that can be managed by "foreground" variable sent via GCM. 

if "foreground" variable is not set in GCM payload, than do the default action but if its set in GCM data, it must work as set by user/developer. Many app user want to display notifications even if app is in foreground. It must be configurable by some means.

PS : I am using Phonegap build service. so manual editing of source file is not possible.

Thanks :)

**Comment by macdonst** [comment]
@mahavirnahata so, you mean the `forceShow` option you can use on Android which is documented over here:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushnotificationinitoptions

Please close this issue if the option resolves your request.
