### ISSUE TITLE
Do we need to call init everytime

### ISSUE THREAD

**Issue by mahavirnahata** [phonegap/phonegap-plugin-push#433]
Hello,

I was going through this plugin and i saw that we need to call this line 

 var push = PushNotification.init({ "android": {"senderID": "12345679"},
         "ios": {"alert": "true", "badge": "true", "sound": "true"}, "windows": {} } );

My question is : do we need to call this line on every page, My mobile app is not single page app.

Please suggest best usecase for multi-page apps built using Phonegap Build Service.

Thanks a lot :)

**Comment by macdonst** [comment]
@mahavirnahata Yes, yes you do. If the app already has a registration ID then it will just return the cached version without having to communicate with the remote service.

My suggestion is to look into single page app techniques. It will make your app much better.
