### ISSUE TITLE
Using stacking notifications but only able to process one

### ISSUE THREAD

**Issue by rodneyworkman291** [phonegap/phonegap-plugin-push#435]
I am using stacking notifications.  On my devices IOS & Android I received multiple notifications as desired.  When I click on any one of those notifications my app processes the notification clicked.  When I go back to my notifications the other notifications I had not yet clicked on are all missing.  

Should I have been able to process the other notifications when I processed the first notification?  Or should the other notifications wait for the user to act upon them?

Also maybe related, my badge count will show "1" even if I have "3" notifications.

**Comment by rodneyworkman291** [comment]
When I stopped calling setApplicationIconBadgeNumber my problem of messages being deleted went away.  The badge number was not working correctly so I'll just skip that part.

**Comment by fredgalvao** [comment]
I'm closing this as a mostly duplicate of https://github.com/phonegap/phonegap-plugin-push/issues/314. Please re-add if that issue doesn't mirror your needs.

Regarding notifications being closed when one of them is clicked, see [this conversation](https://github.com/phonegap/phonegap-plugin-push/issues/423), it'll probably clarify this topic.

Regarding the badge, I may be wrong, but I think you need to update the badge yourself on iOS using [the api](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushsetapplicationiconbadgenumbersuccesshandler-errorhandler-count---ios-only).
