### ISSUE TITLE
Push Notification Data not available in Android

### ISSUE THREAD

**Issue by codecrab-studios** [phonegap/phonegap-plugin-push#437]
I am building an app where i am using Parse Push Notifications.
I did successfully add this plugin without any issues. 
I sent some pushes from Parse and testing on both devices iOS and Android.

push.on('notification', function(data) {

 //  OVER here i am having things frmo additionalData to send the user to the apprpriate screens based on the Push Data. This works perfectly in iOS  but not in Android, in Android it deosnot even enter here and show any data from Push Notificaton, not even a blank.
])

Framework i am using:  Ionic Framework
Push Notification Service i am using: Parse

More Details:
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.8.11
Gulp local:  
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.3 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.0 Build version 7A220

**Comment by codecrab-studios** [comment]
Please help!

**Comment by codecrab-studios** [comment]
@macdonst  Please help me in resolving this issue!

**Comment by codecrab-studios** [comment]
Why is it not working for Android.. whereas for iOS it works perfectly!

**Comment by codecrab-studios** [comment]
@macdonst Simon can you please help me with this? If you cannot please just message!

**Comment by nicoabie** [comment]
@codecrab-studios do you have any adb output?

**Comment by codecrab-studios** [comment]
adb output like?

**Comment by smdvdsn** [comment]
Also how are you sending the push message? Using the Parse REST api or from the Parse dashboard?
What does your message payload look like?

Also make sure that the android senderID you use in the PushNotifcation.init call matches what you are have in the GCMSenderID for your install on Parse.com or you are initialising the push plugin with Parse's senderid

**Comment by codecrab-studios** [comment]
I was sending pushes from Parse Dashboard wiht Additional Data and reading it from app. Everything works smoothly on iOS but not on Android!  It doesnot even show data in push.on('notification')

**Comment by codecrab-studios** [comment]
push.on('notification', function(data) {
                console.log(angular.toJson(data, true));
})

**Comment by codecrab-studios** [comment]
@smdvdsn  Yes! I added SenderID in Parse.com to that  have in PushNotification.init

**Comment by nicoabie** [comment]
@codecrab-studios can you query the result of the sending of that message in the dashboard? To check if it could reach the device?

**Comment by codecrab-studios** [comment]
@nicoabie Yes! it does reaches the device and i see in top status bar, but what i am saying is:  If i have the app Open or Click the Push Notification, it should enter push.on('notification', function(data) {  and process other things from Push Notification Data, but it doesn't, whereas in iOS its working perfectly!

**Comment by nicoabie** [comment]
Looking [here](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/android/com/adobe/phonegap/push/GCMIntentService.java#L194) I see that maybe you need to add a content-available flag.
[Here](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/android/com/adobe/phonegap/push/GCMIntentService.java#L58) is where the message is received on android. Hope that helps @codecrab-studios

**Comment by macdonst** [comment]
Possibly the same issue as #469
