### ISSUE TITLE
No registrationId Samsung Galaxy S2

### ISSUE THREAD

**Issue by ELimburg** [phonegap/phonegap-plugin-push#442]
I can't get the plugin to work on a galaxy s2.
For some reason GCM doesn't return a registrationId.

Strange because it works on other Android devices.
Any ideas on the reason of this problem?

**Comment by macdonst** [comment]
@ELimburg are you running the latest version of Google Play Services on that phone?

**Comment by ELimburg** [comment]
I'm running 6.0.5
I guess that's the latest version

**Comment by macdonst** [comment]
@ELimburg hahahahah, no. The latest version is 7.3 as per https://play.google.com/store/apps/details?id=com.google.android.gms&hl=en. I'm guessing that your phone is running an older version of Android that is not compatible with the latest play services. What version of Android is it?

**Comment by ELimburg** [comment]
Android 4.1.2.

**Comment by macdonst** [comment]
@ELimburg two things to try:

1) Update Google Play Services in the Play Store if you can.
2) run `adb logcat | grep PushPlugin` to see what if any errors pop up

**Comment by ELimburg** [comment]
@macdonst thanks I'll try when I'll get to work on it again.

**Comment by ELimburg** [comment]
@macdonst I checked the log and for some reason it works now. 
If you have any ideas why it didn't work before I would be happy to know.

btw I was wrong about the Google play services version, it is 8.4.89. I looked at the store version :|

**Comment by macdonst** [comment]
@ELimburg sorry, I would only be wildly speculating as to why it is now working. 

_Checks excuse of the day calendar_

Actually, I believe the root cause of your problem was solar flares :wink:
