### ISSUE TITLE
Notifications do not appear in the status bar(only vibrate and sound) v1.5.1

### ISSUE THREAD

**Issue by KinG-InFeT** [phonegap/phonegap-plugin-push#444]
Hello,

I have a problem and it is: When sending a push to my application, the phone vibrates and plays but the notification does not come out.
why?
with app apert instead is captured properly push the alert is executed)

Install the latest version of the plugin and cordoba v1.5.1

thank you.

**Comment by macdonst** [comment]
@KinG-InFeT I cannot reproduce. More details please.

**Comment by KinG-InFeT** [comment]
i send the push and not show the notification into the statusbar...only vibrate and sound

**Comment by macdonst** [comment]
@KinG-InFeT what is your push payload?

**Comment by KinG-InFeT** [comment]
this is 

```
$dataPushMessage = array(
        "body" => $dati_utente['nome'].' '.$dati_utente['cognome'].' - Contact Request', //message
        "title" => $title
    );

$fields = array('registration_ids' => $registatoin_ids, 'data' => $dataPushMessage);
```

and into the logcat out only error:

```
E/PushPlugin_GCMIntentService: Number format exception - Error parsing notId: Invalid int: "null"
```

**Comment by macdonst** [comment]
@KinG-InFeT looks good to me.

**Comment by KinG-InFeT** [comment]
@macdonst yes...but the notify not show into the status bar..... this is a bug?
you have a test app with the show notification?

**Comment by macdonst** [comment]
@KinG-InFeT is your app in the foreground?

**Comment by KinG-InFeT** [comment]
@macdonst yes

**Comment by macdonst** [comment]
@KinG-InFeT then it is normal behaviour. When the app is in the foreground then the `on('notification')` hander is called. If you want it to show up in the notification shade then you need to set `forceShow` to true.

**Comment by KinG-InFeT** [comment]
@macdonst but I would also like to app also closed bait notification in the status bar notifications, but now it sounds, vibrates, but the notification does not come out. in forceview goes beyond the benchmark in playground when sending the push? rides in and how?

**Comment by KinG-InFeT** [comment]
I apologize if I have wasted your time, the problem was simply the icon of the app too big .... should insert a control.

thank you for your time @macdonst

**Comment by einicher** [comment]
I have this problem now too.
This gives me vibration and sound, but no notification, but is successfully received by on('notification'):
```
{
message: 'Something'
}
```

when i push 

```
"notification" : {
      "body" : "great match!",
      "title" : "Portugal vs. Denmark"
}
```
like described here https://developers.google.com/cloud-messaging/concept-options#notifications_and_data_messages the app crashes.

the behavior described here https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md is giving me no notifications, just vibrate, sound and everything is passed successfully to on('notification')
