### ISSUE TITLE
Push notifications: user hits dont allow

### ISSUE THREAD

**Issue by hansgill** [phonegap/phonegap-plugin-push#445]
Ok so I am trying to figure out if there is a way for my app to know if the user hit Don't Allow (IOS)?

Mainly, at some point I want to be able to ask the user to enable notifications but in-order for me to do that I need visibility if the user has allowed notifications for my app.

Hans

**Comment by hansgill** [comment]
sorry totally overlooked hasPermission

**Comment by macdonst** [comment]
It's brand new, as in just went into production today.
