### ISSUE TITLE
notification_applicationDidBecomeActive method

### ISSUE THREAD

**Issue by code-smith** [phonegap/phonegap-plugin-push#447]
In AppDelegate+notification class the method notification_applicationDidBecomeActive replaces applicationDidBecomeActive but its not getting called when app becomes active.

Earlier i used applicationDidBecomeActive to reset badges when opened directly from clicking the app icon, and had few other actions but it doesnt look like i can do that here?
is this a bug or by design , Can anyone please help me here? 

Thanks,
Sid

**Comment by macdonst** [comment]
I'm going to revert the code that caused this problem. Hold tight.

**Comment by code-smith** [comment]
Thanks..

**Comment by macdonst** [comment]
@code-smith published 1.5.2 to NPM. It should show up shortly. In the meantime you can install from the giturl.
