### ISSUE TITLE
google-services.json issue

### ISSUE THREAD

**Issue by joehannouch** [phonegap/phonegap-plugin-push#448]
Hello,

I've been trying to implement this new plugin in my app,
everything sets up correctly however when i launch the app, I get the following error:

GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.

I downloaded google-services.json and placed it in the Platforms/Android folder with no success.

I'm surprised I haven't seen others facing the same issue,

Any help is appreciated.

Joe

**Comment by ansarikhurshid786** [comment]
joehannouch: How to download google-service.json file. I am getting error google-service.json file is missing.

**Comment by joehannouch** [comment]
I actually forgot what i did and what was the issue in the first place.
I'm currently using onesignal (https://onesignal.com). wish i've used it before, give it a try it's free.

**Comment by jcesarmobile** [comment]
@ansarikhurshid786 you have to download the google-services.json from firebase console
