### ISSUE TITLE
1.5.3 version maybe have some conflict with "cordova-plugin-googleplus"

### ISSUE THREAD

**Issue by bau720123** [phonegap/phonegap-plugin-push#449]
hi @macdonst 
I am using phonegap build cli-5.2.0 with your plugin >=1.5.1 (gradle build)
well...

when I use the old version 1.4.5，all build success
 ```
<gap:plugin name="cordova-plugin-googleplus" source="npm" version="4.0.6">
 <param name="REVERSED_CLIENT_ID" value="XXYYZZ" />
</gap:plugin>

<gap:plugin name="phonegap-plugin-push" source="npm" version="1.4.5" />
```

but when I use the new version 1.5.1，only iOS will build fail
 ```
<gap:plugin name="cordova-plugin-googleplus" source="npm" version="4.0.6">
 <param name="REVERSED_CLIENT_ID" value="XXYYZZ" />
</gap:plugin>

<gap:plugin name="phonegap-plugin-push" source="npm" version="1.5.1" />
```
![2015-12-20_133720](https://cloud.githubusercontent.com/assets/5110085/11916713/337b505e-a71e-11e5-82d4-288ad8d7eef4.jpg)

so...is there any behavior change in 1.5.1 version ?
should I post this issue to the "cordova-plugin-googleplus" author @EddyVerbruggen ?
thanks

**Comment by macdonst** [comment]
@bau720123 what does the full build log look like?

**Comment by bau720123** [comment]
oh...thanks @macdonst 
the full log under here
http://pastebin.com/mFvWtKQ6

**Comment by bau720123** [comment]
hi @macdonst 
anything unclear ?

**Comment by bau720123** [comment]
just feedback
1.5.2 version still have the same problem

**Comment by bau720123** [comment]
hi @macdonst 
just feedback
1.5.2 version still have the same problem
should I feedback this problem to @EddyVerbruggen or ... ?

**Comment by macdonst** [comment]
@bau720123 no, it is a problem with this plugin. There are issues compiling the iOS GCM code on PGB.

**Comment by bau720123** [comment]
OK
thanks @macdonst reply
if any progress，please let me know
thanks

**Comment by macdonst** [comment]
Yeah, we need cocoapod support, not unlike Gradle support on Android to avoid this sort of thing.

**Comment by macdonst** [comment]
Go vote up this JIRA item:

https://issues.apache.org/jira/browse/CB-9825

**Comment by bau720123** [comment]
thanks @macdonst 
voted！

**Comment by jacqueskang** [comment]
I have exactly the same issue with @bau720123. 
ios build failing because of duplicated symbols found in 
/Plugins/cordova-plugin-googleplus/GoogleSignIn.framework/GoogleSignIn(GTMSessionUploadFetcher.o)
and
/Plugins/phonegap-plugin-push/GCM/Libraries/libGTMSessionFetcher_core.a(GTMSessionUploadFetcher.o)

My project is referencing cordova-plugin-googleplus v4.0.8 and phonegap-plugin-push v1.5.3
built with Xcode 7.2

**Comment by andres-torres-marroquin** [comment]
Have any of you found a workaround for this?

**Comment by gauravarora** [comment]
A workaround for this would be great.

**Comment by gauravarora** [comment]
I think I finally have a workaround. Downgrading the plugin to v1.4.5 gets everything building again.

**Comment by bau720123** [comment]
hi @macdonst 
just feedback
according to this
http://phonegap.com/blog/2016/02/09/phonegap_6_now_on_build/
so I made a test，for now the 1.5.3 version build success by PGB

**Comment by jacqueskang** [comment]
Thank you @gauravarora 
Indeed downgrading to 1.4.5 works now.

**Comment by chinmaygupta28** [comment]
Builds fine on ionic build for ios too on 1.4.5 but not for 1.5.3

**Comment by dragermrb** [comment]
As a workaround, you can edit **phonegap-plugin-push/plugin.xml** and change _framework="true"_ by _framework="false"_ on this lines:

```
<source-file target-dir="GCM/Libraries" src="src/ios/GoogleNetworkingUtilities/Libraries/libGTMSessionFetcher_core.a" framework="false" />
<source-file target-dir="GCM/Libraries" src="src/ios/GoogleNetworkingUtilities/Libraries/libGTMSessionFetcher_full.a" framework="false" />
<source-file target-dir="GCM/Libraries" src="src/ios/GoogleUtilities/Libraries/libGTM_AddressBook.a" framework="false" />
<source-file target-dir="GCM/Libraries" src="src/ios/GoogleUtilities/Libraries/libGTM_core.a" framework="false" />
<source-file target-dir="GCM/Libraries" src="src/ios/GoogleUtilities/Libraries/libGTM_GTMURLBuilder.a" framework="false" />
<source-file target-dir="GCM/Libraries" src="src/ios/GoogleUtilities/Libraries/libGTM_iPhone.a" framework="false" />
<source-file target-dir="GCM/Libraries" src="src/ios/GoogleUtilities/Libraries/libGTM_KVO.a" framework="false" />
<source-file target-dir="GCM/Libraries" src="src/ios/GoogleUtilities/Libraries/libGTM_Regex.a" framework="false" />
<source-file target-dir="GCM/Libraries" src="src/ios/GoogleUtilities/Libraries/libGTM_StringEncoding.a" framework="false" />
<source-file target-dir="GCM/Libraries" src="src/ios/GoogleUtilities/Libraries/libGTM_SystemVersion.a" framework="false" />
```

Then add platform a build (ionic sample):

```
$ ionic platform add ios
$ ionic build ios
```

**Comment by bau720123** [comment]
hi @dragermrb 
thanks your workaround
could I ask...
if change framework="true" by framework="false" will cause another problem or other situation ?
if I only use "phonegap-plugin-push"，the framework should maintain => framework="true"
right ?

**Comment by dragermrb** [comment]
Hi @bau720123 

This workaround aims to solve conflicts between **phonegap-plugin-push** and **cordova-plugin-googleplus**, so can use it** only on projects with both plugins**.

Option _framework="false"_ prevents link to that library, which already exists in cordova-plugin-googleplus plugin.

**Comment by bau720123** [comment]
hi @dragermrb 
thanks your feedback
but...
just want let you know
the "cordova-plugin-googleplus" still have this problem
https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/175

the "cordova-diagnostic-plugin" have already solved but "cordova-plugin-googleplus" not yet

**Comment by bau720123** [comment]
hi @dragermrb 
I use your workaround，but seem not work
can you try to use Cordova to build ?

[my step by `step]
`111`
one：cordova platform add ios @4.1.0
two：cordova plugin add phonegap-plugin-push
three：cordova plugin add cordova-plugin-googleplus --variable REVERSED_CLIENT_ID="XXX"
four：update the "phonegap-plugin-push/plugin.xml" and replace all framework="true" to framework="false" 
five：cordoba build ios --device --debug

**Comment by dragermrb** [comment]
Hi @bau720123 

I can't try this week but you should add platorm ios after edit plugin.xml and you should not replace all _framework="true"_, only some lines must be changed (look carefully mi workaround)

**Comment by bau720123** [comment]
hi @dragermrb 
after use your workaround，problem solved
it must be remove my ios project at first，otherwise，it still build fail
```
cordova platform rm ios
```

but this way will have a shortcoming
if one day "phonegap-plugin-push " have a new version
so...it will do above step again by again
Very troubled

is there anyway can edit some files in the platform/ios folder directly ?
just ask，anyway，thanks

**Comment by zwacky** [comment]
the workaround didn't work for me. i tried with `phonegap-plugin-push` 1.5.3 and `cordova-plugin-googleplus` 4.0.8.

if i downgrade to `phonegap-plugin-push` 1.4.5 it does work - but sadly i need functionality of a higher version.

what's the solution here? make both projects use another google-service-only plugin?

**Comment by idetia** [comment]
Another workaround (without changes in plugin.xml) could be:

- Open your project with XCode.
- Go to "**Build Phases**" and access to "**Link Binary With Libraries**"
- Remove the next libraries:
  - libGTMSessionFetcher_core.a
  - libGTMSessionFetcher_full.a
  - libGTM_AddressBook.a
  - libGTM_core.a
  - libGTM_GTMURLBuilder.a
  - libGTM_iPhone.a
  - libGTM_KVO.a
  - libGTM_Regex.a
  - libGTM_StringEncoding.a
  - libGTM_SystemVersion.a

**Comment by zwacky** [comment]
thanks, @idetia. that workaround worked well.

**Comment by marcelodl** [comment]
Thanks @idetia, worked for me too!

**Comment by amitbindal09** [comment]
Thanks @idetia, worked for me too!

**Comment by js12690** [comment]
Hello all,

I am using push notification plugin with version 1.8.4 and google plus plugin with version 5.1.1. Create build using phonegap build with cli 6.3.0. I got following error message

 **A plugin in your app does not support the compulsory arm64 (64-bit support) architecture**

Please help me as soon as possible

Thanks

**Comment by js12690** [comment]
@idetia I am not creating build using xcode. With the help of build.phonegap.com create build for IOS and android so how can i solve issue of conflict between push and google plus plugin.

Please reply fast

Thanks in advanced
