### ISSUE TITLE
Topics array

### ISSUE THREAD

**Issue by jellomaster** [phonegap/phonegap-plugin-push#450]
I can't seem to get the topics to work (perhaps I'm not doing something right since it's 2am here).

I'm using the code below and when subscribeToTopics is called.. topics is always null.  Looking in java code: JSONArray topics = jo.optJSONArray(TOPICS) return null. 
           var push = PushNotification.init({
            android: {
                senderID: "999",
                topics: "[\"all\"]"
            },
            ios: {
                senderID: "999",
                alert: "true",
                badge: true,
                clearBadge: true,
                sound: 'false',
                topics: "[\"all\"]"
            },
            windows: {}
            });

**Comment by macdonst** [comment]
@jellomaster it looks correct but I'd make your JSON:

```
var push = PushNotification.init({
android: {
senderID: "999",
topics: "['all']"
},
ios: {
senderID: "999",
alert: "true",
badge: true,
clearBadge: true,
sound: 'false',
topics: "['all']"
},
windows: {}
});
```

I'll re-test when I get a chance.

**Comment by jellomaster** [comment]
Nope .. didn't work either (testing android).  I managed to hack it  and get it to working with one topic by changing line 89 of PushPlugin.java
from:
JSONArray topics = jo.optJSONArray(TOPICS);
to:
                            JSONArray topics = new JSONArray();
                            String mytopics = jo.getString(TOPICS);
                            topics.put(mytopics);

**Comment by jellomaster** [comment]
Unsubscribing to topics also doesn't work on Android.  I managed to fix it by changing line 139 of PushPlugin.java from:
JSONArray topics = data.optJSONArray(0);
to:
JSONArray topics = data;

than calling:
                push.unregister(function() {
                    console.log('topic unregister success');
                    }, function() {
                    console.log('topic unregister error');
                }, "all");

**Comment by macdonst** [comment]
@jellomaster oh, now I see what you are doing wrong. You are making topics a string by enclosing it in double quotes. It should be:

```
var push = PushNotification.init({
android: {
senderID: "999",
topics: "['all']"
},
ios: {
senderID: "999",
alert: "true",
badge: true,
clearBadge: true,
sound: 'false',
topics: ['all']
},
windows: {}
});

push.unregister(function() {
console.log('topic unregister success');
}, function() {
console.log('topic unregister error');
}, ['all']);
```

If you pass in the correctly formatted JSON then you won't need to make changes to the Android code.

**Comment by macdonst** [comment]
@jellomaster Bump

**Comment by fritek373** [comment]
When I try it in the function *registertopic* it still isn't working. It's called inside an other function, which has a *deviceready* "hold".
```
function registertopic(topic) {
	var push = PushNotification.init({
		android: {
			senderID: "999", //is this necessary for Android?
			topics: "['"+ topic +"']"
		},
	});	
}
```

**Comment by OscarGalindo** [comment]
@macdonst if i use this code:

```
                  push.unregister(function() {
                    console.log('unregister success');
                    initialize(registered);
                }, function() {
                    console.log('unregister error');
                }, currentTopics);
```

it does not show nothing, none console.log is executed. If i remove the last parameter (currentTopics) it works. currentTopics is actually an array of topics.

The only what i want is to unsubscribe to a topic and subscribe to another and i see this is the only method to do?

thanks
