### ISSUE TITLE
Custom notification sound in background  not working

### ISSUE THREAD

**Issue by mrqaidi** [phonegap/phonegap-plugin-push#451]
i did everything and search for 2 hours in google and here   to fix issue that i have   when app in background or closed   custom sound  not set its playing  default sound  .play  help

 here is my sending php codes 

```
            // start GCM
            $msg = array
            (
                'message'   => $_POST['message'],
                'title'     => $_POST['subject'],
                //'subtitle'    => 'This is a subtitle. subtitle',
                //'tickerText'  => 'Ticker text here...Ticker text here...Ticker text here',
                'vibrate'   => 1,
                'sound'     => "alert1.mp3",
                'soundname'     => "alert1.mp3",
                'foreground' => false,
                'coldstart' => true

            );
            $regArray[]=$regiID->regid;

            $fields = array
            (
                'registration_ids'  => $regArray,
                'data'          => $msg
            );

            $headers = array
            (
                'Authorization: key=AIzaSyBkhNGSRq.....................',
                'Content-Type: application/json'
            );

            $ch = curl_init();
            curl_setopt( $ch,CURLOPT_URL, 'https://android.googleapis.com/gcm/send' );
            curl_setopt( $ch,CURLOPT_POST, true );
            curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
            curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
            curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
            curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fields ) );
            $result = curl_exec($ch );
            curl_close( $ch );
            $result_array = json_decode($result,true); 
```

**Comment by macdonst** [comment]
@mrqaidi when you send the name of the sound to GCM do not include the file extension. When Android looks for the sound file it only uses the name. Then the sound itself must be in res/raw of your Android project.

**Comment by mrqaidi** [comment]
yeah i try that  too but  not working . also i  decompile my apk  to check that  sound going  to /res/raw  but  folder not  there  
please help

**Comment by mrqaidi** [comment]
please help

this is my   code

whats wrong with it

		// ANDROID PUSH NOTIFICATIONS
		if(ionic.Platform.isAndroid())
		{
			config = {
				"senderID": GCM_SENDER_ID,
				"sound": true,
                
				};

			$cordovaPush.register(config).then(function(result) {
				
			}, function(err) {
				// Error
				console.log("$cordovaPush.register Error");
				console.log(err);
			});

			$rootScope.$on('$cordovaPush:notificationReceived', function(event, notification) {
                    console.log("notification params :"+notification);
                    console.log(notification);
				switch(notification.event)
				{
					case 'registered':
						if (notification.regid.length > 0 ) {
                                console.log("$cordovaPush.register started ");
                                console.log("regID: "+notification.regid);
                                	// if already not registered in api then do it 
                                    if(LocalDeviceID !==notification.regid){
                                          console.log("Send new RegID to server");
                                          PushToServer.storeDeviceToken("android", notification.regid);
                                    }
						}
						break;

					case 'message':
					payload = notification.payload;
					// if this flag is set, this notification happened while we were in the foreground.
					// you might want to play a sound to get the user's attention, throw up a dialog, etc.
					if (notification.foreground) {
					//console.log("Notifiction Received: "+payload.message);
                    var my_media = new Media("/android_asset/www/" + payload.soundname +".mp3");
                        my_media.play();
                        $ionicPopup.alert({
                            title: payload.title,
                            content: payload.message,
                            cancelText: "Close",
                        });


					} else if(notification.coldstart){ // otherwise we were launched because the user touched a notification in the notification tray.

                            $ionicPopup.alert({
                                title: payload.title,
                                content: payload.message,
                                cancelText: "Close",
                            });
                    
                    }else{
                             $ionicPopup.alert({
                                title: payload.title,
                                content: payload.message,
                                cancelText: "Close",
                            });
                                           
                        
                    }	
						
						break;

					case 'error':
						console.log('GCM error = ' + notification.msg);
						break;

					default:
						console.log('An unknown GCM event has occurred');
						break;
				}
			});

		}



also i have issue  when its in background mode its not open app on click

**Comment by macdonst** [comment]
@mrqaidi it looks like you are using a version of Ionic that is using the older deprecated [PushPlugin](https://github.com/phonegap-build/PushPlugin). So yeah, I can't help you with that. You'll have to move to the new plugin or talk to the Ionic guys. I'm actually surprised the docs aren't updated to use it.

**Comment by mrqaidi** [comment]
its ngcordova  and i am updating to $cordovaPushV5   and test  let you know if issues fixed or not :)

**Comment by mrqaidi** [comment]
please help

cant build via phonegap oneline build  give me this error
Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: GCMIntentService.java - You can fix this here

**Comment by macdonst** [comment]
@mrqaidi did you follow the instructions at: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md

**Comment by mrqaidi** [comment]
yes then still not working  something wrong with phonegap build gave me an error after adding this to config.xml
<preference name="android-build-tool" value="gradle" />
<plugin name="phonegap-plugin-push" spec="1.5.2" source="npm" />

do you want me to send u  building log ?

**Comment by macdonst** [comment]
@mrqaidi I suspect it is something with the engine tag for what cordova versions you are using. Can yo post your config.xml somewhere?

**Comment by mrqaidi** [comment]
@macdonst  sent to your google +    please check :)

**Comment by macdonst** [comment]
@mrqaidi this line:

` <plugin name="phonegap-plugin-push" spec="1.5.2" source="npm" /> -->`

is not valid xml. It should be: 

` <plugin name="phonegap-plugin-push" spec="1.5.2" source="npm" />`

**Comment by mrqaidi** [comment]
ignore that . i  commented  to  develop app 

so i build like that

    
    <   plugin name="com.phonegap.plugins.pushplugin" spec="2.5.0" source="pgb" />

    

but when  i use phonegap-plugin-push plugin its not building

**Comment by mrqaidi** [comment]
also i sent you full config.xml file please check

**Comment by mrqaidi** [comment]
please help i dont know whats wrong with it  . all i want is custom sound  working  when its not in foreground

**Comment by macdonst** [comment]
@mrqaidi Here is the config.xml that I use for my quick sample:

```
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.simon.push" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0" xmlns:gap="http://phonegap.com/ns/1.0">
    <name>Push151</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" version="1" />
    <preference name="android-minSdkVersion" value="14" />
    <preference name="android-build-tool" value="gradle" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <plugin name="phonegap-plugin-push" spec="~1.5.2" />
</widget>
```

it builds just fine. The only thing I see odd about your config.xml was locking it down to PhoneGap 5.2.0.

**Comment by mrqaidi** [comment]
aha 

so u want me to change phonegap version ?

    < preference name="phonegap-version" value="cli-5.2.0" />  

what version do i use in that preference  ?

**Comment by uno2xx** [comment]
I have this issue. I am able to send custom sound but the problem sometimes only the default sound will play which I set on my android phone. and how to set vibrate to none? this is my sample value [500,0,500,0] sometimes it vibrate and sometimes not in a half second.

**Comment by mardikacom** [comment]
i have another issue, i am able to play sound, but when the app in background, my phone play 2 sound, one native sound and sound triggered by app. I use Mi4i to test it. The question is how to disable my phone from playing default notification sound (native audio)? thanks

**Comment by uno2xx** [comment]
@mardikacom check your plugin, duplicate phonegap-plugin-push may trigger an issue.
