### ISSUE TITLE
Windows notifications (WP 8.1) - Unable to connect to WNS from client mobile app

### ISSUE THREAD

**Issue by charpin** [phonegap/phonegap-plugin-push#452]
From my windows mobile application, I want to implement the windows notifications.

**I just created a simple basic cordova project generated by Visual Studio 2015 RC**. I added only two plugins : cordova-plugin-device and phonegap-plugin-push of course. 

My mobile application is based on :

 - Cordova (version 4.0.0) 
 - Cordova Windows (version 4.1.0)
 - Deploy on Windows Phone 8.1

To implement this feature, I'm using the cordova plugin "phonegap-plugin-push" (version 1.5.2).

When my mobile application is launched for the first time, I ask to my application to connect to the notification client platform. The goal is this notification client platform ask to WNS to return a new notification channel (URI form) to my application.

When I use the method "registration" from PushNotification class :

        var push = PushNotification.init({
            "windows": {} 
        });
        
        push.on('registration', function(data) {
            console.log("registration event");
            console.log("URI : ", data.registrationId);
            console.log(JSON.stringify(data));
        });

        push.on('notification', function(data) {
            console.log("notification event");
            console.log(JSON.stringify(data));
            
            push.finish(function () {
                console.log('finish successfully called');
            });
        });

        push.on('error', function(e) {
            console.log("Push error : ", e);
        });

I get this error :

> **Push error : The notification client platform is unable to connect to the cloud**
> **notification service**

I thought the notification client platform is currently under maintenance. I found a file where are IP address ranges used by WNS. But when I ping differents IP address ranges and it works.

Is there anyone who already face this problem ? Or is there anyone who have an idea about how to fix it ?

**Comment by rakatyal** [comment]
@charpin: Do you get an error code in return? These are the common errors encountered during connecting with the WNS. Can you verify the data service is active on your device?

https://msdn.microsoft.com/en-us/library/windows/apps/windows.networking.pushnotifications.pushnotificationchannelmanager.createpushnotificationchannelforapplicationasync

**Comment by charpin** [comment]
I don't remember the error code in return. I think it was this error code : 0x800704C6

But thanks to you, I found the problem. I had not checked on my Windows Phone that data service is disabled. I thought by default that data service was activated. So, I activated the data service from my Windows Phone and the push notification works again.
