### ISSUE TITLE
push.on('notification',callback) triggers only when tap on notification on top bar

### ISSUE THREAD

**Issue by jonystorm** [phonegap/phonegap-plugin-push#453]
I've got my app up and running, on my js file I got :

push.on('notification', function(data) {
            console.log(data.message);
            alert(data.message);
        });

When I receive the notification it is shown on the android top bar correctly but it doesn't triggers the alert. It does when I tap on the notification and it reloads de app.

Am I missing something?

**Comment by macdonst** [comment]
@jonystorm no, that is correct behaviour you are not missing anything. If you always want the `on('notification')` event handler called for each push then you will need to force it to be called by setting the appropriate payload for a background notification. See the docs under 'Background Notifications': https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md

Also, you latest movie really sucked.

**Comment by jonystorm** [comment]
I know I'm sorry, I'll do better on the next one.

Thank you very much for your prompt answer
