### ISSUE TITLE
No sounds nor any updates on notification tray and status bar on android 

### ISSUE THREAD

**Issue by srameshr** [phonegap/phonegap-plugin-push#454]
Registration:
```
var push = PushNotification.init({
        android: {
            senderID: "my-id"
        },
        ios: {
            alert: "true",
            badge: "true",
            sound: "true"
        },
        windows: {}
    });
```

<b>Registration successful</b>
```
push.on('registration', function(data) {
        // data.registrationId
        console.log(data) // I get the data here and push it onto my server
    });
```

<b>Receiving data is also successful</b>
```
push.on('notification', function(data) {
        console.log(data) // I see my data in my logs!!
  });
```

<h3>Problem:</b> I am not able to see any notification on my <b>notification tray nor changes on my status bar nor can I hear any sound</b>. The phone just stays still. I am testing on Android 5.0

I am testing it by pinging GCM servers: 
```
curl --header "Authorization: key=my_key_here"        
--header Content-Type:"application/json" https://gcm-http.googleapis.com/gcm/send        
-d "{ \"data\" : { \"title\" : \"The App\", \"text\" : \"MessageText\", \"extra\":{\"url\":\"someurl.js\"}}, \"to\" : \"$device_registration_token_here\" }"
```

<b>I also get a success response from the GCM server:</b>
```
{"multicast_id":some_id_here,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:someIdHeer%AndSomeHere"}]}
```

What might be the issue?

**Comment by macdonst** [comment]
@srameshr Sigh...I believe your problem is the app is in the foreground so the default behaviour is not to show the notification in the shade. You seem to be getting the `on('notification')` method called so that means the plugin is working fine. If you want the notification to always be shown then use the `forceShow` option (https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#android). Forgive me if I seem a bit short, I've just answered this question many, many times.

**Comment by srameshr** [comment]
@macdonst No! No! I can confirm. The app is in the background.

**Comment by code2be** [comment]
Confirming the same issue !

**Comment by srameshr** [comment]
For me adding the android platform and removing it again with ```forceShow``` set to ```true``` in the ```register``` function did the job.

**Comment by code2be** [comment]
For me, been issue with Google's console project, fixed.
