### ISSUE TITLE
No armv7s arch in static libs for ios (plugin version > 1.4.5)

### ISSUE THREAD

**Issue by c0d3r85** [phonegap/phonegap-plugin-push#456]
When I'm building ionic project (ionic build ios --release --device), the build hangs with message:
ld: file is universal (4 slices) but does not contain a(n) armv7s slice: 
.../platforms/ios/Сибмоторс/Plugins/phonegap-plugin-push/GCM/Libraries/libGGLCore.a file '.../Plugins/phonegap-plugin-push/GCM/Libraries/libGGLCore.a' for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Diones** [comment]
I'm getting a similar error:

`ld: file is universal (4 slices) but does not contain a(n) armv7s slice: /Users/package/workspace/ionic_dash-82603uf-10/cordova/platforms/ios/myApp/Plugins/phonegap-plugin-push/GCM/Libraries/libGGLInstanceIDLib.a file '/Users/package/workspace/ionic_dash-925032ef-10/cordova/platforms/ios/myApp/Plugins/phonegap-plugin-push/GCM/Libraries/libGGLInstanceIDLib.a' for architecture armv7s`

**Comment by juanredondo** [comment]
Same problem here

**Comment by macdonst** [comment]
What version of Xcode are you all using because Xcode 7 is required.

**Comment by juanredondo** [comment]
Last xcode here

**Comment by ashishtilara** [comment]
I am receiving something similar too, ```ld: '.../platforms/ios/myApp/Plugins/phonegap-plugin-push/GCM/Libraries/libGGLCloudMessaging.a(GGLContext+CloudMessaging.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
```
XCode version: 7.2

**Comment by RomainLasso** [comment]
Same problem here, I had to remove the armv7 archs in my projet.

**Comment by bardu** [comment]
You can turn off bitcode in Xcode
https://github.com/google/gcm/issues/91

**Comment by bardu** [comment]
I'm using Xcode 7.2, after adding cocoapods and GoogleService-Info.plist to my project with bitcode turned off I'm getting the following error:
> Undefined symbols for architecture arm64:
>  "_OBJC_CLASS_$_GIPLocale", referenced from:
      objc-class-ref in libGGLInstanceIDLib.a(GGLInstanceIDCheckinService.o)
  "___gxx_personality_v0", referenced from:
      +[GGLHash calculatedFingerprintForString:] in libGGLCore.a(GGLHash.o)
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation) 

Any ideas?

**Comment by bardu** [comment]
I solved my issue by going to:
-> Build Setting in Xcode
--> Linking
---> Other Linking Flags
----> Debug and add $(inherited)

following this advice:
http://stackoverflow.com/questions/19213782/undefined-symbols-for-architecture-arm64

**Comment by tony--** [comment]
I have XCode 7.2 and I was able to reproduce this issue with cordova-ios 3.9.2.

This is related to https://issues.apache.org/jira/browse/CB-8788
That is, versions of cordova-ios prior to 4.0.0 specify armv7s in the list of archs, but (most of) the static libraries in phonegap-plugin-push/GCM/Libraries do not include an armv7s slice:
```
[~/pgpush-test/platforms/ios/HelloCordova/Plugins/phonegap-plugin-push/GCM/Libraries]$ lipo -info *.a
Architectures in the fat file: libGGLCloudMessaging.a are: armv7 i386 x86_64 arm64 
Architectures in the fat file: libGGLCore.a are: armv7 i386 x86_64 arm64 
Architectures in the fat file: libGGLInstanceIDLib.a are: armv7 i386 x86_64 arm64 
Architectures in the fat file: libGIP_Reachability.a are: armv7 i386 x86_64 arm64 
Architectures in the fat file: libGSDK_Overload.a are: armv7 x86_64 i386 arm64 
Architectures in the fat file: libGTMSessionFetcher_core.a are: armv7 x86_64 i386 arm64 
Architectures in the fat file: libGTMSessionFetcher_full.a are: armv7 x86_64 i386 arm64 
Architectures in the fat file: libGTMStackTrace.a are: i386 armv7 x86_64 arm64 
Architectures in the fat file: libGTM_AddressBook.a are: i386 armv7 x86_64 arm64 
Architectures in the fat file: libGTM_DebugUtils.a are: i386 armv7 x86_64 arm64 
Architectures in the fat file: libGTM_GTMURLBuilder.a are: i386 armv7 x86_64 arm64 
Architectures in the fat file: libGTM_KVO.a are: i386 armv7 x86_64 arm64 
Architectures in the fat file: libGTM_NSData+zlib.a are: x86_64 i386 armv7 arm64 
Architectures in the fat file: libGTM_NSDictionary+URLArguments.a are: i386 armv7 x86_64 arm64 
Architectures in the fat file: libGTM_NSScannerJSON.a are: i386 armv7 x86_64 arm64 
Architectures in the fat file: libGTM_NSStringHTML.a are: i386 armv7 x86_64 arm64 
Architectures in the fat file: libGTM_NSStringXML.a are: i386 armv7 x86_64 arm64 
Architectures in the fat file: libGTM_Regex.a are: i386 armv7 x86_64 arm64 
Architectures in the fat file: libGTM_RoundedRectPath.a are: i386 armv7 x86_64 arm64 
Architectures in the fat file: libGTM_StringEncoding.a are: i386 armv7 x86_64 arm64 
Architectures in the fat file: libGTM_SystemVersion.a are: i386 armv7 x86_64 arm64 
Architectures in the fat file: libGTM_UIFont+LineHeight.a are: i386 armv7 x86_64 arm64 
Architectures in the fat file: libGTM_core.a are: i386 armv7 x86_64 arm64 
Architectures in the fat file: libGTM_iPhone.a are: i386 armv7 x86_64 arm64 
Architectures in the fat file: libGcmLib.a are: armv7 i386 x86_64 arm64 
Architectures in the fat file: libProtocolBuffers.a are: i386 armv7 armv7s x86_64 arm64 
```

On cordova-ios 3.9.2, you can workaround this issue by patching your project to remove armv7s (as in the commit that fixes CB-8788).
That is, edit platforms/ios/cordova/lib/build.js and remove 'armv7s' from the list of ARCHS and VALID_ARCHS.

This workaround resulted in a successful build (cordova build ios --release --device) in a test project where I had added cordova-ios 3.9.2.
Upgrading to cordova-ios 4.0.1 also resulted in a successful build.

HTH!

**Comment by JerryBels** [comment]
+1

**Comment by Alexintosh** [comment]
+1

**Comment by newcodave** [comment]
+1

**Comment by DavidSunny** [comment]
For me, 

1.5.3 version : error
```
Plugins/phonegap-plugin-push/GCM/Libraries/libGGLCloudMessaging.a(GGLContext+CloudMessaging.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
```

1.3.0 version : build success (Xcode 7.2(7C68))

**Comment by Papipo** [comment]
Does this mean that I can't use the plugin with cordova-ios 3.9.2?

**Comment by macdonst** [comment]
@Papipo as of the 1.6.0 release you will need to use cordova-ios 4 or better.
