### ISSUE TITLE
Should I register my device every time the app starts?

### ISSUE THREAD

**Issue by srameshr** [phonegap/phonegap-plugin-push#457]
``` 
window.pushPlugin = PushNotification.init({
          android: {
              senderID: "42377729696",
              forceShow: true,
          }
        });

        window.pushPlugin.on('notification', function(data) {
          console.log(data);
        });
```

The ```notification``` event, wont be available until and unless I register it every time

**Comment by macdonst** [comment]
@srameshr Yes, you should register every time. The Android code caches your registration ID so it won't communicate with GCM if it doesn't need to. If the registration ID gets refreshed by GCM there is another service that listens to the change and informs you.

**Comment by srameshr** [comment]
Yeah got it. I was wondering about this. Can you add it to the docs? Many, of us get confused on why would someone want to call register() method every time  the app starts.

**Comment by macdonst** [comment]
@srameshr yup, will do. Docs need updating which is something I have planned before end of January. They'll be way better.
