### ISSUE TITLE
build fail in ios - version 1.5.2

### ISSUE THREAD

**Issue by roysG** [phonegap/phonegap-plugin-push#458]
CompileC build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/Objects-normal/i386/AppDelegate+notification.o OkeToki/Plugins/phonegap-plugin-push/AppDelegate+notification.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/Admin/www/oketoki/public_html/app/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Users/Admin/Downloads/android-sdk-macosx//tools:/Users/Admin/Downloads/android-sdk-macosx//platform-tools"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=116 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -fexceptions -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -mios-simulator-version-min=6.0 -iquote /Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/OkeToki-generated-files.hmap -I/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/OkeToki-own-target-headers.hmap -I/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/OkeToki-all-target-headers.hmap -iquote /Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/OkeToki-project-headers.hmap -I/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/emulator/include -I/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/emulator/usr/local/lib/include -I/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/UninstalledProducts/include -I/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/emulator -I/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/DerivedSources/i386 -I/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/DerivedSources -F/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/emulator -FOkeToki/Plugins/phonegap-facebook-plugin -include /Users/Admin/www/oketoki/public_html/app/platforms/ios/build/sharedpch/OkeToki-Prefix-ekfjbdsadrwrozgyokebdtsllahw/OkeToki-Prefix.pch -MMD -MT dependencies -MF /Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/Objects-normal/i386/AppDelegate+notification.d --serialize-diagnostics /Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/Objects-normal/i386/AppDelegate+notification.dia -c /Users/Admin/www/oketoki/public_html/app/platforms/ios/OkeToki/Plugins/phonegap-plugin-push/AppDelegate+notification.m -o /Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/Objects-normal/i386/AppDelegate+notification.o
In file included from /Users/Admin/www/oketoki/public_html/app/platforms/ios/OkeToki/Plugins/phonegap-plugin-push/AppDelegate+notification.m:10:
/Users/Admin/www/oketoki/public_html/app/platforms/ios/OkeToki/Plugins/phonegap-plugin-push/PushPlugin.h:31:35: warning:
      cannot find protocol definition for 'GGLInstanceIDDelegate'
@interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate>
                                  ^
/Users/Admin/www/oketoki/public_html/app/platforms/ios/OkeToki/Plugins/phonegap-plugin-push/PushPlugin.h:30:11: note:
      protocol 'GGLInstanceIDDelegate' has no definition
@protocol GGLInstanceIDDelegate;
          ^
1 warning generated.

CompileC build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/Objects-normal/i386/PushPlugin.o OkeToki/Plugins/phonegap-plugin-push/PushPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/Admin/www/oketoki/public_html/app/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Users/Admin/Downloads/android-sdk-macosx//tools:/Users/Admin/Downloads/android-sdk-macosx//platform-tools"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=116 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -fexceptions -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -mios-simulator-version-min=6.0 -iquote /Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/OkeToki-generated-files.hmap -I/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/OkeToki-own-target-headers.hmap -I/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/OkeToki-all-target-headers.hmap -iquote /Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/OkeToki-project-headers.hmap -I/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/emulator/include -I/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/emulator/usr/local/lib/include -I/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/UninstalledProducts/include -I/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/emulator -I/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/DerivedSources/i386 -I/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/DerivedSources -F/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/emulator -FOkeToki/Plugins/phonegap-facebook-plugin -include /Users/Admin/www/oketoki/public_html/app/platforms/ios/build/sharedpch/OkeToki-Prefix-ekfjbdsadrwrozgyokebdtsllahw/OkeToki-Prefix.pch -MMD -MT dependencies -MF /Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/Objects-normal/i386/PushPlugin.d --serialize-diagnostics /Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/Objects-normal/i386/PushPlugin.dia -c /Users/Admin/www/oketoki/public_html/app/platforms/ios/OkeToki/Plugins/phonegap-plugin-push/PushPlugin.m -o /Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/Objects-normal/i386/PushPlugin.o
In file included from /Users/Admin/www/oketoki/public_html/app/platforms/ios/OkeToki/Plugins/phonegap-plugin-push/PushPlugin.m:29:
/Users/Admin/www/oketoki/public_html/app/platforms/ios/OkeToki/Plugins/phonegap-plugin-push/PushPlugin.h:31:35: warning:
      cannot find protocol definition for 'GGLInstanceIDDelegate'
@interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate>
                                  ^
/Users/Admin/www/oketoki/public_html/app/platforms/ios/OkeToki/Plugins/phonegap-plugin-push/PushPlugin.h:30:11: note:
      protocol 'GGLInstanceIDDelegate' has no definition
@protocol GGLInstanceIDDelegate;
          ^
/Users/Admin/www/oketoki/public_html/app/platforms/ios/OkeToki/Plugins/phonegap-plugin-push/PushPlugin.m:451:42: warning:
      undeclared selector 'userHasRemoteNotificationsEnabled' [-Wundeclared-selector]
    if ([appDelegate respondsToSelector:@selector(userHasRemoteNotificationsEnabled)]) {
                                         ^
/Users/Admin/www/oketoki/public_html/app/platforms/ios/OkeToki/Plugins/phonegap-plugin-push/PushPlugin.m:452:49: warning:
      undeclared selector 'userHasRemoteNotificationsEnabled' [-Wundeclared-selector]
        enabled = [appDelegate performSelector:@selector(userHasRemoteNotificationsEnabled)];
                                                ^
/Users/Admin/www/oketoki/public_html/app/platforms/ios/OkeToki/Plugins/phonegap-plugin-push/PushPlugin.m:452:17: warning:
      incompatible pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from 'id'
      [-Wint-conversion]
        enabled = [appDelegate performSelector:@selector(userHasRemoteNotificationsEnabled)];
                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 warnings generated.

Ld build/emulator/OkeToki.app/OkeToki normal i386
    cd /Users/Admin/www/oketoki/public_html/app/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Users/Admin/Downloads/android-sdk-macosx//tools:/Users/Admin/Downloads/android-sdk-macosx//platform-tools"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -L/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/emulator -L/Users/Admin/www/oketoki/public_html/app/platforms/ios/OkeToki/Plugins/phonegap-plugin-push/GCM/Libraries -F/Users/Admin/www/oketoki/public_html/app/platforms/ios/build/emulator -FOkeToki/Plugins/phonegap-facebook-plugin -filelist /Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/Objects-normal/i386/OkeToki.LinkFileList -Xlinker -objc_abi_version -Xlinker 2 -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=6.0 -framework AssetsLibrary /Users/Admin/www/oketoki/public_html/app/platforms/ios/build/emulator/libCordova.a -framework CoreGraphics -framework MobileCoreServices -weak_framework ImageIO -framework CoreLocation -framework AVFoundation -weak_framework AddressBookUI -framework CoreMotion -weak_framework Social -weak_framework MessageUI -framework FacebookSDK -lsqlite3 -weak_framework Accounts -weak_framework Security -weak_framework AddressBook -lGGLCloudMessaging -lGGLCore -lGGLInstanceIDLib -lGIP_Reachability -lGSDK_Overload -lGTMSessionFetcher_core -lGTMSessionFetcher_full -lGTMStackTrace -lGTM_AddressBook -lGTM_DebugUtils -lGTM_GTMURLBuilder -lGTM_KVO -lGTM_NSData+zlib -lGTM_NSDictionary+URLArguments -lGTM_NSScannerJSON -lGTM_NSStringHTML -lGTM_NSStringXML -lGTM_Regex -lGTM_RoundedRectPath -lGTM_StringEncoding -lGTM_SystemVersion -lGTM_UIFont+LineHeight -lGTM_core -lGTM_iPhone -lGcmLib -lProtocolBuffers -Xlinker -dependency_info -Xlinker /Users/Admin/www/oketoki/public_html/app/platforms/ios/build/OkeToki.build/Debug-iphonesimulator/OkeToki.build/Objects-normal/i386/OkeToki_dependency_info.dat -o /Users/Admin/www/oketoki/public_html/app/platforms/ios/build/emulator/OkeToki.app/OkeToki
Undefined symbols for architecture i386:
  "_deflate", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByCompressingBytes:length:compressionLevel:mode:] in libGTM_NSData+zlib.a(GTMNSData+zlib.o)
  "_deflateEnd", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByCompressingBytes:length:compressionLevel:mode:] in libGTM_NSData+zlib.a(GTMNSData+zlib.o)
  "_deflateInit2_", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByCompressingBytes:length:compressionLevel:mode:] in libGTM_NSData+zlib.a(GTMNSData+zlib.o)
  "_inflate", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByInflatingBytes:length:isRawData:] in libGTM_NSData+zlib.a(GTMNSData+zlib.o)
  "_inflateEnd", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByInflatingBytes:length:isRawData:] in libGTM_NSData+zlib.a(GTMNSData+zlib.o)
  "_inflateInit2_", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByInflatingBytes:length:isRawData:] in libGTM_NSData+zlib.a(GTMNSData+zlib.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by macdonst** [comment]
@roysG what version of XCode are you using?

**Comment by pyroM1** [comment]
Hi, I have the same problem. 
Xcode: 6.2 (6C131e)
osx: 10.9.5

**Comment by RegexLLC** [comment]
Begin from scratch, update Xcode (7.x+), add basic plugins, add the Facebook4 plugin, add Push plugin, add iOS platform. Build iOS, change iOS target platform (~7), Disable bitcode. Run.

**Comment by chance-an** [comment]
Repros for me as well. Xcode 6.2

If I switch to my phone device, it fails for armv7 as well 
```
"Undefined symbols for architecture armv7:"
```

Exactly same symbols are missing.

**Comment by macdonst** [comment]
Uh yeah, you need Xcode 7 for his plugin. I'mma go update the docs.

**Comment by chance-an** [comment]
Confirm that after switching to Xcode 7, the issue is gone.

**Comment by pilladooo** [comment]
I have Xcode 7, but I still have this issue with 'cordova-plugin-pushplugin'

**Comment by fredgalvao** [comment]
@pilladooo You're looking at the wrong plugin. This plugin is [`phonegap-plugin-push`](https://github.com/phonegap/phonegap-plugin-push), you mentioned [`cordova-plugin-pushplugin`](https://www.npmjs.com/package/cordova-plugin-pushplugin) instead.

**Comment by jffs** [comment]
same problem

**Comment by pilladooo** [comment]
@fredgalvao With '[cordova-plugin-push-plugin](https://github.com/phonegap/phonegap-plugin-push)' all ok, '[phonegap-plugin-push](https://github.com/phonegap-build/PushPlugin)' is deprecated. I use Xcode 7.3.

**Comment by fredgalvao** [comment]
You got the names mixed up @pilladooo. You linked this plugin while naming it **cordova-plugin-push-plugin**, and you linked the old PushPlugin while naming it **phonegap-plugin-push**. Those are wrong.

1. `phonegap-plugin-push` is this plugin, repo url = https://github.com/phonegap/phonegap-plugin-push, and it's b**eing maintained**.
1. `PushPlugin` is the old plugin, repo url = https://github.com/phonegap-build/PushPlugin, and it's **deprecated**.

If anything on your code or build error output mentions PushPlugin, you're using the old one and we cannot help you here.
