### ISSUE TITLE
ERROR installing the plugin

### ISSUE THREAD

**Issue by guyCactus** [phonegap/phonegap-plugin-push#459]
Hey, 
Im trying to install the plugin on a "naked" app.
but somehow i get tons of errors just after that.
* no other applications were installed.
* tried the same thing before / after formatting my Mac.
* tried the same thing in 4 different apps.

But still  i get the errors. (especially: "The import com.google cannot be 
 resolved")
also it seems like the installer did not change the required parameters in androidManifest:
i found these lines in AndroidManifest.xml:
    <permission android:name="${applicationId}.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />

(${applicationId} did not changed) 

*anyway this is not the main problem because manually added the AppID but still got tons of other errors.
m

![screen shot 2015-12-26 at 12 47 44 pm](https://cloud.githubusercontent.com/assets/16443546/12006084/13799076-abcf-11e5-9d07-6dffddcf4a5e.png)

I assume it is something stupid and easy but im kinda new, so i'll appreciate any help :)

Thank you!
Guy

**Comment by macdonst** [comment]
@guyCactus it looks like your main problem is you did not add the required libraries to your Android environment.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#compilation

Also, the ${applicationId} is an variable that is set a build/run time and does not get changed in the gradle files so don't worry.

**Comment by guyCactus** [comment]
All of the required libraries are installed.
Now its working great but i needed to add all of the Jars manually.
Do you have any idea why eclipse does not import them automatically after the SDK manager finish downloading them?

Thank you :)

**Comment by macdonst** [comment]
@guyCactus because the Android community has, for the most part, moved from Eclipse to Android Studio. Android Studio uses Gradle to automatically include those frameworks for you. My recommendation is to move to Android Studio as Cordova Android now uses Gradle/Android Studio.
