### ISSUE TITLE
example application?

### ISSUE THREAD

**Issue by rubytastic** [phonegap/phonegap-plugin-push#460]
Is there an application example that implements this?

**Comment by elleryfamilia** [comment]
@rubytastic There's client/server code in the Example directory. Even after reviewing the that, I'm still a little confused as to how the client code works. The example doesn't show usage of any access keys, server urls, or anything like that.

**Comment by rubytastic** [comment]
Ah my bad sorry for wasting time totally right example is provided.
Guess some read on the docs should be enough to get the examples working but a little bit documentation would not hurt 

I wonder how serious we can take this repo with 88 issues?

**Comment by fredgalvao** [comment]
You shouldn't use the number of open issues to score the quality or seriousness of a repo, it's far from accurate in my opinion. Angular.js has almost a thousand open issues, and it's the biggest MV* framework out there for web clients, caressed by Google.

Other than that, documentation improvements are always welcome as suggestions or pull requests :wink:. I did clean it up recently, but the payload docs can still be greatly improved, for example.

**Comment by macdonst** [comment]
Yeah, I'm going to be working on the docs this month. I'll be doing a workshop at PhoneGap Day US at the end of January on Push so it will force me spend a bunch of time improving the docs in this repo. 

Hahaha, it's amazing this repo only has 88 issues. With over 11,000 downloads in December it's a pretty healthy repo.
