### ISSUE TITLE
Push notifications not working with iPhone6 + ios 9.2?

### ISSUE THREAD

**Issue by bmhelp** [phonegap/phonegap-plugin-push#462]
For some reason we can receive push notifications with IPhone 4s + ios 9.2 and iPhone 6 + ios 9.1 but not with iPhone 6 + ios 9.2.

Anybody having same kind of problems?

**Comment by shastox** [comment]
I have.
Development: everything is OK
Production: push works only for IOS>9.0: dont't fire:  ```push.on('notification', function(data) {```

**Comment by bmhelp** [comment]
Ok. You can close this issue now. The plugin worked all the time. We had problems elsewhere. Azure Portal does not send test notifications for all the registered devices.

**Comment by shastox** [comment]
I found a bug in my code.
