### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by fritek373** [phonegap/phonegap-plugin-push#463]
In a recent post I found out the PhoneGap is using Gradle by default for compiling the app (http://phonegap.com/blog/2015/09/28/android-using-gradle/). Does that main I can use build my app via build.phonegap.com? Or do I need to use Android Studio for the compilation proces?

**Comment by macdonst** [comment]
@fritek373 you can use either:

Gradle: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#compilation
PGB: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md

**Comment by macdonst** [comment]
@fritek373 re-open if the above does not answer your question.
