### ISSUE TITLE
Question: any idea why phonegap build insists on using version 1.4.5 (even though I specified 1.5.2 and the current stable v1.5.2) ?

### ISSUE THREAD

**Issue by yoav-zibin** [phonegap/phonegap-plugin-push#464]
Hi,
Curious if you know why phonegap build uses version 1.4.5, even though I specified:
    &lt;gap:plugin name="phonegap-plugin-push" source="npm" spec="1.5.2" /&gt;
?
Maybe you need to update the version somewhere?

See:
![image](https://cloud.githubusercontent.com/assets/1890589/12034858/949dc8f2-ae04-11e5-89c2-c44d2066e5ea.png)

Config is here:
https://github.com/yoav-zibin/phonegap-tictactoe/blob/gh-pages/www/config.xml

current stable is v1.5.2 (https://github.com/phonegap/phonegap-plugin-push/commit/77456b3618271db47e3614c6d71de9a548903fe5),
same is also shown in npm:
https://www.npmjs.com/package/phonegap-plugin-push

**Comment by bau720123** [comment]
hi @yoav-zibin 
I am a PGB user too
but...
you should ask this to PGB
http://community.phonegap.com/nitobi

**Comment by yoav-zibin** [comment]
Sure, done :)
http://community.phonegap.com/nitobi/topics/why-phonegap-build-insists-on-using-version-1-4-5-even-though-i-specified-1-5-2-and-the-current?rfm=1

I'll keep this open for a bit until I discover the answer :)

**Comment by bau720123** [comment]
thanks @yoav-zibin 

another thing (because you are PGB iser too)
the 1.5.2 for now have this problem
https://github.com/phonegap/phonegap-plugin-push/issues/449
maybe @macdonst try so solve it recently

**Comment by yoav-zibin** [comment]
Ok, it's definitely a PGB problem (see answer in http://community.phonegap.com/nitobi/topics/why-phonegap-build-insists-on-using-version-1-4-5-even-though-i-specified-1-5-2-and-the-current?utm_source=notification&utm_medium=email&utm_campaign=new_reply&utm_content=topic_link )

BTW, not worried about #449 : not using G+ :)
