### ISSUE TITLE
Can't build - getting error "A problem occured configuring root project 'android'

### ISSUE THREAD

**Issue by TrueGeek** [phonegap/phonegap-plugin-push#467]
After adding this plugin when I try to build for Android (iOS works fine) I get the error below. I've looked through the docs and made sure to update my Android SDK for the Support Library, Repository, Google Play Services, and Google Repository. My minSDK version is 15. If I remove this plugin my project builds just fine. Any idea what could be causing this?

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.android.support:support-v13:23+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v13/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v13/
     Required by:
         :android:unspecified
   > Could not find any version that matches com.google.android.gms:play-services-gcm:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/
     Required by:
         :android:unspecified

**Comment by macdonst** [comment]
@TrueGeek There is something not quite setup correctly in your environment. It can't find any of the required packages as per the compiling instructions. Not sure how to reproduce this one but if you find a way around it please let me know so I can document it.

**Comment by clearride** [comment]
:compileDebugJavaG:\ionicapps\app\cr\platforms\android\src\com\adobe\phonegap\pu
sh\GCMIntentService.java:571: error: cannot find symbol
            
                      getting this compile error during ionic build android

**Comment by TrueGeek** [comment]
Thanks @macdonst I was able to confirm it was an environmental issue by checking in my code and triggering a build on PhoneGap build, which worked fine.

I'll try to track down what's wrong, hopefully I won't have to reinstall everything!

**Comment by TrueGeek** [comment]
Holy crap. As is often the case in the situations the problem is with the end user. I'm an idiot. I'll document it here in case someone else runs into this.

My background is in C# so to update the Android SDK I open Xamarin Studio and go Tools > Android SDK. Apparently this opens it's open special installation of Android. (Thanks Xamarion).

If I type "Android" from the Terminal it's an entirely different version that hasn't been updated in forever! Nothing is installed! It's updating now but it's going to take forever. I'm confident that'll fix things though so I'll go ahead and close this issue.

Thanks for your patience and help!

**Comment by macdonst** [comment]
@TrueGeek that's good information. Thanks for letting me know. I'm going to add some notes to the Android compilation section of the docs.

**Comment by barocsi** [comment]
@clearride did you manage to fix that?

**Comment by clearride** [comment]
Hey,

Sorry I had to comment this line 577 in GCMIntentService.java. I am still in dev mode so thought this might get resolved by the time I publish the app.

 

Feature works as intended with this change

 

if (iconColor != 0) {

  //mBuilder.setColor(iconColor);

 }
