### ISSUE TITLE
Can i also send GCM to ios devices?

### ISSUE THREAD

**Issue by guyCactus** [phonegap/phonegap-plugin-push#468]
Hey,
I was wondering if i can use this plugin in order to recieve push notifications (through GCM) to an ios device..

It takes me alot of time to actually set & maintain all of ther certificates required for APNS services.
And i saw some discussions about that issue..

So my question is.. Is this even possible?
And if so.. How do i manage to do that?

Thank you :)

**Comment by macdonst** [comment]
@guyCactus Yes, yes you can. Look at the `senderId` and `gcmSandbox` parts of this:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#ios

Right now you can send GCM messages to iOS devices but you still need to maintain your APNS certificates. You just end up uploading them to Google.

https://developers.google.com/cloud-messaging/ios/client
