### ISSUE TITLE
Notification at status bar cannot be CLICK - Android

### ISSUE THREAD

**Issue by aishahismail** [phonegap/phonegap-plugin-push#472]
I'm using Ionic Framework, test in Device Samsung Tab V3 with Android version 4.4.4 (Kitkat).

Here is my **HTML**:
`<button class="button button-balanced" ng-click="register()">Test Push Notification</button>`

Here is my **JS**:
```
$scope.register = function () {
        var userNo = $scope.data.phoneno;
        var push = PushNotification.init({
            "android": {
                "senderID": "XXXXX"
            },
            "ios": {
                "alert": "true",
                "badge": "true",
                "sound": "true"
            },
            "windows": {}
        });

        push.on('registration', function (data) {
            var id = data.registrationId;
            var user = {
                hp: userNo,
                type: 'Android',
                id: id
            };
            
           $http.post('http://my-server', JSON.stringify(user))
                    .success(function (data) {
                        console.log("Success");
                    })
                    .error(function (err) {
                        alert('Error!' + err);
                    });
        });

        push.on('notification', function (e) {
            console.log(e);
        });

        push.on('error', function (e) {
            alert("Push Error ; " + e);
        });
    };
```

The notification was received, but when I clicked on it, it didn't go anywhere. 
Thanks for help.

**Comment by macdonst** [comment]
@aishahismail Sorry, what do you mean it didn't got anywhere? Once you clicked on the notification did the app open?

**Comment by aishahismail** [comment]
@macdonst sorry for unclear question, the notificatin did appear in my status bar - once, i click the notification, the notification did not open my application.

**Comment by macdonst** [comment]
@aishahismail are you doing anything funky to your AndroidManifest.xml as that should, literally, always open the app.

**Comment by aishahismail** [comment]
I didn't changed anything in AndroidManifest.xml, but I'm changed in plugin > phonegap-plugin-push > plugin.xml.

This is the original line: 
``` <framework src="com.android.support:support-v13:23+" /> ```

I replaced to 
```<framework src="com.android.support:support-v13:22.2.0" />```

I changed it because it got the error while I'm running it into the device(android), like this

![capture](https://cloud.githubusercontent.com/assets/14171601/12133252/749ddfc8-b45e-11e5-85ac-20809e81623b.PNG)

All these things already installed and updated
- Android Support Library version 23 or greater
- Android Support Repository version 20 or greater
- Google Play Services version 27 or greater
- Google Repository version 22 or greater

**Comment by aishahismail** [comment]
To confirm, I try again to use the original code in plugin.xml, then good news, my app can run to the device, all the errors not appeared again. But the main problem still not solve, my app still didn't open when I click on the notification

**Comment by macdonst** [comment]
@aishahismail even though you seem to have the correct items installed if you installed it via a IDE it may not be available to the command line. Try doing:

`android update sdk --no-ui --filter "extra"`

from the CLI to get all the most up to date packages. 

Can you run `adb logcat | grep PushPlugin` while reproducing the problem to see what is going on?

**Comment by aishahismail** [comment]
Solved. After I installed 'Google APIs' in SDK Manager. By the way thanks for your suggestion.
