### ISSUE TITLE
 Android 5 Asus ZenFone 2 blocking push notifications when app close

### ISSUE THREAD

**Issue by YaroslavG** [phonegap/phonegap-plugin-push#473]
Hi guys, 
I use this plugin and it works very well for Samsung, Lenovo, Nexus, HTC.

But when I tested it on ASUS ZenFone I did not received push notification when app is offline. Then I need go to manager autorun and must enabled push for my app. 
I want to know, there are some of permission in AndroidManifest to enable push when app is offline by default, without custom enabled?

**Comment by macdonst** [comment]
@YaroslavG sorry, no idea and I have no access to that device.

**Comment by JimmyBillan** [comment]
I have an ZenFone too and the manager autorun is really a problem. Most of users want to save battery, so they blocks services on apps...

**Comment by dludvig** [comment]
+1
Any solution for this case?
Thanks

**Comment by macdonst** [comment]
@dludvig no, there is not. If the user blocks the service that receives push notifications then there is nothing I can do in this plugin. Perhaps take a look at https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#huawei-and-xiaomi-phones as there may be a setting on the phone in question that will enable users to whitelist your app.
