### ISSUE TITLE
Production push notification testing trouble - Development pushes work

### ISSUE THREAD

**Issue by olearyj234** [phonegap/phonegap-plugin-push#476]
**Note:** This is an Ionic project. Android pushes and iOS dev pushes work fine. This regards production push notifications.

**My goal:** Test production push notifications before the app is launched.

**Testing approach summary:** I archive a adhoc production build and install the ipa with itunes.

**Problem:** The user shows up on the ionic.io website but there isn't a device token associated with it. When I view the console log, `Push Plugin register success: <#The_Device's_Token#>` is shown. If I type the device token in ionic.io and send a one time push, my device receives it. When I use push notifications in development mode, everything works and the device token does show up in ionic.io. 

**Question:** Why isn't my device token showing up in ionic.io when using production pushes, my adhoc provisioning file and archived adhoc ipa installed with itunes?  Is there a better approach to test production push notifications? Please comment with any thoughts or help.

**Notes:** For code signing identity, I set to iOS Distribution and the provisioning profile to the adhoc provisioning profile.

Here is my code in my _app.js_ in `$ionicPlatform.ready( function(){` ...

```
  var io = Ionic.io();
  var push = new Ionic.Push({
    "onNotification": function(notification) {
      console.log("Notification received!!!");
      //console.log(JSON.stringify(notification));

      $rootScope.$broadcast('notification');
    },
    "pluginConfig": {
      "android": {
        //"iconColor": "#0000FF"
      },
      "ios": {
        badge: true,
        sound: 'false'
      }
    }
  });
  var user = Ionic.User.current();

  if (!user.id) {
    user.id = Ionic.User.anonymousId();
  }

  // Just add some dummy data..
  user.set('name', ionic.Platform.platform());
  user.set('Platform', ionic.Platform.platform());
  user.set('Version', ionic.Platform.version());
  user.save();

  var callback = function(data) {
    push.addTokenToUser(user);
    console.log("Device token:", data.token);
    user.save();
  };
  push.register(callback);
}
```

Any comments will help. Thank you in advance!

**Comment by seblau** [comment]
Exact same problem! Already some solutions in place?

- Android and iOS dev pushes work fine.
- I also created an adhoc archive to the production push notifications on iOS.
- The user shows up on the ionic.io website but there isn't a device token associated with it.
- If I type the device token in ionic.io from the logs and send a one time push, my device receives it.

        Ionic.io();
        var user = Ionic.User.current();
                    if (!user.id) { user.id = window.sessionStorage['user_id']; }
                    user.save();

                    var push = new Ionic.Push({
                        "debug": false,
                        "pluginConfig": {
                            "ios": {
                                alert: true,
                                badge: true,
                                sound: false,
                                clearBadge: true
                            },
                            "android": {
                                sound: false,
                                vibrate: false
                            }
                        }
                    });
                    
                    push.register(function(token) {
                        user.addPushToken(token.token);
                        alert(token.token);
                        user.save();
                    });

**Comment by vcajes** [comment]
Same problem. The notificarion arrives well in sandbox, but does not arrives in production envoriment.

**Comment by vcenturion** [comment]
Same problem

**Comment by andypotts** [comment]
+1

**Comment by Toufux** [comment]
Does anyone got a solution?

**Comment by olearyj234** [comment]
I gave up a while ago. I would suggest using a 3rd party push notification service until Ionic services become stable. It was in alpha when I posted this question. Look out for the stable release.

**Comment by BarrelRider** [comment]
@olearyj234 what kind of 3rd party push notification service that you used ? Can you share it ?

**Comment by andypotts** [comment]
@BarrelRider you should be able to use something like pusher https://pusher.com/docs/push_notifications
