### ISSUE TITLE
Cannot find symbol variable INSTANCE_ID_SCOPE

### ISSUE THREAD

**Issue by mapeveri** [phonegap/phonegap-plugin-push#477]
Hi, after install this plugin and to build return this error "Error:(30, 41) error: cannot find symbol variable INSTANCE_ID_SCOPE"

What can be?

Thanks!

**Comment by macdonst** [comment]
@mapeveri https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#compilation

**Comment by mapeveri** [comment]
Hi @macdonst I have installed it and you say.

This 4 items with corresponding versions.

Android Support Library version 23 or greater
Android Support Repository version 20 or greater
Google Play Services version 27 or greater
Google Repository version 22 or greater

**Comment by mapeveri** [comment]
![image](https://cloud.githubusercontent.com/assets/6276555/12145347/676c09c0-b46c-11e5-9e38-3626142b270f.png)

**Comment by macdonst** [comment]
@mapeveri do me a favor and run `android update sdk --no-ui --filter "extra"` from the command line and try rebuilding.

**Comment by mapeveri** [comment]
@macdonst I run again and same error:

src\com\adobe\phonegap\push\RegistrationIntentService.java:30: error: cannot fin
d symbol
                    GoogleCloudMessaging.INSTANCE_ID_SCOPE, null);
                                        ^
  symbol:   variable INSTANCE_ID_SCOPE
  location: class GoogleCloudMessaging
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.

**Comment by mapeveri** [comment]
@macdonst any idea?. You can reopen this issue?.

Thank you

**Comment by kest85** [comment]
I have the same issue. Any solutions?

**Comment by macdonst** [comment]
@kest85 I promise you that it is something wrong with your Android build environment. It's near impossible for me to debug from here.

**Comment by fredgalvao** [comment]
Or related to the possible fact that you're trying to compile it through a badly-configurated IDE, as Eclipse or IntellijIDEA or even Android Studio.

**Comment by kest85** [comment]
Removing googleplayservices plugin fixed the problem.

**Comment by furyscript** [comment]
I have the same error, but I need `cordova-plugin-googleplayservices`. How can I resolve?

**Comment by fredgalvao** [comment]
Ask that plugin's author to upgrade to gradle-style dependency management.

**Comment by furyscript** [comment]
I resolve downgrade to `phonegap-plugin-push@1.3.0`. Compilation work, push notification receveid but not showing in emulator, is it normal?

**Comment by andresarslanian** [comment]
Hi everyone... although this post is rather old, I was still experiencing the problem today.

As @macdonst said, the plugin is working, he tried it in different machines and it's working.

Digging around why I still had this problem, I saw that the plugin clearly states that it requires: Google Play Services version 27 or greater

I did a `cordova plugin list` and saw the following:

`
cordova-plugin-app-preferences 0.7.7 "AppPreferences"
cordova-plugin-camera 2.2.0 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-facebook4 1.7.0 "Facebook Connect"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-google-analytics 0.7.1 "Google Universal Analytics Plugin"
cordova-plugin-googleplayservices 19.0.3 "Google Play Services for Android"
cordova-plugin-image-picker 1.0.8 "ImagePicker"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.0 "SocialSharing"
cordova-sqlite-storage 1.2.1 "Cordova sqlite storage plugin (core version)"
ionic-plugin-keyboard 2.0.1 "Keyboard"
`

This is, although I had everything up to date with @macdonst suggestion of doing:
`android update sdk --no-ui --filter "extra"`

I still (don't know why) but had in my config.xml the following line:
`    <plugin name="cordova-plugin-googleplayservices" spec="~19.0.3" />`

So what I did was removing that line, then:
`cordova plugin rm cordova-plugin-googleplayservices`

and voilà!

Hope it helps
