### ISSUE TITLE
How to open a specific page while clicking on the notification...?

### ISSUE THREAD

**Issue by GopalakrishnanK** [phonegap/phonegap-plugin-push#478]
I am using this(phonegap-plugin-push) plugin to push notifications to my cordova/ionic app. I'm sending an extra field called "ad_id" on push payload with each notifications. I need to open a page with corresponding ad loaded for clicked notification. How to do that?

**Comment by GopalakrishnanK** [comment]
I've tried like this https://github.com/phonegap-build/PushPlugin/issues/213. This works properly only when there's only one notification. How to handle multiple notifications?

**Comment by macdonst** [comment]
@GopalakrishnanK duplicate of #81

**Comment by Marcelinne** [comment]
@macdonst this issue is different from #81 , it should not be closed. The difference is that the #81 issues works for only one notifications, and this actual issues is for more than one notification
