### ISSUE TITLE
Multiple push notification problem

### ISSUE THREAD

**Issue by natanaelmaia** [phonegap/phonegap-plugin-push#48]
When there are more than one notification in status bar (different notIds), tapping on any of then will open the last received (Android only).

**Comment by macdonst** [comment]
@natanaelmaia Sounds like a bug. Can you give me a more detailed reproduction scenario so when I have time to look at this I can go right to the problem?

**Comment by natanaelmaia** [comment]
@macdonst, I sent two push notifications to the app. The first one with notId=0 and the last one with notId=1. When I tapped the first notification sent (notId=0), the push.on(’notification’) function was called with notId=1. The other notification also had disappeared from status bar.
This only happend in Android.
Thanks!

**Comment by fredgalvao** [comment]
Seems like this tracks back to [this issue](https://github.com/phonegap-build/PushPlugin/issues/503) where  @sinedied mentions that creating different `notIds` only makes **showing multiple notifications** possible, not **handling them all accordingly**. We need to inform a different `requestCode` for each notification for them to be able to trigger different actions. This behaviour is described in details [here](http://developer.android.com/reference/android/app/PendingIntent.html):

> If you truly need multiple distinct PendingIntent objects active at the same time (such as to use as two notifications that are both shown at the same time), then you will need to ensure there is something that is different about them to associate them with different PendingIntents. This may be any of the Intent attributes considered by Intent.filterEquals, or different request code integers supplied to getActivity(Context, int, Intent, int), getActivities(Context, int, Intent[], int), getBroadcast(Context, int, Intent, int), or getService(Context, int, Intent, int).

Changing https://github.com/phonegap/phonegap-plugin-push/blob/master/src/android/com/adobe/phonegap/push/GCMIntentService.java#L96 from
```java
PendingIntent contentIntent = PendingIntent.getActivity(this, 0, notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT);
```
to
```java
int requestCode = new Random().nextInt();
PendingIntent contentIntent = PendingIntent.getActivity(this, requestCode, notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT);
```
fixes it.

Please take a look into it! Looking forward to 1.1.2 with this!

**Comment by macdonst** [comment]
You guys are the best. I may get a chance to look into this tonight.

**Comment by macdonst** [comment]
@fredgalvao thanks, I tested and merged your change today. It'll show up in the next plugin release officially bug you can clone this repo to get the latest.

**Comment by fredgalvao** [comment]
I appreciate the quick response, and I'm glad I could help!
Now onto that bigText thing on android...

**Comment by VaishaliRavindran** [comment]
I am having notifications with different notId and when I select a notification the corresponding actions are executed correctly, But other notifications with different notIds are disappearing from notification tray in android

**Comment by fredgalvao** [comment]
@VaishaliRavindran Have you tried reading/changing the value of `android.clearNotifications` on your init options?
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#android

Also, if your issue persists, please create a new issue, as your case is not really the same as this issue.
