### ISSUE TITLE
Android: iconColor doesn't work in hexadecimal (#RRGGBB) format

### ISSUE THREAD

**Issue by javiercr** [phonegap/phonegap-plugin-push#480]
Despite of what the [docs says](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#android) about `android.iconColor`, I cannot use colors in `#RRGGBB` format. 

This config won't display the proper background color (will display the default grey instead):
```
config = {
  android: {
    senderID: GCM_SENDER_ID,
    iconColor: "#544A44"
  }
};

$cordovaPushV5.initialize(config)
```

However, it works with `iconColor: "#FF544A44"` (i.e. with the `#AARRGGBB` format). 

Also, for reasons I cannot understand, the `#RRGGBB` format it does work when using black color ( `iconColor: "#000000"`).

Maybe the best option is to just recommend in the docs to use the  `#AARRGGBB` format.

**Comment by macdonst** [comment]
@javiercr I'll give it a try with your value but according to the Android docs the method we use should support #rrggbb and #aarrggbb strings.

http://developer.android.com/reference/android/graphics/Color.html#parseColor(java.lang.String)

**Comment by macdonst** [comment]
@javiercr working fine for me. Can you give me an example payload you are sending to GCM?

**Comment by javiercr** [comment]
@macdonst, I've tested it again and now it works with `#544A44`. Very weird... Closing this, sorry for bothering you.
