### ISSUE TITLE
** BUILD FAILED ** - exit code 1

### ISSUE THREAD

**Issue by kennyzehn** [phonegap/phonegap-plugin-push#486]
hi experts,

if i add this plugin i get the follow error:
…
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **
…

Any ideas?

(disable bitcode doesn't work :()

**Comment by macdonst** [comment]
@kennyzehn try updating your platform to cordova ios 4.0.1.

https://cordova.apache.org/announcements/2015/12/18/cordova-ios-4.0.1.html
