### ISSUE TITLE
How to avoid multiple registration

### ISSUE THREAD

**Issue by al2939** [phonegap/phonegap-plugin-push#487]
From the example code it appears that  PushNotification.init must be called each time deviceready is fired, to initiate receiving notifications. But each time init is called, the registration event is received which means a fresh registration has happened and a new registration token has been generated (canonical), which again needs to be sent and saved at the server end. How to prevent this re-registration everytime? Or am I missing something?

**Comment by fredgalvao** [comment]
There is no "re-registration" per se. What happens is a "make sure the old registration is still in place".

There are many situations where either APNS or GCM needs to invalidate an existing registrationId (uninstallation, inactivity, backend reseting, cache cleaning, etc) so it's needed to **always be up-to-date with the currently valid registrationId**.  It is, for that reason, a good idea to call `.init` often (once every `deviceready`, which is everytime your app initializes, is often enough) and keep your backend or third party service updated.

By not doing that often, you risk having invalid or outdated registrationIds in your hands, and the owner of these said registrationIds would then be out of range for your push notifications.

**Comment by al2939** [comment]
The concern I have is that everytime I init, I am generating a new registration id which I need to save back in my app server before I can start listening. This unnecessarily increases hit on my app server and slows down notification receiving at the client end.

What I would have preferred is for the plugin to let me know whether registration is already done and valid, in which case it should not attempt registration again and avoid all the chatter. In case the registration is not valid, it can inform same and initiate registration. I can then use the canonical id and proceed with that.

Even if the plugin does not do any of the above, but simply initializes the plugin object and allows me to handle the behavior (when to register, when to not) that should also work fine.

It appears at present there is no option but to re-register the device everytime deviceready is fired, and go thru the motion to save the new id.

**Comment by fredgalvao** [comment]
The plugin code, but mostly the sdk's code (gcm and apns) used by it, already does that. 

> The concern I have is that everytime I init, I am generating a new registration id

This doesn't happen. It will only generate a new registrationId if the service has a new one for that device, in which case you'd need to update your backend anyway.

> This unnecessarily increases hit on my app server

You have no way around this. You need to inform your server or whatever service you use for push notifications, that said user/device has a new registrationId, regardless of what canonical version you have stored from a previous GCM response.

> What I would have preferred is for the plugin to let me know whether registration is already done and valid, in which case it should not attempt registration again and avoid all the chatter.

Again,  this is sdk code, we pretty much can't control when the registration will occur "again" or not, we simply ask for GCM's response for that device.

> It appears at present there is no option but to re-register the device everytime deviceready is fired, and go thru the motion to save the new id.

I don't know if that didn't came clear with the docs, but you only need to **save the registrationId and inform your backend/service of that registrationId** `if the previous one is different than the one you just got`. If they're identical, you don't need to do anything, as that's GCM/APNS telling you "this device is okay, move along, nothing to see here".

**Comment by al2939** [comment]
Ok, thanks. So just to be clear about what to expect, the below is what I understand to be the plugin behavior and the expectation from developer:

a) run init everytime when deviceready happens
b) registration event will be fired everytime
c) take the registration id, check if it matches with the existing one stored in the server, do nothing if matches, update server registration id otherwise
d) listen for notification event
e) There does not seem to be any implementation of onTokenRefresh method of GCM which notifies mobile to refresh its token.

Hope I got it right this time.

**Comment by macdonst** [comment]
@al2939 points a through d are correct but there is a implementation of onTokenRefresh in https://github.com/phonegap/phonegap-plugin-push/blob/7cce609ac79812dc26e8ed4e59a3b0e0917fa975/src/android/com/adobe/phonegap/push/PushInstanceIDListenerService.java which will cause a new registration event to be fired. 

If all your questions are answered please close this issue.

**Comment by razam217** [comment]
@macdonst How can we use onTokenRefresh in our ionic application. Can we push the new token on **onTokenRefresh** event to the server? 
If the application is not opened for a longer period and gcm token is expired, how can we push the new token to the app server, so that the notifications should be sent to the new gcm token?
