### ISSUE TITLE
"was built for newer iOS version (7.0) than being linked (6.0)"

### ISSUE THREAD

**Issue by tolomir** [phonegap/phonegap-plugin-push#488]
After updating plugin to latest version and when building for iOS I get lots of warnings with this message: " was built for newer iOS version (7.0) than being linked (6.0)"

Xcode build fails and throws "linker command failed with exit code 1 (use -v to see invocation)".
(Xcode version is 7.2 and Base SDK is Latest iOS(9.2)

Whats the problem? Is there any solution?

Thanks!

**Comment by macdonst** [comment]
@tolomir try updating your platform to cordova ios 4.0.1.

https://cordova.apache.org/announcements/2015/12/18/cordova-ios-4.0.1.html

**Comment by tolomir** [comment]
@macdonst done! But new errors appear! 

https://cordova.apache.org/announcements/2015/12/18/cordova-ios-4.0.1.html#comment-2452094830

**Comment by tolomir** [comment]
@macdonst If ENABLE_BITCODE is off it works in 3.9.2!
Thanks!

**Comment by macdonst** [comment]
@tolomir great, I added a note in the installation docs.
