### ISSUE TITLE
Android notification on notification not fireing when app is in background

### ISSUE THREAD

**Issue by stespr9** [phonegap/phonegap-plugin-push#489]
I cannot find a solution to this problem in all the issue reports.  Using Cordova in Visual Studio 2015 with the 1.5.2 plugin, the on notification event is not firing in the app when the Android app is in background.  It works fine if it is in the foreground and ios works fine too whether in foreground or background.  

When the Android app is in the background and the notification is received, the notification shows up in the shade.  When I touch the notification in the shade it brings the app to the foreground but does not fire the on notification event.  I'm testing on HTC One M9 if that matters.

Here is the javascript code:

         var push = PushNotification.init({
            "android": {
                "senderID": "xxxxxxxxxxxxx",
            },
            "ios": { "alert": "true", "badge": "true", "sound": "true" },
            "windows": {}
        });

        push.on('registration', function (data) {
            registrationId = data.registrationId;
        });

        push.on('notification', function (data) {
            alert("push recieved");
            push.finish(function () {
                alert('finish successfully called');
            });
        });

        push.on('error', function (e) {
            alertPopup("Push notification error: " + e.message);
        });

Here is the JSON sent to GCM:

{
	"registration_ids":["xxxxxxxxx"],
	"time_to_live":604800,
	"delay_while_idle":true,
	"data":{
		"message":"Message from me",
		"time":"1/10/2016 1:04:35 PM",
		"id":179,
		"messageID":179,
		"threadID":2,
		"theMessage":"test",
		"fromUser":"me",
		"messageDate":"01/10/16 1:04 PM",
		"viewed":false
	},
	"notification":
	{
		"title":"test message",
		"body":"Message from me"
	}
}

Any ideas on what I'm doing wrong or ideas for me to try?

Thanks!

**Comment by macdonst** [comment]
@stespr9 what you are describing is the normal behaviour of the plugin. When the app is in the background the notification is not delivered to the app. If you want the app to get the notification when in the background, regardless of whether or not the user taps on the notification you can use the background notification:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications

Also, I see you are adding all your push data into the `notification` object when you push to GCM. This will lead to the OS taking over the push and the GCM listener in this plugin will never get notified. Make your payload this instead:

``` 
{
  "registration_ids": [
    "xxxxxxxxx"
  ],
  "time_to_live": 604800,
  "delay_while_idle": true,
  "data": {
    "message": "Message from me",
    "time": "1\/10\/2016 1:04:35 PM",
    "id": 179,
    "messageID": 179,
    "threadID": 2,
    "theMessage": "test",
    "fromUser": "me",
    "messageDate": "01\/10\/16 1:04 PM",
    "viewed": false
  },
  "data": {
    "title": "test message",
    "body": "Message from me"
  }
}
```

If this works please let us know by closing the issue.

**Comment by stespr9** [comment]
Thank you so much for the explanation.  I changed the payload and it works like we wanted it to now.  Also, thank you for such a fast response.
