### ISSUE TITLE
Notifications are not pushing while the app is running in backround (only in Android 4.x devices)

### ISSUE THREAD

**Issue by GopalakrishnanK** [phonegap/phonegap-plugin-push#490]
Hi,
Initially i was testing my app in android 5.x(Lollipop) devices. I got all my notifications pushed successfully while my app is in background and foreground also. But when i run my app in android 4.x(Kitkat) devices it is receiving notifications only when my app is in foreground and it does not receives while my app is in background. Any suggestion please?

**Comment by macdonst** [comment]
@GopalakrishnanK Can you provide me the full payload you are sending to GCM?

**Comment by GopalakrishnanK** [comment]
@macdonst Please find my full payload which i'm sending to GCM.

{
         message : "30% Offer on each buy!!!",
         title: "Lifestyle Offer!!!!",
         image	: "notification",
         notId : "b3c31373b4e09028161aebac7885e40e",
         info: "Lifestyle Offer!!!!",
         style: "picture",
         picture: "http://36.media.tumblr.com/c066cc2238103856c9ac506faa6f3bc2/tumblr_nmstmqtuo81tssmyno1_1280.jpg",
         summaryText: "30% Offer on each buy!!!",
         collapse_key: "do_not_collapse",
         foreground: true,
         ad_id: "b3c31373b4e09028161aebac7885e40e"
       }

Thanks.

**Comment by macdonst** [comment]
@GopalakrishnanK do you put that in `data` or `notification`?

**Comment by GopalakrishnanK** [comment]
@macdonst I'm putting it in "data" like following.

_msg = {
  "data":{
    message : "30% Offer on each buy!!!",
    title: "Lifestyle Offer!!!!",
    image : "notification",
    notId : "b3c31373b4e09028161aebac7885e40e",
    info: "Lifestyle Offer!!!!",
    style: "picture",
    picture: "http://36.media.tumblr.com/c066cc2238103856c9ac506faa6f3bc2/tumblr_nmstmqtuo81tssmyno1_1280.jpg",
    summaryText: "30% Offer on each buy!!!",
    collapse_key: "do_not_collapse",
    foreground: true,
    ad_id: "b3c31373b4e09028161aebac7885e40e"
  }
}
 
Thanks!!!

**Comment by macdonst** [comment]
@GopalakrishnanK I will try and check on this as soon as I can load Android 4.x on a device. Might take until Wednesday.

**Comment by GopalakrishnanK** [comment]
@macdonst sure. Thanks.

**Comment by macdonst** [comment]
@GopalakrishnanK I installed Android 4.4. on my Nexus 5 and I can't reproduce this issue. I can receive messages when the app is in the foreground or background.

**Comment by GopalakrishnanK** [comment]
@macdonst Thanks. But can you please suggest me what could be possible reasons for this.? I'm confused. Anyways thanks for your help.

**Comment by macdonst** [comment]
@GopalakrishnanK can you run `adb logcat` and reproduce the issue? I'd like to see what the device says.

**Comment by GopalakrishnanK** [comment]
@macdonst Sure. 
Thanks.

**Comment by GopalakrishnanK** [comment]
@macdonst thanks for your help. It is working now actually my problem is 4.x has problem with other plugin. I've fixed it.
