### ISSUE TITLE
Android:Openening second notification cause clearing all notifications

### ISSUE THREAD

**Issue by Moussawi7** [phonegap/phonegap-plugin-push#491]
Hi,
When I open the second notification from the system tray, it cause to clear the all notifications and not the individual.
This is the scenario:
1-I send multiple notification from server having different ***notId***
2-I receive the notifications.
3-I open the first notification (Fine).
4-I open the second notification(foreground/coldstart/background) (Fine) but it clear the other notifications from the tray.

this is my options:
```javascript
{
            android: {
                senderID: "123456789"
            },
            ios: {
                alert: "true",
                badge: "true",
                sound: "true"
            },
            windows: {}
        }
```
Thank you.

**Comment by macdonst** [comment]
@Moussawi7 Did you try setting `clearNotifications` to `false`?

```
{
            android: {
                senderID: "123456789",
                clearNotifications: false
            },
            ios: {
                alert: "true",
                badge: "true",
                sound: "true"
            },
            windows: {}
        }
```

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#android

**Comment by Moussawi7** [comment]
@macdonst , Thank you, you are right the issue has been fixed by adding ***clearNotifications: false***
