### ISSUE TITLE
Phonegap/Ionic push notifications in iOS when app was closed

### ISSUE THREAD

**Issue by nadavb** [phonegap/phonegap-plugin-push#494]
It didn't work for me in Android, until I patched a bit the file GCMIntentService.java, but now I see that even after I updated the plugin, it also doesn't work in iOS. 
It's super basic... Why doesn't it work?
When the app is open in iOS -> it arrives well.
When the app is in background -> well.
When the app is shut down -> nothing happens. Why??

What am I missing here??

**Comment by macdonst** [comment]
@nadavb Why did you have to patch GCMIntentService? What changes did you need to make?

Why would you expect to get a push notification if the app has been shut down?

**Comment by nadavb** [comment]
Hi Mac,
In android I had a problem that I didn't hear a sound when the notification arrived, but I guess it was Ionic problem, not a problem of this plugin -

But when I'm using this plugin in iOS, when I launch the application everything works. When I shut it off, it doesn't work.

It needs to be like other services, for example Whatapp, that even when the application is not turned on, it still gets the notifications... (when people chat each other).

Am I missing something?

**Comment by macdonst** [comment]
@nadavb just to clarify, when you minimize the app on iOS you will still get notifications in the notification shade but if you kill the app from the app switcher you will no longer get notifications. Is this the behaviour you are seeing?

**Comment by nadavb** [comment]
Exactly!

**Comment by nadavb** [comment]
Mac, any insights? When I kill the app I don't even get the notifications to the iOS notifications area. Nothing.

**Comment by infinito84** [comment]
I have the same problem, I have a Cordova application, and I can receive notifications fine, but when the application is closed, the notifications work in Android, but not in iOS. However, when I force stop the application on Android Settings, the notifications don't arrive in Android.

**Comment by rozaydin** [comment]
+1 I have no issues in Android it works pretty good. But in IOS if the application is closed it does not receive the notification. If the application is in background the notification arrives. Any thoughts ?

**Comment by nadavb** [comment]
I found the answer @rozaydin -> Simply don't use ionic.io on the server side, and don't use the ionic push plugin on the client side - and everything will work like charm. Use the regular push plugin of cordova on the client side.

**Comment by rozaydin** [comment]
I am using node-gcm and phonegap-plugin-push, i am not using ionic.io. I have resolved the issue by setting **priority: 'high'** on the node-gcm side. This resolved the not received notifications when application is not running. I guess I should have read the GCM documentation properly, documentation states normal priority notification messages wont wake a sleeping device. 

> You have two options for assigning delivery priority to downstream messages: normal and high priority. Delivery of high and normal priority messages works like this:

> **High priority**: GCM attempts to deliver high priority messages immediately, allowing the GCM service to wake a sleeping device when possible and open a network connection to your app server. Apps with instant messaging, chat, or voice call alerts, for example, generally need to open a network connection and make sure GCM delivers the message to the device without delay. Set high priority only if the message is time-critical and requires the user’s immediate interaction, and beware that setting your messages to high priority contributes more to battery drain compared to normal priority messages.

> **Normal priority**: This is the default priority for message delivery. Normal priority messages won't open network connections on a sleeping device, and their delivery may be delayed to conserve battery. For less time-sensitive messages, such as notifications of new email or other data to sync, choose normal delivery priority.

**Comment by GustavoIO** [comment]
@rozaydin I'm using GCM http interface and phonegap-plugin-push and I'm unable to receive notifications if the app is closed. Did you do any special setup? Can you share your registration object?

Basically I get push.on('notification') if the app is in foreground, I get an alert if it's in background, followed by a push.on('notification') when the user clicks "open" and nothing if the app is closed using the "app switcher".

**Comment by fattanasio** [comment]
Hi, @GustavoIO , I have same problem. Did you resolve this bug ?
Thank you

**Comment by GustavoIO** [comment]
I don't remember anymore... Ask something more tangible and I'll check against the code base.

**Comment by fattanasio** [comment]
Ok ok.

I tested push notifications on Android 5 and when I restart smartphone it works perfectly also when i kill the app from task applications.

On Android 6 when the app is on foreground or background it works but if i kill the app or I restart smartphone it doesn't work.

Thank you !

________________________________
Da: GustavoIO <notifications@github.com>
Inviato: martedì 20 dicembre 2016 16.49
A: phonegap/phonegap-plugin-push
Cc: fattanasio; Comment
Oggetto: Re: [phonegap/phonegap-plugin-push] Phonegap/Ionic push notifications in iOS when app was closed (#494)


I don't remember anymore... Ask something more tangible and I'll check against the code base.

-

**Comment by GustavoIO** [comment]
Oh, I never had problems in Android.
Only for iOS.

**Comment by fattanasio** [comment]
Ok, thank you


________________________________
Da: GustavoIO <notifications@github.com>
Inviato: martedì 20 dicembre 2016 16.58
A: phonegap/phonegap-plugin-push
Cc: fattanasio; Comment
Oggetto: Re: [phonegap/phonegap-plugin-push] Phonegap/Ionic push notifications in iOS when app was closed (#494)


Oh, I never had problems in Android.
Only for iOS.

-

**Comment by NilsonUehara** [comment]
@GustavoIO  Did you resolve the IOs bug (receiving push notification on background/app closed)?
I need process notifications when my app is closed or in background, but I only receipt the notifications when I click on the message notification, if I open app by click in icon nothing happens.

**Comment by vahidvdn** [comment]
I have the same problem. Any idea?

**Comment by NilsonUehara** [comment]
I stopped using this plugin and switched to https://github.com/arnesson/cordova-plugin-firebase

**Comment by vahidvdn** [comment]
@NilsonUehara Does it work fine when app is closed? How do you send push notifications? (for example I use ionic io dashboard to send the push)

Thanks.

**Comment by NilsonUehara** [comment]
Yap. Works fine! Send notifications same as phonegap-plugin-push.

**Comment by vahidvdn** [comment]
@NilsonUehara Thanks. I'm going to try it. And one more question, does it work fine in ios as well as android?

**Comment by NilsonUehara** [comment]
Yes.

**Comment by vahidvdn** [comment]
@NilsonUehara 
Your mentioned plugin requires to put `google-services.json` (That I get from Firebase)  in my root directory. 

As I use ionic push service, I should build my app by cloud build and put my Firebase server key there (in order to send push notification). Ionic cloud build only send `www` directory of my app and build it. So, no other files is going to be sent.
Any idea?
