### ISSUE TITLE
Windows Phone 8.1 : How can I choose this plugin use WNS or MPNS to get an channel URI ?

### ISSUE THREAD

**Issue by charpin** [phonegap/phonegap-plugin-push#497]
I'm currently to implement the windows notification. 

My mobile application is target to Windows Phone 8.1 Universal. This version use both WNS and MPNS support.

From server side in Java, I use the plugin Java-MPNS from https://github.com/notnoop/java-mpns. 

When I get a channel URI from your plugin (by default), the channel URI is like this :

https://db5.notify.windows.com/?token=****

As you know, the link *.notify.windows.com is an WNS channel URI. 

But the plugin Java is only for MPNS. So, can you tell me how I can get an MPNS channel URI from your plugin ? 

The channel URI from MPNS is like this :

*.notify.live.net/?token=***

**Comment by macdonst** [comment]
This plugin does not and will not support MPNS. It is mean to be used with WNS only and Windows Universal.
