### ISSUE TITLE
Support for redirects on android notification image

### ISSUE THREAD

**Issue by Papipo** [phonegap/phonegap-plugin-push#499]
Hi,

I'm not sure if this is doable, but I am trying to use this kind of image in a notification, without luck:

`https://instagram.com/p/fA9uwTtkSN/media/?size=t`

The URL redirects to the actual image. Somehow I think that I was able to use this in the past, but I am not really sure.

Should it work as is? Right now I get the notification title and message, but not the image.

Thanks,
Rodrigo.

**Comment by macdonst** [comment]
@Papipo platform, plugin versions, payload, etc?

You are expecting the plugin to follow the http redirect and show the final image in the push notification? Are you using this image as the icon or as a big picture notification?

**Comment by Papipo** [comment]
Platform: Android
Plugin version: 1.4.4

Example payload:

```
{"ledColor"=>[0, 186, 34, 83],
"vibrationPattern"=>[500, 500, 500],
"priority"=>1,
"cb"=>{"name"=>"newContent", "args"=>["photos"]},
"title"=>"Nueva foto",
"message"=>"Pan integral multisemillas para principiantes", "image"=>"http://instagr.am/p/BAffPjFqZmo/media/?size=t"}
```

Yes, the idea is that the app follows the redirect and displays the image on the notification.

**Comment by macdonst** [comment]
@Papipo I'm using the HttpURLConnection class and it should follow up to 5 redirects as per the docs. What I notice in your example payload you are using:

`"image"=>"http://instagr.am/p/BAffPjFqZmo/media/?size=t"`

but it eventually redirects to a https site. Can you try with:

`"image"=>"https://instagr.am/p/BAffPjFqZmo/media/?size=t"`

and let me know what you see?

**Comment by Papipo** [comment]
You are right, it works perfectly with https.
