### ISSUE TITLE
[FIX] notification not fired when app is in background/killed ? Check this out

### ISSUE THREAD

**Issue by smileapplications** [phonegap/phonegap-plugin-push#502]
Hello everyone,
i'm writing this because I spent 2 days looking at this problem and I don't want other people to lose so much time.

If your notifications are fired only on foreground and not in background is because you only called init() without on('registration')

You need to do like this:

```var push = PushNotification.init(options);
                  push.on("registration", function(token) {});
                  push.on("notification", function(notification) {
alert("Notification clicked");
}```

**Comment by macdonst** [comment]
@smileapplications that doesn't seem correct at all. I'm closing this issue as it does not seem to provide any information. Please feel free to re-open with more info.
