### ISSUE TITLE
GCM topic to iOS is received, but no sound, vibration and badge

### ISSUE THREAD

**Issue by bardu** [phonegap/phonegap-plugin-push#509]
The issue79 branch has fixed issue [404](https://github.com/phonegap/phonegap-plugin-push/issues/440) which is a great step forward.

However, I open this issue because when topic is received there is no sound, vibration and badge.

This is my client setup:
```js
function _initPush() {
        var topics = _getTopics();
        var push = PushNotification.init({
            android: {
                senderID: app.config.gcm.senderID,
                topics: topics
            },
            ios: {
                senderID: app.config.gcm.senderID,
                gcmSandbox: "true",
                alert: "true",
                badge: "true",
                sound: "true",
                vibration: "true",
                clearBadge: "true",
                topics: topics
            }
        });
        
        push.on('registration', function(data) {
             console.log('Registration ID: ' + data.registrationId);
        });
        
        push.on('notification', function(data) {
            //TODO: update badge
            console.log('Push on notification')
            console.dir(data)
            push.finish(function() {
                console.log('Processing of push data is finished');
            });
        });
        
        push.on('error', function(e) {
            console.log('PushNotification error: ' + e.message);
        });
    }
```

On the service side I'm using node-gcm package like this:
```js
var topic = _.findWhere(getTopics(), {"name": data.new_val.category[0]});
    if ( typeof topic !== typeof undefined ) {
        var message = new gcm.Message({
                            priority: 'high',
                            count: 1,
                            contentAvailable: true,
                            //dryRun: true, 
                            notification: {
                                title: 'Yukon Now',
                                body: data.new_val.desc
                            }
                        }),
            sender  = new gcm.Sender(config.gcm.api_key);
            
            sender.send(message, {topic: '/topics/' + topic.topic}, function(err, response) {
                if (err) {
                    console.error(err);
                }
                else {
                    console.log('Push success: ' + JSON.stringify(response));
                }
            });
    }
```

When the topic is receive on my iPhone 6 the console output looks like this:

> 2016-01-14 12:08:51.242 YukonNow[869:513841] didReceiveNotification with fetchCompletionHandler
2016-01-14 12:08:51.242 YukonNow[869:513841] app in-active
2016-01-14 12:08:51.242 YukonNow[869:513841] this should be a silent push
2016-01-14 12:08:51.242 YukonNow[869:513841] Notification received
2016-01-14 12:08:51.242 YukonNow[869:513841] Push Plugin key: content-available
2016-01-14 12:08:51.242 YukonNow[869:513841] Push Plugin key: alert
2016-01-14 12:08:51.257 YukonNow[869:513841] Push Plugin finish called
2016-01-14 12:08:51.332 YukonNow[869:513841] didReceiveNotification with fetchCompletionHandler
2016-01-14 12:08:51.332 YukonNow[869:513841] app in-active
2016-01-14 12:08:51.332 YukonNow[869:513841] this should be a silent push
2016-01-14 12:08:51.332 YukonNow[869:513841] Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.
2016-01-14 12:08:51.332 YukonNow[869:513841] Notification received
14 12:08:51.333 YukonNow[869:513841] Push Plugin key: content-available
2016-01-14 12:08:51.333 YukonNow[869:513841] Push Plugin key: alert
2016-01-14 12:08:51.334 YukonNow[869:513841] Push Plugin finish called
2016-01-14 12:09:11.330 YukonNow[869:513841] Push Plugin stopBackgroundTask called
2016-01-14 12:09:11.331 YukonNow[869:513841] Push Plugin handlerObj
2016-01-14 12:09:11.333 YukonNow[869:513841] Push Plugin: stopBackgroundTask (remaining t: 9.981632)

**Comment by macdonst** [comment]
@bardu great bug report :+1:

**Comment by bardu** [comment]
Is there anything I can do helping to fix this bug?  Unfortunately, I'm not a native programmer.

**Comment by macdonst** [comment]
@bardu no, unless you know Objective-C it's going to be hard for you to contribute to the fix. However, you have written a great bug report. Being able to reproduce a bug is the key step in fixing it. Also, when I've got a fix I'll enlist you in testing. 

It's been a bit crazy this month as we were putting on PhoneGap Day US. Actually we just finished up and folks are flying home today. :airplane:

**Comment by bardu** [comment]
@macdonst  any chance to get a fix in 1.6.0 release?

**Comment by macdonst** [comment]
@bardu haven't had a chance to work on it yet. If not 1.6.0 then 1.6.x,

**Comment by denisbabineau** [comment]
+1, this one isn't on my radar yet but it might be soon. I can assist in testing/debugging as well. Push comes to shove, I'll dive in the ObjC if needed.

**Comment by bardu** [comment]
This seems to be one of the oldest bugs. I checked with the plugin v1.6.1 and it still persist.

Same issue on [Android](https://github.com/phonegap/phonegap-plugin-push/issues/772#issuecomment-205407102)

@macdonst  Any chance for a fix?

**Comment by macdonst** [comment]
@bardu haven't had much of a chance to look at it but I will look at it for the next release.

**Comment by bardu** [comment]
Using plugin v1.6.2, cordova-ios v4.1.0 and a payload such as:
```
{
                            priority: 'high',
                            delayWhileIdle: true,
                            timeToLive: 3,
                            content_available: true,
                            notification: {
                                url: 'infos',
                                title: 'Whitehorse Now',
                                body: data.new_val.title,
                                sound: 'default',
                                badge: 1
                            }
                        }
```
solved the issue.

@macdonst Thanks for all your hard work!
