### ISSUE TITLE
GCMIntentService.java:139: error: cannot find symbol mBuilder.setColor(iconColor);

### ISSUE THREAD

**Issue by mwillbanks** [phonegap/phonegap-plugin-push#51]
symbol:   method setColor(int)
  location: variable mBuilder of type Builder

**Comment by macdonst** [comment]
@mwillbanks What version of Android are you using?

**Comment by macdonst** [comment]
@mwillbanks are you using the "android-support-v13.jar" that is provided in this project? It contains the proper jar that has the setColor method.

**Comment by macdonst** [comment]
@mwillbanks I tested on a 4.4.4 device this afternoon with no problems.

**Comment by Hirbod** [comment]
I've the same problem right now. I needed to delete the support-v13 reference cause by "multiple dex" warnings. I can't any way to get this plugin compile.

**Comment by Dr-Horv** [comment]
Having the same problem. With support-v13 file in platforsm/android/libs I get multiple dexfiles error. If I  "android-support-v13.jar" then I get this problem.

**Comment by Hirbod** [comment]
I give up. Struggeled more then 4 days with this problem and I can't get any support on this. As soon as Facebook is integrated (or any other plugin which needs the v13 support, we get this)

The v13 seems to be only integrated because of the "setColor()" method. Now my notifications look ugly, but I've commented out the line.

**Comment by mwillbanks** [comment]
@Hirbod you need to remove the support library from the facebook SDK, basically search your codebase for where the items are before you build...  

AKA: 
```
find platforms/android -name "android-support*.jar" | grep -v build
```

If you find duplicates or multiple versions, remove the multiple versions.  You can only have *1* support library in your project.  The issue becomes is that many plugins attempt to ship one and it causes conflicts between projects.  I suggest removing all support libraries that a plugin has and then to manually place one in your libs folder.

**Comment by Hirbod** [comment]
Thank you very much. If I remove the support lib from facebook, I can't compile. The only working solution for me was to remove all support libs from /libs/ inside of platform/android and to leave one support file inside of facebook (I have "CCSoft" Facebook plugin installed, the SDK isn't inside of my platform folder, it's placed in my download folder and got referenced manually inside of eclipse as library).

I can't switch to any other facebook plugin at the moment, but I will try your suggestion, maybe I can find a way.

**Comment by Hirbod** [comment]
I tried your "find" command. No results. :(

**Comment by mwillbanks** [comment]
Interesting, your paths might be references differently than provided your earlier comment then; all of mine are inside of the platforms/android folder itself.  You would need to add the additional paths in that case.

For instance:
```
find platforms/android -name "android-support*.jar" | grep -v build
platforms/android/com.phonegap.plugins.facebookconnect/app-FacebookLib/libs/android-support-v13.jar
platforms/android/libs/android-support-v13.jar
```

**Comment by Hirbod** [comment]
I've removed android-support-v13.jar from the /libs/ folder. Also the v14.jar. I don't use the facebookconnect plugin, my support-v13 libs is inside /Users/myname/Downloads/facebooksdk/facebook/libs/android-support-v13.jar

**Comment by Hirbod** [comment]
@mwillbanks and @macdonst 

I've removed the facebook plugin and also the push plugin, removed android platform, readded android platform and the push plugin, but I get this error message:

```
/.../platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:139: error: cannot find symbol
            mBuilder.setColor(iconColor);
```

When I look inside of my /libs/ folder, there is support-v13.jar and support-v4.jar

I've opened the plugin folder, support-v13 and gcm.jar are inside.
Inside of plugin.xml I can see:

```xml
		<source-file src="src/android/libs/android-support-v13.jar" target-dir="libs/" />
```

So what's wrong now?

**Comment by Hirbod** [comment]
Hi again, sorry for that spam. For everybody who stuck on this, I've managed to get this work.
Go inside of plugins/phonegap-plugin-push/src/android/libs/ and copy android-support-v13.jar

Copy it and replace with the one inside of platforms/android/src

Double-Check that there is NO android-support-v4.jar inside of it. When you find v4, just delete it. Now, the plugin build without problems.

I will change my facebook plugin to https://github.com/jeduan/cordova-plugin-facebook4 as this one seems to be a drop-in-replacement and much more active then the official one or the cc-soft one. They also have fixed the multiple DEX problem.

**Comment by macdonst** [comment]
@Hirbod I'm glad you got it resolved. As soon as PhoneGap Build supports gradle I'm switching this plugin to use the "framework" tag which should avoid these dexing problems for good.

**Comment by Hirbod** [comment]
@macdonst thank you very much. My app is working perfectly right now. Push work's also as expected now. Finally :dancer:

**Comment by Dr-Horv** [comment]
@macdonst I'm having similiar issue as Hirbod. Although I cannot seem to resolve it by the same steps. I've tried about anything and lost track of what I have and haven't tried. I've concluded that the facebook-connect plugin I'm using https://github.com/uofmmike/phonegap-facebook-plugin clashes with this one on the support-library thing. It seems in either way I remove them respectively plugin doesn't compile. Do you have any tips of step to try resolve this?

Would it be hard to change this plugin to use framework tag? I'm not using phone gap build, rather cordova build. Which as I understand it has gradle support.

**Comment by macdonst** [comment]
@Dr-Horv yeah, the fix is crazy easy to implement and in fact there is already a PR waiting for when PGB is ready. 

https://github.com/keab42/phonegap-plugin-push/commit/472548af8c9235a0bb459bf2bd9b434d6db8eda3

I will try and use the Facebook plugin with this plugin in an app later to see if there is anything I can do in the meantime.

**Comment by untitledlt** [comment]
@Hirbod did you mean `platforms/android/lib/`?
I tried your suggestion but that does not help.

@macdonst  I have tried to replace those lines as in keab42@472548a but that does not help either...

Any other fixes available?

**Comment by shprink** [comment]
If you are having trouble with Facebook plugin, this fixes it:

```
cp platforms/android/libs/android-support-v13.jar platforms/android/com.phonegap.plugins.facebookconnect/active-FacebookLib/libs/
rm platforms/android/com.phonegap.plugins.facebookconnect/active-FacebookLib/libs/android-support-v4.jar
```

**Comment by hobbysoldat** [comment]
Why is everyone embedding JARs in their Plugins? I thought the new way to to it was using 

  ` <platform name="android">
      <framework src="com.google.android.gms:play-services-gcm:+" /> </platform>`

To pull in dependencies via gradle, and avoid all these conflicts?

**Comment by macdonst** [comment]
@hobbysoldat you are correct. However, PhoneGap Build does not support Gradle yet so I haven't made the switch. I think when I get back off vacation I will switch it and PGB users will have to use version 1.2.2 or earlier.

**Comment by hobbysoldat** [comment]
Sorry for the dupe.

**Comment by macdonst** [comment]
@hobbysoldat no problem, I'm just trying to keep all the discussion on this topic in one thread.

**Comment by alamops** [comment]
@shprink thank you!

**Comment by ZoRDoK** [comment]
@Hirbod
Tnx, you save me out of few hours of headache

**Comment by kentmw** [comment]
Has anyone experienced this issue while using Phonegap Build to assemble the apk?

**Comment by Hirbod** [comment]
Missing symbols. Add android support and google play library via sdk manager

**Comment by kentmw** [comment]
@Hirbod, sorry, was that comment directed at my question? Phonegap Build, or PGB, found here: https://build.phonegap.com, builds the application in the "cloud" or at least on adobe's server. I don't have access or control of sdk manager while using PGB

**Comment by Hirbod** [comment]
hi @kentmw - sorry, I mixed something up with email notification. Please ignore my message

**Comment by adyz** [comment]
I have this issue too. Any solutions that do not imply removing facebook plugin?

**Comment by hobbysoldat** [comment]
Yes. there is a version of the facebook plugin that works with this plugin.
just look at this plugins readme page, it has been updated.

phonegap plugin add https://github.com/jeduan/cordova-plugin-facebook4

2015-10-21 14:44 GMT+02:00 Florescu Adrian <notifications@github.com>:

> I have this issue too. Any solutions that do not imply removing facebook
> plugin?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-plugin-push/issues/51#issuecomment-149883607>
> .
>



-- 
Paul Weber, BSc.
Tel: +43(0)699 18 144 914

**Comment by hobbysoldat** [comment]
It uses gradle dependencies instead of hardcoding stuff.

2015-10-21 15:39 GMT+02:00 Paul Weber <p4ul.weber@gmail.com>:

> Yes. there is a version of the facebook plugin that works with this
> plugin. just look at this plugins readme page, it has been updated.
>
> phonegap plugin add https://github.com/jeduan/cordova-plugin-facebook4
>
> 2015-10-21 14:44 GMT+02:00 Florescu Adrian <notifications@github.com>:
>
>> I have this issue too. Any solutions that do not imply removing facebook
>> plugin?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/phonegap/phonegap-plugin-push/issues/51#issuecomment-149883607>
>> .
>>
>
>
>
> --
> Paul Weber, BSc.
> Tel: +43(0)699 18 144 914
>



-- 
Paul Weber, BSc.
Tel: +43(0)699 18 144 914

**Comment by adyz** [comment]
With facebook4 I get another type of error... :(

**Comment by adyz** [comment]
This to be more exact:


		
		FAILURE: Build failed with an exception.
		
		* What went wrong:
			Execution failed for task ':processArmv7DebugManifest'.
		> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library /Users/adrian/Desktop/Vivre/Setup-Centos-PuPHPet/cordova-app-push/platforms/android/build/intermediates/exploded-aar/com.facebook.android/facebook-android-sdk/4.7.0/AndroidManifest.xml
		Suggestion: use tools:overrideLibrary="com.facebook" to force usage

**Comment by Hirbod** [comment]
I know this error. You're using Crosswalk @adyz and there is currently a bug.

You need to run like that

```bash
> cordova run android -- --minSdkVersion=15
```
```bash
> cordova run android --release -- --minSdkVersion=15
```

Did you see the double -- ? Yes, it has to be EXACTLY like this, or it won't work.

**Comment by adyz** [comment]
@Hirbod  Thanks a ton!!! 

I'm new to all this (cordova, android, ios) and it's a bit overwhelming.

**Comment by hobbysoldat** [comment]
or you could add    <preference name="android-minSdkVersion" value="15" />
to your config.xml

2015-10-21 16:50 GMT+02:00 Florescu Adrian <notifications@github.com>:

> @Hirbod <https://github.com/Hirbod> Thanks a ton!!!
>
> I'm new to all this (cordova, android, ios) and it's a bit overwhelming.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-plugin-push/issues/51#issuecomment-149920385>
> .
>



-- 
Paul Weber, BSc.
Tel: +43(0)699 18 144 914

**Comment by Hirbod** [comment]
Will not work when crosswalk is installed as it gets overwritten

**Comment by nadavb** [comment]
Guys - I see you're talking about the libs folder inside /platforms/android - but I don't have one...
How come?

**Comment by macdonst** [comment]
@nadavb because we no longer need to add jars to this plugin. They've been replaced with frameworks.

**Comment by bvivek20** [comment]
Agreed that jars are not added now, but i still get this error GCMIntentService.java:565: error: cannot find symbol

**Comment by macdonst** [comment]
@bvivek20 update your Android Support Library.

**Comment by bvivek20** [comment]
i already did that. new version is 23.1.1 

i removed and added android platform again, i still get this error

**Comment by JiiBay** [comment]
Having the same issue, running last version of Cordova, all is up to date in the Android SDK manager, and tried to remove and add the platform / the plugin many times...

**Comment by JerryBels** [comment]
Having the same issue, running last version of Cordova, all is up to date in the Android SDK manager, and tried to remove and add the platform / the plugin many times...

**Comment by fredgalvao** [comment]
@JerryBels  That's a bug in these other plugins you mentioned, not on `phonegap-plugin-push`. Report an issue to their authors and request it to be updated to support gradle builds and framework dependencies.

**Comment by Apee** [comment]
Wow thanks a lot guys the combination of @Hirbod  and @hobbysoldat made it work for me ! THANKS!!!!

**Comment by zabojad** [comment]
I'm experiencing this error but reading at your previous comments, I'm not really sure what I should do. Here is what I have:
```
/Users/thomasfetiveau/wksp_wink/wink_app/cordova/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:571: error: cannot find symbol
            mBuilder.setColor(iconColor);
```
And:
```
$ find platforms/android -name "android-support*.jar" | grep -v build
platforms/android/phonegap-facebook-plugin/wink-FacebookLib/libs/android-support-v4.jar
$ cordova plugin list
cordova-plugin-crosswalk-webview 1.5.0 "Crosswalk WebView Engine"
cordova-plugin-whitelist 1.2.0 "Whitelist"
phonegap-facebook-plugin 0.12.0 "Facebook Connect"
phonegap-plugin-push 1.5.2 "PushPlugin"
```
With latest version of Android support lib installed (23.1.1) and android target freshly removed/re-added.

If I just remove `platforms/android/phonegap-facebook-plugin/wink-FacebookLib/libs/android-support-v4.jar`, it does not compile neither...

What should be done ?

**Comment by zabojad** [comment]
Uups, I've posted too fast, the issue actually comes from the facebook plugin and I've managed to fix this issue with this: https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1183

**Comment by zabojad** [comment]
OK, I know what was happening, I was not actually using the correct app secret...

Sorry for posting a issue too fast...

**Comment by fredgalvao** [comment]
@zabojad or you could follow the suggested steps at https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#co-existing-with-facebook-plugin
