### ISSUE TITLE
Phonegap build iOS error with latest version

### ISSUE THREAD

**Issue by lordamon** [phonegap/phonegap-plugin-push#514]
I am using phonegap build, when i try to build with the latest version of this plugin i get this error on iOS (android works fine):
Error - A plugin in your app does not support the compulsory arm64 (64-bit support) architecture.

The error disapper if i use the 1.4.5 version.

**Comment by macdonst** [comment]
@lordamon what version of phonegap do you specify in your config.xml sent to PGB?

**Comment by lordamon** [comment]
i use the latest one:
<preference name="phonegap-version" value="cli-5.2.0" />

**Comment by donaldinou** [comment]
I've got the same here with the latest version (1.5.3).
I use this plugin with ionic framework.
I install the v1.4.5 and build is fine on ios. There is no errors with android (1.5.3 and 1.4.5).

**Comment by bau720123** [comment]
I think this issue is the same with my post before
https://github.com/phonegap/phonegap-plugin-push/issues/449

**Comment by macdonst** [comment]
the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
