### ISSUE TITLE
Register new topic

### ISSUE THREAD

**Issue by fritek373** [phonegap/phonegap-plugin-push#516]
Used the array from this issue: https://github.com/phonegap/phonegap-plugin-push/issues/450; but somehow it isn't working for me. I've the following function, that's called in another function with a *deviceready* "hold".
```
function registertopic(topic){
	var push = PushNotification.init({
		android: {
			senderID: "999", //this necessary for Android?
			topics: "['"+ topic +"']"
		},
	});	
}
```

**Comment by fritek373** [comment]
Do I need to add some other code to the function?

**Comment by macdonst** [comment]
@fritek373 seems correct to me. What do you see in `adb logcat | grep PushPlugin` when you run this code?

**Comment by fritek373** [comment]
Im using PhoneGab Build, everything (register and receiving) is werking as it should. Function is called with:
```
<input type="button" onclick="registertopic('test');" />
```
