### ISSUE TITLE
action callback with parameter ? Or input in notification like WindowsPhone10 

### ISSUE THREAD

**Issue by Xwalk-Company** [phonegap/phonegap-plugin-push#517]
would it be possible to pass parameters to the callback function of the notification? Or in any way whatsoever?

For insider mobile windows 10, the mail application allows us to respond directly in the notification. It's fantastic, is it possible in this case for all platforms?

Thank you

**Comment by diegobill** [comment]
:+1:

**Comment by yanivok** [comment]
Same question here.
is it possible to pass parameters to notification's callback function?

**Comment by Zeipt** [comment]
Found this for Android
http://stackoverflow.com/questions/36834956/cordova-android-push-notification-with-action-button

**Comment by macdonst** [comment]
Well input notification is coming in Android N which is issue #683.

If you want to input parameters for action buttons:

Okay, first imagine you are sending the following payload:

    {
        "registration_ids": ["my device id"],
        "data": {
            "title": "My title",
            "message": "My message.",
            "actions": [
                { "title": "Accept", "callback": "app.accept", "foreground": true},
                { "title": "Ignore", "callback": "app.ignore", "foreground": false}
            ]
        }
    }

and you have setup the following action button handlers:

    app.accept = function(data} {
      // do something
    }
    
    app.ignore = function(data} {
      // do something
    }

so now you have two options you can either put something in the push payload that uniquely identifies the push that was received which will be put in data.additionalData or modify the callbacks to call another event handler:

    app.accept = function(data} {
      app.processPush('accept', data);
    }
    
    app.ignore = function(data} {
      app.processPush('ignore', data);
    }

    app.processPush = function(type, data) {
      if (type === 'accept') {
        // do accept stuff
      } else if (type === 'ignore') {
        // do ignore stuff
      }
    }

**Comment by Xwalk-Company** [comment]
Thank you, I did not use the payload not included. I will try this solution.

For live reply feature is great news that surely many people waiting (the best thing that had WP)

**Comment by sanvenkur** [comment]
+1 same question. Is their any way to send parameters inside action button callback ?
