### ISSUE TITLE
Loosing notification resource icons upon `ionic platform rm / add`

### ISSUE THREAD

**Issue by zwacky** [phonegap/phonegap-plugin-push#519]
hey,
is there a way to not manually have to put notification icons into `platforms/android/res` after i did a ionic `ionic platform rm android`?
i figured this is more plugin related than ionic.

**Comment by macdonst** [comment]
@zwacky nope, if you delete the platforms directory you will lose the icons under res as well. 

You are better off storing the icons in the root of your project and using a hook to copy the icons to the correct folders. @hollyschinsky has a good article that includes a hook you can use to do just that.

http://devgirl.org/2013/11/12/three-hooks-your-cordovaphonegap-project-needs/
