### ISSUE TITLE
iOS Action Button Exception

### ISSUE THREAD

**Issue by ggiordan** [phonegap/phonegap-plugin-push#521]
When I try to have iOS action buttons, I get a nil pointer exception in pushPlugin.m here:
```obj-c
if (yesButton != nil) {
    [categoryArray addObject:yesAction];
    [minimalCategoryArray addObject:yesAction];
}
```
The problem is that yesAction is nil.  yesAction should get initialized a few lines above:
```obj-c
if (yesButton != nil && [yesButton  isKindOfClass:[NSDictionary class]]) {
    yesAction = [self createAction: yesButton];
}
```
However, createAction is returning a nil.

In createAction, these allocations seem to get nil (the allocation failed?):
```obj-c
- (UIMutableUserNotificationAction *)createAction:(NSDictionary *)dictionary {

    UIMutableUserNotificationAction *myAction = [[UIMutableUserNotificationAction alloc] init];

    myAction = [[UIMutableUserNotificationAction alloc] init];
```
For my PushNotification.init, I cut and paste the code from the iOS example.

I'm using the following versions:
phonegap-plugin-push 1.5.3 "PushPlugin"
Installed platforms: ios 3.9.2
cordova --version
5.3.3

I'm really stuck and pointers / guidance would be greatly appreciated.

**Comment by macdonst** [comment]
@ggiordan can you show me the options you use when calling  `PushNotification.init()`?

**Comment by ggiordan** [comment]
Hi Thanks!!  Here is the code.  At the moment, the button text is a bit nonsensical, I was getting it to work first using the sample in the documentation.  Then I'll fix it up.

    push = PushNotification.init({
        "android": { "senderID": "xxxxxxxxxxxxxx" },
        "ios": {
            "alert": "true",
            "badge": "true",
            "sound": "true",
            "categories": {
                "invite": {
                    "yes": {
                        "callback": "app.accept",
                        "title": "RESPONDING",
                        "foreground": true,
                        "destructive": false
                    },
                    "no": {
                        "callback": "respondingButton",
                        "title": "RESPONDING",
                        "foreground": true,
                        "destructive": false
                    },
                    "maybe": {
                        "callback": "respondingButton",
                        "title": "RESPONDING",
                        "foreground": true,
                        "destructive": false
                    }
                }
            }
        },
        "windows": {}
    });

My development device is an iPhone 4, (iOS 7?, I don't have the device handy at the moment)

I did realize that the buttons must be "yes", "no" and "maybe".

**Comment by macdonst** [comment]
@ggiordan yeah, action buttons are only available in iOS 8 and later. I should protect against that code attempting to be called in iOS7.

**Comment by ggiordan** [comment]
Ok, makes sense.

I agree, the version check would be a good idea.
Also, a documentation update to reflect the following:
1) only supported for iOS8+
2) buttons MUST be named yes, no and maybe

Thanks for your super plugin!! and the assist!

**Comment by macdonst** [comment]
![push6-ios](https://cloud.githubusercontent.com/assets/353180/12754125/12d13020-c998-11e5-98b4-b245fda30490.png)
