### ISSUE TITLE
notification event never received while application is in background (Nexus 6 / Android 6.0.1 / Cordova 5.4.1) 

### ISSUE THREAD

**Issue by oNoez** [phonegap/phonegap-plugin-push#523]
GCM test message:

to": [
    "massive device id"
  ],
 "data": {
    "reference": "reference string"
  },
  "notification": {
    "title": "Something is amiss!",
    "body": "Don't complain, at least you got a message on this plugin, unlike the other 3 we tried",
    "sound": "default",
    "tag": "SpamFree!"
  }

So when I receive the above message with the application in the foreground we are all good; my Logcat parser shows GCM getting pinged on-device, GCM referring that message over to the plugin in the form of onMessageReceived firing off (thanks for the detailed logging!), and as a result, my callback set for notification firing off.

Where we go wrong is when the application is in the background.

From my understanding, when the application is in the background, onMessageReceived will not fire unless a couple conditions are met:

1) the user has interacted with the message in the form of a click
2) the message itself has a top tier "data" element with a key-value pair in it

Both of these conditions are met with the above test message and an accompanying click, however, onMessageRecieved seems to not be fired. In this instance, Logcat does not show the same log trace as when the application is in the foreground, instead, I see the message come in from GCM, but no logs from the plugin, indicating that it was never fired from GCM.

The notification still opens the application, however the accompanying event not being fired means that they do not come in with context related to the notification.

I'm sure it's probably a PEBKAC error, so any help would be appreciated.

Cheers

Logs attached:

[while-app-force-terminated.txt](https://github.com/phonegap/phonegap-plugin-push/files/93303/while-app-force-terminated.txt)
[while-in-background.txt](https://github.com/phonegap/phonegap-plugin-push/files/93304/while-in-background.txt)
[while-in-foreground.txt](https://github.com/phonegap/phonegap-plugin-push/files/93305/while-in-foreground.txt)

**Comment by macdonst** [comment]
@oNoez retest with this data and report back:

```
to": [
"massive device id"
],
"data": {
  "reference": "reference string"
  "title": "Something is amiss!",
  "body": "Don't complain, at least you got a message on this plugin, unlike the other 3 we tried",
  "sound": "default",
  "tag": "SpamFree!"
}
```

**Comment by fredgalvao** [comment]
If @macdonst 's suggestion fixes it for you, please close this issue as a duplicate of https://github.com/phonegap/phonegap-plugin-push/issues/515.

**Comment by oNoez** [comment]
That's got it.

Cheers and closing issue.
