### ISSUE TITLE
Adding plugin complains of older cordova version even when latest cordova version is installed

### ISSUE THREAD

**Issue by divkis01** [phonegap/phonegap-plugin-push#524]
Trying to install the plugin as mentioned in docs leads to the following error:

$ cordova plugin add phonegap-plugin-push
Fetching plugin "phonegap-plugin-push@^1.5.3" via npm
npm http GET https://registry.npmjs.org/phonegap-plugin-push
npm http 304 https://registry.npmjs.org/phonegap-plugin-push
Plugin "phonegap-plugin-push" already installed on android.
Installing "phonegap-plugin-push" for browser
Failed to install 'phonegap-plugin-push':CordovaError: Plugin doesn't support this project's cordova version. cordova: 3.5.2, failed version requirement: >=3.6.3
    at checkEngines (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:116:29)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:289:16
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
Plugin doesn't support this project's cordova version. cordova: 3.5.2, failed version requirement: >=3

While the cordova version that I have is 5.0.0.

$cordova --version
  5.0.0

I am not sure why is it complaining about older cordova version.

**Comment by macdonst** [comment]
What version of Cordova Android do you have installed?

Run "cordova platforms"

**Comment by divkis01** [comment]
cordova platforms
Installed platforms: android 4.0.0, browser 3.5.2, ios 3.8.0
Available platforms: amazon-fireos, blackberry10, firefoxos, ubuntu

Although browser platform is unused / not needed in my case.

**Comment by macdonst** [comment]
@divkis01 right, and the engine tag in the plugin says the minimum version of cordova on any platform be 3.6.3 so the fact you have 3.5.2 version of browser installed it fails, which is expected behaviour. 

You'll either need to upgrade or remove the browser version. Actually for iOS, you'll want to upgrade to 4.0.1 as well.
