### ISSUE TITLE
Appcelerator Server Push notification

### ISSUE THREAD

**Issue by rafasegat** [phonegap/phonegap-plugin-push#527]
Hello,

Is possible send pushs with Appcelerator Server and receive the Pushs with this plugin?

Thanks!
Raf

**Comment by charpin** [comment]
Hi Rafasegat,

I don't use this framework but I checked the documentation and I found that is possible to send notifications with Appcelerator. 

You should be check the *PushNotifications-method-notify* API from this framework.

Yes you do. You can use this plugin to manager notifications received on your device. I'm using some Java API to send notifications to android, iOS and Windows device.
