### ISSUE TITLE
Sound not set on iOS 9.2

### ISSUE THREAD

**Issue by rioadrian** [phonegap/phonegap-plugin-push#528]
Hi, i'm using meteor and raix:push meteor package which use phonegap plugin push for notification plugin. I'm having trouble when setting notification center that there is no sound on notification center. I this issue will be fixed after I go through PushPlugin.m and change `UIUserNotificationSettings *settings = [UIUserNotificationSettings settingsForTypes:UIUserNotificationTypeAlert | UIUserNotificationTypeBadge | UIUserNotificationTypeSound categories:nil];`
I hope You can fix this so I dont have to change it manually after meteor reset.

Big Thanks & Regards
Rio

**Comment by macdonst** [comment]
@rioadrian why do you need to change it manually? What options do you use when you call init?

**Comment by neffnet** [comment]
I am having a similar problem here, ios 9.2. We are using APNS and GCM separately. Notifications work as expected on Android, but on ios (we are testing on an iPhone 5s 9.2.1 and an iPad 9.2) the alert arrives silently and without vibration.

Here is how we call init:
```
  var push = PushNotification.init({
    android: {
      senderID: "10xxxxxxxx"
    },
    ios: {
      badge: false,
      alert: true,
      sound: "default"
    }
  });
```
We've tried variations on this such as
   badge: "false", badge:"true",sound:true,sound:"true", etc.
   We also tried the trick of setting the date a few days ahead, rebooting device, resetting time, and rebooting again.

The badge property seems to work correctly, but the sound and vibration behavior is always the same. I notice that in ios notification settings, on other apps I can turn the sound on or off as well as choose the sound, but for my app I only have the on/off option.

**Comment by macdonst** [comment]
@neffnet your params for the init method are not correct. Use: 

```
  var push = PushNotification.init({
    android: {
      senderID: "10xxxxxxxx"
    },
    ios: {
      badge: false,
      alert: true,
      sound: true
    }
  });
```

then if you want the default sound to play upon receipt of push use this payload:

```
{
    "aps": {
        "alert": "Test sound",
        "sound": "default"
    }
}
```

If you want anything other than the default sound see:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#sound-1

**Comment by neffnet** [comment]
Thank you, @macdonst, this solves my issue. I was not setting the default sound on the app server.
Appreciate your fast response!

**Comment by macdonst** [comment]
@neffnet de nada, I'm trying to be as responsive as possible with this plugin. Mind you I really should be working on the work shop I will deliver at next weeks PhoneGap  Day conference which will also, help improve the docs here.
