### ISSUE TITLE
sound notificaiton rest period

### ISSUE THREAD

**Issue by kaynz** [phonegap/phonegap-plugin-push#529]
Hey guys!

I'd like to set a rest period when initializing the pushnotification plugin, for example:

    _push = PushNotification.init({
          android: {
            restperiod: {start: "12:30", end: "22:30"}
          },
          ios: {
            restperiod: {start: "18:30", end: "00:30"}
          });

So, if a new notification arrives on my device and the current smartphone time is in the restperiod, the notification volume will be turned OFF

Is this somehow possible?

Thanks! :)

**Comment by macdonst** [comment]
This is kinda a duplicate of #69

**Comment by kaynz** [comment]
Oh, okay, closing this one!
