### ISSUE TITLE
No default sound in Android

### ISSUE THREAD

**Issue by natanaelmaia** [phonegap/phonegap-plugin-push#53]
The plugin stopped playing notification sounds after I've updated to version 1.1.1 (I’m not passing custom sound file name in the payload).

Maybe the reason is because of the following commented line in GCMIntentService.java bellow:

```
 NotificationCompat.Builder mBuilder =
            new NotificationCompat.Builder(context)
                //.setDefaults(defaults)
                .setWhen(System.currentTimeMillis())
                .setContentTitle(extras.getString("title"))
                .setTicker(extras.getString("title"))
                .setContentIntent(contentIntent)
                .setAutoCancel(true);
```

**Comment by macdonst** [comment]
@natanaelmaia Yes, thanks for pointing that out. I had to comment out setDefaults as it messes with other settings when I try to over-ride them.

**Comment by macdonst** [comment]
Fixed in master

**Comment by natanaelmaia** [comment]
Thanks!

**Comment by natanaelmaia** [comment]
@macdonst I forgot to mention that there is no default vibration also...

**Comment by macdonst** [comment]
@natanaelmaia hmmm...I think these should be properties.
