### ISSUE TITLE
Windows phone registrationId help

### ISSUE THREAD

**Issue by mseppae** [phonegap/phonegap-plugin-push#530]
I am trying to push notification to a Windows Phone, but I get failure about 'invalid token' when sending the push notification (via rpush gem).

Does the registrationId for wpn platform need any special handling or is there something else stupid I am missing?

The registrationId looks legit, in form of "https://db5.notify.windows.com/?token=AwYAAAA...".

iOS and android notifications work fine so I am a little confused and thought of asking here if someone has had similar problem.

**Comment by mseppae** [comment]
This seems to be more of a problem with the [rpush](https://github.com/rpush/rpush/issues/233) gem than this.

**Comment by macdonst** [comment]
@mseppae should we close this issue then?

**Comment by mseppae** [comment]
Yes.
