### ISSUE TITLE
Upload to iTunes Connect fails

### ISSUE THREAD

**Issue by j4hr3n** [phonegap/phonegap-plugin-push#534]
My apps fails during upload to iTunes Connect with this type of error:

`
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'xxx.app/www/lib/phonegap-plugin-push/src/ios/GoogleUtilities/Libraries/libGTM_NSStringHTML.a' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
`

The error as i understand it is caused because `libGTM_NSStringHTML.a` and a lot of files of that sort is added to Link Binary With Libraries in Xcode. The app does however run just fine when i test it on device from Xcode. It is only during upload to iTunes Connect that it fails. 

I have tried removing these files, but then the app will not run at all. I have tried updating the cordova ios platform, removing the platform, rebuilding the project and more. Nothing has helped so far.

Cordova version: 5.0.0
phonegap-plugin-push version: 1.5.3
Xcode version: 7.2
Cordova ios platform version: Tested with 3.8.0, 3.9.1, 3.9.2, 4.0.0, 4.0.1

**Comment by macdonst** [comment]
@j4hr3n Are you somehow including the plugin files in your `www` directory? They shouldn't end up their by default.

**Comment by j4hr3n** [comment]
Yeah, it seems that somehow the plugins from `www` end up in the project, this includes the libraries that break the app. I have never had a problem with that before though. They even stayed behind when i removed the plugin and tried running again. Upon deleting them it worked as expected. Now i just have to figure out why they end up there..

**Comment by macdonst** [comment]
@j4hr3n kk, keep me posted. They shouldn't ever get deployed there.

**Comment by j4hr3n** [comment]
Okay @macdonst, here's the issue. In my `www` folder i have another folder `lib` which contains a number of bower-installed plugins. Somehow phonegap-plugin-push has ended up here with the libraries that broke the build. That has not happened to any other of the cordova plugins i use. Do you know whether phonegap-plugin-push somehow uses bower? If that is the case, we have found the reason.

**Comment by macdonst** [comment]
@j4hr3n yeah, I accepted a PR from someone to add bower support. Check the root of this project and let me know if you see anything wrong. If not, next step is to remove it.

**Comment by rafaelfe** [comment]
Fix for this problem: just remove any plugin folders inside cordova's plugin folder. 
[your project]/plugins/     <-- remove all folders inside this one.

**Comment by tomek360** [comment]
Hello, I can similar problem using phonegap-plugin-push.

ERROR ITMS-90171 "Invalid bundle structure", files with extension .a exist in .IPA file.

I'm using phonegap cloud build with plugin config:
<plugin name="phonegap-plugin-push" source="npm" spec="~1.5.3">

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'XYZ.app/www/platforms/ios/XYZ/Plugins/phonegap-plugin-push/GCM/Libraries/libGTM_core.a' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

![zrzut ekranu 2016-06-01 o 16 18 08](https://cloud.githubusercontent.com/assets/13600855/15712917/7ba25680-2814-11e6-9205-d5cdca022e2a.png)
