### ISSUE TITLE
com.google.android.gms:play-services-gcm:+. Unable to build with VS2015 Apache Tools for Cordova / Ionic

### ISSUE THREAD

**Issue by codingbandit** [phonegap/phonegap-plugin-push#535]
The error:
Could not find any version that matches com.google.android.gms:play-services-gcm:+.

I have searched and found the solution is supposed to be ensuring Android Support Library, Android Support Repository, Google Repository and Google Play services should be installed with Android SDK manager. I have done that and my issue persists. The paths are correct for my Android/Java home. Any advice? 

Here is a segment with a new project with only this plugin installed:
1>------ Rebuild All started: Project: IonicCordovaProject3, Configuration: Debug Android ------
1>  ANDROID_HOME=C:\Users\Carey\AppData\Local\Android\android-sdk
1>  JAVA_HOME=C:\Program Files (x86)\Java\jdk1.7.0_71
1>  Running: C:\SourceCode\IonicCordovaProject3\IonicCordovaProject3\platforms\android\gradlew clean -b C:\SourceCode\IonicCordovaProject3\IonicCordovaProject3\platforms\android\build.gradle -Dorg.gradle.daemon=true
1>
1>  FAILURE: Build failed with an exception.
1>
1>  * What went wrong:
1>  A problem occurred configuring root project 'android'.
1>  > Could not resolve all dependencies for configuration ':_debugCompile'.
1>     > Could not find any version that matches com.google.android.gms:play-services-gcm:+.
1>       Searched in the following locations:
1>           https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
1>           https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/
1>           file:/C:/Users/Carey/AppData/Local/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
1>           file:/C:/Users/Carey/AppData/Local/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/
1>       Required by:
1>           :android:unspecified
1>
1>  * Try:
1>  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
1>
1>  BUILD FAILED
1>
1>  Total time: 2.74 secs
1>  Picked up _JAVA_OPTIONS: -Xmx512M
1>
1>  C:\SourceCode\IonicCordovaProject3\IonicCordovaProject3\platforms\android\cordova\node_modules\q\q.js:126
1>                      throw e;
1>                            ^
1>  Error code 1 for command: cmd with args: /s /c "C:\SourceCode\IonicCordovaProject3\IonicCordovaProject3\platforms\android\gradlew clean -b C:\SourceCode\IonicCordovaProject3\IonicCordovaProject3\platforms\android\build.gradle -Dorg.gradle.daemon=true"
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\ApacheCordovaTools\vs-mda-targets\Microsoft.MDA.FileMirroring.targets(354,5): error MSB3073: The command "platforms\android\cordova\clean.bat" exited with code 1.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by ehlaumarc** [comment]
Just have to download the google repository from Android SDK manager

**Comment by fredgalvao** [comment]
Which non-official cordova plugins do you have installed?

**Comment by codingbandit** [comment]
No other plugins, and I've already downloaded the Google Repository from the Android SDK manager :(
I can create a brand new project, install only this plugin and still have the same problem.

**Comment by codingbandit** [comment]
Cordova CLI 5.1.1

**Comment by macdonst** [comment]
@codingbandit you might be better off asking over on the Visual Studio 2015 forum. It seems like VS can't find where your Android SDK's are installed. Often IDE's like VS will install their own copy of the Android tools. 

Maybe @rakatyal can comment?

**Comment by codingbandit** [comment]
OK, Will do, thanks :)

**Comment by codingbandit** [comment]
I am all fixed up now. Just to let anyone know that may be experiencing this, there was an update posted yesterday for Visual Studio Tools for Apache Cordova (http://blogs.msdn.com/b/visualstudio/archive/2016/01/21/visual-studio-tools-for-apache-cordova-update-5.aspx) . I updated my tools, and selected the now supported CLI version 5.4.1 and it fixed my issue. I am now building and deploying without any issues.

**Comment by romuloinnocencio** [comment]
I have almost the same problem....

```
1>  updated project successfully
1>  Executing "after_prepare"  hook for all plugins.
1>  ------ Copied C:\Users\frontend\Desktop\VSCordova\Smartbabypais\bin\Android\Release\VSBuildInfo.xml to platforms\android\assets\www\VSBuildInfo.xml
1>  ------ Building platform: android
1>  Release
1>  ------ Build configuration options: --release
1>  Executing "before_compile"  hook for all plugins.
1>  ANDROID_HOME=C:\Program Files (x86)\Android\android-sdk
1>  JAVA_HOME=C:\Program Files (x86)\Java\jdk1.7.0_55
1>  Reading build config file: C:\Users\frontend\Desktop\VSCordova\Smartbabypais\build.json
1>  Reading the keystore from: c:\smartbabypais.keystore
1>
1>MSBUILD : cordova-build error : FAILURE: Build failed with an exception.
1>  FAILURE: Build failed with an exception.
1>
1>MSBUILD : cordova-build error : * What went wrong:
1>  * What went wrong:
1>MSBUILD : cordova-build error : A problem occurred configuring root project 'android'.
1>  A problem occurred configuring root project 'android'.
1>MSBUILD : cordova-build error : > Could not resolve all dependencies for configuration ':_debugCompile'.
1>  > Could not resolve all dependencies for configuration ':_debugCompile'.
1>MSBUILD : cordova-build error :  > Could not find any version that matches com.google.android.gms:play-services-gcm:9.0.2+.
1>     > Could not find any version that matches com.google.android.gms:play-services-gcm:9.0.2+.
1>MSBUILD : cordova-build error :  Searched in the following locations:
1>       Searched in the following locations:
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
1>           https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/
1>           https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
1>           file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
1>MSBUILD : cordova-build error :  Required by:
1>       Required by:
1>MSBUILD : cordova-build error :  :android:unspecified
1>           :android:unspecified
1>
1>
1>  BUILD FAILED
1>
1>  Total time: 3.695 secs
1>MSBUILD : cordova-build error : * Try:
1>  * Try:
1>MSBUILD : cordova-build error : Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
1>  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by productank** [comment]
is there a fix for this?

**Comment by romuloinnocencio** [comment]
I don't know, to changed to Android Studio and trying....

**Comment by shibins** [comment]
I was able to resolve the issue by installing "Google Repository” and “Play Services” SDK. Not sure why made this dependency

**Comment by jcesarmobile** [comment]
That's on the install instructions 

> You will need to ensure that you have installed the following items through the Android SDK Manager:
> 
> Android Support Library version 23 or greater
> Local Maven repository for Support Libraries (formerly Android Support Repository) version 20 or greater
> Google Play Services version 27 or greater
> Google Repository version 22 or greater
