### ISSUE TITLE
PhoneGap Build / Android apk size increase (phonegap-plugin-push vs. phonegap-build/PushPlugin)

### ISSUE THREAD

**Issue by davidbarre** [phonegap/phonegap-plugin-push#537]
Hi,

I just migrated from deprecated plugin phonegap-build/PushPlugin to this plugin.
My apk got bigger : It has increased by ~1Mo (1171ko vs. 2104ko)

I looked at the plugin source and I don't understand where this increase comes from.

I presume it may be linked with google-play-services-gcm but on my local android sdk file : the size of play-services-gcm-*.aar is 60ko maximum...

Do you have you any idea ?
Thanks

--
David

**Comment by macdonst** [comment]
@davidbarre It's probably a combination of the Android Support Library and GCM Play Services.

**Comment by gaurav21r** [comment]
@macdonst I believe this is a recent development. In our case, the APK **ballooned** from **6MB** to **23MB** due to this plugin!

Any chance we can reduce this? The situation is worse when we have to add crosswalk on top of this!
