### ISSUE TITLE
Windows 10 Error build with plugin

### ISSUE THREAD

**Issue by Group-TimTeam** [phonegap/phonegap-plugin-push#539]
Hi 

I build on CLI 5.1.1 an app for windows 10 universal app. Work without.

The log it's here

MakeAppx : error : Error info: error C00CE015: App manifest validation error: The app manifest must be valid as per schema: Line 25, Column 195, Reason: The attribute 'ToastCapable' on the element '{http://schemas.microsoft.com/appx/manifest/uap/windows10}VisualElements' is not defined in the DTD/Schema. [...\Bell\platforms\windows\CordovaApp.Windows10.jsproj]
MakeAppx : error : Package creation failed. [...\Bell\platforms\windows\CordovaApp.Windows10.jsproj]
MakeAppx : error : 0x80080204 - The specified package format is not valid: The package manifest is not valid. [...\Bell\platforms\windows\CordovaApp.Windows10.jsproj]
ERROR: Error code 1 for command: ...\MSBuild\14.0\bin\msbuild with args: ...\Bell\platforms\windows\CordovaApp.Windows10.jsproj,/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal,/nologo,/p:Configuration=release,/p:Platform=anycpu
Command finished with error code 2: cmd /s /c "...\Bell\platforms\windows\cordova\build.bat --release --verbose"
ERROR building one of the platforms: Error: cmd: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 2

**Comment by rakatyal** [comment]
Which cordova-windows version are you using? This is caused as Windows 10 removed the toast capable attribute setting and was fixed in the latest release. Upgrading to windows 4.3.0 should remove this issue.

**Comment by Group-TimTeam** [comment]
Thks rakatyal, I use cordova cli 5.1.1 with intelXDK early access and the version of windows is 4.0.0.
I wait the release of intelXDK for upgrading windows version
