### ISSUE TITLE
Android - Notification not always fired

### ISSUE THREAD

**Issue by jeromeXoo** [phonegap/phonegap-plugin-push#542]
Hi,

I have an issue with OnNotification javascript events which are not always working/fired on Android.

Below is how I initialize notifications:

        push = PushNotification.init({
            android: {
                senderID: "xxxxxxxxx", 
                forceShow: true 
            }
        });

On the server side, I send notifications with:

    var message = new gcm.Message({
        collapseKey: 'TopNews',
        priority: 'high',
        contentAvailable: true,
        delayWhileIdle: true,
        data: {
            key1: 'message1'
        },
        notification: {
            title: "Hello Title",
            icon: "ic_launcher",
            body: "My body"        }
    });

In the case the App is in foreground:
when I tap on a notification,  OnNotification javascript event is always fired.

In the case the App is the background:
when I tap on a notification, OnNotification is sometimes fired.

In the case the App coldstarts:
when I tap on a notification, OnNotification is sometimes fired.

When OnNotification is not fired, below is the adb logcat:

I/GCM     (  744): GCM message app.xxxxxx.xxxxxxxxx 0:1453723285525624%9170c9aa9170c9aa
D/dalvikvm( 4719): Late-enabling CheckJNI
I/ActivityManager(  460): Start proc app.xxxxxx.xxxxxxxxx for broadcast app.xxxxxx.xxxxxxxxx/com.googl
e.android.gms.gcm.GcmReceiver: pid=4719 uid=10076 gids={50076, 3003, 1028, 1015}
I/dalvikvm( 4719): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method c
om.google.android.gms.common.zze.zzi
W/dalvikvm( 4719): VFY: unable to resolve virtual method 462: Landroid/content/pm/PackageManager;.getPackageInstaller ()
Landroid/content/pm/PackageInstaller;
D/dalvikvm( 4719): VFY: replacing opcode 0x6e at 0x000b
I/GMPM    ( 4719): App measurement is starting up, version: 8487
I/GMPM    ( 4719): To enable debug logging run: adb shell setprop log.tag.GMPM VERBOSE
E/GMPM    ( 4719): GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id
' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services
gradle plugin.
E/GMPM    ( 4719): Scheduler not set. Not logging error/warn.

I have no idea what is wrong but if any of you had a clue of what I can do to solve my issue, I would be very greatful. Thanks in advance for your answer,

**Comment by fredgalvao** [comment]
Move all of your fields from the `notification` object to the `data` object. GCM will **not** delegate handling of push notifications to listeners (this plugin uses listeners) if a `notification` object is present, and that's why the plugin can't run anything (including your `.on('notification')`). It should look something like this:

```js
var message = new gcm.Message({
    collapseKey: 'TopNews',
    priority: 'high',
    contentAvailable: true,
    delayWhileIdle: true,
    data: {
        key1: 'message1',
        title: "Hello Title",
        icon: "ic_launcher",
        body: "My body"
    }
});
```

**Comment by jeromeXoo** [comment]
Thank a lot!

A clarification for those who encounter the same problem. Remove Property "contentAvailable" when moving all fields to data. Otherwise the android notification appears without the title and defined body. And the javascript event is not triggered. A priori, this property has no more relevance in this context.

Thanks again fredgalvao!
(I was going crazy!)
