### ISSUE TITLE
[iOS] Crash on startup

### ISSUE THREAD

**Issue by Soudny** [phonegap/phonegap-plugin-push#544]
Hi,

I have an issue that happens immediately after adding the plugin to the project - the app crashes without even calling the plugin methods. I am using ionic, and while plugin works perfectly on android, I have tested it on iOS versions 8.4.2 and 9.2.1 and both seem to be malfunctioning.

Is this a known issue and is there something obvious that I am missing?

**Comment by macdonst** [comment]
@Soudny nope, never heard of it before. What logs do you see in Xcode?

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/ISSUES.md

**Comment by Soudny** [comment]
I have fixed the issues and there seemed to be a problem on initialization of phonegap-plugin-push when another, cordova-plugin-app-event plugin has been installed. In case someone comes across this issue, I have fixed it by changing the other plugin, specifically CDVPlugin+APPAppEvent.m file and added another boolean check to prevent it from looping on initialization
```
#pragma mark -
#pragma mark Delegate

bool inited = false;

/**
 * Registers obervers after plugin was inited.
 */
void swizzled_pluginInitialize(id self, SEL _cmd)
{
    if (orig_pluginInitialize != NULL && !inited) {
		inited = true;
        ((void(*)(id, SEL))orig_pluginInitialize)(self, _cmd);
        orig_pluginInitialize = NULL;
    }

    [self addObserver:NSSelectorFromString(@"didReceiveLocalNotification:")
                 name:CDVLocalNotification
               object:NULL];

    [self addObserver:NSSelectorFromString(@"didFinishLaunchingWithOptions:")
                 name:UIApplicationDidFinishLaunchingNotification
               object:NULL];

    [self addObserver:NSSelectorFromString(@"didRegisterUserNotificationSettings:")
                 name:UIApplicationRegisterUserNotificationSettings
               object:NULL];
}
```
