### ISSUE TITLE
[iOS] No notifications received / notification event not fired

### ISSUE THREAD

**Issue by KaiJanis** [phonegap/phonegap-plugin-push#545]
Hi,
I have a big problem and spend so much time too solve it, but I didn't found a solution.
If I send a notification to my iPod with my app developed with phonegap, no notification is received, not even the on('notification') is called. I using iOS 9.2.1 and phonegap 5.4.0

My code:
In the index.html is a script that call the initialzed method of this coding:

pushNotification: undefined,
initialize : function() {
if (device.platform.toUpperCase() === 'IOS') {
this.pushNotification = PushNotification.init({
ios: {
alert: "true",
badge: "true",
sound: "true"
}
});
this.pushNotification.on('registration', this.onRegistrationAPN);
this.pushNotification.on('notification', function(data) {
console.log(data.message);
console.log(data.title);
console.log(data.count);
console.log(data.sound);
console.log(data.image);
console.log(data.additionalData);
alert('notification')
});
this.pushNotification.on('error', this.errorHandler);
}
},

For testing i using the php-script of this site: http://www.raywenderlich.com/32960/apple-push-notification-services-in-ios-6-tutorial-part-1

This plugin says every time, that the registration was sucessful and give me the id of my device. When I sending a notification through the php script to my devicce, the script says sucess, but on my phone nothing happend, also not on the console.

Please help me and thank you for your time.

Regards

**Comment by macdonst** [comment]
@KaiJanis the only think that jumps out at me is you may be sending the notification to the apns service when your app is registered to the apns-sandbox or vice versa.

**Comment by KaiJanis** [comment]
<?php

// Put your device token here (without spaces):
$deviceToken = '';

// Put your private key's passphrase here:
$passphrase = '';

// Put your alert message here:
$message = 'My first push notification!';

////////////////////////////////////////////////////////////////////////////////

$ctx = stream_context_create();
stream_context_set_option($ctx, 'ssl', 'local_cert', 'ck.pem');
stream_context_set_option($ctx, 'ssl', 'passphrase', $passphrase);

// Open a connection to the APNS server
$fp = stream_socket_client(
	'ssl://gateway.sandbox.push.apple.com:2195', $err,
	$errstr, 60, STREAM_CLIENT_CONNECT|STREAM_CLIENT_PERSISTENT, $ctx);

if (!$fp)
	exit("Failed to connect: $err $errstr" . PHP_EOL);

echo 'Connected to APNS' . PHP_EOL;

// Create the payload body
$body['aps'] = array(
	'alert' => $message,
	'sound' => 'default'
	);

// Encode the payload as JSON
$payload = json_encode($body);

// Build the binary notification
$msg = chr(0) . pack('n', 32) . pack('H*', $deviceToken) . pack('n', strlen($payload)) . $payload;

// Send it to the server
$result = fwrite($fp, $msg, strlen($msg));

if (!$result)
	echo 'Message not delivered' . PHP_EOL;
else
	echo 'Message successfully delivered' . PHP_EOL;

// Close the connection to the server
fclose($fp);



So I thinking I sending it to the Sandbox. Do you that mean?

**Comment by trsdln** [comment]
I have the same problem. Also, I tried to send notifications both to sandbox and production server.  

Alternatively I tried to use GCM on iOS by adding `senderId` to `ios` entry. As result I got: 
```
2016-01-26 17:07:17.503 TestApp[636:8b07] Push Plugin register called
2016-01-26 17:07:17.505 TestApp[636:8b07] PushPlugin.register: setting badge to false
2016-01-26 17:07:17.506 TestApp[636:8b07] PushPlugin.register: clear badge is set to 0
2016-01-26 17:07:17.506 TestApp[636:8b07] PushPlugin.register: better button setup
2016-01-26 17:07:17.508 TestApp[636:8b07] GCM Sender ID 24418721324
2016-01-26 17:07:17.508 TestApp[636:8b07] Using GCM Notification
2016-01-26 17:07:17.511 TestApp[636:60b] Push Plugin register success: <274065df 02893f3e dfacd27a aeaacd29 6f368929 33cb09ef 98bc2b9f 031554bb>
2016-01-26 17:07:17.523: GGLInstanceID | Unable to find token in cache Error Domain=com.google.iid Code=-25300 "The operation couldn’t be completed. (com.google.iid error -25300.)"
2016-01-26 17:07:17.988 TestApp[636:60b] Registration to GCM failed with error: The operation couldn’t be completed. (com.google.HTTPStatus error 401.)
2016-01-26 17:07:18.059 TestApp[636:60b] push notification error Error:  - The operation couldn’t be completed. (com.google.HTTPStatus error 401.)
```

**Comment by KaiJanis** [comment]
Hi, I found a solution for my problem.
It was a little strange because it belongs to an not-existent provisioning Profiles. After I fix this problem, the notifications came to me.

Thank you very much.

**Comment by raphaguasta** [comment]
@trsdln Do you resolved the problem? I have the same question here.
