### ISSUE TITLE
Intel XDK error duo to Gradle scripts

### ISSUE THREAD

**Issue by ctvrtlik** [phonegap/phonegap-plugin-push#546]
Hi,
I'm using Intel XDK IDE and with plugin version higher than 1.4.3 is not possible use this plugin due to "Plugin PushPlugin cannot be added. The plugin contains Gradle scripts."
Intel XDK doesn't support Gradle scripts right now (https://software.intel.com/en-us/forums/intel-xdk/topic/605421).

Is there any option (or fork) how to use this plugin in last version and avoid Gradle scripts?

**Comment by macdonst** [comment]
@ctvrtlik nope. In order to avoid conflicts with other plugins that include Google Play Services (or other packages) we've gone full Gradle. Petition Intel to support Gradle.
