### ISSUE TITLE
GCM register on iOS 9.2 failed

### ISSUE THREAD

**Issue by trsdln** [phonegap/phonegap-plugin-push#548]
Unable to get GCM device token iOS. While starting app got logs like:

```
2016-01-26 17:07:17.503 TestApp[636:8b07] Push Plugin register called
2016-01-26 17:07:17.505 TestApp[636:8b07] PushPlugin.register: setting badge to false
2016-01-26 17:07:17.506 TestApp[636:8b07] PushPlugin.register: clear badge is set to 0
2016-01-26 17:07:17.506 TestApp[636:8b07] PushPlugin.register: better button setup
2016-01-26 17:07:17.508 TestApp[636:8b07] GCM Sender ID 24418721324
2016-01-26 17:07:17.508 TestApp[636:8b07] Using GCM Notification
2016-01-26 17:07:17.511 TestApp[636:60b] Push Plugin register success: <274065df 02893f3e dfacd27a aeaacd29 6f368929 33cb09ef 98bc2b9f 031554bb>
2016-01-26 17:07:17.523: GGLInstanceID | Unable to find token in cache Error Domain=com.google.iid Code=-25300 "The operation couldn’t be completed. (com.google.iid error -25300.)"
2016-01-26 17:07:17.988 TestApp[636:60b] Registration to GCM failed with error: The operation couldn’t be completed. (com.google.HTTPStatus error 401.)
2016-01-26 17:07:18.059 TestApp[636:60b] push notification error Error:  - The operation couldn’t be completed. (com.google.HTTPStatus error 401.)
```

This error was produced by this code:

```js
var onDeviceReady = function () {
    var pushNotification = PushNotification.init({
      android: {},
      ios: {
        senderID: google_project_id,
        alert: true,
        badge: true,
        sound: true
      },
      windows: {}
    });
    PushNotification.hasPermission(function (permissionResult) {
      if (permissionResult.isEnabled) {
        pushNotification.on('registration', function (registrationResult) {
          console.log(registrationResult.registrationId);
        });
        pushNotification.on('error', function (error) {
          console.log('push notification error', error);
        });
      }
    });
  };
  document.addEventListener('deviceready', onDeviceReady, false);
```

**Comment by macdonst** [comment]
@trsdln is your app signed with production or sandbox push certificate? By default it will connect to the production environment.

**Comment by trsdln** [comment]
@macdonst It is signed with production push certificate.

**Comment by trsdln** [comment]
@macdonst I figure it out. I didn't enable GCM for iOS in Google Developer Console.

Thanks for help.

**Comment by clembou590** [comment]
could you please tell me where you did that... 
In the google developper console, I only see the "Cloud Messaging for Android" not for IOS....

**Comment by trsdln** [comment]
@clembou590 Yeap, I had the same problem.

1. go to this page: https://developers.google.com/cloud-messaging/ios/client
2. Click on "Get a configuration file" button. Then follow instructions. You should have develop and production APNs certificates in order to enable this API.

**Comment by clembou590** [comment]
Hello.
Thanks for the tip. it worked.
Now I cannot receive the notifications... did you manage to receive some notifications?
I do not know why but it works "fine" on android. (I manage to register and send notification and receive them on the device).

But on Ios, I just got the registration working thanks to you. but no way to receive a notification.
Is it working in "sandbox push mode"?

**Comment by trsdln** [comment]
@clembou590 Yes, it perfectly works on Android and no, it doesn't work on iOS in my case too.

Actually that's very strange. I am able to get device token using this push plugin. Then I register token on server side. After that I send my first notification using GCM API and got success response but there is no notification on device. When I am trying to send second (and for all next notifications too) I got response:

```json
{"error": "NotRegistered"}
```

It looks like push plugin registered and immediately unregistered device from push notification service. Or maybe there is some problem between GCM and APNs. Anyway I wasn't sure whether develop or production server is used, so I tried both `true` and `false` for `gcmSandbox`. None of them worked.

@macdonst Do you have any clues where problem may be?

**Comment by demiurga** [comment]
@trsdln I got same issue with you, did you found the solution?

**Comment by trsdln** [comment]
@demiurga No, I didn't.

**Comment by shaoyunli** [comment]
@trsdln I have enabled the iOS service on GCM by providing both development and production certificates and ensured the AppID of the app installed in the IOS device has both certificates configured. But I still got the same issue that sending the message at the first time with success (response with success but not message actually sent to the device) and failed on all the subsequent sending. 

Have you got any progress on the issue?

**Comment by trsdln** [comment]
Nope. I consider using alternative https://github.com/raix/push plugin

**Comment by shaoyunli** [comment]
@trsdln I might have to do the same thing for different devices. Quite disappointing :-(

**Comment by shaoyunli** [comment]
@trsdln I made some progress but still don't fully understand the difference between gcm sandbox and GCM production. Please see my comments and question on https://github.com/phonegap/phonegap-plugin-push/issues/567

**Comment by shaoyunli** [comment]
@trsdln I think the problem that the device was registered once and unregistered again is because the GCM environment and the certificate (key) we use for development and production environment. During our development, we use iOS development certificate to install the app on iOS device. If it is development certificate, GCM sandbox should be used i.e., 
         ios: {
                    alert: "true",
                    badge: "true",
                    sound: "true",
                    senderID: "******************",
                    gcmSandbox: "true"
                }
. Otherwise, with production certificate, GCM production should be used, i.e.,
         ios: {
                    alert: "true",
                    badge: "true",
                    sound: "true",
                    senderID: "******************"
                }

I haven't tried the app with production certificate, but I think it is the theory. Hope it helps.

**Comment by wmendes** [comment]
Same issue here. I dont understand that behavior. @trsdln @shaoyunli do you have any news on that?

**Comment by macdonst** [comment]
All, you have to understand how GCM for iOS works. First it is kind of a misnomer as GCM does not send push messages directly to devices running iOS.

What happens is on the device side is that it registers with APNS, then that registration ID is sent to GCM which returns a different GCM specific ID. That is the ID you get from the push plugin `registration` event.

When you send a message to GCM using that ID, what it does is look up the APNS registration ID on it's side and forward the message you sent to GCM on to APSN to deliver to your iOS device. 

- If you build your app as development and set gcmSandbox: false it will fail.
- If you build your app as production and set gcmSandbox: true it will fail.
- If you build your app as development and set gcmSandbox: true but haven't uploaded the development certs to Google it will fail.
- If you build your app as production and set gcmSandbox: false but haven't uploaded the production certs to Google it will fail.

The integration between GCM and APNS is a bit finicky. Personally, I feel it is much better to send pushes to Android using GCM and pushes to iOS using APNS which this plugin does support.

**Comment by wmendes** [comment]
I found a solution that works for me. On Xcode -> Capabilities you have to enable push notifications.
My configs was right, that was the issue.

**Comment by shaoyunli** [comment]
@macdonst, it is a well explained summary. It would be very helpful to mention when to set gcmSandbox to true in the official document. If I knew this, it could have saved me two days! Thanks a lot!

**Comment by loyalpocket** [comment]
With Development provisioning profile, set gcmSandbox: "true" will fix the problem.

var push = PushNotification.init({
                    android: {
                        senderID: "**********",
                        icon: "myicon"
                    },
                    ios: {
                        senderID: "**********",
                        alert: "true",
                        badge: "true",
                        sound: "true",
                        **gcmSandbox: "true"**
                    },
                    windows: {}
                });

**Comment by dtruel** [comment]
Usually "not registered" comes from forgetting to change gcmSandbox to "true" or "false".  In xcode under build settings, you also need to make sure you are using the right provisioning profile.  Click the little arrow next to the provisioning profile, and you can set your debug and release provisioning profiles.  You need to make sure to select the development provisioning profile for this specific app that has push notification entitlements.

**Comment by JaimeFerBec** [comment]
Hi. I am getting this error when trying to register my iOS app to use GCM:

> 2016-10-14 15:00:20.503: GGLInstanceID | Unable to find token in cache Error Domain=com.google.iid Code=-25300 "(null)"
> 2016-10-14 15:00:20.896880 Whisper[982:255612] Registration to GCM failed with error: The operation couldn’t be completed. (com.google.HTTPStatus error 401.)

The options object I am sending contains the following:
```
ios: {
    alert: true
    gcmSandbox: true
    senderID: "xxxxxxxxxxxx"
    sound: true
}
```
I am pretty sure that the configuration on the Xcode project is alright, because if I try to register directly to APNS it works just fine. That is, if I try registering for push notifications using this options object:
```
ios: {
    alert: true
    sound: true
}
```
everything works perfectly.

I guess I am missing this part:

> but haven't uploaded the development certs to Google it will fail.

But I do not know what exactly 'updating the development certs to Google' means, or how to do it exactly.
I would thank you if anyone could indicate me how exactly to go about this.

Thank you in advance.

**Comment by Assylkhan** [comment]
Hi JaimeFerBec. I am having the same issue. Did you solve it?

**Comment by dpaksoni** [comment]
Same issue here. Any solution?
