### ISSUE TITLE
Show notification from JS manually and clear notifications

### ISSUE THREAD

**Issue by polyn0m** [phonegap/phonegap-plugin-push#549]
Greetings.

I would like to be able to show notification manually. Explain:

Now the plugin works as follows:
* If the application is running, notification from GCM call '**notification**' event and notification in shade not show.
* If the application is minimized/close notification is displayed as needed.

May arise situation in running application to display notification when obtaining GCM message. Now we can use the [cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications), but use two different plugins for one task is poor.

And how clear notification from shade from app?

Can we make API or options for manually show notification when application running?

**Comment by polyn0m** [comment]
Sorry i don't see **foreground** options.

**Comment by polyn0m** [comment]
When **forceShow** enabled event '**notification**' not throws...

**Comment by macdonst** [comment]
@polyn0m if you want to show the notification you can use  cordova-plugin-local-notifications as you pointed out. I really don't want to add all the functionality to this plugin as it will become bloated. You can also provide your own API to show the notification in JS.

There is no way to clear notifications right now but #346 is a enhancement request.
