### ISSUE TITLE
Warnings on build

### ISSUE THREAD

**Issue by rossholdway** [phonegap/phonegap-plugin-push#550]
When I build my project in xCode 7.2 I receive a lot of warnings along the lines of

`warning: object file (.../Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(Descriptor.pb.o)) was built for newer iOS version (8.3) than being linked (8.0)`

Can the plugin be built with a lower iOS version specified to avoid these warnings?

I also get a range of depreciation warnings too

`UIRemoteNotificationType is depreciated`
`UIRemoteNotificationTypeNone is depreciated`
`UIRemoteNotificationTypeBadge is depreciated`
etc

Should I be worried about these? Will these be updated with the new methods at some point?

Thanks,
Ross

**Comment by macdonst** [comment]
@rossholdway there isn't much I can do about the warnings from the GCM code until Google sends out and update of their library.

Regarding the deprecation warnings, you can ignore them. They are used for iOS7 support which will be going away in a later release.

**Comment by rossholdway** [comment]
@macdonst Thanks for the update!

**Comment by rossholdway** [comment]
@macdonst Is this the update we are waiting for? Sounds like the GCM warnings are fixed in the latest release. See https://github.com/google/gcm/issues/121
