### ISSUE TITLE
Handling notifications in the background (without loading the app UI)

### ISSUE THREAD

**Issue by asunar** [phonegap/phonegap-plugin-push#551]
We're using phonegap push plugin to send interactive push notifications (with buttons) (Android 6.0.1, ios 8). Documentation suggests using "content-available" in the payload for background notifications.

However, even with content-available value set; when user clicks on the push notification button, the plugin loads the application and shows the login page. Below is a sample push notification payload.

`{
"data" : {
    "title":"Test title", 
    "message":"Test message", 
    "content-available": "1",
    "actions": [{ icon: "", title: "APPROVE", callback: "approve"},
         { icon: "",title: "DENY", callback: "deny"}
        ]
    }
}`

Callback functions (approve, deny in the above sample) are fired and push action buttons are handled appropriately.

My question is:

How can the app handle push notification action buttons in the background WITHOUT loading the app and showing the login screen?

Desired workflow:

1.     The app may or may not be running in the background, the phone may or may not be locked (requiring passcode if locked)
2.     User receives a push notification with approve/deny buttons.
3.     User swipes (down in Android, left in ios) and reveals the buttons.
4.     User clicks on a button
5.     User is NOT prompted for a passcode
6.     App UI is NOT shown
7.     Appropriate callback function is executed (working)

**Comment by macdonst** [comment]
@asunar not a useful way of reporting an issue.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/ISSUES.md

**Comment by asunar** [comment]
How can I improve the issue? i realized that I did not include the platform and version number (Android 6.0.1, ios 8). Is there any other information that I can provide? Do you prefer that the details of the issue are replicated in github in addition to stackoverflow?

Thanks.

**Comment by fredgalvao** [comment]
There are definitely a way to do that, but not with this plugin. Action buttons will always launch your app (or try) and delegate the "handling of things" to your code.
If you wanna do that, you'd have to use another plugin (I'm not aware of any that does it) or implement it yourself using native code.

**Comment by macdonst** [comment]
@asunar yes, I would prefer the details of the issue to put in the github issue. It makes it easier for people to search the repo for solutions. Please update your original issue with details.

**Comment by asunar** [comment]
Updated issue per @macdonst.

**Comment by macdonst** [comment]
@asunar yeah, currently clicking on an action button brings the app into the foreground. I'm going to look into it some more for the 1.6.x release but if you figure it out in the meantime, PR's are welcome.
