### ISSUE TITLE
logic behind notId android payload

### ISSUE THREAD

**Issue by candidodmv** [phonegap/phonegap-plugin-push#553]
Hi!

The notId parameter can be any number or need follow some logic? for exemple, if today was sent a notId number 1234, 1235, 1236 and tomorrow these notification still keep in the shad and sent news notifications with the same numbers id what will happen? will be replaced or will be stacked with the others?

Thanks!

**Comment by fredgalvao** [comment]
According to the android source, `notId` is expected to be an `int` ([source](http://developer.android.com/reference/android/app/NotificationManager.html#notify(java.lang.String, int, android.app.Notification))).

For the last question, if you have a notification on the shade with `notId: 123` and you send another notification with `notId: 123`, the old one will be replaced with the new one, yes. Source is the same from above.

> If you call one of the notify methods with a (tag, id) pair that is currently active and a new set of notification parameters, it will be updated. For example, if you pass a new status bar icon, the old icon in the status bar will be replaced with the new one.

**Comment by candidodmv** [comment]
So, for me ensure that always have a stack notifications, that never will replace any previous notification, I need have a incremental counter?

**Comment by macdonst** [comment]
@candidodmv correct

**Comment by candidodmv** [comment]
@fredgalvao and @macdonst  and  Thank you so much!

**Comment by pallaviMN** [comment]
@candidodmv , Have you implemented "Inbox Stacking", If yes, please give us what code need to be changed at the client side. Because for me, "Inbox stacking" always gives the last notification only.
