### ISSUE TITLE
very stange issue...

### ISSUE THREAD

**Issue by clembou590** [phonegap/phonegap-plugin-push#554]
Hello.
I am using an android real device (4.4.4).
It is connected in 3g: I checked using whatsapp , youtube, ping, speedtest...
the connection is good.

I launch the app the function 
--> pushService.on('registration',registrationCallback) is never called!

I kill the app.

turn on the wifi.
it works...

That is very stange cause I did it 20 times and it always work on wifi, never work on 3g even though the connection is good (as I said I really checked with 5 apps to make sure the internet connection was OK).

Any idea what might be the issue?

SAME THING WITH THE PUSH NOTIFICATIONS:
I RECEIVE THEM IN WIFI, never receive them in 3g...

how is that possible?

**Comment by macdonst** [comment]
@clembou590 what do you see in `adb logcat | grep PushPlugin` and/or `adb logcat | grep GCM`. Probably give us better clues.

**Comment by zanemcca** [comment]
I am seeing the exact same thing.

I got no output for `adb logcat | grep GCM`.
 
Here is the output of `adb logcat | grep PushPlugin`:
```
V/PushPlugin( 7843): execute: action=init
V/PushPlugin( 7843): execute: data=[{"android":{"senderID":"xxxxxxxxxxxxxx","iconColor":"#F0F0F0","icon":"notif","vibrate":true,"sound":true,"forceShow":true}}]
V/PushPlugin( 7843): execute: jo={"senderID":"xxxxxxxxxxxxxx","iconColor":"##F0F0F0","icon":"notif","vibrate":true,"sound":true,"forceShow":true}
V/PushPlugin( 7843): execute: senderID=xxxxxxxxxxxxxx
E/PushPlugin( 7843): execute: Got JSON Exception TIMEOUT
V/PushPlugin( 7843): execute: action=init
V/PushPlugin( 7843): execute: data=[{"android":{"senderID":"xxxxxxxxxxxxxx","iconColor":"##F0F0F0","icon":"notif","vibrate":true,"sound":true,"forceShow":true}}]
V/PushPlugin( 7843): execute: jo={"senderID":"xxxxxxxxxxxxxx","iconColor":"#F0F0F0","icon":"notif","vibrate":true,"sound":true,"forceShow":true}
V/PushPlugin( 7843): execute: senderID=xxxxxxxxxxxxxx
E/PushPlugin( 7843): execute: Got JSON Exception TIMEOUT
V/PushPlugin(10164): execute: action=init
V/PushPlugin(10164): execute: data=[{"android":{"senderID":"xxxxxxxxxxxxxx","vibrate":true,"sound":true,"forceShow":true}}]
V/PushPlugin(10164): execute: jo={"senderID":"xxxxxxxxxxxxxx","vibrate":true,"sound":true,"forceShow":true}
V/PushPlugin(10164): execute: senderID=xxxxxxxxxxxxxx
E/PushPlugin(10164): execute: Got JSON Exception TIMEOUT
D/PushPlugin(10164): no icon option
D/PushPlugin(10164): no iconColor option
V/PushPlugin(10662): execute: action=init
V/PushPlugin(10662): execute: data=[{"android":{"senderID":"xxxxxxxxxxxxxx","vibrate":true,"sound":true,"forceShow":true}}]
V/PushPlugin(10662): execute: jo={"senderID":"xxxxxxxxxxxxxx","vibrate":true,"sound":true,"forceShow":true}
V/PushPlugin(10662): execute: senderID=xxxxxxxxxxxxxx
E/PushPlugin(10662): execute: Got JSON Exception TIMEOUT
D/PushPlugin(10662): no icon option
D/PushPlugin(10662): no iconColor option
V/PushPlugin(13772): execute: action=init
V/PushPlugin(13772): execute: data=[{"android":{"senderID":"xxxxxxxxxxxxxx","vibrate":true,"sound":true,"forceShow":true}}]
V/PushPlugin(13772): execute: jo={"senderID":"xxxxxxxxxxxxxx","vibrate":true,"sound":true,"forceShow":true}
V/PushPlugin(13772): execute: senderID=xxxxxxxxxxxxxx
E/PushPlugin(13772): execute: Got JSON Exception TIMEOUT
D/PushPlugin(13772): no icon option
D/PushPlugin(13772): no iconColor option
V/PushPlugin(20705): execute: action=hasPermission
V/PushPlugin(23251): execute: action=hasPermission
```

**Comment by zanemcca** [comment]
`hasPermission` does not call the callback either.
I assume that means it does not have permission?

**Comment by zanemcca** [comment]
This might be related to #366

**Comment by JohnHanks** [comment]
hasPermission is not working for me as well. :disappointed:

**Comment by clembou590** [comment]
SORRY for the delay... I still have no clue on how to get it working
here are the traces of adb pushplugin

with WIFI

V/PushPlugin(25844): execute: action=init
V/PushPlugin(25844): execute: data=[{"android":{"senderID":"XXXXXXXXXXX"},"ios":{"senderID":"XXXXXXXXXXX","badge":"true","gcmSandbox":true,"sound":"true","alert":"true"},"windows":{}}]
V/PushPlugin(25844): execute: jo={"senderID":"XXXXXXXXXXX"}
V/PushPlugin(25844): execute: senderID=XXXXXXXXXXX
V/PushPlugin(25844): execute: action=hasPermission
V/PushPlugin(25844): onRegistered: {"registrationId":"dMZ1Knrjt1w:APA91bH3Qftf-obIUknjRQoXUfroVfcbhPze3oqkKDSS4BISi1CQJgbi-ioJ5j6fK_4jR2kEkaunPRA-A6UdbevwHB_0fvmTtmZLcq9St1P4OSpcPgUMIcaW3VO9UTw8hsQcvzU-WhZ3"}
D/PushPlugin(25844): no icon option
D/PushPlugin(25844): no iconColor option


WITH 3G
V/PushPlugin(30308): execute: action=init
V/PushPlugin(30308): execute: data=[{"android":{"senderID":"XXXXXXXXXXX"},"ios":{"senderID":"XXXXXXXXXXX","badge":"true","gcmSandbox":true,"sound":"true","alert":"true"},"windows":{}}]
V/PushPlugin(30308): execute: jo={"senderID":"XXXXXXXXXXX"}
V/PushPlugin(30308): execute: senderID=XXXXXXXXXXX
V/PushPlugin(30308): execute: action=hasPermission
E/PushPlugin(30308): execute: Got JSON Exception SERVICE_NOT_AVAILABLE
D/PushPlugin(30308): no icon option
D/PushPlugin(30308): no iconColor option





for the GCM traces:
3g
➜  ~  adb logcat | grep GCM
W/GCM     (21627): ACTIVE NETWORK NOT CONNECTED
W/GCM     (21627): ACTIVE NETWORK NOT CONNECTED
D/GCM     (21627): Removing messenger 0:com.tindrive
D/GCM     (21627): GcmService start Intent { act=com.google.android.gms.gcm.PACKAGE_FULLY_REMOVED cmp=com.google.android.gms/.gcm.GcmService (has extras) } com.google.android.gms.gcm.PACKAGE_FULLY_REMOVED
D/GCM     (21627): GcmService start Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms cmp=com.google.android.gms/.gcm.GcmService (has extras) } com.google.android.c2dm.intent.REGISTER
W/GCM     (21627): Missmatched messenger


WIFI
D/GCM     (21627): GcmService start Intent { act=com.google.android.gms.gcm.PACKAGE_FULLY_REMOVED cmp=com.google.android.gms/.gcm.GcmService (has extras) } com.google.android.gms.gcm.PACKAGE_FULLY_REMOVED
D/GCM     (21627): GcmService start Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms cmp=com.google.android.gms/.gcm.GcmService (has extras) } com.google.android.c2dm.intent.REGISTER
W/GCM     (21627): Missmatched messenger

**Comment by clembou590** [comment]
EVEN MORE STRANGE:
IF I CONNECT IN WIFI TO MY GIRLFRIEND phone wich I use as a "wifi spot" (and of course I check that I have internet access...)
I still do not have the push registration working:
I still have the log:
PushPlugin(30308): execute: Got JSON Exception SERVICE_NOT_AVAILABLE


THAT S CRAZY!
what is the problem?

**Comment by clembo590** [comment]
someone has any idea?

**Comment by zanemcca** [comment]
My problem seemed to go away after I had a google account logged into Android.

**Comment by clembo590** [comment]
MINE DID NOT!
I have the problem when "not in wifi" with moto G on android 4.4.4.

The problem does not occur on moto G with android 5.X 

(I tested on my girlfriends phone and there is no problem.... )

**Comment by MichaelJCole** [comment]
This give more info on SERVICE_NOT_AVAILABLE:
https://stackoverflow.com/questions/17188982/how-to-fix-google-cloud-messaging-registration-error-service-not-available

**Comment by macdonst** [comment]
@zanemcca pretty sure it is your version of Google Play Services. 

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#got-json-exception-timeout

**Comment by clembou590** [comment]
I reseted my android phone and did not get the problem after reset.
--> strange issue

**Comment by lunarByrd** [comment]
Is your android device connected to the internet?? scratched my head for 1 full day with this issue.. only to find, I had forgotten to reconnect to my wifi after i reset my phone. Once my phone was connected to the internet, everything was fine.
