### ISSUE TITLE
Custom Notification Sounds using PhoneGap Build

### ISSUE THREAD

**Issue by neffnet** [phonegap/phonegap-plugin-push#555]
Is there any way to use a sound file for background notification from /www folder, instead of /res/raw? Alternatively, do you know a way to instruct PhoneGap Build to place files in res/raw?

Payload being sent to apns includes {sound:"beep.caf"}, and gcm payload includes {soundname:"beep"}. My problem seems to be that the sound files are not in the app's res/raw directory, they are in /www/ (i.e. /assets/www/beep.caf and /assets/www/beep.wav). Unless I'm missing something, we can't tell PhoneGap Build to put the sounds in /res/raw.

Currently, our background notifications trigger vibration-only on android and the default sound/vibration for ios.

We have a custom sound notification we trigger on foreground notifications, using the PhoneGap media plugin. How can we use the same sound for background notifications when the app is built with PhoneGap Build?

Notifications with default system sounds are working great, thanks for your efforts on this.

**Comment by macdonst** [comment]
@neffnet you want to follow what @wildabeast mentions over here:

https://github.com/phonegap/build/issues/401#issuecomment-156277041

I really need to document that and also, please go vote up this issue:

https://github.com/phonegap/build/issues/472

as it really should get added to Cordova proper.

**Comment by neffnet** [comment]
Thank you! My Google skills were not up to the task, but this is exactly what I was looking for.
Referenced solution worked right away for Android: I created a /locales/android/raw/beep.wav, and in the APK generated by Phonegap Build I find a /res/raw/beep.wav which plays for a background notification.

Unfortunately the solution didn't help for ios. Still uncertain how to package sound files in pgBuild for ios background notifications. I'll update here if I figure it out.

**Comment by macdonst** [comment]
@neffnet Yeah, as far as I know there is no way to do it for iOS. 

Please go vote up this discussion thread: https://github.com/cordova/cordova-discuss/issues/6

**Comment by skyprimer** [comment]
Does adding custom sound for Phonegap Build still not working?

**Comment by macdonst** [comment]
@skyprimer you can now use the `resource-file` tag to copy custom files into your app.

http://cordova.apache.org/docs/en/latest/config_ref/index.html#resource-file
