### ISSUE TITLE
"InvalidRegistration" when push to gcm

### ISSUE THREAD

**Issue by WilsonFpz** [phonegap/phonegap-plugin-push#558]
Hi
I got the error "InvalidRegistration" when push to android gcm.
I had check the server api key and the device token provide by  following code
```
push.on('registration', function (data) {
        console.log(data.registrationId);
     
      });
```
please help on it. thanks.

**Comment by charpin** [comment]
I think your

**Comment by charpin** [comment]
I think your API key is not valid. Did you put this following code in your app ?

```
var push = PushNotification.init({
    android: {
        senderID: "your API key"
    }
});
```

This documentation can help you a lot about the differents HTTP code response from Android GCM server : [https://developers.google.com/cloud-messaging/http-server-ref#error-codes](url)

**Comment by WilsonFpz** [comment]
Oh! got the problem. The device token is wrong (had been cut)
Thanks a lot!
