### ISSUE TITLE
it seem no wp8 version for now

### ISSUE THREAD

**Issue by bau720123** [phonegap/phonegap-plugin-push#56]
it seem no wp8 version for now
according to this
https://github.com/phonegap/phonegap-plugin-push/tree/master/src
no wp8 folder too

but the previous pushplugin have this one
https://github.com/phonegap-build/PushPlugin/tree/master/src

so...just want to know
why this new version abandon this ?

**Comment by rakatyal** [comment]
@bau720123: This plugin supports windows phone 8.1 and win8.1 universal apps. May I ask why are you not considering upgrading to wp8.1?

**Comment by bau720123** [comment]
hi @rakatyal 
thanks for your reply
you misunderstood what I mean
I am using windows phone (Nokia Lumia 520，it's initial system is windows phone 8.0 indeed，but it update to 8.1 from microsoft for long time ago)

when I try this plugin in my windows phone 8.1，it really have no any affect
see the folder
https://github.com/phonegap/phonegap-plugin-push/tree/master/src/windows
I am wonder why it only have .js file，if I am not wrong，it should have a .cs file or other source code file
(or maybe only .js file can have a push notification in wp8.1 ?)

**Comment by rakatyal** [comment]
@bau720123: Thanks for the detailed issue. You are right. The .cs file was required only for the wp8 platform and win8.1 universal (windows 8.1+ and windows phone 8.1+) works uniformly on javascript.
You need to add 'windows' platform instead of 'wp8' platform for your project.

**Comment by bau720123** [comment]
hi @rakatyal 
in PGB (build.phonegap.com)
all build is in the cloud
and I am just use this plugin (I am not a engineer in windows)
so...just wonder why the new push plugin have no wp8.1 version

because in the previous plugin，it really have...although it still have some issues but it really work
https://github.com/phonegap-build/PushPlugin/tree/master/src/wp8

**Comment by bau720123** [comment]
hi @rakatyal 
any idea about the PGB ??

**Comment by eduboxgithub** [comment]
Can I use this plugin with platform wp8?

Can I make a "cordova platform add wp8" and espect this to work?

**Comment by rakatyal** [comment]
No wp8 is not supported with this plugin. It supports win8.1+ universal platform which means windows phone 8.1+ and windows 8.1+

**Comment by rakatyal** [comment]
@bau720123 : I am trying to test it on PGB. I will update as soon as I know something.

**Comment by bau720123** [comment]
Thanks @rakatyal

**Comment by rakatyal** [comment]
@bau720123 : PGB supports only wp8 as of now. So you cannot build a windows universal app with it.

**Comment by bau720123** [comment]
Hi @rakatyal
Of course I know that PGB supports android, ios, wp8
I am just simply want to ask if this plugin have wp8 version or not

Well...maybe I will ask PGB team if have a wp8.1 build in the future

Thanks

**Comment by rakatyal** [comment]
@bau720123: Sorry for the confusion. No this plugin won't have wp8 support.
