### ISSUE TITLE
Getting data.count

### ISSUE THREAD

**Issue by tanojaja** [phonegap/phonegap-plugin-push#561]
How can I set the indicator in app icon? I'm trying to get the badge indicator when notifications are received. But data.count do not exist in each case I tried.
Also I want to know if when app is not running what's happends with this indicator if I cant set it manually.

**Comment by macdonst** [comment]
@tanojaja on iOS the badge is set for you. You can also use https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushsetapplicationiconbadgenumbersuccesshandler-errorhandler-count---ios-only to set it manually.
