### ISSUE TITLE
custom notification sound when the app is not active

### ISSUE THREAD

**Issue by pliablepixels** [phonegap/phonegap-plugin-push#562]
Hello, I am a little confused on the workflow and would appreciate some insight:

I'd like for Android to play a custom notification sound when the app is not running (like say, what whatsapp does). So far, I've directly hacked ``GCMIntentService.java`` to force load my sound file and it works fine.

However, I am trying to do it the 'right' way (aka via the plugin options). As I understand it, during ``init()`` I set ``sound:'true'`` - what I don't understand is where do I specify the sound file name? Looking at ``push.on('notification')`` it looks like my app server can specify the sound name to play, but this callback does not get called when the app is not running (exited). So how do I set up a custom sound directly using the plugin options?

thanks

**Comment by macdonst** [comment]
@pliablepixels You need to set the soundname you want played for each push if you don't want the default sound played. So the following push to GCM.

```
{
  "data": {
    "title": "Sound Test",
    "message": "Loaded res/raw",
    "soundname": "test"
  }
}
```

would result in a sound file called "test" being played. The file should be in your `res/raw` folder of your Android project. You'll have to omit the file extension so "test.mp3" just becomes "test".

Try it out and close this issue if the above resolves it for you.

https://github.com/phonegap/phonegap-plugin-push/blob/v1.6.x/docs/PAYLOAD.md#sound

**Comment by pliablepixels** [comment]
Hello @macdonst thank you! I am using air notifier which does not seem to pass soundname across which is probably why I was facing problems. I'll modify air notifier and then check - I'll close this for now. I'll reopen this if needed once I fix air notifier.

**Comment by pliablepixels** [comment]
confirmed - this is working. thanks.
