### ISSUE TITLE
Android Icon only displays transparent images and does not show any colour

### ISSUE THREAD

**Issue by jcus0006** [phonegap/phonegap-plugin-push#564]
First of all, with iOS, simply including the icon in the res/icons/ios folder and adding "icon": "name" in the init did the job. It works fine and no problem.

For Android: I located the drawables folders: platforms/android/res, and added the icon I want to show with the push notification in every folder. Then I added the code in the init line, but initially got nothing. The only way it worked was with a transparent icon. However, even with the transparent icon, it does not work as supposed to, as the icon turns all white and has a gray background.

What I want is a white background and the icon with its original colour, or being able to show the icon in its original form.

Another strange point is the fact that the nameoftheicon.png does not work with Android, but works with iOS. In the Android case, nameoftheicon is what works.

What do you suggest? Not sure if this is a known issue so don't hesitate to correct me if it is. I'd appreciate however if you would direct me to possible solutions.

This is the code of the init:

pushNotification = PushNotification.init({
    "android": { "senderID": GCM_SENDER_ID, "icon": "logo"},
    "ios": { "alert": "true", "badge": "false", "sound": "false", "icon": "logo.png" }, "windows": {}
});

**Comment by macdonst** [comment]
@jcus0006 correct, please read:

https://github.com/phonegap/phonegap-plugin-push/blob/v1.6.x/docs/PAYLOAD.md#images

**Comment by jcus0006** [comment]
So the only way to show a coloured image with a push is to send it from the backend? No way to do it client side along with the registration? Not sure if Im understanding the concept of the large image correctly.

**Comment by pallaviMN** [comment]
Hi Team,

@macdonst  Even i have came across this issue, when i used custom icon in the code & add the same icon in the drawables folder. But still, the icon will not appear. Just it shows white rectangular with grey background. But if the same icon is used with transparent BG then it started showing atleast icon instead of white Background.

**Comment by pallaviMN** [comment]
Can you please help us in this @macdonst

**Comment by jcus0006** [comment]
It seems like it is supposed to work like that, for some strange reason @pallaviMN. It seems like the icon is meant to be transparent in its nature. I cannot understand how to use the concept of large image however, which seems to be what we need to show coloured non-transparent images in the notifcation bar. I am not sending notifications from the GCM like the JSON in the link @macdonst  suggested; but rather from Azure backend (testing) or C# using Notification hubs package.

**Comment by macdonst** [comment]
@jcus0006 the new Android UI guidelines as of Android 5 is for the icon shown in a push to only have white and transparent pixels. There is a link to the information on Google in the doc link I sent you. 

If you absolutely want to use a colored icon then you'd have to build with an earlier version of Android. I really don't recommend this. You should move forward, not back.

The large icon is a way of personalizing each push.

**Comment by macdonst** [comment]
@pallaviMN what you describe is the way Android push notifications are supposed to work.

**Comment by jcus0006** [comment]
Fair enough @macdonst . But how is it 'moving forward' to remove colour from an icon? Personally, and I accept the fact that I am inexperienced in advance, I see it as a step backward rather.

Can you explain how to go about modifying the json sent from GCM for each push?

**Comment by macdonst** [comment]
@jcus0006 by moving forward I mean following the Android style guide. If you don't your app will stick out for the wrong reasons.

How are you sending the data to GCM as you can just follow what is in the docs?

**Comment by jcus0006** [comment]
I am registering with the typical code: creating a mobileServiceClient and a pushPlugin init instance. Then Im doing the register: mobileServiceClient.push.gcm.registerTemplate(...)

Then pushing the notification using the notification hubs package in C#. 

I'm thinking the JSON that is sent with the registerTemplate has to include the "image" as described in the docs?
