### ISSUE TITLE
Inbox Stacking in iPhone

### ISSUE THREAD

**Issue by pallaviMN** [phonegap/phonegap-plugin-push#566]
Hi Team,

Currently as mentioned in the plugin, are you supporting only Inbox stacking in android? or is it available by default in iOS. For me even in android, it doesnt seem to work.

**Comment by macdonst** [comment]
@pallaviMN no such thing as inbox stacking on iOS.

**Comment by pallaviMN** [comment]
@macdonst then in case of multiple notifications sent, whether the last one will be overridden by the new notification?

**Comment by macdonst** [comment]
@pallaviMN nope

**Comment by pallaviMN** [comment]
both notification will be visible to the user when the app is in Background??

**Comment by pallaviMN** [comment]
@macdonst  sorry, if the app is in Background, if that time 2 notifications are received, on tapping that status bar notification, whether both will be available to user when app comes to foreground?

**Comment by pallaviMN** [comment]
@macdonst  can you please suggest us?
