### ISSUE TITLE
How do I reference additionalData

### ISSUE THREAD

**Issue by leydar** [phonegap/phonegap-plugin-push#571]
I'm sending a message as such: 
`    var payload = {
        "data": {
            "title": "Controller",
            "message": "resub: " + new Date(),
            "CONTENT_AVAILABLE": true,
            "additionalData": { "topic": "testing" }
        }
    };`

and trying to access it with:
`alert(data.additionalData.topic);`

I'm receiving 'undefined' for the topic but 'title' and 'message' are readily accessible.

**Comment by macdonst** [comment]
@leydar they way you are sending it the value would end up as:

`data.additionalData.additionalData.topic`

You don't need to put anything in an additionalData object. Anything that isn't title, message, sound or count ends up in additionalData. So if you use the payload:

```
var payload = { "data": { "title": "Controller", "message": "resub: " + new Date(), "CONTENT_AVAILABLE": true, "topic": "testing" } };
```

try that, close the issue when it fixes your problem :smile:

**Comment by leydar** [comment]
Ah I see. That's accurate information. Thank you.
