### ISSUE TITLE
${applicationId} is not replaced when I builded an app with the command line

### ISSUE THREAD

**Issue by deliriousrhino** [phonegap/phonegap-plugin-push#572]
After building my AndroidManifest still contains the ${applicationId} string 
```
  <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="${applicationId}" />
            </intent-filter>
```

```
 <permission android:name="${applicationId}.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />
```

I am building using the cordova command line 

cordova version 5.4.1
phonegap-plugin-push version 1.5.3

**Comment by fredgalvao** [comment]
Does that generates any error? AFAIK that variable reference will be replaced in compile time or maybe runtime, and I'm fairly sure that's how it's been for a long time on my application's manifest (I can't check atm) without any errors.

**Comment by macdonst** [comment]
@deliriousrhino not actually a problem.

**Comment by deliriousrhino** [comment]
@macdonst great thanks did not know android replaced it at runtime

**Comment by Arriegi** [comment]
@deliriousrhino Did it work well? I'm with the same issue and I'm not receiving notifications, I'd like to discard this.

**Comment by deliriousrhino** [comment]
Yes it work fine
