### ISSUE TITLE
[Android] app not brought to foreground when launchMode = singleInstance

### ISSUE THREAD

**Issue by TonivdW** [phonegap/phonegap-plugin-push#573]
In my app I also use cordova-universal-links-plugin. In order to have this plugin behave the way I want I needed to set launchMode to singleInstance in the config.xml. Please see https://github.com/nordnet/cordova-universal-links-plugin/issues/37
If I make this setting the result is that the app is no longer foregrounded on receipt of a push notification. I have verified that the notification is received, and the app processes it correctly and even navigates to the proper page, but all this is done in the background.
Is it possible to change some setting or add some lines of code in the push plugin to force the app to be foregrounded in this scenario?

**Comment by TonivdW** [comment]
I tried to workaround this by using https://github.com/caioladislau/cordova-toforeground to bring the app to the foreground when the push message is handled by the app, but apparently the push message is delivered to and handled by the app upon **receipt**, not at the moment the user **clicks the notification**. This effectively puts the app in foreground upon receipt of the notification. This is not the behavior I was looking for.
Maybe the code from this plugin could be used in plugin-push at the moment the user clicks the notification?

**Comment by TonivdW** [comment]
After I switched to `lauchMode=singleTask` all my issues seem to have vanished. I don't think any changes to plugin-push are needed.

**Comment by viking2917** [comment]
I had exactly this issue, and singleTask solved it.
