### ISSUE TITLE
App Crashes on Android when calling PushNotification.init()

### ISSUE THREAD

**Issue by codecrab-studios** [phonegap/phonegap-plugin-push#574]
Hi Guys

I am facing a weird error. My Applications crashes once the app is opened and PushNotification.init() is called. it happens only in Android whereas in iOS its working without any issues

Stuff i am using Ionic Framework, Parse Push Notifications.

Plugins List:
![screen shot 2016-02-04 at 6 52 20 pm](https://cloud.githubusercontent.com/assets/16228380/12816114/8d87d6f0-cb70-11e5-9f5a-da8da14acf13.png)

Note:  It happens only when app is installed for the first time, and later on its fine, it just happens during the First Install. After that Push on notification function doesnot work, whenver any push is recieved that function doesnot call up!!

**Comment by macdonst** [comment]
@codecrab-studios reproduce while running `adb logcat` it should catch the exception that is crashing your app and I can suggest from there.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/ISSUES.md

**Comment by codecrab-studios** [comment]
i did the adb logcat, but it doesnot stop, is there something i can have the logs only for the app ?

**Comment by codecrab-studios** [comment]
![screen shot 2016-02-04 at 7 30 43 pm](https://cloud.githubusercontent.com/assets/16228380/12817037/d65f6e7e-cb75-11e5-842b-7a2ce0eff7ee.png)

This is the output from ADB

**Comment by codecrab-studios** [comment]
@macdonst  also its just happening when i add this plugin, removing this app, everything works fine.

What could be the issue?

**Comment by macdonst** [comment]
@codecrab-studios run:

`adb logcat > capture_crash.txt`

and you should get all the logs into a file that can be searched. Do not post the entire file here use a gist service like the one I list in https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/ISSUES.md

**Comment by codecrab-studios** [comment]
@macdonst  I did run the adb logcat > capture_crash.txt 
it did nothing... :(

**Comment by macdonst** [comment]
@codecrab-studios lies, all lies.

Seriously, if you connect your android device to your computer and run `adb logcat` it will spit out all the devices logs to the console. Running `adb logcat > capture_crash.txt` will save all those lines to a text file. 

Then you reproduce the issue with the app crashing and click Ctrl-C to cancel the log re-direct. You are left with a file that should show why the app is crashing.

![helpme](https://cloud.githubusercontent.com/assets/353180/12818924/cff90756-cb26-11e5-8f98-88800b11f65d.jpg)

**Comment by codecrab-studios** [comment]
Sorry, it did created a file, but i think it might got lost
Here it is: 

https://gist.github.com/codecrab-studios/3253b61d288f12b8d188

**Comment by macdonst** [comment]
@codecrab-studios the problem is with the Parse plugin you added:

```
E/AndroidRuntime(21888): FATAL EXCEPTION: main
E/AndroidRuntime(21888): java.lang.RuntimeException: Unable to instantiate receiver com.parse.GcmBroadcastReceiver: java.lang.ClassNotFoundException: com.parse.GcmBroadcastReceiver
E/AndroidRuntime(21888): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2223)
E/AndroidRuntime(21888): 	at android.app.ActivityThread.access$1500(ActivityThread.java:134)
E/AndroidRuntime(21888): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1297)
E/AndroidRuntime(21888): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(21888): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(21888): 	at android.app.ActivityThread.main(ActivityThread.java:4624)
E/AndroidRuntime(21888): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(21888): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(21888): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
E/AndroidRuntime(21888): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
E/AndroidRuntime(21888): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(21888): Caused by: java.lang.ClassNotFoundException: com.parse.GcmBroadcastReceiver
E/AndroidRuntime(21888): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
E/AndroidRuntime(21888): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
E/AndroidRuntime(21888): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
E/AndroidRuntime(21888): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2218)
E/AndroidRuntime(21888): 	... 10 more
```

**Comment by codecrab-studios** [comment]
I am using this Plugin : https://github.com/avivais/phonegap-parse-plugin
Do you know some other plugin which is better and should resolve my issue. please!

**Comment by macdonst** [comment]
@codecrab-studios it looks like the jar that the plugin is supposed to include is not being included. It's more appropriate that you open an issue on their plugin. Also, you know that Parse is shutting down right?
