### ISSUE TITLE
Payload for iOS?

### ISSUE THREAD

**Issue by tyrtok** [phonegap/phonegap-plugin-push#577]
Hi,

I got my iOS push notification to work. However, I would like to have more custom key/value for the push notification so that I can have more action performed at the client side. Can I chjeck if there is anyway to input and retrieve custom key/value pairs?

Sample: 
{
 "to" : "phone-gcm",
    "content_available": true,
    "notification" : {
        "title" : "Testing Title",
        "body" : "test body!",
        "type": "test type",
        "topic": "test topic"
    }
}

**Comment by ddddm** [comment]
Yes, you can get payload from the `additionalData` of the push object:
![image](https://cloud.githubusercontent.com/assets/3530727/12839033/769a1940-cbf6-11e5-9fb7-bad8d94cb3e5.png)

Everything you put there on backend will appear in  `additionalData`.

**Comment by macdonst** [comment]
@tyrtok closing this as the question appears to be answered.
