### ISSUE TITLE
Unable to get Picture Message on android

### ISSUE THREAD

**Issue by AtulaGuleria** [phonegap/phonegap-plugin-push#580]
I am trying to to show a picture in the notification bar. My code is 

"pluginConfig": {  
        "android": {
               "senderID": "my_gcm_key" ,  
               "registration_ids": "user_id" , //also tried adding deviceToken here
               "additionalData": {
                          "style": "picture",
                          "picture": "http://36.media.tumblr.com/c066cc2238103856c9ac506faa6f3bc2/tumblr_nmstmqtuo81tssmyno1_1280.jpg" 
                                           }
                   }}
regards.

**Comment by ahlidap** [comment]
Hi,

"registration_ids" accepts a list of ids (REGID from GCM after plugin register)

```
registration_ids: ["id1","id2"]
```

for sending to single device you should use "to"
```
to: "RegID"
```

And it is just "data" (additionalData is for data handling in javascript).
So:

```
{
to: "RegId" , //also tried adding deviceToken here
data: {
style: "picture",
picture: "http://36.media.tumblr.com/c066cc2238103856c9ac506faa6f3bc2/tumblr_nmstmqtuo81tssmyno1_1280.jpg" 
}
}
```

This is the content (application/json) you send to GCM service.
on Javascript application you init the plugin with
```
android: {senderID: "googleid"}
```


Occasionally I'm having problems when receiving push with picture.
Some times, it simply won't display picture.
Have this happened to someone else?

**Comment by AtulaGuleria** [comment]
Thanks for replying ...good relief 
Can you explain where you  have written this regId in your code ... I mean under android section or anywhere else

**Comment by macdonst** [comment]
@AtulaGuleria you don't add your registration ID's and picture url to the JSON object that you pass to PushNotification.init(). You send a POST to GCM that includes your registration ID's you want to push with and the data you want to send. I recently updated the picture message info here:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#picture-messages

which gives you an example of how to do it via node-gcm.

**Comment by AtulaGuleria** [comment]
Thanks for replying ..
I'll check that and come back to you again.

**Comment by AtulaGuleria** [comment]
Oh ! I have already checked that .
Please do one more favor ...tell me how to post .
As I am only able to change icon.

**Comment by macdonst** [comment]
@AtulaGuleria run the node script I linked to above.

**Comment by AtulaGuleria** [comment]
Ok I'll check that .. 
Anyways thanks ..
