### ISSUE TITLE
the plugin is not initialized in iOS

### ISSUE THREAD

**Issue by dolcom87** [phonegap/phonegap-plugin-push#581]
This plugin didn't init in iOS

my code is available here: [https://gist.github.com/dolcom87/bbd2ad395abbf7ac9e01](https://gist.github.com/dolcom87/bbd2ad395abbf7ac9e01)
xCode log: [https://gist.github.com/dolcom87/3a42d5c81c951cc75e72](https://gist.github.com/dolcom87/3a42d5c81c951cc75e72)

When I placing alert before push init code I getting the alert on device ready, but if I placing alert after push init then nothing happens

That's mean the push did not init

I'm using:
- plugin 1.5.3
- xCode 7.2 (7C68)
- cordova 6.0.0
- iPhone 5s iOS 9.2.1 (13D15)

**Comment by macdonst** [comment]
@dolcom87 issues like this where I have no idea what your problem is, is why I wrote this https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/ISSUES.md

**Comment by vivekdoshi2** [comment]
Yes I got the same issue,please let us know ,what to do?

Plugin is working greta with Android,but when I tried to get device id for IOS9.2(13C75)
Its just stops there.

**Comment by macdonst** [comment]
@dolcom87 so if you are putting an alert dialog between lines 10-11 of your example and you are no seeing it then I'd say you need to check the JS console as possibly PushNotification is not found. If it is found, i.e. included correctly then most probably it is an issue with your iOS certs.

**Comment by dolcom87** [comment]
@macdonst I fixed it. It was not a plugin issue, it was an issue of the cordova. But thanks for help.
