### ISSUE TITLE
Android: for action buttons - want the IOS equivalent of 'foreground: false'?

### ISSUE THREAD

**Issue by jopelkey** [phonegap/phonegap-plugin-push#585]
In Android, is there the equivalent in IOS of your 'foreground: false'?
i.e. I want to be able to do something when a user picks an action button without opening the application.  Is that possible?

**Comment by macdonst** [comment]
@jopelkey the value `data.additionalData.foreground` should be available in both Android and iOS.

**Comment by jopelkey** [comment]
Sorry - I wasn't clear in my question.  
I know about data.additional.foreground being available for both Android and IOS when I receive a notification.
However - what I want is the ability when specifying action buttons, to specify on Android that the app does NOT open into the foreground when an action button is selected.  I see that documented in the init config for IOS, but not in the push payload for Android.  I just want to process the callback for an action button in the background for both iOS and Android.

**Comment by macdonst** [comment]
@jopelkey oh okay, I gotcha now. I have already fixed this for #551 and it will be in 1.6.x release.

**Comment by jopelkey** [comment]
That's great - thanks for all the hard work on this plugin!

Do you happen to have an approximate ETA for the 1.6.x release?  Just trying to coordinate some release schedules on my end, so any info you have on when 1.6.x will be available would be helpful.

**Comment by macdonst** [comment]
@jopelkey I will cut a release before Feb 19th. Might have to shed some planned fixes though. Running callbacks when the app is terminated is pretty hard :smile:

**Comment by jopelkey** [comment]
Thanks for the date info on 1.6.x
For what it's worth - personally I'm really hoping for callbacks on IOS when the app is in the background (i.e. #576), even if callbacks when the app is terminated doesn't make it...  I can't tell from your previous comment if that is at risk, or other things are at risk so you can get that done?  Any insight appreciated!  Thanks.
