### ISSUE TITLE
Shoddy image for notification icon,status bar icon?

### ISSUE THREAD

**Issue by jayeshjain24** [phonegap/phonegap-plugin-push#587]
I have successfully implemented the push notification. However I am not happy with outcome because the icons look a little shoddy.  I know I can generate icons from [here](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_stat_logo)  but when I put those images in drawables folder,it looks a little pixelated. 

What guidelines should I follow to generate clean,non-pixelated notification icons. I generated the images from a png image of size 200x139

**Comment by macdonst** [comment]
https://www.google.com/design/spec/style/icons.html#
