### ISSUE TITLE
iOS GCM background Notification is not received 

### ISSUE THREAD

**Issue by davidavsira** [phonegap/phonegap-plugin-push#588]
Hi, 
I'm trying to send push notification with GCM to ios device but only receive it if the app is running.

any idea how to solve this problem?

**Comment by fredgalvao** [comment]
@macdonst what happens if I send a notification without `title|alert+message` but don't specify `"content-available": 1` either? Will it still show a notification? Will it be saved so that it can be sent to the js handlers when they're active? I can't find a way to this one through the current docs.

**Comment by macdonst** [comment]
@fredgalvao what happens is I wish I never merged the GCM to iOS PR. It isn't as feature complete as APNS and I haven't had the time to go document all the inconsistencies.

**Comment by davidavsira** [comment]
ok I solve the problem.
accidently confuse between APNS and GCM syntax:  
1. I wrote "content-available" instead "content_available".
2. I set "content_available" value to "1" instead of "true".
and also set "priority" to "high".

**Comment by fredgalvao** [comment]
Can this issue be closed then, @davidavsira ?

**Comment by davidavsira** [comment]
yes

**Comment by BhomiaAshish151** [comment]
hi friend 
1. I wrote "content-available" instead "content_available".
2. I set "content_available" value to "1" instead of "true".
and also set "priority" to "high".

where we set these values

**Comment by davidavsira** [comment]
You need to set these value on the HTTP Post request (or XMPP).
search for "content_available" and "priority" information here:
https://developers.google.com/cloud-messaging/http-server-ref#downstream-http-messages-json

**Comment by Koozamo** [comment]
The docs still specify that content_available : true should not be used, however I think that iOS still requires it if you want to get the background notification to work without clicking on the notification.  Perhaps, the docs should say for iOS, content_available : true SHOULD be used?

**Comment by lethianqt94** [comment]
I send in Console, but I got no notification on real device. Does someone know why?
