### ISSUE TITLE
Registration ID for android

### ISSUE THREAD

**Issue by streetkid** [phonegap/phonegap-plugin-push#593]
The registraiton for Android gives me this 
: {"registrationId":"ezr4JqDocKk:APA91bHu8fwxxxxxxxxx"}

The previous plugin for push gave me the registration Id  like APA91xxx

Anyone knows what does the first part mean?

**Comment by macdonst** [comment]
@streetkid this plugin uses the Google Instance ID which is the current recommendation from Google. You can read more about it here:

https://developers.google.com/instance-id/
