### ISSUE TITLE
Push Callback "object is not a function"

### ISSUE THREAD

**Issue by 19113** [phonegap/phonegap-plugin-push#594]
I'm using push notifications for android, and on receiving the notification, I am having the notification hook fire more than once for a notification.

On inspecting the logs, I found the following 3 messages which I thought might be relevant:
1. "Error in Success callbackId PushNotificationxxxxxx : TypeError object is not a function"
2. Widevine DRM not supported on this device
3 [AppCertManager] IOException while requesting key

**Comment by macdonst** [comment]
@19113 https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/ISSUES.md#opening-a-new-issue
