### ISSUE TITLE
Accessing notifications received while the app is closed on iOS

### ISSUE THREAD

**Issue by matdev** [phonegap/phonegap-plugin-push#595]
Currently when the app is closed (i.e not in background) the notification event is triggered only when the user opens the app by clicking on the notification in the iOS notification center.

Is it possible to access the list of recent notifications from the iOS or APN api ?

This would enable displaying past notifications when the user re-opens the app.

**Comment by macdonst** [comment]
@matdev this is the same root cause of #557.

**Comment by matdev** [comment]
Indeed, that's why I am looking for a workaround.
Being able to read past notifications when the app starts up would solve the problem.

A "no it's not possible" answer would be fair enough.

**Comment by macdonst** [comment]
@matdev Yeah, it's currently not possible. The user would have to click on the notification in the shade in order to fire the event.

**Comment by matdev** [comment]
But there are many apps displaying past notications received while they are closed.

Do you mean it's not possible to do with the plugin but possible natively ?

**Comment by macdonst** [comment]
@matdev if you want the event fired even when the user does not click on the notification then you'll need to look at background notifications in the docs. You can still have UI with these notifications but you'll have to keep track of the events since if the user clicks on the notification again you'll get the event a second time. Usually folks will just put a unique ID in the notifications to track.

**Comment by matdev** [comment]
I already display background notifications properly, thanks.

My question relates to notifications received when the app is fully closed, i.e not in background.

As I said, many apps displays past notifications when they are re-opened.

Why the plugin does not allow that ?

**Comment by nicoabie** [comment]
@matdev The thing is that the notifications are stored in memory and just the last of them. As of now the plugin doesn't persist them, that's why it doesn't allow that.

**Comment by matdev** [comment]
I don't get it; how could the plugin persist notifications if the app is not running ?

**Comment by nicoabie** [comment]
@matdev In order to accomplish the display of past notifications when the app is re-opened, those notification should be stored somewhere. I don't get your question.

**Comment by matdev** [comment]
Well some past notifications are stored somewhere on the phone, since they are displayed in the notification center.

The question is how do native apps manage to display past notifications when they are re-opened ? 

Do they have an access to past notif' that cordova apps don't ?
Or do they load past notifications from a web service somewhere ?

**Comment by johnnyoin** [comment]
Calling `setApplicationIconBadgeNumber(success, failure, 0)` will clear all the notifications for your app.
