### ISSUE TITLE
node-gcm with phonegap-plugin-push - Background Notification event handler not working 

### ISSUE THREAD

**Issue by ronyrun** [phonegap/phonegap-plugin-push#596]
Hello, currently I'm using phonegap-plugin-push  (amazing thank you!) and I'm properly getting notifications with node-gcm.

When the app is foreground, the push.on('notification', function(){}); is working.
When the app is closed // background I don't get any events when the user click on the notification and open the app.

```
var messageTest = new gcm.Message({
    priority: 'high',
    contentAvailable: true,
    delayWhileIdle: true,
    timeToLive: 3,
    data: {
        key1: 'message1',
        key2: 'message2'
    },
    notification: {
        title: "Hello, World",
        icon: "icon",
        body: "This  is a notification that will be displayed ASAP.",
    },
});
```

the content received in the  push.on('notification', function(){}); is like : 

{"title":"Hello, World","message":"This is a notification that will be displayed ASAP.","additionalData":{"content-available":"1","e":"1","icon":"icon","key1":"message1","key2":"message2","collapse_key":"net.myApp.www","foreground":true}}

This click on the notification open the Ionic / cordova app without problems, but not the event handler.

Do you know how to make it work ?

Regards,

**Comment by ronyrun** [comment]
I found the issue : 

everything must go in the property data.

**Comment by SikZone** [comment]
Hi, can you provide an example of the working code? I don't get how to resolve this issue.

**Comment by macdonst** [comment]
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications-1
