### ISSUE TITLE
push.on 'notification' never fired in android & ios

### ISSUE THREAD

**Issue by novalabstudio** [phonegap/phonegap-plugin-push#597]
Hello,
this is my init:
`push = PushNotification.init({`
`"android":{`
`"senderID": "122121221",`
`"sound": "true",`
`},"ios": {`
`"alert": "true",`
`"sound": "true",`
`}`
`})`

`PushNotification.hasPermission` - says ok
`push.on 'registration'` - says ok

but the push.on notification never fire, nor if the app is in background or in foreground!!

i can't see any error on logcat..

anyone can help me?

**Comment by ronyrun** [comment]
what do you use to send the notification ?

**Comment by shawns582** [comment]
I am also having this issue and would appreciate any help.   I have tried using Amazon SNS to publish to an endpoint (where I use registration id) as well as https://github.com/mattg888/GCM-PHP-Server-Push-Message.  Thanks..im desperate!

**Comment by novalabstudio** [comment]
i use parse. Notifications is correctly displayed into the notification center and if i click on it, they launch the app! But event don't fire!

**Comment by macdonst** [comment]
@novalabstudio I can't reproduce this. Code please.

**Comment by novalabstudio** [comment]
```
var push;		// global variable

document.addEventListener('deviceready', function () {
	parsePlugin.initialize( "dsdsdssdsdsdd", "dsdsdsdsdewewewew", function() {
		console.log('++++++++++++++++++++++ Parse initialization ok!");	
	}, function(e) {
		alert( "Error in plugin initialization:" + e.message );
	});
	push = PushNotification.init({
		"android":{
			"senderID": "1111111",
			"sound": "true",
		},
		"ios": {
			"alert": "true",
			"sound": "true",
		}
	});

	push.on( 'notification', function(data) {
		console.log('++++++++++++++++++++++ FIRE ON!!' );
		alert( data.message );
	});

	push.on('error', function(e) {
		alert(e.message);
	});
} );
```

The alert and console.log into the push.on('notification'.. never fire!!

**Comment by ronyrun** [comment]
https://github.com/ToothlessGear/node-gcm/#gcm-client-compatibility

**Comment by novalabstudio** [comment]
but.. it is parse compatible?

**Comment by boyfunky** [comment]
is anyone able to get the onNotification event to get fired when app is in background?

**Comment by Gnaneshwar511** [comment]
I'm also not able to fire the method " push.on('notification', function(data) { "

**Comment by ronyrun** [comment]
This event is fired when you reopen the app.

**Comment by Gnaneshwar511** [comment]
No. It is not getting fired on the click of notification. Also not when the App is in the Background and in Foreground. Basically, it's never getting called.
When I click on notification, only push.on('registration', function(data) {' and 'receivedEvent: function(id)}' are getting invoked.

**Comment by Gnaneshwar511** [comment]
Sorry. Just now found out that:

> 'push.on('notification', function(data) {' -> gets invoked when a push notification comes while app is in foreground

> 'receivedEvent: function(id) {' and 'push.on('registration', function(data) {' -> gets invoked when push notification is clicked and opened from the notification tray.

However, I want to know the difference between 'receivedEvent: function(id) {' and 'push.on('registration', function(data) {'

**Comment by Gnaneshwar511** [comment]
On further research, I found out that when we have 'notification' block and 'data' block in the payload, or with the 'notification' block alone, we cannot get the 'push.on('notification', function(data) {' function to get fired as intended (i.e with App on both Foreground and Background it should get fired). But if you just have 'data' block in the payload it works absolutely fine.

Hope this helps a bit in fixing the issue.

**Comment by SaiGanesh94** [comment]
Can you please post your code? So that it will be helpful.

**Comment by Gnaneshwar511** [comment]
On Android the below payload is triggering the event for me
`{
  
  "to" : "/topics/general",
    "notification" : {
"body" : "great match!",
"title" : "Portugal vs. Denmark",
"icon" : "myicon"
},
  
    "data" : {
      "url" : "www.url.loc"
    }
  }`

But the payload that has both the 'data' and 'Notification' blocks is failing to trigger the function.

**Comment by fredgalvao** [comment]
Android needs the payload on the `data` field, iOS needs it on the `notification` field.

**Comment by SarabjeetRuby** [comment]
@Gnaneshwar511 sending payload of data fields work for me.It's really help me in my situation (y)

**Comment by macdonst** [comment]
@Gnaneshwar511 I've doc'd and answered this before but on Android you have to send in the data field:

```
{
  "to" : "/topics/general",
  "data" : {
    "body" : "great match!",
    "title" : "Portugal vs. Denmark",
    "icon" : "myicon",
    "url" : "www.url.loc"
  }
}
```

and when the notification event handler gets fired is in this diagram: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#overview

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
