### ISSUE TITLE
Enable Multiple Notifications on Android

### ISSUE THREAD

**Issue by personstays** [phonegap/phonegap-plugin-push#598]
Hi,
Thanks for the plugin. Anyway, how could I have multiple notifications on android? Whenever I send push notifications to a device, the new one always replaces the old one. I prefer to having multiple notifications without replacing any others.

Thanks!

**Comment by rachmansyahbs** [comment]
Based on [PAYLOAD.md](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#stacking) under 'Stacking', you'll have to provide different "notId" in the payload for each notification.

**Comment by abdoutelb** [comment]
you can put a unique value for "notId" prob in notification object

**Comment by personstays** [comment]
Poor me, I didn't check the doc.
Thanks for your answer. (y)
