### ISSUE TITLE
 more than one library with package name 'com.google.android.gms'

### ISSUE THREAD

**Issue by alecapu** [phonegap/phonegap-plugin-push#600]
When some other packages include cordova-google-play-services as cordova-admob or cordova-plugin-analytics is not possibile add the phonegap-plugin-push because during the build process I've this issue:

:processDebugResources FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms'

BUT other plugins that use cordova-google-play-services  can live together without problem (es. cordova-admob and cordova-plugin-analytics). Why phonegap-plugin-push not?

I'm using cordova version 6.0.0

**Comment by macdonst** [comment]
@alecapu specifically which plugin(s) are you having problems with in conjunction with this one?

**Comment by alecapu** [comment]
cordova-plugin-analytics

**Comment by macdonst** [comment]
@alecapu which one? URL please.

**Comment by alecapu** [comment]
cordova plugin add cordova-plugin-analytics
or
cordova plugin add https://github.com/appfeel/analytics-google.git

**Comment by macdonst** [comment]
@alecapu yeah, that plugin is not up to date. It should be using gradle to include the Google Play Services package but instead it includes the cordova-google-play-services plugin as a dependency and that plugin includes the play services jar. So all of that is bad news. The plugin should be updated to use gradle and in fact there is a PR open to do just that https://github.com/appfeel/analytics-google/pull/11. You should bug the team at appfeel to merge that PR.

Alternatively, switch to another plugin that provides the same functionality but uses gradle:

https://github.com/danwilson/google-analytics-plugin
https://github.com/cmackay/google-analytics-plugin

**Comment by alecapu** [comment]
Thank you very much

**Comment by fredgalvao** [comment]
That's a good candidate to be added to https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#common-errors, @macdonst

**Comment by macdonst** [comment]
@fredgalvao will do

**Comment by fredgalvao** [comment]
This is kinda off topic:

@macdonst Something strange happened involving these last commits, I had made some improvements to the description on https://github.com/phonegap/phonegap-plugin-push/commit/8f06ed15da6342011b3cbb64560e340ca7c0d7e2 as you pushed it, as a new commit: https://github.com/phonegap/phonegap-plugin-push/commit/931fd43a0ed5f1130bb5327529b0dd4123e910e5. But that commit is now gone after you seemingly re-pushed a few recent commits. I can't see a way to fix it quickly, nor do I fully understand what happened.

**Comment by fredgalvao** [comment]
@macdonst Can you help me understand what happened with that commit I mentioned?

**Comment by macdonst** [comment]
@fredgalvao I probably did a force push at one point an overwrote it. Can you re-submit your changes?

**Comment by fredgalvao** [comment]
@macdonst Done: https://github.com/phonegap/phonegap-plugin-push/commit/868021357ceeeb1a77f023eea618ac7ef279e92d
