### ISSUE TITLE
How to make GCM show alert automatically ios

### ISSUE THREAD

**Issue by dtruel** [phonegap/phonegap-plugin-push#602]
Hello,

Thanks for your work on this plugin!

I want my app to show a GCM alert just like an ios alert.  For some reason, it is not actually doing the alert.  It is just calling the GCM notification function, where I can show an alert.  I don't really want that function to be called.  I just want the standard ios notification alert to be called.  When a notification comes in the background, I just want it to be handled the standard ios way, and shown without ever needing to contact my app.  Is there any way to do this, or do I always have to do all that manually when using GCM?

Thank you!

**Comment by macdonst** [comment]
@dtruel what are you sending to the iOS device?

**Comment by dtruel** [comment]
I'm doing this right now in php.  Is it supposed to have the functionality I was looking for?

```php
$data = [
  "to" => $gcm_id,
  "content_available" => true,
  "notification" => [
    "title" => "Alert",
    "alert" => "this is an alert",
    "body" => "Tornado Coming!!",
    "sound" => "siren.mp3"
  ] 
];
```

**Comment by dtruel** [comment]
Hey I just added `priority => high` and it's working! thank you!
