### ISSUE TITLE
PushNotification is undefined when running on iOS with Cordova > 5.3.3 (e.g. 6.0.0)

### ISSUE THREAD

**Issue by T18970237136** [phonegap/phonegap-plugin-push#605]
Hi,
I'm using this plugin on a Visual Studio 2015 Cordova Project (with Cordova Tools Update 6 installed) using Cordova 6.0.0. This will use cordova-ios-4.0.1. However, when I run the app, the "PushPlugin" variable is undefined. If I use Cordova 5.3.3 (using cordova-ios-3.9.2), the PushPlugin works correctly.

I used these steps to reproduce:
1) In Visual Studio 2015 with Cordova Tools Update 6, I created a new Cordova project.
2) Double-clicked on config.xml, then on the Platforms tab I selected "6.0.0" for Cordova CLI version.
3) On the Plugins tab, I added the phonegap-plugin-push plugin using the Git URL (Version 1.5.3).
4) On the Common tab (the first tab), I entered "index.xhtml" as start page.
4) In the projects www folder, I removed the default files, and then placed the following index.xhtml file (the extension ".xhtml" is importand so that the document is treated as XML instead of HTML, which is what I'm using):
```xml
<?xml version="1.0" encoding="UTF-8" ?><!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Test Push on iOS</title>
    <!-- Cordova-Script -->
    <script type="text/javascript" charset="utf-8" src="cordova.js"></script>
    <script type="text/javascript" charset="utf-8" src="scripts/platformOverrides.js"></script>
    <script type="text/javascript" charset="utf-8" src="myscript.js"></script>
</head>
<body>
    <div>Test</div>
    <pre id="result"></pre>
</body>
</html>
```
Then added the following myscript.js:
```javascript
(function () {

    // Listen for the device ready event.
    document.addEventListener('deviceready', handleDeviceReady.bind(this), false);

    function logConsole(text) {
        document.getElementById("result").appendChild(document.createTextNode(text + "\r\n"));
    }

    function handleDeviceReady() {
        logConsole("DeviceReady. Trying to register...");
        try {

            // Register for notifications.
            var push = PushNotification.init({
                android: {
                    senderID: "123456",
                    clearNotifications: false
                },
                ios: { alert: true, sound: true },
                windows: {}
            });

            logConsole("Register called.");

            push.on('registration', function (data) {
                logConsole("Registration received: " + data.registrationId);
            });

        } catch (e) {
            logConsole("EXCEPTION: " + e);
        }
    }

})();
```

5) Then I built the project for iOS using the instructions at http://taco.visualstudio.com/en-us/docs/run-app-ios/#iOSDevice (in VS symbol bar, I selected "Debug", "iOS", "Local Device") and then created the project).

6) When running the app on a iPad with iOS 9.2.1, the document shows "ReferenceError: Can't find variable: PushNotification".

7) Then I opened the config.xml again, and set the Cordova CLI version to "5.3.3". To ensure everything is built again, I deleted the "bin", "bld" and "platform" folders in the project directory.

8) After building and running the app again, it works correctly, showing "Registration received" with the registration ID.

Note, that with Cordova CLI 5.4.1, the same error (ReferenceError) happens as with 6.0.0. However I want to upgrade to Cordova 6.0.0 so that I can use the newer WKWebView.

Thanks!

**Comment by macdonst** [comment]
@T18970237136 I have no way of debugging this. Can someone with a windows system step up?

**Comment by T18970237136** [comment]
Hi,
I did some more testing and found that it doesn't seem to be a problem of this plugin, because the same problem (variables are undefined) exists for other plugins. Therefore I created an issue at the Cordova project: https://issues.apache.org/jira/browse/CB-10599

**Comment by Mathijs003** [comment]
@macdonst the ADB plugin handles the console and network tools just like in chrome. Set up adb on your windows and connect your device with "usb debugging" on. Your device should be detected by the plugin. https://chrome.google.com/webstore/detail/adb/dpngiggdglpdnjdoaefidgiigpemgage
