### ISSUE TITLE
Notification on Android does not switch back to app

### ISSUE THREAD

**Issue by Oliv** [phonegap/phonegap-plugin-push#609]
Hello there, I am experiencing an issue on Android, when I tap on a new notification the application does not switch back to front.

Did someone already experienced that ?

Best regards, Olivier

**Comment by macdonst** [comment]
@Oliv nope, never seen that ever. Are you buy chance editing your AndroidManifest.xml to change the `android:launchMode`?

**Comment by Oliv** [comment]
@macdonst  I think the problem is here. I was in singleInstance mode, tried all options but still no good result. When I tap the notification, I get the right notification event in the app, but not the app brought back to front. Do you know what are the right configs ?

Regards, Olivier

**Comment by Oliv** [comment]
It works now, solved it using singleTask param ! Thanks a lot
