### ISSUE TITLE
Ios not playing custom sound only on non-dev device

### ISSUE THREAD

**Issue by dtruel** [phonegap/phonegap-plugin-push#611]
Hello, I am trying to get a custom sound to play with GCM on iOS.  The funny thing is that everything works as it should when I run it on my development device.  I uploaded the app to test flight, deleted the dev version, and it still works fine on my test device.  But when I download to any other device, the custom sound doesn't play and I get the default sound.

I am downloading the sound "siren.wav" to "Library/Sounds" on my device on startup using another cordova plugin.   I hooked up my old iPhone (running ios 8, not my dev iphone), and looked through the application data container, and sure enough, the sound had been downloaded properly and worked when I played it in iTunes on my computer.  The sound is there, but it still plays the default notification. I also had someone with ios 9 download it and they had the same issue.  Any idea why?

I'm sending this to GCM

```
{
  "to":"gcm_id",
  "content_available":true,
  "notification":{
    "title":"title",
    "alert":"this is an alert",
    "body":"this is the body",
    "sound":"siren.wav"
  },
  "priority":"high"
}
```

Thank You!

**Comment by macdonst** [comment]
@dtruel I don't think iOS can play a wav file as a push notification sound. Check out the link I put in https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#sound-1 to convert the sound to the right format.

**Comment by dtruel** [comment]
According to apple, you can use a wav.  But I changed it to m4a and it worked!


https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/IPhoneOSClientImp.html

**Comment by macdonst** [comment]
@dtruel you can use a wave file as long as it is PCM linear alaw or mu-law encoded.
