### ISSUE TITLE
Unable to get Sender ID in iOS

### ISSUE THREAD

**Issue by pallaviMN** [phonegap/phonegap-plugin-push#612]
Hi Team,

when i tried to add this plugin for ios, push.on('registration'), never gets called. When i debugged code in pushplugin.m i found "[self setGcmSenderId: [iosOptions objectForKey:@"senderID"]];" do not retun anything.

**Comment by macdonst** [comment]
@pallaviMN are you trying to use GCM to send messages to iOS? Please look at my guide for creating an issue.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/ISSUES.md

**Comment by pallaviMN** [comment]
No, i am not using GCM, i added cordova plugin in our project, tried to install in iOS device.@mcdonst

**Comment by macdonst** [comment]
@pallaviMN right so you don't need to worry about setting the senderID on iOS then. Please look over the how to report an issue doc I linked to.

**Comment by pallaviMN** [comment]
@macdonst , but i am unable to get registration ID in ios.

**Comment by pallaviMN** [comment]
i am not sending any sender ID
