### ISSUE TITLE
Using GCM for iOS / Android, what to send in Notification/Data objects

### ISSUE THREAD

**Issue by OJcode14** [phonegap/phonegap-plugin-push#616]
I can get a success message back from GCM using node-gcm if I just set the data object, but then nothing is received on the device at all. All I need at this present time is to have an alert received on iOS but nothing I've tried works. As soon as I include the notification object I get a 500 from GCM. 

```
var message = new gcm.Message({
                                        data: {
                                            'title': 'Title Test',
                                            'message': 'message2',
                                            'content-available':'1'
                                        },
                                        notification : {
                                        title:"Title test",
                                        body:"This is a test message",
                                        sound:"default"
                                        }
                                    });
```

I'm only posting this here in hope of a working example of what I can send here as I've spend countless hours in trial and error and trawling the docs and nothing seems to work :(

**Comment by Clebiez** [comment]
Hi, 
GCM mean Google Cloud Messaging, it mean that is only work for Android.

You must use APN (Apple Push Notification) with the node module apn-node for send notifications on your ios devices.

**Comment by OJcode14** [comment]
That's not true. You can use GCM for apple push notifications.

**Comment by neoadventist** [comment]
Yeah you can use GCM for apple @Clebiez

**Comment by OJcode14** [comment]
@neoadventist you have a working example of what you send to GCM for apple notifications? I know it works, I just can't get it going!

**Comment by barocsi** [comment]
+1

**Comment by macdonst** [comment]
@OJcode14 the [payload doc](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#android-behaviour) has many examples of using node-gcm to send messages. Try following them. If they do not work please re-open the issue.

**Comment by neoadventist** [comment]
@macdonst what we're asking is how to use this to send to GCM to send push notifications to ios. Do you have any insight about this?
