### ISSUE TITLE
Nothing is working

### ISSUE THREAD

**Issue by dhwalin** [phonegap/phonegap-plugin-push#617]
I have installed plugin. I have written code in index.js then also nothing is happening. Is there anything to add in index.html?

**Comment by macdonst** [comment]
@dhwalin this is exactly what I talk about in my docs:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/ISSUES.md

If you want people to be able to help you please make it somewhat easy for them to provide you that help.
