### ISSUE TITLE
IOS  just sound no shade

### ISSUE THREAD

**Issue by colonna-mike** [phonegap/phonegap-plugin-push#619]
Hello,
With Version 1.4.3 I only getting sound on my iPad no shade?
however in-app notification is working just find.

my payload looks like this PHP:

because I'm using Intel XDK and they don't support gradle i'm using the above version.

```
 $payload['aps'] = array(
                               'alert' =>  array(
                                    'title' => $title,
                                    'body '  => $message
                               ),
                               'content-available'=> 1,
                               'badge' => '1', 
                               'sound' => 'default',

                               'userid'         => $userid,
                               'familyid'       => $familyid,
                               'postid'         => $postid,
                               'type'           => $type,
                               'postuserid'     => $postuserid,
                               'commentid'      => $commentid
                            );

```

**Comment by macdonst** [comment]
@colonna-mike that's weird. I'm not a PHP expert but you should see this working. Here are two things to try:

1) Remove `content-available => 1` as it can do funny things if your push has a alert, badge or sound as per https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH107-SW6

2) instead of alert being an array just send it as text:

`'alert' =>  $message`

and let me know what's happening.

**Comment by colonna-mike** [comment]
I give it a go but i'm not sure what 'alert' => $message as string would look like?

**Comment by colonna-mike** [comment]
okay I removed the content-available => 1 and when the app is in the foreground it stop working when I put it back I get  when the app is in the foreground it works just find. its when the app is in the background or needs a cold start is where the issue is.

**Comment by macdonst** [comment]
@colonna-mike what I meant was:

```
$payload['aps'] = array(
                               'alert' =>  $message,
                               'content-available'=> 1,
                               'badge' => '1', 
                               'sound' => 'default',

                               'userid'         => $userid,
                               'familyid'       => $familyid,
                               'postid'         => $postid,
                               'type'           => $type,
                               'postuserid'     => $postuserid,
                               'commentid'      => $commentid
                            );
```

Instead of using your PHP code can you try following:

http://macdonst.github.io/push-workshop/module4.html
https://github.com/macdonst/push-workshop/blob/master/server/apnService.js

to send your first test message. There is no reason why you shouldn't see the notification in the shade.

**Comment by colonna-mike** [comment]
okay I could not really use that however, staying with the idea of stripping the payload down I created this payload.

`    $payload['aps'] = array('alert' => 'Oh hai!', 'badge' => 1, 'sound' => 'default');  `


and it worked!  that's the good news the bad news is without the additional payload my app does not show the proper page. .. What  I need to figure out is how to set up the additional data. 

 thanks!

**Comment by colonna-mike** [comment]
OKAY, I just reread you comment above and 
 and it worked! Thank so much for taking the time to help me...
I really do appreciate it.
```
$payload['aps'] = array(
                               'alert' =>  $message,
                               'content-available'=> 1,
                               'badge' => '1', 
                               'sound' => 'default',

                               'userid'         => $userid,
                               'familyid'       => $familyid,
                               'postid'         => $postid,
                               'type'           => $type,
                               'postuserid'     => $postuserid,
                               'commentid'      => $commentid
                            );

```
