### ISSUE TITLE
Don't show notification

### ISSUE THREAD

**Issue by marcoas** [phonegap/phonegap-plugin-push#621]
It's possible hide notifications, or do not show it, from on notificationn event?

Example code ...
    If( notificationData.myField == 10 ) {
       // never show notificación to user
    }

**Comment by macdonst** [comment]
@marcoas yes, it is possible. If you don't want it to end up in the notification shade you send a background notification but omit the bits to be shown like title/body on Android and alert/sound on iOS.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications-1

**Comment by marcoas** [comment]
But I need send the same notification (topic method) with lat/long data in it,  and then, show it to some users and hide to other.  If these user is near location

Do you understand me?

**Comment by macdonst** [comment]
@marcoas right send the data in the background and if the user is close to the location use the local notification plugin to show the data.

https://github.com/katzer/cordova-plugin-local-notifications

**Comment by marcoas** [comment]
+10.  Great idea.
Thank You
