### ISSUE TITLE
[not a bug] when to use hasPermission?

### ISSUE THREAD

**Issue by guykatz** [phonegap/phonegap-plugin-push#628]
Hi all;
I am having some trouble understanding the use case in which I need to use the hasPermission function (android & ios)
I am porting to this plugin from another push plugin where this options was not available. I already have this plugin up and running on android and ios and I did not have to use the hasPermission atall.
can someone enlighten me?
thanks in advance!

**Comment by macdonst** [comment]
@guykatz never, is the best answer. Deprecating for 2.0.0.
