### ISSUE TITLE
multi-line text support

### ISSUE THREAD

**Issue by austinpapp** [phonegap/phonegap-plugin-push#63]
Looking for the ability to display up to some arbitrary number of multi-line text when previewing from the notification drawer.  It looks like gmail has support for at least 3 "lines" of text so we can start there as a base point. however, I'm not sure if this is based on buffer size or a limit on number of characters but either would work just fine here.

This is a follow up to [issue 62](https://github.com/phonegap/phonegap-plugin-push/issues/62)

**Comment by jterps08** [comment]
+1

**Comment by JustDoItSascha** [comment]
Is this implemented yet? How does it work? I can find anything in the docs and my notification title is still truncated...

**Comment by cen78756** [comment]
me too I hav my notification truncated as well, can anybody help me?

**Comment by mokingguy** [comment]
Was this ever implemented? I have this issue and don't know if it's been implemented since the docs don't show support
