### ISSUE TITLE
When user clears Status Bar Notifications

### ISSUE THREAD

**Issue by pallaviMN** [phonegap/phonegap-plugin-push#630]
Expected Behaviour :- The app is in background, now the notifications are received in status bar. User see that status bar notifications & swipes left to clear it. Now when user tries to bring app to Foreground, notifications are not seen in the app.

 Actual Behaviour - when the user clears the status bar notifications, if the app is opened then notifications must be received

 Reproduce Scenario (including but not limited to) - Launch the app. Keep the app in Background. Now trigger some notifications. Notifications will come in status bar. Clear the notification. Now bring the app to foreground. Notifications are not received.

Steps to Reproduce - Launch the app. Keep the app in Background. Now trigger some notifications. Notifications will come in status bar. Clear the notification. Now bring the app to foreground. Notifications are not received.

Platform and Version (eg. Android 5.0 or iOS 9.2.1) - Android 4.2 & above

 Sample Push Data Payload - Not Applicable

 Sample Code that illustrates the problem - Not Applicable

Logs taken while reproducing problem - Not Applicable

**Comment by macdonst** [comment]
@pallaviMN what you are describing is the correct way for notifications to work. If the user dismisses the notification the even should not and in our case is not delivered to the application. Perhaps if you could explain why you want an event on a dismissed notification I might be better able to help you.

**Comment by pallaviMN** [comment]
@macdonst , like in facebook & whats app, even if we clear status bar notifications, after opening an app, we those notifications. So wanted to check once

**Comment by macdonst** [comment]
@pallaviMN don't background notifications fit this use case?

**Comment by pallaviMN** [comment]
@macdonst Background notifications will trigger once if the user taps on the status bar notifications. If the user clears notification in the status bar , then the notification is not received in the app. So please help us if you have any suggestion.

**Comment by rrusher** [comment]
Ditto.
The notification event callback is not called until the user taps the notification in the status bar.

Is there another event that we can use to send data to the app upon receiving the notification, without user intervention?

**Comment by macdonst** [comment]
@rrusher are you setting the `content-available` flag?

**Comment by rrusher** [comment]
@macdonst I think this is the designed behavior. If I want data in the app, I should have the app pull it from the backend. Then use the notifications to inform the user their is new data that might interest them.

**Comment by macdonst** [comment]
@pallaviMN and @rrusher I'm confused, if you send a notification and the user dismisses it then there will be no event fired and that is by design. If you set the `content-available` flag then when the notification is received the event will be fired without the user needing to click on it. Isn't that the behaviour you want?

**Comment by pallaviMN** [comment]
@macdonst , can you please tell in which file we need to set"content-available" flag??

**Comment by macdonst** [comment]
@pallaviMN 

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications-1
