### ISSUE TITLE
Am I downloading custom file to right location in Android

### ISSUE THREAD

**Issue by dtruel** [phonegap/phonegap-plugin-push#633]
### Expected Behaviour
Hi, I'm trying to get  a custom sound to play in android.

### Actual Behaviour
Playing default sound

I download a file called `siren.mp3` to `file:///data/data/com.mycompany.myapp/files/res/raw`.  It doesn't play. Is this the right location?

Thanks!

**Comment by macdonst** [comment]
@dtruel no, that is not the right location. You need to include the sound in your apk when you build. So the location would be:

`project_name/platforms/android/res/raw`

then when you do `cordova build android` it will be packaged in the .apk.

https://github.com/phonegap/phonegap-plugin-push/blob/v1.6.x/docs/PAYLOAD.md#sound

**Comment by dtruel** [comment]
Ok.  From what I have found, it is impossible to modify the apk after it is loaded, unfortunately.

**Comment by leizard** [comment]
I use Ionic Push and the location `project_name/platforms/android/res/raw` seem not work :(
