### ISSUE TITLE
[not a bug] when to use push.finish?

### ISSUE THREAD

**Issue by guykatz** [phonegap/phonegap-plugin-push#634]
Hi;
It is not clear to me from the docs if/when I should use push.finish when working on ios.
what is the purpose of this?
I understand the following:
push.on('notification', function (data) {
    //do something 
    push.finish(function () {console.log("finished");});
});
what code can I put in finish that I could not do inside on notification? also, what exactly does finish signal to the IOS itself? or is this just a hook to a callback?
thanks

**Comment by macdonst** [comment]
@guykatz It is documented here:

https://github.com/phonegap/phonegap-plugin-push/blob/v1.6.x/docs/PAYLOAD.md#background-notifications-1

If you are using background notifications you need to tell the OS that you are done with the background processing.
