### ISSUE TITLE
badge shows on app start up before usage

### ISSUE THREAD

**Issue by guykatz** [phonegap/phonegap-plugin-push#635]
Hi;
I am not sure if this is related to the plugin or PGB but I am asking because the phenomenon is related to notifications.
my app icon in ios always shows a badge of 1. no matter if there is a notification or not. even after i uninstall the app and reinstall it again the badge is there even before I open the app for the first time.
is there a cache somewhere that is not deleted when the app is uninstalled?
any ideas?
thanks

### Expected Behaviour
badge is absent 

### Actual Behaviour
badge shows value if 1 as if a notification is there.

#### Steps to Reproduce:
uninstall my PGB app. reinstall it. after install finishes the badges with value 1 is there...

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ios 9.2.0 on ipad air 1

**Comment by hlopezvg** [comment]
If i'm not mistaking you could set the clearBadge=true to solve the problem.

var push = PushNotification.init({
android: {
senderID: "999"
},
ios: {
senderID: "999",
alert: "true",
badge: true,
clearBadge: true
}

**Comment by macdonst** [comment]
@guykatz Apple persists the badge count even when you uninstall/install the app. Set your badge number to 0 before uninstalling.

**Comment by raphagodoi** [comment]
Ok, but how to know if user's delete the app?

**Comment by macdonst** [comment]
@raphagodoi you don't but once the app is been uninstalled for a few days Apple will clean up the saved badge number.

**Comment by danilo-de-oliveira** [comment]
@guykatz  I have the same problem. Has anyone had a solution?
