### ISSUE TITLE
unable to get registration Id (GCM_ID) on marshmallow.

### ISSUE THREAD

**Issue by karan101292** [phonegap/phonegap-plugin-push#637]
#### Android 6.0

working well on android lesser then 6.0

**Comment by macdonst** [comment]
@karan101292 I do use Marshmallow to test this plugin and I can't reproduce. Please give me more information. Apparently it is throwing an error but what error is it? Please look at my creating an issue guide for help on gather logs, etc.

**Comment by macdonst** [comment]
Closing no response.
