### ISSUE TITLE
Clicking in notification in Android does not open App

### ISSUE THREAD

**Issue by psykologist90** [phonegap/phonegap-plugin-push#638]
When the user receives a notification and clicks, the app is never opened and the event is never triggered. When the app is opened the callback is triggered Ok. It only happens in Android, IOS works as expected. Also, the icon is always blank and the led never illuminates, but in IOS the icon is the app icon.

I've tested it in android 6.0.1 and in 5.1.1 with the same results.

The push payload that I use is the next:

    {
    "to":"xxxxxxxxx",
    "data":{
        "action":"requestReceived",
        "referencedDomain":"friend",
        "referencedId":9,
        "notificationId":19
        
    },
    "content-available":true,
    "priority":"high",
    "notification":{
        "title":"Nueva solicitud de amistad",
        "icon":"icon",
        "body":"Laura Ua te ha enviado una solicitud de amistad",
        "badge":"20",
        "sound":"notification",
        "ledColor":["0","0","255","0"]
        
    }   
    }

I've tried updating the plugin to the last version (1.6.x) with the same results

The logcat of the pushplugin only shows data when the app is open and the callback is trigered.

Thank you.

**Comment by macdonst** [comment]
@psykologist90 try this payload instead and let me know if it fixes your problem.

```
{
"to":"xxxxxxxxx",
"data":{
    "action":"requestReceived",
    "referencedDomain":"friend",
    "referencedId":9,
    "notificationId":19
    "title":"Nueva solicitud de amistad",
    "icon":"icon",
    "body":"Laura Ua te ha enviado una solicitud de amistad",
    "badge":"20",
    "sound":"notification",
    "ledColor":["0","0","255","0"],
    "content-available": "1"
    },
"priority":"high",
}
```

**Comment by psykologist90** [comment]
Thank you! It worked perfect!
