### ISSUE TITLE
[not a bug] thanks for this plugin

### ISSUE THREAD

**Issue by guykatz** [phonegap/phonegap-plugin-push#639]
works great, easy interface, nice abstraction of the underlying OS. I have ported form the previously 'promoted' PGB push plugin that does not work on marshmallow and not updated for a while.
thanks.

**Comment by macdonst** [comment]
@guykatz you are welcome. Yup, this is the new way forward. The PGB plugin is deprecated, development is done in this repo.

**Comment by kaynz** [comment]
+1 thanks =)
