### ISSUE TITLE
Device vibrates and shows notification in the tray even in the foreground #android

### ISSUE THREAD

**Issue by markeeftb** [phonegap/phonegap-plugin-push#640]
On Android 5.0.2 while the app is in the foreground, it shows the notification in the status bar and vibrates, while it shouldn't. 

I initialize the app using:

`push = PushNotification.init({
            "android": {"vibrate": "false", "senderID": senderid
            } 
       		});`

Any ideas on how to change that behaviour?

**Comment by markeeftb** [comment]
It seems, that whenever i send 'message' in the push notification payload, it will be always shown no matter the app is in the foreground or background.

**Comment by macdonst** [comment]
@markeeftb what is the payload you send to the device?

**Comment by markeeftb** [comment]
Hi! There you go:

`{  "registration_ids" : [ "xxxx","xxxxx" ], "collapse_key" : "p773128688" , "delay_while_idle" : false , "time_to_live" : 0 , "data": {                 "title" : "John has joined the discussion"               , "message" : "Discussion started"               , "link" : "discuss"            }}`

When I send empty 'message' - the notification doesn't show up in foreground.

**Comment by markeeftb** [comment]
Found the problem. I had some other Push plugin installed as well and it made that happen.
After I've uninstalled it, your plugin does a perfect job as I wanted.

Sorry for taking your precious time!

**Comment by fredgalvao** [comment]
@macdonst, closing.
