### ISSUE TITLE
PushNotification doesn't fire registration event

### ISSUE THREAD

**Issue by ilvalerione** [phonegap/phonegap-plugin-push#643]
### Expected Behaviour
After init raise registration event

### Actual Behaviour
the pluginis not to be signs of life

### Reproduce Scenario (including but not limited to)
```js
var push = PushNotification.init({ 
	    	android: {
	    		senderID: "xxxxxxxxxxx"
	    	},
	    	ios: {
	    		alert: "true", 
	    		badge: "true", 
	    		sound: "true"
	    	}, 
	    	windows: {} 
	    });

	    push.on('registration', function(data) {
			alert("registration - "+JSON.stringify(data));
			// Success -- send deviceToken to server, and store for future use
			$http.post(urlApi+'/notification/register', {registration_id: data.registrationId, platform: ionic.Platform.platform()})
			success(function(data){
				alert("SUCCESS");
			})
			.error(function(err){
				alert("ERROR - "+JSON.stringify(err));
			});
	    });
```

This code doesn't raise any alert()

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
PhoneGap (iOS / Android / Windows)
cli-5.2.0 (3.9.1 / 4.1.1 / 3.8.1)

Smartphone with Android version 5.0

#### Logs taken while reproducing problem
I also using try catch around all this code example but it doesn't fire anythings

**Comment by fredgalvao** [comment]
Can you get the `adb logcat` output when you launch the app?

**Comment by ilvalerione** [comment]
I don't know how do rhis. Can you link me a guide?

**Comment by ilvalerione** [comment]
I don't know how do this. Can you link me a guide?

**Comment by macdonst** [comment]
@ilvalerione http://developer.android.com/tools/help/logcat.html

**Comment by ilvalerione** [comment]
02-24 07:21:11.308: E/GMPM(2629): GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.

Could be usefull?

**Comment by ilvalerione** [comment]
`push.on('error', function(e) {
				alert("ERR - "+JSON.stringify(e));
		    });`

i'm catch error but e={}

And in DDMS console:

[2016-02-24 13:58:18 - ddms] null
java.lang.NullPointerException
	at com.android.ddmlib.Client.read(Client.java:731)
	at com.android.ddmlib.MonitorThread.processClientActivity(MonitorThread.java:311)
	at com.android.ddmlib.MonitorThread.run(MonitorThread.java:263)

[2016-02-24 13:58:18 - ddms] null
java.lang.NullPointerException
	at com.android.ddmlib.Client.read(Client.java:731)
	at com.android.ddmlib.MonitorThread.processClientActivity(MonitorThread.java:311)
	at com.android.ddmlib.MonitorThread.run(MonitorThread.java:263)

[2016-02-24 13:58:18 - ddms] Can't bind to local 8624 for debugger

**Comment by ilvalerione** [comment]
I found ERROR in log cat!!! :)

02-24 08:05:34.248: E/PushPlugin(3453): execute: Got JSON Exception MISSING_INSTANCEID_SERVICE

**Comment by macdonst** [comment]
@ilvalerione you can't do this on a Genymotion emulator as it does not include Google Play Services. You'll have to use a real device or setup a Android emulator using Google API's.

**Comment by macdonst** [comment]
Closing inactivity and using an emulator.
