### ISSUE TITLE
Cannot build with Android anything beyond 1.3.0

### ISSUE THREAD

**Issue by lunchbag** [phonegap/phonegap-plugin-push#644]
I'm trying to update my plugin from 1.3.0 to latest, and I can't get it to build for anything beyond 1.3.0. (to clarify, it builds and works perfectly for 1.3.0), including 1.4.0 and 1.5.0.

I've gotten to the point where I've updated and installed all the latest in the SDK Manager and I've also run  `android update sdk --no-ui --filter "extra"`. Also did a few laptop restarts in between just to make sure.......

I'm running:
Cordova CLI version 6.0.0
Ionic version 1.2.4
Ionic CLI 1.7.14

I've also uninstalled and reinstalled the platforms, both manually and with `ionic state reset`. Honestly feeling like I've traversed the internet a few times trying to find solutions, but nothing is working!

Here's the error message. It's failing with `cordova clean android` and `cordova build android`:

`
Running command: /Users/lunchbag/mobile/hooks/after_prepare/010_add_platform_class.js /Users/lunchbag/mobile
add to body class: platform-android
Running command: /Users/lunchbag/mobile/platforms/android/cordova/build 
ANDROID_HOME=/usr/local/sdk/adt-bundle-mac-x86_64-20140702/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home
Running: /Users/lunchbag/mobile/platforms/android/gradlew cdvBuildDebug -b /Users/lunchbag/mobile/platforms/android/build.gradle -Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-gcm:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/
         file:/usr/local/sdk/adt-bundle-mac-x86_64-20140702/sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
         file:/usr/local/sdk/adt-bundle-mac-x86_64-20140702/sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.941 secs

/Users/lunchbag/mobile/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/lunchbag/mobile/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/lunchbag/mobile/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Users/lunchbag/mobile/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /Users/lunchbag/mobile/platforms/android/cordova/build: Command failed with exit code 1
`

Thanks in advance for any guidance/insights/tips.

**Comment by macdonst** [comment]
@lunchbag Can you do a `which android` to make sure that it is picking up the one in `/usr/local/sdk/adt-bundle-mac-x86_64-20140702`? Just want to make sure that some other build tool didn't install `android` ahead of the one in your SDK. If it is the same root then run `android &` and make sure you have the latest Android Support Library, etc. installed as per https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#compilation

**Comment by lunchbag** [comment]
@macdonst Oh wow. Problem solved. It was pointed to the right android but I was opening the SDK manager via Android Studio. I had everything installed in there. When I ran `android &` it had opened up another SDK manager in which Google Repository wasn't installed... Thanks!

**Comment by macdonst** [comment]
@lunchbag kk, super glad it's resolved. Often the IDE's will install the ADT in a different spot as the command line causing this confusion.
