### ISSUE TITLE
Receive Notifications in background 

### ISSUE THREAD

**Issue by boyfunky** [phonegap/phonegap-plugin-push#649]
### Expected Behaviour
When Notification is sent even when app is in background, should have an event that catches the notification
### Actual Behaviour
Notification is only caught when app is in foreground not in background
### Reproduce Scenario (including but not limited to)
 ```
this tutorial might help to create a simple ionic app https://devdactic.com/android-push-notifications/
var push = new Ionic.Push({
      "onNotification": function(notification) {
        // send notification_read true to server
        console.log("NOTIFICATION RECEIVED")
        alert("SUCCESSFULLY RECEIVED NOTIFICATION");
      },
      "onRegister": function() {

      }
    });
    push.register();
    
push.on('notification', function(notification) {
  console.log("notification received")
})
```

i get an error saying push.on('notification') is not a function when that is replaced to this, nothing fires  and i get same error 

```
var pushPlugin = window.PushPlugin;
pushPlugin. on('notification', function(notification) {
  console.log("notification received")
})
```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0.1
#### Sample Push Data Payload
```
n = Rpush::Gcm::Notification.new
            n.app = Rpush::Gcm::App.find_by_name("partners")
            n.registration_ids = [@user_auth_token.device_token]
            n.data = { state: "case_status_single", count: badge_unread.length + 1, notification_id: n.id }
            n.notification = {
                body:  " Loan Status Changed " ,
                title: 'Partners',
                tag: true
              }
            n.save!

            Rpush.push
```

**Comment by macdonst** [comment]
@boyfunky I'm pretty sure that Ionic.Push uses a deprecated version of the push plugin from https://github.com/phonegap-build/PushPlugin and that is why you are getting the error saying push.on('notification') is not a function.

So your problem is not really a problem with this plugin. 

What is reported when you run `cordova plugins` from your app directory?

**Comment by boyfunky** [comment]
@macdonst  i get this  phonegap-plugin-push 1.5.3 "PushPlugin"

**Comment by macdonst** [comment]
@boyfunky this is more of an Ionic question as I don't believe that the object being returned from `new Ionic.Push()` is actually the same as when you do a `PushNotificaiton.init()`. 

I'll see if @ericb can comment.

**Comment by ericb** [comment]
@boyfunky Background notifications are only available if you send the appropriate data (see the appropriate [push plugin docs](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md) to learn how to do that).

**Comment by macdonst** [comment]
@ericb look at his code in the original post. He's using some mix of Ionic.Push and this plugin.

**Comment by ericb** [comment]
@boyfunky As @macdonst stated, the Ionic.Push object is not the push plugin interface directly -- it is utilized under the hood -- the `onNotification` function you defined in the Ionic.Push instantiation is sufficient to be called when notifications are received.

**Comment by macdonst** [comment]
Thanks for the clarification @ericb.

@boyfunky also, when you go to send your message the format should be:

```
n = Rpush::Gcm::Notification.new
            n.app = Rpush::Gcm::App.find_by_name("partners")
            n.registration_ids = [@user_auth_token.device_token]
            n.data = { state: "case_status_single", count: badge_unread.length + 1,   notification_id: n.id, 
                content-available: "1",
                body:  " Loan Status Changed " ,
                title: 'Partners',
                tag: true
              }
            n.save!

            Rpush.push
```

**Comment by boyfunky** [comment]
@ericb @macdonst Really appreciate the feedback and help rendered but both didtn work. My onNotification event only gets fired when app is in the foreground. even when app is in the background and i click on notification, nothing gets fired. I added the content-available and all but it still didnt work.

**Comment by augusto-jm-amaral** [comment]
I'm having the same problem

**Comment by PanosParalakis** [comment]
I had the same problem but by using the below format on my request it worked! Notifications are caught when app is in either on foreground or wake/start from background. Tested on Android only.

```
 {
 	"data": {
 		"message": "....",
 		 "title": "...",
 		"info": "...",
 		"content-available": "1"
 	},
 	"to": "..."
 }
```
You can also use registrations_ids array instead of to:
```

 {
 	"data": {
 		"message": "....",
 		"title": "...",
 		"info": "...",
 		"content-available": "1"
 	},
 	"registration_ids":[ "id1","id2"]
 }
```

**Comment by augusto-jm-amaral** [comment]
Worked, thank you!!!

**Comment by ssbDeveloper-SG** [comment]
@PanosParalakis 
I tried and onNotification is called  when I try registration_ids array 
but does not work when I use 
**"to": "..."**

This is my payload 
{
        "data": 
	{
        "title": "Test Push",
        "message": "44444",
        "info": "Test",
        "content_available": "1"
 } ,
to" : "GCM_GROUP_TOKEN"
}
Any help please :(
