### ISSUE TITLE
On Android, GCMIntentService.onError() doesn't get passed to the JavaScript "error" event

### ISSUE THREAD

**Issue by T18970237136** [phonegap/phonegap-plugin-push#65]
Hi, this is a follow-up issue to https://github.com/phonegap/phonegap-plugin-push/issues/54.

I'm using the plugin on a android device:
```javascript
var push = PushNotification.init({
	"android": { "senderID": "123456789" },
	"ios": {}, "windows": {}
});

push.on('registration', function (data) {
	alert("Token: " + data.registrationId);
});


push.on('error', function (e) {
	alert("Error: " + e.message);
});
```

When the device sucessfully gets a token for GCM, everything works and the alert is shown.
However when the device cannot get the token, the "error" event on the push object is not raised, so no alert is shown.

When a error occurs, the android logs show this:
```
D/GCMBaseIntentService( 1895): handleRegistration: registrationId = null, error = AUTHENTICATION_FAILED, unregistered = null
D/GCMBaseIntentService( 1895): Registration error: AUTHENTICATION_FAILED
E/PushPlugin_GCMIntentService( 1895): onError - errorId: AUTHENTICATION_FAILED
```

GCMIntentService.onError() is called, but this method only has a logging statement, so the implementation to delegate the error to the javascript push.error event seems to be missing:
```java
    @Override
    public void onError(Context context, String errorId) {
        Log.e(LOG_TAG, "onError - errorId: " + errorId);
    }
```

Thanks!

**Comment by macdonst** [comment]
Fixed in master, will be part of 1.2 release.
