### ISSUE TITLE
Secret Notifications

### ISSUE THREAD

**Issue by sunojvijayan** [phonegap/phonegap-plugin-push#650]
Hi 

It possible to receive push notifications to receive secret data from server and not to show it in the notification center even when the app is not in the background.

Thanks in advance

**Comment by macdonst** [comment]
@sunojvijayan Android instructions are here: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications

iOS are here: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications-1

**Comment by sunojvijayan** [comment]
I have an application the node-gcm code is like this

var message = new gcm.Message({
        collapseKey: 'demo',
        priority: 'high',
        contentAvailable: true,
        delayWhileIdle: false,
        //timeToLive: 3,
        restrictedPackageName: "com.name.pack",
        dryRun: false,
        data: {
            title: request.body.titlename,
            icon: request.body.icon,
            body: request.body.messagetext.slice(0, 150) + "...",
            image: request.body.imageurl,
            url: request.body.url,
            fullmsg: request.body.messagetext,
            "content-available": "1"
        }
    });


It is sending push to my client. And the push works. But what I have to do is capture all push notifications in my client code

push.on('notification', function (data) {
            $scope.promoTitle = data.title;
            $scope.promoImage = data.image;
            $scope.promoDescription = data.fullmsg;
            $scope.promoUrl = data.url;
            $scope.$apply();
            window.location = "#/promotions";
        });


and give a local nitification instead of the default push being showed in the device when the app is closed. Currently my code is not working and it is showing default push in the notification bar when i push, even after adding  "content-available": "1" in my code. 

Please help
