### ISSUE TITLE
Android PhoneGap build fails

### ISSUE THREAD

**Issue by Nett** [phonegap/phonegap-plugin-push#653]
Hello! Your plugin is really cool, and I would like to use it in my application, but I have an issue with apk build.

I added these 2 lines to my config file: 

```
<preference name="android-build-tool" value="gradle" />
<plugin name="phonegap-plugin-push" spec="~1.4.5" source="npm" />
```

When I submit my PhoneGap project to adobe, to build an APK and it fails with message like: "Oh geez. Your build failed. Sorry, but a problem occurred on the build server"

If I remove "android-build-tool" it fails with another message like: "Error - One of your plugins required the gradle android build tool to build - You can fix this here" and the link [http://docs.build.phonegap.com/en_US/support_failed-builds.md.html#gradle_required](url) .

Here is my config.xml
<?xml version='1.0' encoding='utf-8'?>

<widget id="application.validation" version="1.1.0225a val" versionCode="1" xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0">

```
<name>Application</name>

<description>
    Application
</description>

<author email="" href="">
    Application Team
</author>

<feature name="http://api.phonegap.com/1.0/device" />
<preference name="permissions" value="" />
<preference name="orientation" value="default" />
<preference name="target-device" value="universal" />
<preference name="fullscreen" value="false" />
<preference name="webviewbounce" value="true" />
<preference name="prerendered-icon" value="true" />
<preference name="stay-in-webview" value="false" />
<preference name="ios-statusbarstyle" value="black-opaque" />
<preference name="detect-data-types" value="true" />
<preference name="exit-on-suspend" value="false" />
<preference name="show-splash-screen-spinner" value="true" />
<preference name="auto-hide-splash-screen" value="true" />
<preference name="disable-cursor" value="false" />
<preference name="android-minSdkVersion" value="16" />
<preference name="android-installLocation" value="internalOnly" />
<preference name="phonegap-version" value="cli-5.2.0" />
<preference name="android-maxSdkVersion" value="" />
<preference name="android-targetSdkVersion" value="" />
<preference name="KeepRunning" value="true" />
<preference name="splash-screen-duration" value="5000" />
<preference name="ErrorUrl" value="error.html" />
<preference name="LoadingDialog" value="Please wait, the app is loading." />
<preference name="LoadingPageDialog" value="Please wait, the data is loading." />
<preference name="LoadUrlTimeoutValue" value="20000" />
<preference name="AndroidPersistentFileLocation" value="Internal" />

<icon src="icon.png" />
<icon gap:platform="android" gap:qualifier="ldpi" src="res/icon/android/icon-36-ldpi.png" />
<icon gap:platform="android" gap:qualifier="mdpi" src="res/icon/android/icon-48-mdpi.png" />
<icon gap:platform="android" gap:qualifier="hdpi" src="res/icon/android/icon-72-hdpi.png" />
<icon gap:platform="android" gap:qualifier="xhdpi" src="res/icon/android/icon-96-xhdpi.png" />
<icon gap:platform="android" gap:qualifier="xxhdpi" src="res/icon/android/icon-144-xxhdpi.png" />

<gap:splash gap:platform="android" gap:qualifier="port-ldpi" src="res/screen/android/screen-ldpi-portrait.png" />
<gap:splash gap:platform="android" gap:qualifier="port-mdpi" src="res/screen/android/screen-mdpi-portrait.png" />
<gap:splash gap:platform="android" gap:qualifier="port-hdpi" src="res/screen/android/screen-hdpi-portrait.png" />
<gap:splash gap:platform="android" gap:qualifier="port-xhdpi" src="res/screen/android/screen-xhdpi-portrait.png" />
<gap:splash gap:platform="android" gap:qualifier="port-xhdpi" src="res/screen/android/screen-xhdpi-n7-portrait.png" />
<gap:splash gap:platform="android" gap:qualifier="port-xxhdpi" src="res/screen/android/screen-xxhdpi-portrait.png" />
<gap:splash gap:platform="android" gap:qualifier="port-xxhdpi" src="res/screen/android/screen-xxhdpi-n7-portrait.png" />
<gap:splash gap:platform="android" gap:qualifier="land-xxhdpi" src="res/screen/android/screen-xxhdpi-n7-landscape.png" width="1920" height="1200" />
<gap:splash gap:platform="android" gap:qualifier="land-xxhdpi" src="res/screen/android/screen-xxhdpi-landscape.png" width="1920" height="1080" />
<gap:splash gap:platform="android" gap:qualifier="land-xhdpi" src="res/screen/android/screen-xhdpi-n7-landscape.png" width="1280" height="800" />
<gap:splash gap:platform="android" gap:qualifier="land-xhdpi" src="res/screen/android/screen-xhdpi-landscape.png" width="1280" height="720" />
<gap:splash gap:platform="android" gap:qualifier="land-hdpi" src="res/screen/android/screen-hdpi-landscape.png" width ="800" height="480" />
<gap:splash gap:platform="android" gap:qualifier="land-mdpi" src="res/screen/android/screen-mdpi-landscape.png" width="480" height="320" />
<gap:splash gap:platform="android" gap:qualifier="land-ldpi" src="res/screen/android/screen-ldpi-landscape.png" width="320" height="200" />
<gap:splash gap:platform="ios" height="1136" src="res/screen/ios/screen-iphone-portrait-568h-2x.png" width="640" />

<access origin="*" />
<gap:platform name="android" />
<feature name="http://api.phonegap.com/1.0/camera" />
<feature name="http://api.phonegap.com/1.0/file" />
<feature name="http://api.phonegap.com/1.0/geolocation" />
<feature name="http://api.phonegap.com/1.0/media" />
<feature name="http://api.phonegap.com/1.0/notification" />
<gap:plugin name="cordova-plugin-console" source="npm" />
<gap:plugin name="cordova-plugin-media-capture" source="npm" />
<gap:plugin name="cordova-plugin-device" source="npm" />
<gap:plugin name="cordova-plugin-file" source="npm" />
<gap:plugin name="cordova-plugin-file-transfer" source="npm" />
<gap:plugin name="cordova-plugin-geolocation" source="npm" />
<gap:plugin name="cordova-plugin-media" source="npm" />
<gap:plugin name="cordova-plugin-network-information" source="npm" />
<gap:plugin name="cordova-plugin-dialogs" source="npm" />
<gap:plugin name="cordova-plugin-splashscreen" source="npm" />
<gap:plugin name="com.synconset.imagepicker" source="pgb" />
<gap:plugin name="cordova-plugin-x-toast" source="npm" />
<gap:plugin name="cordova-plugin-whitelist" source="npm" />
<gap:plugin name="cordova-plugin-inappbrowser" source="npm" />
<plugin name="cordova-plugin-mauron85-background-geolocation-phonegapbuild" spec="0.7.3" />
<plugin name="de.appplant.cordova.plugin.background-mode" spec="0.6.4" source="pgb" />
<plugin name="phonegap-plugin-push" spec="~1.4.5" source="npm" />
```

</widget>

Could you please help me to solve this issue.
Thank you.

**Comment by macdonst** [comment]
@Nett please add the two lines to your config file. You want to make sure you are building with Gradle. Then please post the build log so I can see what went wrong.

**Comment by Nett** [comment]
Thanks for quick reply @macdonst!
Here you are log information:

Build Date: 2016-02-26 17:05:42 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Installing "com.synconset.imagepicker@1.0.4" for android
Installing "org.apache.cordova.device@0.2.12" for android
Installing "de.appplant.cordova.plugin.background-mode@0.6.4" for android
Fetching plugin "cordova-plugin-console" via npm
Installing "cordova-plugin-console@1.0.2" for android
Fetching plugin "cordova-plugin-media-capture" via npm
Installing "cordova-plugin-media-capture@1.2.0" for android
Fetching plugin "cordova-plugin-file" via npm
Installing "cordova-plugin-file@4.1.1" for android

The Android Persistent storage location now defaults to "Internal". Please check this plugins README to see if you application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />"

to config.xml in order for the application to find previously stored files.
Fetching plugin "cordova-plugin-device" via npm
cordova-plugin-device" will not install due to "/project/cordova/plugins/org.apache.cordova.device" being installed.
Plugin "org.apache.cordova.device" already installed on android.
Plugin "cordova-plugin-file" already installed on android.
Fetching plugin "cordova-plugin-file-transfer" via npm
Installing "cordova-plugin-file-transfer@1.5.0" for android
Fetching plugin "cordova-plugin-geolocation" via npm
Installing "cordova-plugin-geolocation@2.1.0" for android
Fetching plugin "cordova-plugin-media" via npm
Installing "cordova-plugin-media@2.2.0" for android
Fetching plugin "cordova-plugin-network-information" via npm
Installing "cordova-plugin-network-information@1.2.0" for android
Fetching plugin "cordova-plugin-dialogs" via npm
Installing "cordova-plugin-dialogs@1.2.0" for android
Fetching plugin "cordova-plugin-splashscreen" via npm
Installing "cordova-plugin-splashscreen@3.2.0" for android
Fetching plugin "cordova-plugin-x-toast" via npm
Installing "cordova-plugin-x-toast@2.4.2" for android
Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist@1.2.1" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
Fetching plugin "cordova-plugin-inappbrowser" via npm
Installing "cordova-plugin-inappbrowser@1.3.0" for android
Fetching plugin "cordova-plugin-mauron85-background-geolocation-phonegapbuild@0.7.3" via npm
Installing "cordova-plugin-mauron85-background-geolocation-phonegapbuild@0.7.3" for android
Fetching plugin "cordova-plugin-googleplayservices" via npm
Installing "cordova-plugin-googleplayservices@19.0.3" for android
Fetching plugin "phonegap-plugin-push@~1.4.5" via npm
Installing "phonegap-plugin-push@1.4.5" for android
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Running: /project/gradlew cdvBuildDebug -b /project/build.gradle -Dorg.gradle.daemon=true
:preBuild
:compileDebugNdk
:preDebugBuild
:checkDebugManifest
:preReleaseBuild
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar
:CordovaLib:compileDebugNdk
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar
:CordovaLib:compileReleaseNdk
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease
:prepareComAndroidSupportSupportV132310Library
:prepareComAndroidSupportSupportV42310Library
:prepareComGoogleAndroidGmsPlayServicesBase840Library
:prepareComGoogleAndroidGmsPlayServicesBasement840Library
:prepareComGoogleAndroidGmsPlayServicesGcm840Library
:prepareComGoogleAndroidGmsPlayServicesMeasurement840Library
:prepareProjectCordovaLibUnspecifiedDebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest/project/AndroidManifest.xml:24:13 Error:
	Missing one of the key attributes 'action#name,category#name' on element intent-filter at AndroidManifest.xml:24:13
/project/AndroidManifest.xml:0:0 Error:
	Validation failed, exiting
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.568 secs

/project/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /project/gradlew with args: cdvBuildDebug,-b,/project/build.gradle,-Dorg.gradle.daemon=true

Thank you again!

**Comment by macdonst** [comment]
@Nett please try the following, remove the preferences:

```
<preference name="permissions" value="" />
<preference name="android-maxSdkVersion" value="" />
<preference name="android-targetSdkVersion" value="" />
```

Not sure that those empty values will do to the build service. The actual error you are getting is your AndroidManifest.xml file is not in the right format. 

If the above doesn't work please try removing `spec="~1.4.5"` from `<plugin name="phonegap-plugin-push" spec="~1.4.5" source="npm" />` so it uses the latest plugin version.

**Comment by Nett** [comment]
@macdonst thanks for your response!

I made all changes you described above, but it didn't work. The same error on adobe side.

Do you have any other suggestions?

Thank you.

**Comment by macdonst** [comment]
@Nett try bumping the spec on <plugin name="cordova-plugin-mauron85-background-geolocation-phonegapbuild" spec="0.7.3" /> to 0.9.4. The older version of that plugin does not use Gradle and relies on another plugin that can screw up building.

**Comment by Nett** [comment]
@macdonst, I'll try this.

Actually the build fails when I try to use < plugin name="cordova-plugin-mauron85-background-geolocation-phonegapbuild" spec="0.7.3" /> together with your plugin.
I also wrote to geolocation plugin developer, but there is no answer for now.

Thank you!

**Comment by macdonst** [comment]
@Nett yeah, that is what I tried to say in my last comment but I forgot to put quotes around the XML. If you start using version 0.9.4 of that plugin it should work.

**Comment by Nett** [comment]
Thank you much for your help @macdonst, but I still cannot make it work.

**Comment by macdonst** [comment]
@Nett once you made the switch to using version 0.9.4 of that plugin then what does your build log look like?

**Comment by Nett** [comment]
@macdonst, here is latest failed build log

Build Date: 2016-03-01 16:52:04 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Installing "com.synconset.imagepicker@1.0.4" for android
Installing "org.apache.cordova.device@0.2.12" for android
Installing "de.appplant.cordova.plugin.background-mode@0.6.4" for android
Fetching plugin "cordova-plugin-console" via npm
Installing "cordova-plugin-console@1.0.2" for android
Fetching plugin "cordova-plugin-media-capture" via npm
Installing "cordova-plugin-media-capture@1.2.0" for android
Fetching plugin "cordova-plugin-file" via npm
Installing "cordova-plugin-file@4.1.1" for android

The Android Persistent storage location now defaults to "Internal". Please check this plugins README to see if you application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />"

to config.xml in order for the application to find previously stored files.
Fetching plugin "cordova-plugin-device" via npm
cordova-plugin-device" will not install due to "/project/cordova/plugins/org.apache.cordova.device" being installed.
Plugin "org.apache.cordova.device" already installed on android.
Plugin "cordova-plugin-file" already installed on android.
Fetching plugin "cordova-plugin-file-transfer" via npm
Installing "cordova-plugin-file-transfer@1.5.0" for android
Fetching plugin "cordova-plugin-geolocation" via npm
Installing "cordova-plugin-geolocation@2.1.0" for android
Fetching plugin "cordova-plugin-media" via npm
Installing "cordova-plugin-media@2.2.0" for android
Fetching plugin "cordova-plugin-network-information" via npm
Installing "cordova-plugin-network-information@1.2.0" for android
Fetching plugin "cordova-plugin-dialogs" via npm
Installing "cordova-plugin-dialogs@1.2.0" for android
Fetching plugin "cordova-plugin-splashscreen" via npm
Installing "cordova-plugin-splashscreen@3.2.0" for android
Fetching plugin "cordova-plugin-x-toast" via npm
Installing "cordova-plugin-x-toast@2.4.2" for android
Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist@1.2.1" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
Fetching plugin "cordova-plugin-inappbrowser" via npm
Installing "cordova-plugin-inappbrowser@1.3.0" for android
Fetching plugin "cordova-plugin-mauron85-background-geolocation-phonegapbuild@0.9.4" via npm
Installing "cordova-plugin-mauron85-background-geolocation-phonegapbuild@0.9.4" for android
Fetching plugin "cordova-plugin-googleplayservices" via npm
Installing "cordova-plugin-googleplayservices@19.0.3" for android
Fetching plugin "phonegap-plugin-push" via npm
Installing "phonegap-plugin-push@1.5.3" for android
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Running: /project/gradlew cdvBuildDebug -b /project/build.gradle -Dorg.gradle.daemon=true
:preBuild
:compileDebugNdk
:preDebugBuild
:checkDebugManifest
:preReleaseBuild
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar
:CordovaLib:compileDebugNdk
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar
:CordovaLib:compileReleaseNdk
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease
:prepareComAndroidSupportSupportV132310Library
:prepareComAndroidSupportSupportV42310Library
:prepareComGoogleAndroidGmsPlayServicesBase840Library
:prepareComGoogleAndroidGmsPlayServicesBasement840Library
:prepareComGoogleAndroidGmsPlayServicesGcm840Library
:prepareComGoogleAndroidGmsPlayServicesLocation840Library
:prepareComGoogleAndroidGmsPlayServicesMaps840Library
:prepareComGoogleAndroidGmsPlayServicesMeasurement840Library
:prepareProjectCordovaLibUnspecifiedDebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest/project/AndroidManifest.xml:24:13 Error:
	Missing one of the key attributes 'action#name,category#name' on element intent-filter at AndroidManifest.xml:24:13
/project/AndroidManifest.xml:0:0 Error:
	Validation failed, exiting
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.48 secs

/project/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /project/gradlew with args: cdvBuildDebug,-b,/project/build.gradle,-Dorg.gradle.daemon=true


I'm really thankful for your help! And thank you for your time!

**Comment by macdonst** [comment]
the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
