### ISSUE TITLE
Not registering, trying on iOS

### ISSUE THREAD

**Issue by federicoitollo** [phonegap/phonegap-plugin-push#654]
I'm trying this plugin, previous version worked perfectly, but can't get device token on my iPhone with this version. It seems it's just not firing the registration and I think the error is in my js...
Can anyone check it? This is the full code (sorry I really don't understand how to use the code tag here):

`	var app = {
`    // Application Constructor
`    initialize: function() {
`        this.bindEvents();
`    },
`    // Bind Event Listeners
`    //
`    // Bind any events that are required on startup. Common events are:
`    // 'load', 'deviceready', 'offline', and 'online'.
`    bindEvents: function() {
`        document.addEventListener('deviceready', this.onDeviceReady, false);
`     },
`
`	onDeviceReady: function() {
`
`	var push = PushNotification.init({
`            "android": {
`                "senderID": "1234567890"
`            },
`            "ios": { "alert": "true", "badge": "true", "sound": "true" },
`            "windows": {}
`        });
`	
`
`        push.on('registration', function (data) {
`            console.log("registration event");
`            //document.getElementById("regId").innerHTML = data.registrationId;
`            alert(data.registrationId)
`            console.log(JSON.stringify(data));
`        });
`
`        push.on('notification', function (data) {
`            console.log("notification event");
`            console.log(JSON.stringify(data));
`            var cards = document.getElementById("cards");
`            var card = '<div class="row">' +
`                  '<div class="col s12 m6">' +
`                  '  <div class="card darken-1">' +
`                  '    <div class="card-content black-text">' +
`                  '      <span class="card-title black-text">' + data.title + '</span>' +
`                  '      <p>' + data.message + '</p>' +
`                  '    </div>' +
`                  '  </div>' +
`                  ' </div>' +
`                  '</div>';
`            cards.innerHTML += card;
`
`            push.finish(function () {
`                console.log('finish successfully called');
`            });
`        });
`
`        push.on('error', function (e) {
`            console.log("push error");
`        });
`
`
`       //  var pushNotification = window.plugins.PushNotification;
`       push.registerDevice({ alert: true, badge: true, sound: true }, function (status) {
`           app.myLog.value += JSON.stringify(['registerDevice status: ', status]) + "\n";
`           app.storeToken(status.deviceToken);
`          alert(status.deviceToken)
`       });
`	
`	}, // end ondeviceready function
`	
`    };
`
`   app.initialize();`

By now I didn't create certificates, etc. but they're not required to get just the device token, right?
I just want an alert with the token, nothing more for the moment.
I add iOS platform, run the project in Xcode and build and run it on my device.

**Comment by federicoitollo** [comment]
Ok it seems I fixed this thanks to another answer in the issues. Here's what I did if can help anyone else:

created my app as usual with
`cordova create test com.example.test test`

added the plugin
`cordova plugin add phonegap-plugin-push`

copy and paste the example here in the examples into the onDeviceReady function.

added the platform
`cordova platform add ios`

now go in "your_app_folder/platforms/ios/www"
there should be a file named "cordova_plugins.js" and a folder named "plugins"
In my case those files were missing!
Go in "your_app_folder/platforms/ios/platform_www" you should find the file and the folder above.
Just copy and paste them in "your_app_folder/platforms/ios/www".

That's it... Now when I run the app on my device fires the registration.
Still have to try receiving a push notification but I hope there won't be any problems.

I paste the index.js file for anyone who's still having troubles: I just added an alert in the registration to show me the device token for testing only of course.
I'm sorry but still having problems with the code tag on here... 

`
	var app = {
		initialize: function() {
		this.bindEvents();
	},
	bindEvents: function() {
		document.addEventListener('deviceready', this.onDeviceReady, false);
	},
	onDeviceReady: function() {
		app.receivedEvent('deviceready');
		
		var push = PushNotification.init({
		    android: {
	        senderID: "12345679"
	    	},
	    ios: {
	        alert: "true",
	        badge: "true",
	        sound: "true"
	    	},
	    windows: {}
		});

		push.on('registration', function(data) {
	    alert(data.registrationId);
		});

		push.on('notification', function(data) {
	    // data.message,
	    // data.title,
	    // data.count,
	    // data.sound,
	    // data.image,
	    // data.additionalData
		});

		push.on('error', function(e) {
	    // e.message
		});

    }, // fine funzione onDeviceReady
    // Update DOM on a Received Event
     receivedEvent: function(id) {
        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');

        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');

        console.log('Received Event: ' + id);
    }
}; // fine var app

app.initialize(); 
`

**Comment by macdonst** [comment]
@federicoitollo if you want to paste in a bunch of code follow these rules:

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

You should figure out why those files aren't copying as it seems like something is wrong with your cordova setup. Perhaps upgrade to latest CLI?
