### ISSUE TITLE
clearNotifications on Android should clear only push plugin notifications

### ISSUE THREAD

**Issue by mradosta** [phonegap/phonegap-plugin-push#655]
### Expected Behaviour
On app pause to clear notifications only created by the push plugin

### Actual Behaviour
Clear all notifications (even the ones created by other plugins or by the app)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ANY

#### Sample Push Data Payload
Not necessary

#### Sample Code that illustrates the problem
    var pushNotification = PushNotification.init(
      {
        "android": {"senderID": "my-id"}
      }
    );

#### Sample Code that partially fixes the problem
    var pushNotification = PushNotification.init(
      {
        "android": {"clearNotifications": "false", "senderID": "my-id"}
      }
    );

#### Logs taken while reproducing problem

**Comment by macdonst** [comment]
@mradosta sorry the methods to cancel the notifications for iOS and Android cancel all the notifications created by the app. There is no way to specify only the notifications created by this plugin.
