### ISSUE TITLE
Fire push.on('notification', callback) if the App is in Background

### ISSUE THREAD

**Issue by martinr77** [phonegap/phonegap-plugin-push#657]
### Expected Behaviour
I try to send a Ajax Call if some notifications comes in:

     push.on('notification', function(data) {
     var count = data.count;
	update_count(count, user);
       });

      function update_count(count, user) {
     $.ajax({
    url: site_url + "/?apikey=XXX&email=" + user + "&count=" + count + '&callback=?',
    type: "GET",
    dataType: 'json',
    success: function(data){
    }
      })
     }

### Actual Behaviour

I'm able to set the correct badge with ajax call when the App runs in Foreground but not if the App is closed. 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

IOS 9.2.1

#### Sample Push Data Payload

My PHP script looks like this:

                                       // Create the payload body
					$body['aps'] = array(
						'alert' => $message,
						'sound' => "www/sound.mp3",
						'content-available' => 1,
						'badge' => $badge
						);

#### Logs taken while reproducing problem

**Comment by gdelavald** [comment]
Hello,
this brings me to an older issue I was having, in order to debug it properly, can you please try and add a message field with any content? 
Previous versions of this plugin used to only show a notification if the message content wasn't empty or null.

**Comment by macdonst** [comment]
@martinr77 Can you check to make sure your app is running your `notification` callback in the background? Inspect the app and put it in the background then send your push. Perhaps put a console.log to make it easier to see it is being run.

Also, when you setting a background notification on iOS you'll need to add the finish method to your call back or the OS will get upset. See the example in:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications-1

**Comment by martinr77** [comment]
Thanks for the answers. It works if the app is just in background-mode (if i open the app and click on the home button. then the app is "open" but another app is in foreground for example). I mean if i close it properly completely. Is the notification callback working in this case?

**Comment by macdonst** [comment]
@martinr77 here is an excerpt from the iOS docs at https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/index.html#//apple_ref/occ/intfm/UIApplicationDelegate/application:didReceiveRemoteNotification:fetchCompletionHandler:

```
Use this method to process incoming remote notifications for your app. Unlike the application:didReceiveRemoteNotification: method, which is called only when your app is running in the foreground, the system calls this method when your app is running in the foreground or background. In addition, if you enabled the remote notifications background mode, the system launches your app (or wakes it from the suspended state) and puts it in the background state when a remote notification arrives. However, the system does not automatically launch your app if the user has force-quit it. In that situation, the user must relaunch your app or restart the device before the system attempts to launch your app automatically again.
```

So if the user does a force-quit on your app the `on('notification')` handler will not be called until the user clicks on the notification. Does this answer your question?

**Comment by martinr77** [comment]
Hi, thanks for the detailed answer. I solved it now on another way with controling the badges-count only on server side. then I can delete or change the count if the user is starting the app. Thanks for your help :-)
P.S.: I am happy when android gets badges once that is possible ;-)
