### ISSUE TITLE
on("registration" is not getting called...

### ISSUE THREAD

**Issue by joshuairl** [phonegap/phonegap-plugin-push#66]
It does say it registered successfully in console but the event isn't triggering for some reason?
Any ideas?

**Comment by macdonst** [comment]
Little short on details here @joshuairl. What platform, platform version, plugin version? Do you have a gist of the code you are using?

**Comment by joshuairl** [comment]
So sorry! haha
Was in the middle of the night and my brain was fried.

iOS 9 beta(probably the cause, now that I'm awake)
Latest version of cordova and plugin.

Sorry!

**Comment by macdonst** [comment]
@joshuairl oh okay, well the plan is to support iOS 9 when it is released. Not sure I'll get a chance to play with the beta this month though.

**Comment by joshuairl** [comment]
okay, somehow I got past the registration issue but it's not calling my 'notification' callback.
```
2015-08-17 12:01:00.330 MyApp[764:360640] didReceiveNotification
2015-08-17 12:01:00.765 MyApp[764:360640] active
2015-08-17 12:01:00.769 MyApp[764:360640] Notification received
2015-08-17 12:01:00.769 MyApp[764:360640] Push Plugin key: alert
2015-08-17 12:01:00.769 MyApp[764:360640] Push Plugin key: sound
```

Why would it console.log `didReceiveNotification` and `Notification received` but not trigger the 'notification' event for me to tie into?
Seems odd to me...

**Comment by macdonst** [comment]
@joshuairl what version of the iOS beta are you using and what version of cordova-ios?

**Comment by joshuairl** [comment]
Got it working, Sadly I'm not sure what I did to fix it.
I guess let's just leave this alone for now... :-/
Sorry guys!

**Comment by macdonst** [comment]
@joshuairl No problem, I'm going to close this issue for now. If you re-experience problems just re-open it.
