### ISSUE TITLE
Android - custom notification icon not showing unless AndroidManifest.xml was edited

### ISSUE THREAD

**Issue by parkotron** [phonegap/phonegap-plugin-push#662]
I'm not entirely sure this is a bug report, I don't know enough to know what is expected / should be expected. It may well be caused by other factors (I am using Ionic but had added a fresh Android platform a number of times while trying various combinations of possible factors). Apologies if this is entirely too vague to be of use.

### Expected Behaviour

using the config: 
```
var config = {
	android: {
		senderID: ...,
		vibrate: false,
		alert: true,
		sound: true,
		badge: true,
		icon: 'logo'
	},
	ios: {
		...
	},
	windows: {}
};
```

should show the icon saved in /res/drawable/logo.png when a push message is received and the app is in the background

### Actual Behaviour
The default app icon (in this case it was just a white square because of the design of the logo) was shown.
In the end I solved the problem after a day of trying to test every combination of possible issues by editing AndroidManifest.xml from

`<application android:hardwareAccelerated="true" android:icon="@drawable/icon" android:label="@string/app_name" android:supportsRtl="true">`

to 

`<application android:hardwareAccelerated="true" android:icon="@drawable/logo" android:label="@string/app_name" android:supportsRtl="true">`

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1

#### Logs taken while reproducing problem

**Comment by macdonst** [comment]
@parkotron can you attach the logo.png you are using? Also, when you are reproducing issue run `adb logcat | grep PushPlugin` and we should get some idea as to why it isn't picking up the icon.

**Comment by parkotron** [comment]
Sure, the logo is below

![ic_stat_push](https://cloud.githubusercontent.com/assets/640831/13433679/d04fd55a-dfca-11e5-84eb-89f8b095fe0d.png)

logcat is

V/PushPlugin(27759): execute: action=init
V/PushPlugin(27759): execute: data=[{"android":{"senderID":"397105627974","vibrate":false,"alert":true,"sound":true,"badge":true,"icon":"logo"},"ios":{"senderID":"397105627974","badge":true,"sound":true,"alert":true,"gcmSandbox":"true"},"windows":{}}]
V/PushPlugin(27759): execute: jo={"senderID":"...","vibrate":false,"alert":true,"sound":true,"badge":true,"icon":"logo"}
V/PushPlugin(27759): execute: senderID=...
V/PushPlugin(27759): onRegistered: {"registrationId":"..."}
D/PushPlugin(27759): no iconColor option

**Comment by macdonst** [comment]
@parkotron well the icon looks good and the logs don't say it failed to find the value on setup. What do the logs look like when you receive a push?

**Comment by macdonst** [comment]
@parkotron did you get this resolved? Re-open if not and you have some new information.
