### ISSUE TITLE
How to add Badges for Android with phonegap-plugin-push Plugin? 

### ISSUE THREAD

**Issue by martinr77** [phonegap/phonegap-plugin-push#663]
Whats the difference between phonegap-plugin-push and mp-phonegap-plugin-push ? 

https://github.com/phonegap/phonegap-... 

https://github.com/Code1Tech/phonegap... 

The first is without badges support for android and the second is with badges? 

For installing both have the same name: phonegap-plugin-push 

Very confusing for me. In addition I want to know how I could implement Badges for android at the mp-phonegap-plugin-push Plugin. It is said "added support for Android icon badge number." but I cannot find a explanation. 

Thanks for your help :-) 

Martin

**Comment by macdonst** [comment]
@martinr77 the plugin by Code1Tech is a fork of this one it has badge support but it is behind this plugin in many features and bug fixes. Currently this plugin does not support adding badges on Android as it is a non standard feature. Some launchers support it and some do not. There is actually a PR to add this functionality #624 but I'm worried about adding it into this plugin as I'm sure lots of problems will arise and then I'll be stuck supporting it for a long time.

**Comment by martinr77** [comment]
Okay thanks a lot for your answer.
