### ISSUE TITLE
Push notification register APN to GCM Problem

### ISSUE THREAD

**Issue by shepax** [phonegap/phonegap-plugin-push#665]
I have some problem with IOS push notification using GCM as midleware for the push. 

The plugin Is not doing the registration proces of the apn key with the gcm. i'm getting a gcm tokem but no luck at all with de apn device.tokem.

I been trying to run this for a week, i want to know if this feature is implemented o not? 

and if is not is there a way to do it with what you have now?

the plugin is not doing this work..

**Logic works as follows**

1. We request device token from apns as usual.
2. Then we send that token to gcm service with provided api.
3. Then gcm sends back a another token.
4. We send that token to app server.
5. App server can send notifications using that token.

Sorry for the bad english and if this is not the place to ask this.

**Comment by macdonst** [comment]
@shepax are you using the senderId and gcmSandbox parameter in the ios init options? Because what you describe the plugin should do for you.

**Comment by shepax** [comment]
Yes i'm doing that but with no luck at all. The apn is not sending the code back..

**Comment by macdonst** [comment]
@shepax correct, when sending to GCM on iOS you need to use the `notification` object but when sending to GCM on Android you need to use the `data` object.

**Comment by ef33zy** [comment]
@shepax I am having the same issue with the `"style", "summaryText" `etc for Android. Were you able to find a resolution? @
