### ISSUE TITLE
How to get payload's extra arguments iOS

### ISSUE THREAD

**Issue by acarolinee** [phonegap/phonegap-plugin-push#666]
Hi, i have a question.

I need to get some extra arguments for iOS.

Payload that i send from my c# server, looks like this:

```
{
      "aps":{
          "alert":"Esto es una prueba de notificaciones",
          "badge":1,
          "sound":"default"
      },
      "idcuenta":"HOLA",                                 
      "fecha":"02-03-2016 12:09:09"
}
```

**The extra arguments are: idcuenta and fecha.**
but when i got the console.log in:

```
push.on('notification', function(data) {
    console.log('idcuenta:' + data.idCuenta);
}
```

Says: **idcuenta:undefined**

I don't know how to get those values. Can you help me please, really appreciate.

PD: Apologize for the misunderstanding, my native language is not english.

**Comment by macdonst** [comment]
@acarolinee it should be at `data.additionalData.idcuenta`. In your notification handler you an see the structure of the returned data by doing:

```
push.on('notification', function(data) {
    console.log(JSON.stringify(data.idCuenta));
}
```

**Comment by acarolinee** [comment]
Oh, it works! I used `data.additionalData.idcuenta` as you said.

Thank you so much
