### ISSUE TITLE
iOS sound not found [edited with new debug info]

### ISSUE THREAD

**Issue by dtruel** [phonegap/phonegap-plugin-push#667]
Hello,

I have downloaded a custom sound to Library/Sounds as per this: 

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/IPhoneOSClientImp.html#//apple_ref/doc/uid/TP40008194-CH103-SW6

It works on an iPhone 6s!  But on an iPhone 4s with iOS 8, and on an iPhone 6 it doesn't work.  I have looked into the sandbox on the 4s, and I see the exact same files in Library/Sounds.  One works, the other just plays the default sound.  I'm about to pull my hair out trying to figure out what's wrong.  Does anybody have any ideas?

I found this error on the 4s log (not console, the one in xcode):

```
Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.
```

Could this be an error from the plugin?

**Comment by macdonst** [comment]
@dtruel well that has nothing to do with the sound but I'm betting you are using a background notification without calling finish: 

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications-1

**Comment by dtruel** [comment]
I tried that and still got the error.  However, I commented out the content-available in the gcm push message and that fixed it.  Thanks for the help!
