### ISSUE TITLE
emoji support

### ISSUE THREAD

**Issue by superainovacoes** [phonegap/phonegap-plugin-push#668]
How to send push with emojis?

**Comment by macdonst** [comment]
@superainovacoes you need to send the unicode value. You can look them up at:

http://apps.timwhitlock.info/emoji/tables/unicode

**Comment by superainovacoes** [comment]
i have just checked and it did not work.

i am using node-gcm module, the string is "teste U+1F601 será? U+1F602 aahaha"

when i receive the push the string above is identical.

**Comment by macdonst** [comment]
@superainovacoes oh sorry, use this table instead:

http://www.easyapns.com/category/just-for-fun

**Comment by superainovacoes** [comment]
@macdonst no success :cry: i already have tried all the emoji types/formats

do you use emoji on notifications? are you using node-gcm?

**Comment by superainovacoes** [comment]
@macdonst does your test works?

**Comment by macdonst** [comment]
@superainovacoes take the unicode value like `U+1F601` and translate it to a HTML entity code like: `&#x1f602;`. This is working for me.

**Comment by superainovacoes** [comment]
Thanks it works.
