### ISSUE TITLE
Application does not show up in iOS notifications center anymore

### ISSUE THREAD

**Issue by pitAlex** [phonegap/phonegap-plugin-push#669]
Hi,

This issue started several days after upgrading to cordova ios 4.0.0. The application stopped showing up in notifications center, until then everything worked. Now even with new provision profiles and downgrade to 3.9.2 it still refuses show up there.

**Comment by Oliv** [comment]
Hello, 
did you try to call an .init() in the app to trigger the user prompt ? 
Until the user doesn't accept the notifications, it doesn't show in notification center.

Regards, Olivier

**Comment by pitAlex** [comment]
Wow I feel stupid...what I was doing is calling init in hasPermisions. Thank you for making me see my mistake.

**Comment by Oliv** [comment]
You're welcome :)
