### ISSUE TITLE
Pushes being deleted from notification bar when cold start

### ISSUE THREAD

**Issue by franciswagner** [phonegap/phonegap-plugin-push#67]
I am sending 3 pushes with different notId and when my app is in foreground it receives all 3 pushes, but when it is running in background or it is closed, I receive the 3 pushes on the notification bar, but when I click one of the pushes it gets the app opened and shows the message from the push, but the other 2 messages disappear from the notification bar.

**Comment by macdonst** [comment]
@franciswagner on the init method you can now pass `clearNotifications: false` to prevent the other notifications from being cleared. See the README.
