### ISSUE TITLE
Notifications that only contain data without the notification object won't trigger when the app is in the background

### ISSUE THREAD

**Issue by ManuelOlvera** [phonegap/phonegap-plugin-push#670]
According to GCM it should be possible to send a notification that only contains the data object with a bunch of key/value pairs which should trigger the callback in the notification event without showing a notification in the status bar.

This works fine when the app is in the foreground but doesn't when the app is in the background

Tested in Android 6.0.1 and 5.1.1

This wouldn't work when the app is in the background:
{
   "to" : "bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...",
   "data" : {
     "Nick" : "Mario",
     "body" : "great match!",
     "Room" : "PortugalVSDenmark"
   },
 }

This does work when the app is in the background:
 {
    "to" : "APA91bHun4MxP5egoKMwt2KZFBaFUH-1RYqx...",
    "notification" : {
      "body" : "great match!",
      "title" : "Portugal vs. Denmark",
      "icon" : "myicon"
    },
    "data" : {
      "Nick" : "Mario",
      "Room" : "PortugalVSDenmark"
    }
  }

**Comment by macdonst** [comment]
@ManuelOlvera if you want the `on('notificaiton')` event handler to be called when the app is in the background you must set the correct property:

```
{
"to" : "bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...",
"data" : {
"Nick" : "Mario",
"body" : "great match!",
"Room" : "PortugalVSDenmark",
"content-available": "1"
},
}
```

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications

**Comment by varunreddy212** [comment]
Hi I am having the same issue.
I am using "content-available":"1" in data however when I destroy the app I am getting a a push notification with the text specified in the message but it is not executing the JS in the notification callback until I reopen the app.

Any help would be appreciated

Thanks

Varun

**Comment by macdonst** [comment]
@varunreddy212 sorry, when you say destroy the app do you mean "force close"? If so that would be expected behaviour as the JavaScript callback is not loaded in memory.

**Comment by varunreddy212** [comment]
Hi Simon,
  I click on the recent apps button and close the app from there.
Is there a way for me to reload the callback or app back into memory on
close or phone startup.

Thanks

Varun

**Comment by macdonst** [comment]
@varunreddy212 you are talking about issue #158 which I don't have a fix for at this time.

**Comment by varunreddy212** [comment]
Hi Simon thanks sorry didn't realise that was the issue. Any work around
that you would know off?

Thanks

Varun

**Comment by ManuelOlvera** [comment]
@macdonst you are right, I missed that one. Thanks for the quick response!

**Comment by macdonst** [comment]
@varunreddy212 no, no current work around. If users kill the app on Android or iOS then things stop working. Same problem with native apps.

@ManuelOlvera no problem, I'm going to close this issue then.
