### ISSUE TITLE
iOS InvalidRegistration

### ISSUE THREAD

**Issue by superainovacoes** [phonegap/phonegap-plugin-push#673]
Hi, i'm using version 1.5.3 with phonegap.

The "registrationId" when the event "registration" is fired on iOS (using testflight and certificates are ok to allow push)

The result for iOS is like this "60f59bb1610fe09e8587b4dc3dbe0e97dd8254e6cc8c1397317cbb4861aab97c" and for android is like this "fFLYT-4VfGU:APA91bH-ltYhPHGztZYI4FKNzJJnW-SUo4BvDUydUUWSbei3QsxbudNphYsqAloMc1dGeRbFZ8jqhWzQPTsKPTMVOUinJl8d7GwwC0UKRTvRC3NIkmDdIG0pXu2xbXMavI1fHt58xRKV"

When i send a notification to a android key it works, when to an ios key it returns "InvalidRegistration".

I've tried the simple test (https://github.com/macdonst/push-workshop/blob/master/server/gcmService.js) works for android but dont for ios.

Should the problem be on testflight not allowing the correct key? or am i missing something?

**Comment by macdonst** [comment]
@superainovacoes the ID, "60f59bb1610fe09e8587b4dc3dbe0e97dd8254e6cc8c1397317cbb4861aab97c", is valid on iOS if you are sending pushes via APNS. If you are trying to send via GCM to iOS you'll need to set `senderID` and `gcmSandbox` properly and then you'll get a registration ID useable on GCM on iOS.

**Comment by superainovacoes** [comment]
Ok, understood.

I've took the example from https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md but after i saw the https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md i understood.

Thanks.
