### ISSUE TITLE
Plugin Properties not working for Android with the new Ionic Push API

### ISSUE THREAD

**Issue by rajnandan1** [phonegap/phonegap-plugin-push#674]
I had everything working like butter with the old Ionic Push API. After the new API I had to update the ionic code and a bunch of other things. Now when I test the notification these things happen

1. None of the properties like style,image,summaryText work. The notification just has the default icon with title and body when the app is closed or is in Background
2. However, everything works when the app is in the foreground (where it should have received the notification in the first place)

Can anybody help me

**Comment by macdonst** [comment]
@rajnandan1 please follow the issue format when creating a new issue. You are not giving me enough information to help you.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/ISSUES.md#opening-a-new-issue

**Comment by rajnandan1** [comment]
**Platform Information**
 `
```
Cordova CLI: 6.0.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 7 SP1
Node Version: v0.12.7
```
**Problem 1**: Generic Properties like stlye,image,summaryText are not working when a notification is received sent through or using Ionic Push new API when the app is in the background. Notification does not play the default notification system sound
**Expected** these things to work

**Problem 2** : While the app is in the foreground, notification arrives (unexpected) with all the properties working

**Expected** : No notification from the system should have come as app in foreground

**Tested on** : Android 5.1.1 OnePlus One and OnePlus X

Code to register push notification

```
.controller('DashCtrl', function($scope,$ionicUser, $ionicPush,$ionicPlatform) {
	function signupSuccess(){
        console.log("ionic sign up sucess, now login the user");
        var authProvider = 'basic';
        var authSettings = { 'remember': true };
        var loginDetails = {
          'email': "myemail@gmail.com",
          'password': "myemail"
        };

        Ionic.Auth.login(authProvider, authSettings, loginDetails)
        .then(authSuccess, function(err){console.log(err)});
    }
	
	function authSuccess(){
        console.log("Ionic Login Success, now get the user id and put it in signupform");
        var ionic_user = Ionic.User.current();
        ionic_user.save();
        /*register for push*/
        $ionicPush.init({
          "debug": true,
		   'canRunActionsOnWake': true,
		   'canPlaySound': true,
          "onNotification": function(notification) {
            var payload = notification.payload;
            console.log(notification, payload);
          },
          "onRegister": function(data) {
            console.log(data.token);
            $ionicPush.saveToken(data.token);
          },
        "pluginConfig": {
          "ios": {
            "badge": true,
            "sound": true
           },
           "android": {
             "iconColor": "#1E656D",
			 'sound':true
           }
          } 
        });
        $ionicPush.register(); 
        /*register for push*/
      } 
	console.log("Dash");
        //method that initiates ionic user sign up > then login > then push registration
	$scope.confirmLocality=function(){
		$ionicPlatform.ready(function() {
			var details = {
				'email': "myemail@gmail.com",
				'password':  "myemail"
			} 
			Ionic.Auth.signup(details).then(signupSuccess, function(err){console.log(err)});
		})
      
    }
})
```
**The plugin behavior was

>  normal

 with the old Ionic Push API. **

Tested notification
```

"notification": {
      "title": "Hi",
      "message": "Hello world!",
      "android": {
        "title": "Hey",
        "message": "Hello Android!",
        "data":{
          "style": "picture",
          "summaryText" : "The internet is built on cat pictures",
          "picture" :  "https://pbs.twimg.com/profile_images/617058765167329280/9BkeDJlV.png",
          "image" :  "https://pbs.twimg.com/profile_images/617058765167329280/9BkeDJlV.png"
        },
        "payload":{
          "style": "picture",
          "summaryText" : "The internet is built on cat pictures",
          "picture" :  "https://pbs.twimg.com/profile_images/617058765167329280/9BkeDJlV.png",
          "image" :  "https://pbs.twimg.com/profile_images/617058765167329280/9BkeDJlV.png"
        }
      },
      "ios": {
        "title": "Howdy",
        "message": "Hello iOS!"
      }
    }
```

**Comment by macdonst** [comment]
@ericb can you take a look at this one?

**Comment by ericb** [comment]
@rajnandan1 I've already spoken with you about this issue and it cannot be replicated from a service standpoint.

@macdonst I think a better question here is whether the plugin or android os defines the behavior of the notification based on the GCM properties. I imagine a combination of both? For example, the referenced properties above work as intended for me, but sometimes I may need to pull down on the notification to see the styling, other times it's already fully visible.

**Comment by Remrem84** [comment]
I have te same issue. **pluginConfig** don't work with **android-targetSdkVersion > 20**...

Did someone find a solution ?

**Comment by MazzMazz** [comment]
Got the same issue, with the new ionic push, the remotely loaded image doesn't work anymore. Before ionic switched to the beta, it worked perfect.

My Android settings:.
`````
"android"=>array(
                    "title"=>$this->title,
                    "sound" => 'default',
                    "iconColor"=> "#08addb",
                    "icon"=> "vp",
                    "collapseKey"=>$this->collapseKey,
                    "image"=> $this->image,
                    "forceShow"=>true,
                    "payload"=>array(
                        "tet"=>"tet",
                    )
                )
````
