### ISSUE TITLE
XDK doesn't work with v1.5.x. Are you going to have a non-gradle version for v1.5.x

### ISSUE THREAD

**Issue by chetstriker** [phonegap/phonegap-plugin-push#675]
I can't use XDK with any version after v1.4.3 since XDK doesn't allow gradle plugins.
It appears you only added support to push to iOS through GCM starting at v1.5.0.
It would be nice to use the same method to push notifications to both platforms the same way.
The error on newer builds reports XDK doesn't support plugins using gradle.

**Comment by macdonst** [comment]
@chetstriker nope, I'm not moving back to a pre-gradle method of building the plugin. I causes no end of problems. You are better off opening a feature request to have Intel support Gradle with XDK.

**Comment by xmnboy** [comment]
@chetstriker -- we're working on providing a cloud-based build system for the Intel XDK that _will_ support gradle scripts. I wish I could provide an ETA, but we're not allowed to publish roadmaps or release dates. This is "Paul F." from the XDK forum.
