### ISSUE TITLE
How to configure another icon in the notifications

### ISSUE THREAD

**Issue by walterjsilva** [phonegap/phonegap-plugin-push#677]
In my app I'm using "phonegap/ionic" and I'm trying configure the push notifications to android in this way:
```
var push = PushNotification.init({
  android: {
    icon: 'notification-icon',
    clearNotifications: false,
    sound: true,
    vibrate: true,
    forceShow: true,
    senderID: 'xxxxxxxxxx'
  }
});
```
However, the icon that shows up in the notifications is the default icon of app, which stay in `resources/android/icon`. How to make shows up another icon in the notifications and where put it?

**Comment by macdonst** [comment]
@walterjsilva first make sure you read over the Android images docs:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images

the image you want to show should be in the right format and get copied to platforms/android/res/drawable directory. 

As well your image name `notification-icon` is not a valid Android resource file name. It can't have `-` in it. Make sure you stick to lower case characters and `_` only.

**Comment by walterjsilva** [comment]
Thanks for your answer, but does not worked yet. In addition to copying the image to directory there is something else, maybe to configure some file?

I put the image on drawable directory and reference in PushNotification.init() `icon: 'notification_icon'`. But still shows the default icon.

**Comment by macdonst** [comment]
@walterjsilva nope, that should work. I've just tested it as well. Try using an icon without a `_` in the name just in case. So `notification.png` and pass in:

```
var push = PushNotification.init({
  android: {
    icon: 'notification',
    clearNotifications: false,
    sound: true,
    vibrate: true,
    forceShow: true,
    senderID: 'xxxxxxxxxx'
  }
});
```

**Comment by walterjsilva** [comment]
Now it's working... Thanks a lot for you help! But it has not to do with the line _, after I uninstalled the device app and rebuild worked as expected.
