### ISSUE TITLE
not support Android 6 MM?

### ISSUE THREAD

**Issue by bobolat** [phonegap/phonegap-plugin-push#678]
> Uncaught TypeError: PushNotification.init is not a function

 i got this error on chrome inspect..if use android below 6 it working well..in my phone use android 6 cant get the token.

**Comment by sectorf8** [comment]
phonegap-plugin-push v1.6.0 es working fine in my Android MM.

**Comment by macdonst** [comment]
@bobolat I can't reproduce this problem on either of my Android 6 devices.

**Comment by macdonst** [comment]
Duplicate of #637 which I still can't reproduce.
