### ISSUE TITLE
Purpose of SENDER_ID argument for plugin installation?

### ISSUE THREAD

**Issue by mcm-ham** [phonegap/phonegap-plugin-push#679]
I see you now have to supply sender_id when installing the plugin otherwise you get an error. This then puts the sender_id in cordova config.xml with the --save argument.

- Does this remove the need from supplying it in `PushNotification.init`?
- Why is it a required argument when installing the plugin?
- Does supplying it with `PushNotification.init` override what is set in config.xml?

I want to supply it in `PushNotification.init` since I'm using ember and have different values for different environments like staging and production.

**Comment by mluria** [comment]
I agree, this seems to have just started in version 1.6.0.

This seems like a non-standard way of installing a plugin.  What if I want to have some login to decide which senderid to use.  Also, personally I develop for ios and add android later.  Putting in a bogus Senderid seems like a good source for future errors.

**Comment by macdonst** [comment]
On Android Google Play Services was throwing an warning in the console about the missing Sender ID. I needed it at install time to write the strings.xml file that Android looks for it in. For iOS it is required to write a pList file for GCM. 

For now `PushNotification.init` is the canonical reference point for for Sender ID so you can continue to use it as normal. Any big change to the API would be for a 2.0 release.

**Comment by mluria** [comment]
I'm sorry, I really don't understand, otherwise a warning is thrown during install time?
If I use a different value in .init than in sender_id, which one is used?
What is a canonical reference point?

**Comment by macdonst** [comment]
No, GCM throws warnings at run time if the sender ID is not set where it wants. In order to set it properly I need to know a plugin install time.

`cannonical` is authorized; recognized; accepted. So whatever you use in `PushNotification.init` will be the one used to connect to GCM.

**Comment by mluria** [comment]
If I use a different value in .init than in sender_id, which one is used?

**Comment by thomeijken** [comment]
I'm using the syntax as suggested to set the SENDER ID:
```
    <plugin name="phonegap-plugin-push" source="npm">
        <variable name="SENDER_ID" value="12345" />
    </plugin>
```
However, PGB is still giving me the error:
```
Failed to install 'phonegap-plugin-push':Error: Variable(s) missing: SENDER_ID
    at /usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:347:23
    at _fulfilled (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
Variable(s) missing: SENDER_ID
```

**Comment by thomeijken** [comment]
And by the way: If whatever you define in "PushNotification.init" is used as the SENDER ID, then why require to define it in Config.xml? At build time you could just throw in a random string into strings.xml since it doens't matter what you define there anyway right?...

**Comment by macdonst** [comment]
@thomeijken Sorry, I had the docs wrong. It should be 'param' not 'variable'.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md#including-the-plugin

It doesn't matter on iOS if you don't plan on using GCM but it will matter on Android as a fake GCM ID will send another warning in logs. 

Going forward you won't need to supply it in the init method and I hope to be able to auto-detect if you are production or sandbox on iOS.

**Comment by cgsmith** [comment]
I stumbled here due to the break in compatibility with Ionic.  I ran `ionic state reset` and received this message:

```

cordova plugin add phonegap-plugin-push

/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:543
        throw 'Error executing "' + pluginCommand + '":\n' + output;
        ^
Error executing "cordova plugin add phonegap-plugin-push":
Fetching plugin "phonegap-plugin-push" via npm
Error: Variable(s) missing (use: --variable SENDER_ID=value).
```

I can successfully get around this by changing the `package.json` from having just the `phonegap-plugin-push` string there to:

```
  "cordovaPlugins": [
    {
      "variables": {
        "SENDER_ID": "12345678"
      },
      "locator": "phonegap-plugin-push"
    }
```

**Comment by macdonst** [comment]
@cgsmith thanks I added it to the docs:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md

**Comment by hungdoan2** [comment]
@macdonst Is it possible to change 'SENDER_ID' without reinstalling the plugin ?

**Comment by macdonst** [comment]
@hungdoan2 just change the one in the `init` method.

**Comment by napcat** [comment]
So, basically I can put anything during the plugin installation, and use any correct ID in the init function?
It will not cause any problems?
 
     phonegap plugin add phonegap-plugin-push --variable SENDER_ID="9999999" //some random id

     var push = PushNotification.init(
     {
         android: { senderID: "12345679" }, //correct id
         ios: { alert: "true", badge: true, sound: 'false' },
         windows: {}
     });

**Comment by macdonst** [comment]
@napcat for now yes. Once we go to 2.0.0 then no.

**Comment by shivam268** [comment]
UNIX system users can also try accessing following file and changing file permissions to "read & write"

open '/Users/shivamparikh/.config/configstore/update-notifier-cordova.json'

**Comment by Giusti** [comment]
So I am having troubles with the Sender Id since I cant work with the cordova / phonegap cli how can i specify my SENDER_ID what i tried so far

<plugin name="phonegap-plugin-push" spec="1.6.0">
          <param name="SENDER_ID" value="MYID" />
        </plugin>

I am also working with iconic but since I am working with Teleriks built in Appbuilder for VS i dont have any package json where i could put this:

"cordovaPlugins": [
    {
      "variables": {
        "SENDER_ID": "12345678"
      },
      "locator": "phonegap-plugin-push"
    }

But If you say the SenderID from the Init function is user can I somehow just hardcode a random number into the plugin and change that to the correct SenderID in the Init function ? if yes where can i put the random number in the plugin

**Comment by FutoRicky** [comment]
what about sender_id depending on environment?

**Comment by pke** [comment]
The docs should make it clear the programmatic way is being deprecated soon.

**Comment by pke** [comment]
So Android 7 requires the ID to be part of the manifest now and it can't be set at runtime anymore?

**Comment by pke** [comment]
So what is it now? param or variable?
Having it named "variable" in the config xml installs the plugin into the platform, having it named "param" fails to install the plugin.

```
<plugin name="phonegap-plugin-push" spec="~1.8.0">
        <param name="SENDER_ID" value="xxxx" />
    </plugin>
```

fails: 
```
Discovered plugin "phonegap-plugin-push" in config.xml. Adding it to the project
Fetching plugin "phonegap-plugin-push@~1.8.0" via npm
Failed to restore plugin "phonegap-plugin-push" from config.xml. You might need to try adding it again. Error: Variable(s) missing (use: --variable SENDER_ID=value).
```
    
Having it named "variable" in config fails during runtime however,  if `senderId` is not specified with the `init` call.

Please get this straighten out.
