### ISSUE TITLE
PushNotification.init Fails (only in ios) with phonegap-plugin-push v1.6.0

### ISSUE THREAD

**Issue by sectorf8** [phonegap/phonegap-plugin-push#680]
I use v1.6.0 in ionic 1.2
Android is working fine, but ios fail in  PushNotification.init();

When i called it shows:
"ReferenceError: Can't find variable:  PushNotification"

My code:
```
$ionicPlatform.ready(function() { 
             try{   
			var push = PushNotification.init({
			    android: {
				senderID: "XXXXXX"
			    },
			    ios: {
				alert: "true",
				badge: "true",
				sound: "true"
			    },
			    windows: {}
			});
			push.on('registration', function(data) {
			    alert('registration AA: ' + data.registrationId);
			});
		  }
		  catch(e){
		    alert("tc AA:  " + e);
		  }
}
```
I used "ionic add ionic-platform-web-client" and my plugin list is:

> cordova-plugin-console 1.0.2 "Console"
> cordova-plugin-cs-disable-bitcode 1.0.0 "DisableBitcode"
> cordova-plugin-device 1.1.1 "Device"
> cordova-plugin-splashscreen 3.1.0 "Splashscreen"
> cordova-plugin-statusbar 2.1.1 "StatusBar"
> cordova-plugin-whitelist 1.2.1 "Whitelist"
> ionic-plugin-keyboard 1.0.8 "Keyboard"
> phonegap-plugin-push 1.6.0 "PushPlugin"

My test device is 'itunesstored/1.0 iOS/9.2.1 model/iPhone7,2 hwp/t7000 build/13D15 (6; dt:106)'

Thanks in advance.

**Comment by alexbuijs** [comment]
This is most likely related to #679. I had the same error and finally realised it was caused by the plugin not being installed due to the new required SENDER_ID variable.

**Comment by alexbuijs** [comment]
Ok, I thought this was the reason, but adding the variable still doesn't install on iOS, because cordova-ios version >= 4.0.0 is required. Since I still want to support iOS versions 6 and 7, I am stuck on cordova-ios 3.9.2. I wonder if this requirement is necessary...

**Comment by alexbuijs** [comment]
Update: this has to do with #456. But I fixed this with a [after_platform_add hook](https://gist.github.com/alexbuijs/c6e9ddd9a615e5cd1d23), so unfortunately I must fork this plugin and revert c096c99b0b3f4bd26d42af2c0cd6452b5f787a0d ...

**Comment by macdonst** [comment]
@sectorf8 did you provide the sender ID variable? 

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation

and you must be using Cordova iOS 4 or great as of plugin 1.6.

**Comment by sectorf8** [comment]
- My app (a blank app with push) doesnt work with v1.5.3 too
- I provide sender id 
- I copied /platforms/ios/platform_www/plugins in /platforms/ios/www (it was missing).
but....
error i get same error "ReferenceError: Can't find variable: PushNotification"

**Comment by macdonst** [comment]
@sectorf8 why are you copying files?

**Comment by sectorf8** [comment]
I read in https://github.com/phonegap/phonegap-plugin-push/issues/654

> now go in "your_app_folder/platforms/ios/www"
> there should be a file named "cordova_plugins.js" and a folder named "plugins"
> In my case those files were missing!
> Go in "your_app_folder/platforms/ios/platform_www" you should find the file and the folder above.
> Just copy and paste them in "your_app_folder/platforms/ios/www".

---

**Comment by macdonst** [comment]
@sectorf8 yeah, but you shouldn't need to do that. The copy of files to the right directories should happen during `cordova build ios`.

**Comment by sectorf8** [comment]
i try cordova-ios 4.0.1 and 4.1.1 and alwways get "ReferenceError: Can't find variable: PushNotification". Must i call push.js in index.html? 
I cant use "cordova build ios", i use linux and compile with "ionic package" service.
Thanks a lot @macdonst

**Comment by macdonst** [comment]
@sectorf8 then there is some error when the app is compiled by ionic. Does ionic use a config.xml file?

**Comment by Aumnia** [comment]
If you are using phone gap build to build your project, the highest version you get is 3.9.2 as specified in the cli-5.2.0.  I'm going to set the spec for the plugin to 1.5.3 to work around this for now.

**Comment by sectorf8** [comment]
@macdonst yes, it does (ionic uses a config.xml to define my widget)

**Comment by sectorf8** [comment]
@aumnia i use ionic package service

**Comment by macdonst** [comment]
@Aumnia not true, they have cli-6.0.0 with cordova ios 4.0.1 support.

http://phonegap.com/blog/2016/02/09/phonegap_6_now_on_build/

**Comment by macdonst** [comment]
@sectorf8 can I see your config.xml?

**Comment by sectorf8** [comment]
Yes of course

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<widget android-versionCode="0070101" id="com.ionicframework.inalertsapp374926" version="0.7.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <name>myAPP</name>
  <description>
       Push test.
    </description>
  <author email="info@mydomain.com" href="https://www.mydomain.com/">
      mydomain.com
    </author>
  <content src="index.html"/>
  <access origin="*"/>
  <preference name="webviewbounce" value="false"/>
  <preference name="UIWebViewBounce" value="false"/>
  <preference name="DisallowOverscroll" value="true"/>
  <preference name="android-minSdkVersion" value="16"/>
  <preference name="BackupWebStorage" value="none"/>
  <preference name="SplashScreen" value="screen"/>
  <preference name="SplashScreenDelay" value="3000"/>
  <feature name="StatusBar">
    <param name="ios-package" onload="true" value="CDVStatusBar"/>
  </feature>
  <platform name="android">
    <icon src="resources/android/icon/drawable-ldpi-icon.png" density="ldpi"/>
    <icon src="resources/android/icon/drawable-mdpi-icon.png" density="mdpi"/>
    <icon src="resources/android/icon/drawable-hdpi-icon.png" density="hdpi"/>
    <icon src="resources/android/icon/drawable-xhdpi-icon.png" density="xhdpi"/>
    <icon src="resources/android/icon/drawable-xxhdpi-icon.png" density="xxhdpi"/>
    <icon src="resources/android/icon/drawable-xxxhdpi-icon.png" density="xxxhdpi"/>
    <splash src="resources/android/splash/drawable-land-ldpi-screen.png" density="land-ldpi"/>
    <splash src="resources/android/splash/drawable-land-mdpi-screen.png" density="land-mdpi"/>
    <splash src="resources/android/splash/drawable-land-hdpi-screen.png" density="land-hdpi"/>
    <splash src="resources/android/splash/drawable-land-xhdpi-screen.png" density="land-xhdpi"/>
    <splash src="resources/android/splash/drawable-land-xxhdpi-screen.png" density="land-xxhdpi"/>
    <splash src="resources/android/splash/drawable-land-xxxhdpi-screen.png" density="land-xxxhdpi"/>
    <splash src="resources/android/splash/drawable-port-ldpi-screen.png" density="port-ldpi"/>
    <splash src="resources/android/splash/drawable-port-mdpi-screen.png" density="port-mdpi"/>
    <splash src="resources/android/splash/drawable-port-hdpi-screen.png" density="port-hdpi"/>
    <splash src="resources/android/splash/drawable-port-xhdpi-screen.png" density="port-xhdpi"/>
    <splash src="resources/android/splash/drawable-port-xxhdpi-screen.png" density="port-xxhdpi"/>
    <splash src="resources/android/splash/drawable-port-xxxhdpi-screen.png" density="port-xxxhdpi"/>
  </platform>
  <platform name="ios">
    <icon src="resources/ios/icon/icon.png" width="57" height="57"/>
    <icon src="resources/ios/icon/icon@2x.png" width="114" height="114"/>
    <icon src="resources/ios/icon/icon-40.png" width="40" height="40"/>
    <icon src="resources/ios/icon/icon-40@2x.png" width="80" height="80"/>
    <icon src="resources/ios/icon/icon-50.png" width="50" height="50"/>
    <icon src="resources/ios/icon/icon-50@2x.png" width="100" height="100"/>
    <icon src="resources/ios/icon/icon-60.png" width="60" height="60"/>
    <icon src="resources/ios/icon/icon-60@2x.png" width="120" height="120"/>
    <icon src="resources/ios/icon/icon-60@3x.png" width="180" height="180"/>
    <icon src="resources/ios/icon/icon-72.png" width="72" height="72"/>
    <icon src="resources/ios/icon/icon-72@2x.png" width="144" height="144"/>
    <icon src="resources/ios/icon/icon-76.png" width="76" height="76"/>
    <icon src="resources/ios/icon/icon-76@2x.png" width="152" height="152"/>
    <icon src="resources/ios/icon/icon-small.png" width="29" height="29"/>
    <icon src="resources/ios/icon/icon-small@2x.png" width="58" height="58"/>
    <icon src="resources/ios/icon/icon-small@3x.png" width="87" height="87"/>
    <splash src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" height="1136"/>
    <splash src="resources/ios/splash/Default-667h.png" width="750" height="1334"/>
    <splash src="resources/ios/splash/Default-736h.png" width="1242" height="2208"/>
    <splash src="resources/ios/splash/Default-Landscape-736h.png" width="2208" height="1242"/>
    <splash src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" height="1536"/>
    <splash src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" height="768"/>
    <splash src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" height="2048"/>
    <splash src="resources/ios/splash/Default-Portrait~ipad.png" width="768" height="1024"/>
    <splash src="resources/ios/splash/Default@2x~iphone.png" width="640" height="960"/>
    <splash src="resources/ios/splash/Default~iphone.png" width="320" height="480"/>
  </platform>
  <platform name="wp8">
    <icon src="resources/wp8/icon/ApplicationIcon.png" width="99" height="99"/>
    <icon src="resources/wp8/icon/Background.png" width="159" height="159"/>
    <splash src="resources/wp8/splash/SplashScreenImage.png" width="768" height="1280"/>
  </platform>
  <icon src="resources/android/icon/drawable-xhdpi-icon.png"/>
  <plugin name="cordova-plugin-disable-bitcode" spec="~1.3.2"/>
</widget>
```

**Comment by Aumnia** [comment]
Thanks for the link.  I missed the upgrade note when I was scanning the
phonegap build documentation for how to set the version.

On Wed, Mar 9, 2016 at 1:49 PM, Simon MacDonald <notifications@github.com>
wrote:

> @Aumnia <https://github.com/Aumnia> not true, they have cli-6.0.0 with
> cordova ios 4.0.1 support.
>
> http://phonegap.com/blog/2016/02/09/phonegap_6_now_on_build/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-plugin-push/issues/680#issuecomment-194524458>
> .
>



-- 
Julie Yousefi
Aumnia, Inc.
julie@aumnia.com

**Comment by macdonst** [comment]
@Aumnia I talked to PGB guys and they will update the docs as well which still show 5.2.0 as the latest.

**Comment by macdonst** [comment]
@sectorf8 I don't see anything in your config.xml that includes the Push Plugin.

**Comment by sectorf8** [comment]
Thanks @macdonst , if i use
`$cordova plugin add phonegap-plugin-push --save
`
My config.xml show
```
  <plugin name="phonegap-plugin-push" spec="~1.6.0">
    <variable name="SENDER_ID" value="1111111111111"/>
  </plugin>
```

BUT i get same error "ReferenceError: Can't find variable: PushNotification"

Thanks for you help.

**Comment by sectorf8** [comment]
thanks  @macdonst you're right.
If I use XCODE app works fine.
I think there is a problem with "ionic package" service.

Thanks a lot.

**Comment by macdonst** [comment]
@sectorf8 read the note in installation for Ionic users: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md

**Comment by sectorf8** [comment]
Yes I read yet, but it's OK. My problem is "ionic package" service, i will report to ionic.
Thanks.

**Comment by mbaggott** [comment]
Thank you for your comments in this thread. Ionic cloud package was a problem for me too, until i added the variables noted in the readme file linked above (which by the way are not highlighted very well and easy to miss), and after re-installing the plugin with the --save flag which added details to the config.xml. Cloud Package is now installing the plugin, and i am able to init and get a registrationID

**Comment by christianraj** [comment]
am receiving notification in all case my doubt is i could get my alert when app is in foreground and i have gave the value to alert as true 
my code as follow 
ios: {
				        alert : 'true',
				        clearBadge: 'true',
				        sound : 'true'
				    }
