### ISSUE TITLE
Support Android N inline reply actions

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-plugin-push#683]
With the Direct Reply feature in Android N, users can quickly respond to text messages or update task lists directly within the notification interface. On a handheld, the inline reply action appears as an additional button attached to the notification. When a user replies via keyboard, the system attaches the text response to the intent you had specified for the notification action and sends the intent to your handheld app.

![inline-reply](https://cloud.githubusercontent.com/assets/353180/13647658/15662566-e603-11e5-88e7-2b23c4da222f.png)

![inline-type-reply_2x](https://cloud.githubusercontent.com/assets/353180/13647660/19f14dae-e603-11e5-953d-a3b9c3668e69.png)

**Comment by macdonst** [comment]
![inline_reply](https://cloud.githubusercontent.com/assets/353180/17107446/4290437a-525d-11e6-828d-1e69d99df04f.png)

**Comment by macdonst** [comment]
![inline_reply](https://cloud.githubusercontent.com/assets/353180/17107608/f35c208e-525d-11e6-94de-a3590c6f500d.png)

**Comment by Xwalk-Company** [comment]
Nice feature,
Thks

**Comment by macdonst** [comment]
@Xwalk-Company thanks, should be pushing a 1.8.0 out later today.
