### ISSUE TITLE
Get Push while the App is in Inappbrowser Foreground

### ISSUE THREAD

**Issue by martinr77** [phonegap/phonegap-plugin-push#685]
How is it possible to get a Notification while the App is open and the user is in the inappbrowser?
Right now there is happen nothing.

Thanks

**Comment by macdonst** [comment]
@martinr77 the InAppBrowser is still technically still your app so the OS wouldn't show anything in the notification tray. You should be able to get the `on('notification')` event handler though.

**Comment by martinr77** [comment]
Hi @macdonst 
thanks for your answer. I tried this but it is not working. The on('notification') event handler is only working inside of the "native" app, not in the inappbrowser,

**Comment by macdonst** [comment]
@martinr77 give me an example push payload you are using and what platform are you testing?

**Comment by martinr77** [comment]
@macdonst Right now I'm testing with IOS 9.2.1:

                                    ```
                                       // Create the payload body
					$body['aps'] = array(
						'alert' => $message,
						'sound' => "www/sound.mp3",
						'content-available' => 1,
						'badge' => $badge
						);
```

**Comment by macdonst** [comment]
@martinr77 can you attach the debugger in Safari to your app to see if the console.log is called? Also, you should output the value of `data.additionalData.foreground` as I'm curious if it is true or not. As for doing an alert that is a bad idea as that is one of the few blocking calls in JS.

**Comment by macdonst** [comment]
@martinr77 just looking over this again and I see you are opening the in app browser as `_self` so that loads the remote URL directly into the Cordova Web View. That means all the push code you have setup will be unloaded and you will no longer get the `on('notification')` event called.

So what you are trying to do will never work. Make sense?

**Comment by martinr77** [comment]
Yes, you're right. That makes definitely sense. Thanks for your help.

**Comment by macdonst** [comment]
@martinr77 okay, I'm going to close this one.
