### ISSUE TITLE
[BUG] Showing notification twice when using remote URL with node-gcm

### ISSUE THREAD

**Issue by HowardLoTW** [phonegap/phonegap-plugin-push#687]
Hello, 

I'm using `node-gcm` as my push notification server,
Here is my code snippet from my `server.js`:
```
function sendNotification(notification) {

    var retry_times = 4;
    var sender = new gcm.Sender(GCM_API_KEY);
    var message = new gcm.Message({
        priority: 'high',
        contentAvailable: true,
        delayWhileIdle: false,
        data: {
            "title" : 'Emotion Push',
            "image" : notification.image || 'http://cdn.playbuzz.com/cdn/902475b7-454d-4650-98bd-f66ae859eb1c/2e99694d-e2ff-4611-9190-859d3278686e.png',
            "message" : 'Emotion Push',
            "vibrationPattern" : [400, 200, 400, 200],
        }
    });

    sender.send(message, [notification.device_token], retry_times, function (err, response) {

        console.log('Push notification to: ', notification.device_token);

        if (err) console.error(err);
        else     console.log(response);
    });
}
```

As the code shown above, I set the notification icon with an URL,
then I got two notifications on my android device, which I think it's probably a bug:

![screenshot](https://scontent-hkg3-1.xx.fbcdn.net/hphotos-xap1/v/wl/t34.0-12/12067099_1262904777071991_929173574_n.jpg?oh=c3229f76d5b64dffb04798c69c8bd06a&oe=56E2E703)

As the screenshot shown above, the upper notification contained red notification image loaded from url, which was what I expected. But I received the redundant notification, which is the lower notification contained default app icon and without message text. I guess the redundant one is set as default which is the notification field in gcm message object that I didn't specify.

How to deal with this problem ? Thanks.

**Comment by macdonst** [comment]
@HowardLoTW hmmmm...something weird is happening here. When I send a message using your code the Push Notification Handler of the plugin is never called, the OS takes over. 

However, if I change up the code a bit:

```
function sendNotification(notification) {

    var retry_times = 4;
    var sender = new gcm.Sender(GCM_API_KEY);
    var message = new gcm.Message();
        message.priority= 'high';
        message.contentAvailable= true;
        message.delayWhileIdle= false;
        message.addData('title', 'Emotion Push');
        message.addData('image', notification.image ||  'http://cdn.playbuzz.com/cdn/902475b7-454d-4650-98bd-f66ae859eb1c/2e99694d-e2ff-4611-9190-859d3278686e.png');
        message.addData('message', 'Emotion Push');
        message.addData('vibrationPattern', [400, 200, 400, 200]);

    sender.send(message, [notification.device_token], retry_times, function (err, response) {

        console.log('Push notification to: ', notification.device_token);

        if (err) console.error(err);
        else     console.log(response);
    });
}
```

I'm betting that when you create a gcm.Message the way you did it populates the 'notification' object which signals the OS to take over. I'll have to delve into node-gcm some more.

**Comment by macdonst** [comment]
@HowardLoTW so I looked at it some more and the offending line seems to be the "contentAvailable" one. If you change your code to be:

```
function sendNotification(notification) {

    var retry_times = 4;
    var sender = new gcm.Sender(GCM_API_KEY);
    var message = new gcm.Message({
        priority: 'high',
        delayWhileIdle: false,
        data: {
            "title" : 'Emotion Push',
            "image" : notification.image || 'http://cdn.playbuzz.com/cdn/902475b7-454d-4650-98bd-f66ae859eb1c/2e99694d-e2ff-4611-9190-859d3278686e.png',
            "message" : 'Emotion Push',
            "vibrationPattern" : [400, 200, 400, 200],
            "content-available": "1"
        }
    });

    sender.send(message, [notification.device_token], retry_times, function (err, response) {

        console.log('Push notification to: ', notification.device_token);

        if (err) console.error(err);
        else     console.log(response);
    });
}
```

you should get the desired outcome.

**Comment by HowardLoTW** [comment]
It works ! Thanks a ton !

By the way, I was wondering that how does the `phonegap-plugin-push` make the device show notifications by setting the `data` field in gcm message object in `node-gcm` instead of the notification field ? Since I read the use scenario of `notification` and `data` from  [Google official document](https://developers.google.com/cloud-messaging/concept-options#options), the `notification` field handles the display of the notification, while the `data` field handles the processing of the data messages. But here in `phonegap-plugin-push` seems to get all things done in `data` field.

Thanks.

**Comment by HowardLoTW** [comment]
Another issue report : 
It works when my app is in background. 
But when my app is in foreground, the notification icon is default app icon instead of the image loaded from url.

**Comment by macdonst** [comment]
@HowardLoTW yeah, we have to put everything in the "data" object so our plugin code will get called. If not the OS just takes over and does the UI for us. Since we need to special handlers to call the JS code we have to force everything to go through data. So we're not exactly the same as GCM's default but we get the job done.

**Comment by macdonst** [comment]
@HowardLoTW don't report different issues in the same thread as it makes it hard for people to find. So please open a new issue as it is weird that your app gets a notification UI when it is in the foreground.
