### ISSUE TITLE
question: does it work on IOS emulator?

### ISSUE THREAD

**Issue by clembou590** [phonegap/phonegap-plugin-push#694]
Hello.
This is just a question:
Is this suppose to work on IOS emulator?
(can I get a registration token / receive push notification if I am using only the emulator)

**Comment by macdonst** [comment]
You can not send / receive apple push notifications on iOS simulator as Push notifications are not available in the simulator. They require a provisioning profile from iTunes Connect, and thus are required to be installed on a device.

**Comment by clembou590** [comment]
Can the registration work in the emulator?

**Comment by clembou590** [comment]
Hello.
I understood I cannot receive notification on the emulator.
My question now is: can I use the emulator and get a registration token? (even if the notifications won't be received...)
thank you

**Comment by macdonst** [comment]
@clembou590 no, you cannot.
