### ISSUE TITLE
Java Object is gone

### ISSUE THREAD

**Issue by echonox** [phonegap/phonegap-plugin-push#695]
I just received error in cordova and it seems it is in the push plugin, this is the error:

file:///android_asset/www/plugins/phonegap-plugin-push/www/push.js:63:9", "message": "Java object is gone"

I can't provide repro as this happened on customer device, and also the message doesn't say much, here is the device info:

Browser: Chrome 44
Browser Name: Chrome
Browser Name Code: chrome
Browser Version: 44
Browser Version (full): 44.0.2403.157
Layout Engine Name: WebKit
Layout Engine Version: 537.36
User agent Type: mobile
Android Version: 4.2.2

Why is this error any idea?

**Comment by macdonst** [comment]
@jack-dev I did a quick search and that error seems to be coming from the WebView to Java bridge in Chrome. Sadly I have no idea what caused it. Can you get more info as to what was going on?

**Comment by jack-dev** [comment]
@macdonst unfortunately i can't give you any more info, except that the app uses crosswalk webview, maybe that will help you

**Comment by echonox** [comment]
@macdonst any updates?

**Comment by macdonst** [comment]
@echonox nope, I have 6 devices running various versions of Android. I can't reproduce it and it's not like you've exactly given me a reproduction scenario to go on.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
