### ISSUE TITLE
When I click in notification icon, push.on('notification') is not fired

### ISSUE THREAD

**Issue by Stiveknx** [phonegap/phonegap-plugin-push#698]
### Expected Behaviour
To Fire push.on('notification') when I click in notification from status bar

### Actual Behaviour
Does nothing.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4, 5.0 and 6.0

#### Sample Push Data Payload
    var message = new gcm.Message({
    	collapseKey: 'demo',
    	priority: 'high',
    	contentAvailable: true,
    	delayWhileIdle: true,
    	timeToLive: 3,
    	data: {
    		msgcnt: 1
    	},
    	notification: {
    		title: 'testing',
    		icon: "icon_push",
    		sound: 'default',
    		message: 'test',
    		body: 'testing'
    	}
    });
    var sender = new gcm.Sender('');
sender.send(message, { registrationTokens: regTokens }, function (err, response) {
        	if(err) {
        	    console.log(err);
        	    cb(err);
        	} else {
        	    console.log(response);
        	    cb(response);
        	}
        });
#### Sample Code that illustrates the problem
    $ionicPlatform.ready(function() {
      var config = {
        android: {
          senderID: "xxxx",
          icon: "icon_push"
        },
        ios: {
          alert: "true",
          badge: "true",
          sound: "true"
        },
        windows: {}
      };
      var push = PushNotification.init(config);
      push.on('registration', function(data) {
        alert(data.registrationId);
        // Success -- send deviceToken to server, and store for future use
      });
      push.on('notification', function(data) {
        alert("Title:" + data.title); // This alert for example, it get s fired when the app is in foreground, but when the app launches from clicking on a notification, it's not fired
      });
});
#### Logs taken while reproducing problem
In logcat, I see no logs about PushPlugin when clicking in notification.

**Comment by macdonst** [comment]
@Stiveknx use the following in node-gcm as our properties need to be in the data object:

```
var message = new gcm.Message({
    collapseKey: 'demo',
    priority: 'high',
    contentAvailable: true,
    delayWhileIdle: true,
    timeToLive: 3,
    data: {
        msgcnt: 1,
        title: 'testing',
        icon: "icon_push",
        sound: 'default',
        message: 'test',
        body: 'testing'
    }
});
```

Let me know if that fixes the problem.

**Comment by Stiveknx** [comment]
Yep, fixed.
Thanks.
Is that documented somewhere?
Didn't find it ...

**Comment by macdonst** [comment]
@Stiveknx all of the examples use `data` but I should document it more clearly.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#android-behaviour
