### ISSUE TITLE
Can I use this plugin for parse.com push?

### ISSUE THREAD

**Issue by zhouhao27** [phonegap/phonegap-plugin-push#699]
Can I use this plugin for parse.com push? And how? Thanks

**Comment by macdonst** [comment]
@zhouhao27 yes, other people have successfully used this plugin with Parse. I don't have documentation on how to make it possible. However, Parse.com is going away so you may not want to build an app around it.

**Comment by zhouhao27** [comment]
Thanks. But parse is open source now.

**Comment by macdonst** [comment]
@zhouhao27 ah, originally the push code was not part of the open source drop but I see that is no longer the case.
