### ISSUE TITLE
push sound iOS 9

### ISSUE THREAD

**Issue by lucasabba** [phonegap/phonegap-plugin-push#70]
Hi, i'm creating an app and I'm testing its on iPad with iOS 8 and iPhone with iOS 9. When i accept push notification in iOS 9 sound is not active, infant in push notification setting on iPhone there isn't sound option yes/no for my app, for other app yes. On iPad with iOS 8 sound option there are and i receive sound. Today i update iPad to iOS 9 and sound option disappear so i can't receive sound also on iPad. At this point i think that the problem is with plugin and iOS 9. I hope that someone can help me and all other developer that use this plugin because approximately on 15 settembre iOS 9 became public for everybody.
Thanks

**Comment by macdonst** [comment]
@lucasabba I haven't started looking into iOS9 support. Version 1.3 which will release in September will have support for iOS9.

**Comment by alexbuijs** [comment]
This seems to be an issue unrelated to iOS 9. I experienced this on iOS 8 as well as on iOS 9 beta, but it appears that passing the correct ios options to the init function, solves the issue (at least for me). The documentation doesn't mention these options, but try passing {ios: {sound: true, badge: true, alert: true}} to init.

**Comment by macdonst** [comment]
@alexbuijs What version of the plugin are you using?

**Comment by alexbuijs** [comment]
I'm using the latest version: 1.2.0

**Comment by lucasabba** [comment]
My plugin version is 1.1.1, how can I update?

**Comment by alexbuijs** [comment]
````
cordova plugin rm phonegap-plugin-push
cordova plugin add phonegap-plugin-push

**Comment by lucasabba** [comment]
Thanks, after update I need to use "Cordova prepare iOS"?

**Comment by alexbuijs** [comment]
it shouldn't be necessary, but it won't hurt.

**Comment by lucasabba** [comment]
@alexbuijs where i need to insert {ios: {sound: true, badge: true, alert: true}}  ?
is this ok?

PushNotification.init({
            "android": {
                "senderID": "************"
            },
            "ios": {sound: true, badge: true, alert: true}, 
            "windows": {} 
        });

**Comment by lucasabba** [comment]
everything work on iOS 9 after update plugin to version 1.2.0 and use @alexbuijs idea
Thanks to all for your help!

**Comment by macdonst** [comment]
@alexbuijs thanks! No idea why that is not documented.

@lucasabba I will update the docs and close this issue.
