### ISSUE TITLE
Error in building app once upgrade ios platform version to 4+ when plugin is installed

### ISSUE THREAD

**Issue by razmik** [phonegap/phonegap-plugin-push#701]
### Actual Behaviour
My Ionic App is on ios version 3.9.2. When trying to install the plugin, it skips ios.
Then I updated ios to 4.0.1. There it installed but when I build the app it gave the following error:

** BUILD FAILED **

The following build commands failed:
	CompileC build/testcordova4.build/Debug-iphonesimulator/testcordova4.build/Objects-normal/i386/MainViewController.o testcordova4/Classes/MainViewController.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
ERROR building one of the platforms: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/kosalap/Documents/Development/Test Apps/testcordova4/platforms/ios/cordova/build-debug.xcconfig,-project,testcordova4.xcodeproj,ARCHS=i386,-target,testcordova4,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/kosalap/Documents/Development/Test Apps/testcordova4/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/kosalap/Documents/Development/Test Apps/testcordova4/platforms/ios/build/sharedpch
You may not have the required environment or OS to build this project
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/kosalap/Documents/Development/Test Apps/testcordova4/platforms/ios/cordova/build-debug.xcconfig,-project,testcordova4.xcodeproj,ARCHS=i386,-target,testcordova4,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/kosalap/Documents/Development/Test Apps/testcordova4/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/kosalap/Documents/Development/Test Apps/testcordova4/platforms/ios/build/sharedpch

Are you user https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PLATFORM_SUPPORT.md is updated?
#### Steps to Reproduce 
Using MAC OS,
update cordova and ionic using;
sudo npm install -g cordova ionic

Create a new app.
Add ios platform.
Update the ios platform to ios 4.0.1
Install the plugin.
Build the app - ionic build ios
Above error comes

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ios platform 4.0.1

#### Logs taken while reproducing problem
** BUILD FAILED **

The following build commands failed:
	CompileC build/testcordova4.build/Debug-iphonesimulator/testcordova4.build/Objects-normal/i386/MainViewController.o testcordova4/Classes/MainViewController.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
ERROR building one of the platforms: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/kosalap/Documents/Development/Test Apps/testcordova4/platforms/ios/cordova/build-debug.xcconfig,-project,testcordova4.xcodeproj,ARCHS=i386,-target,testcordova4,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/kosalap/Documents/Development/Test Apps/testcordova4/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/kosalap/Documents/Development/Test Apps/testcordova4/platforms/ios/build/sharedpch
You may not have the required environment or OS to build this project
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/kosalap/Documents/Development/Test Apps/testcordova4/platforms/ios/cordova/build-debug.xcconfig,-project,testcordova4.xcodeproj,ARCHS=i386,-target,testcordova4,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/kosalap/Documents/Development/Test Apps/testcordova4/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/kosalap/Documents/Development/Test Apps/testcordova4/platforms/ios/build/sharedpch

**Comment by macdonst** [comment]
@razmik did you get this resolved?

**Comment by razmik** [comment]
No couldn't. I am now using earlier version of camera plugin.

**Comment by macdonst** [comment]
@razmik which camera plugin?

**Comment by razmik** [comment]
Sorry, my bad.
I'm now using https://github.com/phonegap/phonegap-plugin-push 1.5.3, which works.

**Comment by macdonst** [comment]
@razmik I think if you remove the platform and plugin, then add them back it should work but I'll close this issue for now.

**Comment by zhaowanhua** [comment]
Look like I have a same issue . And it is work when I  remove the platform and plugin, then add them back, but it will back again.
