### ISSUE TITLE
Don't understand how to set header for WP registration

### ISSUE THREAD

**Issue by dadinounet** [phonegap/phonegap-plugin-push#704]
Hi,

Im working on a nokia lumia 630, which run on windows phone 8.1
My app is a simple cordova app wich send the registration token to a server with jQuery.

I succeed easily with android, but i dont know what to do for WP.

Here's my init of the registration:

var push = PushNotification.init({
            android: {
                senderID: "**********"
            },
            ios: {
                alert: "true",
                badge: "true",
                sound: "true"
            },
            windows: {}
        });

So i dont understand what to put inside windows:{} or even if there's something to put in.

And what to do with the information i have from the microsoft dev center like the client_id, the package sid or even the secret client key.

I tryed like this, and returned me an url with a token inside : https://db5.notify.windows.com/?token=*****************************

Will it work corectly if i try to push a notif on the phone with this token as i never used information from the microsoft dev center ?

Thanks for your help

Pierre-Louis
Opensugar developer 
France

**Comment by macdonst** [comment]
@dadinounet you don't need to add any additional parameters for windows. Also, this plugin supports the cordova-windows platform not cordova-wp8.

**Comment by rakatyal** [comment]
Yes you don't need to specify any parameters for registration. The information from the dev centre is used to authenticate your cloud service with WNS and then to send the push notifications to the client. How are you trying to deliver the notifications?

You can read about the related articles here:
https://msdn.microsoft.com/en-us/windows/uwp/controls-and-patterns/tiles-and-notifications-windows-push-notification-services--wns--overview

**Comment by dadinounet** [comment]
Thanks for your reply guys.
Actually i didn't said it and im sorry about it, i already use the cordova windows platform so its ok.
To send a notification im trying to use the code given here: https://msdn.microsoft.com/fr-fr/library/windows/apps/xaml/hh868252

But as i work with a J2EE server i have to translate this code in java.

**Comment by dadinounet** [comment]
So, i just ended to convert the c# code into java to send a notification, here's the code HttpURLConnection connection = null;  
		  try {
		    //Create connection
		    URL url = new URL(WINDOWS_REGISTERATION_KEY);
		    connection = (HttpURLConnection)url.openConnection();
		    connection.setRequestMethod("POST");
		    connection.setRequestProperty("Authorization", WINDOWS_REGISTERATION_KEY);
		    connection.setRequestProperty("X-WNS-Type","wns/toast");
		    connection.setRequestProperty("Content-Type","text/xml");	    
		    connection.setRequestProperty("Content-Length", Integer.toString(message.getBytes().length)); 

		    connection.setUseCaches(false);
		    connection.setDoOutput(true);

		    //Send request
		    DataOutputStream wr = new DataOutputStream (
		        connection.getOutputStream());
		    wr.writeBytes(message);
		    wr.close();

		    //Get Response  
		    InputStream is = connection.getInputStream();
		    BufferedReader rd = new BufferedReader(new InputStreamReader(is));
		    StringBuilder response = new StringBuilder();
		    String line;
		    while((line = rd.readLine()) != null) {
		      response.append(line);
		      response.append('\r');
		    }
		    rd.close();
		  } catch (Exception e) {
		    e.printStackTrace();
		  } finally {
		    if(connection != null) {
		      connection.disconnect(); 
		    }
		  }

WINDOWS_REGISTERATION_KEY --> url returned back when registered with your plugin, which is in this case something like https://db5.notify.windows.com/?token=****************

When i try, i keep having a 401 status code, i tryed to register then instantly send the push to be sure that the token was not expired, same result.

Any idea ?

Thanks

**Comment by rakatyal** [comment]
The 'Authorization' header needs to have the access token which is received on authenticating your cloud service. Also you need to add a 'Bearer: " tag before it. The plugin code gives you the 'notification channel' for the target device and not the 'access token' for the cloud service. Kindly refer to [this](https://msdn.microsoft.com/en-us/windows/uwp/controls-and-patterns/tiles-and-notifications-windows-push-notification-services--wns--overview) article for step by step instructions to authenticate your cloud service and then to send a push notification.

**Comment by dadinounet** [comment]
hi,
first sorry for the time to answer you back, was my holiday week.

I succeeded to make something quite good thanks to the documentation you gave me, but i keep getting an error 400, here's my code

WINDOWS_REGISTERATION_KEY = NotificationsDB.RecupRegKey(deviceToken, appName);
		String subscriptionUri = WINDOWS_REGISTERATION_KEY;
// here, subscription uri = https://db5.notify.windows.com/?token=****************
		String charset = "UTF-8";
		
		String toastMessage = "<?xml version=\"1.0\" encoding=\"utf-8\"?>" +
		        "<wp:Notification xmlns:wp=\"WPNotification\">" +
		           "<wp:Tile>" +
		                "<wp:Text1>" + test + "</wp:Text1>" +		                
		           "</wp:Tile> " +
		        "</wp:Notification>";
		
		URLConnection connection = new URL(subscriptionUri).openConnection();
		connection.setDoOutput(true); // Triggers POST.
		connection.setRequestProperty("Content-Length", ""+toastMessage.getBytes(charset).length+"");
        connection.setRequestProperty("X-NotificationClass", "1");
        connection.setRequestProperty("X-WindowsPhone-Target", deviceToken);
		connection.setRequestProperty("Content-Type", "text/xml");

		try (OutputStream output = connection.getOutputStream()) {
		    output.write(toastMessage.getBytes(charset));
		    //output.flush();
		}
		catch(Exception e){
			System.out.println(e);
		}
		InputStream response = connection.getInputStream();
		String strResponse = response.toString();
		System.out.println(strResponse);

**Comment by dadinounet** [comment]
i tried with many différent parameters in the request property and i also tried with subscriptionUri = https://login.live.com/accesstoken.srf .... still 400
here, https://msdn.microsoft.com/fr-fr/library/windows/apps/hh202967%28v=vs.105%29.aspx, they give the entire server side code in C#, i tried in a test application in C#, still 400 ....

**Comment by rakatyal** [comment]
The link you are following is for WP8 which worked on MPNS notifications. This plugin doesn't support WP8 and is based on WNS. I see that you are targeting WP8.1 so you should be using WNS and not MPNS. You can find the code to do that [here](https://msdn.microsoft.com/library/windows/apps/xaml/hh868252).

**Comment by dadinounet** [comment]
I already tryed to do this but i need the bearer token to do it, and when i follow this tutorial to get it -> https://msdn.microsoft.com/fr-fr/library/windows/apps/xaml/hh868245
I always get an error 400 ... that's why im lost =(

**Comment by rakatyal** [comment]
So are you not able to authenticate your web service? 400 would mean you are using some invalid parameter. Are you using the correct client_id and secret? I followed [this](https://msdn.microsoft.com/en-us/library/windows/apps/xaml/hh868206) tutorial to authenticate my web service and it worked for me. It has the code sample as well.

**Comment by dadinounet** [comment]
ok, damn, im finally succeded in registering my application, and obtaining an authentication token i use this way 

URLConnection connection = new URL(sendingUri).openConnection();
		connection.setDoOutput(true); // Triggers POST.
		connection.setRequestProperty("Authorization", "Bearer xxxxxthetokenxxxxx
		connection.setRequestProperty("Content-Length", ""+toastMessage.getBytes(charset).length+"");
        connection.setRequestProperty("X-NotificationClass", "1");
        connection.setRequestProperty("X-WindowsPhone-Target", deviceToken);
		connection.setRequestProperty("Content-Type", "text/xml");

where sendingUri is the Uri returned by the plugin push : https://db5.notify.windows.com/?token=xxxxxxxx

Is this what i should do ? beacause it always return me 401 ... im trully becoming mad, i keep follow the tutorials you gave me and it always fail XD what a nice idea to become a developper ...

**Comment by rakatyal** [comment]
Sorry for the late reply and that the tutorial didn't work for you. The code you are using works for me. 401 would mean that the authorization token is incorrect or expired. If you want I can set up a call with you to debug. Also just to make sure the problem is with your notification service, you can try sending a notification through a node package like [this](https://github.com/tjanczuk/wns). If it works, that would mean your service has not been correctly authenticated.

**Comment by daserge** [comment]
Here is a great tutorial/sample covering server side and an UWP app setup:
https://brentdacodemonkey.wordpress.com/2015/11/05/a-javascript-based-windows-10-uwp-notification-hub/
https://github.com/brentstineman/Windows10
