### ISSUE TITLE
IOS Registering to topics doesn't work

### ISSUE THREAD

**Issue by jakari** [phonegap/phonegap-plugin-push#706]
### Expected Behaviour

As per the API.md mentions, you should be able to register to topics in IOS, by adding `topics` into init:

```
var push = PushNotification.init({
    ios: {
        senderID: "12345679",
        gcmSandbox: true,
        alert: "true",
        badge: true,
        sound: 'false',
        topics: ['foo', 'bar']
    }
});
```

### Actual Behaviour

When I try to register to topics in IOS like in the example, nothing happens, the system doesn't register to given topics in GCM.

I was confused, so I began digging the source code, and it seems there is nothing that interprets the `topics` array on the IOS side, so the feature seems to be missing altogether.

I digged deeper, and it seems there is a issue #79 with a branch called `issue79` that has this functionality but it isn't merged to master.

Is there some reason why this functionality isn't merged to master?

**Comment by macdonst** [comment]
@jakari Nope, that seems like a screw up on my part. I'm on vacation right now but will look at it within a week.

**Comment by jakari** [comment]
I actually forked and patched it in already since I needed the functionality, so if you don't mind, I can make a pull request of it and see what you think.

**Comment by macdonst** [comment]
Go for it
