### ISSUE TITLE
[Question] Notifications not being stacked

### ISSUE THREAD

**Issue by HowardLoTW** [phonegap/phonegap-plugin-push#709]
Hello, 

I've set the "notId" field with node-gcm, here is the message log I sent : 
```
Push notification:  Message {
  params:
   { data:
      { notId: 'ilunwzn8', // <== Here I use "uniqid" node module to generate different id, but the notifications still be replaced
        title: 'Emotion Push',
        image: 'ic_emotion_joy',
        message: 'I'm happy',
        priority: 2,
        vibrationPattern: [Object],
        'content-available': '1' }
    }
}
```

Here's the code : 
```
var message = new gcm.Message({
        "data" : {
            "notId" : uniqid(),
            "title" : notification.title || "Emotion Push",
            "image" : notification.image || 'icon',
            "message" : notification.message || "Emotion Push",
            "priority" : 2, // Highest priority.
            "vibrationPattern" : [300, 150, 300], 
            "content-available": "1" // Receive notification in background.
        }
    });
```

Tested with Android 4.4.2.
 Thanks.

**Comment by macdonst** [comment]
@HowardLoTW so does every new notification replace the one before it? Just trying to understand what you are seeing.

**Comment by HowardLoTW** [comment]
Yes, it does

**Comment by macdonst** [comment]
@HowardLoTW weird. Okay, I'm on vacation this week but will look at it soon.

**Comment by jopelkey** [comment]
I'm pretty sure that what I ran into last week with the 1.6.0 push plugin and notId was that the notId on Android needed to be an int and not a string.  As a string I was getting exceptions thrown in my logs and my push notifications were not stacking.  When I switched them to be ints (or longs actually) then the exceptions cleared up and I got stacking behavior.  Don't know if that is intentional or a bug?

**Comment by macdonst** [comment]
@jopelkey you are correct it needs to be an int. I should change that.

**Comment by HowardLoTW** [comment]
@macdonst @jopelkey ,
Yap, I've noticed that the stacked sample in doc uses integer id rather than string.
So I also tested it with a given integer id by replacing `uniqid()` with `parseInt(id)` but it didn't work either.

**Comment by macdonst** [comment]
@HowardLoTW when I use:

```
var message = new gcm.Message({
        "data" : {
            "notId" : 1,
            "title" : notification.title || "Emotion Push",
            "image" : notification.image || 'icon'
        }
    });
```

and 

```
var message = new gcm.Message({
        "data" : {
            "notId" : 2,
            "title" : notification.title || "Emotion Push",
            "image" : notification.image || 'icon'
        }
    });
```

I get two separate entries in my notification shade.

**Comment by HowardLoTW** [comment]
Hello, I've tested your code, and it works.
But originally, the "notId" is given by facebook ID, like this "576935779129298" ( and I formatted to `int` ),
and this doesn't work. Is it because of the number was too large ?

**Comment by ericb** [comment]
@HowardLoTW Yes, that is well outside the range of a normal integer value. Until the plugin supports string values, you could attempt to use the last 5 or so digits of the facebook id. (This assumes the facebook ids are unique to any given message)

**Comment by HowardLoTW** [comment]
Yes, I eventually solve this by setting `notId` as `parseInt(facebookId) % 100000` to prevent the number out of range.

I think `notId` need to support string values in the future.

**Comment by macdonst** [comment]
@HowardLoTW I agree. Planned for the next minor release or possibly a bug fix release as this is a trivial change.

**Comment by macdonst** [comment]
@HowardLoTW actually, I can't change this. The NotificationManager.cancel() method takes an `int` as a parameter. So we'll just have to make sure that it is a valid int.
