### ISSUE TITLE
init options should include "categories" option for ios

### ISSUE THREAD

**Issue by jcesarmobile** [phonegap/phonegap-plugin-push#712]
Current API.md docs show this init options for ios
ios.alert
ios.badge
ios.sound
ios.clearBadge

I think ios.categories should be mentioned there too, right now it's "hidden" on https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons-1

**Comment by miparnisari** [comment]
There is an  inconsistency between https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons-1 and https://github.com/phonegap/phonegap-plugin-push/blob/efdef52deec4f7e8b6b4ee87460bd87cc0479c74/docs/API.md. 

The first link says that "categories" should be an object. The second says that it should be an array.

**Comment by fredgalvao** [comment]
@miparnisari You're right. According to [this line](https://github.com/phonegap/phonegap-plugin-push/blob/6b2f3ee981235de127758012059ee3d10e40e709/src/ios/PushPlugin.m#L225), which I can barely read (not fluent in Objective-C), it seems like the object/dictionary notation is the expected one.
If @macdonst or @jcesarmobile can confirm this, we can update the docs accordingly.

**Comment by jcesarmobile** [comment]
Yes, a javascript object translates to NSDictionary on iOS

**Comment by miparnisari** [comment]
I thought so :) Thanks.

Is there something else we need to take into account for this? I'm using node APN to send a "category" of buttons to show in iOS, and debugging on the client I can see that it arrives to the device, and I've already set up the categories, but still the action buttons don't show.

**Comment by fredgalvao** [comment]
Fixed in 0a93fab9cec5ac2a2b813090958054e8e7b15f9a.

**Comment by fredgalvao** [comment]
@miparnisari  If after sending the correct notation it's still not working for you, my best bet would be to create a new issue with detailed info on your scenario so we can try to reproduce/solve.

**Comment by miparnisari** [comment]
Ok, thanks!
