### ISSUE TITLE
Is this plugin suppose to activate an Android app from coldstart?

### ISSUE THREAD

**Issue by netomia** [phonegap/phonegap-plugin-push#718]
Nothing seems to happen when I send a push to my Android app which is closed. The push arrives, but the on('notification') is not called.

I tried this on Android 5 and 6. With and without "content-available": "1".

**Comment by macdonst** [comment]
@netomia do you mean your app was forced closed, ie killed from task
launcher?

**Comment by netomia** [comment]
Yes, if the app is not running - ie force-closed or never activated from boot.

**Comment by macdonst** [comment]
Duplicate of #158
