### ISSUE TITLE
Anyone using it with Ionic / Ionic 2 ?

### ISSUE THREAD

**Issue by ahlidap** [phonegap/phonegap-plugin-push#719]
### Expected Behaviour

Working Push Notifications on Device using Ionic 2 Framework

### Actual Behaviour

I got RegID, but no notification is received.

#### Steps to Reproduce 

I've added both phonegap-plugin-push and facebook-connect4 as stated in documentation.
No error during compile.

#### Platform and Version

Android 5.1.1

#### (Android) What device vendor
One Plus X 

#### Cordova CLI version and cordova platform version

Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.4 LTS 
Node Version: v4.4.0

#### Plugin version

    1.6.0

#### Sample Push Data Payload

```
{
    "to": "f4xTmGFDTac:APA91bHDen_1JJN4H3jGlDDz2z9mGn6RLOg2nrXc-ocLniHESFi8IloGFth8Et8Il87KuxbeC-8wJFCu0k1Sf4TQoYu7n8sEMChcofTtaMAlcoAOelQTrc1HXDWb8dOijDcO7k9c1xeL",
    "data": {
      "placeId" : 407,
      "image": "http://gintonico.com/content/uploads/2015/03/fontenova.jpg",
      "title": "Fonte Nova Esplanada",
      "style": "picture",
      "picture": "http://media5.letsbonus.com/products/285000/285006/14014409744462-0-1700x690.jpg",
      "message": "Venha provar os nossos Gins",
      "summaryText": "Venha provar os nossos Gins"
     }
  }
```

#### Sample Code that illustrates the problem

```
initializeApp() {
    this.platform.ready().then(() => {

      console.log('DEVICE IS READY')
      console.log(device.uuid);

      var pushNotification;
      // PUSH NOTIFICATION PLUGIN INIT
      pushNotification = PushNotification.init({
          android: {
              senderID: "0123456789"
          }
      });

      pushNotification.on('registration', function(data) {
          localStorage.gcm = data.registrationId;
          console.log("SUPER GCM_ID = " + data.registrationId); 
      });
      pushNotification.on('notification', function(data) {
          // Foreground
          if (data.additionalData.foreground) {
              console.log('foreground');
              //buildPush(data);
          }
      });
      pushNotification.on('error', function(e) {
          console.log('PUSH PLUGIN ERROR: ' + e.message);
      });
      console.log('END DEVICE PUSH REGISTER'); 
    });
  }
```

#### Logs taken while reproducing problem

I can get regId with no problem.
But a notification is never received on device (background or foreground).

console.log
```
DEVICE IS READY
END DEVICE PUSH REGISTER
SUPER GCM_ID = eT9dgSIiAs8:APA91bGBSbZOSt29oD2yLTS85PcyLGcuVWr3OGBulpoLmMaZrAJQ4Y8ceC0GA3seSUVA2lPbzoFJhT9KkAYd1l0BAwQQtXGGldHExsHnyrOJnkLjtwLrJGk7MvkfeobPoGqvYcqWZYrn
```

**Comment by ahlidap** [comment]
Hi,

my mistake, It's working correctly.
As I used to use PhonegapBuild, my keystore file was always uploaded and password inserted.

Now building locally with ionic I was just using debug version for testing this.
Now after sign and zipalign the apk everything is ok.


Sorry for the false problem.

**Comment by macdonst** [comment]
@ahlidap no problem. You can always close your issues in the future if you find they are incorrectly diagnosed.

**Comment by victorcarvalhosp** [comment]
What I nedd to do to see the plugin version?

**Comment by MAEVE007** [comment]
Push.init({
        android: {
          senderID: "YOUR_SENDER_ID"
        },

when i run command on gitbash i.e. ionic run android
The upper code is causing error : **Property 'init' does not exist on type 'typeof `Push'.**```


Please guide me with the reasonn and solution for the error.

Thank you.

**Comment by fredgalvao** [comment]
@MAEVE007 Where did you get that `Push` object from? This plugin exports an object with the name `PushNotification`, not `Push`.
If you're getting that from a 3rd party lib, like `ionic native`, then you should tell **them** that it's not working properly.

**Comment by sayanbrainium** [comment]
Hi,
I am using your code but getting error at  "PushNotification.init".
Can you please share the full code with plugin installed and set up in component and module.ts file
Thanks
Sayan
