### ISSUE TITLE
After unregister, doesn't fire registration event again

### ISSUE THREAD

**Issue by fanfavorite** [phonegap/phonegap-plugin-push#720]
I am using PhoneGap Build and looking to have notifications register when someone logs in. When I first install the app, I hit the login page (index.html). When they successfully log in, they go to home.html. On home.html, in the device ready event, it triggers the registration function. When I log out, it triggers the unregister function and completes. When I log back in, it doesn't call the registration function again on home.html.

### Expected Behaviour
I thought that the unregister event would call the register event again when logging back in.

### Actual Behaviour
The register event does not get called again.

### Reproduce Scenario (including but not limited to)
Setup a normal static page (index.html) and then link to another page (home.html) that has the initialization and registration event call. Have a logout button that calls the unregister function and redirects to index.html. Try to go back to home.html and it won't trigger the registration call.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
    iOS 9.2.1

#### Cordova CLI version and cordova platform version
    cordova --version                                    6.0.0
    cordova platform version ios                   4.0.1

#### Plugin version
    cordova plugin version | grep phonegap-plugin-push   1.6

#### Sample Push Data Payload
```
//place at top of page or in javascript file
var push; 

//place in device ready
push = PushNotification.init({
	"android": {
		"senderID": "XXXXXXXXX"
	},
	"ios": {
		"alert": "true",
		"badge": "true",
		"sound": "true"
	}
});
			
push.on('registration', function(data) {
	alert('registration called');
});

//place in a function of click event
push.unregister(function(){
	alert('unregistered successfully');
	window.location.href = 'index.html';
},function(){
	alert('unregistering failed');
	window.location.href = 'index.html';
});
```

**Comment by fanfavorite** [comment]
How does unregister work? Maybe I am misunderstanding the function? My assumption is that it would remove any notification settings, so they can be reset. This isn't the case and the notifications are still all setup in the settings on the iPhone. Any help would be appreciated. Thanks.

**Comment by vousys** [comment]
maybe you may have this unregister code inside of your "onDeviceReady" function

**Comment by macdonst** [comment]
@fanfavorite no unregister does not remove the notification settings, it just invalidates the registration token. If you want to fully reset the push settings on an iOS device for an app you'll have to follow this tech note:

https://developer.apple.com/library/ios/technotes/tn2265/_index.html#//apple_ref/doc/uid/DTS40010376-CH1-TNTAG42

Does that answer your question?

**Comment by fanfavorite** [comment]
Yes it does, thanks for the clarification. The register event is firing as well.

**Comment by macdonst** [comment]
@fanfavorite if you don't mind me asking, since I've seen a few people make the same mistake recently where did you get the idea to put the unregister command after init? Were you following a tutorial?

**Comment by fanfavorite** [comment]
I have always had it in a click event with my logout button, my issue was a misunderstanding of how unregister should work. My code was actually correct and doing what it should, but I was using the initial register notification message as a sign that the register event was working. I can see why people do make a mistake with putting unregister after init though. They follow the same structure of the register event, not thinking that its a function and not an event.
