### ISSUE TITLE
failed cordova build after add latest push plugin

### ISSUE THREAD

**Issue by bobolat** [phonegap/phonegap-plugin-push#721]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'. com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_05\bin\java.exe'' finished with non-zero exit value 1

i got this error after add push plugin
platform android 5.1.1
cordova CLI 6.0

**Comment by macdonst** [comment]
@bobolat what comes before the error? That is usually the more descriptive part of the log. What other plugins are you using?

**Comment by bobolat** [comment]
@macdonst i didnt use any plugin except the deafult one whitelist ..what do you mean "what comes before the errror"?

**Comment by bobolat** [comment]
fixed..just add sender id at config and json package

**Comment by bobolat** [comment]
REOPEN
sorry..i thought it was fixed..but not on android M..i try on android M which is android 6 it keep throwing this error
"Uncaught ReferenceError: module is not define push plugin"
if i install my apps on android below 6 its working fine

**Comment by macdonst** [comment]
@bobolat I can't reproduce this on Android 6. Can you do a:

```
phonegap plugin rm phonegap-plugin-push
phonegap plugin add phonegap-plugin-push --variable SENDER_ID="XXXXXXX" --save
```

and see if you can reproduce the problem.

**Comment by bobolat** [comment]
@macdonst i allready do that..and put sender id into config also package.json file..i can build already right now..the problem is when i run the apps it cant get the token..i got that error on chrome inspect
"Uncaught ReferenceError: module is not define push plugin"

**Comment by macdonst** [comment]
@bobolat when are you calling PushNotification.init?

**Comment by bobolat** [comment]
@macdonst when in device ready fired

**Comment by macdonst** [comment]
@bobolat can you make sure that `<project name>/platforms/android/assets/www/plugins/phonegap-plugin-push/www/push.js` exists?

**Comment by bobolat** [comment]
of course it exist dude..because on lower than android 6, push notification not have problem..only in android 6 it problem..haha..i dont know what to do..

**Comment by mohanchalla** [comment]
Even I am also facing with same issue push notifications are not working in android 6. Does anyone got the solution (:-

**Comment by macdonst** [comment]
@mohanchalla can't reproduce. Tested yesterday on 2 different phones running Android 6.

**Comment by mohanchalla** [comment]
@macdonst Thank you for reply. I am having push plugin 2.5.0 which is deprecated and my cordova is upgraded to 6.0. Should I need to update my plugin to the newer version of push notification.
This is my plugin info
<plugin xmlns="http://www.phonegap.com/ns/plugins/1.0"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:amazon="http://schemas.android.com/apk/lib/com.amazon.device.ads"
    xmlns:rim="http://www.blackberry.com/ns/widgets"
    id="com.phonegap.plugins.PushPlugin"
    version="2.5.0">

**Comment by mohanchalla** [comment]
@macdonst I have installed the new phonegap-plugin-push-1.6.0 plugin. If you don't mind, could you please explain me how to use this new plugin with cordova that way I have used with older plugin. After I upgrade to new plugin it is giving the following error.
$window.plugins.pushNotification - pushNotification is not defined.
Earlier with the older plugin I used register the device with the following code the same code is not working for new plugin.
$cordovaPush.register({
	"senderID": "XXXXXX"
}).then(function(result) {
//saving the device id for future use.
});

$rootScope.$on('pushNotificationReceived', function(event, notification) {});

**Comment by macdonst** [comment]
@mohanchalla I don't support PushPlugin 2.5.0 that plugin is dead. If you've upgrade to phonegap-plugin-push you need to migrate to the new API which is explained in the docs and in my push workshop.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md
http://macdonst.github.io/push-workshop/

**Comment by mohanchalla** [comment]
@macdonst I have incorporated new plugin with my senderID by calling init method.  But push. On('register')  event never called.  What is the extra config that I am missing.  Thank you :)

**Comment by macdonst** [comment]
@mohanchalla I don't have a clue, I don't even know what platform you are running.

**Comment by mohanchalla** [comment]
@macdonst I developing app for android and my cordova version is 6.

**Comment by macdonst** [comment]
@mohanchalla run `adb logcat | grep PushPlugin` when you start your app and try and reproduce the problem.

**Comment by macdonst** [comment]
@bobolat Did this get resolved for you?

**Comment by eduardoaw** [comment]
What happens is that android possess the limitation of 64k method references, the adiconar some plugins you can easily reach it. Also esbarei the same error. Here is a good material to solve this https://developer.android.com/studio/build/multidex.html

**Comment by bobolat** [comment]
@macdonst i forgot already..haha..can close i think
