### ISSUE TITLE
iOS - Via GCM registration ID generated but push messages not receiving

### ISSUE THREAD

**Issue by akilah007** [phonegap/phonegap-plugin-push#722]
iOS - Via GCM registration ID generated but push messages not receiving

**Comment by macdonst** [comment]
@akilah007 please provide the info necessary to debug. https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by akilah007** [comment]
![image](https://cloud.githubusercontent.com/assets/6467916/13879381/3370a1a8-ed3d-11e5-870d-0ee8f74d279d.png)

Can't seem any errors on debug.

**Comment by akilah007** [comment]
Success Message from GCM

![image](https://cloud.githubusercontent.com/assets/6467916/13879465/974b3332-ed3d-11e5-9d69-261bee625f3d.png)

**Comment by akilah007** [comment]
Solved

**Comment by FutoRicky** [comment]
@akilah007 how did you manage to successfully generate registration id for ios? I am using gcm also

**Comment by akilah007** [comment]
Yeh.. Just install Plugin with GCM Sender ID
`cordova plugin add phonegap-plugin-push --variable SENDER_ID="GCM_SENDER_ID"`

**Then set push like this**
```
var push = PushNotification.init({
    ios: {
        senderID: "GCM_SENDER_ID",
        alert: "true",
        badge: "true",
        sound: "true"
    }
});

push.on('registration', function(data) {
    console,log(data.registrationId)
});
```
