### ISSUE TITLE
Is there any way to listen for notification clicks?

### ISSUE THREAD

**Issue by gauravarora** [phonegap/phonegap-plugin-push#725]
I have a simple question. Is there anyway I can know, within my app, that the user has clicked a notification?

**Comment by macdonst** [comment]
@gauravarora you mean besides the fact your app gets opened and the `on('notfication')` event listener is called?

**Comment by gauravarora** [comment]
I thought the listener was called when the notification arrived and not
when the user clicks it. Is this not the case?

**Comment by macdonst** [comment]
@gauravarora if you included the `content-available: 1` property in your push message it will force the `on('notfication')` handler to be called even when the app is in the background. The `on('notfication')` handler will be called again when the user clicks on your notification.

**Comment by gauravarora** [comment]
Thank you. I did not know that the handler is also called when the user
clicks the notification. I shouldn't have assumed that it's only called
when the notification arrives.

**Comment by macdonst** [comment]
@gauravarora it will only be called when the user clicks on the notification if you don't supply the `content-available: 1` property. Read more about **Background Notifications** in the docs.

I'm going to close this issue, re-open if that is in error.
