### ISSUE TITLE
Unable to compile from build.phonegap.com - malformed config.xml

### ISSUE THREAD

**Issue by vousys** [phonegap/phonegap-plugin-push#726]
Hi I'm unable to compile it from https://build.phonegap.com/

this is my config.xml

```
    <preference name="permissions" value="none"/>
    <preference name="DisallowOverscroll" value="true" />
    <preference name="phonegap-version"  /> <!--  value="cli-5.2.0"  andaba bien: 3.7.0 !-->
    <preference name="android-maxSDKVersion" value="" />
    <preference name="android-targetSdkVersion" value="12" />  
    <preference name="orientation" value="auto" />
    <preference name="target-device" value="universal" />
    <preference name="fullscreen" value="false" />
    <preference name="android-minSDKVersion" value="17" /><!-- min android version: 4.2 !-->
    <preference name="android-installLocation" value="auto" />
    <preference name="show-splash-screen-spinner" value="true" />
    <preference name="auto-hide-splash-screen" value="true" />
    <preference name="splash-screen-duration" value="2500" />
    <preference name="exit-on-suspend" value="true" />
    <preference name="load-url-timeout" value="25000" />
    <preference name="deployment-target" value="8.0" /> <!-- min iOS version 7 !-->
    <preference name="android-build-tool" value="gradle" />
     
  	<!-- para el fileupload !-->
	<preference name="AndroidPersistentFileLocation" 		value="Internal" />
	<preference name="AndroidPersistentFileLocation" 		value="Compatibility" />
	<preference name="iosPersistentFileLocation" 			value="Library" />
	<preference name="iosPersistentFileLocation" 			value="Compatibility" />
	<gap:plugin name="cordova-plugin-file"  				source="npm" />	
	<gap:plugin name="cordova-plugin-file-transfer"  		        source="npm" />	
	<access origin="cdvfile://*" />
	<preference name="iosExtraFilesystems" 					value="library,library-nosync,documents,documents-nosync,cache,bundle,root" />
	<preference name="AndroidExtraFilesystems" 				value="files,files-external,documents,sdcard,cache,cache-external,root" />

  	<!-- para el fileupload !-->
 	<gap:plugin name="ionic-plugin-keyboard"     				               source="npm"	/>
   	<gap:plugin name="cordova-plugin-splashscreen"              version="2.1.0" source="npm" />
	<gap:plugin name="cordova-plugin-whitelist"                 version="1.0.0"       source="npm" />
	<gap:plugin name="cordova-plugin-contacts"  						source="npm" />
	<gap:plugin name="cordova-plugin-x-socialsharing" 					source="npm" /> 
	<gap:plugin name="cordova-plugin-geolocation"               version="1.0.1"     source="npm" />
	<gap:plugin name="cordova-plugin-calendar"              	                                 source="npm" />
	<gap:plugin name="cordova-plugin-device"                                                    source="npm" />
	<plugin name="phonegap-plugin-push"                                                          source="npm" />
	    <param name="SENDER_ID" value="700551245280" /> 
	</plugin>
  
    <access origin="tel:*" launch-external="yes" /> 
    <access origin="geo:*" launch-external="yes" />
    <access origin="*"/>
```
The error is :  "malformed config.xml"  and no compile.

If I remove this plugin
```
	<plugin name="phonegap-plugin-push" source="npm" />
	    <param name="SENDER_ID" value="700551245280" /> 
	</plugin>
```
it's compile fine

In my code I've this lines 

```
function onDeviceReady() {

		var push = PushNotification.init({
		    android: {
		        senderID: "700551245280"
		    },
		    ios: {
		        alert: "true",
		        badge: "true",
		        sound: "true"
		    },
		    windows: {}
		});

}

```

**Comment by NoahYarian** [comment]
Maybe try making the opening plugin tag not self-closing? I haven't even used this plugin... just passing through, so don't take my word for it. That's not valid xml though.
```
<plugin name="phonegap-plugin-push" source="npm">
    <param name="SENDER_ID" value="700551245280" />
</plugin>
```

**Comment by macdonst** [comment]
@vousys the comment by @NoahYarian is correct. Both of your examples are invalid XML. Make it look like @NoahYarian and it should work fine. Re-open this bug if that does not fix it.

**Comment by vousys** [comment]
Hi Noah and Simon thanks guys, so please correct this line in the example:
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md

because it says:

<preference name="android-build-tool" value="gradle" />
<plugin name="phonegap-plugin-push" source="npm">
    <param name="SENDER_ID" value="<Your Sender ID>" />
</plugin>



​
Salu2!

Vero | *VOUSYS.com*
<http://www.vousys.com/>

VOUSYS.com Office: Buenos Aires, Argentina | +54.011.5231-2082

http://www.vousys.com     [image: Facebook]
<https://www.facebook.com/vousys> [image: Twitter]
<http://www.twitter.com/vousys> [image: Google Plus]
<https://plus.google.com/u/0/b/111673332818765301661/+Vousys/posts> [image:
Pintrest] <http://www.pinterest.com/vousys/> [image: Skype]
<https://www.vousys.com/> <https://www.vousys.com/exportador>
<http://www.tusfacturas.com.ar/> <http://www.e-xpensas.com/>
<http://www.micampeonato.com/>




2016-03-19 13:26 GMT-03:00 Noah Yarian <notifications@github.com>:

**Comment by macdonst** [comment]
@vousys what is wrong with that example?

**Comment by vousys** [comment]
Simon, execuse me i've found my mistake. Your example was OK, stupid me
i'll delete this issue. Execuse me  for bother you


​
Salu2!

Vero | *VOUSYS.com*
<http://www.vousys.com/>

VOUSYS.com Office: Buenos Aires, Argentina | +54.011.5231-2082

http://www.vousys.com     [image: Facebook]
<https://www.facebook.com/vousys> [image: Twitter]
<http://www.twitter.com/vousys> [image: Google Plus]
<https://plus.google.com/u/0/b/111673332818765301661/+Vousys/posts> [image:
Pintrest] <http://www.pinterest.com/vousys/> [image: Skype]
<https://www.vousys.com/> <https://www.vousys.com/exportador>
<http://www.tusfacturas.com.ar/> <http://www.e-xpensas.com/>
<http://www.micampeonato.com/>




2016-03-19 21:58 GMT-03:00 Simon MacDonald <notifications@github.com>:
