### ISSUE TITLE
No sound and no vibration on notification

### ISSUE THREAD

**Issue by Gp2mv3** [phonegap/phonegap-plugin-push#73]
Hi,
I updated my app to use this plugin and it works fine, except that the app doesn't emit any sound nor it vibrates at the reception of a notification. The notification is however displayed correctly so it's received.
I'm using Cordova 5.2.0 with the last version of the plugin (1.1.1) and it happens on Android and iOS. I'm testing on iOS 8.2 and Android 5.0.

Is there a specific parameter to pass ?

Thanks,

Gp2mv3

**Comment by lucasabba** [comment]
1)Try with option sound with value "default" when you send push notification.
2)Another test: on iPhone go to settings, push notification, select your app and check if there is sound option and if there is check that is enable
3) what iOS versions have you on your iPhone/iPad/iPod touch 


(Sorry for my English level)

**Comment by Gp2mv3** [comment]
1) Already tried with "default", and "true" but it doesn't change anything
2) There is only "Badges", so I've to register the notification differently ?
3) Oops sorry completely forgot to mention (I'll edit the post), iOS 8.2 but as it's also reproducible on Android, I don't think it matters so much.

**Comment by lucasabba** [comment]
Reading answer to point 2 I think that the problem is during push notification register with APNS and Google service because the app don't register sound option in device. When it was release plugin versions that you are using? Because I have your same problem with iOS 9 but with iOS 8.4 everything work, I'm using latest Cordova version. I haven't android versions

**Comment by Gp2mv3** [comment]
I added the plugin today via cordova plugin add phonegap-plugin-push, and the plugin.xml files says v1.1.1.

**Comment by lucasabba** [comment]
After dinner I will check my plugin version so we can check to resolve this
problem. (Now is 6.30 p.m. Where I live)
Il giorno sab 22 ago 2015 alle 18:31 Nicolas Cognaux <
notifications@github.com> ha scritto:

**Comment by Gp2mv3** [comment]
Same here (for the hour).

Thanks a lot !

**Comment by lucasabba** [comment]
Sorry for later. I have plugin version 1.1.1, today i try to install app on an iOS device with iOS 8.4.x and i have your same problem! My push notification is without sound (and vibration) not only with iOS 9 but also with iOS 8.x! Someone can help us?

**Comment by vasilyz81** [comment]
I can confirm that have got the same issue. It would be good to get it solved as soon as possible please.

**Comment by lucasabba** [comment]
What does it mean labels "question" and "docs"? thanks

**Comment by macdonst** [comment]
@lucasabba "question" just reminds me to come back to this issue and answer your questions and "docs" means I should update the readme.

**Comment by lucasabba** [comment]
Thank you! we wait for your solution!

**Comment by macdonst** [comment]
@lucasabba just dropped my daughter off, heading into work and will look at it today. If you and @Gp2mv3 could post a gist that reproduces your issue, I would appreciate it. Sure helps with debugging.

**Comment by lucasabba** [comment]
Yes, of course, thanks to you!
Ok, my situation (iOS 8.x & 9) is this
When i accept the push notification in push notification setting from iOS setting there aren't options to enable push sound and vibration. in the first attachment you can see iOS push setting of the app that i'm developing, in the second the iOS push setting of another random app that i just download from the app store. How you can see there is sound option (called "suoni") in the push setting of app download from the app store but not in the app that i'm developing. So when i received push from my app i see push but without sound and vibration
![20150824060144](https://cloud.githubusercontent.com/assets/6008112/9440653/1484386e-4a71-11e5-8b08-a146241ca450.jpg)
![20150824060133](https://cloud.githubusercontent.com/assets/6008112/9440656/166cdbcc-4a71-11e5-9188-5648d67b7661.jpg)

**Comment by T18970237136** [comment]
Hi,
I'm having the same issue on an iPad with iOS 8.4 (12H143) when using this plugin (unstable branch from today) with Cordova 5.1.1: The message is shown in the notification bar, but no sound is played and there is no vibration. On android with GCM, however, a sound is played and the phone vibrates.

For iOS, I send the following JSON message payload to APNS, specifying a priority of 10 in the message frame):
```javascript
{
  "aps": {
    "alert": {
      "title": "Client1",
      "body": "Hi, this is a test."
    },
    "sound": "default"
  }
}
```

When I open the system settings and go to the application, it shows options for "Allow notifications" with suboptions like "Show in notification center: 5, badge icon, show on lock screen" but no options for sound, just like in the screenshot fom @lucasabba 

Thanks!

**Comment by macdonst** [comment]
Update for those of you testing 1.1.1 on Android there is no default sound or vibration. As of the 1.2.0 version (schedule for August 26th) it will play the default sound and vibration. You can tell your app not to use the defaults by specifying false to the android sound and vibration options. See readme for more details.

Going to plug in my iOS device now.

**Comment by macdonst** [comment]
iOS users I am testing on my iPhone 6+ running iOS 8.4.1. 

I hear no sound when I send the following:

```
{
  "aps": {
    "alert": {
      "title": "Client1",
      "body": "Hi, this is a test."
    }
  }
}
```

I hear the default sound when I send the following:

```
{
  "aps": {
    "alert": {
      "title": "Client1",
      "body": "Hi, this is a test."
    },
   "sound": "default"
  }
}
```

I hear the default sound when I send the following when the referenced sound file does not exist:

```
{
  "aps": {
    "alert": {
      "title": "Client1",
      "body": "Hi, this is a test."
    },
   "sound": "some-non-existent-file.caf"
  }
}
```

And finally it plays the `sub.caf` file from my /Resources directory when I send:


I hear the default sound when I send the following:

```
{
  "aps": {
    "alert": {
      "title": "Client1",
      "body": "Hi, this is a test."
    },
   "sound": "sub.caf"
  }
}
```

When I look in the notification settings my app shows the following"

![img_0069](https://cloud.githubusercontent.com/assets/353180/9446325/074cd046-4a5f-11e5-9fb6-b5f639718c71.PNG)

**Comment by macdonst** [comment]
**IMPORTANT** **IMPORTANT** **IMPORTANT**

On both iOS and Android the sound will not be played when you are in the app. When you are in the app the notification event will contain a `data.sound` property and it is up to you whether or not you want to play this sound to the user.

When the app is in the background or closed the sound value that you send along with the push notification will be played by the OS if it is available.

**Comment by lucasabba** [comment]
i already use 

{
  "aps": {
    "alert": {
      "title": "Client1",
      "body": "Hi, this is a test."
    },
   "sound": "default"
  }
}

but the problem is that in push setting audio option not exist and also "alert style when unlocked" not exist

**Comment by macdonst** [comment]
@lucasabba what version of PhoneGap?

**Comment by lucasabba** [comment]
How can I see phonegap version?

**Comment by macdonst** [comment]
@lucasabba Run `phonegap --version` or `cordova --version`. It depends on what CLI you use.

**Comment by lucasabba** [comment]
my version is 5.1.1, thanks for your help!

**Comment by lucasabba** [comment]
i need to update something? thanks

**Comment by macdonst** [comment]
@lucasabba No, versions 5.1.1 should be fine. I'm at a bit of a loss as to why you aren't seeing the sound option. I know the next bit may seem crazy but give it a try:

- Uninstall the app from your phone
- Reboot
- Now set the phone date ahead at least two days
- Reboot
- Set the date back to normal
- Re-install the app

See if that clears things up.

**Comment by lucasabba** [comment]
i tryed, situation not change. in net day i will try to create a new project to make another test and i will tell you. Thanks for all

**Comment by vasilyz81** [comment]
Hi @macdonst I can confirm that after using v1.2.0 on Android 4.4.2+ the vibration and default sound work absolutely fine with push notifications. I really appreciate your hard work.

**Comment by lucasabba** [comment]
If I create a new project you think that can I resolve the problem?
Thanks

**Comment by lucasabba** [comment]
I also tried to update phonegap/Cordova but situation not change

**Comment by macdonst** [comment]
@vasilyz81 great to hear.

@lucasabba if I could reproduce your problem I'm sure I could fix it

**Comment by lucasabba** [comment]
Thanks but k don't know how help you to reproduce my problem

**Comment by Deathspike** [comment]
@lucasabba I had the same issue. In my case, it was a combination of two things: first, as you mentioned, you have to send a `sound`: `default` in the `aps` dictionary in the push message. If you don't send a `sound`, nothing is played. Secondly, your application needs to get the permissions from the user during initialization, as the screenshots of @macdonst show. It's quite simple, in the `init` call pass `sound: true` in the `ios` options. This is not documented though, and really ought to be.

A more complex example that I currently use for initialization:

    var push = PushNotification.init({
      android: { senderID: 'xxxxxx' },
      ios: { sound: true },
      windows: {}
    });

Reference: https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/PushPlugin.m#L73

**Comment by T18970237136** [comment]
Hi,
@Deathspike thanks a lot! After I included the "sound: true" parameter, the sound finally worked in iOS. The "notification" settings of the app now includes the "Sound" setting (while the "alert style" on @macdonst's screenshot is not shown):
![Notification Settings](http://fs2.directupload.net/images/150910/kjwr3k7j.png)

**Comment by Deathspike** [comment]
That's the `alert` setting. Like this:

    var push = PushNotification.init({
      android: { senderID: 'xxxxxx' },
      ios: { alert: true, sound: true },
      windows: {}
    });

For what it's worth, there is also a `badge` setting in case you want to set badges.

**Comment by macdonst** [comment]
Readme and example updated.

**Comment by lhoezee** [comment]
@vasilyz81 Did your issue get resolved. I seem to still have a problem with Android playing a sound. I thought perhaps it was just Android 5.1.1, but I'm having the same problem with Android 4.2.2. I'm also using Cordova version 5.1.1.

**Comment by lhoezee** [comment]
@vasilyz81 looks like I got it working. I did the following:

Removed the plugin:
```
cordova plugin rm phonegap-plugin-push
```

Installed the new one by tagging the latest version:
```
cordova plugin add phonegap-plugin-push@1.2.3
```
I now have sound on my notifications.

**Comment by roysG** [comment]
i am using version 1.3.0  and i do not have any sound on notification in background.

what to do??

**Comment by gongfan99** [comment]
My app can receive notificatioin in shade but does not emit sound and vibration. The received notifications do not collapse in shade. I use Cordova 5.4.1 CLI to build the app. My config.xml is like:

```
<?xml version='1.0' encoding='utf-8'?>
<widget id="xxxxxxx" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>xxxxxx</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <icon src="icon.png" />
    <plugin name="cordova-plugin-device" />
    <plugin name="cordova-plugin-vibration" />
    <plugin name="cordova-plugin-splashscreen" />
    <plugin name="cordova-plugin-file" />
    <plugin name="cordova-plugin-file-transfer" />
    <plugin name="cordova-plugin-media" />
    <plugin name="cordova-plugin-dialogs" />
    <plugin name="cordova-plugin-network-information" />
    <plugin name="cordova-plugin-battery-status" />
    <plugin name="phonegap-plugin-push" spec="1.5.1" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
        <splash src="splash.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
</widget>
```

The same app, if built with phonegap build, can emit sound/vibration and notifications collapse in tray.

**Comment by gongfan99** [comment]
When I look at the build log, some difference exists on some libraries' version.

Phonegap Build:
```
:prepareComAndroidSupportSupportV132310Library
:prepareComAndroidSupportSupportV42310Library
:prepareComGoogleAndroidGmsPlayServicesBase810Library
:prepareComGoogleAndroidGmsPlayServicesBasement810Library
:prepareComGoogleAndroidGmsPlayServicesGcm810Library
```

My local cordova:
```
:prepareComAndroidSupportSupportV132311Library UP-TO-DATE
:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBase840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBasement840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesGcm840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesMeasurement840Library UP-TO-DATE
```

**Comment by JaydeepPatel** [comment]
i want only vibrate no sound . so which dictionary i set ?
Thank x in advance.
