### ISSUE TITLE
Uncaught ReferenceError: PushNotification is not defined

### ISSUE THREAD

**Issue by AdriVanHoudt** [phonegap/phonegap-plugin-push#730]
### Expected Behaviour

PushNotification is a global object after deviceReady

### Actual Behaviour

PushNotification is undefined

#### Steps to Reproduce 

Upgrade from 1.5.x to 1.6.0

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 5.1.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

One Plus One

#### Cordova CLI version and cordova platform version

Phonegap --version 6.0.1
window.cordova.version 5.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.6.0

#### Sample Push Data Payload
/
#### Sample Code that illustrates the problem

```js
notificationService = PushNotification.init({
                android: {
                    senderID: config.gcm,
                    icon: 'notification', // must match a png in platforms/android/res/drawable-[dpi] folder
                    iconColor: '#33B5E5', // background color
                    clearNotifications: false,
                    forceShow: true
                },
                ios: {
                    alert: true,
                    badge: true,
                    sound: true,
                    clearBadge: false,
                    forceShow: true
                }
            });
```
#### Logs taken while reproducing problem
/

**Comment by thubold** [comment]
For my iOS device too (iPhone 4s with iOS 9.0.1) 
I'm using phonegap build with cli 5.2.0.
Android is still working for me. (Android 4.4.2 - Samsung Galaxy S5)

**Comment by macdonst** [comment]
@AdriVanHoudt did you add the SENDER_ID param in config.xml?

**Comment by rayshan** [comment]
I had the same issue after upgrading from 1.4 (I think) to 1.6. It's resolved after adding `SENDER_ID` to both `config.xml` and `package.json` (not using ionic):

```
    <plugin name="phonegap-plugin-push" spec="~1.6">
        <variable name="SENDER_ID" value="xxx" />
    </plugin>
```

```
  "cordovaPlugins": [
    {
      "variables": {
        "SENDER_ID": "XXXXXXX"
      },
      "locator": "phonegap-plugin-push"
    }
  ]
```

**Comment by AdriVanHoudt** [comment]
No? It was not in the changelog? It should be in both code and config.xml?

**Comment by macdonst** [comment]
@AdriVanHoudt yeah, it was added to the Install docs. https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation

Basically, I want to move that out of init and I want people to get used to it before 2.0.0.

**Comment by AdriVanHoudt** [comment]
I see, I can use @rayshan's solution to put it in my config.xml?

**Comment by macdonst** [comment]
@AdriVanHoudt yes, if you do:

```
phonegap plugin rm phonegap-plugin-push
phonegap plugin add phonegap-plugin-push --variable SENDER_ID="XXXXXXX" --save
```

it will do the work for you.

**Comment by macdonst** [comment]
Closing as I believe this is resolved. Re-open if that is not the case.

**Comment by AdriVanHoudt** [comment]
:+1: will test on out next release

**Comment by chrillewoodz** [comment]
Still happens.

**Comment by BlindJerobine** [comment]
Still happens here, too
