### ISSUE TITLE
Strange issue while debugging in Safari Inspector

### ISSUE THREAD

**Issue by gerhardsletten** [phonegap/phonegap-plugin-push#733]
I experience a very strange issue when I inspect an app the Safari Inspector. If the inspector is open, the app is never rendered (nothing is rendered to the document) and the Memory view in xcode shows a fast increasing memory consumption. 

![image](https://cloud.githubusercontent.com/assets/63344/13921170/e0fa72d2-ef76-11e5-9b2f-939c94f6d737.png)
 
To the debug the init of the push-plugin, I insert a alert() before the main.js is loaded:

```
<script src="cordova.js"></script>
<script>alert('test')</script>
<script src="main.js"></script> 
```

There are no errors in the console.

If I comment out the PushPlugin.init() the app starts as it should, and there is no issue with high memory usage.

Usage stack:
Tarifa 0.15.0 (cordova wrapper)
Cordova 6.0
Platform iOS: 4.0.1

Plugins (from tarifa.json)

```
"cordova-plugin-splashscreen": "cordova-plugin-splashscreen@3.2.0",
"cordova-plugin-whitelist": "cordova-plugin-whitelist@1.0.0",
"cordova-plugin-file": "cordova-plugin-file@3.0.0",
"cordova-plugin-statusbar": "cordova-plugin-statusbar@1.0.1",
"cordova-plugin-console": "cordova-plugin-console@1.0.2",
"cordova-plugin-device": "cordova-plugin-device@1.1.1",
"cordova-plugin-dialogs": "cordova-plugin-dialogs@1.2.0",
"cordova-plugin-file-transfer": "cordova-plugin-file-transfer@1.5.0",
"cordova-plugin-inappbrowser": "cordova-plugin-inappbrowser@1.3.0",
"cordova-plugin-network-information": "cordova-plugin-network-information@1.2.0",
"cordova-plugin-google-analytics": "cordova-plugin-google-analytics@0.8.1",
"cordova-plugin-x-socialsharing": "cordova-plugin-x-socialsharing@5.0.11",
"phonegap-plugin-barcodescanner": "phonegap-plugin-barcodescanner@4.1.0",
"cordova-plugin-transport-security": "cordova-plugin-transport-security@0.1.1",
"phonegap-plugin-push": {
  "uri": "phonegap-plugin-push@1.6.0",
  "variables": {
    "SENDER_ID": "xxx"
  }
}
```

**Comment by gerhardsletten** [comment]
Looks like this is a bug with ios@4.0.1, if I upgrade to 4.1.0 it is fixed.

**Comment by macdonst** [comment]
@gerhardsletten Yes, it was a bug in cordova-ios@4.0.x. As you have found out upgrading to 4.1.x fixes it. I think I'm going to force everyone to use that version of cordova-ios as it will head off a lot of problems.
