### ISSUE TITLE
push.setApplicationIconBadgeNumber not working in background

### ISSUE THREAD

**Issue by Jarvey** [phonegap/phonegap-plugin-push#736]
### Expected Behaviour
When a push message is received override the badge count number with setApplicationIconBadgeNumber() when app is in background.

### Actual Behaviour
When a push message is received when the app is in the background nothing happens, the badge number wil be the badge number that is included in the push payload. When the app is open it works.

#### Steps to Reproduce 
Click app to the background and send a push notification. The app wil show the badge count number included in the push payload and ignores the push.setApplicationIconBadgeNumber function.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 9.3

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
-
#### Cordova CLI version and cordova platform version

    cordova --version                                #6.0.0
    cordova platform version iOS                     #4.0.1

#### Plugin version
    cordova plugin version | grep phonegap-plugin-push   #1.6.0

#### Sample Push Data Payload
`{"aps":{"alert":"Testing.. (1)","badge":1,"sound":"default"}}`
#### Sample Code that illustrates the problem
```
var push = PushNotification.init({ 
			"ios": {
				"alert": true, 
				"badge": true, 
				"sound": true, 
				"clearBadge": false 
			}
			
		});

push.on('notification', function(data) {
	        console.log(data.count);
	        push.setApplicationIconBadgeNumber(function() {
			    console.log('success');
			}, function() {
			    console.log('error');
			}, data.count + 1);
});
```

#### Logs taken while reproducing problem
When the app is running the log is showing me the data.count of the push payload, 1 in this case and it also shows ''succes".
When the app is in de background there are no logs shown.

**Comment by macdonst** [comment]
@Jarvey you are not sending a background notification so your notification handler is not being run. Send this payload:

`{"aps":{"alert":"Testing.. (1)","badge":1,"sound":"default", "content-available": 1}}`

If that fixes the problem please close this issue.

**Comment by Jarvey** [comment]
@macdonst yes this fixed it, it is now working.

**Comment by alaa-alshamy** [comment]
@macdonst is there any thing like badge payload in android to update badge number from os?

because i need to update it even if the app is totally closed
