### ISSUE TITLE
catch 22 when trying to use this plug

### ISSUE THREAD

**Issue by henkkelder** [phonegap/phonegap-plugin-push#741]
When using version 1.60 of this plugin on Phonegap build with cli-5.2.0 the app builds fine for IOS.
But when I run it I got the message 'Can't find variable pushplugin'.

When I switch to cli-6.0.0 again the app builds fine, and YES the errormessage no longer appears. But I have lost my splash screens and some icons. 

After several hours of trying I think the cause of the latter problem is that phonegap ios@4.0.1 for some reason wants all possible icons sizes and splashscreen sizes.. So a splashscreen of 768x1024 is no longer accepted as a valid splash screen for my ipad air.

So there is the catch-22. This plugin does not work properly on IOS using cli-5.2.0 but cli-6.0.0 will force me to add all posible icons and splashscreens thereby enlarging my app.

Any bright ideas of solutions?

Henk

**Comment by sirchas** [comment]
I had the same issue with cli-6.0.0 on build with icons not working. So I did this...
change build config to cli-5.4.1 and this plugin to 1.4.5 and I was able to get push to work.
sample:
` <preference name="phonegap-version" value="cli-5.4.1" />`
`<plugin name="phonegap-plugin-push" spec="~1.4.5" source="npm">`

**Comment by macdonst** [comment]
@henkkelder what is your app id? I will have PGB team look at it.

**Comment by henkkelder** [comment]
1438461, 

 

but I just reverted back to cli-5.4.1 and phonegap-plugin-push version 1.4.5 as was suggested by another user:

<preference name="phonegap-version" value="cli-5.4.1" />
<plugin name="phonegap-plugin-push" spec="~1.4.5" source="npm">

However I still think it’s an error that cli-6.0.0 on IOS seems to need all possible icons and splashes and either does not use the default icon/splash or does not automatically convert existing ones to missing ones. I am not sure what the method is that is being used on cli-5.4.1.

 

Your 1.60 version of the plugin does not work with cli-5.2.0 or cli-5.4.1 on IOS.

 

Groeten

Henk

**Comment by macdonst** [comment]
@henkkelder the PGB team asked me to send you to the forum. Please open this issue at:

https://forums.adobe.com/community/phonegap
