### ISSUE TITLE
No RegID received after updating to 1.6.0 (iOS, GCM, PGB)

### ISSUE THREAD

**Issue by ahlidap** [phonegap/phonegap-plugin-push#745]
### Expected Behaviour

Receiving as usual, a RegistrationID from GCM Service to send push notification
### Actual Behaviour

No RegistrationID is received, "onError" event of plugin not firing
### Reproduce Scenario (including but not limited to)

I'm using phonegap build as usual to build my app.
Using push plugin version 1.5.2 everything works ok.
After updating config.xml to use version 1.60 (I need coldstart), device no longer receive GCM RegistrationID
#### Steps to Reproduce

Same as above
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 9.2
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

iPhone 5C
#### Cordova CLI version and cordova platform version

Phonegap Build cli-5.2.0
#### Plugin version

Phonegap Push Plugin 1.6.0
#### Sample Push Data Payload

not used yet
#### Sample Code that illustrates the problem

Plugin usage as usual in 1.5.2

```
Document.addEventListener('deviceready', onDeviceReady, false);
function onDeviceReady() {
    alert('just to pause app for logging');
    pushNotification = PushNotification.init({
        ios: {
            senderID: GOOGLE_PROJECT_ID,
            alert: true,
            sound: true,
            gcmSandbox: true
        }
    });

    pushNotification.on('registration', function(data) {
        GCM = data.registrationId;
        console.log("SUPER GCM_ID = " + GCM); 
    });

    pushNotification.on('notification', function(data) {
        console.log(JSON.stringify(data));

        // Foreground
        console.log(data.additionalData.placeId)
        if (data.additionalData.foreground) {
            buildPush(data);
        }

        pushNotification.finish(function() {
            console.log('push finish success');
        }, function() {
            console.log('push finish error');
        });
    });

    pushNotification.on('error', function(e) {
        console.log('PUSH PLUGIN ERROR: ' + e.message);
    });
```

**Comment by FutoRicky** [comment]
+1

**Comment by kd8ssq** [comment]
+1

**Comment by FutoRicky** [comment]
Try rebuilding ios

**Comment by kd8ssq** [comment]
I just rebuilt my app 15 minutes ago and it still didn't work.  As soon as I downgraded the plugin, everything started working.

**Comment by FutoRicky** [comment]
I think the latest version supports OS8 +. So yeah downgrading is the best solution if you can't upgrade iOS

**Comment by kd8ssq** [comment]
I'm testing in iOS 9.3

**Comment by Dsqwared** [comment]
+1

**Comment by macdonst** [comment]
the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
