### ISSUE TITLE
Android 5.1: configured push icon is sometimes not taken into account

### ISSUE THREAD

**Issue by jakub-g** [phonegap/phonegap-plugin-push#747]
### Expected Behaviour & Sample Code that illustrates the problem

When I configure push icon in frontend, I expect it to be displayed next to my notif, even when there's no icon configured in notif payload:

```
_pushPlugin = window.PushNotification.init({
  android: {
    iconColor: "blue",
    icon: "push_notification_icon", // this points to a PNG in my resources
    //    senderID: GCM_SENDER_ID,
    //    forceShow: false
  }
});
```
### Actual Behaviour

Depending on exact payload, sometimes the icon is not displayed.
#### Platform and Version

Android 5.1
#### (Android) What device vendor

Motorola MotoG3
#### Cordova CLI version and cordova platform version

```
cordova --version
> 6.0.0
cordova platform version android
> 4.1.1
```
#### Plugin version

```
cordova plugin version | grep phonegap-plugin-push
> 1.6.0
```
#### Sample Push Data Payload

**Icon displayed (case 1a on picture)**

```
var message = new gcm.Message({
    notification: {}
});
message.addData({
    customField: 'my custom field',
    alert: 'ALERT'
});
```

![notifs_depending_on_gcm_payload](https://cloud.githubusercontent.com/assets/1437027/13984726/4e18e5c4-f0f8-11e5-9f1e-9e86b2d99678.png)

**Icon not displayed (case 3 on picture)**

```
var message = new gcm.Message({
    notification: {
        title: "TITLE",
        body: "BODY"
    }
});
message.addData({
    customField: 'my custom field',
    alert: 'ALERT'
});
```

**Comment by macdonst** [comment]
@jakub-g Yeah, the problem is when you add the `notification` property to the `gcm.Message` object with a `title` and `body` the OS takes over. Once the OS takes over the plugin never gets called. It's on my list to look into but for now I suggest not populating the `notification` object. That's why all of my sample node-gcm scripts use the `data` object only.

**Comment by luco** [comment]
+1 on this. Getting the same here.

**Comment by macdonst** [comment]
@luco yeah, I know guys. For now don't use the `notification` section in the push payload. Put everything in the `data` section. That's why I've documented it that way in all the examples.

**Comment by jakub-g** [comment]
Not a big issue for me, I just opened the report for reference. Thanks for
quick response.

**Comment by amritk** [comment]
+1

**Comment by gustavocampos** [comment]
+1, maybe it's worth putting this in documentation.

**Comment by Gp2mv3** [comment]
I agree, it can be really convenient to put this in the documentation.
