### ISSUE TITLE
IOS ReferenceError: Can't find variable: PushNotification

### ISSUE THREAD

**Issue by maplerichie** [phonegap/phonegap-plugin-push#749]
For Android, it work like charm but in iOS, it show this problem via GapDebug console.
iOS Development Profile

```
  <plugin name="phonegap-plugin-push" source="npm">
    <param name="SENDER_ID" value="##4870725283"/>
  </plugin>
```

```
    push = PushNotification.init({
      android: {
        senderID: "##4870725283",
        sound: true,
        vibrate: true
      },
      ios: {
        alert: "true",
        badge: "true",
        sound: "true",
        senderID: "##4870725283",
        gcmSandbox: "true",
      }
    });
```

Can you figure the problem here? Or require other detail?
I'm using Windows10 for develop and build.phonegap.com to build the ipa

**Comment by macdonst** [comment]
@maplerichie requires more details. Not sure what error you are seeing on PGB.

**Comment by maplerichie** [comment]
@macdonst  
Sorry ya. I'm currently double checking my config.xml and PGB. I just look into IPA file and found that PGB doesn't include this plugin in iOS build but Android does. Thanks. Will update you again once found the problem.

**Comment by macdonst** [comment]
@maplerichie this plugin requires cordova-ios 4.0.0 or greater. You are possibly using an older version and that is why it doesn't compile.

**Comment by rohand** [comment]
Is there any way to override the "Contents hidden" via payload when phone is locked? I know there is a phone setting for this but would like to override it via code.

**Comment by maplerichie** [comment]
@macdonst 
I can't find the version i using in build.phonegap.com, can i config in config.xml?

**Comment by macdonst** [comment]
@maplerichie what does your config.xml look like?

**Comment by maplerichie** [comment]
I'm finally done by putting this in my config.xml
 <preference name="phonegap-version" value="cli-6.0.0" />

It will use cordova-ios@4.0.2

**Comment by shastox** [comment]
@maplerichie 
I have the same problem. Do you solved the problem?

**Comment by maplerichie** [comment]
@shastox i solve the problem by creating certificate for development and production
Just follow the instruction to create certificate and upload to Google GCM
https://developers.google.com/cloud-messaging/ios/certs#create_an_app_id

**Comment by shastox** [comment]
@maplerichie 
I do not understand. What do you mean GCM? I don't use GCM.
 Version 1.6 does not work with the current build.phonegap. All certificates is OK.

**Comment by maplerichie** [comment]
@shastox  the problem u face is iOS cant find device rite? The problem for me is pgb doesnt compile this push plugin because version problem. Are u using Phonegap build to compile ipa?
If is pgb, add this line to your config.xml
    <preference name="phonegap-version" value="cli-6.0.0" />
U can try to unarchive the ipa file and look the plugin folder inside, is it included the push plugin?

**Comment by shastox** [comment]
@maplerichie 
Thank you. I found solution: https://github.com/phonegap/phonegap-plugin-push/issues/779

**Comment by braianj** [comment]
sorry but is there a solution for this?

**Comment by maplerichie** [comment]
@braianj I was revert back to version 1.8.1 and it solve the Android issue.

**Comment by braianj** [comment]
@maplerichie thanks, but the problem for me is in ios as the title said. I can make the build but when apps run, console return `ReferenceError: Can't find variable: PushNotification`.
Any solution for IOS?
Thanks

**Comment by maplerichie** [comment]
@braianj  Ops sorry, is iOS. Sorry for didnt check my answer. Android can work juz iOS nid to revert back to version 1.8.*

**Comment by braianj** [comment]
I make it work by putting the init inside a timeout of 5 seconds and that work just fine. No need to revert the version, but that shouldn't be the way.
Thanks anyway.

**Comment by maplerichie** [comment]
@braianj  This is best method for most of the time (Y)

**Comment by fredgalvao** [comment]
@braianj @maplerichie That is a very error-prone way to solve the error, and almost always an indicative that you're not using the `deviceready`. The same error is mentioned on #779.
Now, if you **are** using the `deviceready` event properly, and you still need that `setTimeout()`, I'd instead create a new issue and give more details, as it's something else entirely and you shouldn't rely on that timeout anyway.
