### ISSUE TITLE
Show contents of notification when phone is locked

### ISSUE THREAD

**Issue by rohand** [phonegap/phonegap-plugin-push#750]
When phone is locked it shows "Contents Hidden".
 Is there any way to override the phone settings via code/payload?

#### Platform and Version Android 5.0

Android 5.0

#### Cordova CLI version and cordova platform version

    cordova --version       6.0.0
    cordova platform version android    4.1.1

#### Plugin version

    cordova plugin version 1.6.1

**Comment by macdonst** [comment]
@rohand I'm curious what is your phone set to show?

_Head to Settings and click Sound & Notification. There are three options to choose from in the "When device is locked" option at the bottom of the page: show all notifications, don't' show notifications at all and hide sensitive notification information. The last option -- which will still show an incoming notification, but not any of the content -- will only be available if you have a screen lock pin, pattern or password set up._

That said there is a way to set a notification public, private or secret so I'll add this as an enhancement.

**Comment by RanjitReddy** [comment]
you save my time.... Thank u @rohand
