### ISSUE TITLE
Use cordova-ios 4.1.0 in Milestone 1.7.0

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-plugin-push#751]
There is a bug in cordova-ios 4.0 that can cause the app to lock up. Force people to upgrade to cordova-ios 4.1.x

**Comment by fredgalvao** [comment]
For future reference or mention: https://issues.apache.org/jira/browse/CB-10530

**Comment by macdonst** [comment]
@fredgalvao thanks for the JIRA link. I hate searching through that mess.
