### ISSUE TITLE
App Icon not displayed in tray using build.phonegap and cli-6.0.0 [ios]

### ISSUE THREAD

**Issue by oscarabilleira** [phonegap/phonegap-plugin-push#753]
### Expected Behaviour
App icon must be displayed in tray when notification is recieved.

### Actual Behaviour
Phonegap icon is displayed in tray when notification is recieved.

### Reproduce Scenario (including but not limited to)
Build an app with this plugin under build.phonegap.com using cli-6.0.0

#### Steps to Reproduce 
Send a push notification to the app and icon is wrong displayed.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ios 9.3

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Iphone 6

#### Cordova CLI version and cordova platform version

    phonegap build --version                                  cli-6.0.0
    cordova platform version ios                  4.0.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.6.1

#### Logs taken while reproducing problem

**Comment by oscarabilleira** [comment]
Solved!

Mistaken reference in config.xml... (in previous versions works fine but now after fixed works good)

**Comment by eliea85** [comment]
What is the reference in the config.xml that you did fixed ?
I am facing the same problem.

**Comment by js12690** [comment]
@oscarabilleira : What is the reference in the config.xml that you did fixed ?
I am facing the same problem and stuck in project. I have spend couple of days to solve this issue. Please reply
Thanks in advanced
