### ISSUE TITLE
[Question] Customizing top notification

### ISSUE THREAD

**Issue by felipe-rm** [phonegap/phonegap-plugin-push#755]
Is it possible to customize the top notification shown in the top bar?

Say the server is sending the following info:

```java
new Message.Builder()
 .addData("title", "Test")
 .addData("message", "123")
 .build();

// send
```

And I want to intercept it with the following:

```js
var push = PushNotification.init({
            "android": {
                "senderID": "SENDER_ID",
                "icon": "icon",
                "iconColor": "red"
            },
            "ios": {"alert": "true", "badge": "true", "sound": "true"}, 
            "windows": {} 
        });

  push.on('notification', function(data) {
   data.title += "-abc";      
   data.message += "-xyz";
   
   console.log(data.title); //Test-abc
   console.log(data.message); //123-xyz
});
```

The code above will change the incoming notification and use it inside the my application. But won't change the values in the top notification. It is still shown as the `title` being `Test` and the `message` being `123`.

Is there anyway to change that?

**Comment by macdonst** [comment]
@felipe-rm they only way to do that AFAIK is to resend the notification with the same `notId` so the original push is replaced.
