### ISSUE TITLE
iOS Main App Delegate Register Call Overriden

### ISSUE THREAD

**Issue by bmatto** [phonegap/phonegap-plugin-push#757]
I am working with CleverTap - a mobile analytics solution.  Their tools requires that the main AppDelegate.m method didRegisterForRemoteNotificationsWithDeviceToken get invoked.  I think that the push notification plugin is causing that method not to be called.

Can anyone provide insight as to why that method is not getting called?  Is the Push Notification plugin overriding the method?

**Comment by macdonst** [comment]
@bmatto yes, of course this plugin overrides didRegisterForRemoteNotificationsWithDeviceToken or else it couldn't get push notifications.

https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/AppDelegate%2Bnotification.m#L89

I don't have access to CleverTap to see how the two could be integrated.
