### ISSUE TITLE
Show notification even application is in foreground

### ISSUE THREAD

**Issue by waptaxi** [phonegap/phonegap-plugin-push#76]
It would be useful to have an option to show notification not only when application is in background or not running at all.
For example, to draw user's attention to events in familiar way without inventing disturbing message boxes or popups in application.

**Comment by macdonst** [comment]
@waptaxi is there any precedence for this type of behaviour? As far as I know the OS doesn't show the notification by default when you are in the app. It is up to you as the app developer to act upon the `notification` event in whatever way you seem fit. Whether that be a pop up dialog or some banner in your app.

**Comment by waptaxi** [comment]
Or notification? :)
I agree that apps usually don't show notifications whe in foreground, but in my case it would be useful.
So the most obvious way is to add parameter to push plugin.
Or I have to use separate LocalNotification plugin.
By the way, maybe we can use PushPlugin to show Local notifications?
All we need is to add one function to emulate push notification?

**Comment by AdriVanHoudt** [comment]
Would it be possible to make this optional? We would also like to have this behaviour and it seems to be fairly easy to make an option that overrides the `if isInForeground` @ https://github.com/phonegap/phonegap-plugin-push/blob/master/src/android/com/adobe/phonegap/push/GCMIntentService.java#L91

**Comment by sonicwong** [comment]
+1

To: AdriVanHoudt,
Thank you for the guide on android. May I know which line should I change on iOS version?

**Comment by AdriVanHoudt** [comment]
@sonicwong doing a PR? and I think https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/AppDelegate%2Bnotification.m#L74-L82

**Comment by sonicwong** [comment]
@AdriVanHoudt  yes, I am doing a app to reply client if any delivery time change.
I am not able to get it work when replace line 75-78 to "self.launchNotification = userInfo;"

I see the function "applicationDidBecomeActive" is run and remarked too. But also not working.

**Comment by AdriVanHoudt** [comment]
ah you are changing it on your end? Why not do PR when done? ;)

and I have no experience with the ios side sorry

**Comment by AdriVanHoudt** [comment]
I did a PR for android #178 should be non breaking and I would really love this. As an example twitter android app also does this.

**Comment by lovelyelfpop** [comment]
I found [EBForeNotification](https://github.com/pikacode/EBForeNotification), it can show the Banners and Sounds as the same as the system notifications on foreground in ios.
Can someone integrate EBForeNotification into this plugin?
