### ISSUE TITLE
iOS 9.3

### ISSUE THREAD

**Issue by lucasabba** [phonegap/phonegap-plugin-push#761]
Hello, i reed this https://github.com/phonegap/phonegap-plugin-push/issues/752 about push problem in iOS 9.3. I have the same problem but i don't understand what i need to do to resolve the problem. What does it mean that I need to fill everything on the push object?
Thanks to all!

**Comment by macdonst** [comment]
@lucasabba if you are using the same sample code as in #752 remove the call to unregister. You should only call that method if you don't want to get push messages anymore.

Also, sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the issue submission guidelines.
