### ISSUE TITLE
Documentation mentions old name for dependency

### ISSUE THREAD

**Issue by peteonrails** [phonegap/phonegap-plugin-push#763]
### Expected Behaviour
The docs say that you need to install Android Support Repository version 20 or higher. When I look in the Android SDK, I expect to find this dependency listed. 

### Actual Behaviour
This package no longer appears int he Android SDK.

### Reproduce Scenario (including but not limited to)
Open your SDK Manager, refresh, and look for Android Support Repository under Extras. It's not there. 

#### Steps to Reproduce 
See above. 

I'm only opening this issue so that I can link to it in my 1 line pull request. Thx!

**Comment by macdonst** [comment]
@peteonrails thanks! I merged your PR then added a bit to refer to the old name as per @fredgalvao suggestion.

**Comment by peteonrails** [comment]
+1 Yes good idea @fredgalvao, I was just coming back to make that update per your suggestion and saw that it has already been taken care of. Many thanks to all!
