### ISSUE TITLE
push plugin

### ISSUE THREAD

**Issue by karthi191** [phonegap/phonegap-plugin-push#766]
Error: Can't find variable: PushNotification

**Comment by karthi191** [comment]
its build successfully but on real device its show error on console log like this Error: Can't find variable: PushNotification

**Comment by macdonst** [comment]
@karthi191 Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
