### ISSUE TITLE
[Android] Can't install multiple apps using this plugin (v1.6.x)

### ISSUE THREAD

**Issue by nonplus** [phonegap/phonegap-plugin-push#768]
When I try to install multiple versions of of the an app (dev, test..., each with different bundle name) the second installation fails with an error.

More details about this problem are in #474. Apparently it was fixed for 1.4.x/1.5.x in 15b76632ac2849f1cb2f48e75a5292dfaa97de7f.

Using v1.6.0, the problem occurs again.  It seems to have been broken in #625 48c4a56731f079474bca588af17702cd502f2a16

**Comment by matthijsbierman** [comment]
I think it's related to [CB-10014](https://issues.apache.org/jira/browse/CB-10014).

Their proposed fix would have to be added to this plugin:

### FOR PLUGIN DEVELOPERS

**plugin.xml**
`<framework src="build-extras-PLUGIN_NAME_HERE.gradle" custom="true" type="gradleReference" />`

**build-extras-PLUGIN_NAME_HERE.gradle**
`def manifest = new XmlSlurper().parse(file("AndroidManifest.xml"))
android.defaultConfig.applicationId manifest.@package.text()`

There is also a workaround you can use in your own app, which is simply creating the **build-extras.grade** file under _<project-root>/platforms/android_ and putting the same snippet in there:

`def manifest = new XmlSlurper().parse(file("AndroidManifest.xml"))
android.defaultConfig.applicationId manifest.@package.text()`

I can confirm this workaround works.

**Comment by macdonst** [comment]
Yup, I had to revert the change. Release 1.6.3 has the fix.
