### ISSUE TITLE
After upgrade: 601 duplicate symbols for architecture i386

### ISSUE THREAD

**Issue by bardu** [phonegap/phonegap-plugin-push#769]
### Expected Behaviour

Build iOS version 

### Actual Behaviour

> ...
duplicate symbol _OBJC_METACLASS_$_GSDK_PBMessageSignatureProtocol in:
    /Users/stephan/c9sdk/cordova-projects/yn/platforms/ios/Pods/GoogleInterchangeUtilities/Libraries/libProtocolBuffers_external.a(PBUtilities.o)
    /Users/stephan/c9sdk/cordova-projects/yn/platforms/ios/YukonNow/Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(PBUtilities.o)
duplicate symbol _OBJC_CLASS_$_GSDK_PBMessageSignatureProtocol in:
    /Users/stephan/c9sdk/cordova-projects/yn/platforms/ios/Pods/GoogleInterchangeUtilities/Libraries/libProtocolBuffers_external.a(PBUtilities.o)
    /Users/stephan/c9sdk/cordova-projects/yn/platforms/ios/YukonNow/Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(PBUtilities.o)
ld: 601 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

#### Steps to Reproduce 

On an existing project I:

updated android platform to v 5.1.1
rm platform ios
add platform ios@4.1.0

build android (worked)
run android on device (worked)

build ios (worked)

in platform/ios I executed:

pod init
edited Podfile
pod install

after pod install I got message:

> !] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `YukonNow` to `Pods/Target Support Files/Pods-YukonNow/Pods-YukonNow.debug.xcconfig` or include the `Pods/Target Support Files/Pods-YukonNow/Pods-YukonNow.debug.xcconfig` in your build configuration (`cordova/build-debug.xcconfig`).

>[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `YukonNow` to `Pods/Target Support Files/Pods-YukonNow/Pods-YukonNow.release.xcconfig` or include the `Pods/Target Support Files/Pods-YukonNow/Pods-YukonNow.release.xcconfig` in your build configuration (`cordova/build-release.xcconfig`).

added 

> #include "Pods/Target Support Files/Pods-YukonNow/Pods-YukonNow.debug.xcconfig"
#include "Pods/Target Support Files/Pods-YukonNow/Pods-YukonNow.release.xcconfig" 

to the respective xcconfig files.

#### Cordova CLI version and cordova platform version

    cordova --version     6.1.0
    cordova platform version android   5.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.6.1

#### Logs taken while reproducing problem

see above

Any idea how to fix that?

**Comment by bardu** [comment]
Well, not pods required anymore.

**Comment by athattayathu** [comment]
I am currently experiencing the issue detailed above @bardu. Would you mind explaining how you solved this issue a bit more?

**Comment by dhirajb1989** [comment]
Hi, since the plugin already has the librariries required for gcm ios, it is causing the problem... You don't have to add any library for ios which you usually do by pod install...

**Comment by athattayathu** [comment]
Thanks for the quick reply. Got it working once we removed Pods.
