### ISSUE TITLE
ios not registering

### ISSUE THREAD

**Issue by FutoRicky** [phonegap/phonegap-plugin-push#770]
### Expected Behaviour

To register device, or actually get data when push.on('registration') is called

### Actual Behaviour

it's just not happening. I tried debugging from the console and I just get undefined

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

debugging on ios 7.1.2

#### Cordova CLI version and cordova platform version

    cordova --version 5.4.1
    cordova platform version ios 4.1.0

#### Plugin version

latest one

**Comment by twicejr** [comment]
Same here with phonegap build service.
PushNotification is not defined.

**Comment by FutoRicky** [comment]
I had the `pushNotification is not defined` issue, but I fixed it by updating cordova ios to 4

**Comment by twicejr** [comment]
Yeah, me too, by now :)
Discovered you could use Phonegap 6 on the build service, which uses cordova ios 4+

**Comment by macdonst** [comment]
@FutoRicky Cordova iOS 4 only support iOS 8 or greater. You'll have to test on a new device, sorry.

**Comment by FutoRicky** [comment]
@macdonst tested it on a greater ios and still the same issue

**Comment by macdonst** [comment]
@FutoRicky okay, do you have the iOS certificates with push enabled installed for your bundle ID?

**Comment by FutoRicky** [comment]
@macdonst That is correct

**Comment by macdonst** [comment]
@FutoRicky super weird. Can you run the app in Xcode? It should give some better clue as to why registration isn't being called.

**Comment by FutoRicky** [comment]
@macdonst 
getting this:
```
FAILED pluginJSON = ["PushNotification677907933","PushNotification","init",[{"android":{"senderID":"395336045307"},"ios":{"clearBadge":"true","alert":"true","badge":"true","sound":"true"}}]]
```

**Comment by macdonst** [comment]
@FutoRicky weird. I bet if you look in your Xcode project you'll see that PushPlugin.m hasn't been added to the project in the Plugins folder. You might be better off deleting your platforms and plugin directories and starting from scratch.

**Comment by FutoRicky** [comment]
@macdonst That fixed it. Thanks!
