### ISSUE TITLE
Push not working on iOS (only happens on production)

### ISSUE THREAD

**Issue by ZiFFeL1992** [phonegap/phonegap-plugin-push#774]
### Expected Behaviour

I have been testing push on ionic 2, all seems to work fine on development, but since I'm testing from TestFlight before pushing to final production stage looks like push are not working with those tokens, I mean, I'm able to get the registration_id to my server, but when I send the push notification I have a "NotRegistered" error.
### Reproduce Scenario (including but not limited to)

iPhone's + TestFlight 
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

```
  android 5.1.1
  ios 4.1.0
Devices with iOS9.2x-9.3x
```
#### Cordova CLI version and cordova platform version

```
Your system information:

Cordova CLI: 6.1.0 (cordova-lib@undefined)
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 7.3 Build version 7D175 
```
#### Plugin version

`phonegap-plugin-push 1.6.1 "PushPlugin"`
#### Logs taken while reproducing problem

I don't know how to take logs when production, let me know if it's possible.
Also can I sign from xcode with production certs to avoid upload every test build?

**Comment by macdonst** [comment]
@ZiFFeL1992 are you making sure to use production push?

**Comment by ZiFFeL1992** [comment]
I'm using gcm on iOS as well, configure both apns and upload them to Google Platform, then when I'm building for production just mark gcmSandbox as false as stated on the plugin docs.

After that build, archive and upload.

Is that enough or should I do something else?

**Comment by ZiFFeL1992** [comment]
Seems like changing the code like mentioned on this topic works: http://stackoverflow.com/questions/31625163/why-google-cloud-messaging-notification-not-working-with-iphone-production-envir

Maybe the code is not updating when changing the following variable on init: `gcmSandbox`.

Let me know if I should test anything or you can close this.

Thanks!

**Comment by wiewioraseb** [comment]
@ZiFFeL1992 Do you maybe recall what helped you with this issue?

**Comment by ZiFFeL1992** [comment]
Upps sorry for not closing this, working :D

**Comment by wiewioraseb** [comment]
@ZiFFeL1992 What was the solution to this problem?

**Comment by ZiFFeL1992** [comment]
@wiewioraseb 

Read this: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#how-gcm-on-ios-works
