### ISSUE TITLE
Cannot find plugin.xml error when installing

### ISSUE THREAD

**Issue by henryblackman** [phonegap/phonegap-plugin-push#775]
### Expected Behaviour
Installation completes without error

### Actual Behaviour
Error on installation as follows:
Installing "phonegap-plugin-push" for ios
Error: Cannot find plugin.xml for plugin 'com.phonegap.plugins.PushPlugin'. Please try adding it again.

### Reproduce Scenario (including but not limited to)
Typed cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable SENDER_ID="XXX" and saw error, tried with direct GitHub URL and found same error.

#### Steps to Reproduce 
Type specified install command:
cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable SENDER_ID="XXXX"

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Running cordova command on MacOS

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
N/A

#### Cordova CLI version and cordova platform version

    cordova --version = 6.1.1
    cordova platform version android = N/A

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   =1.6.1

#### Sample Push Data Payload
N/A

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
N/A

**Comment by macdonst** [comment]
@henryblackman I can't reproduce this issue. I'm also using cordova 6.1.1. Can you give it another try?

**Comment by dm-grinko** [comment]
I have the same issue.

**Comment by tylermakin** [comment]
@macdonst I am also experiencing this issue

**Comment by IgorGanapolsky** [comment]
I am having the same issue right now with Cordova v6.4.0.  I have a plugin.xml in my current directory, but when I execute this command:
`plugman install --platform android --project examples/battery/platforms/android/ --plugin .`

I get this error:
> Cannot find plugin.xml for plugin "plugins". Please try adding it again.

**Comment by septronic2** [comment]
Yeah me too, I've got the plugin.xml in the plugins folder, and just to be sure, I added it to the project/plugin/pluginfolder as well, which made no difference.

**Comment by renjithvk** [comment]
### SOLVED

It's just a **permission issue**. Please set current user as the owner of the project files

`$ sudo chown -R $(whoami) project-directory`
