### ISSUE TITLE
Request: extend action buttons to wearables

### ISSUE THREAD

**Issue by michellarcari** [phonegap/phonegap-plugin-push#776]
I need my Pebble smartwatch to be able to display the action buttons, however, it doesn't recognize them. I believe this is because the Notification needs to be extended to wearable devices like 

**NotificationCompat.Builder.extend(new WearableExtender().addAction(action))**

Thanks!

**Comment by michellarcari** [comment]
I forked this plugin and added this feature.
It's working like a charm.

**Comment by macdonst** [comment]
@michellarcari great, can you fix the PR as per my comment over there?

**Comment by michellarcari** [comment]
Sure, will do it soon.

Thanks!
Michell ArcariCel: (19) 99118-1466Campinas/SP

Date: Wed, 6 Apr 2016 06:50:13 -0700

**Comment by michellarcari** [comment]
@macdonst I just fixxed it and requested another pull

**Comment by michellarcari** [comment]
Changes merged. Closing this request.
