### ISSUE TITLE
Apple reject advertisingIdentifier in phonegap-plugin-push/GCM/Libraries/libGGLCore.a

### ISSUE THREAD

**Issue by tslearn** [phonegap/phonegap-plugin-push#778]
I use phonegap-plugin-push in my iOS app without gcm.
but i found advertisingIdentifier in phonegap-plugin-push/GCM/Libraries/libGGLCore.a

Apple reject this and said that:
If your app does not serve ads, please check your code - including any third-party libraries - to remove any instances of:

class: ASIdentifierManager
selector: advertisingIdentifier
framework: AdSupport.framework

If you are planning to incorporate ads in a future version, please remove the Advertising Identifier from your app until you have included ad functionality.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
   iOS 9.2

#### Cordova CLI version and cordova platform version
    6.0.0

#### Plugin version
   1.6.1

**Comment by macdonst** [comment]
@tslearn well that is interesting. I have an app being reviewed by Apple right now. I'll see what they say. Not sure what to do if they don't want the Google libraries.

**Comment by macdonst** [comment]
@tslearn we were able to get an app published into the App Store (Apple) using version 1.6.1 of this plugin. Not sure what to tell you other than to re-submit.

**Comment by tslearn** [comment]
@macdonst  Thanks。 I only remove gcm library and publish successful。

I am not sure weather apple want the Google Libraryes if developer don't use it. Maybe judged by personal minds.

The following is message apple reject gcm, hope it helps:

Program License Agreement
PLA 3.3.12

Thank you for your resubmission. Upon further review of your application, we found the following issue:

We found that your app uses the Advertising Identifier but does not include ad functionality. This does not comply with the terms of the Apple Developer Program License Agreement, as required by the App Store Review Guidelines.

Specifically, section 3.3.12 of the Apple Developer Program License Agreement states:

"You and Your Applications (and any third party with whom you have contracted to serve advertising) may use the Advertising Identifier, and any information obtained through the use of the Advertising Identifier, only for the purpose of serving advertising. If a user resets the Advertising Identifier, then You agree not to combine, correlate, link or otherwise associate, either directly or indirectly, the prior Advertising Identifier and any derived information with the reset Advertising Identifier."

Note: iAd does not use the AdSupport framework, ASIdentifierManager, or the Advertising Identifier. Therefore they are not required for iAd implementations and should not be included in your app for iAd support. 

If your app is serving ads, please:

- Ensure that you have tested your app on a device, not just the simulator, and that you have removed all previous versions of your app prior to testing

- Provide us the steps to locate ads in your app

**Comment by npvn** [comment]
@macdonst I also encountered this issue. One solution I'm thinking about is to remove all GCM related libraries (including `libGGLCore.a` which contains `advertisingIdentifier`) from the ios platform of the plugin. This is ok for me, since I'm not planning to use GCM for my iOS app.

I tried removing them in `plugin.xml`, but got error during the building process. It looks like I also need to modify other files too. Could you please tell me a general direction on what need to be modified?

@tslearn Could you please share how you removed the GCM libraries from the plugin?
