### ISSUE TITLE
iOS 9.2: Reference Error: Can't find variable: PushNotification.

### ISSUE THREAD

**Issue by shastox** [phonegap/phonegap-plugin-push#779]
I've created a new blank project PhoneGap.

Add to config.xml:

```
<plugin name="phonegap-plugin-push" source="npm">
<param name="SENDER_ID" value="{MY_ID}" />
</plugin>
```

Added code from the example: https://github.com/phonegap/phonegap-plugin-push/tree/master/example/www

Global "Object Push Notification" is not created: "Reference Error: Can't find variable: PushNotification."

Apple Certifications are correct. Development.

I use PhoneGap Build.

**Comment by digitsinmotion** [comment]
I'm getting this same issue on PhoneGap Build for cli-5.1.1, cli-5.20 and cli-5.4.1. Works great on Android.

**Comment by shastox** [comment]
I found solution! Many people asked, look: https://github.com/phonegap/phonegap-plugin-push/issues?page=1&q=is%3Aissue+PushNotification&utf8=%E2%9C%93
```
<plugin name="phonegap-plugin-push" **spec="1.5.3" **source="npm">
    <param name="SENDER_ID" value="527513843211" />
</plugin>
```

Version 1.6 is **BAD** for current build.phonegap!

**Comment by digitsinmotion** [comment]
Fantastic, shastox. I've been hunting this down for a while. Thanks for sharing.

**Comment by macdonst** [comment]
@shastox that just means you are using an earlier version of the plugin.

**Comment by shastox** [comment]
@macdonst 
Оf course, I know that.

**Comment by webbpage** [comment]
Exactly what I was looking for, thanks! I really wish plugins were more friendly with PGB, this happens all too often...

**Comment by ewhill** [comment]
I literally spent a whole day trying to figure out why my pgb project wasn't getting notifications. THANK YOU for the "spec='1.5.3'" tip @shastox !!

**Comment by webbpage** [comment]
@ewhill did you by chance try 1.7.2?  There's been a few releases since this issue was opened.

**Comment by Dmatafonov** [comment]
thanks a lot!

**Comment by oleksiy-nesterov** [comment]
1.7.4 still has this issue

**Comment by RezaRahmati** [comment]
Yeah setting to 1.5.3 solved my issue too, and it's bad that bug still exists on 1.7.4 and this issue is closed,
I think since this is a workaround issue should be open to be fixed

@macdonst

**Comment by lucorn** [comment]
you need to add this to the root config.xml:

  <engine name="ios" spec="~4.1.0"/>

**Comment by KaustubhAtMobiuso** [comment]
Hey @shastox  I have add <plugin name="phonegap-plugin-push" spec="1.5.3" source="npm">
        <param name="SENDER_ID" value="904905204931" />
    </plugin> in my config.xml but still getting the error ReferenceError: Can't find variable: PushNotification can you help me please I am building  AEM IOS App do you have any idea how to get solve this issue.

**Comment by KaustubhAtMobiuso** [comment]
Hey @shastox I have add this line in my config.xml
plugin name="phonegap-plugin-push" spec="1.5.3" source="npm"
param name="SENDER_ID" value="904905204931"
plugin

but still getting the error ReferenceError: Can't find variable: PushNotification can you help me please I am building AEM IOS App do you have any idea how to get resolve this issue ?

**Comment by macdonst** [comment]
@KaustubhAtMobiuso do you get an error when you add the plugin because you are using an older version of cordova-ios?

**Comment by KaustubhAtMobiuso** [comment]
@shastox  no i didn't get any error while adding the plugin but when I try to build the project, I got this error 'AppDelegate.h' file not found
          #import "AppDelegate.h"
 after that I  use this command cordova platform update ios which updated the cordova-ios version to 4.3.0 and my build get success, but when I deploy the app on IOS device i got the error ReferenceError: Can't find variable: PushNotification and I have cordova version 6.4.0.

**Comment by shastox** [comment]
@KaustubhAtMobiuso 
Do you use "Device ready" event?

**Comment by KaustubhAtMobiuso** [comment]
Yes @shastox  I use device ready event and device ready event also got fire but still same issue is there.

**Comment by shastox** [comment]
@KaustubhAtMobiuso Show a piece of code with device ready and PushNotification.

**Comment by KaustubhAtMobiuso** [comment]
Hey @shastox  this is my code for device ready and Push Notification check it.
    onDeviceReady: function() {
        app.receivedEvent('deviceready');
    },
    // Update DOM on a Received Event
    receivedEvent: function(id) {
        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');

        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');

        console.log('Received Event: ' + id);

        var push = PushNotification.init({
            "android": {
                "senderID": "904905204931"
            },
            "browser": {},
            "ios": {
                "sound": true,
                "vibration": true,
                "badge": true
            },
            "windows": {}
        });

        push.on('registration', function (data) {
            console.log("Push::Received Registration Id");
            console.log("Push::Received Registration Id => " + data.registrationId);

            var oldRegId = generalUtils.getPreference('REGISTRATION_ID');
            if (oldRegId !== data.registrationId) {
                // Save new registration ID
                console.log(data.registrationId);
            }
        });

        push.on('error', function(e) {
            console.log("push error = " + e.message);
        });
    }

**Comment by shastox** [comment]
Sorry, no idea.

**Comment by KaustubhAtMobiuso** [comment]
@shastox  Ok

**Comment by macdonst** [comment]
the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
