### ISSUE TITLE
The notification doesn't disappear when user opens the app.

### ISSUE THREAD

**Issue by debe78** [phonegap/phonegap-plugin-push#780]
Expected Behaviour:
I get a notification, I open the application does not clicking on the notification, but using the app icon, the notification must disappear.

Actual Behaviour:
I get a notification, I open the application does not clicking on the notification, but using the app icon, the notification doesn't disappear.

Platform and Version: Android 5.0.1 - Huawei P8-lite
Platform and Version: Android 4.1.2 - Samsung GT-I9100

cordova     6.0.0
cordova platform version android       5.1.1
Plugin version: 1.6.1

#### Sample Code that illustrates the problem
When the app is starting i call (after deviceready):

 push.on('registration', function(data) {
   ......
 call to my server ....
});

var callback = function(data){  [My data.....]  };
push.on('notification', callback);
push.off('notification', callback);

I thought the push.off function was used to delete the notification at the top of the phone, but the callback in the push.off function isn't call, instead the callback into push.on function is called correctly.

What's wrong?
Thanks
Enrico

**Comment by macdonst** [comment]
@debe78 what you describe is not normal for Android push notifications. When you start apps the notifications do not disappear. There is a parameter you can send as part of the init function to clear notifications on app close if you would like.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushnotificationinitoptions

Also, the `off` function removes the event listener. So you are using that wrong.

**Comment by debe78** [comment]
ok thank you,

anyway if you receive one notification from WhatsApp and open the app clicking the app icon, after choising the conversation, 
the notification disappear.
This is normal, because notification has finished her task that is to warn user that there is a news in the app.
So like in the example about WhatsApp i need something similar, the possibility to hide the notification at the top of the phone
because if I open the app, notification has finished her task to advise me that there are  news in the app. 
I think this is a normal behavior using notification, the same happens if i open the app by clicking on the notification, it disappears,
but if i open the app cliccing the icon this doesn't happen.


Is it possible?

Thanks
Enrico

**Comment by macdonst** [comment]
@debe78 I do not understand the flow you are taking about. Pictures?

**Comment by debe78** [comment]
ok i will try to explain in a better way the flow using attached images.

I received a notification and i see it at the top of the phone like in the image:
![notification_1_min](https://cloud.githubusercontent.com/assets/11208810/14744042/34c28930-08a5-11e6-90b7-cff83d63bd4f.jpg)

I open my app clicking on the icon app and not clicking on the notification:
![notification_2_min](https://cloud.githubusercontent.com/assets/11208810/14744180/f9c74e64-08a5-11e6-85da-d20fe6c1232d.jpg)

The notification on the top of the phone is disappered and i'm using the app:
![notification_3_min](https://cloud.githubusercontent.com/assets/11208810/14744288/802fbae0-08a6-11e6-9ec1-33b4870061d7.jpg)

So I need something similar using your plugin, the opportunity to make the notification disappear when I'm using the app and not only when I close the app.

Thanks
Enrico

**Comment by macdonst** [comment]
@debe78 Currently if you set `clearNotifications` in init it will clear on close of the app.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushnotificationinitoptions
