### ISSUE TITLE
Background Notifications received but not calling on('notification') event handler

### ISSUE THREAD

**Issue by purinagripal** [phonegap/phonegap-plugin-push#782]
### Expected Behaviour
I want my on('notification') event handler to be called when my app is in the background, because I want to store each notification data in the localStorage.

### Actual Behaviour
While the app is in the background, the on('notification') event handler is called only when I click one notification, so I only get the last notification data in the localStorage...
If the app is open the on('notification') event handler is called for each received notification, so I have all of them in localStorage, but I would like the same behavior while the app is in the background.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.1.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung

#### Cordova CLI version and cordova platform version
PhoneGap (iOS / Android / Windows)
cli-5.2.0 (3.9.1 / 4.1.1 / 3.8.1)

#### Plugin version
1.6.1

#### Sample Push Data Payload
{ "registration_ids":["REGIST_ID"],
  "data":{
         "notId":"61",
         "title":"titulo ejemplo",
         "message":"mensaje ejemplo",
         "id_evento":"61",
         "content-available":"1"
    }
}

#### Sample Code that illustrates the problem

```
push.on('notification', function(data) {
            
            var notif_anteriores;
            
            if( window.localStorage.getItem('notificaciones') ) {
                // tenemos notificaciones guardadas
                notif_anteriores = window.localStorage.getItem('notificaciones');
                notif_anteriores = JSON.parse(notif_anteriores);
                // añadimos la nueva
                notif_anteriores.push(data.additionalData.id_evento);
                
                window.localStorage.setItem('notificaciones', JSON.stringify(notif_anteriores));
                
            } else {
                // aun no hay ninguna notificacion guardada
                notif_anteriores = [data.additionalData.id_evento];
                // guardamos la primera
                window.localStorage.setItem( 'notificaciones', JSON.stringify(notif_anteriores) );
            }
        });

```

**Comment by macdonst** [comment]
@purinagripal that should work as long as the app is in the background. If the app is closed you won't get the `on('notification')` event called.

**Comment by purinagripal** [comment]
You're right! It works.

The only way to have the data of each notification in localStore is with the app never closed??

**Comment by macdonst** [comment]
@purinagripal yeah, there is an enhancement I have to figure out how to do #158 to wake up the app without bringing it to the foreground so the web view can run the JS after someone closes the app.

**Comment by purinagripal** [comment]
Now when the user clicks in the "exit button" I call "navigator.app.exitApp()", so in instance I should use some function to send my app to the background...

I read about use a plugin to do that, but I would like some more simple... is not possible??

Something like navigator.app.toBackgroundApp() ??? 
I try to find docs about it but I couldn't find them...

**Comment by macdonst** [comment]
@purinagripal don't ever call `navigator.app.exitApp()` it goes against Android UI guidelines and I wish we never added it in Cordova Android. Your users should leave you app by using the back button.

**Comment by purinagripal** [comment]
But using the backbutton the app get closed, I need the app in the background to get all the notifications
