### ISSUE TITLE
Push notifications & onNotification not working

### ISSUE THREAD

**Issue by techSavvySaahil** [phonegap/phonegap-plugin-push#783]
### Expected Behaviour
Get Notifications while the app is running in background

### Actual Behaviour
No push notifications received and push.on('notification') not called

### Reproduce Scenario (including but not limited to)
onRegistration is getting called & registrationID is there.
But when a notification comes in the app in background or foreground, no push notification comes.

#### Cordova CLI version and cordova platform version

    cordova --version : 6.0.0
    cordova platform version android  5.1.1

#### Plugin version

   phonegap-plugin-push   # e.g. 1.6.1

#### Sample Code that illustrates the problem
			var app = {
			    // Application Constructor
			    initialize: function() {
			        this.bindEvents();
			    },
			    // Bind Event Listeners
			    //
			    // Bind any events that are required on startup. Common events are:
			    // 'load', 'deviceready', 'offline', and 'online'.
			    bindEvents: function() {
			        document.addEventListener('deviceready', this.onDeviceReady, false);
			    },
			    // deviceready Event Handler
			    //
			    // The scope of 'this' is the event. In order to call the 'receivedEvent'
			    // function, we must explicitly call 'app.receivedEvent(...);'
			    onDeviceReady: function() {
			        var push = PushNotification.init({
			            "android": {
			                "senderID": "xxxxxxxxxxx"
			            },
			            "ios": {"alert": "true", "badge": "true", "sound": "true"}, 
			            "windows": {}
			        });
			        
			        push.on('registration', function(data) {
			            console.log('registered);
			            // document.getElementById("regId").innerHTML = data.registrationId;
			            console.log(JSON.stringify(data));
			        });

			        push.on('notification', function(){
			        	console.log("notified");
			        });
			        var cards = document.getElementById("cards");
			            var card = '<div class="row">' +
					  		   '<div class="col s12 m6">' +
							   '  <div class="card darken-1">' +
							   '    <div class="card-content black-text">' +
							   '      <span class="card-title black-text">' + data.title + '</span>' +
							  '      <p>' + data.message + '</p>' +
							  '    </div>' +
							  '  </div>' +
							  ' </div>' +
							  '</div>';
			            cards.innerHTML += card;
			            
			            push.finish(function () {
			                console.log('finish successfully called');
			            });
			            push.on('error', function(e) {
				            console.log("push error");
				        });
			        }

			        
			    }
			};

			app.initialize();

**Comment by macdonst** [comment]
@techSavvySaahil without the push payload and method in which you are sending the push I cannot reproduce this.

**Comment by techSavvySaahil** [comment]
{
						"timestamp": new Date().getTime(),
		    			"number": result[0].number,
		    			"alertData": {
		    				"message": message,
		    				"type": "SHARING" || "",
		    				"sharedFile" : params.sharedFile,
		    				"sharedBy" : params.sharedBy,
		    				"data": {},
		    			},
		    			"category": "ABC" || ""
				}

**Comment by techSavvySaahil** [comment]
And I'm using GCM

**Comment by macdonst** [comment]
@techSavvySaahil and how are you sending the info?

**Comment by techSavvySaahil** [comment]
I'm emitting through socket.
And I've one more doubt this init() is registering the push also ?

**Comment by macdonst** [comment]
@techSavvySaahil how are you sending the push to GCM? The format you are using doesn't look like anything I've ever seen before.

**Comment by HenryYulaw** [comment]
@macdonst I'm having a similar problem. The notification is received but the push.on('notification') event is not fired. Both when in background and when the app is open.

**Comment by HenryYulaw** [comment]
@macdonst Logcat entry when notification is received on the device:

D/PushPlugin_GCMIntentService: onMessage - from: myID
D/PushPlugin_GCMIntentService: normalize extras
D/PushPlugin_GCMIntentService: key = message
D/PushPlugin_GCMIntentService: replace key message with message
D/PushPlugin_GCMIntentService: key = collapse_key
D/PushPlugin_GCMIntentService: replace key collapse_key with collapse_key
D/PushPlugin_GCMIntentService: background
D/PushPlugin_GCMIntentService: message =[myMessage]
D/PushPlugin_GCMIntentService: title =[null]
D/PushPlugin_GCMIntentService: contentAvailable =[null]
D/PushPlugin_GCMIntentService: create notification
E/PushPlugin_GCMIntentService: Number format exception - Error parsing notId: Invalid int: "null"
D/PushPlugin_GCMIntentService: stored icon=null
D/PushPlugin_GCMIntentService: stored iconColor=null
D/PushPlugin_GCMIntentService: stored sound=true
D/PushPlugin_GCMIntentService: stored vibrate=true
D/PushPlugin_GCMIntentService: no icon resource found - using application icon
D/PushPlugin_GCMIntentService: create actions
V/NotificationManager: com.abletranslations.portable23: notify(0, Notification(pri=0 contentView=com.abletranslations.portable23/0x109007d vibrate=default sound=content://settings/system/notification_sound defaults=0x2 flags=0x10 color=0x00000000 vis=PRIVATE))

**Comment by HenryYulaw** [comment]
Ok, so the event is only called when the notification is actually pressed. If  I manually open the app after receiving the notification, nothing happens. Is that correct?

**Comment by macdonst** [comment]
@HenryYulaw correct, the event isn't fired unless you click on the notification. If you want the event called even when the user doesn't click on the notification check the docs on Background Notifications.

**Comment by divyekhanna** [comment]
@macdonst I'm having exactly the same issue as @techSavvySaahil 

I get `success: 1` from GCM (`https://gcm-http.googleapis.com/gcm/send`) but I get not notification on the android device ... and the 'notification' event is also not fired.

Thanks!

**Comment by macdonst** [comment]
@divyekhanna I need to know the payload of the message in order to help.

**Comment by divyekhanna** [comment]
@macdonst This is the payload:

```
{ 
    "priority":"high",
    "notification": {
        "title": "Stample title notif",
        "body": "Stample title notif",
        "text": "Stample text notif"
    },
    "to" : "gcm-device-token"
}
```

`POST` request to `https://gcm-http.googleapis.com/gcm/send`

Thanks.

**Comment by yesnoj** [comment]
Well...same problem here(Android). When I'm on iOS it works, but if the payload is'n in a object called "notification" ...i can't see anything on the device,but i see the log becouse the push.on ('notification') is called (iOS).
Thanks.

**Comment by divyekhanna** [comment]
It works for me on iOS as well ... Android is the issue.

**Comment by solcre** [comment]
We are having the same problem, when the app is runing in background with Android. Unless the user clicks on the notification the event won't be fired. Also what @macdonst says about "check the docs on Background Notifications". It is not clear what we have to do to trigger the event in the background, if you mean sending a payload without tittle and message, that's what we did and had no luck.

**Comment by peterturquoise** [comment]
We're having the same issue. On Android if the app is in the background, the notification shows up in the shade notification area, but clicking on the notification does not launch the app. I have trie lots of variants of payload e.g.

{
"notification":
	{"title":"notification msg"},
 "data":
        {"title":"data msg","content-available":"1"}
}

In this payload, oddly, the same message ("data msg") is displayed whether the app is in the foreground or background.

**Comment by yesnoj** [comment]
i've posted a question here https://github.com/phonegap/phonegap-plugin-push/issues/801 maybe @peterturquoise this issue is the same for your...

**Comment by solcre** [comment]
We made it to make it work! We had to add: ,"content-available":"1", sadly
this is not documented, but we looked up in the 1.7.x branch and the
documentation was improved and there it says that you have to add that
key-value. After adding that to the payload it worked flawlessly.



[image: Solcre Technology Solutions]

Matias Fuster Coll
Solcre Technology Solutions
www.solcre.com
+598 2706 9927
Ing. Luis P. Ponce 1443A
11602 Montevideo, Uruguay

**Comment by peterturquoise** [comment]
@solcre  can you post your payload please. I tried with "content-available":"1" (as in my post) but when the app is in the background, then clicking on the notification in the shade does not bring the app to the front (nor launch the app if it is not running).

**Comment by solcre** [comment]
Do you mean the app closed from process manager ?



[image: Solcre Technology Solutions]

Matias Fuster Coll
Solcre Technology Solutions
www.solcre.com
+598 2706 9927
Ing. Luis P. Ponce 1443A
11602 Montevideo, Uruguay

**Comment by peterturquoise** [comment]
1) The app is running but in the background
2) I send it a push notification
3) The notification appears at the top of the hone screen in the shade
notification area
4) I click on the notification
5) The app does not come to the front

Does this work for you ? I've tried the payload in lots of different
variations but can't get the notification click to work. If it does work
for you, could you please post a sample payload that works.

Thanks

Peter

On 13 April 2016 at 17:33, Solcre Development Team <notifications@github.com
> wrote:

> Do you mean the app closed from process manager ?
>
>
>
> [image: Solcre Technology Solutions]
>
> Matias Fuster Coll
> Solcre Technology Solutions
> www.solcre.com
> +598 2706 9927
> Ing. Luis P. Ponce 1443A
> 11602 Montevideo, Uruguay
>
> On Wed, Apr 13, 2016 at 1:10 PM, peter <notifications@github.com> wrote:
>
> > @solcre <https://github.com/solcre> can you post your payload please. I
> > tried with "content-available":"1" (as in my post) but when the app is in
> > the background, then clicking on the notification in the shade does not
> > bring the app to the front (nor launch the app if it is not running).
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/phonegap/phonegap-plugin-push/issues/783#issuecomment-209526522
> >
>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-plugin-push/issues/783#issuecomment-209533864>
>



-- 
Founder & CTO Tailster.com, Third Floor, 22, Bloomsbury Street, WC1B 3QJ
<https://www.google.co.uk/maps/preview?hl=en&saddr=&daddr=WC1B+3QJ>, Tel. 0208
004 0860

**Comment by solcre** [comment]
The payload is the same as you and it works. What phone are you testing
this on? Looks more like an issue with the phone than with the plugin since
the functionality of launching the app to the front is from the phone.



[image: Solcre Technology Solutions]

Matias Fuster Coll
Solcre Technology Solutions
www.solcre.com
+598 2706 9927
Ing. Luis P. Ponce 1443A
11602 Montevideo, Uruguay

**Comment by macdonst** [comment]
@divyekhanna use this as a payload:

```
{ 
    "priority":"high",
    "data": {
        "title": "Stample title notif",
        "body": "Stample title notif",
        "text": "Stample text notif"
    },
    "to" : "gcm-device-token"
}
```

Use the `data` object not `notification` object.

**Comment by macdonst** [comment]
@solcre what part of the documentation wasn't clear? I'm always looking to improve. 

It's been documented that you need "content-available":"1" on this page https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications since about December in order to get `on('notification')` to fire when the app is in the background.

**Comment by macdonst** [comment]
@peterturquoise Look at the PAYLOAD.md doc for lots of examples.

**Comment by solcre** [comment]
Mmmm I see it now, maybe I was looking for an old doc, weird, I had to check the documentation of 1.7.x to read about de content-available. Also the part from the Huawei and Xiaomi Phones was not there either when I saw the doc.. 

Thanks for your help!

**Comment by peterturquoise** [comment]
I am testing on an Alcatel Pixi - will try some other phones and see. Many
thanks for feedback

On 13 April 2016 at 18:13, Solcre Development Team <notifications@github.com
> wrote:

> The payload is the same as you and it works. What phone are you testing
> this on? Looks more like an issue with the phone than with the plugin since
> the functionality of launching the app to the front is from the phone.
>
>
>
> [image: Solcre Technology Solutions]
>
> Matias Fuster Coll
> Solcre Technology Solutions
> www.solcre.com
> +598 2706 9927
> Ing. Luis P. Ponce 1443A
> 11602 Montevideo, Uruguay
>
> On Wed, Apr 13, 2016 at 1:38 PM, peter <notifications@github.com> wrote:
>
> > 1) The app is running but in the background
> > 2) I send it a push notification
> > 3) The notification appears at the top of the hone screen in the shade
> > notification area
> > 4) I click on the notification
> > 5) The app does not come to the front
> >
> > Does this work for you ? I've tried the payload in lots of different
> > variations but can't get the notification click to work. If it does work
> > for you, could you please post a sample payload that works.
> >
> > Thanks
> >
> > Peter
> >
> > On 13 April 2016 at 17:33, Solcre Development Team <
> > notifications@github.com
> > > wrote:
> >
> > > Do you mean the app closed from process manager ?
> > >
> > >
> > >
> > > [image: Solcre Technology Solutions]
> > >
> > > Matias Fuster Coll
> > > Solcre Technology Solutions
> > > www.solcre.com
> > > +598 2706 9927
> > > Ing. Luis P. Ponce 1443A
> > > 11602 Montevideo, Uruguay
> > >
> > > On Wed, Apr 13, 2016 at 1:10 PM, peter <notifications@github.com>
> wrote:
> > >
> > > > @solcre <https://github.com/solcre> can you post your payload
> please.
> > I
> > > > tried with "content-available":"1" (as in my post) but when the app
> is
> > in
> > > > the background, then clicking on the notification in the shade does
> not
> > > > bring the app to the front (nor launch the app if it is not running).
> > > >
> > > > —
> > > > You are receiving this because you were mentioned.
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/phonegap/phonegap-plugin-push/issues/783#issuecomment-209526522
> > > >
> > >
> > > >
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/phonegap/phonegap-plugin-push/issues/783#issuecomment-209533864
> > >
> > >
> >
> >
> >
> > --
> > Founder & CTO Tailster.com, Third Floor, 22, Bloomsbury Street, WC1B 3QJ
> > <https://www.google.co.uk/maps/preview?hl=en&saddr=&daddr=WC1B+3QJ>,
> Tel.
> > 0208
> > 004 0860
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/phonegap/phonegap-plugin-push/issues/783#issuecomment-209535412
> >
>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-plugin-push/issues/783#issuecomment-209550066>
>



-- 
Founder & CTO Tailster.com, Third Floor, 22, Bloomsbury Street, WC1B 3QJ
<https://www.google.co.uk/maps/preview?hl=en&saddr=&daddr=WC1B+3QJ>, Tel. 0208
004 0860

**Comment by peterturquoise** [comment]
Simon,

thanks for the reply. I'm going to try with a different phone - Ive about
exhausted my variations on notification/data.

The documentation is pretty good and the plugin (usually) works great - so
excellent job

Thanks for the helpful replies

On 13 April 2016 at 19:34, Simon MacDonald <notifications@github.com> wrote:

> @peterturquoise <https://github.com/peterturquoise> Look at the
> PAYLOAD.md doc for lots of examples.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-plugin-push/issues/783#issuecomment-209586496>
>



-- 
Founder & CTO Tailster.com, Third Floor, 22, Bloomsbury Street, WC1B 3QJ
<https://www.google.co.uk/maps/preview?hl=en&saddr=&daddr=WC1B+3QJ>, Tel. 0208
004 0860

**Comment by macdonst** [comment]
@peterturquoise if you run `adb logcat | grep PushPlugin` while reproducing the issue it may help point us in the right direction.

**Comment by divyekhanna** [comment]
@macdonst I've tried with the `data` object, it is still not getting the notifications. I do get a `"success": 1,` in the HTTP callback object. I'm testing on Android 4.4.2

**Comment by techSavvySaahil** [comment]
Mine is working now in Android but not in iOS.
onDeviceReady: function() {
					        var push = PushNotification.init({
					            "android": {
					                "senderID": "xxxxxx",
					                forceShow:true
					            },
					            "ios": {
					            	"senderID": "xxxxxxxxxx",
									"gcmSandbox": true,
									"alert": "true", 
									"badge": "true", 
									"sound": "true"
								}, 
					            "windows": {} 
					        });
Payload is : 
"registration_ids" : tokens,
						    		"collapse_key":"score_update",
						    		"data" : {
											    "message":params.alertData.message,
											    "title" : "myapp",
											    "pageId" : "notifications",
											    "notId" :  notId,
											    "timeStamp" : new Date().getTime()
											 }

**Comment by macdonst** [comment]
@techSavvySaahil right you have to send different payloads on GCM Android vs GCM iOS.

Example payload for GCM on iOS: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons-using-gcm-on-ios

**Comment by techSavvySaahil** [comment]
@macdonst   What if I don't need action buttons ?

**Comment by macdonst** [comment]
@techSavvySaahil then don't send the category property. Everything else remains the same.

**Comment by solcre** [comment]
Simon, we found something really weird, when IOS app is running in
background, it executes the callback successfully but the webview
(crosswalk) gets refresh. Any idea why this can be?



[image: Solcre Technology Solutions]

Matias Fuster Coll
Solcre Technology Solutions
www.solcre.com
+598 2706 9927
Ing. Luis P. Ponce 1443A
11602 Montevideo, Uruguay

**Comment by techSavvySaahil** [comment]
@macdonst ::
This is my payload for iOS::
"registration_ids" : tokens,
						    	
						    		// "to" : token
						    		"notification" : {
											    "body":params.alertData.message,
											    "title" : "myApp" 
											 },
									"content_available":true


Now please tell me what I've to rectify in this payload.

**Comment by macdonst** [comment]
@techSavvySaahil should be:

```
{
    "registration_ids": ["my device id"],
   "content_available": true,
    "notification": {
        "title": "AUX Scrum",
        "body": "Scrum: Daily touchbase @ 10am Please be on time so we can cover everything on the agenda."
    }
}
```

**Comment by macdonst** [comment]
@solcre seems to be an unrelated issue or at least different enough from this one to warrant a new issue.
