### ISSUE TITLE
App crashes on startup - InstanceID problem

### ISSUE THREAD

**Issue by HenryYulaw** [phonegap/phonegap-plugin-push#787]
App crashes on startup when I try to run it on a device. Logs below.

Appreciate the help.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1.1
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Testing on LTE Blade S6
#### Cordova CLI version and cordova platform version

    cordova --version: 6.0.0
    cordova platform version android: 5.1.1

#### Plugin version

    1.6.1

#### Logs taken while reproducing problem
04-06 18:05:12.613: E/AndroidRuntime(30792): FATAL EXCEPTION: pool-1-thread-2
04-06 18:05:12.613: E/AndroidRuntime(30792): Process: com.abletranslations.portable23, PID: 30792
04-06 18:05:12.613: E/AndroidRuntime(30792): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceID;
04-06 18:05:12.613: E/AndroidRuntime(30792): 	at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:73)
04-06 18:05:12.613: E/AndroidRuntime(30792): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-06 18:05:12.613: E/AndroidRuntime(30792): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-06 18:05:12.613: E/AndroidRuntime(30792): 	at java.lang.Thread.run(Thread.java:818)
04-06 18:05:12.613: E/AndroidRuntime(30792): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.iid.InstanceID" on path: DexPathList[[zip file "/data/app/com.abletranslations.portable23-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
04-06 18:05:12.613: E/AndroidRuntime(30792): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-06 18:05:12.613: E/AndroidRuntime(30792): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-06 18:05:12.613: E/AndroidRuntime(30792): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-06 18:05:12.613: E/AndroidRuntime(30792): 	... 4 more
04-06 18:05:12.613: E/AndroidRuntime(30792): 	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.iid.InstanceID
04-06 18:05:12.613: E/AndroidRuntime(30792): 		at java.lang.Class.classForName(Native Method)
04-06 18:05:12.613: E/AndroidRuntime(30792): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-06 18:05:12.613: E/AndroidRuntime(30792): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-06 18:05:12.613: E/AndroidRuntime(30792): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-06 18:05:12.613: E/AndroidRuntime(30792): 		... 5 more
04-06 18:05:12.613: E/AndroidRuntime(30792): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by macdonst** [comment]
@HenryYulaw you are missing a library in your local Android setup.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#compilation

**Comment by HenryYulaw** [comment]
@macdonst I have the libraries installed as mentioned in the documentation, latest versions. Have updated as per the instructions anyway but the problem persists.

I have added the google-play-services.jar in Eclipse as that solved a bunch of errors after installing the plugin. Might have something to do with that?

**Comment by macdonst** [comment]
@HenryYulaw if you are compiling in Eclipse you really need to spend some time to move to AndroidStudio. My best guess is that your Eclipse instance is not pointing to where the correct Google Play Services code is.

**Comment by HenryYulaw** [comment]
I can confirm that moving to Android Studio solved the problem. The app now runs as intended.
Thank you for the help.
