### ISSUE TITLE
cordova plugin add error, for android, cannot find "/**plugin/abc.gradle/project.properties" referenced in <framework

### ISSUE THREAD

**Issue by amitdix** [phonegap/phonegap-plugin-push#788]
cordova plugin add *.git
Fetching plugin ".git" via git clone
Installing "****plugin" for android
Error during processing of action! Attempting to revert...
Failed to install '*******plugin':Error: Uh oh!
cannot find "/**plugin/abc.gradle/project.properties" referenced in <framework
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@amitdix what the heck is `cordova plugin add .git`?

**Comment by macdonst** [comment]
Closing, re-open with reproduction scenario.
