### ISSUE TITLE
Subscribe to Topics...

### ISSUE THREAD

**Issue by akreienbring** [phonegap/phonegap-plugin-push#79]
Hello,
It seems that subscribing to topics like explained here 
https://developers.google.com/cloud-messaging/topic-messaging 
is not implemented.

That would really be a nice enhancement... :-)

**Comment by akreienbring** [comment]
Thinking of contributing this functionality I just discovered that this plugin still uses gcm.jar and a API that is deprecated for more than 2 years. 

I don't think that is even possible to use the new GCMPubSub classes and the topic feature with this old library.

Are there any plans to migrate to the new API as referenced here:
https://developers.google.com/android/reference/com/google/android/gms/gcm/GoogleCloudMessaging
?

**Comment by macdonst** [comment]
@akreienbring with 1.4.0 release I've gotten rid of the gcm.jar. Paves the wave for subscribing to topics.

**Comment by akreienbring** [comment]
Good to hear.. In the meantime i've contributed to another repo: https://github.com/gonzaloaune/GCMPushPlugin/pull/6#issuecomment-149234576

**Comment by macdonst** [comment]
@akreienbring well 1.4.0 is now out and it no longer includes gcm.jar. We are up to date with the latest GCM libraries from Google. PR for topic functionality would be welcome.

**Comment by Telemakhos** [comment]
@akreienbring is spot on. This functionality would be an awesome addition to this plugin... in many use cases PusSub style notifications are enough for the app, no need to send the regID. Any ptrogress regarding this?

**Comment by sunojvijayan** [comment]
Hi, Can anyone please let me know if this is possible or not in the current system and if there is anyway to subscribe to multiple topics. Please let me know. Thanks in advance.

**Comment by macdonst** [comment]
@sunojvijayan currently not supported, eyeing support for 1.5.0 release.

**Comment by cvsakpal** [comment]
Hi all,
Topic Messaging seems like an important enhancement. Is someone working on this, when is the next release expected? 
In the meantime, I'll checkout @akreienbring 's repo.

**Comment by jellomaster** [comment]
gcm support for ios and supporting topics for ios/android should be top of the list :)

**Comment by macdonst** [comment]
Yup, this functionality is near the top of my to do list. I'm currently working on some exciting new functionality in order to make testing push much easier.

If @akreienbring wants to contribute to this repo I'd be happy as the initial limitations for not supporting topics has been taken care of.

**Comment by marianoarga** [comment]
+1 on topic's enhancement

**Comment by macdonst** [comment]
I checked in a working Android version to the v1.5.x branch and in progress iOS work is in branch `issue79`. I've been able to register for topics but not receive a push so help is appreciated.

**Comment by cvsakpal** [comment]
I was able to get @akreienbring's code working and send notifications (topic messaging) to my app using ToothlessGear/node-gcm... I'm stuck @ a point where on clicking the notification I'm not able to open the app...
@macdonst I'll checkout your branch and see if I can be of any help... Thanks for working on this btw...

**Comment by cvsakpal** [comment]
Added subscribeToTopics and unsubscribeFromTopics methods... I needed those to subscribe after a user has logged in into my app... and unsubscribe on logout... Used @akreienbring's code and merged some of it...
https://github.com/cvsakpal/phonegap-plugin-push.git

**Comment by cvsakpal** [comment]
https://github.com/phonegap/phonegap-plugin-push/issues/387
although this bug isn't with the plugin, I think it shud be documented... this is where I was stuck with akreienbring's code too...

**Comment by macdonst** [comment]
@cvsakpal all of the Android work is done and it is in v1.5.x branch. Still need to figure out why I can't receive notifications in the issue79 branch. Topic registration on iOS works fine.

**Comment by macdonst** [comment]
Merged into master but will need to fix reception of topic messages on iOS, see issue #440

**Comment by Gnaneshwar511** [comment]
I don't know whether it is a problem with subscribing to topics or with the inability to send Notification to a topic, but I'm not able to receive them on my apple device.
If I send it with Device Id, then the same payload is working fine. Can someone please help!

**Comment by adriferracuti** [comment]
@Gnaneshwar511 in my case adding the `message` field (and a value) to the payload made the trick

**Comment by naveedahmed1** [comment]
As per the below link, in order to manage topic subscriptions on the server we need Instance ID:

https://firebase.google.com/docs/cloud-messaging/android/topic-messaging

So that we can manage topic subscription/unsubscripton on server by following instructions mentioned here:

https://developers.google.com/instance-id/reference/server#create_a_relation_mapping_for_an_app_instance


Does this plugin also provides access to Instance ID? so that it could be passed it to server on registration/subscription?
