### ISSUE TITLE
Did not show notification in status bar for Xiomi Redmi Note 3

### ISSUE THREAD

**Issue by aishahismail** [phonegap/phonegap-plugin-push#790]
Device details: 
MIUI version - MIUI 7.0

I created Ionic project using this plugin for push notification. The notification is received but did not show in status bar. I already test in other devices with different model and brand and everything is okay. Thank you.

**Comment by yesnoj** [comment]
i've problem with my Galaxy Note 3, the method : 
push.on('notification', function(data) {
// ecc ecc ecc        
});
is never executed.Instead on iPhone 6s works perfectly... :/

**Comment by ericb** [comment]
@aishahismail : You may need to set `forceShow: true` in the plugin config options. For reference, you also need to call `register` on each app load. 

@yesnoj You're likely not getting the notification at all. you should check your message statuses.

**Comment by aishahismail** [comment]
Did you mean by putting `forceShow: true` in a init?

```
var push = PushNotification.init({
    android: {
        senderID: "12345679",
        forceShow: true
    },
    ios: {
        alert: "true",
        badge: "true",
        sound: "true"
    },
    windows: {}
});
```

Thanks

**Comment by macdonst** [comment]
@aishahismail check issue #707. It's the way the phone's OS handles pushes, not the plugin.

**Comment by yesnoj** [comment]
How can i read the message statuses?I don't have any error in consolle.The notification appears correctly on the status bar,but i cannot see any log on consolle about push.on('notification', function(data) {
// ecc ecc ecc 
});
Any help?
Another thing, if i generate notification from my server,i have an object (additionalData) with all the fields, the notification arrives but i can't see on the status bar (iOS),is becouse there isn't a notification object witch include the previous additionalData object?
