### ISSUE TITLE
Sometimes the onRegistration callback is never called

### ISSUE THREAD

**Issue by jakub-g** [phonegap/phonegap-plugin-push#791]
### Expected Behaviour

I should be able to assure that `onRegistration` callback was called, or in case it's impossible within a given timeout, an error should be raised
### Actual Behaviour

I've noticed that sometimes the `onRegistration` callback is never called, nor the `onError` callback.
Not sure why, is it Google backend issue, or plugin issue. I'm on a reliable WiFi network.
### Proposal

Perhaps if the callback is not called within 30-60 seconds, the plugin should raise an error?
I can do it manually in my own code, but it's such a common use case that maybe the plugin should expose an API for that.
#### Platform and Version

Android 5.1
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Motorola Moto G3
#### Cordova CLI version and cordova platform version

```
cordova --version                                    # 6.0.0
cordova platform version android                     # 4.1.1
```
#### Plugin version

1.6.0
#### Sample Code that illustrates the problem

```
self._pushPlugin = window.PushNotification.init({
  android: {
    senderID: MY_GCM_SENDER_ID,
    iconColor: "blue",
    icon: "push_notification_icon",
    forceShow: false
  }
});

self._pushPlugin.on('registration', function(data) {
  $log.info('[onRegistration]');
}

self._pushPlugin.on('error', function(err) {
  $log.error('[onError]');
  $log.error(err);
});
```

**Comment by mauron85** [comment]
What are the actual consequences of this? I can image if on registration event is not called, app is using old expired registrationId.

Do it means if you're sending push notifications from your server it just might not work?

I'm asking, because this is the behaviour I'm facing now. Sometimes my App event started fresh, is just not receiving push notifications, until I restart it one more time. My app listener to 'registration' event is registered on deviceready, so basically it makes sense to me, that restart is required, when on 'registration' is not fired.

**Comment by jakub-g** [comment]
@mauron85 

Yes it's exactly like this.

I initialize the plugin at each app boot, because the registrationID can change (generally I get the same registrationID each time)

Additionally, when I log out the user, I call `unregister` and `init` again, to obtain a new registrationID for the new user. Usually I get the new value just fine, but sometimes the callback is never called hence the active registrationID is `null` (when I receive registrationID via pushplugin, I store it in memory in a global singleton and I have a feature in the app that can display me some debug info like the current registrationID, and sometimes I see it's `null`)

In fact I just realized that maybe it's the two calls in quick succession that are introducing the issue.
I have a promisified wrapped on top of the pushplugin, and in my logout method I do something like this:

    // unregister the old token, and obtain the new one for the next user
    PushNotificationService.unregister().then(function() {
      PushNotificationService.init();
    }

The `unregister` promise is resolved only in success callback of [`pushPlugin.unregister`](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushunregistersuccesshandler-errorhandler-topics)

**Comment by mauron85** [comment]
@jakub-g basically, I do the same thing. Unregister on user logout and init on login. In logs I saw failed token update request, so maybe it's our server to blame. Anyway I need to investigate bit more, before making any conclusions. But please keep posting updates.
