### ISSUE TITLE
Windows Phone configuration

### ISSUE THREAD

**Issue by jfredsilva** [phonegap/phonegap-plugin-push#792]
Hi, 

I'm building an app with Visual Studio 2013 Tools for Apache Cordova.
Notifications for Android and iOS are working but i'ma having some dificulties on Windows Phone.

I know the configurations for iOS and Windows Phone, but what do I need to put for Windows Phone.

var MobileNotification = {
        configurations: {
          iosConfig: {
            "badge": true,
            "sound": true,
            "alert": true,
          },
          androidConfig: {
            "senderID": "xxxxxxxxxx"
          },
          windowsConfig: {
            "toimpment": "toimplement"
          }
}

Another question is where do I put my WNS informations, such as Package SID, Application identity, Client secret.

Thanks

**Comment by rakatyal** [comment]
Hi @jfredsilva. Windows doesn't need any parameters to start with. The package SID and other details are used to authenticate your cloud service which would send the push notifications to the client and then to send the notifications. You can find more details [here](https://msdn.microsoft.com/en-us/library/windows/apps/xaml/hh868252(v=win.10)).
