### ISSUE TITLE
Why is android.senderID required on PushNotification.init()?

### ISSUE THREAD

**Issue by njtman** [phonegap/phonegap-plugin-push#793]
Why is it mandatory to provide `android.senderID` when initializing the push plugin on android via `PushNotification.init()` when the same project id is also required to be provided as a plugin variable when installing the plugin?

Shouldn't the plugin remember the GCM project id via the `SENDER_ID` variable from the plugin install?
Am I missing something here?

**Comment by macdonst** [comment]
Explained in #689

**Comment by njtman** [comment]
Thanks @macdonst . I did try to search for such a topic before opening this one up, but didn't stumble upon that thread.  Sorry about that.

**Comment by macdonst** [comment]
No problem
