### ISSUE TITLE
Unregistered triggered 1 second after register, no notifications received

### ISSUE THREAD

**Issue by octavianpetrescu** [phonegap/phonegap-plugin-push#794]
### Actual Behaviour
It triggers the unregister event after 1 sec and I cannot receive any notification

### Reproduce Scenario (including but not limited to)
I am on development scenario, first it worked fine, but after I reinstaled some times
the apk, it happened this.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1.1 and Ios 4.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Nexus 5X, Samsung S4

#### Cordova CLI version and cordova platform version

    cordova --version     6.1.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.6.1

Any help is apreciate.

**Comment by macdonst** [comment]
@octavianpetrescu show some code

**Comment by octavianpetrescu** [comment]
let push = PushNotification.init({
            android: {
                senderID: Constants.GCMSenderId,
                forceShow: true
            },
            ios: {
                alert: true,
                badge: true,
                sound: true
            },
            windows: {}
        });

        push.on('registration', (data) => {
            DataStore.SetRegistrationId(data.registrationId);
        });

        push.on('notification', (data) => {
            if (CurrentProfile.IsLogedIn()) {
                console.log(data);
                console.log(data.additionalData);
            }
        });

        push.on('error', (e) => {
            NotificationManager.showErrorNotification(e.message);
        });

        push.unregister(function () {
            alert('success unregister');
        }, function () {
            alert('error ');
        });

And It always show the alert from unregistered

**Comment by octavianpetrescu** [comment]
I don't check the permissions.. I'm using typescript and "hasPermission" methode doesn't exist in typescript definition. This could be the problem?

**Comment by macdonst** [comment]
@octavianpetrescu line 1: is the call to registration. Line 29: you call unregister. So the code is working properly the way you have coded it. However, there is no reason for you to call unregister on line 29, why are you doing that? Did you copy this from a sample somewhere because I would like to find that sample and correct it?

**Comment by octavianpetrescu** [comment]
@macdonst You're wright! I wanted to unregister it and register again to see if it works, but not results. I deleted the unregister methdode. This is my code now:

let push = PushNotification.init({
            android: {
                senderID: Constants.GCMSenderId,
                forceShow: true
            },
            ios: {
                alert: true,
                badge: true,
                sound: true
            },
            windows: {}
        });

        push.on('registration', (data) => {
            console.log("regId:");
            console.log(data.registrationId);
            DataStore.SetRegistrationId(data.registrationId);
        });

        push.on('notification', (data) => {
            if (CurrentProfile.IsLogedIn()) {
                console.log(data);
                console.log(data.additionalData);
                var notification: INotificationDetails = <any>data.additionalData;
                Helpers.SwitchAgency(notification.MSP);
                Helpers.DisplayDetails(notification.Payload);
                if (Helpers.GetOSSystemUId() === OsType.Ios) {
                    push.setApplicationIconBadgeNumber(function () {
                        console.log("cleared with success");
                    }, function () {
                        console.log("error at cleaning badge");
                        }, 0);
                } 
            }
        });

        push.on('error', (e) => {
            NotificationManager.showErrorNotification(e.message);
            console.log(e.message);
        }); 

At this moment, I have this issue on Iphone 6 and Nexus 5X. I instaled the app on a new Device and it's working. 

Do you think it's something from permissions?

PS: Thanks for this!

**Comment by macdonst** [comment]
@octavianpetrescu sorry what is your issue now that you've moved unregister?

**Comment by octavianpetrescu** [comment]
@macdonst It's the same issue. I'm on the development environment, at the begining it worked well and I got the messages, but after reinstalled several times the app, I don't get the notifications anymore. I thought that I have some problem on the server with pushsharp, but I installed the app on a new device and it's working, but I can't make it work again on the devices I used for test and I don't know why. I tried to unregister and register again, but no success.

**Comment by macdonst** [comment]
@octavianpetrescu on Android uninstall and re-install the app and run `adb logcat | grep PushPlugin` to see what is going on.

**Comment by octavianpetrescu** [comment]
@macdonst I'm pretty new with Android Studio, but I think this is the log:

04-11 18:18:58.209   880  4043 I ActivityManager: Killing 17652:org.mozilla.firefox/u0a128 (adj 15): empty #17
04-11 18:18:58.245   880  4043 I ActivityManager: Killing 17848:com.google.android.apps.cloudprint/u0a42 (adj 15): empty #18
04-11 18:19:12.133   517   517 E QCALOG  : [MessageQ] ProcessNewMessage: [LOWI-SERVER] unknown deliver target [OS-Agent]
04-11 18:19:56.213 12539 12551 D QcrilMsgTunnelSocket: readRilMessage: Buffer = [B@2e89e83 HexData = [010000000404000011000000
514f454d484f4f4bef0308000100000000]
04-11 18:19:56.215 12539 12551 D QcrilMsgTunnelSocket: Rcvd UNSOL response with 28 bytes data for SUB0
04-11 18:19:56.216 12539 12551 D QcrilMsgTunnelSocket: Response ID 525295 is not served in this process.
04-11 18:19:56.218 12539 12551 D QcrilMsgTunnelSocket: To broadcast an Intent via the notifier to external apps
04-11 18:19:56.221 12539 12539 D QcrilMsgTunnelIfaceManager: handleMessage what = 0
04-11 18:19:56.223 12539 12539 D QcrilMsgTunnelIfaceManager: Broadcasting intent ACTION_UNSOL_RESPONSE_OEM_HOOK_RAW
04-11 18:20:12.134   517   517 E QCALOG  : [MessageQ] ProcessNewMessage: [LOWI-SERVER] unknown deliver target [OS-Agent]
04-11 18:21:12.134   517   517 E QCALOG  : [MessageQ] ProcessNewMessage: [LOWI-SERVER] unknown deliver target [OS-Agent]






I think this is the problem:  [MessageQ] ProcessNewMessage: [LOWI-SERVER] unknown deliver target [OS-Agent]. 
What do you think?

**Comment by macdonst** [comment]
@octavianpetrescu you want to filter the output in Android Studio. Follow this SO answer http://stackoverflow.com/a/19948588/41679 and put "PushPlugin" in as the filter.

**Comment by atsats** [comment]
I'm having a somewhat similar issue. I have an Android 6 device that has been working fine for many weeks with push registration and notifications. The same application works fine on Android 5, iOS and Windows UWP with registration and notifications.

Just this week, however, the app running on Android 6 (after a deinstall/reinstall cycle) is no longer able to successfully register with the notification hub (which is running in Azure). logcat shows a successful registration:

`04-13 13:06:01.587 24425 24466 V PushPlugin: onRegistered: {"registrationId":"fTOjNF2g6zQ:APA91bH5UsT_XFI7mlPeqwY9Psdlosjkjnk6K78agQN-Aiugwqeh2Rrg5NuTnHN7hLxbaGzLt1WfVHDChKLJfnjYdMOfE__62V6zw8lVVKf1ByV9FVoCCM0ANr7n49biwmks3DRG5IeQ"}
`
and no errors. This registration ID is apparently not usable in Azure and eventually gets rejected. Any suggestions on what to do next? I already exhausted my diagnostic options on the Azure side (from re-keying the APY to recreating the NH, but to no avail).

**Comment by atsats** [comment]
I finally managed to resolve this. I had to do an explicit unregister() call through the plugin, then the device was able to get a valid registration ID afterwards for connection to the notification hub.

Why this particular device got into this state, I don't know.

**Comment by atsats** [comment]
I'm able to reproduce this at will now and I have a work around and opened an associated issue: [#805](https://github.com/phonegap/phonegap-plugin-push/issues/805)
