### ISSUE TITLE
coldstart flag always set to true if the app has been opened through an alert, on ios 9.3.1, plugin version 1.6.2 cordova 6.1.0 cordova ios 4.1.1 

### ISSUE THREAD

**Issue by kilnan** [phonegap/phonegap-plugin-push#795]
### Expected Behaviour
coldstart flag is expected to be false when the notification is received while the app is open, either in background or foreground

### Actual Behaviour
coldstart flag seems to be always set to true if the app has been opened through a push notification alert

### Reproduce Scenario
open the app by clicking the app icon, send a notification to your device and check it. (foreground)
put the app in the background send a notification to your device and click on the alert to get to the app again, so check the received notification (background)

now, close the app and open it by clicking a notification. All the notifications received afterwards will have the coldstart flag set as true

#### Platform and Version
ios 9.3.1

#### Cordova CLI version and cordova platform version
cordova 6.1.0
cordova ios 4.1.1

#### Plugin version
1.6.2

#### Sample Push Data Payload
"payload": { "userId": 123, "goToPage": {"id":"subpage-chat", "parameters": {"conversationId":1}}}

#### Logs of received notification
foreground case:
{"count":0,"sound":"soundName","additionalData":{"foreground":true,"goToPage":{"id":"subpage-chat","parameters" {"conversationId":1}},"userId":123,"coldstart":true},"message":"Foo bar"}

background case: 
{"count":0,"sound":"soundName","additionalData":{"foreground":false,"goToPage":{"id":"subpage-chat","parameters":{"conversationId":1}},"userId":123,"coldstart":true},"message":"Foo bar"}

**Comment by kilnan** [comment]
I edited the description: I did not figured out that the flag was always set to true only if the app is opened through a push notification alert

**Comment by macdonst** [comment]
@kilnan I tested today and could not reproduce. I can get coldstart to flip between true and false depending if the app is started or not.

**Comment by kilnan** [comment]
To be sure to be on the same page, what I'm saying is that if we start the app with a notification, the notification that we used to open the app has correctly the coldstart flag set as true, but then also all the notifications we get afterwards have the flag set as true, while I would expect those to be set as false.

If we open the app "normally", by clicking the icon, the flag is always set as false, just like we would expect.

Let me know If is there any other detail I could provide to help you guys reproduce it.

**Comment by tgensol** [comment]
Not sure if I have the same issue, but the badge is always ON, for all my ios 9.3.1 users, as soon as they got one notification. I do not have more details for now to share with you. with 1.5.3 or 1.6.2 versions of the plugin. And this is since the new 9.3.1 iOs.

They can open and close the app, the notification will always stay on the icon of the application.

**Comment by macdonst** [comment]
@tgensol that is a totally different issue than what @kilnan has reported. Please open a new issue.

**Comment by macdonst** [comment]
@kilnan Fixed for the 1.7.0 release.
