### ISSUE TITLE
No Sound when app is in background

### ISSUE THREAD

**Issue by edujugon** [phonegap/phonegap-plugin-push#796]
Everything is working fine except the sound. when I have the app in background, the nofication only vibrates.

Should I add any extra code to play the sound when it's in background?

**Comment by macdonst** [comment]
@edujugon Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
