### ISSUE TITLE
Plugin init 

### ISSUE THREAD

**Issue by harslanhafeez** [phonegap/phonegap-plugin-push#798]
I could not understand init problem.
My app behaves like
login > init plugin and register tokens > feed page
now whenever app re-open
index.html >check if access_token is valid > feed page

After successful login to app I init the plugin and register GCM/APNS token in my server and assign it access_token from server.
whenever app  re-open it first check if access_token is still valid in index.html page and then goes to news feed page. I can not understand after initiating plugin in login page should i re-initiate this in index.html page or in feed page or in all pages? So whenever notification arrive it should listen for it...
My notification.js is:

```
(function($) {
	  var self;
	  var notification = function (){
	  "use strict";
	  self = notification;
  };
  
  notification.prototype={
	init:function (done){
		  document.addEventListener("deviceready", function(){
	  self.push = PushNotification.init({
			  "android": {
				  "senderID": "123456789",
				  "vibrate":"true",
				  "sound":"false",
				  "clearNotifications":"false",
			  }
		  });
	self.push.on('registration', function(data) {
			  done(data.registrationId);
		  });
		  self.push.on('notification', function(data) {
			  var id,tag ,noid; 
			  try{
				  id = data['additionalData']['source_id'];
				  tag = data['additionalData']['tag'];
				  noid = data['additionalData']['noid'];
			}
			  catch(ex){alert(ex);}
			  if(window.location.pathname == "/android_asset/www/index.html" || window.location.pathname == "/android_asset/www/SignIn.html")
			  {
			  		window.location.replace('notification/postPage.html?source_id='+id+'&tag='+tag);
			  }
			 else
			  	window.location.replace('../notification/postPage.html?source_id='+id+'&tag='+tag);
			  if(data.additionalData.coldstart)
				  alert('yes it is cold start');
			  self.push.finish(function () {
				  
				 console.log('finish successfully called');
			  });
		  });
		  
		  
			self.push.setApplicationIconBadgeNumber(function() {
				console.log('success');
			}, function(e) {
				console.log('error');
			}, 2);
  
		  self.push.on('error', function(e) {
			  self.init();
		  });
	  },false);
  }
  };
  $.notifications = new notification();
  
	})(jQuery);
  
```

**Comment by macdonst** [comment]
@harslanhafeez call init every time you start your app. There is always a chance the registration ID changed. Sometimes APNS/GCM will invalidate ID's.

If you call PushNotification.init on the login.html page and then you move to feed.html page all of your JS will be unloaded and you'll need to call PushNotification.init again.

**Comment by harslanhafeez** [comment]
@macdonst Thanks. But when app is closed and someone tap on notification card its open app and everything goes well.
however when app is in background (not closed) tap on notification it brings up app(feed.html page or some other) but nothing happens....?

**Comment by harslanhafeez** [comment]
Hi, @macdonst  I'm trying to calling PushNotification.init method in 
document.addEventListener('resume'... but it does not listening for registration not for notification event? I have tried $(document).off(); and then tried this.(several other methods) but still didn't work. Is any thing other that I can do? Its urgent....

**Comment by macdonst** [comment]
@harslanhafeez you should really look into single page architecture so your push notification event handlers don't get loaded and unloaded when you switch screens.
