### ISSUE TITLE
Windows registrationId

### ISSUE THREAD

**Issue by vespino** [phonegap/phonegap-plugin-push#799]
I use the following code:

var push = PushNotification.init({
	"android": {
		"senderID": "139434178007"
	},
	"ios": {
		"alert": "true",
		"badge": "true",
		"sound": "true"
	},
	"windows": {
	}
});

push.on('registration', function(data) {
	// data.registrationId
	localStorage.setItem('token', data.registrationId);
});

push.on('registration', function(data) {
	// data.registrationId
	localStorage.setItem('token', data.registrationId);
});
`

Android and iOS return a string (data.registrationId) I can use on my push server, but Windows seems to return an object. Is that a known feature or does Windows work differently from the other systems?

**Comment by rakatyal** [comment]
data.registrationId should give you a string. Windows implements the same API as Android and iOS.

**Comment by vespino** [comment]
Strange. Any idea why it could be returning an object?

**Comment by rakatyal** [comment]
No. data should be a object though. Does typeof (data.registrationId) gives you 'object' in return?

**Comment by vespino** [comment]
Not sure, I will do some more testing.

**Comment by daserge** [comment]
data.registrationId - is String:
https://msdn.microsoft.com/en-us/library/windows/apps/windows.networking.pushnotifications.pushnotificationchannel.uri.aspx
https://github.com/phonegap/phonegap-plugin-push/blob/151c8cd97aa71742798e969dd9e6c2208b8c1f15/src/windows/PushPluginProxy.js#L62
