### ISSUE TITLE
Notification callback for pushes without a message

### ISSUE THREAD

**Issue by iggyfisk** [phonegap/phonegap-plugin-push#80]
My service relies on a few push notifications without a message but with a payload, which means they'll be invisible when the app is in background mode but can be used in foreground mode to trigger a server refresh etc. This worked perfectly in the deprecated PushPlugin, but now I'm foiled by 
`else if (result && typeof result.message !== 'undefined')`
in push.js. Any chance we could check for additionalData / trigger some other event instead for "empty" notifications?

**Comment by macdonst** [comment]
@iggyfisk kk, I'll get a 1.2.1 out as soon as I can to fix the problem. It's actually a pretty trivial change.

**Comment by macdonst** [comment]
@iggyfisk fixed in master, 1.2.1 should be out soon.
