### ISSUE TITLE
iOS vs Android behaviours about push notifications (push.on('notification') never called on Android)

### ISSUE THREAD

**Issue by yesnoj** [phonegap/phonegap-plugin-push#801]
### Expected Behaviour
1) App background,the notification arrives (Android/iOS) , i click on notification and the app come back to foreground and trigg the push.on('notification'),if is in foreground the app trigg instantly the push.on('notification').
2)App closed, the notification arrives (Android/iOS), i click on notification and the app starts and trigg the push.on('notification').
### Actual Behaviour
Android)  App foreground,the notification arrives , i click on notification and the app DON'T trigg the push.on('notification'),if the app is closed using task manager and i click on notification the app start, but no push.on('notification') called.

iOS) If the app is in foreground, this trigg instantly the push.on('notification') and if is in background the app come back to foreground and trigg the push.on('notification') as expected,BUT if app is closed and i click on notification nothing happens,while on Android the app starts even if the push.on('notification') doesn't works.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0 and iOS 9.3.1
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Galaxy Note 3
iPhone 6s
#### Cordova CLI version and cordova platform version

    cordova 6.1.1
    cordova platform version android 5.1.0 and ios 4.0.1

#### Plugin version

    cordova plugin version 1.6.2

#### Sample Push Data Payload
HTTP POST to :
URL : https://push.ionic.io/api/v1/push
X-Ionic-Application-Id : XXXXXXXXX
Authorization : MySecretKey
```
{
  "tokens": [
    "d7avey-3kMM:APA91bxxxxxxx"
  ],
  "notification": {
    "alert": "Test",
    "title": "New test",
    "android": {
      "payload": {
        "id": "193348",
        "text": "Text example",
        "date": "21/03/2011 16:39",
        
      }
    },
    "ios": {
      "sound": "default",
      "payload": {
        "id": "193348",
        "text": "Text example",
        "date": "21/03/2011 16:39",
        
      }
    }
  }
}
```

#### Sample Code that illustrates the problem
This is the code i use for init the plugin:

```
 $rootScope.push = PushNotification.init({
                  android: {
                      senderID : 1049ZZZZZZZZ6,
                      forceShow : true,
                      vibrate : true,
                      sound : true,
                      icon : "notification_icon",
                      iconColor : "#1A8FCB",
                      clearNotification : true
                  },
                  
                  ios: {
                      alert: true,
                      badge: true,
                      clearBadge : true,
                      sound: true
                  }
              });
```

and this is the push.on

```
  $rootScope.push.on('notification', function(data) {
          $rootScope.$broadcast('newNotification', data);
              if(ionic.Platform.isIOS())
              {
                      $rootScope.push.getApplicationIconBadgeNumber(
                          function(n)
                          {
                              console.log("TEST" + n + 1);
                              var number = n+1;
                              $rootScope.push.setApplicationIconBadgeNumber(
                                  function() {},
                                  function() {},
                                  number
                              );
                          },
                          function() {}
                      );
              }
              else
              {
                  cordova.plugins.notification.badge.increase();
              }
     });
```

#### Logs taken while reproducing problem
No log because i don't get any error in console, simply the push.on('notification') isn't called
Please help.

**Comment by yesnoj** [comment]
No one can help me?!Is a bug or is my fault?!

**Comment by yesnoj** [comment]
Someone can help me with the badge increment?If i put the push.setApplicationIconBadgeNumber in push.on('notification') it increments only when i click on notification (app in background) or if the app is in foreground (totally useless),this becouse the first function called when an notification arrives is on('notification') ...where is the correct point to call this function?!Thanks

**Comment by macdonst** [comment]
@yesnoj use the `badge` property in the payload to have iOS set the badge number for you.

**Comment by yesnoj** [comment]
@macdonst so i pass the "badge : 1" in payload and use this as badgeNumber = badgeNumber + badge or something similar?

**Comment by macdonst** [comment]
@yesnoj if you pass `badge: 5` it will set the badge to 5, if you pass `badge: 3` it will set the badge to 3 and so on.

**Comment by yesnoj** [comment]
Uhmm...ok but so it can only be greater...how i can reset this badge for the next notification?!I want to reset the badge once i open the application ,and as i can see this is done automatically, but if in the next notification is badge : 11 ...isn't correct, becouse must be reset to 1

**Comment by macdonst** [comment]
@yesnoj use the setApplicationBadgeNumber method to set the badge to 0.
