### ISSUE TITLE
Init doesn't fire with PhoneGap Build

### ISSUE THREAD

**Issue by stileinverso** [phonegap/phonegap-plugin-push#802]
Hi, guys!
I'm trying to use **phonegap-plugin-push** inside my PG project for testing on my **Android** device.
I'm using **PhoneGap Build** (https://build.phonegap.com).
I spent a lot of time to configure it properly but... 
### My problem:
**PushNotification.init** doesn't fire on my device.
### Here the steps I do:

1. create a zip file for my project
2. upload on PhoneGap Build (https://build.phonegap.com)
3. download .apk on my PC
4. transfer it via bluetooth on my device
5. install
6. run

When the app starts the alert "device ready..." appears (see the code) but no other alert message appears.
If I remove "var push = ....... });" I can see "next step..." alert.

### Where I'm doing wrong?

**Project structure**

    [ .cordova ] // empty folder
    [ hooks ] // empty folder
    [ platforms ] // empty folder
    [ plugins ] // empty folder
    [ www ]
        [ css ]
        [ fonts ]
        [ img ]
        [ js ]
            index.js
        [ spec ]
        icon.png
        index.html
        spec.html
    config.xml

**index.js**

    document.addEventListener('deviceready', onDeviceReady, false);
    
    function onDeviceReady() {
    
        alert('device ready...');
    
        var push = PushNotification.init({
            "android": { "senderID": "***************" }, // <- here I've inserted my Project ID
            "ios": { "alert": "true", "badge": "true", "sound": "true" },
            "windows": {}
        });
    
        alert('next step...');
    
        push.on('registration', function(data) {
            alert('registration...');
            alert(data.registrationId);
            $('#gcm_id').html(data.registrationId);
        });
    
        push.on('notification', function(data) {
            alert('notification...');
            alert(data.title + " Message: " + data.message);
        });
    
        push.on('error', function(e) {
            alert('error!');
            console.log(e.message);
        });
    }

**config.xml**

    ...
    <gap:plugin name="com.phonegap.plugins.pushplugin"/>
    ...

**Comment by macdonst** [comment]
@stileinverso instructions for adding this plugin to config.xml for PGB are at:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md

the line you've shown from your config.xml is incorrect.

**Comment by stileinverso** [comment]
Cool! Thanks!!!
Here the edit I've done to my config.xml file:

    <preference name="android-minSdkVersion" value="14"/> 
    <preference name="android-build-tool" value="gradle" /> 
    <plugin name="phonegap-plugin-push" source="npm"> 
        <param name="SENDER_ID" value="*******" /> 
    </plugin>

**Comment by macdonst** [comment]
@stileinverso and did the above resolve your problem?

**Comment by stileinverso** [comment]
Yes, I receive push notification now!
It works, thanks again!
