### ISSUE TITLE
Hashed image url

### ISSUE THREAD

**Issue by wrrzag88** [phonegap/phonegap-plugin-push#803]
Hello!

I'm trying to customize my push notifications. 
Everithing works fine, but i've got a little question: Exists any way to set a hashed image url to the "image" field in the push payload? 

Being more specific, I can read the payload in the _push.on('notification', ...)_ method, but what I want is read the payload before show the notification and decode the hashed url and set it again in the payload image field.

I'm using push plugin version **1.5.3** and PhonegapCLI **5.4.1**

Thanks for your work!

**Comment by macdonst** [comment]
@wrrzag88 when you receive the data in the notification message the operating system has already displayed the notification in the shade. In order to make this change you would need to change code in GCMIntentService.java before it sets the url of the image to display for the push.
