### ISSUE TITLE
Android 6 PushPlugin registration doesn't work after app uninstall, reinstall sequence

### ISSUE THREAD

**Issue by atsats** [phonegap/phonegap-plugin-push#805]
### Expected Behaviour
Successful notification hub push registration after app uninstall, reinstall sequence
### Actual Behaviour
Push registration is not valid after  app uninstall, reinstall sequence
### Reproduce Scenario (including but not limited to)
Install app, uninstall app, then reinstall app
#### Steps to Reproduce 
Install app, uninstall app, then reinstall app
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Nexus 5X
#### Cordova CLI version and cordova platform version

    cordova --version     6.1.1
    cordova platform version android  5.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.6.2

#### Sample Push Data Payload
N/A
#### Sample Code that illustrates the problem
N/A
#### Logs taken while reproducing problem
Available if necessary; I saved all logs. (please see workaround and possible cause below)
### Workaround
Issue PushPlugin unregister() call. This seems to clear the environment and subsequent push registrations work.

### Possible Causes
On app uninstall, the PushPlugin may not be removing something from the environment causing subsequent re-registrations to fail.

**Comment by macdonst** [comment]
@atsats are you not getting the `on('registration')` event or are your failing to register with Azure?

**Comment by atsats** [comment]
The registration event fires and the call to register with the Azure NH appears to succeed in the sense that I see the registration in the list of registered devices. However, as soon as I attempt to send a push notification to the device, Azure returns a failure indicating that the registration is no longer valid and the device no longer shows in the list of registered devices.

**Comment by macdonst** [comment]
@atsats that seems to be an Azure problem. Can you take Azure out of the picture and just send using node-gcm? You can see a lot of examples here: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#android-behaviour

**Comment by atsats** [comment]
If it's caused by Azure, I'm not sure why calling unregister() on the device would resolve it. [I was able to reproduce this many times.] I'll try to look at node-gcm to see if it behaves differently there. Unfortunately, I'm quite behind on this project due to this and other issues so I may not get to it soon. If you want to close the issue in the meantime, that's fine - at least we have a workaround. Thanks

**Comment by macdonst** [comment]
@atsats I'm not sure what Azure does but sending a new registration ID to their service might just fix things for you. Using a quick node-gcm based script would not take much time at all. You can see a bunch of examples in PAYLOAD.md or http://macdonst.github.io/push-workshop/module4.html

**Comment by atsats** [comment]
@macdonst please give me a day and I'll let you know. Thanks for your fine work on this plugin and also for taking the time to respond to my issue!

**Comment by atsats** [comment]
@macdonst, you were right - the links you provided are quite easy to follow and they would definitely be very helpful in diagnosing these situations in the future. Unfortunately, I have not been able to get the Android 6 device in the same condition as yesterday. If I de-install the app and re-install, push notifications are still working.

There may be 2 situations that caused the device to get into this condition. 1) Repeated de-install/re-install sequences over the past 30 days (during development) and 2) re-registering at every app start (instead of using a previously stored registration): this was my fault and it was due to my misunderstanding the registration process. I fixed the code to register and save the token for future invocations. Coincidentally, Azure just implemented non-expiring device registrations, so the registration never has to be renewed.

I can't say for sure if these 2 situations caused the previous problem, but now, thanks to your reference, I have a better way to diagnose this if it happens again. Please feel free to close this issue. Thanks again for your help.
