### ISSUE TITLE
Android 4.1.2 - hasPermission fails.  PermissionUtils.java throws ClassNotFoundException

### ISSUE THREAD

**Issue by NGumby** [phonegap/phonegap-plugin-push#807]
### Expected Behaviour

hasPermission calls the success handler.
### Actual Behaviour

hasPermission never calls the callback.  on('error') is not triggered

PermissionUtils.java throws ClassNotFoundException
### Reproduce Scenario (including but not limited to)

 PushNotification.hasPermission(function (data) { console.log('hasPermission'); });
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 4.1.2
Google Play Services 7.3.29
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Kyocera C6522N
#### Cordova CLI version and cordova platform version

```
cordova --version                                    # e.g. 6.0.0
```

Tried 5.3.3 and 6.1.1
    cordova platform version android                     # e.g. 4.1.1
5.1.1
#### Plugin version

```
cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3
```

Tried 1.5.3 and 1.6.2
#### Logs taken while reproducing problem

Added a log in HAS_PERMISSION execute
V/PushPlugin( 3554): execute: action=hasPermission
V/PushPlugin( 3554): hasPermission UnknownError class not found

**Comment by macdonst** [comment]
@NGumby can you give me the full stack trace from the ClassNotFoundException?

**Comment by NGumby** [comment]
W/System.err(18128): java.lang.UnknownError: class not found

W/System.err(18128): 	at com.adobe.phonegap.push.PermissionUtils.hasPermission(PermissionUtils.java:42)

W/System.err(18128): 	at com.adobe.phonegap.push.PushPlugin$3.run(PushPlugin.java:173)

W/System.err(18128): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)

W/System.err(18128): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)

W/System.err(18128): 	at java.lang.Thread.run(Thread.java:856)

**Comment by macdonst** [comment]
@NGumby I flashed my old Nexus 7 with Android 4.1.2 but I can't reproduce this. What version of Google Play Services do you have on your device?

**Comment by NGumby** [comment]
Google Play Services 7.3.29

**Comment by macdonst** [comment]
@NGumby Hmmm...I don't know what to say here. I can't reproduce it. Actually you probably shouldn't even use hasPermission. I believe I will deprecate that method for the 2.0.0 release.

**Comment by NGumby** [comment]
hasPermission is really useful on ios.  This allows me to display a button with a link to the Settings when it is not allowed, or to warn to Allow Notifications.  I really hope you won't deprecate it.
How about just returning true on error (this is what I did to make it work)?

**Comment by Demayl** [comment]
Same here, tested on 4.1.2 and 4.2.2

**Comment by macdonst** [comment]
@Demayl sorry, are you saying you can or cannot reproduce the problem?

**Comment by Demayl** [comment]
@macdonst i can reproduce the problem. When it comes to .hasPermission() - his callback never get called, but there isn't any Java exception ( last message is that PushPlugin calls hasPermission ) in my case. I tested in on Nexus S 4.1.2 + Android emulators for 4.1.2 and 4.2.2. I will provide more details later.

**Comment by ujjal008** [comment]
Same problem here, tested on 4.1.2 and 4.2.2 
device token some time generate some time not.
Error:
Ionic Push: (debug) unexpected error occured. ionic.io.bundle.min.js:2
i.value ionic.io.bundle.min.js:2
Ionic Push: 
Error

**Comment by drbeermann** [comment]
Seeing this as well. Cordova 6.1.1 on a HTC Evo with Android 4.1.1.

**Comment by ryaa** [comment]
Also having the same problem on Samsung GT-P3110 with Android 4.2.2

**Comment by luka5** [comment]
Also having the same problem on android devices with API level < 19.
This is caused due to the fact, that the "AppOpsManager" class was added in API 19.

I recommend to simply return "true" for android API level older than 19.
In my tests, the push worked even if I set "show notifications and ring" to false in the app settings.

**Comment by macdonst** [comment]
We are only supporting Android 4.4 and higher now. There is a guard against this happening however.
