### ISSUE TITLE
Class not found issue

### ISSUE THREAD

**Issue by lukasztaras** [phonegap/phonegap-plugin-push#809]
Plugin version: 1.6.2
Android: 5.1.1

```
<plugin name="phonegap-plugin-push" version="1.6.2" src="https://github.com/phonegap/phonegap-plugin-push">
    <param name="SENDER_ID" value="1234567890" />
  </plugin>
  <feature name="phonegap-plugin-push">
    <param name="android-package" value="phonegap-plugin-push"></param>
  </feature>
```

After fireing the app. It throws Class not Found exception.

**Comment by macdonst** [comment]
@lukasztaras get rid of the feature tag completely. Can I see the CNFE stack trace?

**Comment by strabu** [comment]
I had the same problem when I built our application on the Build-Server (Visual Studio Team Services with Cordova Build).
For me it worked after setting the Cordova Version to: 6.1.1
on "Cordova Build for Android".

**Comment by macdonst** [comment]
Closing, inactivity
