### ISSUE TITLE
on('notification') not firing

### ISSUE THREAD

**Issue by LukeMadhanga** [phonegap/phonegap-plugin-push#810]
### Expected Behaviour
Get notification when App is in the Background. Click on notification from notification drawer, expect a JS alert saying notification received when App has opened. 

Get notification when App is in Background. No notification visible in the notification drawer but an alert saying notification received

### Actual Behaviour
Get notification when the App is in the Background. Click on notification. App opens. No alerts

Get notification when the App is in the foreground. Notification in the App drawer. Click on notification. App seems to reinitialise as if opening from cold (no splashscreen). No JS Alerts

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
HTC One M8, Android 6.0, HTC Sense 7.0

#### Cordova CLI version and cordova platform version
App built using Intel XDK. Basic build log:

> Building a Cordova 5.1.1 application.
> Using platform cordova-android 4.1.1.
> The application name is "XYZ"
> The package name is "com.xxx.xyz"
> Plugin "cordova-plugin-device" (1.0.1) installed.
> Plugin "nl.x-services.plugins.calendar" (4.3.4) installed.
> Plugin "cordova-plugin-globalization" (1.0.1) installed.
> Plugin "cordova-plugin-statusbar" (1.0.0) installed.
> Plugin "cordova-plugin-splashscreen" (2.1.0) installed.
> Plugin "cordova-plugin-geolocation" (1.0.1) installed.
> Plugin "cordova-plugin-inappbrowser" (1.0.1) installed.
> Plugin "cordova-plugin-network-information" (1.0.1) installed.
> Plugin "cordova-plugin-app-version" (0.1.8) installed.
> Plugin "cordova-plugin-x-socialsharing" (5.0.7) installed.
> Plugin "phonegap-plugin-push" (1.6.2) installed.
> Plugin "cordova-plugin-legacy-whitelist" (1.1.1) installed.
> App name updated to [XYZ]
> Updated "minSdkVersion" with "14"
> Updated "targetSdkVersion" with "19"
> Updated "installLocation" to "auto"
> Updated "versionCode" to "10"
> Updated "versionName" to "1.0.0"
> Added "debuggable" to "false"

#### Sample Push Data Payload
```json
{
    "registration_ids": [...],
    "data": {
        "sound": (boolean) 1,
        "vibrate": (boolean) 1,
        "title": "Notification title",
        "notId": 999,
        "message": "Notification message",
        "id": (custom) 999
    }
}
```

#### App init code
```js
registerAppForNotifications: function(force) {
    var creds = xxx();
    if ((!creds.applicationId || force) && !parent.ripples) {
        // Ripple is an emulatorm, if parent.ripple is present, do not run this code: Notifications cannot be run on an emulator
        // The application id has not yet been set, or needs resetting
        var push = App.m.system.push = PushNotification.init({
            android: {
                senderID: App.m.system.ANDROID_APP_ID
            },
            ios: {
                alert: "true",
                badge: true,
                sound: 'false'
            },
            windows: {}
        });
        push.on('registration', function(e) {
            if (e.registrationId) {
                // Send registrationId and uuid to the server
            }
        });
        push.on('notification', function(e) {
            alert('Received');
            alert(JSON.stringify(e));
            $.ajax({
                'url': 'http://localserver.com/to/log/what/is/here',
                type: 'post',
                dataType: 'json',
                data: {
                    payload: JSON.stringify(e)
                }
            });
        });
        push.on('error', function(e) {
            alert('Error');
            trace(JSON.stringify(e));
            $.ajax({
                'url': 'http://localserver.com/to/log/what/is/here',
                type: 'post',
                dataType: 'json',
                data: {
                    payload: JSON.stringify(e)
                }
            });
        });
        push.unregister(function() {
            App.m.system.unregisterAppForNotifications();
        }, function() {});
    }
},
```

#### PHP Code
```php
    function sendGoogleCloudMessage(array $regids) {
        $authkey = 'authkey';
        $url = 'https://gcm-http.googleapis.com/gcm/send';
        $notification = $this->notification;
        $notification['message'] = $notification['androidmessage'];
        unset($notification['androidmessage']);
        unset($notification['iosmessage']);
        // Note, the GCM documentation wants us to the 'notification' dictionary. However, the phonegap plugin prefers us to use the 
        //  data entry instead because using 'notification' means that the OS will take over and no custom functionality will be allowed.
        //  This could be updated if push notifications are ever implemented in another way
        $payload = ['registration_ids'  => $regids, 'data' => $notification];
        if ($this->data) {
            $payload['data'] += $this->data;
        }
        $headers = ["Authorization: key=$authkey", 'Content-Type: application/json'];
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($payload));
        curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4 ); // Be sure to use ipV4
        $res = curl_exec($ch);
        $curlerrorno = curl_errno($ch);
        if ($curlerrorno) {
            // Error handling
            return false;
        }
        curl_close($ch);
        $asjson = json_decode($res);
        return $asjson ? $asjson : $res;
    }
```

**Comment by jakari** [comment]
I am experiencing a similar issue... Have you tried if this helps: [https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications]()

I tried to use all combinations with content-available but the notification callback just isn't fired..

**Comment by LukeMadhanga** [comment]
@jakari Yeah I've done tried that too, thanks. When I first tried this several months ago it worked like a charm, but now it's not working. Since then, Intel XDK has changed, Android has updated and so has the plugin. It could be any one of those.

**Comment by DamodarSojka** [comment]
+1

**Comment by macdonst** [comment]
@LukeMadhanga can you run `adb logcat | grep PushPlugin` with your phone connected to your computer and in debug mode. I'd like to see some logs to further debug this problem.

**Comment by fredgalvao** [comment]
I modified your OP for better code readability, hoping you won'

**Comment by macdonst** [comment]
@fredgalvao haha, I didn't even see that. Someone somewhere added that as a blog post or something because that is at least the 5th person to make that mistake.

@LukeMadhanga get rid of that unregister block then retest. When it works, please close the issue.

**Comment by LukeMadhanga** [comment]
Ah right! Damn. I'll look for the original because I have a sneaky suspicion that I got it from here. I won't be able to get to my dev machine until Monday though

**Comment by macdonst** [comment]
@LukeMadhanga original what? I feel like there is a tutorial out there that needs to be fixed.

**Comment by fredgalvao** [comment]
There is no mention of the unregister code being used in such a context or anything similar in this repository currently: https://github.com/phonegap/phonegap-plugin-push/search?utf8=%E2%9C%93&q=unregister

That surely came from somewhere else on the web, and that needs to stop!
If you don't believe me, listen to God instead:
![image](https://cloud.githubusercontent.com/assets/616464/14573494/ca4fd162-032b-11e6-8cca-2a17c6987934.png)

**Comment by macdonst** [comment]
@fredgalvao agreed, if I could find the source of the mistake I'd go help get it corrected.

**Comment by xueenda** [comment]
Same here. Please fix it asap.

**Comment by fredgalvao** [comment]
@xueenda By "same here" do you mean you also call `.unregister()` at right after your `.init()`?

**Comment by yesnoj** [comment]
I've a function in my pushService where i define the unregister function
this.unregister = function  () {
        if ($rootScope.push){
            $rootScope.push.unregister(function() {
              console.log('Success unregister notification');
          }, function() {
              console.log('Error unregister notification');
          });
        }
      };
This is called on logout and on toggle to activate/deactivate push notification...isn't called by itself at the end of init, infact on iOS is working, only on Android there is this issue...

**Comment by LukeMadhanga** [comment]
I have to hang my head in shame on this one, it was indeed the onRegister function that was f***ing things up for me. That is indeed the source of the problem, the unregister function was doing everything it said it would in the docs, I don't know where I got it from!

Thanks for your help

**Comment by fredgalvao** [comment]
@xueenda and @yesnoj please create separated issues if your case isn't exactly the same as @LukeMadhanga.

**Comment by andymurakami** [comment]
If a send:

$resposta = shell_exec('curl -X POST --header '
            . '"Authorization: key=AAAAaUS7Nr4:APA91bHj3O-F4xyGheS2Umk6ZmJBfighcGBd_VTvsih7lAvJNGWyfd5udZVv_Bqchrq6I1Iim6BFRe_IxH1UANbetVb0ojAHx6vl-v4iP-5OzXtJ3tkixSlSZqWtZO6PhIYHJo5E0cBELVlv3kVDzbAF5e_iCqE_Bw"'
            . ' --header'
            . ' "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d '
            . '"{\"to\":\"' . $registrationIds[0] . '\",'
            . '\"priority\":\"high\",'
            . '\"content-available\":\"true\",'
//            . '\"notification\":{\"body\": \"Teste 646\",\"title\": \"teste\", \"id_oferta\": \"646\" }}"');
        . '\"data\":{\"body\": \"646\",\"title\": \"teste\", \"id_oferta\": \"646\" }}"');

Is OK, but use curl_exec, does not work
