### ISSUE TITLE
Deprecate hasPermission method for 2.0.0 release

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-plugin-push#811]
Remove the hasPermission method for the 2.0.0 release.
Add deprecation notice for 1.7.0 release.

**Comment by tropperstyle** [comment]
What will be the recommended way to prevent an immediate iOS permission dialog on first app start? I delay the first `init` call until I gracefully on-board the user to enable push notifications. I use the `hasPermission` check then to fire the `init` on `deviceready`

The API calls felt a bit awkward, but it was the only option.

**Comment by fredgalvao** [comment]
I'm also interested in the details reasoning around this deprecation/issue. `hasPersmission` is the start of something cool that would enable devs using our plugin to increase UX and conversion, and I don't quite understand what's wrong with it.

**Comment by macdonst** [comment]
Well, it doesn't really work. When you call `hasPermission` and it returns `false` what does that mean? Does it mean the user has selected no to the allow push dialog or does it mean the allow push dialog hasn't been shown yet? Because it can mean either of those things.

On iOS it's probably better for conversion if you provide your own UX before you may a call to PushNotification.init() so you can ready the users that the dialog is coming and they should say "Okay".

On Android the PermissionUtils class uses reflection which is slow on Android and there are problems with older versions of Android (4.1.2) causing crashes. As well it uses a method to figure out if the permission is allowed should only be used by System apps so I'm a bit worried that Google may complain someday about this code.

Happy to have a discussion on why it should be kept around though or fixes to make it more reliable.

**Comment by tropperstyle** [comment]
We need to call `PushNotification.init` onload to account for a change in the registration ID. But only selectively. We do not want to intrude new users with an instant plea for permissions. If we can still maintain this via another API change, then `hasPermssions` serves to purpose for the majority of use cases.

Check out the `autoRegister` option in the [OneSignal SDK](https://documentation.onesignal.com/docs/phonegap--cordova-sdk-api)

**Comment by fredgalvao** [comment]
Well, we can partially solve that by asking: `do I already have a registrationId provided by the plugin previously? if (yes) then {I need to call .init() ondeviceready to check for changes on that id} else {I can delay the call to .init() to the point where the user is ready to be optimally converted}.`.

Good points, thank you for explaining @macdonst.

**Comment by dbpieter** [comment]
@macdonst 
"When you call hasPermission() and it returns false what does that mean? Does it mean the user has selected no to the allow push dialog or does it mean the allow push dialog hasn't been shown yet?"

If you're calling hasPermission() after init() it can only mean one thing (no ?) ... The user has selected 'no' on the dialog. 

hasPermission() is very convenient if you want to coach the user into activating the messages (after they actively refused them). "Hey user x , this feature is awesome, please enable it" ...

**Comment by epeli** [comment]
Exactly what @dbpieter said. This is how it works on React Native and is very useful for informing the user about the missing permission. Init tricks can only go so far because this is also needed when the app returns from the background because the use might have disabled the permission from the settings.

**Comment by epeli** [comment]
Maybe more correct name for this would be `canReceivePushMessages()`?

**Comment by clembou590** [comment]
@macdonst 

Use case for using the HasPermission:

I do not let the user use the app until the registration is done
--> I call has Permission
 if NO Then I display a popup than cannot be removed by the user explaining that we need "push"

--> if yes, I hide the popup and go to next page...


Because we cannot know wether the user allowed or not the "push" on the "native dialog"
I loop on this function...


Without this function "HAS PERMISSION", how can I "disable" the user to go to next page?

**Comment by clembou590** [comment]
@macdonst 
maybe my explanation was not very precise.

One easier way to say it:

I need a popup to be displayed until the user has autorized the push. 
Today it's possible only because of the "hasPermission" function.

If tomorrow you remove it, how can we do it?

**Comment by macdonst** [comment]
Okay, let it never be said I don't listen to people. I've removed the deprecation notice but we need to make this API better.

**Comment by jworm7** [comment]
I agree with @macdonst and I have a specific example where the current implementation of `hasPermissions` breaks down: 

Call `init` on app load to check if we need to update the push id (in this case lets assume they already gave us permission). 

1. If the user disabled push since the last time they opened the app then we would get false from `hasPermissions` 

1. We would also get false if the user deleted and redownload the app or if the user got a new phone and logged in with their old account. 

In the first case we'd want to record that we don't want to send pushes anymore while in the second we'd want to prompt them again and get their new id. Has anyone encountered this issue and come up with a solution?

**Comment by fredgalvao** [comment]
@jworm7 mentioned scenarios where `hasPermissions()` **fails**, but not by it's own fault. It can be helped by other practices to make it work reliably.

You can and should identify, by many different ways, an installation of your application so you would know when **[2]** is the case. That would leave **[1]** an easy-to-discern case by exclusion.

* [2] using `device.uuid` from cordova you can *close-to-safely* identify the device itself, so you'd know when it's a new installation from an old user on a new device: 
```json
{
  "registrationId": "new",
  "device.uuid": "new",
  "user": "old",
  "UUID.v4()": "new",
  "hasPermission()": false
}
```
* [2] using `UUID.v4()`(node-uuid) you can generate a key to identify any and every installation of your application, so you would know when it's simply a new installation from an old user on an old device:
```json
{
  "registrationId": "new",
  "device.uuid": "old",
  "user": "old",
  "UUID.v4()": "new",
  "hasPermission()": false
}
```
* [1] if the app doesn't have permission to use push notifications but is a known installation, you know it's \<an installation that has never had push notifications enabled>`localStorage.getItem('registrationId') === null` or \<an installation that has had push notifications enabled once but had it disabled recently somehow>`localStorage.getItem('registrationId') !== null`:
```json
{
  "registrationId": "old|new",
  "device.uuid": "old",
  "user": "old",
  "UUID.v4()": "old",
  "hasPermission()": false
}
```

**Comment by ds8k** [comment]
I don't think there's anything inherently wrong with the idea, but `hasPermission` being set to `false` before the user has accepted or denied the permission is wrong.

**Comment by macdonst** [comment]
Closing, we decided not to deprecate it.

**Comment by jacquesdev** [comment]
@macdonst - I realise this is no longer being deprecated, but just wanted to give a suggestion on how to potentially solve this issue (assuming this method has the available data). 

Why can't we have values, undefined, false and true.

- Undefined means the permission has not yet been set
- False means the permission was expressly denied
- True means the permission was expressly granted

Happy to create a new issue to get this done if you think it could work?

**Comment by jaigtz88** [comment]
@jacquesdev agree, but do you encounter an issue when user select allow permission but has permission still on false status?
