### ISSUE TITLE
Tapping on the notification is not opening the app while in background.

### ISSUE THREAD

**Issue by DamodarSojka** [phonegap/phonegap-plugin-push#812]
### Expected Behaviour
Tapping on notification opens the app regardless if app is in the background or is not running.
### Actual Behaviour
Tapping on notification opens the app only if app is not running. When the app is in background tapping is not opening the app. As soon as app is opened the notification is processed. So .on() callback is called.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0.1
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy S4
#### Cordova CLI version and cordova platform version
6.1.1
4.1.1

#### Plugin version
1.6.2

#### Sample Push Data Payload
var message = new gcm.Message();
message.addData('title', 'Test Push');
message.addData('message', 'Push number 1');
message.addData('info', 'super secret info');
message.addData('content-available', '1');

**Comment by macdonst** [comment]
@DamodarSojka I can't reproduce this. Logs from `adb logcat | grep PushPlugin` would be helpful. Do you mess around with your AndroidManifest.xml at all?

**Comment by DamodarSojka** [comment]
Thanks for getting back to me. So what is the expected behaviour of the plugin. It should open the app then notification is tapped right? Regardless of it being in the background or being shut down completely? I am not able to provide logs from adb, I am using adobe build for building my app and vorlon for remote debugging. I have not touched Manifest, ionic and adobe build are handling that. Here it is in case you need it (drawables omitted):
<content src="index.html"/>
  <access origin="*"/>
  <preference name="webviewbounce" value="false"/>
  <preference name="UIWebViewBounce" value="false"/>
  <preference name="DisallowOverscroll" value="true"/>
  <preference name="android-minSdkVersion" value="16"/>
  <preference name="BackupWebStorage" value="none"/>
  <preference name="SplashScreen" value="screen"/>
  <preference name="SplashScreenDelay" value="3000"/>
  <preference name="android-build-tool" value="gradle" />
  <feature name="StatusBar">
    <param name="ios-package" value="CDVStatusBar" onload="true"/>
  </feature>

  <gap:plugin name="cordova-plugin-console" source="npm"/>
  <gap:plugin name="cordova-plugin-device" source="npm"/>
  <gap:plugin name="cordova-plugin-geolocation" source="npm"/>
  <gap:plugin name="cordova-plugin-splashscreen" source="npm"/>
  <gap:plugin name="cordova-plugin-statusbar" source="npm"/>
  <gap:plugin name="cordova-plugin-whitelist" source="npm"/>
  <gap:plugin name="ionic-plugin-keyboard" source="npm"/>
  <gap:plugin name="cordova-plugin-background-mode" source="npm"/>
  <gap:plugin name="cordova-plugin-app-event" source="npm"/>
  <gap:plugin name="de.appplant.cordova.plugin.local-notification" source="npm"/>
  <gap:plugin name="phonegap-plugin-push" source="npm">
    <param name="SENDER_ID" value="726081412676" />
  </gap:plugin>

  <gap:config-file platform="android" parent="/manifest/application">
    <activity android:launchMode="singleInstance" />
  </gap:config-file>

**Comment by macdonst** [comment]
@DamodarSojka yes, when you click on the notification it should open the app. The problem you are having is your are using `singleInstance` for your launchMode. Switch that to `singleTop` and you should be fine.

**Comment by DamodarSojka** [comment]
@macdonst 
Thanks! It works now. I think it might be helpful for some people to inlude information about that somewhere.

**Comment by macdonst** [comment]
@damodarsojka like the Android platform docs that say not to use `singleInstance`?

**Comment by vcrzy** [comment]
You can fire the on("notification") event when app is closed using the plugin phonegap-plugin-push > 1.6.2, and changing your backend response to :

```
{
   notification : {
      title : 'yourTitle',
      message : 'yourMessage'
   }
}
```

to 

```
{
   data : {
      title : 'yourTitle',
      message : 'yourMessage',
      content-available : "1" //only for IOS
   }
}
```
