### ISSUE TITLE
PushNotification is not defined

### ISSUE THREAD

**Issue by MHaendel** [phonegap/phonegap-plugin-push#814]
### Actual Behaviour

I added this to my config.xml
```xml
<preference name="android-build-tool" value="gradle" />
<plugin name="phonegap-plugin-push" source="npm">
    <param name="SENDER_ID" value="XXX" />
</plugin>
```

```js
document.addEventListener("deviceready", function() {
	var push = PushNotification.init({
		android: {
			senderID: "XXX"
		},
		ios: {
			alert: "true",
			badge: "true",
			sound: "true"
		},
		windows: {}
	});

	push.on('registration', function(data) {
		// data.registrationId
		console.log(JSON.stringify(data));
	});

	push.on('notification', function(data) {
		console.log(JSON.stringify(data));
	});

	push.on('error', function(e) {
		// e.message
		console.log(JSON.stringify(e));
	});
}, false);
```

It throws 
`undefined ReferenceError: PushNotification is not defined at .`

I can see the plugin in phonegap build and in `platform_www/plugins/phonegap-plugin-push`

cordova build android works just fine without errors.

#### Cordova CLI version and cordova platform version

    cordova --version: 6.0.0
    cordova platform version android: 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push: 1.6.2

**Comment by macdonst** [comment]
@MHaendel can you attach the Chrome debugger to your app and see if `PushNotification` gets defined?

**Comment by yesnoj** [comment]
"PushNotification is not defined" is typically an error during simulation on web-browser, i've this error too, testing the app on real device it works.

**Comment by MHaendel** [comment]
Its functional when I build it with phonegap and install the apk manually, but if I enter server information to the phonegap app on my device, it wont work.

**Comment by macdonst** [comment]
@MHaendel sorry, are you trying to run your app in the PhoneGap Dev app? If so that is not supported currently but will be soon (with caveats).

**Comment by MHaendel** [comment]
@macdonst Exactly! There should be some more documentation about it.
