### ISSUE TITLE
Help with iOS InvalidRegistration

### ISSUE THREAD

**Issue by vousys** [phonegap/phonegap-plugin-push#816]
Hi Simon, please, can you help me? I don't know what I'm doing wrong.
I'm creating a phonegap app, built with Javascript, for android an iOs and compile it via phonegap website.-

`Phonegap version: cli-5.4.1
`
Phonegap-plugin push at config.xml: 
```
     <gap:plugin name="phonegap-plugin-push" spec="~1.4.5" source="npm">
            <param name="SENDER_ID" value="XXXXX"/>
            <param name="GOOGLE_APP_ID" value="1:YYYY:ios:YYYY"/> 
        </gap:plugin>  
```
where XXXXX and YYYY are my project ID at console.developers.google.com

**Steps that i've done:**
1- Register at GCM
2- Go to Apple Member's center:
   a)  create a new app bundle ID without wildcard (*)  
   b) Create APNs certificates and mobileprovision file
   c) Create the p12 from keychain with the certificates of point b) and then upload it to GCM console.
3) Enable API at: https://console.developers.google.com/

I'm working in development mode.

In my server side, my php script can send perfectly to GCM the notifications to android, but when it has to send to an iOs device (ex: ipad) it says "InvalidRegistration". But is valid! because is what Ipad log in the event:

`push.on('registration', function(data) { alert(data.registrationId);});
`
Ex this are 2 device that I've to send:
```

 [3] => Array
        (
            [registration_id] => e0379ff6303921979f7b4c344c5234dd577b36b53df62b055dd5dc1c45850a26
            [device_model] => iPad5,3
            [device_platform] => iOS
            [device_uuid] => XXXXXXXXXXXXX
            [device_version] => 9.3.1
            [device_name] =>
        )

    [4] => Array
        (
            [registration_id] => f3y-pmQMlvQ:APA91bGHeWeUxH-6dk4zQzGKDSVH_Cfnqdv9fzXk0GQs6TRxrWjdEHSFYW4mvT6XtFJn75FP7sf5kkkrGHa5X3Xh1rANIcRPtotFUT3p6eXd3CpVtb_acK42SAZdzL1vfmcLb_hefSQf
            [device_model] => XT1058
            [device_platform] => Android
            [device_uuid] => XXXXXXXXXXXXX
            [device_version] => 5.1
            [device_name] =>
        )


```
And the log of that sending is:

```
 RESULT:stdClass Object
(
    [multicast_id] => 6.13549955387E+18
    [success] => 1
    [failure] => 4
    [canonical_ids] => 0
    [results] => Array
        (
            [0] => stdClass Object
                (
                    [error] => InvalidRegistration
                )

            [1] => stdClass Object
                (
                    [error] => MismatchSenderId
                )

            [2] => stdClass Object
                (
                    [error] => InvalidRegistration
                )

            [3] => stdClass Object
                (
                    [error] => InvalidRegistration
                )

            [4] => stdClass Object
                (
                    [message_id] => 0:1461092535705825%d1ee9114f9fd7ecd
                )

        )

)

```
Can you help me ? i don't know what else to do.

**Comment by macdonst** [comment]
@vousys it appears you are sending to both Android and iOS via GCM, correct? If that is the case you should know that GCM on iOS is not supported until version 1.5.0 of this plugin.

**Comment by vousys** [comment]
Hi Simon. I've change the version to 1.5.0  or 1.5.2  and happens the same.

```
       <gap:plugin name="phonegap-plugin-push" spec="~1.5.2" source="npm">
            <param name="SENDER_ID" value="XXX"/>
            <param name="GOOGLE_APP_ID" value="1:XXX:ios:XXX"/> 
        </gap:plugin>  


```

(Where XXX is the GCM project ID)


Those are 2 different registrationIDs I've tryed for the same Ipad : 

```
    [5] => Array
        (
            [registration_id] => 041012d6fca1df3a45e6199f47bf2d88b8a5d9baea455adcae84793adccf8f75
            [device_model] => iPad5,3
            [device_platform] => iOS
            [device_uuid] => CCCCCC
            [device_version] => 9.3.1
            [device_name] =>
        )

    [6] => Array
        (
            [registration_id] => ce9ee135815b13e37e1826676914dc06e3dd62bbb8cee8ed3be1d918ab6d11b7
            [device_model] => iPad5,3
            [device_platform] => iOS
            [device_uuid] => CCCCC
            [device_version] => 9.3.1
            [device_name] =>
        )

```
but the result is the same, what else could it be?
```

 RESULT:stdClass Object
(
    [multicast_id] => 4.69395958079E+18
    [success] => 1
    [failure] => 6
    [canonical_ids] => 0
    [results] => Array
        (
            [0] => stdClass Object
                (
                    [error] => InvalidRegistration
                )

            [1] => stdClass Object
                (
                    [error] => MismatchSenderId
                )

            [2] => stdClass Object
                (
                    [error] => InvalidRegistration
                )

            [3] => stdClass Object
                (
                    [error] => InvalidRegistration
                )

            [4] => stdClass Object
                (
                    [message_id] => 0:1461156689249030%d1ee9114f9fd7ecd
                )

            [5] => stdClass Object
                (
                    [error] => InvalidRegistration
                )

            [6] => stdClass Object
                (
                    [error] => InvalidRegistration
                )

        )

```
The only one that has worked is the notification to  Android.

**Comment by macdonst** [comment]
@vousys yes, I see that you are getting APNS style registration ID's on iOS. What are the parameters you pass to init?

**Comment by vousys** [comment]
Yes I figure this it out reading the following issue: https://github.com/phonegap/phonegap-plugin-push/issues/563   about the registration_ids length 

I'm trying now with your plugin version 1.5.3. I've also read your workshop example.

Now I've re-download the APNS certificates from apple and re-upload them to GCM but nothing changes.
New registration ID from ipad; 9a06ca42a2f0828780c4219cd69b4e4030de4d4f2ce002219197507eb7db0e5c

To init I use this:

```
	var push = PushNotification.init({
		    android: {
		        senderID: api.gcm.sender_id  // Es el ID del proyecto en la consola de GCM
		    },
		    ios: {
		        alert: "true",
		        badge: "true",
		        sound: "false"
		    },
		    windows: {}
		});


```

**Comment by vousys** [comment]
I've got a progress here . This issue: https://github.com/phonegap/phonegap-plugin-push/issues/563

I didn't was sending the sender_id at ios tag.

```

 var push = PushNotification.init({
            "android": {
                "senderID": "XXXX"
            },
            "ios": {
            "senderID": "XXXX",
            "gcmSandbox": "true",
            "alert": "true",
            "badge": "true",
            "sound": "true"
            },
            "windows": {}
        });

```

**Comment by macdonst** [comment]
@vousys yes, those two properties you've added are required for GCM iOS to work.

**Comment by ibrahimAboelsuod** [comment]
@vousys What was your findings? I am stuck exactly where you were, 

> The notifications says it was sent ok m but nothing happens on the screen

**Comment by vousys** [comment]
@ibrahimAboelsuod i've got it working right know, I'm using 
<gap:plugin name="phonegap-plugin-push" source="npm" spec="1.9.4">
And for ios I work with APNS
