### ISSUE TITLE
v1.6.2 failing to build for iOS in XDK

### ISSUE THREAD

**Issue by xgretsch** [phonegap/phonegap-plugin-push#817]
### Expected Behaviour

Correct build for both iOS and Android

### Actual Behaviour

Builds fine for Android, but build for iOS fails. The only error message in the build log is:

"Error: Plugin PushPlugin failed to install."

(By the way: backing off to the previous version available in the dialog, which is 1.4.3, results in a correct installation. So the problem crept in between versions 1.4.3 and 1.6.2)

### Reproduce Scenario (including but not limited to)

Add plugin to code and attempt to build.

#### Steps to Reproduce 

Add phonegap-plugin-push to project, either from Github or from the Cordova plugin repository. (By the way, if I add it from the "featured plugins section", it won't add at all - I get a cycle asking me to specify variables but not giving me anywhere to do so).

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

 Intel XDK, version 3088, including Cordova 5.1.1.

#### Cordova CLI version and cordova platform version

    cordova --version   5.1.1
    cordova platform version android: not sure how to get this from XDK

#### Plugin version
   
1.6.2

#### Logs taken while reproducing problem

BUILD FAILED
Build Log
Building a Cordova 5.1.1 application.
Using platform cordova-ios 3.8.0.
The application name is "xxxxxxxxx"
The package name is "com.xxxxxxxxxxxxx"
Plugin "cordova-plugin-device" (1.0.1) installed.
Plugin "nl.x-services.plugins.calendar" (4.3.4) installed.
Plugin "cordova-plugin-globalization" (1.0.1) installed.
Plugin "cordova-plugin-statusbar" (1.0.0) installed.
Plugin "cordova-plugin-splashscreen" (2.1.0) installed.
Plugin "cordova-plugin-geolocation" (1.0.1) installed.
Plugin "cordova-plugin-inappbrowser" (1.0.1) installed.
Plugin "cordova-plugin-network-information" (1.0.1) installed.
Plugin "cordova-plugin-app-version" (0.1.8) installed.
Plugin "cordova-plugin-x-socialsharing" (5.0.7) installed.
Error: Plugin PushPlugin failed to install.

**Comment by macdonst** [comment]
@xgretsch you are probably better off asking the IntelXDK team why it doesn't build but if I had to point you at an area I would say it is because you are using cordova-ios 3.8.0 while the latest version of this plugin requires cordova-ios 4.x or better.

**Comment by xgretsch** [comment]
Looks like you're right on this being a cordova-ios version issue.

I've asked the XDK people, who recommended a move to Cordova 5.4.1, which brings cordova-ios 4 with it. I therefore tried it and everything built OK - although with the side effect of removing iOS 7 compatibility (and needing some upgrades to other plugins). For completeness, here's [the link on the XDK forum](https://software.intel.com/en-us/forums/intel-xdk/topic/625339#comment-1869298).

Thanks for the quick help.
