### ISSUE TITLE
Not able to recieve notification on Iphone

### ISSUE THREAD

**Issue by asinha08** [phonegap/phonegap-plugin-push#819]
My plugin version is phonegap-plugin-push 1.6.1 "PushPlugin"
cordova version is 6.0.0

I am creating a hybrid application using Cordova. For notification, I am using 'phonegap-plugin-push' plugin and GCM (Google Cloud Messaging). Notification workflow works perfectly for Android devices. But when I send notification to an IOS device, GCM response is 200 but notification is not delivered to IOS device. I am sure that my APNS certificates are proper and correct .p12 certificates are uploaded to GCM.

Below is my payload. Please let me know if I have missed something in payload for APNS
```
var payload = {
            data: {
                type: TYPE,
                requestedBy: XYX,
                id: ID,
                devicePlatform: DEVICE_PLATFORM,
                user: USER,
                isKnowUser: XYZ,
                title: XYZ,
                message: XYZ,
                style: "inbox",
                summaryText: "There are %n% notifications",
                "content-available": "1"
                actions: [
                    {"title": "Open App", "callback": "openApp", "foreground": true},
                    {"title": "Give Data Access", "callback": "giveDataAccess", "foreground": true}
                ]
           },
           to: ABC,
           priority: "high"
}
```
Same payload i am using for android and it works beautifully.

**Comment by macdonst** [comment]
@asinha08 see my comment on #806 about the payload being different on GCM iOS. Also, what does your PushNotification.init() method call look like?

**Comment by macdonst** [comment]
Closing, inactivity
