### ISSUE TITLE
Init PushNotification jus one time

### ISSUE THREAD

**Issue by mv83** [phonegap/phonegap-plugin-push#82]
Hi,
I have this question. If my phonegap app is composed by more than one pages, and I want to receive the push notification on each page, I have to initialize the PushNotification function each time?
Thanks in advance

**Comment by macdonst** [comment]
Yes, this is correct. When you navigate to a new page the Javascript loaded from the current page will be unloaded. So if you setup your push.on("notification") handler on the main page and navigated to a sub page it would no longer exist. 

You may want to look into single page application techniques to reduce the need of loading and unloading your JS code.

**Comment by mauron85** [comment]
My app is SPA so I don't have problem with push plugin init between multiple pages, but anyway I would like to reuse registrationId between app sessions, so registrationId will be assigned once (saved into localStorage) just after first user login and then reused when app is run next time.

I believe it's not currently possible as init has to be called, which in turn generate new registrationId.

**Comment by mv83** [comment]
Ok thanks for your replies. There is the possibility to use the var push = PushNotification.init only one time (maybe when the applciation start) and then use the push,on(...) in the other pages/subpages of the app? 
I think that the PushNotification.init involves a new registrationId request each time, or I'm wrong?

**Comment by macdonst** [comment]
@mv83 @mauron85 It shouldn't be a problem to call init multiple times. The registration ID should be exactly the same on each call to init. Occasionally GCM will change the registration ID on you so it pays to compare it against the previous version.

**Comment by mauron85** [comment]
@macdonst ok. I have no objections then.

**Comment by larryval** [comment]
Hello all :)
I'm doing an app with the push-plugin. Can you confirm that I have to call the PushNotification.init() every time the app is launch, cause effectively, I don't know how to listen to the "notification" event if the push Object is not created ( push = PushNotification.init() ).
Well, I'm a bit surprise to do so, but if you confirm that's the way to do ... 
thank's

**Comment by macdonst** [comment]
@larryval call init every time you start your app. There is always a chance the registration ID changed. Sometimes APNS/GCM will invalidate ID's.

**Comment by larryval** [comment]
whaouh!, thank's a lot for this express response!, thank's
