### ISSUE TITLE
push.on('notification') not fired on Android (Correct payload)

### ISSUE THREAD

**Issue by tropperstyle** [phonegap/phonegap-plugin-push#820]
Everything works well for me with iOS. But with Android, everything seems to work well up to the point of `push.on('notification')`
### Expected Behaviour

JS notification event should fire either in background when 'content-available' is set to 1 in the data option, else when the application is brought to the foreground.
### Actual Behaviour

The notification event is never triggered
### Reproduce Scenario (including but not limited to)

Basic Example
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 4.3 with CrossWalk 17 webview
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Samsung Galaxy S4
#### Cordova CLI version and cordova platform version

cordova cli 6.1.1, android platform 5.1.1
#### Plugin version

phonegap-plugin-push 1.6.2
#### Sample Push Data Payload

```
new gcm.Message({
    priority     : 'high',
    timeToLive   : 86400,
    sound        : 'default',
    data         : { title: 'Some title', body: 'Some content' })
});
```
#### Sample Code that illustrates the problem

```
var push = PushNotification.init({
    android: {
        senderID: "[SENDER ID]"        
    }
});

push.on('registration', function(data) {
    // save to backend
});

push.on('notification', function(notice) {
    console.log('PushPlugin RECEIVED', notice);
});

push.on('error', function(e) {
    console.error('PushPlugin ERROR', e);
});
```
#### Logs taken while reproducing problem

adb logcat | grep PushPlugin

```
# App in background, push event sent, then:

D/PushPlugin_GCMIntentService(18987): onMessage - from: XXXXXXXX
D/PushPlugin_GCMIntentService(18987): normalize extras
D/PushPlugin_GCMIntentService(18987): key = body
D/PushPlugin_GCMIntentService(18987): replace key body with message
D/PushPlugin_GCMIntentService(18987): key = time
D/PushPlugin_GCMIntentService(18987): replace key time with time
D/PushPlugin_GCMIntentService(18987): key = title
D/PushPlugin_GCMIntentService(18987): replace key title with title
D/PushPlugin_GCMIntentService(18987): key = collapse_key
D/PushPlugin_GCMIntentService(18987): replace key collapse_key with collapse_key
D/PushPlugin_GCMIntentService(18987): background
D/PushPlugin_GCMIntentService(18987): message =[Some title]
D/PushPlugin_GCMIntentService(18987): title =[Some message]
D/PushPlugin_GCMIntentService(18987): contentAvailable =[null]
D/PushPlugin_GCMIntentService(18987): create notification
E/PushPlugin_GCMIntentService(18987): Number format exception - Error parsing notId: Invalid int: "null"
D/PushPlugin_GCMIntentService(18987): stored icon=null
D/PushPlugin_GCMIntentService(18987): stored iconColor=null
D/PushPlugin_GCMIntentService(18987): stored sound=true
D/PushPlugin_GCMIntentService(18987): stored vibrate=true
D/PushPlugin_GCMIntentService(18987): no icon resource found - using application icon
D/PushPlugin_GCMIntentService(18987): create actions


# Notification tapped, application opens, then:

D/PushPlugin_PushHandlerActivity(18987): not id = 0
V/PushPlugin_PushHandlerActivity(18987): onCreate
D/PushPlugin_PushHandlerActivity(18987): callback = null
D/PushPlugin_PushHandlerActivity(18987): bringToForeground = true
V/PushPlugin(18987): sendExtras: caching extras to send at a later time.
D/PushPlugin_PushHandlerActivity(18987): isPushPluginActive = false
D/PushPlugin_PushHandlerActivity(18987): forceMainActivityReload
```

Does this line look suspicious?

```
V/PushPlugin(18987): sendExtras: caching extras to send at a later time.
```

**Comment by yesnoj** [comment]
did you use the "content-available": "1" in the android payload?

**Comment by macdonst** [comment]
@tropperstyle okay, but in your sample push payload you did not set content-available so the event won't be fired when the app is in the background. You would need to use:

```
new gcm.Message({
    priority     : 'high',
    timeToLive   : 86400,
    sound        : 'default',
    data         : { title: 'Some title', body: 'Some content', 'content-available': '1' })
});
```

**Comment by tropperstyle** [comment]
I want the `on('notification')` to trigger when the app is brought to the foreground, so no, I did not set `content-available` in the use case I pasted above.

I did however try with `content-available` and again, the notification event was _never_ fired, not in the background, or ever, even when the app was brought into the foreground.

Please re-read my issue carefully. I also split the logs between when the notification was received in the background, and later when I brought the app into the foreground.

The only difference when I added `content-available` was an additional line in the first section of the log

    V/PushPlugin(18987): sendExtras: caching extras to send at a later time.

Along with a few key normalizing log lines

**Comment by tropperstyle** [comment]
For fullness sake, here is the log with `'content-available': '1'`

```
# App in background, push event sent, then:

D/PushPlugin_GCMIntentService(10582): onMessage - from: XXXXXXXX
D/PushPlugin_GCMIntentService(10582): normalize extras
D/PushPlugin_GCMIntentService(10582): key = body
D/PushPlugin_GCMIntentService(10582): replace key body with message
D/PushPlugin_GCMIntentService(10582): key = time
D/PushPlugin_GCMIntentService(10582): replace key time with time
D/PushPlugin_GCMIntentService(10582): key = title
D/PushPlugin_GCMIntentService(10582): replace key title with title
D/PushPlugin_GCMIntentService(10582): key = collapse_key
D/PushPlugin_GCMIntentService(10582): replace key collapse_key with collapse_key
D/PushPlugin_GCMIntentService(10582): key = content-available
D/PushPlugin_GCMIntentService(10582): replace key content-available with content-available
D/PushPlugin_GCMIntentService(10582): background
D/PushPlugin_GCMIntentService(10582): message =[Some message]
D/PushPlugin_GCMIntentService(10582): title =[Some title]
D/PushPlugin_GCMIntentService(10582): contentAvailable =[1]
D/PushPlugin_GCMIntentService(10582): create notification
E/PushPlugin_GCMIntentService(10582): Number format exception - Error parsing notId: Invalid int: "null"
D/PushPlugin_GCMIntentService(10582): stored icon=null
D/PushPlugin_GCMIntentService(10582): stored iconColor=null
D/PushPlugin_GCMIntentService(10582): stored sound=true
D/PushPlugin_GCMIntentService(10582): stored vibrate=true
D/PushPlugin_GCMIntentService(10582): no icon resource found - using application icon
D/PushPlugin_GCMIntentService(10582): create actions
D/PushPlugin_GCMIntentService(10582): send notification event
V/PushPlugin(10582): sendExtras: caching extras to send at a later time.


# Notification tapped, application opens, then:

D/PushPlugin_PushHandlerActivity(10582): not id = 0
V/PushPlugin_PushHandlerActivity(10582): onCreate
D/PushPlugin_PushHandlerActivity(10582): callback = null
D/PushPlugin_PushHandlerActivity(10582): bringToForeground = true
V/PushPlugin(10582): sendExtras: caching extras to send at a later time.
D/PushPlugin_PushHandlerActivity(10582): isPushPluginActive = false
D/PushPlugin_PushHandlerActivity(10582): forceMainActivityReload
```

**Comment by tropperstyle** [comment]
After some digging through the source code, `gWebView` is always null, causing `sendExtras` to always hit [this else block](https://github.com/phonegap/phonegap-plugin-push/blob/c43dbbd43916fdf5be4d37b4c2082c960f10cf67/src/android/com/adobe/phonegap/push/PushPlugin.java#L215)

Does this plugin need to do something special to support pluggable webviews? [cordova-plugin-crosswalk-webview](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview)

**Comment by tropperstyle** [comment]
@macdonst any ideas?

**Comment by macdonst** [comment]
@tropperstyle I haven't had time to dig into it but the fact that you are using Crosswalk probably has something to do with it.

**Comment by tropperstyle** [comment]
@macdonst What would be an alternative check to fix [isPushPluginActive](https://github.com/phonegap/phonegap-plugin-push/blob/c43dbbd43916fdf5be4d37b4c2082c960f10cf67/src/android/com/adobe/phonegap/push/PushHandlerActivity.java#L36)? Why does it even need to check if the webview is present? If you could just take a minute to give a high-level explanation I can try to submit a pull request. This issue is a blocker for my team right now.

````
public static boolean isActive() {
    return gWebView != null;
}
````

**Comment by macdonst** [comment]
@tropperstyle if the webview is null then there isn't any web view to process the JS event. I think the think to look at in more detail is why is the web view null.

**Comment by macdonst** [comment]
@tropperstyle I added the crosswalk plugin into my app and I couldn't reproduce your problem. Mind you I may not have the exact reproduction scenario. Do you need to anything else with Crosswalk other than add in the plugin? Is there a config.xml setting to tell it what webview to use?

**Comment by nikhilsharma8193** [comment]
I am also facing exactly the same issue. I am not using Crosswalk. Even the logs are same. Tried both with `content-available` and without that. I also added the `forceShow` parameter to immediately fire the event in the foreground but no luck. It's neither invoking for background notification nor when the app is running. 

What does  `callback = null` states ?

**Comment by tropperstyle** [comment]
This is my plugin list:
```
$ cordova plugin 
code-push 1.8.0-beta "CodePushAcquisition"
com.telerik.plugins.nativepagetransitions 0.6.3 "Native Page Transitions"
cordova-plugin-camera 2.1.1 "Camera"
cordova-plugin-code-push 1.5.1-beta "CodePush"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-contacts 2.0.1 "Contacts"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-file-transfer 1.5.0 "File Transfer"
cordova-plugin-geolocation 2.2.0 "Geolocation"
cordova-plugin-inappbrowser 1.2.1 "InAppBrowser"
cordova-plugin-splashscreen 3.1.0 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-plugin-wkwebview-engine 1.0.2 "Cordova WKWebView Engine"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 0.8.5 "Cordova sqlite storage plugin (core version)"
phonegap-plugin-push 1.6.2 "PushPlugin"
```

@nikhilsharma8193 Do we share any common plugins? That may help narrow down the culprit

**Comment by macdonst** [comment]
@tropperstyle I can't help but notice your plugin list doesn't include crosswalk. Are you not using it or is the plugin list an error?

**Comment by tropperstyle** [comment]
I only use crosswalk on android (for iOS I use [cordova-plugin-wkwebview-engine](https://github.com/apache/cordova-plugin-wkwebview-engine)), so I have the latest webviews on both platforms. If you want stability while using modern web standards, these plugins are a necessity. I followed the [Android Platform Only Workflow](https://crosswalk-project.org/documentation/cordova.html) which uses `plugman install` instead of `cordova plugin add` - which is probably why it doesn't show up in the list.

**Comment by nikhilsharma8193** [comment]
This is my plugin list:

```
cordova-plugin-customurlscheme 4.1.5 "Custom URL scheme"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-hockeyapp 2.2.2 "HockeyApp"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-spinner-dialog 1.3.1 "SpinnerDialog"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.0.0 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-x-socialsharing 5.0.12 "SocialSharing"
ionic-plugin-keyboard 1.0.8 "Keyboard"
jp.wizcorp.phonegap.plugin.wizSpinnerPlugin 1.2.0 "Wizard Spinner Plugin"
phonegap-plugin-push 1.6.3 "PushPlugin"

```

**Comment by Kushi171987** [comment]
I have the same problem :(

This is my plugin list
`Kushals-MacBook-Pro:BlueApp kushal$ cordova plugin list
cordova-plugin-appversion 1.0.0 "App Version"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-email-composer 0.8.3 "EmailComposer"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-media 2.2.0 "Media"
cordova-plugin-splashscreen 3.1.0 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-vibration 2.1.0 "Vibration"
cordova-plugin-websocket 0.12.0 "WebSocket for Android"
cordova-plugin-whitelist 1.2.1 "Whitelist"
phonegap-plugin-push 1.6.1 "PushPlugin"
vensi-plugin-gattip 0.0.1 "gattip"`

Here is my node server code.
`var sender = new gcm.Sender("APIKey");
    var message = new gcm.Message();
    message.addData('title', appName);
    message.addData('message', 'my message...!');
    message.addData('msgcnt','1');
    message.collapseKey = 'demo';
    message.delayWhileIdle = true;
    message.timeToLive = 3;

    var registrationIds = [];
    registrationIds.push(token);

    sender.send(message, registrationIds, 4, function (result) {
        console.log(result);
    });`

Its working fine for the iOS app, So I released it into AppStore. Just because of this issue am not able to submit the my Android app to Play Store.  Please fix the issue with Android one ASAP. pls.

**Comment by nikhilsharma8193** [comment]
@tropperstyle
@Kushi171987

Solved, it's working fine. I had the issue because the App code was incorrect. The `init()` should be called  every time the app loads to make sure the `WebView` and `CallbackContext` object is available.

Also, it's mentioned in the docs, it got skipped by me. After digging the entire plugin code, I got why it was not working.

Hope it helps. If you have implemented your code correctly, it should work. Drop a reply if it doesn't. I have dug the code enough to give some suggestions. 😄

**Comment by Kushi171987** [comment]
@nikhilsharma8193 

Here is my code, 
`registerPushNotifications: function() {
            if ( (typeof PushNotification === 'undefined') || !PushNotification ){
                console.log('PushNotification plugin is not loaded...');
                return;
            }
            var push = PushNotification.init({
                android: {
                    senderID: senderID
                },
                ios: {
                    alert: 'true',
                    badge: 'true',
                    sound: 'true'
                },
                windows: {}
            });
            push.on('registration', function(data) {
                sendDeviceTokenToDB(data.registrationId);
            });
            push.on('notification', function(data) {
                toaster.show('Message...', data.message, 'success');
                if(data.sound){
                var snd = new Media('/android_asset/www/images/ringtones/Chord.mp3');
                    snd.play();
                }
            });
            push.on('error', function(e) {
                console.log(e.message);
            });            
        },`

I have this function in a factory & calling this function with factory.registerPushNotifications(); when app launch.
Its working for iOS. In Android, I see 'push.on('registration', function(data)' is triggered, but 'push.on('notification', function(data)' is never fired  :(.

**Comment by nikhilsharma8193** [comment]
@Kushi171987

First, attach your `push` object to the window object.

```
window.push = PushNotification.init({
    android: {
        senderID: senderID
    },
    ios: {
        alert: 'true',
        badge: 'true',
        sound: 'true'
    },
    windows: {}
});

window.push.on('registration', function(data) {
    sendDeviceTokenToDB(data.registrationId);
});

window.push.on('notification', function(data) {
    toaster.show('Message...', data.message, 'success');
    if(data.sound){
    var snd = new Media('/android_asset/www/images/ringtones/Chord.mp3');
        snd.play();
    }
});

window.push.on('error', function(e) {
    console.log(e.message);
});

```
If your application is `SPA(Single Page Application)`, the `onNotification` handler needs to be available in all pages,
hence attaching it to the window object (Global context). If your application is not SPA, then you will have to
keep this handler in all pages i.e (call your function in each page).

**Comment by orhankutlu** [comment]
@tropperstyle Have you solved your problem? I am facing exactly the same one. @macdonst Any updates?

**Comment by macdonst** [comment]
@orhankutlu I've never been able to reproduce it.

**Comment by Kushi171987** [comment]
I think am still facing issue with the Android devices. Notifications are only working for iOS, but not Android :(

**Comment by diegobill** [comment]
Same problem

**Comment by bardu** [comment]
My notifiaction handler never get triggered when app is in background.

This is my payload for Android:
```
{
    "priority": "high",
    "delayWhileIdle": true,
    "timeToLive": 3,
    "data": {
        "title": config.gcm.message_title,
        "body": data.new_val.desc,
        "sound": "default",
        "content-available": 1,
        "badge": 1,
        "extra": {
            "url": "deals"
        }
    }
}
```
This is my notification handler:
```
window.gcmPush.on('notification', function(data) {
    // check for url to route to
    if ( data.additionalData.extra.url ) {
        if ( typeof router !== typeof undefined ) {
            console.log(`routing to url ${data.additionalData.extra.url}`)
            router.push(data.additionalData.extra.url);
        }
    }
    window.gcmPush.finish(function() {
        console.log('Processing of push data is finished');
    });
});
```

And this is the logcat output when notification is received by my Google Pixel, the app is in background:
>03-30 16:16:15.618  3961  7290 D PushPlugin_GCMIntentService: onMessage - from: /topics/electronics-android
03-30 16:16:15.618  3961  7290 D PushPlugin_GCMIntentService: normalize extras
03-30 16:16:15.618  3961  7290 D PushPlugin_GCMIntentService: key = content-available
03-30 16:16:15.618  3961  7290 D PushPlugin_GCMIntentService: replace key content-available with content-available
03-30 16:16:15.618  3961  7290 D PushPlugin_GCMIntentService: key = google.sent_time
03-30 16:16:15.618  3961  7290 D PushPlugin_GCMIntentService: replace key google.sent_time with google.sent_time
03-30 16:16:15.618  3961  7290 D PushPlugin_GCMIntentService: key = body
03-30 16:16:15.618  3961  7290 D PushPlugin_GCMIntentService: replace key body with message
03-30 16:16:15.619  3961  7290 D PushPlugin_GCMIntentService: no locale found for key = message, error Value Testing of type java.lang.String cannot be converted to JSONObject
03-30 16:16:15.619  3961  7290 D PushPlugin_GCMIntentService: key = badge
03-30 16:16:15.619  3961  7290 D PushPlugin_GCMIntentService: replace key badge with count
03-30 16:16:15.619  3961  7290 D PushPlugin_GCMIntentService: key = extra
03-30 16:16:15.619  3961  7290 D PushPlugin_GCMIntentService: replace key extra with extra
03-30 16:16:15.619  3961  7290 D PushPlugin_GCMIntentService: key = sound
03-30 16:16:15.619  3961  7290 D PushPlugin_GCMIntentService: replace key sound with sound
03-30 16:16:15.619  3961  7290 D PushPlugin_GCMIntentService: key = title
03-30 16:16:15.619  3961  7290 D PushPlugin_GCMIntentService: replace key title with title
03-30 16:16:15.620  3961  7290 D PushPlugin_GCMIntentService: no locale found for key = title, error Value Look of type java.lang.String cannot be converted to JSONObject
03-30 16:16:15.620  3961  7290 D PushPlugin_GCMIntentService: key = google.message_id
03-30 16:16:15.620  3961  7290 D PushPlugin_GCMIntentService: replace key google.message_id with google.message_id
03-30 16:16:15.620  3961  7290 D PushPlugin_GCMIntentService: background
03-30 16:16:15.620  3961  7290 D PushPlugin_GCMIntentService: count =[1]
03-30 16:16:15.639  3961  7290 D PushPlugin_GCMIntentService: message =[Testing out ]
03-30 16:16:15.639  3961  7290 D PushPlugin_GCMIntentService: title =[Look Inside]
03-30 16:16:15.640  3961  7290 D PushPlugin_GCMIntentService: contentAvailable =[1]
03-30 16:16:15.640  3961  7290 D PushPlugin_GCMIntentService: forceStart =[null]
03-30 16:16:15.640  3961  7290 D PushPlugin_GCMIntentService: create notification
03-30 16:16:15.640  3961  7290 E PushPlugin_GCMIntentService: Number format exception - Error parsing notId: null
03-30 16:16:15.652  3961  7290 D PushPlugin_GCMIntentService: stored icon=null
03-30 16:16:15.652  3961  7290 D PushPlugin_GCMIntentService: stored iconColor=null
03-30 16:16:15.652  3961  7290 D PushPlugin_GCMIntentService: stored sound=true
03-30 16:16:15.652  3961  7290 D PushPlugin_GCMIntentService: stored vibrate=true
03-30 16:16:15.652  3961  7290 D PushPlugin_GCMIntentService: no icon resource found - using application icon
03-30 16:16:15.653  3961  7290 D PushPlugin_GCMIntentService: count =[1]
03-30 16:16:15.653  3961  7290 D PushPlugin_GCMIntentService: create actions: with in-line
03-30 16:16:15.658  3961  7291 D PushPlugin_GCMIntentService: onMessage - from: /topics/electronics-android
03-30 16:16:15.658  3961  7291 D PushPlugin_GCMIntentService: normalize extras
03-30 16:16:15.658  3961  7291 D PushPlugin_GCMIntentService: key = content-available
03-30 16:16:15.658  3961  7291 D PushPlugin_GCMIntentService: replace key content-available with content-available
03-30 16:16:15.658  3961  7291 D PushPlugin_GCMIntentService: key = google.sent_time
03-30 16:16:15.658  3961  7291 D PushPlugin_GCMIntentService: replace key google.sent_time with google.sent_time
03-30 16:16:15.659  3961  7291 D PushPlugin_GCMIntentService: key = body
03-30 16:16:15.659  3961  7291 D PushPlugin_GCMIntentService: replace key body with message
03-30 16:16:15.659  3961  7291 D PushPlugin_GCMIntentService: no locale found for key = message, error Value Testing of type java.lang.String cannot be converted to JSONObject
03-30 16:16:15.659  3961  7291 D PushPlugin_GCMIntentService: key = badge
03-30 16:16:15.659  3961  7291 D PushPlugin_GCMIntentService: replace key badge with count
03-30 16:16:15.659  3961  7291 D PushPlugin_GCMIntentService: key = extra
03-30 16:16:15.659  3961  7291 D PushPlugin_GCMIntentService: replace key extra with extra
03-30 16:16:15.659  3961  7291 D PushPlugin_GCMIntentService: key = sound
03-30 16:16:15.659  3961  7291 D PushPlugin_GCMIntentService: replace key sound with sound
03-30 16:16:15.659  3961  7291 D PushPlugin_GCMIntentService: key = title
03-30 16:16:15.659  3961  7291 D PushPlugin_GCMIntentService: replace key title with title
03-30 16:16:15.659  3961  7291 D PushPlugin_GCMIntentService: no locale found for key = title, error Value Look of type java.lang.String cannot be converted to JSONObject
03-30 16:16:15.659  3961  7291 D PushPlugin_GCMIntentService: key = google.message_id
03-30 16:16:15.659  3961  7291 D PushPlugin_GCMIntentService: replace key google.message_id with google.message_id
03-30 16:16:15.659  3961  7291 D PushPlugin_GCMIntentService: background
03-30 16:16:15.659  3961  7291 D PushPlugin_GCMIntentService: count =[1]
03-30 16:16:15.662  3961  7291 D PushPlugin_GCMIntentService: message =[Testing out ]
03-30 16:16:15.662  3961  7291 D PushPlugin_GCMIntentService: title =[Look Inside]
03-30 16:16:15.662  3961  7291 D PushPlugin_GCMIntentService: contentAvailable =[1]
03-30 16:16:15.662  3961  7291 D PushPlugin_GCMIntentService: forceStart =[null]
03-30 16:16:15.662  3961  7291 D PushPlugin_GCMIntentService: create notification
03-30 16:16:15.662  3961  7291 E PushPlugin_GCMIntentService: Number format exception - Error parsing notId: null
03-30 16:16:15.663  3961  7290 D PushPlugin_GCMIntentService: app is not running and content available true
03-30 16:16:15.663  3961  7290 D PushPlugin_GCMIntentService: send notification event
03-30 16:16:15.663  3961  7290 V PushPlugin: sendExtras: caching extras to send at a later time.
03-30 16:16:15.671  3961  7291 D PushPlugin_GCMIntentService: stored icon=null
03-30 16:16:15.671  3961  7291 D PushPlugin_GCMIntentService: stored iconColor=null
03-30 16:16:15.671  3961  7291 D PushPlugin_GCMIntentService: stored sound=true
03-30 16:16:15.671  3961  7291 D PushPlugin_GCMIntentService: stored vibrate=true
03-30 16:16:15.671  3961  7291 D PushPlugin_GCMIntentService: no icon resource found - using application icon
03-30 16:16:15.672  3961  7291 D PushPlugin_GCMIntentService: count =[1]
03-30 16:16:15.672  3961  7291 D PushPlugin_GCMIntentService: create actions: with in-line
03-30 16:16:15.672  3961  7292 D PushPlugin_GCMIntentService: onMessage - from: /topics/electronics-android
03-30 16:16:15.672  3961  7292 D PushPlugin_GCMIntentService: normalize extras
03-30 16:16:15.672  3961  7292 D PushPlugin_GCMIntentService: key = content-available
03-30 16:16:15.672  3961  7292 D PushPlugin_GCMIntentService: replace key content-available with content-available
03-30 16:16:15.672  3961  7292 D PushPlugin_GCMIntentService: key = google.sent_time
03-30 16:16:15.672  3961  7292 D PushPlugin_GCMIntentService: replace key google.sent_time with google.sent_time
03-30 16:16:15.672  3961  7292 D PushPlugin_GCMIntentService: key = body
03-30 16:16:15.672  3961  7292 D PushPlugin_GCMIntentService: replace key body with message
03-30 16:16:15.673  3961  7292 D PushPlugin_GCMIntentService: no locale found for key = message, error Value Testing of type java.lang.String cannot be converted to JSONObject
03-30 16:16:15.673  3961  7292 D PushPlugin_GCMIntentService: key = badge
03-30 16:16:15.673  3961  7292 D PushPlugin_GCMIntentService: replace key badge with count
03-30 16:16:15.673  3961  7292 D PushPlugin_GCMIntentService: key = extra
03-30 16:16:15.673  3961  7292 D PushPlugin_GCMIntentService: replace key extra with extra
03-30 16:16:15.673  3961  7292 D PushPlugin_GCMIntentService: key = sound
03-30 16:16:15.673  3961  7292 D PushPlugin_GCMIntentService: replace key sound with sound
03-30 16:16:15.673  3961  7292 D PushPlugin_GCMIntentService: key = title
03-30 16:16:15.673  3961  7292 D PushPlugin_GCMIntentService: replace key title with title
03-30 16:16:15.673  3961  7292 D PushPlugin_GCMIntentService: no locale found for key = title, error Value Look of type java.lang.String cannot be converted to JSONObject
03-30 16:16:15.673  3961  7292 D PushPlugin_GCMIntentService: key = google.message_id
03-30 16:16:15.673  3961  7292 D PushPlugin_GCMIntentService: replace key google.message_id with google.message_id
03-30 16:16:15.674  3961  7292 D PushPlugin_GCMIntentService: background
03-30 16:16:15.674  3961  7292 D PushPlugin_GCMIntentService: count =[1]
03-30 16:16:15.676  3961  7292 D PushPlugin_GCMIntentService: message =[Testing out ]
03-30 16:16:15.676  3961  7292 D PushPlugin_GCMIntentService: title =[Look Inside]
03-30 16:16:15.676  3961  7292 D PushPlugin_GCMIntentService: contentAvailable =[1]
03-30 16:16:15.676  3961  7292 D PushPlugin_GCMIntentService: forceStart =[null]
03-30 16:16:15.676  3961  7292 D PushPlugin_GCMIntentService: create notification
03-30 16:16:15.676  3961  7292 E PushPlugin_GCMIntentService: Number format exception - Error parsing notId: null
03-30 16:16:15.685  3961  7291 D PushPlugin_GCMIntentService: app is not running and content available true
03-30 16:16:15.685  3961  7291 D PushPlugin_GCMIntentService: send notification event
03-30 16:16:15.685  3961  7291 V PushPlugin: sendExtras: caching extras to send at a later time.
03-30 16:16:15.700  3961  7292 D PushPlugin_GCMIntentService: stored icon=null
03-30 16:16:15.700  3961  7292 D PushPlugin_GCMIntentService: stored iconColor=null
03-30 16:16:15.700  3961  7292 D PushPlugin_GCMIntentService: stored sound=true
03-30 16:16:15.700  3961  7292 D PushPlugin_GCMIntentService: stored vibrate=true
03-30 16:16:15.701  3961  7292 D PushPlugin_GCMIntentService: no icon resource found - using application icon
03-30 16:16:15.701  3961  7292 D PushPlugin_GCMIntentService: count =[1]
03-30 16:16:15.701  3961  7292 D PushPlugin_GCMIntentService: create actions: with in-line
03-30 16:16:15.718  3961  7292 D PushPlugin_GCMIntentService: app is not running and content available true
03-30 16:16:15.718  3961  7292 D PushPlugin_GCMIntentService: send notification event
03-30 16:16:15.718  3961  7292 V PushPlugin: sendExtras: caching extras to send at a later time.

And this is the output when touching on the notification:
>03-30 16:21:27.048  3961  3961 D PushPlugin_PushHandlerActivity: not id = 0
03-30 16:21:27.049  3961  3961 V PushPlugin_PushHandlerActivity: onCreate
03-30 16:21:27.049  3961  3961 D PushPlugin_PushHandlerActivity: callback = null
03-30 16:21:27.049  3961  3961 D PushPlugin_PushHandlerActivity: dismissed = false
03-30 16:21:27.049  3961  3961 V PushPlugin: sendExtras: caching extras to send at a later time.
03-30 16:21:27.049  3961  3961 D PushPlugin_PushHandlerActivity: bringToForeground = true
03-30 16:21:27.056  3961  3961 D PushPlugin_PushHandlerActivity: isPushPluginActive = false
03-30 16:21:27.056  3961  3961 D PushPlugin_PushHandlerActivity: forceMainActivityReload

**Comment by andymurakami** [comment]
@macdonst I have the same issue , every time the app fire 'registration' and not fire 'notification' why ?

my Payload:

 $fields  = array(
        'data' => array(
          'title'     => 'Teste !',
            "badge" => 1,
            'sound'=>'default',
             'content-available'  => 1,
            'extra'=>array(
             "id_oferta" => '646',
            ),
            
          'body'    => 'Abre Oferta 646'
        ),
        'registration_ids' => $registrationIds,
                  'delayWhileIdle'=>true,
                  'timeToLive'=>3,
        'priority' => 'high',
    );
   
    
    $fields = json_encode ( $fields );

    $headers = array (
            'Authorization: key=' . "my auth",
            'Content-Type: application/json'
    );

    $ch = curl_init ();
    curl_setopt ( $ch, CURLOPT_URL, $url );
    curl_setopt ( $ch, CURLOPT_POST, true );
    curl_setopt ( $ch, CURLOPT_HTTPHEADER, $headers );
    curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, true );
    curl_setopt ( $ch, CURLOPT_POSTFIELDS, $fields );
    curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4 ); // Be sure to use ipV4
    
    $result = curl_exec ( $ch );
