### ISSUE TITLE
Android double on('notification') fired

### ISSUE THREAD

**Issue by dylanvdmerwe** [phonegap/phonegap-plugin-push#828]
### Actual Behaviour
When an Android app is in the background (in memory not killed) and a push message with `content-available: 1` is received the following happens:

1. Push message is received on the phone. 
2. The on('notification') event fires in the background (coldstart: undefined, foreground: false).
2. User presses the push notification.
3. The on('notification') event fires again as the app opens. (coldstart: false, foreground: false).

### Expected Behaviour
I do not expect the notification event to be fired twice. Or if it is going to be fired twice (once to process the data when it is received and another time if the user presses the notification) then this needs to be consistently implemented across iOS as well.

### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 6.0.1

### What device vendor (e.g. Samsung, HTC, Sony...)

Tested on Nexus 5.

### Cordova CLI version and cordova platform version

Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS:
Node Version: v5.10.1
android 5.1.1
ios 4.1.1

### Plugin version

1.6.2

### Sample Code that illustrates the problem

See my [repo](https://github.com/dylanvdmerwe/pushtest) that I have put together for testing the various scenarios.

**Comment by Radu80** [comment]
Hi,
I also have the same problem

**Comment by macdonst** [comment]
@dylanvdmerwe three for three on great issue descriptions but in this case it is by design. If you send a notification with `content-available: 1` it will fire the event in the background. If the notification also includes a title and message then it will be shown in the notification shader. Once you click on the notification the event will be fired again.

I've told people multiple times if they don't want this behaviour they should do one of the following things:

1. don't include title/message in the push so it doesn't show up in the shader.
2. send two pushes, one to be processed in the background the other to show up in the shade.
3. include a unique ID in your push so you can check to see if you've already processed this event.

Perhaps we need better docs?

**Comment by dylanvdmerwe** [comment]
Those suggestions make perfect sense. I think more documentation on this would be extremely beneficial.

**Comment by jordidiaz** [comment]
@macdonst You made my day! I have implemented the third option and works fine. Thank you!

**Comment by macdonst** [comment]
![push-flowchart](https://cloud.githubusercontent.com/assets/353180/15751310/aa605f8c-28b7-11e6-8c32-9252172b36f9.png)

**Comment by macdonst** [comment]
![push-flowchart](https://cloud.githubusercontent.com/assets/353180/15752003/36b80afa-28ba-11e6-818b-c6f5f2966d8f.png)

**Comment by macdonst** [comment]
Add more docs on the process https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#overview

**Comment by checo06** [comment]
@macdonst for avoiding the 'notification' fire twice when "content-available" is set to 1,  im checking that if coldstart and foreground flags both are set to false it cames from a user tap on the notification center, so i skip this event. Do you think this is a valid way (and possibly another strategy) to solve the avoiding twice firing thing?

```
if( !data.additionalData.coldstart && !data.additionalData.foreground ){
//set a flag to skip notification processing
}
```

**Comment by checo06** [comment]
My previous comment was wrong.

I finally also used the strategy "3 include a unique ID" and worked good. In my case i checked with the previous idPushNotification processed (i save the last idPushNotification on localStorage )

**Comment by jakute** [comment]
Hello @checo06  can you please help me with the logic of how to see if the Id already exist?, because i have the issue that mi notifications duplicates. 
thanks in advance
