### ISSUE TITLE
Migrated project to use browserify, PushPlugin then became totally flaky

### ISSUE THREAD

**Issue by behaghel** [phonegap/phonegap-plugin-push#83]
Very odd behaviours since I migrated to browserify: everything works fine but notifications. I am targeting android only. I have tested with v1.1.1 and also with the latest on this repository and the issue remains. If I revert to my commit pre-migration to browserify, it works fine again. I have also tried to keep PushNotification related logic outside of browserify but no luck.

I have added logs before `PushNotification.init`, after and around all my `push.on()` calls. This initialisation will stop randomly in the middle and only rarely print the last log proving it completed properly.

Once loaded, I send a series of notifications to my device and observe randomly one of the below outputs for each notification. I don't do anything beside sending notifications to the device and each notification gets a different treatment by the plugin.

Output 1:
```
V/GCMBaseIntentService( 8663): Intent service name: GCMIntentService-GCMIntentService-12
```

Output 2:
```
V/GCMBroadcastReceiver( 8663): onReceive: com.google.android.c2dm.intent.RECEIVE
V/GCMBroadcastReceiver( 8663): GCM IntentService class: com.adobe.phonegap.push.GCMIntentService
V/GCMBaseIntentService( 8663): Acquiring wakelock
```
Output 3:
```
V/GCMBroadcastReceiver( 8663): onReceive: com.google.android.c2dm.intent.RECEIVE
V/GCMBroadcastReceiver( 8663): GCM IntentService class: com.adobe.phonegap.push.GCMIntentService
V/GCMBaseIntentService( 8663): Acquiring wakelock
D/PushPlugin_GCMIntentService( 8663): onMessage - context: android.app.Application@33b3eeaf
D/PushPlugin( 8663): key = from
D/PushPlugin( 8663): key = goal
D/PushPlugin( 8663): key = user
D/PushPlugin( 8663): key = title
D/PushPlugin( 8663): key = message
D/PushPlugin( 8663): key = collapse_key
D/PushPlugin( 8663): key = foreground
V/PushPlugin( 8663): extrasToJSON: {XXX payload XXX}
>> [here logs of 0, few are all of the registered callbacks on 'notification'] <<
V/GCMBaseIntentService( 8663): Releasing wakelock <-- may or may not be printed
```
Output 4:
```
[here logs of 0, few are all of the registered callbacks on 'notification']
```

In case that helps, output of a successful open+registration (though it didn't print the console.log of my 'registration' callback …but it did run at least part of it as it updated the view with the registration-id):
```
V/WindowManager( 1299): Adding window Window{25f75615 u0 com.hozana.hozanaapp/com.hozana.hozanaapp.MainActivity} at 3 of 7 (before Window{eee8da0 u0 Starting com.hozana.hozanaapp
})
I/ActivityManager( 1299): Displayed com.hozana.hozanaapp/.MainActivity: +570ms (total +2m33s180ms)
D/JsMessageQueue( 8663): Set native->JS mode to OnlineEventsBridgeMode
I/chromium( 8663): [INFO:CONSOLE(1776)] "Could not find cordova.js script tag. Plugin loading may fail.", source: file:///android_asset/www/cordova.js (1776)
I/chromium( 8663): [INFO:CONSOLE(7)] "PUSH: config: init", source: file:///android_asset/www/js/NotificationHandler.js (7)
I/chromium( 8663): [INFO:CONSOLE(18)] "PUSH: config: install callback", source: file:///android_asset/www/js/NotificationHandler.js (18)
I/chromium( 8663): [INFO:CONSOLE(26)] "PUSH: config: DONE", source: file:///android_asset/www/js/NotificationHandler.js (26)
V/PushPlugin( 8663): execute: action=init
V/PushPlugin( 8663): execute: data=[{"android":{"senderID":"ZZZZZZZ"},"ios":{},"windows":{}}]
V/PushPlugin( 8663): execute: jo={"senderID":"ZZZZZZZ"}
V/PushPlugin( 8663): execute: senderID=ZZZZZZZZZ
D/GCMRegistrar( 8663): resetting backoff for com.hozana.hozanaapp
V/GCMRegistrar( 8663): Registering app com.hozana.hozanaapp of senders ZZZZZZZZZ
D/PushPlugin( 8663): no icon option
D/PushPlugin( 8663): no iconColor option
I/GCM     ( 1722): GCM config loaded
V/GCMBroadcastReceiver( 8663): onReceive: com.google.android.c2dm.intent.REGISTRATION
V/GCMBroadcastReceiver( 8663): GCM IntentService class: com.adobe.phonegap.push.GCMIntentService
V/GCMBaseIntentService( 8663): Acquiring wakelock
V/GCMBaseIntentService( 8663): Releasing wakelock
D/TaskPersister( 1299): removeObsoleteFile: deleting file=106_task.xml
```
Sometimes, during this phase, I see (this has always been the case even before I moved to browserify):
```
W/PluginManager( 8136): THREAD WARNING: exec() call to PushNotification.init blocked the main thread for 40ms. Plugin should use CordovaInterface.getThreadPool().
```

I already spent 2 days on this, I am more than happy to do anything that can help investigate this.
Thanks!

**Comment by macdonst** [comment]
@behaghel any update on this?

**Comment by Naveenbc** [comment]
Hi mac,

I update to the latest plugin. I am able to build my project usins ionic CLI. but when I import android project in eclipse, AndroidManifest file gives error, since application id is not populated. I know you provided push.gradle to do this task but I May be doing something wrong while importing kindly correct me.

**Comment by behaghel** [comment]
Hi @macdonst,

Thanks for looking into it, let me resume my work on that this weekend. I
will get back to you with an update then.

--
Hubert

**Comment by behaghel** [comment]
Can't reproduce anymore, closing.
