### ISSUE TITLE
ios not showing Notifications  (background, and non-background)

### ISSUE THREAD

**Issue by vousys** [phonegap/phonegap-plugin-push#831]
Hi Simon.
I can't get the notifications on iOs.  

Phonegap version: cli-5.4.1 
Phonegap-plugin push at config.xml:

```
     <gap:plugin name="phonegap-plugin-push" spec="~1.5.3" source="npm">
            <param name="SENDER_ID" value="XXXXX"/>
            <param name="GOOGLE_APP_ID" value="1:YYYY:ios:YYYY"/> 
        </gap:plugin>  

```

where XXXXX and YYYY are my project ID at console.developers.google.com

Plugin init settings

```
 var push = PushNotification.init({
            "android": {
                "senderID": "XXXX"
            },
            "ios": {
            "senderID": "XXXX",
            "gcmSandbox": "true",
            "alert": "true",
            "badge": "true",
            "sound": "true"
            },
            "windows": {}
        });
```

From my php server, I'm sending 2 different payloads, in order abour your comment here:
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md

Payload for android  (where the notifications appears ok)

```
            $msg   = array
            (
                'body'      => $message,
                'title'     => $titulo,
                'content-available'   => '1' ,
                'badge'     => '1',
                'sound'     =>'default',
                'additionalData' => $adicional_data,
            ); 
             $payload_android = array
            (
                'registration_ids'  => $registration_ids_android,
                'data'              => $msg 
            );

```

Payload for iOs device:

```
$msg_ios   = array
            (
                'body'      => $message,
                'title'     => $titulo,
                'content-available'   => '1' ,
                'click-action'    => 'go_to_notifications' 
           ); 

             $payload_ios = array
            (
                'registration_ids'  => $registration_ids_ios,
                'notification'      => $msg_ios   
            );

```

If I use the $payload_ios , the GCM responds: "NotRegistered"
this is a registration_id for 

```
(
            [registration_id] => mnjg3gmEma4:APA91bEpRqwVXcBVx_KFVDlEIovrYnpm1zn4AV_TmpOlqZobScDLytyL7wr5Ii8Ghq-_MNsPmAl5yUXcD9fKxW8vHWN36ppVq3fJQ6TQITlUZN2aoaEKTRoCNxLeMeMjjwUhqQp8-_YI
            [device_model] => iPad5,3
            [device_platform] => iOS
            [device_uuid] => CCCCCCCC
            [device_version] => 9.3.1
            [device_name] =>
        )

```

Instead, if I send with the "android" payload, for the same registration_id I get success, but nothing shows on the ipad

```
(
    [multicast_id] => 8.84556887701E+18
    [success] => 1
    [failure] => 0
    [canonical_ids] => 0
    [results] => Array
        (
            [0] => stdClass Object
                (
                    [message_id] => 0:1461337511446229%d1ee9114f9fd7ecd
                )

        )

)

```

What else could i try? Thanks.

**Comment by vousys** [comment]
Hi Simon, I upgraded the app to  
Phonegap version: cli-6.0.0
and plugin version: 
     <gap:plugin name="phonegap-plugin-push" spec="~1.6.2" source="npm">
 But, I'm still have this issue.
Can you help me, please?

**Comment by macdonst** [comment]
@vousys try the following payload:

```
{
    "registration_ids": ["my device id"],
    "notification": {
        "title": "AUX Scrum",
        "body": "Scrum: Daily touchbase @ 10am Please be on time so we can cover everything on the agenda."
    }
}
```

then start adding properties to see where it goes wrong.

**Comment by vousys** [comment]
Hi Simon, thanks for answer.
No, is the same response. I've already tried that.
Only says "OK" when I use the android's payload.
I'm using now the latest phonegap version 6.1.0, I don't know what

```
(
    [multicast_id] => 4.75396424848E+18
    [success] => 0
    [failure] => 1
    [canonical_ids] => 0
    [results] => Array
        (
            [0] => stdClass Object
                (
                    [error] => NotRegistered
                )

        )

)
```

**Comment by vousys** [comment]
Hi Simon, what else can I try? I don't understand why they don't arrive

**Comment by JoeRadman** [comment]
For iOS - you have the correct certificates setup in Apple Developer - and in the app ID - Push Notifications - that cert, then convert to p12 and uploaded to Google? Then when you're building for IOS ensure the notification entitlement is enabled.

**Comment by vousys** [comment]
Yes, I've that.

**Comment by raphaguasta** [comment]
I have the same problem =(

**Comment by JoeRadman** [comment]
Couple more things to try. 
IOS - when building, are you building with a Developer certificate - if yes, then you need to make sure Sandbox=true in GCM registration.

If it is developer - then make sure your certificate on GCM is also for development.

Priority - set to high to push the message quickly to the device. Otherwise it can take a while if priority is normal.

App must be closed - so close the app and test. If you can, build on IOS with device attached so you can watch the console. You can put a console.log on.notification - see if the device is getting something.

**Comment by vousys** [comment]
I've got all of that , just like you said, except the priority.



​
Salu2!

Vero | *VOUSYS.com*
<http://www.vousys.com/>

VOUSYS.com Office: Buenos Aires, Argentina | +54.011.4481-3751

http://www.vousys.com     [image: Facebook]
<https://www.facebook.com/vousys> [image: Twitter]
<http://www.twitter.com/vousys> [image: Google Plus]
<https://plus.google.com/u/0/b/111673332818765301661/+Vousys/posts> [image:
Pintrest] <http://www.pinterest.com/vousys/> [image: Skype]
<https://www.vousys.com/> <https://www.vousys.com/exportador>
<http://www.tusfacturas.com.ar/> <http://www.e-xpensas.com/>
<http://www.micampeonato.com/>




2016-05-13 0:07 GMT-03:00 JoeRadman <notifications@github.com>:

**Comment by cotufaloschiflones** [comment]
I'm having the same problem here. @vousys Could you finally fix the problem?

**Comment by vousys** [comment]
no guys I couldn't fix it... I gave up....
do you have the same phoengap Cli version and plugin version like me?
 I think that tomorrow I'll start doing the conection via APN. Don't close
this issue Simon, I'll post here the results.



​
Salu2!

Vero | *VOUSYS.com*
<http://www.vousys.com/>

VOUSYS.com Office: Buenos Aires, Argentina | +54.011.4481-3751

http://www.vousys.com     [image: Facebook]
<https://www.facebook.com/vousys> [image: Twitter]
<http://www.twitter.com/vousys> [image: Google Plus]
<https://plus.google.com/u/0/b/111673332818765301661/+Vousys/posts> [image:
Pintrest] <http://www.pinterest.com/vousys/> [image: Skype]
<https://www.vousys.com/> <https://www.vousys.com/exportador>
<http://www.tusfacturas.com.ar/> <http://www.e-xpensas.com/>
<http://www.micampeonato.com/>




2016-05-19 13:37 GMT-03:00 cotufaloschiflones <notifications@github.com>:

**Comment by raphaguasta** [comment]
Hello Guys! You need to get a configuration file (GoogleService-Info.plist). Have you done that?

Link: https://developers.google.com/cloud-messaging/ios/client#get-config

**Comment by vousys** [comment]
Hi Raphael, are you sure? we're using phonegap not native.
what should we do with that file?
I've upload correctly the certificates to GCM and I've got the Sender ID


​
Salu2!

Vero | *VOUSYS.com*
<http://www.vousys.com/>

VOUSYS.com Office: Buenos Aires, Argentina | +54.011.4481-3751

http://www.vousys.com     [image: Facebook]
<https://www.facebook.com/vousys> [image: Twitter]
<http://www.twitter.com/vousys> [image: Google Plus]
<https://plus.google.com/u/0/b/111673332818765301661/+Vousys/posts> [image:
Pintrest] <http://www.pinterest.com/vousys/> [image: Skype]
<https://www.vousys.com/> <https://www.vousys.com/exportador>
<http://www.tusfacturas.com.ar/> <http://www.e-xpensas.com/>
<http://www.micampeonato.com/>




2016-05-19 14:49 GMT-03:00 Raphael Guastaferro <notifications@github.com>:

**Comment by raphaguasta** [comment]
Yes, in my case it worked. At least in production (not sent to the store yet)...

Make the file and put in your project by XCode, in the root project folder. After it, use the phonegap-plugin-push normally, with the correct certifieds.

**Comment by vousys** [comment]
But I'm not using Xcode ....  :(


​
Salu2!

Vero | *VOUSYS.com*
<http://www.vousys.com/>

VOUSYS.com Office: Buenos Aires, Argentina | +54.011.4481-3751

http://www.vousys.com     [image: Facebook]
<https://www.facebook.com/vousys> [image: Twitter]
<http://www.twitter.com/vousys> [image: Google Plus]
<https://plus.google.com/u/0/b/111673332818765301661/+Vousys/posts> [image:
Pintrest] <http://www.pinterest.com/vousys/> [image: Skype]
<https://www.vousys.com/> <https://www.vousys.com/exportador>
<http://www.tusfacturas.com.ar/> <http://www.e-xpensas.com/>
<http://www.micampeonato.com/>




2016-05-19 15:02 GMT-03:00 Raphael Guastaferro <notifications@github.com>:

**Comment by raphaguasta** [comment]
I do not know how to implement this file without using Xcode. But if you can open Xcode and use it only for this, may solve your problem.

When generating the file on Google's site, there are guidelines for this, is simple.

**Comment by cotufaloschiflones** [comment]
Hello @raphaguasta yes, I'm using cordova/ionic and Xcode aswell, I have this file propertly configured following the google guide. I had it all, the config and settings well setted at least on the app side, so then I have started to dig in the server side, I'm using node.js ( module => node-gcm ) and the problem was the way in what we were setting/sending the object gcm.Message({ _config }), its not pretty clear in the documentation but now it's working (kind of). What technology are you using in the server side @vousys ?

Now I'm receiving data from the server but not in background mode, so I'm facing that now...any suggestion?

**Comment by vousys** [comment]
Hi! We're using PHP + Apache (in server side)



​
Salu2!

Vero | *VOUSYS.com*
<http://www.vousys.com/>

VOUSYS.com Office: Buenos Aires, Argentina | +54.011.4481-3751

http://www.vousys.com     [image: Facebook]
<https://www.facebook.com/vousys> [image: Twitter]
<http://www.twitter.com/vousys> [image: Google Plus]
<https://plus.google.com/u/0/b/111673332818765301661/+Vousys/posts> [image:
Pintrest] <http://www.pinterest.com/vousys/> [image: Skype]
<https://www.vousys.com/> <https://www.vousys.com/exportador>
<http://www.tusfacturas.com.ar/> <http://www.e-xpensas.com/>
<http://www.micampeonato.com/>




2016-05-20 7:55 GMT-03:00 cotufaloschiflones <notifications@github.com>:

**Comment by raphaguasta** [comment]
I'm using PHP + Apache too. Like this: https://gielberkers.com/push-notifications-phonegap-android/#comment-2342

About the background mode, i don't have ideia... But check the other items: sender_id, sandbox, etc.

**Comment by vousys** [comment]
Thanks Raphael, I'll check it!


​
Salu2!

Vero | *VOUSYS.com*
<http://www.vousys.com/>

VOUSYS.com Office: Buenos Aires, Argentina | +54.011.4481-3751

http://www.vousys.com     [image: Facebook]
<https://www.facebook.com/vousys> [image: Twitter]
<http://www.twitter.com/vousys> [image: Google Plus]
<https://plus.google.com/u/0/b/111673332818765301661/+Vousys/posts> [image:
Pintrest] <http://www.pinterest.com/vousys/> [image: Skype]
<https://www.vousys.com/> <https://www.vousys.com/exportador>
<http://www.tusfacturas.com.ar/> <http://www.e-xpensas.com/>
<http://www.micampeonato.com/>




2016-05-20 13:58 GMT-03:00 Raphael Guastaferro <notifications@github.com>:

**Comment by raphaguasta** [comment]
Guys,

My notification worked in development, but not in production! =(

Someone had success with the application in production?

**Comment by macdonst** [comment]
@raphaguasta yes, the PhoneGap Developer App is using the push plugin in production.

**Comment by raphaguasta** [comment]
Hi @macdonst ! In addition to the certificates, there is a difference between development code and production code?

**Comment by sayanbrainium** [comment]
I have the same problem. Running in Android but not working in IOS at all. Response showing notification sent but not receiving in iphone.
I have the same coding @vousys . Can anyone help out?

**Comment by vousys** [comment]
Yes, I fix it. It was a problem when sending the APNS, that says OK but nothing arrives.

1) use the last phonegap cli and the last plugin push

```
  <preference name="phonegap-version"             value="cli-6.5.0" /> 

   <gap:plugin name="phonegap-plugin-push" source="npm" spec="1.9.4">
        <param name="SENDER_ID" value="XXXXXX"/>
    </gap:plugin>  
 
```

2)  Re-generate your Apple Certificates (the one for push and the other). Remember to request the one that works for development and production.

3) If you work with PHP, you can need to create 2 scripts to get it work,   because APNS only works if the request came from a CURL request. 

a) One to recibe the call ex: notifications.php with this code:

```
        $post = [
            'mensaje' => $message_to_send,
            'device_id' => $device_id,
        ];
        $ch = curl_init('https://www.yourdomain.com/notifications-apns.php');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
        $response = curl_exec($ch);
        curl_close($ch);

```
b) One for sending via APNS, ex: notifications-apns.php

```
        $sandbox 			= true;
        $debug                           = true;

       // Certificate must be located in the same directory of this script
        $certificado_push 	= "certificate_name.pem";

        // Put your device token here (without spaces):
        $deviceToken 		= $_POST["device_id"];

        // Put your private key's passphrase here:
        $passphrase 		= 'XXXXXXXXXXXXX';

        // Put your alert message here:
        $message 			= $_POST["mensaje"];

        // SEND to APNS ->
        $ctx = stream_context_create();
        stream_context_set_option($ctx, 'ssl', 'local_cert', $certificado_push);
        stream_context_set_option($ctx, 'ssl', 'passphrase', $passphrase);

        // Open a connection to the APNS server
        $fp = stream_socket_client(
        'ssl://gateway.'.($sandbox ? 'sandbox.' : '').'push.apple.com:2195', $err,
        $errstr, 60, STREAM_CLIENT_CONNECT|STREAM_CLIENT_PERSISTENT, $ctx);

        if (!$fp) {
                if ($debug)  mail("YOUR EMAIL","APNS", "Failed to connect: $err $errstr" );
        }else{    
                if ($debug)  mail("YOUREMAIL","APNS", 'Connected to APNS' );

                // Create the payload body
                $body['aps'] = array(
                'alert' => $message,
                'badge' => '1', //  If you want to increment or decrement you will need to keep track of the current badge number on your server
                'sound' => 'default'
                );

                // Encode the payload as JSON
                $payload = json_encode($body);

                // Build the binary notification
                $msg = chr(0) . pack('n', 32) . pack('H*', $deviceToken) . pack('n', strlen($payload)) .     $payload;

                // Send it to the server
                $result = fwrite($fp, $msg, strlen($msg));

                if (!$result) {
                    if ($debug)  mail("YOUREMAIL","APNS", 'Message not delivered' );
                }else{
                    if ($debug)  mail("YOUREMAIL","APNS", 'Message successfully delivered to '.$deviceToken );
                }

                // Close the connection to the server
                fclose($fp);
         }       

```

All the scripts must be run under HTTPS and you need to open the port 2195 to get it work.

Let me know if this help you @sayanbrainium

**Comment by sayanbrainium** [comment]
@vousys I am integrating it from fcm but its not sending. Now I will follow your process and will let you know what happens. Thanks for your instant and precious help.

**Comment by sayanbrainium** [comment]
@vousys I have integrated my IOS push notification with ionic cordova fcm plugin successfully. 
Thanks for your help. Your code will help me in future.

**Comment by macdonst** [comment]
Closing as original reported resolved their problem.
