### ISSUE TITLE
[iOS] Only receiving 99% of the push notifications

### ISSUE THREAD

**Issue by alexislg2** [phonegap/phonegap-plugin-push#834]
### Expected Behaviour
I expect my users to receive 100% of the notifications I send to them

### Actual Behaviour
Many of my users on iOS (in Android it seems to be OK) report me that sometimes they did not receive the notification. This happens often at night (user phone is ON with WiFi ON)

### Reproduce Scenario (including but not limited to)
Cannot reproduce since it's quite rare and random

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Seems to concern all iOS versions

#### Cordova CLI version and cordova platform version

    cordova 5.1.1 with cordova-ios 3.8 with phonegap-plugin-push 1.5.3

#### Sample Push Data Payload

Only message with priority 10 (max)

Hey my iOS report me they sometimes do not receive some of the notifications I send them. On the server side the APNS service replies with the 'transmitted' status. Anybody experienced this? Do you know any reason why the iOS phone might decide not to display a notification (with priority = 10)? Anyway I can debug?

**Comment by dylanvdmerwe** [comment]
The APN service will queue messages up -- but Apple doesn't [guarantee delivery](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html) of all messages. 

### Quality of Service

> Apple Push Notification service includes a default Quality of Service (QoS) component that performs a store-and-forward function. If APNs attempts to deliver a notification but the device is offline, the notification is stored for a limited period of time, and delivered to the device when it becomes available. Only one recent notification for a particular app is stored. If multiple notifications are sent while the device is offline, the new notification causes the prior notification to be discarded. This behavior of keeping only the newest notification is referred to as coalescing notifications.
> 
> If the device remains offline for a long time, any notifications that were being stored for it are discarded.

**Comment by macdonst** [comment]
@alexislg2 yeah, I have no idea what to tell you on this one other than what @dylanvdmerwe mentioned and Apple doesn't guarantee delivery. I wonder if they are getting tossed by the phones do not disturb rules.

**Comment by alexislg2** [comment]
Hey thank you for your answers. I know that Apple does not guarantee that
messages are processed but I would like to know from your feedback if this
is something that seems usual to you or if this is supposed to happen once
in a while but never happens actually.

But maybe this is because notifications are very important in the game we
develop so players complain more often when they don't receive the
notification than for other apps. So maybe you have the same issues but you
are not aware of it.

**Comment by jedofus** [comment]
hello guys, my question may seem silly but have you got a tutorial to implement this plugin on ios. i don't understand the step before initalise push on my js file (cordova)

**Comment by macdonst** [comment]
@jedofus trying starting with this: http://macdonst.github.io/push-workshop/

**Comment by jedofus** [comment]
thanks @macdonst  ;)

**Comment by yugidazai** [comment]
@alexislg2 I don't know whether it works for you but it happened to me.
I use loopback-component-push plugin to send notification and I also got same problem as you.
Notifications are not always sent 100% probably due to Apple server as of Apple's Quality service mentioned above. The error returned is:
{ [Error: read ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'read' }
[https://github.com/argon/node-apn/issues/100](url)

With loopback-component-push plugin, I can catch it with `Push.on('error'`, callback)`.
So my solution (or workaround) is to resend the notification again whenever I get this error.
