### ISSUE TITLE
IOS : Not receiving notification by using phone gap plugin.

### ISSUE THREAD

**Issue by syedmohiseen** [phonegap/phonegap-plugin-push#835]
I'm successfully sending notifications from server (PHP)

 My application is generating **device token** successfully but  **unable to receive notification**.
Here is my code (by using phone gap push plugin)

```javascript
var push = PushNotification.init({
        android: {
            senderID: "12345679"
        },
        ios: {
            alert: "true",
            badge: true,
            sound: 'false'
        },
        windows: {}
    });
    push.on('registration', function(data) {
        console.log(data.registrationId);
    });
    push.on('notification', function(data) {
        console.log(data.message);
        console.log(data.title);
        console.log(data.count);
        console.log(data.sound);
        console.log(data.image);
        console.log(data.additionalData);
    });
    push.on('error', function(e) {
        console.log(e.message);
    });

```

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
