### ISSUE TITLE
Version 1.6.0+ unable to install on android 5.1

### ISSUE THREAD

**Issue by vousys** [phonegap/phonegap-plugin-push#836]
Hi Simon, do you know that if i use this version of your plugin

 <gap:plugin name="phonegap-plugin-push" spec="~1.6.0" source="npm">

 <gap:plugin name="phonegap-plugin-push" spec="~1.6.1" source="npm">

 <gap:plugin name="phonegap-plugin-push" spec="~1.6.2" source="npm"> 

with <preference name="phonegap-version" value="cli-5.4.1" />

Phonegap Build compile it fine, but on Android 5.1 of Moto X xt1058 is unable to install it.
Do you have that reported?

**Comment by macdonst** [comment]
@vousys the install error might help here 😉

**Comment by vousys** [comment]
I don't have one, it only says "Can't install" and the "X"

**Comment by macdonst** [comment]
@vousys how are you trying to install? Google Play, ADB or QR Code from PGB?

**Comment by vousys** [comment]
Hi Simón, vía qr
Its download fine, but when installing fails
El 1/5/2016 12:08, "Simon MacDonald" <notifications@github.com> escribió:

@vousys <https://github.com/vousys> how are you trying to install? Google
Play, ADB or QR Code from PGB?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/phonegap/phonegap-plugin-push/issues/836#issuecomment-216048581>

**Comment by macdonst** [comment]
@vousys I'm pretty sure you are running into #768. Try to update your plugin version to 1.6.3. You can confirm by downloading the apk from PGB and trying to do an ADB install. The error message that way would be more revealing.

**Comment by vousys** [comment]
Yes, with versión 1.6.3 it works fine.
But i've another issue open that with that versión I don't recive
notifications un Ios

**Comment by macdonst** [comment]
Closing this issue then.
