### ISSUE TITLE
Windows 'registration' event intermittently not firing

### ISSUE THREAD

**Issue by cjpete** [phonegap/phonegap-plugin-push#838]
### Actual Behaviour

PushNotification is intermittently firing the 'error' event, instead of successful 'registration' event being fired:

```
console-via-logger.js (173,15)
   {
      [functions]: ,
      __proto__: { },
      asyncOpCausalityId: 81,
      asyncOpSource: { },
      asyncOpType: "Windows.Foundation.IAsyncOperation`1<Windows.Networking.PushNotifications.PushNotificationChannel>",
      description: "Unknown runtime error",
      message: "Unknown runtime error",
      name: "WinRTError",
      number: -2013002775
   }
```

The PushNotification.init() method is just being passed an empty object for the windows configuration. It is also only called once deviceready has been triggered.
#### Platform and Version

Windows 10.0.10586.0 - Surface Pro 4
#### Cordova CLI version and cordova platform version

Cordova Version: 6.1.1
Cordova Platform Version Windows: 4.3.2
#### Plugin version

1.5.3

**Comment by rakatyal** [comment]
@cjpete: How often does this happen? It may happen due to connectivity issues sometimes.

**Comment by Alkashi** [comment]
Hi,

Same think with the same device and the version 1.6.3 of the plugin.
Any advice ?

**Comment by kamilo81** [comment]
same problem here. Any solution ?
