### ISSUE TITLE
Undertand few code in iOS

### ISSUE THREAD

**Issue by pallaviMN** [phonegap/phonegap-plugin-push#841]
Hi Team, Can you please let me know why the below line is used in AppDelegate+notification.m file,

[pushHandler.handlerObj setObject:safeHandler forKey:@"handler"];

I was facing problem with this line, when the status bar notifications will come, then it will be shown only for a while. After that in iPad device, if i go to notification center i am unable to see received status bar notifications. But after commenting the above line. I was able to see in the notification center as well

We also get below warning

Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.

**Comment by macdonst** [comment]
@pallaviMN if you read the sections on [Background notifications](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications-1) and [Action Buttons](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons-1) you will see the importance of calling `push.finish()`. If you don't do that then you'll get the warning:

```
Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.
```
