### ISSUE TITLE
How to create/use the payload ?

### ISSUE THREAD

**Issue by tahoura** [phonegap/phonegap-plugin-push#843]
I install the plugin and it work right. I want to send payload notification but i don't know how to create and how to use.
The  navigator.notification.alert(
                data.message,         // message
                null,                 // callback
                data.title,           // title
                'Ok'                  // buttonName
            );

Doesn't display.
Thanks to help/give to me the step ?
#### Cordova CLI version and cordova platform version

    cordova --version                                     6.1.1
    cordova platform version android                      4.4.2

**Comment by macdonst** [comment]
@tahoura many example on how to use node to send pushes are available at: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md

**Comment by tahoura** [comment]
@macdonst  thanks but i try an example but doesn't work. Is there any configuration to do ?
