### ISSUE TITLE
remove notifications from the list

### ISSUE THREAD

**Issue by clembou590** [phonegap/phonegap-plugin-push#847]
### Expected Behaviour

notification should be removed from the list once it's been "tapped" on by the user.
### Actual Behaviour

ON IOS 7,1,1. (iphone 4s)

```
     var pushService = PushNotification.init({
                            android: {
                                senderID: tindrive_anrdoid_sender_id
                            },
                            ios: {
                                senderID: tindrive_ios_sender_id,
                                gcmSandbox: true,
                                alert: "true",
                                badge: "true",
                                sound: "true"
                            },
                            windows: {}
                        });
```

I send a notification from a java app through the end point:
https://gcm-http.googleapis.com/gcm/send
(because I am using GCM sandbox).

I send a notification:

```
{
  "to": "luE0jC7ja7w:APA91bHjVRljQFxTds1Tpbfz5UK6aJzQcKHuIwrJujKufbu62IpYp75mUbqOUdVSpo3QdTq_0F6VuG__Mlk8Wz3zny-RNg98U-Zr9WqkDLls24fHpAKIXHMlJzRai72T2xCsrcuO14yJ",
  "notification": {
    "title": "hello title",
    "body": "great match!",
    "td": "2"
  }
}
```

the notification is displayed on the IPHONE
--> everything is fine.

the notification is displayed for "around 5 seconds" then disapear
--> perfect!
 if you go on the "list of notifications" of the iphone you can see it
--> perfect!
if you tap on the notification the app launches and the on('notification') callback is called
--> perfect

the problem is that once you have done that, if you close the app (or kill it) and you go to the list of notifications on the list, the notification is still there...*_(and I think it should not, it should have been removed from the list of notifcations...).
*_
And if you tap on the notification again, then the on('notification') callback is called again for the same notification.
--> that's a problem!

so my question is:
how do you remove the notification from the list once it has been handled?

thank you
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

ON IOS 7,1,1. (iphone 4s)
#### Cordova CLI version and cordova platform version

```
cordova --version                                    5,4,1
cordova platform version IOS                   3.9.2
```
#### Plugin version

```
cordova plugin version | grep phonegap-plugin-push   1.5.3
```

**Comment by macdonst** [comment]
I can't reproduce this and iOS7 is not supported anymore.
