### ISSUE TITLE
Error Uncaught ReferenceError: module is not defined in push.js

### ISSUE THREAD

**Issue by dipedro** [phonegap/phonegap-plugin-push#852]
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung J7

#### Sample Code that illustrates the problem
`module.exports = {
    /**
     * Register for Push Notifications.
     *
     * This method will instantiate a new copy of the PushNotification object
     * and start the registration process.
     *
     * @param {Object} options
     * @return {PushNotification} instance
     */

    init: function(options) {
        return new PushNotification(options);
    },

    hasPermission: function(successCallback, errorCallback) {
        exec(successCallback, errorCallback, 'PushNotification', 'hasPermission', []);
    },

    /**
     * PushNotification Object.
     *
     * Expose the PushNotification object for direct use
     * and testing. Typically, you should use the
     * .init helper method.
     */

    PushNotification: PushNotification
};`
#### Logs taken while reproducing problem
0     466869   error    Uncaught ReferenceError: module is not defined, http://10.0.0.112:8100/js/push.js, Line: 221

Note: Sorry, but i'm so newbie and my english is terrible. :D

**Comment by macdonst** [comment]
@dipedro sorry, how are you trying to test this?

**Comment by bondeulv** [comment]
I'm going to take a stab and guess that @dipedro is using AngularJS, and is having trouble injecting the plugin into his module.
I'm having this problem at least. 
ngCordova has support for PushNotification plugin, but only the deprecated old one.
I have yet to find a way of getting this plugin to be recognized by my angular controller.
I have this in my index.html file.
`<script src="js/push.js"></script>
  <script src="cordova.js"></script>
  <script src="js/app.js"></script>`

and my app.js looks like this:
`var app = angular.module('app', ['onsen', 'ngMap', 'pushNotification']);
  
  app.controller('AppController', function($scope, $http, NgMap, PushNotification) {
      
      var push = PushNotification.init({
          android: {
              senderID: "bondeulv's sender id"
          },
          ios: {
              alert: "true",
              badge: true,
              sound: "false"
          },
          windows: {}
      });
      
      NgMap.getMap().then(function(map){
         console.log(map.getCenter);
         console.log('markers', map.markers);
         console.log('shapes', map.shapes);
      });
      
  });`

**Comment by dipedro** [comment]
In my case, i install this plugin with CLI, and i copy the file push.js for the directory www/js/push.js.
I reference this in my index.html:
`    <script src="cordova.js"></script>  
    
	<script src="js/push.js"></script>
    <script src="js/app.js"></script>`
and put the code PushNotification.init inside of $ionicPlatform.ready function.

So, the big question is:
If I reference the push.js file in index.html, why are you saying that the module has not been set?

**Comment by macdonst** [comment]
@dipedro this plugin is part of ngCordova as `$cordovaPushV5`

https://github.com/yafraorg/yafra/wiki/Blog-Ionic-PushV5

**Comment by dipedro** [comment]
I solved this problem with a crazy solution. I remove this line:
<script src="js/push.js"></script>
of the file index.html and works fine. But i don't understand why. Because this line is the module definition and the issue is module is not defined. Why remove this line solve this problem?

**Comment by RichardGrant** [comment]
I am having the same exact issue. this is an issue with adding any plugin. what are we doing wrong?
