### ISSUE TITLE
Use plugin with its own private API

### ISSUE THREAD

**Issue by eros2187** [phonegap/phonegap-plugin-push#854]
hello I wanted to ask if you can use this plugin to be able to call a own private server without using gmc or ios,use your own exsample api:

```
 $.ajax({
            type:"POST",
            url: "your_url",
            data:data,
            success: function (response){
                var myarray = $.parseJSON(response);

            }
        });


push.on('notification', function(myarray ) {
    console.log(myarray .message);
    console.log(myarray .title);
    console.log(myarray .count);
    console.log(myarray .sound);
    console.log(myarray .image);
    console.log(myarray .additionalData);
});
```

and you can price everything ?
thanks if you can not do this how do I fix ?
Thanks again

**Comment by macdonst** [comment]
@eros2187 sorry, I'm not quite sure what you are asking. Do you want to use this plugin with a 3rd party push service like PushWoosh, Parse or Amazon SNS? Or are you looking to write your own service that totally bypasses Google's GCM and Apple's APNS?

**Comment by eros2187** [comment]
hello Simon MacDonald yes!! Or are you looking to write your own service that totally bypasses Google's GCM and Apple's APNS 
is this possible? as in creating an ajax call that returns me an array that allows me to be able to use the plugin ..
for me that would be great !!

**Comment by macdonst** [comment]
@eros2187 it is possible to write your own push service. I've been part of an effort to do just that before on Android in order to guarentee delivery and level of service but my recommendation after participating in that project is, just don't do it. Trying to build your own GCM or APNS is just madness.

Building your own service you can make an ajax call to which in turn sends that data to your device through GCM or APNS is more that doable. Is that more in line with what you want to do?

**Comment by eros2187** [comment]
already I do this but there are limits of messages both in ios that gcm .. unfortunately .. I wanted to use this plugin in order to have a push my service would be enough to create an ajax call on a server and to reclaim the json data poie use current plugins but I lack the knowledge suitable ..

I used this plugin https://github.com/katzer/cordova-plugin-local-notifications.git

creates local notifications problem is that if the app is closed push no more are displayed .. because the call ajax is not performed unlike most of this plugin that will always work even if the app is closed
so I'm stuck ..
I think it is a problem that many incontrono ..
how could I do for you? ce solution to this Simon MacDonald
Thanks for your time

**Comment by macdonst** [comment]
@eros2187 what you are asking is possible but out of scope for this plugin. I don't recommend you trying to write your own push service to work around GCM or APNS.
