### ISSUE TITLE
'notification' not called when App Icon is clicked on ios

### ISSUE THREAD

**Issue by ayomide101** [phonegap/phonegap-plugin-push#856]
### Expected Behaviour
When a notification is received while the application is in the background, the 'notification' event should be called when the user launches app through app icon, and also, when the notification bar is clicked.

### Actual Behaviour
When a notification is received the 'notification' event is not called when the app is launched through the App Icon, but the notification is called when the notification bar is clicked.

#### Steps to Reproduce 
Not working
1. Put application in background
2. Push a notification to preferred device.
3. Wait for a few seconds then click on the App Icon to launch the application
4. Put an alert message in 'notification' listener to test if a notification is received.

Working
1. Put application in background
2. Push a notification to preferred device
3. Click the notification bar
4. Put an alert message in notification listener to test if a notification is received.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 9.3.1

#### Cordova CLI version and cordova platform version

    cordova --version                                   6.1.1
    cordova platform version ios                  4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.6.3

#### Sample Push Data Payload
`{
	"badge": 1,
	"alert": "New Transaction",
	"sound": "default",
	"category": "invite",
	"payload": {
		"moredata": "We can put extra data in here",
		"content-available": 1,
		"notId": 1,
		"data": {
		}
	}
}`
#### Sample Code that illustrates the problem
```
$rootScope.$on('$cordovaPushV5:notificationReceived', function(event, data) {  // use two variables here, event and data !!!
		//Setting this so that tabs can receive the notification
			//App is in background
			if (data.additionalData.foreground === false) {
				if (ionic.Platform.isIOS() && data.count) {
					$cordovaPushV5.setBadgeNumber(data.count).then(function(result) {
						// OK
					}, function(err) {
						// handle error
					});
				}
                               alert("Notification received in background");
			} else {
				alert('Notification received in foreground');
			}

			$cordovaPushV5.finish().then(function(result) {
				// OK finished - works only with the dev-next version of pushV5.js in ngCordova as of February 8, 2016
			}, function(err) {
				// handle error
			});
		});
```

**Comment by macdonst** [comment]
@ayomide101 thanks for the detailed issue. I'll test it as soon as I can.

**Comment by iEchoic** [comment]
+1, I am experiencing this as well.

**Comment by ayomide101** [comment]
Hi Macdonst,
Thanks for the prompt response. What's the update on testing and fixing on this bug? Have you found where the bug is originating from? Am not so much of an ios developer, I really wish I could help.

**Comment by macdonst** [comment]
@ayomide101 actually, what you describe seems like the expected behaviour. The notification handler doesn't get called when you launch the app via the app icon, only when you launch the app via the notification.

**Comment by ayomide101** [comment]
@Simon is there a way to get the pending notifications then?

On Thu, May 26, 2016 at 3:05 PM, Simon MacDonald <notifications@github.com>
wrote:

> Closed #856 <https://github.com/phonegap/phonegap-plugin-push/issues/856>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-plugin-push/issues/856#event-673207762>
>



-- 
Fagbohungbe Ayomide Oluwaseun
Google Developer Group Unilag
Web Developer, CreditMe

**Comment by anjali14garg** [comment]
can you please provide me the link for this solution issue.

**Comment by robinbonnes** [comment]
Same issue here. Notification event is always called, from notification center, from app icon, from, background, from foreground, but just not when  **the application is killed/closed and user clicks on the app icon**.

**Comment by laagland** [comment]
Is there an update to this issue? Android handles the notification events from coldstart if you start the app by clicking the app icon. IOS does not. Why is this expected behaviour?
