### ISSUE TITLE
PushPlugin is undefined only in phonegap build

### ISSUE THREAD

**Issue by iEchoic** [phonegap/phonegap-plugin-push#857]
### Expected Behaviour
After device is ready, window.PushNotification is defined

### Actual Behaviour
After device is ready, window.PushNotification is undefined

### Reproduce Scenario (including but not limited to)
When built using phonegap build, after device is initialized, wait a few seconds and then alert(window.PushNotification). See undefined

When building using Phonegap developer, it works.

#### Steps to Reproduce 
1. Add to project config.xml:

`<plugin name="phonegap-plugin-push" spec="~1.6.3">`
  `<variable name="SENDER_ID" value="XXXXXXX" />`
`</plugin>`

2. Build project on phonegap build for iOS only. Verify that, in plugins tab on build.cordova.com, the plugin is being recognized and built (1.6.3)
3. Open app. After device is ready and app is loaded, alert(window.PushNotification). See undefined.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 

#### Cordova CLI version and cordova platform version
cli-5.2.0 (3.9.1 / 4.1.1 / 3.8.1)
(this is the version on Build, which doesn't work)

6.2.1 for developer (which works)

#### Plugin version
1.6.3

#### Sample Code that illustrates the problem
after device ready, alert(window.PushNotification)

**Comment by iEchoic** [comment]
Oh, after 4+ hours of fighting with it, I just fixed it by downgrading to 1.4.5. Is it expected that the newest version doesn't work?

**Comment by odellcraig** [comment]
I'm having likely the same problem - IOS has undefined for PushNotification where Android is fine. I was also able to downgrade to v1.4.5 and have it work. Odd thing is that I believe it was working recently. The things I can remember changing recently are adding a couple plugins (com.telerik.plugins.wkwebview) comes to mind as a significant one and also changing to ios v3.9.2 for the cordova version so I could  build said plugin. Here is a list of my current plugins that are running on cordova IOS@3.9.2 if I upgrade to 1.6.3 the PushNotifications object is undefined:

com.telerik.plugins.nativepagetransitions 0.6.3 "Native Page Transitions"
com.telerik.plugins.wkwebview 0.6.9 "WKWebView Polyfill"
com.verso.cordova.clipboard 0.1.0 "Clipboard"
cordova-plugin-app-version 0.1.8 "AppVersion"
cordova-plugin-camera 2.2.0 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-crosswalk-webview 1.6.1 "Crosswalk WebView Engine"
cordova-plugin-customurlscheme 4.1.5 "Custom URL scheme"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-google-analytics 0.8.1 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 1.2.1 "InAppBrowser"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-webserver 1.0.3 "CordovaWebServer"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-x-socialsharing 5.0.12 "SocialSharing"
ionic-plugin-keyboard 2.0.1 "Keyboard"
phonegap-plugin-barcodescanner 4.1.0 "BarcodeScanner"
phonegap-plugin-push 1.4.5 "PushPlugin"

**Comment by vespino** [comment]
Seems to work onwards to version 1.5.3. From 1.6.0 and higher it stops working for me on PGB.

**Comment by coyu1314** [comment]
Thanks. I have the exact same issue. IOS phonegap build doesn't work at all with the latest version 1.6.3. After changing the plugin version to 1.4.5 and 1.5.3, it works fine on ios now. Something must be wrong with the latest version.

**Comment by macdonst** [comment]
Duplicate #779
