### ISSUE TITLE
[question] How do I tell if a notification is clicked?

### ISSUE THREAD

**Issue by iEchoic** [phonegap/phonegap-plugin-push#858]
This seems really obvious, but I've spent a long time reading the docs and testing and I can't figure it out. 'foreground' isn't what I want because it's 'false' if a notif appears and they don't click it but click the app instead, and it looks like there used to be something called "onNotificationAPN" in the old version of the plugin that isn't anywhere in the docs now? Cold start also isn't what I want, because I want to know if the notif was clicked, which can happen independent of cold start state.

I just want something like this:

```
push.on('notificationClicked', function(notification) {
  // Take the user somewhere because they tapped/clicked something
});
```

Does this exist?

**Comment by macdonst** [comment]
@iEchoic your `on('notification')` is called in three situations:

1) your app is in the foreground. In this case `data.additionalData.foreground` is equal to true.
2) your user clicks on the notification in the shade, the app is opened and `data.additionalData.foreground` is equal to false.
3) You set `content-available: 1` so the event will be called even when the user doesn't click on the notification regardless or whether or not it is in the foreground or background. It's up to you to keep track of whether or not the event has been handled by the app.
