### ISSUE TITLE
Push-Message with variable content (key/value)

### ISSUE THREAD

**Issue by Sevenstax** [phonegap/phonegap-plugin-push#859]
I'm working with the plugin on iOS and on Android.
On iOS everything is working fine.

On iOS my push message looks like this:
{"aps":{"alert":{"loc-key":"status1","loc-args":["Name",216]},"sound":"play.wav"}}

In my local string I got for germany a string and for english
"status1" = "%@: TextText Value: %@!"

We would like to the same on Android, but this is not wokring for us.
Our push-message looks like this:
Array
(
    [registration_ids] => Array
        (
            [0] => <reg-key>
        )

    [data] => Array
        (
            [message] => Array
                (
                    [loc-key] => status1
                    [loc-val] => 216
                )

            [title] => Titel
            [vibrate] => 1
            [sound] => 1
        )
)

In our string.xml file we got this:
<string name="status1">%1$s TextText Value %1$s!</string>

In my Push-Message on my android smartphone i only see the message:
{"loc-val":216,"loc-key":"status1"}

The Android-Stuio debug out:
05-03 18:17:03.674 32231-32231/? I/art: Late-enabling -Xcheck:jni
05-03 18:17:03.764 32231-32231/com.iosapp.grillson I/GMPM: App measurement is starting up, version: 8487
05-03 18:17:03.764 32231-32231/com.iosapp.grillson I/GMPM: To enable debug logging run: adb shell setprop log.tag.GMPM VERBOSE
05-03 18:17:03.804 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: onMessage - from: 1069564375664
05-03 18:17:03.807 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: normalize extras
05-03 18:17:03.807 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: key = sound
05-03 18:17:03.807 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: replace key sound with sound
05-03 18:17:03.807 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: key = title
05-03 18:17:03.807 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: replace key title with title
05-03 18:17:03.807 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: key = vibrate
05-03 18:17:03.807 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: replace key vibrate with vibrate
05-03 18:17:03.807 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: key = message
05-03 18:17:03.807 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: extracting nested message data from key = message
05-03 18:17:03.807 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: replace key message with message
05-03 18:17:03.807 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: key = collapse_key
05-03 18:17:03.807 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: replace key collapse_key with collapse_key
05-03 18:17:03.808 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: background
05-03 18:17:03.808 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: message =[{"loc-val":216,"loc-key":"status1"}]
05-03 18:17:03.808 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: title =[Grillson]
05-03 18:17:03.808 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: contentAvailable =[null]
05-03 18:17:03.808 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: create notification
05-03 18:17:03.808 32231-32277/com.iosapp.grillson E/PushPlugin_GCMIntentService: Number format exception - Error parsing notId: Invalid int: "null"
05-03 18:17:03.832 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: stored icon=null
05-03 18:17:03.832 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: stored iconColor=null
05-03 18:17:03.832 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: stored sound=true
05-03 18:17:03.832 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: stored vibrate=true
05-03 18:17:03.832 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: no icon resource found - using application icon
05-03 18:17:03.832 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: android.resource://com.iosapp.grillson/raw/1
05-03 18:17:03.863 32231-32277/com.iosapp.grillson D/PushPlugin_GCMIntentService: create actions

Can anyone help us?
Or do we need to provide more information?

**Comment by macdonst** [comment]
@Sevenstax that's not something that Android provides by default. There is an open issue on this already, #737. Please add comments to that one.
