### ISSUE TITLE
android inbox style not stacking

### ISSUE THREAD

**Issue by purinagripal** [phonegap/phonegap-plugin-push#862]
Inbox style not stacking when in the status bar you have notifications from another app or more information

Is there a way to make it work always?

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
