### ISSUE TITLE
Is it available for large image notification? 

### ISSUE THREAD

**Issue by sarunkumar1990** [phonegap/phonegap-plugin-push#868]
i want show large image in notification . please update receivce large image notifications

**Comment by macdonst** [comment]
@sarunkumar1990 you are not following issue submission guidelines. I'm not sure what you are asking but please read up on:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#picture-messages
