### ISSUE TITLE
Android : on('notification') event triggered only when notification is clicked

### ISSUE THREAD

**Issue by gregorybellencontre** [phonegap/phonegap-plugin-push#869]
### Expected Behaviour

On iOS, when a notification is received in background, the "on('notification')" event is triggered. Then I can log some data in LocalStorage. When I click on the notification, the same event is triggered a second time. It's confusing, but I can handle it. 
### Actual Behaviour

On Android device, the event only triggers when I click on the notification. So if I receive a notification, and I open the app without clicking on the notification, I'm not able to get the notification informations and store them. So I'd like to know if a solution exists with this event or with another one.
### Reproduce Scenario (including but not limited to)

[Only on Android] When a notification is received, if you click on it, the app launches and notification plugin triggers the "on('notification')" event. But if you just runs the app, after receiving a notification, the event doesn't trigger.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 5.1.1
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Wiko Lenny 2
#### Cordova CLI version and cordova platform version

Cordova 6.1.0
Android 5.1.1
#### Plugin version

phonegap-plugin-push 1.6.1 "PushPlugin"
#### Sample Code that illustrates the problem

```
"onNotification": function(notification) {
          var id = notification._raw.additionalData.payload.id;
          var type = notification._raw.additionalData.payload.type;

          window.localStorage.setItem('notification_type',type);
          window.localStorage.setItem('notification_id',id);

          var notification_array = JSON.parse(window.localStorage.getItem('notification_'+type+'_array'));
          notification_array[id] = id;
          window.localStorage.setItem('notification_'+type+'_array',JSON.stringify(notification_array));

          $rootScope.$apply();

          if ($state.current.name != 'index') {
            $state.go($state.current, {}, {reload: true});
          }

          $rootScope.updateBadges();
}

```

**Comment by macdonst** [comment]
@gregorybellencontre what payload do you send to the Android device? If you want the `on('notification')` handler fired while in the background read up on https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications

**Comment by gregorybellencontre** [comment]
Here is the payload I send : 

```
$data = array(
        'tokens' => $tokens,
        'profile' => 'production',
        'notification' => array(
          'title' => $post_title,
          'message' => $post_title,
          'ios' => array(
            'content_available' => 1,
            'sound' => 'default',
            "payload" => array(
              "type" => $post_type,
              "id" => $post_id
            )
          ),
          'android' => array(
            'content_available' => 1,
            'sound' => 'default',
            'image' => 'www/img/icon.png',
            'payload' => array(
              "type" => $post_type,
              "id" => $post_id
            )
          )
        )
      );
```

Thanks for the link, I read about the "content-available". What's the correct spelling ? With a dash or underscore character ?
As you can see, I put it for each device. 
I will make some others tries.

**Comment by gregorybellencontre** [comment]
I tried with a dash "content-available" and not "content_available" with 1 as value.
I also tried to put the property outside of each device (globally in notification)

But nothing changed. 
I didn't say before, but I use the Ionic API to send the notifications. Maybe it's related.

**Comment by macdonst** [comment]
@gregorybellencontre maybe @ericb can weigh in on this one as he's on the Ionic team.

My thoughts are the `content-available` property should probably be in the android -> payload object.

**Comment by gregorybellencontre** [comment]
I tried every possibility. Still doesn't work.
On iOS, it only works if I put ("content_available" => 1) in the iOS object (With the underscore, the dash doesn't work in my tests)

But on Android, every tests I made failed.

**Comment by zigzag-way** [comment]
As for me I want to get stats on how many msgs were recieved and how many - read. This are different numbers.

**Comment by ajaysaini95700** [comment]
When app is in foreground and I pull down Sutter from top and click on notification  icon then nitrification.on('click') not fired

**Comment by epetre** [comment]
I wonder how people typically handle this, because I am having the same problem. Do people typically rely 100% on the user clicking the notification? It doesn't sound right at all...

**Comment by ffranz84** [comment]
I am in the same mindset as @epetre, how do I get the on('notification') event triggered, when the app is lanched directly.
@epetre Did you find a solution for this problem?

**Comment by hnakhuva** [comment]
any one found solution to this problem?? Me too facing the same issue

**Comment by amolpednekar** [comment]
Why was this issue closed without explanation? Did anyone get it to work?

**Comment by imromec** [comment]
Me too facing the same problem.....

**Comment by epetre** [comment]
I think that the main thing here is that to intercept the push when it arrives on the device, we have to do it natively because otherwise it would load the cordova app in memory just to handle the push.

So we can intercept the push natively by rewriting parts of the plugin. In my case I check for missd notifications from the API when the app comes back on and the user did not tap the push.

**Comment by erdem333** [comment]
still the same problem here ..
