### ISSUE TITLE
Question about GCM Notifications and data in the message payload

### ISSUE THREAD

**Issue by mauron85** [phonegap/phonegap-plugin-push#87]
GCM has two options how payload should look like - data and notifications https://developers.google.com/cloud-messaging/concept-options#notifications_and_data_messages

Data messages format
```
{
   "to" : "APA91bHun4MxP5egoKMwt2KZFBaFUH-1RYqx...",
   "data" : {
     "Nick" : "Mario",
     "body" : "great match!",
     "Room" : "PortugalVSDenmark"
   },
 }
 ```

Notifications format
```
 {
    "to" : "APA91bHun4MxP5egoKMwt2KZFBaFUH-1RYqx...",
    "notification" : {
      "body" : "great match!",
      "title" : "Portugal vs. Denmark",
      "icon" : "myicon"
    }
  }
```

I'm using node-gcm which recently added Notifications format, but my cordova app is not recieving this kind of messages. However the data format is working fine.

Question: Is Notifications format supported by phonegap-plugin-push? Is it system level thing? Or phonegap plugin has to support this?

Related question in node-gcm project:
https://github.com/ToothlessGear/node-gcm/issues/150

**Comment by macdonst** [comment]
@mauron85 currently the plugin only supports receiving notifications via the data message format but I just pushed a fix so it should be working fine in the 1.2.1 release.
