### ISSUE TITLE
push.on('notification') is fired only when receive the first push when the app is in foreground (iOS and Android)

### ISSUE THREAD

**Issue by manzapanza** [phonegap/phonegap-plugin-push#870]
### Expected Behaviour

When the app is in foreground it should be able to receive many push notifications firing push.on('notification');

### Actual Behaviour

When the app is in foreground push.on('notification'); is fired only when receive the first push notification. When receive the second is not fired.
When the app is in background or closed every push notification is received correctly. 

#### Steps to Reproduce 

- Open the app
- the app is in foreground
- Send a first push notification
- The push.on('notification') method is fired
- Send a second push notification
- The push.on('notification') method is NOT fired
- Send a third push notification
- The push.on('notification') method is NOT fired and so on

#### Platform and Version
 Same behaviour on:

- Android 6
- Android 5.5
- iOS 9.3.1

#### What device vendor
- Moto G 3 gen. Android 6
- Samsung Galaxy Note 4 Android 5.5
- iPhone 6 Plus iOS 9.3.1
- iPhone 5s iOS 9.3.1

#### Cordova CLI version and cordova platform version

```
cordova --version
5.4.1

cordova platform versions
android 4.1.1
ios 4.1.1
```
#### Plugin version
```
phonegap-plugin-push 1.6.2 "PushPlugin"
```
#### Log iOS:
**First push**:
```
didReceiveNotification with fetchCompletionHandler
app active
Notification received
Push Plugin key: alert
Push Plugin key: badge
Push Plugin finish called
Push Plugin stopBackgroundTask called
```
**Second push**:
```
didReceiveNotification with fetchCompletionHandler
app active
Notification received
Push Plugin key: alert
Push Plugin key: badge
```
#### Log Android
**First push**:
```
PushPlugin_GCMIntentService: onMessage - from: 399909845781
PushPlugin_GCMIntentService: normalize extras
PushPlugin_GCMIntentService: key = gcm.notification.e
PushPlugin_GCMIntentService: replace key gcm.notification.e with e
PushPlugin_GCMIntentService: key = gcm.notification.title
PushPlugin_GCMIntentService: replace key gcm.notification.title with title
PushPlugin_GCMIntentService: key = gcm.notification.body
PushPlugin_GCMIntentService: replace key gcm.notification.body with message
PushPlugin_GCMIntentService: key = collapse_key
PushPlugin_GCMIntentService: replace key collapse_key with collapse_key
PushPlugin_GCMIntentService: foreground
PushPlugin: convert extras to json
PushPlugin: key = e
PushPlugin: key = title
PushPlugin: key = message
PushPlugin: key = collapse_key
PushPlugin: key = foreground
PushPlugin: extrasToJSON: {"title":"wwwww","message":"wwwww","additionalData":{"e":"1","collapse_key":"com.example","foreground":true}}
```
**Second push**:
```
PushPlugin_GCMIntentService: onMessage - from: 399909845781
PushPlugin_GCMIntentService: normalize extras
PushPlugin_GCMIntentService: key = gcm.notification.e
PushPlugin_GCMIntentService: replace key gcm.notification.e with e
PushPlugin_GCMIntentService: key = gcm.notification.title
PushPlugin_GCMIntentService: replace key gcm.notification.title with title
PushPlugin_GCMIntentService: key = gcm.notification.body
PushPlugin_GCMIntentService: replace key gcm.notification.body with message
PushPlugin_GCMIntentService: key = collapse_key
PushPlugin_GCMIntentService: replace key collapse_key with collapse_key
PushPlugin_GCMIntentService: foreground
PushPlugin: convert extras to json
PushPlugin: key = e
PushPlugin: key = title
PushPlugin: key = message
PushPlugin: key = collapse_key
PushPlugin: key = foreground
PushPlugin: extrasToJSON: {"title":"eeeeee","message":"eeeeee","additionalData":{"e":"1","collapse_key":"com.example","foreground":true}}
```

**Comment by macdonst** [comment]
@manzapanza Yeah, but what does your `push.on('notification')` handler look like? It seems by those logs everything is fine with the native side. What are you seeing in the JS console when you receive a push?

**Comment by manzapanza** [comment]
I'm so sorry @macdonst to waste your time! 
I had implemented using promises but obviously `resolve` resolve the promise only one time. Shame on me! Using `notify` works perfectly.

My method was:

```
self.onNotification = function(){
  var deferred = $q.defer();
  _instance.on('notification', function(data) {
    deferred.resolve(data);
  });
  return deferred.promise;
};
```

that I changed to:

```
self.onNotification = function(){
  var deferred = $q.defer();
  _instance.on('notification', function(data) {
    deferred.notify(data);
  });
  return deferred.promise;
};
```

Thank you. You can close this issue!

**Comment by macdonst** [comment]
@manzapanza okay, cool. Glad you got it sorted.

**Comment by trazek** [comment]
I ran into a similar issue but turns out, calling `.init()` on app resume seemed to be preventing the `notification` callback from firing over and over. The documentation suggests calling `.init()` often, even during the app resume. If there another place we can call .`init()` to ensure the 3rd party push service still has our information?

**Comment by fredgalvao** [comment]
@trazek 
What do you mean by `ensuring the 3rd party push service still has our information`?

`init.()` should only be called once per lifecycle of the application, and presumably and preferably right after the `deviceready` event has fired.

If you're worried about always having the most up-to-date `registrationId`, then you should use the `registration` event, as you should already be.

**Comment by trazek** [comment]
@fredgalvao 
I was referring to this note in the documentation:

> Note: you will want to call PushNotification.init() each time your app starts. The remote push service can periodically reset your registration ID so this ensures you have the correct value.

Maybe I misunderstand what _each time your app starts_ means. If we can just call `.init()` once and never again for the life of the app, cool.

Thanks

**Comment by macdonst** [comment]
@trazek Your app starting is when it goes from not running at all to being loaded in memory. As @fredgalvao said that's where you want to call `init` after you get the `deviceready` event. If the app is in the background and you are resuming it then you don't need to call `init`.

**Comment by trazek** [comment]
@macdonst Thank you for the clarification. Makes perfect sense.

**Comment by coolvasanth** [comment]
In my case, it was the issue with checking the platform ready. I had no check for platform ready in the function. Once after I added **this.platform.ready()** event, I started receiving notifications all the time.
