### ISSUE TITLE
Phonegap Dev App INVALID_SENDER

### ISSUE THREAD

**Issue by marcelocpsantos** [phonegap/phonegap-plugin-push#871]
Hi,

I followed "http://docs.phonegap.com/develop/push-notifications/" tutorial and getting INVALID_SENDER error message.

Using UBUNTU 16.04 LTS, 
Phonegap  6.2.1,
phonegap developers app 1.6.3 running on a Motorolola Moto G, Android 5.1.

Thanks for any help.

**Comment by macdonst** [comment]
@marcelocpsantos there seems to be a bug in the connect-phonegap module that this depends on. For now use "85075801930" instead of "XXXXXXXX" as the sender ID.

**Comment by macdonst** [comment]
Yeah, I found and fix the bug in connect-phonegap. Should be released soon. https://github.com/phonegap/connect-phonegap/issues/154

**Comment by marcelocpsantos** [comment]
Thanks for the answer.


2016-05-09 12:08 GMT-03:00 Simon MacDonald <notifications@github.com>:

**Comment by macdonst** [comment]
@marcelocpsantos upgrade to PhoneGap CLI 6.2.2 as it is fixed now.

**Comment by danielro8** [comment]
I have  this problem too and I have PhoneGap CLI 6.5.2 however with 85075801930 instead XXXXX as sender id it works.
