### ISSUE TITLE
"Invalid Bundle Structure" - The binary file is not permitted

### ISSUE THREAD

**Issue by abhikhatri** [phonegap/phonegap-plugin-push#872]
#### Cordova CLI version and cordova platform version

    cordova --version                              # 5.4.1
    cordova platform version ios                   # 4.1.0

#### Plugin version

    push plugin version   # 1.6.3

Hey Guys,

I just installed phonegap-plugin-push in my ionic app and everything is working fine but when I tried to publish it to the App Store for review. It's giving me following error.

![image](https://cloud.githubusercontent.com/assets/6468965/15114679/b11ed396-1618-11e6-8985-46a39bbf907e.png)

I've done some research and some people on stackoverflow says you need to link via "Build Phases Tab" using **Link binary with libraries**.
Can you guys please help me figure out how to link those files so I can publish the app without breaking push plugin functionality.

**Comment by macdonst** [comment]
@abhikhatri how did the entire src code for the push plugin get in your www folder? That should never happen. When the plugin is installed those files should be copied to the Frameworks folder.

**Comment by abhikhatri** [comment]
@macdonst Idk I built my app like I usually do using "ionic build ios". The issue is resolved when I deleted the **phonegap-plugin-push** folder from "platform/ios/www/lib" and build the app again.

**Comment by macdonst** [comment]
@abhikhatri yeah, the plugin should never put the .a files in "platform/ios/www/lib" so I'm not sure what happened there.

**Comment by abhikhatri** [comment]
@macdonst Idk man, It happened itself. I changed the version on config.xml and rebuild the app using the same command. Now there's no lib folder anymore in the new build.

**Comment by macdonst** [comment]
@abhikhatri alright cool, glad it is resolved.

**Comment by PatrickKelly** [comment]
Seeing this issue as well, built like I always do and the phonegap-plugin-push folder ended up in "platform/ios/www/lib"

**Comment by PatrickKelly** [comment]
Actually every time I run "build ionic ios", the phonegap-plugin-push folder ends up in "platform/ios/www/lib"

**Comment by macdonst** [comment]
@PatrickKelly that sounds like an issue with the Ionic CLI not this plugin. Maybe you should ask this question over on the Ionic forums or slack. You can always invoke my name in pretty much every slack by using `@macdonst`.

**Comment by PatrickKelly** [comment]
Will do

**Comment by PatrickKelly** [comment]
Posted: https://forum.ionicframework.com/t/ios-build-puts-phonegap-plugin-push-copy-in-platform-ios-www-lib/61258

**Comment by PatrickKelly** [comment]
Figured it out. Had the plugin listed under my "devDependencies" in bower.json. That caused it to get copied to "www/lib". Removed it and ran bower prune

Not really sure how it got there.
