### ISSUE TITLE
Action Buttons on iOS lockscreen

### ISSUE THREAD

**Issue by ggiordan** [phonegap/phonegap-plugin-push#873]
I am working with the latest release 1.6.3 on iOS.  I have users who would like to initate actions from the lock screen.

Is it (would it be) possible to have the action buttons show on the lock screen?

The only time I see the action buttons is if I down swipe on the notfiication while its showing.  (is this right?  or possibly I'm doing it wrong)

**Comment by macdonst** [comment]
@ggiordan when on the lock screen try swiping from right to left to reveal the action buttons. I believe this should work.

**Comment by ggiordan** [comment]
Thank you.
Is there a way to bypass the lock screen completely? Or capture the response without unlocking?
When I swipe left to right, I do get the buttons (thank you).  What would be great is to be able to press the action button without having to unlock.

**Comment by macdonst** [comment]
@ggiordan er, I don't think you really want to do that. It means anyone can perform actions on your phone whether maliciously or accidentally.

I'm going to close this issue as the original problem is resolved.
