### ISSUE TITLE
Get value notification

### ISSUE THREAD

**Issue by jedofus** [phonegap/phonegap-plugin-push#876]
Hi , i have a question
It's possible to get value data on variable outdoor of method push.on('notification',function(data) ?
for example , i want to get the title value of my notification on variable when i got notification of my app . (JS)

**Comment by macdonst** [comment]
@jedofus I'm not sure what you are asking here. Do you want to set a variable outside who's scope is outside of the push notification event handler with the value of the title? If that is the question then yes, of course you can.

**Comment by jedofus** [comment]
Yes , it's my question , and how can i do this ?

**Comment by macdonst** [comment]
@jedofus all you need to do is declare the variable outside of the `notification` handler.

```
var ack = null;

var push = PushNotification.init({
    android: {
        senderID: "12345679"
    },
    ios: {
        alert: "true",
        badge: true,
        sound: 'false'
    },
    windows: {}
});

push.on('notification', function(data) {
    ack = data.message;
});

var printAck = function() {
    console.log("ack is " + ack);
};
```

So if you call `printAck()` you will see the latest data.message.

Make sense?

**Comment by jedofus** [comment]
yes i solved my problem , thank you !
