### ISSUE TITLE
No visible @interface for 'UIView' declares the selector

### ISSUE THREAD

**Issue by dabeer5stardesigner** [phonegap/phonegap-plugin-push#879]
when i click on build using xcode cordova project i my build was failed and i got this error.

Plugins/com.phonegap.plugins.PushPlugin/PushPlugin.m:222:23: No visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'

An other question is that my push notification not received in ios device.

**Comment by macdonst** [comment]
@dabeer5stardesigner you are raising a bug on the wrong plugin. The issue you have is with the old deprecated [PushPlugin](https://github.com/phonegap-build/PushPlugin). If you upgrade your app to use this repo you wouldn't have that issue.

**Comment by dabeer5stardesigner** [comment]
@macdonst  can you please help me how can i update my plugin using cordova command line or xcode because i m new.

**Comment by macdonst** [comment]
@dabeer5stardesigner it should all be part of this repo's docs. You will see how to install the plugin and what the new API is.

**Comment by dabeer5stardesigner** [comment]
NOW I M UPDATE MY PLUGIN USING THIS REPO BUT STILL SHOW THIS ERROR IN XCODE

**Comment by macdonst** [comment]
@dabeer5stardesigner don't shout.

Did you remove the old plugin first? I'm betting you didn't as that method does not exist in this plugin.

**Comment by dabeer5stardesigner** [comment]
@macdonst thanks for help issue solve can you do me a one more favor my php script show me this message ( Delivered Message to APNS ) but my ios device did not show pushnotification i have my 64 digit device token.
