### ISSUE TITLE
PushPlugin notification icon is too big

### ISSUE THREAD

**Issue by jff1981** [phonegap/phonegap-plugin-push#88]
PushPlugin notification icon is too big

Hi everyone,
I successfully installed  push plugin on my app, but the notifications icon doesn’t look good
See the attached photo
Does someone know how to fix it?

Thank you in advanced!
![screenshot_2015-08-30-11-43-41](https://cloud.githubusercontent.com/assets/14041738/9567861/181e9ab6-4f42-11e5-9d2c-05fde764e101.png)

**Comment by macdonst** [comment]
@jff1981 the space used to display your icon appears to be exactly the same as the Motorola and voicemail icons so I'm not sure what you mean by too big? Regardless, if you check the README you'll see that you can control what is displayed here by setting `options.android.icon` and `options.android.iconColor`.

**Comment by jff1981** [comment]
Thank you for your quick response!
I wasn't sure how to use this feature 
let's say i got an image  res/drawable/notify.png

**Comment by jff1981** [comment]
I tried this but it's not working 
var push = PushNotification.init(
			{ "android": {"senderID": "XXXXXX", "icon":"R.drawable.notify"},
			"ios": {}, "windows": {} } );

what am i doing wrong here?
Thanks in advanced!

**Comment by macdonst** [comment]
You just need to do:

```
var push = PushNotification.init(
{ "android": {"senderID": "XXXXXX", "icon":"notify"},
"ios": {}, "windows": {} } );
```

as long as the notify.png image is somewhere in your drawables folder.

**Comment by jff1981** [comment]
Thanks!
