### ISSUE TITLE
Not receiving notifications when app is closed

### ISSUE THREAD

**Issue by charithvalluru** [phonegap/phonegap-plugin-push#881]
unable to receive notifications when the app is closed. 
**Code written:**

let push = Push.init({
                android: {
                    senderID: [SENDER_ID]
                }
            });
            push.on('registration', (data) => {
                console.log(data.registrationId);
            });
           push.on('notification', (data) => {
                console.log(data.message);
                console.log(data.title);
                console.log(data.count);
                console.log(data.sound);
                console.log(data.image);
                console.log(data.additionalData);
            });
            push.on('error', (e) => {
                console.log(e.message);
            });
    }

and also, what is the frequency of device id getting changed?

**Comment by macdonst** [comment]
@charithvalluru do you mean when the app is in the background or when the app has been killed? If you want the notification event called when the app is in the background see the docs on Background Notifications. If you want your notification to be called when the app is killed then that is not currently supported.

The device ID does not change very frequently.
