### ISSUE TITLE
Device token not generated 

### ISSUE THREAD

**Issue by ujjal008** [phonegap/phonegap-plugin-push#882]
### Ionic Core: init
ionic.io.bundle.min.js:2 Ionic Core: searching for cordova.js
ionic.io.bundle.min.js:2 Ionic Core: attempting to mock plugins
ionic.io.bundle.min.js:2 Ionic Push: register

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 5.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.6.3

#### Sample Code that illustrates the problem

####Token not generated

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
