### ISSUE TITLE
Intel XDK, Gradle

### ISSUE THREAD

**Issue by Moghul** [phonegap/phonegap-plugin-push#883]
I'm building my app using Intel XDK and they can't build if the plugin has a gradle file in it.
From what I can see, the gradle edits what is basically 2 lines in the manifest. It adds the app id to the manifest on those lines.

Is it enough for me to remove the gradle file, remove the reference, and edit those lines in the plugin's xml file with my app id? Will the plugin work?

EDIT: should the app ID be backwards?

Well, I just tried it and it doesn't work, the log says

Package some.example.app attempting to redeclare permission some.example.com.permission.C2D_MESSAGE already owned by com.intel.appx.example.xwalk16

EDIT 2: Fixed mistyped app id. Android built fine but iOS won't build. All it says is failed to install push plugin.

EDIT 3: Found #817, looking into that. Seems like I answered a bunch of my own questions.

**Comment by macdonst** [comment]
@Moghul yeah, the reason I had to switch back to using the gradle file is you get those permission errors if two plugins both want to add the same permission. The only thing to do at this point is to ask IntelXDK team to support gradle files in plugins. Feel free to send them my way.

**Comment by Moghul** [comment]
@macdonst But if I don't have 2 plugins asking for the same permissions it's fine if I just modify the plugin and keep it in mind for the future, correct?

**Comment by ppetree** [comment]
I hate to bring this zombie to the top but what was the ultimate outcome? I'm getting ready to start down this path and want to make sure it works!

P.

**Comment by macdonst** [comment]
@ppetree check out this issue where @tony-- goes through the whole thing. https://github.com/phonegap/phonegap-plugin-push/issues/926#issuecomment-223191041

**Comment by Moghul** [comment]
If you need to build with the Intel XDK, for now, you'll have to remove the gradle file and refactor the ${application} in the plugin.xml with your app's app ID. Note that you'll need to use the debug module's app ID (something like com.intel.appx.[companyname].xwalk16). It's a pain in the ass but it works.

**Comment by macdonst** [comment]
Yeah, I can't add Gradle support to IntelXDK but @tony-- did a great write up on how to compile this plugin with the XDK.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md#intelxdk-support
