### ISSUE TITLE
Android GCM Action Buttons lack of documentation

### ISSUE THREAD

**Issue by ebarault** [phonegap/phonegap-plugin-push#884]
hi, 
this is more of some questions/remarks on the docs:

In [PAYLOAD.md/android/action buttons](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons)
The docs refer to callbacks attached to an `app` object, just like
```
message.addData('actions', [
    { "icon": "emailGuests", "title": "EMAIL GUESTS", "callback": "app.emailGuests", "foreground": true},
    { "icon": "snooze", "title": "SNOOZE", "callback": "app.snooze", "foreground": false},
]);
```

To what app object are you referring to? where should it be declared, attached to what root object? I'm in the context of an ionic app. And I only could make it work using the window object like this:

excerpt of the notification
```
message.addData('actions', [
    { "icon": "emailGuests", "title": "EMAIL GUESTS", "callback": "emailGuests", "foreground": true},
    { "icon": "snooze", "title": "SNOOZE", "callback": "snooze", "foreground": false},
]);
```

excerpt of app code where declaring the callbacks
```
window.emailGuests = function() {
    // do something
}

window.snooze = function() {
    // do something
}
```

a complete example including app code would be much appreciated i guess, as i see some posts of people stuck in the middle with this, including

[here](https://github.com/phonegap/phonegap-plugin-push/issues/274#issuecomment-194794528)
[there](https://forum.ionicframework.com/t/handling-push-notification-action-buttons-with-phonegap-plugin-push/44161/5)

**Comment by macdonst** [comment]
@ebarault 

1. I don't think I have `app.myCallback` anywhere in the docs so I'm not sure where that needs to be cleared up. If that was the function to be called on a button press then there has to be an object `app` which has a function `myCallback`.
2. Yeah, it's probably not a great idea to call code that is not loaded in your app.

Where do you see lots of people struggling with this? I'd love to be able to answer their questions.

**Comment by ebarault** [comment]
@ macdonst: thanks for answering, i updated the issue

**Comment by sumeeranalabs** [comment]
call back function not working ,please any one help me out about this issue.

**Comment by prafull-agarwal** [comment]
Hi Guys 

I am also using this plugin with my push notification having actions buttons with actions to be performed in background without open my app. 

So this works fine in iOS but on Android it works only when i set foreground true but when i set to foreground false for android its action not working. 

So let me know what thing i am doing wrong or its not support this for Android?

**Comment by yesroh** [comment]
please, someone could help me on this? #1569
