### ISSUE TITLE
disable notification's sounds on a per notification basis

### ISSUE THREAD

**Issue by ebarault** [phonegap/phonegap-plugin-push#885]
very short question: is there a way for android notifications to make sure a given notification is not playing any sound at all while not deactivating sounds globally through configuration at push.init?

**Comment by macdonst** [comment]
@ebarault Yeah, you can send the empty string. I just updated the docs:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#sound
