### ISSUE TITLE
silent notification (no title, no message, no icon, no sound, etc.)

### ISSUE THREAD

**Issue by ebarault** [phonegap/phonegap-plugin-push#886]
### Expected Behaviour
completely silent notification while delivering a payload in background: no sound, no notification shown on phone's homescreen, etc.

### Actual Behaviour
whatever i tried to build a background notification as per the docs I still have a notification displayed on the phone's homescreen, with a title which is the name of my app, which i did not configured anywhere

### Reproduce Scenario (including but not limited to)
send the simple notification i've noted down below

#### Steps to Reproduce 
use of ionic push service to send the notification

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
tested on Android 4.4 and Android 6

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung GS6 & HTC One

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.1.1
    cordova platform version android            android 5.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.6.3 

#### Sample Push Data Payload

I've adapted a little bit the actual payload since i'm using the ionic push service, but it comes down to this when stripped all the ionic semantic
```
            "data": {
                "info": "super secret info",
                "content-available": "1"
            }
```

#### Sample Code that illustrates the problem

my push init & register code  (i'm using the plugin through the ionic $angular wrapper)
```
        push = $ionicPush.init({
            'debug': true,
            'onNotification': onNotification,
            'onRegister': onRegister,
            'pluginConfig': {
                'ios': {
                    'badge': true,
                    'sound': true
                },
                'android': {
                    'senderID': 'xxxxx',
                    'sound': true
                }
            }
        });

            $ionicPush.register();
```
#### Logs taken while reproducing problem

**Comment by macdonst** [comment]
@ebarault yes, it is possible but you aren't giving me much to go on here. Please follow the issue reporting guidelines. I need to know what platform you are testing on what your push payload is etc. Please re-open when you provide those details.

**Comment by ebarault** [comment]
I have updated the issue as per the provided guidelines, may you reopen it?

**Comment by ebarault** [comment]
I've updated the issue, i can't reopen it myself i guess

2016-05-14 2:44 GMT+02:00 Simon MacDonald <notifications@github.com>:

**Comment by macdonst** [comment]
@ebarault can you not strip out the Ionic semantics? I have a feeling their service adds in some defaults that keep this from being a silent push. If you reproduce the issue when running `adb logcat | grep PushPlugin` it would help diagnose.

**Comment by ebarault** [comment]
so I read between the lines that the notification i send should result in a trully silent (and background) notification. 
In that case i do believe too that the ionic rewriting is faulty in several cases. I opened 2 issues for ionic push [here](https://github.com/driftyco/ionic-platform-web-client/issues/108) and [there](https://github.com/driftyco/ionic-platform-web-client/issues/109).

the first one exactly describes the issue we're discussing here.

the incriminated payload is the following, which is the only correct set-up i found to make a notification that the app receives in background without requiring to action it.

```
curl -X POST -H "Authorization: Bearer XXXXX" -H "Content-Type: application/json" -d '{
    "tokens": ["myToken"],
    "profile": "ZZZZZ",    
    "notification": {
        "android": {
            "payload": {
                "info": "super secret info"
            },
            "data": {
                "title": "",
                "message": "",
                "content-available": "1"
            }
        },
        "ios": {
            "content_available": 1
        }
    }
}' "https://api.ionic.io/push/notifications"
```

I will post later the adb log, but i can already confirm that there should be some faulty rewriting somewhere at ionic side since a non-empty notification title is added on the fly, and received by the app, and thus shown to the user.

You should definitely give a go to my write-up on ionic push github about the handling of the native notification payloads, your comments would be much appreciated there to sort things out.
I

**Comment by ebarault** [comment]
ok, @macdonst, here is the debug info from adb, so yes: we can see a 'myApp' title being inserted, coming from ionic most probably
```
D/PushPlugin_GCMIntentService(20101): onMessage - from: 44xxxxxxxx956
D/PushPlugin_GCMIntentService(20101): normalize extras
D/PushPlugin_GCMIntentService(20101): key = payload
D/PushPlugin_GCMIntentService(20101): replace key payload with payload
D/PushPlugin_GCMIntentService(20101): key = data
D/PushPlugin_GCMIntentService(20101): extracting nested message data from key = data
D/PushPlugin_GCMIntentService(20101): key = data/message
D/PushPlugin_GCMIntentService(20101): key = data/content-available
D/PushPlugin_GCMIntentService(20101): key = data/title
D/PushPlugin_GCMIntentService(20101): replace key data with data
D/PushPlugin_GCMIntentService(20101): key = title
D/PushPlugin_GCMIntentService(20101): replace key title with title
D/PushPlugin_GCMIntentService(20101): key = collapse_key
D/PushPlugin_GCMIntentService(20101): replace key collapse_key with collapse_key
D/PushPlugin_GCMIntentService(20101): background
D/PushPlugin_GCMIntentService(20101): message =[]
D/PushPlugin_GCMIntentService(20101): title =[myApp]
D/PushPlugin_GCMIntentService(20101): contentAvailable =[1]
D/PushPlugin_GCMIntentService(20101): create notification
E/PushPlugin_GCMIntentService(20101): Number format exception - Error parsing notId: Invalid int: "null"
D/PushPlugin_GCMIntentService(20101): stored icon=ic_notification
D/PushPlugin_GCMIntentService(20101): stored iconColor=#e52a4b
D/PushPlugin_GCMIntentService(20101): stored sound=true
D/PushPlugin_GCMIntentService(20101): stored vibrate=true
D/PushPlugin_GCMIntentService(20101): using icon from plugin options
D/PushPlugin_GCMIntentService(20101): create actions
D/PushPlugin_GCMIntentService(20101): send notification event
D/PushPlugin(20101): convert extras to json
D/PushPlugin(20101): key = content-available
D/PushPlugin(20101): key = payload
D/PushPlugin(20101): key = data
D/PushPlugin(20101): key = title
D/PushPlugin(20101): key = message
D/PushPlugin(20101): key = collapse_key
D/PushPlugin(20101): key = foreground
V/PushPlugin(20101): extrasToJSON: {"message":"","additionalData":{"data":{"message":"","content-available":"1","title":""},"payload":{"info":"super secret info"},"collapse_key":"do_not_collapse","content-available":"1","foreground":false},"title":"myApp"}
```

**Comment by macdonst** [comment]
@ebarault yeah, this is an issue with Ionic Push for sure. I will comment on the issue that you opened and I will be seeing some of the Ionic guys this week so I'll talk to them about it. Going to close this issue for now unless there is something for me to do on my end.

**Comment by ebarault** [comment]
thanks Simon, appreciate that.


2016-05-16 16:24 GMT+02:00 Simon MacDonald <notifications@github.com>:

**Comment by ennisthemenace** [comment]
Any news on this?
