### ISSUE TITLE
iOS Store Warning

### ISSUE THREAD

**Issue by snowbreeze** [phonegap/phonegap-plugin-push#887]
### Expected Behaviour
No warning should be there
### Actual Behaviour
Missing Push Notification Entitlement - Your app appears to include API used to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. See "Provisioning and Development" in the Local and Push Notification Programming Guide for more information. If your app does not use the Apple Push Notification service, no action is required. You may remove the API from future submissions to stop this warning. If you use a third-party framework, you may need to contact the developer for information on removing the API.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.

### Reproduce Scenario (including but not limited to)
Publish to apple store

#### Steps to Reproduce 
Install with google project number as sender id.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 8 and above
#### Cordova CLI version and cordova platform version
cordova 6
ios 4.1.1
    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version
1.6.3
    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

#### Question
Anything I need to do for apple. I have included the google console project number when installing. Apart from that I have done nothing else.

**Comment by macdonst** [comment]
@snowbreeze yeah, that is not a problem with the plugin. You need to set up your provisioning profile with Apple correctly to distribute an app with push functionality.

This stackoverflow question and answer should help you getting past this issue: http://stackoverflow.com/questions/27945557/missing-push-notification-entitlement-warning

**Comment by snowbreeze** [comment]
Thank you!
