### ISSUE TITLE
iOS support is missing from cordova_plugin.js

### ISSUE THREAD

**Issue by itnip** [phonegap/phonegap-plugin-push#888]
### Expected Behaviour
cordova_plugin.js should include:

module.exports.metadata = 
// TOP OF METADATA
{
    ....
    "phonegap-plugin-push": "1.6.3"
    ....
}
// BOTTOM OF METADATA
});

### Actual Behaviour
Reference to plugin-push is missing from iOS but appears in Android
This results with PushNotification() object is undefined in js

### Reproduce Scenario (including but not limited to)
Compile app using phonegap and check the file for both iOS and Android

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
I know that 1.6.2 and 1.6.3 miss the reference
1.5.3 is good

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@itnip not much to go on here. You didn't even tell me what version of cordova-ios you are using. My best guess with this limited information is that you are not using cordova-ios 4.0.0 or greater which is a requirement of plugin version 1.6.x.

**Comment by itnip** [comment]
I'm using phonegap-build with their settings.
It says cli-5.2.0. iOS = 3.9.1, Android = 4.1.1

**Comment by macdonst** [comment]
@itnip right, version 1.5.x of the plugin works with cordova-ios 3.9.x and lower but version 1.6.x requires cordova-ios 4.x and higher. You need to upgrade your version of cordova-ios if you want to use version 1.6.x or higher.

**Comment by itnip** [comment]
I'm using phonegap build. How can I upgrade the iOS version ?
I don't know how, but there should have been some kind of a warning. It took me hours to find out what was the error and weeks to find out that there even was an error.

**Comment by itnip** [comment]
Found it, https://build.phonegap.com/current-support
There should still be a warning, though

**Comment by macdonst** [comment]
@itnip probably is one, if not raise a bug on https://github.com/phonegap/build
