### ISSUE TITLE
Getting the device id 

### ISSUE THREAD

**Issue by ardian** [phonegap/phonegap-plugin-push#896]
Hi, 

How do I get the device id in index ?

**Comment by Davids89** [comment]
You can use the cordova variable device to get it: device.uuid

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
