### ISSUE TITLE
iOS App closed or in background does not receive notification

### ISSUE THREAD

**Issue by fjordansilva** [phonegap/phonegap-plugin-push#899]
### Expected Behavior

iOS app does show a push notification when it's on background or even when the app is closed. 
### Actual Behavior

The app only shows the notification when it's in foreground. 
### Reproduce Scenario (including but not limited to)

New project with the plugin added and receiving push notifications if the app is in foreground. The app has permissions to show push notifications.

Case 1: Send the app to background. Send a new push notification from the test server. The app doesn't show anything.
Case 2: Close the app. Send a new push notification from the test server. The app doesn't show anything.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Tested on iOS 9.3.2
#### Cordova CLI version and cordova platform version

```
cordova --version                                    # e.g. 6.0.0
```

6.1.1
    cordova platform version iOS                     # e.g. 4.1.1
4.1.1
#### Plugin version

1.6.3

**Comment by Moghul** [comment]
If you're using GCM, this payload works:

`{ "priority" : "high",
"notification": {
"title": "Test Notification",
"body": "This offer expires at 11:30 or whatever",
"notId": 10
},
"data" : {
"surveyID": "ewtawgreg-gragrag-rgarhthgbad",
"content-available": "1"
},
"to": "id here"
}`

**Comment by fjordansilva** [comment]
No, I'm using APNS.

**Comment by Moghul** [comment]
You haven't posted the payload you're using but are you using "alert" as per

For instance the following JSON:

{
    "aps": {
        "alert": "Test background push",
        "content-available": 1
    }
}
will produce a notification in the notification shade and call your on('notification') event handler.

However if you want your on('notification') event handler called but no notification to be shown in the shader you would omit the alert property and send the following JSON to APNS:

{
    "aps": {
        "data": "Test silent background push",
        "moredata": "Do more stuff",
        "content-available": 1
    }
}

**Comment by fjordansilva** [comment]
Sorry, I forgot the payload. I use a very simple payload:
```{
    "aps": {
        "alert": "Cambio de estado de TEST del vuelo XXX",
        "sound": "default"
    }
}```

Again, if the app is in foreground everything works fine but if the app is in background or closed, the notification is not shown.

**Comment by Moghul** [comment]
I got nothin'... Use content-available since it wakes up the app? Sorry I couldn't help more.

**Comment by fjordansilva** [comment]
I have found the fix. The iOS part of the plugin also needs the definition of:

```
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
    NSLog(@"application:didReceiveRemoteNotification: %@", userInfo);
}
```

Adding that method everything works fine.

**Comment by macdonst** [comment]
@fjordansilva I'll check out your PR but it's weird to think that would fix anything. All you are doing is printing a log and we already implement `- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler` which is basically the same thing.

**Comment by macdonst** [comment]
@fjordansilva can I see what you use for the init method?

**Comment by felipetoffolo1** [comment]
I have the same problem. Any news?

**Comment by engagedmorales** [comment]
guys,

I have faced this problem for days, and fixed that just adding priority: "high" in the objectt sent to Notifications Service.

Now, my app on IOS shows me notification even the app is killed (closed).

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.

**Comment by faldunate** [comment]
I have the same problem, I tried to apply different solutions but nothing works for me.

This is my json to aps.

`{"aps":{"alert":"","background":true,"content-available":1,"priority":10}}`

With this json to aps `.on('notification')` the event is not executed when the app is closed (killed).

¿Some solution? :/
