### ISSUE TITLE
[iOS] Device doesn't receive notification

### ISSUE THREAD

**Issue by Davids89** [phonegap/phonegap-plugin-push#903]
### Expected Behaviour
A notification should be appear and an ionic alert in the app
### Actual Behaviour
The app doesn't receive the notification
### Reproduce Scenario (including but not limited to)
The device is registered in the backend when we send an example notification. In Android it works perfectly but not in iOS.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 9.3.2
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version ios                     # e.g. 4.0.0

**Comment by dipedro** [comment]
post your payload and more information, because this problem can be many things.

**Comment by Davids89** [comment]
@dipedro can you tell me where I can find it? I read it in a few issues but I don't know where config it

**Comment by macdonst** [comment]
@Davids89 yeah, we really need more info in order to debug this one.

**Comment by dipedro** [comment]
@Davids89 in your payload backend you have it: "content-available": 1 ?

You can also try this : [https://github.com/phonegap/phonegap-plugin-push/issues/899](url)

**Comment by Davids89** [comment]
I think that the problem is in APN because the implementation follow the tutorial

**Comment by Davids89** [comment]
I solved creating a new provisioning file, I didn't know it. Thanks a lot.
