### ISSUE TITLE
Can't recive any notification because onNotification doesn't fire in iOS 9.3.1

### ISSUE THREAD

**Issue by oriolg23** [phonegap/phonegap-plugin-push#905]
### Expected Behaviour

When I send a notification from Amazon SNS the app should show it.

### Actual Behaviour

Aplication does nothing, with the app opened or closed, when I send a push notification. Nothing appears in Notification Center or in the app if it's opened.

I sign the APP with a Profile for APNS Developement, it is archieved correctly.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 9.3.2

#### Cordova CLI version and cordova platform version

    cordova --version  6.1.1
    cordova platform version ios  4.1.1

#### Plugin version

Version PushPlugin 1.6.3

#### Sample Push Data Payload

{
"APNS_SANDBOX":"{\"aps\":{\"badge\":12, \"sound\":\"default\", \"alert\":\"alert text\"}}"
}

#### Sample Code that illustrates the problem

aparcare.run(function (....){

        var push;
        //Code to get the token with on('registration') and register to Amazon SNS (works perfectly!)

        push.on('notification', function(data) {
               alert("Hi");
               alert(data.title+": "+data.message));
        });

});

#### Logs taken while reproducing problem

I put an alert when I get the token and it retrieves correctly, I put and alert immediately after the push.on('notification') but nothing appears.

**Comment by Davids89** [comment]
Same here

**Comment by oriolg23** [comment]
I solved the problem! I explain my solution for other people:

I'm using SNS to send message with Ad:hoc certificate. Because push notifications will work, the app in the AWS Console need to be a Apple iOS Prod.

Thanks for all answers I recived.
