### ISSUE TITLE
'notification' not called when App Icon is clicked on android

### ISSUE THREAD

**Issue by edambasuren** [phonegap/phonegap-plugin-push#910]
### Expected Behaviour

When a notification is received while the application is in the background, the 'notification' event should be called when the user launches app through app icon.

### Actual Behaviour

When a notification is received the 'notification' event is not called when the app is launched through the App Icon, but the notification is called when the notification bar is clicked.

#### Steps to Reproduce 

1. Put application in background
2. Push a notification to preferred device.
3. Wait for a few seconds then click on the App Icon to launch the application
4. Put an alert message in 'notification' listener to test if a notification is received.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

android emulator 6.0
also same on android emulator 5.1.1

#### Cordova CLI version and cordova platform version

    cordova --version                                             6.1.1
    cordova platform version android                     5.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.6.3

#### Sample Push Data Payload

```
var gcmMessage = new gcm.Message();
gcmMessage.addData({
	title: 'title',
	message: 'message', 
});
```

#### Sample Code that illustrates the problem

```
.run(function($ionicPlatform,$location,$rootScope,$state,$stateParams,SMSServer,WebSQL) {
	$ionicPlatform.ready(function() {
		var push = PushNotification.init({
			android: {
				senderID: "xxxxxxxxxxx"
			},
			ios: {
				alert: "true",
				badge: "true",
				sound: "true"
			},
			windows: {}
		});
		push.on('registration', function(data){
                   ..
		});
		push.on('notification', function(data) {
			console.log("PushNotification:notification");
		});
```

#### Comment
   - notifications come to notification bar
   - on 'notification' is called alright when clicked on notification bar
   - it is just clicking on app icon does not produce desired result

   - adding 'content-available': '1' to gcmMessage.addData works as described
     with result that click on app icon still does not call on 'notification'.

**Comment by dipedro** [comment]
1 - Test in one real device and look if behavior is the same.
2 - Post your code completed of service, because i don't see the code of registration the your device.
3 - In line 
`console.log("PushNotification:notification");`
change for:
`console.log("Notification: " + JSON.stringify(data));`

Note: the function 'registration' is called?

**Comment by edambasuren** [comment]
1. tested on Nexus 4 (android 5.1.1). Behavior is the same.
 
2. registration code is fine. It is called and I am sending registration is to server.
I am receiving gcm notifications.

3. console.log("Notification: " + JSON.stringify(data));
gives:
Object {title: "title", message: "message", additionalData: Object}
where additionalData
   coldstart : false
   collapse_key : "do_not_collapse"
   foreground : false
when clicked on notification bar.
Starting the app by clicking on app icon does not call on 'notification' method.

**Comment by edambasuren** [comment]
in case it helps:

$  ionic plugin list
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-contacts 2.1.0 "Contacts"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
ionic-plugin-keyboard 2.1.0 "Keyboard"
phonegap-plugin-push 1.6.3 "PushPlugin"

**Comment by macdonst** [comment]
@edambasuren actually, what you describe seems like the expected behaviour. The notification handler doesn't get called when you launch the app via the app icon, only when you launch the app via the notification.
