### ISSUE TITLE
.init usage, how can I tell if a change was made?

### ISSUE THREAD

**Issue by avielfedida** [phonegap/phonegap-plugin-push#912]
The api reference says:
> you will want to call PushNotification.init() each time your app starts. The remote push service can periodically reset your registration ID so this ensures you have the correct value.

I understand the registration ID can change, after a change was made, how do I know about that change, about the new registration ID, from the statement above: `this ensures you have the correct value`, do I?, I mean I need the new registration ID to update my server.

**My question:**
How do I get the new registration ID?, Should I reattach the 'registration' handler, and compare the old registration ID with the new one?

**Comment by Jojr** [comment]
You get a new Registration ID when run the app first time or uninstall the app, and install again later.
You don't get a new Registration Id when you update or reinstall the app without previous uninstall.

In my Apps, I send the DEVICE ID and GCM ID to server via XHR, and store values in Database. 
In the server side, I just save the values if not exists or don't match both values stored in database.

**Comment by fredgalvao** [comment]
> You get a new Registration ID when run the app first time or uninstall the app, and install again later.

This is true. You get a new registrationId for any new installation of said app.
**PSA: I have no guarantee of this. This has been the case on my personal experience, but I wouldn't COUNT on it.** 

> You don't get a new Registration Id when you update or reinstall the app without previous uninstall.


That is **not** entirely true.

GCM/APNS can, for many reasons, generate new `registrationIds` for any of your devices at any time.
This is why we recommend you to subscribe to the `.on('registration')` event everytime your app starts/opens. That way, you'll always get a value for the `registrationId`. At that point, everytime it runs and gives you a value, it's up to you to:

* save it somewhere everytime, overriding the previous value without regard
* save it the first time, and check everytime after that to see if the previous value is different than the new value, and if positive you proceed to save the new value overriding the previous one
* do whatever else you may want with it

Check this to see a sample of code that does the second option: http://macdonst.github.io/push-workshop/module2.html


## Conclusion

> Should I reattach the 'registration' handler, and compare the old registration ID with the new one?

Yes, you attach the `registration` handler everytime your app starts, and compare the old (wherever it may be stored) with the new one.

**Comment by macdonst** [comment]
@avielfedida I consider @fredgalvao answer to be the official answer and I'm closing this issue.
