### ISSUE TITLE
Receiving MismatchSenderId from backend, no matter what API key/app id/token I use

### ISSUE THREAD

**Issue by iltoga** [phonegap/phonegap-plugin-push#918]
### Expected Behaviour
client app (phonegap app) registers on Gcm, using google project Id (Sender ID - eg. mine is 111019698100) relative to the Server API key (that will be used by the backend to send the push message) and obtains a valid registration Id (to be used together with the Server API key by a backend to send push notifications to the device)

### Actual Behaviour
client (phonegap app) registers (and unregisters) correctly and obtains a registration Id, like this one:
dQGyItBE3LE:APA91bF-SyLQHSJ8JjKkl6MM5Ld9n4O1-Ka8a296WU4VcscwnmLFh0ejclgKVSLEa4uCx83XaN6YqnPDnPbqaEgLV9T26FhQZHAVlK3B6NXc6-MoH5qYpUyvzGUIjpEOf0w1Ta1fKyYL

but when trying to send a push message (either from my backend or curl or http://www.pushwatch.com/gcm/), using the Server API key relative to project id: 111019698100, I receive
 
#### Steps to Reproduce
install a new phonegap app with:
phonegap create ./gcmsampleapp --template phonegap-template-push

change the sender id in config.xml and www/js/index.js with my own: 111019698100

phonegap build android

phonegap serve android

open phonegap app on my development mobile phone (zenfone 2, android 5.0)

copy the registration Id from phonegap console log

execute the following curl command to send a push message:
curl --header "Authorization: key=I-won't-tell-you" --header "Content-Type: application/json" https://android.googleapis.com/gcm/send -d "{\"registration_ids\":[\"dQGyItBE3LE:APA91bF-SyLQHSJ8JjKkl6MM5Ld9n4O1-Ka8a296WU4VcscwnmLFh0ejclgKVSLEa4uCx83XaN6YqnPDnPbqaEgLV9T26FhQZHAVlK3B6NXc6-MoH5qYpUyvzGUIjpEOf0w1Ta1fKyYL\"]}"

response:
{"multicast_id":7288016595189833715,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"MismatchSenderId"}]}

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Asus Zenfone 2

#### Cordova CLI version and cordova platform version
phonegap 6.2.5

#### Plugin version
1.6.3

#### Sample Push Data Payload
"test message"

**Comment by iltoga** [comment]
I've found the reason why I can't get registrations Id to work..
using "phonegap serve" launches the app from 'browser' platform, which is not compatible with push messages. it registers to gcm, but the registration ids are not valid..

using "phonegap run android --debug" together with "chrome://inspect/#devices" (from google chrome url bar) solved the problem. Plus now I can debug real apps instead of 'emulated' ones ;)

**Comment by macdonst** [comment]
@iltoga no, that's not the reason it doesn't work. PG Dev app 1.7.0 now includes the push plugin but in order to send test pushes you have to use our service. The reason we force you to use a test service for PG Dev App is that we need to support iOS as well and there is no way to support it otherwise. Please read:

http://docs.phonegap.com/develop/push-notifications/
http://macdonst.github.io/push-workshop-eu/

for more details.

**Comment by ezstartup** [comment]
excuse , i did follow ur instructions . but i still got mismatchSender Id .

i doubt the value I set here ( "android": { "senderID": "854979356487" }, )  is work . 

because no matter what senderId I set , i always get the same registerId . 

any one know the reason . tks so much ...
