### ISSUE TITLE
How can i create a push notification in android and IOS. Send me a example code to test in my application.

### ISSUE THREAD

**Issue by sumeetitsme** [phonegap/phonegap-plugin-push#919]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by lavarith** [comment]
This is not an actual issue and you should at least read the README before submitting tickets like this.

See here:
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/EXAMPLES.md

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
