### ISSUE TITLE
Notification not bringing app to the foreground on Android

### ISSUE THREAD

**Issue by tcopestake** [phonegap/phonegap-plugin-push#92]
Hello there.

I'm having a problem which has been discussed in issues on https://github.com/phonegap-build/PushPlugin, but doesn't appear to be addressed in any version on this repository and doesn't seem to have been flagged as an issue already here.

When the app is running in the background and a notification comes through, clicking the notification doesn't bring the app to the foreground. Sometimes nothing happens at all, but sometimes I can see that it starts trying to bring the activity to the foreground before it disappears. In either case, the app disappears from the list on the multitasking screen also.

I've tried eliminating all other code to rule out a crash caused by something else in my app, but no dice. The problem does appear to be with the plugin.

Note: Clicking the notification when the app has been closed down completely _does_ launch the app successfully. The problem occurs only when the app is running in the background.

Happens for me on Android 4.4, 5.0 and 5.1.
Using version 1.2.2 of this plugin.

Thanks in advance.

**Comment by macdonst** [comment]
@tcopestake really? I can't reproduce this at all. What are you sending via GCM?

**Comment by tcopestake** [comment]
I'm using a third party PHP package to send the notification via GCM. It has the fields: title, message, signal and data.

**Comment by macdonst** [comment]
@tcopestake can you try using the ruby file in example/server to send a notification and let me know if that makes a difference?

**Comment by tcopestake** [comment]
Hello again.

As requested, I sent a notification using the Ruby example. The notification came through, but again pressing it didn't bring the activity to the foreground.

I used adb to have a look at what happens when I press the notification. The only thing that stands out as relevant is an error message I remember also reading about in another thread:

W/InputMethodManagerService(743): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@3c7f1c3 etc.

A quick Google shows that this error is indeed linked to activities failing to start. Now to figure out why...

**Comment by macdonst** [comment]
@tcopestake that's very weird. Can you try running the example app in examples/www? That is create a new app with that www as the base, add the push plugin and see if you can reproduce?

**Comment by tcopestake** [comment]
After some tweaking, the culprit (in this case, at least) seems to be when `android:launchMode` is set to `singleInstance` - which I have set in my config file. Presumably the other people who reported the same problem had something similar.

For my own purposes, I may be able to live without `singleInstance`. I guess it would be for you guys to decide whether it's worth patching the plugin to work around this limitation.

Thanks again for your time.

**Comment by johnnyoin** [comment]
Hi,

I'm having the same issue here. In my case, using the singleInstance launch mode was the only way I found to bring my app from background when sharing content from outside with WebIntent cordova plugin.

**Comment by KaluKhan** [comment]
I faced same issue, [David Wasser's ](http://stackoverflow.com/questions/12074980/bring-application-to-front-after-user-clicks-on-home-button)  helped me.
