### ISSUE TITLE
Problem with APNs over HTTP/2

### ISSUE THREAD

**Issue by vtellez** [phonegap/phonegap-plugin-push#920]
### Expected Behaviour
Send push notification to registered device token with this plugin for iOS (Android has no problem)

### Actual Behaviour
I am always receiving {“reason”:”DeviceTokenNotForTopic”}

### Reproduce Scenario (including but not limited to)
Everything seems to be OK in the client app. I ask me for permission to receive push notifications.

But when I try to send a push notification through APNs service from the server using the registered token over http, I am always receiving  **{"reason":"DeviceTokenNotForTopic"}**

#### Steps to Reproduce 
In iOS, I am trying to send push notification from commad line with this order:

curl -d '{"aps":{"alert":"[MESSAGE]","sound":"default"}}' --cert "[PATH TO APS CERTIFICATE.pem]":"" -H "apns-topic: [BUNDLE IDENTIFIER]" --http2 https://api.development.push.apple.com/3/device/[TOKEN]

But I am always receiving this error:

**{"reason":"DeviceTokenNotForTopic"}**

In my config.xml I've used this bundle id  <widget id="**es.mypush.example**" ...

with this command from the command line:
`curl -d '{"aps":{"alert":"Hi","sound":"default"}}' --cert "mycert.pem":"" -H "apns-topic: es.mypush.example" --http2 https://api.push.apple.com/3/device/bdd07cc28c5c088cf5279200ef060c0a10397b4fc7b4ece1c4da99c67e82e12a`

Not sure which is the topic is registering the device in apns service, I suposed that the phonegap cli was sending the widegt id, but it does not seems that.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 9.3.2 & iOS 9.2.1

#### Cordova CLI version and cordova platform version
I use phonegap build cli 5.4.1

#### Plugin version

`<gap:plugin name="phonegap-plugin-push" spec="~1.4.5" source="npm">`

#### Sample Push Data Payload
'{"aps":{"alert":"Hi","sound":"default"}}'

#### Sample Code that illustrates the problem
`curl -d '{"aps":{"alert":"Hi","sound":"default"}}' --cert "mycert.pem":"" -H "apns-topic: es.mypush.example" --http2 https://api.push.apple.com/3/device/bdd07cc28c5c088cf5279200ef060c0a10397b4fc7b4ece1c4da99c67e82e12a`

#### Logs taken while reproducing problem
**{"reason":"DeviceTokenNotForTopic"}**

**Comment by macdonst** [comment]
@vtellez I'd have to see your init method parameters and an registration ID you get back from the remote push service to tell you for sure but I'm willing to be you are registering for GCM on iOS but trying to send via APNS. If you register with GCM on iOS you need to send your push via GCM.

**Comment by vtellez** [comment]
Hi @macdonst 

Mi init method is this one:

`        
var push = PushNotification.init({
            android: {
                senderID: "XXXXXX"
            },
            ios: {
                senderID: "XXXXX"
                alert: "true",
                badge: "true",
                sound: "true",
            },
        });
`


This registration gives me this devide id: 97c5f678f32bc12578b3f806214e016e1d1918c5ecd15cbd02e9f7ca03c9ea06

**Comment by macdonst** [comment]
@vtellez yeah, if you are going to use APNS to receive messages you don't need to put senderID: "XXXXX" in your ios options. 

Basically what seems to be happening here is your bundle ID does not match your cert. Take a look at config.xml and make sure the id property of the widget tag, your bundle ID in Xcode and the bundle ID for you cert all match. If they don't you'll get this problem.

Also, don't confuse your debug and production certs.

**Comment by vtellez** [comment]
@macdonst  Ok, let me try without the sender ID, I will post with result in some minutes.

I will also generate new certs to cerify, they are all using the same bundle id

Thanks!

**Comment by vtellez** [comment]
I am still receiving {"reason":"DeviceTokenNotForTopic"}

I detail all the process:

The config.xml widget definition:

`<widget id="com.socialgym" xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0" versionCode="524" version="5.2.4">`

Phonega build cli version (If I use a newer version like 6.0.0 or 6.1.0, phonegap build service does not compile):

> <preference name='phonegap-version' value='cli-5.4.1' />

phonegap-push-plugin version (if I use a newer version, the app seems not working):

> <gap:plugin name="phonegap-plugin-push" spec="~1.5.3" source="npm">
        <param name="SENDER_ID" value="XXXX" />
    </gap:plugin>


On my device ready, I use this registration function:

`        var push = PushNotification.init({
            android: {
                senderID: "768274361309"
            },
            ios: {
                alert: "true",
                badge: "true",
                sound: "true",
            },
        });

        push.on('registration', function(data) {
            localStorage.setItem('deviceid',data.registrationId);
            alert('Dispositivo registrado: '+ localStorage.getItem('deviceid'));
        });

        push.on('notification', function(data) {
            App.alert(data.message);
        });

        push.on('error', function(e) {
            alert(e.message);
        });
`



When I start the APP I get an alert with a correct devide id like: 

> 97c5f678f32bc12578b3f806214e016e1d1918c5ecd15cbd02e9f7ca03c9ea06



I also create an development .cer from .csr file. Then I obtain the .p12 and finally I get the .pem certificate, all these files with bundle id

> com.socialgym


I finally use a command line order to try the push service:

`curl -d '{"aps":{"alert":"Hi","sound":"default"}}' --cert "/path/com.socialgym.pem":"" -H "apns-topic:com.socialgym" --http2 https://api.development.push.apple.com/3/device/97c5f678f32bc12578b3f806214e016e1d1918c5ecd15cbd02e9f7ca03c9ea06`


But I am getting the same response:
`{"reason":"DeviceTokenNotForTopic"}`


I'm getting crazy :(

**Comment by vtellez** [comment]
Hello again @macdonst 

I also try send the push notification through the "old way" using binary api over PHP:

```

 public static function sendToIOS($devices, $msg, $title) {
        $apnsPort = 2195;
        $apnsPass = 'CERT-PEM-PASSWORD';
        $token = '7bfa531b9ab01e2e41cb38e1ac233a23b3b9b3fb40ca1ace56556f2557476e25';
        $message = '{"aps":{"alert":"Hi!"}}';
        $app_bundle_id = 'com.socialgym';
        $url = "https://api.development.push.apple.com:443/3/device/$token";
        $cert = '/path/to/com.socialgym-dev.pem';

        $payload['aps'] = array('alert' => $msg, 'badge' => 1, 'sound' => 'default');
        $output = json_encode($payload);

        foreach ( $devices as $token ) {
            $token = pack('H*', str_replace(' ', '', $token));
            $apnsMessage = chr(0).chr(0).chr(32).$token.chr(0).chr(strlen($output)).$output;

            $streamContext = stream_context_create();
            stream_context_set_option($streamContext, 'ssl', 'local_cert', $apnsCert);
            stream_context_set_option($streamContext, 'ssl', 'passphrase', $apnsPass);

            $apns = stream_socket_client('ssl://'.$apnsHost.':'.$apnsPort, $error, $errorString, 2, STREAM_CLIENT_CONNECT, $streamContext);
            $result[] = fwrite($apns, $apnsMessage);
        }
        fclose($apns);
        return $result;
}
```


But I get code 136 from APNs server.

Reading the documentation I see this:

1 - 	Processing error
3 -   Missing topic
6 -   Invalid topic size

**Comment by vtellez** [comment]
@macdonst 

I also trying ApnsPHP (https://github.com/immobiliare/ApnsPHP) to send the push notification with two devices token differents:

The first one is obtained with phonegap-push-plugin from my iPhone, it's seems that it is incorrect device token. The second one is obtained from a code example from ApnsPHP, it's seem to be ok.

I am using a basic code example:

```
    $devices` = array(
      '08b38a49f70fa0639fee1e9d1b4890f8599ecbe7feb571b763242d4fef1b25e0',
      '1e82db91c7ceddd72bf33d74ae052ac9c84a065b35148ac401388843106a7485',
      );

    $push = new ApnsPHP_Push(
      ApnsPHP_Abstract::ENVIRONMENT_SANDBOX,
      self::$APN_CERT_PATH
      );

    $push->setProviderCertificatePassphrase(self::$APN_CERT_PASS);
    $push->setRootCertificationAuthority(self::$APN_CERT_PATH);
    $push->connect();
    $cont = 1;
    foreach ( $devices as $token ) {
      $message = new ApnsPHP_Message($token);
      $message->setCustomIdentifier("Message-Badge$cont");
      $message->setBadge(1);
      $message->setText('Hello APNs-enabled device!');
      $message->setSound();
      $message->setExpiry(30);
      $push->add($message);
      $cont++;
    }

    $push->send();
    $push->disconnect();
    $aErrorQueue = $push->getErrors();
    if (!empty($aErrorQueue)) {
      var_dump($aErrorQueue);
      echo "<br><br>";
    }
  }
```


This is the response from the script:

```
Wed, 25 May 2016 10:38:28 +0200 ApnsPHP[1073]: INFO: Trying tls://gateway.sandbox.push.apple.com:2195... 

Wed, 25 May 2016 10:38:28 +0200 ApnsPHP[1073]: INFO: Connected to tls://gateway.sandbox.push.apple.com:2195. Wed, 25 May 2016 10:38:28 +0200 ApnsPHP[1073]: INFO: Sending messages queue, run #1: 2 message(s) left in queue. 

Wed, 25 May 2016 10:38:28 +0200 ApnsPHP[1073]: STATUS: Sending message ID 1 [custom identifier: Message-Badge1] (1/3): 119 bytes. Wed, 25 May 2016 10:38:28 +0200 ApnsPHP[1073]: STATUS: Sending message ID 2 [custom identifier: Message-Badge2] (1/3): 119 bytes. 

Wed, 25 May 2016 10:38:28 +0200 ApnsPHP[1073]: ERROR: Unable to send message ID 1: Invalid token (8). Wed, 25 May 2016 10:38:28 +0200 ApnsPHP[1073]: INFO: Disconnected. 

Wed, 25 May 2016 10:38:28 +0200 ApnsPHP[1073]: INFO: Trying tls://gateway.sandbox.push.apple.com:2195... Wed, 25 May 2016 10:38:29 +0200 ApnsPHP[1073]: INFO: Connected to tls://gateway.sandbox.push.apple.com:2195. 

Wed, 25 May 2016 10:38:29 +0200 ApnsPHP[1073]: INFO: Sending messages queue, run #2: 2 message(s) left in queue. Wed, 25 May 2016 10:38:29 +0200 ApnsPHP[1073]: WARNING: Message ID 1 [custom identifier: Message-Badge1] has an unrecoverable error (8), removing from queue without retrying... 

Wed, 25 May 2016 10:38:29 +0200 ApnsPHP[1073]: STATUS: Sending message ID 2 [custom identifier: Message-Badge2] (1/3): 119 bytes. Wed, 25 May 2016 10:38:30 +0200 ApnsPHP[1073]: INFO: Disconnected.


array (size=1)
  1 => 
    array (size=3)
      'MESSAGE' => 
        object(ApnsPHP_Message)[845]
          protected '_bAutoAdjustLongPayload' => boolean true
          protected '_aDeviceTokens' => 
            array (size=1)
              0 => string '08b38a49f70fa0639fee1e9d1b4890f8599ecbe7feb571b763242d4fef1b25e0' (length=64)
          protected '_sText' => string 'Hello APNs-enabled device!' (length=26)
          protected '_nBadge' => int 1
          protected '_sSound' => string 'default' (length=7)
          protected '_sCategory' => null
          protected '_bContentAvailable' => null
          protected '_aCustomProperties' => null
          protected '_nExpiryValue' => int 30
          protected '_mCustomIdentifier' => string 'Message-Badge1' (length=14)
      'BINARY_NOTIFICATION' => string '���WEd�� ��I��c���H��Y�����q�c$-O�%��J{"aps":{"alert":"Hello APNs-enabled device!","badge":1,"sound":"default"}}' (length=119)
      'ERRORS' => 
        array (size=1)
          0 => 
            array (size=5)
              'command' => int 8
              'statusCode' => int 8
              'identifier' => int 1
              'time' => int 1464165508
              'statusMessage' => string 'Invalid token' (length=13)

```

I cant see the problem with the first token. Of course, I am not receiving nothing into my device.

Can anybody help me please?

Regards

**Comment by vtellez** [comment]
Just another test, this time using pusher app (https://github.com/noodlewerk/NWPusher).

Using a device token obtain with phonegap-push-plugin:

![screen shot 2016-05-25 at 11 32 46](https://cloud.githubusercontent.com/assets/1079706/15535200/9c52c62e-226c-11e6-8168-6db2b6f59527.png)


Using a device token taken from ApnsPHP source code exmaples:

![screen shot 2016-05-25 at 11 32 55](https://cloud.githubusercontent.com/assets/1079706/15535217/af0d0504-226c-11e6-81bd-d5dedd0138b0.png)



Maybe I am doing something wrong when I try to obtain the device token using the plugin?

```
var push = PushNotification.init({
            android: {
                senderID: "768274361309"
            },
            ios: {
                alert: "true",
                badge: "true",
                sound: "true",
            },
        });

        push.on('registration', function(data) {
            localStorage.setItem('deviceid',data.registrationId);
            alert('Dispositivo registrado: '+ localStorage.getItem('deviceid'));
        });

        push.on('notification', function(data) {
            App.alert(data.message);
        });

        push.on('error', function(e) {
            alert(e.message);
        });

```

**Comment by macdonst** [comment]
@vtellez somewhere in your chain there is a mis-match on the bundle ID. It seems like you are using PGB so make sure the certificate you uploaded to the service is a development service and it is of the ID "com.socialgym".

**Comment by vtellez** [comment]
@macdonst You are right! I don't know the reason, but I delete all the certificates in itunnes connect and create them from scratch and upload again to PGB.

Now I am able to receive push notification on iOS. 

I really really want to thank you for your time, project and response.

THANK YOU VERY MUCH!
