### ISSUE TITLE
Plugin Error - App not Installed

### ISSUE THREAD

**Issue by eliea85** [phonegap/phonegap-plugin-push#922]
### Expected Behaviour
Application Get installed

### Actual Behaviour
App not installed

### Reproduce Scenario (including but not limited to)
When trying to install an android app that reference the Phonegap-plugin-push version 1.6.3, and i already have an application that use the plugin "com.phonegap.plugins.pushplugin". the result is App not installed.

If i remove the other application, the app get installed successfully
How we could fix that ?

**Comment by macdonst** [comment]
@eliea85 This really isn't enough info for me to debug. What is the error message when you try to install? How do you try to install? Please see issue guidelines.

**Comment by eliea85** [comment]
My mistake,
I just changed the widget id in the Config.xml and it works.
