### ISSUE TITLE
App name shows instead of title on iOS banner.

### ISSUE THREAD

**Issue by lavarith** [phonegap/phonegap-plugin-push#923]
### Expected Behaviour
When I send a notification, the banner shows my app's name instead of showing the title of the notification. The title appears properly in the notification drawer. I'd like both of these experiences to be the same. I don't know if this is a bug or if I'm misunderstanding something.

It works as expected on Android.

### Reproduce Scenario (including but not limited to)
I use GCM to send notifications to both Android and iOS.

The following is a snippet of the php script that processes the notification:

```
$data = array('title' => $title
              , 'body' => $message
              , 'vibrate' => 1
              , 'sound' => 1
              , 'notId' => $notid 
              , 'additionalData' => $additionalData // include action and details here
             );
```
```
    // Set GCM post variables (device IDs and push payload)     
    $post = array(  'to'            => $ids,
                    'priority'      => "high",
                    'notification'  => $data,
                    );

    // Set CURL request headers (authentication and type)
    $headers = array(   'Authorization: key=' . $apiKey,
                        'Content-Type: application/json'
                    );
```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Using iOS 9.3.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPhone 5

#### Cordova CLI version and cordova platform version
I use cordova 6.0.0 via adobe's phonegap build.

#### Plugin version
Using 1.6.3 of this plugin

Let me know if you need any other information.

Screenshots (The name of the app is Launch in this case):
![img_0003](https://cloud.githubusercontent.com/assets/3874034/15502643/542c5f2a-2183-11e6-8fe8-cbdabb8990ee.PNG)
![img_0004](https://cloud.githubusercontent.com/assets/3874034/15502644/542ddc1a-2183-11e6-9010-09d6f3060f51.PNG)

**Comment by macdonst** [comment]
@lavarith that's the way that iOS works, nothing we can do to change it.
