### ISSUE TITLE
Android inbox style: discarding notifications actually does not discard them

### ISSUE THREAD

**Issue by ebarault** [phonegap/phonegap-plugin-push#924]
### Expected Behaviour
using android inbox style, the notifications stacks correcly. Though when user chooses to discard the notifications (left/right swipe, discard button), the next notification will recall all the stacked notifications: it seems they are just hidden, not discarded

### Actual Behaviour
discarding notifications should actually discard the notifications, not just hide them

#### Steps to Reproduce 

1. send two notifications using payloads of the like:
```
        "android": {
            "data": {
               "title": "myTitle",
               "message": "myMessage",
               "style": "inbox",
               "summaryText": "you have %n% notifications"
            }
        }
```

2. discard the notifications in the notification panel
3. send one more notification (same template)
result: the 3 notifications are shown, not just the last one

what is required to really 'consume' the notifications is to actually open the notification

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4 & Android 6.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
HTC One, Samsung GS6

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.1.1
    cordova platform version android           5.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.6.3

#### Sample Push Data Payload
as in the steps to reproduce

#### Sample Code that illustrates the problem
no specific code

**Comment by fredgalvao** [comment]
That's not how any app I know works.

In pretty much every app I could find, the following is the way it works on stacked notifications:

### 1. You receive message "bacon 1". The notification looks like this:
```
bacon 1
```

### 2. You receive message "bacon 2". The notification looks like this now:
#### Collapsed
```
2 new messages
```
#### Expanded
```
bacon 1
bacon 2
```

### 3. If at this point I discard the notification and receive a new message "bacon 3", it'll look like this:
#### Collapsed
```
3 new messages
```
#### Expanded
```
bacon 1
bacon 2
bacon 3
```


### Conclusion
**\<personal-experience-and-opinion\>**
Discarding notifications using operating system level interactions (swipe left/right, embedded discard button, etc) does **not** mean `treat this notification as handled`, it means `postpone this notification's handling to a future unspecified event`.
**\<\/personal-experience-and-opinion\>**

**Comment by ebarault** [comment]
thanks for sharing this @fredgalvao. I was taking the 'basic notification' stand point (i.e. no inbox stacking). For the basic ones, once you swipe to 'postpone/discard', from the user point of view what it sees is that the next notification won't recall the previous one.
Behind the scene it's obvious since the new one replaces the previous one.

As far as inbox stacked notifications are concerned, i have a feeling that some apps then use a kind of hybrid looking notification style, using basic ones then. For example gmail i believe. You have the feeling mails are stacked and once discarded the notification, they won't bubble up again.

**Comment by macdonst** [comment]
As @fredgalvao mentioned this is working as intended.
