### ISSUE TITLE
Push Notification when app is in foreground?

### ISSUE THREAD

**Issue by omaismbakop** [phonegap/phonegap-plugin-push#925]
### Expected Behaviour
should receive notification when app in background and foreground
### Actual Behaviour
i am receiving notification when app in background but not when its in foreground
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

#### Logs taken while reproducing problem

I tested, push notification code is executing each time when app starts,  Code of initial function

         var push = PushNotification.init(
        { "android": {"senderID": "XXXXXXXXXXXXXXX"
                     },
          "ios": {"alert": "true", "badge": "true", "sound": "true"
                 } 
         
        });

    // checking if app already have regisrationID
    if (localStorage.getItem("push") === null) {
                localStorage.setItem("push", 1);
                
    
            push.on('registration', function(data) {
            console.log(data.registrationId);
            //app.alert(data.registrationId);

               //Ajax call to send registration id to server database 
                var postData = {senderid: data.registrationId};
                                         $.ajax({
                                          // cache: false,
                                          type: 'POST',
                                          url: "XXXXXXXXXXXXXX.php",
                                          //beforeSend: function() { },
                                          // complete: function(){  },
                                          //dataType: "json",
                                          data: postData,
                                          success: function(data) {
                                             // PROCESS DATA HERE
                                              //app.alert(JSON.stringify(data));

                                          },
                                          error: function(data) {
                                             //PROCESS HERE FOR FAILURE
                                             // return View.Modal.openNotification("Error!"); //console.log(data);
                                             app.alert("Network not found");

                                          }
                                      });
            });
    }

            push.on('notification', function(data) {
            console.log(data.message);
            alert(data.title+" Message: " +data.message);
            data.title,
            data.sound,
            data.image,
            data.message
                // data.additionalData
            });

            push.on('error', function(e) {
            console.log(e.message);
            });

**Comment by jedofus** [comment]
to take your data notification in foreground and see your alert ,you can call the method finish() on your function  push.on('notification', function(data). Like that : 

  push.on('notification', function(data) {
    push.finish( function() {
          console.log(data.message);
          alert(data.title+" Message: " +data.message);
          data.title,
          data.sound,
          data.image,
          data.message
            // data.additionalData
   }
});

**Comment by omaismbakop** [comment]
i can see alert when its in foreground, but only alert. no sound, no vibration, no alert

**Comment by macdonst** [comment]
@omaismbakop what you are describing is the way the plugin should work. When the app is in the foreground it is up to you to display a dialog, play a sound or vibrate the device.

**Comment by omaismbakop** [comment]
i make it worked by setting forceShow true like this

`var push = PushNotification.init(
        { "android": {"senderID": "533867441597", "forceShow": "true"
                     },
          "ios": {"alert": "true", "badge": "true", "sound": "true"
                 } 
         
        });`

**Comment by leizard** [comment]
Hi @omaismbakop , how about ios ?

**Comment by chirag0110** [comment]
Yes, "forceShow": "true" is work for android. What about IOS?

How can i get notification in forground IOS app.

**Comment by Dineshrajaa** [comment]
is there any option for force showing notification in iOS app?

**Comment by lovelyelfpop** [comment]
I found [EBForeNotification](https://github.com/pikacode/EBForeNotification), it can show the Banners and Sounds as the same as the system notifications on foreground in ios.
Can someone integrate EBForeNotification into this plugin?
