### ISSUE TITLE
Phonegap build won't build on 1.6.4

### ISSUE THREAD

**Issue by chrisschaub** [phonegap/phonegap-plugin-push#928]
So a build that worked yesterday, same source code, does not work today.

Could not find com.android.support:support-v4:23.4.0

Build Date: 2016-05-25 01:46:57 +0000

FAILURE: Build failed with an exception.

    What went wrong:
    A problem occurred configuring root project 'project'.

        Could not resolve all dependencies for configuration ':_debugCompile'.
        Could not find com.android.support:support-v4:23.4.0.
        Searched in the following locations:
        https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
        https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
        file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
        file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
        file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
        file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
        Required by:
        :project:unspecified
        Could not find com.android.support:support-v4:23.4.0.
        Searched in the following locations:
        https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
        https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
        file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
        file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
        file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
        file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
        Required by:
        :project:unspecified > com.android.support:support-v13:23.2.1
        Could not find com.android.support:support-v4:23.4.0.
        Searched in the following locations:
        https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
        https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
        file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
        file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
        file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
        file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
        Required by:
        :project:unspecified > com.google.android.gms:play-services-analytics:8.4.0 > com.google.android.gms:play-services-basement:8.4.0

    Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Version 1.6.3 builds just fine.

**Comment by macdonst** [comment]
@chrisschaub I will ask the PGB team to install 23.4.0 on the build services.

**Comment by macdonst** [comment]
@chrisschaub build guys are going to put 23 onto servers today.

**Comment by chrisschaub** [comment]
Thanks

On Wednesday, May 25, 2016, Simon MacDonald <notifications@github.com>
wrote:

> @chrisschaub <https://github.com/chrisschaub> build guys are going to put
> 23 onto servers today.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-plugin-push/issues/928#issuecomment-221579194>
>


-- 
Christopher Schaub
http://chris.schaub.com

**Comment by stileinverso** [comment]
Same problem for me... I'll wait patiently :-)

**Comment by chrisschaub** [comment]
use spec="1.6.3" in your plugin line in config.xml

On Thursday, May 26, 2016, stileinverso <notifications@github.com> wrote:

> Same problem for me... I'll wait patiently :-)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-plugin-push/issues/928#issuecomment-221784947>
>


-- 
Christopher Schaub
http://chris.schaub.com

**Comment by stileinverso** [comment]
Perfect... it works! 
Thanks!

**Comment by macdonst** [comment]
@chrisschaub PGB was updated please try rebuilding with 1.6.4.

**Comment by stileinverso** [comment]
Now form me it works properly also with 1.6.4
