### ISSUE TITLE
Android build fail with facebook4 plugin

### ISSUE THREAD

**Issue by braianj** [phonegap/phonegap-plugin-push#932]
I'm performing an android build but it's returning an error. It works as a charm in iOS.
If I remove facebook plugin or push plugin the build works, but If both are installed at the same time, it fail.

Some information: 
> $ cordova -v
> 6.1.1

> $  cordova platform version android
> Installed platforms:
> android 5.1.1
> ios 4.1.1

> $ cordova plugin ls
> cc.fovea.cordova.purchase 5.0.2 "Purchase"
> com.google.playservices 19.0.0 "Google Play Services for Android"
> cordova-plugin-app-version 0.1.8 "AppVersion"
> cordova-plugin-calendar 4.4.7 "Calendar"
> cordova-plugin-camera 2.2.0 "Camera"
> cordova-plugin-compat 1.0.0 "Compat"
> cordova-plugin-device 1.0.1 "Device"
> cordova-plugin-extension 1.2.2 "Cordova Plugin Extension"
> cordova-plugin-facebook4 1.7.1 "Facebook Connect"
> cordova-plugin-file 4.2.0 "File"
> cordova-plugin-file-transfer 1.5.1 "File Transfer"
> cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
> cordova-plugin-network-information 1.2.1 "Network Information"
> cordova-plugin-splashscreen 3.2.2 "Splashscreen"
> cordova-plugin-whitelist 1.2.2 "Whitelist"
> phonegap-plugin-push 1.6.4 "PushPlugin"

so when I make the build it return:

> :compileDebugSources UP-TO-DATE
> :transformClassesWithDexForDebug
> UNEXPECTED TOP-LEVEL EXCEPTION:
> com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;
> 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
> 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
> 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
> 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
> 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
> 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
> 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
> 	at com.android.dx.command.dexer.Main.run(Main.java:277)
> 	at com.android.dx.command.dexer.Main.main(Main.java:245)
> 	at com.android.dx.command.Main.main(Main.java:106)
> 
> 
>  FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':transformClassesWithDexForDebug'.
> > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 57.913 secs
> Error: Error code 1 for command: /project/platforms/android/gradlew with args: cdvBuildDebug,-b,/project/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true

**Comment by macdonst** [comment]
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#co-existing-with-facebook-plugin

**Comment by braianj** [comment]
@macdonst thanks for that as you can see there's installed cordova-plugin-facebook4 1.7.1 "Facebook Connect"

Thanks anyway

**Comment by macdonst** [comment]
@braianj well I can see there is a `cordova-plugin-facebook4 1.7.1 "Facebook Connect"` installed but I can't tell if that is using Judan's fork. You may have been using someone else repo.

What I think is the actual problem is you are including `com.google.playservices` as a plugin. That will duplicate the jar causing the `Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;` error. What requires that plugin because that is the old way of specifying Google Play dependencies.

**Comment by braianj** [comment]
And have you any solution on this?

**Comment by macdonst** [comment]
@braianj dude, you are not giving me much to go on here. I don't have your app code. Tell me why or what plugin requires com.google.playservices as a plugin and I can probably help. It may require sending a PR to another plugin author.

**Comment by macdonst** [comment]
@braianj did you get this resolved? Please see my last comment as I feel it is another plugin causing the problem but I'm happy to help fix that one.

**Comment by braianj** [comment]
@macdonst well thank you very much for your interest. 
I'm digging into it, because i'm performing an update of this old app and everything is broken in android, ios work just find and already submitted.
So I do a plugin rm for the playservice, just to see if this plugin is attached to another one, and not. 
Now the build works but the content-security-policy with the whitelist plugin isn't. Can make any ajax call.
So It's I think I need to clarify  a bit more the app before go ahead with this issue.
I'm positive that playservice with facebook4 or playservice with push-plugin works just fine, but all those 3 together not.
Thank you for being there :)

**Comment by macdonst** [comment]
@braianj Did you figure anything out?

**Comment by macdonst** [comment]
Closing, inactivity
