### ISSUE TITLE
Latest plugin not available on build.phonegap.com

### ISSUE THREAD

**Issue by arathikundapur** [phonegap/phonegap-plugin-push#934]
### Expected Behaviour
Latest Plugin to be available in build.phonegap.com
### Actual Behaviour
We have version 1.4.2 which has a bug which prevents multiple apps using this plugin to be installed on the same android device

**Comment by macdonst** [comment]
@arathikundapur what do you mean exactly? Tell me what the problem is? I know people were building with 1.6.4 on PGB yesterday.

**Comment by arathikundapur** [comment]
ok... my bad. Now using npm to get the latest version and it works fine. Thanks.
