### ISSUE TITLE
iOS lot of warnings 

### ISSUE THREAD

**Issue by jffs** [phonegap/phonegap-plugin-push#935]
after i build my app, I get this warnings: 

PushPlugin.m

- PushPlugin.m:169:9:

 'UIRemoteNotificationType' is deprecated: first deprecated in iOS 8.0 - Use UIUserNotificationType for user notifications and registerForRemoteNotifications for receiving remote notifications instead.

- PushPlugin.m:169:54:

 'UIRemoteNotificationTypeNone' is deprecated: first deprecated in iOS 8.0 - Use UIUserNotificationType for user notifications and registerForRemoteNotifications for receiving remote notifications instead.

- PushPlugin.m:178:34:

 'UIRemoteNotificationTypeBadge' is deprecated: first deprecated in iOS 8.0 - Use UIUserNotificationType for user notifications and registerForRemoteNotifications for receiving remote notifications instead.

- PushPlugin.m:186:34:

 'UIRemoteNotificationTypeSound' is deprecated: first deprecated in iOS 8.0 - Use UIUserNotificationType for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
And many others "UIRemoteNotificationType" warnings. Also I get this one

- PushPlugin.m:535:42:

 Undeclared selector 'userHasRemoteNotificationsEnabled'

- PushPlugin.m:536:49:

 Undeclared selector 'userHasRemoteNotificationsEnabled'

- /Users/juampi/Desktop/LIDI/FacInfoApp/Frontend/platforms/ios/Informática UNLP/Plugins/phonegap-plugin-push/

PushPlugin.m:536:17: Incompatible pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from 'id'

- /Users/juampi/Desktop/LIDI/FacInfoApp/Frontend/platforms/ios/Informática UNLP/Plugins/phonegap-plugin-push/

PushPlugin.m:579:24: Unused variable 'app'

Object file (/Users/juampi/Desktop/LIDI/FacInfoApp/Frontend/platforms/ios/Informática UNLP/Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(Descriptor.pb.o)) was built for newer iOS version (8.3) than being linked (8.0)

(null): Object file (/Users/juampi/Desktop/LIDI/FacInfoApp/Frontend/platforms/ios/Informática UNLP/Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(ObjectivecDescriptor.pb.o)) was built for newer iOS version (8.3) than being linked (8.0)

(null): Object file (/Users/juampi/Desktop/LIDI/FacInfoApp/Frontend/platforms/ios/Informática UNLP/Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(PBArray.o)) was built for newer iOS version (8.3) than being linked (8.0)

(null): Object file (/Users/juampi/Desktop/LIDI/FacInfoApp/Frontend/platforms/ios/Informática UNLP/Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(PBCodedInputStream.o)) was built for newer iOS version (8.3) than being linked (8.0)

(null): Object file (/Users/juampi/Desktop/LIDI/FacInfoApp/Frontend/platforms/ios/Informática UNLP/Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(PBDescriptor.o)) was built for newer iOS version (8.3) than being linked (8.0)

(null): Object file (/Users/juampi/Desktop/LIDI/FacInfoApp/Frontend/platforms/ios/Informática UNLP/Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(PBUtilities.o)) was built for newer iOS version (8.3) than being linked (8.0)

(null): Object file (/Users/juampi/Desktop/LIDI/FacInfoApp/Frontend/platforms/ios/Informática UNLP/Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(PBExtensionField.o)) was built for newer iOS version (8.3) than being linked (8.0)

(null): Object file (/Users/juampi/Desktop/LIDI/FacInfoApp/Frontend/platforms/ios/Informática UNLP/Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(PBExtensionRegistry.o)) was built for newer iOS version (8.3) than being linked (8.0)

(null): Object file (/Users/juampi/Desktop/LIDI/FacInfoApp/Frontend/platforms/ios/Informática UNLP/Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(PBField.o)) was built for newer iOS version (8.3) than being linked (8.0)

(null): Object file (/Users/juampi/Desktop/LIDI/FacInfoApp/Frontend/platforms/ios/Informática UNLP/Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(PBGeneratedMessage.o)) was built for newer iOS version (8.3) than being linked (8.0)

(null): Object file (/Users/juampi/Desktop/LIDI/FacInfoApp/Frontend/platforms/ios/Informática UNLP/Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(PBRootObject.o)) was built for newer iOS version (8.3) than being linked (8.0)

(null): Object file (/Users/juampi/Desktop/LIDI/FacInfoApp/Frontend/platforms/ios/Informática UNLP/Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(PBCodedOutputStream.o)) was built for newer iOS version (8.3) than being linked (8.0)

(null): Object file (/Users/juampi/Desktop/LIDI/FacInfoApp/Frontend/platforms/ios/Informática UNLP/Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(PBUnknownFieldSet.o)) was built for newer iOS version (8.3) than being linked (8.0)

(null): Object file (/Users/juampi/Desktop/LIDI/FacInfoApp/Frontend/platforms/ios/Informática UNLP/Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(PBWireFormat.o)) was built for newer iOS version (8.3) than being linked (8.0)

(null): warning: /var/folders/f4/lg23spf10fv19twg_lmrp8zm0045gx/C/org.llvm.clang.136701/ModuleCache/1JNUDWCYE5LC7/Foundation-A3SOD99KJ0S9.pcm: No such file or directory
(null): warning: 
/var/folders/f4/lg23spf10fv19twg_lmrp8zm0045gx/C/org.llvm.clang.136701/ModuleCache/1JNUDWCYE5LC7/UIKit-2LM3EQU7VVY4O.pcm: No such file or directory
(null): warning: /var/folders/f4/lg23spf10fv19twg_lmrp8zm0045gx/C/org.llvm.clang.136701/ModuleCache/1JNUDWCYE5LC7/Darwin-MI6WZSG1PNOM.pcm: No such file or directory
(null): warning: /var/folders/f4/lg23spf10fv19twg_lmrp8zm0045gx/C/org.llvm.clang.136701/ModuleCache/1JNUDWCYE5LC7/SystemConfiguration-2O070L5BFB5B1.pcm: No such file or directory
(null): warning: /var/folders/f4/lg23spf10fv19twg_lmrp8zm0045gx/C/org.llvm.clang.136701/ModuleCache/3ITUVTFWQXGWD/Foundation-A3SOD99KJ0S9.pcm: No such file or directory
(null): warning: /var/folders/f4/lg23spf10fv19twg_lmrp8zm0045gx/C/org.llvm.clang.136701/ModuleCache/3ITUVTFWQXGWD/UIKit-2LM3EQU7VVY4O.pcm: No such file or directory
(null): warning: /var/folders/f4/lg23spf10fv19twg_lmrp8zm0045gx/C/org.llvm.clang.136701/ModuleCache/3ITUVTFWQXGWD/Darwin-MI6WZSG1PNOM.pcm: No such file or directory

How could I solved it? the build was success but the app crashed. 
My system  info is:
Your system information:

Cordova CLI: 6.1.1
Ionic Version: 1.3.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.1.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by macdonst** [comment]
@jffs the warnings are fine, the crash is not. What are the circumstances of the crash.

**Comment by jffs** [comment]
my fault, it was another thing.
