### ISSUE TITLE
What is the difference between this plugin and the cordova-plugin-push-notification?

### ISSUE THREAD

**Issue by iori57** [phonegap/phonegap-plugin-push#936]
Sorry for raising an issue while I actually have a question.

What is the difference between phonegap-plugin-push and [cordova-plugin-push-notification](https://github.com/zckrs/cordova-plugin-push-notification/) ? 

Previously our project was using cordova-plugin-push-notification, and I am currently to upgrading all plugins in our project to the latest version.. after upgrading it to the latest version, while searching the forums I accidentally found this plugin and wonder if we should move our project to this plugin instead. Is that plugin deprecated and replaced by this plugin? That plugin haven't been updating since one year ago.

I also tried to google this but couldn't find anything that answers my question.

Thanks!

**Comment by macdonst** [comment]
@iori57 this plugin is the one that the PhoneGap team at Adobe officially supports. I can't really comment on cordova-plugin-push-notification as I don't know the maintainer. It looks like it was forked off of the now deprecated https://github.com/phonegap-build/PushPlugin.git repo. The main benefits of this plugin are a) it's being maintained and b) it has a consistent API.
