### ISSUE TITLE
Testing on iOS without an account [Question]

### ISSUE THREAD

**Issue by jffs** [phonegap/phonegap-plugin-push#937]
Hi, i was wondering if there is any way to test the plugin on iOS without having a developer account. 

when i build the app i get this error 
Registration to GCM failed with error: The operation couldn’t be completed. (com.google.HTTPStatus error 401.)
and I readed something about certificates but the only way to get with them was paying for an account in Apple.

**Comment by macdonst** [comment]
@jffs yes, I recently got things setup so you can use the PhoneGap Developer app to do testing. See my workshop on the topic:

http://macdonst.github.io/push-workshop-eu/

**Comment by jffs** [comment]
And with Ionic?

**Comment by macdonst** [comment]
Ionic has a different way of testing, check their docs.
