### ISSUE TITLE
Android, example doesn't work when it goes into background

### ISSUE THREAD

**Issue by tyrtok** [phonegap/phonegap-plugin-push#94]
The example works when compiled and run using Cordova. However, once the application goes into background, it doesn't notify user in terms of notification. However, response from GCM states 'OK'. 

anyone idea how to make it work on android?

**Comment by BigBirdRook** [comment]
Send test message to GCM in this format:
{
"registration_ids": ["...your_reg_id..."],
"data" : {"message" : "Test message"}
}

It helped for me...

**Comment by macdonst** [comment]
@tyrtok when the app is in the background do you get the notification in the notification shader?

**Comment by tyrtok** [comment]
Problem solved by changing the json data set sent to GCM.
