### ISSUE TITLE
 Problem with ios 9.3.2

### ISSUE THREAD

**Issue by jakk2** [phonegap/phonegap-plugin-push#943]
Recording does not work with ios 9.3.2

**Comment by macdonst** [comment]
@jakk2 what do you mean by "recording"?

**Comment by jakk2** [comment]
I do not receive tocken device .
Before you upgrade xcode iosSdk and everything worked .
Also when I install the app you do not see the popup to accept push notifications.
Help meeee!

**Comment by jakk2** [comment]
news?

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

That being said, I did attempt to recreate your problem but I can successfully get a registration event and notification evens on my iPad running iOS 9.3.2.
