### ISSUE TITLE
Android Notifications Failing: Documentation Required

### ISSUE THREAD

**Issue by nickos333** [phonegap/phonegap-plugin-push#944]
### Expected Behaviour

Fantastic plugin. I think it needs some documentation on setting the correct Content-Security-Policy to ensure plugins are received on Android devices. I grappled for several days trying to get notifications to arrive on various Android devices (emulators and physical devices) before realising that the absence of a correct Content-Security-Policy meta tag in my index.html file was the culprit.

Using the spec provided by an on-line example (shown below) caused notifications to arrive again on Android devices:

```
<meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline'; style-src 'self' 'unsafe-inline'; media-src *" />
```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android / Lollipop and Marshmallow

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Various

#### Cordova CLI version and cordova platform version

    cordova #6.0.0
    cordova platform version android                     #5.1.1

**Comment by macdonst** [comment]
@nickos333 but how is this different from any other Cordova Android app?

**Comment by fredgalvao** [comment]
Exactly. Cordova documentation specifies that without some kind of configuration of the whitelist plugin/mechanism, no internet connection will ever be allowed by the app's bridge.

**Comment by macdonst** [comment]
I'm going to close this as out of scope for the plugin. Without a CSP everything fails.
