### ISSUE TITLE
IOS, openening one notification cause clearing all other notifications

### ISSUE THREAD

**Issue by gvolkan** [phonegap/phonegap-plugin-push#945]
### Expected Behaviour
I send more than one notificaiton to my device and then drop on my screen. after that i clicked one of them, open my cordova app and catch my clicked notification. its good but other notifications are disappeared?? and then cant be caught by plugin anymore. 

if we got 3 notification on lock screen, can we get them like array??

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
