### ISSUE TITLE
App does not receive notification through the GCM in iOS

### ISSUE THREAD

**Issue by raphaguasta** [phonegap/phonegap-plugin-push#946]
Hi guys,

App does not receive notification through the GCM in iOS.

I did tests in development, and it works. In production the app register the device id in my database, but not receive the nofitication.

My registration in the app:

```
var push = PushNotification.init({
        "android": {
          "senderID": 'XXXXX'
        },
        "ios": {
          "senderID": 'XXXXX',
          "alert": "true",
          "badge": "true",
          "sound": "true",
          "gcmSandbox":"true"
      }
    });
```

I'm sending the apiKey correctly, and my array to the GCM service is:

```
'registration_ids' => $devices,
            'priority' => 'high',
            'notification' => array(
                'title' => $title,
                'body' => $message,
                'priority' => 'high',
                'content-available' => '1'
            )
```

But when i send the message, i receive the result: 

> {"multicast_id":XXXX,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"NotRegistered"}]}

I'm trying for a long time, and I can not find the problem.

Can anyone help?

**Comment by macdonst** [comment]
@raphaguasta Usually this is an issue with development vs production certificates. If you try to push to production but the app is registered as development or vice versa.

What does your registration ID look like?

**Comment by ngystvn90** [comment]
Hi!

How does your server side code look? I have a problem with the registrationID, it is not built only with hexadecimal characters, so the pack('H*', $deviceToken) returns lots of warnings, notification doesn't arrive...

**Comment by Ebineshwar** [comment]
Hey 

I have the same issue...But in my case it shows success but the message is not delivered...

**Comment by NilsonUehara** [comment]
@Ebineshwar My case is the same as yours. I send the message through the firebase, which responds to SUCCESS but the notification does not reach IOS.
Have you solved it yet?

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
