### ISSUE TITLE
Notification in foreground dissapeared

### ISSUE THREAD

**Issue by Davids89** [phonegap/phonegap-plugin-push#948]
### Expected Behaviour
I have a project with a android platform target 22, wich receive the notification in foreground in the drawer. 
### Actual Behaviour
Besides, I am doing test in other folder with another platform, wich is 23, and in this project the app not show the notification in the drawer being in foreground.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
In project 1, in the project.properties of platforms/android 

`target=android-22
android.library.reference.1=CordovaLib
cordova.system.library.1=com.android.support:support-v4:+
cordova.gradle.include.1=phonegap-plugin-push/joinuptaxi908966-push.gradle
cordova.system.library.2=com.android.support:support-v13:23+
cordova.system.library.3=com.google.android.gms:play-services-gcm:+`

In project 2

`target=android-23
android.library.reference.1=CordovaLib
cordova.system.library.1=com.android.support:support-v13:23+
cordova.system.library.2=com.google.android.gms:play-services-gcm:+`
#### Cordova CLI version and cordova platform version

    cordova --version                                   6.1.1
    cordova platform version android          5.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push  1.6.4

Can I select the platform target when I run "ionic platform add android"?

**Comment by Davids89** [comment]
I resolved it with #925 but in iOS I have the same problem

**Comment by macdonst** [comment]
@Davids89 sorry, are you asking for a way to show the push notification in the notification center when the app is in the foreground on iOS?

**Comment by Davids89** [comment]
Yes, I am

**Comment by macdonst** [comment]
@Davids89 right, that is out of scope for this plugin. If the app is in the foreground you get the notification event with all the data so it is up to you to display UI. You can't actually show a notification in the notification shade if the app is in the foreground. iOS doesn't allow you to do this. 

I'm going to close this issue as the original question is answered.
