### ISSUE TITLE
Can't install plugin on iOS

### ISSUE THREAD

**Issue by robinchesterman** [phonegap/phonegap-plugin-push#950]
I'm using Tools for Apache Cordova (taca) on a Windows machine and remotebuild on a cloud mac to build my Cordova app for iOS. For some reason, the push plugin never gets installed. I have other plugins e.g. cordova-plugin-device and they are ok.

cordova 6.2.0
cordova-ios 4.1.1
phonegap-plugin-push 1.6.4
taco 1.2.1

On the remote machine, in the build folder:

builds/{number}/cordovaApp/platforms/ios/MyApp/Plugins

There are folders for the other plugins, but not the push plugin.

I can see a push plugin folder here:

builds/{number}/cordovaApp/plugins/phonegap-plugin-push

**Comment by tony--** [comment]
I have not tested, but I wonder if this might be related to this note from [INSTALLATION.md](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md)?

> Note: You need to specify the SENDER_ID variable in your config.xml if you plan on installing/restoring plugins using the prepare method. The prepare method will skip installing the plugin otherwise.
```
<plugin name="phonegap-plugin-push" spec="1.6.0">
    <variable name="SENDER_ID" value="XXXXXXX" />
</plugin>
```

**Comment by scriby** [comment]
That resolved the issue for me. I had "param" instead of variable in the config file. I guess that changed at some point...

**Comment by macdonst** [comment]
Use `param` on PGB.
