### ISSUE TITLE
One of your plugins requires a parameter: SENDER_ID

### ISSUE THREAD

**Issue by nickwebha** [phonegap/phonegap-plugin-push#951]
PhoneGap Build, while trying to build the Android app, is throwing back the error "_One of your plugins requires a parameter: SENDER_ID_". However I have included
```
<gap:plugin name="phonegap-plugin-push" source="npm" spec="~1.6.2">
 <variable name="SENDER_ID" value="0123456789" />
</gap:plugin>
```
in the config.xml.

I am using plugin version 1.6.2.

**Comment by macdonst** [comment]
Duplicate of #711
