### ISSUE TITLE
Notification disappears in iOS when app is in foreground

### ISSUE THREAD

**Issue by malwatte** [phonegap/phonegap-plugin-push#952]
In my app first screen is the login screen. I call PushNotification.init() if the login is successful. Push notifications works fine after user logged in. 
Lets assume user kills the app after login in and opens the app again and stays in the login screen. If a push sent at that time it is displayed in notification bar in Android because it is not handled. But in iOS notification is disappeared.

My question is, why notifications are not displayed in notification bar when the app is in foreground and plugin is not initialised? (Plugin is initialised and registered successfully before) In android notification is shown in notification bar(even when plugin is not initialised). But in iOS this is not the case.

Do we need to init the plugin every time app starts in iOS?

**Comment by macdonst** [comment]
@malwatte okay, so you should always call the init() method each time your app starts. You'll need to re-register your event listeners, etc. 

The behaviour you describe is the correct behaviour. When your app is in the foreground your `notification` event handler gets called and it is up to you to show any UI you want.

**Comment by malwatte** [comment]
ok. thank you. I'll init the plugin in app start.
