### ISSUE TITLE
How to request a user enable push notifications

### ISSUE THREAD

**Issue by lavarith** [phonegap/phonegap-plugin-push#953]
If a user has previously disabled notifications for an app on opening it for the first time, is there a way to programmatically ask them to enable notifications via the plugin or phonegap?

**Comment by dbpieter** [comment]
you could redirect the users to the settings page

**Comment by lavarith** [comment]
Awesome idea. Thanks.

**Comment by Oliv** [comment]
In my settings page, where the usre can enable push notifications, I periodically check if notifications are available, if not I added a link to the phone settings, this module https://github.com/Oliv/Cordova-open-native-settings did the trick (I hosted it because some push requests were pending)
