### ISSUE TITLE
Error while building app in phonegap build online.

### ISSUE THREAD

**Issue by kristiKeri** [phonegap/phonegap-plugin-push#954]
#### Cordova CLI version and cordova platform version

    cordova --version    cli-6.1.0
    cordova platform version android    5.1.1

#### Plugin version
 plugin version 1.6.4
   <plugin name="phonegap-plugin-push" source="npm">

#### Sample Code that illustrates the problem
Installing "phonegap-plugin-push" at "1.6.4" for android
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:compileDebugAidl
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:compileReleaseAidl
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareComAndroidSupportSupportV132340Library
:prepareComAndroidSupportSupportV42340Library
:prepareComGoogleAndroidGmsPlayServicesBase840Library
:prepareComGoogleAndroidGmsPlayServicesBasement840Library
:prepareComGoogleAndroidGmsPlayServicesGcm840Library
:prepareComGoogleAndroidGmsPlayServicesMeasurement840Library
:prepareProjectCordovaLibUnspecifiedDebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
AAPT: /project/res/drawable-xhdpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /project/res/drawable-mdpi/splash.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /project/res/drawable-mdpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /project/res/drawable-hdpi/splash.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /project/res/drawable-ldpi/splash.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /project/res/drawable-hdpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /project/res/drawable-xhdpi/splash.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
:processDebugManifest
:processDebugResources
:generateDebugSources
:compileDebugJavaWithJavac/project/src/com/adobe/phonegap/push/GCMIntentService.java:20: error: cannot find symbol
import android.support.v4.app.NotificationCompat.WearableExtender;
                                                ^
  symbol:   class WearableExtender
  location: class NotificationCompat
/project/src/com/adobe/phonegap/push/GCMIntentService.java:329: error: cannot find symbol
        mNotificationManager.notify(appName, notId, mBuilder.build());
                                                            ^
  symbol:   method build()
  location: variable mBuilder of type Builder
/project/src/com/adobe/phonegap/push/GCMIntentService.java:338: error: cannot find symbol
                ArrayList<NotificationCompat.Action> wActions = new ArrayList<NotificationCompat.Action>();
                                            ^
  symbol:   class Action
  location: class NotificationCompat
/project/src/com/adobe/phonegap/push/GCMIntentService.java:338: error: cannot find symbol
                ArrayList<NotificationCompat.Action> wActions = new ArrayList<NotificationCompat.Action>();
                                                                                                ^
  symbol:   class Action
  location: class NotificationCompat
/project/src/com/adobe/phonegap/push/GCMIntentService.java:361: error: cannot find symbol
                    NotificationCompat.Action wAction =
                                      ^
  symbol:   class Action
  location: class NotificationCompat
/project/src/com/adobe/phonegap/push/GCMIntentService.java:362: error: cannot find symbol
                    new NotificationCompat.Action.Builder(resources.getIdentifier(action.optString(ICON, ""), DRAWABLE, packageName),
                                          ^
  symbol:   class Action
  location: class NotificationCompat
/project/src/com/adobe/phonegap/push/GCMIntentService.java:366: error: cannot find symbol
                    mBuilder.addAction(resources.getIdentifier(action.optString(ICON, ""), DRAWABLE, packageName),
                            ^
  symbol:   method addAction(int,String,PendingIntent)
  location: variable mBuilder of type Builder
/project/src/com/adobe/phonegap/push/GCMIntentService.java:371: error: cannot find symbol
                mBuilder.extend(new WearableExtender().addActions(wActions));
                                    ^
  symbol:   class WearableExtender
  location: class GCMIntentService
/project/src/com/adobe/phonegap/push/GCMIntentService.java:425: error: cannot find symbol
                NotificationCompat.InboxStyle notificationInbox = new NotificationCompat.InboxStyle()
                                  ^
  symbol:   class InboxStyle
  location: class NotificationCompat
/project/src/com/adobe/phonegap/push/GCMIntentService.java:425: error: cannot find symbol
                NotificationCompat.InboxStyle notificationInbox = new NotificationCompat.InboxStyle()
                                                                                        ^
  symbol:   class InboxStyle
  location: class NotificationCompat
/project/src/com/adobe/phonegap/push/GCMIntentService.java:435: error: cannot find symbol
                NotificationCompat.BigTextStyle bigText = new NotificationCompat.BigTextStyle();
                                  ^
  symbol:   class BigTextStyle
  location: class NotificationCompat
/project/src/com/adobe/phonegap/push/GCMIntentService.java:435: error: cannot find symbol
                NotificationCompat.BigTextStyle bigText = new NotificationCompat.BigTextStyle();
                                                                                ^
  symbol:   class BigTextStyle
  location: class NotificationCompat
/project/src/com/adobe/phonegap/push/GCMIntentService.java:445: error: cannot find symbol
            NotificationCompat.BigPictureStyle bigPicture = new NotificationCompat.BigPictureStyle();
                              ^
  symbol:   class BigPictureStyle
  location: class NotificationCompat
/project/src/com/adobe/phonegap/push/GCMIntentService.java:445: error: cannot find symbol
            NotificationCompat.BigPictureStyle bigPicture = new NotificationCompat.BigPictureStyle();
                                                                                  ^
  symbol:   class BigPictureStyle
  location: class NotificationCompat
/project/src/com/adobe/phonegap/push/GCMIntentService.java:457: error: cannot find symbol
            NotificationCompat.BigTextStyle bigText = new NotificationCompat.BigTextStyle();
                              ^
  symbol:   class BigTextStyle
  location: class NotificationCompat
/project/src/com/adobe/phonegap/push/GCMIntentService.java:457: error: cannot find symbol
            NotificationCompat.BigTextStyle bigText = new NotificationCompat.BigTextStyle();
                                                                            ^
  symbol:   class BigTextStyle
  location: class NotificationCompat
/project/src/com/adobe/phonegap/push/GCMIntentService.java:521: error: cannot find symbol
                if (priority >= NotificationCompat.PRIORITY_MIN && priority <= NotificationCompat.PRIORITY_MAX) {
                                                  ^
  symbol:   variable PRIORITY_MIN
  location: class NotificationCompat
/project/src/com/adobe/phonegap/push/GCMIntentService.java:521: error: cannot find symbol
                if (priority >= NotificationCompat.PRIORITY_MIN && priority <= NotificationCompat.PRIORITY_MAX) {
                                                                                                 ^
  symbol:   variable PRIORITY_MAX
  location: class NotificationCompat
/project/src/com/adobe/phonegap/push/GCMIntentService.java:522: error: cannot find symbol
                    mBuilder.setPriority(priority);
                            ^
  symbol:   method setPriority(Integer)
  location: variable mBuilder of type Builder
/project/src/com/adobe/phonegap/push/GCMIntentService.java:596: error: cannot find symbol
            mBuilder.setColor(iconColor);
                    ^
  symbol:   method setColor(int)
  location: variable mBuilder of type Builder
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
20 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.878 secs
undefined

**Comment by dodekx** [comment]
I have the same issue, what fixed it is instalation extras from android sdk manager ( android support repository, Google repository) After then I manual remove android build cordova folder, and once again add android platform to my project

**Comment by kristiKeri** [comment]
The problem is that the application is compiled online https://build.phonegap.com, so i can not remove the folders.  i think there is something wrong with the libs.  The error starts like this:

:compileDebugJavaWithJavac/project/src/com/adobe/phonegap/push/GCMIntentService.java:20: error: cannot find symbol
import android.support.v4.app.NotificationCompat.WearableExtender;
^
symbol: class WearableExtender
location: class NotificationCompat
/project/src/com/adobe/phonegap/push/GCMIntentService.java:329: error: cannot find symbol
mNotificationManager.notify(appName, notId, mBuilder.build()); ....

**Comment by goya** [comment]
for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.

**Comment by macdonst** [comment]
Closing this issue as it is being handled on PGB forum.
