### ISSUE TITLE
RegistrationID doesn't seems right!

### ISSUE THREAD

**Issue by ngystvn90** [phonegap/phonegap-plugin-push#955]
Hi!

I am trying to send push notifications with your plugin. Everything works well on Android, but on iOS the registration is successful, but I can't send notifications to the registered device (I am using PHP)

### Expected Behaviour

Receive a registrationID with only hexadecimal characters

### Actual Behaviour

RegistrationID contains not only hexadecimal characters.

registrationID received from registration callback:

dBCNCs9v2jY:APA91bFovRcUkhwAeL8_9sIVx7Quck6AWEipB9GDS8rZMKAMbERn0WTVHFrpBFvQ0I1l44OdkPi5XPwDSuQcGRTz-N3CjCXclovC__7kJiYDtfT8RhsfFDrANcFjD_5DzNMThaip8Nb1

### Reproduce Scenario (including but not limited to)

Only follow the step by step configuration in docs.

#### Steps to Reproduce 

Only follow the step by step configuration in docs.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 9.3.2 on iPhone 5S

#### Cordova CLI version and cordova platform version

    cordova --version 6.0.0

#### Plugin version

    cordova plugin version 1.6.3

#### Sample Push Data Payload

`$body['aps'] = array(
'alert' => $message,
				'badge' => 1, 		
				'sound' => 'default',
				'content-available' => 1
				);
			$body['type'] = $type;`

#### Sample Code that illustrates the problem

`var options = {};
options.android = {
	senderID: app.android_sender_id,
};
options.ios = {
	senderID: app.ios_sender_id,
	alert: true,
	badge: true,
	sound: true,
	gcmSandbox: false,
};

app.push = PushNotification.init(options);

app.push.on('registration', function(data){
	alert(data.registrationId);
};`

**Comment by macdonst** [comment]
@ngystvn90 well you are registering your app with GCM on iOS but you are trying to send your push data to APNS directly. If you want to use GCM on iOS you need to send your push payload to GCM which then forwards to APNS which delivers to your device.

**Comment by ngystvn90** [comment]
Yes, you were right. I removed the senderID: app.ios_sender_id, from the ios options. I regenerated my *.pem and now I am able to get notifications in development. I hope everything will be okey in production as well. Thank you for pointing me to the right direction. Cheers!
