### ISSUE TITLE
Notifications never received on Android

### ISSUE THREAD

**Issue by alexislg2** [phonegap/phonegap-plugin-push#96]
Hey,
I have a weird behaviour. Sometimes some notifications are never received (the app is shut down). And sometimes it works fine but the notification sent by the back end is exactly the same.

I had a look at the Google GCM diagnosis tool provided on the play store developer console and all the unreceived notification have tha following status: acknowledged

Acknowledged means that everything is fine. But I never received it, never saw it in the status bar, never eard it...

Anyone else experiences same issues?

**Comment by macdonst** [comment]
@alexislg2 I haven't run into that issue. What version of the plugin are you using? And what is an example notification you are sending via GCM?

**Comment by alexislg2** [comment]
Hey,
thanks for your reply. In fact my test users told me they never received some notifications it but all the notifications I send to myself are well received. So I will close the issue  and will open it back if I can reproduce the problem on my phone.

**Comment by xavianaxw** [comment]
@alexislg2 have you manage to replicate it or fixed it by any chance? I'm having the issue with push notifications not being received when the app is closed. And the status on AWS console is 200.

**Comment by alexislg2** [comment]
No but I still have some complaints from my users who say the didn't
receive notifications
But my guess is that they open the app and then realize that they didn't
receive the notification the expected but the notification disappear as
soon as the app is open

**Comment by xavianaxw** [comment]
@alexislg2 ah that sucks. I'm having the same problem right now and I've the slightest clue how to get it fixed.

Thanks anyways. Cheers!
