### ISSUE TITLE
No notification in notification shade in iOS with payload without notification part

### ISSUE THREAD

**Issue by gitMAZE** [phonegap/phonegap-plugin-push#960]
### Expected Behaviour
Push Notification with payload having only data part, no notification part and content_available =  true (outside data part for running iOS background task) is sent to Android and iOS and Notification should be shown when in background on both in Notification Shade.
USING GCM FOR BOTH(Need to use topics for both)

### Actual Behaviour
Payload with data part is sent to iOS and background task(& didReceiveRemoteNotification) is executed when app is in background but no notification appears since the plugin code doesn't create notification(I guess, not an iOS guy) like in Android. (I'm gonna add code for local notification there in file AppDelegate+notification.m, wondering if it's the right way).
With Notification part, clicking the notification on Android doesn't call onNotification so I have to avoid notification part.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0 and iOS 9.2.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
LG G3

#### Cordova CLI version and cordova platform version

    cordova version 6.0.0
    cordova platform version android 4.1.1

#### Plugin version
    1.6.3

#### Sample Push Data Payload

    {
        to: 'topic',
        data: {
            message: 'msz',
            title: 'title',
            priority: 2,
            'content-available': 1,
            sound: 'sound',
            vibrate: 1
        },
        content_available: true, //for ios
        priority: 'high'//for ios
    }

#### ADDITIONAL STUFF
Want to use topics since I am not using any service to keep track of registration_ids, Do I need to implement it the other way with registration ids for good in future?

**Comment by macdonst** [comment]
@gitMAZE if you are using GCM on iOS the payload format is different:

```
{
    to: 'topic',
    notification: {
        body: 'msz',
        title: 'title',
        priority: 2,
        'content-available': 1,
        sound: 'sound',
        vibrate: 1
    },
    content_available: true, //for ios
    priority: 'high'//for ios
}
```

but then you won't get the proper format for Android. 

You should have an iOS topic and an Android topic so you can send the two different payloads.

**Comment by gitMAZE** [comment]
Ok thanks, I thought of that too. There's that way with two different messages or send single message with data part to both with content available true and create localNotification on iOS in didReceiveRemoteNotification function.

Waiting for FCM support in this plugin :-)
