### ISSUE TITLE
Long delay before receiving notification on latest push plugin

### ISSUE THREAD

**Issue by iori57** [phonegap/phonegap-plugin-push#961]
### Expected Behaviour
Push notification received on client side within a minute after sending

### Actual Behaviour
Push notification received on client side after 5-10 minutes

### Reproduce Scenario (including but not limited to)
- After moving from the deprecated pushplugin (actually one of its fork) to the current phonegap-plugin-push plugin.
- Behaves the same whether app is in background or foreground
- Revert to old plugin on same iOS device, doesn't have this issue
- Android doesn't have this issue

#### Steps to Reproduce 
1) Put a breakpoint at didReceiveRemoteNotification
2) Send a push notification
3) Nothing happens
4) Wait 5-10 minutes
5) Breakpoint gets hit, notification gets processed correctly from this point onwards

At first I suspect is network or APNS issue (sometimes they get congested). But I tried reverting back to old plugin, the plugin receives the notification immediately every single time, while switching to new plugin the delay is always there. I only have one iOS device now but I can test with more devices when I am back in office by Monday.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 9.1

#### Cordova CLI version and cordova platform version

    cordova --version 5.1.1                        
    cordova platform version android 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push 1.6.4

#### Sample Push Data Payload
{
    "aps": {
        "alert": "testing",
        "badge": 5,
    }
}

**Comment by macdonst** [comment]
@iori57 I don't think the delay has anything to do with the plugin.

**Comment by iori57** [comment]
You are right, seems like it is indeed not related to the plugin. Sorry for false alarm. Closing this.
