### ISSUE TITLE
push quote issue

### ISSUE THREAD

**Issue by bechtech** [phonegap/phonegap-plugin-push#962]
in shell command this:

    phonegap push --deviceID c52208c96a2a377655b4 --service apns --payload '{"aps":{"alert":"I'm kevin","badge":1}}'

#### Issue
payload message include single quote ,it didn't work. and the shell blocked.
well, i tried this: I\'m Kevin . 
no fine.

**Comment by macdonst** [comment]
@bechtech this is actually a shell question. If you are on a Mac using Bash then it would be:

```
phonegap push --deviceID c52208c96a2a377655b4 --service apns --payload '{"aps":{"alert":"I\'''m kevin","badge":1}}'
```

http://wiki.bash-hackers.org/syntax/quoting#strong_quoting
