### ISSUE TITLE
Message count (msgcnt) not working on Android in plugin v1.6.4

### ISSUE THREAD

**Issue by iori57** [phonegap/phonegap-plugin-push#963]
I already fixed it manually on my side, but raising this so that it can get fixed in the main code.

The fix:
in GCMIntentService.java setNotificationCount() function,
The function tries to get msgcnt from MSGCNT or BADGE, but both keys have already been normalized into COUNT in normalizeKey() function
so the fix is to change setNotificationCount() to get msgcnt from COUNT, before trying MSGCNT or BADGE

I changed mine to:
`private void setNotificationCount(Bundle extras, NotificationCompat.Builder mBuilder) {`
`        String msgcnt = extras.getString(COUNT);`
`        if (msgcnt == null) {`
`            msgcnt = extras.getString(MSGCNT);`
`        }`
`        if (msgcnt == null) {`
`            msgcnt = extras.getString(BADGE);`
`        }`
`        if (msgcnt != null) {`
`            mBuilder.setNumber(Integer.parseInt(msgcnt));`
`        }`
`    }`
### Expected Behaviour
msgcnt in payload will show beside notification item

### Actual Behaviour
msgcnt in payload gets ignored

#### Steps to Reproduce 
1) Send a payload with msgcnt
2) Notice that message count doesn't show beside notification item

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
LG

#### Cordova CLI version and cordova platform version

    cordova --version 5.1.1                        
    cordova platform version android 5.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push 1.6.4

**Comment by macdonst** [comment]
@iori57 this is already fixed in the 1.7.x branch.

**Comment by iori57** [comment]
Cool, thanks!

**Comment by macdonst** [comment]
@iori57 oh and I'm in the process of merging the 1.7.x branch into master for a release later today.
