### ISSUE TITLE
[iOS] Notification don't sound

### ISSUE THREAD

**Issue by Davids89** [phonegap/phonegap-plugin-push#964]
### Expected Behaviour
When the notification is showed in foreground I want to make it sound.
### Actual Behaviour
I show the dialog but the sound is not playing.

I have this payload 

`{  
   "additionalData":{  
      "message":"text",
      "title":"text",
      "foreground":true,
      "coldstart":false,
      "tag":"SERVICE_PICKUP"
   },
   "message":"text",
   "sound":"default"
}`

How you can see I set default as my sound. I have it placed in www/ as default.wav. According to the docs the sound must be played but no.

**Comment by macdonst** [comment]
@Davids89 actually that's now how you do it at all. When the app is in the background then the OS will play a sound but when the app is in the foreground then it is up to you to show any UI or play any sounds.

So in your `on('notification')` event handler you'd add some code to play the sound:

```
var myMedia = new Media("default.wav")
myMedia.play();
```

**Comment by Davids89** [comment]
Oh! I though I must do it with the plugin. Thanks a lot!
