### ISSUE TITLE
How to generate a action-button JSON in java

### ISSUE THREAD

**Issue by mkj-git** [phonegap/phonegap-plugin-push#969]
I was going through this link https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons

I am using https://github.com/google/gcm to send notification from java. My question is how can i make 

>     "data": {
>         "title": "AUX Scrum",
>         "message": "Scrum: Daily touchbase @ 10am Please be on time so we can cover everything on the agenda.",
>         "actions": [
>             { "icon": "emailGuests", "title": "EMAIL GUESTS", "callback": "app.emailGuests", "foreground": true},
>             { "icon": "snooze", "title": "SNOOZE", "callback": "app.snooze", "foreground": false}
>         ]
>     }

I dont see any method that can produce this kind JSON. addData(String, String) only except String

**Comment by macdonst** [comment]
@mkj-git it's just JSON. There are many Java packages that let you manipulate JSON.

http://stackoverflow.com/a/31743324

**Comment by mkj-git** [comment]
That i got it. My question is the GCM server only allow to send anything in <String, String> format. I can't see any method that allow you to send any other format except <String,Steing>. 

e.g addData(String, String), setData(HashMap<String, String>) are the only method to send data. and both are accepting only Strings.

**Comment by jcesarmobile** [comment]
You can send any JSON to GCM server, how you create it is up to you. If the library you use right now only allows you to add strings search for another

**Comment by mkj-git** [comment]
can you suggest some good GCM java library

**Comment by jcesarmobile** [comment]
I'm not familiar with any GCM java library, the only push notifications I've sent from a java server just did a POST to the GCM server

**Comment by macdonst** [comment]
@mkj-git use node-gcm, there is an example script in the docs:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons

**Comment by mkj-git** [comment]
that is for nodejs i am looking for java
