### ISSUE TITLE
Notification LED is not working

### ISSUE THREAD

**Issue by caipigott** [phonegap/phonegap-plugin-push#97]
Hi,

i'm using cordova android 3.4.0. I added your plugin and so far it works perfect, apart from the led when i receive a notification while the application is closed and the celular is switched off. The vibration works and it's displayed on the lock screen but unfortunatelly no led (and maybe it's also possible to turn on the celular on receiving a notofication? )

Is this a problem of this pluging or do i have add an other plugin to solve this. If yes, please let me know which one as i'm really really confused of all these plugins.

Mana thanks in advance,
Caipigott

**Comment by macdonst** [comment]
@caipigott no, it's a bug. I will fix it in an upcoming release.

**Comment by macdonst** [comment]
Addressed in #108 which should get merged soon.

**Comment by caipigott** [comment]
Hi,

i saw that an update was published for this issue, but unfortunatelly there is still no led flashing on receiving a message. I found inside the commit that "To use, add the `iconColor` key to plugin android options". I'm pretty new to this, so can you help me where I have to add this, and how exactly it has to look like?

Many thanks for your help,
Caipigott

**Comment by macdonst** [comment]
@caipigott hasn't been merged yet. Soon though.

**Comment by macdonst** [comment]
@caipigott re-test with the upcoming 1.3.0 release and re-open if it doesn't fix your issue.
