### ISSUE TITLE
unable to take registrationId id from ios

### ISSUE THREAD

**Issue by hooiyijun** [phonegap/phonegap-plugin-push#974]
I created new phonegap project with `phonegap create my-app --template phonegap-template-push`

And updated 2 sender id to "google key's project id" in phonegap project. First sender id in config.xml. Second sender id in js/index.js. And updated the following xml thing in config.xml as below

```
<gap:plugin name="phonegap-plugin-push" source="npm" spec="~1.6.2">
		<params>
		<param name="SENDER_ID" value="123456" />
		</params>
</gap:plugin>
```

Also added ios api parameters "gcmSandbox" in the following js file js/index.js.

```
        var push = PushNotification.init({
            "android": {
                "senderID": "123456"
            },
            "ios": {
                "gcmSandbox ": false,
                "sound": true,
                "vibration": true,
                "badge": true
            },
            "windows": {}
        });
```

After zipped this phonegap project and submitted to build phonegap website. And signed ios apps with p12 of "IOS Development Certificate" with IOS Provisioning Profiles (Development). After built phonegap, also downloaded apk with ipa. The apk have worked with GSM push notification.

But in ios mobile apps (ipa), i unable to get registration id from  push.on('registration'). I also uploaded p12 of "APN's Development IOS"  in https://developers.google.com/cloud-messaging/ios/client#get-config

My iOS version is 6.1.6

Some version of plugin can be viewed from the part of config.xml

```
    <gap:plugin name="cordova-plugin-statusbar" source="npm" spec="~2.1.3" />
    <gap:plugin name="phonegap-plugin-push" source="npm" spec="~1.6.2">
		<params>
		<param name="SENDER_ID" value="123456" />
		</params>
    </gap:plugin>
	<gap:plugin name="cordova-plugin-console" source="npm" spec="~1.0.3" />
	<gap:plugin name="cordova-plugin-dialogs" source="npm" spec="~1.2.1" />
	<gap:plugin name="cordova-plugin-whitelist" source="npm" spec="~1.2.1" />
```

The issue is:  i unable to get registration id (ios device token) from push.on('registration') for ios push notifcation

**Comment by macdonst** [comment]
@hooiyijun sorry do you mean to say your device is running iOS 6.1.6?

**Comment by hooiyijun** [comment]
hi, my IOS is 3GS. Latest version is 6.1.6

**Comment by macdonst** [comment]
@hooiyijun yeah, I'm sorry this plugin doesn't support an iOS version that old. I can't even begin to debug any problems on iOS 6. You'll need something running iOS 8 or greater.
