### ISSUE TITLE
Can't install this plugin for ionic project in ios

### ISSUE THREAD

**Issue by zhouhao27** [phonegap/phonegap-plugin-push#976]
Got the following error message:

> Updated the hooks directory to have execute permissions
> Installing "phonegap-plugin-push" for ios
> Plugin doesn't support this project's cordova-ios version. cordova-ios: 3.8.0, failed version requirement: >=4.1.0
> Skipping 'phonegap-plugin-push' for ios

So that I used the following command to upgrade the cordova-ios:

> cordova ios upgrade

Then I'm able to install the plugin. But when I run **ionic server**, I got the following error message:

<img width="773" alt="2016-06-10 12 30 24" src="https://cloud.githubusercontent.com/assets/8099731/15954238/329990f8-2f07-11e6-9792-d2f3bccbe43a.png">

**Comment by macdonst** [comment]
@zhouhao27 the answer is right in the logs you posted:

>Plugin doesn't support this project's cordova-ios version. cordova-ios: 3.8.0, failed version requirement: >=4.1.0

You are using cordova-ios 3.8.0 and will need to upgrade to cordova-ios 4.1.0 or better. 

```
cordova platform rm ios
cordova platform add ios
```

That'll pick up the latest version of cordova-ios.

**Comment by macdonst** [comment]
@zhouhao27 I'm assuming this issue is resolved. Please update me if that is not correct.
