### ISSUE TITLE
Sound is working in Reverse

### ISSUE THREAD

**Issue by sunojvijayan** [phonegap/phonegap-plugin-push#977]
Expected Behaviour
Notification sound to be heard when app is in background and not in foreground

 Actual Behaviour
Notification sound is coming when in foreground and is not coming when app is in background

Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1 Nexus 5

(Android) What device vendor (e.g. Samsung, HTC, Sony...)
LG

Cordova CLI version and cordova platform version

    cordova --version                                    . 6.0.0
    cordova platform version android                     6.0.1

Plugin version

**Comment by sunojvijayan** [comment]
Can anyone please help. It was working in previous version for another app

**Comment by macdonst** [comment]
@sunojvijayan that doesn't make any sense. The payload you use to reproduce this and a `adb logcat | grep PushPlugin` would be useful in debugging.

**Comment by sunojvijayan** [comment]
console.log("Vehicle" + JSON.stringify(vehicle));
    var msgTemp = {
        collapseKey: 'Test',
        priority: 'high',
        delayWhileIdle: false,
        timeToLive: 3,
        dryRun: false,
        "sound": "default",
        data: {
            pushtype: 'challenge'
        },
        notification: {
            title: "Reminder for Payment",
            icon: "ic_launcher",
            body: "Payment pending for your vehicle."
        }
    }
    var message = new gcm.Message(msgTemp);

    var regTokens = vehicle.gcms;

    // Set up the sender with you API key
    var sender = new gcm.Sender('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');

    // Now the sender can be used to send messages
    sender.send(message, {
        registrationTokens: regTokens
    }, 1000, function (err, response) {
        if (err) {
            console.error(err);
        } else {
            console.log(response);
            return response;
        }
    });

This is how i send msg

**Comment by sunojvijayan** [comment]
This is my init function

$rootScope.push = PushNotification.init({
            "android": {
                "senderID": "XXXXXXXXXXX",
                "icon": "icon",
                "sound": "true",
                "iconColor": "#FFC90D"
            },
            "ios": {
                "senderID": "XXXXXXXXXX",
                "alert": "true",
                "badge": "true",
                "sound": "true",
                gcmSandbox: "true"
            },
            "windows": {}
        });

**Comment by macdonst** [comment]
@sunojvijayan try sending this instead:

```
var msgTemp = {
    collapseKey: 'Test',
    priority: 'high',
    delayWhileIdle: false,
    timeToLive: 3,
    dryRun: false,
    data: {
        pushtype: 'challenge',
        title: "Reminder for Payment",
        icon: "ic_launcher",
        body: "Payment pending for your vehicle.",
        sound: "default"
    }
}
var message = new gcm.Message(msgTemp);
```

**Comment by sunojvijayan** [comment]
That did it. Thank a lot for your help. Much appreciated.

**Comment by sunojvijayan** [comment]
One more help please.

var msgTemp = {
    collapseKey: 'Test',
    priority: 'high',
    delayWhileIdle: false,
    timeToLive: 3,
    dryRun: false,
    "content-available": 1,
    data: {
        pushtype: 'challenge',
        title: "Reminder for Payment",
        icon: "ic_launcher",
        body: "Payment pending for your vehicle.",
        sound: "default"
    }
}
var message = new gcm.Message(msgTemp);



The content-available flag not working. I want to send a hidden notification to my app to update a content inside the app but i dont want my users to know. Please help

**Comment by macdonst** [comment]
@sunojvijayan omit the title and body from the notification for it to be a silent background notification.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications

**Comment by sunojvijayan** [comment]
Thanks that worked.

I have one more doubt. My case is that i want to enable geolocation based push. I will push to all devices, and in my device check if the device is in that particular location and then show notification (Can be local notification). So i need the push to be caught in the background and check if the device is in the geolocation and show local notification. Is this possible by using this plugin and local notification. Please help.
