### ISSUE TITLE
Notification tray does not appear when app in foreground?

### ISSUE THREAD

**Issue by jayeshjain24** [phonegap/phonegap-plugin-push#978]
### Expected Behaviour
Notification tray should appear when app is in foreground. Notification tray appears when app is background.But I do get the message in my code, when the app is in foreground. Just that I dont get the tray that appears when app is in background.
```
push.on('notification', function(data) {
                console.log(data.message);
                console.log(data.title);
            });

``` 
### Actual Behaviour
The Notification tray should appear even when app is in foreground.
### Reproduce Scenario (including but not limited to)
Send push notification when app is closed. Notification tray pops up. 
Send push notification when app is in foreground . Notification tray does not appear.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Androd 5.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
MotoG
#### Cordova CLI version and cordova platform version

    cordova --version     : 5.3.3                             
    cordova platform version android     : android 4.1.1            

#### Plugin version

    cordova plugin version   : 1.6.2

**Comment by macdonst** [comment]
@jayeshjain24 that is the correct behaviour. On Android if you want to show the notification even in the foreground use the `forceShow` option in init:

https://github.com/phonegap/phonegap-plugin-push/blob/browser/docs/API.md#pushnotificationinitoptions

**Comment by jayeshjain24** [comment]
@macdonst I was trying to emulate the notification experience of twitter. When in foreground, twitter seems to be getting the `forceShow` and `on('notification')` callback at the same time. Do  I need to click on the notification bar to trigger the event  `on('notification')`

**Comment by ajaysaini95700** [comment]
I tried this (forceShow:"true") for android. it is not working.
