### ISSUE TITLE
Sometimes notification is not coming

### ISSUE THREAD

**Issue by mkj-git** [phonegap/phonegap-plugin-push#979]
From server i am sending notification and i am getting response like this

`Message Result: MulticastResult(multicast_id=7200703123850234975,total=1,success=1,failure=0,canonical_ids=0,results: [[ messageId=0:1465616973355751%5036bc7038eb0007 ]]`

but on client i am not getting any notification. `adb logcat | grep PushPlugin` is not shwoing any activity. I am using 1.6.4 version of plugin. on android lollipop with ionic 1.3

Same code send the notification but sometime it doesn't. Do I have to set something to make sure that notification is sent.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
