### ISSUE TITLE
Can't build iOS app with 1.7 version

### ISSUE THREAD

**Issue by oussaki** [phonegap/phonegap-plugin-push#981]
### Expected Behaviour
Build the ios app

### Actual Behaviour
It show's an error : 
The following build commands failed:
	Ld build/emulator/HelloCordova.app/HelloCordova normal i386
(1 failure)

Note : when uninstall the plugin i can build normally . 

#### Steps to Reproduce 

- Create a new project  
- Add iOS platform 
- Try to add the stable version of this plugin (1.7) it shows that i have to upgrade the iOs from 4.0.1 to 4.1.0
- update iOS to 4.1.0 
- Add the plugin again with ( success )
- build the app for iOS 

#### Cordova CLI version and cordova platform version

    cordova --version                                  6.0.0
    cordova platform version ios                 4.1.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.7

### XCode Version
  6.4.0 

### Screenshot targets
[http://i.imgur.com/oT5I8gI.png](url)

#### Logs taken while reproducing problem

Ld build/emulator/HelloCordova.app/HelloCordova normal i386
    cd /Applications/XAMPP/xamppfiles/htdocs/iosapp/mbrjobs/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -L/Applications/XAMPP/xamppfiles/htdocs/iosapp/mbrjobs/platforms/ios/build/emulator -L/Applications/XAMPP/xamppfiles/htdocs/iosapp/mbrjobs/platforms/ios/HelloCordova/Plugins/phonegap-plugin-push/GCM/Libraries -F/Applications/XAMPP/xamppfiles/htdocs/iosapp/mbrjobs/platforms/ios/build/emulator -filelist /Applications/XAMPP/xamppfiles/htdocs/iosapp/mbrjobs/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Objects-normal/i386/HelloCordova.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -objc_abi_version -Xlinker 2 -ObjC -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=8.0 /Applications/XAMPP/xamppfiles/htdocs/iosapp/mbrjobs/platforms/ios/build/emulator/libCordova.a -framework AddressBook -lGGLCloudMessaging -lGGLCore -lGGLInstanceIDLib -lGIP_Reachability -lGSDK_Overload -lGTMSessionFetcher_core -lGTMSessionFetcher_full -lGTMStackTrace -lGTM_AddressBook -lGTM_DebugUtils -lGTM_GTMURLBuilder -lGTM_KVO -lGTM_NSData+zlib -lGTM_NSDictionary+URLArguments -lGTM_NSScannerJSON -lGTM_NSStringHTML -lGTM_NSStringXML -lGTM_Regex -lGTM_RoundedRectPath -lGTM_StringEncoding -lGTM_SystemVersion -lGTM_UIFont+LineHeight -lGTM_core -lGTM_iPhone -lGcmLib -lProtocolBuffers -Xlinker -dependency_info -Xlinker /Applications/XAMPP/xamppfiles/htdocs/iosapp/mbrjobs/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Objects-normal/i386/HelloCordova_dependency_info.dat -o /Applications/XAMPP/xamppfiles/htdocs/iosapp/mbrjobs/platforms/ios/build/emulator/HelloCordova.app/HelloCordova
Undefined symbols for architecture i386:
  "_deflate", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByCompressingBytes:length:compressionLevel:mode:] in libGTM_NSData+zlib.a(GTMNSData+zlib.o)
  "_deflateEnd", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByCompressingBytes:length:compressionLevel:mode:] in libGTM_NSData+zlib.a(GTMNSData+zlib.o)
  "_deflateInit2_", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByCompressingBytes:length:compressionLevel:mode:] in libGTM_NSData+zlib.a(GTMNSData+zlib.o)
  "_inflate", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByInflatingBytes:length:isRawData:] in libGTM_NSData+zlib.a(GTMNSData+zlib.o)
  "_inflateEnd", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByInflatingBytes:length:isRawData:] in libGTM_NSData+zlib.a(GTMNSData+zlib.o)
  "_inflateInit2_", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByInflatingBytes:length:isRawData:] in libGTM_NSData+zlib.a(GTMNSData+zlib.o)
  "_sqlite3_bind_blob", referenced from:
      ___59-[GMRSqliteStore upsertStatementForRecord:inTableWithName:]_block_invoke350 in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore saveMessageWithRmqId:tag:data:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_bind_double", referenced from:
      ___59-[GMRSqliteStore upsertStatementForRecord:inTableWithName:]_block_invoke350 in libGGLCore.a(GMRSqliteStore.o)
  "_sqlite3_bind_int", referenced from:
      -[GCMRmq2PersistentStore saveMessageWithRmqId:tag:data:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore updateLastOutgoingRmqId:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore saveSyncMessageWithRmqID:expirationTime:apnsReceived:mcsReceived:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_bind_int64", referenced from:
      ___59-[GMRSqliteStore upsertStatementForRecord:inTableWithName:]_block_invoke350 in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore saveMessageWithRmqId:tag:data:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore deleteMessagesFromTable:withRmqIds:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore updateLastOutgoingRmqId:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore saveSyncMessageWithRmqID:expirationTime:apnsReceived:mcsReceived:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_bind_null", referenced from:
      ___59-[GMRSqliteStore upsertStatementForRecord:inTableWithName:]_block_invoke350 in libGGLCore.a(GMRSqliteStore.o)
  "_sqlite3_bind_text", referenced from:
      -[GMRSqliteStore bindToStatement:text:atIndex:] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore saveUnackedS2dMessageWithRmqId:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore deleteMessagesFromTable:withRmqIds:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore saveSyncMessageWithRmqID:expirationTime:apnsReceived:mcsReceived:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore updateSyncMessageWithRmqID:column:value:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_changes", referenced from:
      -[GCMRmq2PersistentStore deleteMessagesFromTable:withRmqIds:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore deleteExpiredOrFinishedSyncMessages:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_clear_bindings", referenced from:
      -[GMRSqliteStore tableExists:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore rowCountForTableWithName:columnName:columnValue:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore recordsForQuery:] in libGGLCore.a(GMRSqliteStore.o)
  "_sqlite3_close", referenced from:
      -[GMRSqliteStore closeDatabase] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore dealloc] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_column_blob", referenced from:
      -[GMRSqliteStore valueAtColumn:forStatement:] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore scanOutgoingRmqMessagesWithHandler:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_column_bytes", referenced from:
      -[GMRSqliteStore valueAtColumn:forStatement:] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore scanOutgoingRmqMessagesWithHandler:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_column_count", referenced from:
      -[GMRSqliteStore recordsForQuery:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore validateDatabase] in libGGLCore.a(GMRSqliteStore.o)
  "_sqlite3_column_double", referenced from:
      -[GMRSqliteStore valueAtColumn:forStatement:] in libGGLCore.a(GMRSqliteStore.o)
  "_sqlite3_column_int", referenced from:
      -[GMRSqliteStore rowCountForTableWithName:columnName:columnValue:] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore scanOutgoingRmqMessagesWithHandler:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore querySyncMessageWithRmqID:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_column_int64", referenced from:
      -[GMRSqliteStore valueAtColumn:forStatement:] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore queryHighestRmqId] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore queryLastRmqId] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore scanOutgoingRmqMessagesWithHandler:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore querySyncMessageWithRmqID:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_column_name", referenced from:
      -[GMRSqliteStore recordsForQuery:] in libGGLCore.a(GMRSqliteStore.o)
  "_sqlite3_column_text", referenced from:
      -[GMRSqliteStore columnsForTableWithName:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore validateDatabase] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore valueAtColumn:forStatement:] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore unackedS2dRmqIds] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore querySyncMessageWithRmqID:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_column_type", referenced from:
      -[GMRSqliteStore valueAtColumn:forStatement:] in libGGLCore.a(GMRSqliteStore.o)
  "_sqlite3_errcode", referenced from:
      -[GCMRmq2PersistentStore saveMessageWithRmqId:tag:data:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore deleteExpiredOrFinishedSyncMessages:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore saveSyncMessageWithRmqID:expirationTime:apnsReceived:mcsReceived:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore updateSyncMessageWithRmqID:column:value:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore lastErrorCode] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_errmsg", referenced from:
      -[GMRSqliteStore lastErrorMessage] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore saveMessageWithRmqId:tag:data:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore lastErrorMessage] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_exec", referenced from:
      -[GMRSqliteStore beginTransaction] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore endTransaction] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore rollbackTransaction] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore createTableWithName:command:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore dropTableWithName:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_finalize", referenced from:
      -[GMRSqliteStore columnsForTableWithName:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore deleteRecordFromTableWithName:columnName:columnValue:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore deleteRecordsFromTableWithName:condition:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore recordsForQuery:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore removeStatementForQuery:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore prepareSQL:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore executeSQLStatement:] in libGGLCore.a(GMRSqliteStore.o)
      ...
  "_sqlite3_open", referenced from:
      -[GCMRmq2PersistentStore openDatabase:] in libGcmLib.a(GCMRmq2PersistentStore.o)
  "_sqlite3_open_v2", referenced from:
      -[GMRSqliteStore openAndValidateDatabase] in libGGLCore.a(GMRSqliteStore.o)
  "_sqlite3_prepare_v2", referenced from:
      -[GMRSqliteStore prepareSQL:] in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore saveUnackedS2dMessageWithRmqId:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore saveMessageWithRmqId:tag:data:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore deleteMessagesFromTable:withRmqIds:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore queryHighestRmqId] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore queryLastRmqId] in libGcmLib.a(GCMRmq2PersistentStore.o)
      -[GCMRmq2PersistentStore updateLastOutgoingRmqId:] in libGcmLib.a(GCMRmq2PersistentStore.o)
      ...
  "_sqlite3_reset", referenced from:
      -[GMRSqliteStore tableExists:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore dropTableWithName:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore rowCountForTableWithName:columnName:columnValue:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore deleteAllRecordsFromTableWithName:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore recordsForQuery:] in libGGLCore.a(GMRSqliteStore.o)
  "_sqlite3_step", referenced from:
      -[GMRSqliteStore tableExists:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore dropTableWithName:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore rowCountForTableWithName:columnName:columnValue:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore columnsForTableWithName:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore deleteRecordFromTableWithName:columnName:columnValue:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore deleteRecordsFromTableWithName:condition:] in libGGLCore.a(GMRSqliteStore.o)
      -[GMRSqliteStore deleteAllRecordsFromTableWithName:] in libGGLCore.a(GMRSqliteStore.o)
      ...
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld build/emulator/HelloCordova.app/HelloCordova normal i386
(1 failure)
ERROR building one of the platforms: Error code 65 for command: xcodebuild with args: -xcconfig,/Applications/XAMPP/xamppfiles/htdocs/iosapp/mbrjobs/platforms/ios/cordova/build-debug.xcconfig,-project,HelloCordova.xcodeproj,ARCHS=i386,-target,HelloCordova,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Applications/XAMPP/xamppfiles/htdocs/iosapp/mbrjobs/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Applications/XAMPP/xamppfiles/htdocs/iosapp/mbrjobs/platforms/ios/build/sharedpch
You may not have the required environment or OS to build this project

**Comment by RyDevNL** [comment]
Hi, 

Try removing ios platform and adding it again with cordova platform add ios@4.1.1. I often have similar problems after upgrading the platform ios instead of reinstalling it.

**Comment by macdonst** [comment]
@oussaki https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#xcode

**Comment by oussaki** [comment]
@macdonst  so the xcode 7 is required ! to build this plugin ?

**Comment by macdonst** [comment]
@oussaki yes, yes it is.

**Comment by macdonst** [comment]
@oussaki I'm closing this issue. Update me if you havent' been able to resolve it.
