### ISSUE TITLE
ios - App crash on start

### ISSUE THREAD

**Issue by coyu1314** [phonegap/phonegap-plugin-push#984]
On ios, I am experiencing a crash on start with version greater than 1.5.3. tested on 1.63 and the latest 1.7.0. both of them crash on start.  Please advise. 

#### Platform and Version
ios 9.3.2

#### Cordova CLI version and cordova platform version
phonegap build -  cli-5.2.0 (3.9.1 / 4.1.1 / 3.8.1)

#### Plugin version
1.5.3 is fine. but anything over 1.5.3 will have crash on start issue.

**Comment by macdonst** [comment]
@coyu1314 it is probably because you are using an older version of cordova-ios. Version 1.6.x needs cordova-ios 4.x or better and version 1.7.x needs 4.1.x or better.

**Comment by coyu1314** [comment]
@macdonst but once I changed to phonegap-version 6.1.0 (which will have ios 4.1.0). phonegap build will give me a ios build error. Android is fine. 

`<preference name="phonegap-version" value="cli-6.1.0" />`

the build error on ios is:
Oh geez. Your build failed. Sorry, but a problem occurred on the build server
