### ISSUE TITLE
visibility not working

### ISSUE THREAD

**Issue by balapkm** [phonegap/phonegap-plugin-push#987]
### Expected Behaviour

I'm working with push notification in ionic ..i need to hide notification from notification bar. 

### Actual Behaviour

i refer **Visibility of Notifications**  (https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md)
i set "visibility": 0 
even after setting visibility as 0 notification is not hiding.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4.4
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Redmi 2 (MI)
#### Cordova CLI version and cordova platform version

    cordova --version              : 6:0 
    cordova platform version android     5.1     

#### Sample Push Data Payload
message.addData('title', 'This is a public Notification');
message.addData('message', 'You should be able to read this notification on your lock screen');
message.addData('visibility', 0);

**Comment by macdonst** [comment]
@balapkm thanks for the feedback. I need to document this better. The secret, private and public parameters don't stop a notification from being show in the notification center, they only keep the info from being shown on the lock screen.

**Comment by balapkm** [comment]
Thank You ..! It's working.. i got the clear view of the concept..

**Comment by happy257** [comment]
Is there a way to briefly show the notification on the screen as dropdown and then hide automatically?

**Comment by fredgalvao** [comment]
@happy257  You might get away with it currently by sending a `content_available: 1` (please check the correct syntax on the docs, it depends on a number of aspects) payload as a notification, and then on your background handler calling `push.clearAllNotifications()` (again, please check the api docs for proper usage), to clear all notifications from the Notification Center. It won't work if you have to remove/hide/clear only **some** of the notifications.

It could be implemented as a new feature though, to let users either specify on the payload that the notification has a timeout and is not to be interacted with, for example. Or maybe add a method to the API to let users clear only one notification with a certain `notId` from the Notification Center.
