### ISSUE TITLE
push.on('registeration', callback); gives wrong registration id;

### ISSUE THREAD

**Issue by salman-ghauri** [phonegap/phonegap-plugin-push#988]
### Expected Behaviour
The older deprecated version used to return a registration id aka device token for android device using GCM. The new version should also be returing the similar value on the regitration event.
### Actual Behaviour
The current version return the registration id which is quit similar to the older one but with a change that there are some extra characters and digits before the actual id i.e. dKXLm: After the colon, the actual device token starts. 
Due to this behavior, the device is unable to receive notifications which it was doing very fine on older version on android devices. (not on iOs) 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1.1
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Google Nexus 7
#### Cordova CLI version and cordova platform version

    cordova --version                                   6.2.0
    cordova platform version android                     5.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.7

**Comment by macdonst** [comment]
@salman-ghauri this is expected behaviour. The format of registration ID you are seeing follows the [Google Instance ID](https://developers.google.com/instance-id/) specification that Google wanted everyone to move to. You should still be able to send messages to devices with the full registration ID.

**Comment by salman-ghauri** [comment]
@macdonst that's the thing, when I split the instance Id on ":" and use the actual device token, it works but when I use the full instance Id, it does not. Also I am receiving a single messages three times on the notification event.

**Comment by macdonst** [comment]
@salman-ghauri I can't really debug this as I have no idea how you are sending the message. I'm pretty confident if you use the node-gcm scripts I use as samples in the docs this will work fine.
