### ISSUE TITLE
Push received only on iPhone 6/6-plus but not iPhone 4/5

### ISSUE THREAD

**Issue by antonfire** [phonegap/phonegap-plugin-push#989]
### Expected Behaviour

Pushes to be received in iPhones 4,5,6 and 6plus

### Actual Behaviour

When sending to iPhone4 and 5 no pushes are received, received fine in 6 and 6plus.

### Reproduce Scenario (including but not limited to)

I have 3 devices all logged into the same apple account, only one of these receives pushes.

#### Steps to Reproduce 

Run 3 devices 4,5 and 6 all logged into same account. Apple push certificate is development.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

All devices running 9.3.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

N/a just iOS

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.2.0
    cordova platform version android            N/a
    cordova platform version iOS                  4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push  1.7.0

#### Sample Push Data Payload

{"aps":{"alert":"test","badge":"1"}}

#### Sample Code that illustrates the problem

Code as in example.

#### Logs taken while reproducing problem

No logs as no push received.

**Comment by macdonst** [comment]
@antonfire but how are you sending the push payload?

**Comment by antonfire** [comment]
Hi @macdonst I'm using parse push or an APN tester I use on the mac. Both send ok to 6/6+ but not to 4/5.

**Comment by macdonst** [comment]
@antonfire to an individual registration ID or multiple registration ID's?

**Comment by antonfire** [comment]
@macdonst I can send to multiple on parse, when I do this 6 (user with different apple login) and 6+ (my apple login) arrive but 4 and 5 (both my apple login) do not. I thought maybe there was an issue here and so have tested by sending on the APNs tester on the mac to each device registration ID individually. The results are the same. I can't work it out as all use the same app and all devices are running the same iOS.

**Comment by antonfire** [comment]
@macdonst Any ideas what could be causing this?

**Comment by macdonst** [comment]
@antonfire what does the test return from the server side?

**Comment by antonfire** [comment]
@macdonst Is it possible to send by cURL? On the tester on mac it connects, sends the data, then disconnects. No difference in the readout from the ones that work to the ones that don't. On parse server the push function doesn't give feedback, just returns true.

**Comment by antonfire** [comment]
@macdonst Just thinking how to get some better feedback from the APN api

**Comment by antonfire** [comment]
Forget it, my mistake. In the dev provisioning profile I'd not added the 4/5. Schoolboy error. Thanks for the help.
