### ISSUE TITLE
Cordova Support

### ISSUE THREAD

**Issue by cagb80** [phonegap/phonegap-plugin-push#99]
Where is the Cordova Support for the plugin? The last version was working with Cordova... I don't found how to setup the new plugin with my Cordova...

Can help me please! :)
Nice work indeed!

**Comment by macdonst** [comment]
@cagb80 What do you mean? If you are using the `cordova` command line then just use that command in place of the `phonegap` one.

**Comment by cagb80** [comment]
Thank you MacDonst.... You already add the command ;) Now is working fine...!!!
