### ISSUE TITLE
Notification event works in iOS but not in Android

### ISSUE THREAD

**Issue by Davids89** [phonegap/phonegap-plugin-push#990]
### Expected Behaviour
I need to to some stuff when a notification is received in the event notification. It must works in Android
### Actual Behaviour
Currently the event is shotted in iOS but not in Android

Is there any configuration required to do it?

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
