### ISSUE TITLE
Help wanted: Differantiate if notification click caused app resume or if notification was received in foreground

### ISSUE THREAD

**Issue by Caine72** [phonegap/phonegap-plugin-push#992]
Help wanted.

Is there a way to differentiate if a notification has been clicked and the application has resumed because of that ( not a coldstart mind you). And when it's received when the application is already running in foreground?

Is Actions/Categories the only solution for this?

### Expected Behaviour

When application is running and notification is received. 
 - Show a modal window with the option of read the news item,

When the application is in pause. 
 - Receive the notification but don't act on it.
 - When clicked on, auto navigate to url included in it. 

#### Platform and Version
iOS 9.x track.

#### Cordova CLI version and cordova platform version

    cordova --version - 5.4.1
    cordova platform version ios - 3.9.2 
Ios version because of [this ](https://issues.apache.org/jira/browse/CB-11097?jql=project%20%3D%20CB%20AND%20resolution%20%3D%20Unresolved%20AND%20priority%20%3D%20Major%20ORDER%20BY%20key%20DESC)issue)
#### Plugin version
phonegap-plugin-push  - 1.5.3

**Comment by macdonst** [comment]
@Caine72 yes, there is the `data.additionalData.foreground` property of the received push. It is `true` if the app is in the foreground and `false` if the app is in the background or killed.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#callback-parameters-2

Make sense?

**Comment by Caine72** [comment]
Not really. Because how do I write the code that makes this different from
a notification sent when I'm already in the foreground?

I.e if push is recived when app is open. I want to handle it one way. (open
a modal) If it's recived when a notification is clicked from the
notification list I want a different behavior(auto navigate).

In both cases the notification would have foreground true as far as I have
observed.
Or am I misinterpreting you?

**Comment by macdonst** [comment]
@Caine72 if you click on a notification in the notification center the value is `data.additionalData.foreground: false`, if the app is already running then the value is `data.additionalData.foreground: true`.

Your code would look like:

```
push.on('notification', function(data) {
  if (data.additionalData.foreground) { 
    // show modal
  } else {
    // do something else
  }
});
```

There is a longer write up in my [workshop](http://macdonst.github.io/push-workshop-eu/module7.html)

Try it out and let me know.

**Comment by Caine72** [comment]
Hi.

First of all, the workshop. Great stuff. Answered a lot of questions and
gave me some additional ideas for the future!!

I know realize my mistake. I was sending all notifications as background
notifications as a test. Hence when resuming the application the foreground
property was false.
Because of that i made the .. erroneous.. assumption the same would be true
if the notification was sent as as foreground.

So my solution is now to send dual notifications back/fore-ground. And make
the background contain a specific property that i can act upon, And the
foreground(s) does not contain it.

Hence now know; if it's a true background ,a resumed by  or running
notification. Which for now was my end goal.

Thanks for the great help!!
