### ISSUE TITLE
Why registrationId changes?

### ISSUE THREAD

**Issue by eskaigualker** [phonegap/phonegap-plugin-push#993]
I am testing an app with only one device. But in my table of tokens I have a dozen. Seems that the registrationId changes from time to time (don't know exactly when).
Shouldn't have only one registrationId for each device? Wouldn't be better to use a "deviceId" instead a  "registrationId"?

Thanks

**Comment by macdonst** [comment]
@eskaigualker Occasionally the remote push service GCM/APNS may invalidate your registration ID. That is why the registration ID changes from time to time. It's why you should always `init` the plugin and check the registration ID against the previous version.

No, it would not be better to use the `deviceId` as that uniquely identifies your device but not the individual app running on the device. If push services used `deviceId` then you'd be getting Angry Bird push notifications in your Gmail.
