### ISSUE TITLE
Callback to server on notification

### ISSUE THREAD

**Issue by nigareps** [phonegap/phonegap-plugin-push#994]
Hi all
As I understand, when app is closed, there is no way of calling any callbacks from main activity. Would it be possible to implement in java part of this plugin, a single callback to server to notify that push notification is received and shown? 
I am not a java developer, I think it shouldn't be very hard to do this, but it will be super useful, because there is random phones that for some reason doesn't receive notifications and exact status would be awesome.

**Comment by macdonst** [comment]
@nigareps just some constructive feedback for you but when you say things like _I am not a java developer, I think it shouldn't be very hard to do this_ many developers and maintainers of open source software will find that very insulting.

I'm curious as to how you would implement this feedback service on the phone? How would one provide the native callback code via the plugin interface? Are you aware that native code must be compiled with the application? Apps just can't run arbitrary code. Perhaps you want to implement a generic callback providing an API during init for the endpoint to be provided to native side.

Regardless, the functionality that you are requesting is better implemented on the server side. If the device never gets the push notification how does it tell the sever it never got it, if it never got it? If you read up on [Interpreting Downstream Messages](https://developers.google.com/cloud-messaging/http-server-ref#interpret-downstream) for GCM or implementing a connection to the [APNS Feedback Service](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Appendixes/BinaryProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH106-SW4).

**Comment by nigareps** [comment]
Why would anybody find that insulting? I did a little bit of java research and wrote callback in around 10 lines on java code. Hacked inside of showNotificationIfPossible method. For my app I just hardcoded callback url, but to make it universal, you can pass callback url together with other notification data for example. Or provide it in settings. There are many ways.

If the device never gets the push notification, server never receives ack, so I know that device didn't receive it.
