### ISSUE TITLE
Badge not updating when app is in background [Android]

### ISSUE THREAD

**Issue by parismav87** [phonegap/phonegap-plugin-push#995]
### Expected Behaviour
The app badge should update with the given number when notification arrives and app is in background. (same code works when app is in foreground)
### Actual Behaviour
The badge number is not updated

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0.2
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung
#### Cordova CLI version and cordova platform version

    cordova --version              6.0.0
    cordova platform version android                   Android 5.1.1

#### Plugin version

    phonegap-plugin-push 1.7.0

Code below: 

```
push.on('notification', function(data) {
		console.log(data);
		push.setApplicationIconBadgeNumber(function() {
					    console.log('success');
					}, function() {
					    console.log('error');
					}, 10);
		
	});
```

No console.logs appear either(apparently)

**Comment by macdonst** [comment]
@parismav87 it's because you are not setting the property to run the [notification handler in the background](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications).

**Comment by parismav87** [comment]
@macdonst Simon, I wasn't aware of that, thanks! I will try it out, but I'm pretty sure you can close this issue already. If that's not what's wrong, i'll come back to you. 
Thanks!
