### ISSUE TITLE
Notification event works in iOS but not in Android

### ISSUE THREAD

**Issue by Davids89** [phonegap/phonegap-plugin-push#996]
### Expected Behaviour
I need to to some stuff when a notification is received in the event notification. It must works in Android

### Actual Behaviour
Currently the event is shotted in iOS but not in Android

### Reproduce Scenario (including but not limited to)
My apps receive correctly the push notifications from GCM and you can see them in the mobile. I want to execute some tasks when the notification arrive to the phone but the on.('notification') event is not fired.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
LG Nexus 5X

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.1.1
    cordova platform version android           4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.6.4

#### Logs taken while reproducing problem

**Comment by Davids89** [comment]
Ok I discovered that the event is fired when I remove `forceShow: true` of the init configuration.

Is there anyway to show the notification without disabling this event?

**Comment by macdonst** [comment]
@Davids89 um, you can try setting [`content-available: "1"`](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications). Mind you, you might want to examine why you need the app in the foreground and get the notification event and get the UI in the notification center. Seems like you are over doing it.

**Comment by yugidazai** [comment]
Hi,

I got a similar issue with Android notification, but not exactly.
My purpose is to redirect to a specific screen (A) in app when receiving notification.
I remove `forceShow:true` and use `content-available:"1"`, and get this behavior:
- I open my app and go to its home screen and tap Home button of phone. My app is now in background and if I get a notification from it, I tap the notification, app is not opened.
- but if then I open the app, the screen A is already opened, meaning that the event of receiving notification is fired.
- In case my app is killed, ti works fine. I tap the notification, the app is opened and redirects to screen A as expected.
in IOS, everything works fine.

Is there any way to fix this or is there any reason that why the app is not opened in case it's in background?

Thanks in advance.

**Comment by macdonst** [comment]
Closing, inactivity
