### ISSUE TITLE
Notification icon compressed and alpha removed during build by aapt

### ISSUE THREAD

**Issue by pke** [phonegap/phonegap-plugin-push#997]
### Expected Behaviour

I have this MD valid notification icon (white! on transparent background)
![pushicon](https://cloud.githubusercontent.com/assets/164625/16169854/d27d1fae-353d-11e6-81ac-1eb80b9be6b1.png)

So by definition this is a valid icon. And I expect it to show up as the apps notification icon in the status bar when I set this plugins `icon` property in the android config object.
### Actual Behaviour

The icon is a white square.
#### Steps to Reproduce
1. Put icon in platforms/android/res/drawables/pushicon.png, its 5555 bytes.
2. Put `<meta-data android:name="com.parse.push.notification_icon" android:resource="@drawable/pushicon" />` in "AndroidManifest.xml" `platforms/android/application`
   and `<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="23" />`
3. run `cordova build android --device`
4. When the Android build finished in the
   android\build\intermediates\res\merged\armv7\debug\drawable\
   it ends up as being **recompressed** and **alpha channel removed**
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 5.1
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Wiko Lenny 2
#### Cordova CLI version and cordova platform version

```
Cordova CLI 6.2.0
Android 5.1.1
```
#### Plugin version

```
phonegap-plugin-push 1.6.2 "PushPlugin"
```

Setting those makes no difference:
`<uses-sdk android:minSdkVersion="15" android:targetSdkVersion="23" />`
`<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="23" />`

**Comment by macdonst** [comment]
@pke did you get this resolved?

**Comment by pke** [comment]
@macdonst we have our apps with push notifications running well now. I guess, after all, the input colour format of the icon was wrong.
