### ISSUE TITLE
Push notification entitlement required?

### ISSUE THREAD

**Issue by vsecades** [phonegap/phonegap-plugin-push#998]
### Expected Behaviour
I have 2 devices, one iPod Touch 5/iOS 9.3.1 and and one iPhone 4s/iOS 8.4  I register the devices with APNS successfully, and both devices are sent notifications.  The notification, with the app backgrounded or not running should show.

### Actual Behaviour
The notification is shown on the iPod, not on the iPad.  

### Reproduce Scenario (including but not limited to)
Install version 1.6.4 of the plugin, app boots and it registers with APNS successfully ( I use the APNS registration token to register it somewhere else, so I know that is working like a charm).  I then proceed to send a test notification with the Pusher app, with a very basic payload.  Payload arrives to the device, but notification is never shown on the iOS 8.4 iPhone 4s.

#### Steps to Reproduce 
Same as above?

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
one iPod Touch 5/iOS 9.3.1 and and one iPhone 4s/iOS 8.4  - Android works like a charm 👍 (not including that info as GCM works beautifully).

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
6.2.0
    cordova platform version android                     # e.g. 4.1.1
Installed platforms:
  android 5.1.1
  ios 4.1.1

#### Plugin version
    cordova plugin version | grep phonegap-plugin-push   

phonegap-plugin-push 1.6.4 "PushPlugin"

#### Sample Push Data Payload
{
    "aps": {
        "alert": {
            "title": "value",
            "body": "value"
        },
        "content-available": 1
    },
    "metadata3": "value",
    "metadata2": "value",
    "metadata1": {
        "key1": "value",
        "key2": "value",
        "key3": "value"
    }
}

**Comment by macdonst** [comment]
@vsecades sorry, are you saying the notification is show on the iPod Touch 5/iOS 9.3.1 but not the iPhone 4s/iOS 8.4?

**Comment by vsecades** [comment]
@macdonst exactly.   The notification does come in as it shown in the app logs,  but it shows the foreground key as true when the app is backgrounded.    I am just throwing ideas out there and found the entitlement one.   Any clue?

**Comment by vsecades** [comment]
@macdonst - so... the next step in our saga is that if I change the payload to a simple:

"alert":"value" 

instead of a more complex payload, it fixes our issues with receiving notifications on the different platforms.

What I am a bit out of sorts is that we followed:

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html

to make some very basic changes.  Following the GCM payload spec from Google works like a charm, so I am very much confused as to why your plugin is not working with older devices.

Anyway, any info is appreciated to bring this to conclusion.

**Comment by jcesarmobile** [comment]
It's strange, docs say that title was added on iOS 8.2 and you say that you are testing on 8.4

**Comment by vsecades** [comment]
@jcesarmobile I know.  Its just a bit frustrating I guess.  GCM love it, very flexible and it works.  iOS is a clunky old mess that works when it wants to.

In any case, if you guys don't have further ideas, I'm good for now.  Thanks for spending some time on this.

**Comment by macdonst** [comment]
@vsecades I do keep one of my phones at 8.4.1 for exactly this reason and I couldn't reproduce your issue.
