### ISSUE TITLE
Is there any way to clear count badge in some Android devices?

### ISSUE THREAD

**Issue by oscarabilleira** [phonegap/phonegap-plugin-push#999]
### Expected Behaviour
When push is recieved in some Android devices (Samsung, HTC...) is msgcount is included in playload a  count badge is added over the app icon, like in iois. Even if "clearBadge" option is included in the app (in android configuration line) when the app is opened the badge doesn't be cleared like in ios devices.
Is there any way to clear this badge when the user opens the app like in ios?

### Actual Behaviour
Badge is not cleared when the user opens the app.

### Reproduce Scenario (including but not limited to)
Send a push notification to android device (Samsung, Htc... ) that includes badge, 

#### Steps to Reproduce 
 Adding "msgcount:1" in play load. The badge apears over the icon but it is not cleared the opens the app.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6 (but not only) in some devices.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung, HTC...

#### Cordova CLI version and cordova platform version

    cordova --version                                6.1.0
    cordova platform version android                  5.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.7.1

#### Sample Push Data Payload
Any playload that includes "msgcount":"1"

**Comment by macdonst** [comment]
@oscarabilleira the `clearBadge` option is not implemented on Android but it is a good idea.

**Comment by oscarabilleira** [comment]
Thanks for the answer...   I hope that in a near future this is included.
